HW-3 MVVM + Databinding 적용하기
sjjeong/GoogryAndroidArchitecutreStudy pull request #108
Opened 2019-07-05 17:28 UTC by zion830

넘나 지각해버려서 면목없습니다...

이 블로그의 내용을 많이 참고했습니다. [(링크)](https://medium.com/@ali.muzaffar/android-recyclerview-using-mvvm-and-databinding-d9c659236908)

2019-07-06 03:00 UTC, sjjeong requested changes

2019-07-06 03:00 UTC, sjjeong commented on zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/adapter/CoinRecyclerViewAdapter.kt
> +        return layoutResId
ViewType에 layoutResId를 넘겨주면 안돼요

2019-07-06 03:00 UTC, sjjeong commented on zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/base/BaseViewHolder.kt
> +abstract class BaseViewHolder<T>(itemView: View) : RecyclerView.ViewHolder(itemView) {
view를 받지말고 ViewDataBinding을 Generic으로 선언하고 layoutResId를 받아서 처리해주세요.
https://github.com/sjjeong/dino-library/blob/master/src/main/kotlin/com/dino/library/ui/SimpleRecyclerView.kt

2019-07-06 03:00 UTC, sjjeong commented on zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/showcoin/CoinViewModel.kt
> +    val progressStatus: ObservableInt = ObservableInt(View.INVISIBLE)
View.INVISIBLE을 사용하지말고 처리해보세요.

2019-07-06 03:00 UTC, sjjeong commented on zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/showcoin/CoinViewModel.kt
> +    val adapter = CoinRecyclerViewAdapter(R.layout.item_coin_info)
adapter를 ViewModel에서 사용하지 말아주세요

2019-07-06 03:00 UTC, sjjeong commented on zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/adapter/CoinBindingAdapter.kt
> +object CoinBindingAdapter {
object를 사용하지 말고 global function으로 만들어주세요

2019-07-06 03:00 UTC, sjjeong commented on zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/adapter/CoinBindingAdapter.kt
> +    @BindingAdapter("text_color")
text_color보다 내부에서 어떤 동작을 하는지 알 수 있는 이름으로 변경해주세요.

2019-07-06 03:00 UTC, sjjeong commented on zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/showcoin/CoinViewModel.kt
> +) : ViewModel(),
제거해주세요

2019-07-06 03:00 UTC, sjjeong commented on zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/showcoin/CoinViewModel.kt
> +    CoinDataSource.LoadTickersCallback {
Interface를 제거하고 higher-order function으로 수정해주세요

2019-07-06 03:00 UTC, sjjeong commented on zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/showcoin/CoinViewModel.kt
> +        e(msg, reason ?: "No error message")
앞에 Log을 붙여서 어떤 클래스의 함수인지 명시해주세요

2019-07-06 03:00 UTC, sjjeong commented on zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/showcoin/CoinViewModel.kt
> +import android.databinding.ObservableField
사용하지 않는 임포트 제거

2019-07-09 11:03 UTC, zion830 commented on zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/adapter/CoinRecyclerViewAdapter.kt
> +        return layoutResId
수정했어요~

0d70e14

2019-07-09 12:15 UTC, zion830 commented on zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/showcoin/CoinViewModel.kt
> +    CoinDataSource.LoadTickersCallback {
수정했습니다~

51bbb1e

2019-07-09 12:16 UTC, zion830 commented on zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/showcoin/CoinViewModel.kt
> +        e(msg, reason ?: "No error message")
수정했습니다~
27fc7d0

2019-07-09 12:16 UTC, zion830 commented on zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/showcoin/CoinViewModel.kt
> +import android.databinding.ObservableField
삭제했어요~
acc16f8

2019-07-09 12:16 UTC, zion830 commented on zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/showcoin/CoinViewModel.kt
> +) : ViewModel(),
삭제했어요~
acc16f8

2019-07-12 08:55 UTC, zion830 commented on zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/adapter/CoinBindingAdapter.kt
> +    @BindingAdapter("text_color")
수정했습니다 a46fc5b

2019-07-12 11:12 UTC, zion830 commented on zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/showcoin/CoinViewModel.kt
> +    val progressStatus: ObservableInt = ObservableInt(View.INVISIBLE)
수정 했습니다 
c020f14

2019-07-12 11:12 UTC, zion830 commented on zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/showcoin/CoinViewModel.kt
> +    val adapter = CoinRecyclerViewAdapter(R.layout.item_coin_info)
수정했습니다 
2f966eb

2019-07-12 11:13 UTC, zion830 commented on zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/adapter/CoinBindingAdapter.kt
> +object CoinBindingAdapter {
수정했습니다
218becd

2019-07-12 12:47 UTC, zion830 commented on zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/base/BaseViewHolder.kt
> +abstract class BaseViewHolder<T>(itemView: View) : RecyclerView.ViewHolder(itemView) {
수정했습니다 
fd20cb8

2019-07-12 13:05 UTC, Nanamare commented on zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/adapter/CoinBindingAdapter.kt
> +    adapter.setCoinList(data)
굳이 adapter 를 줄인다면 줄일 수도 있을 것 같네용!
참고만 부탁드립니다 :)

2019-07-12 14:28 UTC, Nanamare approved these changes
고생하셨습니다 :)

2019-07-13 05:20 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-07-13 05:49 UTC, merged