HW-4 MVVM DataBinding
sjjeong/GoogryAndroidArchitecutreStudy pull request #110
Opened 2019-07-06 02:09 UTC by machine-human

2019-07-06 03:07 UTC, sjjeong requested changes
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/96
리뷰 확인하시면 됩니다.

2019-07-11 17:32 UTC, machine-human commented
SimpleRecyclerView적용 시 ViewHolder에서 데이터 셋 방법에 대해 질문 드렸는데,
답변 주시면 적용 후 라벨 변경 하도록 하겠습니다.

늦어서 죄송합니다....

2019-07-13 05:33 UTC, sjjeong approved these changes
마이그레이션 하면서 생긴 패키지 이름들은 다음 과제할때 같이 제거해주세요

2019-07-14 01:56 UTC, machine-human commented
> 마이그레이션 하면서 생긴 패키지 이름들은 다음 과제할때 같이 제거해주세요

네, 알겠습니다!!

2019-07-14 01:56 UTC, merged