HW-5 LiveData 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #120
Opened 2019-07-14 08:33 UTC by sport0102

2019-07-14 15:02 UTC, sjjeong commented
짝꿍 리뷰가 안끝났는데 제가 리뷰를 해서 리뷰내용은 제거 했습니다.

2019-07-15 07:34 UTC, machine-human commented on sport0102/app/build.gradle
> +
Koint 라이브러리는 8주차 과제로 알고있습니다만..? 스터디장님께 여쭤보시고 빼야하면 수정 부탁드립니다!!

2019-07-15 07:42 UTC, machine-human commented on sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/ui/main/MainViewModel.kt
>      private fun modifyTicker(ticker: TickerResponse): TickerResponse {
내부에서가 아닌 다른 패키지/클래스 등으로 빼서 관리하시면 더 깔끔할거 같습니다. :)

2019-07-15 08:16 UTC, machine-human commented on sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/ext/RecyclerViewExt.kt
> +    (this.adapter as? SimpleRecyclerView.Adapter<Any, *>)?.run {
BindingAdapter를 잘못 사용 중이신거 같습니다.
@BindingAdatper("value") 를 했을 경우 xml에서 앞서 어노테이션에서 입력한 "value"를 호출하여 binding을 해주는데
선민님께서는 fun RecyclerView.replaceAll(list: List<Any>?)의 replaceAll 메소드를 호출하여 사용중이십니다.

석준님의 아래 프로젝트를 참고하시면 됩니다 :)
https://github.com/sjjeong/NaverOpenApiSample/blob/master/app/src/main/res/layout/blog_fragment.xml

2019-07-15 08:16 UTC, machine-human commented
고생하셨습니다. 추가적으로 RecyclerView에서 입력하신 ID를 사용 안 하시는데 제거 부탁드립니다 :)

2019-07-15 08:19 UTC, brooks-o requested changes
requested changes로 변경

2019-07-16 08:31 UTC, sport0102 commented on sport0102/app/build.gradle
> +
제거 하였습니다 ㅎㅎ 멘토님도 지우라고 하셨어요!
d397124183be7eb2c304f80ed38daa04141d42b6

2019-07-16 08:39 UTC, sport0102 commented on sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/ui/main/MainViewModel.kt
>      private fun modifyTicker(ticker: TickerResponse): TickerResponse {
StringUtil 하위로 이동시켰습니다
7662737

2019-07-16 09:03 UTC, sport0102 commented on sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/ext/RecyclerViewExt.kt
> +    (this.adapter as? SimpleRecyclerView.Adapter<Any, *>)?.run {
수정하였습니다!
0c82c92

2019-07-16 09:03 UTC, sport0102 commented
> 고생하셨습니다. 추가적으로 RecyclerView에서 입력하신 ID를 사용 안 하시는데 제거 부탁드립니다 :)

이게 무슨 말인지 모르겠어요! 자세한 설명 부탁드리겠습니다 ㅠ

2019-07-16 12:54 UTC, sjjeong commented
> > 고생하셨습니다. 추가적으로 RecyclerView에서 입력하신 ID를 사용 안 하시는데 제거 부탁드립니다 :)
> 
> 이게 무슨 말인지 모르겠어요! 자세한 설명 부탁드리겠습니다 ㅠ

RecyclerView에 추가한 id가 불필요하다는 이야기 인 것 같습니다.

2019-07-16 16:15 UTC, machine-human commented
> > > 고생하셨습니다. 추가적으로 RecyclerView에서 입력하신 ID를 사용 안 하시는데 제거 부탁드립니다 :)
> > 
> > 
> > 이게 무슨 말인지 모르겠어요! 자세한 설명 부탁드리겠습니다 ㅠ
> 
> RecyclerView에 추가한 id가 불필요하다는 이야기 인 것 같습니다.

네, 맞습니다 ^^

수정하신 부분 확인 했습니다.

4760f08
"loalDataSource에서 함수 제대로 사용하게 변경"  
부분이 이해가 안 되는데 어떤 작업인지 설명 부탁드려도 될까요??

2019-07-17 04:40 UTC, sport0102 commented
> > > > 고생하셨습니다. 추가적으로 RecyclerView에서 입력하신 ID를 사용 안 하시는데 제거 부탁드립니다 :)
> > > 
> > > 
> > > 이게 무슨 말인지 모르겠어요! 자세한 설명 부탁드리겠습니다 ㅠ
> > 
> > 
> > RecyclerView에 추가한 id가 불필요하다는 이야기 인 것 같습니다.
> 
> 네, 맞습니다 ^^
> 
> 수정하신 부분 확인 했습니다.
> 
> [4760f08](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/commit/4760f0876b485a5480ef3b8bf212c500df69008d)
> "loalDataSource에서 함수 제대로 사용하게 변경"
> 부분이 이해가 안 되는데 어떤 작업인지 설명 부탁드려도 될까요??

아 로컬 db사용 관련한 부분이구요, 2가지 내용입니다. 테스트로 넣은 함수 대신에 실제로 사용할 함수로 바꾸고, remote db에서 가져온 데이터

2019-07-17 08:08 UTC, machine-human commented
recyclerview에 선언된 Id가 사용되지 않아서 제거 요청 드린겁니다 :)

https://github.com/sport0102/GoogryAndroidArchitectureStudy/blob/class02/sport0102/sport0102/app/src/main/res/layout/fragment_main.xml

2019-07-17 08:12 UTC, sport0102 commented
> recyclerview에 선언된 Id가 사용되지 않아서 제거 요청 드린겁니다 :)
> 
> https://github.com/sport0102/GoogryAndroidArchitectureStudy/blob/class02/sport0102/sport0102/app/src/main/res/layout/fragment_main.xml

아하 이제 이해했습니다 ㅎㅎ 제거 완료했습니다
cf08f1d

2019-07-17 08:13 UTC, brooks-o submitted a review, later dismissed
죄송해요 더 구체적이게 리뷰 드렸어야 하는데..
고생하셨습니다 :)

2019-07-18 11:29 UTC, sjjeong requested changes

2019-07-18 11:29 UTC, sjjeong commented on sport0102/app/build.gradle
> +apply plugin: 'kotlin-android-extensions'
kotlin-android-extensions를 추가하신 이유가 있을까요?

2019-07-18 11:29 UTC, sjjeong commented on sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/data/source/remote/UpbitRemoteDataSource.kt
> +                            db?.tickerDao()?.insert(tickerList)
db에 넣는 작업은 Remote가 아니라 Local에서 해야합니다.
repository에서 LocalDataSource를 사용해서 처리해주시면 됩니다.

2019-07-18 11:29 UTC, sjjeong commented on sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/ui/main/MainFragment.kt
> +    private val db by lazy {
Fragment에서는 db를 들고 있으면 안됩니다.

2019-07-18 11:29 UTC, sjjeong commented on sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/ui/main/MainFragment.kt
> +            context = context!!,
ViewModel에 context를 전달하지 말아주세요.
지금은 문제가 없을수도 있지만 AAC ViewModel을 사용할 때 문제가 발생합니다.

2019-07-19 06:38 UTC, sport0102 commented on sport0102/app/build.gradle
> +apply plugin: 'kotlin-android-extensions'
위에 recyclerview 사용하지 않는 id 삭제와 맞물리면서 이게 자동으로 import가 되었네요... kotlin-android-extensions를 지우니까 fragment에서 binding 액션 부분의 recyclerview 접근 부분에서 에러가 나네요... 신기하네요 id가 없는데 어떻게 알아서 찾았던건지.... 하여튼 저부분 삭제하고 recyclerview id 추가해서 databinding에서 접근 가능하게 수정하였습니다.
1df9145

2019-07-19 06:40 UTC, sport0102 commented on sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/data/source/remote/UpbitRemoteDataSource.kt
> +                            db?.tickerDao()?.insert(tickerList)
repository에서 local datasource를 활용해서 db에 데이터를 넣게끔 수정하였습니다!
1df9145

2019-07-19 06:41 UTC, sport0102 commented on sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/ui/main/MainFragment.kt
> +    private val db by lazy {
윗 코멘트의 수정내용과 같은 커밋안에 수정 내용이 반영되어있습니다.. 죄송합니다 ㅠ
b8891c1

2019-07-19 06:42 UTC, sport0102 commented on sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/ui/main/MainFragment.kt
> +            context = context!!,
uiThread로 접근하기 위해서 context를 가져왔던건데, LiveData의 postValue 메쏘드로 데이터를 넣으니, local db와 데이터 업데이트 시 쓰레드가 달라서 생기는 에러가 해결되었습니다! 
583b7d1

2019-07-19 09:46 UTC, sjjeong commented on sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/data/source/remote/UpbitRemoteDataSource.kt
> +                            db?.tickerDao()?.insert(tickerList)
커밋 번호가 잘못된거같습니다.
@sport0102

2019-07-19 09:47 UTC, sjjeong commented on sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/ui/main/MainFragment.kt
> +            context = context!!,
room에서 livedata를 받아서 처리하는 방식으로 해보세요.

2019-07-20 03:44 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-07-20 03:44 UTC, merged