HW-6 LiveData 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #121
Opened 2019-07-14 13:28 UTC by BeokBeok

Live Data 및 View Pager 적용 하였습니다.

2019-07-15 08:22 UTC, NackUn requested changes

2019-07-15 08:22 UTC, NackUn commented on BeokBeok/app/src/main/java/com/architecturestudy/base/BaseRecyclerView.kt
> +        ): BaseViewHolder<VDB> =
: BaseViewHolder<VDB> 이부분 생략가능하지 않을까요?

2019-07-15 08:22 UTC, NackUn commented on BeokBeok/app/src/main/java/com/architecturestudy/base/BaseRecyclerView.kt
> +        fun onBind(item: Any?) {
석준님 예제에서는 onBindViewHolder로 되어있는데 onBind와의 차이가 있을까요? item을 Bind하느냐, ViewHolder를 Bind하느냐 차이일까요?

2019-07-15 08:22 UTC, NackUn commented on BeokBeok/app/src/main/java/com/architecturestudy/upbitmarket/UpbitContentsFragment.kt
> +                Toast.makeText(
BaseFragment 에 있는 showToast를 사용하시는게 어떠신가요?

2019-07-15 12:12 UTC, BeokBeok commented on BeokBeok/app/src/main/java/com/architecturestudy/base/BaseRecyclerView.kt
> +        fun onBind(item: Any?) {
차이는 없습니다.
다만, 저에게는 onBind 함수명이 더 간결한 것 같아서 이렇게 명명하였습니다.

2019-07-15 12:12 UTC, BeokBeok commented on BeokBeok/app/src/main/java/com/architecturestudy/base/BaseRecyclerView.kt
> +        ): BaseViewHolder<VDB> =
onCreateViewHolder 를 오버라이딩하여 그대로 사용하였기 때문에
생략을 하지 않아도 될 것 같습니다.

2019-07-15 12:12 UTC, BeokBeok commented on BeokBeok/app/src/main/java/com/architecturestudy/upbitmarket/UpbitContentsFragment.kt
> +                Toast.makeText(
afb139118deb95a813ed0f6e42789b72b6d3f7ba
반영하였습니다.

2019-07-16 04:40 UTC, NackUn commented on BeokBeok/app/src/main/java/com/architecturestudy/upbitmarket/UpbitViewModel.kt
>          upBitRepository.getMarketPrice(
init 에서 MarketTypes.KRW.name를 인자로 showMarketPrice 를 호출하는 것은 어떠세요?

2019-07-16 04:40 UTC, NackUn commented on BeokBeok/app/src/main/java/com/architecturestudy/base/BaseRecyclerView.kt
> +        fun onBind(item: Any?) {
아 그렇군요! 감사합니다 ㅎㅎ

2019-07-16 04:41 UTC, NackUn commented on BeokBeok/app/src/main/java/com/architecturestudy/base/BaseRecyclerView.kt
> +        ): BaseViewHolder<VDB> =
넵 고생하셨습니다!

2019-07-16 06:16 UTC, BeokBeok commented on BeokBeok/app/src/main/java/com/architecturestudy/upbitmarket/UpbitViewModel.kt
>          upBitRepository.getMarketPrice(
18bf4cf
적용하였습니다.

2019-07-17 04:19 UTC, NackUn submitted a review, later dismissed
고생하셨습니당!

2019-07-18 11:38 UTC, sjjeong requested changes

2019-07-18 11:38 UTC, sjjeong commented on BeokBeok/app/build.gradle
> +    implementation 'com.android.support:design:29.0.0'
com.android.support는 androidx가 아니기 때문에 사용하시면 안돼요.
https://mvnrepository.com/artifact/com.google.android.material/material/1.0.0
이것으로 적용해주세요.

2019-07-18 11:38 UTC, sjjeong commented on BeokBeok/app/src/main/java/com/architecturestudy/upbitmarket/UpbitContentsFragment.kt
> +    private val position: Int
생성자로 받으면 나중에 재생성 루틴에서 값이 손실 됩니다.
Bundle에 저장해서 가져오는 식으로 변경해주세요.

2019-07-18 11:38 UTC, sjjeong commented on BeokBeok/app/src/main/java/com/architecturestudy/upbitmarket/UpbitOutlineFragment.kt
> +        super.onDestroy()
파괴 주기에서는 super를 나중에 호출하게 해주세요.

2019-07-18 13:04 UTC, BeokBeok commented on BeokBeok/app/build.gradle
> +    implementation 'com.android.support:design:29.0.0'
6e12db737bb06386099898c2c2a7247e62da4884
적용 하였습니다.

2019-07-18 13:04 UTC, BeokBeok commented on BeokBeok/app/src/main/java/com/architecturestudy/upbitmarket/UpbitContentsFragment.kt
> +    private val position: Int
a49cbe47b4f70e348726446c75053e41fe6d32dd
적용 하였습니다.

2019-07-18 13:04 UTC, BeokBeok commented on BeokBeok/app/src/main/java/com/architecturestudy/upbitmarket/UpbitOutlineFragment.kt
> +        super.onDestroy()
70aee34278a091410f733a4ca81a68e3346be362
적용 하였습니다.

2019-07-18 14:13 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-07-18 14:22 UTC, merged