HW-6 LiveData 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #122
Opened 2019-07-15 07:29 UTC by machine-human

LiveData적용과 함께 ViewHolder에서 하던 DataFormat을  ViewModel에서 하도록 변경 했습니다.

2019-07-16 09:35 UTC, sport0102 requested changes
안드로이드 스튜디오 상단 Analyze - Code Inspection 한번 돌려주셔서 수정 한 번 부탁드리겠습니다.

2019-07-16 09:35 UTC, sport0102 commented on machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/base/BaseViewModel.kt
> +abstract class BaseViewModel: ViewModel() {
AAC의 ViewModel은 다음주차 때 사용한다고 하셨습니다. ViewModel 상속 받지 않고 해주세요!

2019-07-16 09:35 UTC, sport0102 commented on machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/view/activity/main/MainFragment.kt
> +                lifecycleOwner = this@MainFragment
BaseFragment에서 lifecycleOwner를 넣어 주셔도 좋을 것 같습니다!

2019-07-16 09:35 UTC, sport0102 commented on machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/util/FormatUtil.kt
> +    fun convertTo(tickerList: TickerModel): ConvertTickerModel{
들어온 객체를 또다른 객체로 바꿔서 리턴하는 것에 대한 고민이 필요할 것 같습니다. 제가 처음에 이렇게 했는데, 이 방법을 사용하지 않고 기존 Model에 변경할 값의 변수를 추가해서 넣는 방향으로 했습니다. 정답은 잘 모르겠습니다. 그냥 이런 방법도 있다고 생각해주십시오 ㅎㅎ...

2019-07-16 09:35 UTC, sport0102 commented on machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/view/activity/main/MainViewModel.kt
> +            var convertTickerList = ArrayList<ConvertTickerModel>()
_observableTickerList.value = tickerList.map{FormatUtil.convertTo(it)}
한줄이면 끝낼 수 있을 것 같습니다!

2019-07-16 16:19 UTC, machine-human commented on machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/base/BaseViewModel.kt
> +abstract class BaseViewModel: ViewModel() {
감사합니다. 수정 완료 했습니다.

5e5ce0d

2019-07-16 16:20 UTC, machine-human commented on machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/view/activity/main/MainFragment.kt
> +                lifecycleOwner = this@MainFragment
감사합니다. 수정 완료했습니다.

bba5747

2019-07-16 16:22 UTC, machine-human commented on machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/util/FormatUtil.kt
> +    fun convertTo(tickerList: TickerModel): ConvertTickerModel{
아, 그런 이슈가 존재하군요.
해당 부분은 찾아보고 수정 하도록 하겠습니다. 감사합니다!

2019-07-16 16:22 UTC, machine-human commented on machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/view/activity/main/MainViewModel.kt
> +            var convertTickerList = ArrayList<ConvertTickerModel>()
수정 완료 했습니다. 감사합니다 :)

2019-07-16 16:22 UTC, machine-human commented on machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/view/activity/main/MainViewModel.kt
> +            var convertTickerList = ArrayList<ConvertTickerModel>()
0837cc0

2019-07-17 04:29 UTC, sport0102 approved these changes
LGMT!

2019-07-18 11:42 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-07-18 11:42 UTC, sjjeong commented on machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/util/FormatUtil.kt
> +    fun convertTo(tickerList: TickerModel): ConvertTickerModel{
객체를 새로 만들어서 리턴해도 됩니다.

2019-07-22 01:19 UTC, merged