HW-6 LiveData 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #123
Opened 2019-07-15 08:25 UTC by NackUn

2019-07-15 12:32 UTC, BeokBeok requested changes

2019-07-15 12:32 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/base/BaseFragment.kt
> +) : androidx.fragment.app.Fragment() {
androids.fragment.app 을 import 해주세요

2019-07-15 12:32 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/ui/ticker/TickerAdapter.kt
> +        private val tickerName = itemView.tickerName
xml로 바인딩해서 사용해주세요.

2019-07-15 12:32 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/ui/ticker/TickerFragment.kt
> +        vm.errMsg.observe(this@TickerFragment, errMsgObserver)
TickerFragment 를 명시적으로 선언하지 않아도 될 것 같습니다.

2019-07-15 12:32 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/ui/ticker/TickerViewModel.kt
> +    val tickers: LiveData<List<Map<String, String>>> get() = _tickers
getter 를 생성해준 경우에는, 타입을 명시하지 않아도 됩니다.

2019-07-15 12:32 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/ui/ticker/TickerViewModel.kt
> +        this._tickers.value = TickerFormatter.convertTo(tickers)
this 가 없어도 됩니다.

2019-07-16 04:50 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/ui/ticker/TickerViewModel.kt
> +        this._tickers.value = TickerFormatter.convertTo(tickers)
제거했습니다.
eac2026

2019-07-16 04:50 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/ui/ticker/TickerViewModel.kt
> +    val tickers: LiveData<List<Map<String, String>>> get() = _tickers
축약했습니다
9436b44

2019-07-16 04:51 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/ui/ticker/TickerFragment.kt
> +        vm.errMsg.observe(this@TickerFragment, errMsgObserver)
제거했습니다.
0c1b2ca

2019-07-16 04:51 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/base/BaseFragment.kt
> +) : androidx.fragment.app.Fragment() {
import했습니다.
dd9d566

2019-07-18 04:55 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/ui/ticker/TickerAdapter.kt
> +        private val tickerName = itemView.tickerName
변경했습니다 ㅎㅎ
f7fcd8d

2019-07-18 05:54 UTC, BeokBeok requested changes

2019-07-18 05:54 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/base/BaseRecyclerView.kt
> +        protected val items = mutableListOf<ITEM>()
private 로 변경해주세요

2019-07-18 05:54 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/base/BaseRecyclerView.kt
> +            items.let {
let은 무슨 용도로 사용하신 것인가요?

2019-07-18 05:54 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/base/BaseRecyclerView.kt
> +        val binding: B = DataBindingUtil.bind(itemView)!!
접근자 추가해주세요

2019-07-18 05:54 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/ui/ticker/TickerFragment.kt
> +        binding.lifecycleOwner = this
BaseFragment 로 이동해주세요

2019-07-18 05:54 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/ui/ticker/TickerFragment.kt
>      private fun setFirstTickers() {
중괄호를 사용하지 않아도 됩니다.

2019-07-18 05:54 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/ui/ticker/TickerFragment.kt
> +        vm.showTickers(vm.selectedMarket.value)
동작은 첫 번째 Ticker를 세팅하는 함수인데
구현부의 파라미터에는 첫 번째와는 상관 없이 선택된 마켓을 보여준다라는 의미로 보입니다.
보다 명확하게 표현 하는 것이 어떤가요?

2019-07-18 05:54 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/ui/ticker/TickerRecyclerViewExt.kt
> +fun RecyclerView.setItems(items: List<Map<String, String>>) {
UNCHECKED_CAST 어노테이션 추가해주세요

2019-07-18 07:26 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/base/BaseRecyclerView.kt
> +        protected val items = mutableListOf<ITEM>()
변경했습니다
2998855

2019-07-18 07:27 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/base/BaseRecyclerView.kt
> +            items.let {
석준님꺼 참고해서 it을 사용합니다. 변경했습니다
b486a0e

2019-07-18 07:27 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/base/BaseRecyclerView.kt
> +        val binding: B = DataBindingUtil.bind(itemView)!!
추가했습니다
b3d58ba

2019-07-18 07:27 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/ui/ticker/TickerFragment.kt
> +        binding.lifecycleOwner = this
이동했습니다
8b697d9

2019-07-18 07:27 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/ui/ticker/TickerFragment.kt
>      private fun setFirstTickers() {
제거했습니다
5c41b91

2019-07-18 07:27 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/ui/ticker/TickerFragment.kt
> +        vm.showTickers(vm.selectedMarket.value)
이렇게 변경해봤습니다
b1084de

2019-07-18 07:28 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/ui/ticker/TickerRecyclerViewExt.kt
> +fun RecyclerView.setItems(items: List<Map<String, String>>) {
추가했습니다
25ed011

2019-07-18 09:18 UTC, BeokBeok requested changes

2019-07-18 09:18 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/base/BaseRecyclerView.kt
> +        fun setItems(items: List<ITEM>) {
items 가 null 일 경우는 없을까요?

2019-07-18 09:18 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/ui/ticker/TickerViewModel.kt
> +    firstMarketName: String
가능한 한 파라미터 개수를 최소화하는 것이 좋습니다.
firstMarketName을 파라미터를 통하여 처리하지 않는 것이 좋을 것 같습니다.

2019-07-18 09:18 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/res/values/strings.xml
> +    <string name="firstMarketName">KRW</string>
marketKRW 와 String이 중복됩니다.
가능하다면, 기존에 있는 String을 사용 하는 것이 좋습니다.

2019-07-18 09:18 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/ui/ticker/TickerViewModel.kt
> +        _selectedMarket.value = firstMarketName
TickerFragment 에서 setFirstTickers 함수를 통하여 Ticker 데이터를 호출하고 있기 때문에
_selectedMarket 변수에 초기화하는 것은 의미가 없어 보입니다.

2019-07-18 10:14 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/ui/ticker/TickerViewModel.kt
> +        _selectedMarket.value = firstMarketName
_selectedMarket 에 초기화해준 이유는 마켓 색깔 변경을 위해서 입니다

2019-07-18 10:15 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/res/values/strings.xml
> +    <string name="firstMarketName">KRW</string>
그럼 firstMarketName 변경 시에 문제가 있지않을까요??
코드를 수정하지 않고 xml을 수정해서 firstMarketName 을 변경하려는 의도였습니다

2019-07-18 10:19 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/ui/ticker/TickerViewModel.kt
> +    firstMarketName: String
@BeokBeok 넵 저번에 관련해서 현석님과 현성님이 대화나누실 때 파라미터로 사용해도 괜찮다고 하셔서, ViewModel이 컨텍스트를 가지는 것을 피하려고 하시는 것 같은데... 좀 더 생각해보도록 하겠습니다.

2019-07-18 10:41 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/base/BaseRecyclerView.kt
> +        fun setItems(items: List<ITEM>) {
수정했습니다
930aa44

2019-07-18 11:11 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/ui/ticker/TickerViewModel.kt
> +    firstMarketName: String
context 를 전달하는 것은 괜찮다고 생각합니다.

2019-07-18 11:12 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/res/values/strings.xml
> +    <string name="firstMarketName">KRW</string>
firstMarketName 를 제거하고, marketKRW 를 사용하는 것을 의도한 것이였습니다.

2019-07-18 14:17 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/ui/ticker/TickerViewModel.kt
> +    firstMarketName: String
context를 전달하려면 파라미터를 하나 주어야되지 않나요?
그러면 위랑 똑같이 되는데 다른 방법이 있을까요??

2019-07-18 14:24 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/res/values/strings.xml
> +    <string name="firstMarketName">KRW</string>
@BeokBeok marketKRW랑 firstMarketName랑 구분해서 두고 싶습니다.
<string name="marketKRW">KRW</string>
<string name="firstMarketName">@string/marketKRW</string>
이런 식으로 사용하는 문법은 없을까요..?

2019-07-18 14:42 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/res/values/strings.xml
> +    <string name="firstMarketName">KRW</string>
개인적으로는 firstMarketName 은 최초 실행 시에만 필요하기 때문에
strings.xml 에서 관리하는 것이 아닌, 변수로 관리하는 것이 좋아 보입니다.
만약 xml에서 구분하고 싶으시다면, naming을 명확하게 하시어 하나로 관리하는 것이 좋아 보입니다.

2019-07-18 14:43 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/ui/ticker/TickerViewModel.kt
> +    firstMarketName: String
firstMarketName 대신에 context를 전달하시고
ViewModel 내부에서 context를 이용하여 getString 함수를 호출하면 될 것 같습니다.
하지만, 개인적 의견으로 첫 로딩 시에만 사용한다면 String 값을 지정하는 것이 좋은 것 같습니다.

2019-07-18 15:13 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/res/values/strings.xml
> +    <string name="firstMarketName">KRW</string>
이렇게 변수로서 사용을 해야하나요??
1a287f3

2019-07-18 15:13 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/ui/ticker/TickerViewModel.kt
> +    firstMarketName: String
삭제했습니다
1a287f3

2019-07-18 15:19 UTC, BeokBeok submitted a review, later dismissed
LGTM

2019-07-20 03:20 UTC, sjjeong requested changes

2019-07-20 03:20 UTC, sjjeong commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/ui/ticker/TickerViewModel.kt
> +    val tickers get() = _tickers
type을 LiveData로 해주세요

2019-07-20 03:56 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/ui/ticker/TickerViewModel.kt
> +    val tickers get() = _tickers
이렇게 바꾸면 될까요?
05d8cf1

2019-07-20 03:58 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/ui/ticker/TickerViewModel.kt
> +    val tickers get() = _tickers
수정했습니다
0f535a3

2019-07-20 04:00 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-07-20 04:44 UTC, merged