HW-1 코인헬퍼 클론 프로젝트
sjjeong/GoogryAndroidArchitecutreStudy pull request #124
Opened 2019-07-16 07:29 UTC by zojae031

기존에 마구잡이로 만들다가 너무 햇갈려서 MVP패턴 어거지로 넣어봤습니다. 
코드가 매우 난잡해요...ㅎ 죄송합니다

2019-07-18 11:58 UTC, wkdehdlr reviewed
코틀린 문법이나 안드로이드 아키텍쳐 부분은 저도 배워가는 입장이라 리뷰가 힘드네요 ㅜㅜ

2019-07-18 11:58 UTC, wkdehdlr commented on zojae031/Project/app/src/main/res/layout/activity_main.xml
> +            app:layout_constraintTop_toBottomOf="@+id/tabLayout" android:id="@+id/pager"/>
tablayout과 viewpager 속성 값들의 순서를 일치시키는게 좋아보입니다!(순서 & 정렬)
속성이 많아졌을때 유지보수 작업이 용이하다고 생각합니다

2019-07-18 11:58 UTC, wkdehdlr commented on zojae031/Project/app/src/main/java/study/architecture/model/DataParser.kt
> +                override fun onSuccess(t: List<Market>) {
t보다는 좀 더 의미있는 네이밍이 좋아보입니다.

2019-07-18 11:58 UTC, wkdehdlr commented on zojae031/Project/app/src/main/java/study/architecture/model/DataParser.kt
> +                    Log.e("Error",e.printStackTrace().toString())
toString()이 필요없지 않을까요?

2019-07-18 11:58 UTC, wkdehdlr commented on zojae031/Project/app/src/main/java/study/architecture/model/DataParser.kt
> +    private val lists = Array(4) { "" }
비어있는 리스트라면 emptyList()는 어떤가요?

2019-07-18 12:16 UTC, zojae031 commented on zojae031/Project/app/src/main/res/layout/activity_main.xml
> +            app:layout_constraintTop_toBottomOf="@+id/tabLayout" android:id="@+id/pager"/>
속성 값들의 순서를 일치시키라는 말씀이 무슨 말씀이신지 잘 이해가 되지않습니다 ㅠㅠ

2019-07-18 12:18 UTC, zojae031 commented on zojae031/Project/app/src/main/java/study/architecture/model/DataParser.kt
> +    private val lists = Array(4) { "" }
이런게 있는지 처음알았네요! 감사합니다.

2019-07-18 12:22 UTC, zojae031 commented on zojae031/Project/app/src/main/java/study/architecture/model/DataParser.kt
> +                override fun onSuccess(t: List<Market>) {
뒷부분에 수정되어있는 내용입니다!

2019-07-18 12:22 UTC, zojae031 commented on zojae031/Project/app/src/main/java/study/architecture/model/DataParser.kt
> +                    Log.e("Error",e.printStackTrace().toString())
뒷부분에 수정되어있는 내용입니다!

2019-07-18 13:34 UTC, wkdehdlr commented on zojae031/Project/app/src/main/res/layout/activity_main.xml
> +            app:layout_constraintTop_toBottomOf="@+id/tabLayout" android:id="@+id/pager"/>
뷰에 속성값을 추가할때 항상 같은 순서로 속성을 지정하면 좋겠다는 뜻이었습니다.
ex>
<첫번째 뷰
  1.width:~~
  2.height:~~
  3.margin:~~
  4.padding:~~/> 이면 두번째 뷰도 이 순서대로 속성지정

<두번째 뷰 -> good!
  1.width:~~
  2.height:~~
  3.margin:~~
  4.padding:~~/> 

<두번째 뷰  -> bad
  4.padding:~~
  2.height:~~
  1.width:~~
  3.margin:~~/>

2019-07-18 13:36 UTC, zojae031 commented on zojae031/Project/app/src/main/res/layout/activity_main.xml
> +            app:layout_constraintTop_toBottomOf="@+id/tabLayout" android:id="@+id/pager"/>
자세한 설명 감사합니다 수정하겠습니다.

2019-07-18 14:14 UTC, sjjeong commented
@zojae031 
본인이 직접 `Mentor Needed`를 남기면 안됩니다.
짝꿍인 리뷰어가 `Mentor Needed`를 추가해야합니다.

2019-07-18 17:49 UTC, zojae031 commented
앗 그렇군요! 죄송합니다

2019-07-20 05:55 UTC, sjjeong requested changes
Editor -> Code Style -> XML에서 Set from...을 선택하시고 Predefined -> Android 선택해주세요.
저번에 알려드린 reformat code 기능 사용해서 xml 코드 정리해주세요.

2019-07-20 05:55 UTC, sjjeong commented on zojae031/Project/app/src/main/java/study/architecture/adapter/CoinDataAdapter.kt
> +    var lists: List<Ticker> = listOf()
Adapter안에 list는 private val로 관리하는게 좋습니다.
private val로 변경해주시고 함수를 통해서 데이터를 넣게 해주세요.

2019-07-20 05:55 UTC, sjjeong commented on zojae031/Project/app/src/main/java/study/architecture/adapter/CoinDataAdapter.kt
> +        val view = LayoutInflater.from(parent.context).inflate(R.layout.list_item, null)
inflate할 때 root 파라미터에 null을 주지 마시고 onCreateViewHolder로 넘어오는 parent를 넣어주세요.
그러면 아래 minimunWidth를 넣어주지 않아도 됩니다.
list_item.xml에도 LinearLayout의 width를 0dp로 변경해주시면 됩니다.

2019-07-20 05:55 UTC, sjjeong commented on zojae031/Project/app/src/main/java/study/architecture/adapter/MainPageAdapter.kt
> +    private val fragments: List<MainFragment> = listOf(
```kotlin
private val fragments = MainFragment.FragIndex.values().map { MainFragment(it) }
```
으로 변경하면 더 좋습니다.

2019-07-20 05:55 UTC, sjjeong commented on zojae031/Project/app/src/main/java/study/architecture/mainjob/MainFragment.kt
> +        presenter.onPause()
onPause에서는 super.onPause()를 뒤에서 부르는게 좋습니다.

2019-07-20 05:55 UTC, sjjeong commented on zojae031/Project/app/src/main/java/study/architecture/mainjob/MainFragment.kt
> +            recyclerView.layoutManager = LinearLayoutManager(this.context, LinearLayoutManager.VERTICAL, false)
xml에서 지정해주면 해당 코드는 필요하지 않습니다.
app:layoutManager="androidx.recyclerview.widget.LinearLayoutManager"

2019-07-20 05:55 UTC, sjjeong commented on zojae031/Project/app/src/main/java/study/architecture/mainjob/MainFragment.kt
> +class MainFragment(idx: FragIndex) : Fragment(), MainContract.View {
생성자로 받은데이터를 바로 사용하지 말아주세요.

bundle을 사용해서 처리해주세요

2019-07-20 05:55 UTC, sjjeong commented on zojae031/Project/app/src/main/java/study/architecture/mainjob/MainPresenter.kt
> +        parser.paresMarketList()
23번째 줄처럼 compositeDisposable.add()는 필요없는 건가요?

2019-07-20 05:55 UTC, sjjeong commented on zojae031/Project/app/src/main/java/study/architecture/model/DataParser.kt
> +    private var stateString: String = when (index) {
private val stateString = index.name
으로 사용하면 됩니다.

2019-07-20 05:55 UTC, sjjeong commented on zojae031/Project/app/src/main/java/study/architecture/model/DataParser.kt
> +                        if (item.market.substringBefore("-") == stateString) list += "${item.market},"
```kotlin
.map {
    it.filter { it.market.startsWith(stateString) }
        .joinToString(",") { it.market }
}
.subscribe(
    { marketList ->
        list = marketList
        resultCallback.successMarketList()
    },
    { e -> Log.e("onErrorMarketList", e.message) }
)
```
이렇게 쓰면 더 좋습니다.

2019-07-20 05:55 UTC, sjjeong commented on zojae031/Project/app/src/main/java/study/architecture/model/UpbitApi.kt
> +    fun getTickers(@Query("markets") markets: String): Observable<List<Ticker>>
Single로 해도 됩니다.

2019-07-20 05:55 UTC, sjjeong commented on zojae031/Project/app/src/main/java/study/architecture/vo/Market.kt
> +    @SerializedName("korean_name") val korean_name: String,
카멜케이스 표기법으로 수정해주세요
Ticker도 동일합니다.

2019-07-20 09:53 UTC, zojae031 commented on zojae031/Project/app/src/main/java/study/architecture/adapter/CoinDataAdapter.kt
> +    var lists: List<Ticker> = listOf()
왜 val로 관리하는게 좋은가요??

2019-07-20 09:57 UTC, zojae031 commented on zojae031/Project/app/src/main/java/study/architecture/adapter/CoinDataAdapter.kt
> +    var lists: List<Ticker> = listOf()
그리고 val 형식인데 어떻게 데이터를 넣는거죠 ㅠㅠ??

2019-07-20 10:06 UTC, zojae031 commented on zojae031/Project/app/src/main/java/study/architecture/adapter/CoinDataAdapter.kt
> +        val view = LayoutInflater.from(parent.context).inflate(R.layout.list_item, null)
root view를 연결해주기위해서
```kotlin
    override fun onCreateViewHolder(parent: ViewGroup, viewType: Int): Holder {
        val view = LayoutInflater.from(parent.context).inflate(R.layout.list_item, parent,true)
        return Holder(view)
    }
````
형식으로 지정했는데 아래와 같은 오류가 발생합니다. 
프래그먼트 생성 시간이 문제인가 싶어 MainFragment에서 

 java.lang.IllegalStateException: ViewHolder views must not be attached when created. Ensure that you are not passing 'true' to the attachToRoot parameter of LayoutInflater.inflate(..., boolean attachToRoot)

```kotlin
private val adapter: CoinDataAdapter by lazy { CoinDataAdapter() }
```
형식으로 lazy생성을 하여도 같은 문제가 발생하네요 ㅠ_ㅠ....

2019-07-20 10:08 UTC, zojae031 commented on zojae031/Project/app/src/main/java/study/architecture/mainjob/MainFragment.kt
> +            recyclerView.layoutManager = LinearLayoutManager(this.context, LinearLayoutManager.VERTICAL, false)
감사합니다

2019-07-20 10:09 UTC, zojae031 commented on zojae031/Project/app/src/main/java/study/architecture/mainjob/MainPresenter.kt
> +        parser.paresMarketList()
onCreate될때 MarketList는 Single로 가져오고
이후에 가지고있는 MarketList를 활용하여
Observable을 이용해 TickerList를 interval을 이용하여 가져오는 형태라 disposable을 가져오지 않습니다!

2019-07-20 10:15 UTC, zojae031 commented on zojae031/Project/app/src/main/java/study/architecture/model/DataParser.kt
> +                        if (item.market.substringBefore("-") == stateString) list += "${item.market},"
우와...이건 아직 제가 연산자에 대한 이해가 부족한것같네요!
좋은방법 감사합니다

2019-07-20 10:18 UTC, zojae031 commented on zojae031/Project/app/src/main/java/study/architecture/model/UpbitApi.kt
> +    fun getTickers(@Query("markets") markets: String): Observable<List<Ticker>>
interval을 주기위하여 Observable을 이용하였는데
Single을 이용해도 할 수 있나요??
찾아보다가 실패하여 위 방법을 사용하였습니다.

2019-07-20 10:21 UTC, zojae031 commented on zojae031/Project/app/src/main/java/study/architecture/adapter/MainPageAdapter.kt
> +    private val fragments: List<MainFragment> = listOf(
map연산자 정말 좋네요!!감사합니다

2019-07-20 15:50 UTC, sjjeong commented on zojae031/Project/app/src/main/java/study/architecture/adapter/CoinDataAdapter.kt
> +    var lists: List<Ticker> = listOf()
Adapter에서 list는 외부와 공유되면 안됩니다.
그래서 내부에서 별도의 list를 가지고 데이터만 넣게 해줘야합니다.

데이터를 넣지 못하는건 val과 관련이 없습니다.
List로 선언해서 넣지 못하는 겁니다.

2019-07-20 15:51 UTC, sjjeong commented on zojae031/Project/app/src/main/java/study/architecture/adapter/CoinDataAdapter.kt
> +        val view = LayoutInflater.from(parent.context).inflate(R.layout.list_item, null)
true대신 false를 주면 됩니다.

2019-07-20 15:52 UTC, sjjeong commented
저번에 말씀드린것처럼 커밋은 리뷰당 한개씩 남겨주셔야 합니다.
그리고 각 리뷰마다 리뷰반영 커밋 남겨주세요.

2019-07-21 05:02 UTC, zojae031 commented on zojae031/Project/app/src/main/java/study/architecture/adapter/CoinDataAdapter.kt
> +    var lists: List<Ticker> = listOf()
[commit](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/124/commits/8d06b3c45ee259685ac2d15b9f3de649243adb06)
수정본 커밋입니다.

2019-07-21 05:04 UTC, zojae031 commented on zojae031/Project/app/src/main/java/study/architecture/adapter/CoinDataAdapter.kt
> +        val view = LayoutInflater.from(parent.context).inflate(R.layout.list_item, null)
[HW-01 inflate시 부모연결작업](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/124/commits/d75961bb0ae14291eca7b488c2caf7cfb909f947)
수정본입니다

2019-07-21 05:05 UTC, zojae031 commented on zojae031/Project/app/src/main/java/study/architecture/mainjob/MainFragment.kt
> +class MainFragment(idx: FragIndex) : Fragment(), MainContract.View {
[
HW-01 inflate시 부모연결작업](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/124/commits/accc06374c2a9141511f35da224f3687e77b1c19)
수정본 커밋입니다.

2019-07-21 08:49 UTC, sjjeong commented on zojae031/Project/app/src/main/java/study/architecture/mainjob/MainPresenter.kt
> +        parser.paresMarketList()
Single이어도 중간에 네트워크 연결을 취소해야하는 경우가 있기 때문에 해야 합니다.
다음 pr에서 수정을 해주세요.

2019-07-21 08:50 UTC, sjjeong commented on zojae031/Project/app/src/main/java/study/architecture/model/UpbitApi.kt
> +    fun getTickers(@Query("markets") markets: String): Observable<List<Ticker>>
interval은 Observable이지만 데이터를 요청하는 부분은 Single로 처리해도 됩니다.
해당 부분도 다음 pr에서 같이 처리해주세요.

2019-07-21 08:50 UTC, sjjeong approved these changes
Rx관련 부분은 해당 pr에서 처리하지않고 다음 과제에서 해주세요.

2019-07-21 08:51 UTC, sjjeong commented
@wkdehdlr 리뷰 보시고 approve해주세요.

2019-07-21 11:24 UTC, zojae031 commented on zojae031/Project/app/src/main/java/study/architecture/model/UpbitApi.kt
> +    fun getTickers(@Query("markets") markets: String): Observable<List<Ticker>>
해당하는부분을 Single로 바꾸었더니
```kotlin 
Observable.interval(0,3000,TimeUnit.SECONDS)
            .subscribeOn(Schedulers.io())
            .flatMap { api.getTickers(listName) }
```
처리가 안됩니다. 혹시 뭐가 문제인지 알 수 있을까요?
현재 해당부분으로 인해 Repository 적용중에도 문제가 있습니다 ㅠㅠ
@sjjeong

2019-07-21 11:44 UTC, sjjeong commented on zojae031/Project/app/src/main/java/study/architecture/model/UpbitApi.kt
> +    fun getTickers(@Query("markets") markets: String): Observable<List<Ticker>>
flatmapSingle이라는 함수를 사용해보세요

2019-07-22 01:01 UTC, wkdehdlr approved these changes
HW2에서 아키텍처에 관한 부분을 중점적으로 보겠습니다

2019-07-22 03:01 UTC, merged