HW-4 LiveData 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #127
Opened 2019-07-17 14:40 UTC by Nanamare

바뀐게 크게 없네요 하하

2019-07-18 11:56 UTC, zion830 requested changes
이미 잘 짜두셔서 리뷰할 게 별로 없네용
이건 저도 그랬던건데, anko가 지금 안쓰이고 있어서 삭제하셔도 될거같아요 ㅋㅋ

2019-07-18 11:56 UTC, zion830 commented on Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/base/BaseViewModel.kt
> +    var isLoadingObservable = MutableLiveData<Boolean>().apply {
val로 변경이 가능합니다.
그리고 Boolean은 디폴트가 false라 초기화를 하지 않아도 될거같네요ㅎㅎ

2019-07-18 11:56 UTC, zion830 commented on Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/vm/CoinViewModel.kt
> +    private var _coins = MutableLiveData<List<CoinModel>>(mutableListOf())
MutableLiveData는 val로 선언가능합니다

2019-07-18 11:56 UTC, zion830 commented on Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/vm/MarketViewModel.kt
> +            _market.value = LinkedHashMap()
새로운 객체를 생성하는 대신 위쪽에서 선언한 marketMap 변수를 사용하면 될 것 같아요

2019-07-20 03:48 UTC, Nanamare commented on Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/base/BaseViewModel.kt
> +    var isLoadingObservable = MutableLiveData<Boolean>().apply {
877a46707b63920579f8a837021c7141a7d5fd08
변경하였습니다!

2019-07-20 03:48 UTC, Nanamare commented on Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/vm/CoinViewModel.kt
> +    private var _coins = MutableLiveData<List<CoinModel>>(mutableListOf())
9085ba27025ec6c7322d614a531d7adb7ca53048
변경하였습니다!

2019-07-20 03:48 UTC, Nanamare commented on Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/vm/MarketViewModel.kt
> +            _market.value = LinkedHashMap()
70102d4f56c3a698e97050a3c0e57072ea78ab0b
변경하였습니다!

2019-07-20 03:50 UTC, zion830 approved these changes
승인 했습니다

2019-07-20 08:28 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-07-20 11:38 UTC, merged