HW-01 코인헬퍼 카피앱 만들기
sjjeong/GoogryAndroidArchitecutreStudy pull request #129
Opened 2019-07-18 01:31 UTC by wkdehdlr

2019-07-18 06:56 UTC, zozero94 reviewed
부족하지만 리뷰 작성해 보았습니다.

2019-07-18 06:56 UTC, zojae031 commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/MainRvAdapter.kt
> +        fun bind(upbitItem: UpbitItem, context: Context) {
context가 사용되고있지 않은것 같습니다.

2019-07-18 06:56 UTC, zojae031 commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/MyPagerAdapter.kt
> +                if (response.body() != null) {
null체크 대신 .?을 사용하셔도 될 것 같습니다

2019-07-18 06:56 UTC, zojae031 commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/MyPagerAdapter.kt
> +                if (response.body() != null) {
위와 동일하게 null 체크 대신 .? 사용이 좋아보입니다

2019-07-18 06:56 UTC, zojae031 commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/MyPagerAdapter.kt
> +                        if (category == "KRW") {
when으로 바꾸면 더 보기 좋을것 같습니다!

2019-07-18 06:56 UTC, zojae031 commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/ApiConnector.kt
> +                        if (category == "KRW") {
when절로 분리하고 
UpbitItem에 데이터 넣는 동작이 중복되므로 모듈화 시켜도 될 것 같습니다.
```kotlin
val data = UpbitItem(
intFormat.format(item.tradePrice),
item.change,
doubleFormat.format(item.signedChangeRate),
doubleFormat.format(item.accTradePrice24h)
)
when(category){
"KRW" -> krwList.add(data)
"BTC" -> btcList.add(data)
//이하 생략
}
```

2019-07-18 06:56 UTC, zojae031 commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/ApiConnector.kt
> +    fun getKRWList() = this.krwList
코틀린에서는 외부에서 접근하기위해 get메소드를 만들지 않고
public으로 설정하는것으로 알고있습니다.
@sjjeong 확인 부탁드립니다.

2019-07-18 06:56 UTC, zojae031 commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/MainActivity.kt
> +        val apiConnector = ApiConnector()
```kotlin
ApiConnector().let{
setUpbitMarket()
viewpager_main.adpater = MyPagerAdapter(supprotFragmentManager,this)
}
```
형태는 어떨까요..? 이건 지극히 개인적인 스타일입니다 ㅎㅎ...

2019-07-18 07:01 UTC, sjjeong commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/ApiConnector.kt
> +    fun getKRWList() = this.krwList
외부에서는 get만하고 set은 하고싶지 않은경우
custom accessor를 사용해서 private set해주시면 됩니다.
https://kotlinlang.org/docs/reference/properties.html#getters-and-setters

2019-07-18 07:13 UTC, zojae031 commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/ApiConnector.kt
> +    private var ethList: MutableList<UpbitItem> = ArrayList()
```kotlin
var ethList:MutableList<UpbitItem> = ArrayList()
private set
```

이런식으로 설정하면 되는것인가요? @sjjeong

2019-07-18 07:14 UTC, sjjeong commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/ApiConnector.kt
> +    private var ethList: MutableList<UpbitItem> = ArrayList()
네 맞습니다.

2019-07-18 07:14 UTC, zojae031 commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/ApiConnector.kt
> +    private var ethList: MutableList<UpbitItem> = ArrayList()
또한 krwList에서 Mutable한 List만 변경되지 참조 자체는 변경되지 않으므로
val을 사용하셔도 될 것 같습니다.

2019-07-18 13:13 UTC, wkdehdlr commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/MainRvAdapter.kt
> +        fun bind(upbitItem: UpbitItem, context: Context) {
수정했습니다 ㅎㅎ

2019-07-18 13:13 UTC, wkdehdlr commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/MyPagerAdapter.kt
> +                if (response.body() != null) {
?.let으로 수정했습니다 ㅎㅎ

2019-07-18 13:43 UTC, zozero94 reviewed
리뷰 추가합니당

2019-07-18 13:43 UTC, zojae031 commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/ApiConnector.kt
> +    var krwList: MutableList<UpbitItem> = ArrayList()
Mutable한 List만 변경되지 참조 자체는 변경되지 않으므로
val을 사용하셔도 될 것 같습니다.

2019-07-20 06:16 UTC, sjjeong requested changes
과제가 제대로 동작하지 않습니다.
@wkdehdlr 과제 다시 완성해서 올려주세요.
@zojae031 과제 다시 리뷰 해주세요.

2019-07-20 06:16 UTC, sjjeong commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/ApiConnector.kt
> +                            else -> krwList.add(data)
전부다 krwList로 넣어주고 있네요
그래서 다른화면에서는 데이터가 보이지 않습니다.

2019-07-21 14:19 UTC, sjjeong approved these changes
추가적인 리뷰는 HW2에서 더 하겠습니다

2019-07-22 03:02 UTC, zozero94 approved these changes

2019-07-22 03:03 UTC, merged