HW-1 코인헬퍼 클론 프로젝트
sjjeong/GoogryAndroidArchitecutreStudy pull request #130
Opened 2019-07-18 14:24 UTC by preludezdev

전체 로직 :
처음 SplashActivity 에서 전체 마켓 목록을 가져온 뒤
MainActivity 에서 각 마켓별 Fragment 의 RecyclerView Adapter 부분에
Ticker 데이터를 가져와 화면에 뿌려주고 있습니다. 
코틀린 프로젝트가 처음이라 어색한 부분이 많을텐데 편하게 피드백해주시면
감사히 받겠습니다.

2019-07-18 18:57 UTC, dlwls5201 reviewed
처음 리뷰를 남기는 거라 부족한 점이 많을 것 같습니다.
코틀린 문법에 관해서도 조금 리뷰 남겼습니다.

2019-07-18 18:57 UTC, dlwls5201 commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/BTCFragment.kt
> +                    for (num in 0..list!!.size - 1) {
코틀린에서는 until 키워드가 있습니다. (0..list.size-1) 은 (0 until size) 랑 동일합니다.
또한 !! 키워드는 해당 변수가 null 이 아니라고 확신할 때만 사용하는 것을 추천드립니다.

2019-07-18 18:57 UTC, dlwls5201 commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/RecyclerViewAdapter.kt
> +                    tvCoinTotalTrade.text = String.format("%6.0f", (currItem.acc_trade_price_24h / 1000000)) + "M"
trade_price , acc_trade_price_24h 값을 다르게 보여주는 것은 마켓별이 아닌 데이터 값에 의해서 보여줄 수 있도록 캡슐화 하는 것이 코드의 재활용 및 유지보수에 더욱 좋을 것 같습니다.
ex) 1000000 이상이면 M, 1000000 미만 1000이상이면 K, 1 미만 0보다 크면 그대로 등등..

2019-07-18 18:57 UTC, dlwls5201 commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/SplashActivity.kt
> +        loadCoinMarketList() //메인액티비티로 이동
1.3초 딜레이를 주고 메인 엑티비티로 이동하고 있습니다. 만일 1.3초안에 마켓 정보를 성공적으로 받아오지 못하면 데이터 없이 메인 화면으로 넘어가게 됩니다. 전체 코인시장 목록에서 받아오는 Response 결과에 따라 메인 화면으로 이동하는 것이 좋을 것 같습니다.

2019-07-18 18:57 UTC, dlwls5201 commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/RecyclerViewAdapter.kt
> +        //뷰홀더 내의 itemView를 거쳐야 한다.
성능 이슈로 onBindViewHolder에서 코틀린 인스텐션을 사용하는 것은 권하는 방법이 아닙니다.
자세한 내용은 링크를 첨부하겠습니다.
https://www.androidhuman.com/lecture/kotlin/2017/11/26/kotlin_android_extensions_on_viewholder/

2019-07-18 18:57 UTC, dlwls5201 commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/MainActivity.kt
> +        var USDT_MARKETS: HashSet<String> = HashSet()
java의 static final을 사용하실러는 거면 companion object 안에 var 을 const val 키워드를 사용해 선언하는 것이 더 정확합니다.

2019-07-19 11:28 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/BTCFragment.kt
> +                    for (num in 0..list!!.size - 1) {
- until 키워드 확인했습니다.
- 들어오는 인자가 null 인지 확신할 수 없어서 먼저 null인지 체크하는 부분을 추가했습니다.

2019-07-19 11:29 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/RecyclerViewAdapter.kt
> +                    tvCoinTotalTrade.text = String.format("%6.0f", (currItem.acc_trade_price_24h / 1000000)) + "M"
말씀해주신대로 마켓별이 아닌 데이터 값에 의해 다르게 출력할 수 있도록 구현했습니다.

2019-07-19 11:30 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/SplashActivity.kt
> +        loadCoinMarketList() //메인액티비티로 이동
Response결과를 성공적으로 받는지 체크하는 변수를 추가해 해당 변수가 true 면 메인액티비티로 넘어가게 구현했습니다.

2019-07-19 11:31 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/RecyclerViewAdapter.kt
> +        //뷰홀더 내의 itemView를 거쳐야 한다.
걸어주신 링크 내용보고 뷰홀더 내에 각 텍스트뷰 별로 프로퍼티를 생성해 onBindViewHolder에서 뷰에 접근할 때 뷰홀더 프로퍼티로 접근하게끔 수정했습니다.

2019-07-19 11:39 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/MainActivity.kt
> +        var USDT_MARKETS: HashSet<String> = HashSet()
말씀해주신대로 코드를 변경하려고 했는데 
Const 'val' has type 'kotlin.collections.HashSet<String> /* = java.util.HashSet<String> */'. Only primitives and String are allowed.
에러가 나면서 변경이 안되서 var을 val로만 바꾸고 커밋했습니다. const val 은 primitive랑 String 타입만 되는 것 같은데 혹시 코드를 이대로 놔두면 생기는 문제점같은게 있는지 궁금합니다.

2019-07-19 13:49 UTC, dlwls5201 commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/SplashActivity.kt
> +        loadCoinMarketList() //메인액티비티로 이동
MainActivity.KRW_MARKETS 의 데이터 유무를 통해 통신 결과를 확인하는 방법도 좋아보입니다. 개인적으로는 responese.isSuccessful() 을 통해 return code가 [200..300) 인지 확인하는 것도 좋을 것 같아 링크 남기겠습니다.
https://square.github.io/retrofit/2.x/retrofit/retrofit2/Response.html

2019-07-19 14:00 UTC, dlwls5201 commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/MainActivity.kt
> +        var USDT_MARKETS: HashSet<String> = HashSet()
const에 대해 제가 미흡하게 알고 있었던것 같습니다:) 이대로 두었을 때 문제는 없는 것 같아 보이고 var -> val로 변해도 충분할 것 같습니다.

2019-07-19 20:31 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/SplashActivity.kt
> +        loadCoinMarketList() //메인액티비티로 이동
레트로핏 통신 후 response.isSuccessful 값이 true 인 경우에만 데이터를 받아오게 구현했습니다.

commit :  1b9404c

2019-07-20 07:04 UTC, sjjeong requested changes

2019-07-20 07:04 UTC, sjjeong commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/data/CoinMarketResponse.kt
> +                              val english_name: String = "")
카멜케이스 표기법으로 수정해주세요
CoinTickerResponse도 동일합니다.

2019-07-20 07:04 UTC, sjjeong commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/network/NetworkHelper.kt
> +    val API_URL = "https://api.upbit.com/"
const val 로 수정해주세요

2019-07-20 07:04 UTC, sjjeong commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/BtcFragment.kt
> +class BtcFragment : Fragment() {
4개의 Fragment가 데이터를 불러오는 것 빼곤 다 동일합니다.
Fragment를 한개만 만들고 Fragment를 생성 할 때 어떤 데이터를 가져오게 할 건지 값을 넘겨주세요

2019-07-20 07:04 UTC, sjjeong commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/SplashActivity.kt
> +                    startActivity(Intent(this@SplashActivity, MainActivity::class.java))
if에 {} 넣어주세요

2019-07-20 07:04 UTC, sjjeong commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/SplashActivity.kt
> +                        var list: List<CoinMarketResponse>? = response.body()
val로 해주세요

2019-07-20 07:04 UTC, sjjeong commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/SplashActivity.kt
> +                                var currMarketName = list[num].market
val로 해주세요

2019-07-20 07:04 UTC, sjjeong commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/SplashActivity.kt
> +                                var arrMarketName = currMarketName.split("-")
val로 해주세요

2019-07-20 07:04 UTC, sjjeong commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/SplashActivity.kt
> +            }, delayTime
만약 데이터가 1.3초 이내에 오지 않으면 어떻게 되나요?

2019-07-20 07:04 UTC, sjjeong commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/RecyclerViewAdapter.kt
> +        NetworkHelper
데이터 호출을 Adapter 안에서 하지 말아주세요

2019-07-20 07:04 UTC, sjjeong commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/RecyclerViewAdapter.kt
> +                tvCurrPrice.text = String.format("%9.2f", currItem.trade_price)
1000단위로 , 추가도 해주세요

2019-07-20 07:04 UTC, sjjeong commented on preludezdev/ArchitectureStudy/app/src/main/res/layout/item_coin.xml
> +        android:text="도지코인"
android:text대신 tools:text를 사용해주세요

2019-07-20 15:59 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/data/CoinMarketResponse.kt
> +                              val english_name: String = "")
업비트 api에서 response로 보내주는 데이터 변수 이름들이 다 스네이크케이스로 되어있는데 상관없는건가요??
![image](https://user-images.githubusercontent.com/41214420/61580936-ad9e2000-ab52-11e9-805a-13c7a3c6de09.png)

2019-07-20 16:21 UTC, sjjeong commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/data/CoinMarketResponse.kt
> +                              val english_name: String = "")
네 데이터를 내려줄때 필드명이 저럴뿐이지 우리가 사용할땐 카멜케이스가 컨벤션입니다.
gson parsing할 때 key를 어떻게 해야하는지 찾아보세요

2019-07-21 04:00 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/BtcFragment.kt
> +class BtcFragment : Fragment() {
Fragment 생성 시 어떤 데이터를 받을지 알려주는 키 값을 가지고 한개만 생성되게 했습니다. 
commit : 19271b7

2019-07-21 04:00 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/network/NetworkHelper.kt
> +    val API_URL = "https://api.upbit.com/"
수정 반영했습니다.
commit : 50352d6c

2019-07-21 04:00 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/SplashActivity.kt
> +                    startActivity(Intent(this@SplashActivity, MainActivity::class.java))
수정 반영했습니다
commit : 23ce89e

2019-07-21 04:01 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/SplashActivity.kt
> +                        var list: List<CoinMarketResponse>? = response.body()
수정 반영했습니다
commit : 6468c8f

2019-07-21 04:01 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/SplashActivity.kt
> +                                var arrMarketName = currMarketName.split("-")
수정 반영했습니다
commit : d8893dd

2019-07-21 04:03 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/SplashActivity.kt
> +            }, delayTime
음... 그러면 반복문으로 해당 부분을 감싸서 1.3초내에 데이터가 안오면 다시 반복하면 괜찮을까요?
그리고 반복문을 3~4번 돌았는데도 데이터를 못받았다 그러면 그대로 앱을 종료하게 하구요

2019-07-21 04:07 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/res/layout/item_coin.xml
> +        android:text="도지코인"
수정 반영했습니다
commit : 49bf2f9

2019-07-21 04:15 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/RecyclerViewAdapter.kt
> +        NetworkHelper
Adapter에 있던 데이터호출을 Fragment 안으로 옮겼습니다
commit : 2784505

2019-07-21 13:56 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/data/CoinMarketResponse.kt
> +                              val english_name: String = "")
컨벤션 확인하고 SerializedName 어노테이션 추가해서 구현했습니다

commit : 712122d

2019-07-21 13:57 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/SplashActivity.kt
> +            }, delayTime
스플래쉬화면에서 바로 레트로핏 통신을 시도해 성공하면 해당 구문 안에서 메인액티비티로 이동하게끔 구현했습니다

commit : dfb4af2

2019-07-21 13:59 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/RecyclerViewAdapter.kt
> +                tvCurrPrice.text = String.format("%9.2f", currItem.trade_price)
Util 패키지 내에 1000단위로 , 추가해주는 함수를 만들어 구현했습니다
어댑터에서 데이터 가공하는 작업(?)을 Fragment로 분리하는 작업은 다음 pr 에서 개선하겠습니다

commit : 64fac68

2019-07-21 14:06 UTC, preludezdev commented
추가로 필요한 개선 작업들
- 뷰홀더 - 데이터 가공 분리
- 뷰홀더에서 데이터 관리하기 위한 새로운 Data Class 만들기 
- 등등...

은 말씀해주신대로 다음 PR에서 진행하도록 하겠습니다

2019-07-21 14:19 UTC, sjjeong approved these changes
추가적인 리뷰는 HW2에서 더 하겠습니다

2019-07-21 14:28 UTC, dlwls5201 approved these changes
approve 합니다.

2019-07-21 14:28 UTC, merged