HW-7 AAC ViewModel 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #133
Opened 2019-07-20 06:45 UTC by NackUn

2019-07-20 12:03 UTC, BeokBeok requested changes

2019-07-20 12:03 UTC, BeokBeok commented on NackUn/StudyFirst/app/build.gradle
>      implementation 'androidx.recyclerview:recyclerview:1.0.0'
com.google.android.material:material 을 추가하여
appcompat, recycler view 를 정리해 주세요

해당 레파지토리의 대한 내용은 하기 URL 에서 확인할 수 있습니다.
https://mvnrepository.com

2019-07-20 12:03 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/ui/ticker/TickerFragment.kt
> +                    return TickerViewModel(
return 대신 = 을 사용할 수 있습니다.

2019-07-20 12:03 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/ui/ticker/TickerFragment.kt
> +
line break 지워 주세요

2019-07-23 02:30 UTC, NackUn commented on NackUn/StudyFirst/app/build.gradle
>      implementation 'androidx.recyclerview:recyclerview:1.0.0'
정리했습니다
062fffc

2019-07-23 02:30 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/ui/ticker/TickerFragment.kt
> +                    return TickerViewModel(
수정했습니다
e3076ba

2019-07-23 02:31 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/ui/ticker/TickerFragment.kt
> +
제거하였습니다
665c722

2019-07-23 03:40 UTC, BeokBeok requested changes

2019-07-23 03:40 UTC, BeokBeok commented on NackUn/StudyFirst/app/build.gradle
> +    implementation group: 'com.google.android.material', name: 'material', version: '1.1.0-alpha08'
com.google.android.material:material:1.1.0 과 같이 쓸 수 있습니다.

2019-07-23 03:40 UTC, BeokBeok commented on NackUn/StudyFirst/app/build.gradle
> -    testImplementation 'junit:junit:4.12'
test 관련 dependency 를 제거하시면, test 관련 코드에서 에러가 발생합니다.

확인 후 추가해주세요.

2019-07-23 04:30 UTC, NackUn commented on NackUn/StudyFirst/app/build.gradle
> +    implementation group: 'com.google.android.material', name: 'material', version: '1.1.0-alpha08'
@BeokBeok 수정했습니다. 이와 같이 쓰는 것과 위와 같이 쓰는 것 중 어느 것이 좋을까요? 
그냥 프로그래머 마음인가요??
85bfb9d

2019-07-23 04:31 UTC, NackUn commented on NackUn/StudyFirst/app/build.gradle
> -    testImplementation 'junit:junit:4.12'
@BeokBeok  수정했습니다.
https://mvnrepository.com/artifact/com.google.android.material/material/1.1.0-alpha08
Test Dependencies 에 junit 이 있는데 지우면 안되는 걸까요

2019-07-23 04:32 UTC, BeokBeok commented on NackUn/StudyFirst/app/build.gradle
> -    testImplementation 'junit:junit:4.12'
junit은 지우셔도 될 것 같습니다.
다만, 지우고나서 반드시 빌드를 해보시고 에러가 나는지 확인해주세요

2019-07-23 04:32 UTC, BeokBeok commented on NackUn/StudyFirst/app/build.gradle
> +    implementation group: 'com.google.android.material', name: 'material', version: '1.1.0-alpha08'
가급적이면 일관된 규칙으로 작성하는 것이 좋다고 봅니다.

2019-07-23 04:39 UTC, NackUn commented on NackUn/StudyFirst/app/build.gradle
> +    implementation group: 'com.google.android.material', name: 'material', version: '1.1.0-alpha08'
넵 감사합니다

2019-07-23 04:41 UTC, NackUn commented on NackUn/StudyFirst/app/build.gradle
> -    testImplementation 'junit:junit:4.12'
넵 제거 후 문제없습니다!
db74e79

2019-07-23 05:00 UTC, BeokBeok approved these changes
LGTM:ok_hand:

2019-07-24 10:24 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-07-25 10:25 UTC, merged