Class03/dlwls5201
sjjeong/GoogryAndroidArchitecutreStudy pull request #134
Opened 2019-07-22 21:47 UTC by dlwls5201

일요일날 작업을 다 끝내고 push를 적용해서 새로 PR을 만들어야 될게 없어 기존 커밋을 되돌리고 새로 작업했습니다. 

 Repository 패턴을 사용해 서버에서 받은 데이터를 local에 저장해 인터넷 여부에 따라 local 혹은 remote 에서 데이터를 받아올 수 있도록 구현해 보았습니다. 또한 Adapter 도 좀더 개선해 보았습니다.

2019-07-23 09:43 UTC, zozero94 reviewed
제가 감히 이해하기에는 코드가 상당히 어렵네요 ㅠㅠ
혹시 몇년차 개발자이신지 여쭤봐도 될까요??
또 궁금한 부분 comment남겼는데 시간 괜찮으실때 답변 주시면 감사하겠습니다!

2019-07-23 09:43 UTC, zojae031 commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/BaseActivity.kt
> +            requestedOrientation = ActivityInfo.SCREEN_ORIENTATION_PORTRAIT
Manifest에서 등록하지 않고 BaseAcitivity를 두어 Orientation을 설정하신 이유가 있을까요?

2019-07-23 09:43 UTC, zojae031 commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/ui/MainAdapter.kt
> +        //super.destroyItem(container, position, `object`)
FragmentPagerAdapter는 Fragment를  파괴하지 않고 재사용 하는것으로 알고 있습니다.
저도 그렇기 때문에 FragmentStatePagerAdapter대신 FragmentPagerAdapter를 사용했는데
위에서 아이템 삭제를 막은 이유를 알 수 있을까요?

생성된 fragment를 파괴하지 않는게 아니라 fragment아이템의 값만 바꿔주고 아이템의 객체를 유지하기 위함인가요?

2019-07-24 00:50 UTC, dlwls5201 commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/BaseActivity.kt
> +            requestedOrientation = ActivityInfo.SCREEN_ORIENTATION_PORTRAIT
1. Manifest로 관리하게 되면 Activity를 생성 할 때마다 Orientation을 적용해야 됩니다. BaseActivity를 상속하여 일괄 처리 하고 싶어서 설정했습니다.
2. https://gun0912.tistory.com/79 박상권님의 삽집 블로그를 보시면 API 26 에서 Orientation 설정 시 Acitivty에 투명 효과를 주면 "Only fullscreen opaque activities can request orientation" 에러가 발생합니다. 이 에러에 대한 예외 처리를 따로 해주기 위함도 있습니다.

2019-07-24 01:17 UTC, dlwls5201 commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/ui/MainAdapter.kt
> +        //super.destroyItem(container, position, `object`)
FragmentPagerAdapter를 사용해도 프래그먼트 생명주기 로그를 확인해보면 onDestroy는 실행되지 않지만 onDestroyView는 실행됩니다. 즉 프래그먼트는 재사용하지만 뷰는 새로 그립니다!  여기서 코인헬퍼는 코인명, 현재가, 전일대비, 거래대금 값에 맞춰 그려진 뷰를 정렬 해야되는데 프래그먼트가 재사용될 때 마다 사용자가 설정한 정렬 값을 적용해주어야합니다. 저는 그러기 보다는 이미 생성된 fragment를 파괴하지 않고 사용자가 설정한 정렬값을 그대로 유지하기 위해 설정했습니다.

fragment아이템의 값만 바꿔주고 아이템의 객체를 유지하기 위함인가요? -> 코인명, 현재가, 전일대비, 거래대금을 클릭했을 때 오름차순, 내림차순을 유지하기 위함입니다.

2019-07-24 06:33 UTC, zojae031 commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/ui/MainAdapter.kt
> +        //super.destroyItem(container, position, `object`)
친절한 답변 감사드립니다!! 덕분에 코드 보고 엄청많이 배워갑니다!

2019-07-24 16:04 UTC, onemask commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/ui/TickerAdapter.kt
Adater에서 정렬에 필요한 변수나 필터값들이 가지고 있어서 길어진것 같은데 
정렬로 필요한 key 값들이 필요한거면 OrderConstants.kt 파일을 따로 빼서 해당 파일의 값을 참조하여
companion object{}를 분리하면 Adapter에 들어 있는 코드들이 좀 더 줄어들지 않을까 생각하였습니다.

2019-07-24 16:04 UTC, onemask commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/ui/TickerAdapter.kt
Constants.kt 나 예외적으로 상수로 계속 참조할만한 파일을 만들고 
object Filter {
        const val KEY_ORDER = "order"
        const val ASC = 0   //오름차순
        const val DESC = 1  //내림차순
        const val KEY_FIELD = "field"
        const val COIN_NAME = "코인명"
        const val LAST = "현재가"
        const val TRADE_DIFF = "전일대비"
        const val TRADE_AMOUNT = "거래대금"
}

2019-07-24 16:04 UTC, onemask commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/ui/TickerAdapter.kt
> +            tvMarket.text = ticker.getCoinName()
BindView에서 참조하는 ticker 값들은 local Data에 있는 CoinName을 참조하는 것인가요?

2019-07-24 16:04 UTC, onemask commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/data/repository/UpbitRepositoryImpl.kt
> -                val pattern = Pattern.compile("^([a-zA-Z]*)-([a-zA-Z]*)$")
`val pattern = Pattern.compile("^([a-zA-Z]*)-([a-zA-Z]*)$")
                    dao.clearMarkets()
                    for (market in markets) {
                        //Timber.d("api market 저장 -> $market")
                        dao.insertMarket(market)
                    }

                    val pattern = Pattern.compile("^([a-zA-Z]*)-([a-zA-Z]*)$")

                    val groupMarket = markets
                        .filter { pattern.matcher(it.market).find() }
                        .groupBy {
                            val idx = it.market.indexOf("-")
                            it.market.substring(0, idx)
                        }

                    Single.just(groupMarket)
                }
                .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())`

2019-07-24 16:04 UTC, onemask commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/data/repository/UpbitRepositoryImpl.kt
> +                    dao.clearMarkets()
network가 연결 되어있으면 위의 로직을 타고 
연결 안되어 있으면 else 구문을 타는데 뭔가 그 안에서 하는 로직들이 비슷한거 같아서 
network의 유무를 판단하여서 getMarkets()을 하는 주체가 누군지 return 해주게끔 하면 코드 수가 훨씬 줄수 있을 거 같아요.

2019-07-24 16:04 UTC, onemask commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/data/repository/UpbitRepositoryImpl.kt
> -    private val api: UpbitApi
변수명을 깔끔하게 잘 지으시네요

2019-07-24 16:04 UTC, onemask commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/ui/TickerAdapter.kt
정렬 안에 when절을 
`  //Dlog.d("order : $order , field : $field")
        when (field) {

            Filter.COIN_NAME-> {
                val selector: (UpbitTicker) -> String = { it.market }
                setOrderByField(selector, order)
            }

            Filter.LAST -> {
                val selector: (UpbitTicker) -> Double = { it.tradePrice }
                setOrderByField(selector, order)
            }

            Filter.TRADE_DIFF -> {
                val selector: (UpbitTicker) -> Double = { it.signedChangeRate }
                setOrderByField(selector, order)
            }

            Filter.TRADE_AMOUNT -> {
                val selector: (UpbitTicker) -> Double = { it.accTradePrice24h }
                setOrderByField(selector, order)
            }
        }`

2019-07-24 16:04 UTC, onemask commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/ui/TickerAdapter.kt
이런식으로 만들면 뭔가 보기 깔끔하지 않을 까 생각하였습니다.

2019-07-24 16:04 UTC, onemask commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/data/source/local/UpbitDao.kt
> +}
번외의 내용인데 지금은 정렬하는 로직이

2019-07-24 16:04 UTC, onemask commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/data/source/local/UpbitDao.kt
> +}
` private fun <R : Comparable<R>> setOrderByField(selector: (UpbitTicker) -> R, order: Int) {
        if (order == ASC) {
            tickers.sortBy(selector)
        } else if (order == DESC) {
            tickers.sortByDescending(selector)
        }

        notifyDataSetChanged()
    }`

2019-07-24 16:04 UTC, onemask commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/data/source/local/UpbitDao.kt
> +}
위와 같았는데 memory Profiler를 돌려본 것은 아니라
 정확하게 퍼포먼스적으로 어느 것이 좋다 라는 
성능적으로 말씀드릴 수는 없지만 
Room을 사용하시려고 query도 추가해주셨다면 
  @Query("SELECT * FROM market ORDER BY ${저장된필드값}  DESC LIMIT 10 ")
으로 정렬하는것도 좋지 않을까 하는 생각을 하였습니다.

2019-07-24 16:04 UTC, onemask commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/ui/TickerAdapter.kt
>                  listener?.onItemClick(ticker)
`
        companion object {
            fun newInstance(parent: ViewGroup, listener: TickerClickListener?): TickerViewHolder {
                return TickerViewHolder(
                    LayoutInflater.from(parent.context).inflate(R.layout.item_ticker, parent, false),
                    listener
                )
            }`

2019-07-24 16:04 UTC, onemask commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/ui/TickerAdapter.kt
>                  listener?.onItemClick(ticker)
위의 코드 블럭 구문에 코멘트가 남겨지지 않아 번거롭겠지만 여기서 코멘트 달겠습니다. 
TickerAdapter에 onCreateViewHolder부분을 newInstance로 처리하여 
        return TickerViewHolder.newInstance(parent, listener)
이렇게 처리해주고 게신데 
저같은 경우는 Extension으로 따로 util 파일 따로 빼서 
`n ViewGroup.inflate(@LayoutRes resource : Int, attachRoot : Boolean =false) : View =
    LayoutInflater.from(context).inflate(resource,this,attachRoot)`
이렇게 작업하고 있습니다. 

extension을 사용하지 않고 adapter마다 newInstance를 생성하여서 view를 inflate하는 것이 더 좋은가요?
코드의 수는 extension이 더 적을거 같은데 newInstance 으로 이용하신 이유가 궁금합니다.

2019-07-25 16:19 UTC, dlwls5201 commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/ui/TickerAdapter.kt
>                  listener?.onItemClick(ticker)
저는 inflate(resource,this,attachRoot) 이 부분을 ViewHolder 클래스에서 처리하고 싶어서 작업했습니다. 위 예제에서는 ViewHolder가 하나이며 Adapter 안에 선언되어 있지만 추후 ViewHolder가 많아지고 따로 패키지로 관리하게 되면 inflate(resource,this,attachRoot) 를 ViewHolder 클래스 내에서가 아닌 onCreateViewHolder에서 확인을 해야하는 번거로움이 있을 것 같았습니다 :)

2019-07-25 16:19 UTC, dlwls5201 commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/data/repository/UpbitRepositoryImpl.kt
> -    private val api: UpbitApi
감사합니다!

2019-07-25 16:28 UTC, dlwls5201 commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/data/source/local/UpbitDao.kt
> +}
이렇게 하면 Adapter에 있는 정렬 로직을 밖으로 뺄 수 있어 더욱 좋을것 같습니다! 
그렇지만 퍼포먼스 적으로 좀더 고민해보겠습니다.

2019-07-25 16:45 UTC, dlwls5201 commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/ui/TickerAdapter.kt
> +            tvMarket.text = ticker.getCoinName()
local Data, remote Data 따로 분리하지 않고 하나의 모델에 같이 쓰고 있습니다. 리포지터리에서는 받아온 모델의 데이터를 TextUtil 를 사용해 가공후 새로 선언한 변수 coinName, last, tradeDiff, tradeAmount 넣어서 Adapter 에서 바로 적용해 주고 있습니다. UpbitTicker 데이터 클래스를 참고해 주세요

2019-07-25 16:47 UTC, dlwls5201 commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/ui/TickerAdapter.kt
훨씬 코드가 깔끔해 진것 같습니다!
ac72646

2019-07-25 16:50 UTC, dlwls5201 commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/data/repository/UpbitRepositoryImpl.kt
> +                    dao.clearMarkets()
UpbitDataSource 인터페이스를 만들어 api와 dao 를 한번더 감싸 공통적으로 사용중인 getMarkets()을 사용할 수 있게 수정했습니다.
5d72985

2019-07-26 16:18 UTC, sjjeong commented
@onemask Review Needed도 추가해주세요

2019-07-28 05:34 UTC, sjjeong reviewed
-

2019-07-28 05:35 UTC, sjjeong requested changes
api랑 dao를 datasource를 통해 가져오게 해주세요

2019-07-29 12:18 UTC, sjjeong requested changes

2019-07-29 12:18 UTC, sjjeong commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/data/repository/UpbitRepositoryImpl.kt
> +    private val dao: UpbitLocalDataSource,
api랑 dao도 이름을 바꿔주면 좋을것 같아요

2019-08-01 14:59 UTC, dlwls5201 commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/data/repository/UpbitRepositoryImpl.kt
> +    private val dao: UpbitLocalDataSource,
변수명 변경했습니다
a790d6f

여기서 궁금한 사항이 있습니다. dataSource로 감싸주긴 했는데 dao와 api의 메소드를 그대로 복붙해서 감싸주었을 뿐 다른 처리를 하지 않았습니다. dataSource로 이렇게 랩핑하는 것이 석준님께서 말씀해 주신 dataSource로 가져오게 하는 방법이 맞는건가요??

2019-08-01 15:12 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-08-03 03:01 UTC, onemask approved these changes

2019-08-04 05:51 UTC, merged