HW-02 Model 적용하기
sjjeong/GoogryAndroidArchitecutreStudy pull request #135
Opened 2019-07-23 07:51 UTC by zojae031

부족한점이 많습니다. 잘부탁드립니다.

2019-07-23 10:47 UTC, zojae031 commented
죄송합니다 중간에 실수해서 forcePush 한번 했습니다. 
commit message만 변경한것이라 큰 문제는 없을것 같습니다.

2019-07-24 01:44 UTC, wkdehdlr reviewed
이번 과제가 model 분리라 repository와 remotedata부분을 중점적으로 봤는데
제가 보기엔 잘 나뉘어져있어 보입니다. 
Local에서 데이터를 가져오는 부분이 추가되었을때 어떤식으로 진행할지도 생각해보면 좋을듯하여
이 부분에 리뷰를 남깁니다.

2019-07-24 01:44 UTC, wkdehdlr commented on zojae031/Project/app/src/main/java/study/architecture/mainjob/MainPresenter.kt
> +    private var list = ""
list를 ""로 초기화하는 이유가 있을까요?  코틀린 lateinit은 어떤가요?

2019-07-24 01:44 UTC, wkdehdlr commented on zojae031/Project/app/src/main/java/study/architecture/util/TextUtil.kt
> +}
포맷팅을 util로 따로 빼서 관리하는 건 좋은 방법인 것 같네요!!

2019-07-24 01:44 UTC, wkdehdlr commented on zojae031/Project/app/src/main/java/study/architecture/model/datasource/RemoteDataSource.kt
> +
만약 로컬에서 데이터를 가져와야한다면 LocalDataSource같은 object를 추가해야하나요?

2019-07-24 01:44 UTC, wkdehdlr commented on zojae031/Project/app/src/main/java/study/architecture/model/repository/Repository.kt
> +object Repository {
Local에서 데이터를 가져온다면 repository에 메소드를 어떻게 추가하실건가요?

2019-07-24 06:38 UTC, zojae031 commented on zojae031/Project/app/src/main/java/study/architecture/util/TextUtil.kt
> +}
@dlwls5201 님 코드보고 배웠습니다.!!

2019-07-24 06:39 UTC, zojae031 commented on zojae031/Project/app/src/main/java/study/architecture/model/datasource/RemoteDataSource.kt
> +
석준님께서 말씀해주시길 Model파트는 데이터를 가져오는부분이라
object (SingleTon Pattern)형식으로 구현된다 하셨습니다!

2019-07-24 06:46 UTC, zojae031 commented on zojae031/Project/app/src/main/java/study/architecture/model/repository/Repository.kt
> +object Repository {
아직 레파지토리패턴에 대해 잘 알지 못하여 정확히는 모르겠습니다
아마도 제가 구현한다면 
```kotlin
fun getRemoteMarketList(){..}
fun getRemoteTickerList(){..}
```

에 추가로 
```kotlin
fun getLocalSometingList(){..}
```
로 두어서 Presenter에서 상황에 따라 가져오고 분리할것 같습니다!

2019-07-24 06:47 UTC, zojae031 commented on zojae031/Project/app/src/main/java/study/architecture/mainjob/MainPresenter.kt
> +    private var list = ""
미처 발견하지 못했네요 감사합니다 수정 커밋입니다.
[a3bb2be](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/135/commits/a3bb2be22578d5d241ecf4a24e09546805f528f6)

2019-07-24 06:48 UTC, zojae031 commented on zojae031/Project/app/src/main/java/study/architecture/model/repository/Repository.kt
> +object Repository {
Local이 추가된 코드는 @dlwls5201 님 코드에 적용이 되어있는데
의존성 주입이랑 제가 이해하기에 다소 어려운 코드가 있어
아직은 제대로 이해하지 못했습니다 ㅠ

2019-07-24 08:39 UTC, zojae031 commented on zojae031/Project/app/src/main/java/study/architecture/model/datasource/RemoteDataSource.kt
> +object RemoteDataSource : UpbitApi {
@onemask 님의 커밋 [Edit > UpbitRepository는 UpbitDataSource를 implement하여 구현](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/137/commits/1025ce5a2188d6bab4168d23f6326f0b50925b35)
을 보고 변경해보았는데 UpbitApi의 존재가 모호합니다.
원래는 UpbitApi가 따로 분리되어 있었습니다. 

``DataSource는 데이터 요청하는 부분이라 하여 최소한으로 데이터를 요청하는 부분만 가지도록 하였습니다.``
``Repository에서 데이터를 가공하고있습니다.``

UpbitApi는 어디부분에 속해야 하나요?? @sjjeong 도와주세요!

2019-07-24 08:43 UTC, sjjeong commented on zojae031/Project/app/src/main/java/study/architecture/model/datasource/RemoteDataSource.kt
> +object RemoteDataSource : UpbitApi {
속해야 한다는게 무슨말인지 모르겠습니다.

UpbitApi는 실제로 Retrofit으로 생성된 api 호출하는 부분이므로 RemoteDataSource에 있는게 맞습니다.

2019-07-24 08:47 UTC, zojae031 commented on zojae031/Project/app/src/main/java/study/architecture/model/datasource/RemoteDataSource.kt
> +object RemoteDataSource : UpbitApi {
원래 따로 분리되어있다가 이번커밋에 위치를 옮겼습니다!!
네이밍을 저렇게하는게 맞나요?

2019-07-24 08:47 UTC, dino-prnd commented on zojae031/Project/app/src/main/java/study/architecture/model/datasource/RemoteDataSource.kt
> +object RemoteDataSource : UpbitApi {
아니요 재영님 생각대로 작성해주세요

2019-07-26 01:02 UTC, wkdehdlr commented on zojae031/Project/app/src/main/java/study/architecture/model/repository/Repository.kt
> +object Repository {
getMarketList, getTickerList같은 메소드를 인터페이스로 분리해서 콜백을 통한 호출을 하는게 좋아보입니다.
따라서 Local이든 Remote든 같은 메소드를 호출할 수 있고 repository에서 이를 분기하여 처리할 수 있습니다.

2019-07-26 03:27 UTC, zojae031 commented on zojae031/Project/app/src/main/java/study/architecture/model/repository/Repository.kt
> +object Repository {
[bbb24fe](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/135/commits/bbb24fe9a467ba37434156a62459e8d89e4aa829) 아래부분에 ``DataSource api 구현체 변경`` 커밋에 변경사항 있습니다! 
rebase를 했어야하는데 죄송합니다

2019-07-27 08:06 UTC, sjjeong requested changes

2019-07-27 08:06 UTC, sjjeong commented on zojae031/Project/app/src/main/java/study/architecture/mainjob/MainPresenter.kt
> +                with(mutableListOf<ProcessingTicker>()) {
list를 새로 만들지 마시고 기존 list에 map함수를 사용해서 해주세요

2019-07-27 08:06 UTC, sjjeong commented on zojae031/Project/app/src/main/java/study/architecture/model/repository/Repository.kt
> +            .observeOn(AndroidSchedulers.mainThread())
observeOn은 getMarketList를 호출한 Activity나 Fragment에서 해주면 좋습니다.

2019-07-27 08:06 UTC, sjjeong commented on zojae031/Project/app/src/main/java/study/architecture/ui/adapter/CoinDataAdapter.kt
> +                changeRate.setTextColor(Color.RED)
색상값도 ProcessingTicker에 저장해서 가져오도록 해보세요

2019-07-27 09:31 UTC, zojae031 commented on zojae031/Project/app/src/main/java/study/architecture/mainjob/MainPresenter.kt
> +                with(mutableListOf<ProcessingTicker>()) {
ProcessingTicker를 사용하지 말라는 것인가요??
그렇다면 Ticker에서
다른 자료형들을 String으로 바꾸어야하는데 어떻게 하는지 모르겠습니다 ㅠㅠ
그렇게 하려다가 실패해서 저렇게 구현했어요

2019-07-27 09:45 UTC, zojae031 commented on zojae031/Project/app/src/main/java/study/architecture/model/repository/Repository.kt
> +            .observeOn(AndroidSchedulers.mainThread())
[9042dea](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/135/commits/9042dea2775a1bce53d6a3d666655ffe2cf38f03)
수정커밋입니다

2019-07-27 09:45 UTC, zojae031 commented on zojae031/Project/app/src/main/java/study/architecture/ui/adapter/CoinDataAdapter.kt
> +                changeRate.setTextColor(Color.RED)
[d8699c3](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/135/commits/d8699c33a4cb4c03d8e7ce0189a12a475b6dcb7b)
수정 커밋입니다.

2019-07-28 03:58 UTC, sjjeong commented on zojae031/Project/app/src/main/java/study/architecture/mainjob/MainPresenter.kt
> +                with(mutableListOf<ProcessingTicker>()) {
.map{ it.map{ data -> ProcessingTicker(
                                TextUtil.getMarketName(data.market),
                                TextUtil.getTradePrice(data.tradePrice),
                                TextUtil.getChangeRate(data.signedChangeRate),
                                TextUtil.getAccTradePrice24h(data.accTradePrice24h)
                            )}

2019-07-28 04:08 UTC, zojae031 commented on zojae031/Project/app/src/main/java/study/architecture/mainjob/MainPresenter.kt
> +                with(mutableListOf<ProcessingTicker>()) {
[5cf5154](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/135/commits/5cf5154ac5b1c2e22afe5e999c8bc4ed8fd1e160) 수정본입니다!

2019-07-28 04:16 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-07-28 05:32 UTC, wkdehdlr approved these changes
수고하셨습니다

2019-07-28 05:32 UTC, merged