HW-7 ViewModel 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #136
Opened 2019-07-23 13:44 UTC by BeokBeok

View Model 과 Sort 기능 적용 하였습니다.

2019-07-25 09:00 UTC, NackUn submitted a review, later dismissed
고생하셨습니다!
93a8ca6 ROOM을 사용해보지 않아서 리뷰가 부족하네요 ㅠ

2019-07-25 15:33 UTC, sjjeong requested changes
CompositeDisposable를 왜 매번 생성해서 사용하셨나요?
객체가 달라져서 사용하는 의미가 없는것 같습니다.

2019-07-26 00:10 UTC, BeokBeok commented
@sjjeong 
CompositeDisposable 객체를 만들고 작업한 것으로 착각했네요.
말씀 안해주셨으면 계속 모르고 넘어갔...

감사합니다! 추가 하였습니다.

2019-07-26 15:34 UTC, sjjeong requested changes

2019-07-26 15:34 UTC, sjjeong commented on BeokBeok/app/src/main/java/com/architecturestudy/util/CompositeDisposable.kt
> +object CompositeDisposable {
예전에 현성님꺼 리뷰에서인가 이렇게 하셔서 제가 문제가 발생할 수 있다고 말한적이 있었어요.
CompositeDisposable은 각각 클래스에서 따로 객체로 관리해야해요

2019-07-26 18:01 UTC, BeokBeok commented on BeokBeok/app/src/main/java/com/architecturestudy/util/CompositeDisposable.kt
> +object CompositeDisposable {
94a14be9fac410cb9984229b77084b1a7f892fb6
뷰모델에서 일괄적으로 관리하도록 변경하였습니다.

2019-07-27 02:57 UTC, sjjeong approved these changes

2019-07-27 03:00 UTC, merged