HW-02 Model 적용하기
sjjeong/GoogryAndroidArchitecutreStudy pull request #138
Opened 2019-07-23 15:38 UTC by wswon

모델에 대해 repository를 추가 하고, package구조를 변경 해보았습니다.
감사합니다.

2019-07-24 18:39 UTC, ganghee commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/data/source/CoinRepository.kt
> +                override fun onFailure(str: String) {
onEmpty와 onFailure는 아무 작업을 하지 않는다면 UpbitRequestListener를 interface가 아니라 그냥 클래스로 구현하고 overriding 하는게 좋을 것 같습니다.
아래 36번 코드 이후도 마찬가지로요

2019-07-24 18:39 UTC, ganghee commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/network/request/UpbitRequest.kt
>              .build()
getMarketList와 getTickerList에서 retrofit객체를 builder패턴으로 중복해서 만들고 있습니다.
싱글톤으로 만들거나 동반객체를 사용하여 retrofit 객체를 구현하면 좋을 것 같습니다.

2019-07-24 19:21 UTC, ganghee commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/view/coin/CoinListActivity.kt
> +        val tabList = listOf(
tabList가 현재 activity에서만 사용한다면 그냥 리스트 변수로 작성해도 좋을 것 같아요
메모리를 낭비하는게 아닌가 싶습니다.

2019-07-25 19:59 UTC, wswon commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/data/source/CoinRepository.kt
> +                override fun onFailure(str: String) {
f87ef96
empty, failure에서 해당내용 Toast메시지로 띄우도록 변경했습니다.

2019-07-25 20:00 UTC, wswon commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/network/request/UpbitRequest.kt
>              .build()
1563d52
공용변수를 사용하도록 변경했습니다.

2019-07-25 20:00 UTC, wswon commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/view/coin/CoinListActivity.kt
> +        val tabList = listOf(
7aaf25f
멤버변수로 사용하도록 변경했습니다.

2019-07-26 15:55 UTC, sjjeong requested changes

2019-07-26 15:55 UTC, sjjeong commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/data/source/CoinRepository.kt
> +        UpbitRequest().apply {
요청하는 것을 CoinRemoteDataSource를 만들어서 처리해주세요.
Repository에서 Remote에 원격데이터 달라고 요청해주시구요

2019-07-28 01:53 UTC, wswon commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/data/source/CoinRepository.kt
> +        UpbitRequest().apply {
4b0c480
object로 CoinRemoteDataSource를 만들어서 수정 해봤습니다.

2019-07-28 04:15 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-07-28 04:17 UTC, ganghee approved these changes

2019-07-28 04:17 UTC, merged