HW-2 코인헬퍼 : 모델에 레포지토리 패턴 적용하기
sjjeong/GoogryAndroidArchitecutreStudy pull request #139
Opened 2019-07-24 07:36 UTC by preludezdev

이번 과제에서 개선한 점
- 리싸이클러뷰 어댑터에서 리스트로 관리하기 위한 data class (Coin) 생성
- 리싸이클러뷰 어댑터에 있던 데이터 가공로직을 Fragment로 이동 
 Repository에서 데이터를 받으면 해당 시점에서 가공해서 Coin 객체를 만든 다음 어댑터에 add 했습니다.

- Repository 패턴 적용

Repository 패턴은 구글 아키텍처 MVP 샘플을 참고했습니다.

https://github.com/googlesamples/android-architecture/tree/todo-mvp/todoapp/app/src/main/java/com/example/android/architecture/blueprints/todoapp/data/source

리뷰 잘 부탁드립니다 :)

2019-07-24 09:08 UTC, dlwls5201 reviewed
구글 샘플에 맞춰 리포지터리 패턴 멋지게 구현한것 같습니다!

2019-07-24 09:08 UTC, dlwls5201 commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/RecyclerViewAdapter.kt
> +        notifyDataSetChanged()
한 아이템만 추가해 주는 경우 notifyItemInserted()를 사용하는게 좋습니다.

2019-07-24 09:08 UTC, dlwls5201 commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/MarketFragment.kt
>                      }
현재 코드에서는 addData 를 할때 마다 notifyDataSetChanged를 실행 해주고 있습니다. setData()를 사용해서 notifyDataSetChanged를 1번만 호출되게 해주세요.

2019-07-24 09:08 UTC, dlwls5201 commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/SplashActivity.kt
>                  }
데이터를 다 받아오면 바로 MainAcitivty로 넘어가 될 것 같은데 굳이 딜레이를 넣은 이유는 무엇인가요?
그리고 MainAcitvity로 이동 할 때 finish() 추가해 주세요.

2019-07-24 09:08 UTC, dlwls5201 commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/data/source/CoinsRepository.kt
> +object CoinsRepository : CoinsDataSource {
CoinsRemoteDataSource, CoinsLocalDataSource 는 이미 object 즉 싱글턴으로 구현 해주셨는데 굳이 Repository까지 object로 하는건 메모리 효율이 떨어지는 부분인것 같습니다. Repository는 class 로 바꿔 사용해도 충분할 것 같습니다.

2019-07-24 09:43 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/RecyclerViewAdapter.kt
> +        notifyDataSetChanged()
수정 반영했습니다.

commit : ace73ab

2019-07-24 09:43 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/MarketFragment.kt
>                      }
피드백 반영했습니다.

commit : beb7e19

2019-07-24 09:46 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/SplashActivity.kt
>                  }
음...메인 들어가기전에 뭐랄까 약간 대문같은 느낌의 스플래쉬 감성...을 넣고싶은거였는데 그거 말고는 아무 의미 없습니다...ㅠ 딜레이 부분 삭제하고 finish() 추가했습니다.

commit : 5ac8d1f

2019-07-24 09:49 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/data/source/CoinsRepository.kt
> +object CoinsRepository : CoinsDataSource {
현재 제 코드에서 Repository에 접근하는 부분이 SplashActivity하고 MainActivity 내에 있는 MarketFragment 인데 두 부분에서 동시에 접근하기 편하게 하기 위해 Repository도 싱클톤(전역변수?) 로 구현했습니다. + 사실 구글 샘플에도 레포지토리 부분이 싱클톤으로 구현되어있어서 따라한것도 있는데... 확인 부탁드립니다.

2019-07-24 13:30 UTC, dlwls5201 reviewed
코멘트 남겼습니다.

2019-07-24 13:30 UTC, dlwls5201 commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/data/source/CoinsRepository.kt
> +object CoinsRepository : CoinsDataSource {
구글 예제의 kotlin 브런치를 보면 getInstance() 를 사용해서 구현하고 있습니다. 현재 작성하신 코드는 CoinsRepository가 CoinsRemoteDataSource, CoinsLocalDataSource에 직접적으로 의존하고 있습니다.  좀더 나은 코드로 변경하기 위해선 구글 예제에서와 같이 getInstance() 를 만들어 변수를 외부에서 주입해 의존도를 낮춰보세요

https://github.com/googlesamples/android-architecture/blob/todo-mvp-kotlin/todoapp/app/src/main/java/com/example/android/architecture/blueprints/todoapp/data/source/TasksRepository.kt

2019-07-24 14:42 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/data/source/CoinsRepository.kt
> +object CoinsRepository : CoinsDataSource {
아 코틀린 샘플도 있었군요.
Repository 는 클래스로 만든 다음 getInstance() 를 사용해 구현하는 부분 확인했습니다. 
생성자에 CoinsRemoteDataSource와 CoinsLocalDataSource를 넣어 SplashActivit와 Fragment에서 Repository 클래스 사용시 두 객체를 매개변수에 넣어 사용하게끔 구현했습니다. 
일단 예제 보고 구현은 했는데... 사실 개념에 대해선 아직 이해가 잘 안되고 있습니다. 
일단 이전코드와 이번에 고친 코드 둘다 싱클톤으로 구현하는거 같긴한데...
두 DataSource객체를 외부에서 넣어주는것만으로 어떻게 의존도가 낮아지는지 궁금합니다.

commit : e829d5b

2019-07-25 01:29 UTC, dlwls5201 commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/data/source/CoinsRepository.kt
> +object CoinsRepository : CoinsDataSource {
이 부분은 MVP, MVVM, DI 순으로 스터디가 진행되면서 같이 이해할 수 있을 것 같습니다! 사실 저도 잘 알고 적용하고 있지는 못하지만 소프트웨어 공학에서 말하는 **결합도는 낮게 응집도는 높게** 하라는 원칙을 계속 생각하면서 배워가고 있습니다. 고생 많으셨습니다!

2019-07-25 02:46 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/data/source/CoinsRepository.kt
> +object CoinsRepository : CoinsDataSource {
네 알겠습니다.
매번 피드백 감사드립니다!! :D

2019-07-25 15:58 UTC, sjjeong requested changes
CoinDataSource에 있는 Callback들을 kotlin higher-order-function으로 변경해보세요

2019-07-25 15:58 UTC, sjjeong commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/data/source/remote/CoinsRemoteDataSource.kt
> +                    response.body()?.let { callback.onAllMarketLoaded(it) } // 이부분 맞게 코딩한건지 확인 필요
body가 null일 때 onDataNotAvailable를 호출해주는게 맞는것 같습니다.

2019-07-25 15:58 UTC, sjjeong commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/MarketFragment.kt
> +        CoinsRepository
CoinsRepository를 loadData를 호출할 때 만들지 마시고 MarketFragment의 property로 가지고 있으면 좋을 것 같아요

2019-07-25 15:58 UTC, sjjeong commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/MarketFragment.kt
> +                        list.add(convertTickerIntoCoin(ticker))
list에 add하지마시고
tickers.map { } 해서 해보세요

2019-07-25 15:58 UTC, sjjeong commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/RecyclerViewAdapter.kt
> +                tvSignedChangedRate.setTextColor(Color.BLUE)
색상정보도 Coin class안에 있으면 될꺼같아요

2019-07-25 15:58 UTC, sjjeong commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/RecyclerViewAdapter.kt
> +    fun addData(data: Coin) {
unused 함수라서 제거해주세요

2019-07-25 15:58 UTC, sjjeong commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/SplashActivity.kt
> +                            "KRW" -> MainActivity.KRW_MARKETS.add(currMarketName.trim())
MainActivity에 있는 XXX_MARKETS를 제거 해주세요.
이렇게 하는 건 좋지 않은 패턴입니다.

2019-07-25 17:12 UTC, zion830 commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/data/source/remote/CoinsRemoteDataSource.kt
> +        retrofit = Retrofit.Builder()
retrofit 객체를 생성하는 코드와 url string을 dataSource 안에서 직접 선언하는 대신,
재사용 할 수 있도록 별도의 클래스로 분리하는건 어떨까요?

2019-07-25 17:24 UTC, zion830 commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/data/source/remote/CoinsRemoteDataSource.kt
> +                    t.printStackTrace()
여기서 콜백 인터페이스에 정의된 onDataNotAvailable가 호출되어야할 것 같아요
 (오버라이딩만 되어있고 쓰이지 않아서 외로워하고 있네요)
```
callback.onDataNotAvailable()
```

2019-07-25 17:32 UTC, zion830 commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/MarketFragment.kt
recyclerView는 이렇게도 초기화할 수 있어요
```
recyclerView.apply { 
            layoutManager = LinearLayoutManager(activity)
            adapter = rvAdapter
        }
```

2019-07-26 11:09 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/data/source/remote/CoinsRemoteDataSource.kt
> +                    response.body()?.let { callback.onAllMarketLoaded(it) } // 이부분 맞게 코딩한건지 확인 필요
엘비스 연산자 이용해서 body가 null 일 때 onDataNotAvailable 호출하게 바꾸었습니다

commit : 68d3738

2019-07-26 11:09 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/MarketFragment.kt
> +        CoinsRepository
피드백 반영했습니다

commit : 201fe54

2019-07-26 11:10 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/MarketFragment.kt
> +                        list.add(convertTickerIntoCoin(ticker))
map 스트림 함수 이용해서 코드 개선했습니다

commit : 0c42048

2019-07-26 11:11 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/RecyclerViewAdapter.kt
> +                tvSignedChangedRate.setTextColor(Color.BLUE)
Coin 클래스에 색상정보 추가하고 관련코드 개선했습니다

commit : d3998ca

2019-07-26 11:11 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/RecyclerViewAdapter.kt
> +    fun addData(data: Coin) {
addData() 함수 제거했습니다

commit : 34d6b2e

2019-07-26 11:15 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/SplashActivity.kt
> +                            "KRW" -> MainActivity.KRW_MARKETS.add(currMarketName.trim())
MainActivity에 있는 XXX_MARKETS를 제거하면서 기존에 SplashActivity와 MarketFragment에서 해당 변수에 접근해서 각각 데이터를 받아오는 로직도 다 변경했습니다. 슬랙에서 말씀해주신데로 '전체마켓목록' 과 '마켓별 코인정보들' 데이터를 가져오는 로직 둘 다 MarketFragment 안에서 구현했습니다만 콜백함수 안에 또 다른 콜백함수 있는게 보기에 조금 지저분하고 맞게 한건지 잘 모르겠습니다. 확인 부탁드립니다.

commit :  71ca7a3

2019-07-26 11:19 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/data/source/remote/CoinsRemoteDataSource.kt
> +        retrofit = Retrofit.Builder()
RetrofitHelper 클래스를 싱클톤으로 만들어 retrofit 객체 생성하는 코드와 url String 데이터를 해당 클래스 안에 넣어주었습니다!

commit : b2bdb31

2019-07-26 11:24 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/data/source/remote/CoinsRemoteDataSource.kt
> +                    t.printStackTrace()
콜백에 실패하면 printStackTrace() 대신에 callback.onDataNotAvailable() 함수를 호출해 해당 함수의 외로움을 덜어주었습니다 : )

commit : 9cbed91

2019-07-26 11:26 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/MarketFragment.kt
알려주신대로 apply() 함수를 이용해 recyclerView 초기화 해주었습니다

commit : 9a606fe

2019-07-26 11:29 UTC, preludezdev commented
> CoinDataSource에 있는 Callback들을 kotlin higher-order-function으로 변경해보세요

말씀해주신 뒤로 higher-order-function 개념 열심히 찾아서 읽어봤는데 아직 잘 감이 안오네요

CoinDataSource에 있는 Callback들을 변경하라는게 혹시...

`fun getCoinTickers(markets: String, callback: GetCoinTickersCallback)

fun getCoinTickers(markets: String, callback: (getCoinTickersCallback : GetCoinTickersCallback) -> Unit)`

이렇게 변경하는게 맞는지 확인 부탁드릴게요

2019-07-26 16:01 UTC, sjjeong commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/MarketFragment.kt
> +                        list.add(convertTickerIntoCoin(ticker))
```kotlin
rvAdapter.setData(tickers.map(::convertTickerIntoCoin))
```
처럼 사용 할 수 있습니다.

2019-07-26 16:17 UTC, sjjeong requested changes

2019-07-26 16:17 UTC, sjjeong commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/MarketFragment.kt
> +                "KRW" -> args.putSerializable("KEY_MARKET", "KRW")
putString을 쓰시면 됩니다.

2019-07-26 18:56 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/MarketFragment.kt
> +                "KRW" -> args.putSerializable("KEY_MARKET", "KRW")
해당 부분 putString() 함수 호출로 변경하였습니다

commit : e6719ae

2019-07-26 18:59 UTC, preludezdev commented
위에 Callback 을 higher-order-function 으로 바꾸는 부분도 피드백 주시면 감사하겠습니다

2019-07-26 19:11 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/MarketFragment.kt
> +                        list.add(convertTickerIntoCoin(ticker))
알려주신대로 코드 개선했습니다

commit : f194d45

2019-07-27 08:11 UTC, sjjeong commented
> > CoinDataSource에 있는 Callback들을 kotlin higher-order-function으로 변경해보세요
> 
> 말씀해주신 뒤로 higher-order-function 개념 열심히 찾아서 읽어봤는데 아직 잘 감이 안오네요
> 
> CoinDataSource에 있는 Callback들을 변경하라는게 혹시...
> 
> ![image](https://user-images.githubusercontent.com/41214420/61948958-3d751b80-afe4-11e9-915d-af2c953c6363.png)
> 
> 이렇게 위 코드를 아래 코드처럼 변경하는게 맞는지 확인 부탁드릴게요

매번 interface를 만들어야해서 불편한게 있는데 higher-order function을 쓰면 Interface 없이 할 수 있습니다.

2019-07-29 11:40 UTC, preludezdev commented
- CoinsRemoteDataSource 생성자에 Retrofit CoinApiService api 를 주입하게 했습니다 f6e72a8
- CoinsRemoteDataSource, CoinsLocalDataSource 둘다 object 대신 class로 생성하고 클래스 내에 getInstance 함수를 추가했습니다
- Higher-Order-Function 을 이용해 Repository 콜백 코드를 개선했습니다  : 339efa8

2019-07-29 12:21 UTC, sjjeong requested changes

2019-07-29 12:21 UTC, sjjeong commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/MarketFragment.kt
> +                            marketList.add(currMarket)
list에 map이라는 함수를 사용해서 처리해보세요.
mutableList를 새로 만들어서 add 해줄 필요가 없습니다.

2019-07-29 14:29 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/MarketFragment.kt
> +                            marketList.add(currMarket)
filter() 스트림 함수를 이용해 코드를 개선했습니다

commit : 6e30786

2019-07-29 15:21 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-08-02 10:03 UTC, dlwls5201 approved these changes
고생하셨습니다.

2019-08-02 10:03 UTC, merged