HW-02 Model 적용하기
sjjeong/GoogryAndroidArchitecutreStudy pull request #140
Opened 2019-07-24 09:22 UTC by ganghee

repository 패턴을 적용해 보았습니다.

2019-07-24 14:57 UTC, wswon reviewed
Rx를 모르고 Model 개념에 대한 확신이 없어서 
그에대한 리뷰는 많이 못달아 드린것 같아요. 
구조에 대한 개념을 계속 공유 할 수 있다면 좋겠습니다!

2019-07-24 14:57 UTC, wswon commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/adapter/TickerAdapter.kt
> +    override fun onBindViewHolder(holder: Holder, position: Int) {
onBindViewHolder에서 데이터를 ViewHolder에 Binding 하게되면,
단일책임의 원칙에 어긋나고 성능에 저하를 준다고 스터디시간에 들었습니다. 
따라서 ViewHolder의 item이 TickerResponse를 포맷팅한 다른 Class가 되어야 할 듯 합니다.

2019-07-24 14:57 UTC, wswon commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/adapter/TickerAdapter.kt
> +        var coinName: TextView = itemView.tv_coin_name
viewHolder의 Textview 객체는 val로 선언하는것이 좋아보입니다.
스터디 시간에 제 코드의 지적사항 이었는데, 
value로 선언하는 습관을 들이고 필요에 따라서만 variable을 사용하는 것이 좋은 습관이라고 들었습니다.

2019-07-24 14:57 UTC, wswon commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/adapter/TickerAdapter.kt
> +        var coinName: TextView = itemView.tv_coin_name
또한 필수사항은 아닐 수 있지만, 
inner class를 따로 파일로 분리하는것이 좋다고 들었습니다.

2019-07-24 14:57 UTC, wswon commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/adapter/TickerAdapter.kt
> +    }
```
override fun onCreateViewHolder(parent: ViewGroup, viewType: Int): Holder {
        val view: View = LayoutInflater.from(ctx).inflate(R.layout.rv_item_list, parent, false)
        return Holder(view)
 }
```
위의코드를 
```
    override fun onCreateViewHolder(parent: ViewGroup, viewType: Int)
            = Holder(LayoutInflater.from(ctx).inflate(R.layout.rv_item_list, parent, false))
```
이렇게 변경할 수 도 있을것 같습니다.

2019-07-24 14:57 UTC, wswon commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/adapter/TickerAdapter.kt
> +        if (dataList[position].tradePrice > 0.1) {
현재가를 포맷하는 부분에 오류가 있는듯 합니다. 
강희님의 프로젝트를 clone해서 실행 해보았더니 
ETH, USDT의 현재가 정보가 CoinHelper어플과 다른점이 있습니다.

2019-07-24 14:57 UTC, wswon commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/fragment/UpbitFragment.kt
> +        tickerAdapter = TickerAdapter(context!!, dataList)
!!을 사용하는 것은 권장되지 않는 방법으로 알고 있습니다.
다른 방법으로는,
fragment의 경우  requireContext() 함수로도 context를 얻을 수 있습니다.

2019-07-24 14:57 UTC, wswon commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/fragment/UpbitFragment.kt
> +                            it.market.split("-")[0] == firstMarket
`it.market.split("-")[0] == firstMarket`
inline함수의 it을 중첩해서 사용하는것은 명시적이지 않아서 좋은 방법이 아닌 것 같습니다.

`tickerResponse -> tickerResponse.market.split("-")[0] == firstMarket`
이렇게 앞에 이름을 지정할 수 있습니다.

2019-07-24 14:57 UTC, wswon commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/fragment/UpbitFragment.kt
>          rv_korean.adapter = adapter
```
val adapter = TickerAdapter(ctx, posts!!)
rv_korean.adapter = adapter
```
line 44의 코멘트와 동일한 이유로
!!을 사용하지 않는다면 좋을 것 같습니다.

```
posts?.let {
       val adapter = TickerAdapter(ctx, it)
       rv_korean.adapter = adapter
 }
```
예를들면 이런 방법이 있습니다.

2019-07-24 14:57 UTC, wswon commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/fragment/UpbitFragment.kt
>      var firstMarket = tabName
priavate val로 선언해도 문제없을 것 같습니다.

2019-07-24 14:57 UTC, wswon commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/fragment/UpbitFragment.kt
> +        repository.getMarket()
Rx를 잘 모르지만 간략히 보기로는
페이지에 해당하는 정보를 가져올때 api가 항상 두번 호출되는 것 같아요. 

market, ticker 순으로 호출을 하는 것 으로 보이고
ticker를 krw, btc, eth, usdt 전부 다 가져온다음에 filter함수로 firstMarket 으로 필터링을 하고 있는데,
이 요청이 있기 전부터 UpbitFragment는 자기가 어떤페이지인지 firstMarket변수를 통해 알고있기 때문에
해당하는 데이터만 불러올 수 있지 않을까 싶습니다.

또, fragment가 생성되기 이전에, 해당하는 fragment의 marketList를 받아온다면 
call market -> call ticker 순으로 진행되는 작업이
call ticker로 끝날 수 있을 것 같습니다.

2019-07-24 19:32 UTC, ganghee commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/adapter/TickerAdapter.kt
> +        var coinName: TextView = itemView.tv_coin_name
#61~#66
UpbitHolder파일을 따로 만들고 val로 수정하였습니다.

2019-07-24 19:50 UTC, ganghee commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/adapter/TickerAdapter.kt
> +    }
```
override fun onCreateViewHolder(parent: ViewGroup, viewType: Int) =
        UpbitHolder(LayoutInflater.from(ctx).inflate(R.layout.rv_item_list, parent, false))
```
로 수정하였습니다.

2019-07-24 19:50 UTC, ganghee commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/fragment/UpbitFragment.kt
> +        tickerAdapter = TickerAdapter(context!!, dataList)
requireContext() 로 수정하였습니다!

2019-07-24 19:50 UTC, ganghee commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/fragment/UpbitFragment.kt
>          rv_korean.adapter = adapter
`66`
우석님의 의견을 참고하여 수정하였습니다.

2019-07-24 19:53 UTC, ganghee commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/fragment/UpbitFragment.kt
>      var firstMarket = tabName
넵 수정하였습니다.

2019-07-25 16:29 UTC, ganghee commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/fragment/UpbitFragment.kt
> +        repository.getMarket()
네 프래그먼트마다 두번의 호출이 있는것을 알고 있습니다. 
하지만 딜레이가 생기는 문제점이 있습니다.
MainActivity에서 서버에서 markets이름을 가져와 string 변수에 저장하였습니다.
Fragment에 String변수를 가져와 ticker를 api요청을 하였습니다. 
두개의 api가 비동기로 작동하여 첫 번째 market이름을 가져오는 api가 완료되기도 전에 ticker api가 실행되어 빈화면이 나타납니다. 수정하려고 했지만 제 역량으로는 비동기 문제를 해결하기 힘드네요...

2019-07-25 18:50 UTC, ganghee commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/adapter/TickerAdapter.kt
> +    override fun onBindViewHolder(holder: Holder, position: Int) {
네! 우석님의 코드를 참고하여 tickerResponse의 toTicker를 구현하였습니다.
그 전에 데이터를 서버에서 불러올 때 옵저버블의 map메서드를 이용하려고 했는데
쉽지 않네요

2019-07-25 19:07 UTC, ganghee commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/adapter/TickerAdapter.kt
> +        if (dataList[position].tradePrice > 0.1) {
넵! 3자리 이상은 정수만 2자리 숫자는 소수점 첫 째자리 1자리 숫자는 소수점 둘 째자리 1미만은 소수점 8자리로 수정하였습니다.

2019-07-25 19:15 UTC, ganghee commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/fragment/UpbitFragment.kt
> +                            it.market.split("-")[0] == firstMarket
이름을 지정하여 수정하였습니다.

2019-07-25 20:04 UTC, wswon commented
수정사항 전부 확인했습니다! mentor needed  라벨 추가할게요.

2019-07-26 16:31 UTC, sjjeong requested changes

2019-07-26 16:31 UTC, sjjeong commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/adapter/UpbitHolder.kt
> +    fun bind(context: Context, ticker: FormatTickers) {
context는 itemView.context를 사용하면 됩니다.
context를 파라미터로 받는 것을 제거해주세요

2019-07-26 16:31 UTC, sjjeong commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/adapter/TickerAdapter.kt
> +class TickerAdapter(private var ctx: Context, private var dataList: List<FormatTickers>) :
context를 파라미터로 받지 말아주세요

2019-07-26 16:31 UTC, sjjeong commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/data/UpbitRepository.kt
> +    private val api: UpbitApi
api를 사용하지 않는 것 같으니 제거해주세요

2019-07-26 16:31 UTC, sjjeong commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/data/UpbitRepository.kt
> +            .subscribeOn(Schedulers.io())
subscribeOn은 RemoteDataSource에서 해주면 됩니다.

2019-07-26 16:31 UTC, sjjeong commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/data/UpbitRepository.kt
> +            .observeOn(Schedulers.newThread())
observeOn은 실제 subscribe하는 곳에서 해주세요

2019-07-26 16:31 UTC, sjjeong commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/data/remote/UpbitDataSource.kt
> +object UpbitDataSource {
UpbitRemoteDataSource로 변경해주세요

2019-07-26 16:31 UTC, sjjeong commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/network/UpbitService.kt
> +    var upbitApi: UpbitApi
외부에서 set이 가능한 상태입니다.
private set을 추가하거나 val로 선언하고 lazy로 처리하거나 해주세요

2019-07-26 16:31 UTC, sjjeong commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/ui/fragment/UpbitFragment.kt
> +                    .subscribeOn(Schedulers.io())
subscribeOn을 remote쪽에서 처리해주세요

2019-07-26 16:31 UTC, sjjeong commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/ui/fragment/UpbitFragment.kt
> +            posts.forEach{
map함수를 사용해 처리해주세요

2019-07-26 16:31 UTC, sjjeong commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/ui/fragment/UpbitFragment.kt
> +            rv_tickers.adapter = TickerAdapter(ctx, tickerList)
RecyclerView setup하는 것은 데이터 오고나서가 아니라 onActivityCreated 되는 시점에 해주세요

2019-07-26 16:31 UTC, sjjeong commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/ui/fragment/UpbitFragment.kt
> +        compositeDisposable.clear()
compositeDisposable을 사용한 목적이 뭔가요?
add하는 부분이 없고 clear하는 부분만 있습니다.

2019-07-26 16:31 UTC, sjjeong commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/util/FormatText.kt
> +class FormatText(val ctx: Context) {
context가 사용되지 않으니 제거해주세요.

2019-07-26 16:31 UTC, sjjeong commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/util/FormatText.kt
> +class FormatText(val ctx: Context) {
class가 아니라 object로 만들어도 될 것 같습니다.

2019-07-26 16:43 UTC, sjjeong commented
Assignees 추가해주세요

2019-07-28 02:11 UTC, ganghee commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/adapter/UpbitHolder.kt
> +    fun bind(context: Context, ticker: FormatTickers) {
네 제거 하였습니다.
[66e147d](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/140/commits/2146a8d5114188a151bdd57c23c4f8e6cfa460ad)

2019-07-28 02:14 UTC, ganghee commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/adapter/TickerAdapter.kt
> +class TickerAdapter(private var ctx: Context, private var dataList: List<FormatTickers>) :
넵 수정하였습니다.
[c250192](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/140/commits/c250192494d11392e4b61b9c5cd6981a58231ae3)

2019-07-28 02:15 UTC, ganghee commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/data/UpbitRepository.kt
> +    private val api: UpbitApi
네 수정하였습니다.
[a151390](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/140/commits/a1513903f58f09435c0c08e7ee057a136e56315e)

2019-07-28 02:15 UTC, ganghee commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/data/UpbitRepository.kt
> +            .subscribeOn(Schedulers.io())
네 수정하였습니다.
[a151390](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/140/commits/a1513903f58f09435c0c08e7ee057a136e56315e)

2019-07-28 02:15 UTC, ganghee commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/data/UpbitRepository.kt
> +            .observeOn(Schedulers.newThread())
네 수정하였습니다.
[a151390](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/140/commits/a1513903f58f09435c0c08e7ee057a136e56315e)****

2019-07-28 02:16 UTC, ganghee commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/data/remote/UpbitDataSource.kt
> +object UpbitDataSource {
네 수정하였습니다.
[ea1d78f](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/140/commits/ea1d78fd4225973a4f1a1c4ea7967205a378f8c3)

2019-07-28 02:17 UTC, ganghee commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/network/UpbitService.kt
> +    var upbitApi: UpbitApi
네 수정하였습니다.
[6bd65ed](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/140/commits/6bd65ed621e1088f5345bc8a83133937f363a3d4)

2019-07-28 02:17 UTC, ganghee commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/ui/fragment/UpbitFragment.kt
> +                    .subscribeOn(Schedulers.io())
네 수정하였습니다.
[e4f8d01](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/140/commits/e4f8d01815e377a0d35d978fc5408d1639ee2f88)

2019-07-28 02:18 UTC, ganghee commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/ui/fragment/UpbitFragment.kt
> +            posts.forEach{
네 수정하였습니다.
[e4f8d01](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/140/commits/e4f8d01815e377a0d35d978fc5408d1639ee2f88)

2019-07-28 02:18 UTC, ganghee commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/ui/fragment/UpbitFragment.kt
> +        compositeDisposable.clear()
네 수정하였습니다.
[e4f8d01](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/140/commits/e4f8d01815e377a0d35d978fc5408d1639ee2f88)

2019-07-28 02:20 UTC, ganghee commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/util/FormatText.kt
> +class FormatText(val ctx: Context) {
네 수정하였습니다.
[66e147d](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/140/commits/66e147ddbe09960b2d1019e2e6c2874cd578f918)

2019-07-28 02:20 UTC, ganghee commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/util/FormatText.kt
> +class FormatText(val ctx: Context) {
네 수정하였습니다.
[66e147d](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/140/commits/66e147ddbe09960b2d1019e2e6c2874cd578f918)

2019-07-28 07:06 UTC, ganghee commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/ui/fragment/UpbitFragment.kt
> +            rv_tickers.adapter = TickerAdapter(ctx, tickerList)
onActivityCreated 시점에 구현하였습니다. 
[3c500d7](
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/140/commits/3c500d7cd80a402eb3c720e941af82414d8519cc)

2019-07-29 12:24 UTC, sjjeong commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/data/UpbitRepository.kt
> +            .observeOn(Schedulers.newThread())
@ganghee 
commit id가 잘못된거같습니다.

2019-07-29 12:26 UTC, sjjeong approved these changes
코멘트당 커밋 하나씩 해주셔야합니다.
같은 라인이라도 코멘트 내용이 다르다면 커밋을 나눠서 해주세요.

2019-07-30 00:42 UTC, wswon approved these changes

2019-07-30 00:48 UTC, merged