HW-2 Model 적용하기
sjjeong/GoogryAndroidArchitecutreStudy pull request #143
Opened 2019-07-24 12:54 UTC by wkdehdlr

뷰에서 모델을 모르게 하는건 알겠는데 막상 구현하려니 어려운 부분이 많네요.....

2019-07-25 03:51 UTC, wkdehdlr commented
repository를 다시 구현했습니다

2019-07-25 06:47 UTC, zozero94 reviewed
각 프레그먼트의 동작이 중복되며 조금더 다듬을 수 있을것 같습니다.
ex) FragmentKRW.kt
```kotlin
private const val ARG_PARAM1 = "param1" //사용안됨 삭제 필요
private const val ARG_PARAM2 = "param2"
```

```kotlin
class FragmentKRW(val itemList: List<UpbitItem>) : Fragment() {


    override fun onCreateView(
        inflater: LayoutInflater, container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View? =

        inflater.inflate(R.layout.fragment_fragment_krw, container, false).apply {
            // Inflate the layout for this fragment
            with(findViewById<RecyclerView>(R.id.mRecyclerView_KRW)) {
                adapter = MainRvAdapter(context!!, itemList)
                layoutManager = LinearLayoutManager(context!!)
                setHasFixedSize(true)
            }
        }
    
}

```
간략하게 요약 가능해보입니다.

**앱 실행시 리스트가 시간이 일정하게 나타나지 않고 왔다갔다 해야 나타나는 문제점 있습니다.**
 해결 부탁드려요

2019-07-25 06:47 UTC, zojae031 commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/ui/MainActivity.kt
> +        loadUpbitMarket()
비동기처리가 되지 않아 해당부분에서 죽네요!
```kotlin
loadUpbitMarket()
```
수행 후 ``marketlist``를 받아 온 후 

```kotlin
 private fun loadUpbitMarket() {
        repository.getMarket(object : UpbitDataSource.GetMarketCallback {
            override fun onMarketLoaded(markets: List<UpbitMarket>) {
                marketList = markets.joinToString(",") { it.market }
                loadUpbitTicker() //추가된 부분
            }

            override fun onDataNotAvailable(t: Throwable) {
                t.printStackTrace()
            }
        })
    }
```

이렇게 호출하는게 좋아 보입니당

2019-07-25 06:47 UTC, zojae031 commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/util/TextEditor.kt
> +    fun makeSignedChangeRate(param: Double) = String.format("%.2f", param * 100)
데이터 가공이 부족해 보입니다.
KRW 프레그먼트에서 전일대비가 100000단위가 나오는 것도 있고
BTC 프레그먼트에서는 0.00으로 나오는게 많네요

2019-07-25 06:47 UTC, zojae031 commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/ui/MainActivity.kt
> +                    val name = item.market.split("-")[1]
해당 부분을 TextEditor로 넘기는게 더 좋을것 같습니다
모듈화가 제대로 안된것 같아요

2019-07-25 06:47 UTC, zojae031 commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/network/ApiConnector.kt
> +                    setUpbitTicker(it.joinToString(",") { it.market })
사용되지 않는 ApiConnector class 삭제 부탁드립니다.

2019-07-25 06:47 UTC, zojae031 commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/data/Repository.kt
> +    private fun getMarketFromRemoteDataSource(callback: UpbitDataSource.GetMarketCallback) {
```kotlin
override fun getMarket(callback: UpbitDataSource.GetMarketCallback) {
 upbitRemoteDataSource.getMarket(object : UpbitDataSource.GetMarketCallback {
            override fun onMarketLoaded(markets: List<UpbitMarket>) {
                callback.onMarketLoaded(markets)
            }

            override fun onDataNotAvailable(t: Throwable) {
                callback.onDataNotAvailable(t)
            }
        })
}

```

으로 함수를 하나로 줄일 수 있을것 같습니다.

2019-07-25 06:50 UTC, zojae031 commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/data/Repository.kt
> +                callback.onTickerLoaded(tickers)
MainActivity에서 데이터를 가공하고있는데
이부분에서 데이터를 가공해서 callback으로 던져주는 형태가 더욱 좋아보입니다

2019-07-25 09:10 UTC, wkdehdlr commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/ui/MainActivity.kt
> +        loadUpbitMarket()
[cc6a226](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/143/commits/cc6a2266f3cf7071a5cec7b4d279e34c5d6f0578) 프래그먼트 수정했습니다
[df87015](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/143/commits/df8701520aa1b6a6ca3ed8719a88692e2ec9b673) 비동기 수정했습니다

2019-07-25 09:12 UTC, wkdehdlr commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/network/ApiConnector.kt
> +                    setUpbitTicker(it.joinToString(",") { it.market })
[1af9a9c](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/143/commits/1af9a9c7163dd0924bb099cd516217f9d42b788c) 삭제했습니다

2019-07-25 09:14 UTC, wkdehdlr commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/data/Repository.kt
> +    private fun getMarketFromRemoteDataSource(callback: UpbitDataSource.GetMarketCallback) {
추후에 Local에서 데이터를 가져올것을 대비해서 getMarket에서 분기를 통해 메소드를 호출하기 위해 따로 분리했습니다.

2019-07-25 09:15 UTC, wkdehdlr commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/data/Repository.kt
> +                callback.onTickerLoaded(tickers)
repository에서는 단순히 전달만 하기 위해 데이터가공을 넣지 않았습니다.

2019-07-25 09:22 UTC, wkdehdlr commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/ui/MainActivity.kt
> +                    val name = item.market.split("-")[1]
[3c5c93d](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/143/commits/3c5c93d84b723609bc2b5164a26dd43362aa097d) 수정했습니다

2019-07-25 09:23 UTC, zojae031 commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/data/Repository.kt
> +                callback.onTickerLoaded(tickers)
DataSource가 데이터 전달부분으로 알고있고
Repository에서 비즈니스로직을 가질 수 있는것으로 알고있긴 한데 참고부탁드립니당
# 수업 필기내용
#### Server (Remote) + DB,Pref,File,Cache (Local) = DataSource

- view는 데이터통신을 할 뿐 무슨 데이터가 오는지 알 필요가 없다.
- 중간에 관리해주는 역할 : Repository (로컬에서 오는가 리모트에서 오는가?)
- 레파지토리는 비즈니스로직을 가질 수 있다.
- 싱글톤으로 관리하기 때문에 변수를 가지거나 그러면 안된다.

2019-07-26 22:58 UTC, wkdehdlr commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/util/TextEditor.kt
> +    fun makeSignedChangeRate(param: Double) = String.format("%.2f", param * 100)
[82a242d](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/143/commits/82a242d0ac1855e4575ed30c6f258741664eaafa) 수정했습니다

2019-07-26 23:08 UTC, wkdehdlr commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/data/Repository.kt
> +                callback.onTickerLoaded(tickers)
[329a586](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/143/commits/329a586cf84cc805719c1905b9b360f749299ec9) repository를 object로 수정했습니다

2019-07-27 03:01 UTC, zojae031 commented
저도 한번 써볼게옇ㅎㅎㅎ...LGTM!

2019-07-27 06:02 UTC, zozero94 reviewed
추가 커밋에 관한 리뷰입니다.

2019-07-27 06:02 UTC, zozero94 commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/ui/CoinFragment.kt
> +class CoinFragment(val itemList: List<UpbitItem>) : Fragment() {
private로 설정하셔도 될것 같습니다

2019-07-27 06:02 UTC, zozero94 commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/ui/MainRvAdapter.kt
>  class MainRvAdapter(val context: Context, val itemList: List<UpbitItem>) :
private 로 설정하셔도 될것같습니다. 
또한 context정보를 인자로 넘기는건 좋지 않다고 들었습니다
parent.context로 사용해주세요!

2019-07-27 06:07 UTC, wkdehdlr commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/ui/MainRvAdapter.kt
>  class MainRvAdapter(val context: Context, val itemList: List<UpbitItem>) :
[d4a859e](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/143/commits/d4a859e51daaab0c3d49977ab5744bd900e7b89c) 수정했습니다. 사실 context를 왜 넘기면 안되는지 잘 모르는데 이유를 설명부탁드려도 될까요?

2019-07-27 06:08 UTC, wkdehdlr commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/ui/CoinFragment.kt
> +class CoinFragment(val itemList: List<UpbitItem>) : Fragment() {
[eda00cd](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/143/commits/eda00cd5958f1971576352ef3b1a2d953d793b89) 수정했습니다

2019-07-27 06:13 UTC, zojae031 commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/ui/MainRvAdapter.kt
>  class MainRvAdapter(val context: Context, val itemList: List<UpbitItem>) :
저번에 멘토님께서 말씀해주신것 처럼 내 액티비티를 다른 앱에서도 실행 할 수 있다고
들었습니다.  그때 의존성문제가 아닐까 싶습니다.
정확한건 멘토님께 저도 한번 들어봐야 할 것 같네요!
@sjjeong 
+ 그리고 앱 실행시 vie에 데이터가 늦게 그려지는 현상이 있습니다

2019-07-27 06:47 UTC, sjjeong commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/ui/MainRvAdapter.kt
>  class MainRvAdapter(val context: Context, val itemList: List<UpbitItem>) :
ViewHolder에서 itemView를 통해 context를 가져올 수 있어서 외부에서 넣어줄 필요가 없어요.

2019-07-27 07:00 UTC, wkdehdlr commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/ui/MainRvAdapter.kt
>  class MainRvAdapter(val context: Context, val itemList: List<UpbitItem>) :
만약 가져올 수 없는 상황이라면 넣어주는게 맞는건가요?
@sjjeong

2019-07-27 07:02 UTC, wkdehdlr commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/ui/MainRvAdapter.kt
>  class MainRvAdapter(val context: Context, val itemList: List<UpbitItem>) :
그리고 앱 실행시 vie에 데이터가 늦게 그려지는 현상이 있습니다
-> 원인파악이 좀 안되는데 retrofit 부분을 수정해야하나요??
@zojae031

2019-07-27 07:15 UTC, sjjeong commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/ui/MainRvAdapter.kt
>  class MainRvAdapter(val context: Context, val itemList: List<UpbitItem>) :
가져올수 없는 상황이 없습니다.
어떤상황이 있나요?

2019-07-27 08:14 UTC, zojae031 commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/ui/CoinFragment.kt
> +        val myRVAdapter = MainRvAdapter(UpbitList.getListFromName(marketName))
MainRvAdapter를 프래그먼트 생성함과 동시에 생성해주고
데이터를 받아왔을때 데이터 변화를 어댑터에 알려주면 될 것 같습니다.
```kotlin
private val adapter =  MainRvAdapter(UpbitList.getListFromName(marketName))
```

```kotlin
adapter.notifyDataSetChanged()
```

두가지 키워드 참고하셔서 적당한 위치에 넣어주시면 될 것 같습니다. 
해당 문제 처리해주면 잘 동작하는것 확인했어요

2019-07-27 09:14 UTC, sjjeong requested changes

2019-07-27 09:14 UTC, sjjeong commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/data/Repository.kt
> +                callback.onTickerLoaded(tickers)
가공은 Activity/Fragment쪽에서 하면 돼요

2019-07-27 09:14 UTC, sjjeong commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/model/UpbitList.kt
> +object UpbitList {
UpbitList를 제거 하는 방향으로 해보세요

2019-07-27 09:48 UTC, zojae031 commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/ui/CoinFragment.kt
> +        val myRVAdapter = MainRvAdapter(UpbitList.getListFromName(marketName))
문제는 데이터를 넣어주기만 하시고 어댑터에 알려주지 않았던 문제 같습니다.
원인 : 페이지를 넘기다가 3번째 페이지로 가면 1번째 프래그먼트가 재호출 되면서
들어간 데이터가 그려지게 됨 그래서 페이지를 넘기다 보면 안보이다가 화면에 나타나는 현상 발생

2019-07-28 02:55 UTC, wkdehdlr commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/ui/CoinFragment.kt
> +        val myRVAdapter = MainRvAdapter(UpbitList.getListFromName(marketName))
[5e80a81](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/143/commits/5e80a81259dbd7ac644f249a2bf659e2adfedbc2) 수정했습니다

2019-07-28 02:58 UTC, wkdehdlr commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/ui/MainRvAdapter.kt
>  class MainRvAdapter(val context: Context, val itemList: List<UpbitItem>) :
그런 상황이 있다는 건 아니고 혹여나 그런 상황이 있으면 넣어주는 게 맞는 건가라고 생각했습니다. 그런 상황이 없다면 고려하지 않아도 될 것 같습니다.

2019-07-28 08:10 UTC, wkdehdlr commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/model/UpbitList.kt
> +object UpbitList {
[446b168](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/143/commits/446b168467c1b83eb3560abd42baa8a31dbe2471) 수정했습니다

2019-07-28 10:23 UTC, zojae031 commented
고생하셨습니다!!

2019-07-31 10:10 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-08-01 06:10 UTC, zozero94 approved these changes
수고하셨습니다

2019-08-01 12:18 UTC, merged