HW-5 AAC 뷰모델 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #144
Opened 2019-07-24 13:53 UTC by Nanamare

2019-07-25 16:19 UTC, zion830 reviewed
수고 많으셨어요!!

2019-07-25 16:19 UTC, zion830 commented on Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/base/BaseViewModel.kt
> +    override fun onCleared() {
생략이 가능합니다~!

2019-07-25 16:19 UTC, zion830 commented on Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/ui/MainActivity.kt
> +        ViewModelProviders.of(this, MarketViewModel().createFactory()).get(MarketViewModel().javaClass)
`.get(MarketViewModel().javaClass)`을 `[MarketViewModel().javaClass]`로 대체할 수 있습니다.
이러한 문법을 syntax sugar라 부른다고 어떤 실력좋은 개발자 분이 알려주셨습니다 하핳

2019-07-26 11:40 UTC, Nanamare commented on Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/base/BaseViewModel.kt
> +    override fun onCleared() {
b5dda832685b467866ec0a9da653ddb4cd7dd85f
확장의 개념으로 추가해놨는데 결과적으로 사용하지 않아서 삭제하였습니다!

2019-07-26 11:40 UTC, Nanamare commented on Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/ui/MainActivity.kt
> +        ViewModelProviders.of(this, MarketViewModel().createFactory()).get(MarketViewModel().javaClass)
e49a6409ac922135e7ef5b407e3e6434dc89dfb7
실력 좋은 개발자분은 윤지님인 걸루 :)
수정하였습니다(부끄러워서 도망)

2019-07-27 02:51 UTC, zion830 commented
확인했습니다! request change를 안했어서 바로 mentor needed로 바꿨습니다

2019-07-27 03:01 UTC, sjjeong requested changes
close를 제거 하고 onCleared로 수정해주세요

2019-07-27 03:34 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-07-28 04:38 UTC, merged