HW-8 Koin 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #146
Opened 2019-07-28 01:13 UTC by BeokBeok

Koin 적용 하였습니다.

2019-07-31 06:15 UTC, NackUn requested changes

2019-07-31 06:15 UTC, NackUn commented on BeokBeok/app/src/main/java/com/architecturestudy/di/UpbitModules.kt
> +val dataSourceModules = module {
분리시키는 게 어떨까요?

2019-07-31 06:15 UTC, NackUn commented on BeokBeok/app/src/main/java/com/architecturestudy/data/upbit/source/UpbitRepository.kt
> +class UpbitRepository constructor(
constructor를 써준 이유가 뭔가요??

2019-07-31 06:15 UTC, NackUn commented on BeokBeok/app/src/main/java/com/architecturestudy/base/BaseFragment.kt
> +abstract class BaseFragment<VDB : ViewDataBinding, VM : BaseViewModel>(
ViewModel 을 공유하려고 추가해주신건가요?

2019-07-31 13:56 UTC, BeokBeok commented on BeokBeok/app/src/main/java/com/architecturestudy/base/BaseFragment.kt
> +abstract class BaseFragment<VDB : ViewDataBinding, VM : BaseViewModel>(
Fragment 에서 ViewModel 을 생성하고, 각 Fragment 들은 BaseFragment 를 상속받기 때문에 추가하였습니다.

2019-07-31 13:58 UTC, BeokBeok commented on BeokBeok/app/src/main/java/com/architecturestudy/data/upbit/source/UpbitRepository.kt
> +class UpbitRepository constructor(
8095b30063620f0e196b9a2b4c2dc42fcd6afde6
제거 하였습니다.

2019-07-31 14:00 UTC, BeokBeok commented on BeokBeok/app/src/main/java/com/architecturestudy/di/UpbitModules.kt
> +val dataSourceModules = module {
Upbit 관련 모듈들을 한 곳에 모아서 처리하였는데, 어떻게 분리시켜야할지 조언 부탁드립니다.

2019-08-01 05:43 UTC, NackUn commented on BeokBeok/app/src/main/java/com/architecturestudy/di/UpbitModules.kt
> +val dataSourceModules = module {
@BeokBeok upbit 관련 모듈들 중 LocalServiceModules, RemoteServiceModules 는 분리시켜서 재사용할 수 있게 만들면 어떨까요..?

2019-08-01 14:22 UTC, sjjeong requested changes

2019-08-01 14:22 UTC, sjjeong commented on BeokBeok/app/src/main/java/com/architecturestudy/di/UpbitModules.kt
> +fun getLocalServiceModules(context: Context) = module {
context를 받아서 넣는 방법 말고 applicationContext를 가져오는 방법이 있습니다.

2019-08-01 22:07 UTC, BeokBeok commented on BeokBeok/app/src/main/java/com/architecturestudy/di/UpbitModules.kt
> +fun getLocalServiceModules(context: Context) = module {
this@Application 을 전달하면 application context로 전달 되는 것으로 알고 있었습니다.

수정 하였습니다.
3117f10632a66051a93716b4f1147331fbd78bf4

2019-08-03 02:52 UTC, sjjeong requested changes

2019-08-03 02:52 UTC, sjjeong commented on BeokBeok/app/src/main/java/com/architecturestudy/di/UpbitModules.kt
> +fun getLocalServiceModules(context: Context) = module {
androidApplication()를 사용하시면 됩니다.

2019-08-03 03:04 UTC, BeokBeok commented on BeokBeok/app/src/main/java/com/architecturestudy/di/UpbitModules.kt
> +fun getLocalServiceModules(context: Context) = module {
적용하였습니다.
e5dcccfd4daf4e0d5b3b2642bd4328e81a195681

2019-08-03 03:08 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-08-03 03:31 UTC, NackUn approved these changes

2019-08-03 03:34 UTC, merged