Class03/zojae031
sjjeong/GoogryAndroidArchitecutreStudy pull request #147
Opened 2019-07-28 05:38 UTC by zojae031

기존에 MVP를 적용해두어서 바로 PR올리겠습니다.
이번주는 카카오 준비하러...총총

2019-07-28 07:32 UTC, zojae031 commented
패턴이 적용되는 과정은 저번 프로젝트에 묻어있기 때문에
clone해서 리뷰 부탁드립니다!

2019-08-08 11:09 UTC, wkdehdlr reviewed
늦어서 죄송합니다...
Rx나 DI, 스터디에서 주로 다루는 내용 외 부분들은 제가 능숙하지 못해서
리뷰에 어려운 부분이 있네요..수고하셨습니다

2019-08-08 11:09 UTC, wkdehdlr commented on zojae031/Project/app/src/main/java/study/architecture/ui/coinjob/CoinPresenter.kt
> +                            separateData.market
it으로 안받으신건 의도가 있는건가요?

2019-08-08 11:09 UTC, wkdehdlr commented on zojae031/Project/app/src/main/java/study/architecture/presentation/coinjob/adapter/CoinDataAdapter.kt
>  /**
findViewById 대신 코틀린 익스텐션을 사용해도 좋아보입니다.

2019-08-08 11:09 UTC, wkdehdlr commented on zojae031/Project/app/src/main/java/study/architecture/presentation/coinjob/CoinPresenter.kt
> +                repository.insertTicker(list)
Log.e("onErrorMarketList", e.message)
이 에러도 view를 통해 ui로 처리하면 어떨까 합니다
다른 부분들은 많이신경쓰신것 같은데 
그에 비하면 이 부분이 약하다고 느껴지네요

2019-08-09 05:03 UTC, zojae031 commented on zojae031/Project/app/src/main/java/study/architecture/ui/coinjob/CoinPresenter.kt
> +                            separateData.market
변수명이 확실해야 나중에 제 코드를 다시 봤을때 이해하기 좋아서 저는 저렇게 명시를 하는편입니다 ㅇ_ㅇ..

2019-08-09 05:11 UTC, zojae031 commented on zojae031/Project/app/src/main/java/study/architecture/presentation/coinjob/adapter/CoinDataAdapter.kt
>  /**
[41516bf](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/147/commits/41516bfa0c29448320c7c966db6b6d17b6ed5d4f)
수정본입니다!

2019-08-09 05:17 UTC, zojae031 commented on zojae031/Project/app/src/main/java/study/architecture/presentation/coinjob/CoinPresenter.kt
> +                repository.insertTicker(list)
[e236422](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/147/commits/e2364226cb17f12ff3361a4a06bf7119fc56d6aa)
수정본입니다!

2019-08-11 05:06 UTC, sjjeong requested changes

2019-08-11 05:06 UTC, sjjeong commented on zojae031/Project/app/src/main/java/study/architecture/presentation/coinjob/CoinPresenter.kt
> +                    repository.insertMarket(list)
insertMarket하는것은 repository에서 remote에서 가져올때 바로 넣어주면 좋습니다.

2019-08-11 05:18 UTC, sjjeong requested changes

2019-08-11 05:18 UTC, sjjeong commented on zojae031/Project/app/src/main/java/study/architecture/model/repository/Repository.kt
> +) : UpbitDataSource {
interface UpbitRepository
class UpbitRepositoryImpl: UpbitRepository

2019-08-11 05:18 UTC, sjjeong commented on zojae031/Project/app/src/main/java/study/architecture/model/dao/BaseDAO.kt
> +interface BaseDAO<T> {
Bao로 수정해주세요

2019-08-11 06:51 UTC, zojae031 commented on zojae031/Project/app/src/main/java/study/architecture/model/repository/Repository.kt
> +) : UpbitDataSource {
[
f1ef0ab](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/147/commits/f1ef0ab849834a2a2bdb0655f5ae40f8933e4683) 해당 커밋입니다

2019-08-11 06:52 UTC, zojae031 commented on zojae031/Project/app/src/main/java/study/architecture/model/dao/BaseDAO.kt
> +interface BaseDAO<T> {
[a8736b0](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/147/commits/a8736b0cfb5fa638c93247fd589b6774d8f1ed16) 커밋입니다.

2019-08-17 13:36 UTC, sjjeong requested changes

2019-08-17 13:36 UTC, sjjeong commented on zojae031/Project/app/src/main/java/study/architecture/data/repository/RepositoryImpl.kt
> +    private val localRemoteDataSource: UpbitLocalDataSource,
이름이 remoteRemote고 localRemote이고 조금 이상한거같아요

2019-08-18 12:16 UTC, zojae031 commented on zojae031/Project/app/src/main/java/study/architecture/data/repository/RepositoryImpl.kt
> +    private val localRemoteDataSource: UpbitLocalDataSource,
[135f47c](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/147/commits/135f47c76312a0a0be96969ba9826493b05b96d6) 변경 커밋입니다

2019-08-19 03:51 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-08-25 03:41 UTC, wkdehdlr approved these changes
고생하셨습니다

2019-08-25 05:18 UTC, merged