HW-8 Koin 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #148
Opened 2019-07-29 07:03 UTC by sport0102

2019-08-02 00:35 UTC, machine-human commented
5f40e4b
수정부분 확인 했습니다.
8주 동안 고생 많이 하셨습니다 :)

2019-08-02 00:35 UTC, brooks-o submitted a review, later dismissed

2019-08-03 02:49 UTC, sjjeong requested changes

2019-08-03 02:49 UTC, sjjeong commented on sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/data/source/local/UpbitDatabase.kt
> +                ?: Room.databaseBuilder(
제가 room을 안해보긴 했는데 이것도 koin으로 주입시켜줄수 있지 않을까요?

2019-08-03 02:49 UTC, sjjeong commented on sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/di/AppModule.kt
> +    viewModel { (fragmentActivity: FragmentActivity) -> ViewModelProviders.of(fragmentActivity)[MainSearchViewModel::class.java] }
아래 MainViewModel처럼 직접 생성자로 만들어도 돼요

2019-08-03 02:49 UTC, sjjeong commented on sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/di/RepositoryModule.kt
> +        UpbitDatabase(context)
context 대신에 androidApplication()를 사용해주세요

2019-08-03 07:06 UTC, sport0102 commented on sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/di/RepositoryModule.kt
> +        UpbitDatabase(context)
수정하였습니다!
cae5ec7

2019-08-03 07:07 UTC, sport0102 commented on sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/data/source/local/UpbitDatabase.kt
> +                ?: Room.databaseBuilder(
싱글턴 코드 삭제 했습니다. 코인처리하는 내부에서 빌드하도록 만들었습니다
27518d4

2019-08-03 07:09 UTC, sport0102 commented on sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/di/AppModule.kt
> +    viewModel { (fragmentActivity: FragmentActivity) -> ViewModelProviders.of(fragmentActivity)[MainSearchViewModel::class.java] }
음 이부분을 이렇게 처리한 이유는, 저게 fragmentActivity의 뷰모델이 만들어져야하는데, fragment에서 MainSearchViewModel() 이런식으로 만들어놓은걸 사용하면 fragment의 뷰모델이 만들어지더라고요... 저 뷰모델을 mainTickerFragment하구 mainSearchFragment하고 공유해야하거든요... 그래서 억지로 저렇게 만들어 놓았는데 다른 방법이 있을까요?

2019-08-04 06:23 UTC, sjjeong commented on sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/di/AppModule.kt
> +    viewModel { (fragmentActivity: FragmentActivity) -> ViewModelProviders.of(fragmentActivity)[MainSearchViewModel::class.java] }
Koin에 sharedViewModel()로 가져오면 돼요

2019-08-04 06:24 UTC, sjjeong commented on sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/di/RepositoryModule.kt
> +        UpbitDatabase(context)
Koin module에 보면 androidApplication()함수가 있어서 따로 외부에서 받지 않아도 사용할 수 있어요

2019-08-05 05:16 UTC, sport0102 commented on sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/di/RepositoryModule.kt
> +        UpbitDatabase(context)
아아 다시 수정하였습니다. 말을 한번에 이해하지 못해서 죄송합니다.
32e7128

2019-08-05 05:33 UTC, sport0102 commented on sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/di/AppModule.kt
> +    viewModel { (fragmentActivity: FragmentActivity) -> ViewModelProviders.of(fragmentActivity)[MainSearchViewModel::class.java] }
아하! 이해했습니다. 한번에 이해 못해서 죄송합니다. 처음 생성하는 곳에서 sharedViewModel로 만들면 내부에서 알아서 activity수준의 viewModelStoreOwner를 가지네요.... 다음에는 코드를 내부까지 까보면서 더 공부하겠습니다. 중간에 MainActivity에서 viewModel 생성시점의 문제인지 알고 코드 순서를 바꾼게 있습니다. 이건 무시하셔도 될것 같습니다. 
7370381

2019-08-05 13:36 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-08-07 04:58 UTC, merged