HW-8 Koin 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #156
Opened 2019-07-31 15:39 UTC by machine-human

2019-08-01 09:14 UTC, sport0102 requested changes
수정내용 확인해주세요~

2019-08-01 09:14 UTC, sport0102 commented on machine-human/AndroidArchitectureStudy/build.gradle
> +        koin_version = '2.0.1'
koin 버전만 따로 빼시지 말고, 다른 버전도 빼셔서 관리하는게 어떨까요? 물론 저는 안하고 있습니다만.... ㅎㅎ 통일성을 위해서!

2019-08-01 09:14 UTC, sport0102 commented on machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/di/NetWorkModule.kt
> +val tickerBaseUrl = "https://api.upbit.com/"
url을 koin 시작할 때 받는게 어떨까요?

2019-08-02 11:58 UTC, machine-human commented on machine-human/AndroidArchitectureStudy/build.gradle
> +        koin_version = '2.0.1'
감사합니다. 수정 완료했습니다 :)

1703a8b

2019-08-02 11:59 UTC, machine-human commented on machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/di/NetWorkModule.kt
> +val tickerBaseUrl = "https://api.upbit.com/"
오 이렇게 외부에서 url을 입력하니까 더욱 시각적 및 관리가 편할거 같습니다
감사합니다!!

a5df1a1

2019-08-03 06:51 UTC, sport0102 submitted a review, later dismissed
LGMT!

2019-08-04 06:28 UTC, sjjeong requested changes

2019-08-04 06:28 UTC, sjjeong commented on machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/di/RepositoryModule.kt
> +    single { TickerRepository(get()) }
Class 가 아닌 interface형식으로 넣어야 합니다.
뷰모델도 동일하게 인터페이스로 받아주셔야해요

2019-08-06 16:08 UTC, machine-human commented on machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/di/RepositoryModule.kt
> +    single { TickerRepository(get()) }
tickerRepositoryModule Interface 형식으로 넣기 적용 af7cb56
ViewModel 인자 타입 ClassType -> InterfaceType으로 변경 적용 474b8f7

완료했습니다. 고생하셨습니다 :)

2019-08-07 03:38 UTC, sjjeong requested changes

2019-08-07 03:38 UTC, sjjeong commented on machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/view/activity/main/MainViewModel.kt
> +    private val tickerRepository: BaseDataSource
BaseRepository를 넣어야하는거 아닌가요?

2019-08-07 04:25 UTC, machine-human commented on machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/view/activity/main/MainViewModel.kt
> +    private val tickerRepository: BaseDataSource
앗! 인터페이스에만 신경 쓰다가 놓쳤습니다. 
마지막까지 섬세히 봐주셔서 감사합니다 :)

69201b8

2019-08-07 13:22 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-08-07 14:00 UTC, merged