HW-6 Koin 적용하기
sjjeong/GoogryAndroidArchitecutreStudy pull request #157
Opened 2019-07-31 15:40 UTC by zion830

2019-08-01 12:18 UTC, Nanamare commented on zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/showcoin/view/MainActivity.kt
> +    private val viewModel: CoinViewModel by viewModel { parametersOf(this@MainActivity) }
private val viewModel by viewModel<CoinViewModel>()
요런식으로도 쓸 수 있을 것 같네유!

2019-08-02 14:27 UTC, Nanamare submitted a review, later dismissed
마지막까지 최고입니다 :)

2019-08-03 02:40 UTC, sjjeong requested changes

2019-08-03 02:40 UTC, sjjeong commented on zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/di/AppModule.kt
> +    viewModel { (fragmentActivity: FragmentActivity) ->
ViewModelProviders를 사용하지 않고 
```kotlin
CoinViewModel(get())
```
만 넣어도 koin 내부적으로 ViewModelProviders로 생성해줘요

2019-08-03 02:40 UTC, sjjeong commented on zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/di/AppModule.kt
> +    single { CoinRepository(get()) }
```kotlin
single<CoinDataSource> { CoinRepository(get() }
```
로 하셔야해요

그리고 ViewModel에서는 class type으로 받는게 아니라 Interface로 받아야해요
```kotlin
class CoinViewModel(private val repository: CoinDataSource) : ViewModel() {
```

2019-08-06 10:38 UTC, zion830 commented on zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/di/AppModule.kt
> +    viewModel { (fragmentActivity: FragmentActivity) ->
5b01d10
수정했습니다~

2019-08-06 10:38 UTC, zion830 commented on zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/di/AppModule.kt
> +    single { CoinRepository(get()) }
1a6b956
수정했습니다~

2019-08-07 03:41 UTC, sjjeong requested changes

2019-08-07 03:41 UTC, sjjeong commented on zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/showcoin/view/MainActivity.kt
> +    private val viewModel: CoinViewModel by viewModel { parametersOf(this@MainActivity) }
MainActivity로 넘겨주는 파라미터가 필요한가요?

2019-08-07 21:48 UTC, zion830 commented on zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/showcoin/view/MainActivity.kt
> +    private val viewModel: CoinViewModel by viewModel { parametersOf(this@MainActivity) }
없어도 되네요.. 삭제햇습니다! 
eaac536

2019-08-09 04:51 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋
고생했어요~

2019-08-09 04:56 UTC, merged