WIP : 1주차 과제
sjjeong/GoogryAndroidArchitecutreStudy pull request #16
Opened 2019-04-29 16:04 UTC by Hoyuo

2019-05-01 17:16 UTC, namjackson commented on hoyuo/MyApplication/app/src/main/java/me/hoyuo/myapplication/model/upbit/Market.kt
> +    val english_name: String,
변수명을 카멜표기법으로 통일하면 좋을거같아요!

2019-05-01 17:16 UTC, namjackson commented on hoyuo/MyApplication/app/src/main/java/me/hoyuo/myapplication/ui/MainActivity.kt
> +        }
람다식( .filter{}.map{})을 쓰면 조금더 깔끔할수 있을거 같아요!

2019-05-02 04:43 UTC, GeoN5 submitted a review, later dismissed
아직 Rx나 이런기술을 잘 몰라서 제가 리뷰할 만한 코드가 아닌거 같네요ㅠㅠ

2019-05-02 14:28 UTC, Hoyuo commented on hoyuo/MyApplication/app/src/main/java/me/hoyuo/myapplication/ui/MainActivity.kt
> +        }
좋은 방법 감사합니다

2019-05-02 15:15 UTC, namjackson submitted a review, later dismissed

2019-05-03 00:25 UTC, GeoN5 submitted a review, later dismissed

2019-05-03 16:50 UTC, sjjeong requested changes

2019-05-03 16:50 UTC, sjjeong commented on hoyuo/MyApplication/app/src/main/java/me/hoyuo/myapplication/ui/adapter/viewholder/CoinItem.kt
> +class CoinItem(parent: ViewGroup) : AndroidExtensionsViewHolder(
class명을 보고 ViewHolder인지 알 수 없습니다.
`CoinItemViewHolder`로 수정해주세요.

2019-05-03 16:50 UTC, sjjeong commented on hoyuo/MyApplication/app/src/main/java/me/hoyuo/myapplication/ui/adapter/ItemAdapter.kt
> +    private var listener: ItemClickListener? = null
higher-order function으로 간단하게 만들 수 있습니다.

2019-05-03 16:50 UTC, sjjeong commented on hoyuo/MyApplication/app/src/main/java/me/hoyuo/myapplication/ui/adapter/ItemAdapter.kt
> +    private var itemList = CopyOnWriteArrayList<Ticker>()
한번 set하고 그 뒤에 변하지 않기 때문에 val로 해주세요.

2019-05-03 16:50 UTC, sjjeong commented on hoyuo/MyApplication/app/src/main/java/me/hoyuo/myapplication/ui/CoinDetailPage.kt
> +class CoinDetailPage : AppCompatActivity() {
뒤에 Activity를 붙여주세요.

2019-05-04 09:11 UTC, sjjeong approved these changes

2019-05-05 03:39 UTC, merged