HW-8 Koin 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #160
Opened 2019-08-01 09:20 UTC by NackUn

2019-08-01 09:30 UTC, BeokBeok requested changes

2019-08-01 09:30 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/ui/ticker/TickerFragment.kt
> +    private val vm: TickerViewModel by viewModel()
뷰에서 뷰모델을 생성하기 때문에,
BaseFragment에서 뷰모델 관련 변수를 만드신 후, 오버라이딩하셔서 사용하시면 좋습니다.

2019-08-02 15:19 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/ui/ticker/TickerFragment.kt
> +    private val vm: TickerViewModel by viewModel()
c510f59
이렇게 말씀이십니까??

2019-08-03 00:11 UTC, BeokBeok submitted a review, later dismissed
LGTM:ok_hand:
두 달 동안 고생 많으셨습니다!

2019-08-04 06:29 UTC, sjjeong requested changes

2019-08-04 06:29 UTC, sjjeong commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/di/RemoteModule.kt
> +    single { RemoteDataSource(get()) }
single<DataSource>{}로해서 인터페이스 형식으로 넘겨주게 해주세요

2019-08-06 02:22 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/di/RemoteModule.kt
> +    single { RemoteDataSource(get()) }
이렇게 말씀이신가요?
e7cdf94

2019-08-07 03:42 UTC, sjjeong requested changes

2019-08-07 03:42 UTC, sjjeong commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/di/RepositoryModule.kt
> +    single { Repository(get()) }
DataSource만 수정하시다니..
이것도 같이 수정해주세요

2019-08-08 01:52 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/di/RepositoryModule.kt
> +    single { Repository(get()) }
변경했습니다.
9a4373e 
7c048f6

2019-08-09 04:53 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-08-10 04:39 UTC, merged