HW-3 MVP
sjjeong/GoogryAndroidArchitecutreStudy pull request #161
Opened 2019-08-02 01:25 UTC by wkdehdlr

큰 틀만 우선 한번 잡아봤습니다. 계속 수정해서 반영하겠습니다.

2019-08-02 08:26 UTC, zozero94 reviewed
구조만 잡아둔 PR이라고 하셔서 그런지 패키지 구조가 햇갈립니다 ㅠ_ㅠ
어떤 클래스는 Adatper를 inner class로 가지고있고 어떤곳은 분리되어있고 '_'

2019-08-02 08:26 UTC, zozero94 commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/tasks/MainActivity.kt
> +        upbitPresenter = UpbitPresenter(Repository, upbitFragment)
Activity도 하나의 View이고
Fragment도 하나의 View로 알고 있습니다.
View랑 Presenter는 1:1매칭이 되야 하는것으로 알고 있는데 위 코드 같은경우는
Activity에서 프레젠터를 생성해 Fragment를 인자로 넘겨주는
**Presenter가 2개의 View를 알고 있는** 코드로 보이네요

2019-08-02 08:26 UTC, zozero94 commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/tasks/UpbitPresenter.kt
> +                    .map { it.market }
```kotlin
.joinToString(",") { it.market }
```
형태로 바꿀 수 있을것 같습니다.

2019-08-02 08:26 UTC, zozero94 commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/tasks/UpbitPresenter.kt
> +    private fun procesUpbit(tickerList: MutableList<UpbitItem>) {
함수명 신경써주세요

2019-08-02 08:26 UTC, zozero94 commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/tasks/UpbitFragment.kt
> +                val name = itemView.findViewById<TextView>(R.id.name)
bind 함수 밖으로 빼내야 할 것 같습니다. 
ViewHolder 패턴을 사용하는 이유가 inflate와 findViewById 의 오버헤드를 줄이기 위해서로 알고 있는데
이렇게되면 **아이템 하나 연결할때마다 계속해서 findViewById를 호출**하여 본질을 잃게되는 것 같습니다.

2019-08-02 08:26 UTC, zojae031 commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/tasks/UpbitFragment.kt
> +                    "RISE" -> signedChangeRate.setTextColor(Color.BLUE)
하드코딩 보다 좀더 보기 쉽게 정규화 하면 좋을듯 합니다.
1. Enum
2. const val

2019-08-02 08:26 UTC, zojae031 commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/tasks/UpbitFragment.kt
> +        coinRecyclerView.adapter = rVAdapter
```kotlin
CoinRecyclerView.apply {
            adapter = rVAdapter
            layoutManager =LinearLayoutManager(context!!)
            setHasFixedSize(true)
        }
```
이렇게 하시면 조금 더 리사이클러뷰에 해당하는 작업들을 보기 쉬울 것 같습니다.

2019-08-02 08:26 UTC, zojae031 commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/tasks/UpbitPresenter.kt
> +                tickers.forEach {
이부분 Log에서 currentThread찍어보면 메인에서 동작하고 있는데 Repository의
ioThread에서 가공해서 주면 좋을 것 같아요

2019-08-02 08:26 UTC, zojae031 commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/tasks/UpbitFragment.kt
> +class UpbitFragment : Fragment(), UpbitContract.View {
UpbitFragment와 CoinFragment의 구분이 모호하네요
같은 View를 inflate하는데 어떤 구조인지 파악이 잘 안됩니다
설명 한번만 부탁드릴게요

2019-08-04 12:36 UTC, wkdehdlr commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/tasks/UpbitPresenter.kt
> +                    .map { it.market }
[e936c60](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/161/commits/e936c60c060dfef651e7cc9cd5674e700f3a3c1b) 수정했습니다

2019-08-04 12:38 UTC, wkdehdlr commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/tasks/UpbitPresenter.kt
> +    private fun procesUpbit(tickerList: MutableList<UpbitItem>) {
[9ec6b9d](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/161/commits/9ec6b9db5b8a2a1f0c9cfaaf0fd5c175a128e7b7) 수정했습니다

2019-08-04 13:08 UTC, wkdehdlr commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/tasks/UpbitFragment.kt
> +                val name = itemView.findViewById<TextView>(R.id.name)
[f7a259e](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/161/commits/f7a259eceefe5f9189648c97943dca20094580ca) 수정했습니다

2019-08-04 13:47 UTC, wkdehdlr commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/tasks/MainActivity.kt
> +        upbitPresenter = UpbitPresenter(Repository, upbitFragment)
[ea0a4b4](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/161/commits/ea0a4b47bb42b55f399c889263f10650acf142a2) 수정했습니다

2019-08-04 13:48 UTC, wkdehdlr commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/tasks/UpbitFragment.kt
> +class UpbitFragment : Fragment(), UpbitContract.View {
[ea0a4b4](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/161/commits/ea0a4b47bb42b55f399c889263f10650acf142a2) 해당 커밋에서 CoinFragment 삭제했습니다

2019-08-06 08:14 UTC, zozero94 reviewed
추가 리뷰입니다.

2019-08-06 08:14 UTC, zojae031 commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/tasks/MainRvAdapter.kt
> +package kr.schoolsharing.coinhelper.tasks
해당 클래스 사용되고 있지 않습니다

2019-08-06 08:14 UTC, zojae031 commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/tasks/UpbitFragment.kt
> +            val bundle = Bundle()
```
Class layout
Generally, the contents of a class is sorted in the following order:

Property declarations and initializer blocks
Secondary constructors
Method declarations
Companion object
```

kotlin coding convention에 따르면 companion object는 아래 위치해야 한다고 합니당
[convention](https://kotlinlang.org/docs/reference/coding-conventions.html)

2019-08-06 08:14 UTC, zojae031 commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/tasks/UpbitFragment.kt
> +class UpbitFragment : Fragment(), UpbitContract.View {
해당 UpbitFragment를 singleton처럼 구현하려 하신다면
생성자를 private로 만들어야 하는 것으로 알고있습니다.
또한 newInstance부분에 Log를 찍어보면 싱글톤처럼 하나의 객체를 생성해서 사용하는 것이 아니라
계속해서 새로운 객체를 생성 하는것을 확인 할 수 있습니다.

2019-08-06 08:14 UTC, zojae031 commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/util/AppCompatActivityExt.kt
> +fun AppCompatActivity.replaceFragmentInActivity(fragment: Fragment, @IdRes frameId: Int) {
해당 함수는 무엇을 하는 함수인가요?? 처음보는 형태라 잘 모르겠습니다

2019-08-08 11:23 UTC, wkdehdlr commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/tasks/UpbitFragment.kt
> +            val bundle = Bundle()
[d17fd71](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/161/commits/d17fd71266b4062ecb45dc2fa6097df9fe53b767) 수정했습니다

2019-08-08 11:29 UTC, wkdehdlr commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/util/AppCompatActivityExt.kt
> +fun AppCompatActivity.replaceFragmentInActivity(fragment: Fragment, @IdRes frameId: Int) {
[f52912c](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/161/commits/f52912cdd9abadefdc84b16c9b27151dc4d7899d) 프래그먼트 관리 찾아보다가 추가했던건데 미처 삭제하지 못했네요. 삭제했습니다

2019-08-08 11:30 UTC, wkdehdlr commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/tasks/MainRvAdapter.kt
> +package kr.schoolsharing.coinhelper.tasks
[2c24825](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/161/commits/2c2482564bbb7ede1d40c4fcc186e91341ae7c9a) 삭제했습니다

2019-08-08 11:33 UTC, wkdehdlr commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/tasks/UpbitFragment.kt
> +        coinRecyclerView.adapter = rVAdapter
[4b17316](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/161/commits/4b173165d0cdb9dee04da20e0f846f7943c51741) 수정했습니다

2019-08-08 11:40 UTC, wkdehdlr commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/tasks/UpbitFragment.kt
> +                    "RISE" -> signedChangeRate.setTextColor(Color.BLUE)
[61c40e1](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/161/commits/61c40e1cfc3da133aa0e47f5ff9d373eae76cbc8) 수정했습니다

2019-08-08 11:40 UTC, wkdehdlr commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/tasks/UpbitPresenter.kt
> +                tickers.forEach {
쓰레드를 달리 작업하려면 Async를 사용하나요?

2019-08-08 11:46 UTC, wkdehdlr commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/tasks/UpbitFragment.kt
> +class UpbitFragment : Fragment(), UpbitContract.View {
[7358b8b](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/161/commits/7358b8b3d9a3891b644b1dcbc61af7c76d78665d) 생성자에 private을 추가했습니다. 생성자에 prviate을 추가해야 비로소 companion object로 싱글톤이 구현되는건가요?

2019-08-09 05:31 UTC, zojae031 commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/tasks/UpbitPresenter.kt
> +                tickers.forEach {
AsyncTask를 사용하셔도 되고
Thread, rx, 코루틴 등등 여러가지 방법이 있겠지요
저같은경우는 해당부분을 해결하기 위해 rx를 사용했습니당

2019-08-09 05:37 UTC, zojae031 commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/tasks/UpbitFragment.kt
> +class UpbitFragment : Fragment(), UpbitContract.View {
[싱글톤](https://jeong-pro.tistory.com/86)
위 블로그 포스트에도 보듯이 ``싱글톤패턴`` 이라하면 **최초 한번만 메모리 할당**
이라 되어있는데 
 private constructor로 막아놓고 
내부에서 companion object로 생성해주는 작업을 하지 않으면 
내부에서 생성한다 할지라도 다른 클래스에서 해당 객체를 생성 할 수 있겠지요

2019-08-09 05:40 UTC, zojae031 commented
당장 금요일이라 추가리뷰는 다음 과제에 진행하겠습니다.
comment에 대한 답변은 모두 남겨두었습니다.

2019-08-11 05:22 UTC, sjjeong requested changes

2019-08-11 05:22 UTC, sjjeong commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/tasks/UpbitFragment.kt
> +class UpbitFragment private constructor() : Fragment(), UpbitContract.View {
private constructor를 제거해주세요

2019-08-11 06:19 UTC, wkdehdlr commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/tasks/UpbitFragment.kt
> +class UpbitFragment private constructor() : Fragment(), UpbitContract.View {
[89097cc](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/161/commits/89097cc50de2b5ae5f17cc237084ecba5f540086) 수정했습니다

2019-08-15 09:17 UTC, wkdehdlr commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/tasks/UpbitPresenter.kt
> +                tickers.forEach {
이 부분은 Rx를 공부한 후에 적용해보도록 하겠습니다

2019-08-16 07:26 UTC, zojae031 commented
수고하셨습니다.

2019-08-23 10:52 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-08-25 05:17 UTC, zozero94 approved these changes

2019-08-25 05:21 UTC, merged