HW-3 코인헬퍼 : Contract 를 이용해 MVP 적용하기
sjjeong/GoogryAndroidArchitecutreStudy pull request #162
Opened 2019-08-02 10:58 UTC by preludezdev

- MarketContract 인터페이스를 만들고 내부에 View, Presenter 인터페이스를 생성했습니다.

- MarketPresenter 클래스를 생성했습니다.

- MarketFragment 를 View 와 Presenter 로 분리하고 Presenter 부분을 MarketPresenter 로 옮겼습니다.

- MarketFragment 는 MarketContract.View 를 상속받고, 직접 MarketPresenter 객체를 생성해 프로퍼티로 가지고 있습니다.

- MarketPresenter 는 MarketContract.Presenter 를 상속받고, MarketContract.View 를 상속받는 클래스를 프로퍼티로 가지고 있습니다.

피드백 부탁드립니다 : )

2019-08-04 06:19 UTC, dlwls5201 reviewed
Presenter의 loadData에서는 Repo 두개를 조합하여 사용하고 있습니다. 모델을 설계할 때 Repository, DataSource 외에도 Repo의 조합을 관리하는 Usecase 즉  domain 을 중간에 하나 더 둘 수 있습니다. 이 부분은 참고만 해주시고 CoinHelper에 적용하는게 좋을 지는 석준님의 의견을 한번 물어봐야겠습니다 :)

2019-08-04 06:19 UTC, dlwls5201 commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/MarketFragment.kt
>          var keyMarket = arguments?.get("KEY_MARKET") as String
getString을 사용해 주시고 String이 null 일 때 예외처리를 해주면 더 좋을 것 같습니다.

2019-08-04 06:19 UTC, dlwls5201 commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/MarketPresenter.kt
> +        var market = ticker.market.split("-")[1]
전체적으로 var 되어 있는 변수를 val로 변환해 줘도 될 것 같습니다.

2019-08-04 06:19 UTC, dlwls5201 commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/MarketContract.kt
> +        fun convertTickerIntoCoin(ticker: CoinTickerResponse): Coin
@sjjeong 
convertTickerIntoCoin은 Presenter 내에서만 쓰이는 private 한 함수인데 이부분도 contract에 선언해 주는게 좋은걸까요??

2019-08-04 06:19 UTC, dlwls5201 commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/MarketContract.kt
> +        fun showTickerList(data: List<Coin>)
이건 개인적인 의견으로 Splash에서 데이터를 미리 받아오는 부분을 제거했으니 showProgress(), hideProgress() 를 만들어 데이터를 받아오는 중일 때를 사용자에게 표시해주는건 어떨까 생각이 듭니다 :)

2019-08-04 13:41 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/MarketFragment.kt
>          var keyMarket = arguments?.get("KEY_MARKET") as String
피드백 반영했습니다

commit : 501db9c

2019-08-04 13:41 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/MarketPresenter.kt
> +        var market = ticker.market.split("-")[1]
피드백 반영했습니다

commit : 3ff1da7

2019-08-04 13:44 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/MarketContract.kt
> +        fun convertTickerIntoCoin(ticker: CoinTickerResponse): Coin
저도 이 부분 고민했다가 Contract 가 다 가지고 있는걸로 짰는데 진성님이 말해주신대로 private 함수로 바꿨습니다. 그런데 Contract 에 있는 함수들이 원래 다른데에선 안쓰이는 private 느낌이지 않나요? 다른 화면에서 이 Contract 를 쓰진 않을 것 같은데... 헷갈리네요.

commit : 8eb6879

2019-08-04 13:45 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/MarketContract.kt
> +        fun showTickerList(data: List<Coin>)
MarketFragment 에 프로그래스 바 추가하고 Contract 에 관련 함수 추가하여 구현했습니다

commit : d650213

2019-08-04 13:50 UTC, preludezdev commented
모델에서 Domain Layer 를 추가하는 부분은 말씀해주신대로 관련 레퍼런스 찾아보면서 공부한 뒤 적용해보겠습니다. 잠깐 찾아보니까 왠지 그 유명한 Clean Architecture 와 연관되는 것처럼 보이기도 하네요

2019-08-05 14:42 UTC, dlwls5201 reviewed
Util의 천 단위로 끊어주는 함수를 재귀 함수로 잘 만들어 주셨는데 DecimalFormat 을 사용해서 더 간단하게 만들 수도 있습니다. 이건 개인 취향인지라 Comment로만 남기겠습니다. 고생하셨습니다.

2019-08-06 05:41 UTC, dlwls5201 submitted a review, later dismissed
바로 Approve 적용하겠습니다.

2019-08-11 05:17 UTC, improve777 commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/MarketPresenter.kt
> +            ticker.accTradePriceH > 1_000 ->
1_000, 100_000 와 같은 숫자는 상수화 시켜주는게 좋을것 같아요!

2019-08-11 05:17 UTC, improve777 commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/MarketPresenter.kt
> +                                    marketFragmentView.setTickerData(coinTickerResponse.map(::convertTickerIntoCoin))
원하는 데이터는 tickerList 인데 마켓 정보를 받고 받은 정보로 tickerList 를 받아서 프레젠터에서 가공하게 됩니다.
레포지토리에서 해야 할 일을 프레젠터에서도 하게 되는 것 같아요

2019-08-11 05:17 UTC, improve777 commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/MarketPresenter.kt
> +    private fun convertTickerIntoCoin(ticker: CoinTickerResponse): Coin {
데이터 클래스 내부 or Mapper 클래스의 메서드로 만드는게 어떨까요?
중복코드가 발생할 수 있을 것 같아요

2019-08-11 05:33 UTC, sjjeong requested changes

2019-08-11 05:33 UTC, sjjeong commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/MarketContract.kt
> +        fun setTickerData(data: List<Coin>)
set보다는 show가 좋아보입니다.

2019-08-11 05:33 UTC, sjjeong commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/MarketFragment.kt
> +        fun newInstance(market: String) = MarketFragment().apply {
companion object는 클래스 맨 아래에 있어야합니다.

2019-08-11 05:33 UTC, sjjeong commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/MarketFragment.kt
> +        val keyMarket = arguments?.getString("KEY_MARKET")
onCreateView에 있는 코드들을 onActivityCreated로 옮겨주세요

2019-08-11 05:33 UTC, sjjeong commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/MarketFragment.kt
> +        val keyMarket = arguments?.getString("KEY_MARKET")
KEY_MARKET을 상수로 빼주세요

2019-08-11 05:33 UTC, sjjeong commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/MarketFragment.kt
> +        val keyMarket = arguments?.getString("KEY_MARKET")
44번째 줄에 있는 layoutmanager set은 xml에서도 가능합니다.

2019-08-11 05:33 UTC, sjjeong commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/MarketFragment.kt
>      private val repository = CoinsRepository.getInstance(
repository를 Fragment가 들고 있을 필요가 없습니다 생성할때 바로 넣어주세요

2019-08-19 04:58 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/MarketFragment.kt
> +        val keyMarket = arguments?.getString("KEY_MARKET")
- KEY_MARKET 을 상수로 뺐습니다
- LayoutManager 을 xml 에서 set 했습니다.

commit :  6cf8128, 20e7711

2019-08-19 04:58 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/MarketFragment.kt
> +        val keyMarket = arguments?.getString("KEY_MARKET")
해당 코드를 onActivityCreated() 로 이동했습니다

commit : af3e5a1

2019-08-19 04:59 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/MarketFragment.kt
>      private val repository = CoinsRepository.getInstance(
repositry 생성과 동시에 Presenter 에 주입하게끔 변경했습니다

commit : ff556f5

2019-08-19 04:59 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/MarketFragment.kt
> +        fun newInstance(market: String) = MarketFragment().apply {
companion object 를 클래스 제일 하단으로 옮겼습니다

commit : 098fd17

2019-08-19 05:00 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/MarketContract.kt
> +        fun setTickerData(data: List<Coin>)
메소드 이름 변경했습니다

commit : 4239aa7

2019-08-19 05:06 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/MarketPresenter.kt
> +            ticker.accTradePriceH > 1_000 ->
해당 숫자들을 상수화 했습니다. 그런데 해당 함수 보면 1_000, 100_000 같은 숫자 말고 1000, 100, 1000000 이런 숫자들도 있는데 이런 숫자들도 다 상수화 해줘야되나요? 아니면 언더바를 넣은 특정 숫자만 상수화를 해줘야 되나요??

commit : 063ba04 ( CoinTickerResponse 클래스에 있습니다)

2019-08-19 05:06 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/MarketPresenter.kt
> +    private fun convertTickerIntoCoin(ticker: CoinTickerResponse): Coin {
convertTickerIntoCoin() 메소드를 data class 인 CoinTickerResponse 클래스 안으로 옮겼습니다

commit : 063ba04

2019-08-19 05:09 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/MarketPresenter.kt
> +                                    marketFragmentView.setTickerData(coinTickerResponse.map(::convertTickerIntoCoin))
그러면 마켓정보를 받는 코드를 레포지토리에서 tickerList 를 가져오는 메소드 안으로 옮기면 되나요?? 그런데 이렇게 하면 마켓 정보를 받는 함수는 레포지토리에서 밖에 안쓰이게 되는데 그래도 구조적으로 상관없나요? 뭐 나중에 쓰일지도 모르니 놔둬도 상관없을거 같긴 한데... 조금 헷갈리네요ㅠ

2019-08-19 07:27 UTC, improve777 commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/MarketPresenter.kt
> +            ticker.accTradePriceH > 1_000 ->
언더바로 가독성만 향상시키기 위함으로 알고 있습니다
동일하게 상수로 사용하셔도 되요!

2019-08-19 07:35 UTC, improve777 commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/MarketPresenter.kt
> +                                    marketFragmentView.setTickerData(coinTickerResponse.map(::convertTickerIntoCoin))
네 프레젠터가 필요한 데이터만 레포지토리에서 받아서 사용하는 것이기 때문에 괜찮습니다

2019-08-19 09:29 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/MarketPresenter.kt
> +            ticker.accTradePriceH > 1_000 ->
상수로 하라(상수화)는 뜻이 정확히 뭘 의미하는지 모르겠어요ㅠㅠ

![image](https://user-images.githubusercontent.com/41214420/63254801-51dcc900-c2af-11e9-8ed4-a50c4700aa2b.png)

상수화가 제가 한 것 처럼 해당 숫자를 val 변수로 만들고 코드 짤 때 숫자 대신에 해당 변수를 넣어서 하라는 의미신가요? 숫자 한 두개면 괜찮을 것 같은데 지금 제가 짠 코드에 들어있는 숫자가 100, 1000, 1000000, 100000, 10000000  처럼 다양한데 이 숫자 전부를 변수로 만들어서 코딩하게 되면 오히려 그냥 숫자로 적을 때보다 가독성이 떨어질 것 같아서 질문드려요

2019-08-19 11:58 UTC, improve777 commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/MarketPresenter.kt
> +            ticker.accTradePriceH > 1_000 ->
음.. when 내부에 조건이랑 아래 나누는 공식이랑 같은 수로 나눈다고 생각했는데 제가 주의깊게 보지 못 했네요
제가 생각했던건 아래처럼 하는 거 였습니다
[코드](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/blob/class01%2Fsabgilhun/sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/ext/TextViewExt.kt)

2019-08-19 14:51 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/MarketPresenter.kt
> +                                    marketFragmentView.setTickerData(coinTickerResponse.map(::convertTickerIntoCoin))
얘기해주신대로 해당 코드를 레포지토리 내 getCoinTickers() 메소드 안으로 옮겼습니다

commit : 5f597d7

2019-08-19 14:53 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/MarketPresenter.kt
> +            ticker.accTradePriceH > 1_000 ->
아 대연씨 코드보고 무슨 뜻인지 확실히 이해했습니다 
코드 보면서 비슷하게 개선해봤습니다

commit : d95776a

2019-08-20 06:11 UTC, ddaeyeonkim approved these changes
LGTM 👍👍👍

2019-08-20 08:26 UTC, dlwls5201 approved these changes
LGTM 👍👍👍

2019-08-20 13:10 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-08-20 14:01 UTC, merged