과제 1주차
sjjeong/GoogryAndroidArchitecutreStudy pull request #17
Opened 2019-04-29 16:34 UTC by GongSulMin

2019-04-30 08:32 UTC, improve777 commented on gongsulmin/StudyGong/app/src/main/java/my/gong/studygong/data/model/response/UpbitMarketResponse.kt
> +        @SerializedName("korean_name") val korean_name: String,
다른 곳과 변수명  표기법을 맞춰주는게 좋을 것 같아요

2019-04-30 08:32 UTC, improve777 commented on gongsulmin/StudyGong/app/src/main/java/my/gong/studygong/data/network/RetrofitProvider.kt
> +object RetrofitProvider {
싱글톤으로 구현하였지만 UpbitApi 인스턴스는 호출할 때마다 새로 생성하는 것으로 보입니다

2019-04-30 08:32 UTC, improve777 commented on gongsulmin/StudyGong/app/src/main/java/my/gong/studygong/viewcontrol/adapter/CoinAdapter.kt
> +    val context: Context,
context 를 사용하지 않는 것 같아요

2019-04-30 08:32 UTC, improve777 commented on gongsulmin/StudyGong/app/src/main/java/my/gong/studygong/data/model/response/UpbitMarketResponse.kt
> +        @SerializedName("korean_name") val korean_name: String,
파라미터의 표기법을 동일하게 맞춰주는게 좋을 것 같아요

2019-04-30 08:32 UTC, improve777 commented on gongsulmin/StudyGong/app/src/main/java/my/gong/studygong/data/network/RetrofitProvider.kt
> +    fun upbitRetrofit(): UpbitApi{
싱글톤으로 선언했지만 메소드 호출 시마다 UpbitApi 인스턴스를 생성하는 것 같아요

2019-05-01 08:06 UTC, sjjeong requested changes

2019-05-01 08:06 UTC, sjjeong commented on gongsulmin/StudyGong/app/src/main/java/my/gong/studygong/viewcontrol/adapter/CoinAdapter.kt
> +    val coinList: MutableList<Ticker>
List를 외부에서 받아서 오지말고 Adpater안에서만 쓰는 객체로 사용해주세요.

2019-05-01 08:06 UTC, sjjeong commented on gongsulmin/StudyGong/app/src/main/java/my/gong/studygong/data/source/upbit/UpbitRepository.kt
> +                                it.market
이 코드는 왜 있는건가요?

2019-05-01 08:06 UTC, sjjeong commented on gongsulmin/StudyGong/app/src/main/java/my/gong/studygong/viewcontrol/MainActivity.kt
> +    val minute = 30000L
시간관련 상수는 목적과 단위를 같이 명시해주는게 좋습니다.
XXX_INTERVAL_MILLIS

2019-05-01 08:06 UTC, sjjeong commented on gongsulmin/StudyGong/app/src/main/java/my/gong/studygong/data/source/upbit/UpbitRepository.kt
> +                                response.body()!!
!!보단 null safe하게 사용하는게 좋습니다.

2019-05-01 13:39 UTC, sabgilhun submitted a review, later dismissed

2019-05-01 15:11 UTC, GongSulMin commented on gongsulmin/StudyGong/app/src/main/java/my/gong/studygong/data/network/RetrofitProvider.kt
> +object RetrofitProvider {
수정하였습니다 !

2019-05-01 15:11 UTC, GongSulMin commented on gongsulmin/StudyGong/app/src/main/java/my/gong/studygong/viewcontrol/adapter/CoinAdapter.kt
> +    val context: Context,
수정하였습니다 !

2019-05-01 15:11 UTC, GongSulMin commented on gongsulmin/StudyGong/app/src/main/java/my/gong/studygong/data/model/response/UpbitMarketResponse.kt
> +        @SerializedName("korean_name") val korean_name: String,
수정하였습니다 !

2019-05-01 15:11 UTC, GongSulMin commented on gongsulmin/StudyGong/app/src/main/java/my/gong/studygong/viewcontrol/adapter/CoinAdapter.kt
> +    val coinList: MutableList<Ticker>
수정하였습니다 !

2019-05-01 15:11 UTC, GongSulMin commented on gongsulmin/StudyGong/app/src/main/java/my/gong/studygong/data/source/upbit/UpbitRepository.kt
> +                                it.market
수정하였습니다 !

2019-05-01 15:11 UTC, GongSulMin commented on gongsulmin/StudyGong/app/src/main/java/my/gong/studygong/viewcontrol/MainActivity.kt
> +    val minute = 30000L
수정하였습니다 !

2019-05-01 15:11 UTC, GongSulMin commented on gongsulmin/StudyGong/app/src/main/java/my/gong/studygong/viewcontrol/MainActivity.kt
> +    val minute = 30000L
수정하였습니다 !

2019-05-01 15:11 UTC, GongSulMin commented on gongsulmin/StudyGong/app/src/main/java/my/gong/studygong/data/source/upbit/UpbitRepository.kt
> +                                response.body()!!
이부분을 수정하긴 했는데 
맞게 수정 했는지 잘모르겠습니다 ㅎㅎ

2019-05-01 16:14 UTC, ddaeyeonkim submitted a review, later dismissed
LGTM 👍👍👍

2019-05-02 01:44 UTC, sabgilhun submitted a review, later dismissed

2019-05-03 17:05 UTC, sjjeong requested changes

2019-05-03 17:05 UTC, sjjeong commented on gongsulmin/StudyGong/app/src/main/java/my/gong/studygong/data/network/RetrofitProvider.kt
> +        val retrofitBuiilder = Retrofit.Builder()
오타 있습니다.

2019-05-03 17:05 UTC, sjjeong commented on gongsulmin/StudyGong/app/src/main/java/my/gong/studygong/data/network/RetrofitProvider.kt
> +            return@lazy retrofitBuiilder.create(UpbitApi::class.java)
`return@lazy`는 필요없습니다.

2019-05-03 17:05 UTC, sjjeong commented on gongsulmin/StudyGong/app/src/main/java/my/gong/studygong/data/network/RetrofitProvider.kt
> +//    fun upbitRetrofit(): UpbitApi{
불필요한 주석 제거해주세요.

2019-05-03 17:22 UTC, sjjeong approved these changes

2019-05-05 03:40 UTC, merged