Class03/dlwls5201
sjjeong/GoogryAndroidArchitecutreStudy pull request #172
Opened 2019-08-04 08:26 UTC by dlwls5201

MVP 변환 작업

특히 MainAcitivty의 **코인명, 현재가, 전일대비, 거래대금**에 따른 정렬부분을 MVP로 변환하는 부분이 잘 작업되었는지 의문이 듭니다:)

2019-08-04 17:05 UTC, preludezdev reviewed
거의 공부하는 마음으로 진성님 프로젝트 봤습니다...
전에 잠깐 훑어본 적은 있는데 이렇게 각잡고 앉아서 보니까 외부 라이브러리도 추가하고 여러가지 많이 하셨네요. 음... Rx 로 대부분 구현하셔서 제가 드릴 수 있는 피드백이 거의 없을 것 같습니다. MVP 는 제가 이해하고 있는 범위 내에선 잘 적용하신 것 같구요. 나머진 석준님 피드백 받으면 될 것 같아요. 

하나 말씀드리고 싶은건 혹시 레이아웃의 id 를 카멜케이스 대신 스네이크 케이스로 하는건 어떠세요? 클래스 내 프로퍼티도 카멜케이스로 쓰다보니 둘이 헷갈리는 경우가 있어서요. 참고하시면 좋을 링크 걸어드릴게요.

![image](https://user-images.githubusercontent.com/41214420/62426850-39a07200-b725-11e9-9e4a-93868d8d106c.png)

[헤이딜러 android-style-guide-resource]
https://github.com/PRNDcompany/android-style-guide/blob/master/Resource.md

아, PR 제목도 변경 부탁드릴게요 : )

2019-08-04 17:05 UTC, preludezdev commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/ui/tickerlist/TickerAdapter.kt
변수 선언을 val 로 바꿀 수 있을 것 같습니다

2019-08-04 17:05 UTC, preludezdev commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/ui/tickerlist/TickerAdapter.kt
안스에서 해당부분에
when (bundle.getString(Filter.KEY_FIELD)) {
처럼 inline 할 수 있다고 뜨긴 하는데 뭐가 더 맞는 방법인진 모르겠네요

2019-08-04 17:38 UTC, preludezdev reviewed
위에 올린 리뷰에 추가로 리뷰 다는 법을 몰라 새로 리뷰 남깁니다.

2019-08-04 17:38 UTC, preludezdev commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/ui/main/MainActivity.kt
> +
보다가 문득 든 생각인데 혹시 위에 함수들 Higher-order-function 이용해서 갯수 줄일 수 있지 않을까요?
implement 해야할 함수는 많은데 하는게 다 비슷해 보여서요
잘은 모르겠는데... 만약 가능하다면 코드량을 많이 줄일 수 있을 것 같습니다

2019-08-05 14:50 UTC, dlwls5201 commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/ui/tickerlist/TickerAdapter.kt
이거 제가 Log를 찍을러고 이렇게 작업했던 거였네요!! 추후 로그를 찍어 확인할 수 있는 부분이니 변수로 두겠습니다.

2019-08-05 14:51 UTC, dlwls5201 commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/ui/tickerlist/TickerAdapter.kt
변경하겠습니다!

2019-08-05 15:03 UTC, dlwls5201 commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/ui/main/MainActivity.kt
> +
이부분은 정말 어려운것 같습니다. 저도 고민인 부분입니다. 하지만 4,4,4 에서 1,1,1로 줄이면 View와 관련된 로직이 Prenent에서 View로 넘어가게 되는게 아닐까 싶어서 이렇게 했습니다. 코인명, 현재가, 전일대비, 거래대금의 각 버튼을 눌렀을 때  1개의 View만 선택되었다고 표시되고 나머지는 비선택으로 변경해야되는 로직을 작성해야되는데 이를 Present에서 구현해볼려고 하니 위와 같은 코드가 되버렸습니다. 그냥 위 코드를 쪼개지 말고 selectCoinName(), selectLast(), selectTradeDiff(), selectTradeAmount() 이런식으로 변경하면 View에 Present 로직이 들어가게 되는것 같아 저도 고민인 부분입니다.

2019-08-05 16:26 UTC, preludezdev commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/ui/main/MainActivity.kt
> +
음... 제가 생각했던건 아래 사진처럼 Presenter 에서 View 로 selectArrow 도 같이 넘겨줘서 View 부분에서 selectArrow 가 뭔지에 따라 다르게 작업을 하는 방식이었습니다

MainContract.kt
![image](https://user-images.githubusercontent.com/41214420/62478896-38377e00-b7e7-11e9-9e6b-5d764b049797.png)

MainActivity.kt
![image](https://user-images.githubusercontent.com/41214420/62478945-57361000-b7e7-11e9-9f6b-d6b20d7a0bd4.png)

MainPresenter.kt
![image](https://user-images.githubusercontent.com/41214420/62478960-60bf7800-b7e7-11e9-89d3-6ddb1547bd7d.png)

이렇게 하면 코드가 조금 지저분해보이긴 해도 코드량이 많이 줄긴하거든요...혹시 이렇게 변경하면 View 와 관련된 로직이 Present 에서 View 로 넘어가는건가요?

2019-08-05 18:03 UTC, dlwls5201 commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/ui/main/MainActivity.kt
> +
빠른 피드백과 상세한 코드 예시 정말 감사합니다! 이렇게 코드로 보니깐 변경하는게 더 좋은것 같아 수정했습니다. 하지만 코드량이 줄어 가독성이 좋아지는것은 느껴지지만 역시 View에 들어있는 When로직은 Presenter에 있어야 되지 않을까? 라는 생각이 계속 들지만 변경한 코드가 더 마음에 듭니다:)
6f61b20

2019-08-05 18:14 UTC, preludezdev commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/ui/main/MainActivity.kt
> +
그 부분은 저도 확신할 수가 없네요ㅠㅠ 나중에 같이 석준님한테 물어보는걸로 해요 :)

2019-08-06 10:27 UTC, preludezdev submitted a review, later dismissed
Approve 합니다 :)

2019-08-11 06:19 UTC, sjjeong requested changes

2019-08-11 06:19 UTC, sjjeong commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/rxobserver/RxObserverHelper.kt
> +object RxObserverHelper {
RxBus를 사용하지 않아도 구현 할 수 있습니다.
다른방법을 찾아보세요

2019-08-11 06:19 UTC, sjjeong commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/ui/tickerlist/TickerListFragment.kt
> +    companion object {
companion object를 클래스 맨 아래로 옮겨주세요

2019-08-11 06:19 UTC, sjjeong commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/ui/tickerlist/TickerListFragment.kt
> +    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
onActivityCreate로 변경해주세요

2019-08-11 06:19 UTC, sjjeong commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/ui/tickerlist/TickerListFragment.kt
> +            layoutManager = LinearLayoutManager(context)
layoutmanager는 xml에서도 설정할 수 있어요

2019-08-11 06:19 UTC, sjjeong commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/ui/tickerlist/TickerListFragment.kt
> +        tickerAdapter.setTickerClickListener(object :
고차함수로 처리해보세요

2019-08-11 06:19 UTC, sjjeong commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/ui/tickerlist/TickerListFragment.kt
> +    override fun getKeyMarkets() = arguments?.getString(KEY_MARKETS) ?: ""
presenter를 만들때 같이 넘겨주도록 해주세요

2019-08-11 06:19 UTC, sjjeong commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/ui/tickerlist/TickerListPresenter.kt
> +                view.hideProgress()
doOnTerminate로 success와 error를 같이 처리하면 될것 같습니다.

2019-08-15 15:19 UTC, dlwls5201 commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/rxobserver/RxObserverHelper.kt
> +object RxObserverHelper {
수정하였습니다.
7f6b64a

2019-08-15 15:20 UTC, dlwls5201 commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/ui/tickerlist/TickerListFragment.kt
> +    companion object {
수정하였습니다.
ecb7523

2019-08-15 15:20 UTC, dlwls5201 commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/ui/tickerlist/TickerListFragment.kt
> +    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
수정하였습니다.
d224ef6

2019-08-15 15:21 UTC, dlwls5201 commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/ui/tickerlist/TickerListFragment.kt
> +            layoutManager = LinearLayoutManager(context)
수정하였습니다.
0383796

2019-08-15 15:21 UTC, dlwls5201 commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/ui/tickerlist/TickerListFragment.kt
> +        tickerAdapter.setTickerClickListener(object :
수정하였습니다.
e899b58

2019-08-15 15:21 UTC, dlwls5201 commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/ui/tickerlist/TickerListFragment.kt
> +    override fun getKeyMarkets() = arguments?.getString(KEY_MARKETS) ?: ""
수정하였습니다.
0003edc

2019-08-15 15:21 UTC, dlwls5201 commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/ui/tickerlist/TickerListPresenter.kt
> +                view.hideProgress()
수정하였습니다.
1a37e14

2019-08-15 15:27 UTC, dlwls5201 reviewed
상단 카테고리 화살표 변경을 get과 set을 사용해 복잡하게 처리한 부분을 showCategoryArrow(selectArrow: Filter.SelectArrow) 1개의 메소드로 변경해 수정했습니다.
4ff4602

2019-08-17 13:39 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-08-19 05:25 UTC, preludezdev approved these changes

2019-08-25 03:12 UTC, merged