HW-3 MVP Architecture 적용하기
sjjeong/GoogryAndroidArchitecutreStudy pull request #174
Opened 2019-08-04 15:02 UTC by wswon

MVP모델 적용해봤습니다.

지금 앱은 
- CoinListActivity - market리스트 가져오는 작업
- CoinListFragment - ticker리스트 가져오는 작업 
으로 분리되어있는데 그래서 각각 presenter와 contract를 정의하게 되었습니다.
이렇게 분리한게 맞는 방법인지 모르겠어서 리뷰 부탁드립니다.

그 외에도 지적 많이해주세요 감사합니다.

2019-08-07 03:16 UTC, ganghee commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/view/coin/CoinListActivity.kt
> +    override lateinit var presenter: CoinListActivityContract.Presenter
activity와 fragment 각각 contract를 구현하셨는데 저희 slack(8월 2일)에 보시면 멘토님이  둘 중 하나에 구현하라고 하셨습니다~

2019-08-07 09:46 UTC, ganghee commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/view/coin/CoinListFragment.kt
> +                it.toTicker(requireContext())
데이터 변환하는 작업은 View에서 하는게 아니라 Presenter에서 하셔야 합니다
8월 2일 slack에서 석준님이 언급하셨어요!

2019-08-07 10:00 UTC, ganghee commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/view/coin/CoinListFragment.kt
> +            presenter.getTickerList(it.joinToString(","))
데이터를 처리하는 부분이니 presenter나 model에서 하는 것이 좋을 것 같아요

2019-08-08 13:08 UTC, wswon commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/view/coin/CoinListActivity.kt
> +    override lateinit var presenter: CoinListActivityContract.Presenter
제가 작업을 해보았는데 제 구조가 activity에 역할이 있다보니 잘 합쳐지지 않더라구요..!! 일단은 이렇게 진행하고 activity의 역할을 어떻게 이전 할 것인지를 생각해보겠습니다.

2019-08-08 13:21 UTC, wswon commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/view/coin/CoinListFragment.kt
> +                it.toTicker(requireContext())
45d1f4a
반영했습니다!

2019-08-08 13:21 UTC, wswon commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/view/coin/CoinListFragment.kt
> +            presenter.getTickerList(it.joinToString(","))
db245a1
반영했습니다!

2019-08-11 05:52 UTC, sjjeong requested changes

2019-08-11 05:52 UTC, sjjeong commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/view/coin/CoinListActivity.kt
> +        this.marketList = marketList
marketList를 setPager()에서만 사용하기 때문에 변수로 저장하지않고 바로 넘겨주시면 될 것 같아요

2019-08-11 05:52 UTC, sjjeong commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/view/coin/CoinListActivity.kt
> +        Toast.makeText(this@CoinListActivity, failure, Toast.LENGTH_SHORT).show()
showEmptyMarketData와 하는 동작이 같습니다.

공통으로 사용할 수 있는 함수명으로 바꿔주세요

2019-08-11 05:52 UTC, sjjeong commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/view/coin/presenter/CoinListActivityPresenter.kt
> +        coinListView.successConnectApi()
view에 successConnectApi를 호출할 필요가 없을 것 같습니다.
여기서 바로 getMarketList를 호출해주세요

2019-08-11 05:52 UTC, sjjeong commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/view/coin/CoinListFragment.kt
>      private lateinit var tickerList: List<Ticker>
사용되지 않는 변수이므로 제거해주세요

2019-08-11 05:52 UTC, sjjeong commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/view/coin/presenter/CoinListFragmentPresenter.kt
> +    private val context: Context,
context를 넘기지 마시고 context를 사용해서 만드는 것들을 미리 만들어서 넘겨주세요

2019-08-11 05:52 UTC, sjjeong commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/view/coin/presenter/CoinListFragmentPresenter.kt
> +                    dataList.forEach {
dataList.map{}으로 처리해보세요

2019-08-15 07:43 UTC, wswon commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/view/coin/presenter/CoinListFragmentPresenter.kt
> +                    dataList.forEach {
e873036
map으로 변경했습니다.

2019-08-15 07:43 UTC, wswon commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/view/coin/CoinListFragment.kt
>      private lateinit var tickerList: List<Ticker>
514560b
제거했습니다.

2019-08-15 07:44 UTC, wswon commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/view/coin/presenter/CoinListActivityPresenter.kt
> +        coinListView.successConnectApi()
f5e5979
바로 getMarketList를 호출하도록 변경했습니다.

2019-08-15 07:44 UTC, wswon commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/view/coin/CoinListActivity.kt
> +        this.marketList = marketList
48110d0
바로 넘겨주도록 함수명을 변경 했습니다.

2019-08-15 07:45 UTC, wswon commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/view/coin/presenter/CoinListFragmentPresenter.kt
> +    private val context: Context,
55c6939
미리 fragment에서 생성하여 넘겨주었습니다.

2019-08-15 07:54 UTC, wswon commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/view/coin/CoinListActivity.kt
> +        Toast.makeText(this@CoinListActivity, failure, Toast.LENGTH_SHORT).show()
ceea34e
공통함수로 변경했습니다.

2019-08-17 13:40 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-08-21 04:24 UTC, ganghee approved these changes

2019-08-21 04:24 UTC, merged