[사전과제2] androidx 프로젝트, gitignore작업
sjjeong/GoogryAndroidArchitecutreStudy pull request #176
Opened 2019-08-05 01:21 UTC by seonoh

gitignore 위치 프로젝트 안으로 수정했습니다.

2019-08-05 13:44 UTC, sjjeong requested changes
제가 리뷰 해드린 pr을 close하지말고 같은 pr에 내용 반영해주세요

2019-08-05 13:44 UTC, sjjeong commented on seonoh/.gitignore
> +
이 파일은 삭제해도 될것같네요

2019-08-06 00:40 UTC, seonoh commented on seonoh/.gitignore
> +
네 알겠습니다 !!

2019-08-06 04:27 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-08-06 06:03 UTC, merged