[사전과제2] Class04/junghum21
sjjeong/GoogryAndroidArchitecutreStudy pull request #177
Opened 2019-08-05 10:06 UTC by junghum21

2019-08-05 13:46 UTC, sjjeong requested changes

2019-08-05 13:46 UTC, sjjeong commented on README.md
> +# 조정흠(junghum21)의 공간입니다.
해당파일은 왜 변경하셨나요?

2019-08-05 13:46 UTC, sjjeong commented on junghum21/.gitignore
> +*.iml
이 파일은 삭제해도 될것같습니다.

2019-08-05 13:46 UTC, sjjeong commented on junghum21/ArchStudy/.gitignore
> +*.iml
gitignore파일을 잘못만드신거같습니다.
https://gitignore.io/ 여기서 만든 파일을 넣어주세요

2019-08-09 05:01 UTC, junghum21 commented on README.md
> +# 조정흠(junghum21)의 공간입니다.
실수로 README 파일을 지우고 커밋을 해서 다른파일에서 붙여넣기 했습니다.

2019-08-09 05:13 UTC, junghum21 commented on junghum21/ArchStudy/.gitignore
> +*.iml
그 사이트에서 만든 파일로 넣었었는데 실수로 누락했나 봅니다.

다시 작성해서 넣었습니다.

2019-08-09 05:23 UTC, closed without merging