HW-3 MVP 구현
sjjeong/GoogryAndroidArchitecutreStudy pull request #179
Opened 2019-08-07 11:17 UTC by ganghee

기존의 mvc패턴을 mvp로  바꾸어 구현하였습니다.

2019-08-08 12:22 UTC, wswon reviewed
제 눈에는 MVP구조가 잘 하신거 같아서 리뷰할게 이것뿐이네요..!!
 감사합니다.

2019-08-08 12:22 UTC, wswon commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/data/UpbitRepository.kt
> +        }
```
 if (INSTANCE == null) {
                INSTANCE = UpbitRepository()
            }
            return INSTANCE!!
```
이부분에 !! 강제호출 연산자가 있어서 

```
           return INSTANCE?.let { it } ?: UpbitRepository().apply {
                INSTANCE = this
            }
```
이렇게해도 되지않을까? 해서 바꿔봤습니다. 그냥 제안입니다.ㅎㅎ

2019-08-08 12:22 UTC, wswon commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/ui/MainActivity.kt
>      }
아래 configureMainTab() 에 리뷰가 안달려서 이 위치에답니다!
이것도 그냥 제안인데요.

   ```
     tabLayout.run {
            setupWithViewPager(viewPager)

            getTabAt(0)?.text = "KRW"
            getTabAt(1)?.text = "BTC"
            getTabAt(2)?.text = "ETH"
            getTabAt(3)?.text = "USDT"
        }
```
!!대신 ?로 safety call 을 하고 run으로 묶으면 가독성에 더좋을거 같아요

2019-08-08 12:22 UTC, wswon commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/ui/UpbitPresenter.kt
> +
init 작업이 필요없어보입니다.

2019-08-08 12:22 UTC, wswon commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/ui/UpbitPresenter.kt
> +
이유는 이미 tickerView 객체에서 presenter를 생성해서 넣었기 때문입니다.

2019-08-10 12:53 UTC, ganghee commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/data/UpbitRepository.kt
> +        }
네 감사합니다!  강제연산자 !!와 return을 사용하지 않고 구현하였습니다.
[cae1c58](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/179/commits/cae1c58a44da63fe6e79acdc3a2ec4f7015a7457)

2019-08-10 12:55 UTC, ganghee commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/ui/MainActivity.kt
>      }
with를 이용하여 수정하였습니다.
[bda10eb](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/179/commits/bda10ebec04383a1eeb0d118052acd8ffdc0e024)

2019-08-10 12:58 UTC, ganghee commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/ui/UpbitPresenter.kt
> +
생성자에 대한 지식이 부족했네요 지적해 주셔서 감사합니다.
[
8f4f942](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/179/commits/8f4f94285d8df1008daa2a62d412c4f181ec7d44)

2019-08-11 05:58 UTC, sjjeong requested changes

2019-08-11 05:58 UTC, sjjeong commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/ui/UpbitPresenter.kt
> +    private val tickerList by lazy { mutableListOf<FormatTickers>() }
tickerList를 사용하는 부분이 없는 것 같습니다.
제거해주셔도 좋겠네요

2019-08-11 05:58 UTC, sjjeong commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/ui/UpbitFragment.kt
> +class UpbitFragment(tabName: String) : Fragment(), UpbitContract.View {
생성자 말고 bundle로 받아주세요

2019-08-11 07:20 UTC, ganghee commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/ui/UpbitPresenter.kt
> +    private val tickerList by lazy { mutableListOf<FormatTickers>() }
네 제거 하였습니다.
[
1858f9f](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/179/commits/1858f9f8d7e152488aa146a1ee0e37bd01ddd5d4)

2019-08-15 09:56 UTC, ganghee commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/ui/UpbitFragment.kt
> +class UpbitFragment(tabName: String) : Fragment(), UpbitContract.View {
생성자 삭제하고 bundle 구현하였습니다. companion object도 구현하였습니다.
[UpbitFragment](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/179/commits/00602c2122f786f62f8c2f4111b6976e21dcf012)

2019-08-17 13:41 UTC, sjjeong requested changes

2019-08-17 13:41 UTC, sjjeong commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/ui/UpbitFragment.kt
> +            bundle.putString("MARKET_NAME", marketName)
MARKET_NAME을 상수로 빼서 사용해주세요.

2019-08-20 13:40 UTC, ganghee commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/ui/UpbitFragment.kt
> +            bundle.putString("MARKET_NAME", marketName)
파라미터에 문자열을 두지않고 상수로 구현하였습니다.
[UpbitFragment](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/179/commits/bf103d1cb62cb71da6bfcb81b51fe1ba007eea23)

2019-08-21 01:05 UTC, sjjeong commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/ui/UpbitFragment.kt
> +            bundle.putString("MARKET_NAME", marketName)
음.. 제가 말했던건 companion object안에 const val로 만들라는 말이였어요 ㅋㅋ

2019-08-21 06:17 UTC, ganghee commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/ui/UpbitFragment.kt
> +            bundle.putString("MARKET_NAME", marketName)
다시 수정 하였습니다.
[UpbitFragment](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/179/commits/e2d987654c57b219d90f9dbbc9619879a4729370)

2019-08-21 14:29 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-08-23 04:27 UTC, wswon approved these changes

2019-08-23 06:05 UTC, merged