1주차 과제
sjjeong/GoogryAndroidArchitecutreStudy pull request #18
Opened 2019-04-30 08:13 UTC by improve777

- 코인 리스트 가져오기

2019-04-30 10:30 UTC, GongSulMin requested changes

2019-04-30 10:30 UTC, GongSulMin commented on improve777/GAASProject/app/src/main/java/dev/daeyeon/gaasproject/data/source/UpbitRepository.kt
> +        if (markets == null) {
수정할 부분은 아닌데 궁금한 부분이 있어서요!
null 처리 하신게 다시 refresh 하실 때 
market 정보는 새로 안불러오신거죠???

2019-04-30 16:50 UTC, improve777 commented on improve777/GAASProject/app/src/main/java/dev/daeyeon/gaasproject/data/source/UpbitRepository.kt
> +        if (markets == null) {
넵 마켓 정보는 빈번하게 리프레시 될 일이 없을 것 같아서 처음 한번만 부르게 하고 
필드로 저장해서 사용하도록 했습니다

2019-04-30 17:44 UTC, GongSulMin commented on improve777/GAASProject/app/src/main/java/dev/daeyeon/gaasproject/data/source/UpbitRepository.kt
> +        if (markets == null) {
감사합니당 :)

2019-05-01 07:57 UTC, sjjeong requested changes

2019-05-01 07:57 UTC, sjjeong commented on improve777/GAASProject/app/src/main/res/layout/fragment_ticker.xml
> +                app:layout_constraintTop_toTopOf="parent"
SwipeRefreshLayout 하위에 있어서  `layout_constraintXXX_XXX`가 필요없습니다.

2019-05-01 07:57 UTC, sjjeong commented on improve777/GAASProject/app/src/main/java/dev/daeyeon/gaasproject/data/source/UpbitDataSource.kt
> +    fun getTicker(success: (list: List<Ticker>) -> Unit?, fail:(msg: String) -> Unit?)
Unit 뒤에는 ?가 없어도 됩니다.

2019-05-01 07:57 UTC, sjjeong commented on improve777/GAASProject/app/src/main/java/dev/daeyeon/gaasproject/data/source/UpbitRepository.kt
> +    var markets: String? = null
```kotlin
var markets = ""
```
으로 하고 다른부분에
```kotlin
markets.isNullOrEmpty()로 처리하면 NonNull하게 사용할 수 있습니다.
```

2019-05-01 07:57 UTC, sjjeong commented on improve777/GAASProject/app/src/main/java/dev/daeyeon/gaasproject/TickerAdapter.kt
> +        tickerList.clear()
addList에 NotifyDataSetChanged()가 있다면 clearList에도 있어야합니다.
```kotlin
tickerAdapter?.clearList()
tickerAdapter?.addList(it)
```
이렇게 쓰는게 목적이라면 replaceList, resetList 등등으로 내부에 clear와 addAll을 같이해주는 함수를 따로 만들어주세요.

2019-05-01 07:57 UTC, sjjeong commented on improve777/GAASProject/app/src/main/java/dev/daeyeon/gaasproject/network/NetworkManager.kt
> +    var instance: UpbitApi? = null
get할 때 초기화 해주고 싶다면 lazy 패턴을 사용하세요. NonNull하게 사용할 수 있습니다.

2019-05-01 08:40 UTC, sjjeong commented
Mentor Review Needed는 팀원들이 approve 해주고 해야합니다.

2019-05-01 08:43 UTC, sjjeong reviewed
47839fdecfc463317acc5e0189aa76849811c117
확인했습니다.

2019-05-01 11:32 UTC, sabgilhun submitted a review, later dismissed
LGTM ㅎㅎ

2019-05-01 13:42 UTC, sjjeong commented
@sabgilhun approve 하셨으면 mentor review needed로 라벨 변경해주셔야합니다.

2019-05-01 13:43 UTC, sjjeong commented
@GongSulMin 리뷰해주세요.

2019-05-01 16:44 UTC, GongSulMin submitted a review, later dismissed
몰라서 찾아본
LGTM...

2019-05-02 01:44 UTC, sabgilhun approved these changes

2019-05-02 01:49 UTC, GongSulMin approved these changes

2019-05-03 17:09 UTC, sjjeong approved these changes

2019-05-05 03:41 UTC, merged