HW-2 코인헬퍼 카피앱
sjjeong/GoogryAndroidArchitecutreStudy pull request #181
Opened 2019-08-13 09:35 UTC by seonoh

코인헬퍼 카피앱 PR
깃이 서툴러서 정말 이것저것 해보다보니 이게 맞나 싶습니다...!!

2019-08-15 13:48 UTC, jskim5923 reviewed
comment test

2019-08-15 15:25 UTC, jskim5923 commented on app/src/main/java/com/example/seonoh/seonohapp/BtcFragmnet.kt
> +class BtcFragmnet : Fragment(), CurrentPriceInfoRequest.ResultListener {
Fragment의 뷰가 같고 내용만 변경 되는 구조로 코인 이름의 Fragment를 나누는 것보다 하나의 Fragment로 데이터만
받아서 갱신하는 것이 좋을 것 같습니다.

2019-08-15 15:25 UTC, jskim5923 commented on app/src/main/java/com/example/seonoh/seonohapp/CoinAdapter.kt
> +    val mData = data
```suggestion
class CoinAdapter(private val data: ArrayList<CurrentPriceInfoModel>,val type : Int) : RecyclerView.Adapter<KrwItemViewHolder>(){
```

- mData변수의 접근자를 private으로 변경하는 것이 좋을 것 같습니다.
- data를 파라미터로 전달 받아, 클래스 변수에 넣는 것보단 주 생성자에서 클래스 변수로 두는 것이 좋을 것같습니다.

2019-08-15 15:25 UTC, jskim5923 commented on app/src/main/java/com/example/seonoh/seonohapp/CoinAdapter.kt
> +    lateinit var mView : View
```suggestion
    override fun onCreateViewHolder(parent: ViewGroup, viewType: Int): KrwItemViewHolder {
        val mView = LayoutInflater.from(parent.context).inflate(R.layout.krw_item,parent,false)
        return KrwItemViewHolder(mView,type)
    }
```
mView는 onCreateViewHolder 함수 내에서만 사용하므로 함수의 멤버 변수로 선언하는 것이 좋을 것 같습니다

2019-08-15 15:25 UTC, jskim5923 commented on app/src/main/java/com/example/seonoh/seonohapp/EthFragment.kt
> +class EthFragment : Fragment(), CurrentPriceInfoRequest.ResultListener {
Fragment의 뷰가 같고 내용만 변경 되는 구조로 코인 이름의 Fragment를 나누는 것보다 하나의 Fragment로 데이터만
받아서 갱신하는 것이 좋을 것 같습니다.

2019-08-15 15:25 UTC, jskim5923 commented on app/src/main/java/com/example/seonoh/seonohapp/UsdtFragment.kt
> +class UsdtFragment :Fragment(), CurrentPriceInfoRequest.ResultListener {
Fragment의 뷰가 같고 내용만 변경 되는 구조로 코인 이름의 Fragment를 나누는 것보다 하나의 Fragment로 데이터만
받아서 갱신하는 것이 좋을 것 같습니다.

2019-08-15 15:25 UTC, jskim5923 commented on app/src/main/java/com/example/seonoh/seonohapp/TabPagerAdapter.kt
> +    constructor(fm: FragmentManager, tabcount: Int) : super(fm) {
```suggestion
   class TabPagerAdapter(fm : FragmentManager, private val tabCount:Int) : FragmentStatePagerAdapter (fm){
```
부생성자 필요없이 주생성자에서 처리하면 tabCount도 immutable하게 설정해서  사용할 수 있을것 같습니다.

2019-08-15 15:25 UTC, jskim5923 commented on app/src/main/java/com/example/seonoh/seonohapp/TabPagerAdapter.kt
> +        when (position) {
position에 따른 별도의 Fragment보다는 하나의 Fragment로 데이터만 전달하여 사용하는게 좋을 것 같습니다.

2019-08-15 15:25 UTC, jskim5923 commented on app/src/main/java/com/example/seonoh/seonohapp/KrwFrgment.kt
> +class KrwFrgment : Fragment(),CurrentPriceInfoRequest.ResultListener{
Fragment의 뷰가 같고 내용만 변경 되는 구조로 코인 이름의 Fragment를 나누는 것보다 하나의 Fragment로 데이터만
받아서 갱신하는 것이 좋을 것 같습니다.

2019-08-15 15:25 UTC, jskim5923 commented on app/src/main/java/com/example/seonoh/seonohapp/MainActivity.kt
> +    private val TAB_COUNT = 4
마켓 종목조회에서 받아온 정보에 따라 TAB_COUNT를 설정하는 것이 좋을 것같습니다.

2019-08-15 15:25 UTC, jskim5923 commented on app/src/main/java/com/example/seonoh/seonohapp/MainActivity.kt
> +        tabLayout.addOnTabSelectedListener(TabLayout.ViewPagerOnTabSelectedListener(coinViewPager))
```suggestion
        tabLayout. setupWithViewPager(coinViewPager)
```
TabLayout - setupWithViewPager() 함수로 TabLayout - ViewPager를 연결하는 방법도 있습니다.

2019-08-15 15:25 UTC, jskim5923 commented on app/src/main/java/com/example/seonoh/seonohapp/MainActivity.kt
> +        tabLayout.apply {
마켓 종목 조회 API에서 받은 정보를 토대로 text 설정하는것이 좋을 것같습니다.

2019-08-15 15:25 UTC, jskim5923 commented on app/src/main/java/com/example/seonoh/seonohapp/MainActivity.kt
> +            when(result[i].market.substring(0,3)){
subStringBefore(delimiter) 함수도 있습니다.

2019-08-15 15:25 UTC, jskim5923 commented on app/src/main/java/com/example/seonoh/seonohapp/CoinItemViewHolder.kt
> +                        coinName.text = market.substring(4,market.length)
subStringAfter(delimeter)함수도 있습니다.

2019-08-15 15:25 UTC, jskim5923 commented on app/src/main/java/com/example/seonoh/seonohapp/CoinItemViewHolder.kt
> +const val KRW_TYPE = 0
viewType은 동일하므로 타입 구분없이 데이터만 갱신하면 될 것같습니다.

2019-08-15 15:25 UTC, jskim5923 commented on app/src/main/java/com/example/seonoh/seonohapp/network/RetrofitCreator.kt
> +            val client = OkHttpClient.Builder()
```suggestion
            val okClient = OkHttpClient.Builder()
                .addInterceptor(
                    LoggingInterceptor.Builder()
                        .loggable(BuildConfig.DEBUG)
                        .setLevel(Level.BASIC)
                        .log(Platform.INFO)
                        .request("OH_req")
                        .response("OH_res")
                        .build()
                )
                .addNetworkInterceptor(StethoInterceptor())
                .build()
```
변수를 하나 더 선언할 필요없이 한번에 설정

2019-08-15 15:25 UTC, jskim5923 commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/BaseFragment.kt
> +    fun showLoading() {
미사용 함수 삭제

2019-08-15 15:25 UTC, jskim5923 commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/BaseFragment.kt
> +    fun hideLoading() {
미사용 함수 삭제

2019-08-15 15:25 UTC, jskim5923 commented on seonoh/ArchitectureStudy/app/src/main/res/layout/coin_fragment.xml
> +            android:layout_height="match_parent"></androidx.recyclerview.widget.RecyclerView>
```suggestion
            android:layout_height="match_parent"/>
```
tag사이에 내용없으면 바로 닫는게 좋을 것 같습니다.

2019-08-15 15:25 UTC, jskim5923 commented on seonoh/ArchitectureStudy/app/src/main/res/layout/activity_main.xml
> +                android:textSize="15dp"
```suggestion
                android:textSize="15sp"
```
textSize는 sp로 변경

2019-08-15 15:25 UTC, jskim5923 commented on seonoh/ArchitectureStudy/app/src/main/res/layout/activity_main.xml
> +                android:textSize="15dp"
```suggestion
                android:textSize="15dp"
```
textSize는 sp로 변경

2019-08-15 15:25 UTC, jskim5923 commented on seonoh/ArchitectureStudy/app/src/main/res/layout/activity_main.xml
> +                android:textSize="15dp"
```suggestion
                android:textSize="15sp"
```

2019-08-15 15:25 UTC, jskim5923 commented on seonoh/ArchitectureStudy/app/src/main/res/layout/activity_main.xml
> +                android:textSize="15dp"
```suggestion
                android:textSize="15sp"
```
textSize는 sp로 변경

2019-08-15 15:25 UTC, jskim5923 commented on seonoh/ArchitectureStudy/app/src/main/res/layout/activity_main.xml
> +            android:layout_height="match_parent"></androidx.viewpager.widget.ViewPager>
```suggestion
            android:layout_height="match_parent"/>
```
tag사이에 내용없으면 바로 닫는게 좋을 것 같습니다.

2019-08-15 15:25 UTC, jskim5923 commented on seonoh/ArchitectureStudy/app/src/main/res/layout/coin_item.xml
> +                android:textSize="14dp"
```suggestion
                android:textSize="14sp"
```
textSize는 sp로 변경

2019-08-15 15:25 UTC, jskim5923 commented on seonoh/ArchitectureStudy/app/src/main/res/layout/coin_item.xml
> +                android:textSize="14dp"
```suggestion
                android:textSize="14sp"
```
textSize는 sp로 변경

2019-08-15 15:25 UTC, jskim5923 commented on seonoh/ArchitectureStudy/app/src/main/res/layout/coin_item.xml
> +                android:textSize="14dp"
```suggestion
                android:textSize="14sp"
```
textSize는 sp로 변경

2019-08-15 15:25 UTC, jskim5923 commented on seonoh/ArchitectureStudy/app/src/main/res/layout/coin_item.xml
> +                android:textSize="14dp"
```suggestion
                android:textSize="14sp"
```

textSize는 sp로 변경

2019-08-15 15:25 UTC, jskim5923 commented on seonoh/ArchitectureStudy/app/src/main/res/layout/fragment_base.xml
> +<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
미사용 파일 삭제

2019-08-15 15:25 UTC, jskim5923 commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/util/CalculateUtils.kt
> +    if(marketName!!.contains("USDT")){
```suggestion
text = marketName?.substringAfter("-") ?: ""
```

- 파라미터가 nullable이면 !! 보단 `?.` , `?:` 연산자를 사용
- length 별로 substring의 카운트를 달리 하는 것보다는 subStringAfter(delimiter) 함수가 가독성이 좋아보입니다.

2019-08-16 01:50 UTC, seonoh commented on app/src/main/java/com/example/seonoh/seonohapp/BtcFragmnet.kt
> +class BtcFragmnet : Fragment(), CurrentPriceInfoRequest.ResultListener {
네! 제가 커밋을 잘못올렸습니다 ! 뒤쪽에 수정본이있습니다.

2019-08-16 01:59 UTC, seonoh commented on app/src/main/java/com/example/seonoh/seonohapp/CoinAdapter.kt
> +    val mData = data
감사합니다 ! 리뷰를 보니 제가 평소에 private을 자주 사용하지 않는 것을 느꼈습니다.

2019-08-16 02:13 UTC, seonoh commented on app/src/main/java/com/example/seonoh/seonohapp/CoinAdapter.kt
> +    lateinit var mView : View
네, mView 멤버 변수로 변경했습니다!

2019-08-16 02:16 UTC, seonoh commented on app/src/main/java/com/example/seonoh/seonohapp/CoinItemViewHolder.kt
> +const val KRW_TYPE = 0
네 확인했습니다.

2019-08-16 02:16 UTC, seonoh commented on app/src/main/java/com/example/seonoh/seonohapp/EthFragment.kt
> +class EthFragment : Fragment(), CurrentPriceInfoRequest.ResultListener {
네 확인했습니다.

2019-08-16 02:17 UTC, seonoh commented on app/src/main/java/com/example/seonoh/seonohapp/KrwFrgment.kt
> +class KrwFrgment : Fragment(),CurrentPriceInfoRequest.ResultListener{
네 확인했습니다.

2019-08-16 02:23 UTC, seonoh commented on app/src/main/java/com/example/seonoh/seonohapp/MainActivity.kt
> +    private val TAB_COUNT = 4
TAB_COUNT는 고정된 값이고 변동될 것이 아니라고 판단하여 4로 지정했습니다!!

2019-08-16 02:24 UTC, seonoh commented on app/src/main/java/com/example/seonoh/seonohapp/TabPagerAdapter.kt
> +    constructor(fm: FragmentManager, tabcount: Int) : super(fm) {
네 확인했습니다!

2019-08-16 02:41 UTC, seonoh commented on app/src/main/java/com/example/seonoh/seonohapp/CoinItemViewHolder.kt
> +                        coinName.text = market.substring(4,market.length)
네 확인했습니다. 감사합니다!

2019-08-16 02:42 UTC, seonoh commented on app/src/main/java/com/example/seonoh/seonohapp/TabPagerAdapter.kt
> +        when (position) {
네 확인했습니다!

2019-08-16 02:42 UTC, seonoh commented on app/src/main/java/com/example/seonoh/seonohapp/UsdtFragment.kt
> +class UsdtFragment :Fragment(), CurrentPriceInfoRequest.ResultListener {
네 확인했습니다.

2019-08-16 02:54 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/BaseFragment.kt
> +    fun showLoading() {
네 제거했습니다.

2019-08-16 02:59 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/util/CalculateUtils.kt
> +    if(marketName!!.contains("USDT")){
네 확인했습니다.

2019-08-16 03:03 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/res/layout/activity_main.xml
> +                android:textSize="15dp"
네 확인했습니다!

2019-08-16 03:03 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/res/layout/coin_fragment.xml
> +            android:layout_height="match_parent"></androidx.recyclerview.widget.RecyclerView>
네 확인했습니다!

2019-08-16 03:03 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/res/layout/coin_item.xml
> +                android:textSize="14dp"
네 확인했습니다.

2019-08-16 03:03 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/res/layout/fragment_base.xml
> +<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
네 확인했습니다.

2019-08-16 03:05 UTC, seonoh reviewed
모든 리뷰 확인했습니다. 제가 git에 서툴러서 이렇게 진행하는게 맞는지 의문이 듭니다.
제가 확인한 파일들은 Viewed 눌렀고 코멘트 달았습니다.
그런데, commit suggestion은 아직 감이안오네요! 상세한 리뷰 정말 감사합니다.

2019-08-16 03:06 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/res/layout/coin_item.xml
> +                android:textSize="14dp"
네 확인했습니다.

2019-08-16 03:06 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/res/layout/coin_item.xml
> +                android:textSize="14dp"
네 확인했습니다.

2019-08-17 07:12 UTC, jskim5923 commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/TabPagerAdapter.kt
> +        when (position) {
```suggestion
return when (position) {
            0 -> CoinFragment.newInstance(KRW_TYPE, krwMarketData)

            1 -> CoinFragment.newInstance(BTC_TYPE, btcMarketData)

            2 -> CoinFragment.newInstance(ETH_TYPE, ethMarketData)

            3 -> CoinFragment.newInstance(USDT_TYPE, usdtMarketData)

            else -> throw Throwable()
        }
```
위와 같이 변경 가능할 것 같습니다.
마켓 정보(KRW, BTC, ETH, USDT)보두 viewType이 같기 때문에 굳이 viewType을 각각 나눌 필요가 없을 것 같습니다.

2019-08-17 07:12 UTC, jskim5923 commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/MainActivity.kt
> +        tabLayout.apply {
addTab(tabLayout.newTab().setText("KRW"))
            addTab(tabLayout.newTab().setText("BTC"))
            addTab(tabLayout.newTab().setText("ETH"))
            addTab(tabLayout.newTab().setText("USDT"))
위와 같이 TAB의 텍스트를 상수로 작성하기 보다는
getMarketAll()에서 받아온 데이터의 market field를 subStringBefore("-") 로 사용하는  것이 좋아보입니다.

2019-08-17 07:12 UTC, jskim5923 commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/MainActivity.kt
> +    fun classifyMarketData(marketData: ArrayList<Market>) {
- 접근자를 private로 변경하는게 좋습니다
- classifyMarketData함수에서 받아온 데이터를 분류 할 때, 아래와 같이 분류 해놓으면 탭의 카운트/텍스트를 상수로 미리 지정하는 것이 아닌 받아온 데이터를 이용해 설정 할 수 있을것 같습니다.
        val titleList = marketData.map {
            it.market.substringBefore("-")
        }.distinct()
        val dataList = ArrayList<String>()

        titleList.forEach { title ->
             dataList += marketData.filter {
                it.market.substringBefore("-") == title
            }.joinToString(",") {
                it.market
            }
        }

2019-08-17 07:31 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/TabPagerAdapter.kt
> +        when (position) {
감사합니다 종선님 !

2019-08-17 08:06 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/MainActivity.kt
> +        tabLayout.apply {
네 수정했습니다 감사합니다!

2019-08-17 08:15 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/MainActivity.kt
> +    fun classifyMarketData(marketData: ArrayList<Market>) {
감사합니다 반영해보겠습니다 !!

2019-08-19 07:00 UTC, ddaeyeonkim reviewed
1기 스터디 했었던 김대연입니다.
전반적으로 2줄씩 개행한 부분, 코드 정렬이 안된 부분, private 이 붙지 않은 부분이 있는 것 같습니다.

무조건 제 리뷰가 옳은 게 아니라서 다른 의견 주시면 감사히 받겠습니다!

2019-08-19 07:00 UTC, ddaeyeonkim commented on seonoh/ArchitectureStudy/app/build.gradle
> +    implementation 'com.squareup.retrofit2:retrofit:2.6.1'
retrofit dependency 가 중복해서 추가되어있습니다

2019-08-19 07:00 UTC, ddaeyeonkim commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/BaseFragment.kt
> +open class BaseFragment : Fragment()
abstract 클래스로 해서 추상화를 하는게 더 좋을 것 같습니다

2019-08-19 07:00 UTC, ddaeyeonkim commented on app/src/main/java/com/example/seonoh/seonohapp/SeonohApplication.kt
> +        var mContext : Context? = null
우선 mContext 변수를 호출하는 부분이 없으시고, 필요하신 경우에는 getAplicationContext() 메서드를 사용하는게 좋을 듯 합니다 
application 클래스의 스태틱 변수는 어디서든지 변경이 될 수 있는 위험이 있습니다

2019-08-19 07:00 UTC, ddaeyeonkim commented on app/src/main/java/com/example/seonoh/seonohapp/network/RetrofitCreator.kt
> +class RetrofitCreator {
싱글톤 클래스로 변경해서 사용하는게 어떨까요?

2019-08-19 07:00 UTC, ddaeyeonkim commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinFragment.kt
> +            layoutManager = mLinearLayoutManager
리스트뷰의 layoutManager 는 xml 에서 설정해줄 수 있습니다

2019-08-19 07:00 UTC, ddaeyeonkim commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/TabPagerAdapter.kt
> +class TabPagerAdapter(fm: FragmentManager, tabcount: Int) : FragmentStatePagerAdapter(fm) {
tabcount 변수를 카멜케이스로 수정하시는게 나을 것 같습니다

2019-08-19 07:00 UTC, ddaeyeonkim commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/TabPagerAdapter.kt
> +    private val tabCount = tabcount
생성자에서 `TabPagerAdapter(fm: FragmentManager, private val tabCount)` 로 선언해서 사용해도 될 것 같아요

2019-08-19 07:00 UTC, ddaeyeonkim commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/TabPagerAdapter.kt
> +            else -> throw Throwable()
Throwable 을 던지면 앱이 죽게 됩니다 else 에 `CoinFragment.newInstance(USDT_TYPE, usdtMarketData)` 를 받는게 나을 듯 합니다

2019-08-19 07:00 UTC, ddaeyeonkim commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinFragment.kt
> +    lateinit var mView : View
view 를 전역으로 들고 있는 것보다는 `getView()` 메서드로 필요한곳에서 호출하는 게 좋을 것 같습니다

2019-08-19 07:00 UTC, ddaeyeonkim commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinFragment.kt
> +    lateinit var mAdapter : CoinAdapter
lazy 패턴을 사용하면 어떨까요?

2019-08-19 07:00 UTC, ddaeyeonkim commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinFragment.kt
> +        mView.krwRecyclerView.apply {
kotlin extension 을 쓰셔서 mView. 를 생략하셔도 되네요

2019-08-19 07:00 UTC, ddaeyeonkim commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinAdapter.kt
> +    private var mData : ArrayList<CurrentPriceInfoModel>? = null
처음에 arrayList 를 생성해서 nullable 하지 않게 하는게 좋을것 같습니다

2019-08-19 07:00 UTC, ddaeyeonkim commented on app/src/main/java/com/example/seonoh/seonohapp/MainActivity.kt
> +    companion object{
kotlin convention 에서 companion object 블록을 최하단으로 내리도록 권장하고 있습니다

![image](https://user-images.githubusercontent.com/36095102/63241759-d15aa000-c28f-11e9-9541-8d13945fa3e8.png)

2019-08-19 07:00 UTC, ddaeyeonkim commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/MainActivity.kt
> +    lateinit var conMarketNameList: List<String>
전역변수에는 헝가리안표기법을 사용하시는데 위 변수는 네이밍 규칙이 안맞는것 같습니다
다만, 권장은 전부 카멜케이스 표기로 알고 있습니다

2019-08-19 07:00 UTC, ddaeyeonkim commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinFragment.kt
> +            bundle.putInt("type",type)
market 과 type 같은 키값은 상수로 사용하는게 좋습니다

2019-08-19 07:00 UTC, ddaeyeonkim commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinItemViewHolder.kt
> +const val USDT_TYPE = 3
CoinFragment 인스턴스의 파라미터인데 실제로는 사용하지 않는 값인 것 같습니다

2019-08-19 07:00 UTC, ddaeyeonkim commented on app/src/main/java/com/example/seonoh/seonohapp/BtcFragmnet.kt
> +        initView(mData)
여기서는 `mAdapter.addCoinData(data)` 만 해주고 initView 는 프래그먼트 생성시에 해주는게 좋습니다
mData 로 따로 들고 있지 않아도 될 것 같아요

2019-08-19 07:00 UTC, ddaeyeonkim commented on app/src/main/java/com/example/seonoh/seonohapp/network/CurrentPriceInfoRequest.kt
> +class CurrentPriceInfoRequest{
CurrentPriceInfoRequest 와 marketRequest 가 레포지토리의 역할을 하는데 
하나로 합치고 싱글톤으로 사용하는게 나을 것 같습니다

2019-08-19 07:00 UTC, ddaeyeonkim commented on app/src/main/java/com/example/seonoh/seonohapp/network/BaseReqeust.kt
> +    val api = SeonohApplication.mApiService
생성자에서 인자로 받아서 쓰는게 좋습니다

2019-08-19 07:00 UTC, ddaeyeonkim commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/MainActivity.kt
> +        krwMarketData = krwMarketData.substring(0, krwMarketData.length - 1)
이미 marketDataList 에 마켓별로 필터링하고 조인 하셔서 리스트에서 가져다가 쓰면 될 것 같네요.

2019-08-19 07:00 UTC, ddaeyeonkim commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinItemViewHolder.kt
> +                totalTradePrice.setTradeAmount(accTradePrice_24h)
리스트뷰에서 매번 바인딩 될때마다 데이터를 가공하게 됩니다
리스트뷰에 보여줄 데이터들의 모델을 별도로 만들어서 넣어주는게 좋습니다

2019-08-19 07:00 UTC, ddaeyeonkim commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/MainActivity.kt
> +        var krwMarketData: String = ""
static 으로 가지지 않는게 좋을 것 같습니다

2019-08-19 11:46 UTC, seonoh commented on seonoh/ArchitectureStudy/app/build.gradle
> +    implementation 'com.squareup.retrofit2:retrofit:2.6.1'
반갑습니다!!! 코드리뷰 감사합니다!

2019-08-19 11:47 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/BaseFragment.kt
> +open class BaseFragment : Fragment()
감사합니다 !

2019-08-19 11:50 UTC, seonoh commented on app/src/main/java/com/example/seonoh/seonohapp/SeonohApplication.kt
> +        var mContext : Context? = null
네 감사합니다!

2019-08-19 11:51 UTC, seonoh commented on app/src/main/java/com/example/seonoh/seonohapp/network/RetrofitCreator.kt
> +class RetrofitCreator {
네 감사합니다!!

2019-08-19 11:53 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinFragment.kt
> +            layoutManager = mLinearLayoutManager
네 감사합니다! 이제 알게된 사실이네요!

2019-08-20 00:28 UTC, improve777 commented on seonoh/ArchitectureStudy/app/build.gradle
> +    implementation 'com.squareup.retrofit2:retrofit:2.6.1'
네 반갑습니다!

2019-08-20 01:19 UTC, seonoh commented on app/src/main/java/com/example/seonoh/seonohapp/network/CurrentPriceInfoRequest.kt
> +class CurrentPriceInfoRequest{
네 감사합니다. 반영했습니다!

2019-08-20 01:19 UTC, seonoh commented on app/src/main/java/com/example/seonoh/seonohapp/network/BaseReqeust.kt
> +    val api = SeonohApplication.mApiService
네 감사합니다 반영했습니다!

2019-08-20 01:48 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinItemViewHolder.kt
> +                totalTradePrice.setTradeAmount(accTradePrice_24h)
통신을 통해서 데이터를 전달받을때 특정 모델에 데이터를 가공해두고 어댑터에서는 그 데이터를 뿌려주기만 하는 용도로 만들면 될까요?

2019-08-20 01:50 UTC, improve777 commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinItemViewHolder.kt
> +                totalTradePrice.setTradeAmount(accTradePrice_24h)
네 맞습니다!

2019-08-20 02:39 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/MainActivity.kt
> +        krwMarketData = krwMarketData.substring(0, krwMarketData.length - 1)
네 감사합니다!!

2019-08-20 02:54 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinItemViewHolder.kt
> +                totalTradePrice.setTradeAmount(accTradePrice_24h)
감사합니다! 수정해봤는데 signedChangeRate(전일대비변화율)은 textview color가 껴있어서 다른데이터들만 가공후 넣어줬습니다.

2019-08-20 02:55 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/MainActivity.kt
> +        var krwMarketData: String = ""
네 수정했습니다!

2019-08-20 03:30 UTC, improve777 commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/MainActivity.kt
> +        var krwMarketData: String = ""
`@JvmStatic` 어노테이션 뿐만 아니라 companion object 로 선언하신 것 자체가 스태틱이라 지양하는게 좋을 것 같구요
소스 수정하셔서 실제로 ~MarketData 는 사용할 필요가 없으시기 때문에 다 지워주셔도 될거 같아요

2019-08-20 04:13 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/MainActivity.kt
> +        var krwMarketData: String = ""
아아 맞습니다 ㅎㅎ 다 삭제했습니다 !

2019-08-20 07:24 UTC, ddaeyeonkim commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/TabPagerAdapter.kt
> +    override fun getCount(): Int = tabcount
tabCount 가 필요없이 이제 data의 사이즈로 대체 할 수 있을 것 같습니다

2019-08-20 07:24 UTC, ddaeyeonkim commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/network/CoinRequest.kt
> +    interface MarketResultListener {
CurrentPriceInfoResultListener 와 매우 유사합니다
추상화를 하는건 어떨까요?

2019-08-20 07:24 UTC, ddaeyeonkim commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/network/CoinRequest.kt
> +    lateinit var mMarketListener: MarketResultListener
메서드의 파라미터로 받아서 활용하기 때문에 필요 없을 것 같아요

2019-08-20 07:24 UTC, ddaeyeonkim commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/network/CoinRequest.kt
> +        var single = api!!.getMarketAll()
notnull 단언자(!!) 생략이 가능합니다
되도록이면 final 을 지향하는 게 좋습니다!

2019-08-20 07:24 UTC, ddaeyeonkim commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/network/CoinRequest.kt
> +    fun marketSend(api: Api, listener: MarketResultListener) {
메서드마다 받지않고 클래스의 생성자에서 받는게 좋을 것 같습니다

2019-08-20 07:24 UTC, ddaeyeonkim commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/network/RetrofitCreator.kt
> +    val okClient = OkHttpClient.Builder()
okClient 는 static 으로 들고 있기보다는 `createOkHttpClient()` 같은 메서드로 사용하는게 좋을것 같습니다

2019-08-20 07:24 UTC, improve777 commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinAdapter.kt
> +    private var mData: ArrayList<UseCoinModel>? = null
final 로 하고 notnull 로 하는게 좋을 것 같아요

2019-08-20 07:24 UTC, improve777 commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinFragment.kt
> +            mAdapter.addCoinData(data)
initView 와 coinData 를 넣는 로직은 분리하는게 나을 것 같습니다

2019-08-20 07:24 UTC, improve777 commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/TabPagerAdapter.kt
> +    private val data: ArrayList<String>,
처음에 생성자로 받지 않고  arrayList 를 가지고 있도록 하는게 좋을 것 같습니다

2019-08-20 11:57 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/TabPagerAdapter.kt
> +    override fun getCount(): Int = tabcount
네 감사합니다 반영했습니다!

2019-08-20 12:04 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/network/CoinRequest.kt
> +    lateinit var mMarketListener: MarketResultListener
네 알겠습니다!

2019-08-20 12:05 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/network/CoinRequest.kt
> +        var single = api!!.getMarketAll()
final을 지향하는 이유가 무엇인가요?

2019-08-20 12:05 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/network/CoinRequest.kt
> +    fun marketSend(api: Api, listener: MarketResultListener) {
네 감사합니다! 반영했습니다!

2019-08-20 12:08 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/network/RetrofitCreator.kt
> +    val okClient = OkHttpClient.Builder()
메서드로 사용하는게 좋은 이유는 무엇인가요?

2019-08-20 12:10 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinAdapter.kt
> +    private var mData: ArrayList<UseCoinModel>? = null
네 감사합니다!

2019-08-20 12:12 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinFragment.kt
> +            mAdapter.addCoinData(data)
네 감사합니다 반영했습니다!

2019-08-20 12:18 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/TabPagerAdapter.kt
> +    private val data: ArrayList<String>,
네 감사합니다 반영했습니다!

2019-08-21 00:24 UTC, improve777 commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/network/CoinRequest.kt
> +        var single = api!!.getMarketAll()
코드에서 final 로 선언하게 되면 명확하게 변하지 않는다는 것을 알수 있어서요
var 는 되도록이면 변경 가능 해야하는 경우만 사용하는게 좋더라구요

2019-08-21 00:44 UTC, improve777 commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/network/RetrofitCreator.kt
> +    val okClient = OkHttpClient.Builder()
안그러면 okClient 를 메모리 상에서 들고 있게 되는데 retrofit 을 처음에 생성할때를 제외하곤 사용하지 않아서 비효율적이라고 생각합니다

2019-08-21 00:46 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/network/CoinRequest.kt
> +        var single = api!!.getMarketAll()
아하 ! 감사합니다!

2019-08-21 02:07 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/res/layout/activity_main.xml
> +            android:layout_height="match_parent"></androidx.viewpager.widget.ViewPager>
네 확인했습니다!

2019-08-21 02:30 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/network/CoinRequest.kt
> +    interface MarketResultListener {
아.. 추상화를 해보려고하는데 기존의 로직을 유지한채로 추상화를 어떻게해야할지 고민됩니다..!

2019-08-21 03:23 UTC, improve777 commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/network/CoinRequest.kt
> +    interface MarketResultListener {
두개의 인터페이스가 똑같이 success 와 failed 메서드를 가지고 있는데
차이점은 success 의 파라미터 뿐이라서요
파라미터의 타입을 제네릭 타입으로 받게 하면 어떨까요?

2019-08-21 04:38 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/network/CoinRequest.kt
> +    interface MarketResultListener {
아 인터페이스를 말씀하는거셨군요!!! 감사합니다!!

2019-08-21 04:38 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/network/RetrofitCreator.kt
> +    val okClient = OkHttpClient.Builder()
감사합니다!

2019-08-21 08:30 UTC, improve777 commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinAdapter.kt
> +        holder.bind(mData!![position])
notnull 단언자(!!) 를 제거 할 수 있습니다
```suggestion
        holder.bind(mData[position])
```

2019-08-21 08:30 UTC, improve777 commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinAdapter.kt
> +    private val mData: ArrayList<UseCoinModel> by lazy { ArrayList<UseCoinModel>() }
초기화 지연을 사용하는 이유에 대해 좀 더 생각을 해봤는데
메모리를 효율적으로 사용하기 위한 부분이 큰 것 같아요
여기서는 바로 객체를 생성하는게 더 좋을 것 같습니다
```suggestion
    private val mData = mutableListOf<UseCoinModel>()
```

2019-08-21 08:30 UTC, improve777 commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinAdapter.kt
> +        val mView = LayoutInflater.from(parent.context).inflate(R.layout.coin_item, parent, false)
전역변수가 아니기 때문에 좋지 않은 네이밍인 것 같습니다
```suggestion
        val view = LayoutInflater.from(parent.context).inflate(R.layout.coin_item, parent, false)
```

2019-08-21 08:30 UTC, improve777 commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/TabPagerAdapter.kt
> +        mData = data
addAll() 로 데이터를 받는게 좋을 것 같습니다
```suggestion
        mData.addAll(data)
        notifyDataSetChanged()
```

2019-08-21 08:30 UTC, improve777 commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/TabPagerAdapter.kt
> +    override fun getCount(): Int = if(::mData.isInitialized) mData.size else 0
lateinit 을 사용하지 않으면 더 깔끔해질거 같아요

2019-08-21 08:30 UTC, improve777 commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/MainActivity.kt
> +        initView(data)
api 응답으로 받은 데이터만 넣어주면 되기 때문에 setData 만 해주는게 좋을 것 같습니다
```suggestion
        mPagerAdapter.setData(data)
```

2019-08-21 08:30 UTC, improve777 commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/MainActivity.kt
> +    fun initView(data: ArrayList<String>) {
initView() 를 `onCreate()` 에서 호출해주는게 어떨까요?
데이터를 넣는 로직은 분리하구요

2019-08-21 10:53 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinAdapter.kt
> +        holder.bind(mData!![position])
네 감사합니다 반영했습니다!

2019-08-21 10:54 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinAdapter.kt
> +    private val mData: ArrayList<UseCoinModel> by lazy { ArrayList<UseCoinModel>() }
네 감사합니다 !

2019-08-21 10:56 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinAdapter.kt
> +        val mView = LayoutInflater.from(parent.context).inflate(R.layout.coin_item, parent, false)
네 수정했습니다!

2019-08-21 10:56 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/TabPagerAdapter.kt
> +        mData = data
네 수정했습니다!

2019-08-21 10:58 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/TabPagerAdapter.kt
> +    override fun getCount(): Int = if(::mData.isInitialized) mData.size else 0
네 반영했습니다!

2019-08-21 11:05 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/MainActivity.kt
> +        initView(data)
네 감사합니다 반영했습니다!

2019-08-21 11:07 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/MainActivity.kt
> +    fun initView(data: ArrayList<String>) {
네 감사합니다 반영했습니다!
대신 addTab부분은 직접 String 값을 넣어주었습니다.

2019-08-21 21:42 UTC, improve777 commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinFragment.kt
> +        initView()
initView() 는 `onActivityCreated()` 에서 해주시는게 나을 것 같아요

2019-08-21 21:42 UTC, improve777 commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinAdapter.kt
> +        mData!!.addAll(data)
notNull 단언자(!!) 생략이 가능합니다
```suggestion
        mData.addAll(data)
```

2019-08-21 21:42 UTC, improve777 commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinAdapter.kt
> +    override fun getItemCount(): Int = mData!!.size
notNull 단언자(!!) 생략이 가능합니다
```suggestion
    override fun getItemCount(): Int = mData.size
```

2019-08-21 21:42 UTC, improve777 commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/network/CoinRequest.kt
> +    fun marketSend(listener: BaseResult<ArrayList<Market>>) {
메서드명은 동사가 앞에 오도록 수정해주세요

2019-08-21 21:42 UTC, improve777 commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/network/CoinRequest.kt
> +    fun currentPriceInfoSend(listener: BaseResult<ArrayList<CurrentPriceInfoModel>>, markets: String) {
메서드명은 동사가 앞에 오도록 수정해주세요

2019-08-21 23:55 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinFragment.kt
> +        initView()
네 수정했습니다!

2019-08-21 23:55 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinAdapter.kt
> +        mData!!.addAll(data)
네 수정했습니다. 감사합니다!

2019-08-21 23:55 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinAdapter.kt
> +    override fun getItemCount(): Int = mData!!.size
네 수정했습니다. 감사합니다!

2019-08-21 23:56 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/network/CoinRequest.kt
> +    fun currentPriceInfoSend(listener: BaseResult<ArrayList<CurrentPriceInfoModel>>, markets: String) {
네 리뷰 감사합니다! 수정했습니다.

2019-08-21 23:58 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/network/CoinRequest.kt
> +    fun marketSend(listener: BaseResult<ArrayList<Market>>) {
네 리뷰 감사합니다! 수정했습니다.

2019-08-22 13:23 UTC, sjjeong commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/network/CoinRequest.kt
> +    fun marketSend(listener: BaseResult<ArrayList<Market>>) {
@seonoh 
반영 커밋 남겨주세요

2019-08-22 13:23 UTC, sjjeong commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinAdapter.kt
> +    override fun getItemCount(): Int = mData!!.size
@seonoh 
반영 커밋 남겨주세요

2019-08-22 13:23 UTC, sjjeong commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinAdapter.kt
> +        mData!!.addAll(data)
@seonoh 
반영 커밋 남겨주세요

2019-08-22 13:23 UTC, sjjeong commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/MainActivity.kt
> +    fun initView(data: ArrayList<String>) {
@seonoh 
반영 커밋 남겨주세요

2019-08-22 13:23 UTC, sjjeong commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/MainActivity.kt
> +        initView(data)
@seonoh 
반영 커밋 남겨주세요

2019-08-22 13:23 UTC, sjjeong commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/TabPagerAdapter.kt
> +    override fun getCount(): Int = if(::mData.isInitialized) mData.size else 0
@seonoh 
반영 커밋 남겨주세요

2019-08-22 13:23 UTC, sjjeong commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/TabPagerAdapter.kt
> +        mData = data
@seonoh 
반영 커밋 남겨주세요

2019-08-22 13:23 UTC, sjjeong commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinAdapter.kt
> +        val mView = LayoutInflater.from(parent.context).inflate(R.layout.coin_item, parent, false)
@seonoh 
반영 커밋 남겨주세요

2019-08-22 13:23 UTC, sjjeong commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinAdapter.kt
> +    private val mData: ArrayList<UseCoinModel> by lazy { ArrayList<UseCoinModel>() }
@seonoh 
반영 커밋 남겨주세요

2019-08-22 13:23 UTC, sjjeong commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinAdapter.kt
> +        holder.bind(mData!![position])
@seonoh 
반영 커밋 남겨주세요

2019-08-22 13:23 UTC, sjjeong commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/TabPagerAdapter.kt
> +    private val data: ArrayList<String>,
@seonoh 
반영 커밋 남겨주세요

2019-08-22 13:23 UTC, sjjeong commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinFragment.kt
> +            mAdapter.addCoinData(data)
@seonoh 
반영 커밋 남겨주세요

2019-08-22 13:23 UTC, sjjeong commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinAdapter.kt
> +    private var mData: ArrayList<UseCoinModel>? = null
@seonoh 
반영 커밋 남겨주세요

2019-08-22 13:23 UTC, sjjeong commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/network/RetrofitCreator.kt
> +    val okClient = OkHttpClient.Builder()
@seonoh 
반영 커밋 남겨주세요

2019-08-22 13:23 UTC, sjjeong commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/network/CoinRequest.kt
> +    fun marketSend(api: Api, listener: MarketResultListener) {
@seonoh 
반영 커밋 남겨주세요

2019-08-22 13:23 UTC, sjjeong commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/network/CoinRequest.kt
> +        var single = api!!.getMarketAll()
@seonoh 
반영 커밋 남겨주세요

2019-08-22 13:23 UTC, sjjeong commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/network/CoinRequest.kt
> +    lateinit var mMarketListener: MarketResultListener
@seonoh 
반영 커밋 남겨주세요

2019-08-22 13:23 UTC, sjjeong commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/TabPagerAdapter.kt
> +    override fun getCount(): Int = tabcount
@seonoh 
반영 커밋 남겨주세요

2019-08-22 13:54 UTC, sjjeong requested changes
prefix로 m을 붙이는 부분 모두 제거 해주세요

2019-08-22 13:54 UTC, sjjeong commented on app/src/main/java/com/example/seonoh/seonohapp/model/CurrentPriceInfoModel.kt
> +    @Expose
Expose annotation은 불필요합니다.
제거해주세요.

2019-08-22 13:54 UTC, sjjeong commented on app/src/main/java/com/example/seonoh/seonohapp/model/Market.kt
> +    @Expose
Expose annotation은 불필요합니다.
제거해주세요.

2019-08-22 13:54 UTC, sjjeong commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/model/UseCoinModel.kt
> +    val accTradePrice_24h: String
`_`제거 해주세요

2019-08-22 13:54 UTC, sjjeong commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/network/CoinRequest.kt
> +    private val mApi = api
class CoinRequest(private val api: Api)
로 하시면 해당 코드는 필요없습니다.

2019-08-22 13:54 UTC, sjjeong commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/network/CoinRequest.kt
> +                } else {
아무동작이 없는 else 제거해주세요

2019-08-22 13:54 UTC, sjjeong commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/network/CoinRequest.kt
> +        var single = mApi.getMarketAll()
var대신 val로 선언해주세요

2019-08-22 13:54 UTC, sjjeong commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/network/CoinRequest.kt
> +        var single = mApi.getCurrentPriceInfo(markets)
var대신 val로 선언해주세요

2019-08-22 13:54 UTC, sjjeong commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/network/CoinRequest.kt
> +                } else {
아무동작이 없는 else 제거해주세요

2019-08-22 13:54 UTC, sjjeong commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/network/RetrofitCreator.kt
> +    fun createClient() : OkHttpClient{
private으로 변경해주세요

2019-08-22 13:54 UTC, sjjeong commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/network/RetrofitCreator.kt
> +        val client = OkHttpClient.Builder()
client를 사용하는 부분이 없으니 바로 return 해주세요

2019-08-22 13:54 UTC, sjjeong commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/util/CalculateUtils.kt
> +        if (marketName!!.contains("USDT")) {
if else 안에 있는 return을 밖으로 빼주세요

2019-08-22 13:54 UTC, sjjeong commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/util/CalculateUtils.kt
> +        if (marketName!!.contains("USDT")) {
!! 대신 null safety하게 처리해주세요

2019-08-22 13:54 UTC, sjjeong commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/util/CalculateUtils.kt
> +            "USDt" -> {
t가 소문자인것은 오타인가요?

2019-08-22 13:54 UTC, sjjeong commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinFragment.kt
> +    lateinit var mView: View
view를 가지고 있을 필요가 없습니다.
필요한 부분에서는 getView()를 사용해주세요

2019-08-22 13:54 UTC, sjjeong commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinFragment.kt
> +            marketName = arguments!!.getString("market")
!! 대신 null safety하게 변경해주세요

2019-08-22 13:54 UTC, sjjeong commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinFragment.kt
> +    fun setData(data: ArrayList<UseCoinModel>) {
private 으로 변경해주세요
아래 initView(), requestData() 도 동일하게 변경해주세요

2019-08-22 13:54 UTC, sjjeong commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinFragment.kt
> +            bundle.putString("market", data)
"market"을 리터럴 문자로 사용하지말고 상수로 선언해서 사용해주세요

2019-08-22 13:54 UTC, sjjeong commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinFragment.kt
> +        setData(mData)
mData대신 result.map{}을 사용해서 처리해주세요
mData는 제거 해주세요.

2019-08-22 13:54 UTC, sjjeong commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/network/CoinRequest.kt
> +    fun marketSend(listener: BaseResult<ArrayList<Market>>) {
수정되지 않았습니다. 수정해주세요

2019-08-22 13:54 UTC, sjjeong commented on app/src/main/java/com/example/seonoh/seonohapp/MainActivity.kt
> +        coinViewPager.addOnPageChangeListener(object : TabLayout.TabLayoutOnPageChangeListener(tabLayout) {
로그만 찍는 용도라면 제거해주세요.

2019-08-23 01:25 UTC, seonoh commented on app/src/main/java/com/example/seonoh/seonohapp/model/CurrentPriceInfoModel.kt
> +    @Expose
네 수정했습니다 ! 
c345cf2

2019-08-23 01:29 UTC, seonoh commented on app/src/main/java/com/example/seonoh/seonohapp/model/Market.kt
> +    @Expose
네 수정했습니다 ! 
508bcb9

2019-08-23 01:30 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/model/UseCoinModel.kt
> +    val accTradePrice_24h: String
네 수정했습니다! 
ad8105e

2019-08-23 01:35 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/network/CoinRequest.kt
> +    private val mApi = api
네 수정했습니다 ! 
aa14d7a

2019-08-23 01:35 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/network/CoinRequest.kt
> +                } else {
네 수정했습니다 ! 
aa14d7a

2019-08-23 02:03 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/network/CoinRequest.kt
> +    fun marketSend(listener: BaseResult<ArrayList<Market>>) {
네 수정했습니다 ! 
aa14d7a

2019-08-23 02:03 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/network/CoinRequest.kt
> +        var single = mApi.getMarketAll()
네 수정했습니다 ! 
aa14d7a

2019-08-23 02:03 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/network/CoinRequest.kt
> +        var single = mApi.getCurrentPriceInfo(markets)
네 수정했습니다 ! 
aa14d7a

2019-08-23 02:03 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/network/CoinRequest.kt
> +                } else {
네 수정했습니다 ! 
aa14d7a

2019-08-23 02:03 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinFragment.kt
> +    fun setData(data: ArrayList<UseCoinModel>) {
네 수정했습니다!

e373365

2019-08-23 02:03 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinFragment.kt
> +            bundle.putString("market", data)
네 수정했습니다!

e373365

2019-08-23 02:03 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinFragment.kt
> +        setData(mData)
네 수정했습니다!

e373365

2019-08-23 02:08 UTC, seonoh commented on app/src/main/java/com/example/seonoh/seonohapp/MainActivity.kt
> +        coinViewPager.addOnPageChangeListener(object : TabLayout.TabLayoutOnPageChangeListener(tabLayout) {
네 수정했습니다

b84dd9a

2019-08-23 02:10 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/network/CoinRequest.kt
> +    fun marketSend(listener: BaseResult<ArrayList<Market>>) {
aa14d7a

2019-08-23 02:12 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/util/CalculateUtils.kt
> +            "USDt" -> {
ㅎㅎㅎ...네 감사합니다!

4405508

2019-08-23 02:13 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/util/CalculateUtils.kt
> +        if (marketName!!.contains("USDT")) {
네 수정했습니다!
4405508

2019-08-23 02:13 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/util/CalculateUtils.kt
> +        if (marketName!!.contains("USDT")) {
네 수정했습니다!
4405508

2019-08-23 02:27 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinAdapter.kt
> +        holder.bind(mData!![position])
네 감사합니다. 커밋남깁니다.
7896ebf

2019-08-23 02:28 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinAdapter.kt
> +    private val mData: ArrayList<UseCoinModel> by lazy { ArrayList<UseCoinModel>() }
네 감사합니다 !
7896ebf

2019-08-23 02:28 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinAdapter.kt
> +        val mView = LayoutInflater.from(parent.context).inflate(R.layout.coin_item, parent, false)
7896ebf

2019-08-23 02:28 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/TabPagerAdapter.kt
> +        mData = data
a2c58bd

2019-08-23 02:28 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/TabPagerAdapter.kt
> +    override fun getCount(): Int = if(::mData.isInitialized) mData.size else 0
a2c58bd

2019-08-23 02:29 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/MainActivity.kt
> +        initView(data)
d3de59a

2019-08-23 02:29 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/MainActivity.kt
> +    fun initView(data: ArrayList<String>) {
d3de59a

2019-08-23 02:29 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinAdapter.kt
> +        mData!!.addAll(data)
d2667c66ab59c847c11c8e48da83cc9eac5acef3

2019-08-23 02:32 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinAdapter.kt
> +    override fun getItemCount(): Int = mData!!.size
d2667c66ab59c847c11c8e48da83cc9eac5acef3

2019-08-23 10:53 UTC, sjjeong commented on app/src/main/java/com/example/seonoh/seonohapp/model/CurrentPriceInfoModel.kt
> +    @Expose
@seonoh 커밋 내용이 리뷰와 다릅니다.

2019-08-23 10:54 UTC, sjjeong commented on app/src/main/java/com/example/seonoh/seonohapp/model/CurrentPriceInfoModel.kt
> +    @Expose
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/181#discussion_r316945373 로 확인했습니다.

2019-08-23 10:55 UTC, sjjeong commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/network/RetrofitCreator.kt
> +    fun createClient() : OkHttpClient{
@seonoh 리뷰 반영해주세요.

2019-08-23 10:55 UTC, sjjeong commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/network/RetrofitCreator.kt
> +        val client = OkHttpClient.Builder()
@seonoh 리뷰 반영해주세요.

2019-08-23 10:55 UTC, sjjeong commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/util/CalculateUtils.kt
> +        if (marketName!!.contains("USDT")) {
@seonoh  수정되지 않았습니다.

2019-08-23 10:56 UTC, sjjeong commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinFragment.kt
> +    lateinit var mView: View
@seonoh 리뷰 반영해주세요.

2019-08-23 10:56 UTC, sjjeong commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinFragment.kt
> +            marketName = arguments!!.getString("market")
@seonoh 리뷰 반영해주세요.

2019-08-23 10:57 UTC, sjjeong commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinFragment.kt
> +            bundle.putString("market", data)
companion object 안에 private로 사용해주세요

2019-08-23 11:46 UTC, seonoh reviewed
감사합니다.

2019-08-23 11:46 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinFragment.kt
> +        mView.krwRecyclerView.apply {
네 감사합니다 !

187f505

2019-08-23 11:46 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinFragment.kt
> +            marketName = arguments!!.getString("market")
네 수정했습니다. 감사합니다!

2019-08-23 11:46 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinFragment.kt
> +    lateinit var mView: View
네 수정했습니다. 감사합니다 !

2019-08-23 11:46 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinFragment.kt
> +    lateinit var mView: View
187f5051e8a70f2029567fb6143774e00e59287a

2019-08-23 11:46 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinFragment.kt
> +            marketName = arguments!!.getString("market")
ef6964707d0e2d926b146d10d62e06a097b60bfd

2019-08-23 11:46 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinFragment.kt
> +            bundle.putString("market", data)
834b835

2019-08-23 11:58 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/network/RetrofitCreator.kt
> +    fun createClient() : OkHttpClient{
15366bdcb41397d94f4a181da31de38b6b853da2

2019-08-23 12:02 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/network/RetrofitCreator.kt
> +        val client = OkHttpClient.Builder()
15366bdcb41397d94f4a181da31de38b6b853da2

2019-08-23 12:02 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/util/CalculateUtils.kt
> +        if (marketName!!.contains("USDT")) {
af53eb7

2019-08-23 12:04 UTC, dino-prnd approved these changes
LGTM ✊ ✌️ 👋⭐️ 🌟 💫

2019-08-23 12:05 UTC, sjjeong approved these changes

2019-08-23 12:06 UTC, merged