HW-1 코인헬퍼 만들기
sjjeong/GoogryAndroidArchitecutreStudy pull request #182
Opened 2019-08-13 15:10 UTC by onemask

제가 만든 코인헬퍼의 구조는
MainActivity에서 upbitrepository를 통하여 API Call하고
ViewPager안에 TickerListFragment으로 Data를 보여주는 형태로 구현하였습니다. 

Package의 대략적인 구조는 
model - Upbit Data Model Request,Response model
uitl - data값으로 인한 %나 전일대비에 따른 컬러처리를 extension으로 처리하였습니다. 

3기때 들어 왔던 commit 내용도 있어서 
Commits on Aug 10, 2019 이후로 보시면 될거 같습니다.

2019-08-17 08:41 UTC, syli9526 commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/util/TextView.kt
> +fun TextView.setTradeAmount(accTradePrice24h : Double) {
코인헬퍼에서는 거래대금 포맷이 무조건 M이 붙는게 아니라 KRW, BTC, ETH, USDT가 다르더라구요!

2019-08-17 08:55 UTC, syli9526 commented
나머지부분은 고칠것이 없는거 같아요! 
필요 없는 코드도 없고, 코드 정리도 깔끔하게 잘 되어있어서 보기 편했어요! 
많이 배워갑니다ㅠㅠ

2019-08-18 09:46 UTC, onemask commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/util/TextView.kt
> +fun TextView.setTradeAmount(accTradePrice24h : Double) {
아하 감사합니다~
수정하였습니다. 
4a1a5b9

2019-08-18 10:44 UTC, syli9526 commented
수고하셨습니다!!

2019-08-19 09:19 UTC, ddaeyeonkim reviewed
1기 스터디 했던 김대연입니다
코드를 보고 제 생각을 리뷰로 남겼습니다. 다른 의견 주시면 감사히 받겠습니다!!

2019-08-19 09:19 UTC, ddaeyeonkim commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/repository/UpbitRepositoryImpl.kt
> +                val marketName = markets
처음 봤을때 변수명과 타입이 매칭이 잘 안되는거 같습니다

2019-08-19 09:19 UTC, ddaeyeonkim commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/MainActivity.kt
> +                val marketName = Array(keys.size){""}
이부분도 처음 봤을때 변수명과 타입이 매칭이 잘 안되는거 같아요

2019-08-19 09:19 UTC, ddaeyeonkim commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/MainActivity.kt
> +            .observeOn(AndroidSchedulers.mainThread())
repository 에서 이미 선언해서 중복 코드인 것 같습니다

2019-08-19 09:19 UTC, ddaeyeonkim commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/MainActivity.kt
> +                Timber.e("${it.printStackTrace()}")
timber 는 throwable 도 받아서 printStackTrace() 를 해주는 것으로 알고 있어요

2019-08-19 09:19 UTC, ddaeyeonkim commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/TickerListFragment.kt
> +            .observeOn(AndroidSchedulers.mainThread())
repository 에서 이미 선언해서 중복 코드인 것 같습니다

2019-08-19 09:19 UTC, ddaeyeonkim commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/adapter/CoinItemAdapter.kt
> +            textTotalTrade.setTradeAmount(ticker)
바인드 할 때마다 연산을 하게 되기 때문에 별도의 뷰에 필요한 데이터만을 담은 model 클래스로 분리하는게 어떨까요?

2019-08-19 09:19 UTC, ddaeyeonkim commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/adapter/CoinItemAdapter.kt
> +    private var dataSet: List<TickerResponse> = ArrayList()
역시 변수명만 봤을때는 List 가 아니라 Set 이 연상되는 것 같습니다
그리고 final 로 선언하는게 나을 것 같아요

2019-08-19 09:19 UTC, ddaeyeonkim commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/adapter/CoinItemAdapter.kt
> +        }
clear 해주고 addAll 하는게 나을 것 같습니다

2019-08-19 09:19 UTC, ddaeyeonkim commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/util/TextView.kt
> +                        amount < 1_000_000L -> {
중복되는 숫자 값은 상수화 해주는게 나을 것 같습니다

2019-08-19 09:19 UTC, ddaeyeonkim commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/adapter/ViewPagerAdapter.kt
> +    private var marketDataSet : Array<String>? = null
list 로 하면 nullable 하지 않아도 될 것 같습니다

2019-08-19 09:19 UTC, ddaeyeonkim commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/TickerListFragment.kt
> +            layoutManager = LinearLayoutManager(context)
layoutManager 를 xml 속성으로 선언하는건 어떨까요?

2019-08-19 09:19 UTC, ddaeyeonkim commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/MainActivity.kt
> +    @SuppressLint("CheckResult")
문제가 될 일은 거의 없겠지만 lifecycle 에 맞춰서 캔슬이 필요할 것 같습니다

2019-08-21 10:55 UTC, onemask commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/repository/UpbitRepositoryImpl.kt
> +                val marketName = markets
수정하였습니다~
018e215

2019-08-21 10:56 UTC, onemask commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/MainActivity.kt
> +            .observeOn(AndroidSchedulers.mainThread())
말씀해주신 부분 수정하였습니다.
7408347

2019-08-21 10:58 UTC, onemask commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/MainActivity.kt
> +                Timber.e("${it.printStackTrace()}")
말씀해주신 바를 제가 잘 이해한건지는 모르겠지만,
수정하였습니다 [b19524f] 
혹시 원하는 방향이 맞나요?

2019-08-21 10:58 UTC, onemask commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/TickerListFragment.kt
> +            .observeOn(AndroidSchedulers.mainThread())
해당 부분 
7408347 커밋에서 동일하게 처리하였습니다. 
감사합니다~

2019-08-21 11:04 UTC, onemask commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/adapter/CoinItemAdapter.kt
> +        }
ea7d63f 으로 수정하였습니다. 

기존에 제가 emptyList()로 List 초기화해주었다가 
dataSet?.let{ }//<- 해당 부분에서 nullable check 해주고 안에 data를 넣었는데,
혹시 clear해주고 addAll로 해주면 어떤 부분에서 더 이로운지 알 수 있을까요?  
@improve777

2019-08-21 11:06 UTC, onemask commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/util/TextView.kt
> +                        amount < 1_000_000L -> {
말씀 해 주신 부분 Constants.kt 라는 상수화된 파일을 새로 만들어 (54d1d56)
TextView.kt에서 Constatns.kt에 있는 값을 참조하도록 수정하였습니다. (c6c2c6c)

2019-08-21 11:06 UTC, onemask commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/adapter/ViewPagerAdapter.kt
> +    private var marketDataSet : Array<String>? = null
말씀 해 주신 부분 수정하였습니다. 
cc26f9a

2019-08-21 11:16 UTC, onemask commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/TickerListFragment.kt
> +            layoutManager = LinearLayoutManager(context)
06b0eb9 로 수정하였습니다~

2019-08-21 11:17 UTC, onemask commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/MainActivity.kt
> +    @SuppressLint("CheckResult")
MainActivity LifeCycle에 맞춰서 dispose() 되어야 한다는 말씀이신가요?

2019-08-21 18:44 UTC, improve777 commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/MainActivity.kt
> +                Timber.e("${it.printStackTrace()}")
네 맞습니다!

2019-08-21 18:47 UTC, improve777 commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/adapter/CoinItemAdapter.kt
> +        }
매번 인스턴스를 생성하지 않아도 되구요
datatSet 을 불변하게 들고 있을 수 있습니다
되도록이면 var 보다는 val 로 선언하기를 권장하고 있어요

2019-08-21 19:03 UTC, ddaeyeonkim commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/util/Constatns.kt
> +class TransactionAmount {
파일명에 오타가 있습니다 `Constatns.kt` -> `Constants.kt`

2019-08-21 19:03 UTC, ddaeyeonkim commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/repository/UpbitDataSource.kt
> +    fun getTikers(@Query("markets") markets : String? ): Single<List<TickerResponse>>
메서드 이름이 `getTickers` 인게 맞을 것 같습니다
변수의 타입을 붙일때는 콜론(:) 을 이름 바로 뒤에 붙이는걸 권장하고 있습니다
```suggestion
    fun getTickers(@Query("markets") markets: String?): Single<List<TickerResponse>>
```

2019-08-21 19:03 UTC, ddaeyeonkim commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/repository/UpbitRepository.kt
> +    fun getTikcers(margket : String) : Single<List<TickerResponse>>
오타인 것 같습니다
```suggestion
    fun getTickers(markets: String): Single<List<TickerResponse>>
```

2019-08-21 19:06 UTC, improve777 commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/adapter/ViewPagerAdapter.kt
> +class ViewpagerAdapter(fragmentManager : FragmentManager) :
카멜케이스로 해주는게 나을 것 같습니다
```suggestion
class ViewPagerAdapter(fragmentManager : FragmentManager) :
```

2019-08-21 19:06 UTC, improve777 commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/adapter/ViewPagerAdapter.kt
> +    FragmentPagerAdapter(fragmentManager){
deprecated 되어서 변경하는게 나을 것 같아요
```suggestion
    FragmentPagerAdapter(fragmentManager, BEHAVIOR_RESUME_ONLY_CURRENT_FRAGMENT) {
```

2019-08-22 11:38 UTC, onemask commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/MainActivity.kt
> +                val marketName = Array(keys.size){""}
수정하였습니다. 
8e700bb

2019-08-22 11:53 UTC, onemask commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/util/Constatns.kt
> +class TransactionAmount {
수정하였습니다.
457201b

2019-08-22 11:53 UTC, onemask commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/repository/UpbitDataSource.kt
> +    fun getTikers(@Query("markets") markets : String? ): Single<List<TickerResponse>>
오호 그렇군요 감사합니다 수정하였습니다.
ffad87e

2019-08-22 11:54 UTC, onemask commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/repository/UpbitRepository.kt
> +    fun getTikcers(margket : String) : Single<List<TickerResponse>>
꼼꼼히 봐주셔서 감사합니다. 수정하였습니다. 
ec54504

2019-08-22 11:54 UTC, onemask commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/adapter/ViewPagerAdapter.kt
> +class ViewpagerAdapter(fragmentManager : FragmentManager) :
수정하였습니다.
969708b

2019-08-22 12:03 UTC, onemask commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/adapter/ViewPagerAdapter.kt
> +    FragmentPagerAdapter(fragmentManager){
해당 리뷰에 대하여 찾아 볼 수 있어서 더 좋았습니다. 
리뷰 감사합니다 : ) 수정하였습니다.
7d88bb1

2019-08-22 13:25 UTC, sjjeong commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/adapter/CoinItemAdapter.kt
> +            textTotalTrade.setTradeAmount(ticker)
@onemask 
이 부분 빠진것같습니다.

2019-08-22 13:25 UTC, sjjeong commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/adapter/CoinItemAdapter.kt
> +    private var dataSet: List<TickerResponse> = ArrayList()
@onemask 
이 부분 빠진것같습니다.

2019-08-22 13:26 UTC, sjjeong commented
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/182#discussion_r315099836
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/182#discussion_r315100215

리뷰 답 해주세요

2019-08-22 14:01 UTC, sjjeong requested changes
전체적으로 reformat code 한번 해주면 좋을 것 같아요

2019-08-22 14:01 UTC, sjjeong commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/repository/UpbitRepository.kt
> +    fun getTickers(margket: String): Single<List<TickerResponse>>
오타 수정해주세요

2019-08-22 14:01 UTC, sjjeong commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/repository/UpbitDataSource.kt
> +interface UpbitDataSource {
이름은 UpbitApi정도가 좋을 것 같습니다.

2019-08-23 11:08 UTC, onemask commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/adapter/CoinItemAdapter.kt
> +            textTotalTrade.setTradeAmount(ticker)
수정하였습니다. 
0c6a944,
7bd245b,
e51139b,
0cd5cf0

2019-08-23 11:09 UTC, onemask commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/adapter/CoinItemAdapter.kt
> +    private var dataSet: List<TickerResponse> = ArrayList()
수정하였습니다. 
f0ac8b9

2019-08-23 11:09 UTC, onemask commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/repository/UpbitRepository.kt
> +    fun getTickers(margket: String): Single<List<TickerResponse>>
수정하였습니다. 
154bd54

2019-08-23 11:10 UTC, onemask commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/repository/UpbitDataSource.kt
> +interface UpbitDataSource {
수정하였습니다.
b034e06

2019-08-23 11:10 UTC, onemask commented
수정하였습니다~

2019-08-23 11:11 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-08-23 14:48 UTC, merged