Class04/jskim5923
sjjeong/GoogryAndroidArchitecutreStudy pull request #183
Opened 2019-08-15 09:44 UTC by jskim5923

HW-1 코인헬퍼-업비트 리스트 구현

2019-08-16 03:22 UTC, seonoh reviewed
앗 ㅎㅎ 언더바여서 데이터 클래스를 이렇게해도 됬었군요...

2019-08-16 03:30 UTC, seonoh commented
제가 리뷰해드릴만한 코드가 없는 것 같습니다....ㅎㅎ 저랑 코드짜는 방식이 비슷한 부분외에는 저보다 잘 짜신 것 같아요!! 리뷰하면서 느낀점은 저 같은 경우에는 커밋을 엄청 많이했는데 ( 이부분은 잘한거라고 생각합니다.) 수정된 부분에 대해서는 돌아가서 커밋한게아니라 뒷부분에 다시 커밋을 올렸는데 이 부분 정말 죄송하게 생각합니다 ㅎㅎ

2019-08-17 15:03 UTC, sjjeong requested changes

2019-08-17 15:03 UTC, sjjeong commented on jskim5923/ArchitectureStudy/app/build.gradle
> +    implementation 'androidx.recyclerview:recyclerview:1.1.0-beta02'
com.google.android.material:material에 recyclerview가 포함되어있는데
다른버전인 beta02를 사용해야하는 이유가 어떤건가요?

2019-08-17 15:03 UTC, sjjeong commented on jskim5923/ArchitectureStudy/app/src/main/java/com/jskim5923/architecturestudy/adapter/CoinListAdapter.kt
> +class CoinListAdapter(private val itemList: List<Ticker>) :
리스트를 생성자를 통해서 전달받지말고
내부에서 객체를 생성하고 함수를 통해 데이터를 받게 해주세요

2019-08-17 15:03 UTC, sjjeong commented on jskim5923/ArchitectureStudy/app/src/main/java/com/jskim5923/architecturestudy/api/ApiManager.kt
> +            .addConverterFactory(GsonConverterFactory.create(Gson()))
create()와 동일한 내용입니다.
Gson()객체를 만들어서 넘겨줄 필요가 없습니다.

2019-08-17 15:03 UTC, sjjeong commented on jskim5923/ArchitectureStudy/app/src/main/java/com/jskim5923/architecturestudy/model/Market.kt
> +    val english_name: String,
camelCase를 지켜주세요

2019-08-17 15:03 UTC, sjjeong commented on jskim5923/ArchitectureStudy/app/src/main/java/com/jskim5923/architecturestudy/model/Ticker.kt
> +    val trade_date: String,
camelCase를 지켜주세요

2019-08-17 15:03 UTC, sjjeong commented on jskim5923/ArchitectureStudy/app/src/main/java/com/jskim5923/architecturestudy/ui/CoinFragment.kt
> +    companion object {
companion object는 클래스 맨 아래로 가야합니다.

2019-08-17 15:03 UTC, sjjeong commented on jskim5923/ArchitectureStudy/app/src/main/java/com/jskim5923/architecturestudy/ui/CoinFragment.kt
> +    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
onViewCreate보다 onActivityCreate시점에 처리해주는게 좋습니다.

2019-08-17 15:03 UTC, sjjeong commented on jskim5923/ArchitectureStudy/app/src/main/java/com/jskim5923/architecturestudy/ui/CoinFragment.kt
> +        recyclerView.layoutManager = LinearLayoutManager(requireActivity())
동적으로 변하는게 아니라면 xml에서 처리해주세요

2019-08-17 15:03 UTC, sjjeong commented on jskim5923/ArchitectureStudy/app/src/main/java/com/jskim5923/architecturestudy/ui/CoinFragment.kt
> +                ApiManager.coinApi.getTicker(market)
flatmap으로 처리하는게 좋습니다.

2019-08-17 15:03 UTC, sjjeong commented on jskim5923/ArchitectureStudy/app/src/main/java/com/jskim5923/architecturestudy/ui/CoinFragment.kt
> +                        recyclerView.adapter = CoinListAdapter(tickerList)
adapter를 set하는 것과 데이터를 넣어주는 시점을 분리해주세요.

2019-08-17 15:03 UTC, sjjeong commented on jskim5923/ArchitectureStudy/app/src/main/java/com/jskim5923/architecturestudy/ui/MainActivity.kt
> +                }.distinct()
```kotlin
marketList.map {
    it.market.getCoinCurrency()
}.distinct()
```
작업을
subscribeOn과 observeOn 사이에 rx operator인 map를 사용해 처리해주세요

2019-08-17 15:03 UTC, sjjeong commented on jskim5923/ArchitectureStudy/app/src/main/java/com/jskim5923/architecturestudy/ui/MainActivity.kt
> +    private fun setViewPager(titleList: List<String>) {
ViewPager를 setup하는 부분과 data를 notify해주는 부분을 분리해주세요

2019-08-18 05:19 UTC, jskim5923 commented on jskim5923/ArchitectureStudy/app/build.gradle
> +    implementation 'androidx.recyclerview:recyclerview:1.1.0-beta02'
[3a239cd](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/183/commits/3a239cda6eebec7630792697f8fc28dea371009e) 적용했습니다.

2019-08-18 06:44 UTC, jskim5923 commented on jskim5923/ArchitectureStudy/app/src/main/java/com/jskim5923/architecturestudy/adapter/CoinListAdapter.kt
> +class CoinListAdapter(private val itemList: List<Ticker>) :
[4ad6c](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/183/commits/4ad6c4a0e600420171f6830ade4828ed7e69da15) 적용 완료

2019-08-18 06:46 UTC, jskim5923 commented on jskim5923/ArchitectureStudy/app/src/main/java/com/jskim5923/architecturestudy/api/ApiManager.kt
> +            .addConverterFactory(GsonConverterFactory.create(Gson()))
[4c38b341](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/183/commits/4c38b3413b73c3220b5370dc2ddffd54628f7a07) 적용완료

2019-08-18 06:50 UTC, jskim5923 commented on jskim5923/ArchitectureStudy/app/src/main/java/com/jskim5923/architecturestudy/model/Market.kt
> +    val english_name: String,
[50978680](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/183/commits/5097868080aa5a8205a8b126121dea5d2ad1055f) 수정 완료

2019-08-18 06:58 UTC, jskim5923 commented on jskim5923/ArchitectureStudy/app/src/main/java/com/jskim5923/architecturestudy/model/Ticker.kt
> +    val trade_date: String,
[9f0be70b](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/183/commits/9f0be70bb8e620dc329fb372c5b75030e45e900d) 적용 완료

2019-08-18 07:00 UTC, jskim5923 commented on jskim5923/ArchitectureStudy/app/src/main/java/com/jskim5923/architecturestudy/ui/CoinFragment.kt
> +    companion object {
[8a581258](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/183/commits/8a581258f4bc83f0d277f87a4f133db763f57ee9) 적용 완료

2019-08-18 07:03 UTC, jskim5923 commented on jskim5923/ArchitectureStudy/app/src/main/java/com/jskim5923/architecturestudy/ui/CoinFragment.kt
> +    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
[bd7c7099](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/183/commits/bd7c7099e43bc11efea2bf0a5d3655622813a8c5) 적용 완료

2019-08-18 07:05 UTC, jskim5923 commented on jskim5923/ArchitectureStudy/app/src/main/java/com/jskim5923/architecturestudy/ui/CoinFragment.kt
> +        recyclerView.layoutManager = LinearLayoutManager(requireActivity())
[705deb3c](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/183/commits/705deb3c0b05a6f4266224a4f74bbc2be617df62) 적용 완료

2019-08-18 07:20 UTC, jskim5923 commented on jskim5923/ArchitectureStudy/app/src/main/java/com/jskim5923/architecturestudy/ui/CoinFragment.kt
> +                ApiManager.coinApi.getTicker(market)
[08706875](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/183/commits/0870687591ef7faacfe9938249b1e4215fd56a52) 적용 완료

2019-08-18 07:23 UTC, jskim5923 commented on jskim5923/ArchitectureStudy/app/src/main/java/com/jskim5923/architecturestudy/ui/CoinFragment.kt
> +                        recyclerView.adapter = CoinListAdapter(tickerList)
[4ad6c](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/183/commits/4ad6c4a0e600420171f6830ade4828ed7e69da15) 적용 완료

2019-08-18 07:26 UTC, jskim5923 commented on jskim5923/ArchitectureStudy/app/src/main/java/com/jskim5923/architecturestudy/ui/MainActivity.kt
> +                }.distinct()
[387598f1f](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/183/commits/387598f1f4d25ba91cc97c1d0a7cdb0019b5630d) 적용 완료

2019-08-18 07:36 UTC, jskim5923 commented on jskim5923/ArchitectureStudy/app/src/main/java/com/jskim5923/architecturestudy/ui/MainActivity.kt
> +    private fun setViewPager(titleList: List<String>) {
[38cf95b8](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/183/commits/38cf95b8440de780042fc42b75d0a415efa39559) 적용 완료

2019-08-19 04:05 UTC, sjjeong requested changes

2019-08-19 04:05 UTC, sjjeong commented on jskim5923/ArchitectureStudy/app/src/main/java/com/jskim5923/architecturestudy/adapter/CoinListAdapter.kt
> +        this.itemList = itemList
외부에 있는 객체와 내부에 있는 객체가 공유되고 있습니다.
데이터만 넣어주는 방식으로 변경해주세요

2019-08-19 04:05 UTC, sjjeong commented on jskim5923/ArchitectureStudy/app/src/main/java/com/jskim5923/architecturestudy/adapter/ViewPagerAdapter.kt
> +        titleList = itemList
Adapter 내부에서 사용하는 list와 외부에 있는 list가 같은 객체가 되지 않도록 해주세요

2019-08-20 13:12 UTC, sjjeong approved these changes
pr이 만들어지고 나서 리뷰가 진행 된 상태라면 force push 하지 말아주세요.

2019-08-20 13:13 UTC, sjjeong commented
force push때문에 해당 https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/183#discussion_r314970276 이 없어져서 기록을 알 수 없습니다.

2019-08-20 13:27 UTC, jskim5923 commented
> force push때문에 해당 [#183 (comment)](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/183#discussion_r314970276) 이 없어져서 기록을 알 수 없습니다.



> force push때문에 해당 [#183 (comment)](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/183#discussion_r314970276) 이 없어져서 기록을 알 수 없습니다.



> pr이 만들어지고 나서 리뷰가 진행 된 상태라면 force push 하지 말아주세요.



> force push때문에 해당 [#183 (comment)](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/183#discussion_r314970276) 이 없어져서 기록을 알 수 없습니다.

알겠습니다!

2019-08-20 13:27 UTC, merged