HW-1 코인헬퍼 카피앱 만들기
sjjeong/GoogryAndroidArchitecutreStudy pull request #184
Opened 2019-08-15 11:40 UTC by syli9526

2019-08-16 09:07 UTC, onemask reviewed
접근 제어자랑 Extension들 좀 더 추가하면 좋을거 같아요~
수고하셨습니다

2019-08-16 09:07 UTC, onemask commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/CoinFragment.kt
> +    var currencyList: List<String>? = null
currencyList를 CoinFragment에서만 사용하면 접근제어자를 붙이는게 좋을거 같아요.

2019-08-16 09:07 UTC, onemask commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/CoinFragment.kt
> +        coinAdapter = CoinAdapter(requireContext(), this)
[SOLID](http://www.nextree.co.kr/p6960/)를 참고하여

CoinAdapter 생성하는걸 onActivityCreated()안에서 한꺼번에 처리하지 말고 
setAdapter나 소율님이 알 수 있는 Adapter를 Setting 한다는 의미의 함수를 만드셔서 
RecyclerAdatper 처리하면 좋을거 같아요.

2019-08-16 09:07 UTC, onemask commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/CoinFragment.kt
> +            adapter = coinAdapter
보니까 item 마다 Decoration이 없는데 
해당 lamda안에 
`            //addItemDecoration(DividerItemDecoration(context,1))
`
를 추가하셔서 item Decoration도 추가하여야 할거 같아요

2019-08-16 09:07 UTC, onemask commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/CoinFragment.kt
> +    override fun onActivityCreated(savedInstanceState: Bundle?) {
저도 이건 확신이 없는데 Fragment에서 RecyclerView를 Set 하는거는
onActivityCreated()보다는 onViewCreated()에서 하는 경우가 best라고 하네요. 
저도 해당 부분에 대해서는 좀 더 찾아봐서 자세하게 알려드릴께요! 
https://stackoverflow.com/questions/52522649/fragment-recyclerview-oncreateview-onviewcreated-or-onactivitycreated?rq=1

2019-08-16 09:07 UTC, onemask commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/CoinFragment.kt
> +                        when (cur) {
util에 TextView extension을 따로 만들면 더 깔끔할꺼 같아요
관련 예제 Repo 링크 첨부하겠습니다. 
[KotlinExtension](https://github.com/ravidsrk/kotlinextensions.com)

2019-08-16 09:07 UTC, onemask commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/MainActivity.kt
> +    fun getInfomation() {
Information 오타 수정과, private fun getInfomation()라고 하면 더 좋을거 같아요.

2019-08-16 09:07 UTC, onemask commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/MainActivity.kt
> +        UpbitRequest().getMarketInfo(object : UpbitListener<MarketResponse> {
getInformation()은 retorift 이용해서 data call 하는 부분인데 TabLayout 정의하는 부분도 있어서 
해당 부분은 밖으로 빼는게 좋을 듯합니다.

2019-08-16 09:07 UTC, onemask commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/MainActivity.kt
> +                        override fun onTabSelected(p0: TabLayout.Tab) {
tabSelected안에 내용도 추가해야 각 탭을 클릭할시 ViewPager 내용이 바뀔거 같은데요 
저도 해당 부분 좀더 좋은 방법 이전에 다른분이 알려주셔서  링크 첨부합니다. 
> 뷰페이저와 탭레이아웃을 간단하게 연동하는 방법이 있습니다. (클릭이벤트 포함) 자세한 내용은 아래 링크에 있습니다.
https://m.blog.naver.com/PostView.nhn?blogId=pistolcaffe&logNo=220629248791&proxyReferer=https%3A%2F%2Fwww.google.com%2F

2019-08-16 09:07 UTC, onemask commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/adapter/CoinAdapter.kt
> +        val height = parent.measuredHeight / 10
R.layout.list_item 에 최상단 View
` android:layout_width="match_parent"
    android:layout_height="30dp"`
이렇게 바꾸면 
        `val height = parent.measuredHeight / 10`
계산 하는부분 없어도 될거 같아요.

2019-08-16 09:07 UTC, onemask commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/adapter/CoinAdapter.kt
> +class CoinAdapter(private val context: Context, private val listener: CoinItemRecyclerViewClickListener) :
CoinAdapter안에 parameter로 Context 넘기는게 나중에 setTextColor 때문인가요? 
Extension으로 해당 부분 빼면 parameter로 Context 넘기지 않아도 될거 같아요.

2019-08-16 09:07 UTC, onemask commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/adapter/CoinAdapter.kt
> +    interface CoinItemRecyclerViewClickListener {
CoinItemRecyclerViewClickListener 부분도
현재 아이템 클릭하고 어떤 이벤트 없어도 생략해도 될거 같아요.

2019-08-16 09:07 UTC, onemask commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/adapter/ViewHolder.kt
> +    fun bind(context: Context, coinInfo: CoinInfo, listener: CoinAdapter.CoinItemRecyclerViewClickListener) {
bind()에도 context,listener 파라미터 정리되면 CoinAdapter가 더 깔끔해질거 같아요~

2019-08-16 09:07 UTC, onemask commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/adapter/CoinAdapter.kt
> +    override fun onBindViewHolder(holder: ViewHolder, position: Int) = holder.bind(context, coinList[position], listener)
ViewHolder bind()에서 파라미터 정리하면 해당 부분 더 깔끔해질거 같아요~

2019-08-16 09:07 UTC, onemask commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/adapter/ViewHolder.kt
> +    private val tvCoinName = itemView.findViewById(R.id.tv_coin_name) as TextView
Kotlin에서 알아서 findViewId에서 TypeCast 가능해서 as로 TextView라고 알려주지 않아도 되서 as 뒤 TextView는 생략해도 될거 같아요.

2019-08-16 09:07 UTC, onemask commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/adapter/ViewPagerAdapter.kt
> +    val context: Context,
private이라고 접근제어자 주면 좋을거 같아요.

2019-08-16 09:07 UTC, onemask commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/adapter/ViewPagerAdapter.kt
> +    val pageList: List<Int>,
private이라고 접근제어자 주면 좋을거 같아요.

2019-08-16 09:07 UTC, onemask commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/adapter/ViewPagerAdapter.kt
> +    val marketList: List<MarketResponse>
private이라고 접근제어자 주면 좋을거 같아요.

2019-08-16 09:07 UTC, onemask commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/adapter/ViewPagerAdapter.kt
> +        marketList.filter { it.market.split("-")[0] == context.getString(pageList[position]) }.map { it.market } as ArrayList<String>
<img width="1523" alt="스크린샷 2019-08-16 오후 5 11 11" src="https://user-images.githubusercontent.com/27774564/63153289-eb567180-c048-11e9-964e-8479c9c37a67.png">
저 (pageList[position]) } 사이에 있는 회색줄을 뭐라고 칭해야 할지 모르겠는데 
저 라인을 넘으면 줄바꿈하는게 좋다고 들었어요~

2019-08-16 09:07 UTC, onemask commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/util/ApiService.kt
> +package com.example.architecturestudy.util
API 통신하는 코드는 
package명을 netowrk로 변경해서 관리하는게 더 좋을거 같아요.

2019-08-16 09:07 UTC, onemask commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/util/UpbitRequest.kt
> +    val url = "https://api.upbit.com"
private 접근 제어자 앞에 추가하면 좋을거 같아요.

2019-08-16 09:07 UTC, onemask commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/util/UpbitRequest.kt
> +        val retrofit = Retrofit.Builder()
retrofit 변수가 apicall하는 뿐마다 초기화 되고 있는거 같아서 UpbitRequest 상위 클래스 내에 
 
private val apiService = Retrofit.Builder()
        .baseUrl(url)
        .addConverterFactory(GsonConverterFactory.create())
        .build()
        .create(ApiService::class.java)

로 하면 getMarketInfo(), getTickerInfo() 안에 retofit과 apiService 변수 생성해주지 않아도 될거 같아요.

2019-08-16 09:07 UTC, onemask commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/util/UpbitRequest.kt
> +        apiService.getMarketData()?.enqueue(object : Callback<List<MarketResponse>> {
apiService.getMarketData()?에서 nullSafety는 체크하지 않아도 될거 같아요

2019-08-16 09:07 UTC, onemask commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/util/UpbitRequest.kt
> +            }
let으로 두번 감싸도 되지만 
` response.body()?.let {
                    listenser.onResponse(it)
                }?:run { listenser.onFailure("null") }`
이렇게 하면 좀더 안전하게 null 처리를 할 수 있습니답.

2019-08-16 09:07 UTC, onemask commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/util/UpbitRequest.kt
> +    fun getTickerInfo(listenser: UpbitListener<TickerResponse>, name: String) {
listenser 오타 수정해야 할거 같아요.

2019-08-16 09:07 UTC, onemask commented on syli9526/ArchitectureStudy/app/src/main/res/layout/list_item.xml
> +        android:layout_height="match_parent"
android:layout_height="match_parent" ->
        android:layout_height="30dp"
로 수정하면 CoinAdapter에서 height안구해도 될거 같아요.

2019-08-18 07:52 UTC, syli9526 commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/CoinFragment.kt
> +    var currencyList: List<String>? = null
[3f041ce](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/184/commits/3f041cec4d00aa38819b7042a63e41fe6ba04095) 
수정했습니다

2019-08-18 07:53 UTC, syli9526 commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/CoinFragment.kt
> +        coinAdapter = CoinAdapter(requireContext(), this)
[d684af4](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/184/commits/d684af4023db875b60d81bba967028860851025f)
수정했습니다

2019-08-18 07:56 UTC, syli9526 commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/CoinFragment.kt
> +            adapter = coinAdapter
[cbcf8ad](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/184/commits/cbcf8ad33dd79eb87371f9f5a8710044d7c537a9)
수정했습니다.

2019-08-18 08:03 UTC, syli9526 commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/CoinFragment.kt
> +    override fun onActivityCreated(savedInstanceState: Bundle?) {
[d684af4](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/184/commits/d684af4023db875b60d81bba967028860851025f)
수정했습니다. 이것저것 찾아봤는데 잘 안나와서 일단 고쳤어요! 더 찾아볼께요!

2019-08-18 08:04 UTC, syli9526 commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/CoinFragment.kt
> +                        when (cur) {
[25710d1](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/184/commits/25710d1c46f5ef9470eba34a4bf443ba017c9bb0)
수정했습니다! 👍

2019-08-18 08:05 UTC, syli9526 commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/util/UpbitRequest.kt
> +        val retrofit = Retrofit.Builder()
[f85e0ab](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/184/commits/f85e0ab68103002495e3683d3e6d6f00705b6554)
수정했습니다.

2019-08-18 08:06 UTC, syli9526 commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/util/UpbitRequest.kt
> +        apiService.getMarketData()?.enqueue(object : Callback<List<MarketResponse>> {
[0873f28](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/184/commits/0873f28ef77febebdb84af769b5c4b610a7b4b3f)
수정했습니다.

2019-08-18 08:07 UTC, syli9526 commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/util/UpbitRequest.kt
> +            }
[a1ab5f8](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/184/commits/a1ab5f8a8ffbefef60de30e88e407779c626787f)
수정했습니다!

2019-08-18 08:08 UTC, syli9526 commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/util/UpbitRequest.kt
> +    fun getTickerInfo(listenser: UpbitListener<TickerResponse>, name: String) {
[6e4796b](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/184/commits/6e4796b44d9c641dc9528ce3ba72c8d93a42269b)
수정했습니다

2019-08-18 08:09 UTC, syli9526 commented on syli9526/ArchitectureStudy/app/src/main/res/layout/list_item.xml
> +        android:layout_height="match_parent"
[2ca77d6](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/184/commits/2ca77d622fa6aa2758f3a58e6a512e0e6b97ddcc)
수정했습니다.

2019-08-18 08:12 UTC, syli9526 commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/MainActivity.kt
> +    fun getInfomation() {
[6e4796b](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/184/commits/6e4796b44d9c641dc9528ce3ba72c8d93a42269b) 
수정했습니다.

2019-08-18 08:20 UTC, syli9526 commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/MainActivity.kt
> +        UpbitRequest().getMarketInfo(object : UpbitListener<MarketResponse> {
[0e8e006](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/184/commits/0e8e006ce5f9f614a405e7e04767641c3200d833)
수정했습니다

2019-08-18 08:35 UTC, syli9526 commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/adapter/CoinAdapter.kt
> +        val height = parent.measuredHeight / 10
[ac95c5d](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/184/commits/ac95c5d4b00a11f26bfe7a478a6e2e7f02a1985d)
수정했습니다.

2019-08-18 08:35 UTC, syli9526 commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/adapter/CoinAdapter.kt
> +class CoinAdapter(private val context: Context, private val listener: CoinItemRecyclerViewClickListener) :
textView extension하면서 수정 했습니다!

2019-08-18 08:36 UTC, syli9526 commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/adapter/CoinAdapter.kt
> +    interface CoinItemRecyclerViewClickListener {
[6f2109f](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/184/commits/6f2109fb6c87a36d6030698eaf551c453434a03d)
수정했습니다.

2019-08-18 08:37 UTC, syli9526 commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/adapter/ViewHolder.kt
> +    fun bind(context: Context, coinInfo: CoinInfo, listener: CoinAdapter.CoinItemRecyclerViewClickListener) {
textView extension하면서 수정 했습니다!

2019-08-18 08:37 UTC, syli9526 commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/adapter/CoinAdapter.kt
> +    override fun onBindViewHolder(holder: ViewHolder, position: Int) = holder.bind(context, coinList[position], listener)
textView extension하면서 수정 했습니다!

2019-08-18 08:38 UTC, syli9526 commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/adapter/ViewHolder.kt
> +    private val tvCoinName = itemView.findViewById(R.id.tv_coin_name) as TextView
[e50e421](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/184/commits/e50e421fcda8b15a863461d75309476c08fea3a9)
수정했습니다.

2019-08-18 08:41 UTC, syli9526 commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/adapter/ViewPagerAdapter.kt
> +        marketList.filter { it.market.split("-")[0] == context.getString(pageList[position]) }.map { it.market } as ArrayList<String>
[6094d39](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/184/commits/6094d39344af02d7fa8184284115cc07c041b54f)
수정했습니다.

2019-08-18 08:42 UTC, syli9526 commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/util/ApiService.kt
> +package com.example.architecturestudy.util
[d570589](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/184/commits/d57058903e9f2a185d2878854fbf21a5e60c7ee6)
수정했습니다.

2019-08-18 08:59 UTC, syli9526 commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/MainActivity.kt
> +                        override fun onTabSelected(p0: TabLayout.Tab) {
[abe8d7f](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/184/commits/abe8d7f21e8d2c7523f96fbf9e6dd589cad6f79f)
해당부분은 링크 내용을 좀더 읽어보고 공부한뒤에 더 좋은방법으로 고쳐보도록하겠습니다 ㅠ

2019-08-18 10:22 UTC, onemask reviewed
수고하셨어요-
* 사용하지 않는 import 제거
* USDT 거래대금 K 붙는 부분 수정
만 하시면 석준님 리뷰 받으면 될거 같아요~

2019-08-18 10:22 UTC, onemask commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/adapter/ViewHolder.kt
> +import android.content.Context
import android.content.Context
사용하지 않는 import는 제거해야할거 같습니답. 

안드로이드 스튜디오에서서 commit할때 
Before commit > Optimize import 되어 있는지 확인해보시면 좋을거 같아요
<img width="893" alt="스크린샷 2019-08-18 오후 7 08 42" src="https://user-images.githubusercontent.com/27774564/63223188-c6026880-c1ec-11e9-969b-4e14c0bbb147.png">

2019-08-18 10:22 UTC, onemask commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/util/TextView.kt
> +            ) + " K"
그 저도 이 부분 헷갈렸는데 ㅠㅠ USDT에서 K만 붙는게 아닌것 같더라구요.
https://github.com/sjjeong/CoinHelper/blob/for_developer/app/src/main/java/com/googry/coinhelper/ext/TextViewExt.kt 
이부분이 석준님 코인헬퍼 TextView.kt 부분인데 참고해서 수정하시면 좋을거 같아요~

2019-08-18 10:46 UTC, syli9526 commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/adapter/ViewHolder.kt
> +import android.content.Context
[8883c4a](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/184/commits/8883c4a14b81d443480a9538250431edc17bced6)
수정했습니다!

2019-08-18 10:46 UTC, syli9526 commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/util/TextView.kt
> +            ) + " K"
[9eb78e8](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/184/commits/9eb78e872a3d8b7c8a620521cfdf3d2223bb6ae7)
수정했습니다!

2019-08-18 10:51 UTC, onemask commented
수고하셨습니당

2019-08-19 14:19 UTC, ddaeyeonkim reviewed
1기 스터디했던 김대연입니다!
제 견해를 리뷰로 올려봤습니다. 혹시 제가 틀린 부분이거나 다른 의견 주신다면 감사히 받겠습니다!!

2019-08-19 14:19 UTC, ddaeyeonkim commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/network/UpbitListener.kt
> +    fun onResponse(dataList: List<T>)
나중에 기능을 추가하게 된다면 
무조건 list 만 들어오지 않는 경우도 있을 수 있기 때문에 리스트 타입으로 제한하지 않는게 좋을것 같아요

2019-08-19 14:19 UTC, ddaeyeonkim commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/util/TextView.kt
> +import android.widget.TextView
원래 TextView 클래스가 있기 때문에 파일명을 바꾸는게 좋을것 같아요

2019-08-19 14:19 UTC, ddaeyeonkim commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/CoinInfo.kt
> +data class CoinInfo(
model 패키지로 옮기는게 나을 것 같아요

2019-08-19 14:19 UTC, ddaeyeonkim commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/CoinFragment.kt
> +    private lateinit var coinAdapter: CoinAdapter
lazy 패턴을 쓰는게 어떨까요?

2019-08-19 14:19 UTC, ddaeyeonkim commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/CoinFragment.kt
> +        currencyList = arguments?.getStringArrayList(CURRENCY_LIST)
사실 필요한건 currencyList 가 joinToString 된 String 이어서 번들로 받을때 String 으로 받는게 나을 것 같습니다

2019-08-19 14:19 UTC, ddaeyeonkim commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/CoinFragment.kt
> +                        val coin = it.market.split("-")[1]
it.market.split("-") 을 두번 하지 않는게 좋을 것 같아요

2019-08-19 14:19 UTC, improve777 commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/CoinFragment.kt
> +                        list.add(CoinInfo(cur, coin, price, compare, amount))
CoinInfo 를 생성할때 파라미터가 많을 때는 이름을 명시해주는게 좋을 것 같아요
```
    CoinInfo(
        currencyType = ~~~,
        coinName = ~~~,
        presentPrice = ~~~,
        signedChangeRate = ~~~,
        transactionAmount = ~~~
    )
```

2019-08-19 14:19 UTC, improve777 commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/CoinFragment.kt
> +            }, name)
파라미터로 할때 콜백은 뒤쪽에 하는게 가독성이 더 좋을 것 같아요
[prnd 가이드](https://github.com/PRNDcompany/android-style-guide/blob/master/Java.md)

2019-08-19 14:19 UTC, improve777 commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/adapter/ViewPagerAdapter.kt
> +        marketList.filter { it.market.split("-")[0] == context.getString(pageList[position])}
매번 계산하기보다 join 한 markets 의 리스트를 들고 있는게 나을 것 같아요

2019-08-21 16:54 UTC, syli9526 commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/network/UpbitListener.kt
> +    fun onResponse(dataList: List<T>)
음.. 그러면 어떤것들이 들어올수있나요...??

2019-08-21 16:56 UTC, syli9526 commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/util/TextView.kt
> +import android.widget.TextView
[
6e24d27
](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/184/commits/6e24d27508f05ef8c7f7fc87b2efd16fbd5e3bf1)
수정하였습니다.

2019-08-21 16:57 UTC, syli9526 commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/CoinInfo.kt
> +data class CoinInfo(
[12b5f5a](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/184/commits/12b5f5acbcc58fe68718a33cb7feb3dfbbe2ffe4)
수정하였습니다.

2019-08-21 16:57 UTC, syli9526 commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/CoinFragment.kt
> +    private lateinit var coinAdapter: CoinAdapter
[47b4d06](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/184/commits/47b4d06884c26169e981f34cc84ac21db2eb612a)
수정하였습니다.

2019-08-21 16:59 UTC, syli9526 commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/CoinFragment.kt
> +        currencyList = arguments?.getStringArrayList(CURRENCY_LIST)
[83d3a77](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/184/commits/83d3a77fa2b7df51c02062059066c0f8801489c2)
수정하였습니다.

2019-08-21 16:59 UTC, syli9526 commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/adapter/ViewPagerAdapter.kt
> +        marketList.filter { it.market.split("-")[0] == context.getString(pageList[position])}
[83d3a77](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/184/commits/83d3a77fa2b7df51c02062059066c0f8801489c2)
수정하였습니다.

2019-08-21 17:00 UTC, syli9526 commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/CoinFragment.kt
> +            }, name)
[a735c22](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/184/commits/a735c221f9f57473047d528726c27f5733d826df)
수정하였습니다.

2019-08-21 17:01 UTC, syli9526 commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/CoinFragment.kt
> +                        list.add(CoinInfo(cur, coin, price, compare, amount))
[dfa2012](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/184/commits/dfa2012765d5606800d8eed1e38a1ed7ccb10c33)
수정하였습니다.

2019-08-21 17:02 UTC, syli9526 commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/CoinFragment.kt
> +                        val coin = it.market.split("-")[1]
[e26f82b](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/184/commits/e26f82b49c61c88cb3eaf1ce1173379049a7433e)
수정하였습니다.

2019-08-21 18:23 UTC, improve777 commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/network/UpbitService.kt
> +class UpbitService {
인스턴스를 `getInstance()` 로만 가져올 수 있어야 합니다
```suggestion
class UpbitService private constructor() {
```

2019-08-21 18:23 UTC, improve777 commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/MainActivity.kt
> +    private fun setPage(dataList: List<MarketResponse>){
view 를 초기화하는 로직과  market 데이터를 넣는 로직을 나눠주는게 좋을 것 같아요

2019-08-21 18:30 UTC, improve777 commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/network/ApiService.kt
> +    @GET("/v1/ticker?")
Query 의 경우 retrofit 에서 자체적으로 ? 를 붙여주도록 되어있기 때문에 생략 가능합니다
```suggestion
    @GET("/v1/ticker")
```

2019-08-21 18:39 UTC, improve777 commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/adapter/ViewHolder.kt
> +        tvTransactionAmount.setTradeAmount(coinInfo.currencyType, coinInfo.transactionAmount)
listview 에 bind 될 때마다 매번 데이터를 계산해서 넣어주게 되는데요
CoinInfo 에 저장할 때 뷰에서 보여주기 위한 데이터로 만들어주면 
setText() 만 할 수 있게 됩니다

2019-08-21 18:39 UTC, improve777 commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/CoinFragment.kt
> +                    dataList.forEach {
CoinFragment 에서 CoinInfo 로 만들어주지 않고 UpbitRequest 에서 만들어서 UpbitListener 로 받는건 어떨까요?

2019-08-21 20:32 UTC, improve777 commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/network/UpbitListener.kt
> +    fun onResponse(dataList: List<T>)
음.. 넵 이건 선택사항일 거 같아요

2019-08-22 02:18 UTC, syli9526 commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/network/UpbitService.kt
> +class UpbitService {
[f4119d8](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/184/commits/f4119d8a5a7c493ec51320edf71309ffec7a735a)
수정하였습니다.

2019-08-22 02:19 UTC, syli9526 commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/MainActivity.kt
> +    private fun setPage(dataList: List<MarketResponse>){
[2a4083f](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/184/commits/2a4083fed132fea743bf8ae39f782b730daf563b)
수정하였습니다.

2019-08-22 02:20 UTC, syli9526 commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/adapter/ViewHolder.kt
> +        tvTransactionAmount.setTradeAmount(coinInfo.currencyType, coinInfo.transactionAmount)
여기에서 말하는 계산이 textViewExt에서 하는 단위 계산을 의미하는 건가요??

2019-08-22 02:21 UTC, syli9526 commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/CoinFragment.kt
> +                    dataList.forEach {
[1aaf010](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/184/commits/1aaf01040950d8f6f18bbe3b8a5957fb78532d01) [e4e019c](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/184/commits/e4e019cc9e26d484bc0ba239a8cb5925da21e954)
수정하였습니다.

2019-08-22 02:21 UTC, improve777 commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/adapter/ViewHolder.kt
> +        tvTransactionAmount.setTradeAmount(coinInfo.currencyType, coinInfo.transactionAmount)
넵 맞습니다!!

2019-08-22 02:22 UTC, syli9526 commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/network/ApiService.kt
> +    @GET("/v1/ticker?")
[975ad5d](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/184/commits/975ad5d3671c73f54924ca529f8afb478daee7ee)
수정하였습니다.

2019-08-22 14:10 UTC, sjjeong requested changes

2019-08-22 14:10 UTC, sjjeong commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/network/UpbitRequest.kt
> +                        list.add(CoinInfo(currencyType, coinName, presentPrice, signedChangeRate, transactionAmount))
add 대신 map 함수를 사용 하시면 돼요
val list = it.map { }
lisetener.onResponse(list)

2019-08-22 14:10 UTC, sjjeong commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/adapter/CoinAdapter.kt
> +    private var coinList = mutableListOf<CoinInfo>()
val 로 선언해주세요

2019-08-22 14:10 UTC, sjjeong commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/adapter/ViewPagerAdapter.kt
> +            list.add((marketList.filter { it.market.split("-")[0] == context.getString(value) }
context를 Adapter 내부에서 사용하는 것보단 List<Int> 대신 List<String>으로 받아오게 해주세요
그렇게 하면 context를 받을 필요가 없게됩니다.

2019-08-22 14:10 UTC, sjjeong commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/CoinFragment.kt
> +        return return inflater.inflate(R.layout.fragment_list_coin, container, false)
return이 두개입니다. 하나 제거 해주세요

2019-08-22 14:10 UTC, sjjeong commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/CoinFragment.kt
> +        UpbitRequest().apply {
apply는 불필요해 보입니다.

2019-08-22 14:10 UTC, sjjeong commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/MainActivity.kt
> +            adapter = ViewPagerAdapter(supportFragmentManager, this@MainActivity, pageList, dataList)
data를 set하는 것과 ViewPagerApdater를 만드는 시점을 분리해주세요.
onCreate시점에 Adapter를 만들어서 set해주시고
setData시점에서는 data를 adapter에 넣어주는 역할만 해주세요

2019-08-23 03:32 UTC, syli9526 commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/adapter/ViewPagerAdapter.kt
> +            list.add((marketList.filter { it.market.split("-")[0] == context.getString(value) }
List 대신 List로 받아오게 하는게..무슨뜻인지.. 잘 모르겠어요..ㅠ

2019-08-23 09:50 UTC, syli9526 commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/network/UpbitRequest.kt
> +                        list.add(CoinInfo(currencyType, coinName, presentPrice, signedChangeRate, transactionAmount))
[e948fb1](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/184/commits/e948fb1b61e293c129330a92c95de6e322ecb18f)
수정하였습니다.

2019-08-23 09:51 UTC, syli9526 commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/adapter/CoinAdapter.kt
> +    private var coinList = mutableListOf<CoinInfo>()
[4016df0](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/184/commits/4016df0d92df30c53cc327406f50bc12ea109c0d)
수정하였습니다.

2019-08-23 09:51 UTC, syli9526 commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/CoinFragment.kt
> +        return return inflater.inflate(R.layout.fragment_list_coin, container, false)
[b5251d4](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/184/commits/b5251d40e43cb18d916c5d4a5d3a6cba5c1db5cf)
수정하였습니다.

2019-08-23 09:52 UTC, syli9526 commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/CoinFragment.kt
> +        UpbitRequest().apply {
[6bac6a2](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/184/commits/6bac6a2b1326b2175a1e6579bad1ad7092e476f2)
수정하였습니다.

2019-08-23 09:56 UTC, syli9526 commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/adapter/ViewPagerAdapter.kt
> +            list.add((marketList.filter { it.market.split("-")[0] == context.getString(value) }
[8ad7257](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/184/commits/8ad7257041b2fc64bcd2dda941ad5467a63e1ba5)
수정하였습니다.

2019-08-23 09:57 UTC, syli9526 commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/MainActivity.kt
> +            adapter = ViewPagerAdapter(supportFragmentManager, this@MainActivity, pageList, dataList)
[0c32302](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/184/commits/0c323027df7dec7bf8450b5e2c46be283af44aac), [8ef8ed5](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/184/commits/8ef8ed5fc25fcf62af584df6db157e269803c2db) 
수정하였습니다.

2019-08-23 10:00 UTC, syli9526 commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/adapter/ViewHolder.kt
> +        tvTransactionAmount.setTradeAmount(coinInfo.currencyType, coinInfo.transactionAmount)
이부분은 coinInfo에 넣어주는게 UpbitRequest로 변경하여서, 
그곳에서 하는게 맞는지 좀 고민해봐야할거같아요

2019-08-23 10:58 UTC, sjjeong commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/network/UpbitRequest.kt
> +                        list.add(CoinInfo(currencyType, coinName, presentPrice, signedChangeRate, transactionAmount))
변수명이 test라니.. ㅠ

2019-08-23 10:59 UTC, sjjeong submitted a review, later dismissed
LGTM ✊ ✌️ 👋

2019-08-23 11:00 UTC, syli9526 commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/network/UpbitRequest.kt
> +                        list.add(CoinInfo(currencyType, coinName, presentPrice, signedChangeRate, transactionAmount))
앜ㅋㅋㅋㅋㅋ 테스트해보고 안고쳤네요..ㅎㅎ
고치겠습니다..ㅎㅎ

2019-08-23 11:06 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-08-23 14:02 UTC, merged