HW-1 코인헬퍼 카피앱
sjjeong/GoogryAndroidArchitecutreStudy pull request #185
Opened 2019-08-17 11:58 UTC by toctocbin

2019-08-18 09:19 UTC, becooni requested changes
커밋이 잘 나뉘어 있어서 보기 수월했네요.

제가 남긴 리뷰 검토 하시고 궁금하신점은 질문 주세요.

ps. Assignees 본인 추가해주세요~

2019-08-18 09:19 UTC, becooni commented on toctocbin/AndroidArchitecture/app/build.gradle
> +    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
레거시 서포트 라이브러리를 추가한 이유가 있나요?

2019-08-18 09:19 UTC, becooni commented on toctocbin/AndroidArchitecture/app/build.gradle
> +    implementation 'com.android.support:design:28.0.0'
androidX 라이브러리 패키지를 사용한다면

com.google.android.material:material:1.0.0

추가하는게 좋겠네요.

2019-08-18 09:19 UTC, becooni commented on toctocbin/AndroidArchitecture/app/build.gradle
> +    implementation 'com.android.support:design:28.0.0'
https://developer.android.com/jetpack/androidx/migrate
저는 여기서 찾아서 씁니다.

2019-08-18 09:19 UTC, becooni commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/adpter/ViewpagerAdapter.kt
> +class ViewpagerAdapter(fm: FragmentManager?,
https://kotlinlang.org/docs/reference/coding-conventions.html#class-header-formatting

코틀린 클래스 선언시 생성자 인자가 길 경우,
여닫는 괄호 모두 개행해서 작성하는게 규칙이네요 :)

2019-08-18 09:19 UTC, becooni commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/MainActivity.kt
> +    private val fragmentList: ArrayList<Fragment> = ArrayList()
가변 리스트를 mutableListOf() 로 초기화하면 좀더 코틀린 스러울것 같네요 ㅎㅎ

2019-08-18 09:19 UTC, becooni commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/network/RetrofitService.kt
> +    fun loadMarketData(): Single<ArrayList<Market>>
불변 리스트가 아닌 가변리스트로 선언하신 이유가 있을까요?

2019-08-18 09:19 UTC, becooni commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/network/RetrofitClient.kt
> +            .baseUrl("https://api.upbit.com/v1/")
BaseUrl을

https://api.upbit.com/

이렇게만 설정해주는게 좋다고 생각합니다.

추후 전체 api가 아닌 개별 api가 v2로 변경될 수도 있기 때문입니다.

2019-08-18 09:19 UTC, junghum21 commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/MainActivity.kt
> +            for (market in marketList) {
리스트를 for문 대신 groupBy()와 map()을 활용하시면 더 깔끔한 코드가 될것 같네요.

제 코드 첨부합니다.

```kotlin
val markets = body.groupBy { it.market.split("-")[0] }
                                .map { map ->
                                    val title = map.key
                                    val markets = map.value.joinToString(separator = ",") {
                                        it.market
                                    }
                                    Market(title, markets)
                                }
```

https://github.com/junghum21/GoogryAndroidArchitectureStudy/blob/2b91e5c497153f84eaeba52d5ea7544e9f5b97e6/junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/ui/MainActivity.kt#L44-L51

2019-08-18 09:19 UTC, junghum21 commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/MainActivity.kt
> +            add(CoinFragment.getInstance(krwList, "KRW"))
CoinFragment 객체 생성을 ViewPagerAdapter#getItem 에서 하는것은 어떨까요?

중복 코드를 줄일수 있을 것 같습니다.

2019-08-18 09:19 UTC, junghum21 commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/adpter/CoinAdapter.kt
> +            val color: Int = when {
https://docs.upbit.com/reference#%EC%8B%9C%EC%84%B8-ticker-%EC%A1%B0%ED%9A%8C

전일대비 %로 구분하는게 아닌,

change 값으로 보합, 상승, 하락(RISE, EVEN, FALL)을 구분하는게 좀더 명확하다고 생각합니다.

2019-08-18 09:19 UTC, junghum21 commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/adpter/CoinAdapter.kt
> +        private fun formatDealPrice(price: Double): String {
1000단위 K를 붙여주는 로직이 필요하겠네요.

2019-08-19 04:31 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/build.gradle
> +    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
잘못 추가한거같습니다.

2019-08-19 04:39 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/build.gradle
> +    implementation 'com.android.support:design:28.0.0'
수정하였습니다!

2019-08-19 04:39 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/adpter/ViewpagerAdapter.kt
> +class ViewpagerAdapter(fm: FragmentManager?,
아하 감사합니다!

2019-08-19 04:39 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/MainActivity.kt
> +    private val fragmentList: ArrayList<Fragment> = ArrayList()
불변 리스트로 변경하였습니다.

2019-08-19 04:45 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/MainActivity.kt
> +    private val fragmentList: ArrayList<Fragment> = ArrayList()
mutableList로 변경하였습니다!

2019-08-19 05:05 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/network/RetrofitService.kt
> +    fun loadMarketData(): Single<ArrayList<Market>>
List 로 변경하는게 맞는거 같습니다. 수정하였습니다.

2019-08-19 05:06 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/network/RetrofitClient.kt
> +            .baseUrl("https://api.upbit.com/v1/")
넵 감사합니다.

2019-08-19 06:15 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/MainActivity.kt
> +            for (market in marketList) {
69e14de

적용했습니다!

2019-08-19 06:17 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/MainActivity.kt
> +            add(CoinFragment.getInstance(krwList, "KRW"))
69e14de

위에 코멘트와 함께 수정하면서 적용하였습니다.

2019-08-19 06:39 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/adpter/CoinAdapter.kt
> +            val color: Int = when {
61ef1eb

적용하였습니다.

2019-08-19 06:39 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/adpter/CoinAdapter.kt
> +        private fun formatDealPrice(price: Double): String {
61ef1eb

위에 코멘트와 함께 적용하였습니다.

2019-08-19 07:03 UTC, becooni requested changes

2019-08-19 07:03 UTC, becooni commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/adpter/ViewpagerAdapter.kt
> +class ViewpagerAdapter(fm: FragmentManager?,
```kotlin
class ViewpagerAdapter(
        fm: FragmentManager?,
```

이렇게 말이죠

2019-08-19 07:03 UTC, becooni commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/MainActivity.kt
> +    private val fragmentList: MutableList<Fragment> = mutableListOf()
https://developer.android.com/kotlin/style-guide#implicit_returnproperty_types

mutableListOf() 로 초기화 해줘서 자료형은 명확하니 자료형을 생략해도 좋겠네요.

2019-08-19 07:15 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/MainActivity.kt
> +    private val fragmentList: MutableList<Fragment> = mutableListOf()
fb897c7

위에건 코맨트가 안달리네요 ㅠ 
수정했습니다 ! 밑에 부분만 변경하고 위엔 변경안했네요 ㅠ

69e14de

삭제되어 수정하지 못했지만 자료형이 명확할때 생락하도록 하겠습니다.

2019-08-19 07:22 UTC, junghum21 commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/MainActivity.kt
> +    private val fragmentList: MutableList<Fragment> = mutableListOf()
넵 수고하셨습니다!

2019-08-19 14:41 UTC, ddaeyeonkim reviewed
1기 스터디 했었던 김대연입니다!
저도 미숙하지만 리뷰 남겨보았습니다. 다른 의견 남겨주신다면 감사히 받겠습니다!!

2019-08-19 14:41 UTC, improve777 commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/network/RetrofitClient.kt
> +class RetrofitClient {
매번 생성하기보다는 싱글톤으로 만들고 쓰는게 좋을 것 같습니다

2019-08-19 14:41 UTC, improve777 commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/CoinFragment.kt
> +    private var adapter: CoinAdapter? = null
retrofitService 와 adapter 를 lazy 패턴으로 바꾸면 notnull 하게 쓸 수 있습니다

2019-08-19 14:41 UTC, improve777 commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/CoinFragment.kt
> +            ?.subscribe({ t: List<Coin>? ->
Single 의 onSuccess 블록에서 null 을 받을 수 없는 것으로 알고 있습니다
```kotlin
    /**
     * Signal a success value.
     * @param t the value, not null
     */
    void onSuccess(@NonNull T t);
```

2019-08-19 14:41 UTC, improve777 commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/CoinFragment.kt
> +            }, { t: Throwable? -> Toast.makeText(context, t?.message, Toast.LENGTH_SHORT).show() })
마찬가지로 null 을 허용하지 않는 것으로 알고 있습니다
```kotlin
    /**
     * Signal an exception.
     * @param t the exception, not null
     */
    void onError(@NonNull Throwable t);
```

2019-08-19 14:41 UTC, improve777 commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/data/Coin.kt
> +data class Coin(
api 의 response 를 담는 모델 클래스는 api 명세서를 지켜주는게 맞다고 생각합니다

2019-08-19 14:41 UTC, improve777 commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/CoinFragment.kt
> +    companion object {
kotlin convention 을 보면 companion object 를 클래스 최하단에 두도록 권장하고 있습니다

2019-08-20 03:48 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/network/RetrofitClient.kt
> +class RetrofitClient {
안녕하세요 리뷰 감사합니다 !

c0e5441

이렇게 변경하는게 맞나요 ?!

2019-08-20 04:09 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/CoinFragment.kt
> +    private var adapter: CoinAdapter? = null
18d7ac6

적용하였습니다!

2019-08-20 04:13 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/CoinFragment.kt
> +            ?.subscribe({ t: List<Coin>? ->
5f9a8eb

수정했습니다!

2019-08-20 04:13 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/CoinFragment.kt
> +            }, { t: Throwable? -> Toast.makeText(context, t?.message, Toast.LENGTH_SHORT).show() })
5f9a8eb

수정했습니다!

2019-08-20 04:29 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/data/Coin.kt
> +data class Coin(
ec1ce32

변경했습니다!

2019-08-20 04:30 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/CoinFragment.kt
> +    companion object {
14ca4ea

수정했습니다!

2019-08-20 05:50 UTC, ddaeyeonkim commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/network/RetrofitClient.kt
> +class RetrofitClient {
네 추가적으로 생성자만 private 으로 해주면 될 것 같아요
[kotlin singleton](https://bonoogi.postype.com/post/3591846)

2019-08-20 05:50 UTC, ddaeyeonkim commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/network/RetrofitClient.kt
> +        val okHttpClient = builder.connectTimeout(20, TimeUnit.SECONDS)
okHttpClient 를 만드는 로직은 메서드를 분리하는게 좋을 것 같아요

2019-08-20 05:50 UTC, ddaeyeonkim commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/CoinFragment.kt
> +    private val retrofitClient by lazy { RetrofitClient.getInstance().getClient() }
RetrofitClient 는 싱글톤인데 Retrofit 객체를 한번만 만들고 가져다 쓰는게 좋을 것 같아요
getClient() 할때마다 매번 생성하게 됩니다

2019-08-20 05:50 UTC, ddaeyeonkim commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/CoinFragment.kt
> +    private val retrofitService by lazy { retrofitClient.create(RetrofitService::class.java) }
retrofitService 도 매번 생성할 필요가 없을 것 같습니다

2019-08-20 05:50 UTC, improve777 commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/MainActivity.kt
> +                    main_viewPager.adapter = viewpagerAdapter
viewPager 에 adapter 를 설정하는 로직과 데이터(marketTitle) 을 넣는 로직은 분리하는게 좋습니다

2019-08-20 05:50 UTC, improve777 commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/adpter/ViewpagerAdapter.kt
> +    private val marketTitles: List<MarketTitle>
생성자로 받지 않고 내부에서 가지고 있는게 좋을 것 같습니다

2019-08-20 05:50 UTC, improve777 commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/CoinFragment.kt
> +                run {
이건 취향차이일 것 같은데 run 블록을 제거해도 될 것 같습니다.

2019-08-20 05:50 UTC, improve777 commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/CoinFragment.kt
> +        marketSearch = arguments?.getString("marketSearch")!!
번들의 키 값인 marketSearch 는 상수로 두는게 좋을 것 같아요

2019-08-20 05:50 UTC, improve777 commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/MainActivity.kt
> +                    val marketTitle = t.groupBy { it.market.split("-")[0] }
split 말고 substringBefore 는 어떨까요?

2019-08-20 05:50 UTC, improve777 commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/MainActivity.kt
> +        retrofitService.loadMarketData().subscribeOn(Schedulers.io())
메서드 체이닝 할때는 개행을 해주는게 가독성이 더 좋을 것 같습니다

2019-08-20 06:58 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/network/RetrofitClient.kt
> +class RetrofitClient {
19ad562

넵 추가했습니다.

2019-08-20 07:33 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/network/RetrofitClient.kt
> +        val okHttpClient = builder.connectTimeout(20, TimeUnit.SECONDS)
f8e127e

밑에 코멘트도 보면서 변경해봤습니다.

2019-08-20 07:40 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/MainActivity.kt
> +                    main_viewPager.adapter = viewpagerAdapter
dc87035

밑에 코멘트와 함께 적용하였습니다!

2019-08-20 07:41 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/CoinFragment.kt
> +                run {
2c04b53

수정했습니다!

2019-08-20 07:48 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/CoinFragment.kt
> +        marketSearch = arguments?.getString("marketSearch")!!
4496c81

수정했습니다!

2019-08-20 07:55 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/MainActivity.kt
> +                    val marketTitle = t.groupBy { it.market.split("-")[0] }
123ba36

꿀정보 감사합니다

2019-08-20 08:03 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/MainActivity.kt
> +        retrofitService.loadMarketData().subscribeOn(Schedulers.io())
d238118

이런식으로 개행하면 될까요 ?

2019-08-20 08:51 UTC, improve777 commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/MainActivity.kt
> +        retrofitService.loadMarketData().subscribeOn(Schedulers.io())
람다는 복잡한 경우(파라미터가 많은 경우)가 아니라면 여는 괄호에서 개행하지 않고 -> 다음에 개행하라고 하더라구요
```kotlin
    @SuppressLint("CheckResult")
    private fun loadMarketData() {
        retrofitService.loadMarketData()
            .subscribeOn(Schedulers.io())
            .observeOn(AndroidSchedulers.mainThread())
            .subscribe(
                { list: List<Market> ->
                    val marketsList = list.groupBy { it.market.substringBefore("-") }
                        .map { (key, value) ->
                            MarketTitle(
                                marketTitle = key,
                                marketSearch = value.joinToString(separator = ",") { it.market }
                            )
                        }
                    viewpagerAdapter?.setData(marketsList)
                },
                { t: Throwable ->
                    Toast.makeText(this, t.message, Toast.LENGTH_SHORT).show()
                }
            )
    }
```
이건 어떨까요??

2019-08-20 13:18 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/MainActivity.kt
> +        retrofitService.loadMarketData().subscribeOn(Schedulers.io())
60f4930

아하 넵 조언 감사합니다

2019-08-20 13:24 UTC, sjjeong commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/CoinFragment.kt
> +    private val retrofitClient by lazy { RetrofitClient.getInstance().getClient() }
@toctocbin 이 부분도 코멘트 남겨주세요

2019-08-20 13:24 UTC, sjjeong commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/CoinFragment.kt
> +    private val retrofitService by lazy { retrofitClient.create(RetrofitService::class.java) }
@toctocbin 이 부분도 코멘트 남겨주세요

2019-08-20 13:24 UTC, sjjeong commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/adpter/ViewpagerAdapter.kt
> +    private val marketTitles: List<MarketTitle>
@toctocbin 이 부분도 코멘트 남겨주세요

2019-08-20 13:25 UTC, sjjeong commented
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/185#discussion_r315505961
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/185#discussion_r315506114
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/185#discussion_r315508016
코멘트 응답 남겨주세요

2019-08-20 14:51 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/CoinFragment.kt
> +    private val retrofitClient by lazy { RetrofitClient.getInstance().getClient() }
f8e127e

방식을 변경해서 적용해봤습니다.

2019-08-20 14:51 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/CoinFragment.kt
> +    private val retrofitService by lazy { retrofitClient.create(RetrofitService::class.java) }
f8e127e

변경해서 적용해봤습니다.

2019-08-20 14:52 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/adpter/ViewpagerAdapter.kt
> +    private val marketTitles: List<MarketTitle>
dc87035

내부에서 받는걸로 변경했습니다.

2019-08-21 01:36 UTC, improve777 commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/MainActivity.kt
> +        retrofitService.loadMarketData().subscribeOn(Schedulers.io())
처음에 리뷰를 달았던 이유는 이부분 때문이었습니다
```kotlin
        retrofitService.loadMarketData()
            .subscribeOn(Schedulers.io())             // 개행
            .observeOn(AndroidSchedulers.mainThread())
```

2019-08-21 04:40 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/MainActivity.kt
> +        retrofitService.loadMarketData().subscribeOn(Schedulers.io())
946576b

넵 수정했습니다.

2019-08-21 05:54 UTC, improve777 commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/adpter/ViewpagerAdapter.kt
> +        this.marketTitles = marketTitles
list 를 넣게 되면 외부에서 변경할 수 있게 되서 addAll() 로 받는게 좋을 것 같구요
그러면 adapter 에서 가지고 있는 marketTitles 를 final 로 쓸 수 있습니다
```suggestion
        this.marketTitles.addAll(marketTitles)
```

2019-08-21 05:54 UTC, improve777 commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/adpter/CoinAdapter.kt
> +            coinDealPriceTextView.setTradePriceText(coin.accTradePrice24h)
listview 에 bind 할때마다 연산 처리를 반복하게 되는데요
데이터를 받아올때 listview 에 보여주기 위한 데이터를 가공해서 
별도의 모델 클래스로 분리하는게 더 효율적일 것 같아요
그러면 여기서는 setText() 만 하면 됩니다

2019-08-21 08:06 UTC, improve777 commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/CoinFragment.kt
> +            args.putString("marketSearch", marketSearch)
여기도 MARKET_SEARCH 로 변경해주시면 됩니다
```suggestion
            args.putString(MARKET_SEARCH, marketSearch)
```

2019-08-21 08:29 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/adpter/ViewpagerAdapter.kt
> +        this.marketTitles = marketTitles
51dc151

변경하였습니다.

2019-08-21 09:10 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/adpter/CoinAdapter.kt
> +            coinDealPriceTextView.setTradePriceText(coin.accTradePrice24h)
83e0ff6

이런식으로 변경하는거 말씀하신건가요 ?

2019-08-21 09:11 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/CoinFragment.kt
> +            args.putString("marketSearch", marketSearch)
507178a

변경했습니다!

2019-08-21 09:19 UTC, ddaeyeonkim reviewed
LGTM 👍👍👍

2019-08-21 09:19 UTC, ddaeyeonkim submitted a review, later dismissed

2019-08-21 10:03 UTC, toctocbin commented
수고하셨습니다!!!!

2019-08-22 14:16 UTC, sjjeong requested changes

2019-08-22 14:16 UTC, sjjeong commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/adpter/ViewpagerAdapter.kt
> +    fun setData(marketTitles: List<MarketTitle>) {
setData라면 marketTitle을 clear 해줘야 할 것 같습니다.

2019-08-22 14:16 UTC, sjjeong commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/CoinFragment.kt
> +        const val MARKET_SEARCH: String = "marketSearch"
private 여도 될 것 같습니다

2019-08-22 14:16 UTC, sjjeong commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/adpter/ViewpagerAdapter.kt
> +class ViewpagerAdapter(fm: FragmentManager?) : FragmentStatePagerAdapter(fm) {
ViewPagerAdapter로 p를 대문자로 변경해주면 더 좋을 것 같습니다.

2019-08-22 23:59 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/adpter/ViewpagerAdapter.kt
> +    fun setData(marketTitles: List<MarketTitle>) {
3e93097

적용했습니다

2019-08-22 23:59 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/CoinFragment.kt
> +        const val MARKET_SEARCH: String = "marketSearch"
7785051

적용했습니다

2019-08-22 23:59 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/adpter/ViewpagerAdapter.kt
> +class ViewpagerAdapter(fm: FragmentManager?) : FragmentStatePagerAdapter(fm) {
c999920

적용했습니다

2019-08-23 10:59 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-08-26 01:44 UTC, becooni approved these changes
수고하셨습니다

2019-08-26 01:50 UTC, merged