HW-01 코인헬퍼 카피앱
sjjeong/GoogryAndroidArchitecutreStudy pull request #186
Opened 2019-08-18 08:10 UTC by junghum21

커밋 쪼개기가 좀 어렵네요..ㅠㅠ

보시기에 많이 엉망이지만 리뷰 잘 부탁드리겠습니다.

2019-08-19 04:27 UTC, haanbin reviewed
저보다 코드를 잘 짜셔서 리뷰할게 안보입니다.. 좀 더 공부해서 리뷰 해드릴 수 있도록 하겠습니다!

2019-08-19 04:27 UTC, toctocbin commented on junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/ui/MainActivity.kt
> +            addOnTabSelectedListener(TabLayout.ViewPagerOnTabSelectedListener(viewPager))
6a868da0576cda6f5836d7658dc9ac76bf3441f7

tabListener 를 다신 이유가 궁긍합니다.

2019-08-19 04:27 UTC, toctocbin commented on junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/ext/TickerExt.kt
> +    text = if (price < 1) String.format("%,.2f", price) else String.format("%,d", price.toInt())
3a39e00e0e452e8bcded1d57d6bf57027673f692

가격이 1 이하 일 시 .8f 로 고정되는거 같습니다.

2019-08-19 06:37 UTC, junghum21 commented on junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/ui/MainActivity.kt
> +            addOnTabSelectedListener(TabLayout.ViewPagerOnTabSelectedListener(viewPager))
리스너 탭을 안달아도 되는지 몰랐네요!

반영 완료 
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/186/commits/5291a900077270a5b277712643fa5f1b5b880d8c

2019-08-19 06:37 UTC, junghum21 commented on junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/ext/TickerExt.kt
> +    text = if (price < 1) String.format("%,.2f", price) else String.format("%,d", price.toInt())
반영 완료 
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/186/commits/99e60457b4600284b2c4512bd1745cf7eeca7d7b

2019-08-19 06:45 UTC, toctocbin commented
수고하셨습니다 !

2019-08-19 11:27 UTC, ddaeyeonkim reviewed
1기 스터디 했던 김대연입니다.
리뷰 확인하시고 의견 달아주시면 감사하겠습니다!!

2019-08-19 11:27 UTC, ddaeyeonkim commented on junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/data/source/UpbitRepository.kt
> +    private val service = ApiUtil.getRetrofit().create<UpbitService>()
나중에는 생성자로 주입 받으시는게 좋습니다
UpbitService 도 싱글톤으로 하는게 좋을것 같아요

2019-08-19 11:27 UTC, ddaeyeonkim commented on junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/ui/TickersFragment.kt
> +    companion object {
kotlin convention 에 의하면 companion object 블록을 최하단에 두는 것을 권장하고 있습니다

2019-08-19 11:27 UTC, ddaeyeonkim commented on junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/ui/TickersFragment.kt
> +    private fun setTickers(tickers: List<TickerResponse>) {
리사이클러뷰의 adapter 를 셋하는 로직은 분리하고 데이터만 갱신해주는게 나을 것 같아요

2019-08-21 09:10 UTC, junghum21 commented on junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/data/source/UpbitRepository.kt
> +    private val service = ApiUtil.getRetrofit().create<UpbitService>()
1. service 프로퍼티를 생성자로 주입하라는 말씀이신가요?

2. UpbitService를 interface말고 싱글톤으로 변경하라는 것인지요?

잘 이해가 안되는데, 설명 부탁드릴께요 :)

2019-08-21 09:11 UTC, junghum21 commented on junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/ui/TickersFragment.kt
> +    companion object {
반영완료!

https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/186/commits/bfeff9e6714e6024c781e3f80afa91fb06c2ad50

2019-08-21 09:11 UTC, junghum21 commented on junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/ui/TickersFragment.kt
> +    private fun setTickers(tickers: List<TickerResponse>) {
반영완료!

https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/186/commits/6137a014c408fc5fe4d76bf6a1acafb6fa00386b

2019-08-21 09:17 UTC, improve777 commented on junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/data/source/UpbitRepository.kt
> +    private val service = ApiUtil.getRetrofit().create<UpbitService>()
1.네 UpbitRepository 를 생성할때 파라미터로 service 를 받는게 좋습니다

2. retrofit.create() 를 하게 되면 UpbitService 인스턴스를 만들게 되는데 아예
    `ApiUtil.getUpbitService()` 로 해도 될 것 같아요

2019-08-21 17:56 UTC, improve777 commented on junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/ui/adapter/TickersAdapter.kt
> +        items.addAll(list)
`notifyDataSetChanged()` 가 빠졌습니다

2019-08-21 17:56 UTC, improve777 commented on junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/ui/adapter/TickersAdapter.kt
> +                tvAccTradePrice.setTradePrice(item.accTradePrice24h)
listview 에 bind 할때마다 연산 처리를 반복하게 되는데요
데이터를 받아올때 listview 에 보여주기 위한 데이터를 가공해서
별도의 data 클래스로 분리하는게 더 효율적일 것 같아요
그러면 여기서는 setText() 만 하면 됩니다

2019-08-21 17:56 UTC, improve777 commented on junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/ext/TickerExt.kt
> +        price > 1000000F -> String.format("%,d", price.toInt() / 1000000) + "M"
의도하신 것인지는 모르겠지만 정확히 1_000_000 일 경우에는 else 로 타게 됩니다

2019-08-22 03:06 UTC, junghum21 commented on junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/ui/adapter/TickersAdapter.kt
> +        items.addAll(list)
반영완료
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/186/commits/af5eda072120d0c96cf01df3208394779028eb87

2019-08-22 03:06 UTC, junghum21 commented on junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/ui/adapter/TickersAdapter.kt
> +                tvAccTradePrice.setTradePrice(item.accTradePrice24h)
반영완료
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/186/commits/55a02d2439554fdcf91a0ddc7d25a6716541ec19

2019-08-22 03:06 UTC, junghum21 commented on junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/ext/TickerExt.kt
> +        price > 1000000F -> String.format("%,d", price.toInt() / 1000000) + "M"
반영완료
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/186/commits/ca1577ba1c9dcebdb3eaec56af350f6d2ad9815e

2019-08-22 03:09 UTC, junghum21 commented on junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/data/source/UpbitRepository.kt
> +    private val service = ApiUtil.getRetrofit().create<UpbitService>()
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/186/commits/1eb0e0aa9978d1aa4c1785a5cf981d3cad996a18

말씀해주신 2가지 모두 적용했습니다.

2019-08-22 03:15 UTC, junghum21 commented on junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/data/source/UpbitRepository.kt
> +    private val service = ApiUtil.getRetrofit().create<UpbitService>()
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/186/commits/f7de0d5c0968fefc0324fa38a8fd65d3e369b502

upbitService도 프로퍼티로 만들었습니다.

2019-08-22 14:23 UTC, sjjeong requested changes

2019-08-22 14:23 UTC, sjjeong commented on junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/ui/adapter/TickersAdapter.kt
> +            ItemTickerBinding.inflate(
ItemTickerBinding.inflate로 하게 되면 나중에 layout.xml 파일명으로 찾기가 어렵게 됩니다.
DataBindingUtil를 사용해주세요

2019-08-23 01:47 UTC, junghum21 commented on junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/ui/adapter/TickersAdapter.kt
> +            ItemTickerBinding.inflate(
석준님의 BaseFragment 참고해서 적용했습니다.

https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/186/commits/074f7b4b567ae81bf97a5ae4ec3d57c1a88ef760

2019-08-23 11:00 UTC, sjjeong commented on junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/ui/adapter/TickersAdapter.kt
> +            ItemTickerBinding.inflate(
@junghum21 
리뷰는 TickerAdapter에 대한 것인데 Fragment를 수정하셨네요.
확인해주세요

2019-08-23 12:35 UTC, junghum21 commented on junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/ui/adapter/TickersAdapter.kt
> +            ItemTickerBinding.inflate(
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/186/commits/327dc23001309061373c19964a11b7a0943fd91a

반영완료

2019-08-24 03:10 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-08-24 03:11 UTC, merged