Class04/seonoh
sjjeong/GoogryAndroidArchitecutreStudy pull request #187
Opened 2019-08-25 00:11 UTC by seonoh

MainActivity , CoinFragment Repository 패턴으로 변경.

DataSource에서는 인터페이스로 getMarket, getCurrentPriceInfo 함수를 선언해주었습니다. 
DataSourceImpl에서는 coinApi를 갖고 있고, DataSource를 구현해주었습니다.
Repository에서는 인터페이스로 sendMarket, sendCurrentPriceInfo 함수를 선언해주었습니다.
RepositoryImpl에서는 DataSourceImpl객체를 갖고 있고, 이를통해 Repository 인터페이스를 구현해주었습니다.

2019-08-25 03:16 UTC, BeokBeok requested changes
안녕하세요. 스터디 2기 강현석이라고 합니다.
부족하지만 잘 부탁드립니다.

---

커밋 시, 앞에 "HW-주차" 를 붙여주세요.

2019-08-25 03:16 UTC, BeokBeok commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinDataSource.kt
> +    fun getMarket() : Single<ArrayList<Market>>
리스코프 치환 원칙(LSP)를 참고하시어 ArrayList 를 List로 바꿔주세요.

2019-08-25 03:16 UTC, BeokBeok commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinDataSourceImpl.kt
> +    val coinApi = Retrofit.Builder()
접근자를 추가해주세요

2019-08-25 03:16 UTC, BeokBeok commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinFragment.kt
> +        coinRepository.sendCurrentPriceInfo(this,marketName!!)
marketName 이 null 인 경우는 없을까요?

2019-08-25 03:16 UTC, BeokBeok commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinDataSourceImpl.kt
> +package com.example.seonoh.seonohapp
DataSource 관련해서 패키지를 추가하여 관리하는 것은 어떠신가요?

2019-08-25 03:16 UTC, BeokBeok commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinRepository.kt
> +    fun sendCurrentPriceInfo(listener: CoinRequest.BaseResult<ArrayList<CurrentPriceInfoModel>>, markets: String)
함수 관련 code convention 을 지켜주세요.
https://kotlinlang.org/docs/reference/coding-conventions.html#function-formatting

2019-08-25 03:16 UTC, BeokBeok commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinRepositoryImpl.kt
> +
너무 많은 개행을 제거해주시고, 가급적이면 한 행으로 구분해주세요.

다음은 클린 코드 책의 내용을 인용하였습니다.
> **개념은 빈 행으로 분리하라**
거의 모든 코드는 왼쪽에서 오른쪽으로 그리고 위에서 아래로 읽힌다.
각 행은 수식이나 절을 나타내고, 일련의 행 묶음은 완결된 생각 하나를 표현한다.
생각 사이는 빈 행을 넣어 분리해야 마땅하다.

2019-08-25 03:16 UTC, BeokBeok commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinRepositoryImpl.kt
> +        val single = coinDataSource.getCurrentPriceInfo(markets)
single 이라는 변수명과 coinDatasource.getCurrentPriceInfo(markets) 과의 의미를 모르겠습니다.
보다 명확한 의미를 가진 변수명으로 작성하시는 것은 어떠신가요?

2019-08-25 03:16 UTC, BeokBeok commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinRepositoryImpl.kt
> +                listener.getNetworkSuccess(it)
it의 body가 null인 경우에 대한 예외처리가 필요해보입니다.

2019-08-25 03:16 UTC, BeokBeok commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinRepositoryImpl.kt
> +                    listener.getNetworkFailed(e.toString())
e.toString() 보다 e.message() 가 더 낫지 않을까요?

2019-08-25 03:16 UTC, BeokBeok commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinFragment.kt
>      lateinit var mAdapter: CoinAdapter
접근자를 추가해주세요.

2019-08-25 03:16 UTC, BeokBeok commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinRepositoryImpl.kt
> +class CoinRepositoryImpl : CoinRepository {
해당 클래스를 추가하면서, 
CoinRequest 클래스의 sendMarket, sendCurrentPriceInfo 함수는 더이상 사용하지 않는 것으로 보입니다.
사용하지 않는다면 제거해주세요.

2019-08-25 03:16 UTC, BeokBeok commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/MainActivity.kt
>      fun initView() {
접근자를 추가해주세요.

2019-08-25 03:16 UTC, BeokBeok commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinRepositoryImpl.kt
> +        single
```suggestion
        single.subscribeOn(Schedulers.io())
```
개행을 제거해주세요

2019-08-25 03:16 UTC, BeokBeok commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/MainActivity.kt
>          toast = Toast.makeText(this, "뒤로가기를 한번 더 누르시면 앱이 종료됩니다.", Toast.LENGTH_SHORT)
toast 변수는 onBackPressed 에서만 사용되는 것으로 보이는데,
그렇다면, onCreate가 아닌 onBackPressed 에서 처리해도 되지 않나요?

2019-08-26 00:43 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinDataSource.kt
> +    fun getMarket() : Single<ArrayList<Market>>
반갑습니다 ! 
리스코프 치환 원칙에 따라서 ArrayList -> List로 변경했습니다. 감사합니다.

08b5a1d

2019-08-26 00:45 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinDataSourceImpl.kt
> +    val coinApi = Retrofit.Builder()
네 private 접근자 추가했습니다. 
e368ad4

2019-08-26 00:48 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinFragment.kt
> +        coinRepository.sendCurrentPriceInfo(this,marketName!!)
네 반영했습니다. 감사합니다 !!

0bd4e37

2019-08-26 02:24 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinDataSourceImpl.kt
> +package com.example.seonoh.seonohapp
네 감사합니다! 반영했습니다.

384b62f

2019-08-26 02:26 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinRepository.kt
> +    fun sendCurrentPriceInfo(listener: CoinRequest.BaseResult<ArrayList<CurrentPriceInfoModel>>, markets: String)
네 감사합니다 ! 
3636f4a

2019-08-26 02:28 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinRepositoryImpl.kt
> +class CoinRepositoryImpl : CoinRepository {
네 감사합니다. 수정했습니다.

08b5a1d

2019-08-26 02:30 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinFragment.kt
>      lateinit var mAdapter: CoinAdapter
네 추가했습니다. 

f2c401f

2019-08-26 02:31 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/MainActivity.kt
>      fun initView() {
네 추가했습니다. 
bd06422

2019-08-26 02:32 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinRepositoryImpl.kt
> +        single
네 개행 제거했습니다. 
9d0744f

2019-08-26 02:33 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/MainActivity.kt
>          toast = Toast.makeText(this, "뒤로가기를 한번 더 누르시면 앱이 종료됩니다.", Toast.LENGTH_SHORT)
네 수정했습니다. 감사합니다! 

4cc77ee

2019-08-26 05:15 UTC, BeokBeok commented
4개의 리뷰에 대해서 피드백을 받지 못하였습니다.

2019-08-26 12:26 UTC, seonoh reviewed
죄송합니다. 리뷰를 확인하지 못했었네요. 혹시 모든 리뷰를 확인하는 기능이 따로 있나요?
저는 https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/187 진입한 후에 보이는 리뷰만 보고 진행했었습니다.

2019-08-26 12:26 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinRepositoryImpl.kt
> +        val single = coinDataSource.getCurrentPriceInfo(markets)
리뷰 내용 수정했습니다!
da120a2

2019-08-26 12:26 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinRepositoryImpl.kt
> +                listener.getNetworkSuccess(it)
네 수정했습니다. 감사합니다 ! 
5ad022a

2019-08-26 12:26 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinRepositoryImpl.kt
> +                    listener.getNetworkFailed(e.toString())
네 수정했습니다. 감사합니다 !

3726dd1

2019-08-26 12:26 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinRepositoryImpl.kt
> +
참고자료까지 정말 감사합니다 ! 수정했습니다!
7ab51a0bfdb653d0808f5ec40fde9d84a19fc2c4

2019-08-26 13:05 UTC, BeokBeok commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinFragment.kt
> +        coinRepository.sendCurrentPriceInfo(this,marketName!!)
arguments 가 null 인 경우, marketName을 nonnull 로 casting 하면 NPE 발생할 여지가 있어서
sendCurrentPriceInfo 에서 두 번째 파라미터 타입을 nullable 타입으로 하는 것을 의도로 하였습니다.

2019-08-26 13:06 UTC, BeokBeok commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinRepositoryImpl.kt
> +                listener.getNetworkSuccess(it)
let을 사용하여 null 처리 해주세요.

2019-08-26 13:09 UTC, BeokBeok reviewed
중간에 보시면
4 hidden conversations
**Load more...**
가 있습니다.

Load more 를 클릭하시면 볼 수 있습니다.

2019-08-26 14:21 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinFragment.kt
> +        coinRepository.sendCurrentPriceInfo(this,marketName!!)
아!! 네 감사합니다 !

b9b5169

2019-08-26 14:29 UTC, seonoh reviewed
아.. 그 방법 뿐이군요!!
감사합니다.

2019-08-26 14:29 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinRepositoryImpl.kt
> +                listener.getNetworkSuccess(it)
네 감사합니다! 수정했습니다
c6cea56

2019-08-27 00:53 UTC, BeokBeok commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinFragment.kt
> +        coinRepository.sendCurrentPriceInfo(this,marketName!!)
```suggestion
        marketName = arguments?.getString(MARKET)
        marketName?.let {
            coinRepository.sendCurrentPriceInfo(
                this,
                it
            )
        } ?: Toast.makeText(
            activity,
            "마켓데이터를 불러올 수 없습니다.",
            Toast.LENGTH_LONG
        ).show()        
```
이런 식으로 하시면 될 것 같습니다.

2019-08-27 00:54 UTC, BeokBeok commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinRepositoryImpl.kt
> +                listener.getNetworkSuccess(it)
it 이 null 일 때 처리도 해주세요

2019-08-27 06:54 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinRepositoryImpl.kt
> +                listener.getNetworkSuccess(it)
네 수정했습니다! 감사합니다. 
79479de

2019-08-27 06:57 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinFragment.kt
> +        coinRepository.sendCurrentPriceInfo(this,marketName!!)
감사합니다 ! 
1c67a4a

2019-08-27 07:03 UTC, BeokBeok submitted a review, later dismissed
LGTM:ok_hand:

2019-08-27 15:39 UTC, jskim5923 reviewed
제가 리뷰하기 앞서 강현석님이 리뷰를 잘해주셨고,
저도 모델 나누는 부분에 있어 헷갈리는 부분이 많아 리뷰할게 별로 없었던것 같습니다.
제가 코멘트를 남긴 부분이 선오님이랑 제 코드가 좀 갈래가 나눠졌는데,
이 부분은 멘토님의 코멘트가 필요해 보입니다!

2019-08-27 15:39 UTC, jskim5923 commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinFragment.kt
> +            "마켓데이터를 불러올 수 없습니다.",
하드코딩 보다는 strings.xml파일을 이용하여 사용하는것이 좋을 것 같습니다.

2019-08-27 15:39 UTC, jskim5923 commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinRepositoryImpl.kt
> +        currentPriceInfoData.subscribeOn(Schedulers.io())
저도 이 부분을 나누는데 고민이 많았었는데요.

RxJava의 Single을 사용하면  onSuccess와 onFailed을 받을 수 있기 때문에, 
굳이 callback listener를 한번 더 사용할 필요가 없다고 생각합니다.
물론 여기서 context를 따로 참조하지 않지 않아, 메모리릭이 발생할 여지는 없는것 같지만
보통 disposable을 compositeDisposable에 추가한 후, lifecycle에 맞춰 destroy되는 시점에 clear시키는 코드를 많이 본것 같습니다.

그래서 레이어를 어떻게 나눌지 고민했었는데,  저는  Model(repository , datasource)에서는 Presenter or ViewModel에서 요청한 data를 전달 해주고, 그 전달 받은 data의 변경은 Presenter or ViewModel에서 변경 하고 그 변경된 데이터의 update는 Presenter or ViewModel에 저장하는게 맞지 않을까 하고 생각했었습니다.

이 코멘트는 수정요청 사항이라기 보다는 추후에 멘토님의 조언을 남겨둡니다.

2019-08-27 15:39 UTC, jskim5923 commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinFragment.kt
> +    override fun getNetworkSuccess(result: List<CurrentPriceInfoModel>) {
위에 남긴 코멘트에 따라 수정 사항이 없어질수도 있지만,
listener없이 Single Observable만 사용한다면, 
stream 형식으로 변경 할 수 있을것 같습니다.

2019-08-27 15:39 UTC, jskim5923 commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinFragment.kt
>          // 데이터 가공후 모델에 넣음.
안드로이드 스튜디오에서는
`result.size != 0` 보다는
` result.isNotEmpty()`

를 권장합니다.

2019-08-27 15:41 UTC, jskim5923 commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/network/BaseResult.kt
> +    fun getNetworkSuccess(result: T)
callback 함수의 네이밍이 getNetwork...보다는 onNetwork...가 가독성이 좋을것 같습니다.

2019-08-27 23:21 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinFragment.kt
> +            "마켓데이터를 불러올 수 없습니다.",
네 감사합니다 ! 
0528f5e

2019-08-27 23:23 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinFragment.kt
>          // 데이터 가공후 모델에 넣음.
앗 ..ㅎㅎ 감사합니다 종선님 !

4d0ea58

2019-08-27 23:24 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/network/BaseResult.kt
> +    fun getNetworkSuccess(result: T)
네 감사합니다 ! 
7034c54

2019-08-28 08:41 UTC, jskim5923 submitted a review, later dismissed

2019-08-29 13:32 UTC, sjjeong requested changes
리뷰 반영하기전에 전체코드를 reformat code 해서 커밋해주세요.
rearrange code와 optimize imports를 하기 위해서입니다.

2019-08-29 13:32 UTC, sjjeong commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinFragment.kt
> +        marketName = arguments?.getString(MARKET)
26번째 줄이랑 같은 코드입니다

2019-08-29 13:32 UTC, sjjeong commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinFragment.kt
> +            coinRepository.sendCurrentPriceInfo(
onCreateView 시점에서 호출하지 말아주세요.
onActivityCreate 시점에 호출해주세요.

2019-08-29 13:32 UTC, sjjeong commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinItemViewHolder.kt
> +        changeRateTv.apply {
apply보단 run이 좋습니다.
apply는 자기자신을 return하기 때문에 생성과 초기화를 같이 할 때 많이 사용합니다

2019-08-29 13:32 UTC, sjjeong commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinRepository.kt
> +package com.example.seonoh.seonohapp
패키지를 repository로 옮겨주세요

2019-08-29 13:32 UTC, sjjeong commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinRepositoryImpl.kt
> +package com.example.seonoh.seonohapp
패키지를 repository로 옮겨주세요

2019-08-29 13:32 UTC, sjjeong commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinRepositoryImpl.kt
> +        if(markets == null){
markets.isNullOrEmpty()를 사용해주세요

2019-08-29 13:32 UTC, sjjeong commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinRepositoryImpl.kt
> +        val currentPriceInfoData = coinDataSource.getCurrentPriceInfo(markets!!)
!!는 필요 없습니다

2019-08-29 13:32 UTC, sjjeong commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinRepositoryImpl.kt
> +        currentPriceInfoData.subscribeOn(Schedulers.io())
저도 동일한 의견입니다.
이 부분 반영해주세요

2019-08-29 13:32 UTC, sjjeong commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinRepositoryImpl.kt
> +                it?.let { listener.onNetworkSuccess(it) } ?: Log.e("coinrepo","CurrentPriceInfoModel is null ")
it이 null인 케이스는 없습니다.
null check를 하지 않아도 됩니다.

2019-08-29 13:32 UTC, sjjeong commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinRepositoryImpl.kt
> +                it?.let { listener.onNetworkSuccess(it) } ?: Log.e("coinrepo","Market is null ")
it이 null인 케이스는 없습니다.
null check를 하지 않아도 됩니다.

2019-08-30 00:42 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinRepositoryImpl.kt
> +        currentPriceInfoData.subscribeOn(Schedulers.io())
네 수정했습니다. 감사합니다. 
a1577a6

2019-08-30 00:45 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinFragment.kt
> +        marketName = arguments?.getString(MARKET)
네 죄송합니다 ! 
9b98bf7

2019-08-30 00:48 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinFragment.kt
> +            coinRepository.sendCurrentPriceInfo(
네 수정했습니다.

7a457b4

2019-08-30 00:49 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinItemViewHolder.kt
> +        changeRateTv.apply {
네 감사합니다!!

6f1d0a5

2019-08-30 00:50 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinRepository.kt
> +package com.example.seonoh.seonohapp
6666df6

2019-08-30 00:50 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinRepositoryImpl.kt
> +package com.example.seonoh.seonohapp
6666df6

2019-08-30 00:52 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinRepositoryImpl.kt
> +        if(markets == null){
네 수정했습니다. 리스너 부분을 제거하면서 해당부분 코드 제거되었습니다.
a1577a6

2019-08-30 00:54 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinRepositoryImpl.kt
> +        val currentPriceInfoData = coinDataSource.getCurrentPriceInfo(markets!!)
네 수정했습니다!

d50a034

2019-08-30 00:54 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinRepositoryImpl.kt
> +                it?.let { listener.onNetworkSuccess(it) } ?: Log.e("coinrepo","CurrentPriceInfoModel is null ")
네 반영했습니다.
a1577a6

2019-08-30 00:55 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinRepositoryImpl.kt
> +                it?.let { listener.onNetworkSuccess(it) } ?: Log.e("coinrepo","Market is null ")
네 반영했습니다. 
a1577a6

2019-08-30 12:41 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-08-30 23:54 UTC, merged