HW-2 Model - Repository Pattern 구현
sjjeong/GoogryAndroidArchitecutreStudy pull request #188
Opened 2019-08-25 13:05 UTC by junghum21

2019-08-25 14:33 UTC, BeokBeok requested changes
안녕하세요. 스터디 2기 강현석이라고 합니다.
부족하지만 잘 부탁 드립니다.

---

커밋 시, 앞에 "HW-주차" 를 붙여주세요.

2019-08-25 14:33 UTC, BeokBeok commented on junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/data/source/UpbitRemoteDataSource.kt
> +                override fun onFailure(call: Call<List<MarketResponse>?>, t: Throwable) {
onResponse와 동일하게 파라미터를 정리해주세요.
```suggestion
                override fun onFailure(
                        call: Call<List<MarketResponse>?>,
                        t: Throwable
                 ) {
```

2019-08-25 14:33 UTC, BeokBeok commented on junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/data/source/UpbitRepository.kt
> +    ) {
한 줄로 표현이 가능합니다.
```suggestion
    = upbitRemoteDataSource.getMarketAll(
            success,
            failure
       )
```

2019-08-25 14:33 UTC, BeokBeok commented on junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/ui/MainActivity.kt
> +                    val markets = map.value.joinToString(separator = ",") {
joinToString 함수는 default separator가 콤마 이므로
파라미터를 생략해도 됩니다.

2019-08-25 14:33 UTC, BeokBeok commented on junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/ui/MainActivity.kt
> +            val markets = response.groupBy { it.market.substringBefore("-") }
원소가 많을 경우, 원본 컬렉션을 시퀀스로 변환하여 처리하는 것을 권장합니다.

2019-08-25 14:33 UTC, BeokBeok commented on junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/ui/MainActivity.kt
> +        }, {})
가급적이면 에러 처리를 해주세요

2019-08-26 01:09 UTC, junghum21 commented on junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/data/source/UpbitRepository.kt
> +    ) {
리턴하지 않고 콜백 함수만 전달해주기 떄문에 이렇게 작성했습니다.

2019-08-26 01:34 UTC, junghum21 commented on junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/data/source/UpbitRemoteDataSource.kt
> +                override fun onFailure(call: Call<List<MarketResponse>?>, t: Throwable) {
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/188/commits/2c940ccc4f5e47087980f273660c262bf0859b1b
반영완료

2019-08-26 01:34 UTC, junghum21 commented on junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/ui/MainActivity.kt
> +                    val markets = map.value.joinToString(separator = ",") {
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/188/commits/713e5bbd9c16a438865089d620a6f1c98909a246

반영완료

2019-08-26 01:35 UTC, junghum21 commented on junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/ui/MainActivity.kt
> +            val markets = response.groupBy { it.market.substringBefore("-") }
https://umbum.tistory.com/599

컬렉션 성능에 관련된 것이군요.
한 수 배웠습니다. 감사합니다 :)

반영완료

https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/188/commits/6f06cd03046e728c69a11759e01e5c8552180e2e

2019-08-26 01:36 UTC, junghum21 commented on junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/ui/MainActivity.kt
> +        }, {})
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/188/commits/66c411a539a4faa1fa52bcbb197c693edf3711cc

반영완료

2019-08-26 11:08 UTC, BeokBeok commented on junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/data/source/UpbitRepository.kt
> +    ) {
리턴 값이 없다면, 기본값은 Unit 입니다.
해서 한 줄로 표현이 가능합니다.

2019-08-27 01:09 UTC, junghum21 commented on junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/data/source/UpbitRepository.kt
> +    ) {
코틀린 펑션에서 블럭을 생략한 = 은 무언가를 return을 한다는 명시적 표현이므로 적절하지 않다고 생각이 드네요.

혼동을 줄수 있는 부분이라고 생각합니다.

2019-08-27 01:13 UTC, haanbin requested changes
잘부탁드립니다!

2019-08-27 01:13 UTC, toctocbin commented on junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/ui/TickersFragment.kt
> +    private val repository = UpbitRepository(UpbitRemoteDataSource(ApiUtil.getUpbitService()))
싱글톤으로 사용하는건 어떻게 생각하시나요 ?

2019-08-27 01:38 UTC, BeokBeok commented on junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/data/source/UpbitRepository.kt
> +    ) {
피드백 감사합니다 ^~^

2019-08-27 01:40 UTC, BeokBeok submitted a review, later dismissed
LGTM:ok_hand:

2019-08-27 02:38 UTC, junghum21 commented on junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/ui/TickersFragment.kt
> +    private val repository = UpbitRepository(UpbitRemoteDataSource(ApiUtil.getUpbitService()))
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/188/commits/ef1e07180b3fc95d70f308ed42dfc1838184e416

반영완료

2019-08-27 04:18 UTC, toctocbin commented on junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/ui/TickersFragment.kt
> +    private val repository = UpbitRepository(UpbitRemoteDataSource(ApiUtil.getUpbitService()))
수고하셨습니다!

2019-08-27 04:20 UTC, haanbin submitted a review, later dismissed

2019-08-29 13:45 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-08-29 14:18 UTC, closed without merging