HW-2 model구현
sjjeong/GoogryAndroidArchitecutreStudy pull request #189
Opened 2019-08-26 13:53 UTC by syli9526

2019-08-28 16:28 UTC, onemask reviewed
* 추가했으면 좋을 라이브러리와 
* Retrofit 객체를 다른 파일로 분리하는거랑
* 코드 축약 할 수 있는 부분 위주로 코멘트 달았습니다

2019-08-28 16:28 UTC, onemask commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/data/source/CoinDataSourceImpl.kt
> +    companion object {
Retrofit 객체를 DataSourceImpl에 선언하지 말고 따로 파일 class나 object로 빼서 관리하는게 가시성이 더 좋을거 같아요

2019-08-28 16:28 UTC, onemask commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/data/source/CoinDataSourceImpl.kt
> +            override fun onResponse(call: Call<List<TickerResponse>>, response: Response<List<TickerResponse>>) {
이 부분은 
`override fun onResponse(call: Call<List<TickerResponse>>,
                                    response: Response<List<TickerResponse>>) = response.body()?.let {
                                        val tickerList = it.map {
                                                tickerResponse -> 
                                            tickerResponse.toTicker()
                                        }
                                        listener.onResponse(tickerList)
                                    } ?: run { listener.onFailure("null") }
        })`
이렇게도 축약할수 있을거 같아요 
it이라는 키워드가 2번이상 반복되니까 
 it이 뭘 명시하는지 따로 lamda안에 ** -> **.toTlicker 로 두면 더 가시적일거 같아요

2019-08-28 16:28 UTC, onemask commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/MainActivity.kt
> +                Toast.makeText(this@MainActivity, "Call Failure : $str", Toast.LENGTH_LONG).show()
Toast 말고 Timber라는 라이브러리 적용해보는것을 추천드립니다.
디버그버전일때만 log가 나오는 라이브러리에요 
[Tibmer 관련 링크 ](https://m.blog.naver.com/PostView.nhn?blogId=ssarang8649&logNo=220947884163&proxyReferer=https%3A%2F%2Fwww.google.com%2F)
https://m.blog.naver.com/PostView.nhn?blogId=ssarang8649&logNo=220947884163&proxyReferer=https%3A%2F%2Fwww.google.com%2F[](url)

2019-08-28 16:28 UTC, onemask commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/data/source/UpbitListener.kt
>  interface UpbitListener<T> {
이걸 Generic Type으로 받은게 UpbitListner 안에 여러 데이터 형태가 올 수 있기 떄문인가요?

2019-08-28 16:28 UTC, onemask commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/data/source/CoinDataSourceImpl.kt
> +    companion object {
retrofit 안에 interceptor 넣어주면 
네트워크 상태나 request, response 받은 데이터를 알 수 있어서 
추가하면 좋을거 같아요! 
[HTTP INTERCEPTOR링크 ](https://gun0912.tistory.com/50)

2019-08-28 16:28 UTC, onemask commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/network/model/MarketResponse.kt
> +package com.example.architecturestudy.network.model
@SerializedName("korean_name") val koreanName: String,
    @SerializedName("english_name") val englishName: String
보니까 이 데이터들은 사용하지 않는거 같은데 제거해도 좋을거 같아요.

2019-08-28 16:28 UTC, onemask commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/adapter/CoinAdapter.kt
>          this.coinList.clear()
`  this.coinList.apply { 
            clear()
            addAll(coinListData)
        }`
로 해당 부분 축약할 수 있을거 같아요

2019-08-28 16:28 UTC, onemask commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/CoinFragment.kt
> +            override fun onResponse(dataList: List<Ticker>) {
override fun onFailure(str: String) {
            }
여기 안에도 왜 onFailure가 나오는지 toast,timber,log로 알려주는게 있어야 할거 같아요

2019-08-28 16:28 UTC, onemask commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/data/model/ITicker.kt
> +interface ITicker {
TickerReponse로 받은 data들 Ticker로 바꿔주기위해 만드신 interface인가요?
오 뭔가 획기적이네요 !

2019-08-29 02:59 UTC, syli9526 commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/data/source/UpbitListener.kt
>  interface UpbitListener<T> {
네! ticker와 market형태 둘다 사용이 되요!

2019-08-29 14:06 UTC, syli9526 commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/data/source/CoinDataSourceImpl.kt
> +    companion object {
이 부분은 일단 DataSourceImpl에서만 직접 retrofit 객체에 접근하기 때문에 안에다가 선언해 두었습니다. 
제가 이번주는 좀 바빠서 interceptor라는것을 주말에 공부해보고 다음주 과제때 적용해볼께요 ㅠㅠ

2019-08-29 14:07 UTC, syli9526 commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/data/source/CoinDataSourceImpl.kt
> +            override fun onResponse(call: Call<List<TickerResponse>>, response: Response<List<TickerResponse>>) {
[f6a18ee](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/189/commits/f6a18ee1cc3fc3c1ea878c769070c3c6a91b22c7)
수정하였습니다.

2019-08-29 14:09 UTC, syli9526 commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/MainActivity.kt
> +                Toast.makeText(this@MainActivity, "Call Failure : $str", Toast.LENGTH_LONG).show()
링크에 나와있는거는 타이머 사용법에대한거같아요! 
이부분도 제가 모르는 부분이라 주말에 공부해서 다음주 과제때 적용해보겠습니다.

2019-08-29 14:09 UTC, syli9526 commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/network/model/MarketResponse.kt
> +package com.example.architecturestudy.network.model
일단 api 요청시 받아오는 데이터들이라 넣어둔것이고, 
ticker에도 똑같이 사용안하는 데이터들이 있습니다.

2019-08-29 14:10 UTC, syli9526 commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/adapter/CoinAdapter.kt
>          this.coinList.clear()
[9e44e49](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/189/commits/9e44e4933f9c8b92e2e595ec34b227cad874e592)
수정하였습니다.

2019-08-29 14:13 UTC, syli9526 commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/CoinFragment.kt
> +            override fun onResponse(dataList: List<Ticker>) {
[bde21a8](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/189/commits/bde21a819081a1e04f111647689b301319edeba7)
일단 Log를 추가해두었고 추후에 Timber적용도 해보겠습니다.

2019-08-29 15:05 UTC, onemask commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/data/source/CoinDataSourceImpl.kt
> +    companion object {
네 알겠습니당!

2019-08-29 15:05 UTC, onemask commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/MainActivity.kt
> +                Toast.makeText(this@MainActivity, "Call Failure : $str", Toast.LENGTH_LONG).show()
어머 죄송해요 다음에 관련 내용 링크 다시 첨부하겠습니다
네 알겠습니다~

2019-08-29 15:07 UTC, onemask submitted a review, later dismissed
수고하셨습니다~
다음번에는 좀 더 빨리 리뷰할 수 있도록 하겠습니다 ㅠㅠ

2019-08-30 01:32 UTC, BeokBeok requested changes
안녕하세요. 스터디 2기 강현석이라고 합니다.
부족하지만 잘 부탁 드립니다 ^~^

2019-08-30 01:32 UTC, BeokBeok commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/data/source/CoinDataSourceImpl.kt
> +
개행은 가급적이면 한 줄 단위로 사용해주세요.

2019-08-30 01:32 UTC, BeokBeok commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/data/source/CoinDataSourceImpl.kt
> +                instance ?: CoinDataSourceImpl().also {
apply 대신 also를 사용하신 이유가 있나요?

2019-08-30 01:32 UTC, BeokBeok commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/data/source/CoinDataSourceImpl.kt
> +            override fun onResponse(call: Call<List<MarketResponse>>, response: Response<List<MarketResponse>>) {
한 줄로 표현하기 긴 경우, 파라미터를 개행해서 작성해주세요.
https://kotlinlang.org/docs/reference/coding-conventions.html#function-formatting

2019-08-30 01:32 UTC, BeokBeok commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/data/source/CoinDataSourceImpl.kt
> +                    val tickerList = it.map { tickerResponse -> tickerResponse.toTicker() }
데이터가 많을 경우, 시퀀스를 사용하는 것을 권장합니다.

2019-08-30 01:32 UTC, BeokBeok commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/adapter/CoinAdapter.kt
> +        this.coinList.apply {
apply 보다 with를 사용하시는 것이 좋을 것 같습니다.

2019-08-30 01:32 UTC, BeokBeok commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/adapter/ViewHolder.kt
> +        tvCompareWithYesterday.setColor(ticker.signedChangeRateColor)
with를 사용하여 중복을 줄일 수 있습니다.

2019-08-30 01:32 UTC, BeokBeok commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/util/CalculateUtils.kt
> +        return if (tradePrice ?: .0 > 1) {
구현부가 리턴만 있는 경우, = 을 사용할 수 있습니다.
https://developer.android.com/kotlin/style-guide#implicit_returnproperty_types
https://kotlinlang.org/docs/reference/functions.html#single-expression-functions

2019-08-30 07:57 UTC, syli9526 commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/data/source/CoinDataSourceImpl.kt
> +                    val tickerList = it.map { tickerResponse -> tickerResponse.toTicker() }
tickerResponse를 여러가지 동작을 하는게 아니라 map만 해주는데 시퀀스로 사용해주는게 좋나요??

2019-08-30 07:59 UTC, syli9526 commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/data/source/CoinDataSourceImpl.kt
> +
[7f6bf99](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/189/commits/7f6bf993ca3d4be8979ddf6959070e81bfc445b1)
수정하였습니다.

2019-08-30 08:01 UTC, syli9526 commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/data/source/CoinDataSourceImpl.kt
> +                instance ?: CoinDataSourceImpl().also {
[40c89fb](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/189/commits/40c89fb6c69a18d17ace8ea4653a716e5be96891)
이유는 따로 없습니다. apply로 바꿨습니다.

2019-08-30 08:04 UTC, syli9526 commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/data/source/CoinDataSourceImpl.kt
> +            override fun onResponse(call: Call<List<MarketResponse>>, response: Response<List<MarketResponse>>) {
[2776b6b](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/189/commits/2776b6bc9d30f4975a48b619311f89297541a495)
수정하였습니다.

2019-08-30 08:05 UTC, syli9526 commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/adapter/CoinAdapter.kt
> +        this.coinList.apply {
[9a02768](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/189/commits/9a02768652eedd7ad4b4d67e6b437ec7590b5a0e)
수정하였습니다.

2019-08-30 08:05 UTC, syli9526 commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/adapter/ViewHolder.kt
> +        tvCompareWithYesterday.setColor(ticker.signedChangeRateColor)
[d70bafb](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/189/commits/d70bafbb607d7c16db5737a38cf543cc87efc578)
수정하였습니다.

2019-08-30 08:06 UTC, syli9526 commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/util/CalculateUtils.kt
> +        return if (tradePrice ?: .0 > 1) {
[2fcbf83](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/189/commits/2fcbf8372b1638b5838f8bc17cf93f324ed25eb9)
수정하였습니다.

2019-08-30 08:42 UTC, BeokBeok commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/data/source/CoinDataSourceImpl.kt
> +                    val tickerList = it.map { tickerResponse -> tickerResponse.toTicker() }
다음은 kotlin in action 에서 시퀀스 관련 내용입니다.

> 큰 컬렉션에 대해서 연산을 연쇄시킬 때는 시퀀스를 사용하는 것을 규칙으로 삼아라.
<중략>
하지만 **컬렉션에 들어있는 원소가 많으면 중간 원소를 재배열하는 비용이 커지기 때문에 지연 계산이 더 낫다.**

map도 하나의 중간연산에 포함되기 때문에 시퀀스로 사용해주는 것이 좋은 것 같습니다.

2019-08-30 08:42 UTC, BeokBeok commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/adapter/ViewHolder.kt
> +        tvCompareWithYesterday.setColor(ticker.signedChangeRateColor)
제가 의도했던 것은
```
with(tvCompareWithYesterday) {
    text = ticker.presentPrice
    setColor(ticker.signedchangeRateColor)
}
```
이 것인데 모호하게 말씀드려서 죄송합니다.

2019-08-30 09:02 UTC, syli9526 commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/adapter/ViewHolder.kt
> +        tvCompareWithYesterday.setColor(ticker.signedChangeRateColor)
[9e069ba](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/189/commits/9e069ba68276bc6baa5df8411497f195b17e4517)
수정하였습니다.

2019-08-30 09:04 UTC, syli9526 commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/data/source/CoinDataSourceImpl.kt
> +                    val tickerList = it.map { tickerResponse -> tickerResponse.toTicker() }
[c4be0c5](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/189/commits/c4be0c5f44085205a30cc0daa7263bc14edb0d0d)
감사합니다!! 수정하였습니다.

2019-08-30 10:41 UTC, BeokBeok approved these changes
LGTM:ok_hand:

2019-08-30 12:50 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-08-30 13:36 UTC, merged