1주차 과제
sjjeong/GoogryAndroidArchitecutreStudy pull request #19
Opened 2019-04-30 15:13 UTC by sabgilhun

2019-04-30 18:32 UTC, improve777 commented on sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/data/remote/upbit/request/UpbitTickerListRequest.kt
> +                for (marketCode in marketCodeList) {
for 문을 filter() 로 변경할 수도 있을 것 같아요

2019-05-01 01:46 UTC, sabgilhun commented on sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/data/remote/upbit/request/UpbitTickerListRequest.kt
> +                for (marketCode in marketCodeList) {
filter를 사용하는게 좀 더 직관성이 있는거 같네요 감사합니다.

bc9b50d232c74ba73698f77dbe9967d0a16f1eee

2019-05-01 07:42 UTC, sjjeong requested changes

2019-05-01 07:42 UTC, sjjeong commented on README.md
> -# GoogryAndroidArchitecutreStudy
`README.md` 다시 추가해주세요

2019-05-01 07:42 UTC, sjjeong commented on sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/data/remote/upbit/UpbitApiHandlerImpl.kt
> +    companion object {
UpbitApiHandlerImpl를 ojbect로 만든다면 싱글턴패턴 구현부분이 필요 없습니다.
다른 문제가 생겨서 이렇게 하셨다면 코멘트 남겨주세요.

2019-05-01 07:42 UTC, sjjeong commented on sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/MainActivity.kt
> +                    tickerList.add(Ticker.from(tickerResponse))
for를 map을 사용해서 변경해보세요.
```kotlin
result.map { ... }
```

2019-05-01 07:42 UTC, sjjeong commented on sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/adapter/TickerAdapter.kt
> +    private var items: MutableList<Ticker>? = null
lazy로 객체를 만들어주면 nonnull하게 사용 할 수 있습니다.
그냥 처음에 객체 만들어줘도 됩니다.

2019-05-01 07:42 UTC, sjjeong commented on sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/data/remote/upbit/request/UpbitTickerListRequest.kt
> +                    }.map {
[joinToString](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/join-to-string.html)으로 변경해보세요.

2019-05-01 13:26 UTC, sabgilhun commented on README.md
> -# GoogryAndroidArchitecutreStudy
ㅎㅎㅎ 실수로 지웠네요

2019-05-01 13:28 UTC, sabgilhun commented on sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/data/remote/upbit/UpbitApiHandlerImpl.kt
> +    companion object {
코틀린에서는 어떻게 만드는지 몰라서  구글 샘플 todoapp에 있는 방법을 따라 썼었습니다.
object 방식으로 변경 했습니다.
5fd5558649d8770470c867c1413f16f4f39e7a4b

2019-05-01 13:29 UTC, sabgilhun commented on sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/MainActivity.kt
> +                    tickerList.add(Ticker.from(tickerResponse))
변경했습니다.

ec2d9d3a593ddc3396e4c75dd5167affb636d882

2019-05-01 13:29 UTC, sabgilhun commented on sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/adapter/TickerAdapter.kt
> +    private var items: MutableList<Ticker>? = null
변경했습니다.

901130d49232fd56df5a43683d615e0cae034d3c

2019-05-01 13:30 UTC, sabgilhun commented on sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/data/remote/upbit/request/UpbitTickerListRequest.kt
> +                    }.map {
변경했습니다.

77a3fe8732b4858438525de2e2b433ed8fec7971

2019-05-01 16:38 UTC, improve777 commented on sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/adapter/TickerViewHolder.kt
> +class TickerViewHolder(itemView: View) : RecyclerView.ViewHolder(itemView) {
스타일인거 같긴 한데 
제 경우에는 뷰홀더에 바로 binding 을 인자로 받아서 이유가 없다면 클래스 몸체가 없어도 되더라구요
```kotlin
class TickerViewHolder(val binding: ItemTickerBinding) : RecyclerView.ViewHolder(binding.root)
```

2019-05-01 16:40 UTC, ddaeyeonkim approved these changes

2019-05-01 16:46 UTC, GongSulMin approved these changes

2019-05-02 01:42 UTC, sabgilhun commented on sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/adapter/TickerViewHolder.kt
> +class TickerViewHolder(itemView: View) : RecyclerView.ViewHolder(itemView) {
이렇게 하면 코드가 더 간결해지네여 👍 

그런데 바깥쪽에서 binding해서 줘야한다는 점이 조금 걸려서... 둘 다 상응할 수 있는 방법을 고민 후 적용해보겠습니다 ~

좋은 의견 감사합니다.😊

2019-05-02 01:42 UTC, sabgilhun commented on sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/adapter/TickerViewHolder.kt
> +class TickerViewHolder(itemView: View) : RecyclerView.ViewHolder(itemView) {
이렇게 하면 코드가 더 간결해지네여 👍

그런데 바깥쪽에서 binding해서 줘야한다는 점이 조금 걸려서... 둘 다 상응할 수 있는 방법을 고민 후 적용해보겠습니다 ~

좋은 의견 감사합니다.😊

2019-05-03 17:14 UTC, sjjeong commented on sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/adapter/TickerViewHolder.kt
> +class TickerViewHolder(itemView: View) : RecyclerView.ViewHolder(itemView) {
방법은 여러가지가 있습니다.
`parent: Parent, layoutId: Int`를 받아서 부모생성자에 inflate하는 코드가 들어가는 방법,
`view: View`를 받는 방법
binding된 객체를 받는 방법
이렇게 3가지가 있을탠데요
지금 단계에서는 크게 중요하지 않아서 본인 취향대로 하시면 될꺼같습니다.

2019-05-03 17:14 UTC, sjjeong approved these changes

2019-05-05 03:43 UTC, merged