HW-2
sjjeong/GoogryAndroidArchitecutreStudy pull request #190
Opened 2019-08-27 01:03 UTC by toctocbin

2019-08-27 15:10 UTC, becooni requested changes
UpbitRemoteDataSourceImpl, UpbitRepository 두 클래스 모두 싱글톤으로 구현하셨는데,

생성자 인자가 없을꺼라면 class가 아닌 object로 선언해도 되지않을까요?

2019-08-27 15:20 UTC, junghum21 commented
컬렉션함수 map() 등의 데이터 처리는 subscribeOn(Schedulers.io()) 이후에 실행할수 있도록 하고,

adapter.addItem() 등의 view 처리는 observeOn(AndroidSchedulers.mainThread()) 이후에 실행하는 것이 효율적이라고 알고 있습니다.

2019-08-27 15:20 UTC, becooni requested changes

2019-08-27 15:20 UTC, junghum21 commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/TickerFragment.kt
>                      adapter.addItem(formatList)
adapter에 아이템을 따로 set하는 함수를 만드는게 좋을것 같네요.

2019-08-28 00:31 UTC, toctocbin commented
f113439
싱글톤 구현 시 생성자 없을 경우 Object로 변경

b776f26
UIThread 전에 데이터 처리

2019-08-28 00:33 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/TickerFragment.kt
>                      adapter.addItem(formatList)
TickerAdapter 안에 
```
    fun setItem(tickerList: List<TickerFormat>) {
        this.tickerFormatList.clear()
        this.tickerFormatList.addAll(tickerList)
        notifyDataSetChanged()
    }
```
이거 말씀하신건가요 ?

b776f26
addItem이 명확하지 않은거 같아 setItem으로 메소드명 변경했습니다.

2019-08-29 02:00 UTC, junghum21 commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/TickerFragment.kt
>                      adapter.addItem(formatList)
후자 입니다.
한개의 메소드는 한개의 역할만 가지는게 좋기 떄문이죠.

2019-08-29 05:47 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/TickerFragment.kt
>                      adapter.addItem(formatList)
f26d98a
아항 넵 반영하였습니다 !

2019-08-29 05:56 UTC, junghum21 commented
수고하셨습니다!

2019-08-29 08:45 UTC, BeokBeok requested changes
안녕하세요. 스터디 2기 강현석이라고 합니다.
부족하지만 잘 부탁드립니다. ^~^

2019-08-29 08:45 UTC, BeokBeok commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/MainActivity.kt
> +    private val upbitRepository: UpbitRepository by lazy { UpbitRepository }
초기화 식이 있는 경우에는 타입 명시를 하지 않으셔도 됩니다.

2019-08-29 08:45 UTC, BeokBeok commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/MainActivity.kt
> +            .map { list: List<Market> ->
타입 추론이 가능한 경우에는 타입 명시를 하지 않으셔도 되며,
데이터가 많을 경우, 시퀀스를 이용하는 것을 권장합니다.

2019-08-29 08:45 UTC, BeokBeok commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/MainActivity.kt
> +                            marketSearch = value.joinToString(separator = ",") { it.market }
joinToString 은 default separator가 콤마이므로, 파라미터를 생략하셔도 됩니다.

2019-08-29 08:45 UTC, BeokBeok commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/adpter/TickerAdapter.kt
> +    private val tickerFormatList: MutableList<TickerFormat> = ArrayList()
```suggestion
    private val tickerFormatList = mutableListOf<TickerFormat>()
```
이렇게 사용하셔도 될 것 같습니다.

2019-08-29 08:45 UTC, BeokBeok commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/adpter/TickerAdapter.kt
> +        return tickerFormatList.size
구현부에 return 문 하나만 있는 경우, = 을 사용하여 표현이 가능합니다.

2019-08-29 08:45 UTC, BeokBeok commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/adpter/TickerAdapter.kt
> +        this.tickerFormatList.addAll(tickerList)
with 를 사용하여 this.tickerFormatList 중복 사용을 제거할 수 있습니다.

2019-08-29 08:45 UTC, BeokBeok commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/network/RetrofitClient.kt
> +    private val retrofitService: RetrofitService
lazy 를 통하여 초기화 할 수 있습니다.

2019-08-29 08:45 UTC, BeokBeok commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/network/RetrofitService.kt
> +    fun loadTickerData(@Query("markets") markets: String): Single<List<Ticker>>
annotation 은 기본적으로 줄바꿈합니다.
https://kotlinlang.org/docs/reference/coding-conventions.html#annotation-formatting

2019-08-29 08:45 UTC, BeokBeok commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/MainActivity.kt
>  import com.test.androidarchitecture.network.RetrofitClient
불필요한 import 는 정리해주세요.

2019-08-29 08:45 UTC, BeokBeok commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/TickerFragment.kt
>      @SuppressLint("CheckResult")
disposable 을 관리하지 않고 annotation 을 명시해준 이유가 있나요?

2019-08-29 13:33 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/MainActivity.kt
> +    private val upbitRepository: UpbitRepository by lazy { UpbitRepository }
b3444d0

안녕하세요 ! 적용했습니다.

2019-08-29 13:34 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/MainActivity.kt
> +            .map { list: List<Market> ->
06f2981

이런식으로 변경하는거 맞나요 ??

55a465b

ticker 부분도 변경 해봤습니다.

2019-08-29 13:57 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/MainActivity.kt
> +                            marketSearch = value.joinToString(separator = ",") { it.market }
05e1773

적용했습니다!

2019-08-29 13:58 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/adpter/TickerAdapter.kt
> +    private val tickerFormatList: MutableList<TickerFormat> = ArrayList()
97f686c

변경했습니다!

2019-08-29 13:58 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/adpter/TickerAdapter.kt
> +        this.tickerFormatList.addAll(tickerList)
f9ce88d

변경했습니다

2019-08-29 13:59 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/adpter/TickerAdapter.kt
> +        return tickerFormatList.size
f9ce88d

변경했습니다!

2019-08-29 14:00 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/network/RetrofitService.kt
> +    fun loadTickerData(@Query("markets") markets: String): Single<List<Ticker>>
6650521

이런식으로 하면 되나요 ?

2019-08-29 14:00 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/MainActivity.kt
>  import com.test.androidarchitecture.network.RetrofitClient
60291f8

넵 제거했습니다.

2019-08-29 14:11 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/TickerFragment.kt
>      @SuppressLint("CheckResult")
26dd4a0

변경해봤습니다!

2019-08-29 14:34 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/network/RetrofitClient.kt
> +    private val retrofitService: RetrofitService
어떤 식으로 해야하는지 힌트좀 주실 수 있을까요?!

2019-08-30 01:45 UTC, BeokBeok commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/network/RetrofitService.kt
> +    fun loadTickerData(@Query("markets") markets: String): Single<List<Ticker>>
네 맞습니다.
또한, 함수 포메팅도 적용해주세요.
https://kotlinlang.org/docs/reference/coding-conventions.html#function-formatting

2019-08-30 01:45 UTC, BeokBeok reviewed
커밋 시에 "HW-주차" 를 붙여주세요.

2019-08-30 05:32 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/network/RetrofitService.kt
> +    fun loadTickerData(@Query("markets") markets: String): Single<List<Ticker>>
c2a0827

적용했습니다 !

2019-08-30 08:43 UTC, BeokBeok approved these changes
LGTM:ok_hand:

2019-08-30 13:29 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-08-31 03:03 UTC, becooni approved these changes

2019-08-31 03:03 UTC, merged