HW-2 모델 repository 패턴 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #192
Opened 2019-08-27 14:38 UTC by jskim5923

* RemoteDataSource 인터페이스를 추가하여, remote에서 받아올 함수를 명세하였습니다.

* RemoteDataSource object를 추가하여, 싱글톤으로 사용할 수 있도록 하였습니다.
   Retrofit객체를 이용하여 RemoteDataSource를 구현합니다.
*  repository를 object로  추가하여 싱글톤으로 사용할 수 있도록 하였으며, RemoteDataSource를 
  RemoteDataSource를 통해 구현합니다.
4. 기존의 Ticker -> TickerResponse로 변경 및 TIcker데이터 클래스를 생성하여, 데이터를 받아올 데이터클래스와 CoinFragment - Recycler에 bind할 데이터클래스로 나눴습니다.
5.

2019-08-28 08:38 UTC, seonoh submitted a review, later dismissed
수고하셨습니다 종선님 !

2019-08-28 08:38 UTC, seonoh commented on jskim5923/ArchitectureStudy/app/src/main/java/com/jskim5923/architecturestudy/ui/CoinFragment.kt
> -        compositeDisposable += ApiManager.coinApi.getMarketList()
제가 아직 compositeDisposable 어레이 스트림이라고만 알고 있었고 많이 사용하지 않았는데,
종선님 코드 보니 무척이나 깔끔하네요!! 아마 제 코드를 수정해야할 것 같습니다 ㅎㅎ

2019-08-28 12:58 UTC, BeokBeok requested changes
안녕하세요. 스터디 2기 강현석이라고 합니다.
부족하지만 잘 부탁드립니다 ^~^

2019-08-28 12:58 UTC, BeokBeok commented on jskim5923/ArchitectureStudy/app/src/main/java/com/jskim5923/architecturestudy/api/CoinApi.kt
> +    fun getTicker(@Query("markets") markets: String): Single<List<TickerResponse>>
Annotation은 일반적으로 개행해서 사용합니다.
https://kotlinlang.org/docs/reference/coding-conventions.html#annotation-formatting

2019-08-28 12:58 UTC, BeokBeok commented on jskim5923/ArchitectureStudy/app/src/main/java/com/jskim5923/architecturestudy/model/TickerResponse.kt
> +    @SerializedName("trade_date") val tradeDate: String,
사용하지 않는 변수를 제거하고 필요한 SerializedName만 선별해서 사용가능합니다.

2019-08-28 12:58 UTC, BeokBeok commented on jskim5923/ArchitectureStudy/app/src/main/java/com/jskim5923/architecturestudy/model/TickerResponse.kt
> +        return Ticker(
구현부에 return 만 있는 경우, = 을 사용하여 처리할 수 있습니다.

2019-08-28 12:58 UTC, BeokBeok commented on jskim5923/ArchitectureStudy/app/src/main/java/com/jskim5923/architecturestudy/ui/CoinFragment.kt
> +            .flattenAsObservable { tickerResponseList ->
데이터가 많을 경우, 시퀀스로 변환해서 사용하시면 좋습니다.

2019-08-28 12:58 UTC, BeokBeok commented on jskim5923/ArchitectureStudy/app/src/main/java/com/jskim5923/architecturestudy/util/DataFormatUtils.kt
> +                var tradeVolume: Long = accTradePrice24h.toLong()
초기화 식을 사용한 경우에는 컴파일러가 타입을 추론할 수 있기 때문에 변수 타입을 생략할 수 있습니다.

2019-08-28 12:58 UTC, BeokBeok commented on jskim5923/ArchitectureStudy/app/src/main/java/com/jskim5923/architecturestudy/util/DataFormatUtils.kt
> +        return when (market.getCoinCurrency()) {
when 을 리턴하는 경우, 중괄호를 제거하고 = 을 사용하여 표현할 수 있습니다.
https://kotlinlang.org/docs/reference/basic-syntax.html#using-when-expression

2019-08-28 12:58 UTC, BeokBeok commented on jskim5923/ArchitectureStudy/app/src/main/java/com/jskim5923/architecturestudy/api/CoinApi.kt
>  import com.jskim5923.architecturestudy.model.Ticker
Ticker에서 TickerResponse로 변경함으로써 사용하지 않는 import 는 제거해주세요.

2019-08-28 12:58 UTC, BeokBeok commented on jskim5923/ArchitectureStudy/app/src/main/java/com/jskim5923/architecturestudy/adapter/CoinListAdapter.kt
> +            diff.run {
with 대신 run 을 사용한 이유가 있나요?

2019-08-28 13:32 UTC, jskim5923 commented on jskim5923/ArchitectureStudy/app/src/main/java/com/jskim5923/architecturestudy/api/CoinApi.kt
> +    fun getTicker(@Query("markets") markets: String): Single<List<TickerResponse>>
감사합니다.
[d6d0dbb](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/192/commits/d6d0dbb4d69d03d74a636ac2efd3f61fab8e236c) 적용했습니다.

2019-08-28 13:40 UTC, jskim5923 commented on jskim5923/ArchitectureStudy/app/src/main/java/com/jskim5923/architecturestudy/model/TickerResponse.kt
> +    @SerializedName("trade_date") val tradeDate: String,
감사합니다.
추후 다른곳에서 다른 필드를 사용할 경우를 위해 제거하지 않았는데,
여기서는 말씀해주신 대로 적용하는 것이 맞는 것 같습니다.
이전에 코멘트 주신대로 Annotation convension 도 같이 적용 하겠습니다.
[9324279] (https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/192/commits/93242790a2e7fee6aaabc39beacc07b6824e0617) 적용했습니다.

2019-08-28 13:45 UTC, jskim5923 commented on jskim5923/ArchitectureStudy/app/src/main/java/com/jskim5923/architecturestudy/model/TickerResponse.kt
> +        return Ticker(
감사합니다.
타입 추론 추가 적용하였습니다.
[73aa23c]

2019-08-28 13:46 UTC, jskim5923 commented on jskim5923/ArchitectureStudy/app/src/main/java/com/jskim5923/architecturestudy/util/DataFormatUtils.kt
> +                var tradeVolume: Long = accTradePrice24h.toLong()
감사합니다.
[22789e7] 적용했습니다.

2019-08-28 13:52 UTC, jskim5923 commented on jskim5923/ArchitectureStudy/app/src/main/java/com/jskim5923/architecturestudy/util/DataFormatUtils.kt
> +        return when (market.getCoinCurrency()) {
감사합니다.
if 표현식, 타입 추론 추가 적용 하였습니다.
[750e40b]

2019-08-28 13:54 UTC, jskim5923 commented on jskim5923/ArchitectureStudy/app/src/main/java/com/jskim5923/architecturestudy/api/CoinApi.kt
>  import com.jskim5923.architecturestudy.model.Ticker
감사합니다.
[d6d0dbb] 적용했습니다.

2019-08-28 13:59 UTC, jskim5923 commented on jskim5923/ArchitectureStudy/app/src/main/java/com/jskim5923/architecturestudy/adapter/CoinListAdapter.kt
> +            diff.run {
평소에 with 대신 run으로 대체해서 사용하던 버릇이 있습니다.
`diff` 가 `TextView` 이기 떄문에 코멘트 주신 대로 적용하는 것이 맞는 것 같습니다.
[8f4b597] 적용했습니다.

2019-08-28 14:23 UTC, jskim5923 commented on jskim5923/ArchitectureStudy/app/src/main/java/com/jskim5923/architecturestudy/ui/CoinFragment.kt
> +            .flattenAsObservable { tickerResponseList ->
감사합니다.
시퀀스에 대해 모르고 있었는데,  하나 배웠습니다.
https://blog.kotlin-academy.com/effective-kotlin-use-sequence-for-bigger-collections-with-more-than-one-processing-step-649a15bb4bf

[e4ff955] 적용했습니다. 처음 사용해봤는데 맞게 사용했는지 확인 부탁드립니다.

2019-08-28 14:26 UTC, BeokBeok approved these changes
LGTM:ok_hand:

2019-08-28 14:28 UTC, BeokBeok commented
추가로 커밋 시 앞에 "HW-주차" 를 넣어주세요.
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/tree/master/sjjeong#pr-commit

2019-08-29 13:49 UTC, jskim5923 commented on jskim5923/ArchitectureStudy/app/src/main/java/com/jskim5923/architecturestudy/ui/CoinFragment.kt
> -        compositeDisposable += ApiManager.coinApi.getMarketList()
코멘트를 늦게봤네요 ㅠㅠ
저도 이 부분이 아직 정립이 안됐어요 
제가 틀리고 선오님이 맞으실 수도 있는 부분입니다!

2019-08-29 13:51 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-08-29 14:57 UTC, merged