HW-05 Databinding 추가
sjjeong/GoogryAndroidArchitecutreStudy pull request #194
Opened 2019-08-28 12:24 UTC by zojae031

2019-09-02 04:22 UTC, wkdehdlr submitted a review, later dismissed
고생하셨습니다!! 이번주는 딱히 리뷰랄게 없네요!! 제 것 수정해서 반영해놓겠습니다!

2019-09-02 09:58 UTC, BeokBeok requested changes
안녕하세요. 스터디 2기 강현석이라고 합니다.
부족하지만 잘 부탁드립니다. ^~^

2019-09-02 09:58 UTC, BeokBeok commented on zojae031/Project/app/src/main/java/study/architecture/ui/coinjob/CoinDataAdapter.kt
개행은 가급적이면 한 줄로 처리해주세요

2019-09-02 09:58 UTC, BeokBeok commented on zojae031/Project/app/src/main/java/study/architecture/ui/coinjob/CoinDataAdapter.kt
> +    override fun onCreateViewHolder(parent: ViewGroup, viewType: Int): Holder {
변수와 함수 사이에 개행하여 구분해주세요.

2019-09-02 09:58 UTC, BeokBeok commented on zojae031/Project/app/src/main/java/study/architecture/ui/coinjob/CoinDataAdapter.kt
> +            LayoutInflater.from(parent.context), parent, false
아래와 같이 정리하시는 것이 좋아 보입니다.
```suggestion
            LayoutInflater.from(parent.context), 
            parent, 
            false
```
https://kotlinlang.org/docs/reference/coding-conventions.html#method-call-formatting

2019-09-02 09:58 UTC, BeokBeok commented on zojae031/Project/app/src/main/java/study/architecture/ui/coinjob/CoinDataAdapter.kt
> +        private val tradePrice: TextView = itemView.tradePrice
itemView가 RecyclerView.ViewHolder 에 존재하는데 해당 itemView를 활용하시는 것은 어떠신가요?

2019-09-02 09:58 UTC, BeokBeok commented on zojae031/Project/app/src/main/java/study/architecture/ui/coinjob/CoinFragment.kt
> +    override fun onCreateView(inflater: LayoutInflater, container: ViewGroup?, savedInstanceState: Bundle?): View? {
파라미터 길이가 길어서 정리가 필요해보입니다.
https://kotlinlang.org/docs/reference/coding-conventions.html#function-formatting

2019-09-02 09:58 UTC, BeokBeok commented on zojae031/Project/app/src/main/java/study/architecture/ui/mainjob/MainActivity.kt
> +    private val binding by lazy { DataBindingUtil.setContentView<ActivityMainBinding>(this, R.layout.activity_main) }
onCreate 에서 초기화하지 않고 상단에 초기화를 하신 이유가 있나요?

2019-09-02 09:58 UTC, BeokBeok commented on zojae031/Project/app/src/main/java/study/architecture/ui/mainjob/MainActivity.kt
> +                    binding.pager.currentItem = tab!!.position
파라미터 타입이 nullable인데 강제로 nonnull 처리를 할 경우 문제가 없나요?

2019-09-02 09:58 UTC, BeokBeok commented on zojae031/Project/app/src/main/java/study/architecture/ui/mainjob/MainActivity.kt
> +        binding.pager.adapter = MainPageAdapter(supportFragmentManager)
with를 사용하여 정리하는 것이 좋아보입니다.

2019-09-02 09:58 UTC, BeokBeok commented on zojae031/Project/app/src/main/res/layout/activity_main.xml
> +    <data>
사용하지 않다면, 제거해주세요.

2019-09-02 09:58 UTC, BeokBeok commented on zojae031/Project/app/src/main/res/layout/activity_main.xml
> +                android:text="KRW" />
가급적이면 strings.xml에 있는 리소스를 참조해주세요.

2019-09-02 09:58 UTC, BeokBeok commented on zojae031/Project/app/src/main/res/layout/activity_main.xml
> +            android:id="@+id/dataWrapper"
안드로이드 리소스는 snake case를 권장합니다.
https://medium.com/mindorks/android-resource-naming-convention-42e4e8026614

2019-09-02 09:58 UTC, BeokBeok commented on zojae031/Project/app/src/main/res/layout/activity_main.xml
> +            android:layout_width="match_parent"
constraint layout 의 자식 view는 match_parent 대신 0dp를 써주세요

2019-09-02 09:58 UTC, BeokBeok commented on zojae031/Project/app/src/main/res/layout/activity_main.xml
> +            app:layout_constraintTop_toBottomOf="@+id/tabLayout">
id를 만드는 것이 아니라면 +는 제거해주세요

2019-09-02 09:58 UTC, BeokBeok commented on zojae031/Project/app/src/main/res/layout/activity_main.xml
> +                android:layout_weight="1"
weight를 사용하는데 wrap_content 를 사용하신 이유가 있나요?

2019-09-02 09:58 UTC, BeokBeok commented on zojae031/Project/app/src/main/res/layout/fragment_coin.xml
> +        <ImageView
ContentDiscription 속성을 사용하지 않는다면,
tools:ignore="ContentDescription"
을 추가해주세요.

2019-09-02 09:58 UTC, BeokBeok commented on zojae031/Project/app/src/main/res/layout/fragment_coin.xml
> +            android:layout_marginBottom="8dp"
`android:layout_margin="40dp"` 와 
```android:layout_margin="
android:layout_marginStart="8dp"
android:layout_marginTop="8dp"
android:layout_marginEnd="8dp"
android:layout_marginBottom="8dp"
```
의 차이는 무엇인가요?

2019-09-02 09:58 UTC, BeokBeok commented on zojae031/Project/app/src/main/res/layout/list_item.xml
> +                android:gravity="left"
left 대신 start를 넣어주세요

2019-09-02 09:58 UTC, BeokBeok commented on zojae031/Project/app/src/main/res/layout/list_item.xml
> +                android:gravity="center|right"
right 대신 end를 넣어주세요.

2019-09-02 09:58 UTC, BeokBeok commented on zojae031/Project/app/src/main/res/layout/list_item.xml
> +                android:textSize="10sp" />
텍스트 크기는 최소 12sp 이상으로 하시는 것을 권장합니다.

2019-09-02 09:58 UTC, BeokBeok commented on zojae031/Project/app/src/main/res/layout/switch_item.xml
> +            android:layout_centerVertical="true" />
```
android:layout_centerHorizontal="true"
android:layout_centerVertical="true"
```
를 `android:layout_centerInParent="true"`  로 사용할 수 있습니다.

2019-09-03 13:46 UTC, BeokBeok requested changes

2019-09-03 13:46 UTC, BeokBeok commented on zojae031/Project/app/src/main/java/study/architecture/ui/coinjob/CoinDataAdapter.kt
> +        binding.executePendingBindings()
executePendingBindings 는 왜 사용하신 것인가요?

2019-09-04 04:41 UTC, zojae031 commented on zojae031/Project/app/src/main/java/study/architecture/ui/mainjob/MainActivity.kt
> +    private val binding by lazy { DataBindingUtil.setContentView<ActivityMainBinding>(this, R.layout.activity_main) }
binding 변수같은경우는 MainActivity에서 전역적으로 사용되기 때문에 lazy 초기화를 사용하였습니다.

2019-09-04 05:12 UTC, zojae031 commented on zojae031/Project/app/src/main/java/study/architecture/ui/coinjob/CoinDataAdapter.kt
> +        binding.executePendingBindings()
https://developer.android.com/topic/libraries/data-binding/generated-binding?hl=ko#advanced_binding
도익님 리뷰에서도 보았지만 해당 이슈에 관련하여 정석준 멘토님께서 필수로 사용하라고 말씀하셨던것 같습니다. @sjjeong

2019-09-04 05:14 UTC, zojae031 commented on zojae031/Project/app/src/main/java/study/architecture/ui/coinjob/CoinDataAdapter.kt
수정 커밋입니다. [05594b1](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/194/commits/05594b1ef7d98f25acb97699125856f8681102c8)

2019-09-04 05:14 UTC, zojae031 commented on zojae031/Project/app/src/main/java/study/architecture/ui/coinjob/CoinDataAdapter.kt
> +    override fun onCreateViewHolder(parent: ViewGroup, viewType: Int): Holder {
[63eeea7](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/194/commits/63eeea7e3a3697a778760736580852a4a185a8cc)
수정 커밋입니다. 나름 컨벤션 지키면서 하고있었다 생각했는데 
놓친부분이 엄청많았군요 ㅠㅠ감사합니다.

2019-09-04 05:15 UTC, zojae031 commented on zojae031/Project/app/src/main/java/study/architecture/ui/coinjob/CoinDataAdapter.kt
> +            LayoutInflater.from(parent.context), parent, false
[e180909](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/194/commits/e1809098c3f0dcf9e95831dbdfeabc51d99165e5)

2019-09-04 05:15 UTC, zojae031 commented on zojae031/Project/app/src/main/java/study/architecture/ui/coinjob/CoinFragment.kt
> +    override fun onCreateView(inflater: LayoutInflater, container: ViewGroup?, savedInstanceState: Bundle?): View? {
[9a59c42](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/194/commits/9a59c4229ff3bf222645d774b988d2ca3739df8b)

2019-09-04 05:16 UTC, zojae031 commented on zojae031/Project/app/src/main/java/study/architecture/ui/mainjob/MainActivity.kt
> +                    binding.pager.currentItem = tab!!.position
[af4217b](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/194/commits/af4217bfbcc16fa067e252fabad9a87fce0a63d0) 미처 확인하지 못하였네요 TabLayout.Tab을 Non-nullable하게 만들었는데 혹시 관련하여 문제가 되나요?

2019-09-04 05:16 UTC, zojae031 commented on zojae031/Project/app/src/main/java/study/architecture/ui/mainjob/MainActivity.kt
> +        binding.pager.adapter = MainPageAdapter(supportFragmentManager)
(8238740)[https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/194/commits/82387405bddb68bcba0bde2f5015ca4921925ef0]

2019-09-04 05:17 UTC, zojae031 commented on zojae031/Project/app/src/main/res/layout/activity_main.xml
> +    <data>
(412af10)[https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/194/commits/8894848cec972c2f570e44c04a3b814c44e51632]

2019-09-04 05:19 UTC, zojae031 commented on zojae031/Project/app/src/main/res/layout/activity_main.xml
> +                android:text="KRW" />
[412af10](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/194/commits/412af107ed47a5263dcd4d05dcf70e23631f601b)
관련하여 string.xml리소스를 참조하면 좋은 이점이 유지보수가 쉬운거 이외에 또 있을까요?

2019-09-04 05:19 UTC, zojae031 commented on zojae031/Project/app/src/main/res/layout/activity_main.xml
> +            android:id="@+id/dataWrapper"
[525a26f](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/194/commits/525a26f901585746e3bdefc62844f31049a0c6eb)

2019-09-04 05:20 UTC, zojae031 commented on zojae031/Project/app/src/main/res/layout/activity_main.xml
> +            android:layout_width="match_parent"
[5d48a6d](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/194/commits/5d48a6d7d063f744d143a21712172b9b761ea899) 해당 관련해서도 궁금합니다.
match_parent와 0dp에 무슨 차이가 있는거죠?

2019-09-04 05:21 UTC, zojae031 commented on zojae031/Project/app/src/main/res/layout/activity_main.xml
> +            app:layout_constraintTop_toBottomOf="@+id/tabLayout">
[34c6a2b](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/194/commits/34c6a2bd622cf17515be044f20004970e8fab98c)
id를 만드는것에 + 를 붙이고
참조하는것에는 붙이지 않는걸 이번에 처음알았네요 감사합니다!

2019-09-04 05:21 UTC, zojae031 commented on zojae031/Project/app/src/main/res/layout/activity_main.xml
> +                android:layout_weight="1"
[eea3646](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/194/commits/eea3646e420b5faaa1163a5d186a86a9bd7e3b6b)
이건 제가 미처 확인하지 못한 것 같습니다. 감사합니다.

2019-09-04 05:23 UTC, zojae031 commented on zojae031/Project/app/src/main/res/layout/fragment_coin.xml
> +        <ImageView
[bb2aa56](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/194/commits/bb2aa5623fc444012ec4e080bc8602423edc9227)
해당 관련해서 찾아보다가 접근성 관련 속성이라고 하는데
정확히 잘 모르겠습니다. 혹시 링크나 흰트 부탁드려도 될까요?

2019-09-04 05:25 UTC, zojae031 commented on zojae031/Project/app/src/main/res/layout/fragment_coin.xml
> +            android:layout_marginBottom="8dp"
[bb2aa56](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/194/commits/bb2aa5623fc444012ec4e080bc8602423edc9227)
``layout_margin``으로 바꾸었고 두개의 차이는 layout_margin같은경우
6개의속성에 모두 영향을 준다로 알고있습니다.
```
layout_maginStart
layout_maginLeft
layout_maginTop
layout_maginEnd
layout_maginRight
layout_maginBouttm
```

2019-09-04 05:26 UTC, zojae031 commented on zojae031/Project/app/src/main/res/layout/list_item.xml
> +                android:gravity="left"
acebbb7

2019-09-04 05:26 UTC, zojae031 commented on zojae031/Project/app/src/main/res/layout/list_item.xml
> +                android:gravity="center|right"
acebbb7

2019-09-04 05:26 UTC, zojae031 commented on zojae031/Project/app/src/main/res/layout/list_item.xml
> +                android:textSize="10sp" />
acebbb7

2019-09-04 05:27 UTC, zojae031 commented on zojae031/Project/app/src/main/res/layout/switch_item.xml
> +            android:layout_centerVertical="true" />
4bb50eb
해당 속성관련해서 처음 접하게 되었네요 감사합니다

2019-09-04 06:56 UTC, BeokBeok commented on zojae031/Project/app/src/main/java/study/architecture/ui/mainjob/MainActivity.kt
> +    private val binding by lazy { DataBindingUtil.setContentView<ActivityMainBinding>(this, R.layout.activity_main) }
setContentView 함수를 onCreate scope에서 하는 것이 좋아 보입니다.
https://developer.android.com/topic/libraries/data-binding/expressions#binding_data

2019-09-04 06:56 UTC, BeokBeok commented on zojae031/Project/app/src/main/java/study/architecture/ui/mainjob/MainActivity.kt
> +                    binding.pager.currentItem = tab!!.position
오버라이딩 시 파라미터 타입이 nullable 이라는 것은
특정 상황에서 nullable 하기 때문이지 않을까 생각합니다.

해서, 강제로 nonnull 처리를 하는 것보다는
null 이 아닐 경우에 동작하도록 처리하는 것이 맞다고 생각합니다.

2019-09-04 06:57 UTC, BeokBeok commented on zojae031/Project/app/src/main/res/layout/activity_main.xml
> +    <data>
커밋 id가 해당 리뷰 수정사항과 다른 것 같습니다.

2019-09-04 06:57 UTC, BeokBeok commented on zojae031/Project/app/src/main/res/layout/activity_main.xml
> +                android:text="KRW" />
유지보수에 용이하며, 단말에 설정된 언어에 따라 번역도 가능합니다.

2019-09-04 06:57 UTC, BeokBeok commented on zojae031/Project/app/src/main/res/layout/activity_main.xml
> +            android:layout_width="match_parent"
constraint layout 에서는 match_parent 는 권장하지 않습니다.

> Important: MATCH_PARENT is not recommended for widgets contained in a ConstraintLayout. Similar behavior can be defined by using MATCH_CONSTRAINT with the corresponding left/right or top/bottom constraints being set to "parent"

https://developer.android.com/reference/android/support/constraint/ConstraintLayout

2019-09-04 06:57 UTC, BeokBeok commented on zojae031/Project/app/src/main/res/layout/fragment_coin.xml
> +        <ImageView
`tools:ignore`는 단순히 warning을 무시하는 용도로 사용합니다.
ContentDiscription 은 해당 뷰에 라벨을 붙이는 것인데, 사용하지 않는다면 무시하셔도 됩니다.
또한, `android:contentDescription="@null"` 로 처리하셔도 됩니다.

2019-09-04 06:57 UTC, BeokBeok commented on zojae031/Project/app/src/main/res/layout/fragment_coin.xml
> +            android:layout_marginBottom="8dp"
Left와 Start, Right와 End는 서로 같다고 보시면 됩니다.
해서 4개의 속성이라고 보시면 되서, 결과적으로는 동일하다고 볼 수 있습니다.

2019-09-04 06:57 UTC, BeokBeok commented on zojae031/Project/app/src/main/java/study/architecture/ui/coinjob/CoinDataAdapter.kt
> +        binding.executePendingBindings()
링크의 아래 글을 보질 못했네요.
덕분에 하나 알아갑니다.
감사합니다. 👍

2019-09-05 01:31 UTC, zojae031 commented on zojae031/Project/app/src/main/java/study/architecture/ui/mainjob/MainActivity.kt
> +    private val binding by lazy { DataBindingUtil.setContentView<ActivityMainBinding>(this, R.layout.activity_main) }
해당 글에보면 왜 onCreate에서 하면 좋은지 명시되있지 않은데 왜 그런가요???
또 onCreate에
```kotlin
override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)

    val binding: ActivityMainBinding = DataBindingUtil.setContentView(
            this, R.layout.activity_main)

    binding.user = User("Test", "User")
}
```

이런식으로 명시하면 onCreate에서만 쓰이게 되니 보통 전역으로
```kotlin
private lateinit var binding :ActivityMainBinding
```
이렇게 선언하고 사용하나요?

2019-09-05 01:33 UTC, zojae031 commented on zojae031/Project/app/src/main/java/study/architecture/ui/mainjob/MainActivity.kt
> +                    binding.pager.currentItem = tab!!.position
null이 아닐 경우 동작하도록 처리하라는 말씀은
```kotlin
binding.pager.currentItem = tab?.position
``` 
이렇게 사용하라고 하시는건가요??

2019-09-05 01:34 UTC, zojae031 commented on zojae031/Project/app/src/main/res/layout/activity_main.xml
> +    <data>
죄송합니다

8894848

2019-09-05 01:35 UTC, zojae031 commented on zojae031/Project/app/src/main/res/layout/activity_main.xml
> +                android:text="KRW" />
오 string.xml에 두게 된다면 만약 영어로 설정하면 영어로 자동번역이 되나요?

2019-09-05 01:36 UTC, zojae031 commented on zojae031/Project/app/src/main/res/layout/activity_main.xml
> +            android:layout_width="match_parent"
감사합니다

2019-09-05 01:37 UTC, zojae031 commented on zojae031/Project/app/src/main/res/layout/fragment_coin.xml
> +        <ImageView
감사합니다

2019-09-05 01:38 UTC, zojae031 commented on zojae031/Project/app/src/main/res/layout/fragment_coin.xml
> +            android:layout_marginBottom="8dp"
오 사실 무슨차이인지 긴가민가 했었는데 감사합니다.

2019-09-05 02:07 UTC, BeokBeok commented on zojae031/Project/app/src/main/java/study/architecture/ui/mainjob/MainActivity.kt
> +    private val binding by lazy { DataBindingUtil.setContentView<ActivityMainBinding>(this, R.layout.activity_main) }
대부분 setContentView 함수를 onCreate 함수단에서 처리를 합니다.
해서, 말씀하신 대로 lateinit 으로 binding 변수를 초기화를 하지만
생각해보니 이 부분은 개발자마다 다를 것 같습니다.

2019-09-05 02:07 UTC, BeokBeok commented on zojae031/Project/app/src/main/java/study/architecture/ui/mainjob/MainActivity.kt
> +                    binding.pager.currentItem = tab!!.position
`binding.pager.currentItem = tab?.position ?: 0`
이렇게 하시면 될 것 같습니다.

2019-09-05 02:07 UTC, BeokBeok commented on zojae031/Project/app/src/main/res/layout/activity_main.xml
> +                android:text="KRW" />
리소스 별 폴더를 생성하고 각 폴더별 strings.xml을 넣게 되면, 
단말 언어별로 string을 보여줍니다.
```
values-ko
values-en
```
자세한 내용은 안드로이드 리소스 관련해서 찾아보시면 될 것 같습니다.

2019-09-05 03:02 UTC, zojae031 commented on zojae031/Project/app/src/main/res/layout/activity_main.xml
> +                android:text="KRW" />
감사합니다!

2019-09-05 03:05 UTC, zojae031 commented on zojae031/Project/app/src/main/java/study/architecture/ui/mainjob/MainActivity.kt
> +                    binding.pager.currentItem = tab!!.position
ad8fb58
감사합니다 엘비스 연산자가 아직 미숙하여 미처 생각하지 못했네요

2019-09-05 03:06 UTC, zojae031 commented on zojae031/Project/app/src/main/java/study/architecture/ui/mainjob/MainActivity.kt
> +    private val binding by lazy { DataBindingUtil.setContentView<ActivityMainBinding>(this, R.layout.activity_main) }
현석님은 보통 어떻게 하시나요??

2019-09-05 03:19 UTC, BeokBeok commented on zojae031/Project/app/src/main/java/study/architecture/ui/mainjob/MainActivity.kt
> +    private val binding by lazy { DataBindingUtil.setContentView<ActivityMainBinding>(this, R.layout.activity_main) }
저는 setContentView 라는 함수를 onCreate 함수에서 호출해줘야하는 느낌이 강해서
binding 변수를 맴버변수로 lateinit으로 선언하여 사용합니다.

2019-09-05 10:55 UTC, zojae031 commented on zojae031/Project/app/src/main/java/study/architecture/ui/mainjob/MainActivity.kt
> +    private val binding by lazy { DataBindingUtil.setContentView<ActivityMainBinding>(this, R.layout.activity_main) }
감사합니다 
1420179
반영커밋입니다.

2019-09-05 13:35 UTC, BeokBeok approved these changes
LGTM:ok_hand:

2019-09-08 03:29 UTC, wkdehdlr approved these changes
고생하셨습니다

2019-09-08 04:45 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-09-08 04:46 UTC, merged