Class03/ganghee
sjjeong/GoogryAndroidArchitecutreStudy pull request #195
Opened 2019-08-28 14:28 UTC by ganghee

MVP패턴의 프로젝트에 kotlin extends를 없애고 databinding을 사용했습니다.

2019-09-02 12:42 UTC, wswon commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/adapter/UpbitHolder.kt
> +        rvBinding.apply { item = ticker }
사소하지만.. 
```suggestion
        rvBinding.item = ticker
```
이렇게만 해도 되지않을까요?

2019-09-02 12:42 UTC, wswon commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/ui/UpbitFragment.kt
>      private val MARKET_NAME = "market name"
석준님 리뷰중에
```suggestion
   const val MARKET_NAME = "market name"
```
이렇게 상수로 companion object로 관리하라는 리뷰를 봤던거같아요!

2019-09-02 12:42 UTC, wswon commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/ui/MainActivity.kt
> +    lateinit var binding : ActivityMainBinding
private으로 선언해도 되지않을까요??

2019-09-02 12:42 UTC, wswon commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/adapter/UpbitHolder.kt
> +    private var rvBinding: RvItemListBinding = binding
`class UpbitHolder(binding: RvItemListBinding) : RecyclerView.ViewHolder(binding.root) {`
이부분에서 

`class UpbitHolder(private val binding: RvItemListBinding) : RecyclerView.ViewHolder(binding.root) {`

이렇게 바로 선언해서 사용해도 될꺼같아요!

2019-09-02 16:56 UTC, ganghee commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/ui/UpbitFragment.kt
>      private val MARKET_NAME = "market name"
네! 수정하였습니다!!
[UpbitFragment](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/195/commits/74cc9e99b83e10f34ab1bbf083893da820e78a62)

2019-09-02 16:56 UTC, ganghee commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/ui/MainActivity.kt
> +    lateinit var binding : ActivityMainBinding
네 수정하였습니다~
[MainActivity](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/195/commits/a2cd734fa7391be450534ce76304a8c57702209e)

2019-09-02 16:59 UTC, ganghee commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/adapter/UpbitHolder.kt
> +        rvBinding.apply { item = ticker }
넵 수정하였습니다.
[UpbitHolder](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/195/commits/5cadb0a166cc625bf9f40cdacb7d8564d2fdf2ca)

2019-09-02 17:58 UTC, ganghee commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/adapter/UpbitHolder.kt
> +    private var rvBinding: RvItemListBinding = binding
네 수정하였습니다.
[UpbitHolder](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/195/commits/480142adaca19322c45963a8e66819b930ca0bdf)

2019-09-03 00:01 UTC, wswon submitted a review, later dismissed
approve 하였습니다!

2019-09-03 02:18 UTC, BeokBeok requested changes
안녕하세요. 스터디 2기 강현석이라고 합니다.
부족하지만 잘 부탁드립니다. ^~^

2019-09-03 02:18 UTC, BeokBeok commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/ui/UpbitFragment.kt
> +        binding = DataBindingUtil.inflate(inflater,R.layout.fragment_upbit,container,false)
함수 파라미터가 많은 경우, 해당 convention 을 따르시는 것을 권장합니다.
https://kotlinlang.org/docs/reference/coding-conventions.html#method-call-formatting

2019-09-03 02:18 UTC, BeokBeok commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/adapter/UpbitHolder.kt
> +class UpbitHolder(private val binding: RvItemListBinding) : RecyclerView.ViewHolder(binding.root) {
클래스 관련 convention을 따르는 것을 권장합니다.
https://kotlinlang.org/docs/reference/coding-conventions.html#class-header-formatting

2019-09-03 02:18 UTC, BeokBeok commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/ui/UpbitFragment.kt
> +        binding.rvTickers.apply {
apply 보다 with나 run이 적합해보입니다.

2019-09-03 14:07 UTC, ganghee commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/adapter/UpbitHolder.kt
> +    private var rvBinding: RvItemListBinding = binding
네 수정하였습니다.
[UpbitHolder](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/195/commits/480142adaca19322c45963a8e66819b930ca0bdf)

2019-09-04 06:24 UTC, ganghee commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/ui/UpbitFragment.kt
> +        binding = DataBindingUtil.inflate(inflater,R.layout.fragment_upbit,container,false)
넵 수정하였습니다.
[UpbitFragment](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/195/files/480142adaca19322c45963a8e66819b930ca0bdf#diff-bab054cc8e9c5f25e4d48bbf47abd43d)

2019-09-04 06:27 UTC, ganghee commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/ui/UpbitFragment.kt
> +        binding.rvTickers.apply {
apply와 with, run 의 설명을 들을 수 있을까요?
어떨 때 객체 접근 키워드를 써야하는지 모르겠습니다
[UpbitFragment](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/195/commits/3f39f76a25cdadb7c7358d7c08a4cce099c3efc2)

2019-09-04 06:29 UTC, ganghee commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/adapter/UpbitHolder.kt
> +class UpbitHolder(private val binding: RvItemListBinding) : RecyclerView.ViewHolder(binding.root) {
수정하였습니다.
[UpbitHolder](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/195/commits/368adf0d1228d7476ab60394d047867d1be367ef)

2019-09-04 07:56 UTC, BeokBeok commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/adapter/UpbitHolder.kt
> +class UpbitHolder(private val binding: RvItemListBinding) : RecyclerView.ViewHolder(binding.root) {
다음과 같이 사용하는 것이 좋을 것 같습니다.
```suggestion
class UpbitHolder(
    private val binding: RvItemListBinding
) : RecyclerView.ViewHolder(binding.root) {
```

2019-09-04 07:56 UTC, BeokBeok commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/ui/UpbitFragment.kt
> +        binding.rvTickers.apply {
![image](https://user-images.githubusercontent.com/48344355/64235121-a7ada400-cf32-11e9-917b-9fb8a1ecb9b6.png)

상기 표를 보시면, apply 와 also는 수신객체를 반환합니다.
예를 들면, 아래와 같이 사용합니다.
```
val test = Test().apply {
    a = 1
    b = "2"
}
```
그리고 저는 with는 해당 객체가 nonnull 이면서 간단하게 세팅할 때 사용하고
run은 세팅해야하는 것들이 많을 경우에 사용하고 있습니다.

하지만, run은 with와 다르게 nullable 인 객체도 null 이 아닐때만 세팅할 수 있어서
개인적으로 run은 let과 with가 합쳐진 것으로 느껴져서 
최근에는 with 대신 run을 사용하고 있습니다.

2019-09-04 09:51 UTC, ganghee commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/ui/UpbitFragment.kt
> +        binding.rvTickers.apply {
네 설명 정말 감사합니다.
각각의 키워드를 어느 때 사용하는지 알겠습니다. 
[UpbitFragment](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/195/commits/7cc0e4bbc65388242ed60d0a03bfe0c252c6ff44)

2019-09-04 14:39 UTC, ganghee commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/adapter/UpbitHolder.kt
> +class UpbitHolder(private val binding: RvItemListBinding) : RecyclerView.ViewHolder(binding.root) {
class에 관한 convention을 적용하여 바꿔보았습니다.
[UpbitHolder](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/195/commits/e8d145432491cdaae3d20f5a17f222d15d928eed)

2019-09-05 00:57 UTC, BeokBeok approved these changes
LGTM:ok_hand:

2019-09-08 04:46 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-09-08 04:46 UTC, merged