HW-5 DataBinding 적용하기
sjjeong/GoogryAndroidArchitecutreStudy pull request #196
Opened 2019-08-28 14:30 UTC by wswon

data binding 적용해보았습니다.  
activity, fragment, viewholder item 에 적용했습니다.
감사합니다.

2019-09-02 15:35 UTC, ganghee commented
코드 받아 실행 바인드한 부분 봤습니다. 특별히 리뷰할 게 없어 보입니다. 
멘토님의 리뷰 받으시면 좋겠네요~~

2019-09-03 01:18 UTC, BeokBeok requested changes
안녕하세요. 스터디 2기 강현석이라고 합니다.
부족하지만 잘 부탁드립니다. ^~^

2019-09-03 01:18 UTC, BeokBeok commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/view/coin/adapter/CoinListAdapter.kt
> +    override fun onCreateViewHolder(parent: ViewGroup, viewType: Int): CoinViewHolder = CoinViewHolder(parent)
함수에 = 을 사용한 경우, 해당 convention 을 따르는 것이 좋을 것 같습니다.
https://kotlinlang.org/docs/reference/coding-conventions.html#expression-body-formatting

2019-09-03 01:18 UTC, BeokBeok commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/view/coin/adapter/CoinTabPagerAdapter.kt
> +    override fun getItem(position: Int): Fragment = CoinListFragment.newInstance(
Chaining 관련 convention을 따라주세요.
https://kotlinlang.org/docs/reference/coding-conventions.html#chained-call-wrapping

2019-09-03 01:18 UTC, BeokBeok commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/view/coin/adapter/holder/CoinViewHolder.kt
> +//            coinNameTv.text = ticker.coinName
불필요한 주석은 제거해주세요.

2019-09-03 01:18 UTC, BeokBeok commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/view/coin/adapter/holder/CoinViewHolder.kt
> +            compareYesterdayTv.setTextColor(ContextCompat.getColor(itemView.context, ticker.compareYesterdayTextColor))
함수에 파라미터가 많은 경우, 개행해주세요.
https://kotlinlang.org/docs/reference/coding-conventions.html#method-call-formatting

2019-09-03 01:18 UTC, BeokBeok commented on wswon/AndroidArchitectureStudy/app/src/main/res/layout/activity_main.xml
> +    <data>
사용하지 않는다면, 제거해주세요.

2019-09-03 01:18 UTC, BeokBeok commented on wswon/AndroidArchitectureStudy/app/src/main/res/layout/activity_main.xml
> +            app:layout_constraintRight_toRightOf="parent"
left, right 대신 start, end를 권장합니다.

2019-09-03 01:18 UTC, BeokBeok commented on wswon/AndroidArchitectureStudy/app/src/main/res/layout/activity_main.xml
> +                android:id="@+id/coin_name_tv"
tv가 앞에 오는 것이 낫지 않을까요?

2019-09-03 01:18 UTC, BeokBeok commented on wswon/AndroidArchitectureStudy/app/src/main/res/layout/fragment_coinlist.xml
> +            android:layout_width="match_parent"
ConstraintLayout 자식 뷰는 match_parent 대신 0dp로 해주세요

2019-09-03 11:54 UTC, wswon commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/view/coin/adapter/CoinListAdapter.kt
> +    override fun onCreateViewHolder(parent: ViewGroup, viewType: Int): CoinViewHolder = CoinViewHolder(parent)
bc0944e
반영했습니다.

2019-09-03 11:54 UTC, wswon commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/view/coin/adapter/CoinTabPagerAdapter.kt
> +    override fun getItem(position: Int): Fragment = CoinListFragment.newInstance(
1b75ea8
반영했습니다.

2019-09-03 11:54 UTC, wswon commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/view/coin/adapter/holder/CoinViewHolder.kt
> +//            coinNameTv.text = ticker.coinName
1a2dafa0
함수 개행과 함께 반영했습니다.

2019-09-03 11:55 UTC, wswon commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/view/coin/adapter/holder/CoinViewHolder.kt
> +            compareYesterdayTv.setTextColor(ContextCompat.getColor(itemView.context, ticker.compareYesterdayTextColor))
1a2dafa0
주석 제거와 함께 반영했습니다.

2019-09-03 11:56 UTC, wswon commented on wswon/AndroidArchitectureStudy/app/src/main/res/layout/activity_main.xml
> +    <data>
4cc0083
사용하지 않는 태그 제거했습니다.

2019-09-03 11:56 UTC, wswon commented on wswon/AndroidArchitectureStudy/app/src/main/res/layout/activity_main.xml
> +            app:layout_constraintRight_toRightOf="parent"
b4e61e1
반영했습니다.

2019-09-03 11:57 UTC, wswon commented on wswon/AndroidArchitectureStudy/app/src/main/res/layout/activity_main.xml
> +                android:id="@+id/coin_name_tv"
9e310c9
전부 타입이 앞으로 오도록 변경했습니다.
보통 tv_coin_name 이렇게 많이 선언하는지 궁금합니다!

2019-09-03 11:58 UTC, wswon commented on wswon/AndroidArchitectureStudy/app/src/main/res/layout/fragment_coinlist.xml
> +            android:layout_width="match_parent"
2942129
ConstraintLayout의 자식뷰에 match_parent 대신 0dp로 변경했습니다.

2019-09-03 12:01 UTC, wswon reviewed
안녕하세요 스터디 3기 원우석입니다!

부족한 점이 많은 코드를
시간내서 리뷰해주셔서 정말 감사합니다. 👍

2019-09-03 12:16 UTC, BeokBeok commented on wswon/AndroidArchitectureStudy/app/src/main/res/layout/activity_main.xml
> +                android:id="@+id/coin_name_tv"
개발자마다 다르긴 합니다.
가령 엑티비티를 생성하게 되면 activity_main.xml 이런식으로 생성되는 것을 보아
앞에는 주로 어떤 타입인지 알 수 있고 그 다음에 세부사항을 적는 것이 낫다고 생각합니다.

2019-09-03 12:16 UTC, BeokBeok approved these changes
LGTM:ok_hand:

2019-09-03 14:09 UTC, ganghee approved these changes

2019-09-04 12:38 UTC, wswon commented on wswon/AndroidArchitectureStudy/app/src/main/res/layout/activity_main.xml
> +                android:id="@+id/coin_name_tv"
답변에 감사드립니다!!

2019-09-04 14:20 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-09-04 14:22 UTC, merged