HW-3 코인헬퍼 : MVP 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #199
Opened 2019-09-01 09:00 UTC by seonoh

CoinMainContract는 MainActivity에서의 view,presenter에 대한 인터페이스,
CoinFragmentContract는 CoinFragment에서의 view,presenter를 선언한 인터페이스입니다.

MainActivity에서 CoinMainPresenter를 통해 받아온 마켓이름데이터를 토대로 페이저어댑터를 생성하고, CoinFragment를 생성하는 과정이 담겨있습니다.

CoinFragment에서는 CoinFragmentPresenter에서 통신 결과를 가공한 데이터를 받아와서 recyclerview에 뿌려줍니다.

어댑터부분 코드를 어떻게 해야할지 의문입니다. 어댑터 부분도 따로 프레젠터를 만들어줘야하는건가요?

2019-09-01 13:48 UTC, jskim5923 reviewed
선오님 수고하셨습니다.

말씀하신 adapter에 대한 제 개인적인 의견은 이렇습니다.

`adapter` 에서는 view를 만들어 주고, binding만 하도록 하고,

`presenter`에서 데이터를 받아온 후 `adapter`에서 binding만 하면 되도록 데이터를 가공해서 넘겨주면 되기 때문에, 굳이 `adapter`에도 `presenter`는 필요없다고 생각합니다.

2019-09-01 13:48 UTC, jskim5923 commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinFragment.kt
> +    override var mAdapter: CoinAdapter = CoinAdapter()
`lateinit`키워드를 이용하여 사용하던 지연 초기화에서, 변수 생성시 초기화 하도록 변경 한 이유가 있나요?
`mAdapter` 변수를 CoinFragmentContract.View 인터페이스에서 가지고 있을 필요가 없을 것 같습니다.

2019-09-01 13:48 UTC, jskim5923 commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinFragment.kt
> +    override var presenter: CoinFragmentContract.Presenter = CoinFragmentPresenter(this)
`presenter` 변수를 CoinFragmentContract.Presenter 인터페이스에서 가지고 있을 필요가 없이,
CoinFragment에서 객체를 생성 후  그 객체를 이용해서 CoinFragmentPresenter의 함수를 사용하면 될 것 같습니다.

2019-09-01 13:48 UTC, jskim5923 commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinFragment.kt
> +            presenter.loadData(it, activity!!)
presenter에는 Android Framework에 종속적인 부분이 없는 것이 좋습니다.

2019-09-01 13:48 UTC, jskim5923 commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinFragmentPresenter.kt
> +    init {
CoinFragmentContract.Presenter 인터페이스에서는 Presenter 변수를 가지고 있을 필요가 없습니다.

2019-09-01 13:48 UTC, jskim5923 commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinFragmentPresenter.kt
> +        coinRepository.sendCurrentPriceInfo(marketName)
RxJava Disposable 객체를 clear 해주세요

2019-09-01 13:48 UTC, jskim5923 commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinFragmentPresenter.kt
> +                translateData(it,context)
presenter에는 Android Framework에 종속적인 부분이 없는 것이 좋습니다.

2019-09-01 13:48 UTC, jskim5923 commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinFragmentPresenter.kt
> +    override fun translateData(result: List<CurrentPriceInfoModel>,context : Context) {
presenter에는 Android Framework에 종속적인 부분이 없는 것이 좋습니다.

2019-09-01 13:48 UTC, jskim5923 commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinMainPresenter.kt
> +        view.presenter = this
CoinMainContract.Presenter 인터페이스에서는 Presenter 변수를 가지고 있을 필요가 없습니다.

2019-09-01 13:48 UTC, jskim5923 commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinMainPresenter.kt
> +        coinRepository.sendMarket().subscribeOn(Schedulers.io())
RxJava의 disposable 객체를 클리어 해주세요.

2019-09-01 13:48 UTC, jskim5923 commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/MainActivity.kt
> +    override var presenter: CoinMainPresenter = CoinMainPresenter(
CoinMainContract.View interface에 presenter 변수를 갖고 있는 것이 아닌 MainActivity 내에서 presenter를 생성하는 게 좋을것 같습니다.

2019-09-01 13:48 UTC, jskim5923 commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinFragment.kt
> +    override fun initView() {
이 부분은 조금 헷갈리긴 하는데,  presenter에서 뷰의 갱신을 요청하는 것이 아니라, UI에서 자체적으로 라이프 사이클에 맞게 수행하는 동작은 굳이 CoinFragmentContract.View interface에 없어도 될것 같다고 생각합니다.

2019-09-01 13:48 UTC, jskim5923 commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/MainActivity.kt
> +    override fun initView() {
이 부분은 조금 헷갈리긴 하는데,  presenter에서 뷰의 갱신을 요청하는 것이 아니라, UI에서 자체적으로 라이프 사이클에 맞게 수행하는 동작은 굳이 CoinMainContract.View interface에 없어도 될것 같다고 생각합니다.

2019-09-01 13:48 UTC, jskim5923 commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/MainActivity.kt
> +        toast = Toast.makeText(this, "뒤로가기를 한번 더 누르시면 앱이 종료됩니다.", Toast.LENGTH_SHORT)
하드코딩 보다는 string resource를 이용하는 것이 좋습니다.

2019-09-01 13:48 UTC, jskim5923 commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/contract/CoinFragmentContract.kt
> +        var mAdapter : CoinAdapter
mAdapter, presenter의 변수는 필요없을 것 같습니다.
initView()와 같은 fragment내에서만 사용하는 필요없을 것 같습니다.
recyclerView를 갱신 하는 함수를 만들어놓고, 이 함수를 presenter에서 view.xxx()로 요청하여 처리하도록 하는 게 좋습니다.

2019-09-01 13:48 UTC, jskim5923 commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinFragmentPresenter.kt
> +        view.mAdapter.addCoinData(data)
직접적으로 view의 adapter 변수를 통해 view를 업데이트 하는 것이 아닌,
Contract.View interface에 view를 업데이트하는 함수를 만들어놓고 view.xxx() 함수를 호출하여 Contract.View를 구현하는 곳에서 처리하도록 하는 게 좋습니다.

2019-09-01 13:48 UTC, jskim5923 commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/contract/CoinFragmentContract.kt
> +        fun translateData(result: List<CurrentPriceInfoModel>,context : Context)
presenter에 Android framework와 종속적인 context를 넘기는 것은 지양하는 것이 좋습니다.

2019-09-01 13:48 UTC, jskim5923 commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/contract/CoinMainContract.kt
> +        var presenter: CoinMainPresenter
presenter 변수는 interface에 선언하는 것보다 presenter를 사용하는 곳에서 생성하는 것이 좋습니다.
initView 같은 view자체적으로 사용하는 함수는 굳이 필요없을 것 같습니다.

2019-09-02 00:33 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinFragment.kt
> +    override var mAdapter: CoinAdapter = CoinAdapter()
제가 생각했을때는 해당 view에서 갖고있는 view관련 변수들을 모두 Contract.View에 넣어서 관리하려고했는데 종선님 말씀을 들어보니 굳이 그럴필요가없을것 같네요! 감사합니다.

2019-09-02 00:37 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinFragment.kt
> +    override var presenter: CoinFragmentContract.Presenter = CoinFragmentPresenter(this)
이 부분은 지난 스터디에서 봤던 코드를 보면서 진행했는데 ... 하면서 좀 이상하다는 생각도 했어요.
저도 기존에는 그냥 Presenter() 생성했었는데...!
우선 익숙한 방식(종선님이 말씀하신 방식)으로 수정했습니다.

ddf1875

2019-09-02 01:44 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinFragment.kt
> +            presenter.loadData(it, activity!!)
네 수정했습니다. 감사합니다 ! 
2f54318

2019-09-02 01:44 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinFragmentPresenter.kt
> +    init {
ddf1875

2019-09-02 01:52 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinFragmentPresenter.kt
> +        coinRepository.sendCurrentPriceInfo(marketName)
네 감사합니다! 이렇게 사용하는게 맞는건지...궁금합니다.

5f987db

2019-09-02 01:55 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/MainActivity.kt
> +        toast = Toast.makeText(this, "뒤로가기를 한번 더 누르시면 앱이 종료됩니다.", Toast.LENGTH_SHORT)
감사합니다 ! 
3bf86aa

2019-09-02 01:58 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/contract/CoinFragmentContract.kt
> +        var mAdapter : CoinAdapter
네 수정했습니다.
그런데 initView함수는 fragment에서만 사용하는데, 해당 initView를 Contract.View에 명시해준다면 해당 View를 이해하는데 더 도움이 되지 않을까요?
ed10b0b

2019-09-02 01:59 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinFragmentPresenter.kt
> +        view.mAdapter.addCoinData(data)
ed10b0bd417307a066af660b6d5308a8153970b0

2019-09-02 02:00 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/contract/CoinFragmentContract.kt
> +        fun translateData(result: List<CurrentPriceInfoModel>,context : Context)
네 수정했습니다 ! 2f543180d18ed8cfe88bd54fe80936dffff5b8ba

2019-09-02 02:03 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/contract/CoinMainContract.kt
> +        var presenter: CoinMainPresenter
네 수정했습니다 ! 
( initView 부분은 유지해두었습니다. )
9f4abab

2019-09-02 13:11 UTC, jskim5923 commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinFragment.kt
> +    override var presenter: CoinFragmentContract.Presenter = CoinFragmentPresenter(this)
아 그러신거였으면.. 제가 코멘트를 잘못 날린걸 수도있겠네요.. 추후에 다시 한번 확인해보겠습니다.!

2019-09-02 13:14 UTC, jskim5923 commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/contract/CoinFragmentContract.kt
> +        var mAdapter : CoinAdapter
저는 View와 Presenter가 서로 관련된 부분만 Contract.View/Presenter interface를 이용해서 사용하는 건줄 알았는데.. 이 부분은 다른분의 의견도 같이 들어보는게 좋을 것 같습니다.

2019-09-02 13:19 UTC, jskim5923 reviewed
수고하셨습니다. 코멘트 반영하시면서 놓치셨던 부분 코멘트 드렸습니다.

2019-09-02 13:19 UTC, jskim5923 commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinFragment.kt
> +    lateinit var mAdapter: CoinAdapter
`private`  접근 지정자를 추가해주는게 좋을 것 같습니다.

2019-09-02 13:19 UTC, jskim5923 commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinFragment.kt
> +        presenter.disposableClear()
저도 이 부분은 2기 강현석님께서 함수는 동사를 먼저 사용하는 것이 좋다고 코멘트를 받았습니다.

2019-09-02 13:19 UTC, jskim5923 commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinMainPresenter.kt
> +        compositeDisposable.clear()
저도 이 부분은 2기 강현석님께서 함수는 동사를 먼저 사용하는 것이 좋다고 코멘트를 받았습니다.

2019-09-03 00:30 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinFragmentPresenter.kt
> +                translateData(it,context)
2f54318

2019-09-03 00:30 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinFragmentPresenter.kt
> +    override fun translateData(result: List<CurrentPriceInfoModel>,context : Context) {
2f54318

2019-09-03 00:32 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinMainPresenter.kt
> +        view.presenter = this
ddf1875

2019-09-03 00:33 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinFragment.kt
> +    lateinit var mAdapter: CoinAdapter
4921484

2019-09-03 00:34 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinMainPresenter.kt
> +        compositeDisposable.clear()
네 감사합니다 ! 
7c9ea49

2019-09-03 00:34 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinFragment.kt
> +        presenter.disposableClear()
7c9ea49

2019-09-03 00:34 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/contract/CoinFragmentContract.kt
> +        var mAdapter : CoinAdapter
네 감사합니다 !

2019-09-03 00:35 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinMainPresenter.kt
> +        coinRepository.sendMarket().subscribeOn(Schedulers.io())
7c9ea49

2019-09-03 00:35 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/MainActivity.kt
> +    override var presenter: CoinMainPresenter = CoinMainPresenter(
ddf1875

2019-09-04 12:02 UTC, jskim5923 submitted a review, later dismissed
LGTM

2019-09-04 13:41 UTC, BeokBeok requested changes
안녕하세요. 스터디 2기 강현석이라고 합니다.
부족하지만 잘 부탁드립니다. ^~^

2019-09-04 13:41 UTC, BeokBeok commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinFragment.kt
> +    private val presenter : CoinFragmentContract.Presenter by lazy { CoinFragmentPresenter(this) }
타입은 명시하지 않으셔도 될 것 같습니다.

2019-09-04 13:41 UTC, BeokBeok commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinFragment.kt
> +    override fun onDestroyView() {
오버라이딩된 함수는 가급적이면 상단에 위치해주세요

2019-09-04 13:41 UTC, BeokBeok commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinFragmentPresenter.kt
> +class CoinFragmentPresenter(
클래스명이 프래그먼트 + 프레젠터 가 있어서 뷰의 역할을 하는 것인지 프레젠터의 역할을 하는 것인지 의미가 모호한 것 같습니다.

2019-09-04 13:41 UTC, BeokBeok commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinFragmentPresenter.kt
> +    private val compositeDisposable: CompositeDisposable = CompositeDisposable()
타입을 명시하지 않으셔도 될 것 같습니다.

2019-09-04 13:41 UTC, BeokBeok commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinFragmentPresenter.kt
> +        compositeDisposable.addAll(
addAll은 뭔가 여러 개의 Disposable 을 해줘야 할 것 같은데
실상 한 개의 Disposable 만 add 하는 것 같습니다.

해서, addAll보다는 add가 더 적합해 보입니다.

2019-09-04 13:41 UTC, BeokBeok commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinFragmentPresenter.kt
> +        var marketType = ""
가능한 한 immutable 타입의 변수를 사용하는 것이 좋습니다.
```suggestion
        val marketType = = if (result.isNotEmpty()) {
            result[0].market.substringBefore("-")
        } else {
            ""
        }
```

2019-09-04 13:41 UTC, BeokBeok commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinItemViewHolder.kt
> +            setTextColor(ContextCompat.getColor(itemView.context,data.signedChangeRate["color"].toString().toInt()))
함수 개행이 많은 경우, convention 을 따라주시는 것이 좋습니다.
https://kotlinlang.org/docs/reference/coding-conventions.html#method-call-formatting

2019-09-04 13:41 UTC, BeokBeok commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinMainPresenter.kt
> +            }.joinToString(",") {
joinToString 함수의 디폴트 파라미터는 콤마 이므로, 생략하셔도 됩니다.

2019-09-04 13:41 UTC, BeokBeok commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/contract/CoinFragmentContract.kt
> +        fun initRecyclerView(data: ArrayList<UseCoinModel>)
리스코프 치환 원칙에 따라 ArrayList를 List로 변경해주세요.

2019-09-04 13:41 UTC, BeokBeok commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/util/CalculateUtils.kt
> +        var mapValue = mutableMapOf<String, Any>()
타입을 val로 변경해주세요.

또한, Any 를 Number 로 변경하여 처리가 가능할 것 같습니다.

2019-09-04 13:41 UTC, BeokBeok commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/util/CalculateUtils.kt
>                  val fmtResId = when {
when 의 리턴 타입이 없습니다.

이와 같이 변경하여 처리하시는 것은 어떤가요?
```suggestion
                mapValue["format"] = when {
```

2019-09-04 13:41 UTC, BeokBeok commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/util/CalculateUtils.kt
> +    fun setTradeDiff(signedChangeRate: Double): Map<String, Any> {
함수 관련 convention 을 따르는 것을 권장합니다.
https://kotlinlang.org/docs/reference/coding-conventions.html#function-formatting

2019-09-04 13:41 UTC, BeokBeok commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/MainActivity.kt
> +    override fun initView() {
저도 종선님의 의견에 동의합니다.
initView 는 Contract 에 없어도 될 것 같습니다.

2019-09-05 00:41 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinFragment.kt
> +    private val presenter : CoinFragmentContract.Presenter by lazy { CoinFragmentPresenter(this) }
네 수정했습니다.64abd93d5711bbbb9b4bb03ed8dc775229d28ad7
그런데 타입 명시하면 가독성이 더 좋은 코드가 되지 않을까요?

2019-09-05 00:43 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinFragment.kt
> +    override fun onDestroyView() {
네 수정했습니다!
3d08de22b74fb82364630b14d72aa92df3e54552

2019-09-05 00:45 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinFragmentPresenter.kt
> +class CoinFragmentPresenter(
네 CoinPresenter로 수정했습니다. 
64199c5a658f06d2e7e41e1a7056a916338124c4

2019-09-05 00:46 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinFragmentPresenter.kt
> +    private val compositeDisposable: CompositeDisposable = CompositeDisposable()
네 수정했습니다.
9986f057dc12ee3c76693676bf42d16a5039321d

2019-09-05 00:47 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinFragmentPresenter.kt
> +        compositeDisposable.addAll(
네 수정했습니다.
18b9a4f6d570ba4b284c592eecb53e29d53cf8c1

2019-09-05 00:50 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinFragmentPresenter.kt
> +        var marketType = ""
네 수정했습니다 !
e4a9883e0d0338b6ad6019092c809f2fd6a4f71b

2019-09-05 00:52 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinItemViewHolder.kt
> +            setTextColor(ContextCompat.getColor(itemView.context,data.signedChangeRate["color"].toString().toInt()))
네 수정했습니다 !
7caf1989654de048035fbca9502d15f74c177f71

2019-09-05 00:54 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinMainPresenter.kt
> +            }.joinToString(",") {
네 수정했습니다!
521e60fbb5676508e591fb02587baef4497e167c

2019-09-05 00:55 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/contract/CoinFragmentContract.kt
> +        fun initRecyclerView(data: ArrayList<UseCoinModel>)
네 수정했습니다.
e44350420c11a0e3d84afe67a5727519ae72eda6

2019-09-05 00:57 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/util/CalculateUtils.kt
> +        var mapValue = mutableMapOf<String, Any>()
네 수정했습니다.
e44350420c11a0e3d84afe67a5727519ae72eda6
타입은 넘버값과,리소스아이디가 포함되어있어서 Any로 설정했습니다.

2019-09-05 01:22 UTC, BeokBeok commented
2개의 리뷰에 대하여 답변을 받지 못하였습니다.

2019-09-07 23:14 UTC, seonoh commented
2개의 답변달리지 않은 리뷰가 어디있나요? 찾아도 보이지 않습니다.

2019-09-08 00:22 UTC, BeokBeok commented
여기 있습니다!:sweat_smile:
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/199#discussion_r320763009
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/199#discussion_r320764227

2019-09-09 00:58 UTC, seonoh commented
![image](https://user-images.githubusercontent.com/21157092/64497342-4d249700-d2e8-11e9-8ddf-cd9de5c0ef42.png)

![image](https://user-images.githubusercontent.com/21157092/64497344-531a7800-d2e8-11e9-8e5e-8658434ed67e.png)

이거 리뷰 반영되어있습니다!!

2019-09-09 01:24 UTC, BeokBeok commented
첨부하신 이미지를 보니 상태가 Pending 으로 되어 있는데
submit change 버튼을 눌러 갱신하셨는지 확인 바랍니다.

2019-09-09 09:55 UTC, seonoh reviewed
확인했습니다! 이제 된 것 같네요!!

2019-09-09 09:55 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/util/CalculateUtils.kt
>                  val fmtResId = when {
감사합니다 Any -> Number로 변경 완료했습니다.

25a3b5d

2019-09-09 09:55 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/util/CalculateUtils.kt
> +    fun setTradeDiff(signedChangeRate: Double): Map<String, Any> {
네 수정했습니다 !
c3ed99b220c6c10de2fd5ab0debde07bc00af5e5

2019-09-09 09:55 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/MainActivity.kt
> +    override fun initView() {
네 수정했습니다. 
두분 모두 감사합니다!!
31f9a8955888dc82fa2a6f8a289ed92316e7aa44

2019-09-09 10:04 UTC, BeokBeok commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/util/CalculateUtils.kt
> +        var mapValue = mutableMapOf<String, Any>()
하기 리뷰

2019-09-09 10:05 UTC, BeokBeok commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinFragment.kt
> +    private val presenter : CoinFragmentContract.Presenter by lazy { CoinFragmentPresenter(this) }
코틀린 컴파일러는 문맥으로부터 변수 타입을 자동으로 추론해주기 때문에
코틀린의 특성을 살려 코딩하는 것이 좋다고 생각합니다.
하지만, 자동으로 추론하지 못하는 경우에만 타입을 명시해주어야 합니다.

2019-09-09 10:06 UTC, BeokBeok commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/util/CalculateUtils.kt
> +        var mapValue = mutableMapOf<String, Any>()
하기 리뷰를 수정하시게 된다면, Any 를 Number 로 변경이 가능해보입니다.

2019-09-10 01:01 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinFragment.kt
> +    private val presenter : CoinFragmentContract.Presenter by lazy { CoinFragmentPresenter(this) }
네 !! 감사합니다.

2019-09-10 01:17 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/util/CalculateUtils.kt
> +        var mapValue = mutableMapOf<String, Any>()
네 감사합니다. 번거롭게해서 죄송합니다..ㅎㅎ 
25a3b5d

2019-09-10 02:39 UTC, BeokBeok approved these changes
LGTM:ok_hand:

2019-09-21 03:32 UTC, sjjeong commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/contract/CoinFragmentContract.kt
> +        fun initRecyclerView(data: List<UseCoinModel>)
showCoinTickerList 정도가 좋을 것 같습니다.

2019-09-21 03:32 UTC, sjjeong commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/contract/CoinFragmentContract.kt
> +        fun translateData(result: List<CurrentPriceInfoModel>)
setData와 translateData는 Contract.Presenter에 정의하는 건 아닌 것 같습니다.
이 부분에서는 지우고 CoinPresenter에서 private함수로 사용하면 좋겠습니다.

2019-09-21 03:32 UTC, sjjeong commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/contract/CoinFragmentContract.kt
> +        fun clearDisposable()
Rx를 기본적으로 사용한다면 Base클래스를 만들어서 처리하면 좋을 것 같습니다.

2019-09-21 03:32 UTC, sjjeong commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinPresenter.kt
> +                    translateData(it)
변환하는 작업은 rx의 map함수를 사용하고 subscribe안에서는 결과를 어떻게 사용할지만 처리해주면 됩니다.

2019-09-21 03:32 UTC, sjjeong commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinMainPresenter.kt
> +    override fun classifyMarketData(marketData: List<Market>): ArrayList<String> {
사용되지 않는 함수라서 제거해주시면 될 것 같아요

2019-09-21 03:32 UTC, sjjeong commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinPresenter.kt
> +    override fun setData(data: ArrayList<UseCoinModel>) {
setData로 사용하는 것보다 setData를 호출하는 부분에 view.initRecyclerView(data)를 호출해주세요

2019-09-21 03:32 UTC, sjjeong commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/MainActivity.kt
> +    override fun showToast() {
기존처럼 onBackPressed에 넣어도 될 것 같아요

2019-09-21 03:32 UTC, sjjeong commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/model/UseCoinModel.kt
> +    val accTradePrice_24h: Map<String,Any>
_를 사용하지말고 카멜케이스를 사용해주세요

2019-09-22 00:58 UTC, merged