1주차 과제
sjjeong/GoogryAndroidArchitecutreStudy pull request #20
Opened 2019-05-01 12:40 UTC by GeoN5

과제 구현

2019-05-01 16:38 UTC, namjackson requested changes

2019-05-01 16:38 UTC, namjackson commented on GeoN5/MyArchitecutreStudy/app/src/main/java/com/example/myarchitecutrestudy/MainActivity.kt
> +                    setViewpager()
마켓정보 가져온 이후에 , setViewPager를 해주는 이유가 있나요?
setViewPager는 Layout Init할때 함께하고, 
마켓List 받아온 이후, CoinPagerAdapter에서 따로 setList 해주는 방법은 어떤가요?

2019-05-01 16:38 UTC, namjackson commented on GeoN5/MyArchitecutreStudy/app/src/main/java/com/example/myarchitecutrestudy/adapter/RecyclerViewAdapter.kt
> +            holder.dayBefote.text = "${tickerList[position].signed_change_rate.toString().
dayBefote -  dayBefore의 오타인거 같아요!  
그리고 signed_change_rate 비율 변수라서 *100을 해야할거같아요!

2019-05-01 16:38 UTC, namjackson commented on GeoN5/MyArchitecutreStudy/app/src/main/java/com/example/myarchitecutrestudy/network/services.kt
> +    @GET("ticker?")//id조회
ticker 뒤에 ? 는 없어도 될거같아요!

2019-05-01 16:38 UTC, namjackson commented on GeoN5/MyArchitecutreStudy/app/src/main/java/com/example/myarchitecutrestudy/model/MarketAll.kt
> +
변수명은 
카멜 표기법에 따르면 좋을거같아요! 
(ex) koreanName   , @SerializedName("korean_name")로 api 표기법을 맞춰주면 좋을거같아요 )

2019-05-01 16:38 UTC, namjackson commented on GeoN5/MyArchitecutreStudy/app/src/main/java/com/example/myarchitecutrestudy/fragment/CoinFragment.kt
> +                        setRecyclerView()
이것도 RecyclerView는 뷰 그려줄때 한번만 초기화하고 
생성된 어댑터를 통해서 list데이터만 변경하는식으로 하면 좋을거같아요!

2019-05-02 05:30 UTC, GeoN5 commented on GeoN5/MyArchitecutreStudy/app/src/main/java/com/example/myarchitecutrestudy/MainActivity.kt
> +                    setViewpager()
비동기라서 처음에 onCreate()에서 해주었더니 리스트를 받아오기 전에 먼저 setViewPager로 로직이 먼저 타버려서 어댑터로 리스트 파라미터를 보낼때 문제가 생기더라고요.
그래서 네트워크 작업이 이루어진 후에 호출을 해서 해결했습니다.
"마켓List 받아온 이후, CoinPagerAdapter에서 따로 setList 해주는 방법은 어떤가요?"
그래도 이 부분은 1번만 호출되긴하는데 로직을 어떻게 구현해야 할지 잘 감이 안오네요ㅠㅠ.

2019-05-02 05:30 UTC, GeoN5 commented on GeoN5/MyArchitecutreStudy/app/src/main/java/com/example/myarchitecutrestudy/adapter/RecyclerViewAdapter.kt
> +            holder.dayBefote.text = "${tickerList[position].signed_change_rate.toString().
오타지적 감사합니다 ㅎㅎ
아래 부분도 그렇게 적용해볼게요

2019-05-02 05:30 UTC, GeoN5 commented on GeoN5/MyArchitecutreStudy/app/src/main/java/com/example/myarchitecutrestudy/network/services.kt
> +    @GET("ticker?")//id조회
감사합니다

2019-05-02 05:30 UTC, GeoN5 commented on GeoN5/MyArchitecutreStudy/app/src/main/java/com/example/myarchitecutrestudy/model/MarketAll.kt
> +
넵 그렇게 적용할게요

2019-05-02 05:30 UTC, GeoN5 commented on GeoN5/MyArchitecutreStudy/app/src/main/java/com/example/myarchitecutrestudy/fragment/CoinFragment.kt
> +                        setRecyclerView()
어댑터내에서 메소드로 리스트를 받아서 하는 식으로 하면
처음에 setRecyclerView()는 언제 호출해야 할까요
57번 line loadData()밑에다가 작성하면 또 이게 먼저 호출되버려서 문제가 생겨버리는데ㅠㅠ

2019-05-02 11:36 UTC, namjackson commented on GeoN5/MyArchitecutreStudy/app/src/main/java/com/example/myarchitecutrestudy/fragment/CoinFragment.kt
> +                        setRecyclerView()
57번 line 에서 RecyclerAdapter에서 tickerList없이 초기화해준 후,
TickerList 받아온후에 RecyclerAdapter 내부의 메소드를 사용해서  tickerList의 값만 넣어주면 좋을거같아요!

2019-05-02 13:11 UTC, Hoyuo reviewed
전체적으로 formatter를 한번 돌려주세요

2019-05-02 13:11 UTC, Hoyuo commented on GeoN5/MyArchitecutreStudy/app/src/main/java/com/example/myarchitecutrestudy/MainActivity.kt
> +                    marketList = response.body()!!
!! 대신 다른 방법을 생각해 보세요

2019-05-02 13:11 UTC, Hoyuo commented on GeoN5/MyArchitecutreStudy/app/src/main/java/com/example/myarchitecutrestudy/MainActivity.kt
> +                viewPager.currentItem = tab!!.position
여기도 같습니다

2019-05-02 13:11 UTC, Hoyuo commented on GeoN5/MyArchitecutreStudy/app/src/main/java/com/example/myarchitecutrestudy/adapter/RecyclerViewAdapter.kt
> +class CoinViewHolder(itemView : View):RecyclerView.ViewHolder(itemView){
Holder 부분 다시 한번 생각해 보세요

2019-05-02 13:11 UTC, Hoyuo commented on GeoN5/MyArchitecutreStudy/app/src/main/java/com/example/myarchitecutrestudy/fragment/CoinFragment.kt
> +                    Log.d("qwer",coinList.toString())
qwer 의미 없는 것보다 TAG를 정해서 진행해보세요

2019-05-02 13:11 UTC, Hoyuo commented on GeoN5/MyArchitecutreStudy/app/src/main/java/com/example/myarchitecutrestudy/fragment/CoinFragment.kt
> +            Log.d("abcd",nameList.toString())
같습니다

2019-05-02 13:11 UTC, Hoyuo commented on GeoN5/MyArchitecutreStudy/app/src/main/java/com/example/myarchitecutrestudy/utils/RetrofitUtil.kt
> +        .build()!!
`!!` 다시 한번 생각해보세요

2019-05-04 05:32 UTC, namjackson commented on GeoN5/MyArchitecutreStudy/app/src/main/java/com/example/myarchitecutrestudy/adapter/RecyclerViewAdapter.kt
> +    }
list 변경후에, notifyDataSetChanged()를 통해 view를 갱신해야할것같아요!

2019-05-04 05:32 UTC, namjackson commented on GeoN5/MyArchitecutreStudy/app/src/main/java/com/example/myarchitecutrestudy/MainActivity.kt
> +                    setViewpager()
추후에,
adapter에서 setlList 이후에, 
각 Fragment에 init(Ticker의 가격을 호출해주는 함수)를 만들어서 호출해주면 좋을것 같아요
(loadData를 초기화이후가 아니라, fragment에 list가 호출되는 시점에 실행시켜주면 될거같아요)

2019-05-04 08:34 UTC, GeoN5 commented on GeoN5/MyArchitecutreStudy/app/src/main/java/com/example/myarchitecutrestudy/adapter/RecyclerViewAdapter.kt
> +    }
CoinFragment 76번째 line에서 다음과 같이 갱신해주었는데
```kotlin
recyclerAdapter.notifyDataSetChanged()
```
setList안에서도 해주어야 하나요?

2019-05-04 08:45 UTC, GeoN5 commented on GeoN5/MyArchitecutreStudy/app/src/main/java/com/example/myarchitecutrestudy/MainActivity.kt
> +                    marketList = response.body()!!
넵

2019-05-04 08:45 UTC, GeoN5 commented on GeoN5/MyArchitecutreStudy/app/src/main/java/com/example/myarchitecutrestudy/MainActivity.kt
> +                viewPager.currentItem = tab!!.position
넵

2019-05-04 08:46 UTC, GeoN5 commented on GeoN5/MyArchitecutreStudy/app/src/main/java/com/example/myarchitecutrestudy/adapter/RecyclerViewAdapter.kt
> +class CoinViewHolder(itemView : View):RecyclerView.ViewHolder(itemView){
구글링을 통해 한번 다른 방식으로 고쳐보았습니다.

2019-05-04 08:46 UTC, GeoN5 commented on GeoN5/MyArchitecutreStudy/app/src/main/java/com/example/myarchitecutrestudy/fragment/CoinFragment.kt
> +                    Log.d("qwer",coinList.toString())
넵

2019-05-04 08:47 UTC, GeoN5 commented on GeoN5/MyArchitecutreStudy/app/src/main/java/com/example/myarchitecutrestudy/fragment/CoinFragment.kt
> +            Log.d("abcd",nameList.toString())
넵

2019-05-04 08:47 UTC, GeoN5 commented on GeoN5/MyArchitecutreStudy/app/src/main/java/com/example/myarchitecutrestudy/utils/RetrofitUtil.kt
> +        .build()!!
넵

2019-05-04 09:42 UTC, namjackson commented on GeoN5/MyArchitecutreStudy/app/src/main/java/com/example/myarchitecutrestudy/adapter/RecyclerViewAdapter.kt
> +    }
아하 CoinFragment에 실행했군요! 
그부분에서 실행하는것보다 
list데이터 변경에 따른 notifyDataSetChanged가 실행는거니 
CoinFragment에서보다 setlist에 해당 코드가 있는게 더 좋은거같아요!

2019-05-04 09:58 UTC, namjackson submitted a review, later dismissed

2019-05-04 12:39 UTC, Hoyuo requested changes
불필요한 주석 부분이 너무 많습니다.

수정이 하였으면 위에 코맨트에서 `Resolve conversation` 을 클릭해 주세요
넵이라고 안 적으셔도 의미가 통합니다

2019-05-05 05:07 UTC, merged