HW-3 MVP 패턴 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #200
Opened 2019-09-01 13:18 UTC by jskim5923

- 기존 ui패키지(MainActivity.kt, CoinFragment.kt) 를 각각 main, coin 패키지로 세분화 시켰습니다.

- main, coin 각각의 패키지에 Presenter/VIew interface를 가지고 있는 Contract interface인 MainContract, CoinContract를 생성하였습니다.

- Main/Coin Presenter Contract.Presenter interface를 구현하여, 모델에서 데이터를 받아와  뷰에 맞는 데이터를 가공하는 비즈니스 로직을 담당한 후 View에게 업데이트를 요청하도록 하였습니다.

- MainActivity / CoinFragment에서는 Presenter의 객체를 들고 있어, 이벤트에 대한 비즈니스 로직을 presenter에게 요청하며, Contract.View를 구현하여 Presenter에서 요청 받은 View를 업데이트 하도록 하였습니다.

2019-09-02 02:11 UTC, seonoh commented
종선님 수고하셨습니다 !!

2019-09-02 02:13 UTC, seonoh submitted a review, later dismissed
수고하셨습니다 종선님 !
제가 거의 종선님 리뷰에 맞추다보니 제가 수정해드릴 사항이 보이질 않네요 ㅜㅜ

2019-09-02 07:48 UTC, BeokBeok requested changes
안녕하세요. 스터디 2기 강현석입니다.
부족하지만 잘 부탁드립니다 ^~^

2019-09-02 07:48 UTC, BeokBeok commented on jskim5923/ArchitectureStudy/app/src/main/java/com/jskim5923/architecturestudy/coin/CoinFragment.kt
> +        presenter.disposableClear()
dispose 처리를 하지 않고 clear 처리를 한 이유가 있나요?

2019-09-02 07:48 UTC, BeokBeok commented on jskim5923/ArchitectureStudy/app/src/main/java/com/jskim5923/architecturestudy/main/MainContract.kt
> +        fun disposableClear()
함수명은 동사가 먼저 오는 것이 좋습니다.
```suggestion
        fun clearDisposable()
```

2019-09-02 07:48 UTC, BeokBeok commented on jskim5923/ArchitectureStudy/app/src/main/java/com/jskim5923/architecturestudy/coin/CoinPresenter.kt
> +                ApiManager.coinApi.getTicker(
Repository에 있는 getTicker를 호출하지 않고
CoinApi 에 있는 getTicker를 호출한 이유가 있나요?

2019-09-02 07:48 UTC, BeokBeok commented on jskim5923/ArchitectureStudy/app/src/main/java/com/jskim5923/architecturestudy/coin/CoinPresenter.kt
> +                    marketList.asSequence().filter {
chained call 관련 convention 을 참고해주세요.
https://kotlinlang.org/docs/reference/coding-conventions.html#chained-call-wrapping

2019-09-02 12:47 UTC, jskim5923 commented on jskim5923/ArchitectureStudy/app/src/main/java/com/jskim5923/architecturestudy/coin/CoinFragment.kt
> +        presenter.disposableClear()
presenter에서 사용하는 compositeDisposable을 lifecycle에 맞게 clear하기 위함이었습니다.
함수명을 좀 더 명확하게 변경하였습니다.
[9713e85]

2019-09-02 12:47 UTC, jskim5923 commented on jskim5923/ArchitectureStudy/app/src/main/java/com/jskim5923/architecturestudy/main/MainContract.kt
> +        fun disposableClear()
[9713e85] 적용하였습니다.

2019-09-02 12:49 UTC, jskim5923 commented on jskim5923/ArchitectureStudy/app/src/main/java/com/jskim5923/architecturestudy/coin/CoinPresenter.kt
> +                ApiManager.coinApi.getTicker(
감사합니다. 
[8df9560] 수정하였습니다.

2019-09-02 12:54 UTC, jskim5923 commented on jskim5923/ArchitectureStudy/app/src/main/java/com/jskim5923/architecturestudy/coin/CoinPresenter.kt
> +                    marketList.asSequence().filter {
감사합니다
[3dc2f3e] 적용하였습니다.

2019-09-03 00:53 UTC, BeokBeok approved these changes
LGTM:ok_hand:

2019-09-21 04:52 UTC, merged