HW-3 MVP 패턴 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #201
Opened 2019-09-02 04:09 UTC by toctocbin

- Contract를 이용해 View와 Presenter에서 사용할 Interface를 정의
- 기존 View에 있었던 비지니스 로직을 Presenter에서 처리

2019-09-03 05:43 UTC, becooni reviewed
Ticker는 Market 쪽에서 코멘트 남긴것과 동일합니다.

2019-09-03 05:43 UTC, junghum21 commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/ui/market/MarketActivity.kt
> +class MarketActivity : AppCompatActivity(), MarketContract.View {
슈퍼클래스와 인터페이스는 개행해서 작성해주는것에 좋겠네요

https://kotlinlang.org/docs/reference/coding-conventions.html#class-header-formatting

```suggestion
class MarketActivity : 
    AppCompatActivity(), 
    MarketContract.View {
```

2019-09-03 05:43 UTC, junghum21 commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/ui/market/MarketActivity.kt
> +    private var viewPagerAdapter: ViewPagerAdapter? = null
viewPagerAdapter는 onCreate 시점에 생성될 것인데 nullable일 필요 있을까요?

2019-09-03 05:43 UTC, junghum21 commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/ui/market/MarketActivity.kt
> +        presenter.disposablesClear()
MVP 패턴에서 View는 어떤 상황(event)에 어떤 일을 해야하는지 알 필요가 없습니다. 

View는 Presenter에게 상황(event)만 전달 하고 Presenter는 전달받은 상황에 맞는 적절한 일을 하면 되는 것 이라고 생각합니다.

presenter.getMarketAll()과 presenter.disposablesClear()는 View에서 상관할 일이 아니라는거죠.

저는 View의 onCreate(), onDestroy()에서 presenter의 onCreate(), onDestroy()를 호출 합니다.

그러면 Presenter는 발생한 상황에 맞는 적절한 일(api call, disposable clear 등)을 합니다.

제가 틀린게 있다면 지적해주세요 :)

2019-09-03 05:43 UTC, junghum21 commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/ui/market/MarketPresenter.kt
> +    companion object {
Presenter를 싱글톤으로 구현한 이유가 궁금합니다.

2019-09-03 05:43 UTC, junghum21 commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/ui/market/MarketPresenter.kt
> +            .apply { disposables.add(this) }
```suggestion
.addTo(disposables)
```

도 가능합니다.

2019-09-03 05:44 UTC, junghum21 commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/ui/ticker/TickerPresenter.kt
> +        val changeRate = """${String.format("%.2f", ticker.signedChangeRate * 100)}%"""
큰따옴표가 왜 3개씩 인가요?

2019-09-04 00:30 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/ui/market/MarketActivity.kt
> +        presenter.disposablesClear()
getMarketAll 이 onCreate에 호출되고 refresh 버튼에도 호출된다면 어떤식으로 하시나요 ?!?

2019-09-04 00:32 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/ui/market/MarketPresenter.kt
> +    companion object {
안에 있는 로직들이 재사용 되어도 문제가 없어 보였어요. 싱글톤으로 사용하면 안되는 이유가 있을까요 !!?

2019-09-04 00:42 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/ui/ticker/TickerPresenter.kt
> +        val changeRate = """${String.format("%.2f", ticker.signedChangeRate * 100)}%"""
c8e4453

제거했습니다!

2019-09-04 00:43 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/ui/market/MarketActivity.kt
> +    private var viewPagerAdapter: ViewPagerAdapter? = null
552447b 
b841c4b
변경했습니다

2019-09-04 00:44 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/ui/market/MarketActivity.kt
> +class MarketActivity : AppCompatActivity(), MarketContract.View {
ca8ddcf

변경했습니다.

2019-09-04 00:54 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/ui/market/MarketPresenter.kt
> +    companion object {
83f669a 
f2e0939

MarketActivity 에서는 하나의 인스턴스로 사용해도 상관없다고 생각했습니다 아닌가요 ?!

2019-09-04 01:11 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/ui/market/MarketPresenter.kt
> +            .apply { disposables.add(this) }
addTo가 추가 안됩니다 ㅠㅜ
52afc5d

다른 방식으로 변경해봤습니다.

2019-09-04 01:58 UTC, junghum21 commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/ui/market/MarketActivity.kt
> +        presenter.disposablesClear()
말씀하신 경우라면,
presenter.onCreate()
presenter.onRefreshClick()
가 호출된 경우 두 함수 모두 Presenter#refresh()를 호출합니다.

지난 스터디때 얘기했던 몸(View)은 현재시간에 따라 어떻게 행동해야 할지를 뇌(Presenter)로 부터 받는다는 것에서 생각한 것입니다.

2019-09-04 02:04 UTC, junghum21 commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/ui/market/MarketPresenter.kt
> +    companion object {
다른곳에서 그 객체를 재사용한다면 적절할 수 있겠지만, 

Presenter와 1:1로 맺어져 있는 View가 아닌 곳에서는 사용하지 않으니 이점을 모르겠습니다.

2019-09-04 02:06 UTC, junghum21 commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/ui/market/MarketPresenter.kt
> +            .apply { disposables.add(this) }
addTo()는 RxKotlin 라이브러리에 있는거네요 :)

2019-09-04 03:57 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/ui/market/MarketPresenter.kt
> +    companion object {
아하 넵 알겠습니다!

2019-09-04 04:08 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/ui/market/MarketActivity.kt
> +        presenter.disposablesClear()
시간에 따라 어떻게 행동해야 할지라면 말씀하신대로 하는게 맞는거 같네요.
저희가 Google sample을 보면서 분석하였는데 Google에서는 행동을 기준으로 나눈거 같아요.
저도 몸이 필요한 행동을 뇌에 요청하는게 더 직관적이라고 생각합니다!

2019-09-04 07:03 UTC, junghum21 commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/ui/market/MarketActivity.kt
> +        presenter.disposablesClear()
아마 관점 또는 취향 차이일 것이란 생각도 듭니다. ㅎㅎ

이 부분을 갖고 얘기를 나눠보고 싶었어요.

다음 스터디 때 이 주제로 다른분들의 의견도 들어보고 싶네요.

2019-09-04 13:03 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/ui/market/MarketActivity.kt
> +        presenter.disposablesClear()
넵! 수고하셨습니다!

2019-09-04 13:51 UTC, BeokBeok requested changes
안녕하세요. 스터디 2기 강현석이라고 합니다.
부족하지만 잘 부탁드립니다. ^~^

2019-09-04 13:51 UTC, BeokBeok commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/ui/market/MarketPresenter.kt
> +class MarketPresenter(private val view: MarketContract.View) : MarketContract.Presenter {
class 관련 convention을 따르는 것을 권장합니다.
https://kotlinlang.org/docs/reference/coding-conventions.html#class-header-formatting

2019-09-04 13:51 UTC, BeokBeok commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/ui/ticker/TickerPresenter.kt
> +        val marketName: String = ticker.market.substringAfter("-")
초기화 값의 타입이 명확한 경우, changeRate 변수와 같이 타입을 생략하셔도 됩니다.
```suggestion
        val marketName = ticker.market.substringAfter("-")
```

2019-09-08 23:59 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/ui/ticker/TickerPresenter.kt
> +        val marketName: String = ticker.market.substringAfter("-")
1e3e95f

제거하였습니다.

2019-09-08 23:59 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/ui/market/MarketPresenter.kt
> +class MarketPresenter(private val view: MarketContract.View) : MarketContract.Presenter {
9e06bd6

적용하였습니다.

2019-09-09 01:25 UTC, BeokBeok approved these changes
LGTM:ok_hand:

2019-09-21 04:04 UTC, merged