HW-3 MVP 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #202
Opened 2019-09-03 05:17 UTC by junghum21

2019-09-04 01:16 UTC, haanbin reviewed
열심히 리뷰해보겠습니다!

2019-09-04 01:16 UTC, toctocbin commented on junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/ui/main/MainActivity.kt
> +            UpbitRepository.getInstance(UpbitRemoteDataSource(ApiUtil.getUpbitService())),
생성자에 넣어주는것과 그냥 Presenter에서 생성하는 방법 어떤 차이점이 있을까요 ?

2019-09-04 01:26 UTC, toctocbin commented on junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/ui/tickers/TickersPresenter.kt
> +    private val marketName: String
API 호출에 필요한 값은 생성자 주입하기보단 호출할때 넘겨주는게 더 좋다고 생각합니다 어떻게 생각하시나요 ??

2019-09-04 01:51 UTC, junghum21 commented on junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/ui/main/MainActivity.kt
> +            UpbitRepository.getInstance(UpbitRemoteDataSource(ApiUtil.getUpbitService())),
생성자에 주입해주면 Presenter는 UpbitRemoteDataSource, ApiUtil.getUpbitService를 알 필요 없이 UpbitRepository만 알면 된다는 차이점이 있겠네요.

2019-09-04 03:57 UTC, toctocbin commented on junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/ui/main/MainActivity.kt
> +            UpbitRepository.getInstance(UpbitRemoteDataSource(ApiUtil.getUpbitService())),
아하 그럼 View에서는 UpbitRepository없이 Presneter에서만 들고있어도 되지 않을까요?

2019-09-04 04:10 UTC, toctocbin commented
보고계신줄 모르고 리뷰를 지워버렸네요. 다시 보니 BasePresenter에서 onCreate를 implements하셔서 구현하였네요! 그래서 삭제했습니다 ㅠ

2019-09-04 06:08 UTC, junghum21 commented on junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/ui/main/MainActivity.kt
> +            UpbitRepository.getInstance(UpbitRemoteDataSource(ApiUtil.getUpbitService())),
'presenter와 repository 간의 결합도가 높아지기 때문이다.' 라고 답을 드리고 싶은데,

저는 DI에 깊은 이해가 없어서 어떻게 설명하기 어렵습니다. ㅠㅠ

DI 개념에 관한 설명이 있는 링크로 대체 하겠습니다.

> https://gmlwjd9405.github.io/2018/11/09/dependency-injection.html

2019-09-04 13:07 UTC, toctocbin commented on junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/ui/main/MainActivity.kt
> +            UpbitRepository.getInstance(UpbitRemoteDataSource(ApiUtil.getUpbitService())),
아하 넵 수고하셨습니다!

2019-09-04 14:02 UTC, BeokBeok requested changes
안녕하세요. 스터디 2기 강현석이라고 합니다.
부족하지만 잘 부탁드립니다. ^~^

2019-09-04 14:02 UTC, BeokBeok commented on junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/base/BaseActivity.kt
> +    @LayoutRes val layoutRes: Int
annotation 은 개행해서 작성하시는 것을 권장합니다.

2019-09-04 14:02 UTC, BeokBeok commented on junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/base/BaseActivity.kt
> +    fun showToast(text: String, duration: Int = Toast.LENGTH_SHORT) {
함수 관련 convention 을 따르는것을 권장합니다.
https://kotlinlang.org/docs/reference/functions.html#named-arguments

2019-09-04 14:02 UTC, BeokBeok commented on junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/base/BasePresenter.kt
> +    fun onDestroy()
해당 함수는 사용하지 않는 것으로 보입니다.
사용하지 않는다면 제거해주세요.

2019-09-04 14:02 UTC, BeokBeok commented on junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/data/source/UpbitRepository.kt
> +        @JvmStatic
Java 와 같이 사용하지 않으므로, 해당 annotation 은 제거해주세요.

2019-09-04 14:02 UTC, BeokBeok commented on junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/data/source/UpbitRepository.kt
> +        @Volatile
이 annotation 을 사용한 이유가 궁금합니다.

2019-09-05 04:56 UTC, junghum21 commented on junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/data/source/UpbitRepository.kt
> +        @JvmStatic
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/202/commits/74bc1d2acbbb922337a249bfff4963a9abe7a425

반영완료

2019-09-05 04:56 UTC, junghum21 commented on junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/base/BasePresenter.kt
> +    fun onDestroy()
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/202/commits/36f7bcd36783005bcc8e6ef62ff392087a0ad254

반영완료

2019-09-05 04:56 UTC, junghum21 commented on junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/base/BaseActivity.kt
> +    fun showToast(text: String, duration: Int = Toast.LENGTH_SHORT) {
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/202/commits/ddb6a5cf247f712c3267c4e21e8e5c53b8f5826d

반영완료

2019-09-05 04:56 UTC, junghum21 commented on junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/base/BaseActivity.kt
> +    @LayoutRes val layoutRes: Int
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/202/commits/ddb6a5cf247f712c3267c4e21e8e5c53b8f5826d

반영완료

2019-09-05 04:57 UTC, junghum21 commented on junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/data/source/UpbitRepository.kt
> +        @Volatile
https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.jvm/-volatile/index.html

코틀린 싱글톤을 구현하기 위해서 입니다.

object로도 구현할 수 있지만, 생성자 인자를 받을 수 없기 때문에 따로 싱글톤을 만들어준 것이구요.

2019-09-05 05:39 UTC, BeokBeok commented on junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/data/source/UpbitRepository.kt
> +        @Volatile
companion object는 thread-safe 한 것으로 알고 있습니다.
만약, thread safe 하게 처리하기 위함이라면, 제거하셔도 될 것 같습니다.
https://kotlinlang.org/docs/tutorials/kotlin-for-py/objects-and-companion-objects.html#companion-objects

2019-09-05 07:52 UTC, junghum21 commented on junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/data/source/UpbitRepository.kt
> +        @Volatile
https://github.com/googlesamples/android-architecture-components/blob/master/BasicRxJavaSampleKotlin/app/src/main/java/com/example/android/observability/persistence/UsersDatabase.kt

이 코드를 참고했습니다.


반영완료
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/202/commits/f1b1af2e41364e8d077627cf8ec4f7d436896ecc

2019-09-05 07:55 UTC, BeokBeok commented on junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/data/source/UpbitRepository.kt
> +        @Volatile
syncronized도 같이 제거하셔도 될 것 같습니다.

2019-09-05 08:58 UTC, junghum21 commented on junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/data/source/UpbitRepository.kt
> +        @Volatile
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/202/commits/70db7008bf4816cbcb0307c46d8b9785087f7629

반영완료

2019-09-05 09:11 UTC, BeokBeok approved these changes
LGTM:ok_hand:

2019-09-16 02:47 UTC, merged