HW-3 mvp적용해보기
sjjeong/GoogryAndroidArchitecutreStudy pull request #203
Opened 2019-09-04 06:57 UTC by syli9526

2019-09-14 09:58 UTC, onemask submitted a review, later dismissed
늦어서 죄송합니다 ㅠㅠ

2019-09-14 10:58 UTC, onemask commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/CoinFragment.kt
여기 개행 없으면 좋을거 같아요-
coinFragment 안에 선언되어있는 다른 함수들은 
method 밑에 개행이 없는데     override fun onViewCreated(view: View, savedInstanceState: Bundle?) {}
만 밑에 개행이 있어서 통일된 모습이면 좋을거 같습니다~

2019-09-14 11:01 UTC, onemask commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/MainActivity.kt
> +    private val pageList = listOf(
그 상수로 리스트 값을 만들어서  addTab 하는것보다는 
getMarketInfo하고 
groupBy나 다른 메소드를 이용해서 값을 
tab.setData()처리하는것이 더 좋을거 같습니다-

2019-09-14 11:06 UTC, onemask commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/adapter/ViewPagerAdapter.kt
> +import com.example.architecturestudy.ui.coin.CoinFragment
오 지금와서 저도 보니 안하였지만 
지금 거의 main pacakge 안에 viewpagerAdapter가 있고 
coin  package안에 recyclerviewAdapter로 쓰이고 있는데 
나중에 기능 단위가 만아지면 feture단위로 adatper를 분리하니까 

adapter package 안에 모든 adpater를 모아두는것 보다는 
main 안에 adapter 패키지 만들고
coin 안에 adapter 패키지 만들어서 관리하는게 어떤 기능이 어떤 adapter를 사용하는지 알기 쉬울거 같아서 
패키지를 그렇게 분리하는게 adapter 관리가 더 용이할거 같습니다!

2019-09-16 12:26 UTC, syli9526 commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/MainActivity.kt
> +    private val pageList = listOf(
groupby를 repository에서 하는게 맞겠죠...?

2019-09-16 12:29 UTC, syli9526 commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/CoinFragment.kt
[a7ca140](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/203)
변경하였습니다.

2019-09-16 12:30 UTC, syli9526 commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/adapter/ViewPagerAdapter.kt
> +import com.example.architecturestudy.ui.coin.CoinFragment
[e8225d8](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/203/commits/e8225d837be54b2ac0f0b273204d5a6bd73b8a7a)
변경하였습니다.

2019-09-16 13:37 UTC, onemask commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/MainActivity.kt
> +    private val pageList = listOf(
🤔음 repository에서도 해도 되는데 
기존 소율님이 하신 로직을 변경 시키지 않는 쪽으로 하고 싶네요ㅠㅠ

2019-09-16 13:39 UTC, onemask commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/MainActivity.kt
> +    private val pageList = listOf(
`` interface View {
        fun setPage(titles : List<String>)
        fun setData(marketList: List<MarketResponse>)
        fun showMessage(message: String)
    }
```

2019-09-16 13:48 UTC, onemask commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/MainActivity.kt
> +    private val pageList = listOf(
``` override fun getMarketList() {

        CoinRepositoryImpl.getInstance().getMarketInfo(object : UpbitListener<MarketResponse> {
            override fun onResponse(dataList: List<MarketResponse>) {
                with(view){

                    dataList.apply {

                        setData(this)
                        setPage(this.groupBy {
                            it.market.split("-")[0]
                        }.map {
                            it.key
                        })
                    }
                }
            }
```
MainPresenter의 onResponse() 부분에서 response로 받은 dataList를 
groupBy{}로 만든 titles을 setPage()로 보내줘서

2019-09-16 14:00 UTC, onemask commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/MainActivity.kt
> +    private val pageList = listOf(
```
class ViewPagerAdapter(

fun setData( marketList: List<MarketResponse>) {

        val list = ArrayList<String>()
        val pageList = marketList.groupBy {
            it.market.split("-")[0]
        }

        for (value in pageList.keys) {
            list.add((marketList.filter { it.market.split("-")[0] == value }
                .map { it.market } as ArrayList<String>).joinToString(","))
        }

        markets = list

        notifyDataSetChanged()
    }
```

2019-09-16 14:02 UTC, onemask commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/MainActivity.kt
> +    private val pageList = listOf(
```override fun setData(marketList: List<MarketResponse>) {
        viewPagerAdapter.setData(marketList)
    }

    override fun setPage(titles : List<String>) {

        currency_tab_layout.run {
            titles.forEach{
                addTab(newTab().setText(it))
            }

```

MainContract View에서 오버라이드해서 사용하는 부분은 이런식으로 바뀌더라구용

2019-09-16 14:07 UTC, onemask commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/MainActivity.kt
> +    private val pageList = listOf(
기존에 구조를 바꾸지 않고 
ViewPager의 Title를 API Call을 하고 어떻게 가져올까 생각하다가
뭔가 이런저런 생각이 나서 시도해보았어요..

이것도 뭔가 ViewPagerAdapter에서 하는게 맘에 안들긴 헌데
뭔가 제가 이런식으로 ~바꾸는게 좋지 않을까요 라고 권유해서 
번거롭게 하는건 아닌지 하는 맘에 시도해보게 되었어요ㅠㅠ 

다른 여러 의견 있으시면 말해주세요!

2019-09-17 06:45 UTC, BeokBeok requested changes
안녕하세요. 스터디 2기 강현석이라고 합니다,
부족하지만 잘 부탁드립니다. 😅

2019-09-17 06:45 UTC, BeokBeok commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/data/repository/CoinRepositoryImpl.kt
> +        CoinDataSourceImpl.getInstance()
CoinDataSourceImpl 을 제거해도 됩니다.

2019-09-17 06:45 UTC, BeokBeok commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/data/repository/CoinRepositoryImpl.kt
>              instance ?: synchronized(this) {
synchronized를 사용하신 이유가 있나요?

2019-09-17 06:45 UTC, BeokBeok commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/data/source/CoinDataSourceImpl.kt
>  class CoinDataSourceImpl : CoinDataSource {
사용하지 않는 클래스는 제거해주세요.

2019-09-17 06:45 UTC, BeokBeok commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/coin/CoinFragment.kt
>      override fun onCreateView(inflater: LayoutInflater, container: ViewGroup?, savedInstanceState: Bundle?): View? {
파라미터가 긴 경우, 함수 컨벤션을 따르는 것을 권장합니다.
https://kotlinlang.org/docs/reference/coding-conventions.html#function-formatting

또한, 구현부에 return 밖에 없는 경우에는 = 을 사용할 수 있습니다.

2019-09-17 06:45 UTC, BeokBeok commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/coin/CoinPresenter.kt
> +
개행은 가급적이면 한줄 단위로 해주세요.

2019-09-17 06:45 UTC, BeokBeok commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/main/MainPresenter.kt
> +class MainPresenter(private val view: MainContract.View):
클래스 관련 컨벤션을 준수하는 것을 권장합니다.
https://kotlinlang.org/docs/reference/coding-conventions.html#class-header-formatting

2019-09-19 12:20 UTC, syli9526 commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/data/repository/CoinRepositoryImpl.kt
>              instance ?: synchronized(this) {
coinPresenter와 MainPresenter 두곳에서 접근해서 혹시 몰라 동기화 처리를 하였습니다.

2019-09-19 12:23 UTC, syli9526 commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/data/source/CoinDataSourceImpl.kt
>  class CoinDataSourceImpl : CoinDataSource {
혹시 사용하지 않는 클래스가 무엇인가요..??
제가 보았을때는 다 사용하는 클래스인거같은데..

2019-09-19 12:33 UTC, syli9526 commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/data/repository/CoinRepositoryImpl.kt
> +        CoinDataSourceImpl.getInstance()
[c3751fa](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/203/commits/c3751fa50f0e5d34500e771bbd678d89b7f4185d)
개행이 잘못 되어있던것 입니다. 수정하였습니다.

2019-09-19 12:34 UTC, syli9526 commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/coin/CoinFragment.kt
>      override fun onCreateView(inflater: LayoutInflater, container: ViewGroup?, savedInstanceState: Bundle?): View? {
[40d7e31](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/203/commits/40d7e314e710865faab5e7ddf96843a5bcbafe4f)
수정하였습니다.

2019-09-19 12:35 UTC, syli9526 commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/coin/CoinPresenter.kt
> +
[a47ea8d](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/203/commits/a47ea8d95975347074081e2332b119ed575dfb65)
수정하였습니다.

2019-09-19 12:35 UTC, syli9526 commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/main/MainPresenter.kt
> +class MainPresenter(private val view: MainContract.View):
[f216568](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/203/commits/f216568cf13e3be500a1da1c4152472dc68753b1)
수정하였습니다.

2019-09-19 12:41 UTC, syli9526 commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/MainActivity.kt
> +    private val pageList = listOf(
음 제가 생각했을때 groupBy를 하려면 하는곳이 repository여야할거같아요.. 쨋든 가져온 데이터를 가공하는것은 repository담당이니까요.. 근데 그러려면.. 대공사를...ㅠㅠ 이번주 주말에 시도해볼께요 ㅠㅠ 바빠서 이제 봤어요 ㅠㅠ

2019-09-19 13:24 UTC, BeokBeok commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/data/repository/CoinRepositoryImpl.kt
> +        CoinDataSourceImpl.getInstance()
외부에서 Data Source를 생성하고, 
생성된 Data Source를 Repository 로 전달하여 처리 하는 것이 좋아보입니다.
즉, 의존성 주입을 해주시는 것이 좋을 것 같습니다.

2019-09-19 13:24 UTC, BeokBeok commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/data/repository/CoinRepositoryImpl.kt
>              instance ?: synchronized(this) {
companion object는 thread safe 한 것으로 알고 있습니다.
해서, synchronized 처리는 제거해도 될 것 같습니다.

2019-09-19 13:24 UTC, BeokBeok commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/data/source/CoinDataSourceImpl.kt
>  class CoinDataSourceImpl : CoinDataSource {
코드를 잘 못 봐서 사용하지 않는 클래스로 보았습니다.

2019-09-20 15:47 UTC, syli9526 commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/data/repository/CoinRepositoryImpl.kt
> +        CoinDataSourceImpl.getInstance()
[fb4e5da](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/203/commits/fb4e5da0895b37c5940c4460a68eacf89e55700e)
수정하였습니다

2019-09-20 15:47 UTC, syli9526 commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/data/repository/CoinRepositoryImpl.kt
>              instance ?: synchronized(this) {
[5507518](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/203/commits/5507518d0279281a810914a7ffbc211be2aa5fe5)
수정하였습니다

2019-09-21 00:06 UTC, BeokBeok approved these changes
LGTM:ok_hand:

2019-09-21 04:53 UTC, sjjeong commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/main/MainActivity.kt
> +    override fun setPage() {
setup으로 하면 더 좋아요

2019-09-21 04:53 UTC, sjjeong commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/coin/CoinPresenter.kt
> +        CoinRepositoryImpl(CoinDataSourceImpl.getInstance())
presenter 생성자로 CoinRepositoryImpl을 CoinRepository 타입으로 받아주세요

2019-09-21 04:53 UTC, sjjeong commented on syli9526/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/data/repository/CoinRepository.kt
> +    fun getMarketInfo(listener: UpbitListener<MarketResponse>)
interface대신 higher-order function을 사용해보세요

2019-09-21 04:53 UTC, closed without merging