Class04/onemask
sjjeong/GoogryAndroidArchitecutreStudy pull request #204
Opened 2019-09-09 11:00 UTC by onemask

MainActivity > Add  MainContract,Presenter
TickerListFragment > Add TickerContract, TickerPresenter
를 추가하여 구현하였습니다. 

MVP로 구조를 바꾸면서 
* adapter 관련한 코드 이동이나 로직 수정이 없어서 해당 사항에 대한 의문과
* recyclerview setup 하는것도 각 view의 contract에서 선언하여서 맞는지 의문이 들었습니다.

2019-09-13 14:35 UTC, syli9526 commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/main/presenter/MainPresenter.kt
> +    private val upbitRepository: UpbitRepositoryImpl,
mainActivity는 레파지토리에 접근할 필요가 없어니까 
mainActivity에서 UpbitRepositoryImpl를 넘겨주지 말고 MainPresenter에서 접근하는게 맞는거같아요

2019-09-13 14:50 UTC, syli9526 commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/tickerlist/presenter/TickerContract.kt
> +        fun setRecyclerView()
제가 이부분은 명확히 이거다!! 라고 할 수는 없지만..
저는 presenter가 알 필요없는 view의 동작은 interface에 넣지는 않았습니다.

2019-09-13 14:51 UTC, syli9526 commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/tickerlist/presenter/TickerPresenter.kt
> +    private val upbitRepository: UpbitRepositoryImpl,
이부분도 마찬가지로 TickerListFragment에서 넘겨주는것이 아니라 TickerPresenter에서 바로 접근하는게 좋은거같아요!

2019-09-13 15:01 UTC, syli9526 commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/main/MainActivity.kt
> +    private val presenter: MainPresenter by lazy { MainPresenter(UpbitRepositoryImpl, this) }
viewPagerAdapter처럼 presenter도 타입은 명시하지 않으셔도 될 것 같습니다.

2019-09-13 15:05 UTC, syli9526 commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/main/presenter/MainContract.kt
> +        fun initViewPager()
이 부분도 사실 presenter가 알 필요 없는 동작이기 때문에 저는 contract에 넣지 않았습니다!

2019-09-14 11:18 UTC, onemask commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/main/presenter/MainPresenter.kt
> +    private val upbitRepository: UpbitRepositoryImpl,
3f90e6a
수정하였습니다

2019-09-14 11:19 UTC, onemask commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/tickerlist/presenter/TickerContract.kt
> +        fun setRecyclerView()
f27bf90
수정하였습니다

2019-09-14 11:20 UTC, onemask commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/tickerlist/presenter/TickerPresenter.kt
> +    private val upbitRepository: UpbitRepositoryImpl,
75c0325,
246c0a5
수정하였습니다!

2019-09-14 11:21 UTC, onemask commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/main/MainActivity.kt
> +    private val presenter: MainPresenter by lazy { MainPresenter(UpbitRepositoryImpl, this) }
수정하였습니다
65d9d1e

2019-09-14 11:21 UTC, onemask commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/main/presenter/MainContract.kt
> +        fun initViewPager()
5be2a16 
수정하였습니다

2019-09-17 01:52 UTC, BeokBeok requested changes
안녕하세요. 스터디 2기 강현석이라고 합니다.
부족하지만 잘 부탁드립니다. ^~^

2019-09-17 01:52 UTC, BeokBeok commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/TickerListFragment.kt
> +    @SuppressLint("CheckResult")
getTicker 함수에 Lint 처리가 되어있어서, 이 Lint 처리는 제거하셔도 됩니다.

2019-09-17 01:52 UTC, BeokBeok commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/main/MainActivity.kt
> +            adapter = viewPagerAdapter
이런 식으로 해도 되지 않을까요? lazy를 사용하신 이유가 있나요?
```suggestion
            adapter = ViewPagerAdapter(supportFragmentManager)
```

2019-09-17 01:52 UTC, BeokBeok commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/main/MainActivity.kt
> +
개행은 가급적 한줄 단위로 해주세요

2019-09-17 01:52 UTC, BeokBeok commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/main/presenter/MainPresenter.kt
> +                view.setViewPagerData(marketNamesArr)
setViewPagerData 함수 인자에 Map을 넘겨서 
title 과 data 처리를 같이 하시는 것은 어떤가요?

2019-09-17 01:52 UTC, BeokBeok commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/main/presenter/MainContract.kt
> + * created by onemask
불필요한 주석은 제거해주세요

2019-09-17 01:52 UTC, BeokBeok commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/main/presenter/MainPresenter.kt
> +    @SuppressLint("CheckResult")
subscribe의 리턴값을 처리하지 않고 해당 Lint 관련하여 ignore 처리한 이유가 있나요?

2019-09-17 01:52 UTC, BeokBeok commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/main/presenter/MainPresenter.kt
> +                        .joinToString(",") { it.market }
joinToString 함수의 파라미터 default 값이 콤마이므로
파라미터에 값을 전달하지 않으셔도 됩니다.
그리고 it 변수가 중복되므로, 다른 이름으로 변경해서 사용해주세요.

2019-09-17 05:34 UTC, onemask commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/TickerListFragment.kt
> +    @SuppressLint("CheckResult")
수정하였습니다
9ea9dd5

2019-09-17 05:47 UTC, onemask commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/main/MainActivity.kt
> +            adapter = viewPagerAdapter
- viewPagerAdapter 변수를  lazy로 선언하면 setViewPagerData()에서 
```suggestion
 viewPagerAdapter.setData(titles,items)
```
  이렇게 선언할 수 있어서 깔끔해 보여서 lazy를 사용하게 되었습니다~

2019-09-17 05:48 UTC, onemask commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/main/MainActivity.kt
> +
수정하였습니다~ 
a74a4d7

2019-09-17 05:49 UTC, onemask commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/main/presenter/MainPresenter.kt
> +                view.setViewPagerData(marketNamesArr)
오 뭔가 덕분에 깔끔하게 된거 같아요! 감사합니다. 수정하였습니다.

5dc0e49, cc7cae9,  33d257e

2019-09-17 05:52 UTC, onemask commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/main/presenter/MainContract.kt
> + * created by onemask
그 수정은 하였지만 
cc7cae9 

해당 주석은 
<img width="2109" alt="스크린샷 2019-09-17 오후 2 49 56" src="https://user-images.githubusercontent.com/27774564/65014765-89946a80-d95a-11e9-8204-318d72e30dd0.png">

Code Templates로 선언해 놓은건데 파일을 생성될때마다 생겨나는데
header로 선언을 하지 않는점이 바람직한가요?

2019-09-17 05:56 UTC, onemask commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/main/presenter/MainPresenter.kt
> +    @SuppressLint("CheckResult")
이유는 없었습니다..
안드로이드 스튜디오가 노란불빛을 내며 
해당 사항을 권고해주어서 그렇게 하였습니다.

말씀 해 주신바대로 하는것이 바람직한가용?

2019-09-17 05:56 UTC, onemask commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/main/presenter/MainPresenter.kt
> +                        .joinToString(",") { it.market }
넵 수정하였습니다~

30067a1

2019-09-17 06:17 UTC, BeokBeok commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/main/presenter/MainContract.kt
> + * created by onemask
파일 생성 관련해서는 커밋한 로그를 보면 누가 생성했는지 알 수 있으므로
개인적으로는 의미가 없는 주석이라 생각됩니다.

2019-09-17 06:17 UTC, BeokBeok commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/main/presenter/MainPresenter.kt
> +    @SuppressLint("CheckResult")
그렇다면, Disposable 관련하여 clear 혹은 dispose 처리를 해 주시는 것이 좋을 것 같습니다.

2019-09-17 06:17 UTC, BeokBeok commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/main/presenter/MainPresenter.kt
> +                view.setViewPagerData(marketNamesArr)
제가 의도한 것은 파라미터를 두개로 받는 것이 아니라,
 getMarketAll 함수를 호출하게 되면 Map 타입의 값이 리턴이 되는데
이 리턴 타입을 그대로 받아서 처리를 하는 것이 어떨지 의견을 제시해봤습니다.

2019-09-17 07:51 UTC, onemask commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/main/presenter/MainPresenter.kt
> +                view.setViewPagerData(marketNamesArr)
그렇쿤요.
말씀하신바대로 수정하였습니다~
빠른 피드백 감사합니다. 
b47ccc0, d313925, dfa2556

2019-09-17 07:55 UTC, onemask commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/main/presenter/MainPresenter.kt
> +    @SuppressLint("CheckResult")
수정하였습니다~
 build.gradle rxkotlin 추가 : c163a88,  
Presenter 처리 : 00200eb, dfa2556
Contract 메소드 추가 : 36830a7, d313925
View destroy 될때 clear 처리 : 0c5cb9f, 96fa659,

2019-09-17 09:02 UTC, BeokBeok commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/main/MainActivity.kt
> +        viewPagerAdapter.apply {
apply 를 run이나 with로 변경해주세요.

2019-09-17 09:02 UTC, BeokBeok commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/main/MainActivity.kt
> +            setData(marketNames)
marketData의 value만 변경해서 marketData를 전달하여 title과 data를 설정하는 것은 어떤가요?

2019-09-17 14:11 UTC, onemask commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/main/MainActivity.kt
> +        viewPagerAdapter.apply {
변경하였습니다~
ee5f061
혹시 근데 왜 apply말고 run이나 with를 권장하시는지 여쭤볼 수 있을까용?

2019-09-17 14:46 UTC, onemask commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/main/MainActivity.kt
> +            setData(marketNames)
marketData의 data 구조가 Map으로 
key 값을 title로 만들고자 하고 있는데,
value만 변경해서 title과 data를 설정한다는 것이 어떤 말씀인지 잘 모르겠습니다 ㅠㅠ

2019-09-18 01:13 UTC, BeokBeok commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/main/MainActivity.kt
> +        viewPagerAdapter.apply {
![image](https://user-images.githubusercontent.com/48344355/65095104-c152ef00-d9fa-11e9-98e6-27be41c0d5c7.png)
apply는 수신 객체 자신을 다시 반환하려는 경우에 쓰입니다.
예를 들면,
```
val viewPagerAdapter = ViewPagerAdapter(supportFragmentManager).apply {
    setTitles(titles.toList())
    setData(marketNames)
}
```
그런데, 여기에서는 코드 블록의 수행결과만 처리하고 있기 때문에
run,let, with를 사용하시는 것을 권장하였습니다.

2019-09-18 01:13 UTC, BeokBeok commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/main/MainActivity.kt
> +            setData(marketNames)
marketData 의 key는 String이고 value는 List<MarketResponse> 로 되어있는데,
여기서 value에 해당하는 List<MarketResponse>를 가공한 형태의 value로 업데이트를 하고
업데이트된 marketData를 전달하는 것이 어떨까 싶었습니다.

2019-09-18 06:00 UTC, onemask commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/main/MainActivity.kt
> +        viewPagerAdapter.apply {
이미지까지 첨부하여 자세한 리뷰 감사드립니다 🙂

2019-09-18 06:04 UTC, onemask commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/main/MainActivity.kt
> +            setData(marketNames)
말씀하신대로 marketData만을 이용하여 해당 로직 수정하였습니다~ 
0d94118,
3ab83ca

2019-09-18 06:07 UTC, BeokBeok commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/main/MainActivity.kt
> +            setData(marketNames)
setTitles 함수에 notifyDataSetChanged() 는 없어도 되지 않나요?

2019-09-18 14:43 UTC, onemask commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/main/MainActivity.kt
> +            setData(marketNames)
넵 없어도 되더라구요!
말씀하신대로 수정하였습니다. 
2fc2494
꼼꼼히 봐주셔서 감사합니다.

2019-09-19 01:32 UTC, BeokBeok approved these changes
LGTM:ok_hand:

2019-09-21 04:52 UTC, sjjeong commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/main/presenter/MainPresenter.kt
> +class MainPresenter(
```
class MainPresenter(view: MainContract.View) : BasePresenter<MainContract.View>(view),
    MainContract.Presenter {

    override fun loadData() {
        UpbitRepositoryImpl.getMarketAll()
            .map {
                val list = it.toList()
                list.map { it.first } to
                        list.map { it.second }.map { it.joinToString { it.market } }
            }
            .subscribe(view::setViewPagerData, Timber::e)
            .addTo(disposables)
    }
}
```

2019-09-21 04:52 UTC, sjjeong commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/tickerlist/presenter/TickerPresenter.kt
> +    override fun getTicker(market: String) {
```kotlin
override fun getTicker(market: String) {
    UpbitRepositoryImpl.getTickers(market)
        .map { it.map(TickerResponse::toTicker) }
        .observeOn(AndroidSchedulers.mainThread())
        .subscribe(view::setData, Timber::e)
        .addTo(disposables)
}
```

2019-09-21 04:53 UTC, merged