Class03/dlwls5201
sjjeong/GoogryAndroidArchitecutreStudy pull request #205
Opened 2019-09-15 06:28 UTC by dlwls5201

Presenter -> ViewModel로 변환하는 식으로 작업을 진행했습니다.

궁금한 점은 구글 예제와는 다르게 Adapter를 ViewModel의 파라미터로 넘긴후 xml에서 모든 작업을 처리하도록 구현해 보았습니다. Activity와 Fragment에는 껍데기만 있게 할러고 하다보니 adapter를 어디에 구현해야 좋을지 고민해 보았습니다.

2019-09-16 07:41 UTC, zozero94 reviewed
덕분에 많이배웠습니다 굽신굽신

2019-09-16 07:41 UTC, zojae031 commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/ui/tickerlist/TickerAdapter.kt
> +                tickerItemModel = TickerItemViewModel(ticker)
여기서 왜 새로운 TicerItemViewModel을 만들었는지 알 수 있을까요???

2019-09-16 07:41 UTC, zojae031 commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/ui/tickerlist/TickerAdapter.kt
> +                tickerItemModel = TickerItemViewModel(ticker)
바로 Adatper에 있는 데이터를 셋하지 못하여 Adapter에 해당하는 ViewModel을 따로만들어서 set한거로 이해하긴 했는데 아직 개념이 왔다갔다해서 너무 헷갈리네요 ㅠㅠ

2019-09-16 16:40 UTC, dlwls5201 reviewed
데이터 바인딩 적용하는게 재밌어서 이짓 저짓 해봤습니다 ㅎㅎ

2019-09-16 16:40 UTC, dlwls5201 commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/ui/tickerlist/TickerAdapter.kt
> +                tickerItemModel = TickerItemViewModel(ticker)
큰 이유는 없습니다 :)
adapter의 아이템도 data binding을 적용 할 수 있겠네? 라는 생각으로 적용했습니다. 이름을 TickerItemViewModel이라 명명해 헷갈릴 수 있을 것 같네요. 굽신굽신

2019-09-17 18:09 UTC, preludezdev reviewed
이번에도 진성님 코드 보면서 많은걸 배웠네요... 어댑터 부분만 빼면 제가 말씀드릴건 없을 것 같습니다 :)

2019-09-17 18:09 UTC, preludezdev commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/ui/main/MainViewModel.kt
>      private val compositeDisposable: CompositeDisposable = CompositeDisposable()
제가 이해하고 있는 범위 내에서 어댑터를 뷰모델의 인자로 받아도 되는지 약간 의문스럽습니다. 어댑터는 데이터를 가지고 있으므로 모델의 성격이 있지만 어댑터에 따라서 뷰를 갱신하거나 관련 뷰를 반환하는 작업도 있어서 뷰의 성격도 가지고 있다고 생각합니다. 그런데 이 어댑터를 뷰모델에 넣게되면 뷰모델에서 뷰에 접근할 수 있기 때문에(?) 뷰모델은 뷰를 몰라야 된다는 MVVM 패턴에 맞지 않다고 생각합니다. 그리고 뷰모델과 뷰는 이론적으로는 다대다 관계가 가능하다고 했는데 특정 어댑터를 넣게 되면 뷰와 뷰모델 간의 의존도도 더 강해질 것 같은데 어떻게 생각하세요?

2019-09-18 16:53 UTC, dlwls5201 commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/ui/main/MainViewModel.kt
>      private val compositeDisposable: CompositeDisposable = CompositeDisposable()
뷰모델은 다대다 관계가 성립되야 되지만 실재 프로젝트에서는 1:1의 관계로 많이 사용하는것 같습니다. 그래서 MVVM 프로젝트에서 adapter 또한 viewModel로 넘기는 예제가 종종 보이네요. 이렇게 작업했지만 저도 애매한 부분인것 같고 학습을 위해 수정했습니다! 감사합니다.

commit : 5c2ce41

2019-09-18 16:55 UTC, dlwls5201 reviewed
MVVM을 공부하면 adapter 부분만 일부 수정했습니다.

2019-09-19 04:36 UTC, preludezdev commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/ui/main/MainViewModel.kt
>      private val compositeDisposable: CompositeDisposable = CompositeDisposable()
아 어댑터를 뷰모델에 넘기는 예제가 있나보네요. 저도 확실히 뭐가 맞는지는 잘 모르겠어서...확실하게 하려면 석준님께 답변 들어야될거같아요. 아직 MainViewModel 은 어댑터를 받고있으니 석준님이 잘 대답해주실거라 믿습니다ㅎㅎ 수고하셨어요!!

2019-09-19 04:43 UTC, preludezdev submitted a review, later dismissed
아 어댑터를 뷰모델에 넘기는 예제가 있나보네요. 저도 확실히 뭐가 맞는지는 잘 모르겠어서...확실하게 하려면 석준님께 답변 들어야될거같아요. 아직 MainViewModel 은 어댑터를 받고있으니 석준님이 잘 대답해주실거라 믿어요ㅎㅎ 고생하셨습니다!!

2019-09-19 13:47 UTC, BeokBeok requested changes
안녕하세요. 스터디 2기 강현석이라고 합니다.
부족하지만 잘 부탁 드립니다. 😅

2019-09-19 13:47 UTC, BeokBeok commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/base/BaseBindingViewHolder.kt
> +    private val variableId: Int?
변수명에 variable은 적합하지 않아 보입니다.
다른 이름으로 변경해주세요.

2019-09-19 13:47 UTC, BeokBeok commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/base/BaseBindingViewHolder.kt
> +            variableId?.let {
immutable 객체인 경우에는 let 대신 if 문을 통한 null check하는 것이 좋아보입니다.
https://medium.com/@elye.project/kotlin-dont-just-use-let-7e91f544e27f

2019-09-19 13:47 UTC, BeokBeok commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/base/BaseViewHolder.kt
> +abstract class BaseViewHolder(@LayoutRes layoutRes: Int, parent: ViewGroup?) :
클래스 관련 컨벤션을 따르는 것을 권장합니다.
https://kotlinlang.org/docs/reference/coding-conventions.html#class-header-formatting

2019-09-19 13:47 UTC, BeokBeok commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/ui/main/MainActivity.kt
> +        mainViewModel.detachView()
함수명과 동작이 상이합니다.
동작에 어울리는 함수명으로 작성해주세요.

2019-09-19 13:47 UTC, BeokBeok commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/ui/main/MainViewModel.kt
>      private val compositeDisposable: CompositeDisposable = CompositeDisposable()
Adapter는 View에서 처리해야 하는 것이 맞다고 생각합니다.
만약, Adapter에서 이벤트 처리를 하신다면
구현하신 TickerAdapter 처럼 처리하시면 될 것 같습니다.

2019-09-19 13:47 UTC, BeokBeok commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/ui/tickerlist/TickerListFragment.kt
>                  Injection.provideFolderRepository(context!!),
context!! 대신 requireContext 함수를 활용하시면 될 것 같습니다.

2019-09-19 13:47 UTC, BeokBeok commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/ui/tickerlist/TickerAdapter.kt
> +    class TickerBindingViewHolder(parent: ViewGroup) :
앞에 inner 키워드를 추가해주세요.

2019-09-19 13:47 UTC, BeokBeok commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/util/Extension.kt
> +        tickerItems?.let {
immutable 변수의 null check 시에는, let 보다는 if문으로 null check 하는 것이 좋은 것 같습니다.
https://medium.com/@elye.project/kotlin-dont-just-use-let-7e91f544e27f

2019-09-19 13:47 UTC, BeokBeok commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/util/Extension.kt
> +    val order: Int = if (isSelected) {
Int 타입 명시를 생략해도 됩니다.

2019-09-19 13:47 UTC, BeokBeok commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/util/Extension.kt
> +    for (i: Int in 0 until (mainAdapter.count)) {
i 변수의 타입 명시를 생략해도 됩니다.

2019-09-19 13:47 UTC, BeokBeok commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/util/Extension.kt
> +        mainAdapter.getFragment(i)?.run {
run 대신 let이 괜찮을 것 같습니다.
https://medium.com/@elye.project/kotlin-dont-just-use-let-7e91f544e27f

2019-09-19 13:47 UTC, BeokBeok commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/util/Extension.kt
> +        ContextCompat.getColor(context, study.architecture.myarchitecture.R.color.diff_up)
`study.architecture.myarchitecture` 를 import 하시어 정리해주세요.

2019-09-21 03:49 UTC, dlwls5201 commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/base/BaseBindingViewHolder.kt
> +    private val variableId: Int?
수정했습니다.
commit:ae2e3a4

2019-09-21 03:52 UTC, dlwls5201 commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/base/BaseBindingViewHolder.kt
> +            variableId?.let {
run과 let을 임의로 사용해 왔었는데 바이트코드로 변환 했을 때 성능 이슈 및 적합한 적용 법에 관한 링크인것 같아 감사합니다. 계속 읽어 보면서 실제 프로젝트에 적용해봐야겠습니다 :)

commit : 545c2bd

2019-09-21 03:52 UTC, dlwls5201 commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/base/BaseViewHolder.kt
> +abstract class BaseViewHolder(@LayoutRes layoutRes: Int, parent: ViewGroup?) :
수정했습니다.
commit : 7809965

2019-09-21 03:53 UTC, dlwls5201 commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/ui/main/MainActivity.kt
> +        mainViewModel.detachView()
수정했습니다.
commit : 3b68bb4

2019-09-21 03:53 UTC, dlwls5201 commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/ui/tickerlist/TickerListFragment.kt
>                  Injection.provideFolderRepository(context!!),
이런게 있었군요! 감사합니다.
commit : 68973ab

2019-09-21 03:54 UTC, dlwls5201 commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/ui/tickerlist/TickerAdapter.kt
> +    class TickerBindingViewHolder(parent: ViewGroup) :
추가했습니다.
commit : cb49e74

2019-09-21 03:54 UTC, dlwls5201 commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/util/Extension.kt
> +        mainAdapter.getFragment(i)?.run {
수정했습니다.
commit : 69b25c5

2019-09-21 03:55 UTC, dlwls5201 commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/util/Extension.kt
> +    val order: Int = if (isSelected) {
수정했습니다.
commit : 0980d9c

2019-09-21 03:55 UTC, dlwls5201 commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/util/Extension.kt
> +    for (i: Int in 0 until (mainAdapter.count)) {
수정했습니다.
commit : 3eb4167

2019-09-21 04:06 UTC, dlwls5201 commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/util/Extension.kt
> +        tickerItems?.let {
수정했습니다.
commit : 0d487cc

2019-09-21 04:09 UTC, dlwls5201 reviewed
디테일한 리뷰 감사합니다! 특히 run과 let 사용법에 대해 조금더 깊게 생각할 수 있어서 좋았습니다. 
mainAdapter의 함수는 mvvm에서 어떻게 써야 되는지 아직 감이 잡히지 않은데 나름 listener을 viewModel의 파라미터로 전달해 해결해 보았습니다.

2019-09-21 07:39 UTC, BeokBeok commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/base/BaseBindingViewHolder.kt
> +    private val variableId: Int?
bindingId 가 적합해 보입니다.
변수명에 variable 은 제거해주세요.

2019-09-21 07:39 UTC, BeokBeok commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/ui/main/MainActivity.kt
> +        mainViewModel.detachView()
MainViewModel 의 destroyView 대신 clearDisposable 가 더 적합해 보입니다.

2019-09-21 07:39 UTC, BeokBeok commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/ui/tickerlist/TickerAdapter.kt
> +    class TickerBindingViewHolder(parent: ViewGroup) :
ViewHolder는 Adapter 에 속한 것이기 때문에 
의도에 따라 inner 키워드를 붙이는 것이 좋다고 생각합니다.

2019-09-22 01:59 UTC, dlwls5201 commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/ui/tickerlist/TickerAdapter.kt
> +    class TickerBindingViewHolder(parent: ViewGroup) :
넵! 감사합니다!

2019-09-22 02:04 UTC, dlwls5201 commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/ui/main/MainActivity.kt
> +        mainViewModel.detachView()
수정했습니다.
commit : e89d04a

2019-09-22 02:05 UTC, dlwls5201 commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/base/BaseBindingViewHolder.kt
> +    private val variableId: Int?
수정했습니다.
commit : 629d17a

2019-09-22 02:05 UTC, dlwls5201 commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/util/Extension.kt
> +        ContextCompat.getColor(context, study.architecture.myarchitecture.R.color.diff_up)
수정했습니다
commit : f56923c

2019-09-22 06:38 UTC, sjjeong approved these changes
7주차 과제에서 처리해주세요

2019-09-22 06:40 UTC, preludezdev approved these changes
고생하셨습니다!

2019-09-23 15:16 UTC, BeokBeok approved these changes
LGTM:ok_hand:

2019-09-23 15:19 UTC, merged