HW-6 코인헬퍼 MVVM 적용하기
sjjeong/GoogryAndroidArchitecutreStudy pull request #207
Opened 2019-09-17 15:14 UTC by preludezdev

- 필터링 기능하고 룸 이용해서 로컬 DataSource 도 구현하고 싶었는데 시간이 없어서 일단 PR 올립니다...주륵ㅠ

2019-09-18 15:15 UTC, dlwls5201 commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/market/RecyclerViewAdapter.kt
> +                viewModel = ItemViewModel(item)
ItemViewModel 생성 필요없이 데이터바인딩 함수 중 setVariable을 사용하여 작업할 수 있습니다.

2019-09-18 15:19 UTC, dlwls5201 commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/viewmodel/MarketViewModel.kt
> +) : ViewModel() {
import 문에 androidx.lifecycle은 AAC입니다.
ViewModel, Room, LiveData, Paging 등등이 Android Architecture Component(AAC)입니다.
이번 과제는 Databinding을 사용것이므로 ObservableField를 사용하는것을 추천드립니다.

참고로 여기서 사용한 ViewModel과 LiveData는 정상적으로 동작되지 않습니다.
ViewModelProviders와 lifecycleowner 추가로 적용해줘야 라이브러리가 제 역활을 할 수 있습니다.

2019-09-18 15:26 UTC, dlwls5201 commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/market/RecyclerViewAdapter.kt
> +        if (data != null) {
코틀린에서는 ?.let 혹은 ?.run 을 사용하는게 어떨까 싶습니다 :)

2019-09-18 15:40 UTC, dlwls5201 reviewed
AAC 라이브러리를 사용하셨는데 DataBinding 함수만을 사용해서 만들어 보면 좋을 것 같습니다. 다음 시간에 AAC를 배우고 AAC로 변환했을 때 어떤점이 더 좋아지는지 비교하시면 좋을 것 같습니다:)

2019-09-19 04:06 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/market/RecyclerViewAdapter.kt
> +                viewModel = ItemViewModel(item)
ItemViewModel 클래스를 제거하고 아이템 레이아웃의 variable을 coin 으로 직접 지정해서 구현했습니다.

commit : c7aa314

2019-09-19 04:11 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/viewmodel/MarketViewModel.kt
> +) : ViewModel() {
MVVM 구조는 얼추 이해해도 코드로 어떻게 짜야할지 몰라 구글 공식홈 검색해서 따라한건데 생각해보니 거기서 알려주는 ViewModel 은 AAC ViewModel 이었네요. 저희가 배운건 MVVM 아키텍처의 ViewModel 인데 말이죠. 이제야 차이점이 보이네요. 감사합니다 :)

commit : afb7fbf

2019-09-19 04:16 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/market/RecyclerViewAdapter.kt
> +        if (data != null) {
말씀해주신 부분을 ?.let 으로 널체크하게 작성했습니다. 그런데 궁금한점이 그럼 코틀린에서는 널체크를 ?.let 이나 ?.run으로 거의 다 하나요? 제 MarketViewModel 의 loadData() 메소드 부분에 보면 keyMarket 이 null 인지 체크하는 if 문이 있는데 이걸 ?.let 으로 바꾸면 뭐랄까 람다식이 한번에 너무 많아지는 느낌인데 그렇게 코딩해도 괜찮은건지 궁금합니다

commit : 56194c3

2019-09-19 04:33 UTC, dlwls5201 commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/market/RecyclerViewAdapter.kt
> +        if (data != null) {
동작만 된다면 코드는 어떻게 되는 상관없습니다. 결국 팀에서 사용하는 컨벤션에 맞춰서 작업하면 되는거니깐요. null 체크관해서는 저 개인 의견이었습니다. ㅎㅎ

2019-09-19 04:34 UTC, dlwls5201 submitted a review, later dismissed
고생하셨습니다! MVVM은 어렵네요.

2019-09-19 04:41 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/market/RecyclerViewAdapter.kt
> +        if (data != null) {
아 그렇군요. 사실 이번 스터디 시작하면서 코틀린을 처음 써봐서 아직 많이 어색해요ㅠ 다들 코틀린스럽게 짜는게 중요하다고 얘기를 해서 어떤것들이 있을까 계속 관심을 가지고 있긴한데... 아무래도 코틀린으로 짠 코드를 많이 봐야될 것 같아요. 의견은 언제나 항상 always 환영입니다. 감사합니다 :D

2019-09-20 04:55 UTC, BeokBeok requested changes
안녕하세요. 스터디 2기 강현석이라고 합니다.
부족하지만 잘 부탁드립니다. ^~^

2019-09-20 04:55 UTC, BeokBeok commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/main/MainActivity.kt
> +            tabLayout.setupWithViewPager(binding.viewPager)
binding 변수는 생략해도 될 것 같습니다.
```suggestion
            tabLayout.setupWithViewPager(viewPager)
```

2019-09-20 04:55 UTC, BeokBeok commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/market/MarketFragment.kt
> +        marketViewModel.loadData(arguments?.getString(key)) // Presenter 를 통해 해당 마켓의 데이터 불러오기
presenter를 viewmodel로 변경함으로써, 주석 또한 변경해줘야 합니다.
`// viewmodel 을 통해 해당 마켓의 데이터 불러오기`

해서 코드상으로 이해할 수 있는 동작이라면, 주석은 가급적이면 달지 않는 것이 좋습니다.

2019-09-20 04:55 UTC, BeokBeok commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/market/MarketFragment.kt
> +        ) // MarketViewModel 객체 생성
이 주석이 꼭 필요한 주석인가요?

2019-09-20 04:55 UTC, BeokBeok commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/market/RecyclerViewAdapter.kt
> +        data?.let {
immutable 변수에 대한 null check 는 let 보다 if 문 사용을 권장합니다.
https://medium.com/@elye.project/kotlin-dont-just-use-let-7e91f544e27f

2019-09-20 04:55 UTC, BeokBeok commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/util/BindingAdapters.kt
> +    @JvmStatic
해당 annotation 은 제거해주세요.

2019-09-20 04:55 UTC, BeokBeok commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/util/BindingAdapters.kt
> +        val adapter = this.adapter as RecyclerViewAdapter
adapter 가 RecyclerViewAdapter 의 타입이 아닌 경우에 에러가 발생하지 않을까요?

2019-09-20 04:55 UTC, BeokBeok commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/viewmodel/MarketViewModel.kt
> +    var isProgressed = ObservableField<Boolean>()
var을 val로 변경해주세요.

2019-09-20 04:55 UTC, BeokBeok commented on preludezdev/ArchitectureStudy/app/src/main/res/layout/activity_main.xml
> +                android:clickable="false"
clickable 속성에 false를 주실 것이면, 안주셔도 될 것 같습니다.

2019-09-20 04:55 UTC, BeokBeok commented on preludezdev/ArchitectureStudy/app/src/main/res/layout/activity_main.xml
>              <TextView
```
<LinearLayout>
    <TextView>
    <ImageView 
<LinearLayout>
```
대신 
TextView의 drawableRight 속성을 사용하시면 
LinearLayout으로 감싸지 않고 ImageView를 사용하지 않으셔도 됩니다.

`android:drawableEnd`

2019-09-20 08:34 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/util/BindingAdapters.kt
> +    @JvmStatic
해당 @JvmStatic 어노테이션을 지우면 아래 에러가 뜨면서 실행이 안되네요
java.lang.IllegalStateException: Required DataBindingComponent is null in class FragmentMarketBindingImpl.
A BindingAdapter in com.example.architecturestudy.util.BindingAdapters is not static and requires an object to use, retrieved from the DataBindingComponent. If you don't use an inflation method taking a DataBindingComponent, use DataBindingUtil.setDefaultComponent or make all BindingAdapter methods static.

2019-09-20 08:46 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/res/layout/activity_main.xml
>              <TextView
나중에 필터링 기능을 추가해서 필터링 기준에 따라 이미지뷰 소스를 바꿔주려고 계획중입니다. 그런데 이렇게 TextView 에 해당속성으로 이미지를 넣게 되면 이미지 소스 바꿀 때 selector 적용이 어려워지지 않나요?

2019-09-20 08:49 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/main/MainActivity.kt
> +            tabLayout.setupWithViewPager(binding.viewPager)
안녕하세요 현석님, 피드백 해주셔서 정말 감사합니다 
저도 잘 부탁드립니다 :)

해당부분 수정했습니다

commit : 33f5232

2019-09-20 08:50 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/market/MarketFragment.kt
> +        marketViewModel.loadData(arguments?.getString(key)) // Presenter 를 통해 해당 마켓의 데이터 불러오기
해당부분 수정했습니다

commit : 0bfe759

2019-09-20 08:50 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/market/MarketFragment.kt
> +        ) // MarketViewModel 객체 생성
필기노트 느낌처럼 주석 남겼던거같아요ㅠ
해당부분 수정했습니다

commit : 49ffc9c

2019-09-20 08:51 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/market/RecyclerViewAdapter.kt
> +        data?.let {
해당부분 수정했습니다

commit : b6681ab

2019-09-20 08:52 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/util/BindingAdapters.kt
> +        val adapter = this.adapter as RecyclerViewAdapter
에러가 발생할 것 같습니다ㅠ
해당부분 수정했습니다

commit : 6b7e77b

2019-09-20 08:52 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/viewmodel/MarketViewModel.kt
> +    var isProgressed = ObservableField<Boolean>()
해당부분 수정했습니다

commit : 34c7c3a

2019-09-20 08:52 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/res/layout/activity_main.xml
> +                android:clickable="false"
해당부분 수정했습니다

commit : c115d8d

2019-09-20 11:54 UTC, BeokBeok commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/util/BindingAdapters.kt
> +            adapter.setData(items.get())
if문에 한 줄 이여도 괄호를 꼭 넣어주세요.
https://developer.android.com/kotlin/style-guide#braces

2019-09-20 11:54 UTC, BeokBeok commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/util/BindingAdapters.kt
> +    @JvmStatic
object 클래스를 제거하시고 BindingAdapter를 구현해주세요.

2019-09-20 11:55 UTC, BeokBeok commented on preludezdev/ArchitectureStudy/app/src/main/res/layout/activity_main.xml
>              <TextView
drawableEnd 속성에 selector 적용하시면 되지 않을까요?

2019-09-21 03:13 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/res/layout/activity_main.xml
>              <TextView
아 그렇게 하면 셀렉터는 먹힐거같네요. 그런데 이미지의 위치를 텍스트의 중간에 오게 하고 사이즈를 조절하고 싶은경우에는 따로 style 로 설정해줘야 되나요? 

![image](https://user-images.githubusercontent.com/41214420/65367223-14ca7480-dc69-11e9-86f7-353aa48a83e8.png)

왼쪽이 drawableEnd 속성으로 준 이미지이고 오른쪽 세개는 기존 이미지입니다

2019-09-21 03:18 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/util/BindingAdapters.kt
> +            adapter.setData(items.get())
해당부분 수정했습니다

commit : 6a68a85

2019-09-21 03:19 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/util/BindingAdapters.kt
> +    @JvmStatic
해당부분 수정했습니다

commit : 6a68a85

2019-09-21 03:22 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/main/MainActivity.kt
> +            tabLayout.setupWithViewPager(binding.viewPager)
안녕하세요 현석님, 피드백해주셔서 감사합니다.
저도 잘 부탁드릴게요 :D

라고 분명히 저번에 답글 달때 이렇게 올렸는데 답글이 안달려있네요 ;( 
여튼 다시 한번 피드백 감사드립니다!!

해당 부분 반영했습니다.
commit : 33f5232

2019-09-21 07:42 UTC, BeokBeok commented on preludezdev/ArchitectureStudy/app/src/main/res/layout/activity_main.xml
>              <TextView
TextView 의 gravity를 center_vertical 로 설정하면 될 것 같습니다.

2019-09-21 08:44 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/res/layout/activity_main.xml
>              <TextView
레이아웃은 여전히 어색하네요ㅠ 
말씀해주신대로 반영했습니다!!

commit : 2cce608

2019-09-21 09:30 UTC, BeokBeok approved these changes
LGTM:ok_hand:

2019-09-22 06:46 UTC, dlwls5201 approved these changes
Approve 합니다.

2019-09-22 06:56 UTC, merged