HW-6 MVVM으로 변경하기
sjjeong/GoogryAndroidArchitecutreStudy pull request #208
Opened 2019-09-18 14:00 UTC by wswon

각자 Presenter를 가지고 있던 이전과 다르게 하나의 ViewModel 사용으로 변경 해보았습니다.
감사합니다.

2019-09-20 05:57 UTC, ganghee commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/view/coin/adapter/holder/CoinViewHolder.kt
> +            executePendingBindings()
개인적으로 궁금해서 그러는데 
`setVariable(BR.ticker, ticker)`
  `executePendingBindings()`
이 부분을 왜 썼는지 알 수 있을까요?

2019-09-20 05:57 UTC, ganghee commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/view/coin/CoinListActivity.kt
> +        ).apply {
apply를 통해 ViewModel을 생성하여 구현하였는데 이부분을 CoinListViewModel 객체안에 구현하는 것이 어떨까요?
변수 isConnectedApi 와 함수 getMarketList가 CoinListViewModel에 있는데 view에서 구현하는게 맞나 싶습니다.
mvvm 에서는 최대한 코드를 줄이고 viewModel에 구현하는 것을 권장하는 것으로 알고 있습니다.

2019-09-20 05:57 UTC, ganghee commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/view/coin/CoinListActivity.kt
> +    private fun setTabPager(marketList: List<MarketResponse>) {
이 함수도 viewModel에서 구현하는 것이 어떨까요?
그리고 getItem, getCount, getPageTitle 은 adapter에서 구현하는 것으로 알고 있는데 view애서 이 코드가 필요한지 궁금합니다~

2019-09-20 05:57 UTC, ganghee commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/viewmodel/CoinListViewModel.kt
> +        const val SUCCESS = "SUCCESS"
동반 객체를 사용한 이유를 알 수 있을까요? 상수가 다른 값으로 바뀌는 것도 아니고 
viewModel을 참조하는데 꼭 SUCCESS 상수를 통해서 참조해야하는 이유를 알고 싶습니다.
단순히 문자열을 나타내는 거라면 res패키지 string에 넣어 보는 건 어떨까요?

2019-09-20 05:57 UTC, ganghee commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/view/coin/CoinListActivity.kt
>      private val tabList = listOf(
view에 있는 코딩내용을 줄이기 위해 tabList 를 viewModel에 구현하는 것이 좋다고 생각합니다.

2019-09-20 06:02 UTC, ganghee commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/base/BaseViewModel.kt
> +abstract class BaseViewModel :
BaseViewModel을 생성하였으니 view의 base패키지 안에 들어있는 BasePresenter와 BaseView의 객체는 필요없을 것 같습니다.

2019-09-20 06:44 UTC, wswon commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/view/coin/adapter/holder/CoinViewHolder.kt
> +            executePendingBindings()
![image](https://user-images.githubusercontent.com/48197016/65304235-1ccbdb00-dbbb-11e9-8b9b-e2585e1f8e52.png)
위는 이거구요.

####즉각적인 바인딩
변수나 Observable이 변경되면 바인딩이 다음 프레임 전에 변경되도록 예약됨.
바인딩을 즉시 실행해야 할 경우 ViewDataBinding#executePendingBindings() 메서드를 사용.

데이터의 변경이 Observable 필드에 반영될 수 있도록 하는것 같아요

2019-09-20 06:44 UTC, wswon commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/viewmodel/CoinListViewModel.kt
> +        const val SUCCESS = "SUCCESS"
![image](https://user-images.githubusercontent.com/48197016/65304446-995eb980-dbbb-11e9-9d94-41422e42241b.png)
이렇게 Toast.LENGTH_SHORT 처럼 클래스 외부에서 알 수 있기 때문에 그렇게 상수로 만들었습니다.
ViewModel의 callback이 어떤 string 일때 success 로 판단하는지 외부에서 알 수 없기 때문입니다.

2019-09-20 06:44 UTC, wswon commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/view/coin/CoinListActivity.kt
> +        ).apply {
isConnectApi 와 getMarketList를 View에서 구현한게 아니라 
ViewModel의 변수화 함수를 사용한것 입니다.
apply를 사용한 이유는 객체 생성과 동시에 ViewModel의 함수를 호출하기 위해서이고,
 ```
        coinListViewModel = CoinListViewModel(
            CoinRepositoryImp.getInstance(Injection.provideCoinRemoteDataSource()),
            tabList.map { getString(it) }
        )
       coinListViewModel.run{
            if(isConnectedApi){
                getMarketList {
                    Toast.LENGTH_LONG
                    if (it == CoinListViewModel.SUCCESS) {
                        coinListViewModel.marketList.get()?.let { marketList->
                            setTabPager(marketList)
                        }
                    } else {
                        showMessage(it)
                    }
                }
            }
        }
```
이런 의미로 작성한 코드입니다.

2019-09-20 06:44 UTC, wswon commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/view/coin/CoinListActivity.kt
>      private val tabList = listOf(
저는 adapter는 ViewModel에 넣지않고 진행했기 때문에 이위치에 있어야 동작할 것 같습니다..!

2019-09-20 06:44 UTC, wswon commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/view/coin/CoinListActivity.kt
> +    private fun setTabPager(marketList: List<MarketResponse>) {
석준님의 CoinHelper를 참고해서 CoinRecyclerViewAdapter  클래스를 삭제하고, 만들어보았습니다.!
ViewModel에서 setTabPager함수를 구현하게 되면 Adapter를 ViewModel에 넣어야하는데 
참고한 CoinHelper 코드가 adapter는 Observable 변수로 넣지 않더라고요

2019-09-20 06:46 UTC, wswon commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/base/BaseViewModel.kt
> +abstract class BaseViewModel :
14603df 감사합니다.

2019-09-20 06:56 UTC, ganghee commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/view/coin/CoinListActivity.kt
> +        ).apply {
네네 이해했습니다!
함수 호출을 view에서 한 이유를 알 수 있을까요?

2019-09-20 06:57 UTC, ganghee commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/view/coin/adapter/holder/CoinViewHolder.kt
> +            executePendingBindings()
네네 답변 감사합니다.

2019-09-20 07:00 UTC, wswon commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/view/coin/CoinListActivity.kt
> +        ).apply {
이유는
```
 { marketList->
                           setTabPager(marketList)
 }
```
이 부분이 higher order funtion을 사용 해서 callback 으로 marketList를 받아 오는 건데요
여기서 marketList를 받아와야 setTabPager를 할 수 있게 설계되어있어서 입니다.

2019-09-20 07:01 UTC, ganghee commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/view/coin/CoinListActivity.kt
> +        ).apply {
아 네네 이해했습니다!

2019-09-20 14:04 UTC, BeokBeok requested changes
안녕하세요. 스터디 2기 강현석이라고 합니다.
부족하지만 잘 부탁드립니다. 😅

2019-09-20 14:04 UTC, BeokBeok commented on wswon/AndroidArchitectureStudy/app/build.gradle
> +    implementation "com.android.support:appcompat-v7:28.0.0"
해당 라이브러리는 제거해주세요.

2019-09-20 14:04 UTC, BeokBeok commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/base/BaseViewModel.kt
> +abstract class BaseViewModel :
class header 관련 컨벤션을 지켜주세요.
https://kotlinlang.org/docs/reference/coding-conventions.html#class-header-formatting

2019-09-20 14:04 UTC, BeokBeok commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/base/BaseViewModel.kt
> +    override fun onCleared() {
해당 함수는 사용하지 않는 것으로 보입니다.
제거해주세요.

2019-09-20 14:04 UTC, BeokBeok commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/data/repository/CoinRepositoryImp.kt
> +class CoinRepositoryImp private constructor(
```suggestion
class CoinRepositoryImpl private constructor(
```
l 까지 붙여주세요

2019-09-20 14:04 UTC, BeokBeok commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/data/repository/CoinRepositoryImp.kt
> +    private val coinRemoteDataSource: CoinRemoteDataSource?
nullable 처리한 이유가 있나요?

2019-09-20 14:04 UTC, BeokBeok commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/data/repository/CoinRepositoryImp.kt
> +        coinRemoteDataSource?.let {
immutable 변수 null check는 let보다 if 문 사용을 권장합니다.
https://medium.com/@elye.project/kotlin-dont-just-use-let-7e91f544e27f

2019-09-20 14:04 UTC, BeokBeok commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/data/source/CoinRemoteDataSourceImp.kt
> +            instance ?: synchronized(this) {
synchronized 를 사용하신 이유가 있을까요?

2019-09-20 14:04 UTC, BeokBeok commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/ext/RecyclerViewExt.kt
> +@BindingAdapter(value = ["replaceAll"])
하나만 사용하시는 경우에는 대괄호가 없어도 됩니다.

2019-09-20 14:04 UTC, BeokBeok commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/ext/RecyclerViewExt.kt
> +        list?.let { tickerList ->
immutable 변수의 null check 는 let 보다 if 문 사용을 권장합니다.
https://medium.com/@elye.project/kotlin-dont-just-use-let-7e91f544e27f

2019-09-20 14:04 UTC, BeokBeok commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/util/Injection.kt
> +        val upbitUrl = "https://api.upbit.com"
상수는 const val 로 사용해주세요.

2019-09-20 14:04 UTC, BeokBeok commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/util/Injection.kt
> +        RetrofitInstance.getInstance<UpbitApi>(upbitUrl)?.let {
RetrofitInstance.getInstance<UpbitApi>(upbitUrl) 값이 null 인 경우가 있나요?

2019-09-20 14:04 UTC, BeokBeok commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/view/coin/CoinListActivity.kt
> +    private lateinit var coinListViewModel: CoinListViewModel
lateinit 대신 lazy를 사용해주세요.

2019-09-20 14:04 UTC, BeokBeok commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/view/coin/CoinListActivity.kt
> +            adapter = object : FragmentStatePagerAdapter(
FragmentPagerAdapter 대신 FragmentStatePagerAdapter를 사용하신 이유가 있나요?

2019-09-20 14:04 UTC, BeokBeok commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/view/coin/CoinListActivity.kt
> +                        marketList
데이터가 많은 경우, 시퀀스로 변환하여 사용하시는 것을 권장합니다.

2019-09-20 14:04 UTC, BeokBeok commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/view/coin/CoinListFragment.kt
> +    private lateinit var coinListViewModel: CoinListViewModel
lateinit 대신 lazy를 사용해주세요.

2019-09-20 14:04 UTC, BeokBeok commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/view/coin/CoinListFragment.kt
>          binding = DataBindingUtil.inflate(inflater, R.layout.fragment_coinlist, container, false)
함수 관련 컨벤션을 따르는 것을 권장합니다.
https://kotlinlang.org/docs/reference/functions.html#named-arguments

2019-09-20 14:04 UTC, BeokBeok commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/view/coin/CoinListFragment.kt
> +                layoutManager = LinearLayoutManager(requireContext())
layoutManager 는 xml에서 속성값으로 설정 가능합니다.

2019-09-20 14:04 UTC, BeokBeok commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/view/coin/CoinListFragment.kt
> +        super.onPause()
super.onPause() 를 맨 마지막에 호출해주세요.

2019-09-20 14:04 UTC, BeokBeok commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/viewmodel/CoinListViewModel.kt
> +    var marketList = ObservableField<List<MarketResponse>>()
val 로 변경해주세요.

2019-09-20 14:04 UTC, BeokBeok commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/viewmodel/CoinListViewModel.kt
> +            marketNameList.joinToString(","),
joinToString 함수의 디폴트 파라미터는 콤마이므로, 
콤마를 사용하시는 경우에는 파라미터 생략이 가능합니다.

2019-09-20 15:03 UTC, wswon commented on wswon/AndroidArchitectureStudy/app/build.gradle
> +    implementation "com.android.support:appcompat-v7:28.0.0"
3213d22  제거했습니다.

2019-09-20 15:04 UTC, wswon commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/base/BaseViewModel.kt
> +    override fun onCleared() {
b231af4  제거했습니다.

2019-09-20 15:05 UTC, wswon commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/data/repository/CoinRepositoryImp.kt
> +class CoinRepositoryImp private constructor(
4927c69 class name을 refactor 했습니다.

2019-09-20 15:08 UTC, wswon commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/data/repository/CoinRepositoryImp.kt
> +    private val coinRemoteDataSource: CoinRemoteDataSource?
그전에 retrofit Instance api를 nullable 하게 받았었는데,
RemoteDataSource의 인자인 retrofit instance api는 Not null로 받다보니,
RemoteDataSource는 nullable로 해야만 하는 상황이었습니다.

지금은 api를 생성하는 부분에서 반환값을 not null로 변경하고,
그에따른 관련 내용을 전부 수정하였습니다.

ad30990

2019-09-20 15:09 UTC, wswon commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/data/repository/CoinRepositoryImp.kt
> +        coinRemoteDataSource?.let {
89fb582 몰랐던 내용인데 감사합니다.

2019-09-20 15:09 UTC, wswon commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/ext/RecyclerViewExt.kt
> +@BindingAdapter(value = ["replaceAll"])
097daf1  변경하였습니다.

2019-09-20 15:09 UTC, wswon commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/ext/RecyclerViewExt.kt
> +        list?.let { tickerList ->
89fb582 반영하였습니다.

2019-09-20 15:10 UTC, wswon commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/util/Injection.kt
> +        val upbitUrl = "https://api.upbit.com"
e709209 변경하였습니다.

2019-09-20 15:14 UTC, wswon commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/util/Injection.kt
> +        RetrofitInstance.getInstance<UpbitApi>(upbitUrl)?.let {
시작은 Api의 연결상태를 미리 알고 connect 상태 변수를 두고싶어서 굳이 nullable 하게 받은 것 같습니다. 
현재는 connect상태 변수는 유지하고, not null 타입으로 변경했습니다.
ad30990

2019-09-20 15:15 UTC, wswon commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/view/coin/CoinListActivity.kt
> +    private lateinit var coinListViewModel: CoinListViewModel
e8252a5  by lazy 가 가능해보이는 변수는 전부 변경했습니다.

2019-09-20 15:16 UTC, wswon commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/view/coin/CoinListActivity.kt
> +                        marketList
127dada 시퀀스로 변환한다는게 이게 맞는지 확인 부탁드립니다

2019-09-20 15:17 UTC, wswon commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/view/coin/CoinListFragment.kt
> +    private lateinit var coinListViewModel: CoinListViewModel
e8252a5 by lazy 가 가능해보이는 변수는 전부 변경했습니다.

2019-09-20 15:17 UTC, wswon commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/view/coin/CoinListFragment.kt
>          binding = DataBindingUtil.inflate(inflater, R.layout.fragment_coinlist, container, false)
5425c83 개행을 말씀하신게 맞는지 확인 부탁드립니다.

2019-09-20 15:18 UTC, wswon commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/view/coin/CoinListFragment.kt
> +                layoutManager = LinearLayoutManager(requireContext())
5d4859c xml에서 설정해보았습니다.

2019-09-20 15:18 UTC, wswon commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/view/coin/CoinListFragment.kt
> +        super.onPause()
903959f method call 순서를 변경했습니다.

2019-09-20 15:19 UTC, wswon commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/viewmodel/CoinListViewModel.kt
> +    var marketList = ObservableField<List<MarketResponse>>()
8bf1be5  val로 변경했습니다.

2019-09-20 15:19 UTC, wswon commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/viewmodel/CoinListViewModel.kt
> +            marketNameList.joinToString(","),
fbf0010 default parameter가 있는지 전혀 몰랐네요.. 감사합니다.

2019-09-20 15:23 UTC, wswon commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/view/coin/CoinListActivity.kt
> +            adapter = object : FragmentStatePagerAdapter(
별생각 없이 원래 사용하던 것을 사용했던것 같습니다.

https://mrgamza.tistory.com/215 이런 링크를 통해 찾아보았는데,
CoinHelper자체가 fragment를 동적으로 변환시키지 않기때문에
FragmentPagerAdapter가 좀더 적절한가? 하는 생각이 드는데
맞을까요?

2019-09-20 15:27 UTC, wswon commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/data/source/CoinRemoteDataSourceImp.kt
> +            instance ?: synchronized(this) {
Thread safe lazy initialization + Double-checked locking
를 보고 다중 스레드에 대해 동기화 시켜주어 한번만 생성됨이 보장되니까
이렇게 사용했습니다. 혹시 잘못된 방법일까요?

2019-09-21 00:05 UTC, BeokBeok commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/view/coin/CoinListActivity.kt
> +                        marketList
asSequence를 사용하여 변환해주시면 됩니다.
```suggestion
                        marketList.asSequence()
```

2019-09-21 00:05 UTC, BeokBeok commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/view/coin/CoinListActivity.kt
> +            adapter = object : FragmentStatePagerAdapter(
네 맞습니다.

2019-09-21 00:05 UTC, BeokBeok commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/data/source/CoinRemoteDataSourceImp.kt
> +            instance ?: synchronized(this) {
companion object는 thread safe 한 것으로 알고 있습니다.

> A companion object is initialized when the class is loaded (typically the first time it's referenced by other code that is being executed), in a thread-safe manner.

[companion-objects](https://kotlinlang.org/docs/tutorials/kotlin-for-py/objects-and-companion-objects.html#companion-objects)

2019-09-21 14:47 UTC, wswon commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/data/source/CoinRemoteDataSourceImp.kt
> +            instance ?: synchronized(this) {
b2a890e 감사합니다. lazy init 으로 변경했습니다.

2019-09-21 14:53 UTC, wswon commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/view/coin/CoinListActivity.kt
> +            adapter = object : FragmentStatePagerAdapter(
2be3f24 FragmentTabPageAdapter로 변경했습니다.

2019-09-21 14:55 UTC, wswon commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/view/coin/CoinListActivity.kt
> +                        marketList
408841e asSequece를 사용하여 처리 해보았습니다.

2019-09-21 15:40 UTC, BeokBeok approved these changes
LGTM:ok_hand:

2019-09-22 02:59 UTC, ganghee approved these changes

2019-09-22 11:43 UTC, merged