Class03/ganghee
sjjeong/GoogryAndroidArchitecutreStudy pull request #209
Opened 2019-09-19 11:13 UTC by ganghee

아직 부족한 점이 많습니다.
많은 리뷰 감사하겠습니다.

2019-09-19 11:17 UTC, sjjeong commented
@ganghee 
PR 이름이랑 Label을 변경해주세요

2019-09-19 15:40 UTC, wswon commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/data/UpbitRepository.kt
> +        UpbitRemoteDataSourceImpl.getTickers(marketList)
getMarkets()는
`upbitRemoteDataSource.getMarkets()`
이렇게 접근하는데
getTiker()는
`UpbitRemoteDataSourceImpl.getTickers(marketList)`
이렇게 접근하는게
생성자로 주입받은 객체를 getTikcers에서는 사용하지 않고 있어서
의미가 안맞는 것 같아요.

2019-09-19 15:40 UTC, wswon commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/network/UpbitRemoteDataSource.kt
> +interface UpbitRemoteDataSource {
Retrofit call을 만드는 UpbitApi를 RemoteDataSource라고 선언을 변경해주신 이유가 있나요?

2019-09-19 15:40 UTC, wswon commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/ui/MainActivity.kt
> +        with(MainViewModel(ViewPagerAdapter(supportFragmentManager,4))){
`ViewPagerAdapter(supportFragmentManager,4)`
ViewPagerAdpater를 두번 생성하는것 같아요.

2019-09-19 15:40 UTC, wswon commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/ui/MainActivity.kt
>          binding.viewPager.adapter = ViewPagerAdapter(supportFragmentManager, num_fragment = 4)
` binding.viewPager.adapter = ViewPagerAdapter(supportFragmentManager, num_fragment = 4)`
두번째 인자인 tab갯수를 동적으로 넣거나, 아예 탭 갯수 받는걸 빼거나 해서 처리할 수 있지 않을까 싶습니다

2019-09-19 15:40 UTC, wswon commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/ui/MainActivity.kt
>          binding = DataBindingUtil.setContentView(this,R.layout.activity_main)
```suggestion
        binding = DataBindingUtil.setContentView(this, R.layout.activity_main)
```

2019-09-20 00:28 UTC, ganghee commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/network/UpbitRemoteDataSource.kt
> +interface UpbitRemoteDataSource {
서버에서  데이터를 가져오는 객체이기 때문에 remotedatasource 라고 명명했습니다.
그리고 패키지 이름도 변경해 보았습니다.

2019-09-20 04:43 UTC, ganghee commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/ui/MainActivity.kt
> +        with(MainViewModel(ViewPagerAdapter(supportFragmentManager,4))){
with 키워드는 단순히 객체에 접근하여 값을 반환하는 것으로 알고 있습니다.
어느 부분에서 2번 생성하는 것인지 알려 주시면 감사하겠습니다.
그리고 with 보다는 run 키워드를 써서 null에 대한 안정성을 보안 하였습니다.

2019-09-20 04:43 UTC, ganghee commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/ui/MainActivity.kt
>          binding.viewPager.adapter = ViewPagerAdapter(supportFragmentManager, num_fragment = 4)
네!! 두번째 파라미터를 삭제 하였습니다.

2019-09-20 04:48 UTC, ganghee commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/data/UpbitRepository.kt
> +        UpbitRemoteDataSourceImpl.getTickers(marketList)
제가 아직 객체에 대한 이해가 부족합니다.
생성자로 주입받는 객체가 무엇인지 알 수 있을까요?
그리고 의미가 안 맞다는 것이 어떤 것인지 물어보고 싶습니다.

2019-09-20 04:50 UTC, wswon commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/ui/MainActivity.kt
>          binding.viewPager.adapter = ViewPagerAdapter(supportFragmentManager, num_fragment = 4)
```
 with(MainViewModel(ViewPagerAdapter(supportFragmentManager,4))){
            binding.vm = this
            initView()
        }
        configureMainTab()
    }
    private fun configureMainTab() {

        binding.viewPager.adapter = ViewPagerAdapter(supportFragmentManager, num_fragment = 4)
```
를 이렇게 해야하지 않나 하는 말이었습니다.
ViewPagerAdapter 생성자를 두번 만들고 있어서요.
with 안에서 ViewPagerAdapter constructor를 호출 하는것도 
ViewModel 의 인자로 생성을 하고있는거라서요.
```
val viewPagerAdapter = ViewPagerAdapter(supportFragmentManager,4)
 with(MainViewModel(viewPagerAdapter )){
            binding.vm = this
            initView()
        }
        configureMainTab()
    }
    private fun configureMainTab() {

        binding.viewPager.adapter = viewPagerAdapter
```
binding.viewPager에 셋팅한 어댑터랑
MainViewModel에 셋팅한 어댑터가 서로 다른객체가 되는거 같아요.

2019-09-20 04:58 UTC, wswon commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/data/UpbitRepository.kt
> +        UpbitRemoteDataSourceImpl.getTickers(marketList)
```
class UpbitRepository (
    private val upbitRemoteDataSource: UpbitRemoteDataSource
){
```
여기서 Interface 타입으로 받은  private val upbitRemoteDataSource 를 사용해서 
UpbitRepository 에서는 remoteDataSource를 접근하는 것인데,
`UpbitRemoteDataSourceImpl.getTickers(marketList)` 이렇게 interface 구현체에 직접 접근하고 있어서
리뷰를 달았습니다.
위의 getMarket처럼,
`upbitRemoteDataSource.getTickers("your_param")` 
이렇게 호출하게 만들어야 하지 않을까 싶어서요

2019-09-20 12:23 UTC, ganghee commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/ui/MainActivity.kt
>          binding.viewPager.adapter = ViewPagerAdapter(supportFragmentManager, num_fragment = 4)
아 네네 이해했습니다. 2번 생성한게 맞네요...
[MainActicity](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/209/commits/0f21415e9804f389611601a736519789abbeacb5)

2019-09-20 12:27 UTC, wswon submitted a review, later dismissed
고생하셨습니다 👍

2019-09-20 12:30 UTC, ganghee commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/ui/MainActivity.kt
>          binding = DataBindingUtil.setContentView(this,R.layout.activity_main)
convention에 맞게 하였습니다.
[MainActivity](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/209/commits/55495a04e1a486cab67304d9e44bd15494f40ae9)

2019-09-20 13:38 UTC, BeokBeok requested changes
안녕하세요. 스터디 2기 강현석이라고 합니다.
부족하지만 잘 부탁드립니다. :sweat_smile:

2019-09-20 13:38 UTC, BeokBeok commented on ganghee/MyStudy2/app/build.gradle
>      implementation 'androidx.legacy:legacy-support-v4:1.0.0'
불필요한 라이브러리로 보입니다.
제거해주세요.

2019-09-20 13:38 UTC, BeokBeok commented on ganghee/MyStudy2/app/build.gradle
> +    implementation 'androidx.appcompat:appcompat:1.1.0'
material 에 해당 라이브러리가 포함되어있습니다.
https://mvnrepository.com/artifact/com.google.android.material/material/1.1.0-alpha10

제거해주세요.

2019-09-20 13:38 UTC, BeokBeok commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/adapter/ViewPagerAdapter.kt
>      FragmentStatePagerAdapter(fm, BEHAVIOR_RESUME_ONLY_CURRENT_FRAGMENT) {
FragmentPagerAdapter 와 비교했을 때 FragmentStatePagerAdapter를 사용하신 이유가 있을까요?

2019-09-20 13:38 UTC, BeokBeok commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/adapter/ViewPagerAdapter.kt
> +    override fun getPageTitle(position: Int): CharSequence? {
구현부에 return 이 하나인 경우에는 = 을 사용하여 정리할 수 있습니다.

2019-09-20 13:38 UTC, BeokBeok commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/data/UpbitRepository.kt
>                  it.joinToString(",") {
joinToString 함수의 default 파라미터는 콤마이므로, 
콤마를 사용하실 것이라면 파라미터 생략이 가능합니다.

2019-09-20 13:38 UTC, BeokBeok commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/data/remote/UpbitRemoteDataSource.kt
> +interface UpbitRemoteDataSource {
RemoteDataSource 보다는 Service 에 가까워보입니다.

2019-09-20 13:38 UTC, BeokBeok commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/data/remote/UpbitRemoteDataSourceImpl.kt
> +    private val RETROFIT: UpbitRemoteDataSource = Retrofit.Builder()
변수가 상수일 경우에만 대문자를 사용합니다.
https://kotlinlang.org/docs/reference/coding-conventions.html#property-names

2019-09-20 13:38 UTC, BeokBeok commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/ui/MainActivity.kt
> +            initView()
view를 초기화하는 부분은 viewmodel 이 아닌 view 에서 해주세요.

2019-09-20 13:38 UTC, BeokBeok commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/ui/UpbitFragment.kt
> +    private var tickerAdapter= TickerAdapter()
val 로 변경해주세요.

2019-09-20 13:38 UTC, BeokBeok commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/ui/UpbitFragment.kt
> +    private lateinit var upbitViewModel: UpbitViewModel
lateinit 대신 lazy로 초기화주세요

2019-09-20 13:38 UTC, BeokBeok commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/viewmodel/MainViewModel.kt
> +class MainViewModel(
해당 뷰모델은 불필요해보입니다. 제거해주세요.

2019-09-20 13:38 UTC, BeokBeok commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/viewmodel/UpbitViewModel.kt
>      @SuppressLint("CheckResult")
해당 annotation 을 추가해주신 이유가 있을까요?

2019-09-21 01:51 UTC, ganghee commented on ganghee/MyStudy2/app/build.gradle
>      implementation 'androidx.legacy:legacy-support-v4:1.0.0'
네 제거 하였습니다.

2019-09-21 01:51 UTC, ganghee commented on ganghee/MyStudy2/app/build.gradle
> +    implementation 'androidx.appcompat:appcompat:1.1.0'
네 제거하였습니다.

2019-09-21 01:53 UTC, ganghee commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/adapter/ViewPagerAdapter.kt
>      FragmentStatePagerAdapter(fm, BEHAVIOR_RESUME_ONLY_CURRENT_FRAGMENT) {
FragmentStatePagerAdapter는 인스턴스가 완전히 제거 되어 메모리 관리에 좋다고 알고 있습니다
하지만 프래그먼트가 유동적으로 바뀌지 않아 FragmentPagerAdapter가 좋을 것 같네요~~

2019-09-21 03:51 UTC, ganghee commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/adapter/ViewPagerAdapter.kt
> +    override fun getPageTitle(position: Int): CharSequence? {
네네 이 부분을 놓쳤네요

2019-09-21 23:47 UTC, ganghee commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/ui/UpbitFragment.kt
> +    private var tickerAdapter= TickerAdapter()
네 val로 고쳤습니다.

2019-09-22 02:43 UTC, ganghee commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/viewmodel/UpbitViewModel.kt
>      @SuppressLint("CheckResult")
결과 값을 반환하지 않아 어노테이션을 썼습니다. 
구글링을 해보니 CompositeDisposable을 사용하여 객체로 반환하는 방법이 있더군요
그걸 다시 사용해보았습니다.

2019-09-22 03:09 UTC, ganghee commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/data/UpbitRepository.kt
>                  it.joinToString(",") {
`it.joinToString()` 를 사용하면 data가 안나오는데 혹시 다른 방법 있을까요?

2019-09-22 03:10 UTC, ganghee commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/data/remote/UpbitRemoteDataSource.kt
> +interface UpbitRemoteDataSource {
service로 수정하였습니다.
[UpbitService](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/209/commits/da3752577a604a04cb558e197dd6a47fb8ae1921)

2019-09-22 03:11 UTC, ganghee commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/data/remote/UpbitRemoteDataSourceImpl.kt
> +    private val RETROFIT: UpbitRemoteDataSource = Retrofit.Builder()
소문자로 변경하였습니다.
[UpbitRemoteDataSource](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/209/commits/3f941ebfb8fa900cc414016f18fc07cd563a2726)

2019-09-22 06:51 UTC, ganghee commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/ui/UpbitFragment.kt
> +    private lateinit var upbitViewModel: UpbitViewModel
네 lazy로 초기화 하였습니다.

2019-09-23 07:10 UTC, ganghee commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/ui/MainActivity.kt
> +            initView()
view에서 초기화 하였습니다.
[MainActivity](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/209/commits/f8699feec49b152c4725a566c2ddb1380a5e829d)

2019-09-23 07:12 UTC, ganghee commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/viewmodel/MainViewModel.kt
> +class MainViewModel(
네 제거 하였습니다. MainActivity에서 구현하였습니다.
[MainActivity](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/209#discussion_r326885794)

2019-09-23 09:11 UTC, BeokBeok commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/data/UpbitRepository.kt
>                  it.joinToString(",") {
`it.joinToString { }` 이렇게 쓰시면 될 것 같습니다.

2019-09-23 09:12 UTC, BeokBeok commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/ui/UpbitFragment.kt
> +    private lateinit var upbitViewModel: UpbitViewModel
link 가 잘못 된 것 같습니다.

2019-09-23 09:12 UTC, BeokBeok commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/viewmodel/MainViewModel.kt
> +class MainViewModel(
link 가 잘못 된 것 같습니다.

2019-09-23 09:12 UTC, BeokBeok commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/viewmodel/UpbitViewModel.kt
>      @SuppressLint("CheckResult")
CompositeDisposable 을 clear 혹은 dispose 처리도 해주세요. #

2019-09-23 10:01 UTC, ganghee commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/ui/UpbitFragment.kt
> +    private lateinit var upbitViewModel: UpbitViewModel
다시 올렸습니다.

2019-09-23 10:02 UTC, ganghee commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/viewmodel/MainViewModel.kt
> +class MainViewModel(
다시 올렸습니다.

2019-09-23 10:14 UTC, ganghee commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/data/UpbitRepository.kt
>                  it.joinToString(",") {
`it.joinToString(",") {it->
                    it.market }`

2019-09-23 11:15 UTC, ganghee commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/viewmodel/UpbitViewModel.kt
>      @SuppressLint("CheckResult")
네 추가하였습니다.
[UpbitViewModel](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/209/commits/91ac009d59bb2298c1e82e628b826c4bc2407ff2)

2019-09-23 11:27 UTC, BeokBeok commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/data/UpbitRepository.kt
>                  it.joinToString(",") {
확인해보니 default 파라미터는 `", "` 이여서
```
KRW-BTC, KRW-DASH
```
로 변환되고 있습니다.

해서, 기존에 처리하시던 방식으로 하시는 것이 좋을 것 같습니다.

2019-09-23 11:27 UTC, BeokBeok commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/viewmodel/UpbitViewModel.kt
>      @SuppressLint("CheckResult")
onCleared 함수를 오버라이딩 하시어 처리해주세요.

2019-09-23 11:39 UTC, ganghee commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/viewmodel/UpbitViewModel.kt
>      @SuppressLint("CheckResult")
viewModel의 생명주기에 대해 부족했네요! 감사합니다~
[UpbitViewModel](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/209/commits/71060d37a76848008bc1f51f0e7ea85bddf4c4ed)

2019-09-23 11:39 UTC, ganghee commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/data/UpbitRepository.kt
>                  it.joinToString(",") {
네 감사합니다

2019-09-23 11:45 UTC, BeokBeok commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/viewmodel/UpbitViewModel.kt
>      @SuppressLint("CheckResult")
clear 를 먼저 호출 하신 후에, onCleared 를 호출해주세요.

2019-09-23 12:15 UTC, ganghee commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/viewmodel/UpbitViewModel.kt
>      @SuppressLint("CheckResult")
onPause를 먼저 호출 해서 clear 한 후
onCleared 에서 dispose 하게 하였습니다.
이렇게 하는 것이 맞을까요?
[UpbitViewModel](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/209/commits/b66f0c03d1d145d8188686fa749d7d9cfc38cb21)

2019-09-23 12:34 UTC, BeokBeok commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/viewmodel/UpbitViewModel.kt
>      @SuppressLint("CheckResult")
onPause 함수는 제거해주세요.

제 의도를 애매모호하게 작성 한 것 같네요ㅠ
제가 말씀드린 것은 CompositeDisposable 을 clear 혹은 dispose 처리를 먼저 하신 후에
부모 ViewModel의 onCleared 함수를 호출하는 것이었습니다.
```
override fun onCleared() {
    if(!compositeDisposable.isDisposed) {
        compositeDisposable.dispose()
    }
    super.onCleared()
}
```

2019-09-23 12:52 UTC, ganghee commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/viewmodel/UpbitViewModel.kt
>      @SuppressLint("CheckResult")
아 네네 이해했습니다!! 감사합니다~
[UpbitViewPager](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/209/commits/84c9f73c7ea4edfba528da168837bbe4f3750edd)

2019-09-23 13:05 UTC, BeokBeok approved these changes
LGTM:ok_hand:

2019-09-24 01:10 UTC, sjjeong approved these changes
BaseClass만드는 것을 포함해서 7주차 과제 진행해주세요

2019-09-24 01:14 UTC, merged