1주차 과제 PR입니다
sjjeong/GoogryAndroidArchitecutreStudy pull request #21
Opened 2019-05-01 16:06 UTC by namjackson

코틀린을 아직 잘못쓰는거 같습니다 ㅠㅠ
좀늦게 올린거같네요.
많은 리뷰해주세요!

2019-05-02 04:59 UTC, GeoN5 requested changes

2019-05-02 04:59 UTC, GeoN5 commented on namjackson/ArchStudy/app/src/main/java/com/namjackson/archstudy/data/repository/UpbitRepository.kt
> +        private var instance: UpbitRepository? = null
일부로 nullable하게 선언하신게 아니라면 lateinit 이나 by lazy 형태로 만들면 좋을거 같아요

2019-05-02 04:59 UTC, GeoN5 commented on namjackson/ArchStudy/app/src/main/java/com/namjackson/archstudy/view/CoinListFragment.kt
> +    private var markets: String? = null
이것들도 nullable한 형태보다는 nonnull이 좋을거 같아요

2019-05-02 07:00 UTC, namjackson commented on namjackson/ArchStudy/app/src/main/java/com/namjackson/archstudy/view/CoinListFragment.kt
> +    private var markets: String? = null
nullable 변수는 최대한 피해봐야겟네요!

2019-05-02 07:00 UTC, namjackson commented on namjackson/ArchStudy/app/src/main/java/com/namjackson/archstudy/data/repository/UpbitRepository.kt
> +        private var instance: UpbitRepository? = null
아하 ! lateinit 이나 by lazy 형태만들면 
null 체크 안해도되서 더 짧아지겠네요!

2019-05-02 13:18 UTC, Hoyuo reviewed
전체적으로 formatter를 한번 돌려주세요

2019-05-02 13:18 UTC, Hoyuo commented on namjackson/ArchStudy/app/src/main/java/com/namjackson/archstudy/view/CoinListFragment.kt
> +    private var adapter: CoinListAdapter? = null
null로 초기화한 이유가 있을까요?

2019-05-02 13:18 UTC, Hoyuo commented on namjackson/ArchStudy/app/src/main/java/com/namjackson/archstudy/view/MainActivity.kt
>          Log.d("test","test")
의미없는 태그 보다는 다른 태그가 어떨까여?

2019-05-02 13:18 UTC, Hoyuo commented on namjackson/ArchStudy/app/src/main/java/com/namjackson/archstudy/view/adapter/CoinListAdapter.kt
> + /*
불필요한 부분이라면 삭제하는것이 좋을꺼같습니다

2019-05-02 13:18 UTC, Hoyuo commented on namjackson/ArchStudy/app/src/main/java/com/namjackson/archstudy/network/RetrofitCreator.kt
> +            .addCallAdapterFactory(RxJava2CallAdapterFactory.create())
`CallAdapter`를 추가 하셨는데 `Call`로 진행하신 이유가 있나요?

2019-05-02 16:04 UTC, namjackson commented on namjackson/ArchStudy/app/src/main/java/com/namjackson/archstudy/network/RetrofitCreator.kt
> +            .addCallAdapterFactory(RxJava2CallAdapterFactory.create())
오 예리하시네요 
rx사용하려다, 코틀린과 rx가 익숙치가 않아서 사용하지않았는데  빼는 걸깜 빡했네여!
지금은 주석처리만 해놓을게요!

2019-05-02 16:04 UTC, namjackson commented on namjackson/ArchStudy/app/src/main/java/com/namjackson/archstudy/view/CoinListFragment.kt
> +    private var adapter: CoinListAdapter? = null
아뇨! 코틀린에 null메카니즘이 아직 익숙치않네요! 
리뷰감사합니다!

2019-05-03 00:26 UTC, Hoyuo requested changes

2019-05-03 00:26 UTC, Hoyuo commented on namjackson/ArchStudy/app/src/main/java/com/namjackson/archstudy/view/CoinListFragment.kt
> +    private lateinit var mTimer: Timer;
멤버변수 m 표기법은 java 스타일 입니다

2019-05-03 00:26 UTC, Hoyuo commented on namjackson/ArchStudy/app/src/main/java/com/namjackson/archstudy/network/RetrofitCreator.kt
> +import retrofit2.adapter.rxjava2.RxJava2CallAdapterFactory
불필요한 import는 삭제해 주세요

2019-05-03 09:38 UTC, namjackson commented on namjackson/ArchStudy/app/src/main/java/com/namjackson/archstudy/view/CoinListFragment.kt
> +    private lateinit var mTimer: Timer;
아하 그렇군요 
코틀린 사용시엔 주의할게요!

2019-05-03 09:39 UTC, namjackson commented on namjackson/ArchStudy/app/src/main/java/com/namjackson/archstudy/network/RetrofitCreator.kt
> +import retrofit2.adapter.rxjava2.RxJava2CallAdapterFactory
네 !

2019-05-03 09:54 UTC, Hoyuo submitted a review, later dismissed

2019-05-03 23:41 UTC, GeoN5 commented on namjackson/ArchStudy/app/src/main/java/com/namjackson/archstudy/view/CoinListFragment.kt
> +    private lateinit var timer: Timer;
세미콜론은 없어도 될것 같아요

2019-05-03 23:44 UTC, GeoN5 submitted a review, later dismissed
CoinListFragment에서 timer변수 뒤에 ;는 필요 없으니 ;만 지우면 될거같아요

2019-05-04 06:45 UTC, sjjeong requested changes

2019-05-04 06:45 UTC, sjjeong commented on namjackson/ArchStudy/app/build.gradle
> +//    kapt "com.android.databinding:compiler:3.3.0"
사용하지 않는 코드는 제거해주세요.

2019-05-04 06:45 UTC, sjjeong commented on namjackson/ArchStudy/app/src/main/java/com/namjackson/archstudy/data/repository/UpbitRepository.kt
> +                }?.map {
joinToString()에 transform으로 던지면 map이 필요하지 않습니다.

2019-05-04 06:45 UTC, sjjeong commented on namjackson/ArchStudy/app/src/main/java/com/namjackson/archstudy/data/repository/UpbitRepository.kt
> +                    it.market.contains((baseCurrency).toRegex())
baseCurrency로 contain해서 찾으면 나중에 base가 btc일때 krw-btc도 검색됩니다.
업비트는 baseCurrency가 앞에서 시작하니까 startsWith()로 체크하는게 좋을 것 같습니다.

2019-05-04 06:45 UTC, sjjeong commented on namjackson/ArchStudy/app/src/main/java/com/namjackson/archstudy/data/repository/UpbitRepository.kt
> +                }?.joinToString().toString())
toString()이 null때문에 쓰셨는데 null일때는 다른처리를 해주는게 좋을 것 같습니다.

2019-05-04 06:45 UTC, sjjeong commented on namjackson/ArchStudy/app/src/main/java/com/namjackson/archstudy/view/adapter/CoinListAdapter.kt
> +        var binding = DataBindingUtil.inflate<ItemCoinListBinding>(
val로 변경해주세요.

2019-05-04 06:45 UTC, sjjeong commented on namjackson/ArchStudy/app/src/main/java/com/namjackson/archstudy/view/CoinListFragment.kt
> +        timer.cancel();
파괴 시점에서는 super를 뒤에 불러주는게 좋습니다.

2019-05-04 10:00 UTC, namjackson commented on namjackson/ArchStudy/app/src/main/java/com/namjackson/archstudy/data/repository/UpbitRepository.kt
> +                    it.market.contains((baseCurrency).toRegex())
아하 BTC 나 ETH 등의 케이스가 있네요! 수정하겠습니다!

2019-05-04 10:00 UTC, namjackson commented on namjackson/ArchStudy/app/src/main/java/com/namjackson/archstudy/data/repository/UpbitRepository.kt
> +                }?.joinToString().toString())
네! 다른처리로 변경하겟습니다!

2019-05-04 10:10 UTC, namjackson commented on namjackson/ArchStudy/app/src/main/java/com/namjackson/archstudy/data/repository/UpbitRepository.kt
> +                }?.map {
감사합니다 ! 더 간결한 방법이있었네요!

2019-05-04 12:44 UTC, Hoyuo approved these changes

2019-05-04 14:40 UTC, sjjeong approved these changes

2019-05-05 03:46 UTC, merged