HW-6 MVVM 패턴 적용하기
sjjeong/GoogryAndroidArchitecutreStudy pull request #210
Opened 2019-09-20 07:58 UTC by wkdehdlr

MVVM 개념상으로는 이해가 되는데 코드로 구현하려니 어려운점이 많았습니다 ㅠㅠㅠ

2019-09-21 11:13 UTC, zozero94 reviewed
앱 실행이 안됩니다 확인해주세여

2019-09-21 11:13 UTC, zozero94 commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/tasks/UpbitBindingAdapter.kt
> +object UpbitBindingAdapter {
해당클래스는 어디서 사용되는건가요?? 찾지 못하였습니다

2019-09-21 11:13 UTC, zojae031 commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/tasks/UpbitFragment.kt
> +        upbitViewModel = UpbitViewModel(Repository)
늦은초기화를 없애고
```kotlin
val marketName = arguments?.get("MARKET_NAME").toString()
        UpbitViewModel(Repository).apply {
            loadUpbitMarket(marketName)
        }.also { binding.viewModel = it }
```

형태로 변경 할 수 있을것 같습니다!
지극히 개인적인 코드 작성방법입니다 참고만 해주세여 ㅎㅎ

2019-09-21 11:13 UTC, zojae031 commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/tasks/UpbitRVAdapter.kt
>      inner class Holder(itemView: MainRvItemBinding) : RecyclerView.ViewHolder(itemView.root) {
저도 지적받은 부분인데 itemView이름을 binding으로 바꾸는게 좋다고 하십니다.
또한 ``binding :MainRvItemBinding``을 전역변수로 두지않고 onCreateViewHolder에서
받아서 사용하는것이 좋다고 합니다.

[``binding`` 필드를 뷰홀더를 만들때 초기화하기 때문에 onBindViewHolder 시점에 holder 의 binding 이 아닌 마지막으로 생성된 binding 인스턴스를 가리킬 가능성이 있습니다. ](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/206/files/1c309b4945826827660c0619fc0e95f72bf72e4a#r326450802)

2019-09-21 11:13 UTC, zojae031 commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/tasks/UpbitViewModel.kt
> +class UpbitViewModel(val repository: Repository) {
private 로 감추어도 될 것 같습니다.

2019-09-21 11:13 UTC, zojae031 commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/tasks/UpbitViewModel.kt
> +                tickerList.set(tickers.map {
저도 이렇게 리스트에 넣어보려하다가 실패하였는데 어떤 원리로 하신건가요??
설명 해주실수 있을까요?

2019-09-23 11:06 UTC, wkdehdlr commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/tasks/UpbitBindingAdapter.kt
> +object UpbitBindingAdapter {
[843cf3b](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/210/commits/843cf3bf680ec44198f3f610e5221aba891cc1dd) 수정했습니다

2019-09-23 11:39 UTC, wkdehdlr commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/tasks/UpbitFragment.kt
> +        upbitViewModel = UpbitViewModel(Repository)
[102048f](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/210/commits/102048f4c771e783ac807123d20386b28c34ffc7) 수정했습니다

2019-09-23 11:39 UTC, wkdehdlr commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/tasks/UpbitRVAdapter.kt
>      inner class Holder(itemView: MainRvItemBinding) : RecyclerView.ViewHolder(itemView.root) {
[7d439e8](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/210/commits/7d439e8e01d1e555654a61ae577d814aae861625) 수정했습니다

2019-09-23 11:41 UTC, wkdehdlr commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/tasks/UpbitViewModel.kt
> +class UpbitViewModel(val repository: Repository) {
[1ae16a8](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/210/commits/1ae16a8e2df1e9e9c5992c63abe9d7580c907f6c) 수정했습니다

2019-09-23 12:27 UTC, wkdehdlr commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/tasks/UpbitViewModel.kt
> +                tickerList.set(tickers.map {
기존 MVP에서는 Fragment에서 Contract.View를 override해서 recyclerview어댑터에 setList해주는 부분이 있었는데요. 그 부분을 들어내면서 뷰모델에서 Observable을 세팅해주는 과정이 들어갔어요. 이 때 기존에는 List를 만들어서 넘겨주었는데 여기서는 List를 만들어서 Observable에 세팅했습니다.

2019-09-24 01:26 UTC, zojae031 commented on wkdehdlr/CoinHelper/app/src/main/res/layout/fragment_coinrecycler.xml
> +        <import type="android.view.View" />
View관련 참조가 없는것 같습니다. 삭제해도 될것같아요

2019-09-24 01:26 UTC, zojae031 commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/tasks/UpbitRVAdapter.kt
> +    inner class Holder(private val binding: MainRvItemBinding) :
inner 명령어 제거가 안되어있습니다.

2019-09-24 05:44 UTC, wkdehdlr commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/tasks/UpbitRVAdapter.kt
> +    inner class Holder(private val binding: MainRvItemBinding) :
[f60c1a2](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/210/commits/f60c1a2aa75f1b407b4a40fb40bf593249f5b7d5) 수정했습니다

2019-09-24 05:48 UTC, wkdehdlr commented on wkdehdlr/CoinHelper/app/src/main/res/layout/fragment_coinrecycler.xml
> +        <import type="android.view.View" />
[58aef48](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/210/commits/58aef48d4145e55b9d2a613a3e23a64853ba1638) 수정했습니다

2019-09-24 06:17 UTC, zozero94 submitted a review, later dismissed
고생하셨습니다.

2019-09-24 07:22 UTC, BeokBeok requested changes
안녕하세요. 스터디 2기 강현석이라고 합니다 ^~^
부족하지만 잘 부탁 드립니다. :sweat_smile:

---

사용하지 않는 파일은 제거해주세요
```
BasePresenter
BaseView
```

2019-09-24 07:22 UTC, BeokBeok commented on wkdehdlr/CoinHelper/app/build.gradle
>      implementation 'androidx.legacy:legacy-support-v4:1.0.0'
제거해주세요.

2019-09-24 07:22 UTC, BeokBeok commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/base/BaseFragment.kt
> +abstract class BaseFragment<B : ViewDataBinding>(private val layoutId: Int) : Fragment() {
LayoutRes annotation 추가해주시면 좋을 것 같습니다.

2019-09-24 07:22 UTC, BeokBeok commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/tasks/UpbitFragment.kt
> +        UpbitViewModel(Repository).apply {
다음과 같이 사용하는 것이 좋을 것 같습니다.
```suggestion
        binding.viewModel = UpbitViewModel(Repository).apply {
            loadUpbitMarket(marketName)
        }
```

2019-09-24 07:22 UTC, BeokBeok commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/tasks/UpbitRVAdapter.kt
> +        return Holder(
= 을 사용하여 중괄호를 정리할 수 있습니다.

2019-09-24 07:22 UTC, BeokBeok commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/tasks/UpbitViewModel.kt
> +    var tickerList = ObservableField<List<UpbitItem>>()
val 로 변경해주세요.

2019-09-24 07:22 UTC, BeokBeok commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/util/BindingAdapters.kt
> +fun RecyclerView.replaceAll(items: ObservableField<List<UpbitItem>>) {
ObservableField 으로 받지 않고 List 로 받을 수 있지 않을까요?

2019-09-24 07:22 UTC, BeokBeok commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/tasks/UpbitFragment.kt
>          //TODO : MARKET_NAME enum으로 빼자
TODO 관련하여 적용해주세요.

2019-09-24 07:27 UTC, wkdehdlr commented on wkdehdlr/CoinHelper/app/build.gradle
>      implementation 'androidx.legacy:legacy-support-v4:1.0.0'
[c790590](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/210/commits/c79059062facd76ab9d2c9262d10f1c778e61b96) 수정했습니다

2019-09-24 07:33 UTC, wkdehdlr commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/base/BaseFragment.kt
> +abstract class BaseFragment<B : ViewDataBinding>(private val layoutId: Int) : Fragment() {
[352a64a](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/210/commits/352a64a45c507926301e15be9ab2f235dde67f42) 수정했습니다. LayoutRes 어노테이션은 처음 접해보는데 용도가 무엇인가요?

2019-09-24 07:36 UTC, wkdehdlr commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/tasks/UpbitFragment.kt
> +        UpbitViewModel(Repository).apply {
[8df16c6](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/210/commits/8df16c65176af7a83b6e1ac0789bc77681fdb063) 수정했습니다

2019-09-24 07:38 UTC, wkdehdlr commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/tasks/UpbitRVAdapter.kt
> +        return Holder(
[cffc099](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/210/commits/cffc099291ea8833fdfa5aac02e9d3f6dfa438e8) 수정했습니다

2019-09-24 07:39 UTC, wkdehdlr commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/tasks/UpbitViewModel.kt
> +    var tickerList = ObservableField<List<UpbitItem>>()
[7cb7037](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/210/commits/7cb7037378ea63855c0e94f6862b776313928cf0) 수정했습니다

2019-09-24 07:48 UTC, wkdehdlr commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/tasks/UpbitFragment.kt
>          //TODO : MARKET_NAME enum으로 빼자
[cd292bd](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/210/commits/cd292bd7d0d3c81ee1ff64df951d2e1a4efce058) 수정했습니다

2019-09-24 07:51 UTC, wkdehdlr commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/util/BindingAdapters.kt
> +fun RecyclerView.replaceAll(items: ObservableField<List<UpbitItem>>) {
이 부분을 observablefield로 처리하는게 mvvm 아닌가요??.....일반 List여도 변화를 감지(?)할 수 있나요?

2019-09-24 08:12 UTC, BeokBeok commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/base/BaseFragment.kt
> +abstract class BaseFragment<B : ViewDataBinding>(private val layoutId: Int) : Fragment() {
리소스 관련하여 전달된 리소스 값의 유효성 체크를 도와줍니다.

2019-09-24 08:12 UTC, BeokBeok commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/tasks/UpbitFragment.kt
> +            bundle.putString(Name.MARKET_NAME.toString(), marketName)
toString 대신 name 을 사용하시면 됩니다.
```suggestion
            bundle.putString(Name.MARKET_NAME.name, marketName)
```
enum 클래스 이름이 너무 General 합니다.
좀 더 명확하게 명명하셨으면 좋겠습니다.
예를 들면,
```
enum class Market {
    NAME
}
```

2019-09-24 08:12 UTC, BeokBeok commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/tasks/UpbitRVAdapter.kt
> +        return Holder(
onCreateViewHolder의 리턴 타입도 생략 가능합니다.

2019-09-24 08:12 UTC, BeokBeok commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/util/BindingAdapters.kt
> +fun RecyclerView.replaceAll(items: ObservableField<List<UpbitItem>>) {
파라미터 타입을 ObservableField<List<UpbitItem>> 에서 List<UpbitItem> 으로 변경하는 것일 뿐
뷰모델에 있는 ObservableField가 데이터 변경을 감지하여 데이터바인딩을 통하여 값을 전달하는 것은 동일합니다.

즉, ObservableField 타입으로 전달 받은 변수를 get 함수를 호출하여 처리하는 것과
List 타입으로 전달 받은 변수를 바로 처리하는 것의 차이인 것 같습니다.

2019-09-25 01:07 UTC, wkdehdlr commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/tasks/UpbitFragment.kt
> +            bundle.putString(Name.MARKET_NAME.toString(), marketName)
[090f7db](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/210/commits/090f7db45a2e3740c7972026e9f4048d92eaea6a) 수정했습니다

2019-09-25 01:09 UTC, wkdehdlr commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/tasks/UpbitRVAdapter.kt
> +        return Holder(
[d3c3ddf](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/210/commits/d3c3ddf1f3ece2c8a34ba26d774af5d636f4ffd5) 수정했습니다

2019-09-25 01:11 UTC, wkdehdlr commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/util/BindingAdapters.kt
> +fun RecyclerView.replaceAll(items: ObservableField<List<UpbitItem>>) {
[33aed0b](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/210/commits/33aed0b123d6aa3a570a303e74bc7b1360317058) 수정했습니다. 굳이 한번 안거치고 바로 하는게 나을듯합니다!

2019-09-25 07:01 UTC, BeokBeok commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/util/BindingAdapters.kt
> +fun RecyclerView.replaceAll(items: ObservableField<List<UpbitItem>>) {
App이 crash가 발생하는데 확인 부탁드립니다.
nullable 처리하시면 될 것 같습니다.

2019-09-25 07:17 UTC, sjjeong commented
해당 PR은 머지하고 7과제에서 마저 반영해주세요

2019-09-25 07:22 UTC, sjjeong commented
@BeokBeok 
7주차 과제 진행을 위해서 이번 pr에 리뷰해주신것은 HW-7에서 리뷰 부탁드립니다.
해당 pr은 approve 해주세요

2019-09-25 07:22 UTC, sjjeong approved these changes
7주차 과제에서 마져 과제 진행해주세요

2019-09-25 07:28 UTC, BeokBeok approved these changes

2019-09-25 07:38 UTC, merged