HW-7 코인헬퍼 MVVM 리팩토링
sjjeong/GoogryAndroidArchitecutreStudy pull request #211
Opened 2019-09-22 07:15 UTC by preludezdev

- 스터디 때 석준님이 말씀해주신 부분 최대한 수정했습니다

2019-09-22 08:16 UTC, dlwls5201 commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/viewmodel/MarketViewModel.kt
> +            isProgressed.set(false) // 프로그래스바 종료
통신 완료 시점에 프로그래스바를 종료해 주세요.

2019-09-22 08:20 UTC, dlwls5201 commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/market/MarketFragment.kt
> +    private var keyMarket = "KEY_MARKET"
val 로 변경해 주세요

2019-09-22 08:51 UTC, dlwls5201 commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/util/BindingAdapters.kt
> +fun RecyclerView.replaceAll(items: ObservableField<List<Coin>>) =
ObservableField를 넘기는게 아닌 List<Coin>의 item만 넘겨서 사용합니다.
https://developer.android.com/topic/libraries/data-binding/binding-adapters

2019-09-24 01:49 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/market/MarketFragment.kt
> +    private var keyMarket = "KEY_MARKET"
해당 부분 수정했습니다

commit : 9d29fc3

2019-09-24 01:49 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/util/BindingAdapters.kt
> +fun RecyclerView.replaceAll(items: ObservableField<List<Coin>>) =
해당 부분 수정했습니다

commit : 46e325a

2019-09-24 01:51 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/viewmodel/MarketViewModel.kt
> +            isProgressed.set(false) // 프로그래스바 종료
지금 위치한 부분이 통신 완료 시점이 아닌가요??

2019-09-24 06:38 UTC, dlwls5201 commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/viewmodel/MarketViewModel.kt
> +            isProgressed.set(false) // 프로그래스바 종료
통신은 비동기로 동작합니다. repository 스코프 안에서 응답 받는 부분이 통신완료 지점입니다. 지금 isProgress.set()은 repository 스코프 밖에있죠? 위 코드는 통신이 오래걸리면 프로그래스는 종료되어도 계속 통신 중인 로직입니다.

-> 구체적으로 말씀드리자면 consList.set()이 있는 부분과 onFailCallback(it) 이 두 부분이 통신이 완료되는 부분이죠

2019-09-24 15:31 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/viewmodel/MarketViewModel.kt
> +            isProgressed.set(false) // 프로그래스바 종료
아아 레트로핏 통신 비동기로 데이터 가져오는건데 프로그레스 종료코드를 통신하는 부분 밖에다 적고 있었네요ㅠ 말씀해주신 부분 반영했습니다!

commit : e3e8c6c

2019-09-24 15:38 UTC, dlwls5201 reviewed
멘토 리뷰끝나고 Approve 하겠습니다. 고생하셨습니다.

2019-09-25 07:15 UTC, BeokBeok requested changes
안녕하세요. 스터디 2기 강현석이라고 합니다.
부족하지만 잘 부탁드립니다. 😅

2019-09-25 07:15 UTC, BeokBeok commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/market/MarketFragment.kt
> +    private val marketViewModel: MarketViewModel by lazy {
타입 생략이 가능합니다.

2019-09-25 07:15 UTC, BeokBeok commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/viewmodel/MarketViewModel.kt
>                      if (coinTickerResponses != null) {
isNullOrEmpty 함수를 사용하셔서 처리하셔도 좋을 것 같습니다.

2019-09-25 07:15 UTC, BeokBeok commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/viewmodel/MarketViewModel.kt
>          if (keyMarket != null) {
keyMarket 이 null 일 경우에 대해서도 예외처리를 추가해주시면 좋을 것 같습니다.

2019-09-25 17:26 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/market/MarketFragment.kt
> +    private val marketViewModel: MarketViewModel by lazy {
수정했습니다.

commit : 17b4c06

2019-09-25 17:26 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/viewmodel/MarketViewModel.kt
>                      if (coinTickerResponses != null) {
수정했습니다.

commit : 54610e2

2019-09-25 17:28 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/viewmodel/MarketViewModel.kt
>          if (keyMarket != null) {
어떻게 예외처리할지 고민하다가 addOnPropertyChangedCallback 함수를 통해 토스트를 띄워 처리해봤습니다.

commit : ff73685

2019-09-26 01:13 UTC, BeokBeok commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/viewmodel/MarketViewModel.kt
>          if (keyMarket != null) {
구현하신 onFailCallback 을 활용하셔서 처리하시는건 어떤가요?

2019-09-26 21:53 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/viewmodel/MarketViewModel.kt
>          if (keyMarket != null) {
onFailCallback 함수를 이용해서 처리해보았습니다
commit : 447e632

2019-09-27 01:54 UTC, BeokBeok submitted a review, later dismissed
LGTM:ok_hand:

2019-09-28 00:56 UTC, sjjeong requested changes

2019-09-28 00:56 UTC, sjjeong commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/market/MarketFragment.kt
> +        private const val keyMarket = "KEY_MARKET"
상수는 KEY_MARKET 처럼 이름 지어야 합니다.
```kotlin
private const val KEY_MARKET = "KEY_MARKET"
```

2019-09-28 00:56 UTC, sjjeong commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/util/BindingAdapters.kt
> +        if (items != null) {
null체크는 RecyclerViewAdapter#setData에서 해주면 됩니다.
null일 때는 데이터를 비워주면 됩니다.
변경하면 해당 코드는 아래와 같이 변경됩니다.
```kotlin
(adapter as? RecyclerViewAdapter)?.setData(items)
```

2019-09-28 03:20 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/market/MarketFragment.kt
> +        private const val keyMarket = "KEY_MARKET"
수정했습니다

commit : 62f046b

2019-09-28 03:21 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/util/BindingAdapters.kt
> +        if (items != null) {
수정했습니다

commit : 7aa9cd9

2019-09-28 15:21 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-09-29 10:43 UTC, BeokBeok approved these changes

2019-10-01 02:30 UTC, merged