HW-7 코인헬퍼 MVVM 변경
sjjeong/GoogryAndroidArchitecutreStudy pull request #212
Opened 2019-09-23 15:53 UTC by dlwls5201

ViewModel의 파라미터로 listener를 보낸 방식을 observableField를 사용해 변경했습니다.

2019-09-24 05:08 UTC, preludezdev reviewed
이번 주도 역시 말씀드릴게 많이 없네요ㅎㅎ 메인액티비티에서 addOnPropertyChangedCallback 써서 모든 프래그먼트의 뷰모델에 들어있는 데이터를 sorting 하는 부분은 코드보면서 많이 공부됐어요. 다만 메인뷰모델 쪽에 Observable 변수가 조금 많은게 아닌가 생각도 드는데 그렇다고 제 수준에서 바로 해결책이 보이진 않아서 드릴 말씀이 없는걸로 하고....조금이지만 리뷰갑니다

2019-09-24 05:08 UTC, preludezdev commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/ui/main/MainActivity.kt
> +
if 문은 for문 위로 나와도 될 것 같습니다

2019-09-24 05:08 UTC, preludezdev commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/ui/main/MainActivity.kt
>              }
코드보면서 든 궁금증이 있는데 뷰모델을 by lazy로 선언해서 만들어주는게 나을까요 아님 진성님처럼 lateinit 으로 하는게 나을까요? 보니까 Fragment 쪽 뷰모델에서는 번들로 넘어온 키값도 넘겨줘야되서 lateinit 하시는거 같은데 저는 그 키값을 뷰모델.loadData() 함수의 인자로 받았거든요. 저는 뭐가 더 나은지 잘 모르겠어서... 그냥 스타일의 차이로 봐도 될까요? 아님 어느쪽이 더 좋은 코드다 라는 생각이 따로 있으신지 궁금해요 :)

2019-09-24 14:32 UTC, dlwls5201 commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/ui/main/MainActivity.kt
> +
수정했습니다.
commit : fe5280a

2019-09-24 14:42 UTC, dlwls5201 commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/ui/main/MainActivity.kt
>              }
Fragment에서는 argument null 여부 체크 후 초기화 해주고 싶기도 했고 lateinit을 사용하는게 더 코드가 깔금해 보여서 이렇게 했습니다.

MainActivity에서는 by lazy로 변경했습니다.
commit : 7224381

2019-09-24 15:37 UTC, preludezdev reviewed
Approve는 나중에 석준님이 Approve하는대로 바로 하겠습니다
고생하셨습니다!!

2019-09-25 06:54 UTC, BeokBeok requested changes
안녕하세요. 스터디 2기 강현석이라고 합니다.
부족하지만 잘 부탁드립니다. ^~^

2019-09-25 06:54 UTC, BeokBeok commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/ui/main/MainActivity.kt
> +                (sender as ObservableField<Pair<Filter.SelectArrow, Boolean>>).get()?.let {
unchecked cast 관련 annotation 을 추가해주시면 좋을 것 같습니다.

2019-09-25 06:54 UTC, BeokBeok commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/ui/main/MainViewModel.kt
> +    val selectField = ObservableField<Pair<Filter.SelectArrow, Boolean>>()
selectedField 는 view 에서 observe 하여 처리하고 있지만,
나머지 프로퍼티(titles, markets, pageLimit, category, isSelected) 에 대해서는 observe 하여 처리하고 있지 않습니다.

그렇다면, ObservableField 를 사용하지 않아도 되지 않을까요?

2019-09-25 06:54 UTC, BeokBeok commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/ui/main/MainViewModel.kt
> +        val selected = !(isSelected.get() ?: false)
apply 를 사용하여 isSelected 변수 값을 false 로 초기화하시면
엘비스 연산자로 null 인 경우에 대한 초기화는 하지 않으셔도 될 것 같습니다.

2019-09-25 07:20 UTC, BeokBeok commented on dlwls5201/MyArchitecture/app/src/main/res/layout/activity_main.xml
> +                        android:isSelected="@{mainModel.isSelected}"
safeUnbox 함수를 사용하여 처리하시는 것을 권장합니다.
```suggestion
                        android:isSelected="@{safeUnbox(mainModel.isSelected)}"
```

2019-09-25 16:34 UTC, dlwls5201 commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/ui/main/MainActivity.kt
> +                (sender as ObservableField<Pair<Filter.SelectArrow, Boolean>>).get()?.let {
추가해주었습니다.
commit : 49f3a75

2019-09-25 16:36 UTC, dlwls5201 commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/ui/main/MainViewModel.kt
> +        val selected = !(isSelected.get() ?: false)
apply 함수를 사용해 추가해 주었습니다. 
commit : 711c6ce

2019-09-25 16:39 UTC, dlwls5201 commented on dlwls5201/MyArchitecture/app/src/main/res/layout/activity_main.xml
> +                        android:isSelected="@{mainModel.isSelected}"
xml에서도  null 여부를 체크해 기본값을 리턴해 주는 함수를 가지고 있었네요. 좋은 정보 감사합니다.
commit : 36bc15a

2019-09-26 00:01 UTC, BeokBeok commented on dlwls5201/MyArchitecture/app/src/main/res/layout/activity_main.xml
> +                        android:isSelected="@{mainModel.isSelected}"
pageLimit 과 isLoading 도 적용해주세요

2019-09-26 16:16 UTC, dlwls5201 commented on dlwls5201/MyArchitecture/app/src/main/res/layout/activity_main.xml
> +                        android:isSelected="@{mainModel.isSelected}"
말씀해 주신 두곳도 추가로 설정해 주었습니다.
commit : 0384dce

2019-09-27 01:27 UTC, BeokBeok commented on dlwls5201/MyArchitecture/app/src/main/res/layout/activity_main.xml
> +                        android:isSelected="@{mainModel.isSelected}"
safeUnbox 를 사용하지 않아도 동작상 문제는 되진 않지만,
LiveData 에서도 Box형 필드는 Unbox 해 주는 것이 좋을 것 같습니다.
https://proandroiddev.com/advanced-data-binding-binding-to-livedata-one-and-two-way-binding-dae1cd68530f

2019-09-27 01:28 UTC, BeokBeok submitted a review, later dismissed
LGTM:ok_hand:

2019-09-28 01:09 UTC, sjjeong requested changes

2019-09-28 01:09 UTC, sjjeong commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/ui/main/MainActivity.kt
> +            binding.mainModel = this
이렇게 해주는 코드는 좋지 않습니다.
MainActivity에서 mainViewModel이 사용되지 않는다면 binding에 mainModel이 set 될일이 없게 됩니다.

2019-09-28 01:09 UTC, sjjeong commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/ui/main/MainActivity.kt
> +                    val selected = it.second
이렇게도 되지 않나요?
```kotlin
val (filter, selected) = it
```

2019-09-28 01:09 UTC, sjjeong commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/ui/main/MainViewModel.kt
> +        set(false)
apply로 set하는 것 대신 생성자로 데이터를 줄 수 있습니다.
```kotlin
val isSelected = ObservableField<Boolean>(false)
```

2019-09-28 03:02 UTC, dlwls5201 commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/ui/main/MainActivity.kt
> +            binding.mainModel = this
null로 초기화 해줄러다가 사용할때마다 null체크를 해줘야 되는게 번거로워 보여 lateinit을 사용해 초기화했습니다.
commit : 411f6b8

2019-09-28 03:03 UTC, dlwls5201 commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/ui/main/MainActivity.kt
> +                    val selected = it.second
수정했습니다.
commit : f34a5f3

2019-09-28 03:04 UTC, dlwls5201 commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/ui/main/MainViewModel.kt
> +        set(false)
수정했습니다.
commit : 71e1402

2019-09-28 15:23 UTC, sjjeong commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/ui/main/MainActivity.kt
> +            binding.mainModel = this
제가 리뷰한 내용은 binding.mainModel 부분 입니다.

2019-09-29 05:10 UTC, dlwls5201 commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/ui/main/MainActivity.kt
> +            binding.mainModel = this
수정했습니다.
commit : cc8b5f0

2019-09-29 15:29 UTC, sjjeong approved these changes

2019-09-30 00:13 UTC, BeokBeok approved these changes

2019-10-01 02:29 UTC, preludezdev approved these changes
고생하셨습니다

2019-10-01 02:43 UTC, merged