Class03/ganghee
sjjeong/GoogryAndroidArchitecutreStudy pull request #213
Opened 2019-09-24 14:25 UTC by ganghee

Base 객체들을 추가하였습니다.

2019-09-24 23:37 UTC, wswon commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/base/BaseViewHolder.kt
> +            itemView.visibility = View.INVISIBLE
GONE 으로 처리해야 정상처리 되지않은 ITEM 의 영역이 안보이지 않을까요?

2019-09-24 23:37 UTC, wswon commented on ganghee/MyStudy2/app/src/main/res/layout/fragment_upbit.xml
> +            app:layoutManager="androidx.recyclerview.widget.LinearLayoutManager" />
```suggestion
            app:layoutManager="LinearLayoutManager" />
```
이렇게 해도 잘 되더라고요

2019-09-25 12:32 UTC, ganghee commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/base/BaseViewHolder.kt
> +            itemView.visibility = View.INVISIBLE
네네 수정하였습니다!!

2019-09-25 12:32 UTC, ganghee commented on ganghee/MyStudy2/app/src/main/res/layout/fragment_upbit.xml
> +            app:layoutManager="androidx.recyclerview.widget.LinearLayoutManager" />
네 감사합니다

2019-09-25 13:56 UTC, wswon submitted a review, later dismissed
고생하셨습니다. 👍

2019-09-26 02:27 UTC, BeokBeok requested changes
안녕하세요. 스터디 2기 강현석이라고 합니다.
부족하지만 잘 부탁드립니다. 😅

2019-09-26 02:27 UTC, BeokBeok commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/base/BaseFragment.kt
> +abstract class BaseFragment<B : ViewDataBinding>(private val layoutId: Int) : Fragment() {
`@LayoutRes` 어노테이션을 사용해주시면 좋을 것 같아요.

2019-09-26 02:27 UTC, BeokBeok commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/base/BaseRecyclerViewAdapter.kt
> +    @LayoutRes private val layoutRes: Int,
어노테이션 관련 코드 컨벤션을 지켜주시면 좋을 것 같아요.
https://kotlinlang.org/docs/reference/coding-conventions.html#annotation-formatting

2019-09-26 02:27 UTC, BeokBeok commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/base/BaseRecyclerViewAdapter.kt
> +    private val bindingVariableId: Int? = null
variable 뜻 자체가 변수를 의미하기 때문에, 변수명에 variable 은 피해주시는 것이 좋아요.

2019-09-26 02:27 UTC, BeokBeok commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/base/BaseRecyclerViewAdapter.kt
> +        items?.let {
immutable 한 변수에는 let 보다 if 문으로 null check 하는 것이 좋아요.
https://medium.com/@elye.project/kotlin-dont-just-use-let-7e91f544e27f

2019-09-26 02:27 UTC, BeokBeok commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/base/BaseRecyclerViewAdapter.kt
> +        holder.onBindViewHolder(items[position])
`=` 을 사용하시면 중괄호를 없앨 수 있어요.

2019-09-26 02:27 UTC, BeokBeok commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/base/BaseViewHolder.kt
> +        try {
try catch 로 예외처리하신 이유가 있나요?

2019-09-26 02:27 UTC, BeokBeok commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/util/AdapterUtil.kt
> +    (this.adapter as? BaseRecyclerViewAdapter<Any, *>)?.let {
let 보다는 run 이 좋아 보여요.
https://medium.com/@elye.project/kotlin-dont-just-use-let-7e91f544e27f

2019-09-26 02:27 UTC, BeokBeok commented on ganghee/MyStudy2/app/src/main/res/layout/activity_main.xml
> +            android:layout_marginTop="3dp"
레이아웃 여백 처리는 4 또는 8dp 단위로 처리하시는 것이 좋아요.
https://material.io/design/layout/understanding-layout.html#

2019-09-26 02:27 UTC, BeokBeok commented on ganghee/MyStudy2/app/src/main/res/layout/activity_main.xml
> +            tools:context=".ui.MainActivity">
이 부분은 최상단 뷰(FrameLayout)에 있어야 할 것 같아요.

2019-09-26 02:27 UTC, BeokBeok commented on ganghee/MyStudy2/app/src/main/res/layout/activity_main.xml
> +                    android:layout_width="wrap_content"
weight 속성을 사용하셨는데, width 혹은 height 에 wrap_content 를 사용하신 이유가 있나요?

2019-09-26 02:27 UTC, BeokBeok commented on ganghee/MyStudy2/app/src/main/res/layout/activity_main.xml
> +                    android:gravity="right"
left, right 대신에 start, end 를 사용하시는 것이 좋아요.

2019-09-26 02:27 UTC, BeokBeok commented on ganghee/MyStudy2/app/src/main/res/layout/rv_item_list.xml
>                  android:layout_width="0sp"
sp가 아니라 dp인 것 같네요.

2019-09-26 12:55 UTC, ganghee commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/base/BaseFragment.kt
> +abstract class BaseFragment<B : ViewDataBinding>(private val layoutId: Int) : Fragment() {
네네 수정하였습니다!

2019-09-26 12:55 UTC, ganghee commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/base/BaseRecyclerViewAdapter.kt
> +    @LayoutRes private val layoutRes: Int,
네 수정하였습니다.

2019-09-26 12:55 UTC, ganghee commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/base/BaseRecyclerViewAdapter.kt
> +    private val bindingVariableId: Int? = null
네 제거하였습니다.

2019-09-26 12:56 UTC, ganghee commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/base/BaseRecyclerViewAdapter.kt
> +        items?.let {
자료 감사합니다 수정하였습니다.

2019-09-26 13:04 UTC, ganghee commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/base/BaseRecyclerViewAdapter.kt
> +        holder.onBindViewHolder(items[position])
= 로 바꾸었습니다.

2019-09-26 13:10 UTC, ganghee commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/base/BaseViewHolder.kt
> +        try {
고민해 보니까 굳이 쓸 필요가 없는 것 같네요~

2019-09-26 13:10 UTC, ganghee commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/util/AdapterUtil.kt
> +    (this.adapter as? BaseRecyclerViewAdapter<Any, *>)?.let {
네 수정하였습니다

2019-09-26 13:14 UTC, ganghee commented on ganghee/MyStudy2/app/src/main/res/layout/activity_main.xml
> +            android:layout_marginTop="3dp"
여백 말고 다른 속성의 단위도 4단위로 맞추는게 좋을까요?

2019-09-26 13:16 UTC, ganghee commented on ganghee/MyStudy2/app/src/main/res/layout/activity_main.xml
> +            tools:context=".ui.MainActivity">
네 수정하였습니다

2019-09-26 13:18 UTC, ganghee commented on ganghee/MyStudy2/app/src/main/res/layout/activity_main.xml
> +                    android:gravity="right"
네 수정하였습니다

2019-09-26 13:18 UTC, ganghee commented on ganghee/MyStudy2/app/src/main/res/layout/rv_item_list.xml
>                  android:layout_width="0sp"
네 수정하였습니다

2019-09-26 13:25 UTC, ganghee commented on ganghee/MyStudy2/app/src/main/res/layout/activity_main.xml
> +                    android:layout_width="wrap_content"
0dp로 바꾸는 것을 실수로 바꾸지 못했네요...
width 속성을 0dp로 설정하고 height 속성을 그대로 wrap_content로 바꾸었습니다
의도하신 부분이 맞는지 모르겠네요 😅

2019-09-27 01:48 UTC, BeokBeok commented on ganghee/MyStudy2/app/src/main/res/layout/activity_main.xml
> +            android:layout_marginTop="3dp"
다른 속성은 잘 모르겠습니다.
해당 속성에 대하여 메테리얼 디자인 사이트에서 찾아봐야 할 것 같습니다.

2019-09-27 01:48 UTC, BeokBeok submitted a review, later dismissed
LGTM:ok_hand:

2019-09-28 01:13 UTC, sjjeong requested changes

2019-09-28 01:13 UTC, sjjeong commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/base/BaseActivity.kt
> +        binding.lifecycleOwner = this
해당 코드는 왜 넣으셨나요?

2019-09-28 01:13 UTC, sjjeong commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/base/BaseFragment.kt
> +        binding.lifecycleOwner = this
해당 코드는 왜 넣으셨나요?

2019-09-28 01:13 UTC, sjjeong commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/base/BaseActivity.kt
> +abstract class BaseActivity<B : ViewDataBinding>(private val layoutId: Int) : AppCompatActivity() {
@LayoutRes 추가해주세요

2019-09-28 02:13 UTC, ganghee commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/base/BaseActivity.kt
> +        binding.lifecycleOwner = this
삭제하였습니다
[BaseActivity](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/213/commits/211c818a015f6d1e88dd315eadaf64b5ebea277a)

2019-09-28 02:15 UTC, ganghee commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/base/BaseFragment.kt
> +        binding.lifecycleOwner = this
삭제하였습니다
[BaseFragment](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/213/commits/7ade32d6242473e46d556cd7bf594ddd47c3c136)

2019-09-28 02:16 UTC, ganghee commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/base/BaseActivity.kt
> +abstract class BaseActivity<B : ViewDataBinding>(private val layoutId: Int) : AppCompatActivity() {
추가하였습니다 ~~^^
[BaseActivity](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/213/commits/2fbedcde8c4c648f5dd3dfc586c4ac13f3599de2)

2019-09-28 15:23 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-09-29 00:53 UTC, wswon approved these changes

2019-09-29 00:54 UTC, merged