HW-7 MVVM 수정사항 반영
sjjeong/GoogryAndroidArchitecutreStudy pull request #214
Opened 2019-09-24 19:54 UTC by wswon

MVVM 리뷰에따른 수정사항 반영했습니다.

2019-09-25 12:23 UTC, ganghee reviewed
과제하시느라 수고하셨습니다 궁금한 부분이나 저의 생각을 리뷰해보았습니다

2019-09-25 12:23 UTC, ganghee commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/viewmodel/MarketViewModel.kt
> +                override fun onSucess(dataList: List<MarketResponse>) {
onSucess 오타가 있네요

2019-09-25 12:23 UTC, ganghee commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/viewmodel/MarketViewModel.kt
> +    val exceptionMessage = ObservableField<String>()
BaseViewModel에
```
abstract class BaseViewModel : ViewModel(){
    val exceptionMessage = ObservableField<String>()
}
```
로 추가해 보는 건 어떨까요? 두 개 공통으로 가지고 있습니다.
 repository도 파라미터로 가지고 있어서 BaseView에 구현하는 것도 좋을 것 같아요

2019-09-25 12:23 UTC, ganghee commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/view/coin/CoinListFragment.kt
>              recyclerViewCoinList.run {
run 함수는 이미 생성된 객체에서 연속적으로 함수나 필드를 호출할 때 사용하는 것으로 알고 있습니다.
또는 지역 변수의 범위를 지정할 때 사용합니다.
위 코드는 adapter 하나만 호출하고 있어서 없어도 될 것 같아요.

2019-09-25 12:23 UTC, ganghee commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/view/coin/CoinListFragment.kt
>          tickerViewModel.run {
run 함수 없어도 될 것 같습니다.

2019-09-25 12:23 UTC, ganghee commented on wswon/AndroidArchitectureStudy/app/src/main/res/layout/item_ticker.xml
>      </data>
data 태그가 item_ticker.xml 에는 아래에 fragment_coin.xml 에는 위로 가있네요
통일 시키는 것이 좋을 것 같아요

2019-09-25 13:59 UTC, wswon commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/viewmodel/MarketViewModel.kt
> +                override fun onSucess(dataList: List<MarketResponse>) {
91306e1 other커밋에 수정사항이 늦게올라간듯 합니다

2019-09-25 14:21 UTC, wswon commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/viewmodel/MarketViewModel.kt
> +                override fun onSucess(dataList: List<MarketResponse>) {
f95c308 수정했습니다.

2019-09-25 14:21 UTC, wswon commented on wswon/AndroidArchitectureStudy/app/src/main/res/layout/item_ticker.xml
>      </data>
2222ab5 이게자꾸 ctrl alt l 을 하면 아래로 내려가네요 ㅠ
혹시 이유를 아시나요?

2019-09-25 14:21 UTC, wswon commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/view/coin/CoinListFragment.kt
>          tickerViewModel.run {
3c4f318 수정했습니다.

2019-09-25 14:21 UTC, wswon commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/view/coin/CoinListFragment.kt
>              recyclerViewCoinList.run {
3c4f318 수정했습니다.

2019-09-25 14:24 UTC, wswon commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/viewmodel/MarketViewModel.kt
> +    val exceptionMessage = ObservableField<String>()
0a3772d generic타입 사용하여 두가지 모두 구현해봤습니다.
헌데 BaseViewModel에 repository를 포함하려면
ViewModel은 하나의 Repository를 가져야한다. 가 전제가 되야하는데,
맞는것인지에 대해 고민이듭니다. 강희님은 어떻게 생각하시나요?

2019-09-25 15:17 UTC, ganghee commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/viewmodel/MarketViewModel.kt
> +    val exceptionMessage = ObservableField<String>()
Viewmodel 은 repository 와 view 를 연결시켜 주는 부분인데
제 생각으로는 ViewModel이 기본적으로 repository를 가지고 있어도 상관없을 것 같아요
흠... repository 객체를 참조할 때 에러를 볼 수 있게 분기 처리도 잘 해놨고요
다른사람들의 의견도 궁금하네요 저도 이부분에 대해 더 고민해 볼게요

2019-09-25 15:21 UTC, ganghee commented on wswon/AndroidArchitectureStudy/app/src/main/res/layout/item_ticker.xml
>      </data>
한번 여기 들어가서 따라해 보는 것 어때요? 저번에 스터디 슬랙에서도 이야기 했었던 부분입니다.
[오류수정 블로그](https://namget.tistory.com/entry/Android-Android-Studio-35-Xml-Code-Style-%EC%98%A4%EB%A5%98-%EC%88%98%EC%A0%95-%EB%B0%A9%EB%B2%95)

2019-09-26 11:08 UTC, wswon commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/viewmodel/MarketViewModel.kt
> +    val exceptionMessage = ObservableField<String>()
감사합니다 저도 더 고민해볼게요!!

2019-09-26 11:08 UTC, wswon commented on wswon/AndroidArchitectureStudy/app/src/main/res/layout/item_ticker.xml
>      </data>
감사합니다 적용해볼게요!!

2019-09-26 12:31 UTC, ganghee commented
수고하셨어요 😀😊

2019-09-26 14:26 UTC, ganghee reviewed
제가 오늘 리뷰에서 지적 받은 것을 우석님에게 리뷰를 해보았어요!!

2019-09-26 14:26 UTC, ganghee commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/base/BaseFragment.kt
> +abstract class BaseFragment<B : ViewDataBinding>(private val layoutId: Int) : Fragment() {
```@LayoutRes``` 사용해주세요

2019-09-26 14:26 UTC, ganghee commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/base/BaseViewHolder.kt
> +    @LayoutRes layoutRes: Int,
어노테이션 관련 코드 컨벤션 사용해주세요
https://kotlinlang.org/docs/reference/coding-conventions.html#annotation-formatting

2019-09-26 14:26 UTC, ganghee commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/base/BaseViewHolder.kt
> +    private val bindingVariableId: Int?
변수를 뜻하는 variable을 제거하여 다시 변수명을 선언해주세요

2019-09-26 14:26 UTC, ganghee commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/base/BaseAdapter.kt
> +        items?.let {
immutable 변수에는 let보다는 if문으로 null 처리해주세요
https://medium.com/@elye.project/kotlin-dont-just-use-let-7e91f544e27f

2019-09-26 14:26 UTC, ganghee commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/base/BaseViewHolder.kt
> +        try {
예외처리할 이유가 없다면 제거하셔도 좋을 것 같아요

2019-09-27 03:31 UTC, wswon commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/base/BaseFragment.kt
> +abstract class BaseFragment<B : ViewDataBinding>(private val layoutId: Int) : Fragment() {
3fee2a0  추가했습니다.

2019-09-27 03:31 UTC, wswon commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/base/BaseViewHolder.kt
> +    @LayoutRes layoutRes: Int,
f83e8e3 수정했습니다.

2019-09-27 03:32 UTC, wswon commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/base/BaseViewHolder.kt
> +    private val bindingVariableId: Int?
6c8b15f 변경했습니다.

2019-09-27 03:32 UTC, wswon commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/base/BaseAdapter.kt
> +        items?.let {
8562286 변경했습니다.

2019-09-27 03:37 UTC, wswon commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/base/BaseViewHolder.kt
> +        try {
생각해보았는데, Base class이다보니 예기치못한 Exception에 대해 대처하기 위해 필요하지 않을까요? 안전한처리를 위해서요.

2019-09-27 03:41 UTC, ganghee submitted a review, later dismissed
수고하셨습니다👍🏻

2019-09-27 04:47 UTC, BeokBeok requested changes
안녕하세요. 스터디 2기 강현석이라고 합니다.
부족하지만 잘 부탁드립니다. 😅

2019-09-27 04:47 UTC, BeokBeok commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/base/BaseAdapter.kt
> +    @LayoutRes private val layoutRes: Int,
annotation 관련하여 컨벤션을 따라주시는 것이 좋아요.
https://kotlinlang.org/docs/reference/coding-conventions.html#annotation-formatting

2019-09-27 04:47 UTC, BeokBeok commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/base/BaseViewHolder.kt
> +        try {
예상치 못한 Exception이 무엇일까요?
그렇다면 모든 예외처리를 try catch 로 하는 것이 좋을까요?

2019-09-27 04:47 UTC, BeokBeok commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/network/RetrofitInstance.kt
> +object RetrofitInstance {C
C 오타가 있는 것 같습니다.
제거해주세요.

2019-09-29 01:01 UTC, wswon commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/base/BaseViewHolder.kt
> +        try {
그렇게 생각했던 이유는 일전에 url로 이미지 가져오고 했을때를 생각했었는데, 이 경우는 객체를 넣는것 뿐이기 때문에 그런 예외가 발생하지 않을꺼 같고.. 그러네요
try ~ catch 는 kotlin에서 잘 사용하지 않는다 본것 같은데, 다른 방법이 있는지는 아직 알지 못하였습니다..

2019-09-29 01:05 UTC, wswon commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/base/BaseAdapter.kt
> +    @LayoutRes private val layoutRes: Int,
3936254 수정하였습니다!

2019-09-29 01:05 UTC, wswon commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/network/RetrofitInstance.kt
> +object RetrofitInstance {C
480f29e  수정했습니다.

2019-09-29 01:07 UTC, wswon commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/base/BaseViewHolder.kt
> +        try {
9630934 try~catch를 제거하였습니다.

2019-09-29 10:46 UTC, BeokBeok commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/base/BaseViewHolder.kt
> +        try {
item이 null 인 경우에 대하여 예외처리가 필요할 것 같아요.

2019-09-30 01:02 UTC, wswon commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/base/BaseViewHolder.kt
> +        try {
443c642 item null check를 추가해보았습니다

2019-09-30 01:11 UTC, BeokBeok approved these changes
LGTM:ok_hand:

2019-10-01 13:13 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-10-08 05:52 UTC, merged