HW-7 MVVM 수정
sjjeong/GoogryAndroidArchitecutreStudy pull request #216
Opened 2019-09-26 09:54 UTC by wkdehdlr

Base위주로 추가했습니다..! 아리까리하네요 ㅠㅠㅠㅠㅠㅠㅠㅠㅠ

2019-09-27 05:50 UTC, zozero94 reviewed
처음 프로젝트를 받았을 때, 저번과제 이번과제 둘다 런타임에러가 발생했습니다 ㅠ_ㅠ
실행 확인 하고 올려주시길 부탁드릴게요!
그리고 Page넘길때마다 Pager에서 fragment를 다시그리는 연산을 하는데
PageLimit을 Databinding으로 MainViewModel에서 주는것도 나쁘지 않아보입니다!

2019-09-27 05:50 UTC, zojae031 commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/util/BindingAdapters.kt
> +fun RecyclerView.replaceAll(items: List<Any>) {
실행시 items는 val (Non-Null) 값인데 nullable하게 넘어와서 오류를 발생시키네요

2019-09-27 09:14 UTC, shareitDOIK commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/util/BindingAdapters.kt
> +fun RecyclerView.replaceAll(items: List<Any>) {
[9cd7837](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/216/commits/9cd7837e54d41a225bd5770c4956343eb8d4bca7) 수정했습니다

2019-09-27 09:37 UTC, wkdehdlr commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/util/BindingAdapters.kt
> +fun RecyclerView.replaceAll(items: List<Any>) {
PageLimit 적용에 대해 좀 더 설명을 부탁드려도 될까요?!?

2019-09-28 06:25 UTC, zojae031 commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/util/BindingAdapters.kt
> +fun RecyclerView.replaceAll(items: List<Any>) {
https://developer.android.com/reference/android/support/v4/view/ViewPager.html#setoffscreenpagelimit

2019-10-10 03:43 UTC, BeokBeok requested changes
안녕하세요. 스터디 2기 강현석이라고 합니다.
부족하지만 잘 부탁드립니다. 😅

2019-10-10 03:43 UTC, BeokBeok commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/base/BaseActivity.kt
> +abstract class BaseActivity<B : ViewDataBinding>(@LayoutRes private val layoutId: Int) :
Annotation 관련 컨벤션을 지켜주시면 좋을 것 같아요.
https://kotlinlang.org/docs/reference/coding-conventions.html#annotation-formatting

2019-10-10 03:43 UTC, BeokBeok commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/base/BaseViewHolder.kt
> +    @LayoutRes layoutId: Int,
접근자를 추가해주시면 좋을 것 같아요.

2019-10-10 03:43 UTC, BeokBeok commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/base/BaseRecyclerViewAdapter.kt
> +    private val bindingVariableId: Int? = null
변수명에 variable 은 지양하시는 것이 좋아요.

2019-10-10 03:43 UTC, BeokBeok commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/base/BaseViewHolder.kt
> +        binding?.apply {
apply 보다는 run 을 사용하시면 좋을 것 같아요.

2019-10-10 03:43 UTC, BeokBeok commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/tasks/UpbitFragment.kt
>              layoutManager = LinearLayoutManager(context!!)
layout manager 는 xml 에서 처리하시면 좋을 것 같아요.

2019-10-11 11:15 UTC, wkdehdlr commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/base/BaseActivity.kt
> +abstract class BaseActivity<B : ViewDataBinding>(@LayoutRes private val layoutId: Int) :
[c8bd16a](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/216/commits/c8bd16ade2c0137df253fc5443bfd16540fe7c49) 수정했습니다

2019-10-11 11:17 UTC, wkdehdlr commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/base/BaseViewHolder.kt
> +    @LayoutRes layoutId: Int,
[2b04718](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/216/commits/2b047187b776250c229073a2d31d3a07ca60880d) 수정했습니다

2019-10-11 11:18 UTC, wkdehdlr commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/base/BaseRecyclerViewAdapter.kt
> +    private val bindingVariableId: Int? = null
[a736298](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/216/commits/a7362981c18eb6c14065eb4de467a0a1227cd472) 수정했습니다

2019-10-11 11:28 UTC, wkdehdlr commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/base/BaseViewHolder.kt
> +        binding?.apply {
[f70e49e](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/216/commits/f70e49ef4b53f09259b0714062a860e4ede85be1) 수정했습니다

2019-10-11 11:31 UTC, wkdehdlr commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/tasks/UpbitFragment.kt
>              layoutManager = LinearLayoutManager(context!!)
[2ee4796](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/216/commits/2ee47963124c1c31a17873eb96c1e28520020889) 수정했습니다

2019-10-11 11:40 UTC, BeokBeok commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/base/BaseActivity.kt
> +    @LayoutRes private val layoutId: Int
어노테이션은 개행해주시는 것이 좋아요
```suggestion
    @LayoutRes 
    private val layoutId: Int
```

2019-10-11 11:40 UTC, BeokBeok commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/base/BaseFragment.kt
> +    @LayoutRes private val layoutId: Int
어노테이션은 개행해주시는 것이 좋아요.
```suggestion
    @LayoutRes 
    private val layoutId: Int
```

2019-10-11 11:40 UTC, BeokBeok commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/base/BaseViewHolder.kt
> +    private val parent: ViewGroup,
해당 변수는 접근자 및 프로퍼티가 필요 없어요.
```suggestion
    parent: ViewGroup,
```

2019-10-12 05:56 UTC, wkdehdlr commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/base/BaseActivity.kt
> +    @LayoutRes private val layoutId: Int
[b0f6acd](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/216/commits/b0f6acdf6805fa6f79a19256ba017ca1f3a19f14) 수정했습니다

2019-10-12 05:56 UTC, wkdehdlr commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/base/BaseFragment.kt
> +    @LayoutRes private val layoutId: Int
[b0f6acd](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/216/commits/b0f6acdf6805fa6f79a19256ba017ca1f3a19f14) 수정했습니다

2019-10-12 05:58 UTC, wkdehdlr commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/base/BaseViewHolder.kt
> +    private val parent: ViewGroup,
[5cd2dbc](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/216/commits/5cd2dbc8630cee4d3ef5dd2ecf4917667192df88) 수정했습니다

2019-10-12 06:00 UTC, BeokBeok approved these changes
LGTM:ok_hand:

2019-10-13 05:19 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-10-13 05:20 UTC, merged