HW-5 BaseContract 정의
sjjeong/GoogryAndroidArchitecutreStudy pull request #217
Opened 2019-09-27 07:40 UTC by seonoh

이렇게 코드를 작성하는 것이 맞는지 궁금합니다.
BaseContract.View에 presenter을 정의하였고, MainActivity와 CoinFragment에서 presenter를 초기화 했습니다. 그
BaseContract.Presenter에서는 공통으로 사용되는 loadData, clearDisposable를 선언했습니다.
MainActivity에서 마켓이름을 불러오는 경우 인자값이 필요하지않고, CoinFragment에서는 marketName을 매개변수로 사용합니다.
Contract.Presenter에서 공통으로 뺼 수 있는 함수들은 BaseContract.Presenter에 정의하였습니다.

2019-09-29 15:47 UTC, jskim5923 reviewed
수고많으셨습니다!! 
이번 과제는 저도 좀 헤매는 부분이라 comment를 남기면서도 이 방법이 확신을 못 해서, 
선오님이 comment보시고, 의아한 부분이 있으면, 추가 comment남겨주시고
멘토님의 리뷰 후에 변경/유지 하시는게 좋을 것 같습니다.

2019-09-29 15:47 UTC, jskim5923 commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/base/BaseContract.kt
> +        fun clearDisposable()
Presenter에서 공통으로 사용하는 view객체와, compositeDisposable 객체도 함께 추가하면 좋을 것 같습니다.

2019-09-29 15:47 UTC, jskim5923 commented on seonoh/ArchitectureStudy/app/build.gradle
> +    implementation 'androidx.appcompat:appcompat:1.1.0'
앞으로는 commit시에 commit 메시지에만 해당하는 변경 사항만 볼 수 있도록 commit이 나눠지면 좋을 것 같습니다.

2019-09-29 15:47 UTC, jskim5923 commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/contract/BaseContract.kt
> +        fun loadData(marketName : String? = null)
loadData를 사용하고 있는 곳에서 항상 parameter로 marketName을 넘겨주지 않기 때문에,
안 넘겨주는 경우를 대비해서 nullable타입으로 변경하기 보다는 
제네릭 타입 + 가변인자로 추상화 시키는게 좋지 않을까 싶습니다.

2019-09-29 15:47 UTC, jskim5923 commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinPresenter.kt
> +            coinRepository.sendCurrentPriceInfo(marketName!!)
BasePresenter에 남겨드린 코멘트에 따라 상황이 변경 되겠지만, 
nullable한 data를 non-null parameter로 넘긴다면, 함수를 호출하기 전에 null check를 하는것이 좋아 보입니다.

2019-09-29 15:47 UTC, jskim5923 commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinMainPresenter.kt
> +        compositeDisposable.addAll(coinRepository.sendMarket()
한개의 disposable을 compositeDisposable에 추가하는 경우에는 compositeDisposable.add() 혹은 .addTo(compositeDisposable) 을 추천드립니다.

2019-10-01 04:44 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/base/BaseContract.kt
> +        fun clearDisposable()
네 수정했습니다.
하면서도 의아했는데... 우선 종선님 코드처럼 수정해봤습니다!
c63adbf616c0bd188262ad22af783f6fda18d67c

2019-10-01 04:44 UTC, seonoh commented on seonoh/ArchitectureStudy/app/build.gradle
> +    implementation 'androidx.appcompat:appcompat:1.1.0'
앗...네 죄송합니다!!

2019-10-01 04:45 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/contract/BaseContract.kt
> +        fun loadData(marketName : String? = null)
네 이 이슈는 각 Presenter로 분리하면서 사라졌습니다.
2e69fb4f8d7dcaab787e18fc500af940bbca02ba

2019-10-01 04:45 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinPresenter.kt
> +            coinRepository.sendCurrentPriceInfo(marketName!!)
네 loadData를 분리하면서 해당 이슈 해결되었습니다.
2e69fb4f8d7dcaab787e18fc500af940bbca02ba

2019-10-01 04:46 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinMainPresenter.kt
> +        compositeDisposable.addAll(coinRepository.sendMarket()
네 수정했습니다 !

2019-10-01 08:33 UTC, BeokBeok requested changes
안녕하세요. 스터디 2기 강현석이라고 합니다.
부족하지만 잘 부탁드립니다. 😅

2019-10-01 08:33 UTC, BeokBeok commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinFragment.kt
> +    override fun setData(data: List<UseCoinModel>) {
= 을 사용하시면 한 줄로 표현이 가능할 것 같아요.
https://kotlinlang.org/docs/reference/coding-conventions.html#function-formatting

2019-10-01 08:33 UTC, BeokBeok commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinMainPresenter.kt
> +            .subscribe({view.setData(it)},{
이렇게 쓰는 것이 더 좋아보여요.
```suggestion
            .subscribe({
                view.setData(it)
            },{
```

2019-10-01 08:33 UTC, BeokBeok commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinPresenter.kt
> +    override val compositeDisposable by lazy { CompositeDisposable() }
lazy를 사용하여 초기화한 이유가 있나요?

2019-10-01 08:33 UTC, BeokBeok commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinPresenter.kt
> +            coinRepository.sendCurrentPriceInfo(marketName!!)
marketName에 `!!`는 없어도 될 것 같아요

2019-10-01 08:33 UTC, BeokBeok commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinPresenter.kt
>          } as ArrayList<UseCoinModel>
ArrayList로 캐스팅하지 않아도 되지 않나요?

2019-10-01 08:33 UTC, BeokBeok commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/MainActivity.kt
>          coinViewPager.apply {
apply 보다는 run이 나은 것 같아요.

2019-10-01 08:33 UTC, BeokBeok commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/MainActivity.kt
>          tabLayout.apply {
apply 보다는 run 이 나은 것 같아요.

2019-10-01 08:33 UTC, BeokBeok commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/MainActivity.kt
> +            addOnPageChangeListener(object : TabLayout.TabLayoutOnPageChangeListener(tabLayout) {})
오버라이딩하여 사용하지 않으실 것이라면, 이렇게 쓰시는게 더 좋아보이네요.
```suggestion
            addOnPageChangeListener(TabLayout.TabLayoutOnPageChangeListener(tabLayout))
```

2019-10-01 08:33 UTC, BeokBeok commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/MainActivity.kt
>          if (toast.view.isShown) {
이 로직에 문제가 있어 보여요.
toast.view.isShown 이 항상 false 이지 않나요?

2019-10-01 08:33 UTC, BeokBeok commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/MainActivity.kt
> +    private fun refineData(marketData: List<Market>): ArrayList<String> {
리턴 타입을 List 로 하시는 것이 좋을 것 같아요.

2019-10-01 08:33 UTC, BeokBeok commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/contract/BaseContract.kt
> +        val presenter : T
변수와 타입은 콜론이 변수에 붙어 있어야 하는 것 같아요.
```suggestion
        val presenter: T
```

자동 정렬 기능을 사용하시면 좋을 것 같네요.

2019-10-01 14:28 UTC, jskim5923 submitted a review, later dismissed
수고하셨습니다! 현석님이 저보다 더 자세하게 리뷰해주시는 것 같아 반성이 됩니다 ㅠㅠ
다음부터는 더 꼼꼼하게 보고 리뷰하도록 하겠습니다.

2019-10-04 11:19 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinPresenter.kt
> +            coinRepository.sendCurrentPriceInfo(marketName!!)
네 loadData를 분리하면서 해당 이슈 해결되었습니다. 2e69fb4

2019-10-04 11:22 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinFragment.kt
> +    override fun setData(data: List<UseCoinModel>) {
네 수정했습니다!
5e621f9ab3ac8609ec7016b00e31c813caa0b0aa

2019-10-04 11:24 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinMainPresenter.kt
> +            .subscribe({view.setData(it)},{
네 수정했습니다.
649102617b2e3018ec057e3308bd3b73ebf9ff55

2019-10-04 11:25 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinPresenter.kt
> +    override val compositeDisposable by lazy { CompositeDisposable() }
무조건 사용되는 객체이기 때문에 사용되는 시점에 생성되도록 lazy를 사용하였습니다.
lazy보다 그냥 초기화시키는게 좋을까요?

2019-10-04 11:30 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinPresenter.kt
>          } as ArrayList<UseCoinModel>
네 맞습니다. 버릇이 되버렸네요....
수정했습니다 ! 
9a1642f46643cd1a506b5af35f32c34822bee00e

2019-10-04 11:30 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/MainActivity.kt
>          tabLayout.apply {
네 감사합니다!
f9576706bbe3e4ef5f59c2c8bd18153c8cfafe31

2019-10-04 11:31 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/MainActivity.kt
> +            addOnPageChangeListener(object : TabLayout.TabLayoutOnPageChangeListener(tabLayout) {})
앗! 감사합니다.
5ed332fd9b3d31f0d0a24e6a456660a4bf1311fa

2019-10-04 11:34 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/MainActivity.kt
>          if (toast.view.isShown) {
맞습니다.!!! 한번 생성된 객체로 했어야했는데...
수정했습니다.
7e7048119b0c0dcaf065f876189cc0b1c96d964f

2019-10-04 11:36 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/MainActivity.kt
> +    private fun refineData(marketData: List<Market>): ArrayList<String> {
네 감사합니다!
09547f11cf274afe6e52214ff2fc95f1fd663e94

2019-10-04 11:37 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/contract/BaseContract.kt
> +        val presenter : T
감사합니다!! 
15f76adf289be5b7aaab2f952161c689af685356

2019-10-04 12:31 UTC, BeokBeok commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/BaseActivity.kt
> +     lateinit var coinMarketNameList: List<String>
접근자를 붙여주시는 것이 좋아요.

2019-10-04 12:31 UTC, BeokBeok commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/BaseActivity.kt
> +        coinViewPager.apply {
run 이 더 좋아보여요.

2019-10-04 12:31 UTC, BeokBeok commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/BaseFragment.kt
> +    var marketName: String? = null
접근자를 붙여주시는 것이 좋아요.

2019-10-04 12:31 UTC, BeokBeok commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/BaseFragment.kt
> +    lateinit var mAdapter: CoinAdapter
맴버변수를 뜻하는 m은 사용하지 않는 것이 좋아요.

2019-10-04 12:31 UTC, BeokBeok commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/BaseFragment.kt
> +        }
apply 를 사용하지 않고 초기화하시는 것이 좋아 보여요.

2019-10-04 12:31 UTC, BeokBeok commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinPresenter.kt
>          return data
data 를 변수로 사용하지 않고 result.map 의 결과를 바로 return 해도 될 것 같아요.

2019-10-04 12:33 UTC, BeokBeok commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinPresenter.kt
> +    override val compositeDisposable by lazy { CompositeDisposable() }
무조건 사용되는 객체라면, 지연 초기화가 아닌 일반 초기화가 적합해보입니다.

다음은 지연 초기화 관련하여 Effective Java 에 나와있는 글입니다.
> 아이템 83. 지연 초기화는 신중히 사용하라.
지연초기화는 양날의 검이다. 클래스 혹은 인스턴스 생성 시의 초기화 비용은 줄지만 그 대신 지연 초기화하는 필드에 접근하는 비용은 커진다. 지연 초기화하려는 필드들 중 결국 초기화가 이뤄지는 비율에 따라, 실제 초기화에 드는 비용에 따라, 초기화된 각 필드를 얼마나 빈번히 호출하느냐에 따라 지연 초기화가 (다른 수많은 최적화와 마찬가지로) 실제로는 성능을 느려지게 할 수도 있다.
그럼에도 지연 초기화가 필요할 때가 있다. **해당 클래스의 인스턴스 중 그 필드를 사용하는 인스턴스의 비율이 낮은 반면, 그 필드의 초기화하는 비용이 크다면 지연 초기화가 제 역할을 해줄 것이다.** 하지만 안타깝게도 정말 그런지를 알 수 있는 유일한 방법은 지연 초기화 적용 전후의 성능을 측정해보는 것이다.
...
**대부분의 상황에서 일반적인 초기화가 지연 초기화보다 낫다.**

2019-10-04 12:40 UTC, BeokBeok commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/MainActivity.kt
> +import android.util.Log
불필요한 import 는 제거해주세요.

2019-10-04 12:43 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinPresenter.kt
> +    override val compositeDisposable by lazy { CompositeDisposable() }
감사합니다 !!!
a85d9c235fce8036916e4442aec60eb85232c751

2019-10-04 12:48 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinPresenter.kt
>          return data
86303cbdfa9fb457dbe0b4fddff9d146d12c5cc7

2019-10-04 12:48 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/BaseActivity.kt
> +     lateinit var coinMarketNameList: List<String>
7fad254fe5da769b88de6f06bbc5a8f95f7ae657

2019-10-04 12:48 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/BaseActivity.kt
> +        coinViewPager.apply {
7da11a3327190a96cdf81b1dcd319df5e5c2e428

2019-10-04 12:49 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/BaseFragment.kt
> +    var marketName: String? = null
85d60c463bd7d5ccbed7b10797fa30c568c806ef

2019-10-04 12:51 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/BaseFragment.kt
> +    lateinit var mAdapter: CoinAdapter
5f791b009771c04d73056584144bff6b55003377

2019-10-04 12:51 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/BaseFragment.kt
> +        }
0cd871ae2fbcf7c45d945f3d03ed262fb6bf1be7

2019-10-04 12:52 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinPresenter.kt
>          return data
86303cbdfa9fb457dbe0b4fddff9d146d12c5cc7

2019-10-04 12:53 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/MainActivity.kt
> +import android.util.Log
네 제거되었습니다.
( 커밋을 잘 못 했던 것 같습니다. )

2019-10-04 12:56 UTC, BeokBeok commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/MainActivity.kt
> +import android.util.Log
적용이 안된 것 같은데 확인 부탁드려요

2019-10-04 13:20 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/MainActivity.kt
> +import android.util.Log
엇... 변경되어있습니다!
변경할게 없어서 찾던중 =을 사용하여 코드 변경하지 않은 부분이 있어서 수정했습니다.
bcdda440b2e5a331a2cf11c2c634593fc32c9c20

2019-10-04 14:09 UTC, BeokBeok submitted a review, later dismissed
LGTM:ok_hand:

2019-10-06 02:08 UTC, sjjeong requested changes

2019-10-06 02:08 UTC, sjjeong commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/BasePresenter.kt
> +) : BaseContract.Presenter<BaseContract.View> {
BaseContract.View를 Generic으로 받아야 합니다.

2019-10-07 01:17 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/BasePresenter.kt
> +) : BaseContract.Presenter<BaseContract.View> {
네 수정했습니다.
d6aa505

2019-10-08 09:16 UTC, sjjeong commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/BasePresenter.kt
> +) : BaseContract.Presenter<BaseContract.View> {
ㅋㅋ 뭔가 의도한 것과 다르게 처리 하셨지만 잘 하셨네요

2019-10-08 09:16 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-10-10 01:11 UTC, merged