HW-5 BasePresenter, BaseView 추가
sjjeong/GoogryAndroidArchitecutreStudy pull request #218
Opened 2019-09-29 15:14 UTC by jskim5923

* 각 CoinPresenter, MainPresenter에서 공통적으로 사용하는 view 객체와 compositeDisposable 객체, clearCompositeDisposable()함수의 생성을 명세하는 BasePresenter를 추가하였습니다.
* presenter 객의 생성을 ㅁ여세하는 BaseView를 추가하였습니다.

2019-10-01 04:48 UTC, seonoh commented
종선님 수고하셨습니다!
저는 BaseContract를 만들면서 최대한 공통으로 뺄 수 있는걸 빼다보니 좀 이상하다는 생각이 들었는데,
종선님이 하신 것을 보니 종선님처럼 코딩하는 것이 나을 것 같아서 제 쪽 코드를 변경했습니다.
매번 종선님 따라가다보니... 제가 리뷰해드릴게 없어서 너무 죄송합니다!!

2019-10-01 08:30 UTC, BeokBeok requested changes
안녕하세요. 스터디 2기 강현석이라고 합니다.
부족하지만 잘 부탁드립니다. 😅

2019-10-01 08:30 UTC, BeokBeok commented on jskim5923/ArchitectureStudy/app/src/main/java/com/jskim5923/architecturestudy/main/MainPresenter.kt
>      override fun clearCompositeDisposable() {
= 을 사용하시면 한 줄로 표현이 가능할 것 같아요.
https://kotlinlang.org/docs/reference/coding-conventions.html#function-formatting

2019-10-01 08:30 UTC, BeokBeok commented on jskim5923/ArchitectureStudy/app/src/main/java/com/jskim5923/architecturestudy/coin/CoinFragment.kt
> +    override val presenter by lazy {
이부분은 저도 고민이 되는 부분인데
지연 초기화는 해당 인스턴스의 사용 비율이 낮으면서, 초기화하는 비용이 큰 경우에 사용하는 것으로 알고 있는데
presenter 는 사용 비율이 크기 때문에, 지연 초기화가 아니라 일반적인 초기화가 낫지 않을까 생각이 듭니다.
종선님의 생각은 어떠신지 궁금하네요

2019-10-01 14:01 UTC, jskim5923 commented on jskim5923/ArchitectureStudy/app/src/main/java/com/jskim5923/architecturestudy/main/MainPresenter.kt
>      override fun clearCompositeDisposable() {
리뷰 감사합니다!
리턴 타입이 `Unit`인 경우에도 =로 식표현이 가능했었군요 !
남겨주신 링크를 확인해보면 주로 return  type이 있는 경우에 `Expression body fomatting`을 사용 하는 것 같은데요.
제 고정관념때문인진 모르겠지만, `Expression body formatting`은 return type이 있는 (Unit이 아닌 경우)함수에서만 사용하는 것이 구분하기가 쉬워보이는데, return type이 Unit인 경우에도 `Expression body formatting` 으로 사용하는 것이 coding convension에 맞는 걸까요?
확인 부탁드립니다.
확인 해주시는데로 수정 하도록 하겠습니다.

2019-10-01 14:24 UTC, jskim5923 commented on jskim5923/ArchitectureStudy/app/src/main/java/com/jskim5923/architecturestudy/coin/CoinFragment.kt
> +    override val presenter by lazy {
리뷰 감사합니다!
약간 습관처럼(?) 쓰기도 했고, presenter에 View를 주입 시켜줄 때, this가 lifeCycle에 따라 초기화를 해줘야 한다고, 잘못 생각 했던 것 같습니다. 사실 프로퍼티들을 by lazy로 초기화위임해주는 코드(presenter가 아니라)를 좀 고민이 되긴 하는데, lifecycle에 따르지 않기도 하고, 현석님 말씀에 공감이 많이 됩니다!

857678e

2019-10-01 14:38 UTC, jskim5923 commented
> 종선님 수고하셨습니다!
> 저는 BaseContract를 만들면서 최대한 공통으로 뺄 수 있는걸 빼다보니 좀 이상하다는 생각이 들었는데,
> 종선님이 하신 것을 보니 종선님처럼 코딩하는 것이 나을 것 같아서 제 쪽 코드를 변경했습니다.
> 매번 종선님 따라가다보니... 제가 리뷰해드릴게 없어서 너무 죄송합니다!!

2019-10-01 14:47 UTC, BeokBeok submitted a review, later dismissed
LGTM:ok_hand:

2019-10-01 14:47 UTC, BeokBeok commented on jskim5923/ArchitectureStudy/app/src/main/java/com/jskim5923/architecturestudy/main/MainPresenter.kt
>      override fun clearCompositeDisposable() {
이 부분은 사실 정답은 없는 것 같아요.
저는 단지 리턴타입이 Unit 이여도 = 을 사용하여 한 줄로 표현이 가능하다는 것을 말씀드리고 싶었습니다.

예전에 정흠님에게도 리뷰를 해드렸었는데, 종선님과 유사하게 생각하고 계시더라구요.
해서, 이부분은 종선님의 판단에 맡기겠습니다. 👍

2019-10-02 05:44 UTC, jskim5923 commented on jskim5923/ArchitectureStudy/app/src/main/java/com/jskim5923/architecturestudy/main/MainPresenter.kt
>      override fun clearCompositeDisposable() {
몰랐던 정보 알려주셔서 감사합니다! 
일단 이 부분은 알고만 있다가 추후 협업하시는 분들과 coding convension에 따라서 사용하는 거롤 하겠습니다!

2019-10-04 07:34 UTC, sjjeong requested changes
abstract class BasePresenter, abstract class BaseActivity, abstract class BaseFragment를 만들어야 합니다.

2019-10-05 08:04 UTC, jskim5923 commented
* BaseView / BasePresenter 인터페이스를 BaseContract.View / BaseContract.Presenter로 변경하였습
니다. 
47dd04e

* BasePresenter 추상클래스를 추가하였습니다. 
a56870b

* BaseActivity 추상 클래스를 추가하였습니다. 
8376cc1

* BaseFragment 추상클래스를 추가하였습니다. 
639c0ff

2019-10-06 03:41 UTC, sjjeong requested changes

2019-10-06 03:41 UTC, sjjeong commented on jskim5923/ArchitectureStudy/app/src/main/java/com/jskim5923/architecturestudy/base/BaseActivity.kt
> +    abstract val layoutRes: Int
코틀린에서는 생성자로 받을 수 있습니다.

2019-10-06 03:41 UTC, sjjeong commented on jskim5923/ArchitectureStudy/app/src/main/java/com/jskim5923/architecturestudy/base/BaseActivity.kt
> +    abstract override fun initView()
이 함수는 BaseContract.View에 있기 때문에 BaseActivity에 추가하지 않아도 됩니다.

2019-10-06 06:14 UTC, jskim5923 commented on jskim5923/ArchitectureStudy/app/src/main/java/com/jskim5923/architecturestudy/base/BaseActivity.kt
> +    abstract val layoutRes: Int
4561ef1 적용했습니다.

2019-10-06 06:15 UTC, jskim5923 commented on jskim5923/ArchitectureStudy/app/src/main/java/com/jskim5923/architecturestudy/base/BaseActivity.kt
> +    abstract override fun initView()
153f76a 적용했습니다.

2019-10-08 09:17 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-10-08 10:55 UTC, merged