HW-5 Base 생성
sjjeong/GoogryAndroidArchitecutreStudy pull request #219
Opened 2019-09-30 02:09 UTC by toctocbin

Rebase해서 수정해보려다가.... 커밋기록이 엄청나게 꼬여버렸습니다....
이 세개 봐주시면 됩니다 !!
6d5c90a
1c355cd
c413a65

2019-10-04 00:51 UTC, junghum21 commented
수고하셨습니다!

2019-10-04 01:16 UTC, BeokBeok requested changes
안녕하세요. 스터디 2기 강현석입니다.
부족하지만 잘 부탁드립니다. 😅

2019-10-04 01:16 UTC, BeokBeok commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/base/BaseFragment.kt
> +    ): View? {
= 을 사용하시면 한 줄로 표현할 수 있을 것 같습니다.

2019-10-04 01:16 UTC, BeokBeok commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/base/BaseFragment.kt
> +
공백은 한 줄로 표현하시는 것이 좋을 것 같아요.

2019-10-04 01:16 UTC, BeokBeok commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/ui/market/MarketActivity.kt
> +    override val presenter by lazy { MarketPresenter(this) }
lazy 보다 일반 초기화가 더 좋아 보입니다.

2019-10-04 01:16 UTC, BeokBeok commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/ui/market/MarketActivity.kt
> +        presenter.clearDisposable()
clearDisposable 함수를 먼저 호출하시는 것이 좋아요.

2019-10-04 01:16 UTC, BeokBeok commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/ui/ticker/TickerFragment.kt
> +    private val marketSearch by lazy { arguments!!.getString(MARKET_SEARCH) }
lazy 보다 일반초기화를 하시는 것이 좋아보입니다.

2019-10-04 01:16 UTC, BeokBeok commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/ui/ticker/TickerPresenter.kt
>      private val disposables by lazy { CompositeDisposable() }
lazy 보다 일반 초기화가 더 좋아 보입니다.

2019-10-04 01:16 UTC, BeokBeok commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/base/BaseActivity.kt
> +    abstract fun start()
start 함수가 꼭 필요한가요?
상속받는 Activity에서 onCreate 를 오버라이딩 해서 사용하면 되지 않을까요?

2019-10-04 01:16 UTC, BeokBeok commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/base/BaseFragment.kt
> +    abstract fun start()
start 함수가 꼭 필요한가요?
onActivityCreate 함수를 오버라이딩하여 사용하면 되지 않을까요?

2019-10-04 01:16 UTC, BeokBeok commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/base/BaseFragment.kt
> +    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
onActivityCreate 를 사용하시는 것이 더 좋을 것 같습니다.

2019-10-04 06:00 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/base/BaseFragment.kt
> +    ): View? {
594cfbc

변경했습니다.

2019-10-04 06:01 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/base/BaseFragment.kt
> +    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
7c57818

변경했습니다.

2019-10-04 06:02 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/base/BaseFragment.kt
> +
7c57818

이커밋과 함께 공백 제거 했습니다.

2019-10-04 06:02 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/ui/market/MarketActivity.kt
> +        presenter.clearDisposable()
9564833

변경했습니다.

2019-10-04 06:05 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/base/BaseActivity.kt
> +    abstract fun start()
onCreate를 오버라이딩 해서 사용할때도 private start() 함수를 항상 만들어서 개발을 하다보니 추상메소드를 사용하는 방법도 괜찮은거 같아 사용해봤습니다.

2019-10-04 06:05 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/base/BaseFragment.kt
> +    abstract fun start()
위 Acitivty에서 사용할때와 같이 private start() 함수를 항상 만들어서 개발을 하다보니 추상메소드를 사용하는 방법도 괜찮은거 같아 사용해봤습니다.

2019-10-04 06:11 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/ui/market/MarketActivity.kt
> +    override val presenter by lazy { MarketPresenter(this) }
a910bd9

변경하였습니다.

2019-10-04 06:11 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/ui/market/MarketActivity.kt
> +        presenter.clearDisposable()
9564833

변경했습니다.

2019-10-04 06:55 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/ui/ticker/TickerFragment.kt
> +    private val marketSearch by lazy { arguments!!.getString(MARKET_SEARCH) }
```
override val presenter = TickerPresenter(this, arguments?.getString(MARKET_SEARCH) ?: "")
```
이런식으로 초기화하니 marketSearch가 공백이 들어가네요 어떤 방법으로 해야하나요 ??ㅠㅜ
그리고 lazy 보다 일반 초기화를 선택할땐 어떤 기준으로 하는게 좋을까요 ?

2019-10-04 06:57 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/ui/ticker/TickerPresenter.kt
>      private val disposables by lazy { CompositeDisposable() }
934990c

적용했습니다.

2019-10-04 08:03 UTC, BeokBeok commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/ui/ticker/TickerFragment.kt
> +    private val marketSearch by lazy { arguments!!.getString(MARKET_SEARCH) }
해당 현상은 화면 생성 관련 이벤트가 호출되기 전에 초기화를 시도하여 발생한 것으로 보입니다.
해서, 말씀하신 presenter 부분만 lazy 로 초기화를 해야 하는 것이 맞아 보입니다.

그리고 지연 초기화와 일반 초기화 중에서 선택하는 기준은 다음 글을 보시면 도움이 될 것 같습니다.
다음은 지연 초기화 관련하여 Effective Java 에 나와있는 글입니다.
> 아이템 83. 지연 초기화는 신중히 사용하라.
지연초기화는 양날의 검이다. 클래스 혹은 인스턴스 생성 시의 초기화 비용은 줄지만 그 대신 지연 초기화하는 필드에 접근하는 비용은 커진다. 지연 초기화하려는 필드들 중 결국 초기화가 이뤄지는 비율에 따라, 실제 초기화에 드는 비용에 따라, 초기화된 각 필드를 얼마나 빈번히 호출하느냐에 따라 지연 초기화가 (다른 수많은 최적화와 마찬가지로) 실제로는 성능을 느려지게 할 수도 있다.
그럼에도 지연 초기화가 필요할 때가 있다. **해당 클래스의 인스턴스 중 그 필드를 사용하는 인스턴스의 비율이 낮은 반면, 그 필드의 초기화하는 비용이 크다면 지연 초기화가 제 역할을 해줄 것이다.** 하지만 안타깝게도 정말 그런지를 알 수 있는 유일한 방법은 지연 초기화 적용 전후의 성능을 측정해보는 것이다.
...
**대부분의 상황에서 일반적인 초기화가 지연 초기화보다 낫다.**

2019-10-04 11:52 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/ui/ticker/TickerFragment.kt
> +    private val marketSearch by lazy { arguments!!.getString(MARKET_SEARCH) }
지연초기화에 대한 정보 감사합니다!
14d1c64
수정했습니다.

2019-10-04 12:21 UTC, BeokBeok submitted a review, later dismissed
LGTM:ok_hand:

2019-10-05 06:28 UTC, toctocbin commented
BaseActivity, BaseFragment, BasePresenter 에서 각각 공통적으로 일어나는 작업을 수행할 수 있도록 수정하였습니다.

2019-10-06 03:43 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-10-06 23:55 UTC, merged