HW-04 Base 추가
sjjeong/GoogryAndroidArchitecutreStudy pull request #221
Opened 2019-10-02 11:38 UTC by junghum21

2019-10-03 23:57 UTC, toctocbin commented
이미 Base를 구현해 놓으셔서 리뷰할게 없어요 ! 수고하셨습니다 !

2019-10-04 01:07 UTC, BeokBeok requested changes
안녕하세요. 스터디 2기 강현석이라고 합니다.
부족하지만 잘 부탁드립니다. 😅

2019-10-04 01:07 UTC, BeokBeok commented on junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/base/BaseContract.kt
> +        )
해당 함수는 사용하지 않는 것으로 보입니다.
사용하지 않는다면 제거해 주시는 것이 좋을 것 같습니다.

---

Higher Order Function 으로 Fail 시 throwable 을 전달하는데
막상 throwable 을 활용하지 않고 string 리소스를 참조하여 toast 를 띄우는 것으로 보이는데
전달하신 throwable 을 활용하시는 것이 좋을 것 같습니다.

2019-10-04 01:07 UTC, BeokBeok commented on junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/base/BaseContract.kt
> +        fun onCreate()
onCreate 는 뭔가 View의 느낌이 강하게 오는데
혹시 다른 이름을 사용하시는 것은 어떠신가요?

2019-10-04 01:07 UTC, BeokBeok commented on junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/base/BaseContract.kt
> +
공백은 한 줄 단위로 해주시면 좋을 것 같아요.

2019-10-05 02:56 UTC, junghum21 commented on junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/base/BaseContract.kt
> +        fun onCreate()
start() 는 어떨까요?

2019-10-05 03:18 UTC, junghum21 commented on junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/base/BaseContract.kt
> +        )
질문의 의도를 정확하게 파악하지 못했습니다.

자세한 설명 부탁드립니다.

2019-10-07 01:26 UTC, junghum21 commented on junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/base/BaseContract.kt
> +
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/221/commits/3070e3c1c4232bc2e7675589cb8641af8434867d

반영완료

2019-10-07 01:27 UTC, junghum21 commented on junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/base/BaseContract.kt
> +        fun onCreate()
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/221/commits/ed461148471758ec717b66a689b0e24a4814d78e

반영완료

2019-10-07 10:03 UTC, BeokBeok commented on junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/base/BaseContract.kt
> +        )
단순하게 말씀드리자면, TickersPresenter 에서 getTickers 함수를 호출할 때
```
repository.getTicker(
            marketName,
            { response ->
                val tickers = response.map { it.toTicker() }
                view.setTickers(tickers)
            },
            {
                view.showToast(R.string.fail_network)
            }
        )
```
여기서 showToast 함수를 호출하는데
it (throwable) 을 사용하지 않고 string 리소스를 가지고 처리한 이유가 궁금합니다.

2019-10-08 02:55 UTC, junghum21 commented on junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/base/BaseContract.kt
> +        )
에러의 종류에 상관없이 '네트워크 오류' 라고 일괄 처리했기 때문입니다.

Throwable을 활용해서 message나 stackTrace를 활용하는게 좋겠다는 말씀인가요?

2019-10-08 03:21 UTC, BeokBeok commented on junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/base/BaseContract.kt
> +        )
**에러의 종류에 상관없이** 일괄처리하신거라면 
throwable 을 failure 의 인자로 전달하는 의미가 없지 않나요?

인자를 활용하시려면, throwable 을 활용하시는 것이 좋고
인자를 활용하지 않으실 것이라면, 인자에 아무것도 전달하지 않는 것이 좋을 것 같아요.

다만, 개인적인 생각을 말씀드리자면
에러에 대한 처리는, 가능한 한 해주시는 것이 좋을 것 같아요.

2019-10-08 05:09 UTC, junghum21 commented on junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/base/BaseContract.kt
> +        )
https://github.com/junghum21/GoogryAndroidArchitectureStudy/blob/4002bddfa4cbb5f624a720aa72b722fa4de7128f/junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/data/source/UpbitRemoteDataSource.kt#L48

RemoteDataSource 단에서 네트워크 요청 실패시 Throwable#printStackTrace() 호출합니다.

지적해주신대로 throwable을 사용하지 않는데 무의미하게 인자로 넘겨주고 있네요.

throwable을 에러로그 찍는것 말고 다른 활용 방법이 있을까요?

2019-10-08 08:07 UTC, BeokBeok commented on junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/base/BaseContract.kt
> +        )
printStackTrace 함수는 
프로그램의 내부 구조를 쉽게 파악할 수 있기 때문에
가급적이면 사용하지 않는 것을 권장합니다.

---

[한국인터넷진흥원 Android-JAVA 시큐어코딩 가이드](http://www.kisa.or.kr/jsp/common/downloadAction.jsp?bno=259&dno=53&fseq=1) 22p. 참고

---

throwable 활용 방법에 대해서는 많이 있겠지만,
에러로그 찍는 것 외에 throwable 의 상세 메시지에 실패 관련 정보를 담아서
에러 발생 시, 보다 유연하게 대처할 수 있지 않을까 싶습니다.

2019-10-08 10:08 UTC, junghum21 commented on junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/base/BaseContract.kt
> +        )
네 조언 고맙습니다.

참고하겠습니다.

2019-10-08 11:06 UTC, BeokBeok approved these changes
LGTM:ok_hand:

2019-10-08 11:06 UTC, BeokBeok commented on junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/base/BaseContract.kt
> +        )
본래의 리뷰 사항보다 부가적으로 리뷰드린 사항이 주가 된 느낌이네요.
이 부분에 대해서는 다음 주차에 수정해주시면 좋을 것 같습니다.

2019-10-10 01:40 UTC, merged