HW-8 LiveData 추가
sjjeong/GoogryAndroidArchitecutreStudy pull request #222
Opened 2019-10-06 10:04 UTC by zojae031

늦게 올리게되어 죄송합니다!

2019-10-11 09:31 UTC, sjjeong requested changes

2019-10-11 09:31 UTC, sjjeong commented on zojae031/Project/app/src/main/java/study/architecture/coinjob/CoinFragment.kt
> +                lifecycleOwner = this@CoinFragment
lifecycleOwner는 base쪽에서 넣어주세요

2019-10-11 09:31 UTC, sjjeong commented on zojae031/Project/app/src/main/java/study/architecture/mainjob/MainActivity.kt
> +            lifecycleOwner = this@MainActivity
Base쪽에서 넣어주세요

2019-10-12 05:12 UTC, zojae031 commented on zojae031/Project/app/src/main/java/study/architecture/mainjob/MainActivity.kt
> +            lifecycleOwner = this@MainActivity
add7323

2019-10-12 05:12 UTC, zojae031 commented on zojae031/Project/app/src/main/java/study/architecture/coinjob/CoinFragment.kt
> +                lifecycleOwner = this@CoinFragment
add7323

2019-10-13 05:14 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-10-13 10:07 UTC, wkdehdlr approved these changes
LGTM

2019-10-13 12:48 UTC, merged