HW8 - 코인헬퍼 AAC 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #223
Opened 2019-10-06 17:01 UTC by dlwls5201

AAC의 ViewModel과 LiveData를 사용해 기존 MVVM을 수정했습니다.

2019-10-07 11:51 UTC, preludezdev reviewed
피드백 남겼습니다~

2019-10-07 11:51 UTC, preludezdev commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/ui/main/MainActivity.kt
>      }
최신 lifecycle-extensions 라이브러리에 ViewModelProviders 클래스가 deprecated 됐다네요. 대신 ViewModelProvider 클래스로 뷰모델을 가져올 수 있다고 합니다. 

https://developer.android.com/jetpack/androidx/releases/lifecycle#2.2.0-alpha03

2019-10-07 11:51 UTC, preludezdev commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/ui/main/MainActivity.kt
> +        binding.lifecycleOwner = this
lifecycleOwner 등록을 Base 에서 하는 것도 괜찮을 것 같아요

2019-10-07 11:51 UTC, preludezdev commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/ui/main/MainViewModel.kt
>      }
앱 처음 실행할 때 화살표 하나 정도 띄워서 필터링 가능하다는 걸 보여주면 좋을것 같아요

2019-10-07 15:35 UTC, dlwls5201 commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/ui/main/MainActivity.kt
>      }
수정했습니다.

commit : f0fec72

2019-10-07 15:35 UTC, dlwls5201 commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/ui/main/MainActivity.kt
> +        binding.lifecycleOwner = this
수정했습니다.

commit : 226cb1c

2019-10-07 15:36 UTC, dlwls5201 commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/ui/main/MainViewModel.kt
>      }
현재 구조에서는 하드코딩으로 밖에 작업을 못하겠네요. 다른 구조로 더 생각해 봐야 겠습니다.

commit : 59fbe6f

2019-10-07 16:40 UTC, preludezdev commented
멘토 리뷰까지 끝나면 바로 Approve 하겠습니다
고생하셨습니다 : )

2019-10-08 01:00 UTC, BeokBeok requested changes
안녕하세요. 스터디 2기 강현석이라고 합니다.
부족하지만 잘 부탁드립니다. 😅

2019-10-08 01:00 UTC, BeokBeok commented on dlwls5201/MyArchitecture/app/build.gradle
>      implementation "androidx.appcompat:appcompat:$supportLibraryVersion"
이 dependency 는 없어도 될 것 같아요.

2019-10-08 01:00 UTC, BeokBeok commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/base/BaseActivity.kt
> +        //setOrientationToPortrait()
주석은 제거하시는 것이 좋을 것 같아요.

2019-10-08 01:00 UTC, BeokBeok commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/base/BaseViewModel.kt
> +open class BaseViewModel : ViewModel() {
abstract 를 사용하지 않고 open 을 사용하신 이유가 있나요?

2019-10-08 01:00 UTC, BeokBeok commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/ui/main/MainActivity.kt
>      private val mainAdapter: MainAdapter by lazy {
일반초기화 대신 지연초기화를 하신 이유가 있나요?

2019-10-08 01:00 UTC, BeokBeok commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/ui/main/MainAdapter.kt
>          return titles?.get(position)
= 을 사용하시면 중괄호를 제거할 수 있어요.

2019-10-08 01:00 UTC, BeokBeok commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/ui/main/MainViewModelFactory.kt
> +        return MainViewModel(upbitRepository) as T
= 을 사용하시면 중괄호를 제거할 수 있어요.

2019-10-08 01:00 UTC, BeokBeok commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/ui/tickerlist/TickerListViewModel.kt
> +                    mTickers.addAll(_tickers.value!!)
_tickers.value 가 null 인 경우가 100% 없다면 다행이겠지만,
가급적이면 not-null assertion (!!) 은 가능한 한 지양하시는 것이 좋을 것 같아요.

2019-10-09 04:28 UTC, dlwls5201 commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/base/BaseActivity.kt
> +        //setOrientationToPortrait()
제거했습니다.
commit : 67caee8

2019-10-09 04:29 UTC, dlwls5201 commented on dlwls5201/MyArchitecture/app/build.gradle
>      implementation "androidx.appcompat:appcompat:$supportLibraryVersion"
제거했습니다. appcompat를 제거해도 될지는 생각도 못했네요..

commit : ded0e30

2019-10-09 04:31 UTC, dlwls5201 commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/base/BaseViewModel.kt
> +open class BaseViewModel : ViewModel() {
이 부분은 제가 크게 생각을 하지 않고 open으로 만들었습니다. BeokBeok님 말씀대로 상속으로 사용한다면 open 보다는 가능하면 abstract로 만드는것이 더 나을 것 같습니다.

commit : 03b2e59

2019-10-09 04:32 UTC, dlwls5201 commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/ui/main/MainActivity.kt
>      private val mainAdapter: MainAdapter by lazy {
사용되는 시점에 초기화를 하고 싶어서 사용했습니다.

2019-10-09 04:34 UTC, dlwls5201 commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/ui/main/MainAdapter.kt
>          return titles?.get(position)
수정했습니다.

commit : 02b8458

2019-10-09 04:36 UTC, dlwls5201 commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/ui/main/MainViewModelFactory.kt
> +        return MainViewModel(upbitRepository) as T
수정했습니다.

commit : 0f06058

2019-10-09 04:37 UTC, dlwls5201 commented on dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/ui/tickerlist/TickerListViewModel.kt
> +                    mTickers.addAll(_tickers.value!!)
위 로직에서 _tickers.value 사용되기 이전에 초기화를 해주기 때문에 100% 아닐꺼라 생각해서 not-null assertion (!!)를 선언했습니다.

2019-10-09 15:12 UTC, BeokBeok approved these changes
LGTM:ok_hand:

2019-10-11 09:18 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-10-12 04:10 UTC, preludezdev approved these changes
고생하셨습니다 XD

2019-10-13 05:01 UTC, merged