HW-8 코인헬퍼 AAC ViewModel & LiveData 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #225
Opened 2019-10-07 11:15 UTC by preludezdev

- 기존 프로젝트에 AAC ViewModel 과 LiveData를 적용했습니다
- 보기에 조금 칙칙한거 같아서 글씨 색깔하고 크기 변경했습니다

2019-10-07 15:13 UTC, dlwls5201 commented on preludezdev/ArchitectureStudy/app/build.gradle
> +    implementation 'androidx.lifecycle:lifecycle-common:2.2.0-alpha05'
lifecycle-common은 추가로 import 해주지 않아도 될 것 같습니다.

2019-10-07 15:15 UTC, dlwls5201 commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/market/MarketFragment.kt
> +                ) as T
@Suppress("UNCHECKED_CAST")  해주세요

2019-10-07 15:22 UTC, dlwls5201 commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/viewmodel/MarketViewModel.kt
> +                    _isProgressed.value = false // 프로그래스바 종료
프로그래스바 시작과 종료를 따로 함수로 만들어서 쓰면 어떨까요?
ex) showProgress(), hideProgress()

2019-10-07 15:31 UTC, dlwls5201 commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/viewmodel/MarketViewModel.kt
>      private fun onFailCallback(errorMsg: String) {
단순 토스트를 보여주는 기능인것 같아보여 onFailCallback 함수명보다는 다른게 나은 것 같습니다.
이 함수는 얼마든지 토스트를 보여주는 기능으로 재 사용할 수 있을 것 같습니다.

2019-10-07 15:32 UTC, dlwls5201 reviewed
xml이 더욱 화사해진것 같습니다. 
AAC 관련되서는 전 리뷰할게 없네요. 오히러 더 배워갑니다.

2019-10-07 16:47 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/build.gradle
> +    implementation 'androidx.lifecycle:lifecycle-common:2.2.0-alpha05'
lifecycle-common 대신 lifecycle-extension 으로 변경해서 import 해주었습니다

commit : f0e9dbc

2019-10-07 16:47 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/market/MarketFragment.kt
> +                ) as T
수정했습니다

commit : e87a5da

2019-10-07 16:48 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/viewmodel/MarketViewModel.kt
> +                    _isProgressed.value = false // 프로그래스바 종료
수정했습니다

commit : 92d56f3

2019-10-07 16:48 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/viewmodel/MarketViewModel.kt
>      private fun onFailCallback(errorMsg: String) {
수정했습니다 

commit : 4279463

2019-10-10 03:02 UTC, BeokBeok requested changes
안녕하세요. 스터디 2기 강현석이라고 합니다.
부족하지만 잘 부탁드립니다. 😅

2019-10-10 03:02 UTC, BeokBeok commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/viewmodel/MarketViewModel.kt
> +        _notificationMsg.value = errorMsg
가령, "데이터를 불러올 수 없습니다" 라는 에러가 여러 번 발생했을 때에는
String 이 동일하므로 토스트가 한 번만 발생할 것으로 보입니다.

예를 들면, KRW 와 ETH 를 둘 다 데이터를 불러오지 못하는 상황이라 가정했을 때
KRW 데이터 불러올 시 "데이터를 불러올 수 없습니다" 토스트가 뜨지만
ETH 데이터 불러올 시에는 토스트가 발생하지 않을 것으로 보입니다.

해서, 이 부분에 대해서 수정이 필요해보입니다.

2019-10-10 03:02 UTC, BeokBeok commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/market/MarketFragment.kt
> +                Toast.makeText(context, msg, Toast.LENGTH_LONG).show()
토스트 관련 함수는 Base 에 있거나, Extension 으로 처리하셔도 좋을 것 같습니다.

2019-10-10 03:02 UTC, BeokBeok commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/market/MarketFragment.kt
> +                ) as T
return 대신 = 을 사용하여 정리할 수 있을 것 같습니다.

2019-10-10 03:02 UTC, BeokBeok commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/main/VpAdapter.kt
>          return MarketFragment.newInstance(
= 을 사용하셔서 중괄호를 없앨 수 있을 것 같아요.

2019-10-10 03:02 UTC, BeokBeok commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/network/RetrofitHelper.kt
>              return INSTANCE ?: RetrofitHelper()
INSTANCE 변수는 항상 null 이지 않나요?

2019-10-10 04:32 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/main/VpAdapter.kt
>          return MarketFragment.newInstance(
수정했습니다

commit : a90d29d

2019-10-10 04:32 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/network/RetrofitHelper.kt
>              return INSTANCE ?: RetrofitHelper()
수정했습니다

commit : 4c7b80a

2019-10-10 04:37 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/viewmodel/MarketViewModel.kt
> +        _notificationMsg.value = errorMsg
데이터를 불러오는 CoinRemoteDataSource 클래스에서 데이터 요청 실패시 마켓별로 다른 에러메세지를 생성해 fail 콜백함수에 담게끔 수정했습니다.

commit : 2605da0 , 49d5729

2019-10-10 04:39 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/market/MarketFragment.kt
> +                Toast.makeText(context, msg, Toast.LENGTH_LONG).show()
Base 에 토스트메세지를 띄울 수 있게 수정했습니다. 혹시 Extension 으로 처리하려면 어떻게 코딩해야 하는지 여쭤봐도 될까요?

commit : 77a68bb

2019-10-10 06:11 UTC, BeokBeok commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/market/MarketFragment.kt
> +                Toast.makeText(context, msg, Toast.LENGTH_LONG).show()
이런 식으로 하시면 되지 않을까 싶습니다.

```
// FragmentExt.kt
fun Fragment.showToast(msg: String) {
    Toast.makeText(requireContext(), msg, Toast.LENGTH_SHORT).show()
}
```

```
//MarketFragment.kt

if (!msg.isNullOrEmpty()) {
        showToast(msg)
}
```

2019-10-10 06:16 UTC, BeokBeok commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/viewmodel/MarketViewModel.kt
> +        _notificationMsg.value = errorMsg
target 이 동일한 경우에도 동일한 현상이 발생할 것 같습니다.
해서, Throwable 에 메시지를 담아서 처리하시면 좋을 것 같아요.

```
onFail: (t: Throwable) -> Unit
```

2019-10-10 08:34 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/viewmodel/MarketViewModel.kt
> +        _notificationMsg.value = errorMsg
- 말씀해주신대로 Throwable 에 메세지를 담아서 처리하려고 했는데 결국 해당 메세지를 토스트로 띄우면 target 이 동일한 경우에도 같은 현상이 발생하게 될 것 같네요. 혹시 메세지를 담아서 예외처리하라는게 토스트 대신 Throwable 클래스의 printStackTrace() 함수를 이용하라는 의미신지 궁금합니다. 

- 궁금해서 빈프로젝트 파서 라이브데이터에 같은 문자열을 setValue() 해서 테스트해봤는데 라이브데이터에 같은 문자열이 set 되도 observe 콜백으로 호출이 되서 토스트가 여러번 발생되는걸 확인했습니다. 혹시 이게 문제가 안된다면 이전에 했던 코드방식으로 작업해도 괜찮은건가요?

commit : 6e0a9ce

2019-10-10 08:35 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/market/MarketFragment.kt
> +                Toast.makeText(context, msg, Toast.LENGTH_LONG).show()
확인했습니다. 감사합니다!

2019-10-10 08:44 UTC, BeokBeok commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/viewmodel/MarketViewModel.kt
> +        _notificationMsg.value = errorMsg
> 말씀해주신대로 Throwable 에 메세지를 담아서 처리하려고 했는데 결국 해당 Throwable 의 메세지를 토스트로 띄우면 같은 Throwable 메세지에 대해서 같은 현상이 발생할 것 같네요. 혹시 메세지를 담아서 예외처리하라는게 토스트 대신 Throwable 클래스의 printStackTrace() 함수를 이용하라는 의미신지 궁금합니다.

A: String 이 아닌 Throwable 을 라이브데이터로 처리하시면,
에러 메시지는 같더라도 Throwable 객체가 다르기 때문에 값이 변했다고 판단하여
동일 메시지에도 observe 가 동작한다는 것을 말씀드리고 싶었습니다.
또한, printStackTrace 함수가 아닌 throwable의 message  사용을 의미였습니다.
printStackTrace 는 시큐어코딩에 적합하지 않으므로, 사용을 권장하지 않습니다.

> 궁금해서 빈프로젝트 파서 라이브데이터에 같은 문자열을 setValue() 해서 테스트해봤는데 라이브데이터에 같은 문자열이 setValue 되도 observe 콜백으로 호출이 되서 토스트가 여러번 발생하는걸 확인했습니다. 혹시 이게 문제가 안된다면 이전에 했던 코드방식으로 작업해도 괜찮은건가요?

A: 제가 스터디 했을 때에는 String 으로 에러 메시지를 라이브데이터로 처리했었는데
동일한 String 인 경우에는 한 번만 observe 가 되고 그 이후에는 observe 가 되지 않아서 
고민하다가 throwable 로 처리한 경험이 있습니다.
만약, 동작이 된다면 이전 방식으로 하셔도 될 것 같습니다.

2019-10-10 09:06 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/viewmodel/MarketViewModel.kt
> +        _notificationMsg.value = errorMsg
네 알겠습니다. 심지어 라이브데이터는 data.value = data.value 이렇게 자기 데이터를 setValue() 해줘도 observe가 되더라구요. 이쯤되면 observe 콜백은 데이터 변경될 때가 아니라 setValue() 하면 observe 호출된다고 설명해야 하지 않을까 싶네요. 
에러처리 하는 부분은 이전에 문자열로 처리하는 코드로 변경했습니다.

commit : fffca14

2019-10-10 09:46 UTC, BeokBeok commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/viewmodel/MarketViewModel.kt
> +        _notificationMsg.value = errorMsg
태휘님 덕분에 잘못 알고 있는 개념을 바로 잡고 가네요. 😄 
감사합니다. 👍

2019-10-10 09:46 UTC, BeokBeok submitted a review, later dismissed
LGTM:ok_hand:

2019-10-11 09:22 UTC, sjjeong requested changes

2019-10-11 09:22 UTC, sjjeong commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/viewmodel/MarketViewModel.kt
> +    private fun showProgressBar(status: Boolean) {
boolean값을 하나만 전달하는 함수인 경우에는 true/false에 해당하는 함수를 각각 만드는게 좋습니다.
show/hide로 만들어서 해보세요

2019-10-11 10:27 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/viewmodel/MarketViewModel.kt
> +    private fun showProgressBar(status: Boolean) {
수정했습니다

commit : 477c395

2019-10-11 15:24 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-10-13 05:01 UTC, dlwls5201 approved these changes
고생하셨습니다.

2019-10-13 05:07 UTC, merged