HW-8 AAC ViewModel, LiveData 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #226
Opened 2019-10-08 07:00 UTC by wswon

늦게올려서 죄송합니다..

2019-10-09 07:08 UTC, ganghee reviewed
리뷰할게 별로 없네요 😅

2019-10-09 07:08 UTC, ganghee commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/view/coin/CoinListFragment.kt
>  class CoinListFragment : BaseFragment<FragmentCoinlistBinding>(R.layout.fragment_coinlist) {
CoinListFragment객체에서 companion object 있는데 
``` 
companion object {
        fun newInstance() = CoinListFragment()
    }
```
이 부분을 삭제하고 getItem에 CoinListFragment() 넣어도 좋을 것 같아요 해당코드에 리뷰창이 활성화가 안되서 이렇게 남겨요!

2019-10-09 07:08 UTC, ganghee commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/view/coin/CoinListFragment.kt
>      private lateinit var monetaryUnitList: List<String>
변수 부분은 없어도 될 것 같아요 코틀린은 파라미터에 인자가 생성자 역할을 하니 굳이 this를 안써도 됩니다
```
fun setMonetaryUnitList(monetaryUnitList: List<String>) {
        this.monetaryUnitList = monetaryUnitList
        tickerViewModel.getTickerList(this.monetaryUnitList)
    }
```

2019-10-10 14:33 UTC, wswon commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/view/coin/CoinListFragment.kt
>  class CoinListFragment : BaseFragment<FragmentCoinlistBinding>(R.layout.fragment_coinlist) {
fragment 생성은 일반적으로 static method 를 사용하는 것으로 알고있어서 이렇게
사용했습니다.
https://m.blog.naver.com/PostView.nhn?blogId=tpgns8488&logNo=220989078813&proxyReferer=https%3A%2F%2Fwww.google.com%2F

그런데 Bundle을 사용한 객체전달이 필요없을때도 이렇게 사용해야 하는건지는 잘모르겠네요 ㅠ 근데 보통은 Bundle을 사용하지 않더라도 저렇게 많이 쓰더라고요!!

2019-10-10 14:40 UTC, wswon commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/view/coin/CoinListFragment.kt
>      private lateinit var monetaryUnitList: List<String>
cca4428 변수가 필요없어진 것을 몰랐네요.. 제거했습니다.

2019-10-10 16:10 UTC, ganghee reviewed
새로 수정하거나 추가된 코드가 아니면 해당코드에 리뷰할 수 없어서 여기에 남길게요😞

2019-10-10 16:10 UTC, ganghee commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/view/coin/CoinListActivity.kt
>                  }
수정하거나 추가되지 않은 코드를 리뷰할 수 없어서 여기에 남길게요 :)

[item_ticker.xml](https://github.com/wswon/GoogryAndroidArchitectureStudy/blob/cca4428bb8/wswon/AndroidArchitectureStudy/app/src/main/res/layout/item_ticker.xml#L50)

실행은 잘 되지만 context 오류가 나와서
```
android:textColor="@{ticker.compareYesterdayTextColor}"
``` 
로 수정하고

[TickerResponse](https://github.com/wswon/GoogryAndroidArchitectureStudy/blob/cca4428bb8/wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/network/model/TickerResponse.kt#L72)
```
compareYesterdayTextColor = Color.RED
```
로 수정하는 건 어떨까요?

2019-10-10 16:10 UTC, ganghee commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/view/coin/CoinListActivity.kt
>              })
수정하거나 추가되지 않은 코드를 리뷰할 수 없어서 여기에 남길게요 :)

[BaseViewHolder](https://github.com/wswon/GoogryAndroidArchitectureStudy/blob/cca4428bb8/wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/base/BaseViewHolder.kt#L21)
private 추가하는건 어떨까요?

2019-10-10 16:10 UTC, ganghee commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/view/coin/CoinListActivity.kt
>          }
[ic_launcher_foreground](https://github.com/wswon/GoogryAndroidArchitectureStudy/blob/cca4428bb8/wswon/AndroidArchitectureStudy/app/src/main/res/drawable-v24/ic_launcher_foreground.xml)

이 피일을 drawable-v24에 두지 않고 drawable에 두는 건 어떨까요?
이미 최소버젼이 24라서 굳이 폴더를 따로 생성할 필요 없을 것 같아요

2019-10-11 00:34 UTC, wswon commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/view/coin/CoinListActivity.kt
>              })
2b8290c 추가했습니다.

2019-10-11 00:34 UTC, wswon commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/view/coin/CoinListActivity.kt
>                  }
bd90e77  수정했습니다.

2019-10-11 00:34 UTC, wswon commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/view/coin/CoinListActivity.kt
>          }
f4afb8b 폴더를 이동했습니다.

2019-10-11 09:25 UTC, sjjeong requested changes

2019-10-11 09:25 UTC, sjjeong commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/network/model/TickerResponse.kt
> +            compareYesterdayTextColor = ContextCompat.getColor(App.instance.context(), R.color.colorRed)
context를 여기서 가져다가 쓰지말고
BindingAdapter를 만들어서 처리해보세요

2019-10-11 09:25 UTC, sjjeong commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/view/coin/CoinListActivity.kt
> +//        MarketViewModel(CoinRepositoryImpl.getInstance(Injection.provideCoinRemoteDataSource()))
불필요한 주석은 제거해요

2019-10-13 06:25 UTC, wswon commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/network/model/TickerResponse.kt
> +            compareYesterdayTextColor = ContextCompat.getColor(App.instance.context(), R.color.colorRed)
db501ab 반영해봤습니다!

2019-10-13 06:25 UTC, wswon commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/view/coin/CoinListActivity.kt
> +//        MarketViewModel(CoinRepositoryImpl.getInstance(Injection.provideCoinRemoteDataSource()))
ec7f0d8 반영했습니다.

2019-10-14 09:57 UTC, ganghee approved these changes

2019-10-14 11:43 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-10-15 00:11 UTC, merged