HW-5 DataBinding 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #227
Opened 2019-10-08 12:10 UTC by jskim5923

* build.gradle(app)파일에서 `kotlin-android-extensions` 제거 후 DataBinding library 적용하였습니다.

2019-10-10 01:13 UTC, seonoh commented
수고하셨습니다 종선님 !!

2019-10-10 03:26 UTC, BeokBeok requested changes
안녕하세요. 스터디 2기 강현석이라고 합니다.
부족하지만 잘 부탁드립니다. 😅

2019-10-10 03:26 UTC, BeokBeok commented on jskim5923/ArchitectureStudy/app/src/main/java/com/jskim5923/architecturestudy/base/BaseActivity.kt
> +    val layoutRes: Int
접근자를 제거하신 이유가 있나요?

2019-10-10 03:26 UTC, BeokBeok commented on jskim5923/ArchitectureStudy/app/src/main/java/com/jskim5923/architecturestudy/base/BaseFragment.kt
> +    abstract val layoutRes: Int
생성자로 받아서 처리하시는 것이 좋아 보여요.

2019-10-10 03:26 UTC, BeokBeok commented on jskim5923/ArchitectureStudy/app/src/main/java/com/jskim5923/architecturestudy/coin/CoinFragment.kt
>      private var coinListAdapter = CoinListAdapter()
val 로 변경해주시는 것이 좋아요.

2019-10-10 03:26 UTC, BeokBeok commented on jskim5923/ArchitectureStudy/app/src/main/java/com/jskim5923/architecturestudy/main/MainActivity.kt
> +            }
코드를 읽는데 좀 어렵지 않나요?

2019-10-10 03:26 UTC, BeokBeok commented on jskim5923/ArchitectureStudy/app/src/main/res/layout/activity_main.xml
> +    </data>
사용하지 않으신다면 제거하시는 것이 좋을 것 같아요.

2019-10-10 03:26 UTC, BeokBeok commented on jskim5923/ArchitectureStudy/app/src/main/res/layout/item_coin_list.xml
> +            android:paddingEnd="5dp">
4dp 단위로 하시는 것이 좋은 것 같아요.
https://material.io/design/layout/understanding-layout.html#usage

2019-10-10 12:01 UTC, jskim5923 commented on jskim5923/ArchitectureStudy/app/src/main/java/com/jskim5923/architecturestudy/base/BaseActivity.kt
> +    val layoutRes: Int
생성자로 이동하면서 접근자를 뺀 것 같습니다.
[07f9a92] 적용했습니다.

2019-10-10 12:02 UTC, jskim5923 commented on jskim5923/ArchitectureStudy/app/src/main/java/com/jskim5923/architecturestudy/base/BaseFragment.kt
> +    abstract val layoutRes: Int
이 전 과제에서 석준님이 리뷰 해주셨는데, 브랜치 merge과정에서 변경된 걸 놓친 것 같습니다.
[a95aed1] 적용했습니다.

2019-10-10 12:03 UTC, jskim5923 commented on jskim5923/ArchitectureStudy/app/src/main/java/com/jskim5923/architecturestudy/coin/CoinFragment.kt
>      private var coinListAdapter = CoinListAdapter()
[168a545] 적용했습니다.

2019-10-10 12:03 UTC, jskim5923 commented on jskim5923/ArchitectureStudy/app/src/main/res/layout/activity_main.xml
> +    </data>
[b1998f4] 적용했습니다.

2019-10-10 12:03 UTC, jskim5923 commented on jskim5923/ArchitectureStudy/app/src/main/res/layout/item_coin_list.xml
> +            android:paddingEnd="5dp">
[efb9f2d] 적용했습니다.

2019-10-10 12:06 UTC, jskim5923 commented on jskim5923/ArchitectureStudy/app/src/main/java/com/jskim5923/architecturestudy/main/MainActivity.kt
> +            }
뷰 바인딩을 함에 있어, binding.viewPager / binding.tabLayout에 binding.부분이 중복되어, run으로 처리하였는데, 
```
with(binding.viewPager) {
    binding.tabLayout.setUpWithViewPager(this)
    adapter = viewpagerAdapter
```
로 변경하는 것이 나을까요? 
답변 주시면 변경하도록 하겠습니다.

2019-10-10 15:25 UTC, BeokBeok commented on jskim5923/ArchitectureStudy/app/src/main/java/com/jskim5923/architecturestudy/main/MainActivity.kt
> +            }
let 을 활용하여 명시해주는 것이 더 좋을 것 같아요.
```
binding.viewPager.let {
    binding.tabLayout.setUpWithViewPager(it)
    it.adapter = viewpagerAdapter
}
```

다음은 제가 이펙티브 코틀린을 읽으면서 정리했던 글인데
receiver 의 scope 관리때문에 let 이 더 좋을 것 같습니다.
https://www.notion.so/beokbeok/Item-15-receiver-29832d08903d457f86a26d416eec843f

2019-10-10 23:02 UTC, jskim5923 commented on jskim5923/ArchitectureStudy/app/src/main/java/com/jskim5923/architecturestudy/main/MainActivity.kt
> +            }
정보 감사합니다.
[3bb333b] 적용했습니다.

2019-10-11 01:31 UTC, BeokBeok approved these changes
LGTM:ok_hand:

2019-10-11 09:10 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-10-11 09:44 UTC, merged