HW-08 livedata 구현
sjjeong/GoogryAndroidArchitecutreStudy pull request #228
Opened 2019-10-08 16:14 UTC by ganghee

livedata와 viewModel 리펙토링하였습니다

2019-10-10 14:25 UTC, wswon reviewed
저는 정말 달게 없네요 ㅠ
 by viewModels로 처리하는것 보고 배우겠습니다.

2019-10-10 14:25 UTC, wswon commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/ui/MainActivity.kt
> +            lifecycleOwner = this@MainActivity
lifecycleOwner 지정은 BaseActivity에서 하면 좋지않을까요?

2019-10-11 06:52 UTC, ganghee commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/ui/MainActivity.kt
> +            lifecycleOwner = this@MainActivity
네! 수정하였습니다
[MainActivity](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/228/commits/cf2d29d7acf7991fd0043a0d0b867364b0396888)

2019-10-11 09:28 UTC, sjjeong requested changes

2019-10-11 09:28 UTC, sjjeong commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/ui/UpbitFragment.kt
> +    private val upbitViewModel by viewModels<UpbitViewModel>()
기존처럼 의존성 주입 패턴을 유지해주세요

2019-10-11 09:28 UTC, sjjeong commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/util/FormatText.kt
> +            signedChangeRate > 0 -> Color.RED
이렇게 변경해도 문제가 없나요?
color res id에서 color value로 변경되면 문제가 있을 것 같습니다.

2019-10-12 01:50 UTC, ganghee commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/ui/UpbitFragment.kt
> +    private val upbitViewModel by viewModels<UpbitViewModel>()
네 수정하였습니다.
[UpbitFragment](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/228/commits/4ea482604cbea7cc96c176e47ffb648fdba9a3e0)

2019-10-12 01:52 UTC, ganghee commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/util/FormatText.kt
> +            signedChangeRate > 0 -> Color.RED
수정하면 색이 바껴서 보이지 않네요 그냥 회색으로 나와요 다른 방법이 있을까요?
[FormatText](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/228/commits/17ec67b3a3352f623dba941a0e06936c79c63b17)

2019-10-14 14:06 UTC, ganghee commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/ui/UpbitFragment.kt
> +    private val upbitViewModel by viewModels<UpbitViewModel>()
다시 수정하였습니다.
[UpbitFragment](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/228/commits/a24ec44528403e5a3dcfb12825c1b7c10b2b261a)

2019-10-14 14:08 UTC, ganghee commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/util/FormatText.kt
> +            signedChangeRate > 0 -> Color.RED
BindingAdapter를 사용하여 구현하였습니다.
[AdapterUtil](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/228/commits/107a846a0a04a89659969e948ec36cfa512d578e)

2019-10-17 06:19 UTC, sjjeong approved these changes

2019-10-17 06:44 UTC, wswon approved these changes

2019-10-17 06:44 UTC, merged