HW-2 MVP 변경
sjjeong/GoogryAndroidArchitecutreStudy pull request #23
Opened 2019-05-06 05:09 UTC by namjackson

기존 코드를 MVP로 변경했습니다.

2019-05-08 15:43 UTC, Hoyuo requested changes

2019-05-08 15:43 UTC, Hoyuo commented on namjackson/ArchStudy/app/src/main/java/com/namjackson/archstudy/CoinListPresenter.kt
> +        if (!this::markets.isInitialized)
`{ }` 으로 감싸 주세요

2019-05-08 15:43 UTC, Hoyuo commented on namjackson/ArchStudy/app/src/main/java/com/namjackson/archstudy/view/CoinListFragment.kt
> +    override fun showCoinList(ticker: List<Ticker>) {
region 설정을 해주세요

2019-05-08 15:43 UTC, Hoyuo commented on namjackson/ArchStudy/app/src/main/java/com/namjackson/archstudy/view/CoinListFragment.kt
> +            binding.progress.visibility = View.VISIBLE
메서드로 만드는것은 어떨까요?

2019-05-08 15:43 UTC, Hoyuo commented on namjackson/ArchStudy/app/src/main/java/com/namjackson/archstudy/view/CoinListFragment.kt
> +        }, 0, (60 * 1000))
Magic Number 보다는 의미 있는 값으로 변경해 주세요

2019-05-09 14:22 UTC, namjackson commented on namjackson/ArchStudy/app/src/main/java/com/namjackson/archstudy/view/CoinListFragment.kt
> +    override fun showCoinList(ticker: List<Ticker>) {
region 설정이 어떤건가요? 
접근제한자인가용?

2019-05-09 14:22 UTC, namjackson commented on namjackson/ArchStudy/app/src/main/java/com/namjackson/archstudy/CoinListPresenter.kt
> +        if (!this::markets.isInitialized)
76e8cdd

2019-05-09 14:22 UTC, namjackson commented on namjackson/ArchStudy/app/src/main/java/com/namjackson/archstudy/view/CoinListFragment.kt
> +            binding.progress.visibility = View.VISIBLE
fcd8a48

2019-05-09 14:22 UTC, namjackson commented on namjackson/ArchStudy/app/src/main/java/com/namjackson/archstudy/view/CoinListFragment.kt
> +        }, 0, (60 * 1000))
926be1b7de5b663fcb4f57591a163067edb549b3

2019-05-10 02:33 UTC, GeoN5 submitted a review, later dismissed
수고하셨습니다!!

2019-05-10 02:33 UTC, GeoN5 commented on namjackson/ArchStudy/app/src/main/java/com/namjackson/archstudy/view/CoinListFragment.kt
> +    fun initTimer() {
어떤 방식이 더 효율적인 거까진 잘 모르겠는데
저는 이런식으로 사용해요.
```kotlin
private lateinit var timerTask: Timer
```
```kotlin
timerTask = timer(period = TIMER_UNIT_MILLISECOND) {
    //작업
}
```

2019-05-10 16:39 UTC, Hoyuo commented on namjackson/ArchStudy/app/src/main/java/com/namjackson/archstudy/view/CoinListFragment.kt
> +    override fun showCoinList(ticker: List<Ticker>) {
코드 상으로 보기 좋게 보이는 것입니다.
이것에 대해서는 스터디때 직접 보여드릴께요

2019-05-10 16:39 UTC, Hoyuo submitted a review, later dismissed

2019-05-11 10:39 UTC, namjackson commented on namjackson/ArchStudy/app/src/main/java/com/namjackson/archstudy/view/CoinListFragment.kt
> +    fun initTimer() {
다른 호출 방식이군요 ㅎㅎ
아마 기능상의 차이는없어보이지만, 
건호님 방법이 좀더 가독성이 좋을거같긴하네요

2019-05-12 15:03 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-05-14 00:32 UTC, merged