HW8 - Koin 적용하기
sjjeong/GoogryAndroidArchitecutreStudy pull request #235
Opened 2019-10-14 08:19 UTC by zojae031

그동안 감사했습니다!
Injection class로 일일히 사용하다가 Koin사용하니 정말 편하군요 ㄷㄷㄷ

2019-10-23 08:39 UTC, wkdehdlr submitted a review, later dismissed
그동안 많이 배웠습니다. 취뽀 응원합니다~

2019-10-23 09:22 UTC, BeokBeok requested changes
안녕하세요. 스터디 2기 강현석이라고 합니다.
부족하지만 잘 부탁드립니다. 😅

2019-10-23 09:22 UTC, BeokBeok commented on zojae031/Project/app/src/main/java/study/architecture/coinjob/CoinViewModel.kt
> +    private lateinit var dispose: Disposable
disposable 관련해서는 BaseViewModel 에서 관리하는 것이 좋을 것 같아요.

2019-10-23 09:22 UTC, BeokBeok commented on zojae031/Project/app/src/main/java/study/architecture/data/datasource/local/di/localModule.kt
> +    single { CoinDatabase.getInstance(androidContext()) }
koin 을 사용하신다면, getInstance 함수는 불필요할 것 같아요.

2019-10-23 09:22 UTC, BeokBeok commented on zojae031/Project/app/src/main/java/study/architecture/data/datasource/remote/di/remoteModule.kt
> +            )
확장성을 위해서 create 하는 부분은 따로 빼주시는 것이 좋을 것 같아요.

2019-10-23 09:22 UTC, BeokBeok commented on zojae031/Project/app/src/main/java/study/architecture/data/datasource/remote/di/remoteModule.kt
> +            .addCallAdapterFactory(RxJava2CallAdapterFactory.create())
GsonConverterFactory 와 RxJava2CallAdapterFactory 또한 객체이기 때문에
이 부분도 따로 빼주시는 것이 좋을 것 같아요.

2019-10-23 09:22 UTC, BeokBeok commented on zojae031/Project/app/src/main/java/study/architecture/data/di/RepositoryModule.kt
> +    single<Repository> { RepositoryImpl.getInstance(get(), get(), get()) }
koin 을 사용하신다면, getInstance 함수는 불필요할 것 같아요.

2019-10-23 09:22 UTC, BeokBeok commented on zojae031/Project/app/src/main/java/study/architecture/data/datasource/remote/di/remoteModule.kt
> +            .baseUrl(RemoteDataSourceImpl.url)
url 을 RemoteDataSourceImpl 에 직접 접근하여 참조하는 것 보다는 
본 파일에서 정의해서 사용하시는 것이 좋을 것 같아요.

2019-10-24 00:34 UTC, zojae031 commented on zojae031/Project/app/src/main/java/study/architecture/data/datasource/remote/di/remoteModule.kt
> +            )
```
single<Retrofit> {
        Retrofit
            .Builder()
            .baseUrl(RemoteDataSourceImpl.url)
            .addConverterFactory(GsonConverterFactory.create())
            .addCallAdapterFactory(RxJava2CallAdapterFactory.create())
            .build()
    }
```
이런식으로 만들어준다음 create를 어떻게 해야하죠...?
RemoteDataSource에서는 UpbitApi로 받는데 아직 잘 이해가 안되네요!

2019-10-24 00:43 UTC, zojae031 commented on zojae031/Project/app/src/main/java/study/architecture/coinjob/CoinViewModel.kt
> +    private lateinit var dispose: Disposable
376f29b 해당커밋입니다!

2019-10-24 00:44 UTC, zojae031 commented on zojae031/Project/app/src/main/java/study/architecture/data/datasource/local/di/localModule.kt
> +    single { CoinDatabase.getInstance(androidContext()) }
78e98c0 해당 커밋입니다!

2019-10-24 00:44 UTC, zojae031 commented on zojae031/Project/app/src/main/java/study/architecture/data/di/RepositoryModule.kt
> +    single<Repository> { RepositoryImpl.getInstance(get(), get(), get()) }
78e98c0 해당 커밋입니다!

2019-10-24 00:47 UTC, zojae031 commented on zojae031/Project/app/src/main/java/study/architecture/data/datasource/remote/di/remoteModule.kt
> +            .addCallAdapterFactory(RxJava2CallAdapterFactory.create())
98c1e14 해당 커밋입니다!
분리한다고 분리해보려 했는데 무엇이 문제인지 잘 모르겠습니다 ㅠㅠ
```debug
     Caused by: org.koin.core.error.InstanceCreationException: Could not create instance for [type:Single,primary_type:'retrofit2.Retrofit']
        at org.koin.core.instance.DefinitionInstance.create(DefinitionInstance.kt:61)
        at org.koin.core.instance.SingleDefinitionInstance.get(SingleDefinitionInstance.kt:40)
        at org.koin.core.definition.BeanDefinition.resolveInstance(BeanDefinition.kt:70)
        at org.koin.core.scope.Scope.resolveInstance(Scope.kt:165)
        at org.koin.core.scope.Scope.get(Scope.kt:128)
        at study.architecture.data.datasource.remote.di.RemoteModuleKt$remoteModule$1$1.invoke(remoteModule.kt:27)
        at study.architecture.data.datasource.remote.di.RemoteModuleKt$remoteModule$1$1.invoke(Unknown Source:4)
        at org.koin.core.instance.DefinitionInstance.create(DefinitionInstance.kt:54)
        	... 80 more
     Caused by: org.koin.core.error.NoBeanDefFoundException: No definition found for 'retrofit2.Converter$Factory' has been found. Check your module definitions.
2019-10-24 09:41:29.019 6127-6127/study.architecture E/AndroidRuntime:     at org.koin.core.scope.Scope.findDefinition(Scope.kt:170)
        at org.koin.core.scope.Scope.resolveInstance(Scope.kt:164)
        at org.koin.core.scope.Scope.get(Scope.kt:128)
        at study.architecture.data.datasource.remote.di.RemoteModuleKt$remoteModule$1$4.invoke(remoteModule.kt:27)
        at study.architecture.data.datasource.remote.di.RemoteModuleKt$remoteModule$1$4.invoke(Unknown Source:4)
        at org.koin.core.instance.DefinitionInstance.create(DefinitionInstance.kt:54)
```
이런식의 오류가 발생하네요 
single로 만든다고 만들었는데 찾지 못하는것 같습니다.
 아직 제가 구조 이해가 더 필요한것 같아요 ㅠㅠ

2019-10-24 00:47 UTC, zojae031 commented on zojae031/Project/app/src/main/java/study/architecture/data/datasource/remote/di/remoteModule.kt
> +            .baseUrl(RemoteDataSourceImpl.url)
추가설명 부탁드려도 될까요??

2019-10-24 00:49 UTC, zojae031 commented on zojae031/Project/app/src/main/java/study/architecture/data/datasource/remote/di/remoteModule.kt
> +            .baseUrl(RemoteDataSourceImpl.url)
본 파일에서 정의해서 사용하라는 말씀이 잘 이해가 되지 않습니다.

2019-10-24 01:20 UTC, BeokBeok commented on zojae031/Project/app/src/main/java/study/architecture/data/datasource/remote/di/remoteModule.kt
> +            .baseUrl(RemoteDataSourceImpl.url)
remoteModule 파일에 
`private const val url = "https://api.upbit.com/v1/"` 을
선언해서 쓰시면 될 것 같아요

2019-10-24 01:20 UTC, zojae031 commented on zojae031/Project/app/src/main/java/study/architecture/data/datasource/remote/di/remoteModule.kt
> +            .baseUrl(RemoteDataSourceImpl.url)
373ed27
우선은 이해한대로 작성해보았습니다!

2019-10-24 01:20 UTC, BeokBeok commented on zojae031/Project/app/src/main/java/study/architecture/data/datasource/remote/di/remoteModule.kt
> +            .addCallAdapterFactory(RxJava2CallAdapterFactory.create())
```
    factory { GsonConverterFactory.create() }
    factory { RxJava2CallAdapterFactory.create() }
```
이렇게 하신 다음

```
            .addConverterFactory(get<GsonConverterFactory>())
            .addCallAdapterFactory(get<RxJava2CallAdapterFactory>())
```
이런 식으로 사용하시면 될 것 같아요.

2019-10-24 01:20 UTC, BeokBeok commented on zojae031/Project/app/src/main/java/study/architecture/data/datasource/remote/di/remoteModule.kt
> +            )
```
    single {
        get<Retrofit>().create(UpbitApi::class.java)
    }
```
이렇게 쓰시면 될 것 같아요

2019-10-24 01:20 UTC, BeokBeok commented on zojae031/Project/app/src/main/java/study/architecture/coinjob/CoinViewModel.kt
> +    private lateinit var dispose: Disposable
disposable 대신 composite disposable 만으로도 관리할 수 있지 않나요?

2019-10-24 01:21 UTC, zojae031 commented on zojae031/Project/app/src/main/java/study/architecture/data/datasource/remote/di/remoteModule.kt
> +            )
373ed27
조금 변경해보았는데 아직도 문제가 발생합니다 ㅠ_ㅠ

2019-10-24 01:23 UTC, zojae031 commented on zojae031/Project/app/src/main/java/study/architecture/coinjob/CoinViewModel.kt
> +    private lateinit var dispose: Disposable
제가 처음 코드를 작성할때 설계가 약간 잘못되어서 marketName을 가져오기 전에
(dispose가 되기 전에)  ticker정보를 요청하면 오류가 발생합니다.
비동기 작업처리를 제대로 분리하지 못하여 발생한 문제같습니다 ㅠ

2019-10-24 01:24 UTC, zojae031 commented on zojae031/Project/app/src/main/java/study/architecture/data/datasource/remote/di/remoteModule.kt
> +            .baseUrl(RemoteDataSourceImpl.url)
앗...댓글 달고있던 도중에 리뷰가 또 달렸군요!
제대로 이해한게 맞는것 같습니다 ㅎㅎ감사합니다

2019-10-24 01:27 UTC, zojae031 commented on zojae031/Project/app/src/main/java/study/architecture/data/datasource/remote/di/remoteModule.kt
> +            )
아아 결국 get()을 쓴다고 알아서 푱푱 찾아 들어가는것이 아니라
Generic타입으로 지정을 해주어야 맞추어서 들어가는거였군요!
제 학습이 부족한탓이네요ㅠㅠ 감사합니다 덕분에 많이 배워갑니다!

828c862

2019-10-24 01:59 UTC, BeokBeok commented on zojae031/Project/app/src/main/java/study/architecture/coinjob/CoinViewModel.kt
> +    private lateinit var dispose: Disposable
`if (::marketName.isInitialized)` 로 체크하시면 될 것 같습니다.

2019-10-24 02:06 UTC, BeokBeok requested changes

2019-10-24 02:06 UTC, BeokBeok commented on zojae031/Project/app/src/main/java/study/architecture/base/BaseViewModel.kt
>      open fun onPause() {
onCleared 를 오버라이딩 하셔서 처리하시는 것이 좋을 것 같아요.

2019-10-24 02:06 UTC, BeokBeok commented on zojae031/Project/app/src/main/java/study/architecture/data/datasource/remote/di/remoteModule.kt
> +const val upbitUrl = "https://api.upbit.com/v1/"
private 접근자를 붙이셔도 될 것 같아요.

2019-10-24 02:06 UTC, BeokBeok commented on zojae031/Project/app/src/main/java/study/architecture/data/datasource/remote/di/remoteModule.kt
> +    single<Retrofit> {
Retrofit 으로 타입 지정하지 않으셔도 될 것 같아요.

2019-10-24 03:06 UTC, zojae031 commented on zojae031/Project/app/src/main/java/study/architecture/coinjob/CoinViewModel.kt
> +    private lateinit var dispose: Disposable
와...이게 lateinit에서만 사용되는게 아니었군요...감사합니다

ea9f5fe

2019-10-24 03:14 UTC, zojae031 commented on zojae031/Project/app/src/main/java/study/architecture/base/BaseViewModel.kt
>      open fun onPause() {
onCleared는 onDestroy될 때 호출된다고 알고있습니다.  
그런데 안드로이드에서 onDestroy의 호출은 보장되지 않는데  
1. 만약 onDestroy가 호출되지 않는경우.
2. CompositeDisposable에 onResume에서 계속 add를 하는데
지속하여 add가 되어 불필요하게 쌓이는 경우
이 부분에 대해서는 어떻게 생각하시나요??

a3f90ca

2019-10-24 03:15 UTC, zojae031 commented on zojae031/Project/app/src/main/java/study/architecture/data/datasource/remote/di/remoteModule.kt
> +const val upbitUrl = "https://api.upbit.com/v1/"
ef4600c 감사합니다 세세한것에 신경쓰는 버릇을 만들어야겠습니다 ㅠㅠ

2019-10-24 03:18 UTC, zojae031 commented on zojae031/Project/app/src/main/java/study/architecture/data/datasource/remote/di/remoteModule.kt
> +    single<Retrofit> {
2336907
안드로이드 스튜디오에서 <Retrofit>관련하여 회색으로 띄워주지 않습니다.
즉, 타입 추정이 된다 하더라도 뭔가 추천사항이 아니라서 그렇다고 생각하는데
사용자의 가독성 측면에서도 저는 있는게 좋다 생각하는데 어떻게 생각하시나요?

2019-10-24 03:55 UTC, BeokBeok commented on zojae031/Project/app/src/main/java/study/architecture/base/BaseViewModel.kt
>      open fun onPause() {
이 부분에 대해서 저도 테스트를 해봤는데
처음 4개의 데이터 (KRW, BTC, ETH, USDT) 를 요청할 때에는 쌓이지 않지만,
Home 키로 왔다 갔다하는 경우에는 계속 쌓이네요.

해서, onCleared 에는 구독을 해지하는 dispose 함수를 호출하여 처리하고
onPause 나 onStop 인 경우에는 clear 함수를 호출하여 처리하는 것이 좋을 것 같습니다.

2019-10-24 03:55 UTC, BeokBeok commented on zojae031/Project/app/src/main/java/study/architecture/data/datasource/remote/di/remoteModule.kt
> +    single<Retrofit> {
재영님 말씀대로, 타입을 지정하는 것이 사용자의 가독성 측면에서 좋다는 것 대해서는 동의합니다.
하지만, 자칫 잘못하다가는 올바르지 않은 타입으로 강제 캐스팅이 될 경우가 발생할 수도 있기 때문에
타입 추정을 하지 못하는 경우에만 해주는 것이 좋다고 생각합니다.

2019-10-24 04:03 UTC, zojae031 commented on zojae031/Project/app/src/main/java/study/architecture/base/BaseViewModel.kt
>      open fun onPause() {
onDestroy의 호출이 보장되지 않는다고 알고있는데
만약 onDestroy가 호출이 안된경우 onCleared가 호출되지 않는데 그러면
MarketName을 가져오는 스트림은 계속 살아있게 되는거 아닐까요?

2019-10-24 05:06 UTC, zojae031 commented on zojae031/Project/app/src/main/java/study/architecture/data/datasource/remote/di/remoteModule.kt
> +    single<Retrofit> {
좋은의견 감사드립니다

2019-10-24 05:46 UTC, sabgilhun reviewed
지나가다가 개인적인 의견 남겨봅니답 ㅎ

2019-10-24 05:46 UTC, sabgilhun commented on zojae031/Project/app/src/main/java/study/architecture/data/datasource/remote/di/remoteModule.kt
> +    single<Retrofit> {
사실 컨벤션 차이라고 느꺼지는 부분이네요. 그런데 어느 방향이든 통일하는것 은 필요해 보입니당

2019-10-24 06:08 UTC, zojae031 commented on zojae031/Project/app/src/main/java/study/architecture/data/datasource/remote/di/remoteModule.kt
> +    single<Retrofit> {
@sabgilhun 감사합니다!

2019-10-24 06:33 UTC, BeokBeok commented on zojae031/Project/app/src/main/java/study/architecture/base/BaseViewModel.kt
>      open fun onPause() {
살아 있는 것은 위 코맨트에 작성하였듯이 확인하였습니다.
해서, 이 부분은 재영님이 처리하신 방법이 좋은 것 같습니다.

2019-10-24 06:49 UTC, zozero94 commented on zojae031/Project/app/src/main/java/study/architecture/base/BaseViewModel.kt
>      open fun onPause() {
감사합니다

2019-10-24 06:51 UTC, zozero94 commented on zojae031/Project/app/src/main/java/study/architecture/base/BaseViewModel.kt
>      open fun onPause() {
400045a
revert commit이력입니다.

2019-10-24 06:58 UTC, BeokBeok submitted a review, later dismissed
LGTM:ok_hand:

---

부족한 리뷰에 대응해주시고, 스터디를 마무리하시느라 고생 많으셨습니다.:smile:

2019-10-24 16:15 UTC, sjjeong requested changes

2019-10-24 16:15 UTC, sjjeong commented on zojae031/Project/app/src/main/java/study/architecture/coinjob/CoinViewModel.kt
> -    private val index: CoinFragment.FragIndex,
기존에 index 전달 해주던 부분을 왜 제거 하셨나요?
https://insert-koin.io/docs/2.0/documentation/reference/index.html#_injection_parameters
이 부분을 적용하시면 됩니다

2019-10-28 07:20 UTC, zojae031 commented on zojae031/Project/app/src/main/java/study/architecture/coinjob/CoinViewModel.kt
> -    private val index: CoinFragment.FragIndex,
fafdb00
해당 커밋입니다.

2019-10-29 06:44 UTC, sjjeong requested changes
https://github.com/zojae031/GoogryAndroidArchitectureStudy/tree/class03/zojae031
브랜치에 다른것들이 많이 추가 됐습니다.
HW9에 해당하는 내용들만 추가되게 수정해주세요 

리뷰 작성하는 작업은 pr 따로 만들어서 처리해주세요

2019-10-29 09:29 UTC, zojae031 commented
해당작업 reset 시켰습니다.

2019-10-29 12:14 UTC, sjjeong approved these changes

2019-10-30 08:05 UTC, merged