HW-9 Koin 적용하기
sjjeong/GoogryAndroidArchitecutreStudy pull request #239
Opened 2019-10-15 01:17 UTC by wswon

감사합니다.

2019-10-15 09:56 UTC, ganghee reviewed
리뷰하면서 많이 공부했습니다!! 제 리뷰 참고하시고 다른 의견 있으면 편하게 리뷰 달아주세요!!

2019-10-15 09:56 UTC, ganghee commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/di/ViewModelModule.kt
> +package com.architecture.study.di
여기 패키지 안에 di 파일들을 한번에 넣는게 좋을 것 같아요!!
di는 앱이 실행되면 어느 패키지에 종속 되지 않고 Application객체에 의해 전역으로 실행되기 때문입니다!!

2019-10-15 09:56 UTC, ganghee commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/App.kt
>      }
Application 객체를 인스턴스화할 필요가 있을까요?
전역 객체이기 때문에 필요가 없을 것 같아요~

2019-10-15 09:56 UTC, ganghee commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/App.kt
>      fun context(): Context = applicationContext
필요없는 함수 같아요!

2019-10-15 09:56 UTC, ganghee commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/data/source/remote/CoinRemoteDataSourceImpl.kt
> +class CoinRemoteDataSourceImpl private constructor(private val upbitApi: UpbitApi) :
제가 잘 몰라서 그러는데 private constructor 를 사용한 이유를 알 수 있을까요?

2019-10-15 09:56 UTC, ganghee commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/data/source/remote/CoinRemoteDataSourceImpl.kt
>              }
koin을 사용하는 목적은 이러한 코드를 모듈화하고 single이라는 키워드로 singleton객체를 쉽게 생성,주입 할 수 있다고 생각합니다!
이 부분을 삭제하고 
```
single<CoinRemoteDataSource> { CoinRemoteDataSourceImpl.getInstance(get()) }
->  single<CoinRemoteDataSource> { CoinRemoteDataSourceImpl(get()) }
```
```
class CoinRemoteDataSourceImpl private constructor(private val upbitApi: UpbitApi) :
-> class CoinRemoteDataSourceImpl(private val upbitApi: UpbitApi) :
```
으로 수정하는 것도 좋을 것 같아요 다른 방법으로 수정해도 좋고요!!

2019-10-16 07:52 UTC, wswon commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/di/ViewModelModule.kt
> +package com.architecture.study.di
di package를 
layor마다 
network/di
data/repository/di 
data/source/di

이런식으로 나눈 이유는 그냥 개발할때 보기 편하다고 느껴서 였습니다! 
석준님 repository의 FirstCarFinder를 참고해서 나누어 보았는데, 
과도하게 흩어져있는건 아닌지 점검해보겠습니다. 감사합니다.

2019-10-16 07:54 UTC, wswon commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/data/source/remote/CoinRemoteDataSourceImpl.kt
> +class CoinRemoteDataSourceImpl private constructor(private val upbitApi: UpbitApi) :
private constructor로 선언한 이유는
```
CoinRemoteDataSourceImpl(api) - (X)
CoinRemoteDataSourceImpl.getInstance(api) - (O)
```
이렇게 다른 사람이 처음사용할 때도 혼용하지 않도록 한가지 case로만 생성가능하게 하기 위함이였습니다.
private constructor가 없으면 1번케이스가 실행이 되거든요.

2019-10-16 08:04 UTC, wswon commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/data/source/remote/CoinRemoteDataSourceImpl.kt
>              }
사실 general에 올라온 topic을 보고 
singleton 선언문을 지웠다고 했을때
koin을 사용하지 않고 해당 클래스를 사용하게 되면?
이라는 문제에서 저는 자유롭지 못하다고 생각하여 그대로 두었는데요.

그런데 또 드는 생각은 
koin을 제대로 활용하지 못하는건 아닌가 생각이 들어서 수정했습니다. 감사합니다

5e48dd2

2019-10-16 08:16 UTC, wswon commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/App.kt
>      }
Application의 applicationContext는 singleton 객체이지만, 
Application 클래스인 App은 사용에 있어서 일반 클래스와 같은 것 같습니다.

![image](https://user-images.githubusercontent.com/48197016/66900666-36d0d000-f038-11e9-9a0a-6c09b96c040d.png)
일반클래스와 다른가? 하는 의문이 들어 테스트 해보았습니다.

instance로 만든 이유는 App의 applicationContext를 
App.instance.context() 이렇게 여러번 접근하기 위함입니다! 
그렇지 않으면 App class를 context가 필요할 때 마다 매번 생성해야 하니까요.

그런데 석준님 리뷰 반영하면서 Global context 접근하는 부분이 사라져서 
해당코드는 삭제했습니다.

2019-10-16 09:06 UTC, ganghee commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/data/source/remote/CoinRemoteDataSourceImpl.kt
> +class CoinRemoteDataSourceImpl private constructor(private val upbitApi: UpbitApi) :
한가지  case라는 것이 하나의 객체를 말하는 것인가요? 아니면 하나의 api라는 건가요?

2019-10-17 00:03 UTC, wswon commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/data/source/remote/CoinRemoteDataSourceImpl.kt
> +class CoinRemoteDataSourceImpl private constructor(private val upbitApi: UpbitApi) :
Apple 이라는 class가있다고 했을때 저는 singleton으로만 생성가능하게 할건데
Apple.getInstance() 이렇게 하면 singleton으로 접근 할 수 있잖아요?

그런데 private constructor를 붙이지않으면,
Apple() 이렇게 사용할 가능성이 있기에 (이 경우는 singleton이 아니기에)
애초에 외부에서의 생성자를 통한 객체생성을 막고 (private constructor)
Apple.getInstance() 이런식으로만 호출 가능하게 한다는 의미에서 달았습니다.

2019-10-17 02:46 UTC, ganghee commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/data/source/remote/CoinRemoteDataSourceImpl.kt
> +class CoinRemoteDataSourceImpl private constructor(private val upbitApi: UpbitApi) :
아아 그렇군요 처음 알게 되었네요 감사합니다!!

2019-10-17 04:04 UTC, BeokBeok requested changes
안녕하세요. 스터디 2기 강현석이라고 합니다.
부족하지만 잘 부탁드립니다. 😅

2019-10-17 04:04 UTC, BeokBeok commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/view/coin/CoinListActivity.kt
> +import android.util.Log
불필요한 import 는 제거해 주시는 것이 좋아요.

2019-10-17 04:04 UTC, BeokBeok commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/view/coin/CoinListFragment.kt
> +    private lateinit var monetaryUnitList: List<String>
val 로 변경하시는 것이 좋을 것 같아요.
mutable object 는 가급적이면 사용을 지양하시는 것이 좋아요.

2019-10-17 04:04 UTC, BeokBeok commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/viewmodel/TickerViewModel.kt
> +    private val onClick: (ticker: Ticker) -> Unit =
이렇게 쓰시는 게 좋아 보여요.
```suggestion
    private val onClick: (ticker: Ticker) -> Unit = { ticker ->
```

2019-10-17 04:04 UTC, BeokBeok commented on wswon/AndroidArchitectureStudy/app/src/main/res/layout/item_ticker.xml
> +        android:onClick="@{_ -> ticker.onClick.invoke(ticker)}"
() 대신 _ 를 쓰신 이유가 있나요?

2019-10-17 04:04 UTC, BeokBeok commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/view/coin/CoinListFragment.kt
> +//        Log.d("::monetaryUnitList.isInitialized", "${::monetaryUnitList.isInitialized}")
불필요한 주석은 제거해주시는 것이 좋아요.

2019-10-18 06:20 UTC, wswon commented on wswon/AndroidArchitectureStudy/app/src/main/res/layout/item_ticker.xml
> +        android:onClick="@{_ -> ticker.onClick.invoke(ticker)}"
https://stackoverflow.com/questions/54778874/how-do-i-bind-and-invokefunction-type-in-android-data-binding
방법을 찾다가 이런 글을 보고 적용했는데 혹시 ()랑 다른점이 있을까요??,,

2019-10-18 06:23 UTC, wswon commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/view/coin/CoinListFragment.kt
> +//        Log.d("::monetaryUnitList.isInitialized", "${::monetaryUnitList.isInitialized}")
8ee531c 제거했습니다.

2019-10-18 06:23 UTC, wswon commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/view/coin/CoinListActivity.kt
> +import android.util.Log
8ee531c 제거했습니다.

2019-10-18 06:23 UTC, wswon commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/viewmodel/TickerViewModel.kt
> +    private val onClick: (ticker: Ticker) -> Unit =
d3f5388 수정했습니다.

2019-10-18 06:28 UTC, wswon commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/view/coin/CoinListFragment.kt
> +    private lateinit var monetaryUnitList: List<String>
음 이전에는 activitiy에서 market의 정보를 통신을 통해 다 받아왔을때 fragment를 생성하여 bundle로 monetaryUnitList를 넘겨줬었는데요.

중간에 수정을하여서 fragment를 먼저 생성하고,
 market의 정보를 통신을 통해 다 받아왔을때 monetaryUnitList를 fragment에 주입을 하는형태로 변경했습니다.

따라서 monetaryUnitList를 value로 만들 수가 없는 상황이라 lateinit var 로 만들었어요.
주입받은 monetaryUnitList를 재사용해야하는 경우 때문에요.
lazy로는 불가능해보이는데 혹시 다른방법이 있을까요..?

2019-10-18 08:21 UTC, sjjeong commented on wswon/AndroidArchitectureStudy/app/src/main/res/layout/item_ticker.xml
> +        android:onClick="@{_ -> ticker.onClick.invoke(ticker)}"
_는 unused variable 나타낼 때 쓰는 방법이라서 
() -> {}
_ -> {}
(_) -> {}
view -> {}
(view) -> {}
다 상관은 없어요

2019-10-18 08:28 UTC, sjjeong requested changes

2019-10-18 08:28 UTC, sjjeong commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/di/ViewModelModule.kt
> +package com.architecture.study.di
저는 멀티모듈 고려해서 만든거라서 나누긴 했는데 합쳐도 상관없어요~

2019-10-18 08:28 UTC, sjjeong commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/network/di/NetworkModule.kt
> +    single<Retrofit> { (url: String) ->
여러개의 Retrofit을 만들어주고 싶은 목적으로 url을 받는 것 같습니다.
그렇다면 이 부분은 single이 아니라 factory로 만들어야 합니다.

2019-10-18 08:28 UTC, sjjeong commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/view/coin/CoinListFragment.kt
> +    private lateinit var monetaryUnitList: List<String>
```kotlin
private val monetaryUnitList = mutableList<String>()

fun setMonetaryUnitList(monetaryUnitList: List<String>) {
    this.monetaryUnitList.clear()
    this.monetaryunitList.addAll(monetaryUnitList)
    tickerViewModel.getTickerList(monetaryUnitList)
}
```

2019-10-21 15:46 UTC, wswon commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/network/di/NetworkModule.kt
> +    single<Retrofit> { (url: String) ->
40323d7 수정했습니다!

2019-10-21 15:46 UTC, wswon commented on wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/view/coin/CoinListFragment.kt
> +    private lateinit var monetaryUnitList: List<String>
6c6419f 수정했습니다1

2019-10-21 15:47 UTC, wswon commented on wswon/AndroidArchitectureStudy/app/src/main/res/layout/item_ticker.xml
> +        android:onClick="@{_ -> ticker.onClick.invoke(ticker)}"
감사합니다!

2019-10-22 02:19 UTC, BeokBeok approved these changes
LGTM:ok_hand:
스터디 하시느라 고생 많으셨습니다. 👍

2019-10-22 15:36 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-10-22 15:37 UTC, sjjeong commented
지금까지 고생많으셨어요 ㅎㅎ
후기도 꼭 남겨주세요!

2019-10-23 01:00 UTC, ganghee approved these changes

2019-10-23 01:04 UTC, ganghee commented
부족하지만 제 리뷰 반영해 주시고 같이 과제에 대해 고민 할 수 있어서 정말 고맙습니다.
정말 수고하셨습니다. 👏👏
LGTM⭐️

2019-10-30 13:00 UTC, merged