HW-2 MVP 아키텍처로 변환
sjjeong/GoogryAndroidArchitecutreStudy pull request #24
Opened 2019-05-07 12:16 UTC by improve777

2019-05-08 11:02 UTC, GongSulMin requested changes

2019-05-08 11:02 UTC, GongSulMin commented on improve777/GAASProject/app/src/main/java/dev/daeyeon/gaasproject/ui/ticker/adapter/TickerAdapterContract.kt
> +interface TickerAdapterContract {
tickerAdatperContract 인터페이스 목적이 view 와 model 기능을 나누기 위해선가요?? ㅎㅎ

2019-05-08 11:02 UTC, GongSulMin commented on improve777/GAASProject/app/src/main/java/dev/daeyeon/gaasproject/ui/ticker/TickerPresenter.kt
> +                    adapterView.notifyAdapter()
TickerAdapterContract 인터페이스를 잘 이해하지 못해서 확신은 안서지만... ㅎㅎ 
nofifyadapter 메소드는 activity에서 호출하는거는 어떠신가요??

2019-05-08 11:38 UTC, ddaeyeonkim commented on improve777/GAASProject/app/src/main/java/dev/daeyeon/gaasproject/ui/ticker/adapter/TickerAdapterContract.kt
> +interface TickerAdapterContract {
넵 어댑터는 데이터 조작이랑 뷰의 조작을 같이 하게 되서 각각의 역할을 분리하기 위해 만들었습니다

2019-05-08 11:47 UTC, ddaeyeonkim commented on improve777/GAASProject/app/src/main/java/dev/daeyeon/gaasproject/ui/ticker/TickerPresenter.kt
> +                    adapterView.notifyAdapter()
tickerAdapterContract view 와 model 을 받는 이유가 프레젠터에서 액티비티를 거치지 않고 어댑터에 바로 접근하게 하기 위해서 했습니다

2019-05-09 04:09 UTC, sabgilhun requested changes
ㅎㅎ 받아서 한번 돌려봤는데 디자인도 엄청 이쁘네요

2019-05-09 04:09 UTC, sabgilhun commented on improve777/GAASProject/app/src/main/java/dev/daeyeon/gaasproject/ui/ticker/TickerContract.kt
> +        val upbitRepository: UpbitRepository
MVP 규칙상 View가 Model을 접근하지 않기 때문에 repository getter가 필요하지 않을것 같습니다.

2019-05-09 04:09 UTC, sabgilhun commented on improve777/GAASProject/app/src/main/java/dev/daeyeon/gaasproject/ui/ticker/TickerContract.kt
> +        val adapterModel: TickerAdapterContract.Model
adapterView, adaterModel 둘 다 Contract에 getter로 두지 말고 Presenter 생성자로 넘겨주는 방식은 어떨까요??

2019-05-09 14:51 UTC, improve777 commented on improve777/GAASProject/app/src/main/java/dev/daeyeon/gaasproject/ui/ticker/TickerContract.kt
> +        val upbitRepository: UpbitRepository
넵 수정하였습니다

80c342b6ce10821985bc2a50672d90b2d5362bd2

2019-05-09 14:52 UTC, improve777 commented on improve777/GAASProject/app/src/main/java/dev/daeyeon/gaasproject/ui/ticker/TickerContract.kt
> +        val adapterModel: TickerAdapterContract.Model
view: TickerContact.View 도 같은 의미로 생각되어 같이 반영하였습니다

6a3b6df30cdcbab745c52a01ed795fe48cc6880b

2019-05-10 01:13 UTC, sabgilhun submitted a review, later dismissed

2019-05-10 05:29 UTC, GongSulMin submitted a review, later dismissed

2019-05-15 11:32 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-05-15 14:34 UTC, merged