HW-6 MVVM 패턴 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #240
Opened 2019-10-15 14:45 UTC by toctocbin

MVP 구조에서 BaseViewModel을 사용하여 각각 Acitivity와 Fragment에 MVVM패턴을 적용하였습니다.

2019-10-17 07:16 UTC, junghum21 commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/ui/market/MarketActivity.kt
> +        vm.toastMessage.addOnPropertyChangedCallback(object  : Observable.OnPropertyChangedCallback(){
저는 toast changedCallback을 BaseActivity, BaseFragment에 구현해두었습니다.

2019-10-17 07:25 UTC, junghum21 commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/ui/ticker/TickerFragment.kt
> +        vm.tickerList.addOnPropertyChangedCallback(object : Observable.OnPropertyChangedCallback() {
recycler view를 위한 BindingAdapters를 만들어 보는건 어떨까요?

2019-10-18 06:19 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/ui/ticker/TickerFragment.kt
> +        vm.tickerList.addOnPropertyChangedCallback(object : Observable.OnPropertyChangedCallback() {
aa69c3a

변경했습니다!

2019-10-18 06:19 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/ui/market/MarketActivity.kt
> +        vm.toastMessage.addOnPropertyChangedCallback(object  : Observable.OnPropertyChangedCallback(){
dc82a07

변경했습니다!

2019-10-18 08:23 UTC, junghum21 commented
수고하셨습니다

2019-10-18 08:37 UTC, sjjeong requested changes

2019-10-18 08:37 UTC, sjjeong commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/ui/market/MarketActivity.kt
> +        vm.getMarketAll()
지금 당장은 문제가 없지만 
2주뒤에 공부할 AAC VM에서는 해당 코드가 문제가 될 수 있습니다.

ViewModel class의 init {} 안으로 이동해주세요

2019-10-18 08:45 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/ui/market/MarketActivity.kt
> +        vm.getMarketAll()
a2dbcf8

변경했습니다!

2019-10-22 16:19 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-10-24 08:50 UTC, merged