HW-9 코인헬퍼 Koin 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #243
Opened 2019-10-16 06:04 UTC by preludezdev

- di 패키지를 만들고 레포지토리, 뷰모델, 레트로핏 등을 모듈로 생성해 관리하게끔 작업했습니다.
- 새로고침 기능을 추가했습니다.
- 필터링 기능을 추가했습니다.

2019-10-16 18:14 UTC, dlwls5201 reviewed
동작하는데 이상없이 이쁘게 잘 구현 하신 것 같습니다! Koin도 잘 적용되었습니다. 하지만 di 패키지에서 Network, Repository, ViewModel 3개의 모듈로 구분해주셨는데 저는 더 세분화 하는걸 선호하지만 이부분은 많이 써보면서 뭐가 적합한지는 알아봐야 될것 같습니다 👍

2019-10-16 18:14 UTC, dlwls5201 commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/main/MainActivity.kt
> +
1. ivReload의 클릭 이벤트는 ViewMode에서 데이터바인딩과 observe를 사용해 충분이 처리할 수 있을 것 같습니다. 
2. addOnPageChangeListener와 공통으로 사용하는 vpAdapter.getFragment(pos).refresh() 함수는 pos 파라미터만 다를 뿐 동일한 코드이니 묶어서 사용해도 좋을 것 같습니다.

ps : addOnPageChangeListener() 는 initClickEvent() 에서 초기화 해주는 것은 메소드 명과 맞지 않습니다.

2019-10-17 03:13 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/main/MainActivity.kt
> +
1. 수정했습니다 a6ffc23
2. 수정했습니다 7ae61de, 28b07d6

2019-10-19 05:15 UTC, dlwls5201 reviewed
리뷰가 늦어져서 죄송합니다. ㅠㅜ

ivReload 또한 viewModel에서 옵저빙하면 좋을 것 같다 생각했는데 다시 보니 더 복잡해진것 같네요. 위와 같이 한 경우 viewpager의 addOnPageChangeListener를 adapterbinding을 통해 viewmodel에서 로직이 동작되게 하면 더 좋은 것 같고 아닐경우에는 기존처럼 Activity에서 refreshData()를 하는게 더 좋아 보일것도 같습니다.
(리뷰할 때는 가능한 모든 코드를 viewModel에서 하면 좋겠다는 생각이었습니다..)

이 부분은 저도 MVVM을 많이 안써봐서 어디까지 viewModel에서 처리할지 Activity에서 처리할지 감이 잘 오지 않네요. 고생많으셨습니다!

2019-10-19 16:53 UTC, BeokBeok requested changes
안녕하세요. 스터디 2기 강현석이라고 합니다.
부족하지만 잘 부탁드립니다. 😅 
마지막까지 고생하셨습니다.

2019-10-19 16:53 UTC, BeokBeok commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/data/source/CoinsRepositoryImpl.kt
>                  coinsRemoteDataSource,
koin 을 사용하신다면, 객체를 생성하는 부분은 제거하시는 것이 좋아요.

2019-10-19 16:53 UTC, BeokBeok commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/data/source/local/CoinsLocalDataSource.kt
>              return INSTANCE ?: CoinsLocalDataSource().apply { INSTANCE = this }
koin 을 사용하신다면, 객체를 생성하는 부분은 제거하시는 것이 좋아요.

2019-10-19 16:53 UTC, BeokBeok commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/di/RepositoryModule.kt
> +    single { CoinsLocalDataSource.getInstance() }
인터페이스 타입으로 바인딩 해 주시면 좋아요.
https://insert-koin.io/docs/2.0/documentation/reference/index.html#_definition_binding_an_interface

2019-10-19 16:53 UTC, BeokBeok commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/market/MarketFragment.kt
> +    private lateinit var marketViewModel: MarketViewModel
mutable object는 가급적이면 사용을 지양하는 것이 좋아요.
koin 을 사용하여 val 로 변경하시면 좋을 것 같아요.

2019-10-19 16:53 UTC, BeokBeok commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/viewmodel/MarketViewModel.kt
> +    private var mCoinList = mutableListOf<Coin>()
val 로 변경하시는 것이 좋을 것 같아요.
또한, 맴버변수를 뜻하는 접두어 m 은 안쓰시는 것이 좋은 것 같아요.

2019-10-19 16:53 UTC, BeokBeok commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/main/VpAdapter.kt
> +    private val fragmentReferenceMap = HashMap<Int, Fragment>()
HashMap 보다 SparseArray 를 사용하시는 것이 좋아 보여요.

2019-10-19 16:53 UTC, BeokBeok commented on preludezdev/ArchitectureStudy/app/src/main/res/layout/activity_main.xml
> +            app:layout_constraintTop_toBottomOf="@+id/tabLayout">
id 를 참조할 때에는 + 는 사용하지 않는 것이 좋아요.

2019-10-19 16:53 UTC, BeokBeok commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/data/source/local/CoinsLocalDataSource.kt
> +class CoinsLocalDataSource private constructor() : CoinsDataSource {
이 클래스는 사용하지 않는 것 같아요.
사용하지 않는다면 제거하시는 것이 좋을 것 같아요.

2019-10-19 16:53 UTC, BeokBeok commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/main/MainActivity.kt
> +            }
사용하지 않는다면, 구현부에 주석으로 `NO OP`  를 달아주시거나
OnPageChangeListener 을 구현하는 추상클래스를 생성하여
필요한 함수만 오버라이딩 하시면 좋을 것 같아요.

2019-10-19 16:53 UTC, BeokBeok commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/viewmodel/MainViewModel.kt
> +    val isReload: LiveData<Boolean> get() = _isReload
해당 라이브데이터는 의미가 없는 것 같아요.
리플래시 버튼을 누를때마다 동작하지 않나요?
리플래시 버튼을 눌렀을 때, filter 관련 라이브데이터에 동일한 값을 넣어주면 될 것 같아요.

2019-10-19 16:53 UTC, BeokBeok commented on preludezdev/ArchitectureStudy/app/src/main/res/layout/activity_main.xml
> +            <ImageView
contentDescription 속성을 사용하지 않으시는 경우에는
`android:contentDescription="@null"` 처리나
`tools:ignore="contentDescription"` 처리를 해주시면 좋을 것 같아요.

2019-10-19 16:53 UTC, BeokBeok commented on preludezdev/ArchitectureStudy/app/src/main/res/values/dimen.xml
> +    <dimen name="standard_iv_arrow_size">12dp</dimen>
text size 가 sp 가 아닌 dp 를 사용하신 것은 의도하신건가요?

2019-10-24 00:46 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/di/RepositoryModule.kt
> +    single { CoinsLocalDataSource.getInstance() }
![image](https://user-images.githubusercontent.com/41214420/67444200-fdedb800-f642-11e9-8265-d9ca2c88ab8b.png)
인터페이스 타입으로 하려니까 no cast needed 라고 뜨는데 인터페이스 타입으로 바인딩해주는 이유가 따로 있나요?

2019-10-24 01:03 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/data/source/local/CoinsLocalDataSource.kt
> +class CoinsLocalDataSource private constructor() : CoinsDataSource {
시간이 없어서 못했지만 나중에 사용할 목적으로 미리 만들어놨습니다ㅠ

2019-10-24 01:16 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/viewmodel/MainViewModel.kt
> +    val isReload: LiveData<Boolean> get() = _isReload
filter 관련 라이브데이터는 데이터 변경 시 데이터를 sort 해주는 옵저버 패턴이 적용되어있습니다.  
화살표를 눌렀을 때 해당 분류로 데이터를 sort 해주기 위해서 그렇게 로직을 짜봤거든요. 리플래시 버튼이 눌렀을때는 데이터를 가져오는 작업도 있기 때문에 둘을 분류해주었습니다

2019-10-24 01:24 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/data/source/local/CoinsLocalDataSource.kt
>              return INSTANCE ?: CoinsLocalDataSource().apply { INSTANCE = this }
수정했습니다.

commit : a497d8e

2019-10-24 01:24 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/data/source/CoinsRepositoryImpl.kt
>                  coinsRemoteDataSource,
안녕하세요 현석님, 수정이 늦어서 죄송합니다.
마지막 피드백도 잘 부탁드립니다 :)

수정했습니다.

commit : d71d91f

2019-10-24 01:25 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/market/MarketFragment.kt
> +    private lateinit var marketViewModel: MarketViewModel
수정했습니다

commit : 7ee63a2

2019-10-24 01:25 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/viewmodel/MarketViewModel.kt
> +    private var mCoinList = mutableListOf<Coin>()
수정했습니다

commit : 6b3c832

2019-10-24 01:25 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/main/VpAdapter.kt
> +    private val fragmentReferenceMap = HashMap<Int, Fragment>()
수정했습니다

commit : 50c8067

2019-10-24 01:26 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/res/layout/activity_main.xml
> +            app:layout_constraintTop_toBottomOf="@+id/tabLayout">
수정했습니다

commit : 36acd25

2019-10-24 01:26 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/main/MainActivity.kt
> +            }
수정했습니다 

commit  : 7f269fe

2019-10-24 01:27 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/res/layout/activity_main.xml
> +            <ImageView
수정했습니다

commit : 46f289e

2019-10-24 01:29 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/res/values/dimen.xml
> +    <dimen name="standard_iv_arrow_size">12dp</dimen>
네 의도했습니다. sp 사용했을 때 폰 시스템 폰트 크기를 바꾸면 레이아웃이 다 깨지더라구요.

2019-10-24 02:26 UTC, BeokBeok commented on preludezdev/ArchitectureStudy/app/src/main/res/values/dimen.xml
> +    <dimen name="standard_iv_arrow_size">12dp</dimen>
의도하신 것이라면
`tools:ignore="SpUsage"` 를 넣어주시면 해당 warning 은 제거할 수 있어요.
말씀하신 상황에 따라, 꼭 sp 를 사용하지 않으셔도 됩니다.

2019-10-24 02:26 UTC, BeokBeok commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/viewmodel/MainViewModel.kt
> +    val isReload: LiveData<Boolean> get() = _isReload
태휘님이 의도하신 기능과 맞는지 모르겠지만
한번 isReload 를 제거하고 코드를 작성해봤어요.
```
// MainActivity
class MainActivity : BaseActivity<ActivityMainBinding>(R.layout.activity_main) {
...
    private fun initEvent() {
        binding.viewPager.addOnPageChangeListener(object : AbstractOnPageChangeListener() {
            override fun onPageSelected(position: Int) {
                binding.viewModel?.reloadData()
            }
        })
    }

    private fun initCallback() {
        mainViewModel.filter.observe(this, Observer {
            for (position in 0 until vpAdapter.count) {
                vpAdapter.getFragment(position)?.sortData(it.first, it.second)
            }
            vpAdapter.getFragment(binding.viewPager.currentItem)?.reload(it.first, it.second)
        })
    }
}
```

```
// MainViewModel
class MainViewModel : ViewModel() {
...
    fun showSortedTypeArrow(type: Filter.Type) {
        when (type) {
            _type.value -> {
                _isSelected.value = !(isSelected.value)!!
                _order.value =
                    if (order.value == Filter.Order.ASC) Filter.Order.DESC else Filter.Order.ASC
            }
            else -> {
                _type.value = type
            }
        }

        reloadData()
    }

    fun reloadData() {
        _filter.value = Pair(_type.value!!, _order.value!!)
    }
}
```
한번 확인해주세요~

2019-10-24 02:26 UTC, BeokBeok commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/di/RepositoryModule.kt
> +    single { CoinsLocalDataSource.getInstance() }
현재 태휘님 브랜치를 받아서 작성했을 경우에는 no cast needed 가 뜨지 않네요.

인터페이스 타입으로 바인딩해주시면
CoinsRemoteDataSource 와 CoinsLocalDataSource 의 타입이 동일해지기 때문에
name 을 붙여서 사용하시면 될 것 같습니다.
https://insert-koin.io/docs/2.0/documentation/reference/index.html#_definition_naming_default_bindings

2019-10-24 07:50 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/di/RepositoryModule.kt
> +    single { CoinsLocalDataSource.getInstance() }
![image](https://user-images.githubusercontent.com/41214420/67463823-17abf100-f67d-11e9-86e3-ab237ff24842.png)

말씀해주신대로 하려고 하면 해당 레포지토리를 이용해 뷰모델을 만드는데 이 부분에서 객체 생성이 안되고 계속 에러가 나고있습니다. single<>  방식으로 인터페이스 타입을 명시해서 바인딩 하려고 해도 같은 에러가 납니다. 혹시 몰라서 해당 클래스들의 인자를 구현클래스가 아닌 인터페이스로 바꿔도 같은 에러가 납니다ㅠㅠ 인터페이스로 바인딩하는게 위에서 제가 작성한데로 코딩하는게 맞는지 궁금합니다.

2019-10-24 08:07 UTC, BeokBeok commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/di/RepositoryModule.kt
> +    single { CoinsLocalDataSource.getInstance() }
```
val repositoryModule = module {
    single { CoinsRepositoryImpl(get(named("Remote")), get(named("Local"))) }
    single(named("Remote")) { CoinsRemoteDataSource(get()) as CoinsDataSource }
    single(named("Local")) { CoinsLocalDataSource() as CoinsDataSource }
}
```
![스크린샷 2019-10-24 오후 5 04 50](https://user-images.githubusercontent.com/48344355/67465608-732bae00-f680-11e9-865c-ffb5280f11aa.png)
이렇게 쓰시면 될 것 같습니다.

말씀하신 에러 관련해서는 MarketViewModel 에서 Repository 의 타입을 맞춰주시면 될 것 같습니다.
만약, ViewModel 단도 인터페이스로 바인딩하고 싶으시다면
MarketViewModel의 Repository 의 타입을 변경해주시면 될 것 같습니다.
```
class MarketViewModel(
    private val repository: CoinsRepository,
    private val keyMarket: String?
) : ViewModel() {
...
```

2019-10-24 08:39 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/viewmodel/MainViewModel.kt
> +    val isReload: LiveData<Boolean> get() = _isReload
- 이렇게 하면 화살표 아이콘 클릭 시 데이터 sort 뿐만 아니라 데이터 load 도 하게 되서 제 의도와는 다르게 구현되는 것 같아요. 저는 데이터 load 는 데이터 load 만 하고 화살표 클릭해서 sort 할 때는 데이터 load 랑 상관없이 기존에 가지고 있는 데이터만 sort 해주려고 저렇게 작성한거였거든요. 
- 데이터 load 안에 현재 정렬기준값을 가지고 sort 하는 로직도 있는데 initCallBack() 안에서 sort 먼저 한다음 다시 데이터를 가져와서 또 같은 기준으로 sort 하는건 조금 비효율적인 것 같아요

2019-10-24 08:49 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/di/RepositoryModule.kt
> +    single { CoinsLocalDataSource.getInstance() }
![image](https://user-images.githubusercontent.com/41214420/67468958-64e09080-f686-11e9-9d89-cf5344fd8588.png)
- 말씀해주신데로 코드 변경하고 MarketViewModel 인자도 CoinsRepository 인터페이스로 받게 했지만 에러는 그대로네요. 
- 일단 안스 3.5.1로 업그레이드 하고 그래들도 업데이트 하니까 no cast needed 는 안뜨네요. 그런데 아직 해당 에러는 해결이 안되고 있습니다...

2019-10-24 08:50 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/res/values/dimen.xml
> +    <dimen name="standard_iv_arrow_size">12dp</dimen>
수정했습니다

commit : 943da90

2019-10-25 01:56 UTC, BeokBeok commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/viewmodel/MainViewModel.kt
> +    val isReload: LiveData<Boolean> get() = _isReload
저도 스터디 진행했을 때 Sort 기능을 넣었었는데
저같은 경우에는 Remote Data Source 를 Local 로 저장해서
Local 에 저장한 데이터를 Sort 해서 뿌려주게 하였습니다.

태휘님이 의도하신 바와 다르다고 말씀하시니 이 리뷰는 닫도록 하겠습니다. 😅

2019-10-25 01:57 UTC, BeokBeok commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/di/RepositoryModule.kt
> +    single { CoinsLocalDataSource.getInstance() }
```
val repositoryModule = module {
    single { CoinsRepositoryImpl(get(named("Remote")), get(named("Local"))) }
    single(named("Remote")) { CoinsRemoteDataSource(get()) as CoinsDataSource }
    single(named("Local")) { CoinsLocalDataSource() as CoinsDataSource }
}
```
이렇게 쓰신다면 MarketViewModel 에서 받는 Repository 타입을 CoinsRepositoryImpl

```
val repositoryModule = module {
    single { CoinsRepositoryImpl(get(named("Remote")), get(named("Local"))) as CoinsRepository }
    single(named("Remote")) { CoinsRemoteDataSource(get()) as CoinsDataSource }
    single(named("Local")) { CoinsLocalDataSource() as CoinsDataSource }
}
```
이렇게 쓰신다면 MarketViewModel 에서 받는 Repository 타입을 CoinsRepository 로 변경하시면 될 것 같아요

2019-10-25 03:08 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/di/RepositoryModule.kt
> +    single { CoinsLocalDataSource.getInstance() }
아... MarketViewModel 에 레포지토리 타입을 바꿨으니까 di 에서도 해당 부분 데이터 타입을 변경해줬어야 했는데 안해서 에러가 난거였군요. 아직 코인이 익숙치 않아서 어디가 잘못된건지 잘 안보이네요ㅠㅠ 알려주신대로 수정했습니다. 계속 질문해서 많이 귀찮으셨을텐데 피드백 해주셔서 정말 감사합니다!!

commit : 9dd6856

2019-10-25 03:19 UTC, BeokBeok submitted a review, later dismissed
LGTM:ok_hand:

---

부족한 리뷰를 대응해주셔서 감사드리고
스터디 하시느라 고생 많으셨습니다. 👍

2019-10-27 11:08 UTC, sjjeong requested changes

2019-10-27 11:08 UTC, sjjeong commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/data/source/CoinsRepositoryImpl.kt
> +    private val coinsRemoteDataSource: CoinsRemoteDataSource,
CoinsDataSource로 하면 문제가 있나요?

2019-10-27 11:08 UTC, sjjeong commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/data/CoinTickerResponse.kt
> +        val mTradePrice = when {
m을 prefix로 사용하지 말아주세요

2019-10-28 03:45 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/data/CoinTickerResponse.kt
> +        val mTradePrice = when {
수정했습니다

commit : d27fc1b

2019-10-28 03:45 UTC, preludezdev commented on preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/data/source/CoinsRepositoryImpl.kt
> +    private val coinsRemoteDataSource: CoinsRemoteDataSource,
수정했습니다

commit : e0136f4

2019-10-29 06:45 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-10-30 02:10 UTC, merged