HW9 - Koin 적용하기
sjjeong/GoogryAndroidArchitecutreStudy pull request #244
Opened 2019-10-16 11:55 UTC by wkdehdlr

스터디하면서 재영님께 많이 배웠습니다 👍

2019-10-17 06:22 UTC, zozero94 reviewed
저도 아직 코인에 대해 공부가 부족해서 리뷰를 할 수 있는게 얼마 없네요 ㅠ_ㅠ...
시간 날 때 다른분들 리뷰 컨닝좀 하고 다시 오겠습니다!

2019-10-17 06:22 UTC, zojae031 commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/tasks/UpbitFragment.kt
> +    val viewModel by viewModel<UpbitViewModel>()
이렇게 해도 
```kotlin
val viewModel : UpbitViewModel by inject()
```
이 문법과 같은건가요?? 제가 잘 모르겠어서 ㅇ_ㅇ..

2019-10-18 05:13 UTC, zojae031 commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/tasks/UpbitFragment.kt
> +    val viewModel by viewModel<UpbitViewModel>()
koin 문서보고 이해했습니다!
덕분에 배워갑니다 ㅎ

2019-10-28 10:48 UTC, BeokBeok requested changes
안녕하세요. 스터디 2기 강현석이라고 합니다.
부족하지만 잘 부탁드립니다. 😅

2019-10-28 10:48 UTC, BeokBeok commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/data/remote/di/RemoteModule.kt
> +    single { UpbitRemoteDataSource(get()) }
인터페이스 타입으로 바인딩 하시는 것이 좋아요.
https://insert-koin.io/docs/2.0/documentation/koin-core/index.html#_definition_binding_an_interface

2019-10-28 10:48 UTC, BeokBeok commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/tasks/UpbitViewModel.kt
> +    val tickerList = MutableLiveData<List<UpbitItem>>()
public getter private setter 로 만들어주시면 좋을 것 같아요.

private setter 는 MutableLiveData 로 사용하시고
public getter 는 LiveData 로 사용하시면 될 것 같아요.

[property-names](https://kotlinlang.org/docs/reference/coding-conventions.html#property-names) 의 **Names for backing properties**

2019-10-28 10:48 UTC, BeokBeok commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/data/Repository.kt
>      private val upbitLocalDataSource: UpbitLocalDataSource = UpbitLocalDataSource
사용하지 않다면, 제거하시는 것이 좋을 것 같아요.

2019-10-28 10:48 UTC, BeokBeok commented on wkdehdlr/CoinHelper/app/build.gradle
> +    implementation "org.koin:koin-androidx-scope:2.0.1"
scope 는 없어도 될 것 같아요.

2019-10-28 10:48 UTC, BeokBeok commented on wkdehdlr/CoinHelper/app/src/main/java/kr/schoolsharing/coinhelper/data/di/RepositoryModule.kt
> +    single { Repository(get()) }
인터페이스 타입으로 바인딩 하시는 것이 좋아요.
https://insert-koin.io/docs/2.0/documentation/koin-core/index.html#_definition_binding_an_interface

2019-11-04 02:44 UTC, closed without merging