HW-06 MVVM 패턴 적용하기.
sjjeong/GoogryAndroidArchitecutreStudy pull request #245
Opened 2019-10-16 16:10 UTC by onemask

presenter 해서 하는 작업들을 viewModel 로 바꾸었습니다. 

* activity 
* fragment
* recyclerview 
전부 Databinding을 적용하였습니다. 

Ticker() data class에서 data를 가져올 수 있게끔 함수를 만들었는데,
해당 사항 효율 적이지가 않은것 같아서 다른 효율적인 방법이 있는지 궁금합니다.

2019-10-18 08:43 UTC, sjjeong requested changes

2019-10-18 08:43 UTC, sjjeong commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/tickerlist/viewmodel/TickerViewModel.kt
> +                    tickerList.set(it.map(TickerResponse::toTicker))
여기에는 it.map(TickerResponse::toTicker)만 있고
set하는건 subscribe에서 해주세요

2019-10-20 07:59 UTC, onemask commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/tickerlist/viewmodel/TickerViewModel.kt
> +                    tickerList.set(it.map(TickerResponse::toTicker))
수정하였습니다. 
248249

2019-10-22 16:48 UTC, sjjeong requested changes
전체적으로 Reformat Code가 필요해보이네요

2019-10-22 16:48 UTC, sjjeong commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/tickerlist/adapter/TIckerLIstBindingAdapter.kt
> +object TIckerLIstBindingAdapter {
i에 힘이 많이 들어갔네요

2019-10-22 16:48 UTC, sjjeong commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/tickerlist/viewmodel/TickerViewModel.kt
> +                    ticker::toTicker.invoke()
이건 무슨 문법이죠? ㅋㅋㅋ
ticker.toTicker()만 해도 될 것 같네요 
아니면 tickerList.map(Ticker::toTicker) 정도면 되겠네요

2019-10-22 16:48 UTC, sjjeong commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/util/DataFormatutils.kt
> +object DataFormatUtills {
위에 패키지가 없네요

2019-10-25 09:57 UTC, onemask commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/tickerlist/viewmodel/TickerViewModel.kt
> +                    ticker::toTicker.invoke()
온갖가지의 방법으로 map이 중첩되었네요..
수정하였습니다~ 2e83109

2019-10-25 09:58 UTC, onemask commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/util/DataFormatutils.kt
> +object DataFormatUtills {
수정하였습니다.
2332ad6

2019-10-25 09:58 UTC, onemask commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/tickerlist/adapter/TIckerLIstBindingAdapter.kt
> +object TIckerLIstBindingAdapter {
힘을 줄여보았습니다~
b303b7b

2019-10-25 12:56 UTC, sjjeong commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/tickerlist/adapter/TIckerLIstBindingAdapter.kt
> +object TIckerLIstBindingAdapter {
list도!

2019-10-25 13:05 UTC, sjjeong requested changes
list에도 i가!

2019-10-25 13:55 UTC, onemask commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/tickerlist/adapter/TIckerLIstBindingAdapter.kt
> +object TIckerLIstBindingAdapter {
꼼꼼히 보는 습관을 길러야겠어요...ㅠㅠㅠ 꼼꼼히 봐주셔서 감사합니다...
수정하였습니다. 
1d0d79b

2019-10-26 03:19 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-11-03 03:35 UTC, merged