HW-06 MVVM 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #246
Opened 2019-10-17 07:11 UTC by junghum21

이번에도 커밋이 보기 좋지 않을수 있습니다 ㅠㅠ

files changed를 활용해 주세요.

잘 부탁드립니다.

2019-10-17 08:09 UTC, toctocbin commented on junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/ui/main/MainActivity.kt
> +    override val viewModel by lazy {
다음은 지연 초기화 관련하여 Effective Java 에 나와있는 글입니다.

아이템 83. 지연 초기화는 신중히 사용하라.
지연초기화는 양날의 검이다. 클래스 혹은 인스턴스 생성 시의 초기화 비용은 줄지만 그 대신 지연 초기화하는 필드에 접근하는 비용은 커진다. 지연 초기화하려는 필드들 중 결국 초기화가 이뤄지는 비율에 따라, 실제 초기화에 드는 비용에 따라, 초기화된 각 필드를 얼마나 빈번히 호출하느냐에 따라 지연 초기화가 (다른 수많은 최적화와 마찬가지로) 실제로는 성능을 느려지게 할 수도 있다.
그럼에도 지연 초기화가 필요할 때가 있다. 해당 클래스의 인스턴스 중 그 필드를 사용하는 인스턴스의 비율이 낮은 반면, 그 필드의 초기화하는 비용이 크다면 지연 초기화가 제 역할을 해줄 것이다. 하지만 안타깝게도 정말 그런지를 알 수 있는 유일한 방법은 지연 초기화 적용 전후의 성능을 측정해보는 것이다.
...
대부분의 상황에서 일반적인 초기화가 지연 초기화보다 낫다.

이전에 이런 피드백을 받았었습니다!

2019-10-18 02:31 UTC, haanbin commented on junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/ui/main/MainActivity.kt
> +    override val viewModel by lazy {
다음은 지연 초기화 관련하여 Effective Java 에 나와있는 글입니다.

아이템 83. 지연 초기화는 신중히 사용하라.
지연초기화는 양날의 검이다. 클래스 혹은 인스턴스 생성 시의 초기화 비용은 줄지만 그 대신 지연 초기화하는 필드에 접근하는 비용은 커진다. 지연 초기화하려는 필드들 중 결국 초기화가 이뤄지는 비율에 따라, 실제 초기화에 드는 비용에 따라, 초기화된 각 필드를 얼마나 빈번히 호출하느냐에 따라 지연 초기화가 (다른 수많은 최적화와 마찬가지로) 실제로는 성능을 느려지게 할 수도 있다.
그럼에도 지연 초기화가 필요할 때가 있다. 해당 클래스의 인스턴스 중 그 필드를 사용하는 인스턴스의 비율이 낮은 반면, 그 필드의 초기화하는 비용이 크다면 지연 초기화가 제 역할을 해줄 것이다. 하지만 안타깝게도 정말 그런지를 알 수 있는 유일한 방법은 지연 초기화 적용 전후의 성능을 측정해보는 것이다.
...
대부분의 상황에서 일반적인 초기화가 지연 초기화보다 낫다.

이전에 이런 피드백을 받았었습니다!

2019-10-18 02:31 UTC, haanbin commented on junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/ui/main/MainActivity.kt
> +        viewModel.markets.run {
run 을 사용하신 이유가 궁금합니다 !

2019-10-18 02:40 UTC, junghum21 commented on junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/ui/main/MainActivity.kt
> +        viewModel.markets.run {
callback 메소드 안에서 viewModel.markets 에 또 접근해야해서 run을 사용했습니다.

2019-10-18 03:14 UTC, junghum21 commented on junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/ui/main/MainActivity.kt
> +    override val viewModel by lazy {
좋은 정보와 피드백 감사합니다.

지연초기화에 관해선 그냥 아무 생각없이 썼었고,

주로 intent extra나 bundle arguments extra에 지연초기화를 사용 했었어요.

2019-10-18 08:15 UTC, haanbin commented on junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/ui/main/MainActivity.kt
> +        viewModel.markets.run {
아 두번사용하셨군요 수고하셨습니다 !

2019-10-18 08:49 UTC, sjjeong requested changes

2019-10-18 08:49 UTC, sjjeong commented on junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/base/BaseActivity.kt
> +        viewModel.start()
나중에 AAC VM을 가면 이런 패턴은 좋지 않습니다.
ViewModel class 내부에 init {}을 만들어서 처리해주세요 

Fragment도 수정 해주세요

2019-10-18 08:49 UTC, sjjeong commented on junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/ui/main/MainActivity.kt
> +    override val viewModel by lazy {
제 개인적인 경험에 기반하여 이야기 해보자면
저는 주로 ViewModel은 lazy를 사용하는 편이고
lifecycle에 맞춰서 onCreate나 onActivityCreated에서 ViewModel을 사용함으로써 lifecycle 시점에 생성해주는 편입니다.

2019-10-21 02:44 UTC, junghum21 commented on junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/base/BaseActivity.kt
> +        viewModel.start()
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/246/commits/1cbfe43bb264d4662e5e23fdc6319acd8d2b142c

반영완료

2019-10-21 02:46 UTC, junghum21 commented on junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/ui/main/MainActivity.kt
> +    override val viewModel by lazy {
ViewModel의 경우 init {} 코드가 activity, fragment 생성 시점에 동작해야 하니 저도 그것이 적절하다고 생각합니다.

2019-10-22 16:55 UTC, sjjeong approved these changes

2019-10-23 08:10 UTC, merged