HW-06 MVVM 패턴 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #247
Opened 2019-10-17 09:24 UTC by seonoh

제가 이번주 결혼식이 있어서 참석하지 못합니다.
배워야할게 아직 많은데... !! 
우선 제가 생각하고 있는 패턴대로 작성해봤습니다.
다른분이 하신것처럼 viewmodel안에 loadData 로직을 넣는 것이 맞는지 의문입니다.

2019-10-17 12:32 UTC, jskim5923 reviewed
수고하셨습니다.

2019-10-17 12:32 UTC, jskim5923 commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/BaseActivity.kt
> +    protected val compositeDisposable = CompositeDisposable()
compositeDisposable 변수는 BaseViewModel에 있는 것이 좋아보입니다.

2019-10-17 12:32 UTC, jskim5923 commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/BaseActivity.kt
> +        compositeDisposable.clear()
compositeDisposable clear는 BaseViewModel에서 담당하는 것이 좋을 것같습니다.

2019-10-17 12:32 UTC, jskim5923 commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/BaseFragment.kt
> +    protected val compositeDisposable = CompositeDisposable()
compositeDisposable 변수는 BaseViewModel에 있는 것이 좋아보입니다.

2019-10-17 12:32 UTC, jskim5923 commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/BaseFragment.kt
> +        compositeDisposable.clear()
compositeDisposable clear는 viewModel에서 담당하는 것이 좋아보입니다.

2019-10-17 12:32 UTC, jskim5923 commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinFragment.kt
> +    }
data를 repository에서 가져와 변환 및 ObservableField에 set하는 로직은 viewModel에서 담당하는 것이 좋을 것 같습니다.

2019-10-17 12:32 UTC, jskim5923 commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/MainActivity.kt
> +    private fun loadData() {
data를 repository에서 가져와  ObservableField에 set하는 로직은 viewModel에서 담당하는 것이 좋을 것 같습니다.

2019-10-18 02:09 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/BaseActivity.kt
> +    protected val compositeDisposable = CompositeDisposable()
08c3d8e06877c62f4db6293bdaf9f6ac57a0c2a2 수정했습니다. 감사합니다!

2019-10-18 02:10 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/BaseActivity.kt
> +        compositeDisposable.clear()
08c3d8e06877c62f4db6293bdaf9f6ac57a0c2a2

2019-10-18 02:10 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/BaseFragment.kt
> +        compositeDisposable.clear()
0323d8eb0d4232c5ac408445e712bbb9b538d429

2019-10-18 02:10 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinFragment.kt
> +    }
b74c410c7831045a1084087f3eea72243654a476

2019-10-18 02:10 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/MainActivity.kt
> +    private fun loadData() {
4753f1e99993eda80d0c8483e6ae090517650aca

2019-10-18 11:43 UTC, jskim5923 commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/MainActivity.kt
> +    private var pagerAdapter = TabPagerAdapter(supportFragmentManager)
한번에 코멘트를 남기지 못해 죄송합니다.
해당 변수는 immutable로 선언하는 것이 좋을 것 같습니다.
supportFragmentManager가 lifecycle에 의존성이 있는지는 확실하지나, 의존성이 있다면 by lazy 패턴도 함께 사용하는것이 좋을것 같습니다.

2019-10-18 11:43 UTC, jskim5923 commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/model/MainViewModel.kt
> +    var marketInfo = ObservableField<List<String>>()
한번에 코멘트 남기지 못해 죄송합니다.
해당 변수는 private val 로 선언하는것이 좋을 것 같습니다.

2019-10-18 11:43 UTC, jskim5923 commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/model/CoinViewModel.kt
> +    var coinItem = ObservableField<List<UseCoinModel>>()
한번에 코멘트 남기지 못해 죄송합니다.
해당 변수는 private val 로 선언하는것이 좋아보입니다.

2019-10-21 01:33 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/MainActivity.kt
> +    private var pagerAdapter = TabPagerAdapter(supportFragmentManager)
a4a395f866d0b5f40e473be2466ee56f5181a19a

2019-10-21 01:34 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/model/MainViewModel.kt
> +    var marketInfo = ObservableField<List<String>>()
a55f0fc853ef09b57df2b47e73ffd53ae96d2101

2019-10-21 01:34 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/model/CoinViewModel.kt
> +    var coinItem = ObservableField<List<UseCoinModel>>()
6b8e853ce29e16442ccc0d0e89bd96cb0aeda43e

2019-10-21 09:25 UTC, jskim5923 submitted a review, later dismissed

2019-10-21 15:05 UTC, BeokBeok requested changes
안녕하세요. 스터디 2기 강현석이라고 합니다.
부족하지만 잘 부탁드립니다. 😅

2019-10-21 15:05 UTC, BeokBeok commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/BaseActivity.kt
> +import io.reactivex.disposables.CompositeDisposable
불필요한 import 는 제거해주세요.

2019-10-21 15:05 UTC, BeokBeok commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/BaseApplication.kt
> +class BaseApplication : Application() {
application 의 context 를 사용하는 용도로 만드신 것이라면,
activity 단이나 fragment 단에서 얻어오는 방식으로 하시는 것이 좋을 것 같아요.

2019-10-21 15:05 UTC, BeokBeok commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/BaseFragment.kt
> +    protected val compositeDisposable = CompositeDisposable()
저도 종선님과 같은 의견입니다.

2019-10-21 15:05 UTC, BeokBeok commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinAdapter.kt
> +    fun setCoinData(data: List<UseCoinModel>) {
이 함수를 호출하는 부분에서는 data 가 nullable 이기 때문에
본 함수에서도 nullable 처리를 해주시는 것이 좋을 것 같아요.

2019-10-21 15:05 UTC, BeokBeok commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinBindingAdapter.kt
> +    @JvmStatic
해당 annotation 은 제거하셔도 될 것 같아요.

2019-10-21 15:05 UTC, BeokBeok commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/model/BaseViewModel.kt
> +    protected val coinRepository = CoinRepositoryImpl()
이 부분은 여기에 있으면 안될 것 같아요.
BaseViewModel 을 상속받는 ViewModel 에서 처리해주시는 것이 좋을 것 같아요.

2019-10-21 15:05 UTC, BeokBeok commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/model/BaseViewModel.kt
> +    protected val compositeDisposable = CompositeDisposable()
private 로 하셔도 될 것 같아요.

2019-10-21 15:05 UTC, BeokBeok commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/model/BaseViewModel.kt
> +    }
이 부분을 onCleared 함수를 오버라이딩 하시어 처리하시는 것이 좋을 것 같아요.

2019-10-21 15:05 UTC, BeokBeok commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/model/CoinViewModel.kt
> +    private val coinItem = ObservableField<List<UseCoinModel>>()
접근자를 private 로 하시면 xml에서 접근할 때 접근이 안되지 않나요?

2019-10-21 15:05 UTC, BeokBeok commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/model/CoinViewModel.kt
> +                it.accTradePrice24h?.let { CalculateUtils.setTradeAmount(marketType, it) ?: "0" }
accTradePrice24h 변수가 nonnull 이기 때문에
let 을 사용하지 않으셔도 될 것 같아요.

2019-10-21 15:05 UTC, BeokBeok commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/model/MainViewModel.kt
> +    private val marketInfo = ObservableField<List<String>>()
접근자가 private 이면 xml 에서 접근할 때 접근이 안되지 않나요?

2019-10-21 15:05 UTC, BeokBeok commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/util/CalculateUtils.kt
> +        return String.format(
string 을 return 하신 다음에
받는 쪽에서 format 처리를 하시는 것이 좋을 것 같아요.

2019-10-21 15:05 UTC, BeokBeok commented on seonoh/ArchitectureStudy/app/src/main/res/layout/activity_main.xml
>              xmlns:app="http://schemas.android.com/apk/res-auto"
xmlns 는 최상위 엘리먼트에 있는 것이 좋을 것 같아요.

2019-10-21 15:05 UTC, BeokBeok commented on seonoh/ArchitectureStudy/app/src/main/res/layout/coin_item.xml
> +            xmlns:app="http://schemas.android.com/apk/res-auto"
xmlns 는 최상위 엘리먼트에 있는 것이 좋을 것 같아요.

2019-10-22 00:46 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/BaseActivity.kt
> +import io.reactivex.disposables.CompositeDisposable
네 해당 임포트는 지워져있었고, 또 다른 불필요 임포트가 있어서 제거했습니다.
3d23a4c03f14ecb56ed0a825933ffefbcea6c461

2019-10-22 00:50 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/BaseApplication.kt
> +class BaseApplication : Application() {
네 감사합니다.
혹시 Application단 onCreate에서 받으면 문제될 부분이 있어서 그런건가요?

2019-10-22 00:53 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinAdapter.kt
> +    fun setCoinData(data: List<UseCoinModel>) {
ab2f674f9488e04b2a476f5cdb1b11d845d08e2c

2019-10-22 02:17 UTC, BeokBeok commented
commit id 달아주세요

2019-10-23 01:01 UTC, seonoh commented
어느 부분 commit id가 필요하신가요? 현석님 코멘트에 수정하지 않고 답글남긴거 외에는 모두 커밋id를 달아두었습니다!

2019-10-23 05:52 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinBindingAdapter.kt
> +    @JvmStatic
해당어노테이션 ( @JvmStatic)을 지우게 되면, object에서 사용하려면 static을 사용하여야한다는 에러 문구가 나타납니다!

2019-10-23 05:52 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/model/BaseViewModel.kt
> +    protected val compositeDisposable = CompositeDisposable()
해당 compositeDisposable을 privat로 선언하게되면 CoinViewModel에서 loadData시에 compositeDisposable에 접근할수가 없습니다. 혹시 다른방법이 있는건가요?

2019-10-23 05:52 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/model/BaseViewModel.kt
> +    protected val coinRepository = CoinRepositoryImpl()
네 수정했습니다. 99105166e1c3bcbb7ec2e469829d03ea679a42a8
그런데 이렇게되면 같은 코드를 두번 써줘야하는 번거로움이 있는데, 그래도 이 방법이 가독성떄문에 괜찮은건가요?

2019-10-23 05:52 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/model/BaseViewModel.kt
> +    }
죄송하지만 onCleared함수는 어디에 있는 함수인가요?

2019-10-23 05:52 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/model/CoinViewModel.kt
> +    private val coinItem = ObservableField<List<UseCoinModel>>()
맞습니다. 수정했습니다! 감사합니다.
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/commit/99105166e1c3bcbb7ec2e469829d03ea679a42a8

2019-10-23 05:52 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/model/CoinViewModel.kt
> +                it.accTradePrice24h?.let { CalculateUtils.setTradeAmount(marketType, it) ?: "0" }
a9c36be03646c446e7596ff2fb02c77a2dc1eb35

2019-10-23 05:52 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/model/MainViewModel.kt
> +    private val marketInfo = ObservableField<List<String>>()
9910516

2019-10-23 05:52 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/util/CalculateUtils.kt
> +        return String.format(
그렇게되면 viewmodel 로직에 context가 있게되는데 괜찮은건가요? ( MVP 일때는 Presenter에 context가 들어가게되어서 이렇게 코딩했었습니다. )

2019-10-23 05:52 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/res/layout/coin_item.xml
> +            xmlns:app="http://schemas.android.com/apk/res-auto"
64e9fe71a06285f57859eb30b333c5979fb115c2

2019-10-23 05:52 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/res/layout/activity_main.xml
>              xmlns:app="http://schemas.android.com/apk/res-auto"
69cd979d803b1b42b92f9fb8c6adb0c9eb5764e7

2019-10-23 08:54 UTC, BeokBeok commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/util/CalculateUtils.kt
> +        return String.format(
coin_item.xml 에서 데이터바인딩을 활용하셔서 format 처리를 하시면 될 것 같습니다.

2019-10-23 08:54 UTC, BeokBeok commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/model/BaseViewModel.kt
> +    }
혹시 AAC ViewModel 에 대해서 진도가 나갔나요?

2019-10-23 08:54 UTC, BeokBeok commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/model/BaseViewModel.kt
> +    protected val compositeDisposable = CompositeDisposable()
BaseViewModel 에 add 함수를 만드셔서 관리하시면 될 것 같습니다.

2019-10-23 08:54 UTC, BeokBeok commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/model/BaseViewModel.kt
> +    protected val coinRepository = CoinRepositoryImpl()
coinRepository 자체는 base 가 아니지 않을까요?
BaseViewModel 를 모든 ViewModel 에서 상속받아서 사용할텐데
coinRepository 와 관련없는 ViewModel 을 만드시게 된다면 문제가 될 것 같습니다.

2019-10-23 08:54 UTC, BeokBeok commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinBindingAdapter.kt
> +    @JvmStatic
object 내부에서 사용해서 그런 것 같습니다.
object 를 제거하시고 사용하시면 될 것 같습니다.

2019-10-23 08:54 UTC, BeokBeok commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinAdapter.kt
> +    fun setCoinData(data: List<UseCoinModel>) {
파라미터 타입이 nonnull 이기 때문에,
nullable 처리하신 것은 의미가 없어 보입니다.
파라미터 타입을 nonnull 이 아닌 nullable 처리를 하시는 것이 좋을 것 같습니다.

2019-10-23 08:54 UTC, BeokBeok commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/BaseApplication.kt
> +class BaseApplication : Application() {
이런 방식으로 하지 않아도 application 의 context 를 얻어올 수 있기 때문입니다.

2019-10-23 08:58 UTC, BeokBeok commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinAdapter.kt
> +        data?.let {
immutable 인 경우에는 let 보다 if 문을 사용하여 null check 하는 것이 좋아요.

2019-10-23 08:58 UTC, BeokBeok commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/MainActivity.kt
> +        BaseApplication.context = this
application 의 context 를 main activity 의 context 로 바꾸는 것은 문제가 있어 보여요.

2019-10-23 08:58 UTC, BeokBeok commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/model/CoinViewModel.kt
> +    private val coinRepository = CoinRepositoryImpl()
coinRepository 를 주입받아서 사용하시는 것이 좋을 것 같아요.

2019-10-23 08:58 UTC, BeokBeok commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/model/MainViewModel.kt
> +    private val coinRepository = CoinRepositoryImpl()
coinRepository 를 주입받아서 사용하시는 것이 좋을 것 같아요.

2019-10-24 00:56 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/BaseApplication.kt
> +class BaseApplication : Application() {
네 답변감사합니다!!

2019-10-24 00:58 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinAdapter.kt
> +    fun setCoinData(data: List<UseCoinModel>) {
d1c6d0a9a9980e37a847448314dd4abde3c43244

2019-10-24 01:01 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinBindingAdapter.kt
> +    @JvmStatic
179c97b81df41e70e859ba4fdd304e6f9435a64a

2019-10-24 01:23 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/util/CalculateUtils.kt
> +        return String.format(
a2141844892c147ea7a3d9a43805c07ab5bd201f 감사합니다 !

2019-10-24 01:25 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/MainActivity.kt
> +        BaseApplication.context = this
네 리뷰 반영하면서 BaseApplication 제거했습니다.
25245d533dc73da2501b062583f3e8ee59ae5654

2019-10-24 01:32 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinAdapter.kt
> +        data?.let {
아 그렇군요!! 감사합니다 !!
042e0a8b19eaa24ecdc472d129f724e9b5000311

2019-10-24 01:51 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/model/CoinViewModel.kt
> +    private val coinRepository = CoinRepositoryImpl()
adc6f3fa020d239189f29ea9729de8f23832f3fc

2019-10-24 01:51 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/model/MainViewModel.kt
> +    private val coinRepository = CoinRepositoryImpl()
adc6f3fa020d239189f29ea9729de8f23832f3fc

2019-10-24 01:51 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/model/BaseViewModel.kt
> +    protected val coinRepository = CoinRepositoryImpl()
감사합니다!! 
adc6f3fa020d239189f29ea9729de8f23832f3fc

2019-10-24 01:52 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/model/BaseViewModel.kt
> +    }
아직입니다 !!

2019-10-24 01:57 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/model/BaseViewModel.kt
> +    protected val compositeDisposable = CompositeDisposable()
네 감사합니다 ! d00cd16044d72aba1714eab7d12274c6b193f202

2019-10-24 02:31 UTC, BeokBeok commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/model/BaseViewModel.kt
> +    }
이 부분은 AAC ViewModel 을 학습하시게 되면 아시게 되는 부분이므로
이 리뷰는 닫도록 하겠습니다. 😅

2019-10-24 03:19 UTC, BeokBeok commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/model/CoinViewModel.kt
> +    private val coinRepository = repo
이 변수는 필요 없어보여요.
repo 변수로 처리하면 될 것 같아요.

2019-10-24 03:19 UTC, BeokBeok commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/model/MainViewModel.kt
> +    private val mainRepository = repo
이 변수는 필요 없어보여요.
repo 변수로 처리하면 될 것 같아요.

2019-10-24 03:19 UTC, BeokBeok commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/util/CalculateUtils.kt
>      fun setTradeAmount(
변수의 범위를 최소화하기 위해서 이 부분을 이렇게 바꿔봤어요.

```
fun setTradeAmount(
        marketType: String,
        accTradePrice24h: Double
    ): Map<String, Number> {
        val totalPriceAmount = accTradePrice24h.toLong()
        return when (marketType) {
            "KRW" -> {
                when {
                    totalPriceAmount < 1_000_000L -> {
                        mapOf<String, Number>(
                            "format" to R.string.trade_amount_fmt,
                            "price" to totalPriceAmount
                        )
                    }
                    totalPriceAmount < 1_000_000_000_000L -> {
                        mapOf<String, Number>(
                            "format" to R.string.trade_amount_mega_fmt,
                            "price" to totalPriceAmount / 1_000_000L
                        )
                    }
                    else -> {
                        mapOf<String, Number>(
                            "format" to R.string.trade_amount_giga_fmt,
                            "price" to totalPriceAmount / 1_000_000_000L
                        )
                    }
                }
            }
            "BTC", "ETH" -> {
                mapOf(
                    "format" to R.string.trade_amount_milli_fmt,
                    "price" to accTradePrice24h
                )
            }
            "USDT" -> {
                when {
                    totalPriceAmount < 1_000_000L -> {
                        mapOf<String, Number>(
                            "format" to R.string.trade_amount_fmt,
                            "price" to totalPriceAmount
                        )
                    }
                    totalPriceAmount < 1_000_000_000L -> {
                        mapOf<String, Number>(
                            "format" to R.string.trade_amount_kilo_fmt,
                            "price" to totalPriceAmount / 1_000L
                        )
                    }
                    totalPriceAmount < 1_000_000_000_000L -> {
                        mapOf<String, Number>(
                            "format" to R.string.trade_amount_mega_fmt,
                            "price" to totalPriceAmount / 1_000_000L
                        )
                    }
                    else -> {
                        mapOf<String, Number>(
                            "format" to R.string.trade_amount_giga_fmt,
                            "price" to totalPriceAmount / 1_000_000_000L
                        )
                    }
                }
            }
            else -> {
                when {
                    totalPriceAmount < 1_000L -> {
                        mapOf<String, Number>(
                            "format" to R.string.trade_amount_milli_fmt,
                            "price" to accTradePrice24h
                        )
                    }
                    totalPriceAmount < 1_000_000L -> {
                        mapOf<String, Number>(
                            "format" to R.string.trade_amount_fmt,
                            "price" to totalPriceAmount
                        )
                    }
                    totalPriceAmount < 1_000_000_000L -> {
                        mapOf<String, Number>(
                            "format" to R.string.trade_amount_kilo_fmt,
                            "price" to totalPriceAmount / 1_000L
                        )
                    }
                    totalPriceAmount < 1_000_000_000_000L -> {
                        mapOf<String, Number>(
                            "format" to R.string.trade_amount_mega_fmt,
                            "price" to totalPriceAmount / 1_000_000L
                        )
                    }
                    else -> {
                        mapOf<String, Number>(
                            "format" to R.string.trade_amount_giga_fmt,
                            "price" to totalPriceAmount / 1_000_000_000L
                        )
                    }
                }
            }
        }
    }
```

추후에 마켓 타입별 함수로 추출하게 되면 보다 간결해질 수 있을 것 같네요.

2019-10-24 09:48 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/model/CoinViewModel.kt
> +    private val coinRepository = repo
71285162274d434a74bb54a55dbe4b13c8176e2c

2019-10-24 09:48 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/model/MainViewModel.kt
> +    private val mainRepository = repo
71285162274d434a74bb54a55dbe4b13c8176e2c

2019-10-24 09:51 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/util/CalculateUtils.kt
>      fun setTradeAmount(
정말 감사합니다 현석님 ! 3ee39b2f59e3ae02c9d44272017625ad04493028

2019-10-24 09:54 UTC, BeokBeok submitted a review, later dismissed
LGTM:ok_hand:

2019-10-26 05:00 UTC, sjjeong requested changes

2019-10-26 05:00 UTC, sjjeong commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/BaseFragment.kt
> +    protected val compositeDisposable = CompositeDisposable()
@seonoh 처리해주세요

2019-10-26 05:00 UTC, sjjeong commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/model/MainViewModel.kt
> +        )
```kotlin
repo.sendMarket()
    .map(::refineData)
    .subscribeOn(Schedulers.io())
    .observeOn(AndroidSchedulers.mainThread())
    .subscribe(marketInfo::set, ::handleError)
    .add()
```

```kotlin
fun handleError(throwable: Throwable){
    Log.e("currentPriceInfo", "Main Network failed!! ${it.message}")
}
```

2019-10-26 05:23 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/model/MainViewModel.kt
> +        )
dde18de7d9235e9f680e57b1c477e191403aa775

2019-10-26 05:58 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/BaseFragment.kt
> +    protected val compositeDisposable = CompositeDisposable()
d5c408bfc2b727505135d127de0770879c3d83b2

2019-10-26 08:46 UTC, sjjeong approved these changes

2019-10-28 01:23 UTC, merged