HW9-Koin
sjjeong/GoogryAndroidArchitecutreStudy pull request #248
Opened 2019-10-17 12:43 UTC by ganghee

Datasource 인자에 Service
Repository 인자에 Datasource
Viewmodel 인자에 Repository 를 넣어서 구현하였습니다.
그리고 NetworkService모듈, Datasource모듈, Repository모듈, Viewmodel모듈로 나누었습니다.

2019-10-18 06:45 UTC, wswon reviewed
Repositoy, RemoteDataSource를 interface로 만들고 Impl class로 사용해보는것은 어떨까요?
잘 몰랐는데 clean architecture의 한 부분이더라고요! 고생하셨습니다 👍

2019-10-18 06:45 UTC, wswon commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/di/NetworkModule.kt
> +    }
```
single {
        Retrofit.Builder()
            .baseUrl(url)
            .addConverterFactory(get<GsonConverterFactory>())
            .addCallAdapterFactory(get<RxJava2CallAdapterFactory>())
            .build()
    }
```
이거를
   ```
 factory<Retrofit> { (url: String) ->
        Retrofit.Builder()
            .baseUrl(url)
            .addConverterFactory(get<GsonConverterFactory>())
            .addCallAdapterFactory(get<RxJava2CallAdapterFactory>())
            .build()
    }
```
이렇게 바꿔서 확장가능성을 열어두면 좋지않을까요?
여러 url, api가 필요한 개발을 하다보니 get<Retrofit>()은 singleton이면 안되더라고요

2019-10-18 06:45 UTC, wswon commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/di/NetworkModule.kt
> +fun getRemoteServiceModules(url: String) = module {
```suggestion
val remoteServiceModule = module {
```
아래 리뷰에따라 url을 인자로 따로 받는것이 어떨까 합니다.

2019-10-18 06:45 UTC, wswon commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/CoinHelperApplication.kt
> +            androidLogger()
해당줄은 debug, release log 분할해줄것이 아니면 필요없다고 하였습니다.

2019-10-18 16:29 UTC, ganghee commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/di/NetworkModule.kt
> +    }
Alication 객체에 
`getRemoteServiceModules("https://api.upbit.com/v1/")` 를 구현해서 싱글톤으로 구현했습니다.
파라미터만 수정하거나 추가하면 확장성에는 문제 없을 것 같아요~
우석님 코드를 봤는데 저랑 다른 점은 저는 함수를 통해 객체를 생성하는 factory패턴을 사용했어요
우석님은 모듈하나가 객체하나를 싱글톤 객체를 사용했어요 이럴 경우 Retrofit 객체가 생성할 경우에 하나의 api처리 되죠 또 다른 클래스에서 Retrofit 객체가 생성되면 여러개의 api가 생성되는게 아니라 기존에 생성된 Retrofit 객체가 사용될 거예요!!

2019-10-18 16:29 UTC, ganghee commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/di/NetworkModule.kt
> +fun getRemoteServiceModules(url: String) = module {
위의 리뷰가 이유입니다!

2019-10-18 16:29 UTC, ganghee commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/CoinHelperApplication.kt
> +            androidLogger()
네 삭제했습니다.

2019-10-21 15:39 UTC, wswon commented on ganghee/MyStudy2/app/src/main/java/com/example/mystudy/di/NetworkModule.kt
> +    }
넵 이해했습니다!

2019-10-21 15:40 UTC, wswon submitted a review, later dismissed
너무 늦게확인했네요 ㅠ 죄송합니다! 고생많으셨습니다. 👍

2019-10-23 01:56 UTC, sjjeong requested changes
![image](https://user-images.githubusercontent.com/4777586/67349763-cc61e780-f583-11e9-8a44-05ed5296375e.png)
에러 해결해주세요

2019-10-23 12:26 UTC, ganghee commented
다시 올렸습니다!
[NetworkModule](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/248/files#diff-17)

2019-10-24 16:29 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-10-25 01:16 UTC, wswon approved these changes

2019-10-25 01:18 UTC, wswon approved these changes
9주동안 같이 고민해주시고 리뷰 해주셔서 정말 감사했습니다 👍 
고생많으셨습니다

2019-10-25 01:19 UTC, merged