HW-1-과제 샘플 프로젝트 제작
sjjeong/GoogryAndroidArchitecutreStudy pull request #259
Opened 2019-10-27 07:07 UTC by ironelder

HW-1-과제 샘플 프로젝트 제작
 -- 코드 reformat관련 스타일 변경

2019-10-30 03:54 UTC, bean628 commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/view/CustomItemView.kt
> +    constructor(context: Context?, type: String) : super(context) {
생성자 부분이 하나밖에 없으셔서 부생성자말고 주생성자로 정의하시는게 어떨까요?

2019-10-30 04:02 UTC, bean628 commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/component/MainActivity.kt
> +class MainActivity : BaseActivity() {
화면마다 검색바를 각각 가지고 있어서 탭 이동시마다 다른 검색바가 나오고있는데
화면 구조를 검색바는 하나만 사용하는것도 나쁘지 않을것 같아요.

2019-10-30 04:04 UTC, bean628 commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/utils/RetrofitForNaver.kt
> +    private var mRetrofit = Retrofit.Builder()
okhttp를 함께 사용하면 인터페이스 함수마다 헤더값을 넣지 않고 고정으로 할 수 있어요.
성능적인 이점도 있는걸로 알고있습니다.

2019-10-30 04:05 UTC, bean628 reviewed
원활한 리뷰를 위해 더 공부해야겠어요 ㅋㅋ 
보이는게 거의 없어서 민망하네요

2019-10-30 07:54 UTC, ironelder commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/view/CustomItemView.kt
> +    constructor(context: Context?, type: String) : super(context) {
부생성자를 제거하고 주 생성자를 활용하도록 수정하였습니다

51c666f

2019-10-30 07:54 UTC, ironelder commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/utils/RetrofitForNaver.kt
> +    private var mRetrofit = Retrofit.Builder()
okhttp라이브러리를 사용하여 header를 고정하도록 수정하였습니다.
추가 기능의 이점 및 성능은 있을 것 같은데 가독성이 많이 저하되긴 하네용 ㅎㅎ

4bae956

2019-10-30 07:56 UTC, ironelder commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/component/MainActivity.kt
> +class MainActivity : BaseActivity() {
음... 현재 구조가 프라그먼트 내부에서 검색부분을 각자 컨트롤하고 있는데... 이부분을 상단의 툴바 영역으로 옮겨서 수정해보겠습니다... 시간은 좀 걸릴 것 같습니다 ㅎㅎ

2019-10-30 08:28 UTC, ironelder commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/component/MainActivity.kt
> +class MainActivity : BaseActivity() {
만약 검색바를 프라그먼트가 아닌 액티비티에서 1개만 만들어서 관리한다고 했을 경우에 검색을 하게 되면 해당 프라그먼트에만 값이 전달되어서 검색되는게 맞을까요? 아니면 모든 프라그먼트가 다 검색되는 것이 맞을까요?

2019-10-30 08:29 UTC, ironelder commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/component/MainActivity.kt
> +class MainActivity : BaseActivity() {
@bean628 
리뷰 의견 반영 부탁드립니다~

2019-10-30 10:12 UTC, ironelder commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/component/MainActivity.kt
> +class MainActivity : BaseActivity() {
상단의 액션바를 활용하도록 메뉴를 추가하여 각 프래그먼트별로 해당 액션바를 활용한 검색창을 사용하도록 통합해보았습니다

f6bec35

2019-10-31 06:39 UTC, ddaeyeonkim reviewed
안녕하세요 스터디를 수강 했었던 김대연입니다.
부족한 리뷰는 지적 및 첨삭 부탁드립니다.
감사합니다!!

2019-10-31 06:39 UTC, ddaeyeonkim commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/component/MainFragment.kt
> +    }
view 의 확장함수로 별도 클래스에 빼면 유틸처럼 쓸수 있을 것 같아요

2019-10-31 06:39 UTC, ddaeyeonkim commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/component/MainFragment.kt
> +            LinearLayoutManager(context, LinearLayoutManager.VERTICAL, false)
취향인데 xml 에서 `layoutManager` 속성으로 넣어줄수도 있습니다

2019-10-31 06:39 UTC, ddaeyeonkim commented on ironelder/AndroidArchitecture/app/build.gradle
> +    annotationProcessor 'com.github.bumptech.glide:compiler:4.10.0'
프로젝트 build.gradle 에 ext {} 로 버전 넣어주는게 편리합니다
https://developer.android.com/studio/build/gradle-tips?hl=ko

![image](https://user-images.githubusercontent.com/36095102/67919431-9e178400-fbe3-11e9-93f0-b955bb613119.png)

2019-10-31 06:39 UTC, ddaeyeonkim commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/component/BaseActivity.kt
> +    open fun doDestroy() {}
do- 로 라이프사이클 메서드를 생성하신 이유가 궁금합니다.
프래그먼트는 이렇게 안쓰시는것 같구요..

2019-10-31 06:39 UTC, ddaeyeonkim commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/view/CustomListViewAdapter.kt
> +        mItemList = list ?: arrayListOf()
생성자로 받은 리스트와 같은 주소를 참조하게 되어서 어댑터 외부에서도 리스트를 변경할 수 있게 됩니다. addAll 로 변경해주는게 좋을것 같아요

2019-10-31 06:39 UTC, ddaeyeonkim commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/view/CustomListViewAdapter.kt
> +        var view: View = CustomItemView(mContext, mType)
parent.context 를 쓰면 mContext 를 생성자로 받지 않아도 될 것  같습니다.

2019-10-31 06:39 UTC, ddaeyeonkim commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/view/CustomListViewAdapter.kt
> +        }
생성자를 클래스 이름 옆에 두고 init{} 블록 내부에서 캐스팅해도 될 것 같아요
CustomItemView 를 다형성을 고려해서 View 로 받으신다면
interface 를 만들어서 setData(item: T) 메서드를 구현하도록 하는게 좋을 것 같습니다.

2019-10-31 06:39 UTC, ddaeyeonkim commented on ironelder/AndroidArchitecture/app/src/main/res/layout/fragment_main.xml
> +        android:layout_height="match_parent"
constraintlayout 을 쓸때 match_parent 보다는 0dp (match_constraint) 를 더 권장 하는 것 같아요

2019-10-31 06:39 UTC, ddaeyeonkim commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/view/CustomListViewAdapter.kt
> +    private var mItemList: ArrayList<Item>,
어댑터 생성자에서 컨텍스트와 리스트를 안받는게 좋을 것 같습니다.

2019-10-31 06:39 UTC, ddaeyeonkim commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/utils/RetrofitForNaver.kt
> +            }
인터셉터 생성부분을 별도 메서드로 빼주시면 어떨까요? 그럼 좀 더 깔끔해질 것 같아요
이번앱에서는 네이버 api 만 쓰지만 네이버 api 가 아닌경우엔 옵션이 될 수 있기도 하구요

2019-10-31 06:39 UTC, ddaeyeonkim commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/utils/RetrofitForNaver.kt
> +            logging.level = HttpLoggingInterceptor.Level.BODY
HttpLoggingInterceptor 생성 부분을 별도 메서드로 빼주시면 어떨까요? 그럼 좀 더 깔끔해질 것 같아요
객체의 속성을 정의할때 .apply() 를 쓰면 편리합니다.

2019-10-31 06:39 UTC, ddaeyeonkim commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/utils/RetrofitForNaver.kt
> +            httpClient.addNetworkInterceptor(logging)
여기도 apply {} 로 하면 편리합니다.

2019-10-31 06:39 UTC, ddaeyeonkim commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/utils/RetrofitForNaver.kt
> +    fun getSearchForNaver(): SearchForNaver = mRetrofit.create(SearchForNaver::class.java)
RetrofitForNaver 는 싱글톤으로 선언하셨지만 SearchForNaver 는 매번 생성해서 쓰게 되는 것 같습니다.

2019-10-31 06:39 UTC, ddaeyeonkim commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/utils/RetrofitForNaver.kt
> +object RetrofitForNaver {
utils 패키지 보다는 data 패키지의 성격이 더 강한 것 같습니다.
외부에서 데이터를 가져오는 역할을 가지고 있어서요

2019-10-31 06:39 UTC, ddaeyeonkim commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/utils/RetrofitForNaver.kt
> +    }
별도 파일로 분리해주는게 좋을 것 같아요

2019-10-31 06:39 UTC, ddaeyeonkim commented on ironelder/AndroidArchitecture/app/src/main/res/layout/item_custom_item_view.xml
> +        android:text="Title"
데이터를 넣기전에 화면에서 Title 이라고 표시 될 수 있는데 `tools:text` 속성을 쓰면
안드로이드 스튜디오의 프리뷰에서만 볼수 있어요

2019-10-31 06:39 UTC, ddaeyeonkim commented on ironelder/AndroidArchitecture/app/src/main/res/layout/layout_search_listview.xml
> +    <androidx.recyclerview.widget.RecyclerView
`tools:listitem` 속성으로 아이템뷰의 layout 을 넣어주면 프리뷰에서도 확인이 가능해서 편리합니다

2019-10-31 06:39 UTC, ddaeyeonkim commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/component/MainFragment.kt
> +class MainFragment(private val mType:String?) : Fragment() {
프래그먼트의 생성자로 외부에서 호출하는건 권장하지 않습니다.
시스템이 프래그먼트를 재생성하면 인자 없이 생성되기 때문에 
static getInstance() 를 추가해서 번들로 받아서 쓰는게 좋습니다

https://stackoverflow.com/questions/47104345/kotlin-idiomatic-way-to-create-a-fragment-newinstance-pattern

2019-10-31 06:39 UTC, ddaeyeonkim commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/component/MainFragment.kt
> +        v.resultListView.adapter = CustomListViewAdapter(context, arrayListOf(), mType?: BLOG)
코틀린 익스텐션을 쓰면 v. 을 생략할 수 있습니다.

2019-10-31 06:39 UTC, improve777 commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/view/CustomListViewAdapter.kt
> +        )
이 코드는 CustomItemView init {} 블록에서 해주는게 좋지 않을까요?

2019-10-31 06:43 UTC, improve777 commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/component/MainFragment.kt
> +        var result = retrofitService.requestSearchForNaver(mType?: BLOG, searchString)
var 보다는 val 로 선언해주시는게 좋을 것 같습니다.

2019-10-31 06:43 UTC, improve777 commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/component/MainFragment.kt
> +                var resultList = response.body()
var 보다는 val 로 선언해주시는게 좋을 것 같습니다.

2019-10-31 07:21 UTC, improve777 commented on ironelder/AndroidArchitecture/app/src/main/AndroidManifest.xml
>          android:allowBackup="true"
allowBackup="false" 로 하는걸 권장한다고 하네요
취약점이 있을수 있다고 합니다
https://nvd.nist.gov/vuln/detail/CVE-2017-16835

2019-10-31 07:23 UTC, sjjeong commented on ironelder/AndroidArchitecture/app/src/main/AndroidManifest.xml
>          android:allowBackup="true"
allowBackup은 default가 true라서 true로 하는건 따로 안해도 됩니다

2019-10-31 14:43 UTC, ironelder commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/component/MainFragment.kt
> +    }
해당 함수는 사용하지 않는 함수로 제거하였습니다~
cdcb0a6

2019-10-31 14:44 UTC, ironelder commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/component/MainFragment.kt
> +            LinearLayoutManager(context, LinearLayoutManager.VERTICAL, false)
xml 속성으로 선언하도록 수정하였습니다~
감사합니다~

3a90088

2019-10-31 14:45 UTC, ironelder commented on ironelder/AndroidArchitecture/app/build.gradle
> +    annotationProcessor 'com.github.bumptech.glide:compiler:4.10.0'
버전 관리를 ext를 활용하도록 수정하였습니다..
그런데 kotlin_version도 ext로 옮기고 싶은데 그렇게 되면 buildscript에서 오류가 나는데... 왜그런지 잘 모르겠습니다..
f2ab7c5

2019-10-31 14:47 UTC, ironelder commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/component/BaseActivity.kt
> +    open fun doDestroy() {}
저게 원래 각 화면을 Activity로 분할하려고 해서 공통 액티비티에서 함수를 빼려고 했는데.. Fragment로 구현되면서 사용하지 않게 되었습니다. 혹시나 액티비티 시작전에 액션이 필요할까봐 남겨두었었습니다

2019-10-31 14:48 UTC, ironelder commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/view/CustomListViewAdapter.kt
> +        mItemList = list ?: arrayListOf()
리스트 뷰를 addAll로 변경하였습니다.
또한 기존의 set과 add함수를 구분하기 위하여 clear를 추가하였습니다
78f45dc

2019-10-31 14:49 UTC, ironelder commented on ironelder/AndroidArchitecture/app/src/main/res/layout/item_custom_item_view.xml
> +        android:text="Title"
테스트로 넣어둔 항목의 속성을 tools를 활용하도록 변경하였습니다.
c95472b

2019-10-31 14:50 UTC, ironelder commented on ironelder/AndroidArchitecture/app/src/main/AndroidManifest.xml
>          android:allowBackup="true"
안드로이드 취약점을 수정하였습니다.
031e30a

2019-10-31 14:51 UTC, ironelder commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/component/MainFragment.kt
> +                var resultList = response.body()
var 변수를 read-only로 변경하였습니다
c541bd9

2019-10-31 14:51 UTC, ironelder commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/component/MainFragment.kt
> +        var result = retrofitService.requestSearchForNaver(mType?: BLOG, searchString)
var 변수를 read-only로 변경하였습니다
c541bd9

2019-10-31 14:52 UTC, ironelder commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/view/CustomListViewAdapter.kt
> +        )
layoutparam설정을 해당 아이템의 init으로 이동하였습니다
e59a560

2019-10-31 14:56 UTC, ironelder commented on ironelder/AndroidArchitecture/app/src/main/res/layout/layout_search_listview.xml
> +    <androidx.recyclerview.widget.RecyclerView
tools:listitem속성을 추가하였습니다.
19e8873

2019-10-31 14:57 UTC, ironelder commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/component/MainFragment.kt
> +class MainFragment(private val mType:String?) : Fragment() {
프래그먼트의 생성자를 외부에서 호출하지 않고 Instance를 통해서 생성하도록 수정하였습니다.
90599c5

2019-10-31 14:58 UTC, ironelder commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/component/MainFragment.kt
> +        v.resultListView.adapter = CustomListViewAdapter(context, arrayListOf(), mType?: BLOG)
v.를 생략하여 사용하도록 코드를 수정하였습니다

35cdb81

2019-10-31 16:02 UTC, ironelder commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/view/CustomListViewAdapter.kt
> +        var view: View = CustomItemView(mContext, mType)
parent의 콘텍스트를 쓰도록 변경하였습니다

e0a229d

2019-10-31 16:02 UTC, ironelder commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/view/CustomListViewAdapter.kt
> +    private var mItemList: ArrayList<Item>,
어댑터 생성자에서 컨텍스트와 리스트를 받지 않도록 수정하였습니다~
e0a229d

2019-10-31 16:03 UTC, ironelder commented on ironelder/AndroidArchitecture/app/src/main/res/layout/fragment_main.xml
> +        android:layout_height="match_parent"
match_parent를 사용하지 않도록 수정하였습니다

c4d5838

2019-10-31 16:04 UTC, ironelder commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/utils/RetrofitForNaver.kt
> +object RetrofitForNaver {
retrofit 파일을 utils에서 data 패키지로 변경하였습니다~
b18058e

2019-10-31 16:06 UTC, ironelder commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/utils/RetrofitForNaver.kt
> +    }
인터페이스를 별도의 파일로 분리하였습니다~
2efac75

2019-10-31 16:08 UTC, ironelder commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/view/CustomListViewAdapter.kt
> +        }
생성자를 별도로 처리하지 않고 클래스의 주생성자에서 처리하도록 변경하였습니다
48a885d

더불어 다형성을 고려하진 않았지만 interface를 만들어서
setData를 제네릭 함수로 오버라이드 받을 수 있도록 수정해보았습니다
e21df0f

2019-10-31 16:09 UTC, ironelder commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/utils/RetrofitForNaver.kt
> +    fun getSearchForNaver(): SearchForNaver = mRetrofit.create(SearchForNaver::class.java)
검색 부분을 싱글톤을 사용하도록 수정했는데
이게 맞는지 잘 모르겠습니다

c6853b3

2019-10-31 16:26 UTC, ironelder commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/utils/RetrofitForNaver.kt
> +            }
인터셉터 생성 부분을 함수로 변경하였습니다~
377ed46

2019-10-31 16:27 UTC, ironelder commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/utils/RetrofitForNaver.kt
> +            httpClient.addNetworkInterceptor(logging)
apply를 적용시켰습니다~
377ed46

2019-10-31 16:27 UTC, ironelder commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/utils/RetrofitForNaver.kt
> +            logging.level = HttpLoggingInterceptor.Level.BODY
HttpLoggingInterceptor를 별도의 메소드로 분리시켰습니다
객체 속성 정의시 apply를 적용시켰습니다
확실히 가독성이 좋아졌습니다
감사합니다
377ed46

2019-10-31 22:18 UTC, ironelder commented
> 안녕하세요 스터디를 수강 했었던 김대연입니다.
> 부족한 리뷰는 지적 및 첨삭 부탁드립니다.
> 감사합니다!!

안녕하세요 5기 수강생 장진혁 입니다
리뷰 수정사항을 반영하였습니다
나름 신경쓴다고 했는데, 빼먹은게 엄청 많이 있네요.
잘부탁드리겠습니다
감사합니다~!!!

2019-11-01 06:10 UTC, sjjeong requested changes

2019-11-01 06:10 UTC, sjjeong commented on ironelder/AndroidArchitecture/app/build.gradle
> +    implementation "com.android.support:design:$rootProject.ext.design_version"
해당 내용은 사용하시면 안됩니다.
![image](https://user-images.githubusercontent.com/4777586/68005037-2f0b5f80-fcb7-11e9-8edf-710f484608b5.png)
https://mvnrepository.com/artifact/com.google.android.material/material 로 변경해주세요

2019-11-01 06:10 UTC, sjjeong commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/component/BaseActivity.kt
> +    open fun doDestroy() {}
따로 추가적인 동작하는 것이 없는 함수들인데 doCreate를 override하는 것과 onCreate를 override하는 것과 동일한 효과로 보입니다.
불필요함수로 보입니다.

2019-11-01 06:10 UTC, sjjeong commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/component/MainFragment.kt
> +    companion object {
companion object는 클래스 안에 맨 마지막에 위치해야합니다.

2019-11-01 06:10 UTC, sjjeong commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/component/MainFragment.kt
> +            return fragment
apply를 사용해서 처리해보면 어떨까요?
Bundle이랑 Fragment 둘다요

2019-11-01 06:10 UTC, sjjeong commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/component/MainFragment.kt
> +    override fun onCreateView(
BaseActivity만드신것처럼 BaseFragment를 만들어서 해당부분 처리 해보면 어떨까요?

2019-11-01 06:10 UTC, sjjeong commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/component/MainFragment.kt
> +        resultListView.adapter = CustomListViewAdapter(mType ?: BLOG)
resultListView에 여러번 접근한다면 with나 run 함수가 도움이 될 수 있습니다.

2019-11-01 06:10 UTC, sjjeong commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/data/RetrofitForNaver.kt
> +            level = HttpLoggingInterceptor.Level.BODY
이렇게 되면 실제 환경에서 로그가 보이는 문제가 발생합니다.
BuildConfig로 Debug환경인지 분기를 추가해서 Level.NONE을 추가해주면 좋습니다.

2019-11-01 06:10 UTC, sjjeong commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/view/CustomListViewAdapter.kt
> +    private var mItemList: ArrayList<Item> = arrayListOf()
val로 선언해주시면 됩니다.

2019-11-01 06:10 UTC, sjjeong commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/view/CustomListViewAdapter.kt
> +        mItemList.addAll(list ?: arrayListOf())
list가 null일때는 addAll함수를 호출하지 않으면 됩니다.

2019-11-01 06:10 UTC, sjjeong commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/view/CustomListViewAdapter.kt
> +            mCustomItemView.setOnClickListener {
click listener는 setData에서 처리하게 되면 onBindViewHolder시점에 호출되는 것이기 때문에 여러번 호출 될 수 있습니다.
onCreateViewHolder 시점에서 한번만 set되게 처리해주세요

2019-11-01 06:10 UTC, sjjeong commented on ironelder/AndroidArchitecture/app/src/main/res/layout/item_custom_item_view.xml
> +        android:id="@+id/itemImage"
id는 앞에 prefix를 붙여주는게 좋습니다.
TextView -> tv_xxx
ImageView -> iv_xxx

2019-11-01 14:42 UTC, ironelder commented on ironelder/AndroidArchitecture/app/src/main/res/layout/item_custom_item_view.xml
> +        android:id="@+id/itemImage"
뷰 컴포넌트의 id 에 prefix를 추가하였습니다
9503694

2019-11-01 14:42 UTC, ironelder commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/view/CustomListViewAdapter.kt
> +            mCustomItemView.setOnClickListener {
CustomItemView의 ClickListener를 onCreateViewHolder시점으로 이동하였습니다.
ce92634

2019-11-01 14:43 UTC, ironelder commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/view/CustomListViewAdapter.kt
> +        mItemList.addAll(list ?: arrayListOf())
list를 검사하여 null일 경우에는 addAll함수를 호출하지 않도록 수정하였습니다~

5802481

2019-11-01 14:44 UTC, ironelder commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/data/RetrofitForNaver.kt
> +            level = HttpLoggingInterceptor.Level.BODY
HttpLog관련 Interceptor의 레벨을 BuildConfig를 참조하여 분기하도록 처리하였습니다
8a9fa23

2019-11-01 14:45 UTC, ironelder commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/view/CustomListViewAdapter.kt
> +    private var mItemList: ArrayList<Item> = arrayListOf()
Adapter수정하면서 해당 부분을 함께 수정하였습니다

5802481

2019-11-01 14:47 UTC, ironelder commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/component/MainFragment.kt
> +        resultListView.adapter = CustomListViewAdapter(mType ?: BLOG)
resultListView를 with를 사용하여 수신객체를 전달하도록 수정하였습니다
144cfdb

2019-11-01 14:48 UTC, ironelder commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/component/MainFragment.kt
> +    override fun onCreateView(
BaseFragment를 추가하여 공통으로 기본적으로 수행할 함수를 처리하였습니다

670f8e2
144cfdb

2019-11-01 14:49 UTC, ironelder commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/component/MainFragment.kt
> +            return fragment
해당 인스턴스를 생성하기 위한 항목으로 apply를 적용시켜 보았습니다

@sjjeong 
apply안의 apply가 존재해도 문제가 없는지 잘 모르겠습니다.

5b5129c

2019-11-01 14:50 UTC, ironelder commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/component/MainFragment.kt
> +    companion object {
컴패니언 오브젝트의 위치를 수정하였습니다

c5fa549

2019-11-01 14:51 UTC, ironelder commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/component/BaseActivity.kt
> +    open fun doDestroy() {}
사용하지 않는 BaseActivity를 제거하고 기존의 MainActivity를 AppCompat을 상속받도록 원복하였습니다.

77a78a1
9ec3b61

2019-11-01 14:51 UTC, ironelder commented on ironelder/AndroidArchitecture/app/build.gradle
> +    implementation "com.android.support:design:$rootProject.ext.design_version"
라이브러리 참조 항목을 수정하였습니다

799267c

2019-11-02 09:33 UTC, sjjeong commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/component/MainFragment.kt
> +            return fragment
Bundle apply안에서 Fragment 꺼를 접근하는게 아니라면 괜찮습니다.

2019-11-02 09:38 UTC, sjjeong requested changes

2019-11-02 09:38 UTC, sjjeong commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/component/BaseFragment.kt
> +        return inflater.inflate(R.layout.fragment_main, container, false)
BaseFragment인데 layout이 지정되면 안될 것 같습니다.

2019-11-02 10:06 UTC, ironelder commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/component/BaseFragment.kt
> +        return inflater.inflate(R.layout.fragment_main, container, false)
BaseFragment의 layout지정을 제거하였습니다
e3f6b2b

2019-11-02 10:07 UTC, ironelder commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/component/MainFragment.kt
> +            return fragment
넵 감사합니다

2019-11-02 10:09 UTC, sjjeong commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/component/BaseFragment.kt
> +        return inflater.inflate(R.layout.fragment_main, container, false)
제가 말씀드린건 R.layout.fragment_main을 자식클래스에서 전달받아서 넣어주라는 말이였습니다.
다시 해주세요

2019-11-02 10:16 UTC, ironelder commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/component/BaseFragment.kt
> +        return inflater.inflate(R.layout.fragment_main, container, false)
요렇게 수정하면 될까요?
자식인자로 리턴받아서 그대로 올려주도록 했습니다
2491b78

2019-11-02 12:02 UTC, sjjeong requested changes

2019-11-02 12:02 UTC, sjjeong commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/component/MainFragment.kt
> +        return inflater.inflate(R.layout.fragment_main, container, false)
주로 자바에서는 
abstract int getLayoutResId();를 만들어서 처리했었고
코틀린에서는 생성자로 layoutResId를 전달받아서 처리합니다.

2019-11-02 12:28 UTC, ironelder commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/component/MainFragment.kt
> +        return inflater.inflate(R.layout.fragment_main, container, false)
layoutResId를 생성자를 통해 자식으로부터 전달받도록 수정했습니다
77d4ad7

@sjjeong 
코틀린에서는 
abstract val layoutResId: Int
요러케 선언하고
@LayoutRes override val layoutResId = R.layout.fragment_main
요러케 하면 자바랑 비슷하게 쓰는 것 같은데
생성자로 받도록 변경된 이유가 있을까요?
4d4f4d8

2019-11-02 12:47 UTC, sjjeong commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/component/MainFragment.kt
> +        return inflater.inflate(R.layout.fragment_main, container, false)
이유는 따로없고 코틀린할때 그렇게 쓰는게 편해서 많이 쓰고있어요

2019-11-02 12:48 UTC, sjjeong approved these changes

2019-11-02 12:49 UTC, ironelder commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/component/MainFragment.kt
> +        return inflater.inflate(R.layout.fragment_main, container, false)
아하 생성자로 받으면 해당 프라그먼트 옆에 레이아웃을 같이 써줘야하니 더 직관적이고 좋겠네요  ㅎㅎ 감사합니다~!!

2019-11-02 13:13 UTC, bean628 approved these changes
저도 Approve 해야하는건가요? 이렇게 하는건가..?

2019-11-02 13:14 UTC, bean628 commented
> 저도 Approve 해야하는건가요? 이렇게 하는건가..?

맞네요 ㅋㅋㅋ 몰랐어요 이렇게 해야하는건지 ! 승인!

2019-11-03 04:25 UTC, merged