HW-2 MVP 변환
sjjeong/GoogryAndroidArchitecutreStudy pull request #26
Opened 2019-05-07 14:21 UTC by GongSulMin

2019-05-09 04:29 UTC, sabgilhun requested changes
수고하셨습니다.  😊

2019-05-09 04:29 UTC, sabgilhun commented on gongsulmin/StudyGong/app/src/main/java/my/gong/studygong/mvp/view/CoinActivity.kt
> +    }
Timer 구현도 Presenter에서 하면 어떨까요?

2019-05-09 04:29 UTC, sabgilhun commented on gongsulmin/StudyGong/app/src/main/java/my/gong/studygong/mvp/view/CoinActivity.kt
> +    private val REPEAT_INTERVAL_MILLIS = 3000L
상수로 REPEAT_INTERVAL_MILLIS 선언하면 좋을것 같습니다~

2019-05-09 12:15 UTC, GongSulMin commented on gongsulmin/StudyGong/app/src/main/java/my/gong/studygong/mvp/view/CoinActivity.kt
> +    }
Timer 도는게 새로고침을 클릭하는거랑 같다고 생각해서 View 에 넣었습니다~
그래도 presenter에 하는게 더 좋을까요 ??

2019-05-09 23:28 UTC, improve777 commented on gongsulmin/StudyGong/app/src/main/java/my/gong/studygong/mvp/view/CoinActivity.kt
> +    private var timer: Timer = Timer()
CoinActivity 에서는 사용하지 않는 코드 같습니다

2019-05-09 23:28 UTC, improve777 commented on gongsulmin/StudyGong/app/src/main/AndroidManifest.xml
> +        <activity android:name=".mvp.view.CoinActivity">
mvp 로 변경하면서 MainActivity 를 아예 사용하지 않게 되었는데 아키텍처 변경시마다 백업이 필요하다면 별도 브랜치로 나누어 놓는 방식으로 코드를 보존하는게 낫지 않을까요?

2019-05-10 02:41 UTC, sabgilhun commented on gongsulmin/StudyGong/app/src/main/java/my/gong/studygong/mvp/view/CoinActivity.kt
> +    }
일리있는 의견인것 같습니다 :+1:

2019-05-10 05:11 UTC, GongSulMin commented on gongsulmin/StudyGong/app/src/main/java/my/gong/studygong/mvp/view/CoinActivity.kt
> +    private var timer: Timer = Timer()
대연님꺼 commit 을 수정하다가 빠진 부분인것 같습니다.
수정하겠습니다~

2019-05-10 08:59 UTC, GongSulMin commented on gongsulmin/StudyGong/app/src/main/AndroidManifest.xml
> +        <activity android:name=".mvp.view.CoinActivity">
수정하였습니다~
899b915

2019-05-10 08:59 UTC, GongSulMin commented on gongsulmin/StudyGong/app/src/main/java/my/gong/studygong/mvp/view/CoinActivity.kt
> +    private var timer: Timer = Timer()
수정하였습니다~
fe5d3fa

2019-05-10 08:59 UTC, GongSulMin commented on gongsulmin/StudyGong/app/src/main/java/my/gong/studygong/mvp/view/CoinActivity.kt
> +    private val REPEAT_INTERVAL_MILLIS = 3000L
수정하였습니다~
626d1f4__

2019-05-10 09:27 UTC, ddaeyeonkim submitted a review, later dismissed
LGTM 👍👍👍

2019-05-10 13:35 UTC, sabgilhun submitted a review, later dismissed
LGTM 💯

2019-05-12 15:05 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-05-13 06:42 UTC, merged