HW-1 과제 샘플 프로젝트 제작
sjjeong/GoogryAndroidArchitecutreStudy pull request #260
Opened 2019-10-28 00:38 UTC by bean628

진혁님~
리뷰 부탁드려요 ~!

2019-10-29 00:40 UTC, ironelder reviewed
중복되는 API처리 및 HTML태그 제거 한번 확인 부탁드려요~
음.. 그리고 Glide에서 잘못된 이미지 주소로 인하여 이미지 없을 때 예외처리로 플레이스 홀더 넣어주면 이미지 없을 경우 처리가 가능합니당~
into 앞쪽에 
.placeholder( 이미지 리소스 아이디 )
요렇게 넣으시면 예외처리 될 꺼에요 아마 ㅎㅎ

2019-10-29 00:40 UTC, ironelder commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/network/RetrofitInterface.kt
> +
@GET("v1/search/movie.json")
    fun searchMovie(
        @Query("query") query: String
    ): Call<ResultOfSearchingModel>


위의 이런 부분을 하나로 통합해서 받을때 category와 query를 받는 것은 어떤가요?


@GET("v1/search/{category}.json")
    fun search(
        @Path("category") type:String,
        @Query("query") query: String
    ): Call<ResultOfSearchingModel>

2019-10-29 00:40 UTC, ironelder commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/SearchMovieAndBookAdapter.kt
> +                MyStringUtil.removeHtmlTags(item?.description ?: item?.director)
Html Tag를 제거하는 부분을

HtmlCompat.fromHtml(item?.description ?: item?.director, HtmlCompat.FROM_HTML_MODE_COMPACT)

위와 같은 형식으로 하면 별도의 companion object없이 사용할 수 있을 것 같은데... 잘 되는지 모르겠네요 ㅎㅎ

2019-10-29 14:04 UTC, bean628 commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/network/RetrofitInterface.kt
> +
@Path 활용할 생각을 못했었네요
수정했습니다~

2019-10-29 14:07 UTC, bean628 commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/SearchMovieAndBookAdapter.kt
> +                MyStringUtil.removeHtmlTags(item?.description ?: item?.director)
수정했습니다~
글라이드는 찾아보니 placeholder는 이미지 보여주기 전 대기 상태에 관한 처리를 하고
error 부분이 예외처리부분이네요
리뷰 감사합니다~

2019-10-30 03:21 UTC, sjjeong commented
@bean628 
수정한거 리뷰 코멘트에 커밋번호 남겨주세요

2019-10-30 11:20 UTC, BeokBeok requested changes
안녕하세요. 스터디 2기 강현석이라고 합니다.
부족하지만 잘 부탁드립니다. 😅

2019-10-30 11:20 UTC, BeokBeok commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/MainActivity.kt
> +    private lateinit var mRetrofitClient: RetrofitClient
맴버변수를 뜻하는 m 은 빼주시면 좋을 것 같아요.

2019-10-30 11:20 UTC, BeokBeok commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/MainActivity.kt
> +    private var mSearchType: Int = 0    // 0: 영화, 1: 책, 2: 블로그, 3: 뉴스
주석으로 표시하는 것 보다는
상수를 사용하시거나, enum 을 사용하시는 것은 어떠신가요?

2019-10-30 11:20 UTC, BeokBeok commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/MainActivity.kt
> +        input_search_sth.setOnEditorActionListener { v, actionId, event ->
사용하지 않는 인자는 `_` (언더바) 로 표기하시면 좋을 것 같아요.

2019-10-30 11:20 UTC, BeokBeok commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/MainActivity.kt
> +        rv_searched_list.layoutManager = LinearLayoutManager(this)
xml 에서 layoutManager 를 설정할 수 있어요.

2019-10-30 11:20 UTC, BeokBeok commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/MainActivity.kt
> +        }
리스너를 등록하는 함수를 만드시는 것이 좋을 것 같아요.

2019-10-30 11:20 UTC, BeokBeok commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/MainActivity.kt
> +    private lateinit var mRetrofitClient: RetrofitClient
일반초기화를 사용하지 않고 지연초기화를 사용하신 이유가 있나요?

2019-10-30 11:20 UTC, BeokBeok commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/MainActivity.kt
> +        val word: String = input_search_sth?.text.toString()
nullable 처리를 하지 않으셔도 되지 않나요?

2019-10-30 11:20 UTC, BeokBeok commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/MainActivity.kt
> +        val word: String = input_search_sth?.text.toString()
타입이 명확한 경우에는 타입 추론을 사용하시는 것이 좋을 것 같아요.

2019-10-30 11:20 UTC, BeokBeok commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/MainActivity.kt
> +            Toast.makeText(this@MainActivity, "검색어를 입력해주세요.", Toast.LENGTH_SHORT).show()
String 은 xml 에 정의해놓고 사용하시는 것이 좋을 것 같아요.

2019-10-30 11:20 UTC, BeokBeok commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/MainActivity.kt
> +                if (response.code() == 200) {
`isSuccessful` 을 사용하시면 더 좋을 것 같아요.
```suggestion
                if (response.isSuccessful) {
```

2019-10-30 11:20 UTC, BeokBeok commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/MainActivity.kt
> +                    if (rv_searched_list.adapter!!.itemCount == 0) {
nonnull assertion (!!) 은 사용을 지양하시는 것이 좋아요.
`!!` 보다 `?` 을 사용하시면 좋을 것 같아요.

2019-10-30 11:20 UTC, BeokBeok commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/MainActivity.kt
> +                t.printStackTrace()
printStackTrace 함수는 사용을 지양하시는 것이 좋아요.
내부 구조가 노출될 가능성이 있어요.

2019-10-30 11:20 UTC, BeokBeok commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/SearchBlogAndNewsAdapter.kt
> +        holder.apply {
apply 보다 with 나 run 을 사용하시는 것이 좋을 것 같아요.

2019-10-30 11:20 UTC, BeokBeok commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/SearchBlogAndNewsAdapter.kt
> +            LayoutInflater.from(parent.context).inflate(R.layout.item_blog_and_news, parent, false)
inflate 함수는 개행해주시는 것이 좋을 것 같아요.

2019-10-30 11:20 UTC, BeokBeok commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/SearchBlogAndNewsAdapter.kt
> +        private var view: View = v
해당 변수는 제거하시고, 
RecyclerView.ViewHolder 에 있는 itemView 변수를 사용하시면 좋을 것 같아요.

2019-10-30 11:20 UTC, BeokBeok commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/SearchBlogAndNewsAdapter.kt
> +                HtmlCompat.fromHtml(item?.description.toString(), HtmlCompat.FROM_HTML_MODE_COMPACT)
item 변수 null check 를 선작업 하신 후에 진행하시는 것이 좋을 것 같아요.

2019-10-30 11:20 UTC, BeokBeok commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/SearchBlogAndNewsAdapter.kt
> +            ViewHolder {
```
override fun onCreateViewHolder(
    parent: ViewGroup, 
    viewType: Int
): ViewHolder {
```

이렇게 쓰시거나

```
override fun onCreateViewHolder(parent: ViewGroup, viewType: Int): ViewHolder {
```

이렇게 쓰시는 것이 좋을 것 같아요.

2019-10-30 11:20 UTC, BeokBeok commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/SearchMovieAndBookAdapter.kt
> +
개행은 한 줄 단위로 개행하시는 것이 좋을 것 같아요.

2019-10-30 11:20 UTC, BeokBeok commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/SearchMovieAndBookAdapter.kt
> +            item?.image?.let {
immutable 변수는 let 보다 if 문으로 safe null 처리 하는 것이 좋을 것 같아요.

2019-10-30 11:20 UTC, BeokBeok commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/SearchMovieAndBookAdapter.kt
> +                    .into(view.iv_main_image)
외부 라이브러리는 wrapper 클래스를 별도로 만드셔서 처리하시면 좋을 것 같아요.

2019-10-30 11:20 UTC, BeokBeok commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/model/Item.kt
> +data class Item(
클래스명이 너무 일반적인 의미를 갖고 있는 것 같아요.
좀 더 자세한 이름을 사용하시는 것이 좋을 것 같아요.

2019-10-30 11:20 UTC, BeokBeok commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/model/ResultOfSearchingModel.kt
> +    val items: ArrayList<Item>,
ArrayList 보다 List 인터페이스 타입으로 하시면 좋을 것 같아요.
결국 ArrayList 도 List 를 구현하기 때문에,
타입을 List 로 하신다 하더라도 ArrayList 타입으로 쓸 수 있어요.

2019-10-30 11:20 UTC, BeokBeok commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/network/RetrofitClient.kt
> +    private val BASE_URL: String = "https://openapi.naver.com/"
url 은 생성자로 받아서 처리하시면 좋을 것 같아요.

2019-10-30 11:20 UTC, BeokBeok commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/network/RetrofitClient.kt
> +        }
프로퍼티의 custom getter 보다는 함수로 만들어서 처리하시는 것이 좋을 것 같아요.

2019-10-30 11:20 UTC, BeokBeok commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/network/RetrofitInterface.kt
> +interface RetrofitInterface {
인터페이스 명에 인터페이스가 들어가는 것은 이상한 것 같아요.
`RetrofitService` 은 어떠신가요?

2019-10-30 11:20 UTC, BeokBeok commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/network/RetrofitInterface.kt
> +        @Query("query") query: String
어노테이션은 일반적으로 개행해서 쓰시는 것이 좋을 것 같아요.
[annotation-formatting](https://kotlinlang.org/docs/reference/coding-conventions.html#annotation-formatting)

2019-10-30 11:20 UTC, BeokBeok commented on bean628/MyProject/app/src/main/res/layout/activity_main.xml
> +            android:text="검색"
string.xml 에서 참조하여 사용하면 좋을 것 같아요.

2019-10-30 11:20 UTC, BeokBeok commented on bean628/MyProject/app/src/main/res/layout/activity_main.xml
> +            android:textSize="16dp" />
text size 를 sp 가 아닌 dp 로 하신 것은 의도하신건가요?

2019-10-30 11:20 UTC, BeokBeok commented on bean628/MyProject/app/src/main/res/layout/activity_main.xml
> +            android:background="#03A9F4"
colors.xml 에서 참조하여 사용하면 좋을 것 같아요.

2019-10-30 11:20 UTC, BeokBeok commented on bean628/MyProject/app/src/main/res/layout/item_book_and_movie.xml
> +    <ImageView
content description 을 사용하지 않으신다면,
`android:contentDescription:@null` 을 추가해주시면 좋을 것 같아요.

2019-10-30 11:20 UTC, BeokBeok commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/MainActivity.kt
> +                        else -> SearchMovieAndBookAdapter(response.body()?.items ?: ArrayList())
response.body() 에 대해서 null check 를 선행한 이후에 작업하시는 것이 좋을 것 같아요.

2019-10-30 12:22 UTC, bean628 commented
> 중복되는 API처리 및 HTML태그 제거 한번 확인 부탁드려요~
> 음.. 그리고 Glide에서 잘못된 이미지 주소로 인하여 이미지 없을 때 예외처리로 플레이스 홀더 넣어주면 이미지 없을 경우 처리가 가능합니당~
> into 앞쪽에
> .placeholder( 이미지 리소스 아이디 )
> 요렇게 넣으시면 예외처리 될 꺼에요 아마 ㅎㅎ



> @bean628
> 수정한거 리뷰 코멘트에 커밋id 남겨주세요

넵!

2019-10-30 14:58 UTC, bean628 commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/MainActivity.kt
> +    private lateinit var mRetrofitClient: RetrofitClient
수정했습니다~

69aef96

2019-10-30 14:59 UTC, bean628 commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/MainActivity.kt
> +    private var mSearchType: Int = 0    // 0: 영화, 1: 책, 2: 블로그, 3: 뉴스
상수사용하는 방식으로 변경했습니다.


cc5e81d

2019-10-30 14:59 UTC, bean628 commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/MainActivity.kt
> +        input_search_sth.setOnEditorActionListener { v, actionId, event ->
수정했습니다.

0925e17

2019-10-30 15:00 UTC, bean628 commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/MainActivity.kt
> +        rv_searched_list.layoutManager = LinearLayoutManager(this)
네 수정했습니다. 

a4c0c0b

2019-10-30 15:01 UTC, bean628 commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/MainActivity.kt
> +        }
리스너를 등록하는 함수를 만든다는게 어떤걸 뜻하는건지 잘 모르겠어요~

2019-10-30 15:01 UTC, bean628 commented on bean628/MyProject/app/src/main/res/layout/activity_main.xml
> +            android:text="검색"
수정했습니다.

5c89079

2019-10-30 15:03 UTC, bean628 commented on bean628/MyProject/app/src/main/res/layout/activity_main.xml
> +            android:textSize="16dp" />
sp로 하는 경우 단말기 설정값에 따라 텍스트 크기를 키울수 있는걸로 알고있습니다.
텍스트가 커지는 경우 레이아웃이 깨지거나 글씨가 보이지 않는 경우가 있어 dp로 했습니다.

2019-10-30 15:04 UTC, bean628 commented on bean628/MyProject/app/src/main/res/layout/activity_main.xml
> +            android:background="#03A9F4"
수정했습니다~

8a377c6

2019-10-30 15:05 UTC, bean628 commented on bean628/MyProject/app/src/main/res/layout/item_book_and_movie.xml
> +    <ImageView
수정했습니다

0681411

2019-10-30 15:06 UTC, bean628 commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/MainActivity.kt
> +                        else -> SearchMovieAndBookAdapter(response.body()?.items ?: ArrayList())
수정했습니다~

736fbed

2019-10-30 15:07 UTC, bean628 commented
> 안녕하세요. 스터디 2기 강현석이라고 합니다.
> 부족하지만 잘 부탁드립니다. 😅

코드 리뷰해주셔서 감사합니다~~
저도 잘부탁드려요!

2019-10-30 15:18 UTC, BeokBeok commented
![스크린샷 2019-10-31 오전 12 17 58](https://user-images.githubusercontent.com/48344355/67871578-ed25d080-fb73-11e9-9af3-54c3dc95d4db.png)
**Load more**  누르시면 21개가 더 있습니다.

2019-10-30 15:22 UTC, bean628 commented
> ![스크린샷 2019-10-31 오전 12 17 58](https://user-images.githubusercontent.com/48344355/67871578-ed25d080-fb73-11e9-9af3-54c3dc95d4db.png)
> **Load more** 누르시면 21개가 더 있습니다.

저 표시를 못봤네요! 내일 마저 수정하겠습니다!

2019-10-31 07:24 UTC, sjjeong commented on bean628/MyProject/app/src/main/res/layout/activity_main.xml
> +            android:textSize="16dp" />
구글 권장은 sp지만 dp로 하는 기업도 많아서 이 부분은 넘겨도 괜찮다고 생각합니다.

2019-11-02 03:03 UTC, bean628 commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/MainActivity.kt
> +    private lateinit var mRetrofitClient: RetrofitClient
코틀린 공부하면서 저런게 있길래 써봤......습니다 ㅋㅋㅋ
나중에 프로젝트에서 무거운 동작을 하게될 경우가 생긴다면 나중에 초기화돼도 문제없는 로직들에 지연초기화를 유용하게 사용할것 같네요.

2019-11-02 03:10 UTC, bean628 commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/MainActivity.kt
> +        val word: String = input_search_sth?.text.toString()
as InputMethodManager 이 부분이 필요없다는 말씀이신가요??
현재 코드에서 as InputMethodManager이 부분을 제거하면 require 타입은 inputmethodManager인데 추론된 발견된 타입은 Any!로 나와서 에러가 떠있는 상태가 됩니다
혹시 제가 잘 못 이해한거면 말씀 부탁드려요~

2019-11-02 07:02 UTC, bean628 commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/MainActivity.kt
> +        val word: String = input_search_sth?.text.toString()
수정했습니다

b20f938

2019-11-02 07:03 UTC, bean628 commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/MainActivity.kt
> +            Toast.makeText(this@MainActivity, "검색어를 입력해주세요.", Toast.LENGTH_SHORT).show()
수정했습니다.

5ce1fd6

2019-11-02 07:03 UTC, bean628 commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/MainActivity.kt
> +                if (response.code() == 200) {
수정했습니다

3445d76

2019-11-02 07:03 UTC, bean628 commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/MainActivity.kt
> +                    if (rv_searched_list.adapter!!.itemCount == 0) {
수정했습니다

2ba4738

2019-11-02 07:04 UTC, bean628 commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/SearchBlogAndNewsAdapter.kt
> +        holder.apply {
수정했습니다~

91b5764

2019-11-02 07:04 UTC, bean628 commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/SearchBlogAndNewsAdapter.kt
> +            LayoutInflater.from(parent.context).inflate(R.layout.item_blog_and_news, parent, false)
수정했습니다

87dd780

2019-11-02 07:04 UTC, bean628 commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/SearchBlogAndNewsAdapter.kt
> +        private var view: View = v
오 이런게 있었네요! 
수정했습니다~

5242d48

2019-11-02 07:05 UTC, bean628 commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/SearchBlogAndNewsAdapter.kt
> +                HtmlCompat.fromHtml(item?.description.toString(), HtmlCompat.FROM_HTML_MODE_COMPACT)
수정했습니다.

d9c554e

2019-11-02 07:05 UTC, bean628 commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/SearchBlogAndNewsAdapter.kt
> +            ViewHolder {
수정했습니다

2c6b6b2

2019-11-02 07:05 UTC, bean628 commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/SearchMovieAndBookAdapter.kt
> +
수정했습니다~

fe0ff03

2019-11-02 07:06 UTC, bean628 commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/SearchMovieAndBookAdapter.kt
> +            item?.image?.let {
수정했습니다

fe0ff03

2019-11-02 07:14 UTC, bean628 commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/SearchMovieAndBookAdapter.kt
> +                    .into(view.iv_main_image)
음.. 어떻게 하면 좋다는건지 잘 모르겠어요 ~~~

2019-11-02 07:14 UTC, bean628 commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/model/ResultOfSearchingModel.kt
> +    val items: ArrayList<Item>,
수정했습니다

56457d8

2019-11-02 07:15 UTC, bean628 commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/network/RetrofitClient.kt
> +    private val BASE_URL: String = "https://openapi.naver.com/"
수정했습니다~

212249f

2019-11-02 07:15 UTC, bean628 commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/network/RetrofitClient.kt
> +        }
수정했습니다~

ee4b2c6

2019-11-02 07:16 UTC, bean628 commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/network/RetrofitInterface.kt
> +interface RetrofitInterface {
수정했습니다~

8b43560

2019-11-02 07:16 UTC, bean628 commented on bean628/MyProject/app/src/main/res/layout/activity_main.xml
> +            android:textSize="16dp" />
넵

2019-11-02 07:18 UTC, bean628 commented
오늘 새벽 1시까지 야근해서 퇴근하고 기절했다가 이제야 겨우 끝냈네요 후.. 
리뷰 감사합니다!

2019-11-02 07:54 UTC, BeokBeok commented on bean628/MyProject/app/src/main/res/layout/activity_main.xml
> +            android:textSize="16dp" />
만약 의도하신 것이라면,
`tools:ignore="spUsage"` 를 추가해주시면
다른 개발자가 코드를 보았을 때, 의도한 것이라 이해하고 넘어갈 수 있을 것 같아요.

2019-11-02 07:54 UTC, BeokBeok commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/SearchMovieAndBookAdapter.kt
> +                    .into(view.iv_main_image)
GlideWrapper 클래스를 만드셔서 클래스 내에 함수를 만드시고
함수를 호출해서 처리하시는 것이 좋을 것 같아요.

```
fun showImage( /* 파라미터 추가 */) {
    // 이미지 보여주는 로직 구현
}

// 호출 시
GlideWrapper.showImage( /* 파라미터 전달 */ )
```

Wrapper 를 만드시게 되면 
만약 Glide 관련하여 수정사항이 발생하면,
Glide 를 사용하는 모든 곳을 찾아가서 수정하는 번거로움을 덜 수 있어요.

2019-11-02 07:54 UTC, BeokBeok commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/MainActivity.kt
> +        val word: String = input_search_sth?.text.toString()
68 번째 라인만 선택을 하였는데, 윗단 코드까지 나와서 혼동하신 것 같아 죄송합니다.

2019-11-02 07:54 UTC, BeokBeok commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/MainActivity.kt
> +    private lateinit var mRetrofitClient: RetrofitClient
지연초기화는 신중하게 사용하는 것이 좋을 것 같아요.
어쩔 수 없이 지연초기화를 사용해야하는 경우가 아니라면, 일반초기화가 더 좋을 것 같습니다.

다음은 이펙티브 자바 책을 인용하였습니다.

> 아이템 83. 지연 초기화는 신중히 사용하라.
지연초기화는 양날의 검이다. 클래스 혹은 인스턴스 생성 시의 초기화 비용은 줄지만 그 대신 지연 초기화하는 필드에 접근하는 비용은 커진다. 지연 초기화하려는 필드들 중 결국 초기화가 이뤄지는 비율에 따라, 실제 초기화에 드는 비용에 따라, 초기화된 각 필드를 얼마나 빈번히 호출하느냐에 따라 지연 초기화가 (다른 수많은 최적화와 마찬가지로) 실제로는 성능을 느려지게 할 수도 있다.
그럼에도 지연 초기화가 필요할 때가 있다. 해당 클래스의 인스턴스 중 그 필드를 사용하는 인스턴스의 비율이 낮은 반면, 그 필드의 초기화하는 비용이 크다면 지연 초기화가 제 역할을 해줄 것이다. 하지만 안타깝게도 정말 그런지를 알 수 있는 유일한 방법은 지연 초기화 적용 전후의 성능을 측정해보는 것이다.
...
대부분의 상황에서 일반적인 초기화가 지연 초기화보다 낫다.

2019-11-02 07:54 UTC, BeokBeok commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/MainActivity.kt
> +        }
```
fun registerClickListener() {
        btn_search.setOnClickListener(this)
        btn_search_type_movie.setOnClickListener(this)
        btn_search_type_book.setOnClickListener(this)
        btn_search_type_blog.setOnClickListener(this)
        btn_search_type_news.setOnClickListener(this)
        input_search_sth.setOnEditorActionListener { v, actionId, event ->
            when (actionId) {
                EditorInfo.IME_ACTION_SEARCH -> {
                    search(mSearchType)
                    true
                }
                else -> false
            }
        }
}
```

이런 식으로 리스너를 등록하는 함수를 만들어주시면 좋을 것 같아요.

2019-11-02 07:55 UTC, BeokBeok commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/MainActivity.kt
> +        rv_searched_list.layoutManager = LinearLayoutManager(this)
소스상에서는 빠졌지만, xml 에 추가하는 코드가 없는 것 같습니다.

2019-11-02 07:56 UTC, BeokBeok commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/MainActivity.kt
> +                t.printStackTrace()
커밋 아이디 추가해주세요.

2019-11-02 07:56 UTC, BeokBeok commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/model/Item.kt
> +data class Item(
커밋 아이디 추가해주세요.

2019-11-02 07:56 UTC, BeokBeok commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/network/RetrofitInterface.kt
> +        @Query("query") query: String
커밋 아이디 추가해주세요.

2019-11-02 07:59 UTC, BeokBeok commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/SearchMovieAndBookAdapter.kt
> +                    .with(itemView.context)
Glide 와 with는 붙여쓰시면 좋을 것 같아요.
`Glide.with(itemView.context)`

2019-11-02 07:59 UTC, BeokBeok commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/network/RetrofitClient.kt
>          }
custom getter  보다는 함수로 처리하시는 것이 좋을 것 같아요.

2019-11-02 07:59 UTC, BeokBeok commented on bean628/MyProject/app/src/main/java/common/Constant.kt
> +
개행은 한 줄 단위로 해주시면 좋을 것 같아요.

2019-11-02 10:42 UTC, bean628 commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/MainActivity.kt
> +        rv_searched_list.layoutManager = LinearLayoutManager(this)
```
 <androidx.recyclerview.widget.RecyclerView
        android:id="@+id/rv_searched_list"
        android:layout_width="match_parent"
        android:layout_height="0dp"
        android:layout_marginTop="10dp"
        android:layout_marginBottom="10dp"
        android:layout_weight="1"
        android:clipToPadding="false"
        app:layoutManager="androidx.recyclerview.widget.LinearLayoutManager" />
```
제일 하단에 있는 app:layoutManager 이부분 말씀하시는건가요?? 
이 부분은 제가 처음에 있었는데 코드에도 중복으로 저 부분이 들어간거라 
xml에는 수정된게 없어서 그런것 같아요!

2019-11-02 10:43 UTC, bean628 commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/MainActivity.kt
> +        }
아~ 모아서 등록하라는 말이였군요! 
수정했습니다~

bab3d60

2019-11-02 10:43 UTC, bean628 commented on bean628/MyProject/app/src/main/res/layout/activity_main.xml
> +            android:textSize="16dp" />
수정했습니다!

5dcc8da

2019-11-02 10:44 UTC, bean628 commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/SearchMovieAndBookAdapter.kt
> +                    .with(itemView.context)
수정했습니다.

615770b

2019-11-02 10:44 UTC, bean628 commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/network/RetrofitClient.kt
>          }
수정했습니다

801ebc1

2019-11-02 10:45 UTC, bean628 commented on bean628/MyProject/app/src/main/java/common/Constant.kt
> +
수정했습니다~

615770b

2019-11-02 12:05 UTC, BeokBeok reviewed
Load more 버튼을 누르셔서 리뷰 내용을 전부 확인하시고, 
커밋 아이디 및 누락된 리뷰에 대해서 검토해주세요.

2019-11-02 12:05 UTC, BeokBeok commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/network/RetrofitClient.kt
> +        return Retrofit.Builder()
구현부가 return 하나인 경우에는 = 을 사용하면 중괄호를 없앨 수 있을 것 같아요.

2019-11-02 12:31 UTC, bean628 commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/network/RetrofitClient.kt
> +        return Retrofit.Builder()
수정했습니다~

0eeed37

2019-11-02 12:35 UTC, bean628 commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/MainActivity.kt
> +    private lateinit var mRetrofitClient: RetrofitClient
수정했습니다~ 

801ebc1f

2019-11-02 12:38 UTC, bean628 commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/MainActivity.kt
> +        val word: String = input_search_sth?.text.toString()
아아 word 변수였었군요! 저도 바로 밑줄인데 생각을 못했네요 ㅎㅎ
수정했습니다

7a7cdf2

2019-11-02 12:40 UTC, bean628 commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/MainActivity.kt
> +                t.printStackTrace()
엇 여기요! 수정했습니다!

143a30aa

2019-11-02 12:52 UTC, bean628 commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/SearchMovieAndBookAdapter.kt
> +                    .into(view.iv_main_image)
Wrapper 클래스 추가했습니다!!
retrofitClient 처럼 쓰는것도 Wrapper 클래스의 일종이라고 할수 있을까요? 
Wrapper 클래스에 대한 개념이 아직 덜 잡혀서요 궁금하네요

2a1fce8

2019-11-02 12:53 UTC, bean628 commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/model/Item.kt
> +data class Item(
누락된 커멘트 추가했습니다!
8b435607

2019-11-02 12:54 UTC, bean628 commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/network/RetrofitInterface.kt
> +        @Query("query") query: String
누락된 커멘트 추가했습니다!
9375b19e

2019-11-02 12:57 UTC, bean628 commented
누락된 코멘트들 추가했습니다!

2019-11-02 14:08 UTC, BeokBeok commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/SearchMovieAndBookAdapter.kt
> +                    .into(view.iv_main_image)
GlideWrapper 를 class 가 아닌 object 로 만드시고
companion object 는 사용하지 않으시는 것이 더 좋을 것 같아요.

wrapper 는 단순히 감싼다 라고 생각하시면 될 것 같습니다.
retrofitClient 도 wrapper 의 일종이라고 할 수 있을 것 같습니다.

2019-11-02 14:25 UTC, bean628 reviewed
Review Changes도 체크해서 해야하나요?

2019-11-02 14:26 UTC, bean628 commented
제가 더 해야할께 있나요?

2019-11-02 14:32 UTC, BeokBeok commented
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/260#discussion_r341812369

이 리뷰 검토해주시면 될 것 같습니다. 😅

2019-11-02 14:38 UTC, bean628 commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/SearchMovieAndBookAdapter.kt
> +                    .into(view.iv_main_image)
넵 감사합니다~~ 
수정했습니다! 

36bda53

2019-11-02 14:39 UTC, bean628 commented
> [#260 (comment)](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/260#discussion_r341812369)
> 
> 이 리뷰 검토해주시면 될 것 같습니다. 😅

넵 수정했습니다.
죄송합니다 어떤 리뷰를 누락됐는지 잘 안보이네요.  ㅎㅎ;

2019-11-02 14:41 UTC, BeokBeok submitted a review, later dismissed
LGTM:ok_hand:

2019-11-03 01:34 UTC, ironelder submitted a review, later dismissed

2019-11-03 03:06 UTC, sjjeong requested changes

2019-11-03 03:06 UTC, sjjeong commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/MainActivity.kt
> +                        rv_searched_list.adapter = when (this@MainActivity.searchType) {
어뎁터를 네트워크 통신 이후에 생성하지 말아주세요
어뎁터를 생성하는 것은 onCreate 시점에서 해주시고
데이터를 갱신하는 작업만 해주세요

2019-11-03 03:06 UTC, sjjeong commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/SearchBlogAndNewsAdapter.kt
> +        val listener = View.OnClickListener { it ->
listener 등록하는 것은 onBindViewHolder시점이 아닌 onCreateViewHolder에서 해주세요

2019-11-03 04:57 UTC, bean628 commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/MainActivity.kt
> +                        rv_searched_list.adapter = when (this@MainActivity.searchType) {
수정했습니다

a9ae1b2

2019-11-03 13:00 UTC, bean628 commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/SearchBlogAndNewsAdapter.kt
> +        val listener = View.OnClickListener { it ->
수정했습니다!

037bb43

2019-11-03 15:28 UTC, sjjeong commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/SearchBlogAndNewsAdapter.kt
> +        val listener = View.OnClickListener { it ->
동일하게 onBindViewHolder에서 되고 있습니다.

2019-11-03 15:30 UTC, sjjeong requested changes

2019-11-03 15:30 UTC, sjjeong commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/SearchBlogAndNewsAdapter.kt
> +class SearchBlogAndNewsAdapter(private var items: List<SearchedItem>) :
list를 생성자로 받지 마시고 내부적으로 가지고 있게 해주세요.

2019-11-03 15:30 UTC, sjjeong commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/SearchBlogAndNewsAdapter.kt
> +        items = newItems
adapter내부에서 사용하는 list와 외부에서 사용하는 list의 객체를 공유하지말아주세요
clear() addAll()함수를 사용해주세요

2019-11-03 22:09 UTC, bean628 commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/SearchBlogAndNewsAdapter.kt
> +        val listener = View.OnClickListener { it ->
다시 수정했습니다!

fc7b62b

2019-11-03 22:09 UTC, bean628 commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/SearchBlogAndNewsAdapter.kt
> +class SearchBlogAndNewsAdapter(private var items: List<SearchedItem>) :
수정했습니다!

4d511cb

2019-11-03 22:09 UTC, bean628 commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/SearchBlogAndNewsAdapter.kt
> +        items = newItems
수정했습니다~ 

8ea6e17

2019-11-04 11:09 UTC, sjjeong approved these changes

2019-11-04 23:27 UTC, ironelder approved these changes

2019-11-05 04:08 UTC, merged