HW-1 샘플 프로젝트 과제 제작
sjjeong/GoogryAndroidArchitecutreStudy pull request #262
Opened 2019-10-29 06:51 UTC by 2giwon

1. 탭 4개 (ViewPager) 구성
2. 각 탭에 Fragment 생성
3. retrofit으로 api 호출하여 recyclerview에 반영하도록 적용
4. glide로 썸네일 요청하여 적용하도록 수정
5. 의식의 흐름대로 코드 작성

코드 리뷰 부탁드립니다.

2019-10-31 10:21 UTC, taeiim reviewed
처음 해보는 코드리뷰라 많이 서투릅니다! ㅎㅎ ㅜㅜ 
확인 부탁드립니당

2019-10-31 10:21 UTC, taeiim commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/tabs/ContentsAdapter.kt
> +                .into(holder.imageThumbnail)
사진이 없는 탭에서도 호출될 필요성이 있을까요?! 
위에 when 에서 movie, book 묶어서 안에 넣어줘도 될 것 같습니다.

2019-10-31 10:21 UTC, taeiim commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/tabs/ContentsAdapter.kt
> +            }
중복된 if문이 반복되어 코드가 더 복잡해 보이는 것 같습니다. 
tvTitle과 tvDescription setText하는 코드를 하나의 if문에 같이 넣거나, 
html text를 처리해주는 extensions를 만들어서 처리하면 깔끔해질 것 같습니다!

2019-10-31 10:21 UTC, taeiim commented on 2giwon/ArchitectureStudy/app/build.gradle
> +    implementation 'androidx.core:core-ktx:1.1.0'
$kotlin_version처럼 
api 버전들을 따로 빼서 관리하면 더 좋을 것 같습니당 ㅎㅎ

2019-10-31 10:21 UTC, taeiim commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/tabs/ContentsAdapter.kt
> +                .apply(RequestOptions.placeholderOf(R.mipmap.ic_launcher))
placeholder을 ic_launcher로 해주어서 유저들에게 안드로이드 이미지를 보여주는것보다
아예 visible gone 시키는건 어떨까요?

2019-10-31 10:21 UTC, taeiim commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/tabs/ContentsFragment.kt
> +        val contentsAdapter = ContentsAdapter(type)
검색할때마다 adapter를 계속 생성해 줄 필요가 있을까요?!
한 번 만들어놓고 재사용하는게 어떨까 싶습니다.. ! 🧐

2019-10-31 14:13 UTC, 2giwon commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/tabs/ContentsFragment.kt
> +        val contentsAdapter = ContentsAdapter(type)
처음 생성시에만 어댑터를 만들도록 수정했습니다

a775a0ae99fdf5b2c6eacca35f909f5a9e805852

2019-10-31 14:14 UTC, 2giwon commented on 2giwon/ArchitectureStudy/app/build.gradle
> +    implementation 'androidx.core:core-ktx:1.1.0'
ext 로 따로 관리하도록 수정했습니다^^ 

a8b36da220c70c3f25a3ef6cc07e84f0537c3a12

2019-10-31 14:15 UTC, 2giwon commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/tabs/ContentsAdapter.kt
> +                .into(holder.imageThumbnail)
사진이 없는 탭에서 글라이드를 호출하지 않도록 수정했습니다^^

166aa586ed31b651578b860a398639090ebc8a3e

2019-10-31 14:16 UTC, 2giwon commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/tabs/ContentsAdapter.kt
> +            }
스트링 ext로 처리할 수 있도록 수정했습니다.

감사합니다

166aa586ed31b651578b860a398639090ebc8a3e

2019-10-31 14:29 UTC, 2giwon commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/tabs/ContentsAdapter.kt
> +                .apply(RequestOptions.placeholderOf(R.mipmap.ic_launcher))
음 이거는 앱 구현 취향일 수도 있을 거 같은데 저는 리싸이클러뷰에서 visible을 gone으로 처리할경우 

view의 자리를 같은 아이템 뷰에 있는 다른 뷰 들이 차지해버리니 리싸이클러뷰의 각 아이템의 정렬이 맞지 않아서  일부러 그렇게 처리하지 않았습니다. 

이거는 제가 틀린 것일 수도 있으나 앱 구현 컨셉에 따라 달라 질 수 있다고 생각합니다.
아예 이미지가 나오지 않으면 레이아웃 오류로 생각될 수도 있을 거 같습니다.

디폴트 이미지는 어떤 걸로도 바꿀 수 있기 때문에 사용자에게 이미지가 없는 것으로 보일 수도 있도록 유도할 수 있어 보입니다.

2019-11-01 07:04 UTC, taeiim submitted a review, later dismissed

2019-11-01 08:05 UTC, sjjeong requested changes

2019-11-01 08:05 UTC, sjjeong commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/data/ContentsService.kt
> +        @Header("X-Naver-Client-Id") clientId: String,
OkHttp Client에 interceptor로 추가해보면 어떨까요

2019-11-01 08:05 UTC, sjjeong commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/data/SearchService.kt
> +                    level = HttpLoggingInterceptor.Level.BODY
디버그가 아닐 때 Level.NONE을 set해주세요

2019-11-01 08:05 UTC, sjjeong commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/tabs/ContentsAdapter.kt
> +        items.iterator().forEach {
list.addAll(items)로 할 수 있습니다.

2019-11-01 08:05 UTC, sjjeong commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/tabs/ContentsFragment.kt
> +        rv_contents.addItemDecoration(
rv_contents를 with나 run으로 묶어주면 좋을 것 같습니다.

2019-11-01 08:05 UTC, sjjeong commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/tabs/ContentsFragment.kt
> +        }
(rv_contents.adapter as? ContentsAdapter).setList(searchContents)
로 사용할 수 있습니다.

2019-11-01 14:52 UTC, 2giwon commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/data/ContentsService.kt
> +        @Header("X-Naver-Client-Id") clientId: String,
interceptor 추가했습니다^^

986a9dc15eed5b53039da30943c4ad248819ff05

2019-11-01 14:53 UTC, 2giwon commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/data/SearchService.kt
> +                    level = HttpLoggingInterceptor.Level.BODY
디버그가 아닐때 조건 추가 했습니다

9dd54bf4b909f1ffe7d13830513feee09a53f539

2019-11-01 14:54 UTC, 2giwon commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/tabs/ContentsAdapter.kt
> +        items.iterator().forEach {
addAll 로 수정했습니다.

8fadb09c78c7953234f65d493f4af55c2bb866fd

2019-11-01 14:55 UTC, 2giwon commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/tabs/ContentsFragment.kt
> +        rv_contents.addItemDecoration(
with로 묶었습니다^^

4495fabe024c3b2381918a87b803a23b5102839f

2019-11-01 14:55 UTC, 2giwon commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/tabs/ContentsFragment.kt
> +        }
코드 수정했습니다.

41d3d7f648551f6a5c723abb9c0764b2147bc8e4

2019-11-02 09:40 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-11-03 04:52 UTC, taeiim approved these changes

2019-11-03 04:59 UTC, merged