HW-1 샘플 프로젝트 과제 제작
sjjeong/GoogryAndroidArchitecutreStudy pull request #263
Opened 2019-10-30 05:05 UTC by taeiim

2019-10-30 10:34 UTC, 2giwon requested changes
리뷰 끝났습니다. 확인 부탁드립니다.

2019-10-30 10:34 UTC, 2giwon commented on taeiim/MyApplication/app/build.gradle
> +    implementation "androidx.appcompat:appcompat:$appcompat_version"
material 에 포함되는 라이브러리 입니다 빼셔도 될 것 같습니다.

2019-10-30 10:34 UTC, 2giwon commented on taeiim/MyApplication/app/build.gradle
> +    implementation "androidx.recyclerview:recyclerview:$recyclerview_version"
material 에 포함되는 라이브러리 입니다 빼셔도 될 것 같습니다.

2019-10-30 10:34 UTC, 2giwon commented on taeiim/MyApplication/app/src/main/res/menu/menu_main_bottom_navigation.xml
> +        android:title="블로그" />
하드코딩 보다 string.xml 로 처리하는게 나을 것 같습니다.

2019-10-30 10:34 UTC, 2giwon commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/BlogFragment.kt
> +        return inflater.inflate(R.layout.fragment_main, null)
왜 null로 처리하신건지 궁금합니다. 
inflater.inflate(R.layout.fragment_main, container, false) 이건 어떤가요?ㅎㅎㅎ

2019-10-30 10:34 UTC, 2giwon commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/MainActivity.kt
> +        val tag = itemId.toString()
tag 변수 없이 바로 이렇게도 가능 할 것 같습니다.

supportFragmentManager.findFragmentByTag(itemId.toString())

2019-10-30 10:34 UTC, 2giwon commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/MainActivity.kt
> +        val fragment = supportFragmentManager.findFragmentByTag(tag) ?: when (itemId) {
fragment 변수 없이 이렇게도 가능 할 것 같습니다.

supportFragmentManager.findFragmentByTag(
            itemId.toString()
        ) ?: when (itemId) {
            R.id.blogNavigation -> BlogFragment()
            R.id.newsNavigation -> NewsFragment()
            R.id.movieNavigation -> MovieFragment()
            R.id.bookNavigation -> BookFragment()
            else -> null
        } ?.let { replaceFragment(it) }

2019-10-30 10:34 UTC, 2giwon commented on taeiim/MyApplication/app/src/main/res/layout/fragment_main.xml
> +        android:text="검색"
하드 코딩 보다 strings.xml로 처리하는게 나을 것 같습니다.

2019-10-30 10:34 UTC, 2giwon commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/api/model/SearchResult.kt
> +        var items: List<Item>
val로 해도 되지 않나요?

2019-10-30 10:34 UTC, 2giwon commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/api/model/SearchResult.kt
> +            val items: ArrayList<Item>,
이 변수는 어떤 용도인지 궁금합니다

2019-10-30 10:34 UTC, 2giwon commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/MovieFragment.kt
> +    internal var searchCall: Call<SearchResult>? = null
이 변수만 왜 internal로 처리 하셨는지 궁금합니다.

2019-10-30 10:34 UTC, 2giwon commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/MovieFragment.kt
> +    val api: SearchApi by lazy { provideAuthApi() }
private 으로 해도 될 것 같습니다.

2019-10-30 10:34 UTC, 2giwon commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/MovieFragment.kt
> +    var searchResultList: ArrayList<SearchResult.Item> = ArrayList()
private 해도 될 것 같습니다.

2019-10-30 10:34 UTC, 2giwon commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/MovieFragment.kt
> +            val query = searchEditTv.text.toString()
searchMovie(searchEditTv.text.toString()) 이렇게 해도 될 것 같습니다.

2019-10-30 10:34 UTC, 2giwon commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/MovieFragment.kt
> +        searchCall!!.enqueue(object : Callback<SearchResult> {
searchCall 이 null인 경우 처리가 필요해보입니다.

2019-10-30 10:34 UTC, 2giwon commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/MovieFragment.kt
> +                    setItems(response.body()!!.items as ArrayList<SearchResult.Item>)
response.body() 가 null인 경우 처리가 필요해 보입니다.

2019-10-30 10:34 UTC, 2giwon commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/MovieFragment.kt
> +            val view = LayoutInflater.from(parent.context).inflate(R.layout.item_movie, parent, false)
return BlogListHolder(
                LayoutInflater
                    .from(parent.context)
                    .inflate(R.layout.item_contents, parent, false)
            )

이렇게 처리도 가능해 보입니다.

2019-10-30 10:34 UTC, 2giwon commented on taeiim/MyApplication/app/src/main/res/layout/item_movie.xml
> +        android:layout_marginLeft="16dp"
marginLeft 보다 marginStart가 좋을 것 같습니다.

2019-10-30 10:34 UTC, 2giwon commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/MovieFragment.kt
> +                    setOnClickListener { startActivity(Intent(Intent.ACTION_VIEW, Uri.parse(movie.link))) }
코틀린 convention 적용 부탁드립니다.

2019-10-30 10:34 UTC, 2giwon commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/NewsFragment.kt
> +    var searchResultList: ArrayList<SearchResult.Item> = ArrayList()
이 변수는 adapter에 전달하여 인자 값을 그대로 사용하고 있습니다.

레트로핏으로 받은 결과를 adapter에서 셋팅하는 용도로 쓰이는 것이라면 인자값을 그대로 값을 변경하는 것은

좋지 않은 것 같습니다.  adapter의 list변수를 만들어서 거기에 적용하여 사용하는 것이 어떨까 싶어요

2019-10-30 10:34 UTC, 2giwon commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/NewsFragment.kt
> +    private val api: SearchApi by lazy { provideAuthApi() }
단순히 레트로핏 api를 호출하는 용도로 멤버변수를 들고 있을 필요는 없을 것 같습니다.

2019-10-30 10:34 UTC, 2giwon commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/NewsFragment.kt
> +    private var searchCall: Call<SearchResult>? = null
var로 지정하여 사용할 필요는 없을 것 같습니다. 아니면 처음에 멤버변수로 지정할 필요가 있는지 확인이 필요해 보입니다.

2019-10-31 11:50 UTC, taeiim commented on taeiim/MyApplication/app/build.gradle
> +    implementation "androidx.appcompat:appcompat:$appcompat_version"
제거했습니다.

commit : 964cc7d9e28404c46dc3c66e5bd4eca2964d97bc

2019-10-31 11:51 UTC, taeiim commented on taeiim/MyApplication/app/build.gradle
> +    implementation "androidx.recyclerview:recyclerview:$recyclerview_version"
제거했는데 constraintlayout 도 포함되어있는것 맞나요?? 
constraintlayout 에서 빌드가 안돼서 다시 추가했습니다ㅠㅠ 

commit : 964cc7d9e28404c46dc3c66e5bd4eca2964d97bc

2019-10-31 11:52 UTC, taeiim commented on taeiim/MyApplication/app/src/main/res/menu/menu_main_bottom_navigation.xml
> +        android:title="블로그" />
변경했습니다. 

commit : 1c1ae13213423249376123e2af06a979f96ad26e

2019-10-31 11:52 UTC, taeiim commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/BlogFragment.kt
> +        return inflater.inflate(R.layout.fragment_main, null)
변경했습니다. 감사합니다 ㅎㅎ

commit : 9f6deb290abfdad7c5fcfc7c878cf68e83bbbb94

2019-10-31 11:53 UTC, taeiim commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/MainActivity.kt
> +        val tag = itemId.toString()
변경했습니다! 

commit : c98b87549a7d1d0fc8929b5ccc0c5b4bfeb9b931

2019-10-31 11:53 UTC, taeiim commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/MainActivity.kt
> +        val fragment = supportFragmentManager.findFragmentByTag(tag) ?: when (itemId) {
ㅎㅎ 변경했습니다

commit : c98b87549a7d1d0fc8929b5ccc0c5b4bfeb9b931

2019-10-31 11:53 UTC, taeiim commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/MainActivity.kt
> +        val tag = itemId.toString()
commit : 1c1ae13213423249376123e2af06a979f96ad26e

2019-10-31 11:55 UTC, taeiim commented on taeiim/MyApplication/app/src/main/res/layout/fragment_main.xml
> +        android:text="검색"
commit : 1c1ae13213423249376123e2af06a979f96ad26e

2019-10-31 11:55 UTC, taeiim commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/api/model/SearchResult.kt
> +        var items: List<Item>
감사합니다. 변경했습니다. 

commit : eee3dce4e95f8e1465958b2c525e76fddf32d159

2019-10-31 11:56 UTC, taeiim commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/api/model/SearchResult.kt
> +            val items: ArrayList<Item>,
잘못 추가된 것 같습니다. 감사합니다! 

commit : eee3dce4e95f8e1465958b2c525e76fddf32d159

2019-10-31 11:58 UTC, taeiim commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/MovieFragment.kt
> +    internal var searchCall: Call<SearchResult>? = null
private 으로 변경하였습니다. 
commit : 974ffdb2e08b26266170f123297b46b1e297b1ae

2019-10-31 11:58 UTC, taeiim commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/MovieFragment.kt
> +    val api: SearchApi by lazy { provideAuthApi() }
commit : 974ffdb2e08b26266170f123297b46b1e297b1ae

2019-10-31 11:58 UTC, taeiim commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/MovieFragment.kt
> +    var searchResultList: ArrayList<SearchResult.Item> = ArrayList()
commit : 974ffdb2e08b26266170f123297b46b1e297b1ae

2019-10-31 11:59 UTC, taeiim commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/MovieFragment.kt
> +            val query = searchEditTv.text.toString()
null check 까지 추가하였습니다. 
commit : 3fe3426ec8a2f3b4f9bbf35769f42b192f6b49bc

2019-10-31 12:00 UTC, taeiim commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/MovieFragment.kt
> +        searchCall!!.enqueue(object : Callback<SearchResult> {
null 인경우 리스트 clear 하는 방식으로 처리하였습니다.

commit : e13b25638042699e76bf80f47c722506e3ca718b

2019-10-31 12:02 UTC, taeiim commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/MovieFragment.kt
> +                    setItems(response.body()!!.items as ArrayList<SearchResult.Item>)
null check 추가하였고, null이면 리스트 clear 하는 방식으로 처리하였습니다.

commit : e198bf067c5d0e5cd5669c91158b012d947f86f0

2019-10-31 12:02 UTC, taeiim commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/MovieFragment.kt
> +            val view = LayoutInflater.from(parent.context).inflate(R.layout.item_movie, parent, false)
반영하였습니다. 감사합니다.

commit : 44decb078b1450a6a6bbfe8cccb9673d407e5b9a

2019-10-31 12:02 UTC, taeiim commented on taeiim/MyApplication/app/src/main/res/layout/item_movie.xml
> +        android:layout_marginLeft="16dp"
commit : d94ff5af8fc26ac904149781ab9da54fc6c37721

2019-10-31 12:03 UTC, taeiim commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/MovieFragment.kt
> +                    setOnClickListener { startActivity(Intent(Intent.ACTION_VIEW, Uri.parse(movie.link))) }
@2giwon  어떤 kotlin convention을 말씀하시는건가요?

2019-10-31 12:05 UTC, taeiim commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/NewsFragment.kt
> +    private val api: SearchApi by lazy { provideAuthApi() }
@2giwon  멤버변수로 들고 있지 않으면 호출할 때마다 provideAuthApi()가 호출될텐데 괜찮을까요?

2019-10-31 12:10 UTC, taeiim commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/NewsFragment.kt
> +    private var searchCall: Call<SearchResult>? = null
반영하였습니다. 꼼꼼한 리뷰 감사합니다! 😄

commit : e13b25638042699e76bf80f47c722506e3ca718b

2019-10-31 12:11 UTC, taeiim commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/NewsFragment.kt
> +    var searchResultList: ArrayList<SearchResult.Item> = ArrayList()
`searchResultList`를 fragment 내에서 삭제하고, adapter 내부에 만들었습니다! 

commit : 2680cce0bc6e15df8bd80bcc2b9ad1fda517c270

2019-10-31 14:33 UTC, 2giwon commented on taeiim/MyApplication/app/build.gradle
> +    implementation "androidx.recyclerview:recyclerview:$recyclerview_version"
앗 제가 얘기한건 appcompat과 recyclerview였습니다.

다 지우신거 같은데 다시 확인이 필요해보입니다.

2019-10-31 14:46 UTC, 2giwon commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/MovieFragment.kt
> +                    setOnClickListener { startActivity(Intent(Intent.ACTION_VIEW, Uri.parse(movie.link))) }
```
setOnClickListener {
                        startActivity(
                            Intent(
                                Intent.ACTION_VIEW,
                                Uri.parse(movie.link)
                            )
                        )
                    }
```

이런 식으로 하는 것은 어떨 가요? ㅎ

2019-10-31 15:24 UTC, 2giwon commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/NewsFragment.kt
> +    private val api: SearchApi by lazy { provideAuthApi() }
이건 좀 생각할 필요가 있는거 같아요

저도 배우는 입장이라서 뭐라 할 순 없지만 

다른 분들께 배운 바로는 지연 초기화는 라이플 싸이클상에 필요한 경우나 

다른 필요한 상황이 있을 경우에 사용하는 것이 좋다고 보여져서 해놓았습니다. 

멤버변수는 실제 레트로핏 사용되는 클래스에 있거나 

지연 초기화보다는 일반초기화가 낫지 않을까 싶어서 리뷰로 지정해놓았습니다.

레트로핏이 처음 할당되지 않고 나중에 할당되어야 할 필요가 없어 보여서 였습니다.

실제로 지연초기화는 일반 초기화보다 비용이 많이 든다고 들었습니다.

저도 정확히 알진 못하지만 이부분은 생각이 필요해 보입니다 ㅎ

2019-11-01 07:03 UTC, 2giwon commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/NewsFragment.kt
> +    private val api: SearchApi by lazy { provideAuthApi() }
이 부분은 석준님 리뷰를 받아야 알 것 같습니다.

2019-11-02 03:34 UTC, taeiim commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/MovieFragment.kt
> +                    setOnClickListener { startActivity(Intent(Intent.ACTION_VIEW, Uri.parse(movie.link))) }
제 IDE 설정을 `kotlin obsolete intelliJ IDEA codestyle` 로 해놨었네요 ㅜㅜ 
'Kotlin style guide' 로 변경한 다음 코드 전제 재정렬했습니다.
commit : c54c577bf034ab897c6aa329aea237e940ae0c1e

실제 현업에서도 kotlin style guide로 설정해서 사용하는 곳이 많은가 궁금하네요 !! 
저는 뭔가 `kotlin obsolete intelliJ IDEA codestyle` 요걸로 설정하는게 코드가 안 늘어져서 더 보기 좋은 느낌이라,, ㅜㅜ

2019-11-02 03:35 UTC, taeiim commented on taeiim/MyApplication/app/build.gradle
> +    implementation "androidx.recyclerview:recyclerview:$recyclerview_version"
다시 추가하였습니다! 

commit : b7fd2416b9286ecc6a123edcb75367d5ddf48bd6

2019-11-02 08:48 UTC, 2giwon submitted a review, later dismissed
LGTM 👍

2019-11-02 09:59 UTC, sjjeong requested changes
Fragment에 있는 리뷰 내용은 다른 Fragment에도 반영해주세요

2019-11-02 09:59 UTC, sjjeong commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/BlogFragment.kt
> +        fun setItems(items: ArrayList<SearchResult.Item>) {
items의 파라미터를 List<SearchResult.Item>으로 만드시면 전달할 때 타입캐스팅 하지 않아도 됩니다.

2019-11-02 09:59 UTC, sjjeong commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/BlogFragment.kt
> +                    titleTv.text = blog.title!!.fromHtml()
!!를 사용하면 앱이 죽을 수 있습니다.
fromHtml()를 String.fromHtml대신 String?.fromHtml로 하시고 내부적으로 null일 때 ""를 리턴하게 해보세요

2019-11-02 09:59 UTC, sjjeong commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/BlogFragment.kt
> +                    setOnClickListener {
onBindViewHolder에서는 불필요하게 여러번 set됩니다.
onClickListener를 set하는 과정은 onCreateViewHolder시점에 해주면 됩니다.

2019-11-02 09:59 UTC, sjjeong commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/NewsFragment.kt
> +    private val api: SearchApi by lazy { provideAuthApi() }
@2giwon @taeiim 
저는 괜찮다고 생각합니다.
그렇지만 기원님 말씀대로 지연초기화가 일반초기화보단 비용이 많이 들기 때문에 지연초기화가 꼭 필요하지 않는 곳이라면 일반초기화로 하는게 좋습니다.

2019-11-02 11:42 UTC, taeiim commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/BlogFragment.kt
> +        fun setItems(items: ArrayList<SearchResult.Item>) {
수정했습니다. 
commit : 8496d9690cbb187f8b3a03725be5f381f3b9732a

2019-11-02 11:43 UTC, taeiim commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/BlogFragment.kt
> +                    titleTv.text = blog.title!!.fromHtml()
수정했습니다~~

commit : f150036933af2df8bfa7ceb4fca11ec9b353ecd8

2019-11-02 11:43 UTC, taeiim commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/BlogFragment.kt
> +                    setOnClickListener {
수정했습니다

commit : 73a18a31cb1378e0d69f40849ca04a9344553a11

2019-11-02 12:06 UTC, sjjeong commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/BlogFragment.kt
> +                    titleTv.text = blog.title!!.fromHtml()
@taeiim 
String.kt에 있는 코드를 수정하라는 말이였어요~

2019-11-02 16:20 UTC, taeiim commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/BlogFragment.kt
> +                    titleTv.text = blog.title!!.fromHtml()
그렇군용 ㅎㅎ 다시 수정했습니다!

commit : 859329f2ce8dafbd6acdb58b7d59599e9829b296

2019-11-03 02:27 UTC, sjjeong approved these changes

2019-11-03 04:58 UTC, 2giwon approved these changes

2019-11-03 04:59 UTC, merged