Class05/developerkhm
sjjeong/GoogryAndroidArchitecutreStudy pull request #265
Opened 2019-10-30 09:01 UTC by developerkhm

1. 코틀린 처음이라 연습한다 생각하고 생각 나는되로 인터넷 찾아가며 코드 작성
2. 기능구현 위주로 디자인패턴이 아닌 클래스/코드 재사용 리팩토링 고려 안하고 작성
3. 구글에서 새로나온 NavagationUI 를 사용해서 4개의 탭을 구현했는데, 탭핑마다 리프레쉬를 피하고 싶으나 아직 시간이 없어서 방법을 못찾고 있음
4. 일부 소스는 시간이 없어서 일단 스터디 그룹원 중에 복붙 소스도 있음(노가다) 소스
5. 최대한 안드로이드스튜디오에서 제공하는 자동생성을 사용함 ex)액티비티 생성, 탭생성 etc

2019-10-31 09:38 UTC, buddman1208 requested changes
제 눈에 보이는 몇가지 피드백을 남겨보았어요! 보시고 피드백 부탁드려요 :)

2019-10-31 09:38 UTC, buddman1208 commented on developerkhm/AndroidStudy/app/src/main/java/com/example/androidstudy/adapter/AdapterBlog.kt
> +    private var itemList: ArrayList<Item>,
ArrayList 타입이 아닌 List 타입으로 받아도 괜찮을것 같아 보여요!

2019-10-31 09:38 UTC, buddman1208 commented on developerkhm/AndroidStudy/app/src/main/res/layout/item_blog_view.xml
> +        android:text="Title"
기본값이 아니라 에디터에서 임시로 확인하기 위해서라면 tools:text="Title"을 사용해도 괜찮을것 같아요!
android:text="Title"같이 실제 텍스트를 넣어놓는 경우 예외 상황이 생겼을때 테스트 데이터가 보여졌던 경험이 있네요

2019-10-31 09:38 UTC, buddman1208 commented on developerkhm/AndroidStudy/app/src/main/res/layout/item_blog_view.xml
> +        android:text="Content"
여기도 tools:text=""로 사용해도 괜찮을것 같아요!

2019-10-31 09:38 UTC, buddman1208 commented on developerkhm/AndroidStudy/app/src/main/java/com/example/androidstudy/ui/movie/MovieFragment.kt
> +        resultRecyclerView.adapter = AdapterBlog(context, arrayListOf(), "blog")
네곳에서 공통된 Adapter를 쓰고 있으니 이름이 추후 유지보수한다하면 혼동이 있을 수 있을것 같아요!

2019-10-31 09:38 UTC, buddman1208 commented on developerkhm/AndroidStudy/app/src/main/res/layout/layout_search_view.xml
> +        android:text="Search"
strings.xml을 참조하도록 하면 좋을것 같아요!

2019-10-31 09:38 UTC, buddman1208 commented on developerkhm/AndroidStudy/app/src/main/java/com/example/androidstudy/api/data/TotalModel.kt
> +data class Item(
모델 짤때 저는 이렇게 한번에 Item을 만들지 분기할지 고민하다 Common / Movie / Book으로 분기했는데요
어느쪽이 효율적일지 저는 피드백 받아보고 싶어요!

2019-11-01 00:52 UTC, developerkhm commented on developerkhm/AndroidStudy/app/src/main/res/layout/item_blog_view.xml
> +        android:text="Title"
수정했습니다. 

id : 1ee763d

2019-11-01 00:53 UTC, developerkhm commented on developerkhm/AndroidStudy/app/src/main/res/layout/item_blog_view.xml
> +        android:text="Content"
완료했습니다.~~

id : 3511adf

2019-11-01 00:53 UTC, developerkhm commented on developerkhm/AndroidStudy/app/src/main/java/com/example/androidstudy/ui/movie/MovieFragment.kt
> +        resultRecyclerView.adapter = AdapterBlog(context, arrayListOf(), "blog")
완료했습니다.~~

id : 9a71d6a

2019-11-01 00:54 UTC, developerkhm commented on developerkhm/AndroidStudy/app/src/main/res/layout/layout_search_view.xml
> +        android:text="Search"
수정했습니다.
id: 99c6ab3

2019-11-01 03:38 UTC, buddman1208 commented
LGTM!

2019-11-01 06:16 UTC, sjjeong commented on developerkhm/AndroidStudy/app/src/main/java/com/example/androidstudy/adapter/AdapterBlog.kt
> +    private var itemList: ArrayList<Item>,
저도 주로 List로 받는편인데 크게 중요하지 않는것 같아요

2019-11-01 06:17 UTC, sjjeong commented on developerkhm/AndroidStudy/app/src/main/java/com/example/androidstudy/api/data/TotalModel.kt
> +data class Item(
모델은 하나로 해도 되고 나눠도 되고 개인취향이라고 생각합니다.

2019-11-01 06:35 UTC, developerkhm commented on developerkhm/AndroidStudy/app/src/main/java/com/example/androidstudy/api/data/TotalModel.kt
> +data class Item(
저는 그냥 따로따로 만듭니다. 응답마다 대부분 api 끝에 주소로 파일명을 만듭니다.

2019-11-01 06:53 UTC, sjjeong requested changes
리뷰하다보니 과제가 아직 완성되지 않은 것 같습니다.
탭이 전부다 blog만 가져오고 있습니다.
@buddman1208 과제리뷰 다시 해주세요.

2019-11-01 06:53 UTC, sjjeong commented on developerkhm/AndroidStudy/app/src/main/java/com/example/androidstudy/ui/base/BaseFragment.kt
> +private const val ARG_PARAM1 = "param1"
자동으로 생성된 내용들은 제거 해주세요

2019-11-01 06:53 UTC, sjjeong commented on developerkhm/AndroidStudy/app/src/main/java/com/example/androidstudy/ui/blog/BlogFragment.kt
> +    override fun onCreateView(
BaseFragment로 옮겨서 처리 할 수 있습니다.

2019-11-01 06:57 UTC, buddman1208 commented
@sjjeong 앗..이름만 Blog로 처리되어 있고 제대로 받아오고 있는줄 알았는데 아니었군요 ㅠㅠ
조금 더 꼼꼼하게 보겠습니다

2019-11-02 13:59 UTC, buddman1208 requested changes
각 Fragment에서 BaseFragent.search()를 동일하게 호출하고 있는데 BaseFragment에서 무조건 typeArray의 0번째 인덱스를 가져와서 검색하고 있어서 타입별 검색이 제대로 되지 않고 있습니다!
수정 부탁드려요 @developerkhm

2019-11-02 13:59 UTC, buddman1208 commented on developerkhm/AndroidStudy/app/src/main/java/com/example/androidstudy/ui/base/BaseFragment.kt
> +            apiFetchData(searchEditText.text.toString(), typeArray[0], { response ->
@developerkhm BaseFragment에서 typeArray[0]으로 무조건 보내고 있어서 검색이 타입별로 되지 않고 있어요!

2019-11-03 02:01 UTC, developerkhm commented on developerkhm/AndroidStudy/app/src/main/java/com/example/androidstudy/ui/base/BaseFragment.kt
> +private const val ARG_PARAM1 = "param1"
수정 했습니다.

2019-11-03 02:01 UTC, developerkhm commented on developerkhm/AndroidStudy/app/src/main/java/com/example/androidstudy/ui/base/BaseFragment.kt
> +private const val ARG_PARAM1 = "param1"
수정했습니다.

id : b332b47

2019-11-03 02:02 UTC, developerkhm commented on developerkhm/AndroidStudy/app/src/main/java/com/example/androidstudy/ui/blog/BlogFragment.kt
> +    override fun onCreateView(
수정했습니다.

id : 06ac3c3

2019-11-03 02:03 UTC, developerkhm commented on developerkhm/AndroidStudy/app/src/main/java/com/example/androidstudy/ui/base/BaseFragment.kt
> +            apiFetchData(searchEditText.text.toString(), typeArray[0], { response ->
수정했습니다.

id : 68f4383

2019-11-03 03:33 UTC, sjjeong requested changes

2019-11-03 03:33 UTC, sjjeong commented on developerkhm/AndroidStudy/app/src/main/java/com/example/androidstudy/adapter/AdapterSearch.kt
> +        private val mItemType: String
코틀린에서는 m prefix를 사용하지 않습니다.

2019-11-03 03:33 UTC, sjjeong commented on developerkhm/AndroidStudy/app/src/main/java/com/example/androidstudy/adapter/AdapterSearch.kt
> +        itemList = list ?: arrayListOf()
itemList에 들어가는 객체를 변경하지마시고
clear() / addAll() 해주세요

2019-11-03 03:33 UTC, sjjeong commented on developerkhm/AndroidStudy/app/src/main/java/com/example/androidstudy/adapter/AdapterSearch.kt
> +        (itemList as? ArrayList)?.addAll(list ?: arrayListOf())
list가 null이면 addAll함수 자체를 호출하지 말아주세요

2019-11-03 03:33 UTC, sjjeong commented on developerkhm/AndroidStudy/app/src/main/java/com/example/androidstudy/api/service/APINaverService.kt
> +interface APINaverService {
ApiNaverService로 하셔야 합니다.

2019-11-03 03:33 UTC, sjjeong commented on developerkhm/AndroidStudy/app/src/main/java/com/example/androidstudy/ui/base/BaseFragment.kt
> +        if(this is BlogFragment){
이런 패턴이라면 Fragment가 추가 될 때 마다 BaseFragment를 수정해야합니다.
layout id를 전달받아서 처리하게 변경해주세요

2019-11-03 03:33 UTC, sjjeong commented on developerkhm/AndroidStudy/app/src/main/java/com/example/androidstudy/ui/base/BaseFragment.kt
> +        fun newInstance(param1: String, param2: String) =
자동생성된 부분 제거해주세요

2019-11-03 03:33 UTC, sjjeong commented on developerkhm/AndroidStudy/app/src/main/java/com/example/androidstudy/ui/blog/BlogFragment.kt
> +//    }
주석제거 해주세요

2019-11-03 03:33 UTC, sjjeong commented on developerkhm/AndroidStudy/app/src/main/java/com/example/androidstudy/ui/book/BookFragment.kt
> +        resultRecyclerView.adapter = AdapterSearch(context, arrayListOf(), "blog")
BookFragment인데 "blog"를 사용하고 있습니다.
다른 Fragment도 확인해주세요

2019-11-03 03:46 UTC, buddman1208 commented on developerkhm/AndroidStudy/app/src/main/java/com/example/androidstudy/ui/base/BaseFragment.kt
> +            apiFetchData(searchEditText.text.toString(), typeArray[0], { response ->
확인했습니다!

2019-11-03 06:59 UTC, buddman1208 submitted a review, later dismissed
확인했습니다!

2019-11-03 07:03 UTC, sjjeong requested changes

2019-11-03 07:03 UTC, sjjeong commented on developerkhm/AndroidStudy/app/src/main/java/com/example/androidstudy/ui/movie/MovieFragment.kt
> +        resultRecyclerView.adapter = AdapterSearch(context, arrayListOf(), "blog")
```suggestion
        resultRecyclerView.adapter = AdapterSearch(context, arrayListOf(), "movie")
```

2019-11-03 07:05 UTC, sjjeong commented on developerkhm/AndroidStudy/app/src/main/java/com/example/androidstudy/ui/movie/MovieFragment.kt
> +        resultRecyclerView.adapter = AdapterSearch(context, arrayListOf(), "blog")
29eee66

2019-11-04 09:59 UTC, developerkhm commented on developerkhm/AndroidStudy/app/src/main/java/com/example/androidstudy/adapter/AdapterSearch.kt
> +        private val mItemType: String
수정했습니다.

id : ac8a6118

2019-11-04 10:00 UTC, developerkhm commented on developerkhm/AndroidStudy/app/src/main/java/com/example/androidstudy/adapter/AdapterSearch.kt
> +        itemList = list ?: arrayListOf()
수정했습니다.

id : 0b04fc8

2019-11-04 10:00 UTC, developerkhm commented on developerkhm/AndroidStudy/app/src/main/java/com/example/androidstudy/adapter/AdapterSearch.kt
> +        (itemList as? ArrayList)?.addAll(list ?: arrayListOf())
수정했습니다.

id : 0b04fc8

2019-11-04 10:01 UTC, developerkhm commented on developerkhm/AndroidStudy/app/src/main/java/com/example/androidstudy/adapter/AdapterSearch.kt
> +        (itemList as? ArrayList)?.addAll(list ?: arrayListOf())
아 확인못하고 처리 못했습니다. 2주차 과제 이어가면서 수정해 놓겠습니다.

2019-11-04 10:01 UTC, developerkhm commented on developerkhm/AndroidStudy/app/src/main/java/com/example/androidstudy/api/service/APINaverService.kt
> +interface APINaverService {
수정했습니다.

id : ac8a611

2019-11-04 10:02 UTC, developerkhm commented on developerkhm/AndroidStudy/app/src/main/java/com/example/androidstudy/ui/base/BaseFragment.kt
> +        if(this is BlogFragment){
수정했습니다.
레이아웃 id를 주는 방식으로 했는데?  더 좋은 방법이 있을까요..?
id : e15d018

2019-11-04 10:02 UTC, developerkhm commented on developerkhm/AndroidStudy/app/src/main/java/com/example/androidstudy/ui/base/BaseFragment.kt
> +        fun newInstance(param1: String, param2: String) =
수정했습니다.

id : 59a96ad

2019-11-04 10:02 UTC, developerkhm commented on developerkhm/AndroidStudy/app/src/main/java/com/example/androidstudy/ui/blog/BlogFragment.kt
> +//    }
수정했습니다.

2019-11-04 10:03 UTC, developerkhm commented on developerkhm/AndroidStudy/app/src/main/java/com/example/androidstudy/ui/book/BookFragment.kt
> +        resultRecyclerView.adapter = AdapterSearch(context, arrayListOf(), "blog")
수정했습니다.
id : 5282e04

2019-11-04 11:10 UTC, sjjeong commented on developerkhm/AndroidStudy/app/src/main/java/com/example/androidstudy/adapter/AdapterSearch.kt
> +        private val mItemType: String
@developerkhm 커밋 id가 잘못된거 같습니다.

2019-11-04 11:11 UTC, sjjeong commented on developerkhm/AndroidStudy/app/src/main/java/com/example/androidstudy/ui/base/BaseFragment.kt
> +        if(this is BlogFragment){
java 였을 때는 주로 abstract function을 많이 이용했었지만
kotlin에서는 생성자로 전달해주기도 합니다.

2019-11-04 11:13 UTC, sjjeong requested changes
4f2f276
내용을 확인했지만 커밋메시지와 다른 작업 내용이였습니다.
프로젝트 전체적으로 m을 prefix를 붙이는 부분을 모두 수정해주세요

2019-11-04 13:08 UTC, developerkhm commented on developerkhm/AndroidStudy/app/src/main/java/com/example/androidstudy/ui/base/BaseFragment.kt
> +        if(this is BlogFragment){
생성자 방식으로 수정했습니다.

id : 3d216d8

2019-11-04 13:09 UTC, developerkhm commented on developerkhm/AndroidStudy/app/src/main/java/com/example/androidstudy/adapter/AdapterSearch.kt
> +        (itemList as? ArrayList)?.addAll(list ?: arrayListOf())
수정 했습니다.

id : 0df925a

2019-11-04 13:09 UTC, developerkhm commented on developerkhm/AndroidStudy/app/src/main/java/com/example/androidstudy/adapter/AdapterSearch.kt
> +        private val mItemType: String
다시 했습니다.~

id : 8d943ea

2019-11-04 13:13 UTC, developerkhm commented
다시 수정했습니다.~~

2019-11-04 15:29 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-11-04 15:30 UTC, sjjeong commented
@buddman1208 
변경사항 확인해주시고 approve 해주세요

2019-11-05 02:52 UTC, buddman1208 approved these changes
확인했습니다!

2019-11-05 04:42 UTC, merged