HW-1 샘플 프로젝트 제작
sjjeong/GoogryAndroidArchitecutreStudy pull request #266
Opened 2019-10-31 03:31 UTC by buddman1208

@developerkhm 학명님 리뷰 부탁드리겠습니다~

네트워크 Call 리턴방식을 RxJava2로 해두었는데, 추후에 스트림처리할 일이 있지 혹여나 있을까 해서 일단 그렇게 해두었습니다.
제가 보이는건 하드코딩이나 Lint 표시되는 항목 등 고쳐야 할 사항들을 적어두었는데, 더 있을것 같네요 ㅠㅠ 코멘트 부탁드리겠습니다.

2019-10-31 07:33 UTC, developerkhm reviewed
확인해주세요.

2019-10-31 07:33 UTC, developerkhm commented on buddman1208/ArchitectureStudy/app/src/main/res/values/strings.xml
>      <string name="book">도서</string>
해당 string 값이 어디에 사용하는건지 구분이 있었으면 더 좋을 것 같습니다.
ex) tab_book

2019-10-31 07:33 UTC, developerkhm commented on buddman1208/ArchitectureStudy/app/src/main/res/layout/content_movie_item.xml
> -        android:layout_width="wrap_content"
max 3줄 이상 넘었을때 텍스트 줄임 표시를 어떻게 설정할건지 설정값이 있으면 좋을 것 샅습니다.

2019-10-31 09:50 UTC, buddman1208 commented on buddman1208/ArchitectureStudy/app/src/main/res/values/strings.xml
>      <string name="book">도서</string>
b12bf5d 커밋에서 앞에 menu_를 붙여서 수정했습니다!

2019-10-31 09:50 UTC, buddman1208 commented on buddman1208/ArchitectureStudy/app/src/main/res/layout/content_movie_item.xml
> -        android:layout_width="wrap_content"
3da2d66 커밋에서 text ellipsize 처리했습니다!

2019-11-01 06:57 UTC, sjjeong commented
@buddman1208 
사전과제 먼저 pr 만들어서 처리하는거 해주세요

2019-11-01 09:08 UTC, sjjeong requested changes
if else 부분 전부 컨벤션에 맞게 수정해주세요
https://developer.android.com/kotlin/style-guide#braces

2019-11-01 09:08 UTC, sjjeong commented on buddman1208/ArchitectureStudy/app/build.gradle
> +    implementation 'com.android.support:design:28.0.0'
더이상 사용하면 안되는 dependency입니다.
![image](https://user-images.githubusercontent.com/4777586/68012000-2f622580-fccc-11e9-8096-1d23342d13b5.png)
https://mvnrepository.com/artifact/com.google.android.material/material 이걸 사용해주세요

2019-11-01 09:08 UTC, sjjeong commented on buddman1208/ArchitectureStudy/app/src/main/java/com/buddman1208/architecturestudy/MainActivity.kt
> +                                when (currentMode) {
else에 포함된 부분인가요? 아닌가요?
{}은 없는데 정렬이 이상합니다.
확인해주세요

2019-11-01 09:08 UTC, sjjeong commented on buddman1208/ArchitectureStudy/app/src/main/java/com/buddman1208/architecturestudy/MainActivity.kt
> +    private fun updateToolbarTitle() {
currentMode에 Delegate.observable을 delegate해보면 어떨까요

2019-11-01 09:08 UTC, sjjeong commented on buddman1208/ArchitectureStudy/app/src/main/java/com/buddman1208/architecturestudy/utils/Constants.kt
> +    const val API_KEY_SERECT = "O5ATnchoCc"
오타있습니다.

2019-11-01 09:08 UTC, sjjeong commented on buddman1208/ArchitectureStudy/app/src/main/java/com/buddman1208/architecturestudy/utils/NetworkServiceGenerator.kt
> +            interceptor.level = HttpLoggingInterceptor.Level.BODY
Debug일때만 Level.BODY를 셋하게 변경해주세요

2019-11-01 09:08 UTC, sjjeong commented on buddman1208/ArchitectureStudy/app/src/main/java/com/buddman1208/architecturestudy/MainActivity.kt
> +                        200 -> {
응답을 Observable<Response<CommonResponse>>가 아닌 Observable<CommonResponse>로 받으면 성공일때만 onNext를 탑니다.

2019-11-01 09:08 UTC, sjjeong commented on buddman1208/ArchitectureStudy/app/src/main/java/com/buddman1208/architecturestudy/utils/NetworkAPI.kt
> +interface NetworkAPI {
NetworkApi로 변경해주세요

2019-11-01 09:08 UTC, sjjeong commented on buddman1208/ArchitectureStudy/app/src/main/java/com/buddman1208/architecturestudy/utils/NetworkAPI.kt
> +    ): Observable<Response<CommonResponse>>
Observable대신 Single을 사용해주세요

2019-11-01 09:08 UTC, sjjeong commented on buddman1208/ArchitectureStudy/app/src/main/java/com/buddman1208/architecturestudy/utils/Extensions.kt
> +fun String.removeHtmlTags(): String {
removeHtmlBoldTags 정도면 될 것 같습니다.

2019-11-02 13:38 UTC, buddman1208 commented on buddman1208/ArchitectureStudy/app/src/main/java/com/buddman1208/architecturestudy/MainActivity.kt
> +                        200 -> {
이미 Observable<Response<>> 형태로 리턴받고 있는 것으로 확인됩니다!

2019-11-02 13:51 UTC, buddman1208 commented on buddman1208/ArchitectureStudy/app/src/main/java/com/buddman1208/architecturestudy/MainActivity.kt
> +    private fun updateToolbarTitle() {
수정했습니다! 커밋 520303b4954cb23c7681066c2da12c8c4b87e8e4

2019-11-02 13:52 UTC, buddman1208 commented on buddman1208/ArchitectureStudy/app/src/main/java/com/buddman1208/architecturestudy/utils/Extensions.kt
> +fun String.removeHtmlTags(): String {
수정했습니다! 커밋 37633a9a20e869ce148ea81b3cf62cc9b27f8fc2

2019-11-02 13:52 UTC, buddman1208 commented on buddman1208/ArchitectureStudy/app/src/main/java/com/buddman1208/architecturestudy/utils/NetworkAPI.kt
> +    ): Observable<Response<CommonResponse>>
수정했습니다! 커밋 5acf3d741119603aa48460b0b4c8f56cc2db2002

2019-11-02 13:53 UTC, buddman1208 commented on buddman1208/ArchitectureStudy/app/src/main/java/com/buddman1208/architecturestudy/utils/NetworkAPI.kt
> +interface NetworkAPI {
수정했습니다! 커밋 d3de28030b7ae496446b30d24429fcc038eeac0d

2019-11-02 13:53 UTC, buddman1208 commented on buddman1208/ArchitectureStudy/app/src/main/java/com/buddman1208/architecturestudy/MainActivity.kt
> +                        200 -> {
피드백 주신대로 Observable -> Single로 변경된 상태입니다

2019-11-02 13:53 UTC, buddman1208 commented on buddman1208/ArchitectureStudy/app/src/main/java/com/buddman1208/architecturestudy/utils/NetworkServiceGenerator.kt
> +            interceptor.level = HttpLoggingInterceptor.Level.BODY
수정했습니다! 커밋 5b9ab9209a578cd981f68489630aa77acb81cb1f

2019-11-02 13:53 UTC, buddman1208 commented on buddman1208/ArchitectureStudy/app/src/main/java/com/buddman1208/architecturestudy/utils/Constants.kt
> +    const val API_KEY_SERECT = "O5ATnchoCc"
수정했습니다! 커밋 383ef75f810dee313c94b81af670958dad907e89

2019-11-02 13:53 UTC, buddman1208 commented on buddman1208/ArchitectureStudy/app/src/main/java/com/buddman1208/architecturestudy/MainActivity.kt
> +                                when (currentMode) {
수정했습니다! 커밋 7035de35ab27a19db7c4ee709eb3987156b4c59d

2019-11-02 13:53 UTC, buddman1208 commented on buddman1208/ArchitectureStudy/app/build.gradle
> +    implementation 'com.android.support:design:28.0.0'
수정했습니다! 커밋 af24f37fc05a4f4283516468351ce4b32bf426f2

2019-11-02 13:54 UTC, buddman1208 commented
피드백 주신대로 수정 완료했습니다~

2019-11-03 02:46 UTC, sjjeong commented on buddman1208/ArchitectureStudy/app/src/main/java/com/buddman1208/architecturestudy/MainActivity.kt
> +                        200 -> {
@buddman1208
Response 클래스 안에서 사용하는게 it.code()로 200 검사하는 것 뿐이기 때문에 Response를 사용하지 않아도 된다는 이야기였습니다.

2019-11-03 03:43 UTC, buddman1208 commented on buddman1208/ArchitectureStudy/app/src/main/java/com/buddman1208/architecturestudy/MainActivity.kt
> +                        200 -> {
그렇군요!
수정했습니다! 커밋 80c438240ece5f22c84021bc5c4e924d88d22402 39da53080f23e8caa059cef6cb7ad18c945bee91

2019-11-03 03:59 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-11-03 06:59 UTC, developerkhm approved these changes
확인했습니다.

2019-11-03 07:00 UTC, merged