HW-2-Model 적용을 위한 View에서 Remote 호출방식을 분리하여 repository와 source 추가
sjjeong/GoogryAndroidArchitecutreStudy pull request #269
Opened 2019-11-03 15:11 UTC by ironelder

HW-2-Model 적용을 위한 View에서 Remote 호출방식을 분리하여 repository와 source 추가

2019-11-04 14:33 UTC, bean628 reviewed
저는 아직 모델 계층 작업을 완료하지 못해서 일단 보이는건 이거 두개밖에 안보이네요!! ㅋㅋ

2019-11-04 14:33 UTC, bean628 commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/component/MainFragment.kt
> +            .show()
제가 조금이라도 써본 통신라이브러리는 Volly랑 Retrofit 밖에 없는데 
Volly가 지금 처럼 onSuccess 콜백이랑 onFail 콜백이 따로 되어있는 형식이고
Retrofit은 callBack안에 onSuccess 콜백이랑 onFail 콜백이 한 묶음으로 되있는 형식이더라구요.

Retrofit 라이브러리를 사용중이시니 repository 콜백도 한 묶음으로 형식을 통일하는건 어떨까요?

2019-11-04 14:33 UTC, bean628 commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/data/repository/SearchDataRepoImpl.kt
> +class SearchDataRepoImpl:ISearchDataRepo<TotalModel> {
스터디시간에 repository는 싱글톤으로 구현하기로 했었던것 같아요!
google sample에도 repository는 싱글톤으로 구현되어있어요

2019-11-04 23:58 UTC, ironelder commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/component/MainFragment.kt
> +            .show()
@bean628 
음... 어떤 방식을 말씀하지는지 잘 모르겠습니다 ㅠㅠ
retrofit callback을 봤는데...
인터페이스로 내부에는 똑같이 success와 onfail이 있는데용..
'''public interface Callback<T> {
  void onResponse(Call<T> call, Response<T> response);
  void onFailure(Call<T> call, Throwable t);
}
'''
인터페이스를 하나 더 추가하면 될지... 아니면, 던지는 함수가 하나에서 response.isSuccess로 분기해서 함수에서 파라미터로 나눠서 하면될지 잘 모르겠습니다 ㅠㅠ

2019-11-05 00:19 UTC, ironelder commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/data/repository/SearchDataRepoImpl.kt
> +class SearchDataRepoImpl:ISearchDataRepo<TotalModel> {
싱글톤 방식으로 수정하였습니다~
b9ba83e

2019-11-05 13:21 UTC, bean628 commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/component/MainFragment.kt
> +            .show()
헙 음 다시보니 제가 잘못생각했던거 같아요 callback 자체를 부를수 있다고 생각했었는데 생각해보니 그러면 통신을 액티비티에서 하는거랑 다른게 없는거군요 ㅋㅋ 하핫..

2019-11-05 13:35 UTC, bean628 commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/component/MainFragment.kt
> +            .show()
아 음.. 아닌가 가능한가... 음 그러니까 제가 원했던 형태는
```
SearchDataSrcImpl.getDataForSearch(mType ?: BLOG, query, callback: Callback<TotalModel> )
```
약간 이런 형태랄까요 음~~~ 저도 작업을 해봐야알것 같아요

2019-11-05 14:25 UTC, ironelder commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/component/MainFragment.kt
> +            .show()
이런 형식을 원하시는게 맞나용?
c9fa0a8

그런데 저렇게 하면 기존의 callBack을 감싸는 형태로 밖에 안나오고
오히려 제네릭을 제거하면서 
해당 callback의 경우에는 오로지 totalModel에만 사용할 수 있어서 재사용성이 떨어지는 것 같아서요..

2019-11-05 15:04 UTC, bean628 commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/component/MainFragment.kt
> +            .show()
죄송해요 제가 설명을 잘 못하는게 문제인거 같아요 ㅠㅠ
제네릭은 진혁님이 원하시는대로 하셔도될것 같아요! 엄.. 그러니까 제가 전달하고싶었던건...
현재 구현된 모습은
```
 SearchDataSrcImpl.getDataForSearch(mType ?: BLOG, query, ::onSuccess, ::onFail)
``` 
이렇게 함수를 호출할 때 인자가 mType , query, success, fail  총 4개가 되는거잖아요?
근데 success랑 fail을 callback 인자 하나로 받이서 mType , query, callBack 이렇게 총 3개가 되게 만들고 callBack 안에 success랑 fail을 묶어서 처리하는 형태를 말했던거였어요

2019-11-05 15:06 UTC, bean628 commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/component/MainFragment.kt
> +            .show()
네네 맞아요

2019-11-05 15:54 UTC, sjjeong requested changes
전체적으로 변경해주셔야 할 것이 있습니다.
1. interface에 prefix로 I를 붙이는건 좋지 않습니다.
2. class이름을 지을때 약어를 사용하지 않고 풀네임으로 적어주는게 좋습니다.
3. 코드 정렬 해주세요(reformat code)

2019-11-05 15:54 UTC, sjjeong commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/component/MainFragment.kt
> +        (rv_resultListView?.adapter as CustomListViewAdapter).setItemList(result.items)
as대신 as?를 사용하는게 좋습니다.

2019-11-05 15:54 UTC, sjjeong commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/data/repository/ISearchDataRepo.kt
> +interface ISearchDataRepo<T> {
제네릭 T를 넣을 필요가 없을 것 같습니다.

2019-11-05 15:54 UTC, sjjeong commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/data/source/ISearchDataSrc.kt
> +interface ISearchDataSrc<T, R> {
제네릭이 필요 없습니다.

2019-11-05 23:50 UTC, ironelder commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/data/repository/ISearchDataRepo.kt
> +interface ISearchDataRepo<T> {
제네릭을 사용하도록 다른곳을 변경해보았습니다
d691eb9

2019-11-05 23:51 UTC, ironelder commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/data/source/ISearchDataSrc.kt
> +interface ISearchDataSrc<T, R> {
기존의 제네릭을 통해서 사용하고 있었는데. 테스트로 인터페이스를 넣었었다가 다시 원복했습니다
제네릭이 아닌 그냥 모델클래스와 스트링을 넣어주는것이 더 좋은지 잘 모르겠습니다
d691eb9

2019-11-05 23:57 UTC, ironelder commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/component/MainFragment.kt
> +        (rv_resultListView?.adapter as CustomListViewAdapter).setItemList(result.items)
코드 정렬 및 as?를 사용하도록 수정하였습니다.
32b4581

interface에 앞쪽에 prefix를 제거하였습니다
f1ad171

2019-11-06 14:53 UTC, sjjeong commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/data/source/ISearchDataSrc.kt
> +interface ISearchDataSrc<T, R> {
제네릭 제거 관련 커밋이 아닌거 같습니다.

2019-11-06 14:54 UTC, sjjeong commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/data/source/ISearchDataSrc.kt
> +interface ISearchDataSrc<T, R> {
제네릭이 왜 필요하다고 생각하셨나요?

2019-11-07 00:02 UTC, ironelder commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/data/source/ISearchDataSrc.kt
> +interface ISearchDataSrc<T, R> {
지금은 모델이 하나 밖에 없지만 만약 모델이 블로그, 뉴스, 책, 영화 네가지로 분류 되었을 경우에 똑같은 함수를 또 만들지 않기 위하여 필요하다고 생각되었습니다

2019-11-07 03:02 UTC, sjjeong commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/data/source/ISearchDataSrc.kt
> +interface ISearchDataSrc<T, R> {
그럼 만약에 블로그, 뉴스, 책, 영화 네가지로 모델이 분류 됐을 때 저 DataSource가 싱글톤으로 유지될 수 있나요?

2019-11-07 04:53 UTC, ironelder commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/data/source/ISearchDataSrc.kt
> +interface ISearchDataSrc<T, R> {
아, 그건 생각 못했었네요 ㅠㅠ
제네릭을 제거하고 타입을 명시하였습니다

c134431

2019-11-07 04:53 UTC, ironelder commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/data/repository/ISearchDataRepo.kt
> +interface ISearchDataRepo<T> {
제네릭을 제거하였습니다~
c134431

2019-11-07 06:57 UTC, sjjeong approved these changes

2019-11-08 03:14 UTC, bean628 approved these changes

2019-11-08 04:09 UTC, merged