WIP : HW-2 MVP
sjjeong/GoogryAndroidArchitecutreStudy pull request #27
Opened 2019-05-08 15:54 UTC by Hoyuo

2주차 작업 MVP 변환

2019-05-09 15:38 UTC, namjackson requested changes
아직 MVP로 로직이 분리되지않은거같아요!

2019-05-09 15:38 UTC, namjackson commented on hoyuo/MyApplication/app/src/main/java/me/hoyuo/myapplication/util/ContextHelper.kt
> +        get() = if (weakReference?.get() != null) {
weakReference변수를  nullable로 선언하지 않아도, lazy등을 활용하면 
nonNull변수로 사용하는것도 좋지않을까요?

또 변수의 !=null check보단 safeCall(.?)하면 코드를 더 짧게 만들수도 있을거같아요

2019-05-10 16:48 UTC, Hoyuo commented on hoyuo/MyApplication/app/src/main/java/me/hoyuo/myapplication/util/ContextHelper.kt
> +        get() = if (weakReference?.get() != null) {
`(weakReference?.get() != null)` 이 부분에 대한 경우
 `weakReference`가 null 인 경우와 `weakReference.get()` 값이 null 경우 둘 다 체크 하기 위해서 이렇게 표현 하였습니다.

좀 더 개선된 방법을 생각 중 입니다

2019-05-11 10:28 UTC, namjackson approved these changes
수고하셨습니다!

2019-05-11 10:28 UTC, namjackson commented on hoyuo/MyApplication/app/src/main/java/me/hoyuo/myapplication/ui/coinlist/CoinListPresenter.kt
> +    override fun onItemClick(ticker: Ticker) {
단순 상세페이지 이동이라면 Presenter에 거치지 않아도 되지않은거같아요
추후 클릭했을때, 기능 추가를 고려하셔서 만들어놓으신건가요?

2019-05-12 15:16 UTC, sjjeong approved these changes
다음주 스터디 시간에 다시 리뷰할게요.

2019-05-15 15:48 UTC, merged