HW-1 Model 과제
sjjeong/GoogryAndroidArchitecutreStudy pull request #271
Opened 2019-11-04 12:34 UTC by taeiim

2019-11-04 14:48 UTC, 2giwon requested changes

2019-11-04 14:48 UTC, 2giwon commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/BlogFragment.kt
> +        adapter.setItems(resultList.items)
clearItem이 없어서 동일한 쿼리를 계속 실행하면

리스트에 계속 add가 되고 있습니다

2019-11-04 15:02 UTC, 2giwon requested changes

2019-11-04 15:02 UTC, 2giwon commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/data/NaverRepository.kt
> +interface NaverRepository {
NaverRemoteDataSource 와 구조가 동일해 보이는데

같은 인터페이스를 쓰신 이유가 있나요?

2019-11-05 14:48 UTC, taeiim commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/BlogFragment.kt
> +        adapter.setItems(resultList.items)
수정했습니다! 

commit : 2fb105592644ef115417e635ab5bb64f0f3abf4f

2019-11-05 14:50 UTC, taeiim commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/data/NaverRepository.kt
> +interface NaverRepository {
추후에 Repository에서 다른 역할이 추가되면 달라질 수 있다고 생각해서 분리하였습니다!

2019-11-05 15:00 UTC, 2giwon commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/data/NaverRepository.kt
> +interface NaverRepository {
다른 역할이라는 것은  어떤 뜻인가요? remote data source 외에 local data source(로컬 캐시, db)같은 기능을 말씀하시는 건가요? 

만약 그런 이유라면 Repository가 클래스로 두고 그런 datasource를 멤버 변수로 갖고 있어도 되지 않나요?

아니면 Repository interface에 2가지 메소드를 두는 건가요?

2019-11-05 15:01 UTC, 2giwon commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/data/NaverRepository.kt
> +interface NaverRepository {
절대 따지는 것은 아닙니다. 글로 쓰니 오해를 불러일으킬 수 있어서 ㅋㅋ

궁금해서 그럽니다. 제가 알고 있는 것이 맞는 건지 궁금해서 ㅋ

2019-11-07 18:44 UTC, taeiim commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/data/NaverRepository.kt
> +interface NaverRepository {
따로 만들었던 repository interface 제거하고 data source 같이 사용하는 것으로 변경했습니다 ㅎㅎ
리뷰 감사합니다 ! 

commit : d31e94ace91189611fa27bcfa7982ad3e5591c56

2019-11-08 01:07 UTC, 2giwon submitted a review, later dismissed
LGTM 👍

2019-11-08 09:29 UTC, BeokBeok requested changes
안녕하세요, 스터디 2기 강현석이라고 합니다.
부족하지만 잘 부탁드립니다. 😅

2019-11-08 09:29 UTC, BeokBeok commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/data/source/NaverRemoteDataSourceImpl.kt
> +                    response.body()?.let { result -> success(result) } ?: fail(Throwable())
immutable 은 let 보다는 if 문으로 null check 하시면 좋을 것 같아요.
또한, Throwable 을 던지기보다는 IllegalStateException 혹은 IllegalArgumentException 을 던지시고
파라미터에 어떤 예외인지 알 수 있도록 파라미터에 값을 전달하시면 좋을 것 같아요.

2019-11-08 09:29 UTC, BeokBeok commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/BookFragment.kt
> +    private fun successGetSearchResult(resultList: SearchResult) {
함수명은 동사구로 작성하시면 좋을 것 같아요.

2019-11-08 09:29 UTC, BeokBeok commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/BookFragment.kt
> +    private fun errorGetSearchResult() {
함수명은 동사구로 작성하시면 좋을 것 같아요.

2019-11-08 09:29 UTC, BeokBeok commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/NewsFragment.kt
>      private inner class NewsAdapter : RecyclerView.Adapter<NewsListHolder>() {
Fragment 와 Adapter 코드가 중복이 많은 것 같습니다.
Fragment 와 Adapter 를 하나만 만드신 후, 파라미터를 통하여 객체들을 구별하여 처리하시면 좋을 것 같아요.

2019-11-09 15:45 UTC, taeiim commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/data/source/NaverRemoteDataSourceImpl.kt
> +                    response.body()?.let { result -> success(result) } ?: fail(Throwable())
감사합니다 ! 수정했습니다 ㅎㅎ 

commit : fbc32b6a5a5512aabdf7f58e5be816bc3da51fd2, adda933b462fbe2fefb83a0292903e91cf268938

2019-11-09 15:46 UTC, taeiim commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/BookFragment.kt
> +    private fun successGetSearchResult(resultList: SearchResult) {
refreshList로 수정했는데 괜찮을까요? ㅜㅜ 
네이밍은 항상 어렵네요😭  혹시 의견 있으시면 또 주세요 ! ㅎㅎ 감사합니다

commit : 048a0c255a8b0dc1d7730ad24aa79cee0f4d22c1

2019-11-09 15:48 UTC, taeiim commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/BookFragment.kt
> +    private fun errorGetSearchResult() {
일단 clearItems() 로 변경했는데, 
이 함수에서 list를 clear 해주는 역할뿐만 아니라 실패 토스트도 보여주는 역할을 하는데
혹시 더 좋은 네이밍 있을까요!! 

commit : 048a0c255a8b0dc1d7730ad24aa79cee0f4d22c1

2019-11-09 15:50 UTC, taeiim commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/NewsFragment.kt
>      private inner class NewsAdapter : RecyclerView.Adapter<NewsListHolder>() {
수정했습니다.
다른 노트북 두개로 작업해서 커밋을 깔끔히 나누지 못했습니다ㅜㅜ 양해부탁드려요 !! 

commit : 77f303626ab7d7646cbf93a6470d183df9f885ab, 
384a8590293cafaa08b0654318edb3e520e828a2, 048a0c255a8b0dc1d7730ad24aa79cee0f4d22c1

2019-11-09 23:23 UTC, BeokBeok commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/BookFragment.kt
> +    private fun errorGetSearchResult() {
clearItems 도 괜찮은 것 같습니다.
하지만, 실패 토스트를 보여주는 동작까지 담기에는 살짝 아쉬운 것 같습니다.

개인적인 생각이지만, `failToSearch` 는 어떠신지 제안드리며
또한, 함수로 추출하지 않으셔도 괜찮을 것 같습니다.
```
fail = {
    adapter.clearItems()
    Toast.makeText(context, getString(R.string.err_search), Toast.LENGTH_SHORT).show()
}
```

2019-11-09 23:23 UTC, BeokBeok commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/BookFragment.kt
> +    private fun successGetSearchResult(resultList: SearchResult) {
괜찮은 것 같습니다. 😄

2019-11-09 23:44 UTC, BeokBeok commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/ContentsFragment.kt
> +            layoutManager = LinearLayoutManager(context)
xml 에서도 처리가 가능해요.

2019-11-09 23:44 UTC, BeokBeok commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/ContentsFragment.kt
> +        return inflater.inflate(R.layout.fragment_main, container, false)
`=` 을 사용하시면, 중괄호를 정리할 수 있어요.

2019-11-09 23:44 UTC, BeokBeok commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/ContentsFragment.kt
> +    private var searchType = ""
searchType 변수는 멤버로 만들지 않으셔도 될 것 같아요.

2019-11-09 23:44 UTC, BeokBeok commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/ContentsFragment.kt
> +            searchEditTv.text.toString()?.let { searchBlog(it) }
`?` 는 없어도 될 것 같아요.

2019-11-09 23:44 UTC, BeokBeok commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/SearchResultRecyclerAdapter.kt
> +        return resultList.size
`=` 을 사용하시면, 중괄호를 정리할 수 있어요.

2019-11-09 23:44 UTC, BeokBeok commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/SearchResultRecyclerAdapter.kt
> +    private var resultList = ArrayList<SearchResult.Item>()
val 로 변경해주시는 것이 좋을 것 같습니다.
또한, ArrayList 보다는 List 가 좋을 것 같아요.

2019-11-09 23:44 UTC, BeokBeok commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/SearchResultRecyclerAdapter.kt
> +            }
when 을 하나로 합치면 좋을 것 같아요.

2019-11-10 08:17 UTC, taeiim commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/BookFragment.kt
> +    private fun errorGetSearchResult() {
failToSearch() 로 변경하였습니다. 

commit : 66b417701029717b26e1b243c126493e705fbde9

2019-11-10 08:17 UTC, taeiim commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/ContentsFragment.kt
> +            layoutManager = LinearLayoutManager(context)
오호 꿀팁 감사합니다 ~~~

commit : 66b417701029717b26e1b243c126493e705fbde9

2019-11-10 08:17 UTC, taeiim commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/ContentsFragment.kt
> +        return inflater.inflate(R.layout.fragment_main, container, false)
수정했습니다 ~~

commit : 66b417701029717b26e1b243c126493e705fbde9

2019-11-10 08:20 UTC, taeiim commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/ContentsFragment.kt
> +    private var searchType = ""
음.. searchType 변수를 사용하는 곳이 2-3군데 있어서 변수로 만들었습니다 ㅜㅜ 
근데 코드를 보다보니 searchType으로 넣어줘야 되는데 바로 처리한게 있어서 그 부분만 searchType으로 대치하였습니다 ~~ 

commit : 66b417701029717b26e1b243c126493e705fbde9

2019-11-10 08:20 UTC, taeiim commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/ContentsFragment.kt
> +            searchEditTv.text.toString()?.let { searchBlog(it) }
수정했습니다 감사합니다 !

commit : 66b417701029717b26e1b243c126493e705fbde9

2019-11-10 08:20 UTC, taeiim commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/SearchResultRecyclerAdapter.kt
> +        return resultList.size
commit : 66b417701029717b26e1b243c126493e705fbde9

2019-11-10 08:21 UTC, taeiim commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/SearchResultRecyclerAdapter.kt
> +    private var resultList = ArrayList<SearchResult.Item>()
List로 변경하면 밑에 arraylist.clear() 등을 사용하지 못해서 
List대신 mutableListOf 로 변경하였습니다 ~~

commit : 66b417701029717b26e1b243c126493e705fbde9

2019-11-10 08:22 UTC, taeiim commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/SearchResultRecyclerAdapter.kt
> +            }
함수로 빼서 호출하는 방식으로 변경했습니다 ~~~~ 리뷰 감사합니다 !! 

commit : 66b417701029717b26e1b243c126493e705fbde9

2019-11-10 09:12 UTC, sjjeong requested changes

2019-11-10 09:12 UTC, sjjeong commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/Tabs.kt
> +fun getSearchType(tab: Tabs) =
Tabs에 property를 추가해주시면 됩니다.

2019-11-10 09:12 UTC, sjjeong commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/ContentsFragment.kt
> +            searchEditTv.text.toString().let { searchBlog(it) }
searchBlog(searchEditTv.text.toString())

2019-11-10 09:12 UTC, sjjeong commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/ContentsFragment.kt
> +        private const val ARG_TYPE = ""
이거는 왜 값이 비어있나요?

2019-11-11 16:02 UTC, taeiim commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/Tabs.kt
> +fun getSearchType(tab: Tabs) =
반영했습니다!

commit : e262cf1b2e3f254e2ff8dd551b84a77e6398f62a

2019-11-11 16:02 UTC, taeiim commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/ContentsFragment.kt
> +        private const val ARG_TYPE = ""
수정했습니다 ! 

commit : e262cf1b2e3f254e2ff8dd551b84a77e6398f62a

2019-11-11 16:03 UTC, taeiim commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/ContentsFragment.kt
> +            searchEditTv.text.toString().let { searchBlog(it) }
수정했습니다 

commit : cac1447c9e7376ee8866b060d48169f30ae44068

2019-11-12 02:29 UTC, BeokBeok approved these changes
LGTM:ok_hand:

--- 

리뷰 수정 시, 하나의 리뷰에 하나의 커밋으로 해주시면 좋을 것 같아요.
수정하신 내용 검토하기에 불편합니다. 😭

2019-11-12 05:55 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-11-12 05:56 UTC, merged