HW-2 MVP의 Model 생성
sjjeong/GoogryAndroidArchitecutreStudy pull request #272
Opened 2019-11-04 14:00 UTC by 2giwon

1. 기존 서비스 작업들을 RemoteDataSource와 Repository로 이동
2. Repository에서 받은 결과값을 fragment에 Callback으로 전달하여 UI를 업데이트 할 수 있도록 변경

2019-11-05 17:32 UTC, taeiim reviewed
제가 코멘트 할 부분을 찾기가 어렵네요 ㅜㅜ 석준님이 어떻게 리뷰해주실지 매우 궁금합니다 ㅎㅎ 😸🤓

2019-11-05 17:32 UTC, taeiim commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/data/source/remote/NaverRemoteDataSourceImpl.kt
>                      }
body가 null 일때도 fail 콜백 보내도록 처리하면 좋을 것 같습니다.

2019-11-05 17:32 UTC, taeiim commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/tabs/ContentsFragment.kt
> +                }
실패했을때 리스트를 clear 한다던가, 토스트를 주는 등의 방식으로 사용자가 실패했다고 인지할 수 있게 처리해주면 좋을 것 같습니다ㅎㅎ

2019-11-06 14:05 UTC, 2giwon commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/data/source/remote/NaverRemoteDataSourceImpl.kt
>                      }
body가 null 일때도 fail 콜백을 보내도록 수정했습니다.

8f34d63c2b0f3a795f225e298cad96783433dfdc

2019-11-06 14:05 UTC, 2giwon commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/tabs/ContentsFragment.kt
> +                }
실패 콜백을 받으면 Toast메세지를 띄우도록 수정했습니다.

600f8b66448d081c9357516b8706a28ebfcfbc48

2019-11-07 08:19 UTC, BeokBeok requested changes
안녕하세요. 스터디 2기 강현석이라고 합니다.
부족하지만 잘 부탁드립니다. 😅

2019-11-07 08:19 UTC, BeokBeok commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/PagerAdapter.kt
>      override fun getItem(@IntRange(from = 0, to = 3) position: Int): Fragment =
annotation 은 개행해주시면 좋을 것 같아요.
https://kotlinlang.org/docs/reference/coding-conventions.html#annotation-formatting

2019-11-07 08:19 UTC, BeokBeok commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/data/Content.kt
>      @SerializedName("lastBuildDate") var lastBuildDate: String,
annotation 은 개행해주시면 좋을 것 같아요.
https://kotlinlang.org/docs/reference/coding-conventions.html#annotation-formatting

2019-11-07 08:19 UTC, BeokBeok commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/data/source/NaverDataRepository.kt
> +    override fun getContents(
변수 정의부와 함수 정의부 사이에는 개행해주시면 좋을 것 같아요.

2019-11-07 08:19 UTC, BeokBeok commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/data/source/NaverDataRepository.kt
> +    ) {
`=` 을 사용하시면, 중괄호를 정리할 수 있어요.

2019-11-07 08:19 UTC, BeokBeok commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/data/source/NaverDataRepository.kt
> +object NaverDataRepository : NaverRemoteDataSource {
Repository 는 local 과 remote 를 모두 제어할 수 있는 개념인데,
NaverRemoteDataSource 만 구현받는 것은 이상해보여요.

NaverRemoteDataSource 인터페이스의 이름을 변경해주시면 좋을 것 같아요.

2019-11-07 08:19 UTC, BeokBeok commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/data/source/remote/NaverRemoteDataSourceImpl.kt
> +    NaverRemoteDataSource {
한 줄로 표현하시는 것이 좋을 것 같아요.

`object NaverRemoteDataSourceImpl : NaverRemoteDataSource {`

2019-11-07 08:19 UTC, BeokBeok commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/data/source/remote/NaverRemoteDataSourceImpl.kt
>      private val retrofit = Retrofit.Builder()
retrofit 관련하여 따로 관리하는 클래스가 있으면 좋을 것 같아요.

2019-11-07 08:19 UTC, BeokBeok commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/data/source/remote/NaverRemoteDataSourceImpl.kt
> +                    callback.onFailure(throwable = this)
this 를 annotation 으로 어느 scope 에 있는 인스턴스인지 표시해주면 좋을 것 같아요.

번외로 with 보다는 let 이 좋을 것 같아요.

2019-11-07 08:19 UTC, BeokBeok commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/data/source/remote/NaverRemoteDataSourceImpl.kt
>                      response.body()?.let {
immutable 변수는 let 보다 if 문을 활용하여 null check 하시는 것이 더 좋을 것 같아요.

2019-11-07 08:40 UTC, sjjeong submitted a review, later dismissed
LGTM ✊ ✌️ 👋

2019-11-07 08:40 UTC, sjjeong commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/data/source/remote/NaverRemoteDataSource.kt
> +interface NaverRemoteDataSource {
해당 인터페이스를 Repository랑 RemoteDataSource 쪽 둘다 사용한다면 NaverDataSource가 더 어울릴 것 같습니다.
이건 제 개인적인 의견이라서 반영 안하셔도 됩니당

2019-11-07 13:48 UTC, 2giwon commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/PagerAdapter.kt
>      override fun getItem(@IntRange(from = 0, to = 3) position: Int): Fragment =
개행처리 수정했습니다.
ebeaa4d6d2635bc723efa69f364af44eadb95a79

2019-11-07 13:49 UTC, 2giwon commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/data/Content.kt
>      @SerializedName("lastBuildDate") var lastBuildDate: String,
annotation 개행 처리 수정했습니다.

c550f049bfdfd161fd79993c8f68fa938a25fb3a

2019-11-07 13:50 UTC, 2giwon commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/data/source/NaverDataRepository.kt
> +    override fun getContents(
변수를 제거하고 Repository에 멤버 변수로 갖게 수정했습니다.

5dcca3cb0f5d2da87b5b4ac75adb42a21791a1d9

2019-11-07 13:51 UTC, 2giwon commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/data/source/NaverDataRepository.kt
> +    ) {
중괄호 제거 수정했습니다^^

fa389d8b7657b46f9c2e72d66264a85c8a8e8c6a

2019-11-07 13:53 UTC, 2giwon commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/data/source/NaverDataRepository.kt
> +object NaverDataRepository : NaverRemoteDataSource {
NaverRemoteDataSource를 NaverDataSource로 변경 수정했습니다.

Repository에서 NaverDataSource를 implement하고
NaverRemoteDataSource를 생성자로 받게끔 수정했습니다.

Repository 는 Object에서 Class 로 변경하고 싱글턴으로 생성하게 수정했습니다.

5dcca3cb0f5d2da87b5b4ac75adb42a21791a1d9

2019-11-07 13:54 UTC, 2giwon commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/data/source/remote/NaverRemoteDataSourceImpl.kt
> +    NaverRemoteDataSource {
수정했습니다.

5dcca3cb0f5d2da87b5b4ac75adb42a21791a1d9

2019-11-07 13:55 UTC, 2giwon commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/data/source/remote/NaverRemoteDataSourceImpl.kt
>      private val retrofit = Retrofit.Builder()
Retrofit을 Object로 전달받을 수 있도록 수정했습니다.

ec81de136c82cc906c3b8a307d8117a41885019b

2019-11-07 13:56 UTC, 2giwon commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/data/source/remote/NaverRemoteDataSourceImpl.kt
> +                    callback.onFailure(throwable = this)
with(t) 를 t.let으로 수정했습니다.

0e76a4021ac1aa177913f9efcc8a02905ee52d8f

2019-11-07 15:06 UTC, 2giwon commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/data/source/remote/NaverRemoteDataSourceImpl.kt
>                      response.body()?.let {
if 로 null 체크를 하도록 수정했습니다.

1c579be5e009f1081550671336610bab64ef1ef7

2019-11-08 01:03 UTC, BeokBeok approved these changes
LGTM:ok_hand:

2019-11-08 01:31 UTC, taeiim approved these changes

2019-11-08 09:16 UTC, merged