HW-7 AAC-ViewModel, LiveData 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #275
Opened 2019-11-05 00:17 UTC by toctocbin

이전 BaseViewModel 에 AAC-ViewModel 을 적용하였고 ObservableField 로 되어있는 부분을 LiveData로 변경하였습니다.

2019-11-05 02:22 UTC, junghum21 commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/ui/market/MarketViewModel.kt
> +    var marketTitle = MutableLiveData<List<MarketTitle>>()
외부에선 LiveData에 접근하고, MutableLiveData는 내부에서만 접근할수 있도록 하는게 좋겠네요.

2019-11-05 02:22 UTC, junghum21 commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/ui/ticker/TickerFragment.kt
>          binding.coinRecyclerView.adapter = this.adapter
BindingAdapter에서 adapter를 초기화 해주는게 좋을 것 같네요.

2019-11-05 02:22 UTC, junghum21 commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/ui/ticker/TickerViewModel.kt
> +    var tickerList = MutableLiveData<List<TickerFormat>>()
앞서 드린 코멘트와 마찬가지로 변경은 내부에서만, 외부 접근은 LiveData로만 가능하게 바꿔주세요.

2019-11-07 01:59 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/ui/market/MarketViewModel.kt
> +    var marketTitle = MutableLiveData<List<MarketTitle>>()
41375e3

적용했습니다!

2019-11-07 01:59 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/ui/ticker/TickerViewModel.kt
> +    var tickerList = MutableLiveData<List<TickerFormat>>()
2be7086

적용했습니다!

2019-11-07 02:00 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/ui/ticker/TickerFragment.kt
>          binding.coinRecyclerView.adapter = this.adapter
7acb9bb

적용했습니다!

2019-11-07 02:00 UTC, toctocbin commented
그외에도 정흠님 리뷰보면서 잘못된 부분 수정했습니다!

2019-11-07 06:12 UTC, junghum21 commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/ui/ticker/TickerFragment.kt
> +        binding.lifecycleOwner = viewLifecycleOwner
BaseFragment에서 lifecycleOwner 초기화 해줘도 될것 같아요

2019-11-08 16:07 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/ui/ticker/TickerFragment.kt
> +        binding.lifecycleOwner = viewLifecycleOwner
50e3094

적용했습니다.

2019-11-09 13:52 UTC, BeokBeok requested changes
안녕하세요. 스터디 2기 강현석이라고 합니다.
부족하지만 잘 부탁드립니다. 😅

2019-11-09 13:52 UTC, BeokBeok commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/base/BaseViewModel.kt
> +    protected val _toastMessage = MutableLiveData<String>()
언더바(`_`) 는 private 접근자를 가진 변수에 사용하는 것으로 알고 있어요.

해서, protected 접근자를 유지하고 싶으시다면
언더바를 제거한 변수명으로 사용하시면 좋을 것 같고
접근자를 private 로 변경하신다면
value 를 set 하는 함수를 만드셔서 처리하시면 좋을 것 같아요.

2019-11-09 13:52 UTC, BeokBeok commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/ui/ticker/TickerFragment.kt
> +                return TickerViewModel(arguments?.getString(MARKET_SEARCH) ?: "") as T
`=` 을 사용하시면, 중괄호를 정리할 수 있을 것 같아요.

2019-11-09 13:52 UTC, BeokBeok commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/ui/ticker/TickerViewModel.kt
> +    var tickerList : LiveData<List<TickerFormat>> = _tickerList
var 보다는 val 을 사용하시면 좋을 것 같아요.

2019-11-09 13:52 UTC, BeokBeok commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/ui/market/MarketViewModel.kt
> +    var marketTitle: LiveData<List<MarketTitle>> = _marketTitle
var 보다는 val 을 사용하시는 것이 좋을 것 같아요.

2019-11-11 03:34 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/base/BaseViewModel.kt
> +    protected val _toastMessage = MutableLiveData<String>()
93b1658

적용했습니다.

2019-11-11 03:34 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/ui/ticker/TickerFragment.kt
> +                return TickerViewModel(arguments?.getString(MARKET_SEARCH) ?: "") as T
bdf5576

적용했습니다.

2019-11-11 03:35 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/ui/ticker/TickerViewModel.kt
> +    var tickerList : LiveData<List<TickerFormat>> = _tickerList
180bb2e
적용했습니다.

2019-11-11 03:35 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/ui/market/MarketViewModel.kt
> +    var marketTitle: LiveData<List<MarketTitle>> = _marketTitle
c4e2461
적용했습니다.

2019-11-11 05:12 UTC, BeokBeok submitted a review, later dismissed
LGTM:ok_hand:

2019-11-12 06:35 UTC, sjjeong requested changes

2019-11-12 06:35 UTC, sjjeong commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/base/BaseFragment.kt
> +        vm.toastMessage.observe(this, Observer {
viewLifecycleOwner를 사용해주세요.

2019-11-12 06:35 UTC, sjjeong commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/base/BaseViewModel.kt
> +    fun setToastMessage(s: String){
showToastMessage가 좋을 것 같습니다.

2019-11-12 06:50 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/base/BaseViewModel.kt
> +    fun setToastMessage(s: String){
c3a45fd

적용했습니다.

2019-11-12 06:50 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/base/BaseFragment.kt
> +        vm.toastMessage.observe(this, Observer {
188711b

적용했습니다.

2019-11-13 08:35 UTC, sjjeong approved these changes

2019-11-13 08:36 UTC, merged