HW-07 AAC ViewModel, LiveData 적용하기
sjjeong/GoogryAndroidArchitecutreStudy pull request #276
Opened 2019-11-05 01:43 UTC by junghum21

어느덧 스터디 막바지에 왔네요.

리뷰 잘 부탁드립니다.

2019-11-07 00:54 UTC, haanbin requested changes
확인하면서 제꺼 수정할거만 생긴거같아요! 코드에 대해선 리뷰할게 없는거 같아요 ㅠ
수고하셨습니다!

2019-11-07 00:54 UTC, toctocbin commented on junghum21/ArchStudy/app/build.gradle
> +    implementation 'androidx.lifecycle:lifecycle-extensions:2.1.0'
dependency 를 따로 추가하지 않았는데 사용가능하길래 그냥 진행 했는데 차이점이 있을까요?!

2019-11-07 01:34 UTC, toctocbin commented on junghum21/ArchStudy/app/build.gradle
> +    implementation 'androidx.lifecycle:lifecycle-extensions:2.1.0'
androidx에 ViewModelProviders가 포함 안되어있네요..

2019-11-07 01:40 UTC, toctocbin commented on junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/base/BaseViewModel.kt
>      val toast = ObservableField<String>()
Toast String도 LiveData로 변경하시는건 어떨까요 !

2019-11-07 06:10 UTC, junghum21 commented on junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/base/BaseViewModel.kt
>      val toast = ObservableField<String>()
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/276/commits/618282fe71f7a348401d829ff3c1001c8b8fb860

반영완료

2019-11-08 08:03 UTC, toctocbin commented on junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/base/BaseViewModel.kt
>      val toast = ObservableField<String>()
수고하셨습니다 !

2019-11-08 09:03 UTC, BeokBeok requested changes
안녕하세요. 스터디 2기 강현석이라고 합니다.
부족하지만 잘 부탁드립니다. 😅

2019-11-08 09:03 UTC, BeokBeok commented on junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/base/BaseViewModel.kt
> +    protected val _toast = MutableLiveData<String>()
변수명 앞에 언더바 (`_`) 는 private 한 느낌이 강한 것 같습니다.

해서, 접근자를 private 로 변경하신 후
value 에 대한 setter 를 만드셔서 처리하시면 좋을 것 같아요.

2019-11-08 09:03 UTC, BeokBeok commented on junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/ui/main/MainActivity.kt
> +                return MainViewModel(
`=` 를 사용하시면, 중괄호를 정리할 수 있을 것 같아요.

2019-11-08 09:03 UTC, BeokBeok commented on junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/ui/main/MainActivity.kt
> +        )
SAM 인 경우에는, 람다로 표현하시면 가독성이 올라갈 것 같아요.

2019-11-08 09:03 UTC, BeokBeok commented on junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/ui/main/MainViewModel.kt
>                          val markets = map.value.joinToString { it.market }
이렇게 정리하시면 보다 간결해질 것 같아요.
`val (title, markets) = map.key to map.value.joinToString { it.market }`

2019-11-08 09:03 UTC, BeokBeok commented on junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/ui/tickers/TickersViewModel.kt
> +                _tickers.value = tickers
변수 선언하지 않고 바로 적용이 가능할 것 같아요.
`_tickers.value = response.map {  it.toTicker() }`

2019-11-10 14:27 UTC, junghum21 commented on junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/ui/main/MainActivity.kt
> +        )
반영완료 

https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/276/commits/108ebc4bc790606ce3457a815caee0b4897f65d9

2019-11-10 14:28 UTC, junghum21 commented on junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/ui/tickers/TickersViewModel.kt
> +                _tickers.value = tickers
반영완료

https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/276/commits/1a38de9a8ceadd543956e30717a7019ad6b4b1ad

2019-11-10 14:28 UTC, junghum21 commented on junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/base/BaseViewModel.kt
> +    protected val _toast = MutableLiveData<String>()
반영완료

https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/276/commits/d62167ced1dc269cb589b1d91db7c49fc861f547

2019-11-10 14:28 UTC, junghum21 commented on junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/ui/main/MainViewModel.kt
>                          val markets = map.value.joinToString { it.market }
반영완료

https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/276/commits/e47ac029ad62d091b60298e420848f198199cbab

2019-11-10 14:28 UTC, junghum21 commented on junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/ui/main/MainViewModel.kt
>                          val markets = map.value.joinToString { it.market }
몰랐던 문법이었네요. 유용한 피드백 고맙습니다.

2019-11-10 14:32 UTC, junghum21 commented on junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/ui/main/MainActivity.kt
> +                return MainViewModel(
저는 메소드 리턴은 한줄로 끝낼수 있을정도로 간결할때만 사용합니다. 가독성면에선 그게 더 낫다고 생각해요.

2019-11-11 00:26 UTC, BeokBeok commented on junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/base/BaseViewModel.kt
> +    protected val _toast = MutableLiveData<String>()
함수명과 변수명이 겹쳐서 혼란스러울것 같아요.

게다가, 함수명만 봤을 때
이 함수가 어떤 기능을 하는지 판단하기가 힘든 것 같아요.

해서, 함수명을 변경하시면 좋을 것 같아요.

2019-11-11 10:37 UTC, junghum21 commented on junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/base/BaseViewModel.kt
> +    protected val _toast = MutableLiveData<String>()
showToast() 로 변경했습니다.

https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/276/commits/befda0972a0a69c2f13dcd63c4219d33b2a7d6ed

2019-11-11 12:20 UTC, BeokBeok approved these changes
LGTM:ok_hand:

2019-11-12 04:00 UTC, haanbin approved these changes

2019-11-12 04:01 UTC, merged