HW-7 AAC-ViewModel, LiveData 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #277
Opened 2019-11-05 05:08 UTC by seonoh

LiveData를 제대로 사용해본적이 없습니다. 코드는 작성했지만 이해가 부족한 상황입니다.

고쳐야 할 부분들 피드백주시면 감사하겠습니다!

2019-11-05 15:07 UTC, jskim5923 reviewed
수고하셨습니다!

2019-11-05 15:07 UTC, jskim5923 commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/BaseActivity.kt
>          setContentView(layoutRes)
```
binding = DataBindingUtil.setContentView(this, layoutRes)
```
을 해당 위치로 옮기고 setContentView(layoutRes)는 삭제해도 될것 같습니다.

2019-11-05 15:07 UTC, jskim5923 commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinFragment.kt
> +            lifecycleOwner = this@CoinFragment
`Fragment`에서는 lifecyclerOwner로 this가 아닌 `viewLifecycleOwner`로 set해주세요.

`lifeCycleOwner`는  onDestroy에 데이터가 해제되는 데, Fragment의 경우 `onDestroyView`까지만 타는 경우가 많아 메모리 누수의 위험이 있다고 알고 있습니다.

2019-11-05 15:07 UTC, jskim5923 commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/model/CoinViewModel.kt
> +    val coinItem = MutableLiveData<List<UseCoinModel>>()
`MutableLiveData` type은  private으로 지정하고,  `LiveData` type의 public변수를 만들어서 접근 시키는게 좋을것같습니다.

2019-11-05 15:07 UTC, jskim5923 commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/MainActivity.kt
>              tabLayout.run {
굳이 run을 이용할 필요는 없을 것 같습니다.

2019-11-05 15:07 UTC, jskim5923 commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/MainActivity.kt
>                  addOnPageChangeListener(TabLayout.TabLayoutOnPageChangeListener(tabLayout))
```
coinViewPager.addOnPageChangeListener(TabLayout.TabLayoutOnPageChangeListener(tabLayout))
tablayout.addOnTabSelectedListener(TabLayout.ViewPagerOnTabSelectedListener(coinViewPager)
```
이거 tabLayout.setupWithViewPager(coinViewPager) 이거로 바꿀수 있을것 같습니다.

2019-11-05 15:07 UTC, jskim5923 commented on seonoh/ArchitectureStudy/app/src/main/res/layout/activity_main.xml
> +                addTab="@{mainViewModel.marketInfo}"
TabLayout에서 addTab해주는 방법 말고 viewPager에 데이터를 넘겨서 `getPageITitle`함수를 override해보는건 어떠세요?

2019-11-05 15:07 UTC, jskim5923 commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/MainBindingAdapter.kt
> +        data.forEach {
comment남겨드린것처럼 addTab대신 viewPager의 getPageTitle을 이용하시면 상관없는 comment이지만

만약 이걸 유지하신다면 `it.forEach {`로 접근하시는게 좋을 것 같습니다.

2019-11-05 15:07 UTC, jskim5923 commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/MainActivity.kt
> +    override val viewModel by lazy {
저같은 경우 viewModel변수 위에 `@Suppress("UNCHECKED_CAST")` annotaion을 달아서 에디터상의 highlight를 없앱니다!

2019-11-06 01:10 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/BaseActivity.kt
>          setContentView(layoutRes)
앗 감사합니다. 수정했습니다. 740287fddc2b0734dd3e85ffadfc8d2323333284

2019-11-06 01:11 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinFragment.kt
> +            lifecycleOwner = this@CoinFragment
감사합니다 ! a5acbcfe5aff0edfbfc869bb207b99b19b5e5cbe

2019-11-06 01:14 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/model/CoinViewModel.kt
> +    val coinItem = MutableLiveData<List<UseCoinModel>>()
감사합니다 !60bebea299032a76656f42ff9cf0258de4c5f2f4

2019-11-06 01:24 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/MainActivity.kt
>              tabLayout.run {
네 ! 72c0d3fa0f90878c7c02a668d4d64e3b9fb26ae7

2019-11-06 01:24 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/MainActivity.kt
>                  addOnPageChangeListener(TabLayout.TabLayoutOnPageChangeListener(tabLayout))
72c0d3fa0f90878c7c02a668d4d64e3b9fb26ae7

2019-11-06 01:24 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/res/layout/activity_main.xml
> +                addTab="@{mainViewModel.marketInfo}"
네 감사합니다 ! cbb6e513ccfc0ed2f3e27c93f08297ba76617e4a

2019-11-06 01:24 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/MainBindingAdapter.kt
> +        data.forEach {
cbb6e513ccfc0ed2f3e27c93f08297ba76617e4a (종선님이 말하신대로 수정했습니다 감사합니다 ! )

2019-11-06 01:26 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/MainActivity.kt
> +    override val viewModel by lazy {
af2630b453276d2f8fee9c42507353b27e7c31b0 감사합니다 !

2019-11-06 15:08 UTC, jskim5923 requested changes

2019-11-06 15:08 UTC, jskim5923 commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinFragment.kt
> +            lifecycleOwner = viewLifecycleOwner
BaseFragment에서 하는 것이 좋다고 저도 코멘트를 받았습니다.

2019-11-06 15:08 UTC, jskim5923 commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/MainActivity.kt
> +            lifecycleOwner = this@MainActivity
BaseActivity에서 하는 것이 좋다고 저도 코멘트를 받았습니다.

2019-11-07 01:15 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinFragment.kt
> +            lifecycleOwner = viewLifecycleOwner
네 감사합니다 !! c3a596ce7295ada20073392783b13d36d1c0adee

2019-11-07 01:15 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/MainActivity.kt
> +            lifecycleOwner = this@MainActivity
네 감사합니다 !! c3a596ce7295ada20073392783b13d36d1c0adee

2019-11-07 04:30 UTC, jskim5923 commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/MainActivity.kt
> +            lifecycleOwner = this@MainActivity
c3a596c 커밋만 봐서는 MainActivity의 
```
lifecycleOwner = this@MainActivity
```
부분 삭제가 안 되어있는것 같습니다.

2019-11-08 05:38 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/MainActivity.kt
> +            lifecycleOwner = this@MainActivity
b609535f31b8045fce3f0006615d8259fd8872af 죄송합니다!

2019-11-08 10:43 UTC, jskim5923 submitted a review, later dismissed
LGTM

2019-11-08 12:24 UTC, BeokBeok requested changes
안녕하세요. 스터디 2기 강현석이라고 합니다.
부족하지만 잘 부탁드립니다. 😅

2019-11-08 12:24 UTC, BeokBeok commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinFragment.kt
> +                return CoinViewModel(
`=` 을 사용하시면, 중괄호를 정리할 수 있어요.

2019-11-08 12:24 UTC, BeokBeok commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/TabPagerAdapter.kt
>          this.data.addAll(data)
this 에 annotation 을 달아주면, 어떤 인스턴스의 this 인지 알아보기 쉬울 것 같아요.
```suggestion
        this@TabPagerAdapter.data.addAll(data)
```

2019-11-08 12:24 UTC, BeokBeok commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/model/BaseViewModel.kt
> +        super.onCleared()
super 를 나중에 호출해주시면 좋을 것 같아요.

2019-11-08 12:24 UTC, BeokBeok commented on seonoh/ArchitectureStudy/dependencies.gradle
개행은 한 줄 단위로 하시면 좋을 것 같아요.

2019-11-09 03:27 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinFragment.kt
> +                return CoinViewModel(
1385cbd0ba935a09e4a6a8ca92ac3590709ad3c5

2019-11-09 03:28 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/TabPagerAdapter.kt
>          this.data.addAll(data)
e94a03b63b0c2be405ff607207d9516950787622

2019-11-09 03:28 UTC, seonoh commented on seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/model/BaseViewModel.kt
> +        super.onCleared()
1d0aa61dc221db48e8f1dd652b31a3d8178f2647

2019-11-09 03:28 UTC, seonoh commented on seonoh/ArchitectureStudy/dependencies.gradle
331e84468fd33b3dc0a8a1d6759015a485bf5d0f

2019-11-09 13:16 UTC, BeokBeok approved these changes
LGTM:ok_hand:

2019-11-10 08:10 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-11-10 13:29 UTC, merged