HW-7 AAC-ViewModel, LiveData 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #279
Opened 2019-11-05 14:19 UTC by onemask

LiveData랑 ViewModel 적용하였습니다. 

* clearCompositeDisposable() 처리를 BaseViewModel()로 받아서 처리하고
해당 메소드 view가 onDestroy 될떄 call 하고 있어서 이 점과

* mainViewModel()에서는 init{}으로 바로 data call하는데 
   TickerViewModel() 에서는 TickerFragment 에서 viewModel에서 api 호출하고 있는데 

이 2가지 사항 뭔가 좀더 개선하고 싶습니다. 
하여 위와 관련된 리뷰나 이 외에도 다른 코멘트도 환영입니답

2019-11-05 15:56 UTC, sjjeong requested changes

2019-11-05 15:56 UTC, sjjeong commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/tickerlist/viewmodel/TickerViewModel.kt
> +    get() = _tickerList
TAP추가 해주세염

2019-11-05 15:56 UTC, sjjeong commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/main/MainActivity.kt
> +            lifecycleOwner = this@MainActivity
요거는 BaseActivity로 옮겨도 됩니다

2019-11-05 15:56 UTC, sjjeong commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/TickerListFragment.kt
> +            lifecycleOwner = this@TickerListFragment
BaseFragment로 옮겨주세요.
그리고 viewLifecycleOwner를 사용해주세요

2019-11-06 11:50 UTC, onemask commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/tickerlist/viewmodel/TickerViewModel.kt
> +    get() = _tickerList
석준님 TAP가 tablayout의 tap 인가요? @dino

2019-11-06 12:11 UTC, sjjeong commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/tickerlist/viewmodel/TickerViewModel.kt
> +    get() = _tickerList
들여쓰기!

2019-11-07 13:47 UTC, onemask commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/tickerlist/viewmodel/TickerViewModel.kt
> +    get() = _tickerList
저런.. 부끄럽네요..
수정하였습니답 
a1e076e

2019-11-07 13:47 UTC, onemask commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/main/MainActivity.kt
> +            lifecycleOwner = this@MainActivity
수정하였습니다.
5522e8f

2019-11-07 13:48 UTC, onemask commented on onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/TickerListFragment.kt
> +            lifecycleOwner = this@TickerListFragment
수정하였습니다.
d480db7

2019-11-08 14:08 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-11-08 15:26 UTC, merged