HW-2 MVP 과제
sjjeong/GoogryAndroidArchitecutreStudy pull request #280
Opened 2019-11-06 08:01 UTC by developerkhm

MVP 과제입니다.

2019-11-10 05:01 UTC, buddman1208 requested changes
확인 부탁드립니다!

2019-11-10 05:01 UTC, buddman1208 commented on developerkhm/AndroidStudy/app/src/main/java/com/example/androidstudy/model/data/NaverDataImpl.kt
> +    override fun callAPiNaverSearch(type: String, query: String): Call<TotalModel> {
callApiNaverSearch가 좋을것 같아요!
```suggestion
    override fun callApiNaverSearch(type: String, query: String): Call<TotalModel> {
```

2019-11-10 07:05 UTC, buddman1208 submitted a review, later dismissed
확인했습니다!

2019-11-10 08:06 UTC, sjjeong requested changes

2019-11-10 08:06 UTC, sjjeong commented on developerkhm/AndroidStudy/app/src/main/java/com/example/androidstudy/model/data/INaverData.kt
> +interface INaverData {
interface에 I를 붙이는건 좋은 명명법이 아닙니다.
클린코드 관련 내용을 찾아보시면 좋습니다.

INaverDataRepository도 같이 수정해주세요.

2019-11-10 08:06 UTC, sjjeong commented on developerkhm/AndroidStudy/app/src/main/java/com/example/androidstudy/ui/base/BaseFragment.kt
> +                    result.let {
let을 제거해도 좋습니다.

2019-11-13 00:29 UTC, developerkhm commented on developerkhm/AndroidStudy/app/src/main/java/com/example/androidstudy/model/data/INaverData.kt
> +interface INaverData {
수정했습니다.

id : 2e056455

2019-11-13 00:29 UTC, developerkhm commented on developerkhm/AndroidStudy/app/src/main/java/com/example/androidstudy/ui/base/BaseFragment.kt
> +                    result.let {
수정했습니다. 이미 결과 콜백전에 null 체크를 하고 있었네요~ 감사감사

id : d601082d

2019-11-17 06:28 UTC, developerkhm commented
확인부탁드립니다.~

2019-11-18 02:21 UTC, sjjeong commented
PR이름을 변경해주세요
MVP과제가 아닙니다.

2019-11-22 16:36 UTC, sjjeong approved these changes

2019-11-30 10:07 UTC, merged