HW-2 Model 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #281
Opened 2019-11-06 11:15 UTC by bean628

진혁님~ 조금 늦었지만 리뷰 부탁드려요~!!
어제 PR 올리고 잔줄 알았는데 좀 전에 집와서 보니 안 올라가있네요 ㅋㅋㅋ

2019-11-06 12:51 UTC, ironelder submitted a review, later dismissed

2019-11-06 12:51 UTC, ironelder commented on bean628/MyProject/app/src/main/java/common/Constant.kt
> +const val NETWORK_ERROR_MSG = "네트워크 통신 장애입니다."
에러 관련 메시지는 상수로 선언보다 추후 다국어 처리를 고려하여 string.xml 리소스로 옮기면 좋을 것 같습니다~

2019-11-06 12:51 UTC, ironelder commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/data/source/NaverRepository.kt
> +}
해당 소스 구조가 잘못된 것 같습니다 현재 인터페이스는 DataSource를 가져서 구현하고 있는데
이는 아랫쪽의 DataSourceImpl과 같은 동작을 하고 있습니다.

실제로 현재 MainActivity에 NaverRepository참조 부분을 NaverRemoteDataSourceImpl로 교체하여도 동일한 동작을 하기 때문에 해당 오브젝트가 하는 일이 없는 것 같습니다.

구조 개선이 필요한 것 같습니다~

2019-11-06 12:51 UTC, ironelder commented on bean628/MyProject/app/src/main/java/common/BaseActivity.kt
> +}
Toast를 공통으로 사용하기 위하여 빼신 것도 괜찮아 보입니다.
하지만 Toast를 위함이라면
AppCompatActivity를 확장하는 함수를 만들어보시는 건 어떤가요?

```
fun AppCompatActivity.makeToast(id: Int) {
    Toast.makeText(this, this.getString(id), Toast.LENGTH_LONG).show()
}

fun AppCompatActivity.makeToast(text: String) {
    Toast.makeText(this, text, Toast.LENGTH_LONG).show()
}
```

위와같은 형식으로 확장함수를 구현하면 makeToast에 String ResourceId 또는 문자열 값으로 토스트를 띄울 수 있을 것 같습니다

2019-11-06 13:53 UTC, bean628 commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/data/source/NaverRepository.kt
> +}
저도 구글 샘플을 보면서 작업할 때 의아하긴 했어요! 사실 지금도 왜 그렇게 되어있는지 잘 모르겠어요. 물론 제가 구글 샘플 구조를 잘못 이해했을수도 있구요 ㅎㅎ
음~~ 지금 다시 생각해보니 구글 샘플은 캐시때문에 로컬이랑 같이 불리면서 작업이 복잡해지는 경우가 있어서 그렇게 되어있던것 같기도 하네요!

지금 제 프로젝트 구조가 너무 단순해서 ㅋㅋ 진혁님 말씀처럼 불필요한게 맞다고 생각합니다.수정했습니다!! 

ba9fb99

2019-11-06 13:54 UTC, bean628 commented on bean628/MyProject/app/src/main/java/common/BaseActivity.kt
> +}
수정했습니다!

4249ced

2019-11-06 13:57 UTC, bean628 commented on bean628/MyProject/app/src/main/java/common/Constant.kt
> +const val NETWORK_ERROR_MSG = "네트워크 통신 장애입니다."
사실 이거 작업할 때 Repository에서 Context나 Activity 없이 어떻게 R.String.~~ 에 접근해서 사용하는지 몰라서 방법 찾다가 못 찾아서 상수로 작업을 했었어요 ㅋㅋㅋ
  오늘 다시 찾아보니 
```
Resources.getSystem().getString(R.string.toast_network_error_msg)
```
이렇게 하는 방법이 있더라구요!

수정했습니다!
0c43479

2019-11-06 14:09 UTC, ironelder commented on bean628/MyProject/app/src/main/java/common/BaseActivity.kt
> +}
음... 확장함수의 경우에는 클래스 내부가 아닌 외부에 선언하게 됩니당~
```
Class BaseActivity: AppCompatActivity(){
 ... blablabla...
}
fun AppCompatActivity.makeToast( ... parameter ){
}
```

위와 같이 선언되게 되는데
사실 보기가 좋지 않기 때문에 보면 Extension.kt 파일을 만들고 그 안에 확장함수를 몰아 넣으시더라구요

2019-11-06 14:11 UTC, ironelder commented on bean628/MyProject/app/src/main/java/common/BaseActivity.kt
> +}
BaseActivity를 선언하신 이유가 사용해보시려고 하는 것인지 아니면 다른 Try조건이 있으신건지 궁금합니당~

2019-11-08 03:10 UTC, bean628 commented on bean628/MyProject/app/src/main/java/common/BaseActivity.kt
> +}
BaseActivity는 Toast 편하게 쓰려고 만들었었어요!
확장함수를 모아놓은 Extension.kt 파일을 만들어서 그 안에 확장함수를 넣도록 변경했습니다!

수정했습니다
99888b0

2019-11-08 12:49 UTC, BeokBeok requested changes
안녕하세요. 스터디 2기 강현석이라고 합니다.
부족하지만 잘 부탁드립니다. 😅

2019-11-08 12:49 UTC, BeokBeok commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/data/source/remote/NaverRemoteDataSource.kt
> +    interface GetResultOfSearchingCallBack {
인터페이스명은 명사구 혹은 형용사 형태로 지으면 좋을 것 같아요.

2019-11-08 12:49 UTC, BeokBeok commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/data/source/remote/NaverRemoteDataSourceImpl.kt
> +    private val naverApiService = RetrofitClient(NAVER_API_BASE_URL).makeRetrofitServiceForNaver()
Retrofit 객체를 생성자로 받게 처리하시면 좋을 것 같아요.

2019-11-08 12:49 UTC, BeokBeok commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/data/source/remote/NaverRemoteDataSourceImpl.kt
> +                    response.body()?.items?.let {
response.body().items 는 immutable 이므로,
let 보다는 if 문을 사용하여 null check 하시면 좋을 것 같아요.

2019-11-08 12:49 UTC, BeokBeok commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/data/source/remote/NaverRemoteDataSourceImpl.kt
> +                    callBack.onFailure(Resources.getSystem().getString(R.string.toast_network_error_msg))
DataSource 부분에는 android 관련 속성의 의존성이 없는 것이 좋을 것 같아요.

2019-11-08 12:49 UTC, BeokBeok commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/data/source/remote/NaverRemoteDataSourceImpl.kt
> +                callBack.onFailure(Resources.getSystem().getString(R.string.toast_network_error_msg))
t.messge 를 활용해보시는 것은 어떠신가요?

2019-11-08 16:49 UTC, bean628 commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/data/source/remote/NaverRemoteDataSource.kt
> +    interface GetResultOfSearchingCallBack {
수정했습니다!

428920a

2019-11-08 16:49 UTC, bean628 commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/data/source/remote/NaverRemoteDataSourceImpl.kt
> +                    response.body()?.items?.let {
수정했습니다!
557c0bd

2019-11-08 16:49 UTC, bean628 commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/data/source/remote/NaverRemoteDataSourceImpl.kt
> +                callBack.onFailure(Resources.getSystem().getString(R.string.toast_network_error_msg))
수정했습니다!

f20528d

2019-11-08 16:50 UTC, bean628 commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/data/source/remote/NaverRemoteDataSourceImpl.kt
> +    private val naverApiService = RetrofitClient(NAVER_API_BASE_URL).makeRetrofitServiceForNaver()
```
object NaverRemoteDataSourceImpl(var naverApiService: RetrofitService) : NaverRemoteDataSource {
```
이렇게 생성자에 넣으려고 하면 "Constructor are not allowed for objects" 라고 컴파일 에러가 나요
어떻게 해야될까요...?

2019-11-08 16:54 UTC, bean628 commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/data/source/remote/NaverRemoteDataSourceImpl.kt
> +                    callBack.onFailure(Resources.getSystem().getString(R.string.toast_network_error_msg))
android 관련 속성의 의존성이 없는게 어떤건지 감을 잘 못잡겠어요.
resource에 접근하려면 Context나 activity, Application 에서 context.getString(R.string.string_name) 이런식으로 접근하거나 
context 없이 Resources.getSystem()로 시스템에서 바로 스트링을 가져오는 방법밖에는 모르겠어요

2019-11-09 02:14 UTC, BeokBeok commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/data/source/remote/NaverRemoteDataSource.kt
> +    interface GetResultOfSearchingCallBack {
제가 의도한 것은 NaverRemoteDataSource 변경이 아닌
GetResultOfSearchingCallback 이였습니다.

7번 라인을 클릭하고 리뷰를 하였는데, 의도치않게 5번 라인까지 해당사항으로 보였네요.

2019-11-09 02:15 UTC, BeokBeok commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/data/source/remote/NaverRemoteDataSourceImpl.kt
> +    private val naverApiService = RetrofitClient(NAVER_API_BASE_URL).makeRetrofitServiceForNaver()
object 는 생성자를 받을 수 없습니다.
class 로 변경하시면 될 것 같습니다.

2019-11-09 02:16 UTC, BeokBeok commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/data/source/remote/NaverRemoteDataSourceImpl.kt
> +                    callBack.onFailure(Resources.getSystem().getString(R.string.toast_network_error_msg))
R.string.toast_network_error_msg  값만 던지시고
받는 쪽에서 getString 해서 활요하시면 될 것 같습니다.

2019-11-09 02:28 UTC, BeokBeok commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/data/source/remote/NaverRemoteDataSourceImpl.kt
> +                    }
if 문이 많이 중첩되어있어서 보기 어려운 것 같습니다.
다음과 같이 하시면 좋을 것 같아요.
```
if (!response.isSuccessful) {
    callBack.onFailure(Resources.getSystem().getString(R.string.toast_network_error_msg))
    return
}
val body = response.body()
if (body == null) {
    callBack.onSuccessButEmptyData()
    return
}
body.items.ifEmpty {
    callBack.onSuccessButEmptyData()
    return
}
callBack.onSuccess(body.items)
 ```

2019-11-09 02:45 UTC, bean628 commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/data/source/remote/NaverRemoteDataSource.kt
> +    interface GetResultOfSearchingCallBack {
수정했습니다!
84f9defc

2019-11-09 02:46 UTC, bean628 commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/data/source/remote/NaverRemoteDataSourceImpl.kt
> +    private val naverApiService = RetrofitClient(NAVER_API_BASE_URL).makeRetrofitServiceForNaver()
수정했습니다!
a7964a57

2019-11-09 02:46 UTC, bean628 commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/data/source/remote/NaverRemoteDataSourceImpl.kt
> +                    callBack.onFailure(Resources.getSystem().getString(R.string.toast_network_error_msg))
이렇게 하면될까요??

662ba814

2019-11-09 02:55 UTC, bean628 commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/data/source/remote/NaverRemoteDataSourceImpl.kt
> +                    }
ifEmpty 확장 함수도 let을 immutable 변수에 쓰면 안되는 경우와 같은 이유로 쓰면 안되는거 아닌가요?? 

일단 수정했습니다~ 
8c0cdce2

2019-11-09 04:16 UTC, sjjeong commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/data/source/remote/NaverRemoteDataSourceImpl.kt
> +                    callBack.onFailure(Resources.getSystem().getString(R.string.toast_network_error_msg))
네 이렇게 해도 되지만 보통 throwable을 던져서 처리하거나
error관련된 상수를 만들어서 그걸 넘기고 받는쪽에서 분기처리로 보여주는 식으로 합니다.

2019-11-09 11:31 UTC, bean628 commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/data/source/remote/NaverRemoteDataSourceImpl.kt
> +                    callBack.onFailure(Resources.getSystem().getString(R.string.toast_network_error_msg))
throwable 객체를 넘기는 방식으로 수정했습니다.

b8227d40

2019-11-09 13:08 UTC, BeokBeok commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/data/source/remote/NaverRemoteDataSourceImpl.kt
> +                    }
ifEmpty 함수와 let 과 어떤 상관관계가 있는지 잘 모르겠습니다.
죄송하지만 자세하게 설명해주실 수 있으신가요?

2019-11-09 13:15 UTC, BeokBeok requested changes

2019-11-09 13:15 UTC, BeokBeok commented on bean628/MyProject/app/src/main/java/common/Constant.kt
> +const val NETWORK_ERROR_MSG = "네트워크 통신 장애입니다."
이 변수는 사용하지 않는 것으로 보입니다.
사용하지 않는다면 제거해주시면 좋을 것 같아요.

2019-11-09 13:15 UTC, BeokBeok commented on bean628/MyProject/app/src/main/res/values/strings.xml
> +
개행은 한 줄 단위로 해주시면 좋을 것 같아요.

2019-11-09 13:15 UTC, BeokBeok commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/data/source/remote/NaverRemoteDataSourceImpl.kt
> +
개행은 한 줄 단위로 해주시면 좋을 것 같아요.

2019-11-09 13:15 UTC, BeokBeok commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/data/source/remote/NaverRemoteDataSourceImpl.kt
> +                    callBack.onFailure(R.string.toast_network_error_msg)
이 부분도 마찬가지로 Exception 을 생성하여 전달해주시면 좋을 것 같아요.

2019-11-09 13:15 UTC, BeokBeok commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/data/source/remote/NaverRemoteDataSource.kt
> +        fun onFailure(stringResId: Int)
throwable 을 전달하게 수정하시게 되면서
stringResId 를 전달하는 함수는 필요하지 않을 것 같아요.

2019-11-09 13:50 UTC, bean628 commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/data/source/remote/NaverRemoteDataSourceImpl.kt
> +                    }
일단 제가 여기 리뷰 부분에서 ifEmpty 함수에 대해 언급했던건 
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/281#discussion_r344157205
요 부분이 생각나서 언급을 했었는데요.

사용하지 말아야 할 이유는 따로 말씀해주시지 않으셔서 이유를 찾아서 검색해봤었습니다.
일단 제가 찾은 이유는 null check를 let 함수로 체크할 때  체크 하려는 변수가 immutable 변수일 경우.
 let 함수를 이용한 널 체크 코드 부분을  java 디컴파일해서 확인해보면 널 체크 작업에 불필요한 변수가 자동으로 선언되서 쓸모없는 코드가 만들어진다. 그래서 immutable 변수의 경우 그냥 != null 을 이용해서 널 체크하는게 더 올바른 null check 라는 것 같더라구요.

그게 생각나서 ifEmpty 함수 부분도 java 디컴파일해서 코드를 보니 위의 경우와 같이 불필요한 변수가 자동으로 선언되더라구요. 그래서 다른 이유가 있는건지 궁금해서 저렇게 물어봤던거였어요~!

2019-11-09 13:53 UTC, bean628 commented on bean628/MyProject/app/src/main/java/common/Constant.kt
> +const val NETWORK_ERROR_MSG = "네트워크 통신 장애입니다."
NaverRemoteDataSourceImpl.kt 파일 26번째 줄에 사용하고 있어요!
response.isSuccessful 의 값이 false 일 때 해당 메시지를 띄우고 있습니다!  :)

2019-11-09 15:03 UTC, bean628 commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/data/source/remote/NaverRemoteDataSourceImpl.kt
> +
지정해주신 곳 외에도 개행 2둘 이상 되어있는 경우 수정했습니다!

6925059d

2019-11-09 15:04 UTC, bean628 commented on bean628/MyProject/app/src/main/res/values/strings.xml
> +
지정해주신 곳 외에도 개행 2둘 이상 되어있는 경우 수정했습니다!

6925059d

2019-11-09 15:05 UTC, bean628 commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/data/source/remote/NaverRemoteDataSourceImpl.kt
> +                    callBack.onFailure(R.string.toast_network_error_msg)
수정을 하다보니 https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/281#discussion_r344443643
이 리뷰와 작업부분이 어느정도 겹쳐서 한번에 작업 했습니다

6ca56e43

2019-11-09 15:05 UTC, bean628 commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/data/source/remote/NaverRemoteDataSource.kt
> +        fun onFailure(stringResId: Int)
수정을 하다보니 https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/281#discussion_r344443589
이 리뷰와 작업부분이 어느정도 겹쳐서 한번에 작업 했습니다

6ca56e43

2019-11-09 15:40 UTC, BeokBeok commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/data/source/remote/NaverRemoteDataSourceImpl.kt
> +                    }
> 사용하지 말아야 할 이유는 따로 말씀해주시지 않으셔서 이유를 찾아서 검색해봤었습니다.
일단 제가 찾은 이유는 null check를 let 함수로 체크할 때 체크 하려는 변수가 immutable 변수일 경우.
let 함수를 이용한 널 체크 코드 부분을 java 디컴파일해서 확인해보면 널 체크 작업에 불필요한 변수가 자동으로 선언되서 쓸모없는 코드가 만들어진다. 그래서 immutable 변수의 경우 그냥 != null 을 이용해서 널 체크하는게 더 올바른 null check 라는 것 같더라구요.
> > A : 영제님이 말씀하신 개념이 맞습니다.

> 그게 생각나서 ifEmpty 함수 부분도 java 디컴파일해서 코드를 보니 위의 경우와 같이 불필요한 변수가 자동으로 선언되더라구요. 
> > A : 말씀하신 내용은 처음 알게 되었습니다. 
> > ifEmpty 가 내부적으로는 다음과 같이 되어 있어서 사용했습니다.
> >```
> >    if (isEmpty()) defaultValue() else this
> >```
> > `ifEmpty` 사용이 내키지 않으시다면, if 문을 사용하셔서 처리하시면 좋을 것 같습니다.

2019-11-09 15:40 UTC, BeokBeok commented on bean628/MyProject/app/src/main/java/common/Constant.kt
> +const val NETWORK_ERROR_MSG = "네트워크 통신 장애입니다."
말씀하신 라인을 찾아가보면 다음과 같이 되어있습니다.
`callBack.onFailure(ResponseNotSuccessException(R.string.toast_network_error_msg))`

즉, NETWORK_ERROR_MSG 변수는 사용하지 않는 것으로 보입니다.

2019-11-10 00:39 UTC, bean628 commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/data/source/remote/NaverRemoteDataSourceImpl.kt
> +                    }
저는 개인적으로 편한걸 더 좋아하는 스타일이라 동작이 무거워지는 경우가 아닌 이상은 let, ifEmpty 둘 다 immutable 변수여도 사용하고 넘어가고 싶은 작은 소망이...... ㅋㅋㅋㅋㅋ 있어요 ㅋㅋ
현석님 덕분에 ifEmpty 함수를 알게됐습니다~! 리뷰 감사합니다!

2019-11-10 00:39 UTC, bean628 commented on bean628/MyProject/app/src/main/java/common/Constant.kt
> +const val NETWORK_ERROR_MSG = "네트워크 통신 장애입니다."
헐 감기약에 취해서 제가 완전 다른걸 보고 있었네요 ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ
죄송합니다ㅋㅋㅋㅋ

수정했습니다.
c4fae40

2019-11-10 00:53 UTC, BeokBeok submitted a review, later dismissed
LGTM:ok_hand:

2019-11-10 07:53 UTC, sjjeong requested changes

2019-11-10 07:53 UTC, sjjeong commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/MainActivity.kt
> +    private var naverRemoteDataSourceImpl =
Impl을 안붙이셔도 됩니다.
let으로 변경해주세요

2019-11-10 07:53 UTC, sjjeong commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/Extension.kt
> +package com.practice.achitecture.myproject
Extension이라고 파일명을 지으면 다른 extension도 들어와야해서 규모가 커지게 됩니다.
다른사람들꺼를 보면 보통
XxxExtension이나 XxxExt라는 이름으로 파일명을 합니다.

2019-11-10 08:03 UTC, bean628 commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/MainActivity.kt
> +    private var naverRemoteDataSourceImpl =
수정했습니다!
1f14c4a

2019-11-10 08:03 UTC, bean628 commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/Extension.kt
> +package com.practice.achitecture.myproject
수정했습니다!

0b08d645

2019-11-10 08:59 UTC, sjjeong approved these changes

2019-11-10 12:04 UTC, ironelder approved these changes

2019-11-10 12:59 UTC, merged