[HW-2] DataSource, DataRepository 구조 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #282
Opened 2019-11-09 08:11 UTC by buddman1208

@developerkhm 과제 제출 너무 늦었지요 죄송합니다 ㅠㅠ 여유 되실때 리뷰 부탁드리겠습니다..

2019-11-10 00:14 UTC, developerkhm submitted a review, later dismissed

2019-11-10 08:00 UTC, sjjeong requested changes

2019-11-10 08:00 UTC, sjjeong commented on buddman1208/ArchitectureStudy/app/src/main/java/com/buddman1208/architecturestudy/data/NaverData.kt
> +interface NaverData {
NaverDataSource처럼 Source를 붙여주세요.
그리고 Remote인지 Local인지 구분해주세요
NaverRemoteDataSource로 변경 해주세요

2019-11-10 08:00 UTC, sjjeong commented on buddman1208/ArchitectureStudy/app/src/main/java/com/buddman1208/architecturestudy/repo/NaverDataRepositoryImpl.kt
> +            .subscribeOnIO()
이것은 Remote에서 추가해주시면 됩니다.

2019-11-10 08:00 UTC, sjjeong commented on buddman1208/ArchitectureStudy/app/src/main/java/com/buddman1208/architecturestudy/repo/NaverDataRepositoryImpl.kt
> +            .observeOn(AndroidSchedulers.mainThread())
observeOn과 subscribe 는 view단에서 처리해주시면 됩니다.
그래서 Rx를 쓰면 DataSource에 success나 failure없이 Observable이나 Single를 retrun 시켜주시면 됩니다.

2019-12-01 04:28 UTC, buddman1208 commented on buddman1208/ArchitectureStudy/app/src/main/java/com/buddman1208/architecturestudy/data/NaverData.kt
> +interface NaverData {
수정했습니다!
커밋 : e795f3b

2019-12-01 04:29 UTC, buddman1208 commented on buddman1208/ArchitectureStudy/app/src/main/java/com/buddman1208/architecturestudy/repo/NaverDataRepositoryImpl.kt
> +            .subscribeOnIO()
수정했습니다!
커밋 : 9b8772a

2019-12-01 04:29 UTC, buddman1208 commented on buddman1208/ArchitectureStudy/app/src/main/java/com/buddman1208/architecturestudy/repo/NaverDataRepositoryImpl.kt
> +            .observeOn(AndroidSchedulers.mainThread())
수정했습니다!
커밋 : 9b8772a

2019-12-01 09:43 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-12-03 01:18 UTC, merged