HW-3 샘플 프로젝트 MVP로 변환 작업
sjjeong/GoogryAndroidArchitecutreStudy pull request #283
Opened 2019-11-10 14:41 UTC by bean628

진혁님~ 리뷰 부탁드려요~~~

2019-11-11 10:26 UTC, ironelder commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/BaseView.kt
> +}
BaseView와 BasePresenter가 하는일이 없는 것 같습니다

2019-11-11 10:26 UTC, ironelder commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/main/MainContract.kt
> +        BaseView<Presenter> {
Presenter타입을 사용하는 곳이 없으니 제거해도 될 것 같습니다~

2019-11-11 10:26 UTC, ironelder commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/main/MainPresenter.kt
> +    private val repository: NaverRepository
NaverRepository의 경우 object로 구현되었기 때문에 별도로 인자로 받지 않고 바로 접근할 수 있을 것 같습니다~

2019-11-13 13:51 UTC, bean628 commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/main/MainPresenter.kt
> +    private val repository: NaverRepository
수정했습니다~

7bbba06

2019-11-15 15:24 UTC, sjjeong requested changes
`abstract class BaseActivity`와 `abstract class BasePresenter`를 만든다음
```kotlin
interface BaseContract {
    interface View
    interface Presenter
}
```
를 각각 BaseActivity와 BasePresenter에 Implements 해주세요.

2019-11-15 15:24 UTC, sjjeong commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/main/MainActivity.kt
> +            makeToast(R.string.toast_empty_word)
word가 비어있는지에 대한 로직이 view에 있으면 안됩니다.
presenter로 옮겨주세요.

2019-11-15 15:24 UTC, sjjeong commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/main/MainActivity.kt
> +        when (this@MainActivity.searchType) {
해당 코드는 presenter에서 처리 해주셔야합니다.
어떤것을 보여줄지는 view에서 처리하는게 아닙니다.
view에서는 searchMovieAndBookAdapter를 보여주는것과 searchBlogAndNewsAdapter를 보여주는 것만 있으면 됩니다.

2019-11-15 15:24 UTC, sjjeong commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/main/MainActivity.kt
> +        presenter.searchWordByNaver(category, word)
searchType에 따라 category를 구하는 로직은 presenter에 있으면 됩니다.
view에서는 사용자가 입력한 text를 presenter로 보내주기만 하면 됩니다.

2019-11-15 15:24 UTC, sjjeong commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/main/MainContract.kt
> +        fun searchingOnSuccess(items: List<SearchedItem>)
showSearchResult 정도면 좋을 것 같습니다.

2019-11-19 13:35 UTC, bean628 commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/main/MainActivity.kt
> +            makeToast(R.string.toast_empty_word)
수정했습니다~!

72fa59b2

2019-11-19 13:35 UTC, bean628 commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/main/MainActivity.kt
> +        when (this@MainActivity.searchType) {
수정했습니다~
f60002eb

2019-11-19 13:37 UTC, bean628 commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/main/MainActivity.kt
> +        presenter.searchWordByNaver(category, word)
위에서 비어있는 검사로직 presenter에서 처리하도록 수정하고 뒤늦게 봐가지고 같이 수정됐어요

72fa59b2

2019-11-19 13:37 UTC, bean628 commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/main/MainContract.kt
> +        fun searchingOnSuccess(items: List<SearchedItem>)
수정했습니다~~ 

0c5eba26

2019-11-19 13:39 UTC, bean628 commented
> `abstract class BaseActivity`와 `abstract class BasePresenter`를 만든다음
> 
> ```kotlin
> interface BaseContract {
>     interface View
>     interface Presenter
> }
> ```
> 
> 를 각각 BaseActivity와 BasePresenter에 Implements 해주세요.

어떻게 해야할지 모르겠어요ㅋㅋㅋ
도움이 필요합니다!!!

2019-11-20 14:19 UTC, sjjeong commented
> > `abstract class BaseActivity`와 `abstract class BasePresenter`를 만든다음
> > ```kotlin
> > interface BaseContract {
> >     interface View
> >     interface Presenter
> > }
> > ```
> > 
> > 
> > 를 각각 BaseActivity와 BasePresenter에 Implements 해주세요.
> 
> 어떻게 해야할지 모르겠어요ㅋㅋㅋ
> 도움이 필요합니다!!!

이거는 제가 스터디날에 알려드릴게요

2019-11-20 14:20 UTC, sjjeong approved these changes

2019-12-01 05:06 UTC, ironelder approved these changes

2019-12-01 05:11 UTC, merged