HW-3-프로젝트에 MVP 패턴 적용하기
sjjeong/GoogryAndroidArchitecutreStudy pull request #285
Opened 2019-11-12 11:58 UTC by ironelder

HW-3-프로젝트에 MVP 패턴 적용하기

2019-11-13 13:43 UTC, bean628 requested changes
리뷰 작성했어요~
잘 부탁드립니다~

2019-11-13 13:43 UTC, bean628 commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/component/CustomListViewAdapter.kt
>      }
이 부분 2번씩 불려요~!
음 예를 들어 nice 라는 검색어를 블로그 타입으로 검색하면 처음엔 한번만 통신하는데
 다시 검색하면 그 다음부터는 2번씩 통신되는 것 같더라구요. 
제가 확인을 잘못한걸수도 있으니 한번 테스트 해보시고 버그면 수정 부탁드려요~

2019-11-13 13:43 UTC, bean628 commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/view/mainview/MainFragment.kt
> +                )
View와 Presenter는 1:1로 서로가 서로를 알고있는 강한 결합을 하는데
presenter가 NonNullable한 상태여야할 것 같아요

2019-11-13 13:43 UTC, bean628 commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/view/mainview/MainPresenter.kt
> +    }
이 클래스에서도 마찬가지로 view가 NonNullable한 상태여야할 것 같아요

2019-11-14 10:40 UTC, ironelder commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/component/CustomListViewAdapter.kt
>      }
검색 후에 포커스를 제거해주지 않아서 두번 불리는 문제가 있었습니다.
수정 하였습니다
4bbec92

2019-11-14 11:09 UTC, ironelder commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/view/mainview/MainFragment.kt
> +                )
추후에 Fragment가 여러개가 존재할 경우 별도의 Presenter를 선언하거나 View선언할 필요없이 Base를통하여 자동으로 View와 Presenter를 주입시키고, 프라그먼트가 이동하여 distach될 경우 자동으로 View를 해지하도록 개발해 보았습니다.
현재 화면에서는 Fragment가 1개라 해당 nullable을 제거하였습니다

ab644b7

2019-11-14 11:09 UTC, ironelder commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/view/mainview/MainPresenter.kt
> +    }
추후에 Fragment가 여러개가 존재할 경우 별도의 Presenter를 선언하거나 View선언할 필요없이 Base를통하여 자동으로 View와 Presenter를 주입시키고, 프라그먼트가 이동하여 distach될 경우 자동으로 View를 해지하도록 개발해 보았습니다.
현재 화면에서는 Fragment가 1개라 해당 nullable을 제거하였습니다

ab644b7

2019-11-14 13:56 UTC, bean628 commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/view/mainview/MainPresenter.kt
> +    }
그런거였군요~
다른 사람의 코드를 보고 의도를 파악하는건 많이 어렵네요 ㅠㅠ

2019-11-14 23:31 UTC, ironelder commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/view/mainview/MainPresenter.kt
> +    }
저도 외부에서 설명 첨부된 부분을 줍줍해왔습니당 ㅠㅠㅋ

2019-11-15 16:55 UTC, sjjeong requested changes

2019-11-15 16:55 UTC, sjjeong commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/view/baseview/BaseFragment.kt
> +    abstract fun onCreatePresenter(): PRESENTER
이 함수는 불필요해보입니다.
lateinit var로 선언한 presenter를 abstract val로 선언하면 됩니다.

2019-11-15 16:55 UTC, sjjeong commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/view/baseview/BaseFragment.kt
> +abstract class BaseFragment<in VIEW : BaseContract.View, PRESENTER : BaseContract.Presenter<VIEW>>(
BaseFragment는 BaseContract.View를 implements 해야 합니다.

2019-11-16 08:21 UTC, ironelder commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/view/baseview/BaseFragment.kt
> +    abstract fun onCreatePresenter(): PRESENTER
와 저 함수 계속 걸리적 거렸는데..!! 감사합니다 ㅎㅎ
수정하였습니다~!

80fe4d9

2019-11-16 08:22 UTC, ironelder commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/view/baseview/BaseFragment.kt
> +abstract class BaseFragment<in VIEW : BaseContract.View, PRESENTER : BaseContract.Presenter<VIEW>>(
BaseFragment에서 BaseContract.View를 implements 하도록 수정하였습니다~

23e1a11

2019-11-16 09:54 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-11-18 12:24 UTC, bean628 approved these changes

2019-11-18 23:15 UTC, merged