HW-3 MVP 구조 변경 작업
sjjeong/GoogryAndroidArchitecutreStudy pull request #286
Opened 2019-11-12 12:31 UTC by 2giwon

1.  BaseView, BasePresenter 생성하여 적용하도록 수정
2. Presenter 생성
3. onBindViewHolder에서 타입 String 으로 구분하여 ImageView의 Visible 상태를 조정하던것 수정
4. viewType으로 구분하여 ViewHolder를 생성하도록 수정

2019-11-14 12:15 UTC, taeiim commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/tabs/Tab.kt
> +    }
api 보내는 목적으로 생성하신 것 같은데 !
.name 사용해서 (Tabs.BLOG.name) 해서 대문자로 보내도 api 응답 잘 오더라구요 !
그치만 이건 수정하셔도 되고 안하셔도 되고 상관없을 것 같습니다!!

2019-11-14 12:15 UTC, taeiim commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/tabs/ContentsFragment.kt
> +            NaverDataRepository(NaverRemoteDataSource())
```suggestion
            NaverDataRepository(NaverRemoteDataSource.getInstance())

```

2019-11-14 12:15 UTC, taeiim commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/tabs/ContentsFragment.kt
> +            NaverDataRepository(NaverRemoteDataSource())
`NaverRemoteDataSource.kt` 에는 getInstance() 만들어 놓으시고 생성할때는 사용하고 계시지 않는것 같습니다 🧐

2019-11-14 12:15 UTC, taeiim commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/tabs/ContentsFragment.kt
> +        }
exception 검사하는 이유가 있으신가요?? 궁금해서요 ! ㅎㅎ

2019-11-15 20:18 UTC, 2giwon commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/tabs/ContentsFragment.kt
> +        }
bundle로 tab enum을 가져올때 지연 초기화를 통해서 가져오는데 최초 사용 시점이

setAdapter일때라서 exception을 추가했습니다.

bundle로 가져올때 illigalException을 염두해서 그렇습니다.

2019-11-15 20:21 UTC, 2giwon commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/tabs/Tab.kt
> +    }
수정했습니다^^
60d946f6027fd8104889415c624d42c85bfbe685

2019-11-18 02:59 UTC, sjjeong requested changes

2019-11-18 02:59 UTC, sjjeong commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/base/BasePresenter.kt
> +interface BasePresenter {
abstract class BasePresenter를 따로 만들고
```kotlin
interface BaseContract {
    interface View
    interface Presenter
}
```
형태로 만들어야 합니다.

2019-11-18 02:59 UTC, sjjeong commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/base/BaseView.kt
> +interface BaseView<T> {
BaseFragment가 implement 하게 해주세요

2019-11-18 02:59 UTC, sjjeong commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/base/BaseViewHolder.kt
> +    val tvTitle: TextView = itemView.tv_title
BaseViewHolder는 범용적으로 사용하는 느낌이 강합니다.
특정 View가 들어간다면 BaseViewHolder보다는 BaseXxxViewHolder로 하는게 좋습니다.

2019-11-18 02:59 UTC, sjjeong commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/tabs/ContentsAdapter.kt
> +            (holder as? ImageViewHolder)?.run {
BaseViewHolder에 abstract fun bind(item: T)를 만들어서 처리하면 onBindViewHolder 내부는
```kotlin
holder.bind(list[position])
```
만 있을 수 있습니다.

2019-11-18 02:59 UTC, sjjeong commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/tabs/ContentsPresenter.kt
> +    val naverDataRepository: NaverDataRepository
contentsView와 naverDataRepository 둘다 private으로 만들어주세요

2019-11-18 02:59 UTC, sjjeong commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/tabs/ContentsPresenter.kt
> +            query = query,
요청하기전에 query가 빈값인지 체크해주세요
빈값이면 에러를 보여주는 작업도 추가해주세요

2019-11-18 02:59 UTC, sjjeong commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/ext/ImageViewExt.kt
> +fun ImageView.loadAsync(url: String?, block: BaseRequestOptions<RequestOptions>) =
사용하는 쪽이
```kotlin
holder.imageThumbnail.loadAsync(list[position].image){
    placeholder(R.mipmap.ic_launcher)
}
```
이렇게 되도록 변경해보세요.

extension function과 higher-order function 기능을 잘 활용하면 됩니다.

2019-11-18 02:59 UTC, sjjeong commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/tabs/ContentsPresenter.kt
> +                    contentsView.onUpdateUi(list)
List가 비어있을 때 `검색 결과가 없습니다.`라는 내용을 사용자에게 보여주세요.

2019-11-18 15:22 UTC, 2giwon commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/base/BasePresenter.kt
> +interface BasePresenter {
수정했습니다 
b1536bf42c8ff491951c127c8f56c73b6b06323c

2019-11-18 15:23 UTC, 2giwon commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/base/BaseView.kt
> +interface BaseView<T> {
BaseFragment에서 implement하도록 수정했습니다.
7b5c25fcd830ca65f78359cddabf6b14d94e3a1c

2019-11-18 17:04 UTC, 2giwon commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/base/BaseViewHolder.kt
> +    val tvTitle: TextView = itemView.tv_title
수정했습니다.
3f53f343fc99570ed9d5cbe8bb22a53989ac336c

2019-11-18 17:04 UTC, 2giwon commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/tabs/ContentsAdapter.kt
> +            (holder as? ImageViewHolder)?.run {
이렇게도 할 수 있군요 
수정했습니다.

33bfa696572bed6c935bfcb57356cf359e82e11a

2019-11-18 17:05 UTC, 2giwon commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/tabs/ContentsPresenter.kt
> +    val naverDataRepository: NaverDataRepository
private 으로 변경 했습니다.
2dfa80a1dfe732d2aafb2c6e92a654cf56e30abc

2019-11-18 17:05 UTC, 2giwon commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/tabs/ContentsPresenter.kt
> +            query = query,
빈값이면 onFail로 던지도록 수정했습니다.
e6a75ba6836c97f4e4e441e6374b4fffca5903e7

2019-11-18 17:06 UTC, 2giwon commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/tabs/ContentsPresenter.kt
> +                    contentsView.onUpdateUi(list)
리스트가 비어있을때 에러 문구를 띄우도록 수정했습니다.
e6a75ba6836c97f4e4e441e6374b4fffca5903e7

2019-11-18 17:37 UTC, 2giwon commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/ext/ImageViewExt.kt
> +fun ImageView.loadAsync(url: String?, block: BaseRequestOptions<RequestOptions>) =
수정했습니다. 하이오더펑션이 익숙치 않아서 이렇게 하는건지 잘모르겠습니다.
더 나은방법이나 조언 부탁드립니다.

b0b8a959bb55d555672884b37b5c0cd3a79e4075

2019-11-20 13:56 UTC, sjjeong requested changes

2019-11-20 13:56 UTC, sjjeong commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/base/BaseView.kt
> +interface BaseView<T> : BaseContract.View<T> {
이 파일은 삭제 하셔도 됩니다.

2019-11-20 13:56 UTC, sjjeong commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/ext/ImageViewExt.kt
> +        .apply(block.invoke(RequestOptions()))
제가 알려드린 방식으로 변경해주세요

2019-11-20 13:56 UTC, sjjeong commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/tabs/ContentsFragment.kt
> +    override val presenter: BasePresenter =
BasePresenter가 아닌 ContentContract.Presenter로 되게 해주세요

2019-11-21 15:22 UTC, 2giwon commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/base/BaseView.kt
> +interface BaseView<T> : BaseContract.View<T> {
이 파일이 삭제 되면 BaseFragment는 아무것도 Implement 하지 않아도 되나요?

2019-11-21 15:31 UTC, 2giwon commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/ext/ImageViewExt.kt
> +        .apply(block.invoke(RequestOptions()))
수정했습니다.
38f4f6df0d9bbf59fba35e6b8d1e022f5880fa3d

2019-11-21 15:32 UTC, 2giwon commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/tabs/ContentsFragment.kt
> +    override val presenter: BasePresenter =
BasePresenter -> ContentContract.Presenter로 수정했습니다.
59f19d0bc84ffb54061528f10f9447a6d1cd259d

2019-11-21 15:40 UTC, sjjeong commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/base/BaseView.kt
> +interface BaseView<T> : BaseContract.View<T> {
abstract class BaseFragment: Fragment(), BaseContract.View<T>
이런 형태로 가시면 돼요!

2019-11-22 14:18 UTC, 2giwon commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/base/BaseView.kt
> +interface BaseView<T> : BaseContract.View<T> {
수정했습니다.
1a96653a4fab66bde368e4f81b274d90dd53fc06

2019-11-22 16:33 UTC, sjjeong approved these changes

2019-11-23 01:59 UTC, taeiim approved these changes
LGTM 👏

2019-11-23 07:31 UTC, merged