HW-3 MVP 구조 변경 작업
sjjeong/GoogryAndroidArchitecutreStudy pull request #287
Opened 2019-11-14 18:11 UTC by taeiim

- View, Presenter 추가
- RecyclerView ViewHolder 각자 따로 만들어서 onCreateViewHolder에서 분기하도록 변경

2019-11-15 19:58 UTC, 2giwon requested changes
viewHolder를 저런식으로 처리하는 것도 나쁘지 않네요

코드 보면서 많이 배웁니다.

2019-11-15 19:58 UTC, 2giwon commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/ContentsFragment.kt
> +            searchEditTv.text.toString().let { presenter.searchContents(searchType.name, it) }
```suggestion
searchBtn.setOnClickListener {
            presenter.searchContents(
                searchType.name,
                searchEditTv.text.toString()
            )
        }
```
이렇게 하는 것도 나쁘지 않을 것 같습니다.

2019-11-15 19:58 UTC, 2giwon commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/SearchResultRecyclerAdapter.kt
> +            itemView.subTitleTv.visibility = View.GONE
visibility 를 없애고자 createViewHolder에서 처리를 하자고 했는데

bind에서 view.GONE을 해주는 건 의미가 없어 보입니다.

layout을 나눠서 만드는건 어떨까요?

2019-11-15 19:58 UTC, 2giwon commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/SearchResultRecyclerAdapter.kt
> +                Glide.with(itemView)
3rd party 라이브러리를 wrapper클래스로 빼는게 좋다고 들었습니다.

2019-11-15 19:58 UTC, 2giwon commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/SearchResultRecyclerAdapter.kt
>                  thumbnailIv.visibility = View.VISIBLE
굳이 visible 처리를 할 필요가 있나요?

glide에 placeHolder로 디폴트 이미지를 넣는건 어떨까요?ㅎ

2019-11-17 13:14 UTC, taeiim commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/ContentsFragment.kt
> +            searchEditTv.text.toString().let { presenter.searchContents(searchType.name, it) }
반영했습니다 감사합니다 ㅎㅎ ~

2019-11-17 14:00 UTC, taeiim commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/SearchResultRecyclerAdapter.kt
> +                Glide.with(itemView)
반영했습니다 ㅎㅎ 

commit : e79fb044409f6ccddd275a278cd35cceed8bea1b

2019-11-17 14:01 UTC, taeiim commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/SearchResultRecyclerAdapter.kt
>                  thumbnailIv.visibility = View.VISIBLE
수정했습니다!! 

commit : a7ad61da730bbc6c299e0b69cb1d67aadcb3acb8

2019-11-17 14:06 UTC, taeiim commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/SearchResultRecyclerAdapter.kt
> +            itemView.subTitleTv.visibility = View.GONE
visibility를 없애고자 viewholder를 분리한 것이 아니라, 
분기를 제거할 목적으로 나누었다고 생각합니다.

News 일때 저런 처리를 한다는 것이고, 기획에 따라서 NewsViewHolder의 구성이 
visible GONE 외에도 다른 것이 추가 될 수도 있다고 생각합니다 ㅜㅜ 
단순히 subTitle visibility 때문에 layout을 나눌 필요가 있을까요?? ㅎㅎ

2019-11-18 14:38 UTC, 2giwon submitted a review, later dismissed
LGTM 👍

2019-11-18 14:38 UTC, 2giwon commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/SearchResultRecyclerAdapter.kt
> +            itemView.subTitleTv.visibility = View.GONE
bind 메소드는 onBindViewHolder에서 자주 호출되는 메소드 인거 같은데
여기서 되도록이면 작업을 최소화 해야 한다고 생각했습니다. 

자주 호출되는 메소드에서 visibility 처리가 잦다 보면 아무래도 layout onMesure나 layout 내의 위젯들의 위치를 조정하는
작업이 한번 더 될 거 같다고 생각해서 그런부분을 최소화 해야 한다고 생각했습니다.

현재로써는 다른 추가 기능이 없으니 고려해볼 문제 인 것 같습니다.

2019-11-20 15:03 UTC, sjjeong requested changes

2019-11-20 15:03 UTC, sjjeong commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/ContentsFragment.kt
> +searchBtn.setOnClickListener {
setOnClickListener가 왜 두번 있나요?

2019-11-20 15:03 UTC, sjjeong commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/ContentsPresenter.kt
> +    override fun searchContents(searchType: String, query: String) {
query가 비어있을 때 처리도 추가해주세요

2019-11-20 15:03 UTC, sjjeong commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/SearchResultRecyclerAdapter.kt
> +    abstract class BaseViewHolder<T>(itemView: View) : RecyclerView.ViewHolder(itemView) {
BaseViewHolder 구현이 조금 이상하지만 이부분은 스터디때 알려드릴게요

2019-11-22 15:14 UTC, taeiim commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/ContentsFragment.kt
> +searchBtn.setOnClickListener {
commit suggestion 해주신 것을 바로 적용하면서 문제가 발생했던 것 같습니다 !  
수정했습니다 ㅎㅎ 

commit : 6af310e997416958eb84a64d569cb415c896c19b

2019-11-22 15:14 UTC, taeiim commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/ContentsPresenter.kt
> +    override fun searchContents(searchType: String, query: String) {
추가했습니다~~ 

commit : 951663b2a2d856f5798f7037b80b2cb8e04f45f4

2019-11-22 15:14 UTC, taeiim commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/SearchResultRecyclerAdapter.kt
> +    abstract class BaseViewHolder<T>(itemView: View) : RecyclerView.ViewHolder(itemView) {
넵 감사합니당

2019-11-22 16:35 UTC, sjjeong approved these changes

2019-11-23 01:18 UTC, 2giwon approved these changes

2019-11-23 01:59 UTC, merged