HW- 2-1 BaseCurrency , 검색 기능 추가
sjjeong/GoogryAndroidArchitecutreStudy pull request #29
Opened 2019-05-15 16:23 UTC by GongSulMin

2019-05-18 06:46 UTC, improve777 commented on gongsulmin/StudyGong/app/src/main/res/layout/dialog_coin_market.xml
> +    <!--<TextView-->
앞으로도 안 쓸거 같아요

2019-05-18 06:46 UTC, improve777 commented on gongsulmin/StudyGong/app/src/main/res/layout/dialog_coin_detail.xml
> +    </android.support.v7.widget.RecyclerView>
레이아웃도 reformat code 해주셔야 할 듯 싶습니다

2019-05-18 06:46 UTC, improve777 commented on gongsulmin/StudyGong/app/src/main/java/my/gong/studygong/mvp/base/BaseDialog.kt
> +            width = resources.displayMetrics.widthPixels / 10 * 8
apply 를 안써도 될것 같아요
Uint 을 명시하지 않아도 되네요
setPosition 메소드에 범위지정자를 붙이는게 좋을 것 같아요

2019-05-18 06:46 UTC, improve777 commented on gongsulmin/StudyGong/app/src/main/java/my/gong/studygong/mvp/presenter/coindetail/CoinDetailContract.kt
> +        fun errorCoinDetail(erroeMsg: String)
인자명 오타입니다

2019-05-18 06:46 UTC, improve777 commented on gongsulmin/StudyGong/app/src/main/java/my/gong/studygong/mvp/presenter/coindetail/CoinDetailContract.kt
> +package my.gong.studygong.mvp.presenter.coinmarketlist
코틀린은 패키지명이 동일하지 않아도 되긴 하는데 그래도 맞춰주는게 좋을 것 같아요

2019-05-18 06:46 UTC, improve777 commented on gongsulmin/StudyGong/app/src/main/java/my/gong/studygong/data/source/upbit/UpbitRepository.kt
> +                                it.market.substring(0, it.market.indexOf("-"))
`startsWidth` 로 하는게 어떨까요?

2019-05-18 06:46 UTC, improve777 commented on gongsulmin/StudyGong/app/src/main/java/my/gong/studygong/mvp/view/CoinMarketDialog.kt
> +            clickCoinMaketListener = {
여기도 오타 발견!

2019-05-18 06:46 UTC, improve777 commented on gongsulmin/StudyGong/app/src/main/java/my/gong/studygong/mvp/view/CoinMarketDialog.kt
> +                dismissDialog.invoke(it)
변수명이 다이얼로그 종료의 의미 같았는데 역할은 마켓 string 을 던져주는 것  같아요
그런데 dismiss 는 별도로 아래에 호출해서 의미가 맞지 않는 것 같아요

2019-05-18 08:58 UTC, sabgilhun requested changes
수고하셨습니다 👍

2019-05-18 08:58 UTC, sabgilhun commented on gongsulmin/StudyGong/app/src/main/java/my/gong/studygong/data/source/upbit/UpbitRepository.kt
> +    override fun getCoinCurrency(
getCoinCurrency에서 받아오는 결과가 보통 바뀌게 되는 경우가 없으니까 처음에만 서버에서 가져온 후 캐시로 저장하고 다음에 요청할 땐 캐시 된 값을 리턴하는 방법을 사용하는건 어떤가요?

2019-05-18 08:58 UTC, sabgilhun commented on gongsulmin/StudyGong/app/src/main/java/my/gong/studygong/mvp/base/BaseDialog.kt
> +    fun setPosition(): Unit {
접근 지정자를 private나 protected로 해주는게 좋을것 같습니다.

2019-05-18 08:58 UTC, sabgilhun commented on gongsulmin/StudyGong/app/src/main/java/my/gong/studygong/mvp/view/CoinListActivity.kt
> +    val presenter: CoinListContract.Presenter by lazy {
private으로 해주어도 될것 같습니다.

2019-05-22 12:09 UTC, GongSulMin commented on gongsulmin/StudyGong/app/src/main/res/layout/dialog_coin_market.xml
> +    <!--<TextView-->
d87ff6e
수정하였습니다~

2019-05-22 12:09 UTC, GongSulMin commented on gongsulmin/StudyGong/app/src/main/res/layout/dialog_coin_detail.xml
> +    </android.support.v7.widget.RecyclerView>
d87ff6e
수정하였습니다~

2019-05-22 12:09 UTC, GongSulMin commented on gongsulmin/StudyGong/app/src/main/java/my/gong/studygong/mvp/presenter/coindetail/CoinDetailContract.kt
> +        fun errorCoinDetail(erroeMsg: String)
d87ff6e
수정하였습니다~

2019-05-22 12:09 UTC, GongSulMin commented on gongsulmin/StudyGong/app/src/main/java/my/gong/studygong/mvp/presenter/coindetail/CoinDetailContract.kt
> +package my.gong.studygong.mvp.presenter.coinmarketlist
d87ff6e
수정하였습니다~

2019-05-22 12:11 UTC, GongSulMin commented on gongsulmin/StudyGong/app/src/main/java/my/gong/studygong/mvp/view/CoinMarketDialog.kt
> +            clickCoinMaketListener = {
d87ff6e
수정하였습니다~

2019-05-22 12:12 UTC, GongSulMin commented on gongsulmin/StudyGong/app/src/main/java/my/gong/studygong/mvp/base/BaseDialog.kt
> +            width = resources.displayMetrics.widthPixels / 10 * 8
f9901b7
수정하였습니다~

2019-05-22 12:12 UTC, GongSulMin commented on gongsulmin/StudyGong/app/src/main/java/my/gong/studygong/mvp/view/CoinListActivity.kt
> +    val presenter: CoinListContract.Presenter by lazy {
f9901b7
수정하였습니다~

2019-05-22 12:12 UTC, GongSulMin commented on gongsulmin/StudyGong/app/src/main/java/my/gong/studygong/mvp/base/BaseDialog.kt
> +    fun setPosition(): Unit {
f9901b7
수정하였습니다~

2019-05-22 12:13 UTC, GongSulMin commented on gongsulmin/StudyGong/app/src/main/java/my/gong/studygong/data/source/upbit/UpbitRepository.kt
> +    override fun getCoinCurrency(
92d11d1
수정하였습니다~

2019-05-22 12:13 UTC, GongSulMin commented on gongsulmin/StudyGong/app/src/main/java/my/gong/studygong/mvp/view/CoinMarketDialog.kt
> +                dismissDialog.invoke(it)
8266155
수정하였습니다~

2019-05-22 12:18 UTC, GongSulMin commented on gongsulmin/StudyGong/app/src/main/java/my/gong/studygong/data/source/upbit/UpbitRepository.kt
> +                                it.market.substring(0, it.market.indexOf("-"))
BaseCurrecy를 중복없이 list로 가져오고 있는데
`startswith` 로는 방법이 떠올르지 않네요
괜찮은 방법 있을까요??

2019-05-22 14:52 UTC, sabgilhun approved these changes

2019-05-23 02:47 UTC, improve777 commented on gongsulmin/StudyGong/app/src/main/java/my/gong/studygong/mvp/view/CoinListActivity.kt
> +        }
음... 석준님께서 말씀하신 방법이 액티비티에서 다이얼로그의 리스너를 set 해준다기보다
```kotlin
// CoinMarketDialog 의 onAttach()
dialogCallBackListener = {
            (activity as CoinListActivity).onClickCoinMarketItem(it)
        }

// CoinListActivity
fun onClickCoinMarketItem(market: String) {
    txt_select_coin_market.text = market
    coinMarket = market
    populateCoin(coinMarket)
}
```
이런 식으로 메소드를 실행한다거나,
```kotlin
// CoinMarketDialog 의 onAttach()
dialogCallBackListener = (activity as CoinListActivity).getDialogCallBackListener()

// CoinListActivity
fun getDialogCallBackListener(): (String) -> Unit {
    return {
        txt_select_coin_market.text = it
        coinMarket = it
        populateCoin(coinMarket)
    }
}
```
이렇게 함수형으로 반환받는 방식이 아닐까요? 
저도 추측이라 확신은 없긴 하네요😅

2019-05-23 13:42 UTC, GongSulMin commented on gongsulmin/StudyGong/app/src/main/java/my/gong/studygong/mvp/view/CoinListActivity.kt
> +        }
직접 코드 까지 작성해주시다니 감사합니당 😍
저도 써보면서 생각을 해봤는데 뭐가 정답이라고 말하기에는 애매한...
다시 한번 여쭈어 봐야겠어요ㅎㅎ 감사합니다!

2019-05-23 15:12 UTC, ddaeyeonkim approved these changes
LGTM 👍👍👍

2019-05-26 06:39 UTC, merged