HW-8 Dagger 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #295
Opened 2019-11-17 23:56 UTC by toctocbin

리뷰 잘부탁드립니다 !

2019-12-04 02:24 UTC, BeokBeok requested changes
안녕하세요. 스터디 2기 강현석이라고 합니다.
부족하지만 잘 부탁드립니다. 😅

2019-12-04 02:24 UTC, BeokBeok commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/UpbitApplication.kt
> +open class UpbitApplication : DaggerApplication() {
`open` 은 제거하셔도 될 것 같아요.

2019-12-04 02:24 UTC, BeokBeok commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/adpter/ViewPagerAdapter.kt
> +class ViewPagerAdapter(fm: FragmentManager) : FragmentStatePagerAdapter(fm, BEHAVIOR_RESUME_ONLY_CURRENT_FRAGMENT) {
안스 3.5.2 기준으로 `BEHAVIOR_RESUME_ONLY_CURRENT_FRAGMENT` 추가 시 빌드 에러가 발생합니다.

2019-12-04 02:24 UTC, BeokBeok commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/data/source/UpbitRepository.kt
> +): UpbitRemoteDataSource {
Repository 가 RemoteDataSource 를 implement 하는 것은 이상해 보이네요.

2019-12-04 02:24 UTC, BeokBeok commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/data/source/UpbitRepository.kt
> +    private val upbitRemoteDataSourceImpl : UpbitRemoteDataSourceImpl
타입을 UpbitRemoteDataSource 로 하시면 좋을 것 같아요.

2019-12-04 02:24 UTC, BeokBeok commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/di/ActivityScope.kt
> +annotation class ActivityScope
해당 scope 는 사용하지 않는 것으로 보이는데,
사용하지 않는다면 제거 하시면 좋을 것 같아요.

2019-12-04 02:24 UTC, BeokBeok commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/di/AppComponent.kt
> +        AndroidSupportInjectionModule::class,
`AndroidSupportInjectionModule` 을 `ApplicationModule` 의 상단으로 위치시키면 좋을 것 같아요.

2019-12-04 02:24 UTC, BeokBeok commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/di/ApplicationModule.kt
> +    @Qualifier
`Qualifier` annotation 은 의미가 없어 보입니다.

2019-12-04 02:24 UTC, BeokBeok commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/di/AppComponent.kt
> +        NetworkModule::class,
NetworkModule 은 Repository 에서 사용하기 때문에
ApplicationModule 에 include 하는 것이 좋을 것 같습니다.

2019-12-04 02:24 UTC, BeokBeok commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/di/ApplicationModule.kt
> +object ApplicationModule {
class 대신 object 를 사용하신 이유가 있나요?

2019-12-04 02:24 UTC, BeokBeok commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/di/ApplicationModule.kt
> +    @JvmStatic
`JvmStatic` annotation 은 제거해도 될 것 같아요.

2019-12-04 02:24 UTC, BeokBeok commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/di/NetworkModule.kt
>          val interceptor = HttpLoggingInterceptor()
`HttpLoggingInterceptor` 도 객체이므로 provide 함수를 만들어주시면 좋을 것 같아요.

2019-12-04 02:24 UTC, BeokBeok commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/di/NetworkModule.kt
> +            .addCallAdapterFactory(RxJava2CallAdapterFactory.create())
`GsonConverterFactory` 와 `RxJava2CallAdapterFactory` 도 객체이므로 provide 함수를 만들어주시면 좋을 것 같아요.

2019-12-04 02:24 UTC, BeokBeok commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/di/ViewModelFactory.kt
> +            throw RuntimeException(e)
Exception 을 throw 하는 것 보다, `error` 함수로 처리하시면 좋을 것 같아요.

2019-12-04 02:24 UTC, BeokBeok commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/ui/market/MarketActivity.kt
> +    override val vm : MarketViewModel by lazy { ViewModelProviders.of(this, viewModelFactory).get(MarketViewModel::class.java) }
가로 줄이 너무 길기 떄문에, 개행 처리 해주시면 좋을 것 같아요.

2019-12-04 02:24 UTC, BeokBeok commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/ui/market/MarketActivity.kt
> +    lateinit var viewModelFactory: ViewModelProvider.Factory
BaseActivity 에 선언하셔서 사용하시면 좋을 것 같아요.

2019-12-04 02:24 UTC, BeokBeok commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/ui/ticker/TickerFragment.kt
> +    lateinit var viewModelFactory: ViewModelProvider.Factory
BaseFragment 에 선언하셔서 사용하시면 좋을 것 같아요.

2019-12-07 08:27 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/adpter/ViewPagerAdapter.kt
> +class ViewPagerAdapter(fm: FragmentManager) : FragmentStatePagerAdapter(fm, BEHAVIOR_RESUME_ONLY_CURRENT_FRAGMENT) {
c51a53b

수정완료.

2019-12-07 08:27 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/UpbitApplication.kt
> +open class UpbitApplication : DaggerApplication() {
e23b008

수정완료.

2019-12-07 08:28 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/data/source/UpbitRepository.kt
> +): UpbitRemoteDataSource {
23240e9

수정완료.

2019-12-07 08:28 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/data/source/UpbitRepository.kt
> +    private val upbitRemoteDataSourceImpl : UpbitRemoteDataSourceImpl
550b696

수정완료.

2019-12-07 08:30 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/di/AppComponent.kt
> +        AndroidSupportInjectionModule::class,
744ef50

수정완료.

2019-12-07 08:33 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/di/ApplicationModule.kt
> +    @Qualifier
2563704

수정완료.

2019-12-07 08:33 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/di/ActivityScope.kt
> +annotation class ActivityScope
c6ee040

파일 제거.

2019-12-07 08:34 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/di/AppComponent.kt
> +        NetworkModule::class,
0f1f369

수정완료.

2019-12-07 08:38 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/di/ApplicationModule.kt
> +object ApplicationModule {
JvmStatic 어노테이션을 사용하기 위해 object로 선언하였는데 피드백 확인해보니 JvmStatic으로 선언하지 않아도 된다고 판단되어서 class로 변경했습니다.

2d5b1b9

적용완료.

2019-12-07 08:38 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/di/ApplicationModule.kt
> +    @JvmStatic
2d5b1b9

적용완료.

2019-12-13 00:42 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/di/NetworkModule.kt
>          val interceptor = HttpLoggingInterceptor()
5c70ea0

적용완료.

2019-12-13 00:42 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/di/NetworkModule.kt
> +            .addCallAdapterFactory(RxJava2CallAdapterFactory.create())
ac8afb0

적용완료.

2019-12-13 00:42 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/ui/market/MarketActivity.kt
> +    override val vm : MarketViewModel by lazy { ViewModelProviders.of(this, viewModelFactory).get(MarketViewModel::class.java) }
c1378e1

적용완료.

2019-12-13 00:42 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/ui/market/MarketActivity.kt
> +    lateinit var viewModelFactory: ViewModelProvider.Factory
c560edd

적용완료.

2019-12-13 00:43 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/ui/ticker/TickerFragment.kt
> +    lateinit var viewModelFactory: ViewModelProvider.Factory
0fb5557

적용완료.

2019-12-13 00:57 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/di/ViewModelFactory.kt
> +            throw RuntimeException(e)
어떻게 처리해야할지 감이 안잡히는데 힌트좀 주실수 있나요 ?!

2019-12-13 00:58 UTC, toctocbin commented
리뷰 남겨주셨는데 늦게 코멘트를 달게되서 너무 죄송합니다 ㅠㅜ
리뷰해주셔서 감사합니다 !

2019-12-13 01:02 UTC, BeokBeok commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/di/ViewModelFactory.kt
> +            throw RuntimeException(e)
```
catch (e: Exception) {
    error(e)
}
``` 

이런식으로 하시면 될 것 같습니다. 😅

2019-12-13 01:20 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/di/ViewModelFactory.kt
> +            throw RuntimeException(e)
```
@kotlin.internal.InlineOnly
public inline fun error(message: Any): Nothing = throw IllegalStateException(message.toString())
```
이 에러함수를 사용하라고 하시는건가욥 ?

2019-12-13 01:22 UTC, BeokBeok commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/di/NetworkModule.kt
>          interceptor.level = HttpLoggingInterceptor.Level.BODY
Debug 모드와 Release 모드일 때의 레벨을 설정해주시면 좋을 것 같아요.

2019-12-13 01:22 UTC, BeokBeok commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/di/NetworkModule.kt
> +        interceptor.level = HttpLoggingInterceptor.Level.BODY
intercepter 의 레벨 설정은 불필요해보여요.

2019-12-13 01:22 UTC, BeokBeok commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/ui/market/MarketViewModel.kt
>      fun getMarketAll() {
접근자를 private 로 하시면 좋을 것 같아요.

2019-12-13 01:22 UTC, BeokBeok commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/ui/market/MarketViewModel.kt
> +    private val upbitRepositoryImpl : UpbitRepositoryImpl
타입을 인터페이스 타입으로 바꿔주시면 좋을 것 같아요.

2019-12-13 01:22 UTC, BeokBeok commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/base/BaseActivity.kt
>  import dagger.android.support.DaggerAppCompatActivity
DaggerAppCompatActivity 를 사용하게 되면서, AppCompatActivity 관련 import 는 불필요해보여요.

2019-12-13 01:22 UTC, BeokBeok commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/base/BaseFragment.kt
>  import dagger.android.support.DaggerFragment
DaggerFragment 를 사용하게 되면서, Fragment 관련 import 는 불필요해보여요.

2019-12-13 01:22 UTC, BeokBeok commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/ui/ticker/TickerFragment.kt
> -    lateinit var viewModelFactory: ViewModelProvider.Factory
사용했던 import 도 정리해주시면 좋을 것 같아요.

2019-12-13 01:46 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/di/NetworkModule.kt
> +        interceptor.level = HttpLoggingInterceptor.Level.BODY
26c2684

적용완료.

2019-12-13 01:47 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/di/NetworkModule.kt
>          interceptor.level = HttpLoggingInterceptor.Level.BODY
c49f1b8

적용완료.

2019-12-13 01:47 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/ui/market/MarketViewModel.kt
>      fun getMarketAll() {
77e55de

적용완료.

2019-12-13 01:47 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/ui/market/MarketViewModel.kt
> +    private val upbitRepositoryImpl : UpbitRepositoryImpl
3911480

적용완료.

2019-12-13 01:47 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/base/BaseActivity.kt
>  import dagger.android.support.DaggerAppCompatActivity
5eb3ec4

적용완료.

2019-12-13 01:47 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/base/BaseFragment.kt
>  import dagger.android.support.DaggerFragment
5eb3ec4

적용완료.

2019-12-13 01:47 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/ui/ticker/TickerFragment.kt
> -    lateinit var viewModelFactory: ViewModelProvider.Factory
5eb3ec4

적용완료.

2019-12-13 01:48 UTC, BeokBeok commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/di/ViewModelFactory.kt
> +            throw RuntimeException(e)
네 맞습니다:smile:

2019-12-13 01:59 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/di/ViewModelFactory.kt
> +            throw RuntimeException(e)
저 함수도 내부적으로는 동일하게 throw를 하는데 어떤점에서 더 좋을 것 같은지 궁금합니다 !

2019-12-13 02:14 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/di/ViewModelFactory.kt
> +            throw RuntimeException(e)
92afd8b

적용완료.

2019-12-13 02:19 UTC, BeokBeok commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/di/ViewModelFactory.kt
> +            throw RuntimeException(e)
여기에서는 RuntimeException 과 IllegalStateException 의 차이(?) 밖에는 없는 것 같습니다.

제가 생각했을 때의 장점은
어떤 타입이든, Exception 으로 만들어서 던져주는 점 같습니다.
가령, String 으로 에러메시지를 만들어서 전달한다든지
문제가 발생한 객체를 전달하여 디버깅 시 유연하게 처리할 수 있지 않을까 싶습니다.

본 리뷰의 목적은, `error` 함수가 있다는 것을 알려드리고 싶었다는 것에 있습니다. 😄 
그런데 제가 `error` 를 쓰는 것이 더 좋다는(?) 것 처럼 말을 한 것 같네요:sob:

2019-12-13 02:28 UTC, BeokBeok approved these changes
LGTM:ok_hand:

---

부족한 리뷰 받아주시고
스터디 하시느라 고생 많으셨습니다.:clap:

2019-12-13 02:30 UTC, toctocbin commented on toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/di/ViewModelFactory.kt
> +            throw RuntimeException(e)
아항 넵 감사합니다!

2019-12-13 02:31 UTC, toctocbin commented
아닙니다. 현석님 덕분에 많이 알아가서 좋았습니다.
리뷰해주셔서 감사합니다 👍 
수고하셨습니다!

2019-12-17 07:59 UTC, merged