HW 2-1 검색 기능
sjjeong/GoogryAndroidArchitecutreStudy pull request #30
Opened 2019-05-16 14:59 UTC by sabgilhun

2019-05-18 15:42 UTC, ddaeyeonkim reviewed
용훈님 코드 리뷰할 때마다 제 공부의 부족함을 느끼네요ㅠ 😭

2019-05-18 15:42 UTC, improve777 commented on sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/view/home/HomeActivity.kt
> +                startActivity(Intent(applicationContext, SearchCoinActivity::class.java))
applicationContext 보다는 this 가 나을 것 같습니다. 권장하지 않는 것 같아요

![image](https://user-images.githubusercontent.com/36095102/57971484-cd399080-79c9-11e9-8d97-b81fff59f3c3.png)

2019-05-18 15:42 UTC, improve777 commented on sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/view/searchcoin/SearchCoinPresenter.kt
> +        if(disposables.size() > 0) {
reformat code 가 안 되어 있어요

2019-05-18 15:42 UTC, improve777 commented on sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/data/CoinRepositoryImpl.kt
>              .subscribeOn(Schedulers.newThread())
`Schedulers.newThread()` 보다 `Schedulers.io()` 를 권장하는거 같아요
석준님 코드도 `newThead()` 인 것 같은데 이유를 여쭤봐야 겠군요

[retrofit-with-rxjava-schedulers-newthread-vs-schedulers-io](https://stackoverflow.com/questions/33415881/retrofit-with-rxjava-schedulers-newthread-vs-schedulers-io)

2019-05-19 03:32 UTC, sjjeong requested changes
화이팅

2019-05-22 14:43 UTC, sabgilhun commented on sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/view/home/HomeActivity.kt
> +                startActivity(Intent(applicationContext, SearchCoinActivity::class.java))
좋은 정보 감사합니다. 😊 
수정했습니다.
350f65a11eb207caa8bc06a3aa5e7886e01ef8ca

2019-05-22 14:43 UTC, sabgilhun commented on sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/view/searchcoin/SearchCoinPresenter.kt
> +        if(disposables.size() > 0) {
b6996550ae6817b6320d6c102678450c3be41e26

2019-05-22 14:44 UTC, sabgilhun commented on sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/data/CoinRepositoryImpl.kt
>              .subscribeOn(Schedulers.newThread())
석준님 코드를 참고해보니 확장함수로 아예 묶어두셨길래 저도 그렇게 수정했습니다.
c416c0b4f686344c8718ed443919411687427b40

2019-05-23 00:30 UTC, ddaeyeonkim approved these changes
LGTM 👍👍👍

2019-05-24 00:58 UTC, GongSulMin approved these changes

2019-05-26 10:35 UTC, sjjeong approved these changes

2019-05-26 10:36 UTC, merged