HW-3.1-자율과제-프로젝트에서 RX사용해보기
sjjeong/GoogryAndroidArchitecutreStudy pull request #306
Opened 2019-11-28 10:08 UTC by ironelder

HW-3.1-자율과제-프로젝트에서 RX사용해보기

2019-11-29 15:18 UTC, sjjeong requested changes
1. 기존에 Call로 통신하던 로직을 제거 해주세요.
2. DataSource와 Repository 개념이 반대로 구현되어있습니다.
3. 불필요한 주석은 제거 해주세요

2019-11-29 15:18 UTC, sjjeong commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/view/mainview/MainFragment.kt
> +                    .subscribe({ presenter.onSuccess(it) }, { presenter.onError(it) })
subscribe를 view가 아니라 presenter에서 해주세요

2019-12-03 09:23 UTC, ironelder commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/view/mainview/MainFragment.kt
> +                    .subscribe({ presenter.onSuccess(it) }, { presenter.onError(it) })
subscribe 및 rx의 위치를 presenter로 이동하였습니다
8544da6

@sjjeong 
rx로 변경 후 기존의 call통신하던 로직을 제거하면서 Datasource를 보면 더이상 하는일이 없어지는 것이 맞나요?
rx의 single을 repository가 반환해주게되면 datasource의 할일이 없어지는 것 같습니당...

2019-12-03 10:11 UTC, sjjeong commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/view/mainview/MainFragment.kt
> +                    .subscribe({ presenter.onSuccess(it) }, { presenter.onError(it) })
presenter <=> repository <=> remote datasource
이런식으로 구현되어야 합니다.
remote datasource에서는 retrofit을 통해 가져오는 역할을 하고
repository에서는 remote datasource에 데이터를 원격서버에서 가져오라고 하는 역할이고
presenter는 repository에 데이터를 요청하는 역할입니다.

2019-12-04 09:45 UTC, ironelder commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/view/mainview/MainFragment.kt
> +                    .subscribe({ presenter.onSuccess(it) }, { presenter.onError(it) })
repository와 data source의 역할을 변경하면서 rx의 호출 구조를 변경해보았습니다.
6cf3af9

@sjjeong 
받아온 Single을 .observeOn <--이렇게 접근 하지 않고, 
apply혹은 run으로 해당 스코프 안에서 적용할 수는 없는지 궁금합니다.
해봤더니 에뮬레이터 오류가 발생해서요... ㅎㅎ

2019-12-05 12:01 UTC, sjjeong requested changes

2019-12-05 12:01 UTC, sjjeong commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/data/repository/SearchDataRepository.kt
> +        get: (observable: Single<TotalModel>) -> Unit
이것도 리턴 형식으로 주면 됩니다.

2019-12-05 12:02 UTC, sjjeong commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/view/mainview/MainFragment.kt
> +                    .subscribe({ presenter.onSuccess(it) }, { presenter.onError(it) })
결국 .subscribe하기전에 .observeOn을 호출해주기만 하면 됩니다.

2019-12-05 12:08 UTC, ironelder commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/view/mainview/MainFragment.kt
> +                    .subscribe({ presenter.onSuccess(it) }, { presenter.onError(it) })
@sjjeong 
```
SearchDataRepositoryImpl.getDataForSearch(type, query).apply {
            observeOn(AndroidSchedulers.mainThread())
            subscribeOn(Schedulers.io())
            subscribe(::onSuccess, ::onError).addDisposable()
        }
```
혹시 이런식으로 쓸 수는 없나 해서요 ㅎㅎ

2019-12-05 12:10 UTC, ironelder commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/data/repository/SearchDataRepository.kt
> +        get: (observable: Single<TotalModel>) -> Unit
repository에서 single을 리턴하도록 수정하였습니다~
c94acc2

@sjjeong 
그런데 이렇게 되면 Datasource에서 바로 리턴받아서 쓰는것과 차이가 어떤점이 있는지 잘 모르겠습니다

2019-12-05 12:12 UTC, sjjeong commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/data/repository/SearchDataRepository.kt
> +        get: (observable: Single<TotalModel>) -> Unit
콜백과 리턴으로 받는 형식의 차이 인거죠
기존에 비동기통신은 callback패턴이라서 저런식으로 받아야하는데
Rx Stream같은경우는 저럴 필요가 없는 것이죠

2019-12-05 12:12 UTC, sjjeong approved these changes

2019-12-05 12:12 UTC, sjjeong commented
확인하시고 저에게 알려주시면 머지 해드릴게요

2019-12-05 12:20 UTC, merged