2차 사전과제
sjjeong/GoogryAndroidArchitecutreStudy pull request #308
Opened 2019-11-28 13:14 UTC by doubleclutch30

내폴더 제외 나머지폴더 제거 
androidx 생성 gitignore 추가

2019-11-28 15:41 UTC, sjjeong requested changes
2. 본인폴더와 README.md를 제외한 남은 폴더를 제거하는 commit
해당 부분이 진행되지 않았습니다.

2019-11-29 05:37 UTC, doubleclutch30 commented
수정했습니다.

2019-11-29 14:31 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-11-30 06:21 UTC, jjunji commented
스터디 첫 회 진행 중에 approval 설정을 바꾸셔서 그 전 pr 에 대한 reviewer 로 저를 추가했습니다.

2019-11-30 06:22 UTC, jjunji approved these changes

2019-11-30 06:23 UTC, merged