HW-3-2 자율 과제 RxJava 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #309
Opened 2019-11-28 15:53 UTC by 2giwon

1. Call -> Single 변경
2. retrofit rxJavaCallAdapter 추가
3. remote 결과 값을 disposable로 반환하도록 수정
4. BaseContact.Presenter에 dispose처리 추가

2019-11-28 15:57 UTC, 2giwon commented
HW-4로 푸쉬한 뒤에 로그 메시지를 변경해서 두 개가 생겼습니다.
HW-4로 한 것은 무시해주세요ㅠ

2019-11-29 15:26 UTC, sjjeong requested changes

2019-11-29 15:26 UTC, sjjeong commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/data/source/remote/NaverRemoteDataSource.kt
> +            .subscribe({
subscribe는 presenter쪽에서 처리해주세요

2019-11-29 15:26 UTC, sjjeong commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/base/BasePresenter.kt
> +        if (!compositeDisposable.isDisposed) {
CompositeDisposable#clear가 dispose를 하고 있기 때문에 이 로직은 불필요합니다.

2019-11-29 18:49 UTC, 2giwon commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/data/source/remote/NaverRemoteDataSource.kt
> +            .subscribe({
수정했습니다. 코드를 보니 잘못 된 부분이 많아서 수정량이 많습니다 ㅠ

1. CompositeDisposable에 add안되는 문제 수정했습니다.
2. BasePresenter에서 모두 처리를 하고 자식 presenter에서는 신경안쓰도록 만들고 싶었는데 하지못했습니다. BaseFragment에 있는 presenter를 제거했습니다.
3. ContentFragment에서 onPause, onDestroy 때 BasePresenter의 clearCompositeDisposable을 호출하도록 수정했습니다.

304fc89a92c8c3360f08707a13059752b98fcbe9

2019-11-29 18:50 UTC, 2giwon commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/base/BasePresenter.kt
> +        if (!compositeDisposable.isDisposed) {
수정했습니다. 

3897f5e30999c9ce582a91b23da52bf0d0fbdac2

2019-11-30 00:16 UTC, sjjeong requested changes

2019-11-30 00:16 UTC, sjjeong commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/base/BaseFragment.kt
> -    override fun onPause() {
이거는 글로벌하게 사용될 수 있는 개념이라서 유지하는게 좋아요

2019-11-30 00:16 UTC, sjjeong commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/base/BasePresenter.kt
> +        compositeDisposable.dispose()
제 리뷰 내용은 CompositeDisposable의 clear함수 내에서 dispose를 호출하기 때문에
dispose를 따로 호출할 필요가 없다는 것이 였어요.
clear함수만 호출해도 되게 때문에 
```kotlin
fun disposeDisposable()
```
함수가 필요가 없는 거죠

근데 내부 코드를 보니까 clear와 dispose함수의 차이점이 CompositeDisposable의 disposed를 true바꿔주는 작업이 있는 것인데 이것은 조금더 알아봐야겠네요

2019-11-30 15:55 UTC, 2giwon commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/base/BaseFragment.kt
> -    override fun onPause() {
basePresenter가 없이 만드는 법을 모르겠습니다.

저 변수가 있는 한 잘못 동작합니다. 

ContentsPresenter가 갖고 있는 compositeDisposable과 basePresenter의 compositeDisposable이 다르기 때문에

정상동작을 못하고 있습니다.

2019-12-01 09:42 UTC, sjjeong submitted a review, later dismissed
LGTM ✊ ✌️ 👋

2019-12-01 12:32 UTC, merged