HW 2-1 기본통화 설정, 검색 기능 구현
sjjeong/GoogryAndroidArchitecutreStudy pull request #31
Opened 2019-05-18 03:26 UTC by improve777

기본통화 설정, 검색 기능 구현
AlertDialog 만 활용하려고 했더니 더 불편해진 느낌이 듭니다...

2019-05-18 10:38 UTC, sabgilhun requested changes
수고하셨습니다.

2019-05-18 10:38 UTC, sabgilhun commented on improve777/GAASProject/app/src/main/java/dev/daeyeon/gaasproject/ui/ticker/TickerPresenter.kt
> +        list.addAll(upbitRepository.markets.split(",")
upbitRepository를 구현체인 UpbitRepository로 받아 사용하기보단 다형성을 위해 인터페이스로 받아서 사용하는게 좋을것 같습니다. markets는 인터페이스에 getter/setter 정의하고 사용하는게 어떨까요?

2019-05-18 15:59 UTC, improve777 commented on improve777/GAASProject/app/src/main/java/dev/daeyeon/gaasproject/ui/ticker/TickerPresenter.kt
> +        list.addAll(upbitRepository.markets.split(",")
수정 완료하였습니다.
getter/setter 는 코틀린에서 자동으로 해주기 때문에 별도 메소드로 생성할 필요는 없을 것 같아요. 
다른 의도이셨다면 좀 더 자세히 말씀 부탁 드릴게요.

0ee29e7b1b7a46604bc9190eef01637de2b9d065

2019-05-22 12:29 UTC, namjackson commented on improve777/GAASProject/app/src/main/java/dev/daeyeon/gaasproject/ui/ticker/TickerFragment.kt
> +            .setSingleChoiceItems(presenter.currencyArray, -1) { _, item ->
문제는 없지만, -1로 초기화하는것보다 
currencyArray.indexOf(baseCurrency) 로 현재 값을 보여주는것도 좋을거같아요!

2019-05-22 12:29 UTC, namjackson commented on improve777/GAASProject/app/src/main/java/dev/daeyeon/gaasproject/ui/ticker/TickerContract.kt
> +        var baseCurrency: String?
nullable 변수 대신 
lateinit으로 선언후, isInitialized로 체크하는 방법은 어떨까요?

2019-05-22 12:29 UTC, namjackson commented on improve777/GAASProject/app/src/main/java/dev/daeyeon/gaasproject/ui/ticker/TickerContract.kt
> +
어떤부분이 더 좋을진 모르겠지만,
currencyArray, baseCurrency 변수들을 
Presenter 내부에 private 선언하고, 메소드를 호출하는 방식은 어떤가요?

2019-05-22 13:49 UTC, improve777 commented on improve777/GAASProject/app/src/main/java/dev/daeyeon/gaasproject/ui/ticker/TickerFragment.kt
> +            .setSingleChoiceItems(presenter.currencyArray, -1) { _, item ->
수정하였습니다

89433bcab152f1a79057d1d651fcf5ccdaf5c857

2019-05-22 14:54 UTC, sabgilhun commented on improve777/GAASProject/app/src/main/java/dev/daeyeon/gaasproject/ui/ticker/TickerPresenter.kt
> +        list.addAll(upbitRepository.markets.split(",")
네 커밋하신 내용이 제 의도와 동일합니다~

2019-05-22 14:54 UTC, sabgilhun submitted a review, later dismissed

2019-05-22 23:23 UTC, improve777 commented on improve777/GAASProject/app/src/main/java/dev/daeyeon/gaasproject/ui/ticker/TickerContract.kt
> +        var baseCurrency: String?
수정하였습니다

a489ed054ecc80e28d58a701bc4ca9c240bea23c

2019-05-22 23:23 UTC, improve777 commented on improve777/GAASProject/app/src/main/java/dev/daeyeon/gaasproject/ui/ticker/TickerContract.kt
> +
수정 하였습니다

a489ed054ecc80e28d58a701bc4ca9c240bea23c

2019-05-23 00:22 UTC, namjackson approved these changes
수고하셨습니다!

2019-05-23 14:01 UTC, sabgilhun approved these changes

2019-05-23 14:35 UTC, GongSulMin approved these changes

2019-05-26 09:24 UTC, merged