Class06/jay yi
sjjeong/GoogryAndroidArchitecutreStudy pull request #311
Opened 2019-12-02 02:22 UTC by JayYi

HW-1 [1주차 과제] 네이버 검색 API 연동 및 검색 기능 구현

2019-12-02 05:14 UTC, gitpushyj requested changes

2019-12-02 05:14 UTC, gitpushyj commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/MainActivity.kt
> +        override fun getItem(position: Int): Fragment {
override fun getItem(position: Int) = fragments[position] 
요렇게 하는게 좀 더 코틀린 스럽지 않을까요 ~?

2019-12-02 05:14 UTC, gitpushyj commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/MainActivity.kt
> +        override fun getCount(): Int {
여기도 위와 마찬가지로 더 간단하게 할 수 있을 것 같아요!

2019-12-02 05:14 UTC, gitpushyj commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/network/Api.kt
> +    fun getMovies(keyword: String) : Call<ResponseMovies> {
여기도 특별한 로직 없이 바로 return 가능한다면, 
fun getMovies(keyword: String) = ApiClient.getApiSErvice()~~
이렇게 하는건 어떨까요??~?~?

2019-12-02 05:14 UTC, gitpushyj commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/ui/BaseFragment.kt
> +    open fun search(keyword: String) {
추후 BaseFragment 하위 클래스가 더 생겨날 경우 search를 override하지 않고 넘어갈 위험이 있을 것 같아 보입니당.
꼭 오버라이드 해야한다면 abstract로 하시는건 어떨까요 ~?

2019-12-02 05:14 UTC, gitpushyj commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/ui/blog/BlogAdapter.kt
> +    private lateinit var model: Blog
혹시 model을 BlogHolder의 프로퍼티로 가지고 있으려는 이유가 따로 있나요?
bind 메서드 안에 지역변수로만 가지고 있어도 충분할 것 같아서요 ㅎㅎ

2019-12-02 05:14 UTC, wooooooak commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/ui/kin/KinFragment.kt
> +                        layoutManager = LinearLayoutManager(activity)
이 부분은 xml에서 설정해 줄 수 있을것 같습니다!

2019-12-02 05:14 UTC, wooooooak commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/ui/image/ImageFragment.kt
> +                        addItemDecoration(SpacesItemDecoration(12.toPx(), 6.toPx(), 11.toPx()))
12, 6, 11 같은 숫자도 외부 resource화 시켜야 유지보수하기 쉬울것 같아요 ㅎㅎ
resource 파일로 관리하고, 사용할땐 getDimensionPixelSize를 사용하면 될 것 같은데...어떠신가용?

2019-12-02 05:16 UTC, gitpushyj requested changes

2019-12-02 05:16 UTC, wooooooak commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/network/ApiClient.kt
> +
아래 getApiService메서드를 사용해서 lazy init을 하시려는건가요?
그렇다면
val apiService: ApiService by lazy {
~~~
}

이렇게 하는 건 어떨까요 ㅎㅎ

2019-12-02 05:31 UTC, wooooooak commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/ui/kin/KinAdapter.kt
> +    private var data = arrayListOf<Kin>()
값이 변경되지 않는 것 같아보이는데, val로 선언하는게 더 안전할것 같습니다 ㅎㅎ

2019-12-02 14:19 UTC, JayYi commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/MainActivity.kt
> +        override fun getItem(position: Int): Fragment {
수정했습니다.
b0995d52bf57b1d8b42f0137cce1274911c87dde

2019-12-02 14:20 UTC, JayYi commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/MainActivity.kt
> +        override fun getCount(): Int {
수정했습니다.
b0995d52bf57b1d8b42f0137cce1274911c87dde

2019-12-02 14:20 UTC, JayYi commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/network/Api.kt
> +    fun getMovies(keyword: String) : Call<ResponseMovies> {
수정했습니다.
b0995d52bf57b1d8b42f0137cce1274911c87dde

2019-12-02 14:23 UTC, JayYi commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/ui/BaseFragment.kt
> +    open fun search(keyword: String) {
설계 당시에 search 함수를 필수로 구현되어야 한다고 생각하지 않고 재사용 차원에서 open을 선언하였습니다. 현재 프로젝트 구조상 필수로 override가 되어야 하긴 하지만...
신규 기능이 추가 되거나 요구 사항이 변경되어 구조가 변경되어야 한다면 그 때 고민해보면 어떨까 생각이 듭니다.

2019-12-02 14:27 UTC, JayYi commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/ui/blog/BlogAdapter.kt
> +    private lateinit var model: Blog
습관적으로...전역 변수를...
수정했습니다.
3a526081c7c51e009762b966f6ad4d0957f5f9a2

2019-12-02 14:29 UTC, JayYi commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/ui/kin/KinFragment.kt
> +                        layoutManager = LinearLayoutManager(activity)
저는 xml 코드가 눈에 잘 안들어와서 잘 읽혀서요.
특별한 이유가 없으면 위와 같이 코드에 직접 선언하는 것도 나쁘지 않다고 생각합니다.

2019-12-02 14:31 UTC, JayYi commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/ui/image/ImageFragment.kt
> +                        addItemDecoration(SpacesItemDecoration(12.toPx(), 6.toPx(), 11.toPx()))
말씀해주신데로 전역으로 사용하는 것이면 resource가 필요하다고 생각합니다.
하지만 위 코드는 해당 선언부분에만 필요하고 전역으로 사용될 가능성이 없어보입니다. 
전역으로 사용하지 않는 경우에 위와 같이 직접선언하는 편이예요. 코드가 직관적이기도 하구요.

2019-12-02 14:36 UTC, JayYi commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/network/ApiClient.kt
> +
lazy init을 하려고 했던건 아니구요 ㅎㅎ 
단지 object이다 보니 memory leak을 걱정..(습관적으로 코드를...)하다보니 위와 같이 작성했습니다.

object가 생성될 때 바로 초기화 선언되도록 변경하였습니다.
af4937e50586f9e4eefe53c00468f37bff02c4c1

2019-12-02 14:42 UTC, JayYi commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/ui/kin/KinAdapter.kt
> +    private var data = arrayListOf<Kin>()
1cbf95072d6e9a3873c783d90bfdcf516b4d05b9

2019-12-02 15:39 UTC, wooooooak commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/ui/BaseFragment.kt
> +    open fun search(keyword: String) {
음.... 이번 1주차 과제는 완성된 프로젝트를 Pull Request하는 것이기 때문에 말씀하신 것 처럼 현재 상황에서 필수로 override 되어야 한다면, override를 강제시켜야 한다고 생각합니다. 만약 현 시점에서 다른 개발자분이 투입된다고 했을 때, default 구현이 되어있지 않은 것을 간과하고 넘어갈 위험이 커보이기도 하구요..

2019-12-03 00:08 UTC, JayYi commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/ui/BaseFragment.kt
> +    open fun search(keyword: String) {
필수 구현해야 한다고 해서 강제성을 주입하는것은 유연하지 않은 코드라고 생각이 듭니다. BaseFragment의 경우 General하게 모든 fragment가 상속할 목적의 구조를 설계하였습니다. search 함수를 abstract로 선언하면 해당 기능 구현이 필요 없는 다른 fragment의 경우 불필요하게 함수 선언을 하여 boilerplate code를 만드는 꼴이라 생각이 드네요. 정말 강제성이 필요하다면 BaseSearchFragment와 같이 별도의 abstract fragment를 생성하는것도 방법일 것 같다는 생각이 들지만 이 또한 BaseFragment 코드와 많이 중복될 것으로 보입니다. default 구현이 되지 않아 발생하는 문제는 설계의 문제라기 보다는 구현의 문제라고 생각이 들어요. 구현되지 않는 것들은 디버깅이나 QA과정에 발견될테니 설계단의 이슈는 아닌 것으로 생각이 드네요(정말 발견을 못한다면............음....그건 그 회사의 문제........아닐수도..있지만...)

2019-12-03 00:26 UTC, gitpushyj submitted a review, later dismissed

2019-12-03 00:26 UTC, wooooooak commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/ui/BaseFragment.kt
> +    open fun search(keyword: String) {
아~이게 Search를 목적으로 하는 Fragment만의 확장을 고려한 Base가 아니었군요..? 
이 BaseFragment를 상속하게 되는 자식 클래스들이 onViewCreated에서 search_editor와 search_btn을 강제하고 있어서 Search를 목적으로 하는 Fragment만을 위한 부모 클래스인줄 알았네요....
이미 검색창과 검색 버튼을 강제하고 있는 BaseFragment라면 말씀하신 것 처럼 General하게 모든 fragment가 상속할 수 있을까...하는 생각이 들었습니다ㅠㅠ

이건 다음에 한 번 이야기 해보면 좋을 주제인것 같아요!!
이제 석준님에게 넘겨보겠습니다 ㅎㅎ

2019-12-03 00:31 UTC, JayYi commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/ui/BaseFragment.kt
> +    open fun search(keyword: String) {
답변 주신것 처럼 검색 코드가 있어서......저도 고민이 많았는데
이번주 스터디 전에 시간이 된다면 별도의 검색 창 뷰를 생성해서 BaseFragment 내에 검색 기능 함수의 의존성을 빼보려고 합니다.

2019-12-03 15:46 UTC, sjjeong requested changes

2019-12-03 15:46 UTC, sjjeong commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/model/Movie.kt
> +data class ResponseMovies(
다른 모델과 비슷한 형태로 되어있습니다.
items를 generic으로 처리해서 하면 좋을 것 같습니다.

2019-12-03 15:46 UTC, sjjeong commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/network/ApiClient.kt
> +    fun getApiService() = apiService
kotlin에서는 getter를 따로 만들어 줄 필요가 없습니다.
apiService를 public으로 만들어주세요

2019-12-03 15:46 UTC, sjjeong commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/network/ApiClient.kt
> +            addHeader("Content-Type", "application/json")
Accept와 Content-Type은 추가해주지 않아도 됩니다.

2019-12-03 15:46 UTC, sjjeong commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/MainActivity.kt
> +            bottom_navigation.menu.getItem(position).setChecked(true)
```kotlin
bottom_navigation.menu.getItem(position).isChecked = true
```
로 변경할 수 있습니다.

2019-12-03 15:46 UTC, sjjeong commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/ui/BaseFragment.kt
> +    open fun search(keyword: String) {
`BaseFragment의 경우 General하게 모든 fragment가 상속할 목적의 구조를 설계하였습니다. `
라고 하신다면 해당 함수는 없는게 맞습니다.
또한 위에 있는 search_btn.setOnClickListener도 없어야합니다.
만약 view_search layout이 없는 Fragment라면 search_btn에 접근하면 null로 죽습니다.

2019-12-03 15:46 UTC, sjjeong commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/ui/BaseFragment.kt
> +open class BaseFragment : Fragment() {
Base개념이라면 open보단 abstract로 해주세요.

2019-12-03 15:46 UTC, sjjeong commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/ui/WebViewActivity.kt
> +    private lateinit var webView: WebView
url이나 webView가 초기화되는 시점과 사용되는 시점이 같은 block안에 있다면 property로 빼지 않아도 된다고 생각합니다.

2019-12-03 15:46 UTC, sjjeong commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/ui/blog/BlogAdapter.kt
> +internal class BlogAdapter(private val context: Context) : RecyclerView.Adapter<BlogHolder>() {
4개의 Adapter가 비슷한 형태로 구현 되어있습니다.
BaseAdapter를 만들어보면 좋을 것 같습니다.

2019-12-03 15:46 UTC, sjjeong commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/ui/blog/BlogAdapter.kt
> +            setOnClickListener {
clickListener를 등록하는 것은 data를 set하는 것과 달리 한번만 등록해주면 되기 때문에 onBindViewHolder 시점에 clickListener를 등록해주는 것은 좋지 않습니다.

2019-12-03 15:46 UTC, sjjeong commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/ui/blog/BlogAdapter.kt
> +    private val view: View
ViewHolder에서 생성자로 받은 view를 itemView라는 property로 가지고 있기 때문에 view를 직접 들고 있을 필요는 없습니다.

2019-12-03 15:46 UTC, sjjeong commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/ui/blog/BlogAdapter.kt
> +        val view = LayoutInflater.from(context).inflate(R.layout.list_item_blog, parent, false)
context를 생성자로 받아와서 사용할 필요는 없습니다.
parent.context로 하면됩니다.
생성자에 추가한 것은 제거 해주세요

2019-12-03 15:46 UTC, sjjeong commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/ui/blog/BlogFragment.kt
> +                        layoutManager = LinearLayoutManager(activity)
layoutManager는 xml에서도 추가해 줄 수 있습니다.

2019-12-03 15:46 UTC, sjjeong commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/ui/blog/BlogFragment.kt
> +                        adapter = it
also를 사용해서 It으로 넣을 필요가 없어보입니다.
blogAdapter로 넣어주세요.

2019-12-03 15:46 UTC, sjjeong commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/ui/blog/BlogFragment.kt
> +    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
onViewCreated시점보단 onActivityCreated에서 해주는게 좋습니다.

2019-12-03 15:46 UTC, sjjeong commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/ui/blog/BlogFragment.kt
> +    override fun onCreateView(
BaseFragment에서 생성자로 layout id를 전달 받아서 처리해줄 수 있습니다.

2019-12-03 15:46 UTC, sjjeong commented on JayYi/ArchitectureStudy/app/src/main/res/layout/list_item_image.xml
> +        app:layout_constraintTop_toBottomOf="parent"
원래 의도는 `layout_constraintBottom_toBottomOf` 아닌가요? top에 제약이 2개가 걸려있습니다.

2019-12-03 15:46 UTC, sjjeong commented on JayYi/ArchitectureStudy/app/src/main/res/layout/list_item_movie.xml
> +        android:layout_marginLeft="15dp"
left, right보단 start, end를 사용해야합니다.

2019-12-05 14:59 UTC, JayYi commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/model/Movie.kt
> +data class ResponseMovies(
수정했습니다.
8e03dba3503ad5fb3b91b645a6056edb8690806a

2019-12-05 15:01 UTC, JayYi commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/network/ApiClient.kt
> +    fun getApiService() = apiService
수정하였습니다.
데이터 모델 수정된 내용과 같이 소스 커밋이 되었으니 참고바랍니다.

8e03dba3503ad5fb3b91b645a6056edb8690806a

2019-12-05 15:04 UTC, JayYi commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/network/ApiClient.kt
> +            addHeader("Content-Type", "application/json")
수정완료하였습니다.
apiService 관련 수정 코드와 같이 커밋했습니다.

2835aff0edf20c909c193046cefa60d95b158729

2019-12-05 15:05 UTC, JayYi commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/MainActivity.kt
> +            bottom_navigation.menu.getItem(position).setChecked(true)
수정완료했습니다.
bdc2a62b23fad4e2877e8fd8a5f634dcabd2ab7b

2019-12-05 15:08 UTC, JayYi commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/ui/BaseFragment.kt
> +open class BaseFragment : Fragment() {
수정완료 하였습니다.

Basefragment abstract class 변경
41ce1f87a7baeab1ca7b218ff85668dc21692fbc

onViewCreated 내 onClickListener 제거
b39ae4fab9988ac4cc592b76fbf49c7ce9ce6b2e

Serach method를 abstract method 변경
ce8e1bd77dd9dd2e2fefb4942a2ee1889ef20c6c

2019-12-05 15:09 UTC, JayYi commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/ui/WebViewActivity.kt
> +    private lateinit var webView: WebView
수정완료했습니다.
e865e1311f85134b24ec51642e6f493608da63fd

2019-12-05 15:10 UTC, JayYi commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/ui/blog/BlogAdapter.kt
> +internal class BlogAdapter(private val context: Context) : RecyclerView.Adapter<BlogHolder>() {
수정완료했습니다.
fa366efdb7a3fa34a26d525dc9a1243190137d21

2019-12-05 15:11 UTC, JayYi commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/ui/blog/BlogAdapter.kt
> +    private val view: View
수정하였습니다.
f4cbceb93d16b3f4392264db7566ab9a841c0919

2019-12-05 15:12 UTC, JayYi commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/ui/blog/BlogAdapter.kt
> +            setOnClickListener {
수정완료했습니다.
687d61e2641a096a176bbff1af939e216732b4e6

2019-12-05 15:13 UTC, JayYi commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/ui/blog/BlogAdapter.kt
> +        val view = LayoutInflater.from(context).inflate(R.layout.list_item_blog, parent, false)
수정완료했습니다.
5f05dfe706f3c544f66b26c84f39c5ca863b5696

2019-12-05 15:17 UTC, JayYi commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/ui/blog/BlogFragment.kt
> +                        layoutManager = LinearLayoutManager(activity)
수정완료하였습니다.
b492fbb870ba5f8ca18f526b1289fbaa86bc5281

질문이 있습니다.
제가 난독증이 조금 있어서 xml에 선언한 내용이 눈에 잘 안들어와서 특별한 문제가 없으면 class 내 코드를 선언하는 것을 선호합니다. class 내 코드를 사용하는 것이 특별한 이슈가 있어서 xml에 선언하는 것이 좋은것인지 궁금합니다.

2019-12-05 15:18 UTC, JayYi commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/ui/blog/BlogFragment.kt
> +                        adapter = it
수정하였습니다.
dffedf00d0a84caf08e68b263905ec1d672f25e5

2019-12-05 15:19 UTC, JayYi commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/ui/blog/BlogFragment.kt
> +    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
수정하였습니다.
3e1c77a58c80bb856df907d756c3407aeb92301f

2019-12-05 15:20 UTC, JayYi commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/ui/blog/BlogFragment.kt
> +    override fun onCreateView(
수정하였습니다.

3e1c77a58c80bb856df907d756c3407aeb92301f
fe8d7e9dca5e55183c617de1c52608a5c7faf30e

2019-12-05 15:21 UTC, JayYi commented on JayYi/ArchitectureStudy/app/src/main/res/layout/list_item_image.xml
> +        app:layout_constraintTop_toBottomOf="parent"
수정완료하였습니다.
04cde38075d8f89cf9ab3eef7bb7290e3beda47a

2019-12-05 15:23 UTC, JayYi commented on JayYi/ArchitectureStudy/app/src/main/res/layout/list_item_movie.xml
> +        android:layout_marginLeft="15dp"
수정완료하였습니다.
d20de58a35f4112ea280ce29034d64cc43b62164

2019-12-05 16:23 UTC, sjjeong commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/ui/BaseAdapter.kt
> +        this.items.addAll(items)
여기서 addAll을 하고 자식클래스에서 다시 clear, addAll을 하고 있습니다.
자식클래스에 있는 내용을 전부 부모클래스에서 처리해도 될 것 같습니다.

2019-12-05 16:23 UTC, sjjeong commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/ui/blog/BlogFragment.kt
> +                        layoutManager = LinearLayoutManager(activity)
이거는 기준을 어떻게 두는지 차이 일 것 같아요.
저는 대부분 정적인(변수가 없는) 처리는 xml에서 하고 동적으로 변하는 내용은 코드에서 처리합니다.
만약 xml에 선언한게 눈에 잘 안들어오신다고 하면 id, margin 등등과 같은 다른 attr들이 xml에 있는게 다른사람이 보기에 의아하게 생각 할 수도 있습니다.
xml에서 지원하는 attr을 굳이 코드에서 처리했을까 라는 의문만 더 생기게 됩니다.

2019-12-05 16:25 UTC, sjjeong commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/ui/blog/BlogFragment.kt
> +                        layoutManager = LinearLayoutManager(activity)
ImageFragment에 있는 LayoutManager도 xml로 이동해주세요

2019-12-05 16:40 UTC, JayYi commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/ui/BaseAdapter.kt
> +        this.items.addAll(items)
방금...코드 다시 보면서...수정했는데 답변 해주셨네여..ㅎㅎ
수정했습니다.

63dc116fb501647394d0ddb3cdc11b81babc3a94
9fc18dc119e22560ce83641ab0412d38672159c3

2019-12-05 16:48 UTC, sjjeong commented
@JayYi 
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/311#discussion_r354413999
이것도 처리해주세요

2019-12-05 23:58 UTC, JayYi commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/ui/blog/BlogFragment.kt
> +                        layoutManager = LinearLayoutManager(activity)
수정했습니다.

1acfe18f0050ddb40444c06814062b6908ac814c

2019-12-06 08:21 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-12-07 02:04 UTC, gitpushyj approved these changes

2019-12-07 02:04 UTC, merged