HW-1 [1주차과제] Naver API 연동 앱 구현
sjjeong/GoogryAndroidArchitecutreStudy pull request #312
Opened 2019-12-02 13:48 UTC by dksush

HW-1 [1주차과제] Naver API 연동 앱 구현

2019-12-04 00:40 UTC, ghost reviewed
커밋 메시지(HW-n xxx) 양식을 지켜주셔야 할것같습니다.

2019-12-04 00:40 UTC, ghost commented on dksush/AndroidArchitecture/app/src/main/java/com/example/androidarchitecture/models/BlogData.kt
> +    @SerializedName("bloggerlink")
객체의 이름과 json 필드명이 동일한데 @SerializedName 으로 직렬화한 이유가 있나요?

2019-12-04 09:18 UTC, dksush commented on dksush/AndroidArchitecture/app/src/main/java/com/example/androidarchitecture/models/BlogData.kt
> +    @SerializedName("bloggerlink")
앱에 proguard 를 적용해 릴리즈시 SerializedName를 해주지 않으면 "bloggerlink" 의 값이 변해 gson 이 작동하지 않을 수 있다고 알고있습니다.

2019-12-04 12:45 UTC, chanhoparkcj commented on dksush/AndroidArchitecture/app/src/main/java/com/example/androidarchitecture/models/BlogData.kt
> +    @SerializedName("bloggerlink")
아 그렇군요

2019-12-04 12:48 UTC, ghost requested changes
git 에 커밋 하실때 파일 또는 클래스 별로 나눠서 했으면 리뷰할때 보기가 좋을것 같습니다. 하나의 커밋메시지에 여러개 파일 변경사항이 있으니 보기 힘듭니다.

2019-12-04 14:32 UTC, dksush commented on dksush/AndroidArchitecture/app/src/main/java/com/example/androidarchitecture/models/BlogData.kt
> +    @SerializedName("bloggerlink")
커밋 메세지를 나중에 바꿀 수 있나요? 아니면 추가로 answer 로 태그를 단 이유가 있으신가영

2019-12-05 03:55 UTC, ghost approved these changes

2019-12-05 03:58 UTC, chanhoparkcj commented on dksush/AndroidArchitecture/app/src/main/java/com/example/androidarchitecture/models/BlogData.kt
> +    @SerializedName("bloggerlink")
바꿀수 있는 방법은 있습니다만... 알아보니 좀 꼬일수 있는 부분이 있는거 같네요

2019-12-05 03:59 UTC, ghost approved these changes

2019-12-05 03:59 UTC, ghost approved these changes

2019-12-05 03:59 UTC, ghost submitted a review, later dismissed

2019-12-05 16:11 UTC, sjjeong requested changes
1. class name이 소문자로 시작하는 것을 대문자로 시작하게 변경해주세요.
2. BlogFragment, BlogAdapter에 리뷰 남긴 내용을 나머지 Fragment, Adapter에도 동일하게 반영해주세요.
3. Android Studio에서 노란색밑줄 그어진 부분을 모두 처리해주세요
4. 사용되지 않는 변수, 함수들을 제거해주세요

2019-12-05 16:11 UTC, sjjeong commented on dksush/AndroidArchitecture/app/src/main/java/com/example/androidarchitecture/apis/Api.kt
> +        val base_url: String = "https://openapi.naver.com/v1/search/"
상수개념은 대문자로 쓰셔야 합니다.
그리고 baseUrl은 도메인만 있는게 좋습니다
```kotlin
val BASE_URL: String = "https://openapi.naver.com/"
```

2019-12-05 16:11 UTC, sjjeong commented on dksush/AndroidArchitecture/app/src/main/java/com/example/androidarchitecture/apis/Api.kt
> +    fun getMovielist(
list의 l을 대문자로 사용해주세요

2019-12-05 16:11 UTC, sjjeong commented on dksush/AndroidArchitecture/app/src/main/java/com/example/androidarchitecture/apis/Api.kt
> +    ): Call<MovieData>
모델들이 4개다 비슷한 개념으로 들어가니 generic을 사용하는 방법으로 변경해보세요

2019-12-05 16:11 UTC, sjjeong commented on dksush/AndroidArchitecture/app/src/main/java/com/example/androidarchitecture/apis/NetworkUtil.kt
> +        private var SAFE_DNS: Dns? = Dns { hostname ->
lazy패턴으로 간다면 nonnull하게 사용할 수 있습니다.

2019-12-05 16:11 UTC, sjjeong commented on dksush/AndroidArchitecture/app/src/main/java/com/example/androidarchitecture/apis/NetworkUtil.kt
> +    companion object {
NetworkUtil을 인스턴스화 시켜서 사용하지 않는다면 companion object대신 NetworkUtil을 object로 만드시면 됩니다.

2019-12-05 16:11 UTC, sjjeong commented on dksush/AndroidArchitecture/app/src/main/java/com/example/androidarchitecture/apis/NetworkUtil.kt
> +        private var okHttpClient: OkHttpClient? = OkHttpClient.Builder()
nonnull하게 사용할 수 있습니다.

2019-12-05 16:11 UTC, sjjeong commented on dksush/AndroidArchitecture/app/src/main/java/com/example/androidarchitecture/apis/NetworkUtil.kt
> +        fun getRetrofit(baseUrl: String, factory: Converter.Factory?): Retrofit {
factory 파라미터가 null체크에 사용되는 것 외에 사용되지 않고 있습니다.
삭제 해주셔도 좋을 것 같습니다.

2019-12-05 16:11 UTC, sjjeong commented on dksush/AndroidArchitecture/app/src/main/java/com/example/androidarchitecture/apis/NetworkUtil.kt
> +        class appInterceptor : Interceptor {
class는 대문자로 시작해야 합니다.

2019-12-05 16:11 UTC, sjjeong commented on dksush/AndroidArchitecture/app/src/main/java/com/example/androidarchitecture/ui/MainActivity.kt
> +        TabLayoutMediator(tab_layout, pager, object :TabLayoutMediator.TabConfigurationStrategy{
```kotlin
        TabLayoutMediator(
            tab_layout,
            pager,
            TabLayoutMediator.TabConfigurationStrategy { tab, position ->
                when (position) {
                    0 -> tab.text = "Movie"
                    1 -> tab.text = "Image"
                    2 -> tab.text = "Blog"
                    3 -> tab.text = "Kin"
                }
            }).attach()
```
이렇게 간소화 해서 사용 할 수 있습니다.

2019-12-05 16:11 UTC, sjjeong commented on dksush/AndroidArchitecture/app/src/main/java/com/example/androidarchitecture/ui/WebviewActivity.kt
> +    private lateinit var Webview: WebView
url과 webView를 property로 선언할 필요가 없을 것 같습니다.

2019-12-05 16:11 UTC, sjjeong commented on dksush/AndroidArchitecture/app/src/main/java/com/example/androidarchitecture/ui/blog/BlogFragment.kt
> +            if (input_text != null) {
여기서 Null 체크는 필요 없어 보이는데 어떤 이유로 추가하셨나요?

2019-12-05 16:11 UTC, sjjeong commented on dksush/AndroidArchitecture/app/src/main/java/com/example/androidarchitecture/ui/blog/BlogFragment.kt
> +        val api = retrofit.create(Api::class.java)
retrofit 객체와 create된 api객체는 매번 생성할 필요가 없습니다.
한번만 생성해서 사용하는 쪽으로 변경해주세요

2019-12-05 16:11 UTC, sjjeong commented on dksush/AndroidArchitecture/app/src/main/java/com/example/androidarchitecture/ui/blog/BlogFragment.kt
> +    private fun setList(blog: List<ResponseBlog>) {
setList 함수안에서 RecyclerView에 필요한 값들을 초기화 해주고 있습니다.
Adapter, LayoutManager, ItemDecoration은 onActivityCreated 시점에 초기화 해주고
setList시점에는 데이터를 adapter에 set하는 작업만 해주세요.

2019-12-05 16:11 UTC, sjjeong commented on dksush/AndroidArchitecture/app/src/main/java/com/example/androidarchitecture/ui/blog/blogAdapter.kt
> +    val items: List<ResponseBlog>
item을 생성자로 전달받지 마시고 내부 property로 선언하고 함수를 통해 collection 내부에 있는 데이터를 addAll해주는 방식으로 해주세요

2019-12-05 16:11 UTC, sjjeong commented on dksush/AndroidArchitecture/app/src/main/java/com/example/androidarchitecture/ui/blog/blogAdapter.kt
> +                setOnClickListener() {
ClickListener는 onBindViewHolder가 호출 될 때마다 set할 필요가 없습니다.
View가 생성되는 시점에만 set하게 해주세요

2019-12-05 16:11 UTC, sjjeong commented on dksush/AndroidArchitecture/app/src/main/res/layout/activity_main.xml
> +<!--    <com.google.android.material.bottomnavigation.BottomNavigationView-->
주석처리한 부분 제거해주세요

2019-12-05 16:11 UTC, sjjeong commented on dksush/AndroidArchitecture/app/src/main/res/layout/item_image.xml
> +    <TextView
텍스트가 이미지와 겹치게 나오고 있습니다.

2019-12-06 03:36 UTC, dksush commented on dksush/AndroidArchitecture/app/src/main/java/com/example/androidarchitecture/apis/NetworkUtil.kt
> +        private var SAFE_DNS: Dns? = Dns { hostname ->
NetworkUtil
1. lazy 패턴
2. class -> object
3. 노란줄들 제거 및 nonnull 하게 수정
4. getRetrogit() 의 factory 파라미터 제거
5. 인터셉터 클래스명 대문자 시작으로 변경
1cec5ac

2019-12-06 03:44 UTC, dksush commented on dksush/AndroidArchitecture/app/src/main/java/com/example/androidarchitecture/ui/MainActivity.kt
> +        TabLayoutMediator(tab_layout, pager, object :TabLayoutMediator.TabConfigurationStrategy{
수정했습니다.
0bf5af3

2019-12-06 03:46 UTC, dksush commented on dksush/AndroidArchitecture/app/src/main/res/layout/activity_main.xml
> +<!--    <com.google.android.material.bottomnavigation.BottomNavigationView-->
주석 제거하였습니다.

fd4c4d1

2019-12-06 03:53 UTC, dksush commented on dksush/AndroidArchitecture/app/src/main/java/com/example/androidarchitecture/ui/WebviewActivity.kt
> +    private lateinit var Webview: WebView
수정하였습니다.

7e4bbd6

2019-12-06 07:29 UTC, dksush commented on dksush/AndroidArchitecture/app/src/main/java/com/example/androidarchitecture/ui/blog/BlogFragment.kt
> +        val api = retrofit.create(Api::class.java)
수정했습니다. 
d51257f

2019-12-06 07:29 UTC, dksush commented on dksush/AndroidArchitecture/app/src/main/java/com/example/androidarchitecture/ui/blog/BlogFragment.kt
> +    private fun setList(blog: List<ResponseBlog>) {
수정했습니다.
초기화 위치를 onActivityCreated 해주는 이유가 어떤것인가요
d51257f

2019-12-06 08:06 UTC, dksush commented on dksush/AndroidArchitecture/app/src/main/java/com/example/androidarchitecture/ui/blog/blogAdapter.kt
> +    val items: List<ResponseBlog>
수정하였습니다. 
해당 방식으로 하는 이유가 어떤것인가요

3e4eaad

2019-12-06 08:06 UTC, dksush commented on dksush/AndroidArchitecture/app/src/main/java/com/example/androidarchitecture/ui/blog/blogAdapter.kt
> +                setOnClickListener() {
수정하였습니다.

3e4eaad

2019-12-06 08:11 UTC, dksush commented on dksush/AndroidArchitecture/app/src/main/res/layout/item_image.xml
> +    <TextView
수정했습니다

0ccb67c

2019-12-06 08:16 UTC, dksush commented on dksush/AndroidArchitecture/app/src/main/java/com/example/androidarchitecture/apis/Api.kt
> +        val base_url: String = "https://openapi.naver.com/v1/search/"
수정했습니다.

fdb6da8

2019-12-06 08:16 UTC, dksush commented on dksush/AndroidArchitecture/app/src/main/java/com/example/androidarchitecture/apis/Api.kt
> +    fun getMovielist(
수정했습니다.

fdb6da8

2019-12-06 08:21 UTC, dksush commented on dksush/AndroidArchitecture/app/src/main/java/com/example/androidarchitecture/ui/blog/BlogFragment.kt
> +            if (input_text != null) {
앗.. 수정하였습니다.

389ae67

2019-12-06 08:28 UTC, dksush commented on dksush/AndroidArchitecture/app/src/main/java/com/example/androidarchitecture/apis/Api.kt
> +    ): Call<MovieData>
음.. 어떤 말씀이신지 잘 모르겠어 그러는데, 
힌트를 좀 더 주실 수 있을까요.. generic 관련해서 찾아보고 있는데 감이 잘 안옵니다..

2019-12-06 15:10 UTC, sjjeong commented on dksush/AndroidArchitecture/app/src/main/java/com/example/androidarchitecture/ui/blog/BlogFragment.kt
> +    private fun setList(blog: List<ResponseBlog>) {
뷰를 초기화 하는 작업과 데이터를 넣는 작업처럼 작업단위를 분리하기 위해서 입니다.
또한 뷰를 초기화 하는 작업은 매번 일어날 필요가 없기 때문입니다

2019-12-06 15:10 UTC, sjjeong commented on dksush/AndroidArchitecture/app/src/main/java/com/example/androidarchitecture/ui/blog/blogAdapter.kt
> +    val items: List<ResponseBlog>
Adapter내부에 있는 객체와 외부에 있는 객체가 공유를 한다면
외부에서 데이터를 변경 했을 때 내부에 있는 데이터도 같이 변경되기 때문에 버그가 발생 할 수 있습니다.

2019-12-06 15:16 UTC, sjjeong requested changes
blogAdapter, kinAdapter, movieAdapter 파일명이 소문자로 시작하고 있습니다.
클래스처럼 대문자로 시작해주세요

2019-12-06 15:16 UTC, sjjeong commented on dksush/AndroidArchitecture/app/src/main/java/com/example/androidarchitecture/apis/Api.kt
> +    ): Call<MovieData>
다른분이 하신 과제인데 참고해보세요
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/commit/8e03dba3503ad5fb3b91b645a6056edb8690806a

2019-12-06 15:16 UTC, sjjeong commented on dksush/AndroidArchitecture/app/src/main/java/com/example/androidarchitecture/apis/NetworkUtil.kt
> +    private val apiService: Api = getRetrofit(BASE_URL).create()
private을 제거하면 getApiService()함수가 필요 없습니다.

2019-12-06 15:16 UTC, sjjeong commented on dksush/AndroidArchitecture/app/src/main/java/com/example/androidarchitecture/ui/blog/BlogFragment.kt
> +                    recycle.layoutManager = LinearLayoutManager(activity)
layoutManager는 xml에서 선언해줄 수 있습니다.

2019-12-06 15:16 UTC, sjjeong commented on dksush/AndroidArchitecture/app/src/main/java/com/example/androidarchitecture/ui/blog/blogAdapter.kt
> +class BlogAdapter(private val context: Context) : RecyclerView.Adapter<BlogAdapter.BlogHolder>() {
Adapter에 context를 전달 할 필요가 없습니다.
외부에서 context를 전달하지 않는 방식으로 처리해주세요.

2019-12-06 23:42 UTC, dksush commented on dksush/AndroidArchitecture/app/src/main/java/com/example/androidarchitecture/apis/NetworkUtil.kt
> +    private val apiService: Api = getRetrofit(BASE_URL).create()
수정했습니다

f6784e6

2019-12-06 23:48 UTC, dksush commented on dksush/AndroidArchitecture/app/src/main/java/com/example/androidarchitecture/ui/blog/BlogFragment.kt
> +                    recycle.layoutManager = LinearLayoutManager(activity)
수정했습니다

9833e99

2019-12-07 00:06 UTC, dksush commented on dksush/AndroidArchitecture/app/src/main/java/com/example/androidarchitecture/ui/blog/blogAdapter.kt
> +class BlogAdapter(private val context: Context) : RecyclerView.Adapter<BlogAdapter.BlogHolder>() {
수정했습니다.

9952162

2019-12-07 06:48 UTC, dksush commented on dksush/AndroidArchitecture/app/src/main/java/com/example/androidarchitecture/apis/Api.kt
> +    ): Call<MovieData>
수정했습니다.

9b5c4d0

2019-12-08 14:47 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-12-09 04:00 UTC, ghost approved these changes

2019-12-09 04:01 UTC, merged