HW-1 naver api 연동 앱 구현
sjjeong/GoogryAndroidArchitecutreStudy pull request #317
Opened 2019-12-04 18:07 UTC by jjunji

HW-1 naver api 연동 앱 구현

2019-12-06 00:57 UTC, suhyeong-seo reviewed
context 대신 getActivity()를 사용해도 좋을거 같습니다.

2019-12-06 00:57 UTC, doubleclutch30 commented on jjunji/StudyApplication/app/src/main/java/com/example/studyapplication/image/ImageFragment.kt
> +        recyclerView.layoutManager = LinearLayoutManager(mContext)
context 대신 getActivity()를 사용해도 좋을거 같습니다.

2019-12-06 05:43 UTC, jjunji commented on jjunji/StudyApplication/app/src/main/java/com/example/studyapplication/image/ImageFragment.kt
> +        recyclerView.layoutManager = LinearLayoutManager(mContext)
Fragment에서 getActivity( ) 를 호출하면 null 값을 반환 받는 경우가 있다고 들었습니다.
때문에 Fragment 가 상위 액티비티에 붙어서 생성되는 시점에 context를 얻어오는게 안전하다고 생각했습니다. (정확한 이유는 모르겠어요.. ㅠ )

2019-12-07 06:00 UTC, suhyeong-seo reviewed
LayoutInflater를 생성할 때 LayoutInflater.from()을 사용하면 코드가 더 간결해 질 수 있을 듯 해요~
val view = LayoutInflater.from(parent.context).inflate(R.layout.item_blog, parent, false)
return BlogHolder(view)

```
private fun setAdapter(response : ImageList) {
        recyclerView.adapter = ImageAdapter(response.arrImageInfo)
        recyclerView.layoutManager = LinearLayoutManager(mContext)
```

2019-12-07 06:01 UTC, doubleclutch30 commented
> LayoutInflater를 생성할 때 LayoutInflater.from()을 사용하면 코드가 더 간결해 질 수 있을 듯 해요~
> val view = LayoutInflater.from(parent.context).inflate(R.layout.item_blog, parent, false)
> return BlogHolder(view)

2019-12-07 06:06 UTC, doubleclutch30 commented on jjunji/StudyApplication/.idea/codeStyles/Project.xml
> +              <order>ANDROID_ATTRIBUTE_ORDER</order>
ㄹㄷㄴㄹㄴㅇ

2019-12-07 09:52 UTC, suhyeong-seo requested changes

2019-12-07 09:52 UTC, doubleclutch30 commented on jjunji/StudyApplication/.idea/codeStyles/Project.xml
> +</component>
이파일은 gitignore 추가하시고 삭제하시는게 좋을듯 해요~~

2019-12-07 09:52 UTC, doubleclutch30 commented on jjunji/StudyApplication/.idea/codeStyles/codeStyleConfig.xml
> +</component>
이것도 마찬가지로 gitignore 처리해주시면 될거같아요~~!!

2019-12-07 09:52 UTC, doubleclutch30 commented on jjunji/StudyApplication/app/src/main/AndroidManifest.xml
> +        tools:ignore="GoogleAppIndexingWarning">
GoogleAppIndexingWarning를 선언하신 이유가 궁금해요!

2019-12-07 09:52 UTC, doubleclutch30 commented on jjunji/StudyApplication/app/src/main/java/com/example/studyapplication/MainActivity.kt
> +            .commitAllowingStateLoss()
fragment를 뷰페이저를 통해서 화면에 그려주는건 어떨까요?

2019-12-07 09:52 UTC, doubleclutch30 commented on jjunji/StudyApplication/app/src/main/java/com/example/studyapplication/blog/BlogFragment.kt
> +        view.btnSearch.setOnClickListener(btnSearchClickListener())
버튼 이벤트 부분은 onAcitvityCreated에 선언 해 주시면 좋을 것 같아요~!

2019-12-07 09:52 UTC, doubleclutch30 commented on jjunji/StudyApplication/app/src/main/java/com/example/studyapplication/image/adapter/ImageAdapter.kt
> +        val view : View = inflater.inflate(R.layout.item_image, parent, false)
LayoutInflater.from() 으로 선언해 주시면 코드가 더 간결해 질 거 같아요~

2019-12-09 15:57 UTC, jjunji commented on jjunji/StudyApplication/app/src/main/java/com/example/studyapplication/blog/BlogFragment.kt
> +        view.btnSearch.setOnClickListener(btnSearchClickListener())
c4f35d6 수정했습니다~

2019-12-09 15:57 UTC, jjunji commented on jjunji/StudyApplication/app/src/main/java/com/example/studyapplication/image/adapter/ImageAdapter.kt
> +        val view : View = inflater.inflate(R.layout.item_image, parent, false)
e2cf88e 넵 보기 훨씬 좋네요 ㅎㅎ

2019-12-09 15:58 UTC, jjunji commented on jjunji/StudyApplication/.idea/codeStyles/Project.xml
> +</component>
d492d8d 추가 했습니다~

2019-12-09 15:58 UTC, jjunji commented on jjunji/StudyApplication/.idea/codeStyles/codeStyleConfig.xml
> +</component>
d492d8d 추가 했습니다~

2019-12-09 16:02 UTC, jjunji commented on jjunji/StudyApplication/app/src/main/AndroidManifest.xml
> +        tools:ignore="GoogleAppIndexingWarning">
스튜디오 3.5.2 업데이트 이후 해당 라인 선언 안하면 lint 에 걸려서요.. warning이 보기 싫어 넣긴 했는데 정확한 이유를 모르겠네요.. 찾아보겠습니다!

2019-12-09 16:02 UTC, jjunji commented on jjunji/StudyApplication/app/src/main/java/com/example/studyapplication/MainActivity.kt
> +            .commitAllowingStateLoss()
프래그먼트 구조를 변경해야되서 멘토 리뷰 진행 후 고려해보겠습니다!

2019-12-11 04:11 UTC, suhyeong-seo approved these changes

2019-12-16 14:12 UTC, sjjeong requested changes

2019-12-16 14:12 UTC, sjjeong commented on jjunji/StudyApplication/app/src/main/java/com/example/studyapplication/MainActivity.kt
> +    private val fragmentManager : FragmentManager = supportFragmentManager
따로 변수로 빼서 가지고 있을 필요가 없습니다.

2019-12-16 14:12 UTC, sjjeong commented on jjunji/StudyApplication/app/src/main/java/com/example/studyapplication/custom/view/CustomEditTextView.kt
> +    constructor(context: Context, attrs: AttributeSet, defStyleAttr : Int) : super(context, attrs, defStyleAttr)
secondary constructor대신 primary constructor로 선언하고 default 인자를 주면 더 깔끔하게 처리할 수 있습니다.
privmary constructor에 @JvmOverloads도 추가해주시면 됩니다.

2019-12-16 14:12 UTC, sjjeong commented on jjunji/StudyApplication/app/src/main/java/com/example/studyapplication/custom/view/CustomEditTextView.kt
> +    private fun touchListener() : OnTouchListener {
사용하지 않는다면 제거해주시면 됩니다.
위에 주석도 제거해주세요

2019-12-16 14:12 UTC, sjjeong commented on jjunji/StudyApplication/app/src/main/java/com/example/studyapplication/main/blog/BlogFragment.kt
> +    lateinit var mContext : Context
Context를 들고 있을 필요가 없습니다.

2019-12-16 14:12 UTC, sjjeong commented on jjunji/StudyApplication/app/src/main/java/com/example/studyapplication/main/blog/BlogFragment.kt
> +    companion object {
companion object는 클래스 맨 아래에 선언해주는게 컨벤션입니다.

2019-12-16 14:12 UTC, sjjeong commented on jjunji/StudyApplication/app/src/main/java/com/example/studyapplication/main/blog/BlogFragment.kt
> +                    setAdapter(it)
api 요청 성공할 때마다 adapter를 set하는건 좋지 않습니다.
adapter set은 onActivityCreated에서 해주시고 여기서는 data만 변경하는 방법으로 변경해주세요

2019-12-16 14:12 UTC, sjjeong commented on jjunji/StudyApplication/app/src/main/java/com/example/studyapplication/main/blog/adapter/BlogAdapter.kt
> +class BlogAdapter(var arrBlogInfo : Array<BlogList.BlogInfo>) : RecyclerView.Adapter<BlogHolder>() {
데이터를 생성자로 주입받는건 좋지 않습니다.
외부와 리스트 객체를 공유하지 마시고 Adapter 내부에서만 사용되는 List를 만들고 함수를 통해 데이터만 넣어주는 식으로 변경해주세요

2019-12-16 14:12 UTC, sjjeong commented on jjunji/StudyApplication/app/src/main/java/com/example/studyapplication/network/ApiClient.kt
> +        private var retrofit : Retrofit? = null
lazy 패턴을 이용하시면 됩니다.

2019-12-16 14:12 UTC, sjjeong commented on jjunji/StudyApplication/app/src/main/java/com/example/studyapplication/network/ApiClient.kt
> +class ApiClient {
class 내부에 compaion object만 있다면 class대신 object로 선언하면 됩니다.

2019-12-16 14:12 UTC, sjjeong commented on jjunji/StudyApplication/app/src/main/java/com/example/studyapplication/network/ApiClient.kt
> +        private const val BASE_URL = "https://openapi.naver.com/v1/"
BASE_URL에는 도메인만 있는게 좋습니다. v1는 빼주세요

2019-12-16 14:12 UTC, sjjeong commented on jjunji/StudyApplication/app/src/main/java/com/example/studyapplication/network/IConn.kt
> +interface IConn {
interface가 I로 시작하는건 좋지 않습니다.
IService도 동일합니다.

2019-12-16 14:12 UTC, sjjeong commented on jjunji/StudyApplication/app/src/main/java/com/example/studyapplication/network/Remote.kt
> +class Remote {
object로 선언해주세요

2019-12-16 15:03 UTC, jjunji commented on jjunji/StudyApplication/app/src/main/java/com/example/studyapplication/main/blog/BlogFragment.kt
> +    companion object {
코틀린은 static한 메소드를 맨 아래에 선언하나보네요. 컨벤션 읽어보겠습니다. 감사합니다!

2019-12-16 15:05 UTC, jjunji commented on jjunji/StudyApplication/app/src/main/java/com/example/studyapplication/main/blog/BlogFragment.kt
> +    lateinit var mContext : Context
setAdapter( ) 함수 내에서 recyclerView.layoutManager = LinearLayoutManager(mContext)
를 하기 위함이었는데, 위 부분은 xml 에서 해결하고 Context 를 담은 변수는 제거했습니다.

2019-12-16 15:51 UTC, jjunji commented on jjunji/StudyApplication/app/src/main/java/com/example/studyapplication/MainActivity.kt
> +    private val fragmentManager : FragmentManager = supportFragmentManager
a20f784 제거 했습니다~

2019-12-16 15:52 UTC, jjunji commented on jjunji/StudyApplication/app/src/main/java/com/example/studyapplication/custom/view/CustomEditTextView.kt
> +    constructor(context: Context, attrs: AttributeSet, defStyleAttr : Int) : super(context, attrs, defStyleAttr)
a20f784 수정했습니다~

2019-12-16 15:52 UTC, jjunji commented on jjunji/StudyApplication/app/src/main/java/com/example/studyapplication/custom/view/CustomEditTextView.kt
> +    private fun touchListener() : OnTouchListener {
제거 했습니다!

2019-12-16 15:53 UTC, jjunji commented on jjunji/StudyApplication/app/src/main/java/com/example/studyapplication/main/blog/BlogFragment.kt
> +    lateinit var mContext : Context
21c7e4c

2019-12-16 15:53 UTC, jjunji commented on jjunji/StudyApplication/app/src/main/java/com/example/studyapplication/network/ApiClient.kt
> +        private var retrofit : Retrofit? = null
bf22561 수정했습니다!

2019-12-16 15:54 UTC, jjunji commented on jjunji/StudyApplication/app/src/main/java/com/example/studyapplication/network/ApiClient.kt
> +class ApiClient {
f4815a6 변경 했습니다.

2019-12-16 15:54 UTC, jjunji commented on jjunji/StudyApplication/app/src/main/java/com/example/studyapplication/network/ApiClient.kt
> +        private const val BASE_URL = "https://openapi.naver.com/v1/"
f4815a6 변경 했습니다.

2019-12-16 15:54 UTC, jjunji commented on jjunji/StudyApplication/app/src/main/java/com/example/studyapplication/network/Remote.kt
> +class Remote {
f4815a6 변경 했습니다.

2019-12-16 15:54 UTC, jjunji commented on jjunji/StudyApplication/app/src/main/java/com/example/studyapplication/network/IConn.kt
> +interface IConn {
네이밍 수정 했습니다~

2019-12-17 15:41 UTC, jjunji commented on jjunji/StudyApplication/app/src/main/java/com/example/studyapplication/main/blog/BlogFragment.kt
> +                    setAdapter(it)
33361ec 수정했습니다~

2019-12-17 15:43 UTC, jjunji commented on jjunji/StudyApplication/app/src/main/java/com/example/studyapplication/main/blog/adapter/BlogAdapter.kt
> +class BlogAdapter(var arrBlogInfo : Array<BlogList.BlogInfo>) : RecyclerView.Adapter<BlogHolder>() {
33361ec adapter 안에 addItem( ) 메소드 선언 후 호출 부에서 adapter.addItem( ) 하는 구조로 변경했습니다.

2019-12-17 15:53 UTC, sjjeong requested changes

2019-12-17 15:53 UTC, sjjeong commented on jjunji/StudyApplication/app/src/main/java/com/example/studyapplication/main/blog/adapter/BlogAdapter.kt
> +    private var arrBlogInfo : MutableList<BlogList.BlogInfo> = mutableListOf()
val로 선언해주세요

2019-12-17 15:53 UTC, sjjeong commented on jjunji/StudyApplication/app/src/main/java/com/example/studyapplication/main/blog/adapter/BlogAdapter.kt
> +    fun addItem(items: Array<BlogList.BlogInfo>) {
addItem이면 추가하는 느낌이 강합니다.
replaceItem이나 resetItem 으로 변경해주세요

2019-12-18 04:32 UTC, jjunji commented on jjunji/StudyApplication/app/src/main/java/com/example/studyapplication/main/blog/adapter/BlogAdapter.kt
> +    private var arrBlogInfo : MutableList<BlogList.BlogInfo> = mutableListOf()
c2a8090 수정했습니다~

2019-12-18 04:32 UTC, jjunji commented on jjunji/StudyApplication/app/src/main/java/com/example/studyapplication/main/blog/adapter/BlogAdapter.kt
> +    fun addItem(items: Array<BlogList.BlogInfo>) {
c2a8090 수정했습니다~

2019-12-18 10:23 UTC, sjjeong approved these changes
리뷰에 대한 커밋은 1리뷰 1커밋 입니다.
같은 내용이 아니라면 단위별로 나눠서 해주세요

2019-12-18 10:56 UTC, merged