HW-1 [1주차 과제] 네이버 API 연동 앱 구현
sjjeong/GoogryAndroidArchitecutreStudy pull request #318
Opened 2019-12-05 07:50 UTC by doubleclutch30

네이버 API 연동 앱 구현

2019-12-05 12:17 UTC, sjjeong commented
@doubleclutch30 
Reviewers와 Labels 추가해주세요

2019-12-06 09:12 UTC, jjunji reviewed
프로젝트가 열리면 더 자세히 볼 수 있을 것 같습니다.  확인 한번 부탁드려용

2019-12-06 09:12 UTC, jjunji commented on doubleclutch30/NaverSearchApiStudy/app/src/main/java/com/example/naversearchapistudy/MovieAdapter.kt
> +        val actor = itemView.findViewById<TextView>(R.id.movie_actor)
kotlin extensions 를 사용하면 findViewById 생략 가능합니다~

2019-12-06 09:12 UTC, jjunji commented on doubleclutch30/NaverSearchApiStudy/app/src/main/AndroidManifest.xml
> +
인터넷 사용 권한이 누락된 것 같습니다.

2019-12-06 09:12 UTC, jjunji commented on doubleclutch30/NaverSearchApiStudy/app/src/main/java/com/example/naversearchapistudy/KinFragment.kt
> +        recycleview.layoutManager = LinearLayoutManager(activity)
Fragment 사용 시 getActivity() 호출하면 간혹 null 이 반환되는 경우가 있다고 합니다.
저는 onCreateView() 시점에 inflate 한 View 로 부터 context 를 얻거나
onAttach() 주기에서 전달 받은 context 를 사용합니다.
제가 정답은 알지 못해서 이 부분에 대해 고민해 보시면 좋을 것 같습니다.

2019-12-06 10:27 UTC, doubleclutch30 commented on doubleclutch30/NaverSearchApiStudy/app/src/main/java/com/example/naversearchapistudy/MovieAdapter.kt
> +        val actor = itemView.findViewById<TextView>(R.id.movie_actor)
익스텐션을 쓰니 코드가 더 간결해 졋네요~~!!

2019-12-07 03:53 UTC, doubleclutch30 commented on doubleclutch30/NaverSearchApiStudy/app/src/main/AndroidManifest.xml
> +
네 누락된 부분 추가했습니다~

2019-12-07 03:54 UTC, doubleclutch30 commented on doubleclutch30/NaverSearchApiStudy/app/src/main/java/com/example/naversearchapistudy/KinFragment.kt
> +        recycleview.layoutManager = LinearLayoutManager(activity)
fragment 생성 주기를 한번 찾아봐야겠네요~

2019-12-08 15:02 UTC, sjjeong commented
@doubleclutch30 
리뷰이후로 추가된 커밋이 없는데 라벨은 변경되었네요
확인부탁드립니다.

2019-12-14 04:55 UTC, doubleclutch30 commented on doubleclutch30/NaverSearchApiStudy/app/src/main/AndroidManifest.xml
> +
[](0875d60)

2019-12-14 07:30 UTC, jjunji approved these changes

2019-12-16 14:31 UTC, sjjeong requested changes
현재 프로젝트가 3개가 만들어져있습니다.
작업하는 프로젝트 외에 나머지는 지워주세요
![image](https://user-images.githubusercontent.com/4777586/70914888-38307000-205c-11ea-938f-c30b1ae0ef31.png)

2019-12-16 14:31 UTC, sjjeong commented on doubleclutch30/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/network/ApiClient.kt
> +    private var retrofit: Retrofit
okHttpClient와 retrofit을 val로 선언해주세요

2019-12-16 14:31 UTC, sjjeong commented on doubleclutch30/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/network/ApiClient.kt
> +    init {
init은 property 선언부 바로 아래에 있어야합니다

2019-12-16 14:31 UTC, sjjeong commented on doubleclutch30/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/PagerAdapter.kt
> +class PagerAdapter(fm : FragmentManager) : FragmentPagerAdapter(fm) {
동작하는 것을 보니 뷰페이져는 필요 없어보입니다.

2019-12-16 14:31 UTC, sjjeong commented on doubleclutch30/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/blog/BlogAdapter.kt
> +    private val blogList : MutableList<BlogItems> = mutableListOf()
이 변수가 실제로 사용되고 있나요?
로직을 보니 생성자로 넘겨주는 것을 사용하는 것 같습니다.

2019-12-16 14:31 UTC, sjjeong commented on doubleclutch30/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/blog/BlogAdapter.kt
> +class BlogAdapter(val items : List<BlogItems>) : RecyclerView.Adapter<BlogAdapter.BlogHolder>(){
생성자로 데이터를 넘겨받지 말아주세요
외부와 리스트 객체를 공유하는 것은 좋지 않습니다.
해당 부분을 제거 해주시고 blogList를 사용해주세요

2019-12-16 14:31 UTC, sjjeong commented on doubleclutch30/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/blog/BlogAdapter.kt
> +    fun upDate(blogList : List<BlogItems>) {
update로 변경해주세요

2019-12-16 14:31 UTC, sjjeong commented on doubleclutch30/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/blog/BlogFragment.kt
> +    private fun blogListAdapter(blog: List<BlogItems>) {
recyclerview를 init하는 과정과 데이터를 set하는 로직을 분리해주세요

2019-12-18 04:33 UTC, doubleclutch30 commented on doubleclutch30/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/network/ApiClient.kt
> +    private var retrofit: Retrofit
103b9d1 수정했습니다~

2019-12-18 04:34 UTC, doubleclutch30 commented on doubleclutch30/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/network/ApiClient.kt
> +    init {
efdc43b property 선언부 아래로 이동했습니다

2019-12-18 04:35 UTC, doubleclutch30 commented on doubleclutch30/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/PagerAdapter.kt
> +class PagerAdapter(fm : FragmentManager) : FragmentPagerAdapter(fm) {
c33cc85 사용하지 않는 뷰페이져는 제거했습니다

2019-12-18 05:26 UTC, doubleclutch30 commented on doubleclutch30/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/blog/BlogAdapter.kt
> +    private val blogList : MutableList<BlogItems> = mutableListOf()
896e1a6 생성자로 넘겨주는 삭제하고 blogItem을 가리키도록 수정했습니다

2019-12-18 05:27 UTC, doubleclutch30 commented on doubleclutch30/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/blog/BlogAdapter.kt
> +class BlogAdapter(val items : List<BlogItems>) : RecyclerView.Adapter<BlogAdapter.BlogHolder>(){
896e1a6 변경했습니다!

2019-12-18 05:27 UTC, doubleclutch30 commented on doubleclutch30/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/blog/BlogAdapter.kt
> +    fun upDate(blogList : List<BlogItems>) {
update로 변경했습니다

2019-12-18 05:29 UTC, doubleclutch30 commented on doubleclutch30/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/blog/BlogFragment.kt
> +    private fun blogListAdapter(blog: List<BlogItems>) {
1a4b7eb 로직분리 했습니다

2019-12-18 16:15 UTC, sjjeong requested changes
프로젝트를 실행해볼수 있는 구조가 아니게 되었습니다.
프로젝트에 필요한 파일들을 추가해주세요

2019-12-21 02:18 UTC, sjjeong approved these changes

2019-12-21 08:22 UTC, merged