HW-2-1 기능 추가 (검색 및 BaseCurrency선택)
sjjeong/GoogryAndroidArchitecutreStudy pull request #32
Opened 2019-05-18 13:01 UTC by namjackson

늦어서 죄송합니다 ..ㅠㅠ

2019-05-19 03:32 UTC, sjjeong requested changes
@improve777 대연님이 봐주실꺼에요

2019-05-21 03:01 UTC, ddaeyeonkim requested changes
그래들 프로퍼티에 
```
android.useAndroidX=true
android.enableJetifier=true
```
를 추가해주세요

2019-05-21 03:01 UTC, ddaeyeonkim commented on namjackson/ArchStudy/app/src/main/java/com/namjackson/archstudy/view/coinlist/CoinListFragment.kt
>          timer = Timer()
타이머를 여기서 초기화 해주시는 이유가 있나요?
`onResume()` 때마다 매번 될 필요는 없어보여서요

2019-05-21 03:01 UTC, ddaeyeonkim commented on namjackson/ArchStudy/app/src/main/java/com/namjackson/archstudy/view/coinlist/CoinListFragment.kt
> +        fun newInstance(baseCurrency: String) =
`onViewCreated` 에서 `getArgument` 하는 부분이 스피너 추가 된 이후로 의미가 없어졌어요
프래그먼트 시작하면서 스피너에 첫번째 아이템이 `onItemSelected` 를 타서 `Bundle`에 뭘 넣든 
스피너 array 의 첫번째 아이템을 보게 됩니다

2019-05-21 03:01 UTC, ddaeyeonkim commented on namjackson/ArchStudy/app/src/main/java/com/namjackson/archstudy/view/coinlist/CoinListPresenter.kt
> +    private val coinList = mutableListOf<Ticker>()
프레젠터의 코인리스트에 Ticker 의 데이터를 전부 가지는 것보다 뷰에 필요한 데이터만 가지는게 좋을것 같네요

2019-05-21 03:01 UTC, ddaeyeonkim commented on namjackson/ArchStudy/app/src/main/res/layout/activity_main.xml
> +        android:id="@+id/toolbar"
리니어레이아웃의 id 가 toolbar 인건 혼동의 여지가 있을 것 같아요

2019-05-21 03:01 UTC, ddaeyeonkim commented on namjackson/ArchStudy/app/src/main/res/layout/activity_main.xml
> +                android:layout_gravity="center_vertical"
`android:layout_gravity` 가 아니라 `android:gravity` 로 바꾸시면 텍스트뷰 내부의 텍스트가 수직 중앙으로 오게 됩니다
리니어 - 리니어 - 텍스트뷰 할 필요 없이 리니어 - 텍스트뷰로 할 수 있게 돼요

2019-05-21 03:01 UTC, ddaeyeonkim commented on namjackson/ArchStudy/app/src/main/res/layout/fragment_coin_list.xml
>              android:layout_width="match_parent"
리니어레이아웃 바깥에 `FrameLayout` 으로 감싸주지 않아도 될거 같아요

2019-05-21 03:01 UTC, ddaeyeonkim commented on namjackson/ArchStudy/app/src/main/res/layout/fragment_coin_list.xml
>                      android:layout_width="0dp"
아이템 네개의 너비가 다 0dp 라 `app:layout_constraintHorizontal_chainStyle` 속성은 적용이 안되는 것 같네요
그리고 제가 생각하기에는 첫번째 아이템에만 체인스타일을 주면 되는 것 같아요

2019-05-21 03:01 UTC, ddaeyeonkim commented on namjackson/ArchStudy/app/src/main/res/layout/fragment_coin_list.xml
>                  app:layout_constraintBottom_toBottomOf="parent"
리니어레이아웃에 있어서 제약조건이 필요가 없습니다

2019-05-21 03:01 UTC, ddaeyeonkim commented on namjackson/ArchStudy/app/src/main/java/com/namjackson/archstudy/view/coinlist/adapter/CoinListAdapter.kt
>  import com.namjackson.archstudy.databinding.ItemCoinListBinding
예전 커밋에 올라온 변경사항들이라 해당 코드에 코멘트를 달아놓을 수가 없네요ㅠ
CoinListAdapter 에서 자바처럼 된 코드가 있네요. `string.equals` 나 `list.get()`
1000000L 은 상수화 해주는게 좋을 듯 합니다
그리고 저번에 onBind() 에서 되도록이면 계산하는 로직을 넣지 않는게 좋다고 하셨던 것 같아요

2019-05-21 13:10 UTC, namjackson commented on namjackson/ArchStudy/app/src/main/java/com/namjackson/archstudy/view/coinlist/CoinListFragment.kt
>          timer = Timer()
한번 cancle된 Timer객체는 재활용이 안된다고 하더라구요!

2019-05-22 16:07 UTC, namjackson commented on namjackson/ArchStudy/app/src/main/java/com/namjackson/archstudy/view/coinlist/adapter/CoinListAdapter.kt
>  import com.namjackson.archstudy.databinding.ItemCoinListBinding
네 상수화 및 onBind에서 계산하는 로직을 수정했습니다! 
34ac15f83df2d96991c9579a97d647c263ea5916

2019-05-22 16:08 UTC, namjackson commented on namjackson/ArchStudy/app/src/main/res/layout/fragment_coin_list.xml
>                      android:layout_width="0dp"
네 불필요한 체인스타일 제거완료했습니다 
역시 매의눈이시네요 !
b07afeb5dbbbc66d8a01b6974eb34564f4a6e99e

2019-05-22 16:08 UTC, namjackson commented on namjackson/ArchStudy/app/src/main/res/layout/fragment_coin_list.xml
>              android:layout_width="match_parent"
네 FrameLayout 수정했습니다! 
081a67b9060767cc20ace9e0ad842341e59902fa

2019-05-22 16:10 UTC, namjackson commented on namjackson/ArchStudy/app/src/main/res/layout/activity_main.xml
> +        android:id="@+id/toolbar"
툴바에서 ll_title로 변경했습니다! 
생각없이 네이밍 했는데 진짜 toolbar와 혼동될수도 있겠네요
894956c3a966e9a37b9b128d32e5f69c76ed16bd

2019-05-22 16:13 UTC, namjackson commented on namjackson/ArchStudy/app/src/main/java/com/namjackson/archstudy/view/coinlist/CoinListPresenter.kt
> +    private val coinList = mutableListOf<Ticker>()
List를 말씀하시는거라면 , 
검색할때  remote에서 가져오는게 아니라 
현재 들고있는 List에서 필터링하도록 로직이 구현되어있어
리스트는 가지고 있습니다! 

`private fun showCoinList() {
        coinListView.showCoinList(coinList.filter { it.name.contains(searchStr.toUpperCase()) })
    }`

더 좋은 방법이 어떤게 있을까요?

2019-05-22 16:15 UTC, namjackson commented on namjackson/ArchStudy/app/src/main/res/layout/activity_main.xml
> +                android:layout_gravity="center_vertical"
좋은 지적감사합니다 ! 
286a95f0631df1f59f28cb75ab7709e412736d66

2019-05-22 16:22 UTC, namjackson commented on namjackson/ArchStudy/app/src/main/java/com/namjackson/archstudy/view/coinlist/CoinListFragment.kt
> +        fun newInstance(baseCurrency: String) =
오 역시 예리하시네요! 
해당 부분 변경했습니다! 
4d1b2cc4a718d25ef352ee7ec7d402e4145df100

2019-05-22 16:28 UTC, namjackson commented on namjackson/ArchStudy/app/src/main/res/layout/fragment_coin_list.xml
>                  app:layout_constraintBottom_toBottomOf="parent"
7eb03a15ae5b4d19fea416a0ee209239c1f9555b

2019-05-22 16:29 UTC, namjackson commented
추가적으로 data모델 부분 구조를 수정했습니다! 
많은 리뷰해주시면 감사하겠습니다!

2019-05-22 16:31 UTC, Hoyuo requested changes

2019-05-22 16:31 UTC, Hoyuo commented on namjackson/ArchStudy/app/src/main/java/com/namjackson/archstudy/view/coinlist/CoinListFragment.kt
> +        binding.recyclerView.visibility = View.GONE
별도의 메서드로 해주시는걸 추천합니다

2019-05-22 16:31 UTC, Hoyuo commented on namjackson/ArchStudy/app/src/main/java/com/namjackson/archstudy/view/coinlist/CoinListFragment.kt
> +        binding.recyclerView.visibility = View.VISIBLE
같습니다

2019-05-22 16:40 UTC, namjackson commented on namjackson/ArchStudy/app/src/main/java/com/namjackson/archstudy/view/coinlist/CoinListFragment.kt
> +        binding.recyclerView.visibility = View.GONE
어떤식으로 묶는게 좋을까요ㅠㅠ?

2019-05-23 02:50 UTC, ddaeyeonkim submitted a review, later dismissed
LGTM 👍👍👍

2019-05-26 05:28 UTC, namjackson commented on namjackson/ArchStudy/app/src/main/java/com/namjackson/archstudy/view/coinlist/CoinListFragment.kt
> +        binding.recyclerView.visibility = View.VISIBLE
5de10e7af977da6995d7763a41bf97715d3bb69e

2019-05-26 05:28 UTC, namjackson commented on namjackson/ArchStudy/app/src/main/java/com/namjackson/archstudy/view/coinlist/CoinListFragment.kt
> +        binding.recyclerView.visibility = View.GONE
5de10e7af977da6995d7763a41bf97715d3bb69e
수정했습니다!

2019-05-26 10:37 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-05-26 14:24 UTC, ddaeyeonkim approved these changes
LGTM 👍👍👍

2019-05-27 05:40 UTC, merged