Class07/init readme
sjjeong/GoogryAndroidArchitecutreStudy pull request #323
Opened 2019-12-06 16:39 UTC by AhnHyeonho

7기  안현호 사전과제 - README.md 수정 및 개인공간 생성

2019-12-07 02:00 UTC, sjjeong requested changes

2019-12-07 02:00 UTC, sjjeong commented on README.md
> -
라인 구분하는 부분 제거 하지 말아주세요

2019-12-07 05:51 UTC, AhnHyeonho commented
라인구분 추가하였습니다.

2019-12-08 02:06 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-12-09 06:17 UTC, merged