HW-2 모델 레이어 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #324
Opened 2019-12-07 06:14 UTC by wooooooak

2019-12-07 17:56 UTC, JayYi requested changes

2019-12-07 17:56 UTC, JayYi commented on wooooooak/StudyApp/app/src/main/java/wooooooak/com/studyapp/data/model/datasource/local/NaverLocalDataSource.kt
> +    suspend fun getBlogList(title: String, startIndex: Int?): List<Blog>
startIndex에 nullable type보다는 default 값을 설정해주는 것이 좋을 것 같아요

2019-12-08 01:48 UTC, wooooooak commented on wooooooak/StudyApp/app/src/main/java/wooooooak/com/studyapp/data/model/datasource/local/NaverLocalDataSource.kt
> +    suspend fun getBlogList(title: String, startIndex: Int?): List<Blog>
반영했습니다. 감사합니다~!

4861cb51f8e6d2455d0cda8257d7e4ade5b28a3e

2019-12-08 13:22 UTC, JayYi commented on wooooooak/StudyApp/app/src/main/java/wooooooak/com/studyapp/data/model/datasource/local/NaverLocalDataSource.kt
> +    suspend fun getBlogList(title: String, startIndex: Int?): List<Blog>
API 명세서 보니 default 값이 1이던데 0으로 넘겼을 때 문제가 없나요?

2019-12-08 13:44 UTC, wooooooak commented on wooooooak/StudyApp/app/src/main/java/wooooooak/com/studyapp/data/model/datasource/local/NaverLocalDataSource.kt
> +    suspend fun getBlogList(title: String, startIndex: Int?): List<Blog>
아 1이었군요 ㅎㅎ
0으로 넘겨도 에러는 없었지만 아마도 응답 받은 갯수가 하나 적었을것 같네요..
반영했습니다!

e12412bd32a125090584733cf921033ce1fbbb70

2019-12-09 13:30 UTC, JayYi approved these changes

2019-12-09 15:09 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋
역시 코루틴이라서 코드가 엄청 깔끔하고 코드체인지가 별로 없네요
Adapter에 repository가 들어가는게 이상하지만 다음 스터디때 MVP 를 공부하고나서 개선될 작업이기 때문에 이번 pr에서는 approve 하겠습니다~

2019-12-10 01:27 UTC, merged