HW-4 최신 검색 결과 cache 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #326
Opened 2019-12-07 20:04 UTC by bean628

최신 검색 결과 cache 적용 과제 제출합니다~

검색하면 캐시 파일이 저장됩니다.
앱을 종료 후 실행시 가장 마지막 검색 리스트가 보입니다.

리뷰 부탁드립니다~~

2019-12-09 10:43 UTC, ironelder reviewed
리뷰사항 확인부탁드립니다~

2019-12-09 10:43 UTC, ironelder commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/data/source/NaverRepository.kt
> +    private const val CACHE_FILE_PATH = "/data/user/0/com.practice.achitecture.myproject/cache/"
FilePath의 경우 리소스항목으로 이동하는 것이 차후 유지보수에 좋을 것 같습니다

2019-12-09 10:43 UTC, ironelder commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/data/source/local/NaverLocalDataSourceImpl.kt
> +}
해당 클래스가 하는 업무가 없는 것 같습니다

2019-12-09 10:43 UTC, ironelder commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/data/source/NaverRepository.kt
> +                    setCache(searchType, items)
데이터를 불러오는 부분은 프레젠터에서 하는데 저장하는 부분도 프레젠터에서 하는것이 일관성이 있지 않을까 싶습니다.

2019-12-10 12:20 UTC, BeokBeok commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/data/source/NaverRepository.kt
> +    private const val CACHE_FILE_PATH = "/data/user/0/com.practice.achitecture.myproject/cache/"
Context 의 `cacheDir` 을 사용하시면 좋을 것 같아요.

2019-12-11 14:56 UTC, bean628 commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/data/source/NaverRepository.kt
> +    private const val CACHE_FILE_PATH = "/data/user/0/com.practice.achitecture.myproject/cache/"
스터디시간에 Repository 쪽에 Context 사용을 피하라고 들었던것 같아서요.
두 분께서 리뷰해주신 방법 모두 context가 필요한데 어떻게 해야할까요...?

2019-12-11 14:56 UTC, bean628 commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/data/source/NaverRepository.kt
> +                    setCache(searchType, items)
setCache() 부분을 말씀하시는 건가요?
이번주 과제를 하면서 data 부분은 구글 todo app과 가능하면 비슷한 구조로 만들려고 했습니다.

Repository가 remote 와 local 소스를 가지고 있고 캐시 관련 처리도 Repository에서 처리하고 있어서 해당 파일에서 구현했습니다.

2019-12-11 15:02 UTC, bean628 commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/data/source/local/NaverLocalDataSourceImpl.kt
> +}
이번주엔 시간이 안나서 ㅠㅠ 자율과제인 검색 결과 히스토리 화면 작업을 할 때 Room과 함께 사용하려고 아직 비워둔 상태였었습니다.
TODO로 함수에 동작이 없는 이유를 알 수 있도록 주석을 달았습니다! 
이번 PR 끝나면 17일까지 추가 작업해서 올리겠습니다!!

fbed6ef

2019-12-12 00:29 UTC, BeokBeok commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/data/source/NaverRepository.kt
> +    private const val CACHE_FILE_PATH = "/data/user/0/com.practice.achitecture.myproject/cache/"
Repository 생성 시, view 단에서 `cacheDir` 로 만든 String 을 인자로 넘겨주면 될 것 같아요.

2019-12-12 14:31 UTC, bean628 commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/data/source/NaverRepository.kt
> +    private const val CACHE_FILE_PATH = "/data/user/0/com.practice.achitecture.myproject/cache/"
Repository가 object여서 생성자에 넣을 수가 없더라구요. 
캐시 폴더 경로를 담을 property를 추가한 후 프레젠터에서 set하는 방식으로 구현했습니다!

91403a6

2019-12-13 00:35 UTC, BeokBeok commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/data/source/NaverRepository.kt
> +    private const val CACHE_FILE_PATH = "/data/user/0/com.practice.achitecture.myproject/cache/"
`object` 대신 `class` 로 만드셔서 생성자에 넣으시는 것은 어떠신가요?

2019-12-18 14:32 UTC, bean628 commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/data/source/NaverRepository.kt
> +    private const val CACHE_FILE_PATH = "/data/user/0/com.practice.achitecture.myproject/cache/"
넵 수정했습니다!

d24157d5

2019-12-19 16:26 UTC, sjjeong requested changes

2019-12-19 16:26 UTC, sjjeong commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/base/BaseActivity.kt
> +        progress_bar?.visibility = View.VISIBLE
activity_main을 참조하고 있습니다.
이런 경우에는 findViewById를 사용하는게 좋습니다.

2019-12-19 16:26 UTC, sjjeong commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/data/source/NaverRepository.kt
> +    private val naverLocalDataSource: NaverLocalDataSourceImpl,
파일 관련 처리를 모두 NaverLocalDataSourceImpl 내부에서 처리해야합니다.
그리고 Repository에서는 naverLocalDataSource의 함수를 호출하기만 하면 됩니다.

2019-12-19 16:26 UTC, sjjeong commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/data/source/NaverRepository.kt
> +                    setCache(searchType, items)
여기서 하는게 맞습니다.

2019-12-21 04:56 UTC, bean628 commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/base/BaseActivity.kt
> +        progress_bar?.visibility = View.VISIBLE
findViewById를 사용했지만 여전히 activity_main을 참조하고있어서 이렇게 하길 바라신건 아닌것 같은데 일단 커밋했어요. 확인 부탁드려요~!

cd4b2768

2019-12-21 05:29 UTC, bean628 commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/data/source/NaverRepository.kt
> +    private val naverLocalDataSource: NaverLocalDataSourceImpl,
수정했습니다!

a1eabd61

2019-12-21 08:39 UTC, sjjeong commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/base/BaseActivity.kt
> +        progress_bar?.visibility = View.VISIBLE
open var로 nullable하게 만들어서 사용하면 더 좋을 것 같습니다.

2019-12-21 08:40 UTC, sjjeong commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/base/BaseActivity.kt
> +        progress_bar?.visibility = View.VISIBLE
만약 id를 동일하게 가져간다고 한다면 base에서 find하시고 nullable로 선언해주시면 됩니다.

2019-12-21 13:26 UTC, bean628 commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/base/BaseActivity.kt
> +        progress_bar?.visibility = View.VISIBLE
open var 로 수정했습니다!

342ee0b8

2019-12-23 11:59 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-12-23 12:11 UTC, ironelder approved these changes

2019-12-24 00:05 UTC, merged