HW-2 model layer 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #327
Opened 2019-12-08 13:27 UTC by JayYi

[2주차 과제] model layer 적용
- repository 생성
- datasource remote/local 생성

2019-12-08 14:23 UTC, gitpushyj requested changes
리뷰 완료했습니다~:D

2019-12-08 14:23 UTC, gitpushyj commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/data/repository/NaverSearchRepositoryImpl.kt
> +        success: (ResponseMovie) -> Unit,
success, fail이란 단어가 함수라는 것을 명확하게 하기 위해 onSuccess나 onFail로 하는 것은 어떤가요?
안드로이드에서 click되었을때 이벤트를 받는 함수 이름이 'onClick'인 것 처럼요.

2019-12-08 14:23 UTC, wooooooak commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/network/NetworkException.kt
> +    val statusCode: Int,
statusCode는 해당 클래스에서 쓰이지 않나요?
쓰이지 않으면 없애도 될 것 같습니다!

2019-12-08 14:23 UTC, wooooooak commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/network/NetworkException.kt
> +                        return NetworkException(response. code(), it.errorCode, it.errorMessage)
code() <- 이 코드 어떻게...동작하는건가요??
생성자로 code를 String 타입으로 받았는데 함수처럼 동작할수 있는건가요....(혼란)

2019-12-08 14:23 UTC, wooooooak commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/util/ResponseExt.kt
> +    }
아마 항상 Nothing? 타입으로 리턴될 것 같은데...
let()은 인자로 받은 코드블럭의 결과를 자동으로 return해주기 때문에 마지막에 넣으신 return 키워드는 빼셔야 할것 같아요!

2019-12-09 06:24 UTC, JayYi commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/network/NetworkException.kt
> +    val statusCode: Int,
statusCode는 http code여서 네트워크 통신 중에 사용됩니다.

2019-12-09 13:40 UTC, JayYi commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/data/repository/NaverSearchRepositoryImpl.kt
> +        success: (ResponseMovie) -> Unit,
success, fail의 경우에는 실행 함수로 생각해서 일반적인 이름을 사용했습니다.

```
  fun onClick() {
      doSomething()
  }
```

위와 같이 이벤트가 트리거되는 부분은 prefix에 on 을 사용하고 이벤트가 트리거가 되었을 때 실행되는 로직은 prefix를 사용하지 않는 것으로 이해하고 선언했습니다.

사실 이 부분에 대해서 잘 몰라 방금 리서치를 해봤는데 정답을...찾을 수가 없네요....
success, fail은 실행함수로 생각하고 있는데 용준님은 어떻게 생각하시나요?

2019-12-09 13:41 UTC, JayYi commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/network/NetworkException.kt
> +                        return NetworkException(response. code(), it.errorCode, it.errorMessage)
띄어쓰기가 잘 못 들어갔네요...그래도 에러 없이 돌아 갔다는게...신기하네요..

수정했습니다.
4e679de83e935dcae3c68c069eee5f77934b8b9e

2019-12-09 13:43 UTC, JayYi commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/util/ResponseExt.kt
> +    }
다행인지는 모르겠지만 정상적으로 코드가 돌아가네요.
그래도 문제의 소지가 있어보이니 리뷰 반영해서 수정했습니다.
fb2ac0285d95eb0bea978b7f2b802cef0ab89063

2019-12-10 00:43 UTC, wooooooak commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/data/repository/NaverSearchRepositoryImpl.kt
> +        success: (ResponseMovie) -> Unit,
민재님 말씀도 일리가 있네요 ㅎㅎ
success나 fail은 명사로 인식되는 경우가 많아서  "명사()" 이렇게 실행되는게 어색하지 않을까해서 댓글 남겼었는데요, 저도 찾아보니 고차함수에 들어가는 함수 파라미터명은 명사로 쓰기도하고, 동사형태로 쓰기도 하네요.
이 부분은 정답이 있다기 보다는 프로젝트 팀원들과의 합의 문제가 아닐까 싶어요 ㅎㅎ
승인 누르겠습니다!

2019-12-10 00:43 UTC, gitpushyj approved these changes

2019-12-10 03:02 UTC, BeokBeok commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/data/repository/NaverSearchRepositoryImpl.kt
> +        success: (ResponseMovie) -> Unit,
지나가다가 첨언을 드리고 싶어서 잠깐 들렸습니다.

함수는 하나의 동작 단위이기 때문에, 동사구로 함수명을 작성하는 것이 좋을 것 같습니다.
또한 함수타입의 경우에는
함수타입을 받아서 해당 함수 내부에서 처리하는 경우에는 변수명으로 취급하여 명사로 사용하고(`aaa.invoke()`)
함수타입을 받아서 콜백 형식으로 처리하는 경우에는 앞에 `on` 을 붙여주는 것이 좋을 것 같습니다. 😅

2019-12-10 03:57 UTC, JayYi commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/data/repository/NaverSearchRepositoryImpl.kt
> +        success: (ResponseMovie) -> Unit,
@BeokBeok 
설명 감사합니다!

2019-12-17 15:24 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-12-17 15:36 UTC, merged