HW-4-과제-로컬저장소에 검색결과 저장 및 불러오기
sjjeong/GoogryAndroidArchitecutreStudy pull request #334
Opened 2019-12-10 11:47 UTC by ironelder

HW-4-과제-로컬저장소에 검색결과 저장 및 불러오기

2019-12-11 14:08 UTC, bean628 reviewed
제가 repository에 대해서 잘 못 이해한걸 수 도 있는데
제가 생각하기엔 repository가 여러개일 수 있지만 각각의 repository에 해당 소스에 맞는 local과 remote가 나뉜다고 이해했거든요.  

그런데 진혁님 data 패키지에 repository 자체가 local 하고 remote로 나눠져있고 source도 remote랑 local이랑 나눠져 있더라구요.  repository 하나에 remote와 local 소스를 담는건 어떻게 생각하시나요?

2019-12-11 14:10 UTC, bean628 commented
> 제가 repository에 대해서 잘 못 이해한걸 수 도 있는데
> 제가 생각하기엔 repository가 여러개일 수 있지만 각각의 repository에 해당 소스에 맞는 local과 remote가 나뉜다고 이해했거든요.
> 
> 그런데 진혁님 data 패키지에 repository 자체가 local 하고 remote로 나눠져있고 source도 remote랑 local이랑 나눠져 있더라구요. repository 하나에 remote와 local 소스를 담는건 어떻게 생각하시나요?

코드상 리뷰를 뭔가 더 하고 싶었지만.. ㅠㅠ 지금 제 실력으로는 이거 하나밖에는 안보이네요 ㅠㅠ

2019-12-15 06:28 UTC, ironelder commented
@bean628 
Repository에서 DataSource의 Local과 Remote를 통합시켰습니다~


0a0ea08
22faee4
853652c

2019-12-17 15:48 UTC, sjjeong requested changes

2019-12-17 15:48 UTC, sjjeong commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/view/mainview/MainFragment.kt
> +        presenter.setSearchResultToRoom(
캐싱하는 작업을 여기서 하면 안됩니다.
RemoteDataSource -> Repository 할 때 Repository에서 LocalDataSource에 저장하는 로직을 구현하면 됩니다.

2019-12-19 03:48 UTC, ironelder commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/view/mainview/MainFragment.kt
> +        presenter.setSearchResultToRoom(
Local저장을 Repository에서 수행하도록 수정해보았습니다

다만 context를 넘겨받아야 하는데 이렇게 하는게 맞는지 모르겠습니다

48cb358

2019-12-19 15:18 UTC, sjjeong commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/view/mainview/MainFragment.kt
> +        presenter.setSearchResultToRoom(
@ironelder 
context대신 context를 사용해서 가져오는 것을 넘겨주시면 됩니다.
SearchResultDatabase.getInstance(context) 로 리턴되는 instance를 넘겨주세요

2019-12-19 23:46 UTC, ironelder commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/view/mainview/MainFragment.kt
> +        presenter.setSearchResultToRoom(
Repository에는 Instance를 넘겨주도록 변경했습니다~

@sjjeong 
Presenter에서는 Context를 참조 받아도 괜찮을까요?
아니면 View에서부터 Instance를 생성해서 줘야 하는 건지 궁금합니다


8fc2463

2019-12-20 02:49 UTC, sjjeong commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/view/mainview/MainFragment.kt
> +        presenter.setSearchResultToRoom(
@ironelder 
Presenter에는 context가 들어가면 좋지 않습니다.
View에서 만들어서 넘겨주세요

2019-12-21 04:23 UTC, ironelder commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/view/mainview/MainFragment.kt
> +        presenter.setSearchResultToRoom(
presenter에서 context를 참조하지 않도록 수정하였습니다.

@sjjeong 
Database의 경우 null일 경우에
```
SearchLocalDatabase.getInstance(context).let{
...
}
```

위의 처럼 처리하는게 좋을까요 혹은 받는 파라미터 인자를 ? 를 붙여서  nullable로 받는게 좋을까요?

2019-12-23 12:10 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-12-24 00:04 UTC, bean628 approved these changes

2019-12-24 00:05 UTC, merged