HW-4 마지막 검색한 결과 Local에 저장, 앱 시작했을 때 검색어와 결과리스트를 화면에 표시
sjjeong/GoogryAndroidArchitecutreStudy pull request #335
Opened 2019-12-12 12:05 UTC by taeiim

2019-12-13 06:19 UTC, 2giwon requested changes

2019-12-13 06:19 UTC, 2giwon commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/base/BaseActivity.kt
> +abstract class BaseActivity : AppCompatActivity() {
이 코드는 아무것도 하지 않는 것 같습니다.

넣으신 의도가 있나요? ㅎ

2019-12-13 06:19 UTC, 2giwon commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/base/BaseFragment.kt
> +abstract class BaseFragment : Fragment() {
이 코드는 아무것도 하지 않는 것 같습니다.

넣으신 의도가 있나요? ㅎ

2019-12-13 06:19 UTC, 2giwon commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/base/BasePresenter.kt
> +    fun start()
이 코드도 어떤 역할을 하지 않는 것 같습니다.

어떤 의도 인지 궁금합니다.

2019-12-13 06:19 UTC, 2giwon commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/data/source/NaverRepositoryImpl.kt
> +        @JvmStatic
companion object에 jvmStatic은 안붙여도 됩니다.

2019-12-13 06:19 UTC, 2giwon commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/data/source/local/NaverLocalDataSourceImpl.kt
> +                synchronized(NaverLocalDataSourceImpl::javaClass) {
synchronized를 if문 아래에 넣은 이유가 있나요?ㅎ

2019-12-13 06:19 UTC, 2giwon commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/data/source/local/SearchHistoryDatabase.kt
> +                        .allowMainThreadQueries()
이 코드는 어떤 처리를 하는건가요? 궁금합니다.

2019-12-13 06:19 UTC, 2giwon commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/ContentsPresenter.kt
> +                if (it != null)
전달해주는 값이 nonnull이라서 이 코드는 필요 없어 보입니다.

2019-12-13 06:19 UTC, 2giwon commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/ContentsPresenter.kt
> +    override fun start() {
아무것도 하지 않는 함수 인 것 같습니다. 지워도 되지 않나요? ㅎ

2019-12-13 06:19 UTC, 2giwon commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/ContentsPresenter.kt
> +        view.presenter = this
this를 넘겨주는 이유가 있나요? 어떤 의도이신지 궁금합니다 ㅎ

2019-12-13 06:19 UTC, 2giwon commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/ContentsFragment.kt
> +    override lateinit var presenter: ContentsContract.Presenter
BaseView에서 var로 선언을 해서 이 presenter도 lateinit을 쓰신거 같습니다.

중간에 presenter가 바뀌는 일이 없다면 val로 선언하는 게 낫다고 봅니다.

2019-12-18 10:07 UTC, taeiim commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/base/BaseActivity.kt
> +abstract class BaseActivity : AppCompatActivity() {
나중에 BaseActivity를 사용할 일이 있을거라 생각하고 추가하였습니다 ㅎㅎ ㅜㅜ 
(사실 rx 과제 하려구 base 추가했었습니당,,ㅋㅋㅠㅠㅠ )

2019-12-18 10:07 UTC, taeiim commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/base/BaseFragment.kt
> +abstract class BaseFragment : Fragment() {
위와 같습니다 ㅎㅎ

2019-12-18 11:31 UTC, taeiim commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/base/BasePresenter.kt
> +    fun start()
위와 같이 나중에 사용하려고 만들어놨습니다ㅜㅜ

2019-12-19 16:32 UTC, sjjeong requested changes

2019-12-19 16:32 UTC, sjjeong commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/data/source/NaverRepositoryImpl.kt
> +        @JvmStatic
자바에서 사용하는 경우라면 붙여야 코드를 깔끔하게 쓸 수 있지만
코틀린만 사용하는 경우라면 붙이지 않아도 됩니다.

2019-12-19 16:32 UTC, sjjeong commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/data/source/local/SearchHistoryDatabase.kt
> +                        .allowMainThreadQueries()
함수명만 봐서는 MainThread에서도 데이터를 가져올 수 있도록 해주는 것 같아요
원래 Room은 MainThread에서 접근하면 ui가 lock이 되기 때문에 Exception을 내버리거든요

2019-12-19 16:32 UTC, sjjeong commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/ContentsFragment.kt
> +    override lateinit var presenter: ContentsContract.Presenter
저도 동일하게 생각합니다.
lateinit var 보단 lazy로 해주세요

2019-12-19 16:32 UTC, sjjeong commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/ContentsPresenter.kt
> +                    naverRepository.saveSearchResult(SearchHistory(it.items, searchType, query))
저장하는건 Presenter쪽이 아니라 Repository 안에서 해주시면 됩니다.

2019-12-19 16:32 UTC, sjjeong commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/ContentsPresenter.kt
> +                if (it != null)
만약 nullcheck를 이렇게 하신다면 ?.let으로 하시면 됩니다.

2019-12-20 17:46 UTC, taeiim commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/data/source/NaverRepositoryImpl.kt
> +        @JvmStatic
제거하였습니다. 감사합니다!

commit : 88eb992a4e1aafdfd11fb2aff2542f31781dcafe

2019-12-20 17:46 UTC, taeiim commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/data/source/local/NaverLocalDataSourceImpl.kt
> +                synchronized(NaverLocalDataSourceImpl::javaClass) {
기원님 리뷰 보기전에 짠 코드입니다 ㅜㅜ 수정하였습니다 ㅎㅎ

commit : 3fcae494fb6c3ce7809ab28e0c471bb38ca792f4

2019-12-20 17:48 UTC, taeiim commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/data/source/local/SearchHistoryDatabase.kt
> +                        .allowMainThreadQueries()
맞습니다. 메인쓰레드에서 데이터베이스 접근을 허용하기 위한 코드입니다

2019-12-20 17:49 UTC, taeiim commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/ContentsPresenter.kt
> +                if (it != null)
null check를 하지 않으면 room 에 저장되어 있는 값이 없을때 강제종료되어 체크 코드를 넣었습니다. 
 ?.let으로 변경하였습니다ㅎㅎ!

commit : f1d576338c6437424e47f8497286e66193dae099

2019-12-20 17:49 UTC, taeiim commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/ContentsPresenter.kt
> +    override fun start() {
나중을 위하여 생성해놨던 함수입니다.. ㅜㅜㅜ

2019-12-20 17:49 UTC, taeiim commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/ContentsPresenter.kt
> +        view.presenter = this
제거하였습니다. 

commit : c3d0ee8301175236ed42d227b8240f602a98bc9d

2019-12-20 17:50 UTC, taeiim commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/ContentsFragment.kt
> +    override lateinit var presenter: ContentsContract.Presenter
lazy로 변경하였습니다. 감사합니다 !

commit : 65fbb3351a205c4ff3c2cdd4579d152889339610

2019-12-29 07:25 UTC, taeiim commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/ContentsPresenter.kt
> +                    naverRepository.saveSearchResult(SearchHistory(it.items, searchType, query))
수정했습니다!!!!!!!!!!!

commit : ff419d11192baaea8820c94efeeb7ca9a32a4576

2019-12-29 08:46 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-01-01 15:35 UTC, merged