HW-3 MVP 과제
sjjeong/GoogryAndroidArchitecutreStudy pull request #338
Opened 2019-12-18 05:27 UTC by developerkhm

View와 Model, 비지니스 로직을 분리한 MVP Presenter 과제

2019-12-19 16:19 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-12-21 07:39 UTC, buddman1208 reviewed
비어있는 부분 외에는 괜찮은것 같습니다!

2019-12-21 07:39 UTC, buddman1208 commented on developerkhm/AndroidStudy/app/src/main/java/com/example/androidstudy/ui/base/BaseFragment.kt
> +    override fun showNoSearchData() {
이 부분이 비어있는 이유가 있을까요?

2019-12-28 08:44 UTC, buddman1208 requested changes
확인했습니다!

2019-12-28 08:45 UTC, buddman1208 approved these changes
확인했습니다! (이전걸 잘못 올렸네요)

2019-12-30 04:46 UTC, merged