Class02/readme init
sjjeong/GoogryAndroidArchitecutreStudy pull request #34
Opened 2019-05-21 15:58 UTC by Nanamare

프로필 추가 작업

2019-05-21 16:16 UTC, sjjeong commented
요구사항을 잘못 파악하신것 같습니다.
이번 과제는 `upstream에 root/README.md파일에 본인 기수 항목에 이름/프로필링크/폴더링크를 추가한다.`입니다.
본인 공간에 readme 추가해주는 작업도 진행해주셔야 합니다.
그리고 sample project만드는 것은 다음 과제 입니다.

2019-05-21 16:20 UTC, sjjeong requested changes
요구사항을 잘못 파악하신것 같습니다.
이번 과제는 `upstream에 root/README.md파일에 본인 기수 항목에 이름/프로필링크/폴더링크를 추가한다.`입니다.
본인 공간에 readme 추가해주는 작업도 진행해주셔야 합니다.
그리고 sample project만드는 것은 다음 과제 입니다.

이번 과제만 들어가게 해서 작업해주세요.

2019-05-21 16:39 UTC, Nanamare commented
이런 식으로 하면 될까요 ~?
확인하시고 잘못된 부분 말씀해주세요:)

2019-05-22 11:33 UTC, sjjeong requested changes

2019-05-22 11:33 UTC, sjjeong commented on README.md
> -[공간](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/tree/master/Nana)
StudyFork저장소에 master브랜치에 머지 될 것 이여서 
```
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/tree/master/Nanamare
```
로 해주시면 됩니다.

2019-05-22 11:38 UTC, Nanamare commented on README.md
> -[공간](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/tree/master/Nana)
수정 완료 하였습니다.

2019-05-28 15:18 UTC, sjjeong submitted a review, later dismissed
LGTM ✊ ✌️ 👋

2019-05-30 10:58 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-05-30 10:59 UTC, merged