HW-2 프로젝트 추가
sjjeong/GoogryAndroidArchitecutreStudy pull request #346
Opened 2019-12-20 06:56 UTC by AhnHyeonho

1. 본인폴더를 와 README.md를 제외한 폴더를 제거하였습니다.
2. androidx 기반 kotlin 사용 프로젝트를 생성하고 gitignore와 함께 추가하였습니다.

2019-12-20 08:51 UTC, sjjeong requested changes
Reviewers, Assignees 추가해주세요

2019-12-20 08:54 UTC, AhnHyeonho commented
추가하였습니다.

2019-12-20 11:38 UTC, sjjeong requested changes

2019-12-20 11:38 UTC, sjjeong commented on AhnHyeonho/.gitignore
> +
이 파일은 프로젝트 안에 있어야합니다.

2019-12-21 08:57 UTC, AhnHyeonho commented
gitignore 파일 위치 수정하였습니다. 확인 부탁 드립니다.

2019-12-21 09:19 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-12-21 09:20 UTC, merged