HW-3 MVP 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #361
Opened 2019-12-22 04:08 UTC by wooooooak

MVP를 적용한 PR입니다.

2019-12-22 13:11 UTC, JayYi reviewed
확인 부탁드려요.

2019-12-22 13:11 UTC, JayYi commented on wooooooak/StudyApp/app/src/main/java/wooooooak/com/studyapp/ui/blog/BlogListAdatper.kt
> +    private val itemListener: ItemListener<Blog>
listener 는 property로 선언하는게 좋을 것 같습니다.

2019-12-22 13:11 UTC, JayYi commented on wooooooak/StudyApp/app/src/main/java/wooooooak/com/studyapp/ui/blog/BlogFragment.kt
> +                presenter.fetchMoreItems(list, index)
검색창에 입려된 input 값이랑 불러오는 아이템 목록이랑 다른 경우가 생기네요. 
예를 들면 검색을 한 후에 사용자가 검색어를 삭제 한 상태에서 계속 페이지를 넘기는 경우에는 이전의 검색어로 처리 되는게 맞는상황인지 한번 고민해봐야 될 것 같아요.

2019-12-23 04:11 UTC, wooooooak commented on wooooooak/StudyApp/app/src/main/java/wooooooak/com/studyapp/ui/blog/BlogListAdatper.kt
> +    private val itemListener: ItemListener<Blog>
음...이미 프로퍼티인데..... 무슨 말씀이신지 잘 모르겠습니다ㅠ
코틀린에서는 주 생성자에서 val 로 선언함으로써 자동적으로 프로퍼티가 되는데, 이부분 말씀하시는게 맞는건가요??

2019-12-23 04:14 UTC, wooooooak commented on wooooooak/StudyApp/app/src/main/java/wooooooak/com/studyapp/ui/blog/BlogFragment.kt
> +                presenter.fetchMoreItems(list, index)
"나는" 을 입력하고 검색 버튼을 누르면 리스트들이 랜더링되는데, 이 상태에서 검색어를 지우고 스크롤을 내려도 계속 랜더링 되는 걸 말씀하시는건가요..??
만약 맞다면 의도한게 맞습니다...ㅎㅎ Search 버튼이 있기때문에, Search버튼을 클릭하지 않으면 아무 변화도 일어나지 않도록 기획해서요.

혹시 말씀하신게 이게 아니라면 다시 알려주세요ㅠㅠ

2019-12-23 04:35 UTC, JayYi commented on wooooooak/StudyApp/app/src/main/java/wooooooak/com/studyapp/ui/blog/BlogListAdatper.kt
> +    private val itemListener: ItemListener<Blog>
아 제가 제대로 설명을 못드렸네요. 생성자로 넘기지 말고 별도의 변수로 선언하는게 어떨까 해서 댓글 남겼습니다.

2019-12-23 04:43 UTC, JayYi commented on wooooooak/StudyApp/app/src/main/java/wooooooak/com/studyapp/ui/blog/BlogFragment.kt
> +                presenter.fetchMoreItems(list, index)
네 설명해주신 부분이 맞습니다.

2019-12-23 04:48 UTC, wooooooak commented on wooooooak/StudyApp/app/src/main/java/wooooooak/com/studyapp/ui/blog/BlogListAdatper.kt
> +    private val itemListener: ItemListener<Blog>
별도의 변수로 선언하고, 클라이언트에게 setItemListener 함수를 노출시켜서 listener를 등록하게끔 유도하는걸 말씀하시는건가요?

2019-12-23 04:50 UTC, wooooooak commented on wooooooak/StudyApp/app/src/main/java/wooooooak/com/studyapp/ui/blog/BlogFragment.kt
> +                presenter.fetchMoreItems(list, index)
아 그렇군요. 이부분은 딱히 요구사항이 있던게 아니라... 기획적인 부분은 크게 신경쓰지않으려고 했습니다 ㅎㅎ

2019-12-23 08:00 UTC, JayYi commented on wooooooak/StudyApp/app/src/main/java/wooooooak/com/studyapp/ui/blog/BlogListAdatper.kt
> +    private val itemListener: ItemListener<Blog>
제가 설명이 많이 부족했나보네요. 네 말씀하신 부분이 맞아요. 전체적으로 코드를 보면 listener가 필수 항목이라서 생성자로 전달하는 것 같은데, 사실 해당 방법이 맞는지가 의문이 들어서요. 사실 개인적인 스타일 일수도 있구요. 동작상 에러가 없는 부분이니 우선 이 부분은 석준님께 따로 한번 의견을 구해보는 것도 방법인 것 같네요.

2019-12-23 08:01 UTC, JayYi approved these changes
고생하셨습니다.

2019-12-23 12:18 UTC, wooooooak commented on wooooooak/StudyApp/app/src/main/java/wooooooak/com/studyapp/ui/blog/BlogListAdatper.kt
> +    private val itemListener: ItemListener<Blog>
생성자로 넘기는건 google blueprint 보고 참고한거긴 한데요, 어차피 setItemListener를 강제할거라면 따로 함수를 만들어서 제공하는 것 보다 생성자로 받는게 더 강제성이 있어서 요렇게 했습니다..!
보통 함수로 받는 코드가 많이 보이는것 같긴 한데, 그 방법이 더 좋은 이유가 있다면 알려주시면 감사하겠습니다 ㅎㅎ

2019-12-24 08:12 UTC, sjjeong requested changes
Android Studio 3.5.1에서 빌드에러가 발생해요
compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
}
추가해주세요

2019-12-24 08:12 UTC, sjjeong commented on wooooooak/StudyApp/app/src/main/java/wooooooak/com/studyapp/ui/MainViewPagerAdapter.kt
> +    override fun createFragment(position: Int) = fragmentList[position] as Fragment
불필요한 type casting인 것 같은데 추가하신 이유가 있나요?

2019-12-24 08:12 UTC, sjjeong commented on wooooooak/StudyApp/app/src/main/java/wooooooak/com/studyapp/ui/base/ItemContract.kt
> +    interface View<T> : ItemView<T>
ItemView와 ItemPresenter를 따로 만든 이유가 있을까요?
제가 보기엔 interface를 상속하지 않아도 될 것 같습니다.

2019-12-24 11:28 UTC, wooooooak commented on wooooooak/StudyApp/app/src/main/java/wooooooak/com/studyapp/ui/MainViewPagerAdapter.kt
> +    override fun createFragment(position: Int) = fragmentList[position] as Fragment
개발하면서 이것 저것 코드 수정해보느라 넣었는데 깜빡하고 그대로 뒀나보네요..
제거 했습니다!

23d77af14c7376485eff355e050e5e7afce03bae

2019-12-24 11:28 UTC, wooooooak commented on wooooooak/StudyApp/app/src/main/java/wooooooak/com/studyapp/ui/base/ItemContract.kt
> +    interface View<T> : ItemView<T>
요것도 리팩토링 하면서 지웠어야 했는데 나둬버렸네요...ㅎㅎ
수정했습니다 감사합니다!

56db3951a52aa46e08671d0c12e2579bc932d420

2019-12-25 01:53 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-12-25 04:16 UTC, merged