HW-3 MVP
sjjeong/GoogryAndroidArchitecutreStudy pull request #362
Opened 2019-12-22 09:55 UTC by dksush

2019-12-24 00:08 UTC, chanhoparkcj commented
build 자체가 안됩니다. 확인 부탁드립니다

2019-12-24 00:10 UTC, chanhoparkcj commented
이미지, 블로그, 지식인, 영화 별 fragment를 생성했는데 viewpager로 생성하면  하나의 fragment로 공통으로  쓸수 있습니다.

2019-12-24 00:27 UTC, dksush commented
> 이미지, 블로그, 지식인, 영화 별 fragment를 생성했는데 viewpager로 생성하면 하나의 fragment로 공통으로 쓸수 있습니다.

2019-12-24 01:07 UTC, chanhoparkcj commented
> * build 문제 수정했습니다.
> * 영화, 블로그등 각 프레그먼트를 동일한 ui와 기능인데 합치지 않은 이유는, 패턴 적용을 반복 사용해 익숙질려고 놔두었습니다.

-> slack 으로 올렸습니다 확인해주세요

2019-12-24 01:18 UTC, ghost requested changes

2019-12-24 01:18 UTC, chanhoparkcj commented on dksush/AndroidArchitecture/app/src/main/java/com/example/androidarchitecture/data/repository/NaverRepo.kt
> +object NaverRepo : NaverRepoInterface {
NaverRepo 란 이름이 직관적이지 않습니다. NaverRepoImpl 로 변경해주셨으면 더 좋을것이라 생각합니다

2019-12-24 01:51 UTC, ghost requested changes
패키지 구조가 좀 전체적으로 파악하기 어려운 구조로 되어있습니다. presenter를 위한 패키지 생성해서 presenter 만 모아두고 관리하면 좀더 보기 편할것 같습니다 이 외에도  activity / adapter/util/fragment 등의 패키지를 생성해서 따로 관리하는것도 조심스럽게 제안합니다.

2019-12-24 01:51 UTC, chanhoparkcj commented on dksush/AndroidArchitecture/app/src/main/java/com/example/androidarchitecture/models/KinData.kt
> +package com.example.androidarchitecture.models
kin 부분은 present 적용안해주셨습니다

2019-12-24 01:52 UTC, ghost requested changes
https://thdev.tech/androiddev/2017/02/20/Android-MVP-Package-Structure/ 참고할 mvp 패턴의 패키지  구조입니다

2019-12-24 02:03 UTC, chanhoparkcj commented
StudyFork:class06/dksush 로 merge 요청하셔야 합니다 현재  StudyFork:master 로 머지 요청 되어있습니다

2019-12-24 02:23 UTC, ghost requested changes
전체적으로 코드 정렬이 안되어있습니다.

2019-12-24 04:12 UTC, ghost requested changes

2019-12-24 04:12 UTC, chanhoparkcj commented on dksush/AndroidArchitecture/app/src/main/java/com/example/androidarchitecture/ui/base/NaverContract.kt
> +    interface View<T> : NaverView<T>
NaverView 인터페이스를 또 생성했는지 이해가 안갑니다 
interface view 안에 renderItem / errorToast 를 선언 할수 있습니다.

2019-12-24 04:27 UTC, dksush commented on dksush/AndroidArchitecture/app/src/main/java/com/example/androidarchitecture/data/repository/NaverRepo.kt
> +object NaverRepo : NaverRepoInterface {
수정했습니다.

b3a6361

2019-12-24 04:27 UTC, dksush commented on dksush/AndroidArchitecture/app/src/main/java/com/example/androidarchitecture/models/KinData.kt
> +package com.example.androidarchitecture.models
수정했습니다.

3ab1040

2019-12-24 04:27 UTC, dksush commented on dksush/AndroidArchitecture/app/src/main/java/com/example/androidarchitecture/ui/base/NaverContract.kt
> +    interface View<T> : NaverView<T>
앗 그러게요.. 수정했습니다

de4699c

2019-12-24 04:46 UTC, dksush commented
> 패키지 구조가 좀 전체적으로 파악하기 어려운 구조로 되어있습니다. presenter를 위한 패키지 생성해서 presenter 만 모아두고 관리하면 좀더 보기 편할것 같습니다 이 외에도 activity / adapter/util/fragment 등의 패키지를 생성해서 따로 관리하는것도 조심스럽게 제안합

->패키지 구조를 컴포넌트 끼리 묶어두면 작업시 여러 폴더를 열고 이동해야 하고, view 단위로 파악하기 힘든 불편함이 있어 이런 패키지 구조로 구성하였습니다. 나중에 특정 view를 수정, 추가, 삭제 시 컴포넌트로 묶여 있으면, 폴더별로 하나하나 찾아서 수정해야 하는 불편함도 있다 생각합니다. 

첨부해주신 링크도 adapter를 제외하면 저와 동일한 패키지 구조를 추천하고 있는 링크입니다.

2019-12-25 14:31 UTC, JayYi commented on dksush/AndroidArchitecture/app/src/main/java/com/example/androidarchitecture/ui/MainActivity.kt
> +                    0 -> tab.text = "Movie"
`
tab.text = when(position) {
     ...
}
`
변경하면 좋을 것 같아요.

2019-12-26 01:20 UTC, dksush commented on dksush/AndroidArchitecture/app/src/main/java/com/example/androidarchitecture/ui/MainActivity.kt
> +                    0 -> tab.text = "Movie"
이렇게도 쓸 수 있군요.
감사합니다.

f3b0351

2019-12-26 01:49 UTC, ghost approved these changes

2019-12-26 01:49 UTC, ghost approved these changes

2019-12-26 16:12 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-12-27 00:12 UTC, merged