HW-3 MVP pattern 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #365
Opened 2019-12-22 13:19 UTC by JayYi

기존에 작업한 코드를 MVP 패턴으로 수정

2019-12-23 12:13 UTC, gitpushyj requested changes
리뷰 완료했습니다~!

2019-12-23 12:13 UTC, wooooooak commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/ui/BaseContract.kt
> +
여기서 T는 항상 BaseContract.Presenter이기 때문에 
```kotlin
interface View<H> {
    var presenter: Presenter
   ...
}
```
이렇게 해도 되지않을까요? 구현해 놓으신 여러 Presenter 구현체들이 있지만 클라이언트 입장에선 모두 BaseContract.Presenter 타입이라서 결국 T는 항상 BaseContract.Presenter 인것 같아요!

2019-12-23 12:13 UTC, wooooooak commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/ui/blog/BlogFragment.kt
> +    override lateinit var presenter: BlogContract.Presenter
위 댓글과 동일한 맥락인데요, 모든 Presenter들이 동일한 interface를 가지고 있으므로 더 큰 상위 개념인 BaseContract.Presenter 타입으로 선언하는게 어떨까요?

현재 코드로 보기에는 BlogPresenter, KinPresenter, ImagePresenter, MoviePresenter 모두 BasePresenter와 완전히 동일한 인터페이스를 가지고 있기때문에  각각의 인터페이스를 파일을 중복해서 만들이유가 없어 보여요.

2019-12-23 12:13 UTC, wooooooak commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/ui/blog/BlogPresenter.kt
> +) : BasePresenter(view, repository), BlogContract.Presenter {
BasePresenter 내부적으로 BaseContract.Presenter를 구현하도록 강제하고 있고, BlogContract.Presenter 역시 BaseContract.Presenter를 구현하도록 강제하고 있기 때문에 인터페이스 선언이 중복되는 형태인것 같아요.

BlogContract.Presenter 부분을 지워도 해당 파일에는 이상이 없는데, 이건 클라이언트 입장에서 BasePresenter의 인터페이스로 충분하지 BlogContract.Presenter는 불필요하다는 의미인것 같습니다! (이것도 위의 댓글들과 동일한 맥락이네요ㅠ)

2019-12-23 12:13 UTC, wooooooak commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/ui/image/ImageFragment.kt
> +    override lateinit var presenter: ImageContract.Presenter
lateinit var 로 선언하시는것 보다. by lazy를 사용하는게 어떨까요?
BaseContract.View의 presenter 프로퍼티는 val로 선언하시고
```kotlin
override val presenter: BaseContract.Presenter by lazy {
    MoviePresenter(this, naverSearchRepository)
}
```
이렇게 사용하는 게 더 안전하고 깔끔할 것 같아요 ㅎㅎ

2019-12-23 12:13 UTC, wooooooak commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/ui/kin/KinFragment.kt
> +        presenter = KinPresenter(this, naverSearchRepository)
naverSearchRepository는 어떤 상태를 가지고 있지 않는 객체이기 때문에, 네개의 프래그먼트에서 각각 새로운 객체를 생성하기 보다는 싱글톤 객체로 만들어서 사용하는게 좋을 것 같습니다.

2019-12-23 13:36 UTC, JayYi commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/ui/BaseContract.kt
> +
지금 구조에서는 BaseCotnract에 있는 함수만 사용하게 되어 Presenter만 선언해도 되는 구조입니다. 하지만 각 화면에서 커스텀한 함수가 추가 된다고 하면 BaseContract.Presenter를 사용하는 것이 아니라 BaseContract.Presenter를 상속한 각각의 Presenster내에서 별도의 함수를 사용할 수 있기 때문에 T 제너릭 타입으로 선언하였습니다.

2019-12-23 13:43 UTC, JayYi commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/ui/blog/BlogFragment.kt
> +    override lateinit var presenter: BlogContract.Presenter
동일하게 동일한 콜백함수를 가지고 있어서 BaseContract.Presenter 사용하는 것이 맞다고 생각합니다. 하지만, 추후 각 화면의 별도의 함수를 가질 수 있다고 생각합니다. Movie, Image, Kin, Blog 들이 독립된 view라고 생각하면 현재 구조와 별개로 별도의 contract를 가지고 있는게 맞다고 생각드네요.

2019-12-23 13:43 UTC, JayYi commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/ui/blog/BlogPresenter.kt
> +) : BasePresenter(view, repository), BlogContract.Presenter {
위에 제가 남긴 댓글과 같은 생각입니다.

2019-12-23 13:45 UTC, JayYi commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/ui/image/ImageFragment.kt
> +    override lateinit var presenter: ImageContract.Presenter
val 선언이 안됩니다. 그리고 안전하다는 부분에서는 좀 이해가 안되요 ㅠ
lateinit은 위험하니 사용하지 말고 다른것을 사용하는게 좋다라는 것으로 이해되서요.

2019-12-23 13:46 UTC, JayYi commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/ui/kin/KinFragment.kt
> +        presenter = KinPresenter(this, naverSearchRepository)
이부분은 지난 스터디 시간에 동일한 질문을 석준님께 하였는데, 결국은 코드를 testable하게 하기 위해서 별도로 의존성을 주입한 것입니다. 말씀하신대로 object로 선언하게 되면 추후에 테스트 코드 작성할 때 mock이 안됩니다.

2019-12-23 14:18 UTC, BeokBeok commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/ui/image/ImageFragment.kt
> +    override lateinit var presenter: ImageContract.Presenter
var 은 값의 변경이 가능하지만, val 은 값의 변경이 불가합니다.
해서, 가변성의 관점으로 보았을 때 var 보다는 val 을 사용하시는 것이 더 좋은 것 같습니다.

하기 링크를 참고하시면 좋을 것 같습니다.
[Item1. 가변성을 제한하라](https://www.notion.so/beokbeok/Item-1-16bc67e579d54b20abe10f4cb9845002)

2019-12-23 14:51 UTC, JayYi commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/ui/image/ImageFragment.kt
> +    override lateinit var presenter: ImageContract.Presenter
@wooooooak 
제가 리뷰 내용을 착각했네요...(아시다시피 제가 난독증이 좀 있어서....죄송합니다ㅠ) BaseContract.View 내 presenter가 var 선언해 놓구선...안된다고 하는 이런 멍청한 짓을 했네요.
@BeokBeok 
코멘트 남겨주셔서 감사합니다. 저의 착각으로 인하여 위의 댓글을 잘 못 남겼네요. 가변성을 제한하는 내용 공유해주셔서 감사합니다.
코멘트 남겨 주신 점 다시 한번 감사 드립니다.

수정했습니다.
c6e320b6ad9f23ada73c761d64b52526333d0103

2019-12-24 00:36 UTC, wooooooak commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/ui/kin/KinFragment.kt
> +        presenter = KinPresenter(this, naverSearchRepository)
제가 테스트 코드에 대해서는 잘 몰라서 그러는데용, 지금 naverSearchRepository를 각 화면마다 만들고 나서 이후에 주입하는 것 처럼 싱글톤 객체를 하나를 각 화면마다 주입하면 안되는건가요?

어떤 부분에서 mock이 안되는지와, 싱글톤으로 인해 testable한 코드가 방해된다면 프로젝트 내에서 싱글톤은 피해야 하는건지 궁금합니다 ㅎㅎ

2019-12-24 01:33 UTC, wooooooak commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/ui/blog/BlogPresenter.kt
> +) : BasePresenter(view, repository), BlogContract.Presenter {
음.... 문맥 적으로 보더라도 BasePresenter는 말 그대로 기반이 되는 Presenter이기 때문에 BlogContract.Presenter가 BasePresetner를 구현하는 형태가 되야 하지, BasePresenter 와 BlogContract.Presenter가 동일한 레벨에서 선언되어있는게 어색해 보여서요..!

default 구현이 필요하여 BasePresenter를 만든거라면 BaseContract.Presenter가 view인터페이스를 가지고 있고(BaseContract.VIew가 presenter를 가지고 있는것 처럼), 거기서 구현하면 어떨까 싶었습니다 ㅎㅎ

2019-12-24 01:36 UTC, JayYi commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/ui/kin/KinFragment.kt
> +        presenter = KinPresenter(this, naverSearchRepository)
저도 자세한 점은 모르고 제가 아는(?) 공부한 정도로 말씀드리자면,

Android unit test를 하기 위해선 Mock up이 필요합니다. Mock 은 클래스 단위의 테스트인데 static method 혹은 singleton pattern으로 이루어진 경우 mock up이 되지 않는다고 합니다. Unittest에 사용되는 Mockito 에서 두 패턴을 가진 객체에 대해서 테스트가 힘든것을 알고 있어요. Mock Object는 빌드시에 테스트 생성에 필요한 데이터만 동적으로 생성을 하게 되는데 static 혹은 singelton patten의 객체는 메모리에 이미 생성되어서 테스트에 필요한 데이터로 재정의 하기 힘들어서 mock 안된다고 하네요
(참고: 
1. https://stackoverflow.com/questions/4482315/why-doesnt-mockito-mock-static-methods
2. https://gamjatwigim.tistory.com/95) 
찾아보니 Mockito도 안드로이드 파이부터 static 메소드를 지원한다고 합니다. 아니면 PowerMock을 사용해도 된다고 하네요.

싱글톤이 테스트에 제한된다고 해서 싱글톤을 안하는 건 아닌것 같구요. 단지 제가 해당 부분에 대해서 싱글톤으로 할지 안할지 결정하는 과정에서 기존에 가졌던 궁금중과 함께 석준님이 말씀해주신 테스트 하는 부분에 대해 말씀해주신 내용을 조합해서 결정한 코드입니다.

2019-12-24 02:16 UTC, JayYi commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/ui/blog/BlogPresenter.kt
> +) : BasePresenter(view, repository), BlogContract.Presenter {
BasePresenter는 모든  presenter가 공통적으로 사용하는 함수(코드상에서는 handleError())를 상속해서 사용할 수 있도록 의도하였구요. BlogContract.Presetner의 경우 Movie, Blog, Image, Kin의 경우 각각 별도의 화면이다고 생각하고 각각 view, presneter를 생성 각각의 별도의 interface를 선언하였습니다. 현재 코드 상으로는 모든 4개의 뷰가 동일한 함수를 사용하고 있어서 Base 기반으로 사용하는 것이 맞을 수도 있지만, 다른 뷰와의 의존성도 끊어야 된다고 생각합니다.

2019-12-24 02:22 UTC, wooooooak commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/ui/kin/KinFragment.kt
> +        presenter = KinPresenter(this, naverSearchRepository)
와 감사합니다 ㅎㅎ 테스트 코드 관련해서 공부해야지 공부해야지 하는데 손이 자꾸 안가네요ㅠㅠ
링크보고 한 번 공부해보겠습니다~!

2019-12-24 02:24 UTC, gitpushyj reviewed
수고 하셨습니다~

2019-12-24 02:25 UTC, gitpushyj approved these changes

2019-12-24 09:49 UTC, sjjeong requested changes

2019-12-24 09:49 UTC, sjjeong commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/ui/BaseFragment.kt
> +    fun showErrorMessage(message: String) {
BaseFragment가 BaseContract.View를 implements해고 override를 추가해주세요

2019-12-24 09:49 UTC, sjjeong commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/ui/BaseContract.kt
> +interface BaseContract {
사실 Base개념이라면 어떤 화면이든 관련없이 다 사용할 수 있도록 만드는게 일반적이라고 생각합니다.
그래서 updateResult라던지 search와 같은 함수는 BaseContract가 아닌 BaseContract를 상속한 BaseSearchContract같은 것을 만들고 거기에 넣어야 한다고 생각합니다.
하지만 과제 프로젝트에서는 별도 화면이 없어서 의견만 남겨드립니다.
이 부분은 따로 반영하지 않으셔도 됩니다.

2019-12-24 09:49 UTC, sjjeong commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/ui/blog/BlogPresenter.kt
> +) : BasePresenter(view, repository), BlogContract.Presenter {
@wooooooak 
이 형태가 일반적으로 맞는 형태입니다.
BasePresenter가 BaseContract.Presenter를 implements하고 있고
BlogPresenter가 BasePresenter를 상속하고있고
BlogContract.Presenter가 BaseContract.Presenter를 상속하고 있는 형태라면
BlogPresenter가 BlogContract.Presenter를 상속받아야 하는 형태인거죠
현재 이 상태에서 BlogContract.Presenter를 지워도 에러는 나지 않겠지만 추후 BlogContract.View에서 BlogContract.Presenter의 함수를 호출해야 할 일이 생기면 문제가 발생하겠지요

2019-12-24 09:55 UTC, minjae2 commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/ui/BaseContract.kt
> +interface BaseContract {
해당부분은 저도 고민을 했는데 말씀해주신 대로 프록젝트가 별도의 화면이 없다보니....그래도 명확하게 해둔게 좋은 것 같습니다.

2019-12-24 12:07 UTC, wooooooak commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/ui/blog/BlogPresenter.kt
> +) : BasePresenter(view, repository), BlogContract.Presenter {
@sjjeong 
BlogContract.View를 지우면 추후에 문제가 생기긴 하겠네요!ㅎㅎ

그런데 제가 이해를 잘못한건지..궁금한게 있는데용,
일반적으로 클래스가
(abstract or interface) BaseViewModel, 
(abstract or interface) SearchViewModel,
(class) BlogSearchViewModel 
이렇게 세 개가 있을 경우 BaseViewModel은 모든 뷰 모델의 기반이 되는 클래스라 SearchViewModel역시 이를 상속 받을 것이고, 따라서 아래 코드와 같이 사용될 것을 기대하는데요.
```kotlin
class BlogSearchViewModel: SearchViewModel {
 ...
}
```
제가 댓글을 단 코드는 아래의 형태와 같은게 아닌가 하는 생각이 들었습니다.
```kotlin
class BlogSearchViewModel: BaseViewModel, SearchViewModel {
 ...
}
```

Base와 Base를 상속받은 클래스 or 인터페이스가 동일 레벨에 있는 형태가....제가 익숙하지 않은건지ㅠㅠ
원래 이런식으로 많이 사용하는건가요?ㅎㅎ

2019-12-24 14:54 UTC, JayYi commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/ui/BaseContract.kt
> +interface BaseContract {
아 핸드폰이 회사 계정으로 로그인 되어있는 줄 몰랐네요 ㅠ

수정했습니다.
54d146b4803b60126399e9a8ab3258986e59a03d
c6bd35525c7ecb158882af7aa89ef7a7290e0d1a

2019-12-24 14:55 UTC, JayYi commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/ui/BaseFragment.kt
> +    fun showErrorMessage(message: String) {
수정했습니다.
a86f5b1ceefea5a67442542019266bf7a5e703ad

2019-12-25 01:55 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-12-25 05:18 UTC, merged