HW-1 영화정보 검색 어플리케이션
sjjeong/GoogryAndroidArchitecutreStudy pull request #366
Opened 2019-12-23 00:13 UTC by AhnHyeonho

1. MainActivity에서 검색어를 입력하고, 검색결과를 RecyclerView에 표시하였습니다.
2. RecyclerAdapter는 따로 정의하였고, 요청에따른 결과값 중 검색어는 HTML태그로 감싸져 있어 이 태그를 제거하는 stripHtml() 메소드를 정의하였습니다.
3. 결과값을 받아오는 Movie data class와 Movies data class를 Movies.kt으로 따로 정의하였습니다.

2019-12-26 05:08 UTC, seunghee63 commented on AhnHyeonho/FirstProject/app/src/main/res/layout/activity_main.xml
> +            android:id="@+id/recyclerView_movies"
camelCase와 snake_case가 혼용되어 있습니다. xml은 snake로 네이밍 하는 것이 컨벤션이므로, 수정 할 필요가 있어보입니다!

2019-12-26 05:11 UTC, seunghee63 commented on AhnHyeonho/FirstProject/app/src/main/java/com/hansung/firstproject/MainActivity.kt
> +                println("Failed to execute request")
통신을 실패했을 경우, 실패했다는 로그만 띄우는 것 보다 에러를 출력하여 에러를 확인 할 수 있도록 하는 방법이 더 좋을 것 같습니다!

2019-12-26 05:16 UTC, seunghee63 commented on AhnHyeonho/FirstProject/app/src/main/res/layout/movie_item.xml
> +        android:id="@+id/movie_image"
id 네이밍이 직관적이지 않은 것 같습니다! 지금은 기능이 적으니 쉽게 알아볼 수 있으나, 나중에 큰 프로젝트에서는 이름이 충돌하거나.. 하는 문제가 발생할 수도 있을 것 같아요!
저의 경우에는 '아이템뷰_액티비티or프래그먼트_기능' 과 같이 네이밍을 하는데, 현호님도 조금 더 자세하게 네이밍을 하면 좋을 것 같습니다..!

2019-12-26 05:17 UTC, seunghee63 commented on AhnHyeonho/FirstProject/app/src/main/java/com/hansung/firstproject/MainActivity.kt
> +    private val clientSecret = "SVd8sHWiui" //naver 검색API 사용을 위한 Client Secret
중요한 개인정보이니, 직접 코드에 적는 것 보다는 다른 파일에 넣고 이그노어 처리하는 것이 좋을 것 같습니다!

2019-12-26 05:53 UTC, seunghee63 commented on AhnHyeonho/FirstProject/app/src/main/java/com/hansung/firstproject/Movies.kt
> +    val userRating: String
널 값 처리를 해 주는것이 좋을 것 같습니다! *정확하게는 잘 모르겠어요...ㅠ

2019-12-26 17:15 UTC, AhnHyeonho commented on AhnHyeonho/FirstProject/app/src/main/res/layout/activity_main.xml
> +            android:id="@+id/recyclerView_movies"
안드로이드 코딩이 미숙하다보니 네이밍을 일관성있게 하지 못했네요. 지적 감사합니다. 앞으로도 주의하면서 코딩하겠습니다. :)
994b756

2019-12-26 17:19 UTC, AhnHyeonho commented on AhnHyeonho/FirstProject/app/src/main/java/com/hansung/firstproject/MainActivity.kt
> +                println("Failed to execute request")
개발자만 알아볼 수 있는 로그만 생각하고 사용자의 입장을 고려하는 걸 깜빡했네요.
사용자도 통신 실패를 알 수 있게 끔 Toast메세지를 추가하였습니다.

1f60727

2019-12-26 17:19 UTC, AhnHyeonho commented on AhnHyeonho/FirstProject/app/src/main/res/layout/movie_item.xml
> +        android:id="@+id/movie_image"
첨언해주신 방식을 참고해서 수정해보았습니다.

041854c

2019-12-26 17:21 UTC, AhnHyeonho commented on AhnHyeonho/FirstProject/app/src/main/java/com/hansung/firstproject/MainActivity.kt
> +    private val clientSecret = "SVd8sHWiui" //naver 검색API 사용을 위한 Client Secret
특정파일로 따로 관리하도록 수정하였습니다.
또, gitignore에 해당 파일을 추가하여 push 되는 것을 막았습니다.

08fcd65

2019-12-26 17:25 UTC, AhnHyeonho commented on AhnHyeonho/FirstProject/app/src/main/java/com/hansung/firstproject/Movies.kt
> +    val userRating: String
검색api로부터 읽어온 자료를 저장하는 클래스로서 널 값에 대한 처리는 OkHttp쪽 통신 오류처리에서 처리가 되므로 해당 파일에서도 널 값에 대한 정의가 필요한지는 느끼지 못하였습니다. 혹시 어떤 측면에서 널 값을 처리해 주는 게 좋은지 설명해주실수있을까요 ?.?

2019-12-26 17:48 UTC, AhnHyeonho commented on AhnHyeonho/FirstProject/app/src/main/java/com/hansung/firstproject/Movies.kt
> +    val userRating: String
널러블 변수로 수정하였습니다!

d80707e

2019-12-26 22:56 UTC, seunghee63 commented on AhnHyeonho/FirstProject/app/src/main/java/com/hansung/firstproject/MainActivity.kt
> +                println("Failed to execute request")
제가 말했던 통신 실패 에러를 띄워야 할 것 같다는말은! onFailure 함수의 두번째 인자인 'e'를 Log로 찍어보고 어떤 에러가 나오는지 확인을 할 필요가 있을 것 같다는 말이었어요!

2019-12-27 00:03 UTC, seunghee63 commented on AhnHyeonho/FirstProject/app/src/main/java/com/hansung/firstproject/MainActivity.kt
> +                println("Failed to execute request")
제가 말한 '에러를 출력한다'는 말은, Toast메세지를 띄워서 사용자가 에러를 확인 할 수 있도록 한다는 말이 아닌, 오버라이드한 함수의 두번째 인자인 'e'를 출력 하여 오류의 원인을 제대로/정확히 확인 해 보는 것이 어떨까- 하고 제안 해 본 것 이었습니다!

2019-12-27 11:24 UTC, AhnHyeonho commented on AhnHyeonho/FirstProject/app/src/main/java/com/hansung/firstproject/MainActivity.kt
> +                println("Failed to execute request")
확인하고 수정하였습니다.

9e87879

2019-12-27 12:35 UTC, seunghee63 approved these changes

2019-12-27 14:35 UTC, sjjeong requested changes

2019-12-27 14:35 UTC, sjjeong commented on AhnHyeonho/FirstProject/app/src/main/java/com/hansung/firstproject/MainActivity.kt
> +                )
RecyclerView를 초기화 하는 작업은 setOnClickListener 안에 있지 않아도 됩니다.
안에 있으면 클릭이 될때 마다 초기화를 하기 때문에 불필요한 작업입니다.

2019-12-27 14:35 UTC, sjjeong commented on AhnHyeonho/FirstProject/app/src/main/java/com/hansung/firstproject/MainActivity.kt
> +    private fun fetchJson(vararg p0: String) {
p0보다 의미있는 파라미터명을 써주세요.
vararg는 필요 없습니다.

2019-12-27 14:35 UTC, sjjeong commented on AhnHyeonho/FirstProject/app/src/main/java/com/hansung/firstproject/MainActivity.kt
> +        val client = OkHttpClient()
Retrofit을 사용하면 조금더 쉽게 사용 할 수 있어요.
Retrofit 공부해서 반영해보세요

2019-12-27 14:35 UTC, sjjeong commented on AhnHyeonho/FirstProject/app/src/main/java/com/hansung/firstproject/RecyclerViewAdapter.kt
> +class RecyclerViewAdapter(private val movies: Movies) :
Movies를 넘기지 말고 실제 data list만 넘기는 방식으로 해보세요

2019-12-27 14:35 UTC, sjjeong commented on AhnHyeonho/FirstProject/app/src/main/res/layout/activity_main.xml
> +                android:layout_width="wrap_content"
weight 값을 줄 땐 LinearLayout의 orientation 방향의 크기를 0dp로 주면 됩니다.

2019-12-27 20:07 UTC, AhnHyeonho commented on AhnHyeonho/FirstProject/app/src/main/res/layout/activity_main.xml
> +                android:layout_width="wrap_content"
수정하였습니다.

3a9b537

2019-12-27 20:12 UTC, AhnHyeonho commented on AhnHyeonho/FirstProject/app/src/main/java/com/hansung/firstproject/MainActivity.kt
> +        val client = OkHttpClient()
Retrofit을 적용하여 코드 전반적인 내용이 수정되었습니다. 커밋내용 확인 부탁드립니다.


02a4a83 - retrofit을 위한 dependency추가 
c6c4ff9 - retrofit 적용을 위한 인터페이스 및 구현체 생성 
a2c4e30 - retrofit을 이용한 검색 메소드 작성
0391e90 - MainActivity에서 기존 Okhttp3를 통한 방식을 retrofit으로 변환 및 일부 메소드 정리

2019-12-27 20:13 UTC, AhnHyeonho commented on AhnHyeonho/FirstProject/app/src/main/java/com/hansung/firstproject/RecyclerViewAdapter.kt
> +class RecyclerViewAdapter(private val movies: Movies) :
Adapter 전체적으로 수정해보았습니다. Adapter 클래스와 Holder 클래스를 분리하였고, 말씀하신대로 Adapter에는 Movies 전체가아닌 실제 검색결과를 통해 얻은 data list를 넘기도록 수정했습니다. 

e0993ec

2019-12-27 20:14 UTC, AhnHyeonho commented on AhnHyeonho/FirstProject/app/src/main/java/com/hansung/firstproject/MainActivity.kt
> +    private fun fetchJson(vararg p0: String) {
전체적인 Retrofit 적용으로 인하여 해당 메소드는 제거하였습니다.

2019-12-27 20:17 UTC, AhnHyeonho commented on AhnHyeonho/FirstProject/app/src/main/java/com/hansung/firstproject/MainActivity.kt
> +                )
recyclerView에대한 초기화 작업은 따로 메소드로 작성하여 onCreate메소드에서 호출해주었고 
(line: 36)

검색버튼의 setOnClickListner에는 올바르게 값이 입력됬을 경우에 Retrofit을 이용한 검색결과가 호출되고, 이를 통해 얻은 결과값을 기반으로 recyclerView의 view들을 생성하게 수정하였습니다.
(line: 46)

0391e90

2019-12-28 04:53 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-12-28 04:54 UTC, merged