HW-1 영화 검색 어플리케이션
sjjeong/GoogryAndroidArchitecutreStudy pull request #368
Opened 2019-12-23 09:05 UTC by ghkdua1829

2019-12-24 07:29 UTC, handnew04 requested changes

2019-12-24 07:29 UTC, handnew04 commented on ghkdua1829/app/src/main/java/com/example/architecture_project/data/Movie.kt
> +    @SerializedName("director")
변수 명과 SerializedName 이 같은데 왜 사용 하는지 궁금해요

2019-12-24 07:29 UTC, handnew04 commented on ghkdua1829/app/src/main/java/com/example/architecture_project/feature/search/MainActivity.kt
> +                        Log.e("A ", response.toString())
A 라고 하면 어디의 로그인지 알아보기 힘들 것 같아요.

2019-12-24 07:29 UTC, handnew04 commented on ghkdua1829/app/src/main/res/layout/item_movie.xml
>          android:text="배우"
위의 영화 제목과 배우 부분에 string 값을 사용하는게 나중에 수정할 일이 생기면 더 편할 것 같아요.

2019-12-24 11:14 UTC, ghkdua1829 commented on ghkdua1829/app/src/main/java/com/example/architecture_project/data/Movie.kt
> +    @SerializedName("director")
제가 습관이라서 저렇게 계속 썻는데 불필요하니 빼도록 하겠습니다!eba475cfe787c649469f011c20b3ddb10b1d95d6

2019-12-24 11:15 UTC, ghkdua1829 commented on ghkdua1829/app/src/main/java/com/example/architecture_project/feature/search/MainActivity.kt
> +                        Log.e("A ", response.toString())
2c49218228348e66d54fe2b59ee3d9cfa9dc932f

2019-12-24 11:15 UTC, ghkdua1829 commented on ghkdua1829/app/src/main/res/layout/item_movie.xml
>          android:text="배우"
41f5b13a31f58e1fc419477ea1d5e199d200fdbb

2019-12-24 14:31 UTC, handnew04 approved these changes

2019-12-25 02:28 UTC, sjjeong requested changes

2019-12-25 02:28 UTC, sjjeong commented on ghkdua1829/app/src/main/java/com/example/architecture_project/feature/movie/MovieAdapter.kt
> +class MovieAdapter(private val context: Context) : RecyclerView.Adapter<MovieViewHolder>() {
RecyclerView.Adapter를 생성할 때 context를 전달할 필요가 없습니다.
onCreateViewHolder에서는 parent로 넘어오는 ViewGroup에서 가져올 수 있습니다.

2019-12-25 02:28 UTC, sjjeong commented on ghkdua1829/app/src/main/java/com/example/architecture_project/feature/movie/MovieAdapter.kt
> +    var data = listOf<Movie>()
Adapter내부에서 사용하는 것과 외부에서 사용되는 것의 객체를 다르게 해주셔야 합니다.
함수를 만들고 그 안에서 데이터를 collection에 넣어주는 방식으로 변경해주세요

2019-12-25 02:28 UTC, sjjeong commented on ghkdua1829/app/src/main/java/com/example/architecture_project/feature/movie/MovieViewHolder.kt
> +        itemView.setOnClickListener {
bind시점에서 setOnClickListener를 호출 하는 것은 불필요한 로직입니다.
View가 생성되는 시점에 1번만 set해주면 됩니다.

2019-12-25 02:28 UTC, sjjeong commented on ghkdua1829/app/src/main/java/com/example/architecture_project/feature/movie/MovieViewHolder.kt
> +            go_webview.putExtra("url", data.link)
extra로 전달할 때 key는 상수로 선언해서 사용하는게 좋습니다.
WebviewActivity에 상수로 선언해주세요

2019-12-25 02:28 UTC, sjjeong commented on ghkdua1829/app/src/main/java/com/example/architecture_project/feature/movie/MovieViewHolder.kt
> +            val go_webview = Intent(itemView.context, WebviewActivity::class.java)
변수명은 카멜케이스로 해주세요

2019-12-25 02:28 UTC, sjjeong commented on ghkdua1829/app/src/main/java/com/example/architecture_project/feature/search/MainActivity.kt
> +    fun Call_Movie(keyword: String) {
함수는 소문자로 시작해야하고 _를 사용하지 않아야합니다.

2019-12-25 02:28 UTC, sjjeong commented on ghkdua1829/app/src/main/java/com/example/architecture_project/feature/search/MainActivity.kt
> +    private lateinit var MovieRecyclerView: RecyclerView
변수명은 카멜케이스를 따라서 지어주세요

2019-12-25 02:28 UTC, sjjeong commented on ghkdua1829/app/src/main/java/com/example/architecture_project/feature/search/MainActivity.kt
> +        MovieRecyclerView.layoutManager = LinearLayoutManager(this)
layoutManager를 동적으로 변경해주는게 아니라면 xml에서 처리할 수 있습니다.

2019-12-25 02:28 UTC, sjjeong commented on ghkdua1829/app/src/main/java/com/example/architecture_project/feature/search/MainActivity.kt
> +            NaverSevicelmpl.service.getMovie("Ega4tpqIyDDMBsf8nb7O", "GinlKHXc11", keyword)
retrofit interceptor add header 라는 키워드로 구글링해서 변경해보세요

2019-12-25 02:28 UTC, sjjeong commented on ghkdua1829/app/src/main/java/com/example/architecture_project/feature/search/MainActivity.kt
> +        MovieRecyclerView = findViewById(R.id.rv_movie)
RecyclerView를 setup하는 부분은 검색을 할 때마다 매번 할 필요가 없습니다.
onCreate에서 한번만 하게 해주세요

2019-12-25 02:28 UTC, sjjeong commented on ghkdua1829/app/src/main/java/com/example/architecture_project/feature/search/WebviewActivity.kt
> +        webview_settings.setSupportZoom(false)
같은 View를 여러번 사용해야 한다면 with, run과 같은 함수를 사용해 보세요

2019-12-25 02:28 UTC, sjjeong commented on ghkdua1829/app/src/main/res/layout/activity_main.xml
> +        android:layout_width="match_parent"
ConstraintLayout에서는 match_parent를 사용하지 않는 것을 권장합니다.
0dp로 변경후에 양 옆으로 제약조건을 추가해주세요

다른 layout들도 동일하게 변경해주세요

2019-12-25 02:28 UTC, sjjeong commented on ghkdua1829/app/src/main/res/layout/activity_main.xml
> +        app:layout_constraintLeft_toLeftOf="@id/ll_search"
left대신 start를 사용해주시고 parent로 값을 변경해주세요

2019-12-25 02:28 UTC, sjjeong commented on ghkdua1829/app/src/main/res/layout/activity_main.xml
> +        android:layout_height="550dp"
0dp로 하고 bottom을 parent의 bottom으로 잡으면 됩니다.

2019-12-25 07:08 UTC, ghkdua1829 commented on ghkdua1829/app/src/main/java/com/example/architecture_project/feature/movie/MovieAdapter.kt
> +class MovieAdapter(private val context: Context) : RecyclerView.Adapter<MovieViewHolder>() {
ae721ef8015577effc85bb874f69707f16bf41ef

2019-12-25 07:09 UTC, ghkdua1829 commented on ghkdua1829/app/src/main/java/com/example/architecture_project/feature/movie/MovieAdapter.kt
> +    var data = listOf<Movie>()
4abcb7a64f73ef0d78189c90064a13681f15ffe0

2019-12-25 07:09 UTC, ghkdua1829 commented on ghkdua1829/app/src/main/java/com/example/architecture_project/feature/movie/MovieViewHolder.kt
> +            go_webview.putExtra("url", data.link)
bcdcaca989eaf13fdb24cf3b41697f0be12cbe09

2019-12-25 07:09 UTC, ghkdua1829 commented on ghkdua1829/app/src/main/java/com/example/architecture_project/feature/movie/MovieViewHolder.kt
> +            val go_webview = Intent(itemView.context, WebviewActivity::class.java)
96ab40087263d5e641b2005eaa678d20bc2ed80b

2019-12-25 07:09 UTC, ghkdua1829 commented on ghkdua1829/app/src/main/java/com/example/architecture_project/feature/search/MainActivity.kt
> +        MovieRecyclerView = findViewById(R.id.rv_movie)
957d52cec13707e57d14451204565f17153a06ce

2019-12-25 07:09 UTC, ghkdua1829 commented on ghkdua1829/app/src/main/java/com/example/architecture_project/feature/search/WebviewActivity.kt
> +        webview_settings.setSupportZoom(false)
ef6d9b6a963d7dec5967f0337d3963df0a07b70b

2019-12-25 07:09 UTC, ghkdua1829 commented on ghkdua1829/app/src/main/res/layout/activity_main.xml
> +        android:layout_width="match_parent"
77f0ddef822f26dfba861ec5248b27e06edb9f83

2019-12-25 07:09 UTC, ghkdua1829 commented on ghkdua1829/app/src/main/res/layout/activity_main.xml
> +        app:layout_constraintLeft_toLeftOf="@id/ll_search"
77f0ddef822f26dfba861ec5248b27e06edb9f83

2019-12-25 07:09 UTC, ghkdua1829 commented on ghkdua1829/app/src/main/res/layout/activity_main.xml
> +        android:layout_height="550dp"
77f0ddef822f26dfba861ec5248b27e06edb9f83

2019-12-25 08:21 UTC, ghkdua1829 commented on ghkdua1829/app/src/main/java/com/example/architecture_project/feature/movie/MovieViewHolder.kt
> +        itemView.setOnClickListener {
이렇게 수정하긴 했는데 제대로 한건지 잘 모르겠습니다.
6897d2f7b8460bc16d4a4423c6245b8e2404de8e

2019-12-25 08:35 UTC, sjjeong commented on ghkdua1829/app/src/main/java/com/example/architecture_project/feature/movie/MovieAdapter.kt
> +        this.movieData=movieData
이렇게하면 객체가 공유되고 있는 거에요
clear와 addAll함수를 이용해주세요

2019-12-25 08:35 UTC, sjjeong commented on ghkdua1829/app/src/main/java/com/example/architecture_project/feature/movie/MovieViewHolder.kt
> +        itemView.setOnClickListener {
결국 위치만 변경된 것이지 bind시점에 호출되는 것 같습니다.
View가 생성되는 시점을 찾아보세요

2019-12-25 08:36 UTC, sjjeong commented on ghkdua1829/app/src/main/java/com/example/architecture_project/feature/movie/MovieViewHolder.kt
> +            go_webview.putExtra("url", data.link)
get하는 부분말고 put하는 부분도 동일한 상수를 사용하셔야 해요

2019-12-25 08:37 UTC, sjjeong requested changes
![image](https://user-images.githubusercontent.com/4777586/71439496-3d1cb000-273d-11ea-8c0e-c3cb73d49c5a.png)
로 있는 부분 마져 리뷰 반영해주세요

2019-12-26 16:11 UTC, ghkdua1829 commented on ghkdua1829/app/src/main/java/com/example/architecture_project/feature/movie/MovieViewHolder.kt
> +            go_webview.putExtra("url", data.link)
13e23874e497d7efe89d505e51f5ae46ad5bd9a4

2019-12-26 16:12 UTC, ghkdua1829 commented on ghkdua1829/app/src/main/java/com/example/architecture_project/feature/movie/MovieAdapter.kt
> +        this.movieData=movieData
13e23874e497d7efe89d505e51f5ae46ad5bd9a4

2019-12-26 16:12 UTC, ghkdua1829 commented on ghkdua1829/app/src/main/java/com/example/architecture_project/feature/movie/MovieViewHolder.kt
> +        itemView.setOnClickListener {
13e23874e497d7efe89d505e51f5ae46ad5bd9a4

2019-12-26 17:05 UTC, sjjeong requested changes
누락된 4개 리뷰 사항도 반영해주세요

2019-12-26 17:05 UTC, sjjeong commented on ghkdua1829/app/src/main/java/com/example/architecture_project/feature/movie/MovieAdapter.kt
> +            view.findViewById(com.example.architecture_project.R.id.rv_item_iv_movie_image)
com.example.architecture_project.R를 import 해주세요

2019-12-26 17:05 UTC, sjjeong commented on ghkdua1829/app/src/main/java/com/example/architecture_project/feature/movie/MovieAdapter.kt
> +    private var movieData: ArrayList<Movie> = ArrayList()
val로 선언해주세요

2019-12-27 08:46 UTC, ghkdua1829 commented on ghkdua1829/app/src/main/java/com/example/architecture_project/feature/search/MainActivity.kt
> +    fun Call_Movie(keyword: String) {
a91a029d3f978e6eec96a3ea6c161df30224c5ce

2019-12-27 08:46 UTC, ghkdua1829 commented on ghkdua1829/app/src/main/java/com/example/architecture_project/feature/search/MainActivity.kt
> +    private lateinit var MovieRecyclerView: RecyclerView
ea2ef362c97e4796917fdd0b3df2109ffe027d4b

2019-12-27 08:46 UTC, ghkdua1829 commented on ghkdua1829/app/src/main/java/com/example/architecture_project/feature/search/MainActivity.kt
> +        MovieRecyclerView.layoutManager = LinearLayoutManager(this)
4ddf4bceb46d756d9d04e4169d0db5dcc32c6ef4

2019-12-27 08:48 UTC, ghkdua1829 commented on ghkdua1829/app/src/main/java/com/example/architecture_project/feature/movie/MovieAdapter.kt
> +            view.findViewById(com.example.architecture_project.R.id.rv_item_iv_movie_image)
34c778ad9305d330be9612150d989f66eab9cde8

2019-12-27 08:48 UTC, ghkdua1829 commented on ghkdua1829/app/src/main/java/com/example/architecture_project/feature/movie/MovieAdapter.kt
> +    private var movieData: ArrayList<Movie> = ArrayList()
4d40978793521cbea39e219be27cb9da50acf670

2019-12-27 08:50 UTC, ghkdua1829 commented on ghkdua1829/app/src/main/java/com/example/architecture_project/feature/search/MainActivity.kt
> +            NaverSevicelmpl.service.getMovie("Ega4tpqIyDDMBsf8nb7O", "GinlKHXc11", keyword)
4adb027c6958d2b631ee7deec0ec2b5196aba8e0

2019-12-27 14:37 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-12-27 15:14 UTC, merged