HW-1 네이버 검색 API를 활용한 영화정보 검색 어플리케이션 제작
sjjeong/GoogryAndroidArchitecutreStudy pull request #369
Opened 2019-12-23 15:42 UTC by 172900

- EditText를 통해 검색어를 입력받아 검색버튼으로 영화 검색
- 네이버 검색 API를 활용하여 검색어에 해당하는 결과 받아오기
- 검색결과를 RecyclerView에 표시하기
- 각 영화정보에는 아래 정보가 모두 표시 : 썸네일 이미지, 제목, 평점, 연도, 감독, 출연배우
- 목록에서 영화 선택시 해당 영화 정보 link페이지로 이동

2019-12-25 18:47 UTC, swppppp commented
꼼꼼하게 잘 하신것 같아요!!
코루틴은 내용을 잘 몰라서 제가 리뷰해드릴 수 없는 부분인것 같습니다.
로딩바 추가한 부분이나, 검색버튼 누를 시 키보드 숨김같은부분은 저도 적용하면 좋을것 같습니다.

2019-12-25 18:50 UTC, swppppp commented on 172900/GoogleArchitectureStudy/app/src/main/java/com/onit/googlearchitecturestudy/Movie.kt
> +    @SerializedName("link") val link: String
이부분 SerializedName을 붙인 이유가 따로 있나요?
그냥 궁금해서요!

2019-12-25 18:52 UTC, swppppp approved these changes

2019-12-26 02:07 UTC, 172900 commented on 172900/GoogleArchitectureStudy/app/src/main/java/com/onit/googlearchitecturestudy/Movie.kt
> +    @SerializedName("link") val link: String
responseBody로 넘어오는 필드 이름이 마음에 안 드는 경우가 많아서(스네이크 케이스로 넘어온다던가 너무 축약형을 많이 써서 단어의 뜻을 잘모르겠다던가)해서 쓰는 경우가 있어요.

2019-12-26 16:46 UTC, sjjeong requested changes

2019-12-26 16:46 UTC, sjjeong commented on 172900/GoogleArchitectureStudy/app/src/main/java/com/onit/googlearchitecturestudy/MainActivity.kt
> +const val MOVIE_URL = "movieURL"
MovieInformationActivity에 전달하기 위한 목적인 상수 임으로 MovieInformationActivity안에 companion object안에 상수로 선언해주세요

2019-12-26 16:46 UTC, sjjeong commented on 172900/GoogleArchitectureStudy/app/src/main/java/com/onit/googlearchitecturestudy/MainActivity.kt
> +            layoutManager = LinearLayoutManager(context)
xml에서 처리해줄수 있습니다.

2019-12-26 16:46 UTC, sjjeong commented on 172900/GoogleArchitectureStudy/app/build.gradle
> +    implementation 'com.jakewharton.retrofit:retrofit2-kotlin-coroutines-adapter:0.9.2'
해당 Adapter는 Deprecated되었습니다.

2019-12-26 16:46 UTC, sjjeong commented on 172900/GoogleArchitectureStudy/app/src/main/java/com/onit/googlearchitecturestudy/NaverAPIService.kt
> +    fun getMovieList(
Deferred를 리턴하지 않고 이 함수를 suspend 함수로 만들면 됩니다.

2019-12-26 16:46 UTC, sjjeong commented on 172900/GoogleArchitectureStudy/app/src/main/java/com/onit/googlearchitecturestudy/NaverAPIService.kt
> +        @Header("X-Naver-Client-Id") Client_Id: String,
retrofit interceptor를 참고해서 변경해보세요

2019-12-26 16:46 UTC, sjjeong commented on 172900/GoogleArchitectureStudy/app/src/main/java/com/onit/googlearchitecturestudy/ResultMovieListRecyclerAdapter.kt
> +    private var list: ArrayList<Movie>,
생성자로 받지 마시고 내부에 선언해주시고 val로 변경해주세요

2019-12-26 16:46 UTC, sjjeong commented on 172900/GoogleArchitectureStudy/app/src/main/java/com/onit/googlearchitecturestudy/ResultMovieListRecyclerAdapter.kt
> +            movieViewHolder.setOnClickListener {
moviewViewHolder대신 itemView를 사용하면 됩니다.

2019-12-26 16:46 UTC, sjjeong commented on 172900/GoogleArchitectureStudy/app/src/main/java/com/onit/googlearchitecturestudy/ResultMovieListRecyclerAdapter.kt
> +) : RecyclerView.Adapter<RecyclerView.ViewHolder>() {
generic을 MovieViewHolder로 해주면 onBindViewHolder에서 type casting이 필요 없습니다.

2019-12-26 16:46 UTC, sjjeong commented on 172900/GoogleArchitectureStudy/app/src/main/java/com/onit/googlearchitecturestudy/ResultMovieListRecyclerAdapter.kt
> +        with(holder as MovieViewHolder) {
해당 내부 내용들은 MovieViewHolder안에 bind함수를 만들어서 처리해주세요

2019-12-26 16:46 UTC, sjjeong commented on 172900/GoogleArchitectureStudy/app/src/main/java/com/onit/googlearchitecturestudy/MainActivity.kt
> +        return Retrofit.Builder().apply {
Retrofit.Builder().apply {
            baseUrl(Config.NAVER_API_BASE_URL)
            addConverterFactory(GsonConverterFactory.create())
            addCallAdapterFactory(CoroutineCallAdapterFactory())
        }.build().create(NaverAPIService::class.java)
여기까지는 한번만 만들고 재사용하시면 됩니다.

2019-12-27 04:15 UTC, 172900 commented on 172900/GoogleArchitectureStudy/app/src/main/java/com/onit/googlearchitecturestudy/MainActivity.kt
> +const val MOVIE_URL = "movieURL"
1c8daa0

2019-12-27 04:35 UTC, 172900 commented on 172900/GoogleArchitectureStudy/app/src/main/java/com/onit/googlearchitecturestudy/MainActivity.kt
> +            layoutManager = LinearLayoutManager(context)
40db819

2019-12-27 06:32 UTC, 172900 commented on 172900/GoogleArchitectureStudy/app/src/main/java/com/onit/googlearchitecturestudy/MainActivity.kt
> +        return Retrofit.Builder().apply {
d2b4714

싱글톤 클래스로 분리하였습니다.
클래스 이름은 열심히 고민해봤는데 적절한 이름이 떠오르지 않아
networkService라고 지어봤습니다.

2019-12-27 06:33 UTC, 172900 commented on 172900/GoogleArchitectureStudy/app/src/main/java/com/onit/googlearchitecturestudy/ResultMovieListRecyclerAdapter.kt
> +        with(holder as MovieViewHolder) {
352a90c

2019-12-27 06:33 UTC, 172900 commented on 172900/GoogleArchitectureStudy/app/src/main/java/com/onit/googlearchitecturestudy/ResultMovieListRecyclerAdapter.kt
> +) : RecyclerView.Adapter<RecyclerView.ViewHolder>() {
01b7244

2019-12-27 06:33 UTC, 172900 commented on 172900/GoogleArchitectureStudy/app/src/main/java/com/onit/googlearchitecturestudy/ResultMovieListRecyclerAdapter.kt
> +            movieViewHolder.setOnClickListener {
f307e94

2019-12-27 06:34 UTC, 172900 commented on 172900/GoogleArchitectureStudy/app/src/main/java/com/onit/googlearchitecturestudy/ResultMovieListRecyclerAdapter.kt
> +    private var list: ArrayList<Movie>,
df50205

2019-12-27 06:34 UTC, 172900 commented on 172900/GoogleArchitectureStudy/app/src/main/java/com/onit/googlearchitecturestudy/NaverAPIService.kt
> +        @Header("X-Naver-Client-Id") Client_Id: String,
4704779

2019-12-27 06:35 UTC, 172900 commented on 172900/GoogleArchitectureStudy/app/src/main/java/com/onit/googlearchitecturestudy/NaverAPIService.kt
> +    fun getMovieList(
3f0eb88

2019-12-27 06:35 UTC, 172900 commented on 172900/GoogleArchitectureStudy/app/build.gradle
> +    implementation 'com.jakewharton.retrofit:retrofit2-kotlin-coroutines-adapter:0.9.2'
3f0eb88

2019-12-27 14:50 UTC, sjjeong requested changes

2019-12-27 14:50 UTC, sjjeong commented on 172900/GoogleArchitectureStudy/app/src/main/java/com/onit/googlearchitecturestudy/NaverAPIInterceptor.kt
> +class NaverAPIInterceptor : Interceptor {
https://source.android.com/setup/contribute/code-style#treat-acronyms-as-words
보시고 클래스명 수정해주세요

2019-12-27 14:59 UTC, 172900 commented on 172900/GoogleArchitectureStudy/app/src/main/java/com/onit/googlearchitecturestudy/NaverAPIInterceptor.kt
> +class NaverAPIInterceptor : Interceptor {
bae3742

2019-12-27 15:29 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-12-27 15:42 UTC, merged