HW-1 영화 검색 어플리케이션
sjjeong/GoogryAndroidArchitecutreStudy pull request #370
Opened 2019-12-23 18:43 UTC by handnew04

2019-12-24 06:29 UTC, ghkdua1829 requested changes

2019-12-24 06:29 UTC, ghkdua1829 commented on handnew04/app/src/main/res/layout/activity_main.xml
> +        android:id="@+id/editText"
아이디명을 좀 더 명확하고 직관적으로 알아 볼 수 있게 바꿔주시면 더 좋을 것 같습니다!

2019-12-24 06:29 UTC, ghkdua1829 commented on handnew04/app/src/main/res/layout/activity_main.xml
> +        android:id="@+id/button"
아이디명 이것두요!!

2019-12-24 06:29 UTC, ghkdua1829 commented on handnew04/app/src/main/res/layout/activity_main.xml
> +        android:id="@+id/et_searchBar"
아 여기서 바꿔주셧네요..ㅎㅎㅎ 처음 피드백은 무시하셔도 될거같습니다!!

2019-12-24 06:29 UTC, ghkdua1829 commented on handnew04/app/src/main/java/com/example/handnew04/RetrofitService.kt
> +    @Headers("X-Naver-Client-Id: _dxLf04IXVNiUhZX4W5y", "X-Naver-Client-Secret: 9NQwQGbGve")
와우 이런 좋은 방법이 있었는 지 몰랐네요. 하나 배워갑니다...(메모)

2019-12-24 06:29 UTC, ghkdua1829 commented on handnew04/app/src/main/java/com/example/handnew04/MainActivity.kt
> +
이 변수를 싱글톤 패턴(?)으로 만드시면 더 효율적이라고 들었어요!

2019-12-24 17:31 UTC, handnew04 commented on handnew04/app/src/main/java/com/example/handnew04/MainActivity.kt
> +
89329f2

2019-12-24 17:43 UTC, handnew04 commented on handnew04/app/src/main/java/com/example/handnew04/MainActivity.kt
> +
object 로 선언하면 싱글톤이라고 해서 바꿔 보았어요.

2019-12-25 04:43 UTC, ghkdua1829 approved these changes

2019-12-26 17:01 UTC, sjjeong requested changes
https://www.geeksforgeeks.org/java-naming-conventions/
참고해서 변수명 클래스명 함수명 모두 변경해주세요.

2019-12-26 17:01 UTC, sjjeong commented on handnew04/app/build.gradle
> +    annotationProcessor 'com.github.bumptech.glide:compiler:4.7.1'
kotlin을 사용한다면 kapt로 해야 합니다.
위에 apply plugin: 'kotlin-kapt'도 추가해주세요

2019-12-26 17:01 UTC, sjjeong commented on handnew04/app/src/main/java/com/example/handnew04/MainActivity.kt
> +        rcv_movies.layoutManager = LinearLayoutManager(this)
layoutManager는 xml에서 추가해줄 수 있습니다.

2019-12-26 17:01 UTC, sjjeong commented on handnew04/app/src/main/java/com/example/handnew04/MovieDetailActivity.kt
> +        if (intent.hasExtra(getString(R.string.movieLink))) return intent.getStringExtra(getString(R.string.movieLink))
intent.getStringExtra(getString(R.string.movieLink))에서 key가 없다면 null이 리턴되기 때문에 
return intent.getStringExtra(getString(R.string.movieLink)) 만 하셔도 됩니다.

2019-12-26 17:01 UTC, sjjeong commented on handnew04/app/src/main/java/com/example/handnew04/MovieDetailActivity.kt
> +    private fun webViewInit() {
initWebView가 더 좋은 함수명입니다

2019-12-26 17:01 UTC, sjjeong commented on handnew04/app/src/main/java/com/example/handnew04/RecyclerAdapter_Movie.kt
> +class RecyclerAdapter_Movie(private val context: Context) :
context는 외부에서 받을 필요가 없습니다.

2019-12-26 17:01 UTC, sjjeong commented on handnew04/app/src/main/java/com/example/handnew04/RecyclerAdapter_Movie.kt
> +        this.movies = movies
외부와 객체를 공유하지 말아주세요
clear()와 addAll()를 사용해주세요

2019-12-26 17:01 UTC, sjjeong commented on handnew04/app/src/main/java/com/example/handnew04/RecyclerAdapter_Movie.kt
> +    private var movies: ArrayList<items> = ArrayList()
val로 선언해 주세요

2019-12-26 17:01 UTC, sjjeong commented on handnew04/app/src/main/java/com/example/handnew04/RecyclerAdapter_Movie.kt
> +        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
함수를 하나 만들고 내부적으로 분기코드를 가지게 해주세요
최종 코드는 다음과 같이 나오면 됩니다.
```kotlin
override fun onBindViewHolder(holder: ViewHolder, position: Int) {
    val item = movies.get(position)

    holder.iv_Image?.let { Glide.with(context).load(item.image).into(it) }
    
    holder.tv_title?.text = getHtmlText(item.title)
    holder.tv_pubDate?.text = getHtmlText(item.pubDate)
    holder.tv_director?.text = getHtmlText(item.director)
    holder.tv_actors?.text = getHtmlText(item.actor)
    
    holder.rb_userRating?.rating = item.userRating.toFloat()

    holder.itemView.setOnClickListener {
        itemClickListner.onClick(it, position)
    }
}

2019-12-26 17:01 UTC, sjjeong commented on handnew04/app/src/main/java/com/example/handnew04/RetrofitService.kt
> +    @Headers("X-Naver-Client-Id: _dxLf04IXVNiUhZX4W5y", "X-Naver-Client-Secret: 9NQwQGbGve")
retrofit intercepter에 대해 알아보시고 변경해보세요

2019-12-28 12:27 UTC, handnew04 commented on handnew04/app/build.gradle
> +    annotationProcessor 'com.github.bumptech.glide:compiler:4.7.1'
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/370/commits/7c3705d94b5d18b2331cf61697d3aa447ca0979d

2019-12-28 12:27 UTC, handnew04 commented on handnew04/app/src/main/java/com/example/handnew04/MainActivity.kt
> +        rcv_movies.layoutManager = LinearLayoutManager(this)
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/370/commits/a1e6c4a00624297654cb5de09d4f6077c051bd9c

2019-12-28 12:28 UTC, handnew04 commented on handnew04/app/src/main/java/com/example/handnew04/MovieDetailActivity.kt
> +        if (intent.hasExtra(getString(R.string.movieLink))) return intent.getStringExtra(getString(R.string.movieLink))
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/370/commits/0889a3e0a149129ed74c9ebd4b3c3fcc6dd1e511

2019-12-28 12:28 UTC, handnew04 commented on handnew04/app/src/main/java/com/example/handnew04/MovieDetailActivity.kt
> +    private fun webViewInit() {
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/370/commits/aa527a1f17dfd0e119662da2df873e45afa146e2

2019-12-28 12:28 UTC, handnew04 commented on handnew04/app/src/main/java/com/example/handnew04/RecyclerAdapter_Movie.kt
> +class RecyclerAdapter_Movie(private val context: Context) :
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/370/commits/a4d3e9b05db35424383359e5b1128a63403669d5

2019-12-28 12:29 UTC, handnew04 commented on handnew04/app/src/main/java/com/example/handnew04/RecyclerAdapter_Movie.kt
> +        this.movies = movies
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/370/commits/d20726e568523e31b62f1770a6ff747a15340494

2019-12-28 12:29 UTC, handnew04 commented on handnew04/app/src/main/java/com/example/handnew04/RecyclerAdapter_Movie.kt
> +    private var movies: ArrayList<items> = ArrayList()
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/370/commits/d20726e568523e31b62f1770a6ff747a15340494

2019-12-28 12:29 UTC, handnew04 commented on handnew04/app/src/main/java/com/example/handnew04/RecyclerAdapter_Movie.kt
> +        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/370/commits/74d273c3af95b9488737e771e509f503b43cbe43

2019-12-28 12:29 UTC, handnew04 commented on handnew04/app/src/main/java/com/example/handnew04/RetrofitService.kt
> +    @Headers("X-Naver-Client-Id: _dxLf04IXVNiUhZX4W5y", "X-Naver-Client-Secret: 9NQwQGbGve")
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/370/commits/f51fda0cfb4a4cacf189ed36397c7e270e127474

2019-12-28 13:14 UTC, sjjeong commented on handnew04/app/build.gradle
> +    annotationProcessor 'com.github.bumptech.glide:compiler:4.7.1'
annotationProcessor를 kapt로 변경해주세요

2019-12-28 13:16 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-12-28 13:30 UTC, merged