HW5 데이터 바인딩 적용하기
sjjeong/GoogryAndroidArchitecutreStudy pull request #371
Opened 2019-12-25 12:33 UTC by bean628

이번주 과제인 데이터 바인딩 적용하기와 지난주에 시작했다가 못 끝낸
HW4-2 검색 히스토리 화면 구현하기도 같이 했습니다~

2019-12-26 11:30 UTC, ironelder approved these changes
Main과 history부분에 겹치는 코드가 몇군데 있는데... 이를 Base로 올려보는 것은 어떨까요?

2019-12-26 11:30 UTC, ironelder commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/data/source/local/NaverLocalDataSourceImpl.kt
> +    }
Thread안에서 또다른 Thread가 생성되어서 불리고 있는데... 이게 괜찮은지 잘 모르겠습니다...

만약 단순 DB작업 때문이라면 Rx또는 Coroutine을 사용해보는 것은 어떨까요? ㅎㅎ

2019-12-28 07:14 UTC, bean628 commented
> Main과 history부분에 겹치는 코드가 몇군데 있는데... 이를 Base로 올려보는 것은 어떨까요?

막상 해보니 대부분 Contract에서 오버라이드를 하다보니 생각보다 Base에서 처리할수 있는 코드가 적어서 큰 차이는 없지만 Base로 처리할 수 있는 부분은 옮겼습니다.

94c4ad0

2019-12-28 07:24 UTC, bean628 commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/data/source/local/NaverLocalDataSourceImpl.kt
> +    }
구글 샘플 보고 별 생각없이 따라한거라 진혁님께서 질문하신걸 보고 해당 코드에 대해서 좀 검색해보면서 고민해봤는데요.

크게 2가지 이유인 것 같습니다.
1. DiskIO는 싱글 쓰레드여서 UI를 변경할 수 없고, UI 변경 관련 작업은 UI 쓰레드인 MainThread에서 해야함.
2.  쓰레드 하나에만 동작이 몰려 무거워지지 않게 하면서 용도별로 쓰레드를 구분하려고 한 것 같습니다.

Rx나 Corutine은 자율 과제이기도하고 지금은 시간이 없어성... 다음주에.. 늦어도 다다음주까지 적용해보도록 하겠습니다. ㅎㅎ

2019-12-28 13:33 UTC, sjjeong requested changes

2019-12-28 13:33 UTC, sjjeong commented on bean628/MyProject/app/build.gradle
> +apply plugin: 'kotlin-android-extensions'
이 라인은 제거해야 합니다.
제거하고 나서 다시 리뷰 하겠습니다.

2019-12-28 14:52 UTC, bean628 commented on bean628/MyProject/app/build.gradle
> +apply plugin: 'kotlin-android-extensions'
엇? 저거 처음에 지웠었는데 작업하면서 저도 모르는사이에 복구?가 됐네요

수정했습니다.
0ac7fb7

2019-12-29 13:57 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-12-29 22:06 UTC, merged