HW-5 데이터 바인딩 추가
sjjeong/GoogryAndroidArchitecutreStudy pull request #372
Opened 2019-12-25 16:41 UTC by 2giwon

1. ktx로 레이아웃 아이디를 가져와 처리하던 부분 데이터 바인딩으로 변경
2. BaseRecyclerView에서 데이터바인딩 타입을 제네릭으로 선언하여 처리하도록 수정

2019-12-27 04:00 UTC, taeiim commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/base/BaseFragment.kt
> +
set은 어떤 용도로 있는것인가요?

2019-12-27 04:00 UTC, taeiim commented on 2giwon/ArchitectureStudy/app/src/main/res/layout/fg_contents.xml
전체적으로 data binding을
단순히 view만 bind하는 역할로만 사용하신 것 같습니다 ! 

클래스에서 view에 대한 참조를 끊고 xml 에서 처리할 수 있도록 하면 더 좋을 것 같습니다.

2019-12-27 05:41 UTC, 2giwon commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/base/BaseFragment.kt
> +
var로 지연초기화를 하지만 가변성을 제한하여 immutable처럼 사용하게 위해서 적용하였습니다.

자식클래스에서 접근해서 사용할 수 있지만 인스턴스는 바꾸지 못하도록 입니다.

2019-12-27 08:15 UTC, 2giwon commented on 2giwon/ArchitectureStudy/app/src/main/res/layout/fg_contents.xml
수정했습니다.
76bb4cb0769ff4937d71777841b5c08854a8c5c3
0b2205e555d01ea6b1a219d58aa557155874a46c

2019-12-27 17:58 UTC, taeiim commented on 2giwon/ArchitectureStudy/app/src/main/res/layout/rv_contents_item.xml
> +    </data>
item으로 model을 한번에 받아서 item.description 
이런 형식으로 사용하는 것은 어떤가요?ㅎㅎ

2019-12-28 02:22 UTC, 2giwon commented on 2giwon/ArchitectureStudy/app/src/main/res/layout/rv_contents_item.xml
> +    </data>
수정했습니다^^
6ab0aa6e46390d5a79487ea85fdce4dcd9422a37

2019-12-28 03:11 UTC, taeiim approved these changes

2019-12-28 13:32 UTC, sjjeong requested changes

2019-12-28 13:32 UTC, sjjeong commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/base/BaseRecyclerView.kt
> +            binding.executePendingBindings()
onBindViewHolder자체를 override하게 하면 지금은 super를 나중에 부르지만 사용하는 입장에서 super를 나중에 호출해야하는 것을 인지 해야 합니다.
abstract fun을 만들고 여기서 먼저 호출해주는게 좋을 것 같습니다.

2019-12-28 13:32 UTC, sjjeong commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/base/BaseRecyclerView.kt
> +    abstract class Adapter<A : Any, B : ViewDataBinding>(
Any라면 `: Any`를 제거 해도 좋을 것 같습니다.

2019-12-28 13:32 UTC, sjjeong commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/ext/ViewExt.kt
> +}
이 extension 함수들은 View보단 context extension 성격으로 보입니다.

2019-12-28 13:32 UTC, sjjeong commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/ext/ViewExt.kt
> +    setOnClickListener {
start라고 하면 새로운 화면이 바로 시작 되어야 할 것 같은데 내부 코드는 clickListener를 등록하는 로직입니다.
함수명을 변경하거나 내부 로직을 변경해주세요

2019-12-28 17:31 UTC, 2giwon commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/base/BaseRecyclerView.kt
> +    abstract class Adapter<A : Any, B : ViewDataBinding>(
수정했습니다
827073d6dd1ff641ae0d3735b356e22f50f0ab1f

2019-12-28 17:31 UTC, 2giwon commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/base/BaseRecyclerView.kt
> +            binding.executePendingBindings()
수정했습니다.
05d162826a893fdcf14b373e4171189dd4fd3fd5

2019-12-28 17:31 UTC, 2giwon commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/ext/ViewExt.kt
> +}
수정했습니다
6775374c2b40a2b7a01496019782cf92674872e3

2019-12-28 17:32 UTC, 2giwon commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/ext/ViewExt.kt
> +    setOnClickListener {
수정했습니다.
2bb1ddc9b2449de42d703defd75564f4ef7ceb5e

2019-12-29 04:47 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-12-29 08:10 UTC, merged