HW-1. 네이버 영화검색 api 구현
sjjeong/GoogryAndroidArchitecutreStudy pull request #373
Opened 2019-12-25 18:41 UTC by swppppp

- 네이버 api사용, 영화검색 및 상세 웹뷰 이동 구현

2019-12-26 05:16 UTC, 172900 requested changes

2019-12-26 05:16 UTC, 172900 commented on swppppp/app/src/main/java/com/siwon/prj/MainActivity.kt
>              }
onBindViewHolder() 메소드는 RecyclerView에 새 항목이 표시 될 때마다 호출되므로 
목록이 매우 크면 수백 또는 더 많은 클릭 리스너가 불필요하게 생성됩니다.
따라서 setOnClickListener는 viewHolder생성 시점에 달아주는게 좋습니다.

2019-12-26 05:16 UTC, 172900 commented on swppppp/app/src/main/res/layout/activity_main.xml
> +        android:id="@+id/list"
xml위젯의 id name은 명확하게 지어야 합니다.

특히 kotlin-android-extensions을 사용하여 id이름을 변수명으로 바로 사용하는 경우에는
코드내에서 더더욱 뭔지 알아보기 힘들어서 확실히해줘야 합니다.
저같은 경우에는 movieRecyclerView, searchEditText, searchButton등 id 가장 뒤에 위젯의 이름을 넣어
코드상에서 어떤 위젯의 id인지 알아 볼 수 있도록 씁니다.

추가로 코틀린 컨벤션에선 카멜케이스를 기본으로 하여서
저는 id를 그대로 변수명으로 쓰는 kotlin android에선 id이름을 지을 때 스네이크 케이스가 아닌 카멜케이스를 사용합니다.

2019-12-26 05:16 UTC, 172900 commented on swppppp/app/src/main/java/com/siwon/prj/MainActivity.kt
> +    lateinit var movies: ArrayList<Movie>
검색결과인 movies를 activity에서 멤버변수로 가지고 있을 이유가 없어보입니다..!
response.body()의 결과를 멤버변수로 저장하지말고
지역변수로 함수내에서 처리하는게 좋아보입니다.

2019-12-26 05:16 UTC, 172900 commented on swppppp/app/src/main/java/com/siwon/prj/MainActivity.kt
>                      }
검색버튼을 눌렀을 때 adapter를 생성하고 recyclerView에 지정해주는데
이렇게 하면 검색버튼을 누를 때 마다 어댑터를 생성하는 작업이 반복되어 좋지 않습니다.

어댑터는 onCreate() 내부에서 한번만 생성하고
검색버튼을 눌렀을 땐 어댑터를 새로 생성하는게 아니라
어댑터 내부의 movieList에 검색결과를 추가(ex movieList.addAll(검색결과))하는 메소드를 만들어 사용하는게 좋습니다.

2019-12-26 05:16 UTC, 172900 commented on swppppp/app/src/main/java/com/siwon/prj/DetailWebview.kt
> +        webview.loadUrl(intent.getStringExtra("link"))
위와 같이 반복되는 구문은 코틀린에서 제공하는 with() 혹은 run()함수를 사용하면 간결하게 표시할 수 있습니다.
찾아보고 적용해보세요!

2019-12-26 17:42 UTC, swppppp commented on swppppp/app/src/main/java/com/siwon/prj/MainActivity.kt
>              }
감사합니다!2bcc486a

2019-12-26 17:42 UTC, swppppp commented on swppppp/app/src/main/res/layout/activity_main.xml
> +        android:id="@+id/list"
d684a1f4

2019-12-26 17:43 UTC, swppppp commented on swppppp/app/src/main/java/com/siwon/prj/MainActivity.kt
> +    lateinit var movies: ArrayList<Movie>
649646f5

2019-12-26 17:43 UTC, swppppp commented on swppppp/app/src/main/java/com/siwon/prj/MainActivity.kt
>                      }
976a0a0b

2019-12-26 17:44 UTC, swppppp commented on swppppp/app/src/main/java/com/siwon/prj/DetailWebview.kt
> +        webview.loadUrl(intent.getStringExtra("link"))
d5523294

2019-12-27 04:59 UTC, 172900 commented on swppppp/app/src/main/java/com/siwon/prj/MainActivity.kt
>                      }
`fun set(items: ArrayList<Movie>) {
             this.items = items
             notifyDataSetChanged()
}`

에서 this.items = items는 얕은 복사가 발생하여 외부와 객체를 공유하게 됩니다.

adapter내부의 items를 late init말고  val items = ArrayList<>()로 선언하고
set함수 내부에서는 
this.items.clear()
this.items.addAll(item)와 같이 
내부 노드들을 삭제하고 깊은 복사로 추가해주는 형식이 좋습니다.

추가로 set이라는 함수 이름은 어떤 동작을 기대하는지 애매모호해서 좀 더 명확한 이름을 주는게 좋을 것 같습니다.

2019-12-27 05:22 UTC, swppppp commented on swppppp/app/src/main/java/com/siwon/prj/MainActivity.kt
>                      }
621b0d6
수정했습니당!

2019-12-27 05:25 UTC, 172900 approved these changes

2019-12-28 04:54 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-12-29 01:41 UTC, merged