HW-1 네이버 API를 이용한 영화 검색 어플리케이션
sjjeong/GoogryAndroidArchitecutreStudy pull request #375
Opened 2019-12-26 11:46 UTC by seunghee63

2019-12-26 18:35 UTC, AhnHyeonho commented
전반적으로 코드들이 잘 나뉘어져있고 객체들의 네이밍도 깔끔한 것 같아 리뷰하면서 많은 것을 배워갑니다 :) 
다만 아쉬운 점 이있다면 커밋을 찍을 때 해당 커밋과 관련된 파일만 add해서 찍어주시면 리뷰할 때 조금 더 도움이 될 것 같습니다. A 파일이 여러 커밋에 걸쳐 수정되다보니 리뷰를 적었다 지웠다 하는 경우가 종종 있었네요...!  이 점만 보완해주시면 좋을 것 같습니다!

2019-12-27 10:49 UTC, AhnHyeonho commented on seunghee63/MyApplication/app/src/main/java/com/song2/myapplication/network/NetworkServiceImpl.kt
> +}
리뷰에 앞서 레트로핏을 사용해본적이 없음을 미리 말씀드립니다. 리뷰에 문제가 있어도 양해부탁드립니다!

Impl는 구현체로서 위의 오브젝트같은 경우에는 NetworkService 인터페이스를 상속받아서 구현하는 것일텐데 
NetworkServiceImpl : NetworkSevice와 같이 쓰지않고 line:16과 같이 멤버변수로서 사용한 이유를 알 수 있을까요?

2019-12-27 10:49 UTC, AhnHyeonho commented on seunghee63/MyApplication/app/src/main/java/com/song2/myapplication/adapter/MovieViewHolder.kt
>          rating.numStars = movieData.userRating!!.toInt() / 2
moveData.userRating은 Double형으로 받아오는데 이를 toInt()해준다음에 2로 나눠준 배경이 궁금합니다. 만약 Int형으로 처리를 해주고싶었다면 moveData.userRating의 자료형을 Int로 정의해 주는게 맞지 않나 싶습니다!

2019-12-27 22:43 UTC, seunghee63 commented on seunghee63/MyApplication/app/src/main/java/com/song2/myapplication/adapter/MovieViewHolder.kt
>          rating.numStars = movieData.userRating!!.toInt() / 2
ratingbar의 numStarts가  값을 설정 해 주는 메소드라고 생각했고, int형 밖에 처리가 되지 않아서 형변환을 했던것인데 리뷰를 받고 다시 고민 해 보니 잘못된 메소드를 사용했다는 것을 알게되었고 알맞은 메소드를 사용하여 수정 해 보았습니다!

2019-12-27 22:44 UTC, seunghee63 commented on seunghee63/MyApplication/app/src/main/java/com/song2/myapplication/adapter/MovieViewHolder.kt
>          rating.numStars = movieData.userRating!!.toInt() / 2
(`77fe794`)[https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/375/commits/77fe794fb8196f82c2337d882ad7b3c70b169ea6]

2019-12-27 23:00 UTC, seunghee63 commented on seunghee63/MyApplication/app/src/main/java/com/song2/myapplication/network/NetworkServiceImpl.kt
> +}
저도 완벽하게 알고 적용했던 개념이 아니라 정확히는 잘 모르지만.. 제가 이해한 바로는 

NetworkServiceImpl는 단순히 싱글톤패턴으로 retrofit을 빌드 해 주는 역할을하고,
NetworkService는 서버연동 메소드를 가지고 있는 서버연동IF로, 각각의 함수를 NetworkServiceImpl와 UI단을 오가는 매개체로 사용하는 역할을 수행하는 것 이였습니다.

잘못된 개념이 있다면 피드백 해 주시면 감사하겠습니다..!

2019-12-28 13:21 UTC, sjjeong requested changes

2019-12-28 13:21 UTC, sjjeong commented on seunghee63/MyApplication/app/src/main/java/com/song2/myapplication/adapter/MovieAdapter.kt
> +    var data = arrayListOf<MovieData>()
private val로 선언하고 함수를 통해서 데이터만 넣어주도록 해주세요

2019-12-28 13:21 UTC, sjjeong commented on seunghee63/MyApplication/app/src/main/java/com/song2/myapplication/data/GetMovieDataResponse.kt
> +    var items : ArrayList<MovieData>
List로 해주세요

2019-12-28 13:21 UTC, sjjeong commented on seunghee63/MyApplication/app/src/main/java/com/song2/myapplication/data/GetMovieDataResponse.kt
> +    var lastBuildDate : String?,
response는 val로 선언해주시면 됩니다.
MovieData도 동일하게 수정해주세요

2019-12-28 13:21 UTC, sjjeong commented on seunghee63/MyApplication/app/src/main/java/com/song2/myapplication/data/GetMovieDataResponse.kt
> +data class GetMovieDataResponse (
클래스명을 MovieDataResponse로 변경해주세요

2019-12-28 13:21 UTC, sjjeong commented on seunghee63/MyApplication/app/src/main/java/com/song2/myapplication/adapter/MovieViewHolder.kt
> +        itemView.setOnClickListener {
클릭리스너를 bind시점이 아니라 ViewHolder가 생성되는 시점에 해주세요

2019-12-28 13:21 UTC, sjjeong commented on seunghee63/MyApplication/app/src/main/java/com/song2/myapplication/data/MovieRepository.kt
> +        service.getMovieSearch(clientId, secret, keyword, cnt)
NetworkServiceImpl.service로 해주세요.
service라고만 하면 어디서 참조하는지 알 수 없습니다.

2019-12-28 13:21 UTC, sjjeong commented on seunghee63/MyApplication/app/src/main/java/com/song2/myapplication/network/NetworkService.kt
> +        @Header("X-Naver-Client-Id") clientId: String,
Retrofit interceptor를 알아보고 수정해보세요

2019-12-28 13:21 UTC, sjjeong commented on seunghee63/MyApplication/app/src/main/java/com/song2/myapplication/ui/MainActivity.kt
> +    private var dataList = arrayListOf<MovieData>()
dataList를 제거 해보세요

2019-12-28 13:21 UTC, sjjeong commented on seunghee63/MyApplication/app/src/main/java/com/song2/myapplication/ui/MainActivity.kt
> +        rv_main_act_movie_list.apply {
RecyclerView를 초기화하는 작업을 버튼 클릭할때마다 처리 할 필요는 없습니다.
onCreate시점에 한번만 하게 해주세요

2019-12-28 22:29 UTC, seunghee63 commented on seunghee63/MyApplication/app/src/main/java/com/song2/myapplication/ui/MainActivity.kt
> +        rv_main_act_movie_list.apply {
29cd2dc

2019-12-28 22:32 UTC, seunghee63 commented on seunghee63/MyApplication/app/src/main/java/com/song2/myapplication/data/MovieRepository.kt
> +        service.getMovieSearch(clientId, secret, keyword, cnt)
4b5fd0a

2019-12-28 22:33 UTC, seunghee63 commented on seunghee63/MyApplication/app/src/main/java/com/song2/myapplication/data/GetMovieDataResponse.kt
> +    var items : ArrayList<MovieData>
2f9f34c

2019-12-28 22:33 UTC, seunghee63 commented on seunghee63/MyApplication/app/src/main/java/com/song2/myapplication/data/GetMovieDataResponse.kt
> +    var lastBuildDate : String?,
e07c52a

2019-12-28 22:34 UTC, seunghee63 commented on seunghee63/MyApplication/app/src/main/java/com/song2/myapplication/data/GetMovieDataResponse.kt
> +    var lastBuildDate : String?,
459b498

2019-12-28 22:34 UTC, seunghee63 commented on seunghee63/MyApplication/app/src/main/java/com/song2/myapplication/data/GetMovieDataResponse.kt
> +data class GetMovieDataResponse (
d363212

2019-12-29 00:25 UTC, seunghee63 commented on seunghee63/MyApplication/app/src/main/java/com/song2/myapplication/network/NetworkService.kt
> +        @Header("X-Naver-Client-Id") clientId: String,
a8a4a2f

2019-12-29 00:26 UTC, seunghee63 commented on seunghee63/MyApplication/app/src/main/java/com/song2/myapplication/adapter/MovieViewHolder.kt
> +        itemView.setOnClickListener {
fcabk46

2019-12-29 01:25 UTC, seunghee63 commented on seunghee63/MyApplication/app/src/main/java/com/song2/myapplication/ui/MainActivity.kt
> +    private var dataList = arrayListOf<MovieData>()
2edf699

2019-12-29 07:55 UTC, seunghee63 commented on seunghee63/MyApplication/app/src/main/java/com/song2/myapplication/adapter/MovieAdapter.kt
> +    var data = arrayListOf<MovieData>()
2edf699

2020-01-01 15:33 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋
라벨을 잘못 보고 리뷰를 안했었네요 ㅠ 죄송합니다

2020-01-01 15:33 UTC, merged