HW-3 mvvm (Delegates.observable) 변환
sjjeong/GoogryAndroidArchitecutreStudy pull request #38
Opened 2019-05-27 05:30 UTC by improve777

2019-05-27 13:15 UTC, namjackson requested changes

2019-05-27 13:15 UTC, namjackson commented on improve777/GAASProject/app/src/main/java/dev/daeyeon/gaasproject/ui/ticker/TickerFragment.kt
> +            }
뷰모델이 이너클래스로 정의되어 있어서 애매한데, 
뷰모델에선 newValue만 던지고 
실제 메세지 처리는 View쪽에서 처리해주는 게 좋을거같아요!

2019-05-27 13:15 UTC, namjackson commented on improve777/GAASProject/app/src/main/java/dev/daeyeon/gaasproject/ui/ticker/TickerFragment.kt
> +        }
이부분도 마찬가지로 뷰쪽에 잇는게 더 좋을거같아요!

2019-05-27 13:15 UTC, namjackson commented on improve777/GAASProject/app/src/main/java/dev/daeyeon/gaasproject/ui/ticker/TickerFragment.kt
> +
변수 네이밍에 대해서 찾아봤는데 , 아래와 같이 변수명이 중복되는 경우에 _변수로 선언하고 
그외에는 변수앞에 _를  빼는게 좋다고합니다! 


Names for backing properties
If a class has two properties which are conceptually the same but one is part of a public API and another is an implementation detail, use an underscore as the prefix for the name of the private property:

`
class C {
      private val _elementList = mutableListOf<Element>()
      
      val elementList: List<Element>
            get() = _elementList
}`

[https://kotlinlang.org/docs/reference/coding-conventions.html#naming-rules](url)

2019-05-31 06:35 UTC, improve777 commented on improve777/GAASProject/app/src/main/java/dev/daeyeon/gaasproject/ui/ticker/TickerFragment.kt
> +            }
수정 완료하였습니다

2b5062a5803f06a37ea6d30d33ae56bbd89b561f

2019-05-31 06:36 UTC, improve777 commented on improve777/GAASProject/app/src/main/java/dev/daeyeon/gaasproject/ui/ticker/TickerFragment.kt
> +        }
수정 완료하였습니다

2b5062a5803f06a37ea6d30d33ae56bbd89b561f

2019-05-31 06:36 UTC, improve777 commented on improve777/GAASProject/app/src/main/java/dev/daeyeon/gaasproject/ui/ticker/TickerFragment.kt
> +
수정 완료하였습니다

4595d6095fa8cbdd0cb936d0eb412fd0fe1075cf

2019-05-31 12:54 UTC, namjackson submitted a review, later dismissed
수고하셨습니당!

2019-05-31 16:58 UTC, sjjeong commented on improve777/GAASProject/app/src/main/java/dev/daeyeon/gaasproject/ui/ticker/TickerFragment.kt
> +        }
토스트는 빼는게 맞는데 이거는 여기서 처리해도 됩니다.

2019-05-31 23:57 UTC, improve777 commented on improve777/GAASProject/app/src/main/java/dev/daeyeon/gaasproject/ui/ticker/TickerFragment.kt
> +        }
수정 완료하였습니다

5936872dea02d706f677df3efce1bc6696143608

2019-06-01 03:01 UTC, namjackson submitted a review, later dismissed

2019-06-09 11:33 UTC, sjjeong requested changes

2019-06-09 11:33 UTC, sjjeong commented on improve777/GAASProject/app/src/main/java/dev/daeyeon/gaasproject/ui/ticker/TickerFragment.kt
> +            if (marketList[0].isNotEmpty()) {
이 부분 코드 해석하는게 너무 오래걸립니다.
initCurrentArray()를 조금 더 readability하게 수정해주세요

2019-06-09 11:41 UTC, improve777 commented on improve777/GAASProject/app/src/main/java/dev/daeyeon/gaasproject/ui/ticker/TickerFragment.kt
> +            if (marketList[0].isNotEmpty()) {
수정 완료하였습니다

0fdf167e98b7ed30cb3dd497a84a9bf21b82f23f

2019-06-09 11:44 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-06-09 11:45 UTC, merged