HW-4 데이터 캐싱
sjjeong/GoogryAndroidArchitecutreStudy pull request #381
Opened 2019-12-29 14:16 UTC by wooooooak

4주차 데이터 캐싱 과제 PR입니다.
요번에 참석을 못해서... 제대로 했는지 모르겠네요ㅠ 리뷰 부탁드립니다 ㅎㅎ

2019-12-30 14:51 UTC, JayYi requested changes
리뷰 했습니다. 확인 부탁드려요.

2019-12-30 14:51 UTC, JayYi commented on wooooooak/StudyApp/app/src/main/java/wooooooak/com/studyapp/data/model/repository/NaverApiRepositoryImpl.kt
> +                naverLocalDataSource.clearBlogList()
네트워크 에러로 인해서 결과값을 못 받아 올 경우가 있을 텐데, 결과 확인전에 cached 된 값을 clear 하는게 맞을지가....
로직상에 문제라 한번 고민해보세요.

2019-12-30 14:51 UTC, JayYi commented on wooooooak/StudyApp/app/src/main/java/wooooooak/com/studyapp/data/model/sharedpreference/SharedPreferenceManager.kt
> +        get() = preferenceManager.getString(BLOG_SEARCH_TITLE, "") ?: ""
getString의 두번째 param이 default vaule여서 ?: "" 코드는 삭제 하셔도 됩니다.

2019-12-30 14:51 UTC, JayYi commented on wooooooak/StudyApp/app/src/main/res/layout/fragment_movie.xml
> +        android:layout_height="wrap_content"
해당 코드 확인(android:layout_height="wrap_content") 부탁드립니다. 아래쪽에서 top, bottom 위치를 align을 하셔서 확인 부탁드렸어요.

2019-12-30 14:51 UTC, JayYi commented on wooooooak/StudyApp/app/src/main/java/wooooooak/com/studyapp/ui/blog/BlogPresenter.kt
> +                        view.renderListEmptyView(true)
기존에 이미 render 아이템의 있는 경우에는 adapter 내 data를 clear하는게 맞을 것 같아요. 해당 코드 확인 부탁드려요.

2019-12-30 14:51 UTC, JayYi commented on wooooooak/StudyApp/app/src/main/java/wooooooak/com/studyapp/data/model/database/AppDataBase.kt
> +            instance ?: buildDatabase(context).also { instance = it }
해당줄의 instance 코드가 의미 없어보여요. 이미 윗줄에서 instance null 상태 확인되었어요.

2019-12-30 15:07 UTC, BeokBeok commented on wooooooak/StudyApp/app/src/main/java/wooooooak/com/studyapp/data/model/database/AppDataBase.kt
> +            instance ?: buildDatabase(context).also { instance = it }
`invoke` 연산자에서 객체 생성을 하는 것은 권장하지 않습니다.
연산자가 아닌 함수를 통하여 객체 생성을 해주시면 좋을 것 같습니다.

2019-12-30 16:25 UTC, JayYi requested changes

2019-12-30 16:25 UTC, JayYi commented on wooooooak/StudyApp/app/src/main/java/wooooooak/com/studyapp/ui/blog/BlogPresenter.kt
> +                        view.renderListEmptyView(true)
기존에 이미 화면에 결과가 있는 경우 recycler view랑 empty list view와 겹쳐 보일 것 같은데 해당 로직에 대한 처리가 안 돼 있어 보여요. 확인 부탁드려요.

2019-12-30 16:29 UTC, wooooooak commented on wooooooak/StudyApp/app/src/main/java/wooooooak/com/studyapp/data/model/sharedpreference/SharedPreferenceManager.kt
> +        get() = preferenceManager.getString(BLOG_SEARCH_TITLE, "") ?: ""
두번째 param이 default value라서 non-nullable 할줄 알았는데 getString 함수 정의를 보니 아래와 같이 nullable이더라구요..
```kotlin
@Nullable
 String getString(String key, @Nullable String defValue);
```
실제로 ?: "" 코드를 제거하면 컴파일 에러가 납니다.
저도 혼란스러웠는데... 그렇더라구요ㅠ

2019-12-30 16:34 UTC, wooooooak commented on wooooooak/StudyApp/app/src/main/res/layout/fragment_movie.xml
> +        android:layout_height="wrap_content"
음... 어떤 말씀이신지 잘 모르겠습니다ㅠ
텍스트의 높이는 텍스트에 맞게 wrap_content로 설정하였고, textAlignment로 텍스트 가운데 정렬을 했는데 이게 전체적인 top, bottom 과 관련이 있는건가요??

2019-12-30 16:39 UTC, wooooooak commented on wooooooak/StudyApp/app/src/main/java/wooooooak/com/studyapp/ui/blog/BlogPresenter.kt
> +                        view.renderListEmptyView(true)
기존에 데이터를 조회해서 items.isEmpty가 아니라면 view.renderListEmptyView(false)가 호출되어 empty list view는 랜더링 되지 않고 있습니다.

제가 실행해보았을때는 말씀해주신 현상이 안보였는데... 혹시 실행해보았더니 그렇게 되던가요..?

2019-12-30 16:54 UTC, wooooooak commented on wooooooak/StudyApp/app/src/main/java/wooooooak/com/studyapp/ui/blog/BlogPresenter.kt
> +                        view.renderListEmptyView(true)
제가 짠 로직으로는 이미 rendering된 아이템(cached data 포함)이 있는 경우, 검색어를 새로 바꿔 입력하지 않는다면 기존 item의 마지막 index부터 무한 로딩이 가능하게 되어서 clear를 하지 않고있어요 ㅎㅎ
참고로 제가 ListAdapter를 사용하고 있어서 만약 검색어를 새로 입력하여 리스트가 완전히 바껴야 할 경우에는, ListAdapter가 알아서 기존 데이터와 신규 데이터를 비교해서 처리해줍니다.

2019-12-30 17:19 UTC, wooooooak commented on wooooooak/StudyApp/app/src/main/java/wooooooak/com/studyapp/data/model/repository/NaverApiRepositoryImpl.kt
> +                naverLocalDataSource.clearBlogList()
예리하시군요... +_+ 
수정했습니다 감사합니다!

434d5b8eb76c7ef416fe02e89dc8b2d30f2c9e37

2019-12-30 17:23 UTC, wooooooak commented on wooooooak/StudyApp/app/src/main/java/wooooooak/com/studyapp/data/model/database/AppDataBase.kt
> +            instance ?: buildDatabase(context).also { instance = it }
@JayYi  @BeokBeok 
수정 했습니다 감사합니다!

https://android.jlelse.eu/android-room-using-kotlin-f6cc0a05bf23
위 문서를 보고 괜찮은것 같아서 사용했는데 권장하지 않는 방법인가 보네요..ㅎㅎ
혹시 invoke연산자로 객체 생성을 권장하지 않는 이유는, 객체 생성 역할을 담당하는 생성자가 존재하기 때문인가요?

2019-12-30 17:34 UTC, JayYi commented on wooooooak/StudyApp/app/src/main/java/wooooooak/com/studyapp/ui/blog/BlogPresenter.kt
> +                        view.renderListEmptyView(true)
update 된 코드만 보다 보니 DiffUtil을 사용하신 걸 깜빡했네요.

2019-12-30 17:42 UTC, JayYi commented on wooooooak/StudyApp/app/src/main/java/wooooooak/com/studyapp/ui/blog/BlogPresenter.kt
> +                        view.renderListEmptyView(true)
윗 댓글에 말씀드렸듯이 우선은 DiffUtil 사용하신 걸 깜빡하고.....리뷰를 잘 못 남겼네요.
현재 코드 상으로는 문제가 없어 보입니다.
하지만, recycler view에 기본 배경 색깔이 있는 경우에 empty list view 내 글자 색상에따라 알림 문구가 보이지 않을 것 같아요. 이 부분은 반영 안하셔도 되니 참고만 해주세요.

2019-12-30 17:44 UTC, JayYi commented on wooooooak/StudyApp/app/src/main/java/wooooooak/com/studyapp/data/model/sharedpreference/SharedPreferenceManager.kt
> +        get() = preferenceManager.getString(BLOG_SEARCH_TITLE, "") ?: ""
음..
preferenceManager를 자바에서만 써본 경험이..
이런...저의 바닥이 보였네요....ㅠ

2019-12-30 17:51 UTC, JayYi requested changes

2019-12-30 17:51 UTC, JayYi commented on wooooooak/StudyApp/app/src/main/res/layout/fragment_movie.xml
> +        android:layout_height="wrap_content"
제가 또 실수했네요;;
제대로 봤어야했는데, 제가 휴가를 너무 오래 갔나 보네요.
죄송합니다.

2019-12-30 17:52 UTC, JayYi approved these changes
고생하셨습니다.

2019-12-31 00:58 UTC, BeokBeok commented on wooooooak/StudyApp/app/src/main/java/wooooooak/com/studyapp/data/model/database/AppDataBase.kt
> +            instance ?: buildDatabase(context).also { instance = it }
@wooooooak 
invoke 연산자는 `호출`과 관련된 연산자이므로 
invoke 연산자 내에서 인스턴스를 생성하게 된다면 (여기서는 객체보다는 인스턴스라는 말이 더 좋겠네요.)
해당 연산자의 의도와 다른 기능을 수행하게 됩니다.

즉, 연산자의 의미가 함수의 이름과 일치해야함을 위반하게 됩니다.

예를 들자면, not 연산자(`!`) 를 호출하여 팩토리얼 기능을 구현하는 것과 비슷하게 생각하시면 될 것 같습니다.

2019-12-31 02:35 UTC, wooooooak commented on wooooooak/StudyApp/app/src/main/java/wooooooak/com/studyapp/data/model/database/AppDataBase.kt
> +            instance ?: buildDatabase(context).also { instance = it }
@BeokBeok 
아하 감사합니다. 의도와 다르게 사용될뻔 했네요...ㅎㅎ

2020-01-01 14:41 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋
interface에 var로 get/set을 처리하게 하는 방식이 제가 사용하던 방식이 아니라서 신기했습니다.

2020-01-02 03:42 UTC, merged