HW-2 dataModel 적용하기
sjjeong/GoogryAndroidArchitecutreStudy pull request #384
Opened 2019-12-30 19:50 UTC by handnew04

2019-12-31 04:56 UTC, ghkdua1829 approved these changes
수고하셨습니다!!

2020-01-01 15:26 UTC, sjjeong requested changes

2020-01-01 15:26 UTC, sjjeong commented on handnew04/app/src/main/java/com/example/handnew04/data/remote/MovieRemoteDataResource.kt
> +interface MovieRemoteDataResource {
DataResource가 아니라 DataSource 입니다

2020-01-02 12:07 UTC, handnew04 commented on handnew04/app/src/main/java/com/example/handnew04/data/remote/MovieRemoteDataResource.kt
> +interface MovieRemoteDataResource {
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/384/commits/c30eadb45f7831ed31bce39973c24a69d5883474

2020-01-02 15:28 UTC, sjjeong approved these changes

2020-01-03 01:44 UTC, merged