HW-2 Model 적용하기
sjjeong/GoogryAndroidArchitecutreStudy pull request #385
Opened 2019-12-31 04:47 UTC by ghkdua1829

2019-12-31 12:13 UTC, handnew04 approved these changes
수고하셨어요!!

2020-01-01 15:28 UTC, sjjeong requested changes

2020-01-01 15:28 UTC, sjjeong commented on ghkdua1829/app/src/main/java/com/example/architecture_project/data/datasource/local/NaverLocalDataSourceImpl.kt
> +class NaverLocalDataSourceImpl {
NaverLocalDataSource를 implements 하는게 빠졌습니다.

2020-01-01 15:28 UTC, sjjeong commented on ghkdua1829/app/src/main/java/com/example/architecture_project/feature/search/MainActivity.kt
> +//        )
주석 제거해주세요

2020-01-01 20:31 UTC, ghkdua1829 commented on ghkdua1829/app/src/main/java/com/example/architecture_project/data/datasource/local/NaverLocalDataSourceImpl.kt
> +class NaverLocalDataSourceImpl {
9a6dd40d7c2e6a50a027b608323aae3249268de0

2020-01-01 20:31 UTC, ghkdua1829 commented on ghkdua1829/app/src/main/java/com/example/architecture_project/feature/search/MainActivity.kt
> +//        )
9c230123a48d1b9136bd1faef8ded04f8f612cf8

2020-01-02 11:08 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋
다음부턴 커밋하기 전에 Reformat code 해주셔야해요

2020-01-02 12:30 UTC, merged