HW-2 Model 적용하기
sjjeong/GoogryAndroidArchitecutreStudy pull request #388
Opened 2020-01-01 07:51 UTC by AhnHyeonho

* NaverRepository 생성
* NaverRemoteDataSource 생성
* MainActivity 수정
* Model 적용으로 인한 코드 전체적인 수정

2020-01-01 07:52 UTC, AhnHyeonho commented
커밋 메시지 수정으로 인하여 HW-1 의 내용도 함께 올라왔습니다.  HW-2 내용부터 리뷰해주시면 되겠습니다.

2020-01-02 01:13 UTC, kts6056 reviewed
-펑-

2020-01-02 01:13 UTC, kts6056 commented on AhnHyeonho/FirstProject/app/src/main/java/com/hansung/firstproject/data/repository/NaverRepository.kt
> +    fun getInstance(dataSource: NaverRemoteDataSource): NaverRepository {
https://stackoverflow.com/questions/45777304/kotlin-how-to-make-field-read-only-for-external-classes 참고해보세요

2020-01-04 04:20 UTC, seunghee63 requested changes

2020-01-04 04:20 UTC, seunghee63 commented on AhnHyeonho/FirstProject/app/src/main/java/com/hansung/firstproject/network/NaverApiServiceImpl.kt
>  }
아직 저도 Repository패턴에 대한 이해가 많이 부족해서 정확히는 모르겠지만..
naverApi도 remote 저장소에서 가져오는 내용이니, 관련 파일은 source>remote패키지에 넣는 것이 더 좋을 것 같습니다!

2020-01-04 04:20 UTC, seunghee63 commented on AhnHyeonho/FirstProject/app/src/main/java/com/hansung/firstproject/adapter/MovieHolder.kt
> +                val webPage = Uri.parse(data.link)
지난번 스터디에서 말씀 해 주셨듯이, 
bind함수는 새로운 데이터를 추가 할 때 마다 호출되므로, viewHolder에서 클릭리스너를 정의 해 주는 것이 좋을 듯 합니다!

2020-01-04 04:20 UTC, seunghee63 commented on AhnHyeonho/FirstProject/app/src/main/java/com/hansung/firstproject/network/NaverApiServiceImpl.kt
> +    private val naverSearchService: NaverApiService = retrofit.create(NaverApiService::class.java)
retrofit 을 build 할 때는 싱글톤 패턴을 사용하는 것이 좋을 것 같습니다.

2020-01-04 07:15 UTC, AhnHyeonho commented on AhnHyeonho/FirstProject/app/src/main/java/com/hansung/firstproject/network/NaverApiServiceImpl.kt
> +    private val naverSearchService: NaverApiService = retrofit.create(NaverApiService::class.java)
어느부분을 싱글톤으로 적용해야하는지 이해가 잘 안갑니다...! 혹시 좀 더 자세히 설명 가능하실까요?.?

2020-01-04 07:15 UTC, AhnHyeonho commented on AhnHyeonho/FirstProject/app/src/main/java/com/hansung/firstproject/network/NaverApiServiceImpl.kt
>  }
수정하였습니다!


93eb6d2

2020-01-04 07:15 UTC, AhnHyeonho commented on AhnHyeonho/FirstProject/app/src/main/java/com/hansung/firstproject/adapter/MovieHolder.kt
> +                val webPage = Uri.parse(data.link)
수정하였습니다!


3467a19

2020-01-04 11:11 UTC, zozero94 reviewed
안녕하세요 3기 조재영입니다.
안현호 학생이 제 소개로 온 친구라서 부족하지만 리뷰한번 적어봅니다.

2020-01-04 11:11 UTC, zozero94 commented on AhnHyeonho/FirstProject/app/src/main/AndroidManifest.xml
> +        <activity android:name=".MovieInformationActivity"></activity>
```xml
<activity android:name=".MovieInformationActivity" />
```
형태 추천드려여

2020-01-04 11:11 UTC, zozero94 commented on AhnHyeonho/FirstProject/app/src/main/java/com/hansung/firstproject/adapter/MovieHolder.kt
>  class MovieHolder(private val movieView: View) : RecyclerView.ViewHolder(movieView) {
RecyclerViewAdapter와 유사하게 템플릿 클래스로 (Base class) 만들어보는건 어떨까요?

2020-01-04 11:11 UTC, zozero94 commented on AhnHyeonho/FirstProject/app/src/main/java/com/hansung/firstproject/adapter/MovieHolder.kt
> +            val webIntent = Intent(
개인적인 취향인데 
```kotlin
    itemView.setOnClickListener {
            Intent(
                movieView.context,
                MovieInformationActivity::class.java
            ).apply {
                putExtra("WEB_PAGE", webPage.toString())
            }.also { movieView.context.startActivity(it) }
```
webIntent 변수는 init시 ``한번`` 사용하기 때문에 이렇게 사용하는것도 나쁘지 않아보입니다.

2020-01-04 11:11 UTC, zozero94 commented on AhnHyeonho/FirstProject/app/src/main/java/com/hansung/firstproject/adapter/MovieHolder.kt
> +            val webIntent = Intent(
또 석준님한테 들었던 방법인데 
액티비티를 시작하는 인텐트는 확실하게 그 액티비티를 명시하기 위해서

```kotlin
itemView.setOnClickListener {
            MovieInformationActivity.getIntent(movieView.context).apply {
                putExtra(MovieInformationActivity.TAG, webPage.toString())
            }.also { movieView.context.startActivity(it) }
        }
```
형태로 해당 액티비티에서 Intent를 가져오는게 좋다고 들었습니다.
<hr>  
해당 코드는 MovieInformationActivity에 위치해야 하는 코드입니다.

```kotlin
companion object {
        const val TAG = "WEB_PAGE"
        fun getIntent(context: Context): Intent {
            return Intent(context, MovieInformationActivity::class.java)
        }
    }
```

2020-01-04 11:11 UTC, zozero94 commented on AhnHyeonho/FirstProject/app/src/main/java/com/hansung/firstproject/adapter/RecyclerViewAdapter.kt
> +        var item = items[position]
val 변수로 바꾸는게 좋아보입니당

2020-01-04 11:11 UTC, zozero94 commented on AhnHyeonho/FirstProject/app/src/main/java/com/hansung/firstproject/adapter/RecyclerViewAdapter.kt
> +            holder.bindItems(item)
ViewHolder도 Template Class로 만든다면 해당작업은 필요없어 보입니다!
이부분은 databinding 배우고 다시 해보면 좋을것 같습니다!

2020-01-04 11:11 UTC, zozero94 commented on AhnHyeonho/FirstProject/app/src/main/java/com/hansung/firstproject/data/repository/NaverRepository.kt
> +    fun getInstance(): NaverRepository {
내부함수로 존재한다면 NaverRepository의 getInstance를 부르기 위해서
NaverRepository를 생성해야하는 문제가 발생해서 싱글톤으로 동작하지 않을것 같습니다.
[해당 라인 참고](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/388/files#diff-a0ae0eef3ce8e8e7b83f94eb3b84b557R23)

2020-01-04 11:11 UTC, zojae031 commented on AhnHyeonho/FirstProject/app/src/main/java/com/hansung/firstproject/MainActivity.kt
> +                adapter.addItems(it.items)
```kotlin
adapter.run {
                    addItems(it.items)
                    notifyDataSetChanged()
                }
```
중복은 제거하는게 좋아보여요

2020-01-04 11:11 UTC, zojae031 commented on AhnHyeonho/FirstProject/app/src/main/java/com/hansung/firstproject/MainActivity.kt
> +                Toast.makeText(applicationContext, "인터넷 연결을 확인하세요", Toast.LENGTH_SHORT)
지금은 아니지만 나중에 다중언어 지원을 위해
32,33번 라인처럼 String Resource에 넣어서 가져오는 방법을 추천드려요
[32Line](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/388/files#diff-a0ae0eef3ce8e8e7b83f94eb3b84b557R32)

2020-01-04 11:11 UTC, zojae031 commented on AhnHyeonho/FirstProject/app/src/main/java/com/hansung/firstproject/data/source/remote/NaverRemoteDataSourceImpl.kt
> +    fun getInstance(): NaverRemoteDataSourceImpl {
마찬가지로 싱글톤의 의미가 없어보입니다.

2020-01-04 11:11 UTC, zojae031 commented on AhnHyeonho/FirstProject/app/src/main/java/com/hansung/firstproject/data/MovieResponseModel.kt
> +    val items: ArrayList<MovieModel>
해당 dataClass는 보고서 약간 의아했습니다.
Retrofit으로 데이터를 가져올때 
```kotlin 
Call<MovieResponseModel>
```
형태로 맵핑하는걸 원하신것 같은데
```kotlin 
Call<List<MovieResponseModel>>
```
로 만드는것과 별 차이가 없어보입니다. 이건 취향인것 같아요 :)

2020-01-04 13:39 UTC, AhnHyeonho commented on AhnHyeonho/FirstProject/app/src/main/java/com/hansung/firstproject/data/MovieResponseModel.kt
> +    val items: ArrayList<MovieModel>
현재는 검색결과로 넘어오는 영화리스트만 필요하지만, 추후에 다른 데이터도 필요하게 된다면 해당 데이터 클래스의 맴버로 다른 데이터들을 추가해주는 방식으로 진행해볼 생각이었습니다. 

향후 확장성를 고려한다면 지금 형태가 좋을거라 판단하여 이렇게 작성하였습니다.

2020-01-04 13:40 UTC, AhnHyeonho commented on AhnHyeonho/FirstProject/app/src/main/AndroidManifest.xml
> +        <activity android:name=".MovieInformationActivity"></activity>
간결하게 수정하였습니다.


e006d7a

2020-01-04 13:42 UTC, AhnHyeonho commented on AhnHyeonho/FirstProject/app/src/main/java/com/hansung/firstproject/adapter/MovieHolder.kt
>  class MovieHolder(private val movieView: View) : RecyclerView.ViewHolder(movieView) {
말씀하신대로 BaseViewHolder class와 이를 상속받은 구현체 MovieHolder class로 적용해보았습니다.

e938f0d
b958f47
e1128cb

2020-01-04 13:43 UTC, AhnHyeonho commented on AhnHyeonho/FirstProject/app/src/main/java/com/hansung/firstproject/adapter/MovieHolder.kt
> +            val webIntent = Intent(
첨부해주신 방식이 좀 더 명확하고 간결해보여서 수정해보았습니다.

4d52c04

2020-01-04 13:44 UTC, AhnHyeonho commented on AhnHyeonho/FirstProject/app/src/main/java/com/hansung/firstproject/adapter/RecyclerViewAdapter.kt
> +            holder.bindItems(item)
뷰홀더 변경으로 인하여 수정했습니다.

47da821

2020-01-04 13:45 UTC, AhnHyeonho commented on AhnHyeonho/FirstProject/app/src/main/java/com/hansung/firstproject/adapter/RecyclerViewAdapter.kt
> +        var item = items[position]
바로 아래 리뷰답변을 참고 부탁드립니다.

2020-01-04 13:46 UTC, AhnHyeonho commented on AhnHyeonho/FirstProject/app/src/main/java/com/hansung/firstproject/data/repository/NaverRepository.kt
> +    fun getInstance(): NaverRepository {
내부에 위치한 dataSource의 getInstance부분을 메인액티비티로 옮겨왔습니다. 올바르지 못한 싱글톤 객체였기에 뒤에있는 리뷰에서 수정해보았습니다.

56d6c6a

2020-01-04 13:46 UTC, AhnHyeonho commented on AhnHyeonho/FirstProject/app/src/main/java/com/hansung/firstproject/MainActivity.kt
> +                adapter.addItems(it.items)
수정했습니다.

04571b1

2020-01-04 13:47 UTC, AhnHyeonho commented on AhnHyeonho/FirstProject/app/src/main/java/com/hansung/firstproject/MainActivity.kt
> +                Toast.makeText(applicationContext, "인터넷 연결을 확인하세요", Toast.LENGTH_SHORT)
string resource에 메세지들을 추가하고 이를 불러오는 방식으로 수정해보았습니다.

2b1d5ef

2020-01-04 13:47 UTC, AhnHyeonho commented on AhnHyeonho/FirstProject/app/src/main/java/com/hansung/firstproject/data/source/remote/NaverRemoteDataSourceImpl.kt
> +    fun getInstance(): NaverRemoteDataSourceImpl {
올바른 singleton class 문법으로 수정했습니다.

193f4a0
e28f0e2

2020-01-05 03:04 UTC, seunghee63 approved these changes

2020-01-05 07:33 UTC, sjjeong commented on AhnHyeonho/FirstProject/app/src/main/java/com/hansung/firstproject/data/MovieResponseModel.kt
> +    val items: ArrayList<MovieModel>
@zojae031 
response가 { "items":[] } 라서 이렇게 만들어야 합니다.

2020-01-05 07:43 UTC, sjjeong requested changes

2020-01-05 07:43 UTC, sjjeong commented on AhnHyeonho/FirstProject/app/src/main/java/com/hansung/firstproject/data/repository/NaverRepository.kt
> +    companion object {
companion object는 클래스 내부 맨 아래에 있어야합니다.
NaverRemoteDataSourceImpl도 동일하게 수정해주세요

2020-01-05 07:54 UTC, AhnHyeonho commented on AhnHyeonho/FirstProject/app/src/main/java/com/hansung/firstproject/data/repository/NaverRepository.kt
> +    companion object {
수정하였습니다. 


a72cbc9

2020-01-05 08:29 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-01-05 08:31 UTC, merged