HW-6 MVVM 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #390
Opened 2020-01-01 11:05 UTC by 2giwon

- 기존 Presenter 구현 부분을 viewModel로 전환
- Contract 제거
- BehaviorSubject 로 Observable 적용

2020-01-01 12:43 UTC, sabgilhun commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/tabs/ContentsFragment.kt
> +        viewModel.asSearchQueryListObservable()
ViewModel extension 함수로 열어서 적용하면 반복되는 'viewModel.'을 없앨수 있을거 같네요.
(private로 접근 지정하면 좋을듯)

2020-01-01 14:25 UTC, 2giwon commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/tabs/ContentsFragment.kt
> +        viewModel.asSearchQueryListObservable()
수정했습니다.
이제 맞는지 모르겠네요^^

eaddf526d47d9df9c062108ee4fe0f5dc5980d45

2020-01-01 15:17 UTC, sabgilhun commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/tabs/ContentsFragment.kt
> +        viewModel.asSearchQueryListObservable()
```
private fun ContentsViewModel.subscribeObservables() {
...
}
```

제가 의도를 제대로 파악 한건지 확실하지 않지만 `subscribeObservables` 함수로 옵저버블 구독 로직을 모아둔거로 보여서 위와 같이 private extension을 이용하면 좀 더 간결하게 사용 할 수 있을거 같아 의견 드려봤습니다 ^^

약간 스타일 차이여서 마음에 드시면 적용해보시는게 좋을듯 싶어용

2020-01-01 15:25 UTC, 2giwon commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/tabs/ContentsFragment.kt
> +        viewModel.asSearchQueryListObservable()
이게 더 깔끔하네요
수정했습니다.
fa86b524af30bb6d9ed3038ecda6fa8491148fe0

2020-01-02 13:57 UTC, taeiim commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/tabs/ContentsFragment.kt
>              }
저도 잘은 모르지만..! 
mvvm에서 모든 데이터들은 fragment가 아닌 ViewModel에서 가지고 있어야 하는거 아닌가욤??
etSearch.text를 fragment에서 넘기는게 아니라 
fragment에서는 loadContents() 요청만 하고, viewmodel에서 데이터를 가지고 있다가 처리해야하는게 아닌지요..!

2020-01-02 15:48 UTC, 2giwon commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/tabs/ContentsFragment.kt
>              }
네 모든 데이터는 뷰모델에 있는게 맞습니다. 

그러나 최초 사용자가 입력한 값은 뷰를 통해서 입력이 되기 때문에 
뷰의 데이터를 뷰모델에 보내야 할 것 같습니다.

제가 정확히 이해한 것인지 모르겠지만 다른 의도나 방법이 있으시면 피드백 부탁드립니다.

2020-01-03 12:21 UTC, taeiim commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/tabs/ContentsFragment.kt
>              }
음 two way binding을 이용해서 계속 입력된 값을 viewmodel에서 가지고 있는 것은 어떨까요?
전체적으로 fragment에서 view에 직접 접근해 gettext settext를 하는 방식이 mvvm이 맞는지 잘 모르겠어요..! ㅠㅠ 🤓🤓

2020-01-03 15:05 UTC, 2giwon commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/tabs/ContentsFragment.kt
>              }
저도 정확히 MVVM 을 알고 있는 것은 아니지만,

MVVM은 뷰 -> 뷰모델 -> 모델 이고 반대방향으로는 알지 못하는 것이 맞습니다.

투웨이 바인딩으로 처리를 하려면 옵저버블 필드나 livedata 를 써야 합니다.

현재는 옵저버블 필드나 아니면 바인딩 어댑터로 텍스트 와쳐를 붙여서 만들면 됩니다.

추후에 aac livedata를 배우게 되면 꼭 적용하겠습니다.

그리고 fragment에서 뷰모델에 요청은 하는 것은 맞고 

setText는 BehaviorSubject로 옵저버블 필드로 값을 받는 것이니 뷰모델이 알고 있는 것은 아닙니다.

2020-01-04 03:39 UTC, 2giwon commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/tabs/ContentsFragment.kt
>              }
생각해보니 livedata라고 해서 다른 건 없으니 수정이 가능할 것 같습니다.

수정했습니다.

7b8ed24c8b5344c91c56cd73b55b2ad0cbf08989

2020-01-04 13:41 UTC, taeiim approved these changes

2020-01-05 04:25 UTC, sjjeong requested changes

2020-01-05 04:25 UTC, sjjeong commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/data/NaverDataRepositoryImpl.kt
>              .flatMap { response ->
flatMap말고 doOnSuccess로 처리해보면 어떨까요

2020-01-05 04:25 UTC, sjjeong commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/ext/EditTextExt.kt
> +}
android:text를 사용하면 되지만 학습을 위해서 진행하신건가요?

2020-01-05 04:25 UTC, sjjeong commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/ext/EditTextExt.kt
> +            listener.onChange()
이 부분은 onTextChanged에 있어야 합니다.

2020-01-05 04:25 UTC, sjjeong commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/tabs/ContentsFragment.kt
> +                viewModel.loadContents(tab)
버튼 처리를 xml에서 처리해주세요

2020-01-05 04:25 UTC, sjjeong commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/tabs/ContentsFragment.kt
> +    private fun hideLoading() {
show hide가 ProgressBar에 Visible, Gone 처리 임으로 xml에서 DataBinding으로 처리해주세요

2020-01-05 04:25 UTC, sjjeong commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/tabs/ContentsViewModel.kt
> +    fun asSearchQueryListObservable(): Observable<List<ContentItem>> =
https://kotlinlang.org/docs/reference/properties.html#backing-properties
backing property 개념으로 사용하셨는데 컨벤션이 있습니다 참고만 해주세요

2020-01-05 04:25 UTC, sjjeong commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/tabs/ContentsViewModel.kt
> +    private val searchQueryResultEmptyList: BehaviorSubject<Unit> = BehaviorSubject.create()
View에서 보여주는 입장에서 ResultList가 비어있으면 show, 있으면 hide 해주는 로직이 있으면 됩니다.

2020-01-05 04:25 UTC, sjjeong commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/tabs/ContentsViewModel.kt
> +    private val searchQueryResultEmptyList: BehaviorSubject<Unit> = BehaviorSubject.create()
Rx도 좋지만 ObservableField로 해보면 어떨까요
우리 스터디에서 목표는 DataBinding으로 MVVM 구현하기 입니다.

2020-01-08 03:55 UTC, closed without merging