HW4 - 데이터 캐싱
sjjeong/GoogryAndroidArchitecutreStudy pull request #392
Opened 2020-01-01 15:43 UTC by JayYi

4주차 과제입니다.
검색 결과 local에 저장한 후, 앱 재실행시 최근 검색 결과 보여주는 방법으로 구현하였습니다.

2020-01-02 11:55 UTC, gitpushyj requested changes
수고많으셨습니다~!
전체적으로 코드 포매팅 한 번 해주시면 좋을것 같아요 :D

2020-01-02 11:55 UTC, gitpushyj commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/util/DisposableExt.kt
> +inline fun Disposable.addTo(compositeDisposable: CompositeDisposable) {
inline 함수는 없어도 될것 같은데 넣으신 이유가 있나요~?
그리구 코틀린에서는 보통 이런 종류의 함수를  plusAssingn operator를 이용해 더 직관적으로 하는 만드는것 같아요.
```kotlin
operator fun Disposable.plusAssign(compositeDisposable: CompositeDisposable) {
    compositeDisposable.add(this)
}
```
이렇게요 ㅎㅎ

2020-01-02 11:55 UTC, gitpushyj commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/ui/movie/MoviePresenter.kt
> +    }
제가 Rx를 사용했었을 때는 주로
```kotlin
disposables += loadImageSearchHistory(
            keyword = lastKeyword
        ).subscribe({
            view.updateUi(it.first, it.second)
        }, { e ->
            val message = e.message ?: return@subscribe
            Log.e("image", message)
        })
```
이런 형태로 사용했었는데 순서가 바뀌니 새롭네요 이건 취향 차이라고 봐야할까요 ㅎㅎ

2020-01-02 11:55 UTC, gitpushyj commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/ui/movie/MoviePresenter.kt
> +        }
여기도 singleIoMainThread()를 compose할 수 있지 않나요??

2020-01-02 11:55 UTC, wooooooak commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/ui/kin/KinFragment.kt
> +        presenter.subscribe()
어떠한 객체에게 메세지를 전달할 때, 메세지 이름만 봐도 어떤 역할을 하는지 명확해야 한다고 생각하는데
presenter 객체에게 "구독해라"라고만 메세지를 전달하니 코드를 처음 보는 입장에서는 조금 모호한것 같습니다..
subscribe 함수를 타고 들어가니 캐싱된 데이터를 불러오는 기능을 하는것 같은데요, 이에 걸맞는 이름으로 만드는게 어떨까요?
혹시 추후 생길 여러 기능 확장성을 고려한 네이밍이었다면, initData 정도도 괜찮을것 같구요!

2020-01-02 11:55 UTC, wooooooak commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/ui/kin/KinPresenter.kt
> +            }
map은 단순히 mapping을 하는 목적을 가져야 하는데 현재는 많은 기능들이 있는 것 같습니다.
getKin(), clearKinResult(), saveKinResult(), saveKinKeyword() 등이 모두 비동기이고 이들의 순서가 보장되어야 한다면 flatMap정도를 사용해서  가독성을 높이는게 좋을것 같아요! 
최근에 코루틴만 쓰다보니 rx를 이쁘게 쓰는 방법을 많이 까먹었네요ㅠㅠㅋㅋ

2020-01-02 11:55 UTC, wooooooak commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/ui/image/ImagePresenter.kt
> +    }
```kotlin
private fun loadImageSearchHistory(keyword: String) = if (keyword.isBlank()) {
        Single.just(Pair(keyword, emptyList()))
    } else {
        repository.getLatestImageResult()
            .compose(singleIoMainThread())
            .map { Pair(keyword, it) }
    }
```
이렇게 작성하면 좀더 코틀린답게 명료할 것 같아요!

2020-01-02 11:55 UTC, wooooooak commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/util/BooleanExt.kt
> +    if (this) action() else {}
if문을 식으로 사용하고 있기 때문에 아무것도 하지 않는 else문 보다는 Unit을 반환하는 else가 더 좋을 것 같습니다.
(아마 컴파일러가 경고성 문구를 띄워줬을것 같은데 아닌가요...ㅎㅎ)

2020-01-02 11:55 UTC, wooooooak commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/ui/BaseSearchPresenter.kt
> +    }
BaseSearchPresenter를 구현하는 클래스에서 사용하는 subscribe만으로도 충분해 보였는데 혹시 어떤 의도로 BaseSearchPresenter에도 넣으신건가요~?

2020-01-02 11:55 UTC, wooooooak commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/data/source/local/NaverSearchLocalDataSourceImpl.kt
> +        TODO("not implemented") //To change body of created functions use File | Settings | File Templates.
여기 있는 TODO 들은 아직 미구현인건가요? ㅎㅎ

2020-01-02 11:55 UTC, wooooooak commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/data/source/local/NaverSearchLocalDataSourceImpl.kt
> +        context.getSharedPreferences("search_history", Context.MODE_PRIVATE)
PREFS_NAME 상수를 깜빡하신거죠?ㅎㅎ

2020-01-02 12:37 UTC, JayYi commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/ui/movie/MoviePresenter.kt
> +    }
단지 extenstion을 사용한거라 동일한 코드입니다.

2020-01-02 12:42 UTC, JayYi commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/ui/kin/KinFragment.kt
> +        presenter.subscribe()
보통  presenter를 subscribe/unsubscribe 아니면  start/stop같은 패턴으로 많이 하더라구요. 저도 자세한 의미는 모르지만 view 가 presenter에게 update할 준비가 되어서 구독(직역이라..정확한 의미는 모르겠지만)하겠다는 의미로 통상적으로 사용하는 함수명으로 알고 있습니다.

2020-01-02 13:23 UTC, JayYi commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/util/DisposableExt.kt
> +inline fun Disposable.addTo(compositeDisposable: CompositeDisposable) {
우선 제가 아는 내용을 공유 드리자면, 
`
loadMovieSearchHistory(
            keyword = lastKeyword
        )
            .subscribe({
                view.updateUi(it.first, it.second)
            }, { e ->
                val message = e.message ?: return@subscribe
                Log.e("movie", message)
            })
            .addTo(disposables)
`
저는 disposlabe += ....와 같은 코드 보단 위와 같이 코드를 사용하는 것을 선호하여서 해당 코드와 같이 extension을 선안했어요. 그리고, 보통은 아래와 같이 코드도 선언하기도 합니다.
`
fun Disposable.addTo(compositeDisposable: CompositeDisposable) = 
    apply { compositeDisposable.add(this) }
`
위 코드에 보시면 고차 함수 형태의 코드(apply 에 compositeDisposable 추가 하는 함수 자체를 파라미터로 전달)로 되어 있습니다. 고차 함수를 사용할 때 inline을 선언하면 런타임 성능에 도움을 준다고하여 inline으로 선언했습니다.

2020-01-02 13:32 UTC, JayYi commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/data/source/local/NaverSearchLocalDataSourceImpl.kt
> +        TODO("not implemented") //To change body of created functions use File | Settings | File Templates.
최근 기록을 삭제 하는 기능을 구현할 때 구현하려고 선언했는데, 이번 과제 할 때 기능을 구현하지 못해서요. 추후 구현 예정입니다.

2020-01-02 13:41 UTC, JayYi commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/ui/BaseSearchPresenter.kt
> +    }
의도는 없습니다. 단지 subscribe/unsubscribe의 쌍을 맞추는데 습관이 들다 보니 선언하게 되었습니다.

2020-01-02 13:43 UTC, JayYi commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/ui/BaseSearchPresenter.kt
> +    }
수정했습니다. 
d71901770d8f560c9353a2a080e922320077f977

2020-01-02 13:43 UTC, JayYi commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/data/source/local/NaverSearchLocalDataSourceImpl.kt
> +        context.getSharedPreferences("search_history", Context.MODE_PRIVATE)
실수....ㅋㅋㅋㅋㅋ
수정했습니다.
d71901770d8f560c9353a2a080e922320077f977

2020-01-02 13:45 UTC, JayYi commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/util/BooleanExt.kt
> +    if (this) action() else {}
컴파일러가 경고성 문구를 띄어줘서 선언한 것 맞아요.
근데 한가지 궁금한 점은  {} 선언과 unit으로 반환하는 것이 더 좋을 것 같다고 하셨는데 이유가 있을까요?

2020-01-02 13:50 UTC, JayYi commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/ui/movie/MoviePresenter.kt
> +        }
수정했습니다.
5751cde5d54bc097463f3718b4da7e71f7e054f2

2020-01-02 14:06 UTC, JayYi commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/ui/image/ImagePresenter.kt
> +    }
필요 없는 코드가 포함되어 있어서 다르게 수정했습니다.
dcc5e7bdcaf62ef1f9a9d39c1ba15d6f0149f3f5

개인적으로 궁금한 점이 있어요. 회사에서 주로 return ... , = 을 사용하는 패턴 2개다 사용하고 있어요. 제가 사용한 코드도 코틀린에서만 사용한거라 저는 보통 return을 이용해요. = 을 사용하는 경우는 한줄 안에 끝나는 코드일 때 사용하자는 저 나름의 기준이 있는데, 용준님은 주로 = 을 사용하는 패턴을 사용하시는지요? 이유가 있을까요?

2020-01-02 15:18 UTC, JayYi commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/ui/kin/KinPresenter.kt
> +            }
수정했습니다.
98ae6f308b2d70e59859ecbc5f8bb30ac6f515bd

2020-01-03 02:03 UTC, wooooooak commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/ui/image/ImagePresenter.kt
> +    }
아 저는 if문이 식으로 쓰여서 그 값을 바로 리턴하기만 하는 함수라면 항상 = 를 사용합니다!
코틀린에서 자바와는 다르게 if문을 식으로 사용할 수 있게 해준 이유가 간단 명확 인 것 같아서.... 가급적이면 코틀린에서 제공해주는 문법을 많이 사용하려고 하구 있어요.
이전에 리뷰로 남긴 plusAssign operator 확장 같은 경우도 코틀린에서 제공해주는 기능이기 때문에 가급적 코틀린 적으로 코드 짜려고 노력하고 있어요ㅠㅠ

하지만 이건 취향차이겠죠 ㅎㅎ

2020-01-03 02:18 UTC, wooooooak commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/ui/kin/KinPresenter.kt
> +            }
flatMap 세 개 정도가 이어지는 형태로 나올것으로 생각했는데 아니군요 ㅎㅎㅎ 
이것도 색다르네요!

2020-01-03 02:45 UTC, wooooooak commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/util/DisposableExt.kt
> +inline fun Disposable.addTo(compositeDisposable: CompositeDisposable) {
inline함수는 고차함수의 파라미터로 람다식을 받을때 의미가 있습니다. 지금의 함수에서는 inline을 선언하는 것과 선언 하지 않은 것의 차이가 없는 것 같아요.

2020-01-03 02:55 UTC, wooooooak commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/util/BooleanExt.kt
> +    if (this) action() else {}
기능에는 문제가 없겠지만.. if문을 식으로 사용할 때는 무언가를 반환하려고 하는게 목적이라, 아무 기능이 없다면 if의 반환타입과 동일한 Unit타입을 반환하는게 맞을 것 같다는 생각이 들었어요(개인적으로ㅎㅎ).

예를 들어 아래처럼 고차함수의 파라미터가 String을 반환하는 함수를 받았다면
```kotlin
fun Boolean.then2(action: () -> String): Any =
    if(this) action() else {}
```
이렇게 될텐데, 이것 보다는
```kotlin
fun Boolean.then2(action: () -> String): String or String? =
    if(this) action() else "" or null
```
이렇게 작성하는 것이 반환값이 Any가 되지 않고 String 또는 String?처럼 명확하게 되기 때문에요 ㅎㅎ

이건 꼭 변경하지 않으셔두 되고 눈에 더 익으신대로 놔두셔도 될것 같습니다!

2020-01-03 03:07 UTC, JayYi commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/util/DisposableExt.kt
> +inline fun Disposable.addTo(compositeDisposable: CompositeDisposable) {
저도 스택오버플로우를 보고 고친건데 예전이라 기억이 안나지만 disposable이 observable 함수를 포함하고 있어서가 아닐까....하네요

2020-01-03 03:08 UTC, JayYi commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/ui/kin/KinPresenter.kt
> +            }
디비 집근함수들이 completable이라 연속으로 flatmap으로 하기 힘들다고 생각이 들더라구요
그래서 방법을 찾다찾다 찾은 방법이 andthen이였어요

2020-01-03 04:11 UTC, minjae2 commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/util/DisposableExt.kt
> +inline fun Disposable.addTo(compositeDisposable: CompositeDisposable) {
스택오버 플로우가 아니였군요. RxKotlin 이였네요. 정식으로 반영된건 아닌데,
https://github.com/ReactiveX/RxKotlin/issues/202
이분의 의견을 듣고 고친거였어요.
원래 코드는 아래와 같습니다.
https://github.com/ReactiveX/RxKotlin/blob/2.x/src/main/kotlin/io/reactivex/rxkotlin/disposable.kt

2020-01-03 04:12 UTC, JayYi commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/util/DisposableExt.kt
> +inline fun Disposable.addTo(compositeDisposable: CompositeDisposable) {
스택오버 플로우가 아니였군요. RxKotlin 이였네요. 정식으로 반영된건 아닌데,
https://github.com/ReactiveX/RxKotlin/issues/202
이분의 의견을 듣고 고친거였어요.
원래 코드는 아래와 같습니다.
https://github.com/ReactiveX/RxKotlin/blob/2.x/src/main/kotlin/io/reactivex/rxkotlin/disposable.kt

2020-01-03 08:25 UTC, wooooooak commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/util/DisposableExt.kt
> +inline fun Disposable.addTo(compositeDisposable: CompositeDisposable) {
으음.... 저분의 의견이 맞는건가...싶은 생각이 들긴 하는데......
요건 다른분들의 생각도 궁금하네요 ㅎㅎㅎ
수고하셨어요!

2020-01-03 08:27 UTC, gitpushyj approved these changes

2020-01-04 06:44 UTC, sjjeong requested changes
오늘 말씀드린 내용 반영해주세요

2020-01-05 07:53 UTC, JayYi commented
@sjjeong 님,
리뷰 반영했습니다

[리뷰 반영] Presenter 내 검색 결과 저장 logic repository로 이동
b4b1709ae21832c87f85ef7187c919241bf77346

추가로, Repository DTO, DataLocalSource DTO 분리 하여서 적용했습니다.
49017f13cf7ff50b6973fcc8f1a774a50536b6f5
1d616b8428096f75ca67d6cbc5d35250e2693574

2020-01-07 13:08 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-01-07 14:06 UTC, merged