HW2-Model적용. Class07/swppppp
sjjeong/GoogryAndroidArchitecutreStudy pull request #393
Opened 2020-01-01 16:01 UTC by swppppp

이전 코드 리팩토링 및
모델 적용

2020-01-02 01:09 UTC, 172900 commented
머지 리퀘스트 대상 브랜치를 StudyFork:master가 아닌 StudyFork:class07/swppppp로 해주세요.

2020-01-02 01:10 UTC, 172900 reviewed
머지 리퀘스트 대상 브랜치를 StudyFork:master가 아닌 StudyFork:class07/swppppp로 해주세요.

2020-01-02 07:49 UTC, swppppp commented
> 머지 리퀘스트 대상 브랜치를 StudyFork:master가 아닌 StudyFork:class07/swppppp로 해주세요.

흐어정신머리봐ㅠㅠ바꿨습니다!!

2020-01-02 10:57 UTC, 172900 requested changes

2020-01-02 10:57 UTC, 172900 commented on swppppp/app/src/main/java/com/siwon/prj/ui/MainActivity.kt
> +//    }
안 쓰는 주석처리 지워주세요~

2020-01-03 01:13 UTC, swppppp commented on swppppp/app/src/main/java/com/siwon/prj/ui/MainActivity.kt
> +//    }
4ecbbc5

2020-01-03 01:14 UTC, swppppp commented on swppppp/app/src/main/java/com/siwon/prj/ui/MainActivity.kt
> +//    }
주석제거까지했습니다~!

2020-01-03 01:17 UTC, 172900 approved these changes
잘하셨어요!

2020-01-04 07:43 UTC, sjjeong requested changes

2020-01-04 07:43 UTC, sjjeong commented on swppppp/app/src/main/java/com/siwon/prj/MovieHolder.kt
> +        setOnClickListener { clickListener(item.link) }
listener는 bind 시점이 아니라 ViewHolder 가 생성 될 때 해주세요

2020-01-04 07:43 UTC, sjjeong commented on swppppp/app/src/main/java/com/siwon/prj/datasource/MovieSearchDataSource.kt
> +class MovieSearchDataSourceImpl : MovieSearchDataSource {
class MovieSearchRemoteDataSourceImpl : MovieSearchRemoteDataSource {

Remote 단어를 추가해주세요

2020-01-04 07:43 UTC, sjjeong commented on swppppp/app/src/main/java/com/siwon/prj/ui/MainActivity.kt
> +    lateinit var mAdapter: MovieAdapter
m prefix 제거해주세요

2020-01-04 07:43 UTC, sjjeong commented on swppppp/app/src/main/java/com/siwon/prj/ui/MainActivity.kt
> +                movieListRv.adapter = mAdapter
adapter는 한번만 set 해주면 됩니다.

2020-01-05 05:31 UTC, swppppp commented on swppppp/app/src/main/java/com/siwon/prj/datasource/MovieSearchDataSource.kt
> +class MovieSearchDataSourceImpl : MovieSearchDataSource {
7266f5cc

2020-01-05 05:32 UTC, swppppp commented on swppppp/app/src/main/java/com/siwon/prj/ui/MainActivity.kt
> +    lateinit var mAdapter: MovieAdapter
bc7e74d0

2020-01-05 05:32 UTC, swppppp commented on swppppp/app/src/main/java/com/siwon/prj/ui/MainActivity.kt
> +                movieListRv.adapter = mAdapter
cbc37d0a

2020-01-05 05:32 UTC, swppppp commented on swppppp/app/src/main/java/com/siwon/prj/MovieHolder.kt
> +        setOnClickListener { clickListener(item.link) }
7482eed2

2020-01-05 05:33 UTC, swppppp commented
코멘트달아주신부분 수정하였습니다!!

2020-01-05 07:50 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-01-05 08:16 UTC, merged