HW-1 네이버 영화 검색
sjjeong/GoogryAndroidArchitecutreStudy pull request #398
Opened 2020-01-04 09:38 UTC by Minoyam

2020-01-05 09:41 UTC, YKW93 commented
1. 통신 할때 rxjava를 사용하셨는데 혹시 Single 말고 Observable을 사용한 이유가 있을까요?
2. CompositeDisposable을 사용하셨는데 메모리 할당 해제? 가 필요 같습니다!

추가적으로 통신 작업할때 progress bar show/hide 작업을 doOnTerminate, doOnSubscribe() 함수를 사용하는게 더 깔끔하고 좋을꺼같습니다.

2020-01-06 12:01 UTC, Minoyam commented
RxJava를 아직 잘 몰라서 Observable 밖에 사용을 안해봐가지고 Single의 존재를 모르고 있었습니다
clear()를 깜빡해서 추가하려고 생각하고 있었는데 광우님이 한발 빠르셨네요 ㅠㅠ
doOnTerminate, doOnSubscribe() 함수에 대해서도 새롭게 알아갑니다.
감사합니다!
4f942c1

2020-01-07 14:06 UTC, sjjeong requested changes

2020-01-07 14:06 UTC, sjjeong commented on class08/Minoyam/app/src/main/java/com/cnm/homework/ui/MainActivity.kt
> +            if (et_movie_search.text.toString() != "") {
isNotEmpty 함수를 사용해보세요

2020-01-07 14:06 UTC, sjjeong commented on class08/Minoyam/app/src/main/java/com/cnm/homework/ui/MainActivity.kt
> +        disposable.clear()
super.onDestroy 보다 먼저 호출 되어야 합니다

2020-01-07 14:06 UTC, sjjeong commented on class08/Minoyam/app/src/main/java/com/cnm/homework/ui/MainActivity.kt
> +            .compose {
compose를 사용하지 않아도 됩니다.

2020-01-07 14:06 UTC, sjjeong commented on class08/Minoyam/app/src/main/java/com/cnm/homework/ui/MovieAdapter.kt
> +        fun Bind(movieItem: NaverResponse.Item) {
함수는 소문자로 시작 해야 합니다

2020-01-08 10:43 UTC, Minoyam commented
수정사항 반영 했습니다
a206646

2020-01-08 15:16 UTC, sjjeong approved these changes
앞으로 수정은 1코멘트에 1커밋이고 코멘트마다 어떤내용 수정했는지 커밋아이디 남겨주세요

2020-01-08 15:16 UTC, sjjeong commented
@YKW93 
Mentor Needed를 추가하실땐 approve 해주셔야 합니다.

2020-01-09 02:55 UTC, Minoyam commented
@sjjeong 
넵 알겠습니다.

2020-01-09 06:16 UTC, YKW93 approved these changes

2020-01-09 06:17 UTC, merged