Class01/sabgilhun
sjjeong/GoogryAndroidArchitecutreStudy pull request #40
Opened 2019-05-28 06:26 UTC by sabgilhun

2019-05-31 10:15 UTC, GongSulMin requested changes

2019-05-31 10:15 UTC, GongSulMin commented on sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/view/coinlist/CoinListViewModel.kt
> +    val coinListListeners = mutableListOf<((List<Ticker>?) -> Unit)?>()
리스너를 `mutableList` 로 하셨는데 따로 이유가 있으신가요 ??

2019-05-31 10:15 UTC, GongSulMin commented on sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/view/searchcoin/SearchCoinViewModel.kt
> +        if (disposables.size() == 0 && currentCoin != "") {
`isNotBlank` 로 하셔도 될거같습니다 !

2019-05-31 17:16 UTC, sjjeong requested changes
새벽 2시에 한 거 라서 이상한게 있을 수도 있으니 이상한게 보이면 답변 달아주세요.

2019-05-31 17:16 UTC, sjjeong commented on sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/view/home/HomeViewModel.kt
> +        showToastEventListeners.map { it?.invoke(message) }
이 코드는 map 보다는 for가 더 어울릴것 같습니다.

2019-05-31 17:16 UTC, sjjeong commented on sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/view/searchcoin/SearchCoinActivity.kt
> +            searchCoinViewModel.searchCoin(binding.etKeyword.text.toString())
binding.etKeyword에 있는 값은 ViewModel이 가지고 있어야 합니다.
etKeyword가 TextWatcher 달아서 ViewModel에 데이터를 two-way binding해주시고
여기서는 searchCoinViewModel.searchCoin()정도만 있으면 됩니다.

2019-05-31 17:16 UTC, sjjeong commented on sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/view/searchcoin/SearchCoinViewModel.kt
> +        if (disposables.size() == 0 && currentCoin != "") {
``` kotlin
if (disposables.isEmpty() && currentCoin.isNotEmpty()) { ... }
```

2019-05-31 17:16 UTC, sjjeong commented on sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/view/searchcoin/SearchCoinViewModel.kt
> +    val showToastEventListeners = mutableListOf<((String) -> Unit)?>()
왜 nullable한 고차함수로 하셨나요?

2019-06-01 07:01 UTC, sabgilhun commented on sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/view/coinlist/CoinListViewModel.kt
> +    val coinListListeners = mutableListOf<((List<Ticker>?) -> Unit)?>()
ViewModel에 View가 여러개 붙을때를 생각해서 했는데.. 의미가 없네요 ㅎㅎ

2019-06-01 08:43 UTC, sabgilhun commented on sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/view/searchcoin/SearchCoinViewModel.kt
> +        if (disposables.size() == 0 && currentCoin != "") {
``` kotlin
if (disposables.isEmpty() && currentCoin.isNotBlank()) {
```
이렇게 변경 했습니다.  CompositeDisposable클래스에 isEmpty가 없어서 확장함수로 구현하여 사용하였습니다. 

실수로 커밋이 섞여서 이렇게 답변합니다. ㅜㅜ

2019-06-01 08:43 UTC, sabgilhun commented on sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/view/home/HomeViewModel.kt
> +        showToastEventListeners.map { it?.invoke(message) }
넵 수정하였습니다. 그런데 map과 for의 차이가 어떤건가요.. 찾아봐도 잘 안나오네요

2019-06-01 08:45 UTC, sabgilhun commented on sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/view/searchcoin/SearchCoinActivity.kt
> +            searchCoinViewModel.searchCoin(binding.etKeyword.text.toString())
``` kotlin
        binding.tvSearch.setOnClickListener {
            searchCoinViewModel.searchCoinByKeyword()
        }

        binding.etKeyword.setTextChangeListener {
            searchCoinViewModel.keyword = it
        }
```

이런식으로 변경하였습니다.

2019-06-01 08:47 UTC, sabgilhun commented on sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/view/searchcoin/SearchCoinViewModel.kt
> +    val showToastEventListeners = mutableListOf<((String) -> Unit)?>()
리스너가 없는 경우도 수용하려고 nullable 했던건데, 제가 비어 있는 List가 null이라고 착각했습니다...
수정했습니다.

2019-06-08 14:19 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-06-09 02:08 UTC, GongSulMin approved these changes

2019-06-09 02:09 UTC, merged