HW-5 databinding 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #401
Opened 2020-01-04 15:59 UTC by taeiim

recyclerViewAdapter 안에 주석 처리된 코드들은 일단 무시해주세요ㅜㅜ !!

2020-01-05 13:19 UTC, 2giwon requested changes

2020-01-05 13:19 UTC, 2giwon commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/base/BaseFragment.kt
> +) : Fragment(layoutResId) {
여기서 레이아웃 아이디를 넘겨서 인플레이트를 하는데 밑에 onCreateView에서 인플레이트를 한번더 해주고 있습니다.

둘 중 하나만 해주면 될 것 같습니다.

2020-01-05 13:19 UTC, 2giwon commented on taeiim/MyApplication/app/src/main/res/layout/activity_main.xml
> +                app:layout_constraintBottom_toTopOf="@+id/bottomNavigation"
아이디를 정의 하는 것이 아니라면 + 기호는 빠져도 될 것 같습니다.

2020-01-05 13:19 UTC, 2giwon commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/base/BaseRecyclerAdapter.kt
> +open class BaseRecyclerAdapter<ITEM : Any, B : ViewDataBinding>(
Any라면 : Any를 제거 해도 좋을 것 같습니다.

2020-01-05 13:19 UTC, 2giwon commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/ContentsFragment.kt
> +        binding.fg = this
adapter를 xml 레이아웃에서 데이터 바인딩으로 넣어 주기 위해서 프레그먼트 전체를 넘겨 주는 것 같은데 좋지 않은 방식 같습니다.

꼭 모든 것을 데이터 바인딩으로 할 필욘 없을 거 같습니다. 학습을 위해서 넣으신 건가요?

2020-01-05 13:19 UTC, 2giwon commented on taeiim/MyApplication/app/src/main/res/layout/fragment_main.xml
> +                android:adapter="@{fg.searchResultAdapter}"
android:adapter라는 attribute는 없는 것으로 알고 있습니다. 동작하지 않을 것 같은데 확인 부탁드립니다.

2020-01-05 14:20 UTC, taeiim commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/base/BaseFragment.kt
> +) : Fragment(layoutResId) {
수정했습니다. 감사합니다 ㅎㅎ

commit : 9712294364801f65d8c4da7b43d0680b43e8f1a6

2020-01-05 14:20 UTC, taeiim commented on taeiim/MyApplication/app/src/main/res/layout/activity_main.xml
> +                app:layout_constraintBottom_toTopOf="@+id/bottomNavigation"
수정했습니다.

commit : e2d40b112b05a7cefcffa032e5cebccc771b4587

2020-01-05 14:21 UTC, taeiim commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/base/BaseRecyclerAdapter.kt
> +open class BaseRecyclerAdapter<ITEM : Any, B : ViewDataBinding>(
제거했습니다 ㅎㅎ 
commit : d637510dc73ddbf4e1464d45adcb8d2a61d97c83

근데 Any를 제거해도 동작이 잘 되는 이유가 뭔가요??

2020-01-05 14:21 UTC, taeiim commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/ContentsFragment.kt
> +        binding.fg = this
제거했습니다. 감사합니다! 

commit : 5df9ff7b1e6fad78fe42278aa1776232ce65585e

2020-01-05 14:22 UTC, taeiim commented on taeiim/MyApplication/app/src/main/res/layout/fragment_main.xml
> +                android:adapter="@{fg.searchResultAdapter}"
제거했습니다 ㅎㅎ 

commit : 5df9ff7b1e6fad78fe42278aa1776232ce65585e

2020-01-05 14:43 UTC, 2giwon commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/base/BaseRecyclerAdapter.kt
> +open class BaseRecyclerAdapter<ITEM : Any, B : ViewDataBinding>(
Any가 최상위 타입이라서 그렇습니다. 자바의 Object와 같은 타입이라고 알고 있습니다

2020-01-05 14:45 UTC, 2giwon approved these changes
수고하셨습니다.

2020-01-07 14:29 UTC, sjjeong requested changes
미사용 주석 제거 해주세요

2020-01-07 14:29 UTC, sjjeong commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/base/BaseActivity.kt
> +) : AppCompatActivity(layoutResId) {
layoutResId를 생성자로 넘기면 setContentView가 2번 됩니다.

2020-01-07 14:29 UTC, sjjeong commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/base/BaseRecyclerAdapter.kt
> +    protected fun getItem(position: Int): ITEM? = items.getOrNull(position)
사용하는 곳이 없긴하지만
nullable보단 nonnull로 만드는게 좋을 것 같아요

2020-01-07 14:29 UTC, sjjeong commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/BindingAdapter.kt
> +fun ImageView.loadUrl(url: String?) {
GlideExt에 있는 함수를 여기로 이동해서 사용하면 될 것 같습니다.

2020-01-07 14:29 UTC, sjjeong commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/ContentsPresenter.kt
> +    }
searchType은 Tabs로 받으면 됩니다.
searchResult.items.map{} 한번으로 해결 될 것 같습니다.

2020-01-08 18:00 UTC, taeiim commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/base/BaseActivity.kt
> +) : AppCompatActivity(layoutResId) {
수정했습니다 ~! 감사합니다.

commit : 74411028ecc68b804afa9ec0a4745c34e11fd64f

2020-01-08 18:01 UTC, taeiim commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/base/BaseRecyclerAdapter.kt
> +    protected fun getItem(position: Int): ITEM? = items.getOrNull(position)
null이면 throwable을 던지도록 수정했는데 괜찮을까요?

commit : d032b8c7c75e64620e712238f24fd614a49cbee3

2020-01-08 18:01 UTC, taeiim commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/BindingAdapter.kt
> +fun ImageView.loadUrl(url: String?) {
수정했습니다 

commit : c3b5284fe74886929ed02b64804ae5d8102bb410

2020-01-08 18:02 UTC, taeiim commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/ContentsPresenter.kt
> +    }
searchType을 Tabs로 넣는 작업은 반영했습니다. 
commit : 98a4d630a0db31a9fc8f26775a5f0298d255860f

근데 map을 한 번만 쓰는 방법은 잘 모르겠네요 ㅜㅜ 어떤 방식으로 해야하는지 좀 더 자세히 설명해주실 수 있나요?

2020-01-09 11:51 UTC, sjjeong commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/base/BaseRecyclerAdapter.kt
> +    protected fun getItem(position: Int): ITEM? = items.getOrNull(position)
그냥 items[position] 하면 됩니당

2020-01-09 11:52 UTC, sjjeong requested changes
merge commit 만들어주세요

2020-01-09 12:52 UTC, taeiim commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/base/BaseRecyclerAdapter.kt
> +    protected fun getItem(position: Int): ITEM? = items.getOrNull(position)
그냥 items[position] 으로 하면  position 잘못 요청했을 때 indexOutOf 에러 안생기나용??

2020-01-09 13:06 UTC, sjjeong commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/base/BaseRecyclerAdapter.kt
> +    protected fun getItem(position: Int): ITEM? = items.getOrNull(position)
Exception이 발생하는데 보통 position이 넘는 값을 넣는 경우는 없죠
특히 Adapter내부라면..

2020-01-09 13:06 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-01-09 13:11 UTC, merged