HW-6-ViewModel적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #402
Opened 2020-01-05 04:18 UTC by ironelder

Presenter제거 및 ViewModel적용

2020-01-05 07:03 UTC, bean628 commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/view/mainview/MainFragment.kt
>      }
MainViewModel 생성할때  .apply를 이용해서 하시면  it?.  와 같이 널값을 체크하지 않아도 될것 같습니다~!

2020-01-05 07:10 UTC, ironelder commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/view/mainview/MainFragment.kt
>      }
수정하였습니다~

3ef0da4

2020-01-05 07:12 UTC, bean628 commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/view/mainview/MainFragment.kt
>      }
바인딩 변수에 있는 뷰모델 말고 처음에 바인드할때 생성하는곳에서 하는거 어떤가요??

2020-01-05 07:15 UTC, ironelder commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/view/mainview/MainFragment.kt
>      }
뷰모델 선언시 apply를 통해서 초기 설정을 하도록 수정하였습니다~

81066f3

2020-01-07 14:39 UTC, sjjeong requested changes

2020-01-07 14:39 UTC, sjjeong commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/view/mainview/MainFragment.kt
> +        binding.lifecycleOwner = this@MainFragment
이 부분은 base로 빼면 좋습니다
또한 Fragment는 viewLifeCyclerOwner를 사용하는게 좋습니다.

2020-01-07 14:39 UTC, sjjeong commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/view/mainview/MainFragment.kt
> +                    searchWithAdapter(
searchQuery를 observe하고 여기서 다시 searchWithAdapter를 호출할 필요 없이
ViewModel 내부에서 처리해주시면 됩니다.

2020-01-07 14:39 UTC, sjjeong commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/view/mainview/MainFragment.kt
> +                })
아무 동작하지 않는 코드입니다. 제거해주세요

2020-01-07 14:39 UTC, sjjeong commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/view/mainview/MainFragment.kt
> +
이 코드는 필요 없습니다.
내부적으로 ViewModel의 onCleared를 호출합니다.

2020-01-07 14:47 UTC, BeokBeok commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/view/mainview/MainFragment.kt
> +        binding.lifecycleOwner = this@MainFragment
[5 common mistakes when using Architecture Components](https://proandroiddev.com/5-common-mistakes-when-using-architecture-components-403e9899f4cb) 의 
`1. Leaking LiveData observers in Fragments` 참고하시면 좋을 것 같아요.

2020-01-08 10:13 UTC, ironelder commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/view/mainview/MainFragment.kt
> +        binding.lifecycleOwner = this@MainFragment
lifeCycleOwner를 Base로 옮기고 viewLifeCycleOwner를 사용하고, 선언 위치를 onActivityCreated로 옮겼습니다

b3c9236

2020-01-08 10:14 UTC, ironelder commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/view/mainview/MainFragment.kt
> +                })
제거하였습니다~
aa1fbdf

2020-01-08 10:14 UTC, ironelder commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/view/mainview/MainFragment.kt
> +
해당 코드 제거하였습니다

aa1fbdf
936910f

2020-01-08 10:16 UTC, ironelder commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/view/mainview/MainFragment.kt
> +                    searchWithAdapter(
@sjjeong 
searchQuery를 제거하였습니다.
다만 ViewModel내부에서 처리하는 의미를 잘 모르겠습니다.

검색어 버튼 클릭하여 summit이 들어왔을때 searchWithAdapter을 호출하고 
ViewModel에서 searchQuery의 변수 값을 참조하여 사용하도록 수정하였는데
이게 맞는지 모르겠습니다

fba3558

2020-01-08 16:02 UTC, sjjeong requested changes
1. SearchResultDatabase에 SearchResultDao함수가 대문자로 시작하고 있습니다. 소문자로 시작하고 동사로 시작하게 해주세요
2. MainActivity에서 PagerAdapter가 미사용되고 있으니 제거 해주세요 
3. todo 처리 해주세요
4. reformat code 해주세요. 사용되지 않는 import제거와 코드 재정렬이 필요합니다.
5. Repository에서 LocalDataSource를 사용하지 않고 room database에 직접 접근하고 있습니다. LocalDataSource를 사용하게 변경해주세요

2020-01-08 16:02 UTC, sjjeong commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/view/mainview/MainViewModel.kt
>          searchResultDatabase: SearchResultDatabase?
SearchResultDatabase#getInstance에서 nullable로 오다보니 이와 관련된 코드들이 전부다 Nullable로 처리되고 있습니다.
getInstance를 nonnull로 변경하는게 좋을 것 같습니다.

2020-01-08 16:02 UTC, sjjeong commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/view/mainview/MainViewModel.kt
> +            searchQuery.value,
getRemoteSearchData의 파라미터로 nullable를 받지 마시고 앞에서 null handling을 해주신 다음 nonnull로 전달해주세요

2020-01-08 16:02 UTC, sjjeong commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/view/mainview/MainFragment.kt
> +                    context?.applicationContext ?: (activity as Context).applicationContext
activity도 nullable이기 때문에 as로 type casting하면 null 이어서 죽습니다. as?로 처리 하셔야 합니다.

2020-01-09 10:58 UTC, ironelder commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/view/mainview/MainViewModel.kt
>          searchResultDatabase: SearchResultDatabase?
SearchResultDatabase를 nonnull로 수정하였습니다

0b815d5

2020-01-09 10:58 UTC, ironelder commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/view/mainview/MainViewModel.kt
> +            searchQuery.value,
검색어 부분을 NonNull로 받도록 수정하였습니다.
0b7d8e0

2020-01-09 11:02 UTC, ironelder commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/view/mainview/MainFragment.kt
> +                    context?.applicationContext ?: (activity as Context).applicationContext
해당 부분을 수정하였습니다
6440e40

@sjjeong 
수정하면서 activity를 as?로 하게 되면 뒤에 따라오는 applicationContext쪽에도 ? 를 붙여야 하는데 Room의 경우에는 applicationContext가 필요합니다.
앱 최초에 MainApplication에서 initialize함수를 선언하여 해당 부분을 이미 선언하고 있기는 합니다.
따라서 SearchResultDatabase 클래스에 
```
fun getInstance():SearchResultDatabase = INSTANCE!!
```
위와 같은 함수를 하나 더 추가해서 그냥 Instance만 받아와서 넘겨주도록 해야할지 잘 모르겠습니다

2020-01-09 11:54 UTC, sjjeong commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/view/mainview/MainFragment.kt
> +                    context?.applicationContext ?: (activity as Context).applicationContext
이 부분은 koin 하면서 없어질 코드이기에 넘어가겠습니다

2020-01-09 11:56 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-01-10 04:54 UTC, bean628 approved these changes

2020-01-10 04:57 UTC, merged