HW-5 데이터바인딩 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #403
Opened 2020-01-05 08:06 UTC by wooooooak

데이터바인딩 적용한 PR입니다.
리뷰 부탁드려요~

2020-01-06 14:28 UTC, JayYi requested changes
WebView 설정, adapter 설정 부분까지 BindingAdapter 설정이 가능 할 줄 몰랐네요.

다만, 너무 지나치게 모든 코드를 databinding을 적용하는 느낌이 들기도 하네요.
제가 이해한 databinding은 뷰의 속성, 이미지 로드나 웹뷰 url 로드 수준으로 구현하는 것으로 이해해서요.
제가 잘 모르는 거라 틀릴 수도 있어요. 어디까지나 개인적인 생각이라 용준님 생각은 어떠신지 궁금하네요.

아무튼 고생하셨습니다!

2020-01-06 14:28 UTC, JayYi commented on wooooooak/StudyApp/app/src/main/java/wooooooak/com/studyapp/common/ext/ListAdapterExt.kt
> +    adapter ?: kotlin.run {
adpater가 null이 아니면 갱신이 되지 않네요. 해당 코드가 의도하신것이 맞는지 궁금하네요.

2020-01-06 14:28 UTC, JayYi commented on wooooooak/StudyApp/app/src/main/java/wooooooak/com/studyapp/ui/blog/BlogPresenter.kt
> +//            view.setTitle(userInputTitle)
사용하지 않는 코드면 삭제하는게 좋을 것 같아요.

2020-01-07 10:26 UTC, wooooooak commented on wooooooak/StudyApp/app/src/main/java/wooooooak/com/studyapp/ui/blog/BlogPresenter.kt
> +//            view.setTitle(userInputTitle)
넵 불필요한 주석 제거했습니다~!

d1493b020b8aa0acf44af153340e433a895fda7c

2020-01-07 10:30 UTC, wooooooak commented on wooooooak/StudyApp/app/src/main/java/wooooooak/com/studyapp/common/ext/ListAdapterExt.kt
> +    adapter ?: kotlin.run {
넵 의도한 코드 맞습니다. adapter가 null이 아닐때(이미 설정되었을 때) 새로운 어댑터로 갈아끼워지는 것을 방지하려는 목적으로 작성한 코드입니다.

2020-01-07 10:30 UTC, wooooooak commented
> WebView 설정, adapter 설정 부분까지 BindingAdapter 설정이 가능 할 줄 몰랐네요.
> 
> 다만, 너무 지나치게 모든 코드를 databinding을 적용하는 느낌이 들기도 하네요.
> 제가 이해한 databinding은 뷰의 속성, 이미지 로드나 웹뷰 url 로드 수준으로 구현하는 것으로 이해해서요.
> 제가 잘 모르는 거라 틀릴 수도 있어요. 어디까지나 개인적인 생각이라 용준님 생각은 어떠신지 궁금하네요.
> 
> 아무튼 고생하셨습니다!

2020-01-07 10:35 UTC, wooooooak commented
> 다만, 너무 지나치게 모든 코드를 databinding을 적용하는 느낌이 들기도 하네요.
> 제가 이해한 databinding은 뷰의 속성, 이미지 로드나 웹뷰 url 로드 수준으로 구현하는 것으로 이해해서요.
> 제가 잘 모르는 거라 틀릴 수도 있어요. 어디까지나 개인적인 생각이라 용준님 생각은 어떠신지 궁금하네요.

저는 최대한 activity에서 코드를 제거하고, databinding으로 할수 있는건 databinding으로 하는게 깔끔할 것 같다는 생각에 이렇게 코드를 구현하긴 했는데요, 민재님 말씀 듣고 adapter나 webview 부분을 다시 빼볼까 생각했었는데, kotlin-android-extension을 제거하고 나니 databinding없이 어떻게 깔끔하게 짤수있을지 잘 모르겠네요...ㅎㅎ 민재님 PR 날리시면 한번 보고 참고해보겠습니다!!

2020-01-07 14:08 UTC, JayYi approved these changes
@wooooooak 
저는 깔끔하게 짠다는 생각보다는...그냥 일부 기능을 간단명료 하게 할 수 있는 수준으로 생각해서요. 아마 도움이 안 될 것 같은데.....

아무튼 고생하셨습니다.

2020-01-08 16:26 UTC, sjjeong requested changes

2020-01-08 16:26 UTC, sjjeong commented on wooooooak/StudyApp/app/src/main/java/wooooooak/com/studyapp/common/ext/WebViewExt.kt
> +    }
init하는 것과 url을 load하는 것은 분리해야 할 것 같습니다.

2020-01-08 16:26 UTC, sjjeong commented on wooooooak/StudyApp/app/src/main/java/wooooooak/com/studyapp/common/ext/MaterialRatingBarExt.kt
> +fun MaterialRatingBar.setRating(_rating: Float) {
취향차이 이긴하지만 저는 기존에 Movie 모델에서 userRating를 가지고 사용하는 것을 더 선호합니다.

2020-01-08 16:26 UTC, sjjeong commented on wooooooak/StudyApp/app/src/main/java/wooooooak/com/studyapp/ui/base/ItemSearchFragment.kt
> +    protected lateinit var binding: H
저는 H보단 B를 많이 사용합니다.
H를 사용한 이유가 있을까요?

2020-01-12 08:22 UTC, closed without merging