HW-1 영화 검색 어플리케이션
sjjeong/GoogryAndroidArchitecutreStudy pull request #404
Opened 2020-01-05 09:30 UTC by YKW93

2020-01-06 11:17 UTC, Minoyam commented on class08/YKW93/ArchitectureStudy/app/src/main/java/com/studyfork/architecturestudy/ApiClient.kt
> +    fun getService(): ApiService = retrofit.create(ApiService::class.java)
메소드는 아래쪽에 넣어줘야합니다.
implementation "com.google.android.material:material:1.2.0-alpha03"

2020-01-06 11:35 UTC, Minoyam commented on class08/YKW93/ArchitectureStudy/app/src/main/java/com/studyfork/architecturestudy/ApiClient.kt
> +    fun getService(): ApiService = retrofit.create(ApiService::class.java)
메소드는 아래쪽에 넣어줘야합니다.
Generally, the contents of a class is sorted in the following order:
Property declarations and initializer blocks
Secondary constructors
Method declarations
Companion object

2020-01-06 11:35 UTC, Minoyam commented on class08/YKW93/ArchitectureStudy/app/src/main/java/com/studyfork/architecturestudy/MovieResultRVAdapter.kt
> +            itemView.tv_movie_actor.text = item.actor
with을 사용해주시면 좀더 깔끔하게 만들수있습니다.

2020-01-07 05:00 UTC, YKW93 commented on class08/YKW93/ArchitectureStudy/app/src/main/java/com/studyfork/architecturestudy/ApiClient.kt
> +    fun getService(): ApiService = retrofit.create(ApiService::class.java)
수정했습니다!
commit : f9eb139

2020-01-07 05:01 UTC, YKW93 commented on class08/YKW93/ArchitectureStudy/app/src/main/java/com/studyfork/architecturestudy/MovieResultRVAdapter.kt
> +            itemView.tv_movie_actor.text = item.actor
수정했습니다! 감사합니다!
commit : 131f25a

2020-01-07 14:48 UTC, sjjeong requested changes

2020-01-07 14:48 UTC, sjjeong commented on class08/YKW93/ArchitectureStudy/app/build.gradle
> +    implementation 'androidx.recyclerview:recyclerview:1.1.0'
'com.google.android.material:material:1.0.0'에 포함되어 있으니 제거 해도 됩니다.

2020-01-07 14:48 UTC, sjjeong commented on class08/YKW93/ArchitectureStudy/app/src/main/java/com/studyfork/architecturestudy/ApiClient.kt
> +            .addInterceptor(HttpLoggingInterceptor().setLevel(HttpLoggingInterceptor.Level.BODY))
if (BuildConfig.DEBUG) HttpLoggingInterceptor.Level.BODY else HttpLoggingInterceptor.Level.NONE
이런식으로 해야 DEBUG모드가 아닐때 로그가 나오지 않습니다.

2020-01-07 14:48 UTC, sjjeong commented on class08/YKW93/ArchitectureStudy/app/src/main/java/com/studyfork/architecturestudy/ApiClient.kt
> +    fun getService(): ApiService = retrofit.create(ApiService::class.java)
이것도 함수보단 val로 선언해주셔도 됩니다

2020-01-07 14:48 UTC, sjjeong commented on class08/YKW93/ArchitectureStudy/app/src/main/java/com/studyfork/architecturestudy/MainActivity.kt
> +        compositeDisposable.clear()
super.onDestory()보다 먼저 호출되어야 합니다

2020-01-07 14:48 UTC, sjjeong commented on class08/YKW93/ArchitectureStudy/app/src/main/java/com/studyfork/architecturestudy/MovieResultRVAdapter.kt
> +    val items = mutableListOf<MovieResponse.Item>()
private으로 변경해주세요

2020-01-07 14:48 UTC, sjjeong commented on class08/YKW93/ArchitectureStudy/app/src/main/java/com/studyfork/architecturestudy/RxUtils.kt
> +        }
Single의 Extension함수로 만들면 compose로 처리하지 않아도 됩니다.

2020-01-07 14:48 UTC, sjjeong commented on class08/YKW93/ArchitectureStudy/app/src/main/java/com/studyfork/architecturestudy/CommonUtils.kt
> +    }
View의 extension으로 처리해보세요

2020-01-07 14:48 UTC, sjjeong commented on class08/YKW93/ArchitectureStudy/app/src/main/java/com/studyfork/architecturestudy/MainActivity.kt
> +            CommonUtils.hideKeyboard(baseContext, it)
hide할때는 주로 currentFocus를 넣어줍니다

2020-01-08 09:46 UTC, YKW93 commented on class08/YKW93/ArchitectureStudy/app/build.gradle
> +    implementation 'androidx.recyclerview:recyclerview:1.1.0'
삭제 했습니다.
c7c0ab030f23fe8cdfaec2e904ab4c8922555240

2020-01-08 09:46 UTC, YKW93 commented on class08/YKW93/ArchitectureStudy/app/src/main/java/com/studyfork/architecturestudy/ApiClient.kt
> +    fun getService(): ApiService = retrofit.create(ApiService::class.java)
변수로 변경했습니다!
467695b2d2a9078bfabcdcb64095c9feecfd8c5d

2020-01-08 09:47 UTC, YKW93 commented on class08/YKW93/ArchitectureStudy/app/src/main/java/com/studyfork/architecturestudy/ApiClient.kt
> +            .addInterceptor(HttpLoggingInterceptor().setLevel(HttpLoggingInterceptor.Level.BODY))
변경했습니다!
516c0ea08a30a3098cda03a232c1f3efdc2b0793

2020-01-08 09:47 UTC, YKW93 commented on class08/YKW93/ArchitectureStudy/app/src/main/java/com/studyfork/architecturestudy/MainActivity.kt
> +        compositeDisposable.clear()
abf6b98ec056d1ba8734d7d7611c79a8f7e5ac41

2020-01-08 09:48 UTC, YKW93 commented on class08/YKW93/ArchitectureStudy/app/src/main/java/com/studyfork/architecturestudy/MovieResultRVAdapter.kt
> +    val items = mutableListOf<MovieResponse.Item>()
변경했습니다.
55e63bf9472baf0ea2c7685b64f1be8247a93c31

2020-01-08 09:48 UTC, YKW93 commented on class08/YKW93/ArchitectureStudy/app/src/main/java/com/studyfork/architecturestudy/RxUtils.kt
> +        }
이렇게 처리 하는게 맞을까요..?

ae8e6b7764270db828e22516c05d4af7f96d831d

2020-01-08 09:50 UTC, YKW93 commented on class08/YKW93/ArchitectureStudy/app/src/main/java/com/studyfork/architecturestudy/RxUtils.kt
> +        }
이렇게 처리하는게 맞을까요?

ae8e6b7764270db828e22516c05d4af7f96d831d

2020-01-08 09:50 UTC, YKW93 commented on class08/YKW93/ArchitectureStudy/app/src/main/java/com/studyfork/architecturestudy/CommonUtils.kt
> +    }
변경했습니다.
707aa5124fb2d3cb04f40484fb695d70af2d61b5

2020-01-08 09:50 UTC, YKW93 commented on class08/YKW93/ArchitectureStudy/app/src/main/java/com/studyfork/architecturestudy/MainActivity.kt
> +            CommonUtils.hideKeyboard(baseContext, it)
707aa5124fb2d3cb04f40484fb695d70af2d61b5

2020-01-08 15:37 UTC, sjjeong commented on class08/YKW93/ArchitectureStudy/app/src/main/java/com/studyfork/architecturestudy/RxUtils.kt
> +        }
네 비슷하게 구현 하신것 같아요
```kotlin
fun <T> Single<T>.applySchedulers() = subscribeOn(Schedulers.io()).observeOn(AndroidSchedulers.mainThread())
```
였습니다.

2020-01-08 15:37 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-01-09 02:56 UTC, Minoyam approved these changes

2020-01-09 06:17 UTC, merged