HW-1 영화 검색 어플리케이션
sjjeong/GoogryAndroidArchitecutreStudy pull request #405
Opened 2020-01-05 11:52 UTC by slflfl12

2020-01-07 07:33 UTC, L91519 commented on class08/slflfl12/Study/app/src/main/java/com/example/study/DetailActivity.kt
> +
var로 하신 이유가 따로 있으신가요? val로 해도 되지 않을까요?

2020-01-07 07:50 UTC, L91519 commented on class08/slflfl12/Study/app/src/main/java/com/example/study/DetailActivity.kt
> +
Enter가 두번이상 입력되어있습니당

2020-01-07 07:54 UTC, L91519 commented on class08/slflfl12/Study/app/src/main/java/com/example/study/MainActivity.kt
> +
엔터가 여러번 입력되어있습니당

2020-01-07 10:44 UTC, L91519 commented on class08/slflfl12/Study/app/src/main/res/layout/movie_view.xml
> +            android:text="제목"
"제목", "년도" 등등은 string (xml파일)에 빼서 쓰는게 좋을 것 같아요!

2020-01-07 10:46 UTC, L91519 commented on class08/slflfl12/Study/app/src/main/res/layout/activity_main.xml
> +            app:layout_constraintTop_toBottomOf="@+id/linearLayout" />
@+id/를 @id/로 안 바꾸신 부분이 몇 군데 있는 것 같습니당

2020-01-08 16:43 UTC, sjjeong requested changes

2020-01-08 16:43 UTC, sjjeong commented on class08/slflfl12/Study/app/build.gradle
> +    dataBinding {
dataBinding은 나중에 다뤄볼 내용이기 때문에 지금은 넣지 말아주세요

2020-01-08 16:43 UTC, sjjeong commented on class08/slflfl12/Study/app/build.gradle
> +    implementation 'com.squareup.okhttp3:okhttp:4.1.0'
okhttp를 직접 바로 사용하는 것도 좋지만 retorfit library를 사용해보면 더 좋을 것 같습니다.

2020-01-08 16:43 UTC, sjjeong commented on class08/slflfl12/Study/app/src/main/java/com/example/study/MainActivity.kt
> +        recycler_view.layoutManager = LinearLayoutManager(this)
RecyclerView에 LayoutManager를 넣는 것은 xml에서도 할 수 있습니다.

2020-01-08 16:43 UTC, sjjeong commented on class08/slflfl12/Study/app/src/main/java/com/example/study/MovieAdapter.kt
> +                root.setOnClickListener {
클릭 이벤트는 onBindViewHolder시점이 아니라 onCreateViewHolder 시점에 set해야 합니다.

2020-01-09 09:53 UTC, slflfl12 commented on class08/slflfl12/Study/app/src/main/java/com/example/study/MainActivity.kt
> +
수정했습니다 
163d7493a04583b066e638604ff1f93b9e2701a4

2020-01-09 09:53 UTC, slflfl12 commented on class08/slflfl12/Study/app/src/main/res/layout/movie_view.xml
> +            android:text="제목"
수정했습니다
commit 87da1a839d30838303326c0d973c901ddc6c57e6

2020-01-09 09:54 UTC, slflfl12 commented on class08/slflfl12/Study/app/src/main/res/layout/activity_main.xml
> +            app:layout_constraintTop_toBottomOf="@+id/linearLayout" />
수정했습니당
commit efd0c1b31eb1b92ccae56f9fe1f441e91962ce35

2020-01-09 14:38 UTC, slflfl12 commented on class08/slflfl12/Study/app/build.gradle
> +    dataBinding {
데이터바인딩 제거했습니당
efb43be

2020-01-09 14:38 UTC, slflfl12 commented on class08/slflfl12/Study/app/build.gradle
> +    implementation 'com.squareup.okhttp3:okhttp:4.1.0'
레트로핏 적용했습니다!

74d0b03

2020-01-09 14:41 UTC, slflfl12 commented on class08/slflfl12/Study/app/src/main/java/com/example/study/MainActivity.kt
> +        recycler_view.layoutManager = LinearLayoutManager(this)
layoutManager xml로 변경했습니다

e81a909

2020-01-09 14:54 UTC, slflfl12 commented on class08/slflfl12/Study/app/src/main/java/com/example/study/MovieAdapter.kt
> +                root.setOnClickListener {
변경했습니다!

23ea040

2020-01-10 04:26 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-01-12 14:23 UTC, L91519 approved these changes

2020-01-12 15:01 UTC, merged