HW-3 MVP 패턴 적용하기
sjjeong/GoogryAndroidArchitecutreStudy pull request #407
Opened 2020-01-05 13:07 UTC by AhnHyeonho

* MainActivity에 관련된 ui/main 패키지 추가 및 MainContract, MainPresenter 생성
* MovieInformationActivity에 관련된 ui/movieinformation 패키지 추가 및 MovieInformationContract, MovieInformationPresenter 생성
* MVP 패턴 적용으로 인한 코드 전체적인 수정
* 기존 MainActivity에서 관리하던 clientId와 clientSecret을 dataSource에서 관리하도록 수정

2020-01-07 23:24 UTC, seunghee63 requested changes
멘토님이 말씀 해 주셨던 것 처럼 

- 검색결과 무한 스크롤 구현
- 유효하지 않은 검색어, 검색결과 처리
- 기타 알수 없는 에러발생 처리

등의 추가적인 기능구현을 해서 MVP패턴을 조금 더 다양한 기능에 적용 해 보면 좋을 것 같습니다!

2020-01-07 23:24 UTC, seunghee63 commented on AhnHyeonho/FirstProject/app/src/main/java/com/hansung/firstproject/ui/main/MainActivity.kt
> +        ).also { it.init() }
MVP 패턴에서, View는 오직 Presenter와 의존하며, View와 Model 사이에서는 의존성이 없는 것으로 알고있습니다.
그렇기에 repository 객체를 호출하는 과정을 MainActivity가 아닌, Presenter에서 호출해서 다뤄야 하는 것이라고 생각합니다. 사실 멘토님이 실습 하실 때도 이렇게 View와 repository를 함수인자로 넘겨주는 방식으로 구현 하셨어서.. 헷갈리긴 하지만.. 현호님의 의견을 알고 싶어서 리뷰 남깁니다..!!

2020-01-07 23:31 UTC, seunghee63 requested changes

2020-01-07 23:31 UTC, seunghee63 commented on AhnHyeonho/FirstProject/app/src/main/java/com/hansung/firstproject/ui/main/MainActivity.kt
> +
저는 데이터의 영향을 받지 않는 초기화 or 기본적인 세팅을 하는 부분은 Presenter를 거치지 않고 단순하게 Activity 내에서 처리를 한 것에 반해
현호님은 view에서 발생하는 모든 기능들을 presenter를 통해서 구현을 하셨는데, 초기화 or 세팅과정도 presenter를 거치는 방식으로 구현을 한 이유가 궁금합니다!

2020-01-10 06:30 UTC, zozero94 reviewed
3기 조재영입니다.
간단리뷰 남겨요

2020-01-10 06:30 UTC, zozero94 commented on AhnHyeonho/FirstProject/app/src/main/java/com/hansung/firstproject/data/repository/NaverRepository.kt
>      companion object {
dataSource를 주입해서 사용하는게 어떨까요

2020-01-10 06:30 UTC, zojae031 commented on AhnHyeonho/FirstProject/app/src/main/java/com/hansung/firstproject/ui/main/MainActivity.kt
> +    }
presenter를 lazy로 만드는것은 어떨까요?
onCreate에서는 presenter.init()만 호출할수 있도록 바꾸는것도 좋을것 같아요

또, naverReposiotry를 변수를 할당해서 mainActivity가 가지고 있는데 이러면 activity가 Repository(Model)에 의존성이 생기는 현상이 발생하는것 같아요
(Repositroy를 담기 위한 naverRepositroy 메모리 할당이 있을것 같아요)
presenter를 만들때, 생성하여 주입해주는 방법은 어떨까요?

2020-01-10 06:30 UTC, zojae031 commented on AhnHyeonho/FirstProject/app/src/main/java/com/hansung/firstproject/ui/main/MainActivity.kt
> +        initRecyclerView()
```kotilin
override fun init() {
        view.initRecyclerView()
    }
```

presenter에서 init시에도 호출하는데 두 번 호출되는 것 같습니다.

2020-01-10 08:40 UTC, AhnHyeonho commented on AhnHyeonho/FirstProject/app/src/main/java/com/hansung/firstproject/ui/main/MainActivity.kt
> +        ).also { it.init() }
코드를 수정해보았습니다.  말씀하신대로 호출과정 자체를 presenter에서 해주기 보다는 
의존성 개입 측면 때문에 외부에서 정의해주고 넘겨주는 방식으로 해결하려던 의도였습니다. 

저도 어느게 올바른지는 멘토님의 의견을 들어봐야 알 것 같네요!

```kotlin
    private val presenter by lazy {
        MainPresenter(
            this,
            NaverRepository.getInstance(
                NaverRemoteDataSourceImpl.getInstance(
                    getString(R.string.client_id),
                    getString(R.string.client_secret)
                )
            )
        )

    }
```

'검색결과가 없는 경우' 와 같이 커밋 된 점 양해바랍니다...!
f4e0165

2020-01-10 08:45 UTC, AhnHyeonho commented on AhnHyeonho/FirstProject/app/src/main/java/com/hansung/firstproject/ui/main/MainActivity.kt
> +
저도 같은 고민을 했었는데 승희님 의견이 맞는 것 같네요. 불필요하게 presenter를 거치는 것 같습니다. 수정했습니다.

89ee86b

2020-01-10 12:46 UTC, AhnHyeonho commented on AhnHyeonho/FirstProject/app/src/main/java/com/hansung/firstproject/data/repository/NaverRepository.kt
>      companion object {
의존성 주입형식으로 수정하였습니다.


9f13d7e

2020-01-10 12:50 UTC, AhnHyeonho commented on AhnHyeonho/FirstProject/app/src/main/java/com/hansung/firstproject/ui/main/MainActivity.kt
> +    }
커밋이 묶인 점 양해 바랍니다. 아래 코드와 같이 수정하였습니다. 라인은 21~31입니다.

```kotlin
    private val presenter by lazy {
        MainPresenter(
            this,
            NaverRepository.getInstance(
                NaverRemoteDataSourceImpl.getInstance(
                    getString(R.string.client_id),
                    getString(R.string.client_secret)
                )
            )
        )

    }
```


f4e0165

2020-01-10 12:54 UTC, AhnHyeonho commented on AhnHyeonho/FirstProject/app/src/main/java/com/hansung/firstproject/ui/main/MainActivity.kt
> +        initRecyclerView()
커밋이 묶인 점 양해 바랍니다. 해당 코드는 삭제하였고 view에 관한 메소드이므로 presenter를 거치지 않고 46번 라인과 같이 처리하였습니다.

89ee86b

2020-01-10 12:56 UTC, AhnHyeonho commented on AhnHyeonho/FirstProject/app/src/main/java/com/hansung/firstproject/ui/main/MainActivity.kt
> +        ).also { it.init() }
기타 알수없는 에러에 대해서도 핸들링 가능하도록 수정해보았습니다.


1de4925

2020-01-10 17:32 UTC, seunghee63 approved these changes

2020-01-12 02:41 UTC, sjjeong requested changes

2020-01-12 02:41 UTC, sjjeong commented on AhnHyeonho/FirstProject/app/src/main/java/com/hansung/firstproject/data/source/remote/NaverRemoteDataSourceImpl.kt
> +                            onResponse(response.body()!!)
if가 {} 가 있다면 else도 {}가 있어야 합니다

2020-01-12 02:41 UTC, sjjeong commented on AhnHyeonho/FirstProject/app/src/main/java/com/hansung/firstproject/data/source/remote/NaverRemoteDataSourceImpl.kt
> +        fun getInstance(stringRes: Resources): NaverRemoteDataSourceImpl =
Resource를 가져와서 사용하는 것은 좋지 않습니다.
fail 처리에서 400, 401, 500 같은 것은 enum class같은 것을 사용해서 전달하도록 하고
client_id, client_secret같은 경우는 파라미터로 String을 전달 받으면 됩니다.

2020-01-12 10:09 UTC, AhnHyeonho commented on AhnHyeonho/FirstProject/app/src/main/java/com/hansung/firstproject/data/source/remote/NaverRemoteDataSourceImpl.kt
> +                            onResponse(response.body()!!)
수정하였습니다.


9e12c90

2020-01-12 10:10 UTC, AhnHyeonho commented on AhnHyeonho/FirstProject/app/src/main/java/com/hansung/firstproject/data/source/remote/NaverRemoteDataSourceImpl.kt
> +        fun getInstance(stringRes: Resources): NaverRemoteDataSourceImpl =
필요한 enum class 를 정의하였고  c505844

그에 따른 코드 수정입니다.   fb18d63

2020-01-13 11:07 UTC, sjjeong commented on AhnHyeonho/FirstProject/app/src/main/java/com/hansung/firstproject/data/source/remote/NaverRemoteDataSourceImpl.kt
> +                            onResponse(response.body()!!)
https://developer.android.com/kotlin/style-guide#braces 이거 보고 다시 수정해주세요

2020-01-13 11:23 UTC, AhnHyeonho commented on AhnHyeonho/FirstProject/app/src/main/java/com/hansung/firstproject/data/source/remote/NaverRemoteDataSourceImpl.kt
> +                            onResponse(response.body()!!)
수정하였습니다. 2


973218f

2020-01-13 11:24 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-01-13 11:28 UTC, merged