HW-5 데이터바인딩
sjjeong/GoogryAndroidArchitecutreStudy pull request #408
Opened 2020-01-06 15:04 UTC by dksush

2020-01-09 12:29 UTC, sjjeong commented
@chanhoparkcj 
approve도 해주세요

2020-01-09 12:38 UTC, sjjeong requested changes

2020-01-09 12:38 UTC, sjjeong commented on dksush/AndroidArchitecture/app/src/main/java/com/example/androidarchitecture/data/datasource/local/NaverLocalDataSourceIml.kt
> +class NaverLocalDataSourceIml(private val context: Context) : NaverLocalDataSourceInterface {
context를 전달 받기 보단 SharedPreferences와 SearchHistDatabase를 전달 받는게 좋습니다.
관련 내용은 Dependency Injection 개념에 대해 알아보시면 좋습니다.

2020-01-09 12:38 UTC, sjjeong commented on dksush/AndroidArchitecture/app/src/main/java/com/example/androidarchitecture/ui/blog/BlogAdapter.kt
> +        context = parent.context
context를 따로 가지고 있을 필요가 없습니다.

2020-01-09 12:38 UTC, sjjeong commented
그 외에 잘 하셨네요

2020-01-09 17:25 UTC, ghost approved these changes

2020-01-10 01:57 UTC, dksush commented on dksush/AndroidArchitecture/app/src/main/java/com/example/androidarchitecture/ui/blog/BlogAdapter.kt
> +        context = parent.context
수정했습니다.

74c0302

2020-01-10 01:57 UTC, dksush commented on dksush/AndroidArchitecture/app/src/main/java/com/example/androidarchitecture/data/datasource/local/NaverLocalDataSourceIml.kt
> +class NaverLocalDataSourceIml(private val context: Context) : NaverLocalDataSourceInterface {
수정했습니다.

9602c55

2020-01-10 04:27 UTC, sjjeong commented on dksush/AndroidArchitecture/app/src/main/java/com/example/androidarchitecture/ui/blog/BlogAdapter.kt
> +        context = parent.context
ViewHolder 내부에서는 itemView의 context에 접근하면 됩니다.

2020-01-10 05:05 UTC, dksush commented on dksush/AndroidArchitecture/app/src/main/java/com/example/androidarchitecture/ui/blog/BlogAdapter.kt
> +        context = parent.context
오오 그렇게 들어갈 수도 있었군요. 감사합니다

67b8dd5

2020-01-11 02:11 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-01-12 09:13 UTC, merged