HW-3 MVP 패턴 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #409
Opened 2020-01-06 17:36 UTC by handnew04

2020-01-07 13:02 UTC, ghkdua1829 approved these changes
클릭리스너 처리를 저도 정확하게는 잘 모르겠네요..ㅠㅠ 수고하셨습니다!

2020-01-07 14:59 UTC, sjjeong requested changes

2020-01-07 14:59 UTC, sjjeong commented on handnew04/app/src/main/AndroidManifest.xml
> +        <activity android:name="com.example.handnew04.ui.movie.MovieDetailActivity"></activity>
3번째 줄에 package="com.example.handnew04"라고 했기 때문에 `com.example.handnew04`는 생략 가능합니다.

2020-01-07 14:59 UTC, sjjeong commented on handnew04/app/src/main/java/com/example/handnew04/ui/base/BaseActivity.kt
> +class BaseActivity : BaseContract.View {
이거는 어떤용도로 만드신건가요?

2020-01-07 14:59 UTC, sjjeong commented on handnew04/app/src/main/java/com/example/handnew04/ui/main/MainActivity.kt
> +                showMovieDetailActivity(position)
괜찮습니다 잘 하셨어요

2020-01-07 14:59 UTC, sjjeong commented on handnew04/app/src/main/java/com/example/handnew04/ui/main/MainContract.kt
> +        fun getContext(): Context
Presenter에 context를 전달하지 않도록 해주세요

2020-01-07 14:59 UTC, sjjeong commented on handnew04/app/src/main/java/com/example/handnew04/ui/main/MainPresenter.kt
> +    }
보통 이럴땐 NetworkManager라는것을 만들고 ApplicationContext를 이용해서 처리합니다.

2020-01-07 14:59 UTC, sjjeong commented on handnew04/app/src/main/java/com/example/handnew04/ui/main/MainPresenter.kt
> +    lateinit var mInputText: String
kotlin에서 m prefix를 사용하지 않습니다.

2020-01-08 13:54 UTC, handnew04 commented on handnew04/app/src/main/java/com/example/handnew04/ui/main/MainPresenter.kt
> +    }
ApplicationContext 를 어떻게 받아와야 할지 감이 안와요

2020-01-09 15:16 UTC, handnew04 commented on handnew04/app/src/main/AndroidManifest.xml
> +        <activity android:name="com.example.handnew04.ui.movie.MovieDetailActivity"></activity>
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/409/commits/f688cbeea10332da15f74a0a34264e0335ed2be0

2020-01-09 15:17 UTC, handnew04 commented on handnew04/app/src/main/java/com/example/handnew04/ui/base/BaseActivity.kt
> +class BaseActivity : BaseContract.View {
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/409/commits/21ede53c04bfa1c249d0fe7cad06ed0733439185

https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/409/commits/d5eb618c319d8d84b013180092871d9c8c9b4278

Base를 전부 다 만들어야 하는줄 알았는데 필요가 없었던거 같아요

2020-01-09 15:17 UTC, handnew04 commented on handnew04/app/src/main/java/com/example/handnew04/ui/main/MainPresenter.kt
> +    lateinit var mInputText: String
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/409/commits/c14c167b2675d143b605e50c0628e7bbbb187d3e

2020-01-09 15:18 UTC, handnew04 commented on handnew04/app/src/main/java/com/example/handnew04/ui/main/MainPresenter.kt
> +    }
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/409/commits/c14c167b2675d143b605e50c0628e7bbbb187d3e

생성자에 this.application 을 바로 넣으니 null 에러가 떠서 lazy 를 사용하였는데, 맞는지 모르겠어요

2020-01-09 15:18 UTC, handnew04 commented on handnew04/app/src/main/java/com/example/handnew04/ui/main/MainContract.kt
> +        fun getContext(): Context
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/409/commits/c14c167b2675d143b605e50c0628e7bbbb187d3e

2020-01-09 15:19 UTC, handnew04 commented on handnew04/app/src/main/java/com/example/handnew04/ui/main/MainPresenter.kt
> +    }
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/409/commits/c14c167b2675d143b605e50c0628e7bbbb187d3e

2020-01-10 04:28 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-01-10 04:42 UTC, merged