HW-1 네이버 영화 검색 API 앱 구현
sjjeong/GoogryAndroidArchitecutreStudy pull request #410
Opened 2020-01-07 07:18 UTC by HudsonPark

2020-01-08 07:11 UTC, HudsonPark reviewed
test

2020-01-08 07:13 UTC, devLibCH requested changes

2020-01-08 07:13 UTC, devLibCH commented on class08/HudsonPark/ArchtectStudy/app/src/main/java/com/example/archstudy/MovieListAdapter.kt
>                      .into(ivThumbnail)
점으로 이어지는 패턴에서는 점 하나마다 줄을 바꿔주는게 좋습니다.

2020-01-08 07:13 UTC, devLibCH commented on class08/HudsonPark/ArchtectStudy/app/src/main/java/com/example/archstudy/MovieListAdapter.kt
> +                    clickPosition = adapterPosition
clickPosition은 사용하고 있는 변수인가요?

2020-01-08 07:13 UTC, devLibCH commented on class08/HudsonPark/ArchtectStudy/app/src/main/java/com/example/archstudy/MovieListAdapter.kt
> +
view 한가지마다 메소드를 만드는 것 보단 한번에 처리하는게 좋을 것 같습니다.

2020-01-08 07:13 UTC, devLibCH commented on class08/HudsonPark/ArchtectStudy/app/src/main/java/com/example/archstudy/MovieListAdapter.kt
> +                    context.startActivity(intent)
intent처리는 adapter 내에서보다 listener등을 이용해서 Activity에서 처리하는 편이 좋습니다.

2020-01-08 07:13 UTC, devLibCH commented on class08/HudsonPark/ArchtectStudy/app/src/main/java/com/example/archstudy/MainActivity.kt
> +                            movieData = response.body()!!.items
! 사용시에 exception이 발생하면 앱이 죽어서 ?를 사용하시거나 body null 체크 후 사용하시는게 좋을 것 같습니다.

2020-01-08 07:13 UTC, devLibCH commented on class08/HudsonPark/ArchtectStudy/app/src/main/java/com/example/archstudy/MainActivity.kt
> +    private var query = ""
멤버변수로 사용하는 일이 없으므로 지역변수로 변환하시는게 좋을 것 같습니다.

2020-01-08 07:13 UTC, devLibCH commented on class08/HudsonPark/ArchtectStudy/app/src/main/java/com/example/archstudy/MovieListAdapter.kt
> +        holder.bind(movieList[position])
한줄만 사용한다면 getItemCount처럼 =을 사용하시는게 좋습니다.

2020-01-08 09:48 UTC, HudsonPark commented on class08/HudsonPark/ArchtectStudy/app/src/main/java/com/example/archstudy/MovieListAdapter.kt
>                      .into(ivThumbnail)
@devLibCH 알겠습니다 코드 수정해서 반영하겠습니다

2020-01-08 09:53 UTC, HudsonPark commented on class08/HudsonPark/ArchtectStudy/app/src/main/java/com/example/archstudy/MovieListAdapter.kt
> +                    clickPosition = adapterPosition
@devLibCH 다른 방법으로 구현하려다가 지우지 않았었네요

2020-01-08 10:02 UTC, HudsonPark commented on class08/HudsonPark/ArchtectStudy/app/src/main/java/com/example/archstudy/MainActivity.kt
> +                            movieData = response.body()!!.items
@devLibCH 네 null exception 처리하는 코드 적용하겠습니다

2020-01-08 10:03 UTC, HudsonPark commented on class08/HudsonPark/ArchtectStudy/app/src/main/java/com/example/archstudy/MovieListAdapter.kt
> +
@devLib 배우 정보가 없는 데이터가 있어서 처리하려고 func 분리했는 데 아직 코드를 적용하지 않았습니다

2020-01-08 10:06 UTC, HudsonPark commented on class08/HudsonPark/ArchtectStudy/app/src/main/java/com/example/archstudy/MovieListAdapter.kt
> +                    context.startActivity(intent)
@devLibCH 네 listener 구현해서 처리해보겠습니다

2020-01-08 10:16 UTC, HudsonPark commented on class08/HudsonPark/ArchtectStudy/app/src/main/java/com/example/archstudy/MainActivity.kt
> +    private var query = ""
@devLibCH 확인해보니 지역변수로도 충분할 듯하네요. query 변수 지역변수로 변환했습니다.

2020-01-08 10:34 UTC, HudsonPark commented on class08/HudsonPark/ArchtectStudy/app/src/main/java/com/example/archstudy/MovieListAdapter.kt
> +        holder.bind(movieList[position])
@devLibCH 수정했습니다.

2020-01-08 16:27 UTC, sjjeong commented
@HudsonPark 
리뷰 반영하셨다면 코멘트에 commit id 남겨주세요
그래야 리뷰어가 확인하기 쉽습니다.
항상 리뷰어를 배려해줘야 합니다.

2020-01-09 12:28 UTC, sjjeong requested changes

2020-01-09 12:28 UTC, sjjeong commented on class08/HudsonPark/ArchtectStudy/app/src/main/java/com/example/archstudy/MainActivity.kt
> +        rvMovieList.adapter = rvMovieAdapter
요청 할 때마다 adapter를 새로 생성해서 set 할 필요 없이 adapter에 데이터를 변경하고 notify만 해주면 됩니다.

2020-01-09 12:28 UTC, sjjeong commented on class08/HudsonPark/ArchtectStudy/app/src/main/java/com/example/archstudy/MainActivity.kt
> +                rvMovieList.adapter?.notifyDataSetChanged()
이 코드는 동작하는데 아무 효과가 없는 코드 인 것 같습니다.
제거 해주시는게 좋을 것 같습니다.

2020-01-09 12:28 UTC, sjjeong commented on class08/HudsonPark/ArchtectStudy/app/src/main/java/com/example/archstudy/MovieListAdapter.kt
> +                layoutItem.setOnClickListener {
listener는 onBindViewHolder시점이 아니라 onCreateViewHolder 시점에서 처리해주면 됩니다.
onBindViewHolder는 스크롤 될 때마다 호출 되기 때문에 불필요한 set이 많이 됩니다.

2020-01-10 04:49 UTC, devLibCH approved these changes

2020-01-10 08:16 UTC, HudsonPark commented on class08/HudsonPark/ArchtectStudy/app/src/main/java/com/example/archstudy/MovieListAdapter.kt
> +                layoutItem.setOnClickListener {
@sjjeong onCreateViewHolder()에서 리스너를 선언해준다면 리스너를 받는 뷰와 데이터는 어떻게 얻어와야 될까요?

2020-01-10 09:33 UTC, HudsonPark commented on class08/HudsonPark/ArchtectStudy/app/src/main/java/com/example/archstudy/MainActivity.kt
> +        rvMovieList.adapter = rvMovieAdapter
@sjjeong 코드 변경했습니다.

2020-01-10 09:34 UTC, HudsonPark commented on class08/HudsonPark/ArchtectStudy/app/src/main/java/com/example/archstudy/MainActivity.kt
> +                rvMovieList.adapter?.notifyDataSetChanged()
@sjjeong 제거 완료했습니다
`else {
                showToast("요청하신 관련 영화 : $query")
                requestMovieList(query) // 네이버 영화 정보 API 요청

            }`

2020-01-10 11:05 UTC, HudsonPark commented on class08/HudsonPark/ArchtectStudy/app/src/main/java/com/example/archstudy/MovieListAdapter.kt
> +                layoutItem.setOnClickListener {
@sjjeong onCreateViewHolder()에서 holder 리턴 전에 holder.itemView.onClickListener(data[holder.adapterPosition].link)해줘서 문제를 해결했습니다.
2d9939f

2020-01-11 04:51 UTC, sjjeong requested changes

2020-01-11 04:51 UTC, sjjeong commented on class08/HudsonPark/ArchtectStudy/app/src/main/java/com/example/archstudy/MovieListAdapter.kt
> +class MovieListAdapter(private var movieList: ArrayList<Item>, @Nullable private var listener: ItemClickListener) :
list 객체를 Adapter 외부에 있는 것과 공유하지말고 내부에 따로 객체를 만들어서 사용하도록 해주세요

2020-01-11 08:43 UTC, HudsonPark commented on class08/HudsonPark/ArchtectStudy/app/src/main/java/com/example/archstudy/MovieListAdapter.kt
> +class MovieListAdapter(private var movieList: ArrayList<Item>, @Nullable private var listener: ItemClickListener) :
@sjjeong 
03e7d9c Adapter 클래스 내 list 선언하여 내부 fun에서 이 리스트를 참조하도록 했습니다.

2020-01-11 09:25 UTC, sjjeong commented on class08/HudsonPark/ArchtectStudy/app/src/main/java/com/example/archstudy/MovieListAdapter.kt
> +class MovieListAdapter(private var movieList: ArrayList<Item>, @Nullable private var listener: ItemClickListener) :
여전히 외부와 객체를 공유하고 있습니다.

2020-01-11 09:54 UTC, HudsonPark commented on class08/HudsonPark/ArchtectStudy/app/src/main/java/com/example/archstudy/MovieListAdapter.kt
> +class MovieListAdapter(private var movieList: ArrayList<Item>, @Nullable private var listener: ItemClickListener) :
@sjjeong 그럼 매개변수로 movieList를 받지 않고 구현하라는 말씀이신가요?

2020-01-12 02:00 UTC, sjjeong commented on class08/HudsonPark/ArchtectStudy/app/src/main/java/com/example/archstudy/MovieListAdapter.kt
> +class MovieListAdapter(private var movieList: ArrayList<Item>, @Nullable private var listener: ItemClickListener) :
@HudsonPark 
네 맞습니다.

2020-01-12 10:43 UTC, HudsonPark commented on class08/HudsonPark/ArchtectStudy/app/src/main/java/com/example/archstudy/MovieListAdapter.kt
> +class MovieListAdapter(private var movieList: ArrayList<Item>, @Nullable private var listener: ItemClickListener) :
@sjjeong 
4de3b68 Adapter에서 매개변수 제거하고 따로 func을 선언했습니다.

2020-01-13 11:04 UTC, sjjeong commented on class08/HudsonPark/ArchtectStudy/app/src/main/java/com/example/archstudy/MovieListAdapter.kt
> +class MovieListAdapter(private var movieList: ArrayList<Item>, @Nullable private var listener: ItemClickListener) :
@HudsonPark 
아직 제 리뷰에 대해 제대로 답변되지 않았습니다.
`list 객체를 Adapter 외부에 있는 것과 공유하지말고 내부에 따로 객체를 만들어서 사용하도록 해주세요`가 어떤 내용인지 이해가 안되시면 슬랙에 질문 올려주세요. dm말고 general이나 class08 채널에 올려주세요

2020-01-13 12:10 UTC, HudsonPark commented on class08/HudsonPark/ArchtectStudy/app/src/main/java/com/example/archstudy/MovieListAdapter.kt
> +class MovieListAdapter(private var movieList: ArrayList<Item>, @Nullable private var listener: ItemClickListener) :
@sjjeong 
4f5f388 제가 다시 이해한대로 수정했습니다. 만약 아니라면 slack에 질문 남기겠습니다.

2020-01-13 12:13 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-01-13 12:14 UTC, merged