HW-1 영화 검색 어플리케이션
sjjeong/GoogryAndroidArchitecutreStudy pull request #412
Opened 2020-01-07 13:51 UTC by L91519

2020-01-10 04:30 UTC, sjjeong commented
@L91519 
폴더 위치가 원위치 되고 나면 리뷰 하도록 하겠습니다.

2020-01-10 06:25 UTC, L91519 commented
> @L91519
> 폴더 위치가 원위치 되고 나면 리뷰 하도록 하겠습니다.

수정 했습니다. 확인 부탁드립니다. 감사합니다!

2020-01-11 04:55 UTC, sjjeong commented
@L91519 
리뷰 다시 할게요

2020-01-11 06:26 UTC, seosh817 requested changes

2020-01-11 06:26 UTC, seosh817 commented on L91519/My Application/app/src/main/java/com/example/myapplication/MainActivity.kt
> +        wv_movie_detail.loadUrl(link)
이 부분을 인터페이스로 따로 빼서 함수를 구현하는 것도 좋을 것 같습니다

2020-01-11 06:26 UTC, seosh817 commented on L91519/My Application/app/src/main/java/com/example/myapplication/ApiClient.kt
> +    val BASE_URL = "https://openapi.naver.com/v1/"
이  멤버 변수들도 private로 바꿔주는게 낫지 않을까요???

2020-01-11 06:26 UTC, seosh817 commented on L91519/My Application/app/src/main/java/com/example/myapplication/ApiClient.kt
> +    fun getService(): MovieApi = retrofit.create(MovieApi::class.java)
fun 말고 val로 선언해주셔도 될것 같습니다

2020-01-12 01:22 UTC, L91519 commented on L91519/My Application/app/src/main/java/com/example/myapplication/ApiClient.kt
> +    val BASE_URL = "https://openapi.naver.com/v1/"
변경 했습니다!  6000c364cf4832d6b9061d1cf554bb27017876d2

2020-01-12 01:22 UTC, L91519 commented on L91519/My Application/app/src/main/java/com/example/myapplication/ApiClient.kt
> +    fun getService(): MovieApi = retrofit.create(MovieApi::class.java)
변경 했습니다!  6000c364cf4832d6b9061d1cf554bb27017876d2

2020-01-12 02:08 UTC, sjjeong requested changes

2020-01-12 02:08 UTC, sjjeong commented on class08/L91519/My Application/app/src/main/java/com/example/myapplication/ApiClient.kt
> +    fun getService(): MovieApi = retrofit.create(MovieApi::class.java)
val로 만들어주세요

2020-01-12 02:08 UTC, sjjeong commented on class08/L91519/My Application/app/src/main/java/com/example/myapplication/MainActivity.kt
> +        rv_movie_list.layoutManager = LinearLayoutManager(this, RecyclerView.VERTICAL, false)
LayoutManager를 xml에서 할 수 있습니다.

2020-01-12 02:08 UTC, sjjeong commented on class08/L91519/My Application/app/src/main/java/com/example/myapplication/MainActivity.kt
> +                adapter.setItems(response.body()?.items as ArrayList<MovieResult.Item>)
아마 에러나서 이렇게 하신것 같은데 !! 쓰는거랑 같은 효과입니다.
response.body()?.items가 null이 아닐때 전달해주거나 setItems를 nullable하게 받을 수 있게 변경해주세요

2020-01-12 02:08 UTC, sjjeong commented on class08/L91519/My Application/app/src/main/java/com/example/myapplication/MovieRecyclerViewAdpater.kt
> +            itemView.setOnClickListener {
item click listener는 onBindViewHolder에서 말고 onCreateViewHolder시점에서 해주세요

2020-01-12 02:08 UTC, sjjeong commented on class08/L91519/My Application/app/src/main/res/layout/activity_main.xml
> +        app:layout_constraintLeft_toRightOf="@id/et_movie"
left right보단 start end를 사용하는걸 추천합니다

2020-01-12 03:29 UTC, L91519 commented on class08/L91519/My Application/app/src/main/res/layout/activity_main.xml
> +        app:layout_constraintLeft_toRightOf="@id/et_movie"
start end보다 left right을 사용한 것이 대부분이었어서 그러는데 이런 같은 속성들은 스타일에 따로 작성하는게 좋을까요? 어떨때 스타일을 작성하고 적용해야할지 잘 모르겠습니다. 

그냥 중복되는 속성이라면 다 사용해도 되는건지...

2020-01-12 03:30 UTC, sjjeong commented on class08/L91519/My Application/app/src/main/res/layout/activity_main.xml
> +        app:layout_constraintLeft_toRightOf="@id/et_movie"
RTL LTR 에서 동작하는게 달라져요
left right는 RTL LTR 상관없이 왼쪽 오른쪽인데
start end는 시작 끝이라서 RTL LTR에 따라 다르게 동작해요
구글에서도 start end를 권장하고 있습니다

2020-01-12 04:01 UTC, L91519 commented on class08/L91519/My Application/app/src/main/res/layout/activity_main.xml
> +        app:layout_constraintLeft_toRightOf="@id/et_movie"
넵 변경했습니다. 98646c580921f0af0d868ebadae367edb089e67c

2020-01-12 04:03 UTC, L91519 commented on class08/L91519/My Application/app/src/main/java/com/example/myapplication/MovieRecyclerViewAdpater.kt
> +            itemView.setOnClickListener {
변경했습니다. bb4eb2da6062fb26a2b2671ac4b6b37ee40efb2f

2020-01-12 04:03 UTC, L91519 commented on class08/L91519/My Application/app/src/main/java/com/example/myapplication/MainActivity.kt
> +                adapter.setItems(response.body()?.items as ArrayList<MovieResult.Item>)
변경했습니다. 73d8f5d93510f993e6df552c22f524333f1416cd

2020-01-12 04:03 UTC, L91519 commented on class08/L91519/My Application/app/src/main/java/com/example/myapplication/MainActivity.kt
> +        rv_movie_list.layoutManager = LinearLayoutManager(this, RecyclerView.VERTICAL, false)
변경했습니다. 2f1b8ea99bf11f310ab35f6abbd594f7e7913194

2020-01-12 04:04 UTC, L91519 commented on class08/L91519/My Application/app/src/main/java/com/example/myapplication/ApiClient.kt
> +    fun getService(): MovieApi = retrofit.create(MovieApi::class.java)
@sjjeong 변경했습니다. 
6000c364cf4832d6b9061d1cf554bb27017876d2

2020-01-12 04:05 UTC, L91519 commented on class08/L91519/My Application/app/src/main/res/layout/activity_main.xml
> +        app:layout_constraintLeft_toRightOf="@id/et_movie"
이때 commit 확인 했었는데 xml 파일이 바뀌어도 file change에 뜨지 않는 것 처럼 보입니다.

2020-01-12 04:15 UTC, L91519 commented on class08/L91519/My Application/app/src/main/java/com/example/myapplication/MainActivity.kt
> +                adapter.setItems(response.body()?.items as ArrayList<MovieResult.Item>)
변경했습니다. 73d8f5d93510f993e6df552c22f524333f1416cd

2020-01-12 04:23 UTC, sjjeong commented on class08/L91519/My Application/app/src/main/java/com/example/myapplication/MainActivity.kt
> +        rv_movie_list.layoutManager = LinearLayoutManager(this, RecyclerView.VERTICAL, false)
@L91519 
xml에서 추가가 되지 않았습니다.

2020-01-12 04:34 UTC, L91519 commented on class08/L91519/My Application/app/src/main/java/com/example/myapplication/MainActivity.kt
> +        rv_movie_list.layoutManager = LinearLayoutManager(this, RecyclerView.VERTICAL, false)
감사합니다. 추가했습니다. 
682a875739f763e4e593974e8a37c41de2d7b4e2

2020-01-12 12:03 UTC, seosh817 approved these changes

2020-01-13 11:08 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-01-13 12:32 UTC, merged