HW-3 MVP 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #413
Opened 2020-01-07 16:12 UTC by ghkdua1829

2020-01-08 05:57 UTC, handnew04 requested changes

2020-01-08 05:57 UTC, handnew04 commented on ghkdua1829/app/src/main/java/com/example/architecture_project/feature/search/MainContract.kt
> +        fun noKeyword()
함수의 경우 동사로 시작하는 것으로 알고 있는데, 혹시 no는 앞에 붙일 수 있는 건가요? 헷갈려서요

2020-01-08 05:57 UTC, handnew04 commented on ghkdua1829/app/src/main/java/com/example/architecture_project/feature/search/MainContract.kt
> +        fun getMovieData(keyword: String)
presenter 내부에서 처리하는 동작은 확인 하였으나, 함수 자체가 하나인점은 조금 아쉽습니다.

2020-01-08 16:32 UTC, sjjeong commented on ghkdua1829/app/src/main/java/com/example/architecture_project/feature/search/MainContract.kt
> +        fun getMovieData(keyword: String)
@handnew04 
예를 들면 어떤 함수가 더 있으면 좋을까요?

2020-01-09 07:04 UTC, handnew04 commented on ghkdua1829/app/src/main/java/com/example/architecture_project/feature/search/MainContract.kt
> +        fun getMovieData(keyword: String)
저는 입력받은 글자의 길이체크나 인터넷연결확인을 함수로 분리하였는데, 그런 것이나
지금 생각 나는 함수로는 만약 검색된 자료가 많을 경우 페이징을 할 때 
다음 페이지의 데이터로 교체해주는 함수라던지, 
아니면 페이지 별로 데이터를 요청할 수 있게끔 해주는 것도 좋을거 같아요. 
또는 데이터의 카테고리를 분류하는 함수도 존재할 수 있을 것 같아요.

2020-01-09 15:29 UTC, ghkdua1829 commented on ghkdua1829/app/src/main/java/com/example/architecture_project/feature/search/MainContract.kt
> +        fun noKeyword()
41fc30c6b939546d4092fa87c6bb9a7a1b938e15
수정할 사항 있으면 다시 말씀해주세요!! 감사해요 ㅎㅎ

2020-01-09 15:31 UTC, ghkdua1829 commented on ghkdua1829/app/src/main/java/com/example/architecture_project/feature/search/MainContract.kt
> +        fun getMovieData(keyword: String)
601703c9887aea4b5636587b4ab97899af4bb740
검색된 데이터의 총개수를 표현해주는 함수를 만들어봤습니다.

2020-01-09 15:41 UTC, handnew04 approved these changes
고생하셨습니다!

2020-01-10 04:34 UTC, sjjeong requested changes
함수명 바꾸는 것 외에는 잘 하셨습니다

2020-01-10 04:34 UTC, sjjeong commented on ghkdua1829/app/src/main/java/com/example/architecture_project/data/model/NaverApi.kt
> +    val item: ArrayList<Movie>
ArrayList보단 List형태로 받아주세요

2020-01-10 04:34 UTC, sjjeong commented on ghkdua1829/app/src/main/java/com/example/architecture_project/ui/main/MainContract.kt
> +        fun notAvailableKeyword()
이 함수도 show가 붙으면 좋겠네요

2020-01-11 01:26 UTC, ghkdua1829 commented on ghkdua1829/app/src/main/java/com/example/architecture_project/data/model/NaverApi.kt
> +    val item: ArrayList<Movie>
421dbc17616b6252a5b22b60553bc93e6e130330

2020-01-11 01:28 UTC, ghkdua1829 commented on ghkdua1829/app/src/main/java/com/example/architecture_project/ui/main/MainContract.kt
> +        fun notAvailableKeyword()
50a18a029de9636d552a4efcfc9efedfb6dbb998

2020-01-11 07:16 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-01-12 04:12 UTC, merged