HW-1 네이버 영화 검색 앱
sjjeong/GoogryAndroidArchitecutreStudy pull request #414
Opened 2020-01-07 16:52 UTC by devLibCH

2020-01-08 12:06 UTC, HudsonPark commented on class08/devLibCH/Study/app/build.gradle
> +        }
@devLibCH 저는 BuildConfigField를 사용해서 id와 secret을 불러왔는데 proguard-rules를 사용하는 게 보안 상 더 좋은 방법인가요?

2020-01-08 12:06 UTC, HudsonPark commented on class08/devLibCH/Study/app/build.gradle
> +    implementation 'gun0912.ted:tedpermission-rx2:2.2.2'
@devLibCH permission에 인터넷 권한 외에 다른 위험권한을 요청하시는 부분이 있나요? manifest에는 따로 요청하시는 게 없어서요

2020-01-08 12:06 UTC, HudsonPark commented on class08/devLibCH/Study/app/src/main/AndroidManifest.xml
> +        android:usesCleartextTraffic="true"
@devLibCH https://developside.tistory.com/85  덕분에 Glide4.0 Issue 내용 잘 알았습니다. 3.x version으로 쓰다보니 이런 이슈가 있는 줄 몰랐군요 :)

2020-01-08 12:06 UTC, HudsonPark commented on class08/devLibCH/Study/app/src/main/java/app/ch/study/core/App.kt
> +        }
@devLibCH 말로만 들었던 모듈화인가요?

2020-01-08 12:06 UTC, HudsonPark commented on class08/devLibCH/Study/app/src/main/java/app/ch/study/data/remote/parse/StudyRequestInterceptor.kt
> +}
@devLibCH 이 부분은 커니의 코틀린 책에서 Github API 예제에서 본 적이 있는데 아직 스터디가 안되서 이해가 안되네요... 스터디 해보겠습니다

2020-01-08 15:33 UTC, sjjeong requested changes
과제 내용은 우리가 앞으로 공부 할 것을 사용하지 않고 구현인데
이미 전부 다 사용해서 구현 하셨네요.
이렇게 하시면 앞으로 과제를 하기도 어렵고 짝꿍이 리뷰하기가 어렵습니다.
불편하시겠지만 앞으로 공부 할 것인 DataBinding, MVVM, AAC ViewModel, AAC LiveData, Koin을 사용하지 않고 과제를 구현해주세요

2020-01-09 01:01 UTC, devLibCH commented on class08/devLibCH/Study/app/build.gradle
> +        }
프로가드는 아니고 resValue 사용 방식인데 같은 방법이에요 
리소스에 내용을 추가할건지 자바에 추가할건지에 대한 방식이라서 저는 string같은 경우 리소스로 쓰고있어요

2020-01-09 01:03 UTC, devLibCH commented on class08/devLibCH/Study/app/build.gradle
> +    implementation 'gun0912.ted:tedpermission-rx2:2.2.2'
딱히 없습니다
소스 구현 전에 추가했다가 삭제를 안했네요

2020-01-09 01:10 UTC, devLibCH commented
다시 구현하겠습니다

2020-01-09 02:04 UTC, devLibCH commented on class08/devLibCH/Study/app/src/main/java/app/ch/study/data/remote/parse/StudyRequestInterceptor.kt
> +}
requst 할때 먼저 거치는 곳이에요 헤더 담는용으로 사용하고 있어요

2020-01-09 07:08 UTC, HudsonPark commented on class08/devLibCH/Study/app/src/main/java/app/ch/study/data/remote/api/WebApiTask.kt
> +    private var Interface: WebApi? = null
API의 경우 변수 네이밍이 대문자로 시작하는건가요?

2020-01-09 07:12 UTC, devLibCH commented on class08/devLibCH/Study/app/src/main/java/app/ch/study/data/remote/api/WebApiTask.kt
> +    private var Interface: WebApi? = null
아뇨 이건 제가 잘못 써놓았네요

2020-01-09 07:16 UTC, devLibCH commented on class08/devLibCH/Study/app/src/main/java/app/ch/study/data/remote/api/WebApiTask.kt
> +    private var Interface: WebApi? = null
1285835

2020-01-09 12:30 UTC, sjjeong commented
@HudsonPark 
approve도 해주세요

2020-01-09 13:13 UTC, sjjeong requested changes

2020-01-09 13:13 UTC, sjjeong commented on class08/devLibCH/Study/app/build.gradle
> +        }
@HudsonPark @devLibCH 
저는 res로 하면 context를 통해서 가져와야하는 불편함이 있어서 Field로 하곤 해요

2020-01-09 13:13 UTC, sjjeong commented on class08/devLibCH/Study/app/src/main/java/app/ch/study/view/DetailActivity.kt
> +        val url = intent.getStringExtra("url")
url을 리터럴로 사용하지 마시고 상수로 빼서 사용하면 좋습니다.

2020-01-09 13:13 UTC, sjjeong commented on class08/devLibCH/Study/app/src/main/java/app/ch/study/view/MainActivity.kt
> +        compositeDisposable.clear()
보통 pause stop destroy에서는 super를 맨 마지막에 호출하고
compositeDisposable.clear()같은 함수를 먼저 호출합니다.

2020-01-09 13:13 UTC, sjjeong commented on class08/devLibCH/Study/app/src/main/java/app/ch/study/view/MainActivity.kt
> +                        adapter = MovieAdapter(this, list as ArrayList<MovieModel>, this)
어뎁터를 매번 만들어 줄 필요는 없습니다.
init하는 시점에 한번만 만들어서 넣어주면 됩니다.

2020-01-09 13:13 UTC, sjjeong commented on class08/devLibCH/Study/app/src/main/java/app/ch/study/view/MovieAdapter.kt
> +    private val context: Context,
context를 받을 필요가 없습니다.

2020-01-09 13:13 UTC, sjjeong commented on class08/devLibCH/Study/app/src/main/java/app/ch/study/view/MovieAdapter.kt
> +    private val list: ArrayList<MovieModel>,
list는 생성자로 받지 마시고 
내부적으로 private val로 관리해주시면 됩니다.

2020-01-09 13:13 UTC, sjjeong commented on class08/devLibCH/Study/app/src/main/java/app/ch/study/view/MovieAdapter.kt
> +            itemParent.setOnClickListener {
클릭 리스너는 onCreateViewHolder 시점에 한번만 해주면 됩니다.

2020-01-09 13:13 UTC, sjjeong commented on class08/devLibCH/Study/app/src/main/java/app/ch/study/view/MovieAdapter.kt
> +    interface EventListener {
interface말고 higher-order function으로 해보세요

2020-01-10 04:01 UTC, devLibCH commented on class08/devLibCH/Study/app/src/main/java/app/ch/study/view/DetailActivity.kt
> +        val url = intent.getStringExtra("url")
a799031 
e8aaf26

2020-01-10 04:02 UTC, devLibCH commented on class08/devLibCH/Study/app/src/main/java/app/ch/study/view/MovieAdapter.kt
> +    interface EventListener {
e1266f8

2020-01-10 04:02 UTC, devLibCH commented on class08/devLibCH/Study/app/src/main/java/app/ch/study/view/MainActivity.kt
> +                        adapter = MovieAdapter(this, list as ArrayList<MovieModel>, this)
d40a16d

2020-01-10 04:02 UTC, devLibCH commented on class08/devLibCH/Study/app/src/main/java/app/ch/study/view/MovieAdapter.kt
> +    private val context: Context,
fd2e9bf

2020-01-10 04:02 UTC, devLibCH commented on class08/devLibCH/Study/app/src/main/java/app/ch/study/view/MovieAdapter.kt
> +    private val list: ArrayList<MovieModel>,
116d76d

2020-01-10 04:47 UTC, devLibCH commented on class08/devLibCH/Study/app/src/main/java/app/ch/study/view/MainActivity.kt
> +        compositeDisposable.clear()
10e6809

2020-01-10 04:48 UTC, devLibCH commented on class08/devLibCH/Study/app/src/main/java/app/ch/study/view/MovieAdapter.kt
> +            itemParent.setOnClickListener {
e1266f8

2020-01-10 12:41 UTC, HudsonPark approved these changes

2020-01-11 04:57 UTC, sjjeong commented on class08/devLibCH/Study/app/build.gradle
> +        }
@HudsonPark @devLibCH 
확인해보세요

2020-01-11 04:58 UTC, sjjeong commented on class08/devLibCH/Study/app/build.gradle
> +        }
@HudsonPark @devLibCH
확인해보세요

2020-01-11 06:43 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-01-12 12:48 UTC, merged