HW-5 Databinding
sjjeong/GoogryAndroidArchitecutreStudy pull request #415
Opened 2020-01-07 18:00 UTC by JayYi

5주차 과제 Databinding 적용하였습니다. 리뷰 부탁드립니다.

@wooooooak 
용준님 리뷰 남길 때 BindingAdapter에 구현을 간단하게 하는 것이 좋지 않을까라는 의견을 말했는데, 
막상 실제 코드를 진행하다 보니 저도 용준님이랑 비슷하게 BindingAdapter를 많이 사용하는 쪽으로 코드를 작성했네요;;; 코드 작성하면서 용준님이 왜 저렇게 했을까라는 맘을 십분 이해 했습니다.

2020-01-08 12:08 UTC, gitpushyj requested changes
리뷰 완료했습니다 :D

2020-01-08 12:08 UTC, gitpushyj commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/ui/blog/BlogFragment.kt
> +            }
프로퍼티를 set해주는 setter가 실제로는 프로퍼티를 set하지 않기 때문에, field는 항상 BaseSearchContract.ViewType.VIEW_SEARCH_BEFORE 일테니 위의 코드는 아래와 같지 않나요??
```kotlin
...
set(value) {
    if (BaseSearchContract.ViewType.VIEW_SEARCH_BEFORE != value) {
        binding.viewType = field
        binding.invalidateAll()
    }
```
setter를 사용하고 있기 때문에 해당 프로퍼티의 값이 바뀔거라 예상하고 코드를 보았는데, 실제 field는 바뀌지 않아서 조금 의문이 들었습니다...

의도하신건지는 모르겟지만, 만약 setter가 set을 하지 않도록 의도하신거라면 if문의 field는 굳이 유추하지 않아도 되게 BaseSearchContract.ViewType.VIEW_SEARCH_BEFORE로 고정시키는건 어떤가요?

2020-01-08 12:08 UTC, gitpushyj commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/ui/blog/BlogFragment.kt
>          activity?.let { activity ->
let 블록에서 activity와 같이 쓰이지 않는 값은 _ 로 선언해 주시는게 권장되는걸로 알고 있어요 ㅎㅎ
그런데 activity?.let이 onActivityCreated에서 꼭 필요한 부분인가요..?

2020-01-08 12:08 UTC, gitpushyj commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/ui/image/ImageAdapter.kt
> +        )
ListItemImageBinding 클래스에서 제공되는 inflate를 사용하면 더 깔끔하게 작성됩니다!
```kotlin
val binding2 = ListItemMovieBinding.inflate(LayoutInflater.from(parent.context), parent, false)
```

2020-01-08 12:08 UTC, gitpushyj commented on JayYi/ArchitectureStudy/app/src/main/res/layout/fragment_image.xml
> +            visible="@{viewType == ViewType.VIEW_SEARCH_NO_RESULT ? true : false}"
visibility가 두개가 있는데 이렇게 되면 항상 visibility가 gone인 건가요..?

2020-01-08 12:08 UTC, gitpushyj commented on JayYi/ArchitectureStudy/app/src/main/res/layout/list_item_kin.xml
> +        android:clickable="true"
이 clickable=true는 false로 막는 경우가 있기 때문에 선언하신건가요?
보통 항상 clickable하다면 해당 프로퍼티를 명시적으로 true로 하지 않기 때문에 없애시는게 덜 혼란스러울것 같습니다.!
의도적으로 명시하신거라면 다른 default 값들도 명시적으로 넣어주시는게 통일성이 있을것 같아요 ㅎㅎ

2020-01-08 12:08 UTC, gitpushyj commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/util/RecyclerViewExt.kt
> +}
뷰가 갱신될때 마다 계속해서 ItemDecoration이 add될것 같아요!

2020-01-08 12:08 UTC, wooooooak commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/ui/image/ImageFragment.kt
>              }
run을 없애고 binding.recyclerView.adapter = movieAdapter 이렇게 한줄로 가능할것 같은데 혹시 run을 남겨두신 이유가 있으신가요?

2020-01-08 12:08 UTC, wooooooak commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/MainActivity.kt
> +        binding.main.viewPager.addOnPageChangeListener(pageChangeListener)
with나 run 함수를 이용하면 가독성이 더 좋을것 같아요!

2020-01-08 14:32 UTC, JayYi commented on JayYi/ArchitectureStudy/app/src/main/res/layout/fragment_image.xml
> +            visible="@{viewType == ViewType.VIEW_SEARCH_NO_RESULT ? true : false}"
tools는 preview에만 반영되고 runtime 때는 반영이 되지 않아요.

2020-01-08 14:35 UTC, JayYi commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/ui/blog/BlogFragment.kt
>          activity?.let { activity ->
원래는 제거를 했어야 했는데 미쳐 제거 하지 못했습니다.
하지만 해당 코드 내에 adapter 코드를 다시 롤백하게 되어서 다시 선언했습니다.
참고바래요.
1f3acf4f0100ee6c3cc3d1c3affaf4d842336663

2020-01-08 14:36 UTC, JayYi commented on JayYi/ArchitectureStudy/app/src/main/res/layout/list_item_kin.xml
> +        android:clickable="true"
잘못 선언 했었네요.
수정했습니다.

2e2f04ba161b86f04190e74c99b2e45cb4e12989

2020-01-08 14:36 UTC, JayYi commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/util/RecyclerViewExt.kt
> +}
좋은 방향으로 개선이 힘들어 보여 제거 하였습니다.
1f3acf4f0100ee6c3cc3d1c3affaf4d842336663

2020-01-08 14:37 UTC, JayYi commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/ui/image/ImageFragment.kt
>              }
해당 코드는 RecyclerViewExt 제거 되면서 기존 코드로 롤백했어요.
참고 바랍니다.
1f3acf4f0100ee6c3cc3d1c3affaf4d842336663

2020-01-08 14:38 UTC, JayYi commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/MainActivity.kt
> +        binding.main.viewPager.addOnPageChangeListener(pageChangeListener)
수정했습니다.
62b67f6021468b155bf7572e325341f766a315c8

2020-01-08 14:41 UTC, JayYi commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/ui/blog/BlogFragment.kt
> +            }
버그였어요. 수정했습니다.
e67f7d0c290b28c6748d485d7c3752e2422f0bee

2020-01-08 14:48 UTC, JayYi commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/ui/image/ImageAdapter.kt
> +        )
수정했습니다.
b4b65b95f1930e5b9b2c3fb79a3980fab5831c9c

개인적으로는 해당 코드는 깔끔하다는 느낌보다는 선언하는 스타일이 문제로 생각이 드네요.  Databinding 선언하는 방법이 여러개 있다보니 어느 것을 쓰는게 좋을지 약간 혼란이 오네요.

2020-01-08 23:03 UTC, wooooooak commented on JayYi/ArchitectureStudy/app/src/main/res/layout/fragment_image.xml
> +            visible="@{viewType == ViewType.VIEW_SEARCH_NO_RESULT ? true : false}"
tools를 제외하고visibility 속성과 bindingAdapter위 visible이 같이 존재하는것 같아요.

2020-01-09 00:35 UTC, JayYi commented on JayYi/ArchitectureStudy/app/src/main/res/layout/fragment_image.xml
> +            visible="@{viewType == ViewType.VIEW_SEARCH_NO_RESULT ? true : false}"
55번째 줄을 확인을 못했네요.
onCreate에서 ViewType을 갱신하는 시점에서 visibility가 visible 상태로 되었나보내요. 
그래서 실행할 때 발견을 못했네요..
감사합니다!

acf14a56618f62ae0f2f7b73a83394ea8ac48375

2020-01-09 10:15 UTC, gitpushyj approved these changes
수고하셨습니다~!

2020-01-09 12:08 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-01-10 06:14 UTC, merged