HW-2 Model 분리하기
sjjeong/GoogryAndroidArchitecutreStudy pull request #416
Opened 2020-01-07 21:07 UTC by seunghee63

2주차 과제입니다.
3주차 과제와 추가기능구현을 바로 이어서 진행하다가 push 를 해버려서.. 3주차 commit 몇개가 같이 올라갔는데.. HW-2 내용 까지만 리뷰 해 주시면 감사하겠습니다! 번거롭게해서 죄송해요ㅜ.ㅜ!

3주차는 2주차 내용이 merge되면 바로 PR 날리도록 하겠습니다!

2020-01-08 16:29 UTC, sjjeong commented
@seunghee63 
3주차는 branch를 별도로 만들어서 작업하시고
class07/seunghee63 브랜치는 2주차까지 과제 마무리 한 곳으로 reset hard하신 다음에 force push 해주세요

2020-01-09 09:47 UTC, seunghee63 commented
> @seunghee63
> 3주차는 branch를 별도로 만들어서 작업하시고
> class07/seunghee63 브랜치는 2주차까지 과제 마무리 한 곳으로 reset hard하신 다음에 force push 해주세요

f40c165
3주차 과제는 별도로 branch 만든 후, 이전에 작업하던 내용들을 모두 이동시키고 이어서 작업하였습니다.
현재 PR에는 3주차 커밋 내용들은 모두 reset 한 후 강제 push 하였습니다.

@AhnHyeonho 
현재 PR에 올라온 내용들만 리뷰 해 주시면 될 것 같습니다!
감사합니다 :>

2020-01-10 07:30 UTC, AhnHyeonho commented on seunghee63/MyApplication/app/src/main/java/com/song2/myapplication/ui/MainActivity.kt
> +    private lateinit var imm: InputMethodManager
inputMethodManager를 lateinit으로선언하신 이유가 다른 메소드에서도 해당 변수가 필요한 경우 쓸데없는 호출을 줄이기 위한 의도이신 것 같은데 아래 getMovieData() 메소드에있는 코드처럼
```kotlin
imm = getSystemService(Context.INPUT_METHOD_SERVICE) as InputMethodManager
imm.hideSoftInputFromWindow(et_main_act_search.windowToken, 0)
```
초기화를 해주신다면 getMovieData()메소드 말고 다른 메소드에서도 해당변수가 필요한 경우
```kotlin
imm = getSystemService(Context.INPUT_METHOD_SERVICE) as InputMethodManager
```
이 부분을 반복적으로 작성하게 될 것 같습니다.
lateinit 보단 by lazy로 처리해주는게 좋을 것 같습니다...!

2020-01-10 07:30 UTC, AhnHyeonho commented on seunghee63/MyApplication/app/src/main/java/com/song2/myapplication/ui/MainActivity.kt
> +        //TODO : 이전 데이터에 이어서 추가로 데이터를 받아오는 방법에 대한 기능 구현
간단한 설명 주석이면 TODO는 지워주는게 좋을 것 같습니다!

2020-01-10 07:30 UTC, AhnHyeonho commented on seunghee63/MyApplication/app/src/main/java/com/song2/myapplication/ui/MainActivity.kt
> +                setNoResult(it.count())
해당 코드를 보고 저도 검색결과가 0개인 경우의 핸들링을 추가해 보았습니다. 
현재 작성하신 코드는 view에서 검색결과 개수(data)를 판단하기 때문에 model쪽에서 처리를 해주는게 옳다고 생각합니다. 
아래는 제가 작성한 코드인데 참고하셔서 수정해보셨으면 좋겠습니다...!

[참고 - 검색결과가 0인 경우처리 추가](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/407/commits/f4e016582b8e74fd3eebc402cd04715b2a28291b)

2020-01-13 11:28 UTC, sjjeong requested changes
Practice로 만든 프로젝트는 제거해 주세요

2020-01-13 11:28 UTC, sjjeong commented on seunghee63/MyApplication/app/src/main/java/com/song2/myapplication/source/local/MovieLocalDataSource.kt
> +object MovieLocalDataSource : MovieLocalDataSourceImpl {
서로 이름이 반대로 되어있습니다.

2020-01-13 11:28 UTC, sjjeong commented on seunghee63/MyApplication/app/src/main/java/com/song2/myapplication/source/remote/MovieRemoteDataSource.kt
> +object MovieRemoteDataSource : MovieRemoteDataSourceImpl {
서로 이름이 반대로 되어있습니다.

2020-01-13 11:28 UTC, sjjeong commented on seunghee63/MyApplication/app/src/main/java/com/song2/myapplication/ui/MainActivity.kt
> +                setNoResult(it.count())
여기서 해도 괜찮습니다

2020-01-13 11:28 UTC, sjjeong commented on seunghee63/MyApplication/app/src/main/java/com/song2/myapplication/ui/MainActivity.kt
> +        //TODO : 이전 데이터에 이어서 추가로 데이터를 받아오는 방법에 대한 기능 구현
구현을 완료 했다면 TODO주석은 제거해주세요

2020-01-13 14:01 UTC, seunghee63 commented on seunghee63/MyApplication/app/src/main/java/com/song2/myapplication/ui/MainActivity.kt
> +    private lateinit var imm: InputMethodManager
9988a15

2020-01-13 14:03 UTC, seunghee63 commented on seunghee63/MyApplication/app/src/main/java/com/song2/myapplication/ui/MainActivity.kt
> +        //TODO : 이전 데이터에 이어서 추가로 데이터를 받아오는 방법에 대한 기능 구현
HW-3 작업을 하던 브랜치에서 내용을 수정하였습니다!

9c54517

2020-01-13 14:03 UTC, seunghee63 commented on seunghee63/MyApplication/app/src/main/java/com/song2/myapplication/source/local/MovieLocalDataSource.kt
> +object MovieLocalDataSource : MovieLocalDataSourceImpl {
82ec482

2020-01-13 14:03 UTC, seunghee63 commented on seunghee63/MyApplication/app/src/main/java/com/song2/myapplication/source/remote/MovieRemoteDataSource.kt
> +object MovieRemoteDataSource : MovieRemoteDataSourceImpl {
82ec482

2020-01-13 14:05 UTC, seunghee63 commented on seunghee63/MyApplication/app/src/main/java/com/song2/myapplication/source/local/MovieLocalDataSource.kt
> +object MovieLocalDataSource : MovieLocalDataSourceImpl {
82ec482

2020-01-13 14:11 UTC, closed without merging