HW-7 AAC ViewModel, LiveData 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #417
Opened 2020-01-08 14:11 UTC by bean628

Delegate 제거 및 AAC ViewModel, Live Data 적용

2020-01-09 10:12 UTC, ironelder reviewed
음.. 제 맥이 이상한건지 모르겠는데 ... 영화만 자꾸 네트워크 에러를 뱉어내는것 같아요
다른탭을 한번씩 실행시키고 다시 영화탭에오면 검색이 안되는 것 같습니다~

2020-01-09 10:12 UTC, ironelder commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/main/MainViewModel.kt
> +        if (TextUtils.isEmpty(query.value)) {
TextUtils를 사용하신 이유가 있는지 궁금합니다
String에서 자체적으로 지원하는 isNullOrEmpty를 사용하시면 어떨까요?
```
query.value.isNullOrEmpty()
```

2020-01-09 10:12 UTC, ironelder commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/main/MainViewModel.kt
> +    val eventGoToHistoryActivity = MutableLiveData<Boolean>(false)
여기 빌드오류 발생하는 것 같습니당 ^^;;

2020-01-09 10:12 UTC, ironelder commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/main/MainViewModel.kt
> +    val eventGoToHistoryActivity = MutableLiveData<Boolean>(false)
빌드 등급 낮추니까 사라지긴하는데... 혹시 초기값을 위해서라면...
```
val query = MutableLiveData<String>().default("")
fun <T : Any?> MutableLiveData<T>.default(initialValue: T) = apply { setValue(initialValue) }
```
이런식은 어떠신가요?

2020-01-09 10:12 UTC, ironelder commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/data/source/local/NaverLocalDataSourceImpl.kt
> +    fun setCache(searchType: SearchType?, word: String?, list: List<SearchedItem>) {
nullable로 변경하신 이유가 있으신지 궁금합니다

2020-01-10 12:28 UTC, bean628 commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/main/MainViewModel.kt
> +        if (TextUtils.isEmpty(query.value)) {
저도 query.value.isEmpty(), query.value.isNullOrEmpty() 이런 형태로 써보려고 했지만 에러가 나더라구요. query.value!!.isEmpty() 이렇게 하면 에러가 나지는 않기는한데 저렇게 써도되는지를 판단을 못하겠어서 TextUtils가 더 익숙하다보니 TextUitls를 썻습니다. 
혹시 이 부분에 대해 아시는거 있으면  알려주세요~!

2020-01-10 12:38 UTC, bean628 commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/main/MainViewModel.kt
> +    val eventGoToHistoryActivity = MutableLiveData<Boolean>(false)
알려주신 방법으로 수정했습니다!
22f9868e

무슨 차이인지 잘 모르겠어서
MutableLiveData(T value) 생성자 코드
`    
public LiveData(T value) {
        mData = value;
        mVersion = START_VERSION + 1;
}
`
setValue(T value) 함수 코드 부분

`
    @MainThread
    protected void setValue(T value) {
        assertMainThread("setValue");
        mVersion++;
        mData = value;
        dispatchingValue(null);
    }
`

인데 초기화 할 때 생성자와 다르게 setValue의 이점이 뭔지를 잘 모르겠습니다...

2020-01-10 12:41 UTC, bean628 commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/data/source/local/NaverLocalDataSourceImpl.kt
> +    fun setCache(searchType: SearchType?, word: String?, list: List<SearchedItem>) {
이때 뭔가 작업하면서 nullable해야 작업이 진행됐었던거 같은데 다시 해보니
nonNull로 작업을 해도 괜찮네요... 잉... ㅎㅎ  수정했습니다!!

8fc19cd0

2020-01-10 12:43 UTC, ironelder commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/main/MainViewModel.kt
> +        if (TextUtils.isEmpty(query.value)) {
오잉........저는 에러 안나던데... 클린하고 하셔도 에러 나시나요;;;

2020-01-10 12:44 UTC, ironelder commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/main/MainViewModel.kt
> +    val eventGoToHistoryActivity = MutableLiveData<Boolean>(false)
저도 사실 잘 몰라요... 미안해요... 그냥 빨간줄 쳐서 나오길래... 수정해봤어요 ㅎㅎㅎ

2020-01-10 12:44 UTC, bean628 commented
> 음.. 제 맥이 이상한건지 모르겠는데 ... 영화만 자꾸 네트워크 에러를 뱉어내는것 같아요
> 다른탭을 한번씩 실행시키고 다시 영화탭에오면 검색이 안되는 것 같습니다~


재현을 해보니 저는 그런 에러가 뜨지 않긴하는데.. 음...  DB 작업했던거 때문인가.....?
혹시 지웠다가 다시 설치해도 같은 에러가 발생하나요?

2020-01-10 14:29 UTC, bean628 commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/main/MainViewModel.kt
> +        if (TextUtils.isEmpty(query.value)) {
넵 클린, 리빌드, 인발리드 캐시까지 했는데 에러나요 먼가 코틀린 언어 버전이나 그래들 버전 차이로 인한걸수도있을것 같습니다

2020-01-10 14:32 UTC, bean628 commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/main/MainViewModel.kt
> +    val eventGoToHistoryActivity = MutableLiveData<Boolean>(false)
괜찮아요~ 모르기 때문에 알려고 저희가 공부하는 거니까요. 모르는거에서 아는걸로 하나씩 바꿔가는거죠 뭐 ㅎㅎㅎ
석준님은 아시겠죠 ㅎㅎㅎ

2020-01-11 08:30 UTC, sjjeong requested changes

2020-01-11 08:30 UTC, sjjeong commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/history/HistoryActivity.kt
> +            movieOrBookItems.observe(this@HistoryActivity, Observer {
list를 BindingAdapter를 사용해서 ui에 뿌려지게 만들어보세요

2020-01-12 02:18 UTC, bean628 commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/history/HistoryActivity.kt
> +            movieOrBookItems.observe(this@HistoryActivity, Observer {
기존에 어뎁터가 2개였었는데 하나로 합치고 수정했습니다.

63889429
df36aa67

2020-01-12 02:43 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-01-12 06:20 UTC, ironelder approved these changes

2020-01-12 06:20 UTC, merged