HW-6 MVVM 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #418
Opened 2020-01-08 19:08 UTC by taeiim

2020-01-10 13:54 UTC, 2giwon requested changes

2020-01-10 13:54 UTC, 2giwon commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/ContentsFragment.kt
> +                if (vm?.getQueryStr()!!.isBlank()) {
!! 는 지양 하는 것이 좋을 듯 합니다. vm 널체크로 표준 스코프 메소드(let, 등)을 사용하면 되지 않을까요?

2020-01-10 13:54 UTC, 2giwon commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/ContentsFragment.kt
> +                    blankSearchQuery()
여기서 에러를 체크하는 것 보다 뷰모델에서 체크해서 뷰에서는 에러 값만 옵저브하여 보여주는게 나을 듯 합니다.

2020-01-10 13:54 UTC, 2giwon commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/ContentsFragment.kt
> +                } ?: failToSearch()
뷰모델에서 널을 보내서 널인 경우 에러체크를 하는 것 같습니다. 널을 보내서 받는 쪽에서 에러를 체크하는 것은 좋은 코딩이 아닌 듯 합니다. 

전달 해주는 뷰모델에서 에러일 경우 에러 옵저버블 필드로 값을 보내주고 뷰에서 옵저브하여 처리하는게 낫지 않을까 생각합니다.

2020-01-10 13:54 UTC, 2giwon commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/ContentsViewModel.kt
> +    val query = ObservableField<String>()
이 값이 옵저버블 필드가 아니어도 되지 않나요?

2020-01-10 13:54 UTC, 2giwon commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/ContentsViewModel.kt
> +            searchResultList.set(null)
null 을 보내는 것은 좋지 않은 것 같습니다. 뷰모델에서 블랭크인 경우 에러 옵저버블 필드에 값을 셋팅하는 것은 어떨까요?

2020-01-12 23:36 UTC, taeiim commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/ContentsFragment.kt
> +                if (vm?.getQueryStr()!!.isBlank()) {
blank 처리를 viewModel에서 하도록 변경하여 해당 코드는 삭제되었습니다.

2020-01-12 23:37 UTC, taeiim commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/ContentsFragment.kt
> +                    blankSearchQuery()
변경하였습니다ㅎㅎ 

commit : 7d9e21d642821f943147f84e2c9e85a1acdf0f2b

2020-01-12 23:37 UTC, taeiim commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/ContentsFragment.kt
> +                } ?: failToSearch()
변경하였습니다 ! 감사합니다!!!! ㅎㅎ

commit : 7d9e21d642821f943147f84e2c9e85a1acdf0f2b

2020-01-12 23:38 UTC, taeiim commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/ContentsViewModel.kt
> +    val query = ObservableField<String>()
오우.. 그렇네요!! 변경하였습니다 

commit : 52bf161a6dd2d47bc16e7465eb5a1121f9610df2

2020-01-12 23:38 UTC, taeiim commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/ContentsViewModel.kt
> +            searchResultList.set(null)
commit : 7d9e21d642821f943147f84e2c9e85a1acdf0f2b

2020-01-13 11:18 UTC, sjjeong approved these changes
6주차 과제에는 6주차만 올라오게 해야 합니다.
일단 머지 해주시고 다음 부터는 과제 하실때 rebase해서 pr 만들어주세요

2020-01-14 14:11 UTC, 2giwon approved these changes
수고 하셨습니다.

2020-01-14 15:39 UTC, merged