HW3. MVP적용. Class07/swppppp
sjjeong/GoogryAndroidArchitecutreStudy pull request #419
Opened 2020-01-09 06:49 UTC by swppppp

mvp구조 적용

앞에 코드리펙토링한부분 추가되어있습니다!!

2020-01-10 04:27 UTC, 172900 requested changes

2020-01-10 04:27 UTC, 172900 commented on swppppp/app/src/main/java/com/siwon/prj/MainPresenter.kt
> +    val repository: MovieSearchRepository by inject()
koin을 사용하시면 Presenter도 의존성 주입 방식으로 바꾸는게 좋습니다.
모듈에 factory로 presenter선언해주시고
activity에서 by inject()로 view 넘겨주면서 주입하면 깔끔 할 것 같습니다.

2020-01-12 04:43 UTC, swppppp commented on swppppp/app/src/main/java/com/siwon/prj/MainPresenter.kt
> +    val repository: MovieSearchRepository by inject()
activity에서 
by inject{ parametersOf(this)}
이런식으로 view넘겨주면서 주입하려했는데 계속 실패하네요ㅠㅠㅠㅠ혹시 다른방법을 사용해야하는건가요?

2020-01-12 04:52 UTC, 172900 commented on swppppp/app/src/main/java/com/siwon/prj/MainPresenter.kt
> +    val repository: MovieSearchRepository by inject()
@swppppp 
지금 알바 가야해서 자세히는 못봐드려가지고
제가 리뷰하면서 제 프로젝트에 Koin적용한거 PR에 올려놨는데 한번 비교하면서 확인해보시겠어요?
presenter랑 repository등등 DI로 빼뒀고 완벽하게 돌아가는 코드예요

2020-01-12 05:13 UTC, swppppp commented on swppppp/app/src/main/java/com/siwon/prj/MainPresenter.kt
> +    val repository: MovieSearchRepository by inject()
937c4116

감사해요!!! 모듈에 bind써서 해결이되었군요..!!!

2020-01-12 06:17 UTC, 172900 approved these changes

2020-01-12 08:09 UTC, sjjeong requested changes
koin은 나중에 공부할 내용이어서 이번 과제에서는 제거해주세요

2020-01-15 01:19 UTC, swppppp commented
koinㅈㅔ거했습니다!!

2020-01-17 15:11 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-01-18 01:03 UTC, merged