HW-3 MVP 패턴 구현
sjjeong/GoogryAndroidArchitecutreStudy pull request #420
Opened 2020-01-09 10:20 UTC by seunghee63

2주차 과제가 아직 merge되지 않아 PR을 날리면 겹치는 부분이 있어서
새로운 브랜치를 파서 3주차 과제를 진행하였습니다. 

그러다 보니 앞부분에 3주차 이전의 커밋내용이 같이 올라왔는데, 뒷부분 부터 봐주시면 감사하겠습니다!..!

2020-01-10 08:07 UTC, AhnHyeonho commented on seunghee63/MyApplication/app/src/main/java/com/song2/myapplication/adapter/MovieAdapter.kt
> +        Log.e("setMovieList 데이터1", newMovieList.toString())
배포 시에도 쓰이지 않는 로그라면 지워주시는게 좋을 것 같습니다.

2020-01-10 08:07 UTC, AhnHyeonho commented on seunghee63/MyApplication/app/src/main/java/com/song2/myapplication/adapter/MovieAdapter.kt
> +            Log.e("setMovieList 데이터", newMovieList.toString())
배포 시에도 쓰이지 않는 로그라면 지워주시는게 좋을 것 같습니다.

2020-01-10 08:07 UTC, AhnHyeonho commented on seunghee63/MyApplication/app/src/main/java/com/song2/myapplication/adapter/MovieViewHolder.kt
>      private val actor: TextView = view.findViewById(R.id.tv_rv_movie_item_actor)
굳이 findViewById를 쓰신 이유가 궁금합니다...!

2020-01-13 11:31 UTC, sjjeong requested changes

2020-01-13 11:31 UTC, sjjeong commented on seunghee63/MyApplication/app/src/main/java/com/song2/myapplication/ui/MainActivity.kt
> +        imm.hideSoftInputFromWindow(et_main_act_search.windowToken, 0)
함수로 따로 빼주세요

2020-01-13 11:31 UTC, sjjeong commented on seunghee63/MyApplication/app/src/main/java/com/song2/myapplication/ui/MainActivity.kt
> +        if (movieDataList.count() == 0) {
이 로직들은 Presenter에서 처리하고 VISIBLE, GONE을 처리해주는 각각 함수를 만들어주세요

2020-01-13 11:31 UTC, sjjeong commented on seunghee63/MyApplication/app/src/main/java/com/song2/myapplication/ui/MainContract.kt
> +        fun getMoreMovie(keyword: String)
두개 함수는 하나로 만들 수 있습니다.

2020-01-13 13:51 UTC, seunghee63 commented on seunghee63/MyApplication/app/src/main/java/com/song2/myapplication/ui/MainContract.kt
> +        fun getMoreMovie(keyword: String)
기능 추가하면서 전반적으로 조금 손을 봤는데, 수정 할 내용 있으면 첨언 부탁드립니다!

9c54517

2020-01-13 13:51 UTC, seunghee63 commented on seunghee63/MyApplication/app/src/main/java/com/song2/myapplication/ui/MainActivity.kt
> +        if (movieDataList.count() == 0) {
f2024f4

2020-01-13 13:52 UTC, seunghee63 commented on seunghee63/MyApplication/app/src/main/java/com/song2/myapplication/adapter/MovieAdapter.kt
> +            Log.e("setMovieList 데이터", newMovieList.toString())
6a3e7ea

2020-01-13 13:56 UTC, seunghee63 commented on seunghee63/MyApplication/app/src/main/java/com/song2/myapplication/adapter/MovieViewHolder.kt
>      private val actor: TextView = view.findViewById(R.id.tv_rv_movie_item_actor)
평상시에 습관처럼 뷰홀더에서는 findViewById로 아이디를 불러와서 그랬던 것 같습니다.
수정했습니다~

28b0f73

2020-01-13 14:00 UTC, seunghee63 commented on seunghee63/MyApplication/app/src/main/java/com/song2/myapplication/ui/MainActivity.kt
> +        imm.hideSoftInputFromWindow(et_main_act_search.windowToken, 0)
변수선언 방식을 바꾸었더니 굳이 함수를 만들 필요가 없는 것 같아서 일단은 그대로 두었습니다!
변경해야 한다면 말씀 해 주시면 감사하겠습니다!

9988a15

2020-01-15 12:12 UTC, sjjeong commented on seunghee63/MyApplication/app/src/main/java/com/song2/myapplication/ui/MainContract.kt
> +        fun getMoreMovie(keyword: String)
다음시간에 pagination 하는 방법 질문해주세요

2020-01-15 12:12 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-01-15 14:29 UTC, seunghee63 commented on seunghee63/MyApplication/app/src/main/java/com/song2/myapplication/ui/MainContract.kt
> +        fun getMoreMovie(keyword: String)
넵 알겠습니다 :> !!!

2020-01-16 15:02 UTC, merged