HW-8 KOIN 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #422
Opened 2020-01-12 15:21 UTC by 2giwon

- DI 코인 적용

2020-01-14 15:25 UTC, taeiim approved these changes

2020-01-15 01:21 UTC, BeokBeok requested changes
안녕하세요. 스터디 2기 강현석이라고 합니다.

부족하지만 잘 부탁드립니다.:sweat_smile:

2020-01-15 01:21 UTC, BeokBeok commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/base/BaseViewModel.kt
> +    val showErrorText: LiveData<Int> get() = errorText
변수명과 타입이 어울리지 않는 것 같습니다.
타입에 맞는 변수명으로 바꾸시면 좋을 것 같습니다.

2020-01-15 01:21 UTC, BeokBeok commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/base/BaseFragment.kt
>      }
접근자를 추가해주시면 좋을 것 같습니다.

2020-01-15 01:21 UTC, BeokBeok commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/di/DataSourceModule.kt
> +    single { ContentDataBase.getInstance(context = androidContext()).contentDao() }
DataBase 도 koin 을 사용하여 만들어주시면 좋을 것 같습니다.

2020-01-15 01:21 UTC, BeokBeok commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/di/NetworkModule.kt
> +                    )
이 부분도 객체이므로, koin 을 사용하여 만들어주시면 좋을 것 같습니다.

2020-01-15 01:21 UTC, BeokBeok commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/di/NetworkModule.kt
> +                    }
이 부분도 객체이므로, koin 을 사용하여 만들어주시면 좋을 것 같습니다.

2020-01-15 01:21 UTC, BeokBeok commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/di/NetworkModule.kt
> +            .addConverterFactory(GsonConverterFactory.create())
이 부분도 객체이므로, koin 을 사용하여 만들어주시면 좋을 것 같습니다.

2020-01-15 01:21 UTC, BeokBeok commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/di/NetworkModule.kt
> +            .create(ContentsService::class.java)
이 부분도 객체이므로, koin 을 사용하여 만들어주시면 좋을 것 같습니다.

2020-01-15 01:21 UTC, BeokBeok commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/ui/TabsFragment.kt
>          vp_contents.apply {
apply 대신 run 혹은 with 를 쓰는 것이 좋을 것 같습니다.

2020-01-15 01:21 UTC, BeokBeok commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/ui/tabs/ContentsFragment.kt
> +    override fun onActivityCreated(savedInstanceState: Bundle?) {
onActivityCreated 보다는 onViewCreated 가 더 좋을 것 같습니다.

2020-01-15 13:56 UTC, 2giwon commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/base/BaseViewModel.kt
> +    val showErrorText: LiveData<Int> get() = errorText
수정했습니다

a08f428235ba225b78fd721574d373f387814631

2020-01-15 13:56 UTC, 2giwon commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/base/BaseFragment.kt
>      }
수정했습니다.
cb03fe669b660aeee2f194b79d83fd2e41fce241

2020-01-15 13:57 UTC, 2giwon commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/di/DataSourceModule.kt
> +    single { ContentDataBase.getInstance(context = androidContext()).contentDao() }
데이터 베이스도 koin으로 적용했습니다.

bbf22efd10a6a7762da571fcc4fc7f7d741cfe0e

2020-01-15 13:57 UTC, 2giwon commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/di/NetworkModule.kt
> +                    )
수정했습니다.

4acd71a938ffae17c73d9801d4569e7492d1c374

2020-01-15 13:58 UTC, 2giwon commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/di/NetworkModule.kt
> +                    }
수정했습니다.

4acd71a938ffae17c73d9801d4569e7492d1c374

2020-01-15 13:58 UTC, 2giwon commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/di/NetworkModule.kt
> +            .addConverterFactory(GsonConverterFactory.create())
수정했습니다.
4acd71a938ffae17c73d9801d4569e7492d1c374

2020-01-15 13:58 UTC, 2giwon commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/di/NetworkModule.kt
> +            .create(ContentsService::class.java)
수정했습니다.
4acd71a938ffae17c73d9801d4569e7492d1c374

2020-01-15 13:58 UTC, 2giwon commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/ui/TabsFragment.kt
>          vp_contents.apply {
수정했습니다.
f86bc1e1aa9dea04b69c447c385c7bf50c42b223

2020-01-15 13:58 UTC, 2giwon commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/ui/tabs/ContentsFragment.kt
> +    override fun onActivityCreated(savedInstanceState: Bundle?) {
수정했습니다.
46beb3c10b17d43672da44ada3a4a68ae4ea3828

2020-01-16 01:04 UTC, BeokBeok commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/base/BaseViewModel.kt
> +    val showErrorText: LiveData<Int> get() = errorText
변수명이 text 라고 되어있으면 타입도 웬지 String 이어야할 것 같지 않나요?

2020-01-16 01:04 UTC, BeokBeok commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/base/BaseFragment.kt
>      }
함수 파라미터 타입이 Int 인 함수에 대해서도 접근자를 변경해주세요.

2020-01-16 01:04 UTC, BeokBeok commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/di/DataSourceModule.kt
> +    single { ContentDataBase.getInstance(context = androidContext()).contentDao() }
context 를 파라미터로 받지 마시고 `androidApplication()` 을 사용하시면 좋을 것 같습니다.

2020-01-16 01:04 UTC, BeokBeok commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/di/NetworkModule.kt
> +            .create(ContentsService::class.java)
`build()` 와 `create()` 는 각 별개의 객체를 만드므로, 따로 만들어주시면 좋을 것 같습니다.

2020-01-16 04:07 UTC, 2giwon commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/di/DataSourceModule.kt
> +    single { ContentDataBase.getInstance(context = androidContext()).contentDao() }
이 부분은 왜 그런지 궁금하네요 어떤 장점이 있는거죠?

2020-01-16 04:08 UTC, 2giwon commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/di/NetworkModule.kt
> +            .create(ContentsService::class.java)
객체를 나누면 어떤 장점이 있는건가요? 재사용성인가요?

2020-01-16 04:27 UTC, BeokBeok commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/di/DataSourceModule.kt
> +    single { ContentDataBase.getInstance(context = androidContext()).contentDao() }
koin 에서 application context 를 함수로 제공해주기 때문에, 별도의 context 를 받지 않으셔도 됩니다.

2020-01-16 04:27 UTC, BeokBeok commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/di/NetworkModule.kt
> +            .create(ContentsService::class.java)
가령 서비스만 변경하고 싶을 경우에
create 함수 부분만 별도로 만들어서 주입하면 됩니다.

2020-01-16 14:50 UTC, 2giwon commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/base/BaseViewModel.kt
> +    val showErrorText: LiveData<Int> get() = errorText
그렇죠 타입에 맞게 변수명을 지어야하는데...잘못 착각하고 있었네요

리뷰 감사합니다. 수정했습니다.

5aad2d47214839eefa98d723397a9d81e537c63b

2020-01-16 14:51 UTC, 2giwon commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/base/BaseFragment.kt
>      }
리뷰를 해주셨는데 하나만 확인 했네요

밑에 함수까지 확인 못했습니다. 감사합니다.

2f4cdc6e2731f191d1980f2cbe6aa98fcca867cc

2020-01-16 14:51 UTC, 2giwon commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/di/DataSourceModule.kt
> +    single { ContentDataBase.getInstance(context = androidContext()).contentDao() }
수정했습니다.
20007e9f09962646027a364250b6e1ff17497dca

2020-01-16 14:52 UTC, 2giwon commented on 2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/di/NetworkModule.kt
> +            .create(ContentsService::class.java)
서비스를 나누면 나중에 다른 서비스가 필요하면 서비스만 만들어서 주입할 수 있겠네요

리뷰 감사합니다. 덕분에 하나 더 배웁니다.

ff4017d4ac6bc9b91cf79fbe4cda839ecb742af4

2020-01-16 15:01 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-01-17 01:29 UTC, BeokBeok approved these changes
LGTM:ok_hand:

2020-01-17 04:12 UTC, merged