HW-8 Koin 적용하기
sjjeong/GoogryAndroidArchitecutreStudy pull request #423
Opened 2020-01-12 15:24 UTC by bean628

Koin 적용했습니다~

2020-01-13 07:21 UTC, ironelder commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/di/ViewModelModule.kt
> +}
ViewModelModule의 경우 하나로 합치는 것은 어떨지 제안드려봅니다.

2020-01-13 07:21 UTC, ironelder commented on bean628/MyProject/app/build.gradle
> +    implementation 'org.koin:koin-android-viewmodel:2.0.1'
윗쪽에서 androidx lifecycle을 사용하셔서 koin도 androidx를 사용하시는 것이 좋을 것 같습니다

2020-01-13 22:15 UTC, bean628 commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/di/ViewModelModule.kt
> +}
수정했습니다.

885371b

2020-01-13 22:15 UTC, bean628 commented on bean628/MyProject/app/build.gradle
> +    implementation 'org.koin:koin-android-viewmodel:2.0.1'
수정했습니다


80959bb
411df3e

2020-01-15 10:53 UTC, sjjeong commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/di/RepositoryModule.kt
> +    single { NaverRepository(get(), get()) }
주입을 해줄 때 class형태가 아닌 interface 형태로 주입 해줘야 합니다.
model에 속하는 클래스 3개를  single<> {} 형태로 바꿔주세요

2020-01-15 10:54 UTC, sjjeong requested changes
리뷰 사항 반영해주세요

2020-01-15 13:59 UTC, bean628 commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/di/RepositoryModule.kt
> +    single { NaverRepository(get(), get()) }
무슨 말인지 잘 모르겠어요 ㅠㅠ 
model에 속하는 클래스라는게 저는 떠오르는게 data class 이런것만 떠올라서..  저거중에 어떤 3개가 model에 속하는건지 모르겠어요.

2020-01-16 03:22 UTC, ironelder commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/di/RepositoryModule.kt
> +    single { NaverRepository(get(), get()) }
@bean628 
viewModelModule에 보면 single이 아니라 viewModel로 선언되어 있는데 요걸 말씀하시는게 아뉠까영...?

2020-01-16 05:02 UTC, BeokBeok commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/di/RepositoryModule.kt
> +    single { NaverRepository(get(), get()) }
[learning modular approach to android with dagger](https://medium.com/@rohitsingh14101992/learning-modular-approach-to-android-with-dagger-4b65fe880309)
dagger 이긴 하지만 di 관점에서는 유사해서 본 링크를 참고하시면 좋을 것 같아요

2020-01-16 12:57 UTC, sjjeong commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/di/RepositoryModule.kt
> +    single { NaverRepository(get(), get()) }
MVVM할때 나오는 Model을 말하는 것이였습니다

2020-01-27 07:14 UTC, bean628 commented on bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/di/RepositoryModule.kt
> +    single { NaverRepository(get(), get()) }
늦었지만 8주차 마무리 하려고 올렸어요! 이렇게 하면될까요?

6e18d67

2020-01-27 08:56 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-01-28 11:38 UTC, ironelder approved these changes

2020-01-28 12:10 UTC, merged