HW-6 mvvm 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #424
Opened 2020-01-13 13:24 UTC by dksush

1. '이전 검색 기록' 을 앱 시작과 함께 view 에서 viewmodel의 메소드를 직접 찔러 가져오고 있습니다. 데이터의 변화가 아니라, 시작과 함께 api 호출로 새롭게 가져와야 하는경우 view에서 직접 데이터를 요청하는 식으로 구현하는게 맞을런지요

2. 웹뷰 activity 로 이동하는 intent가 adapter 에 있는데, 이것도 viewmodel 에 있어야 하는걸까요

2020-01-15 10:59 UTC, sjjeong requested changes

2020-01-15 10:59 UTC, sjjeong commented on dksush/AndroidArchitecture/app/src/main/java/com/example/androidarchitecture/ui/blog/BlogFragment.kt
> +        })
BindingAdapter로 처리해보세요

2020-01-15 10:59 UTC, sjjeong commented on dksush/AndroidArchitecture/app/src/main/java/com/example/androidarchitecture/ui/blog/BlogFragment.kt
> +                binding.isListEmpty = vm.isListEmpty.get()
xml에서 처리 할 수 있습니다.

2020-01-15 10:59 UTC, sjjeong commented on dksush/AndroidArchitecture/app/src/main/java/com/example/androidarchitecture/ui/blog/BlogViewModel.kt
> +    val blankInputText = ObservableField<Any>() //get,set 자동생성? //ObservableField 를 이용해 xml 에 바인딩 할 수 있는 클래스를 만듬
Any대신 Unit을 사용하면됩니다.

2020-01-15 10:59 UTC, sjjeong commented on dksush/AndroidArchitecture/app/src/main/java/com/example/androidarchitecture/ui/blog/BlogViewModel.kt
> +        inputKeyword = s.toString()
two-way binding을 적용하면 됩니다

2020-01-15 11:00 UTC, sjjeong commented
> 1. '이전 검색 기록' 을 앱 시작과 함께 view 에서 viewmodel의 메소드를 직접 찔러 가져오고 있습니다. 데이터의 변화가 아니라, 시작과 함께 api 호출로 새롭게 가져와야 하는경우 view에서 직접 데이터를 요청하는 식으로 구현하는게 맞을런지요
> 2. 웹뷰 activity 로 이동하는 intent가 adapter 에 있는데, 이것도 viewmodel 에 있어야 하는걸까요

1. ViewModel이 init 될 때 하면 됩니다.
2. activity에 있으면 됩니다.

2020-01-16 04:27 UTC, dksush commented on dksush/AndroidArchitecture/app/src/main/java/com/example/androidarchitecture/ui/blog/BlogFragment.kt
> +        })
수정했습니다

1834190

2020-01-16 04:27 UTC, dksush commented on dksush/AndroidArchitecture/app/src/main/java/com/example/androidarchitecture/ui/blog/BlogFragment.kt
> +                binding.isListEmpty = vm.isListEmpty.get()
수정했습니다

e0740d9

2020-01-16 04:37 UTC, dksush commented on dksush/AndroidArchitecture/app/src/main/java/com/example/androidarchitecture/ui/blog/BlogViewModel.kt
> +    val blankInputText = ObservableField<Any>() //get,set 자동생성? //ObservableField 를 이용해 xml 에 바인딩 할 수 있는 클래스를 만듬
수정했습니다

794b1f3

2020-01-16 05:01 UTC, dksush commented on dksush/AndroidArchitecture/app/src/main/java/com/example/androidarchitecture/ui/blog/BlogViewModel.kt
> +        inputKeyword = s.toString()
수정했습니다

768d3e5

2020-01-16 12:57 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-01-17 21:05 UTC, ghost approved these changes

2020-01-17 23:59 UTC, merged