HW-2 Model 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #425
Opened 2020-01-13 16:53 UTC by devLibCH

2020-01-15 10:08 UTC, HudsonPark commented on class08/devLibCH/Study/app/src/main/java/app/ch/study/data/repository/NaverQueryRepositoryImple.kt
> +class NaverQueryRepositoryImple(
class명 Impl로 통일하시는 게 좋을 듯합니다.

2020-01-16 00:57 UTC, devLibCH commented on class08/devLibCH/Study/app/src/main/java/app/ch/study/data/repository/NaverQueryRepositoryImple.kt
> +class NaverQueryRepositoryImple(
eca2100

2020-01-16 04:59 UTC, HudsonPark approved these changes

2020-01-16 15:41 UTC, sjjeong requested changes

2020-01-16 15:41 UTC, sjjeong commented on class08/devLibCH/Study/app/src/main/java/app/ch/study/data/local/LocalDataManager.kt
> +open class LocalDataManager(context: Context) {
context를 전달받지 않고 context를 사용해서 만든 객체를 넘겨주세요

2020-01-16 15:41 UTC, sjjeong commented on class08/devLibCH/Study/app/src/main/java/app/ch/study/data/local/LocalDataManager.kt
> +    companion object {
companion object는 클래스 맨 아래에 있어야 합니다

2020-01-16 15:41 UTC, sjjeong commented on class08/devLibCH/Study/app/src/main/java/app/ch/study/data/local/source/NaverQueryLocalDataSourceImpl.kt
> +        val jsonList = LocalDataManager.getInstance(App.context)?.searchMovieList() ?: ""
instance가 singleton으로 만들어지긴 하지만 searchMovie를 호출 할 때 마다 매번 getInstance함수를 호출 할 필요는 없을 것 같습니다.
생성자를 통해서 주입 받거나 필드로 선언해주세요

2020-01-17 01:22 UTC, devLibCH commented on class08/devLibCH/Study/app/src/main/java/app/ch/study/data/local/LocalDataManager.kt
> +    companion object {
5048d2e

2020-01-17 01:22 UTC, devLibCH commented on class08/devLibCH/Study/app/src/main/java/app/ch/study/data/local/source/NaverQueryLocalDataSourceImpl.kt
> +        val jsonList = LocalDataManager.getInstance(App.context)?.searchMovieList() ?: ""
f92901c

2020-01-17 01:22 UTC, devLibCH commented on class08/devLibCH/Study/app/src/main/java/app/ch/study/data/local/LocalDataManager.kt
> +open class LocalDataManager(context: Context) {
e960721

2020-01-17 15:13 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-01-18 08:30 UTC, merged