HW-8-Koin적용하기
sjjeong/GoogryAndroidArchitecutreStudy pull request #427
Opened 2020-01-14 09:31 UTC by ironelder

Koin적용하여 기존의 Fragment에서 사용하는 Viewmodel을 koin에서 받아오도록 수정

2020-01-16 13:17 UTC, sjjeong requested changes
기존에 static처럼 사용했던 것 들을 주입하게 넣어보세요
httpclient나 retrofit이나 api service등등이요

2020-01-16 13:17 UTC, sjjeong commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/component/MainApplication.kt
> +    private val veiwModelModule: Module = module {
오타있네요

2020-01-16 13:17 UTC, sjjeong commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/data/repository/SearchDataRepositoryImpl.kt
> +class SearchDataRepositoryImpl(private val localSearchDataSourceImpl: LocalSearchDataSourceImpl) :
타입은 인터페이스 형태로 받아야합니다

2020-01-18 07:27 UTC, ironelder commented on ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/data/repository/SearchDataRepositoryImpl.kt
> +class SearchDataRepositoryImpl(private val localSearchDataSourceImpl: LocalSearchDataSourceImpl) :
@sjjeong 
음... 
private val localSearchDataSourceImpl: LocalSearchDataSource
이렇게 interface방식으로 받으면 앱이 죽는데 뭐가 잘못된건지 잘 모르겠습니당...

2020-01-19 06:36 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-01-21 07:42 UTC, bean628 approved these changes

2020-01-21 07:43 UTC, merged