HW-2 Model 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #428
Opened 2020-01-14 10:09 UTC by slflfl12

2020-01-14 13:07 UTC, L91519 commented on class08/slflfl12/Study/app/src/main/java/com/example/study/data/datasource/remote/NaverSearchRemoteDatasourceImpl.kt
> +                        success(response.body()!!)
!! 을 사용하게 된다면 null일 때 앱이 먹통이 된다고 알고 있는데 혹시 널이 아닐때만 success를 실행하거나 등으로 처리하는게 어떨까요?

2020-01-14 13:07 UTC, L91519 commented on class08/slflfl12/Study/app/src/main/java/com/example/study/ui/MainActivity.kt
> +        naverSearchRepository.getMovies(query, success = { movieAdapter.setItem( it.items)}, fail = { Log.e("error is ", it.toString())})
한 줄이 좀 긴 것 처럼 보입니다.

2020-01-14 13:07 UTC, L91519 commented on class08/slflfl12/Study/app/src/main/java/com/example/study/ui/MainActivity.kt
> +    private var movieAdapter = MovieAdapter()
var 대신 val으로 사용해도 괜찮을 것 같습니다.

2020-01-14 14:16 UTC, slflfl12 commented on class08/slflfl12/Study/app/src/main/java/com/example/study/data/datasource/remote/NaverSearchRemoteDatasourceImpl.kt
> +                        success(response.body()!!)
새로운거 알아가네용 감사합니다. 수정했습니다.
915f671

2020-01-14 14:16 UTC, slflfl12 commented on class08/slflfl12/Study/app/src/main/java/com/example/study/ui/MainActivity.kt
> +    private var movieAdapter = MovieAdapter()
수정했습니다

d9d33a8

2020-01-14 14:16 UTC, slflfl12 commented on class08/slflfl12/Study/app/src/main/java/com/example/study/ui/MainActivity.kt
> +        naverSearchRepository.getMovies(query, success = { movieAdapter.setItem( it.items)}, fail = { Log.e("error is ", it.toString())})
수정했습니다

dc83db3

2020-01-15 01:38 UTC, L91519 approved these changes

2020-01-15 11:32 UTC, sjjeong requested changes
commit 하기전에 항상 reformat code하는 습관 가져주세요

2020-01-15 11:32 UTC, sjjeong commented on class08/slflfl12/Study/app/src/main/java/com/example/study/data/datasource/remote/NaverSearchRemoteDatasource.kt
> +interface NaverSearchRemoteDatasource {
DataSource로 해야 합니다.

2020-01-15 11:32 UTC, sjjeong commented on class08/slflfl12/Study/app/src/main/java/com/example/study/data/datasource/remote/network/NaverApiServiceImpl.kt
> +object NaverApiServiceImpl {
이건 Impl이 안붙어도 됩니다

2020-01-15 11:32 UTC, sjjeong commented on class08/slflfl12/Study/app/src/main/java/com/example/study/ui/MainActivity.kt
> +    private lateinit var naverSearchRepository: NaverSearchRepository
lateinit var말고 val로 선언해서 사용할 수 있겠네요

2020-01-15 11:32 UTC, sjjeong commented on class08/slflfl12/Study/app/src/main/java/com/example/study/ui/MainActivity.kt
> +            intent.putExtra("url", movie.link.toString())
전달하는 key인 "url"을 DetailActivity의 companion object안에 const val로 선언해서 관리하면 더 좋습니다.

2020-01-15 12:30 UTC, L91519 approved these changes

2020-01-15 17:13 UTC, slflfl12 commented on class08/slflfl12/Study/app/src/main/java/com/example/study/data/datasource/remote/NaverSearchRemoteDatasource.kt
> +interface NaverSearchRemoteDatasource {
수정했습니다!
c611e48

2020-01-15 17:14 UTC, slflfl12 commented on class08/slflfl12/Study/app/src/main/java/com/example/study/data/datasource/remote/network/NaverApiServiceImpl.kt
> +object NaverApiServiceImpl {
수정했습니다!

2020-01-15 17:15 UTC, slflfl12 commented on class08/slflfl12/Study/app/src/main/java/com/example/study/ui/MainActivity.kt
> +    private lateinit var naverSearchRepository: NaverSearchRepository
이렇게 바꾸는게 맞나요??? 수정했습니다!
52b6215

2020-01-15 17:15 UTC, slflfl12 commented on class08/slflfl12/Study/app/src/main/java/com/example/study/ui/MainActivity.kt
> +            intent.putExtra("url", movie.link.toString())
넵! 수정했습니다
d4c12f2

2020-01-16 13:20 UTC, sjjeong requested changes

2020-01-16 13:20 UTC, sjjeong commented on class08/slflfl12/Study/app/src/main/java/com/example/study/ui/DetailActivity.kt
> +        var movie_url = intent.getStringExtra(MOVIE_URL)
변수명에는 _가 들어가지 않고 카멜케이스 형태를 사용해야 합니다

2020-01-17 08:16 UTC, slflfl12 commented on class08/slflfl12/Study/app/src/main/java/com/example/study/ui/DetailActivity.kt
> +        var movie_url = intent.getStringExtra(MOVIE_URL)
수정했습니다!

3aa3f35
649fe2f

2020-01-17 08:18 UTC, slflfl12 commented on class08/slflfl12/Study/app/src/main/java/com/example/study/ui/DetailActivity.kt
> +        var movie_url = intent.getStringExtra(MOVIE_URL)
그리고 rxjava로 바꿔봤는데 rxjava 부분 코드 리뷰좀 해주실 수 있나요?

2020-01-17 15:16 UTC, sjjeong requested changes

2020-01-17 15:16 UTC, sjjeong commented on class08/slflfl12/Study/app/src/main/java/com/example/study/ui/MainActivity.kt
> +            intent.putExtra("movieUrl", movie.link.toString())
DetailActivity의 MOVIE_URL를 사용해야합니다
그래야 넣는쪽과 받는쪽이 같은 값을 사용합니다.

2020-01-17 15:16 UTC, sjjeong commented on class08/slflfl12/Study/app/src/main/java/com/example/study/ui/MainActivity.kt
> +                        Toast.makeText(this@MainActivity, R.string.error_message, Toast.LENGTH_SHORT ).show()
각각 {} 추가해주세요

2020-01-17 17:08 UTC, slflfl12 commented on class08/slflfl12/Study/app/src/main/java/com/example/study/ui/MainActivity.kt
> +            intent.putExtra("movieUrl", movie.link.toString())
수정했습니다!
c76c32a

2020-01-17 17:08 UTC, slflfl12 commented on class08/slflfl12/Study/app/src/main/java/com/example/study/ui/MainActivity.kt
> +                        Toast.makeText(this@MainActivity, R.string.error_message, Toast.LENGTH_SHORT ).show()
수정했습니다!
07532ee

2020-01-18 02:01 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-01-18 05:08 UTC, merged