HW-4 databinding 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #429
Opened 2020-01-14 14:22 UTC by AhnHyeonho

* BaseAdapter 추가
* 기존 RecyclerAdatper를 MovieItemAdapter로 이름 변경 및 BaseAdapter를 상속받도록 구조 변경
* databinding에 필요한 추가 메소드 구현 (extension/BindingHelper.kt)
* databinding 적용

2020-01-16 01:23 UTC, seunghee63 requested changes
수정사항을 많이 찾지 못해 리뷰 내용이 많지 않네요..! ㅜ
수고하셨습니다~

2020-01-16 01:23 UTC, seunghee63 commented on AhnHyeonho/FirstProject/app/src/main/java/com/hansung/firstproject/extension/BindingHelper.kt
> +@TargetApi(Build.VERSION_CODES.N)
해당 어노테이션이 어떤 기능을 하는 것인지 알 수 있을까요?!
바인딩어뎁터에 Html태그를 적용하여 TextView에 뿌려주는 기능을 하는 함수도 구현을 했었는데, 잘 적용이 되지 않아 일단은 적용시키지 않은 상태입니다. 이 문제와 관련이 있는 것인지 궁금해서 여쭤봅니다!

2020-01-16 01:23 UTC, seunghee63 commented on AhnHyeonho/FirstProject/app/src/main/res/layout/activity_main.xml
> +                    android:inputType="textPersonName" />
줄넘김을 막는 속성을 추가 하신 것을 보고 추가적으로 의견을 남겨보면, 
안드로이드 시스템 키보드의 엔터버튼을 검색버튼으로 바꾸어서 줄넘김을 방지하는 방법을 사용해도 좋을 것 같습니다!

2020-01-16 05:03 UTC, AhnHyeonho commented on AhnHyeonho/FirstProject/app/src/main/java/com/hansung/firstproject/extension/BindingHelper.kt
> +@TargetApi(Build.VERSION_CODES.N)
저도 다시 찾아보고 답을 드립니다! 

해당 어노테이션은 명시된 버전 이후의 버전에 대해서만 아래 함수를 실행하겠다고 IDE에게 알려주는 역할을 합니다.
저는 minSdkVersion을 23으로 잡았고,  Html.fromHtml()함수자체가 버전24부터 지원을 해주기에 버전23일때는 해당 함수를 호출하지 못하고 오류가 발생하게 합니다. 따라서 IDE에서는 아래 함수에 오류가 발생한다고 알려주지만 해당 어노테이션을 통해서 무시하는 방식 해결한 것입니다.
따라서 저도 추가적으로 if문 등 분기처리를 통해 Html.fromHtml()함수를 호출하지 못하는 버전들에 대한 문제를 해결해야 할 것 같습니다. 문제 해결 후 커밋남겨드리곘습니다..!

아래링크에 TargetApi 어노테이션에 대해 간략히 정리가 잘 되어있습니다. 참고하시면 좋을 것 같아 남겨드립니다.  
[TargetApi 참고 링크](https://minseok-kr.github.io/android/2018/12/19/Requires%EC%99%80-TargetAPI%EC%9D%98-%EC%B0%A8%EC%9D%B4.html)

2020-01-16 06:30 UTC, AhnHyeonho commented on AhnHyeonho/FirstProject/app/src/main/res/layout/activity_main.xml
> +                    android:inputType="textPersonName" />
말씀하신 의견 반영해서 수정했습니다!


b64cc79

2020-01-16 10:05 UTC, seunghee63 commented on AhnHyeonho/FirstProject/app/src/main/java/com/hansung/firstproject/extension/BindingHelper.kt
> +@TargetApi(Build.VERSION_CODES.N)
설명 감사합니다 :> !

2020-01-17 07:46 UTC, zozero94 reviewed
RemoteDataSourceImpl에
![image](https://user-images.githubusercontent.com/31091115/72593119-85e41500-3947-11ea-858d-75efdd9d242d.png)

아래 이미지에 해당하는 부분도 enum class혹은 다른 방법으로 처리를 해주는게 좋아보여요

2020-01-17 07:46 UTC, zojae031 commented on AhnHyeonho/FirstProject/app/src/main/java/com/hansung/firstproject/extension/BindingHelper.kt
> +        this.text = Html.fromHtml(title)
fromHtml
![image](https://user-images.githubusercontent.com/31091115/72591943-cee69a00-3944-11ea-8e25-786e504eef61.png)
Deprecated 된 함수입니다. 
버전대응에 필요한 함수가 필요해 보여요

2020-01-17 07:46 UTC, zojae031 commented on AhnHyeonho/FirstProject/app/src/main/java/com/hansung/firstproject/ui/main/MainActivity.kt
recyclerView의 세팅에 대한 함수이기 때문에 명시적으로 
with으로 묶어서 처리해줘도 될것 같아요

2020-01-17 07:46 UTC, zojae031 commented on AhnHyeonho/FirstProject/app/src/main/java/com/hansung/firstproject/adapter/MovieHolder.kt
> +        binding.apply {
scope function 이 불필요하게 여러개인것 같아여 apply와 run에 대해서 구분하여 사용하는게 좋을것 같아요

2020-01-17 07:46 UTC, zojae031 commented on AhnHyeonho/FirstProject/app/src/main/java/com/hansung/firstproject/extension/BindingHelper.kt
> +    Glide.with(context)
error에 대한 처리를 해주는게 좋아요!
안그러면 앱이 아마 죽을거에요

2020-01-17 07:46 UTC, zojae031 commented on AhnHyeonho/FirstProject/app/src/main/res/layout/activity_main.xml
> +    <data>
당장 사용하지 않는다면 없애는걸 추천드립니다.

2020-01-17 07:46 UTC, zojae031 commented on AhnHyeonho/FirstProject/app/src/main/res/layout/movie_item.xml
> +            loadUrl="@{item.image}"
위치를 보아하니 Reformat Code가 되어있지 않은듯 합니다. 
xml에도 적용하는 습관!

2020-01-17 07:46 UTC, zojae031 commented on AhnHyeonho/FirstProject/app/src/main/java/com/hansung/firstproject/ui/main/MainActivity.kt
> +        Toast.makeText(this, ErrorStringResource.valueOf(errorMessage).resId, Toast.LENGTH_SHORT)
이 부분이 무엇을 말하는지 모르겠습니다.
직접 테스트를 해본결과
![image](https://user-images.githubusercontent.com/31091115/72593602-b4162480-3948-11ea-838c-3d2903181e4e.png)
```kotlin
ErrorStringResource.valueOf(errorMessage).resId
```  
는 아래와 같은 값을 뿌려주는데 의도한 동작인가요?

2020-01-17 09:38 UTC, AhnHyeonho commented on AhnHyeonho/FirstProject/app/src/main/java/com/hansung/firstproject/extension/BindingHelper.kt
> +        this.text = Html.fromHtml(title)
버전대응하려고 각 버전에따른 분기처리를 한건데 문제가 될까요?

2020-01-17 09:39 UTC, zojae031 commented on AhnHyeonho/FirstProject/app/src/main/java/com/hansung/firstproject/extension/BindingHelper.kt
> +        this.text = Html.fromHtml(title)
Deprecated 된 함수 말고 다른 함수를 사용하는게 좋아보입니다.

2020-01-17 10:52 UTC, AhnHyeonho commented on AhnHyeonho/FirstProject/app/src/main/java/com/hansung/firstproject/ui/main/MainActivity.kt
61라인 부터 말씀하시는 것 같아 해당부분 수정하였습니다.

e8cdce5

2020-01-17 10:53 UTC, AhnHyeonho commented on AhnHyeonho/FirstProject/app/src/main/java/com/hansung/firstproject/adapter/MovieHolder.kt
> +        binding.apply {
수정하였습니다.

819e9ec

2020-01-17 10:53 UTC, AhnHyeonho commented on AhnHyeonho/FirstProject/app/src/main/java/com/hansung/firstproject/extension/BindingHelper.kt
> +    Glide.with(context)
어떠한 부분의 error를 말씀하시는지 모르겠습니다... 혹시 어디를 말씀하시는건지 알 수 있을까요?

2020-01-17 10:54 UTC, AhnHyeonho commented on AhnHyeonho/FirstProject/app/src/main/res/layout/activity_main.xml
> +    <data>
수정하였습니다.


c5ac203

2020-01-17 10:54 UTC, AhnHyeonho commented on AhnHyeonho/FirstProject/app/src/main/res/layout/movie_item.xml
> +            loadUrl="@{item.image}"
수정하였습니다.

d22ea7f

2020-01-17 11:08 UTC, AhnHyeonho commented on AhnHyeonho/FirstProject/app/src/main/java/com/hansung/firstproject/ui/main/MainActivity.kt
> +        Toast.makeText(this, ErrorStringResource.valueOf(errorMessage).resId, Toast.LENGTH_SHORT)
MainPresenter쪽을 보시면
```kotlin
            repository.getMoviesData(
                keyword,
                success = {
                    view.addItemToAdapter(it)
                },
                fail = {
                    view.showErrorByErrorMessage(it.message!!)
                },
                isEmptyList = {
                    view.showErrorEmptyList()
                }
            )
```
위와 같이 쓰이게됩니다. 

여기서 전달받는 it.message는 ErrorStringResource.ERROR_CODE_###.name 입니다.

따라서 showErrorByErrorMessage()내부에 ErrorStringResource.valueOf(errorMessage)는 
enum class 멤버 중 해당 value값 (ErrorStringResource.ERROR_CODE_### 의 value: R.string.error_message_###의 id값)를 의미하게 됩니다.

결과적으론 
```kotlin
Toast.makeText(this, R.string.error_message_###, Toast.LENGTH_SHORT)
```
와 같이 적어주는 것과 동일한 결과를 나타냅니다.

2020-01-17 13:28 UTC, zojae031 commented on AhnHyeonho/FirstProject/app/src/main/java/com/hansung/firstproject/extension/BindingHelper.kt
> +    Glide.with(context)
Glide 를 사용했는데 중간에 internet연결이 끊기거나 해서 이미지를 불러 올 수 없는 상황이라면 어떻게 동작할까요?

2020-01-17 13:28 UTC, zojae031 commented on AhnHyeonho/FirstProject/app/src/main/java/com/hansung/firstproject/ui/main/MainActivity.kt
> +        Toast.makeText(this, ErrorStringResource.valueOf(errorMessage).resId, Toast.LENGTH_SHORT)
이건 제가 제대로 확인하지 못햇네요!!

2020-01-17 15:25 UTC, sjjeong requested changes

2020-01-17 15:25 UTC, sjjeong commented on AhnHyeonho/FirstProject/app/src/main/java/com/hansung/firstproject/extension/BindingHelper.kt
> +    Glide.with(context)
https://stackoverflow.com/questions/47910536/glide-4-3-1-how-to-use-error
아마도 이걸 말하는 것 같네요
근데 이거 처리 안하면 이미지 로드 실패 했을 때 앱이 죽나요?

2020-01-17 15:25 UTC, sjjeong commented on AhnHyeonho/FirstProject/app/src/main/java/com/hansung/firstproject/extension/BindingHelper.kt
> +        this.text = Html.fromHtml(title)
![image](https://user-images.githubusercontent.com/4777586/72623588-c44df400-3988-11ea-89dd-6eb09b206a69.png)
api 24 이상에서 flags가 추가된 함수를 사용 할 수 있기에 24 미만에서는 deprecated된 함수를 사용 할 수 밖에 없습니다.

2020-01-17 15:25 UTC, sjjeong commented on AhnHyeonho/FirstProject/app/build.gradle
>  apply plugin: 'kotlin-android-extensions'
kotlin-android-extensions를 제거 해주셔야 합니다

2020-01-18 07:05 UTC, zojae031 commented on AhnHyeonho/FirstProject/app/src/main/java/com/hansung/firstproject/extension/BindingHelper.kt
> +    Glide.with(context)
네 맞습니다 따로 처리안하면 죽는것으로 알고있었는데 아니었나보네요!

2020-01-18 13:14 UTC, AhnHyeonho commented on AhnHyeonho/FirstProject/app/build.gradle
>  apply plugin: 'kotlin-android-extensions'
수정하였습니다

d4471d2

2020-01-18 13:20 UTC, AhnHyeonho commented on AhnHyeonho/FirstProject/app/src/main/java/com/hansung/firstproject/extension/BindingHelper.kt
> +    Glide.with(context)
이미지 로딩에 실패했을 경우 처리해주는 error를 추가해주었습니다.

6a385f1

2020-01-19 02:26 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-01-19 02:32 UTC, zozero94 approved these changes
고생하셧습니다

2020-01-19 03:50 UTC, seunghee63 approved these changes

2020-01-19 03:50 UTC, merged