Class08/minoyam
sjjeong/GoogryAndroidArchitecutreStudy pull request #431
Opened 2020-01-15 03:18 UTC by Minoyam

2020-01-15 03:28 UTC, YKW93 commented on class08/Minoyam/app/src/main/java/com/cnm/homework/ui/MainActivity.kt
> +            .observeOn(AndroidSchedulers.mainThread())
subscribeOn, observeOn 처리는 NaverQueryRemoteDataSourceImpl 클래스에서도 할 수 있지 않을까요??

2020-01-15 03:35 UTC, YKW93 commented on class08/Minoyam/app/src/main/java/com/cnm/homework/ui/MainActivity.kt
> +            .observeOn(AndroidSchedulers.mainThread())
추가적으로 subscribeOn과 observeOn을 single Extension 함수로 만들어서 한번에 처리 할 수 도 있을 거 같습니다.
자바 같은 경우에는 Extension 함수를 만들 수 없어 compose 함수를 사용합니다!

2020-01-15 03:46 UTC, Minoyam commented on class08/Minoyam/app/src/main/java/com/cnm/homework/ui/MainActivity.kt
> +            .observeOn(AndroidSchedulers.mainThread())
72fec56 수정했습니다~

2020-01-15 08:03 UTC, YKW93 approved these changes

2020-01-15 12:09 UTC, sjjeong requested changes

2020-01-15 12:09 UTC, sjjeong commented on class08/Minoyam/app/src/main/java/com/cnm/homework/data/source/local/NaverQueryLocalDataSourceImpl.kt
> +class NaverQueryLoclDataSourceImpl(context: Context) : NaverQueryLocalDataSource {
context를 전달 받는건 좋지 않아요
context를 이용해서 만드는 LocalDao를 전달 받는게 좋습니다

2020-01-15 12:09 UTC, sjjeong commented on class08/Minoyam/app/src/main/java/com/cnm/homework/ui/MainActivity.kt
> +        disposable.add(NaverQueryRepositoryImpl.getInstance(
NaverQueryRepositoryImpl를 매번 만들지 말고 한번만 만들고 사용하게 해주세요

2020-01-16 05:26 UTC, Minoyam commented on class08/Minoyam/app/src/main/java/com/cnm/homework/data/source/local/NaverQueryLocalDataSourceImpl.kt
> +class NaverQueryLoclDataSourceImpl(context: Context) : NaverQueryLocalDataSource {
fe6f883 수정했습니다

2020-01-16 05:26 UTC, Minoyam commented on class08/Minoyam/app/src/main/java/com/cnm/homework/ui/MainActivity.kt
> +        disposable.add(NaverQueryRepositoryImpl.getInstance(
e4f0979 수정했습니다

2020-01-16 05:27 UTC, Minoyam commented on class08/Minoyam/app/src/main/java/com/cnm/homework/data/source/local/NaverQueryLocalDataSourceImpl.kt
> +class NaverQueryLoclDataSourceImpl(context: Context) : NaverQueryLocalDataSource {
수정하면서 로컬 쪽 좀 만들어봤는데  잘 이해가안가서 스터디날에 한번 봐주실수있을까요?

2020-01-16 13:28 UTC, sjjeong requested changes

2020-01-16 13:28 UTC, sjjeong commented on class08/Minoyam/app/src/main/java/com/cnm/homework/data/source/local/NaverQueryLocalDataSourceImpl.kt
> +    private val dao = localDao
클래스 생성자에 private val로 선언해주시면 됩니다

2020-01-16 13:28 UTC, sjjeong commented on class08/Minoyam/app/src/main/java/com/cnm/homework/ui/MainActivity.kt
> +            }
이 과정은 repository에서 해주면 됩니다

2020-01-16 13:28 UTC, sjjeong commented on class08/Minoyam/app/src/main/java/com/cnm/homework/data/repository/NaverQueryRepositoryImpl.kt
> +    private val localDataSoure: NaverQueryLocalDataSourceImpl
기존처럼 interface type으로 선언해주세요

2020-01-17 01:22 UTC, Minoyam commented on class08/Minoyam/app/src/main/java/com/cnm/homework/data/source/local/NaverQueryLocalDataSourceImpl.kt
> +    private val dao = localDao
cd6d740 수정했습니다

2020-01-17 01:22 UTC, Minoyam commented on class08/Minoyam/app/src/main/java/com/cnm/homework/ui/MainActivity.kt
> +            }
acbf337 수정했습니다

2020-01-17 01:23 UTC, Minoyam commented on class08/Minoyam/app/src/main/java/com/cnm/homework/data/repository/NaverQueryRepositoryImpl.kt
> +    private val localDataSoure: NaverQueryLocalDataSourceImpl
c6c29c6 수정했습니다

2020-01-17 15:26 UTC, sjjeong commented on class08/Minoyam/app/src/main/java/com/cnm/homework/data/source/local/NaverQueryLocalDataSourceImpl.kt
> +class NaverQueryLoclDataSourceImpl(context: Context) : NaverQueryLocalDataSource {
스터디 날에 말씀해주세요

2020-01-17 15:27 UTC, sjjeong requested changes
conflict난거 merge commit 만들어주세요

2020-01-17 16:12 UTC, Minoyam commented
c76b0b1 수정했습니다

2020-01-18 02:02 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-01-18 05:08 UTC, merged