HW-4 데이터 캐싱
sjjeong/GoogryAndroidArchitecutreStudy pull request #433
Opened 2020-01-15 15:36 UTC by jjunji

2020-01-17 00:21 UTC, suhyeong-seo reviewed
블로그는 검색결과를 안보여주네요
확인 부탁드려요~

2020-01-18 03:38 UTC, jjunji commented
> 블로그는 검색결과를 안보여주네요
> 확인 부탁드려요~

2020-01-18 03:41 UTC, jjunji commented
16c29d8
통신 실패 케이스 확인하려고 일부러 failed 시켜놓고 원복을 안했네요.. 수정했습니다~

2020-01-22 07:49 UTC, doubleclutch30 commented
수고하셨습니다!

2020-01-22 14:32 UTC, minjae2 commented
@doubleclutch30 
리뷰 라벨이 빠졌어요

2020-01-27 05:24 UTC, sjjeong requested changes

2020-01-27 05:24 UTC, sjjeong commented on jjunji/StudyApplication/app/src/main/java/com/example/studyapplication/BaseApplication.kt
> +    }
이 코드가 BuildConfig.DEBUG와 같은 동작을 하는지는 잘 모르겠지만
빌드할 때 디버그빌드이면 true가 되는게 목적이면 BuildConfig.DEBUG를 사용하셔도 됩니다.

2020-01-27 05:24 UTC, sjjeong commented on jjunji/StudyApplication/app/src/main/java/com/example/studyapplication/ui/main/blog/BlogPresenter.kt
> +                            }
delete하고 save하는 로직이 presenter가 아니라 repository에서 get할 때 내부로 들어가야합니다.

2020-01-27 05:24 UTC, sjjeong commented on jjunji/StudyApplication/app/src/main/java/com/example/studyapplication/ui/main/blog/BlogPresenter.kt
> +                        repository.deleteMovieList()
이 부분도 repository로 들어가면 됩니다.

2020-02-11 14:48 UTC, jjunji commented on jjunji/StudyApplication/app/src/main/java/com/example/studyapplication/BaseApplication.kt
> +    }
b67da95a906c923bb9fa2d505e4d49c2baeecdad 수정했습니다~

2020-02-11 14:48 UTC, jjunji commented on jjunji/StudyApplication/app/src/main/java/com/example/studyapplication/ui/main/blog/BlogPresenter.kt
> +                            }
b67da95a906c923bb9fa2d505e4d49c2baeecdad 수정했습니다~

2020-02-11 14:48 UTC, jjunji commented on jjunji/StudyApplication/app/src/main/java/com/example/studyapplication/ui/main/blog/BlogPresenter.kt
> +                        repository.deleteMovieList()
b67da95a906c923bb9fa2d505e4d49c2baeecdad 수정했습니다~

2020-02-11 14:50 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-02-18 14:04 UTC, merged