HW-4 데이터 바인딩 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #434
Opened 2020-01-15 19:41 UTC by handnew04

2020-01-16 03:24 UTC, ghkdua1829 commented on handnew04/app/src/main/java/com/example/handnew04/adapter/MovieRecyclerAdapter.kt
> +        fun onClick(position: Int)
View 파라미터를 삭제해주신 이유가 궁금해요!!

2020-01-16 03:24 UTC, ghkdua1829 commented on handnew04/app/src/main/res/layout/item_movie.xml
> +            type="com.example.handnew04.adapter.MovieRecyclerAdapter" />
이 adapter variable는 어디에 쓰이는건지 궁금합니다

2020-01-16 15:05 UTC, handnew04 commented on handnew04/app/src/main/java/com/example/handnew04/adapter/MovieRecyclerAdapter.kt
> +        fun onClick(position: Int)
사용하지 않아서 삭제했어요!

2020-01-16 15:18 UTC, handnew04 commented on handnew04/app/src/main/res/layout/item_movie.xml
> +            type="com.example.handnew04.adapter.MovieRecyclerAdapter" />
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/434/commits/d875ca4b6cdebc91da3854d1a7446d98d4a4350c

사용하지 않아서 삭제했습니다.

2020-01-16 15:19 UTC, handnew04 commented
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/434/commits/8b0a821d729d958ddd5725ac46dc8bd7850c7f3d

웹뷰 액티비티를 변경은 했으나 어떻게 데이터바인딩을 써야할지 잘 모르겠습니다. 변경전과 차이가 없습니다 ㅜㅜ

2020-01-17 00:10 UTC, ghkdua1829 approved these changes
고생하셨습니다~ 웹뷰 쪽은 저하고 비슷해서 저도 뭐라고 해드릴 피드백이 없네요..ㅠㅠㅠ

2020-01-17 15:32 UTC, sjjeong requested changes

2020-01-17 15:32 UTC, sjjeong commented on handnew04/app/src/main/java/com/example/handnew04/adapter/DataBindingAdapter.kt
> +}
android:text를 override 한다면 기존 구현방식 내용들이 추가되어야 합니다.
그렇지 않으면 two-way binding할 때 문제가 생깁니다.
https://android.googlesource.com/platform/frameworks/data-binding/+/refs/heads/studio-master-dev/extensions/baseAdapters/src/main/java/androidx/databinding/adapters/TextViewBindingAdapter.java#67

2020-01-17 15:32 UTC, sjjeong commented on handnew04/app/src/main/java/com/example/handnew04/adapter/MovieRecyclerAdapter.kt
>          init {
init은 함수 선언 보다 위에 있어야합니다.

2020-01-17 18:15 UTC, handnew04 commented on handnew04/app/src/main/java/com/example/handnew04/adapter/MovieRecyclerAdapter.kt
>          init {
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/434/commits/b475bcb50d16739ca04489a0591c6d3bed702556

2020-01-17 18:15 UTC, handnew04 commented on handnew04/app/src/main/java/com/example/handnew04/adapter/DataBindingAdapter.kt
> +}
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/434/commits/5157c584e8cb65df15910941318fdc6c0344c863

2020-01-18 02:01 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-01-18 04:52 UTC, merged