HW-4 데이터바인딩 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #436
Opened 2020-01-16 03:19 UTC by ghkdua1829

2020-01-16 11:14 UTC, handnew04 requested changes

2020-01-16 11:14 UTC, handnew04 commented on ghkdua1829/app/src/main/java/com/example/architecture_project/ui/main/MainActivity.kt
> +
주석을 지워주세요.

2020-01-16 11:14 UTC, handnew04 commented on ghkdua1829/app/src/main/java/com/example/architecture_project/feature/search/WebviewActivity.kt
> +        var webViewSettings = binding.wbPage.settings
제가 잘 몰라서 그런데, 혹시 val 로 하면 에러가 나나요?

2020-01-17 00:06 UTC, ghkdua1829 commented on ghkdua1829/app/src/main/java/com/example/architecture_project/ui/main/MainActivity.kt
> +
6c524b527f6d541f9b033932783c7f179c339332

2020-01-17 00:08 UTC, ghkdua1829 commented on ghkdua1829/app/src/main/java/com/example/architecture_project/feature/search/WebviewActivity.kt
> +        var webViewSettings = binding.wbPage.settings
9f236c113f31824968360b2c779fe9e8416687bb

2020-01-17 00:34 UTC, handnew04 commented
수고하셨습니다!

2020-01-17 00:37 UTC, handnew04 approved these changes
수고하셨습니다!

2020-01-17 15:34 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-01-17 16:37 UTC, merged