HW-2 MVP 패턴 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #437
Opened 2020-01-18 09:08 UTC by devLibCH

HW-2 내용 Merge를 안한채로 작업해서 몇가지가 마지막에 변경되었습니다.

2020-01-20 10:41 UTC, HudsonPark commented on class08/devLibCH/Study/app/src/main/java/app/ch/study/ui/main/presenter/MainContract.kt
> +class MainContract {
@devLibCH MainContract를 클래스로 선언하신 이유가 있을까요?

2020-01-20 10:41 UTC, HudsonPark commented on class08/devLibCH/Study/app/src/main/java/app/ch/study/ui/main/view/MainActivity.kt
> +
@devLibCH noResultView는 검색 결과가 없을 때 보여주는 View인거죠?

2020-01-22 10:06 UTC, devLibCH commented on class08/devLibCH/Study/app/src/main/java/app/ch/study/ui/main/presenter/MainContract.kt
> +class MainContract {
없습니다 interface로 변경할게요

2020-01-22 10:07 UTC, devLibCH commented on class08/devLibCH/Study/app/src/main/java/app/ch/study/ui/main/view/MainActivity.kt
> +
네 맞습니다

2020-01-22 10:09 UTC, devLibCH commented on class08/devLibCH/Study/app/src/main/java/app/ch/study/ui/main/presenter/MainContract.kt
> +class MainContract {
da8d062

2020-01-23 10:07 UTC, HudsonPark commented on class08/devLibCH/Study/app/src/main/java/app/ch/study/ui/main/presenter/MainContract.kt
> +class MainContract {
@devLibCH 변경 확인했습니다.

2020-01-23 10:08 UTC, HudsonPark approved these changes

2020-01-27 05:31 UTC, sjjeong requested changes

2020-01-27 05:31 UTC, sjjeong commented on class08/devLibCH/Study/app/src/main/java/app/ch/study/core/BaseActivity.kt
> +abstract class BaseActivity<P : BaseContract.Presenter>(@LayoutRes resId: Int) :
BaseActivity가 BaseContract.View를 implements 해야하지 않나요?

2020-01-27 05:31 UTC, sjjeong commented on class08/devLibCH/Study/app/src/main/java/app/ch/study/core/BasePresenter.kt
> +    override fun addDisposable(disposable: Disposable) =
Disposable의 extension 함수로 만들면 가독성 좋은 코드를 만들 수 있습니다.

2020-01-27 05:31 UTC, sjjeong commented on class08/devLibCH/Study/app/src/main/java/app/ch/study/ui/main/presenter/MainPresenter.kt
> +        repository = NaverQueryRepositoryImpl(local, remote)
이 코드들은 searchMovie 함수 호출 할 때 생성 하지말고 MainPresenter가 init되는 시점에 생성해주세요

2020-01-27 05:31 UTC, sjjeong commented on class08/devLibCH/Study/app/src/main/java/app/ch/study/ui/main/view/MainActivity.kt
> +        get() = findViewById(R.id.pb_loading)
이렇게하면 pbLoading을 get할 때 마다 findViewById가 호출되어서 좋지 않습니다.

2020-02-01 10:49 UTC, sjjeong requested changes

2020-02-01 10:49 UTC, sjjeong commented on class08/devLibCH/Study/app/src/main/java/app/ch/study/core/BasePresenter.kt
> +    fun Disposable.addTo(androidDisposable: CompositeDisposable): Disposable
BasePresenter가 CompositeDisposable를 가지고 있기 때문에 파라미터로 받을 필요는 없습니다.

2020-02-03 16:24 UTC, devLibCH commented on class08/devLibCH/Study/app/src/main/java/app/ch/study/core/BasePresenter.kt
> +    fun Disposable.addTo(androidDisposable: CompositeDisposable): Disposable
05ab5b2

2020-02-05 00:54 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-02-05 14:37 UTC, merged