HW-2 네이버 영화 검색 API 앱 - Model 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #438
Opened 2020-01-20 07:24 UTC by HudsonPark

2020-01-22 09:54 UTC, devLibCH requested changes
위에 세개 보고 리뷰 하다가 네번째 커밋에서 ItemDao 지워져서 다 없앴네요 ㅋㅋㅋ

2020-01-22 09:54 UTC, devLibCH commented on class08/HudsonPark/ArchtectStudy/app/src/main/java/com/example/archstudy/data/source/remote/NaverQueryRemoteDataSourceImpl.kt
> +            .build()
rerofit을 바로 생성하지마시고 RetrofitService를 생성자로 받아서 사용하는게 더 낫습니다

2020-01-22 09:54 UTC, devLibCH commented on class08/HudsonPark/ArchtectStudy/app/src/main/java/com/example/archstudy/ui/MainActivity.kt
> +        remoteData.enqueue(object : Callback<MovieData> {
Repository requestRemoteData 호출 시점에 enqueue를 Repository 내에서 실행하도록해서  Callback을 파라미터로 넘겨주는게 좋을 것 같네요

2020-01-22 09:54 UTC, devLibCH commented on class08/HudsonPark/ArchtectStudy/app/src/main/java/com/example/archstudy/ui/main/MainActivity.kt
> +    private fun setSharedPreference(query: String) {
room으로 DB에 저장 했으므로 SharedPreference에다시 저장하지 않고 DB에서 꺼내오면 될 것 같습니다.

2020-01-23 10:13 UTC, HudsonPark commented on class08/HudsonPark/ArchtectStudy/app/src/main/java/com/example/archstudy/ui/MainActivity.kt
> +        remoteData.enqueue(object : Callback<MovieData> {
@devLibCH 그럼 onResponse() 블럭에서 어떻게 데이터를 Activity로 어떻게 전달할 수 있을까요? 예전에  이런 경우에 블럭 바깥 쪽에서 null이 뜨더라구요

2020-01-23 10:14 UTC, HudsonPark commented on class08/HudsonPark/ArchtectStudy/app/src/main/java/com/example/archstudy/ui/main/MainActivity.kt
> +    private fun setSharedPreference(query: String) {
@devLibCH 알겠습니다 관련 로직 수정하겠습니다

2020-01-28 02:17 UTC, devLibCH commented on class08/HudsonPark/ArchtectStudy/app/src/main/java/com/example/archstudy/ui/MainActivity.kt
> +        remoteData.enqueue(object : Callback<MovieData> {
Callback을 액티비티에서 생성 후 requestRemoteData의 파라미터로 넘겨주시면 됩니다.

2020-01-29 12:26 UTC, HudsonPark commented on class08/HudsonPark/ArchtectStudy/app/src/main/java/com/example/archstudy/ui/MainActivity.kt
> +        remoteData.enqueue(object : Callback<MovieData> {
@devLibCH 
29d80bb

2020-01-29 12:26 UTC, HudsonPark commented on class08/HudsonPark/ArchtectStudy/app/src/main/java/com/example/archstudy/ui/main/MainActivity.kt
> +    private fun setSharedPreference(query: String) {
@devLibCH 
29d80bb

2020-02-01 06:56 UTC, devLibCH approved these changes

2020-02-01 11:13 UTC, sjjeong requested changes

2020-02-01 11:13 UTC, sjjeong commented on class08/HudsonPark/ArchtectStudy/app/src/main/java/com/example/archstudy/ui/main/MainActivity.kt
> +                insertLocalData(query, it) //  해당 데이터를 내부 DB에 저장
insert시켜주는것을 repository 내부에서 해주면 됩니다.
repositoryImpl에 requestRemoteData를 가져올 때 insert 해주세요

2020-02-03 04:57 UTC, HudsonPark commented on class08/HudsonPark/ArchtectStudy/app/src/main/java/com/example/archstudy/ui/main/MainActivity.kt
> +                insertLocalData(query, it) //  해당 데이터를 내부 DB에 저장
@sjjeong 
8eb8335

2020-02-05 00:55 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-02-05 01:09 UTC, merged