HW-7 AAC ViewModel, LiveData 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #440
Opened 2020-01-21 12:31 UTC by taeiim

2020-01-21 13:17 UTC, 2giwon requested changes

2020-01-21 13:17 UTC, 2giwon commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/ContentsFragment.kt
> +    private lateinit var vm: ContentsViewModel
viewModel을 var로 적용한 이유가 무엇인가요?

2020-01-21 13:17 UTC, 2giwon commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/ContentsFragment.kt
> +        vm = ViewModelProvider(this@ContentsFragment, object : ViewModelProvider.Factory {
여기서 뷰모델을 생성한 이유가 있나요?

2020-01-21 13:17 UTC, 2giwon commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/ContentsFragment.kt
> +            it?.let { updateItems(it) } ?: failToSearch()
리스트에 값이 없을 경우 viewModel에서 liveData로 transformation을 이용하여 처리 할 수 있을 것 같습니다.

2020-01-23 10:22 UTC, taeiim commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/ContentsFragment.kt
> +    private lateinit var vm: ContentsViewModel
f753992b451bbc49a8c35e5330e185437b4d2240

커밋을 분리하지 못했습니다 ㅜㅜ 죄송해요 ㅜㅜ

2020-01-23 10:22 UTC, taeiim commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/ContentsFragment.kt
> +        vm = ViewModelProvider(this@ContentsFragment, object : ViewModelProvider.Factory {
f753992b451bbc49a8c35e5330e185437b4d2240

2020-01-23 10:22 UTC, taeiim commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/ContentsFragment.kt
> +            it?.let { updateItems(it) } ?: failToSearch()
f753992b451bbc49a8c35e5330e185437b4d2240

2020-01-23 13:51 UTC, 2giwon approved these changes
수고하셨습니다.

2020-01-27 06:03 UTC, sjjeong requested changes

2020-01-27 06:03 UTC, sjjeong commented on taeiim/MyApplication/app/build.gradle
> +apply plugin: 'kotlin-android-extensions'
이거는 왜 추가하셨나요?

2020-01-27 06:03 UTC, sjjeong commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/MainActivity.kt
> +    }
MainViewModel 생성자에 인자로 받는게 없다면 ViewModelProvider.Factory를 넣지 않아도 됩니다.

2020-01-27 06:03 UTC, sjjeong commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/ContentsViewModel.kt
> +    private fun getQueryStr(): String {
함수를 따로 만드는 것보단 사용하는 쪽에서 vm에 있는 query에 직접 접근하는게 좋은 패턴인것 같습니다.

2020-01-30 16:17 UTC, taeiim commented on taeiim/MyApplication/app/build.gradle
> +apply plugin: 'kotlin-android-extensions'
제거하였습니다.

commit : 8cfe8072c7b652649730af6784a4dffd0ecf0212

2020-01-30 16:18 UTC, taeiim commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/ContentsViewModel.kt
> +    private fun getQueryStr(): String {
변경하였습니다. 감사합니다 

commit : 0dd58a9d8255092cb1115264887bc04df58af392

2020-01-30 16:19 UTC, taeiim commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/MainActivity.kt
> +    }
어떤식으로 해야되나요??
제거해봤는데 ViewModelProvider의 Factory가 NonNull 이라서 제거하면 빨간줄 뜨고 안되네요 ㅜㅜ

2020-01-31 15:47 UTC, sjjeong commented on taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/MainActivity.kt
> +    }
ViewModelProviders를 사용하면 됩니다

2020-02-10 16:16 UTC, closed without merging