HW-6 MVVM 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #442
Opened 2020-01-21 15:27 UTC by JayYi

2020-01-27 05:48 UTC, sjjeong requested changes

2020-01-27 05:48 UTC, sjjeong commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/ui/BaseFragment.kt
> +    override fun onActivityCreated(savedInstanceState: Bundle?) {
최근에 onActivityCreated를 사용하지말고 onViewCreated를 사용하라고 권장하더라구요

2020-01-27 05:48 UTC, sjjeong commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/ui/kin/KinViewModel.kt
> +            }
해당 코드는 repository에서 getKin함수 내부에서 호출 해야 할 것 같습니다.
ViewModel입장에서는 repository가 준 데이터만 받아오면 되는데 history를 refresh하는 작업까지 있는건 좋지 않습니다.

2020-01-27 13:10 UTC, JayYi commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/ui/BaseFragment.kt
> +    override fun onActivityCreated(savedInstanceState: Bundle?) {
수정했습니다.
095f7b84ca68557c8a95137d2790157bdf5dce64

2020-01-27 13:11 UTC, JayYi commented on JayYi/ArchitectureStudy/app/src/main/java/com/jay/architecturestudy/ui/kin/KinViewModel.kt
> +            }
수정했습니다.
8e5e16aff73f881deaa3e2d9e240255dd33a4647

2020-01-28 15:37 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-01-28 15:39 UTC, sjjeong-dino approved these changes

2020-01-29 00:32 UTC, merged