Class06/ AAC ViewModel + LiveData
sjjeong/GoogryAndroidArchitecutreStudy pull request #443
Opened 2020-01-22 08:35 UTC by dksush

2020-01-27 05:54 UTC, sjjeong requested changes

2020-01-27 05:54 UTC, sjjeong commented on dksush/AndroidArchitecture/app/build.gradle
> +apply plugin: 'kotlin-android-extensions'
이거는 왜 다시 추가하셨나요?

2020-01-27 05:54 UTC, sjjeong commented on dksush/AndroidArchitecture/app/src/main/java/com/example/androidarchitecture/ui/blog/BlogFragment.kt
> +        vm.blankInputText.observe(this, Observer {
fragment에서는 lifecycleOwner를 this가 아닌 viewLifecycleOwner를 사용해야 합니다.
아래 errorToast도 같이 수정해주세요

2020-01-27 05:54 UTC, sjjeong commented on dksush/AndroidArchitecture/app/src/main/java/com/example/androidarchitecture/ui/blog/BlogViewModel.kt
> +    val renderItems get() = _renderItems
이렇게 하면 type이 MutableLiveData라서 의미가 없습니다.
type을 LiveData라고 명시해줘야 합니다.

2020-01-27 05:54 UTC, sjjeong commented on dksush/AndroidArchitecture/app/src/main/java/com/example/androidarchitecture/ui/blog/BlogViewModel.kt
> +                isListEmpty.value = it.isEmpty()
이거 같은 경우에는 Transformations.map()을 이용하시면 됩니다.
그리고 위에서 isNotEmpty를 검사했기 때문에 isEmpty는 무조건 false입니다.

2020-01-27 05:54 UTC, sjjeong commented on dksush/AndroidArchitecture/app/src/main/res/layout/fragment_image.xml
> +            android:visibility="@{vm.isListEmpty()? View.VISIBLE : View.INVISIBLE}"
왜 여기에만 isListEmpty()라고 ()가 붙어있나요?

2020-01-28 05:37 UTC, dksush commented on dksush/AndroidArchitecture/app/src/main/java/com/example/androidarchitecture/ui/blog/BlogFragment.kt
> +        vm.blankInputText.observe(this, Observer {
수정했습니다.

c368089

2020-02-05 02:35 UTC, dksush commented on dksush/AndroidArchitecture/app/src/main/java/com/example/androidarchitecture/ui/blog/BlogViewModel.kt
> +    val renderItems get() = _renderItems
수정했습니다

153fa86

2020-02-05 02:47 UTC, dksush commented on dksush/AndroidArchitecture/app/src/main/res/layout/fragment_image.xml
> +            android:visibility="@{vm.isListEmpty()? View.VISIBLE : View.INVISIBLE}"
수정했습니다

910d1ce

2020-02-05 02:49 UTC, dksush commented on dksush/AndroidArchitecture/app/build.gradle
> +apply plugin: 'kotlin-android-extensions'
수정했습니다. 추가 이유는.. 별 이유 없었습니다..

6107b7e

2020-02-05 02:50 UTC, dksush commented on dksush/AndroidArchitecture/app/src/main/java/com/example/androidarchitecture/ui/blog/BlogViewModel.kt
> +                isListEmpty.value = it.isEmpty()
Transformations.map 을 찾아봤는데
이같은 경우가 어떤 경우인지 잘 이해가 안됩니다. 설명해 주시면 감사하겠습니다.

2020-02-06 11:38 UTC, sjjeong requested changes

2020-02-06 11:38 UTC, sjjeong commented on dksush/AndroidArchitecture/app/src/main/java/com/example/androidarchitecture/ui/blog/BlogViewModel.kt
> +                isListEmpty.value = it.isEmpty()
renderItems가 값이 변하면 isListEmpty도 변해야 하는것이기 때문에 transformations.map을 쓰면 되는거죠
작성하신 코드처럼 하게 되면 나중에 다른 부분에서 isListEmpty에 값을 넣어야하는 것을 하지 않으면 버그가 발생하게 됩니다.

2020-02-07 02:41 UTC, dksush commented on dksush/AndroidArchitecture/app/src/main/java/com/example/androidarchitecture/ui/blog/BlogViewModel.kt
> +                isListEmpty.value = it.isEmpty()
아아 그렇군요. 수정했습니다.

93e784d

2020-02-07 13:54 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-02-08 03:23 UTC, merged