HW-5 MVVM 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #444
Opened 2020-01-22 18:59 UTC by handnew04

2020-01-26 18:06 UTC, ghkdua1829 approved these changes
수고하셨습니다~~!👍

2020-01-27 05:58 UTC, sjjeong requested changes

2020-01-27 05:58 UTC, sjjeong commented on handnew04/app/src/main/java/com/example/handnew04/adapter/DataBindingAdapter.kt
> +    }
두개 조건을 하나의 if식에 넣을 수 있습니다.
run을 쓸 필요가 없습니다.

2020-01-27 05:58 UTC, sjjeong commented on handnew04/app/src/main/java/com/example/handnew04/ui/main/MainActivity.kt
>      }
ViewModel로 옮겨서 xml에서도 ViewModel에 있는 함수를 호출하게 해주면 됩니다.
입력값은 vm에 가지고 있고 two-way binding으로 처리해주면 됩니다.

2020-01-28 15:34 UTC, handnew04 commented on handnew04/app/src/main/java/com/example/handnew04/adapter/DataBindingAdapter.kt
> +    }
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/444/commits/3f80ca9fcdaa968e7d733346cb8a3136379a16ba

2020-01-28 15:35 UTC, handnew04 commented on handnew04/app/src/main/java/com/example/handnew04/ui/main/MainActivity.kt
>      }
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/444/commits/2de815627acc087bf3c57c330fad90391524e21b

2020-01-28 15:40 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-01-29 16:49 UTC, merged