HW-3 MVP 패턴 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #445
Opened 2020-01-23 02:51 UTC by YKW93

2020-01-25 17:44 UTC, Minoyam approved these changes
제가 볼때는 문제 없어보이네요 ㅋㅋ

2020-01-27 06:02 UTC, sjjeong requested changes

2020-01-27 06:02 UTC, sjjeong commented on class08/YKW93/ArchitectureStudy/app/src/main/java/com/studyfork/architecturestudy/base/BaseContract.kt
> +        fun setLoadingVisible(visible: Boolean)
setLoadingVisible이라는 것으로 boolean을 파라미터로 전달하는 것 보다 showLoading, hideLoading처럼 함수를 나누는게 더 명확합니다.

2020-01-27 06:02 UTC, sjjeong commented on class08/YKW93/ArchitectureStudy/app/src/main/java/com/studyfork/architecturestudy/base/BasePresenter.kt
> +    override fun subscribe(disposable: Disposable) {
Disposable의 extension함수로 만들면 더 가독성 좋은 코드를 만들 수 있습니다.

2020-01-27 06:02 UTC, sjjeong commented on class08/YKW93/ArchitectureStudy/app/src/main/java/com/studyfork/architecturestudy/ui/main/MainActivity.kt
> +        get() = MainPresenter(this)
이렇게 하면 presenter를 get 할 때 마다 새로운 MainPresenter가 생성됩니다.
override val presenter: MainPresenter = MainPresenter(this)
로 해야합니다.

2020-01-29 05:29 UTC, YKW93 commented on class08/YKW93/ArchitectureStudy/app/src/main/java/com/studyfork/architecturestudy/base/BaseContract.kt
> +        fun setLoadingVisible(visible: Boolean)
87860b9 변경했습니다!

2020-01-29 05:30 UTC, YKW93 commented on class08/YKW93/ArchitectureStudy/app/src/main/java/com/studyfork/architecturestudy/ui/main/MainActivity.kt
> +        get() = MainPresenter(this)
4959725 수정했습니다!

2020-01-29 05:30 UTC, YKW93 commented on class08/YKW93/ArchitectureStudy/app/src/main/java/com/studyfork/architecturestudy/base/BasePresenter.kt
> +    override fun subscribe(disposable: Disposable) {
2da17f3 수정은했는데 이렇게 하는게 맞는지 모르겠네요 ㅠㅠ..

2020-01-29 11:42 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-01-29 11:55 UTC, merged