HW-3 MVP패턴 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #446
Opened 2020-01-23 16:57 UTC by slflfl12

2020-01-28 13:30 UTC, L91519 commented on class08/slflfl12/Study/app/src/main/java/com/example/study/data/source/local/NaverSearchLocalDataSourceImpl.kt
> +            return instance!!
!!를 사용하신 이유가 따로 있으실까요?

2020-01-28 13:30 UTC, L91519 commented on class08/slflfl12/Study/app/src/main/java/com/example/study/data/source/local/SearchResultDatabase.kt
> +            return instance!!
!!가 위험하다고 알고있는데 이렇게 사용하신 이유가 따로 있으실까요?

2020-01-29 12:05 UTC, slflfl12 commented on class08/slflfl12/Study/app/src/main/java/com/example/study/data/source/local/NaverSearchLocalDataSourceImpl.kt
> +            return instance!!
instance의 타입이 NaverSearchLocalDataSourceImpl? 타입이라 !!안붙이면 빨간줄 그여서 사용했었습니다.
그래서 커밋처럼 바꾸니까 되긴하던데 이렇게 바꾸면 왜 오류가 아닌건지 이유는 모르겠네요
d8424cc

2020-01-29 12:05 UTC, slflfl12 commented on class08/slflfl12/Study/app/src/main/java/com/example/study/data/source/local/SearchResultDatabase.kt
> +            return instance!!
수정했습니다
c7040ae

2020-01-29 12:07 UTC, slflfl12 commented on class08/slflfl12/Study/app/src/main/java/com/example/study/data/source/local/NaverSearchLocalDataSourceImpl.kt
> +            return instance!!
instance의 타입이 NaverSearchLocalDataSourceImpl? 타입이라 !!을 안붙이면 빨간줄이 생겨서 붙였었습니다.
그런데 커밋처럼 바꾸면 되긴하던데 왜그런지는 이유는 모르겠네요...
d8424cc

2020-01-29 12:07 UTC, slflfl12 commented on class08/slflfl12/Study/app/src/main/java/com/example/study/data/source/local/SearchResultDatabase.kt
> +            return instance!!
수정했습니다
c7040ae

2020-01-29 12:57 UTC, L91519 approved these changes

2020-01-29 15:55 UTC, sjjeong requested changes

2020-01-29 15:55 UTC, sjjeong commented on class08/slflfl12/Study/app/src/main/java/com/example/study/data/source/local/SearchResultDatabase.kt
> +            return instance!!
리뷰는 SearchResultDatabase 인데 수정하신건 NaverSearchRemoteDataSourceImpl네요

2020-01-29 15:55 UTC, sjjeong commented on class08/slflfl12/Study/app/src/main/java/com/example/study/ui/main/MainPresenter.kt
> +                        naverSearchRepository.addSearchResult(SearchResult(Gson().toJson(it.items)))
이 로직은 repository에서 처리해줘야 합니다.

2020-01-29 15:55 UTC, sjjeong commented on class08/slflfl12/Study/app/src/main/java/com/example/study/ui/main/MainPresenter.kt
> +            }
이 작업이 repository에서 진행되고나서 가져온 데이터를 view.updateMovieList()에 파라미터로 넣어주면 됩니다.

2020-01-29 15:55 UTC, sjjeong commented on class08/slflfl12/Study/app/src/main/java/com/example/study/ui/main/MainPresenter.kt
> +    }
이 함수가 있는 이유를 잘 모르겠습니다.
결국 addDisposable에 넘어온 disposable을 compositeDisposable에 넣어주는거라면 함수 호출부분에 compositeDisposable에 직접 넣어주면 되지 않나요?

2020-01-30 13:36 UTC, slflfl12 commented on class08/slflfl12/Study/app/src/main/java/com/example/study/ui/main/MainPresenter.kt
> +    }
저도 굳이 안만들어도 되는 함수라고 생각하긴 했었는데 역시 그렇군요!!
그럼 이렇게 바꾸면 되나요???
abbfb31

2020-01-30 13:44 UTC, slflfl12 commented on class08/slflfl12/Study/app/src/main/java/com/example/study/ui/main/MainPresenter.kt
> +                        naverSearchRepository.addSearchResult(SearchResult(Gson().toJson(it.items)))
이런식으로 RemoteDataSource에서 addSearchResult()를 수행 할 수 있도록 변경하였는데
파라미터로 SearchResultDatabase를 넘겨줘야 실행할 수 있더라구요
이렇게 바꾸라는 말씀이셨나요..?
d1be2e7

2020-01-30 13:50 UTC, slflfl12 commented on class08/slflfl12/Study/app/src/main/java/com/example/study/ui/main/MainPresenter.kt
> +            }
이해가 가질 않습니다 ㅠㅠ
위에 코드는 view.updateMovieList()의 파라미터로 repository에서 가져온 데이터를 넣은 것이 아닌가요?? ㅠㅠ

2020-01-30 13:51 UTC, slflfl12 commented on class08/slflfl12/Study/app/src/main/java/com/example/study/data/source/local/SearchResultDatabase.kt
> +            return instance!!
아 그렇네요 죄송합니다! 변경했습니다
5bad2e4

2020-01-30 13:59 UTC, slflfl12 commented on class08/slflfl12/Study/app/src/main/java/com/example/study/ui/main/MainPresenter.kt
> +            }
.subscribeOn(Schedulers.io())
            .observeOn(AndroidSchedulers.mainThread())
            .doOnSubscribe {
                view.showProgress()
            }
            .doAfterTerminate {
                view.hideProgress()
            }
            .subscribe({
                it?.let {
                    if (it.items.isNotEmpty()) {
                        view.updateMovieList(it.items)
                        view.hideKeyboard()
                    } else {
                        view.showErrorEmptyResult()
                    }
                }
            }, {
                it.printStackTrace()
            })
그리고 또 궁금한게 이 부분 전체를 repository에서 실행시켜주는것이 더 나은구조인가요??

2020-01-30 13:59 UTC, slflfl12 commented on class08/slflfl12/Study/app/src/main/java/com/example/study/ui/main/MainPresenter.kt
> +                        naverSearchRepository.addSearchResult(SearchResult(Gson().toJson(it.items)))
.subscribeOn(Schedulers.io())
        .observeOn(AndroidSchedulers.mainThread())
        .doOnSubscribe {
            view.showProgress()
        }
        .doAfterTerminate {
            view.hideProgress()
        }
        .subscribe({
            it?.let {
                if (it.items.isNotEmpty()) {
                    view.updateMovieList(it.items)
                    view.hideKeyboard()
                } else {
                    view.showErrorEmptyResult()
                }
            }
        }, {
            it.printStackTrace()
        })
그리고 또 궁금한게 이 부분 전체를 repository에서 실행시켜주는것이 더 나은구조인가요??

2020-01-31 15:51 UTC, sjjeong commented on class08/slflfl12/Study/app/src/main/java/com/example/study/ui/main/MainPresenter.kt
> +                        naverSearchRepository.addSearchResult(SearchResult(Gson().toJson(it.items)))
@slflfl12 
repository에 addSearchResult()를 사용하시면 되지 않을까요?
이미 remote와 관련된 건 NaverSearchRemoteDataSource가 하고 local과 관련된건 NaverSearchLocalDataSource 하고 있으니까요
그리고 remote에 dao를 넘겨서 저장시키는 코드를 작성하신건 아직 Repository와 DataSource에 대해 이해를 못하신것 같습니다.
Repository, RemoteDataSource, LocalDataSource가 각각 어떤 역할을 하는지 다시 생각해보세요

2020-01-31 15:53 UTC, sjjeong commented on class08/slflfl12/Study/app/src/main/java/com/example/study/ui/main/MainPresenter.kt
> +            }
SearchResult

2020-02-02 08:27 UTC, slflfl12 commented on class08/slflfl12/Study/app/src/main/java/com/example/study/ui/main/MainPresenter.kt
> +            }
변경했습니다
2d3cd3a

2020-02-02 08:28 UTC, slflfl12 commented on class08/slflfl12/Study/app/src/main/java/com/example/study/ui/main/MainPresenter.kt
> +                        naverSearchRepository.addSearchResult(SearchResult(Gson().toJson(it.items)))
변경했습니다
2d3cd3a

2020-02-02 08:28 UTC, slflfl12 commented on class08/slflfl12/Study/app/src/main/java/com/example/study/ui/main/MainPresenter.kt
> +            }
변경했습니다
9a3674c

2020-02-05 00:56 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-02-05 18:12 UTC, merged