HW-5 MVVM 적용하기
sjjeong/GoogryAndroidArchitecutreStudy pull request #448
Opened 2020-01-26 18:03 UTC by ghkdua1829

2020-01-27 12:43 UTC, handnew04 requested changes

2020-01-27 12:43 UTC, handnew04 commented on ghkdua1829/app/src/main/java/com/example/architecture_project/ui/main/MainActivity.kt
> +    private fun ObservableData() {
첫글자를 소문자로, 첫 단어를 동사로 바꿔주세요

2020-01-27 14:50 UTC, ghkdua1829 commented on ghkdua1829/app/src/main/java/com/example/architecture_project/ui/main/MainActivity.kt
> +    private fun ObservableData() {
d425098e2a075db153e14d86e76d3a7fb7e16572

2020-01-28 14:44 UTC, handnew04 approved these changes
수고하셨습니다!

2020-01-29 15:56 UTC, sjjeong requested changes

2020-01-29 15:56 UTC, sjjeong commented on ghkdua1829/app/src/main/java/com/example/architecture_project/feature/movie/ImageBindingModel.kt
> +                (this.adapter as MovieAdapter).setMovieItemList(movieData as List<Movie>)
{} 추가 해주세요

2020-01-29 15:56 UTC, sjjeong commented on ghkdua1829/app/src/main/java/com/example/architecture_project/ui/main/MainViewModel.kt
> +    fun getMovieDataNum(data: NaverApi) {
함수명이 get이면 return이 있는게 일반적입니다.
함수명을 적절하게 변경하거나 inline으로 처리하면 될 것 같습니다.

2020-01-31 12:36 UTC, ghkdua1829 commented on ghkdua1829/app/src/main/java/com/example/architecture_project/ui/main/MainViewModel.kt
> +    fun getMovieDataNum(data: NaverApi) {
ab76aab821e5dfa06e276cfcad73e02153fb4a83

2020-01-31 12:36 UTC, ghkdua1829 commented on ghkdua1829/app/src/main/java/com/example/architecture_project/feature/movie/ImageBindingModel.kt
> +                (this.adapter as MovieAdapter).setMovieItemList(movieData as List<Movie>)
ab76aab821e5dfa06e276cfcad73e02153fb4a83

2020-01-31 15:55 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-02-01 00:36 UTC, merged