HW-5 MVVM 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #449
Opened 2020-01-27 04:17 UTC by AhnHyeonho

* 기존 MVP패턴 적용해제 (-> MVVM으로 변경)
* 그에 따른 BindingAdapter추가
* 그에 따른 xml 수정
* kapt warning 제거를 위한 gradle.properties 수정

2020-01-31 09:05 UTC, seunghee63 requested changes

2020-01-31 09:05 UTC, seunghee63 commented on AhnHyeonho/FirstProject/app/src/main/res/layout/activity_main.xml
> +                    android:onClick="@{()-> mainActivity.btnSearchClick()}"
xml 에서 액티비티를 변수로 지정하고 메소드를 호출하는.. 이런 방법으로 해당 기능을 구현하는것이 올바른 방법인지에 대한 의문이 듭니다!

Databinding의 특징을 잘 적용한 코드인 것 같다는 생각은 들지만,
MainActivity를 xml 상에서 변수로 지정하여 메모리를 차지하는 것 보다는 activity상에서 클릭리스너를 설정하고, viewModel 내의 함수를 실행시키는 것이 더 나을 수도 있다는 생각이 들어서요..! 사실 저도 이전 프로젝트를 진행하거나 혼자 공부를 할 때, 현준님과 같은 방법으로 구현을 해왔었기에 어떤 방법이 옳을 것이라고 확정 할 수는 없지만 뭔가 의문이 들어서.. 현준님의 생각을 알고 싶어서 의견 남겨봅니다.
기본적인 java 또는 안드로이드의 동작원리?! 를 알아야 정확하게 알 수 있는 내용인가 싶기도 해서 계속 고민이 되네요..?!

2020-01-31 10:40 UTC, AhnHyeonho commented on AhnHyeonho/FirstProject/app/src/main/res/layout/activity_main.xml
> +                    android:onClick="@{()-> mainActivity.btnSearchClick()}"
승희님 의견듣고 곰곰히 생각해 보았습니다! 우선 저도 두가지 측면에서 생각을 해보았는데요,

1. 제가한 방법 - xml에 activity를 변수로 할당하고 메소드를 호출하는 방식
-> 액션메소드(click메소드)명을 알맞게 수정한다면, activity코드를 보지않고 xml만 보고도 해당 버튼이 어떠한 기능을 수행하는지 파악하기 용이할 것 같습니다. (제 코드에서는 btnSearchClick()명을 수정해야할 것 같습니다.)

2. 승희님의 방법
-> 말씀하신대로 변수를 할당을 하지 않아서 메모리 측면에서 효율적인 것 같습니다.

현재 제 코드상으로도 단발적으로만 사용하므로 승희님 의견대로 activity상에서 설정해주는 게 효율적으로 보입니다.

2020-01-31 12:51 UTC, BeokBeok commented on AhnHyeonho/FirstProject/app/src/main/res/layout/activity_main.xml
> +                    android:onClick="@{()-> mainActivity.btnSearchClick()}"
지나가다가 첨언 드리고자 들렀습니다.:sweat_smile:

xml 상에서 클릭 리스너를 지정하나 소스 상에서 클릭 리스너를 지정하나 
결국 메모리를 할당하는 것은 동일합니다.

xml 상에 데이터바인딩 적용 후 빌드 시, 파일이 생성됩니다. (본 리뷰 기준 ActivityMainBindingImpl.java)

```
@Override
    protected void executeBindings() {
        // 중략
        if ((dirtyFlags & 0x8L) != 0) {
            // api target 1

            this.btnSearch.setOnClickListener(mCallback1);
        }
        // 중략
    }
```

위의 코드를 보시면, setOnClickListener 를 통하여 등록해주고 있습니다.

2020-01-31 14:59 UTC, sabgilhun commented on AhnHyeonho/FirstProject/app/src/main/res/layout/activity_main.xml
> +                    android:onClick="@{()-> mainActivity.btnSearchClick()}"
변수 할당이 어떤걸 의미하는지 정확히 모르겠지만 지금처럼 액티비티를 바인딩클래스에서 변수로 들고 있으면 순환참조 구조가 되어서 바람직해보이진 않네욥

2020-01-31 19:30 UTC, seunghee63 commented on AhnHyeonho/FirstProject/app/src/main/res/layout/activity_main.xml
> +                    android:onClick="@{()-> mainActivity.btnSearchClick()}"
'메모리 할당' 문제 때문에 잘못 된게 아닌가- 했던 제 생각은 아마 틀린듯 하네요... ㅎㅎ!
그래도 sabgilhun님의 의견을 근거로 '순환참조구조' 이기에, 이의 코드보다는 현재 코드가 조금 더 바람직한 것 같다는 생각이 듭니다!

멘토님 의견도 들어보면 좋을 것 같습니다 :> !

2020-01-31 19:30 UTC, seunghee63 approved these changes

2020-02-01 11:45 UTC, sjjeong commented on AhnHyeonho/FirstProject/app/src/main/res/layout/activity_main.xml
> +                    android:onClick="@{()-> mainActivity.btnSearchClick()}"
제가 의도했던 구현방법은 아래와 같습니다.
```xml
android:onClick="@{() -> vm. doSearch()}"
```
이렇게 하고 ViewModel에서는 two-way binding으로 검색어를 들고 있어서 doSearch()에서 그 값을 사용하는 겁니다.

2020-02-01 12:22 UTC, AhnHyeonho commented on AhnHyeonho/FirstProject/app/src/main/res/layout/activity_main.xml
> +                    android:onClick="@{()-> mainActivity.btnSearchClick()}"
수정했습니다.

2b759d7

2020-02-02 05:27 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-02-02 05:47 UTC, merged