HW-3 MVP 구현
sjjeong/GoogryAndroidArchitecutreStudy pull request #450
Opened 2020-01-27 05:43 UTC by Minoyam

2020-01-29 02:40 UTC, YKW93 approved these changes

2020-01-29 16:15 UTC, sjjeong requested changes

2020-01-29 16:15 UTC, sjjeong commented on class08/Minoyam/app/src/main/java/com/cnm/homework/ui/MainPresenter.kt
> +class MainPresenter(private val view: MainContract.View, private val context: Context) :
여기서 context를 받지 말고 context로 만드는 객체들을 받아주세요

2020-01-30 14:18 UTC, Minoyam commented on class08/Minoyam/app/src/main/java/com/cnm/homework/ui/MainPresenter.kt
> +class MainPresenter(private val view: MainContract.View, private val context: Context) :
b65a0e3e2f8ab7f54bca13c0624276e1fefef7c9 수정했습니다

2020-01-31 15:56 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-02-01 05:14 UTC, merged