HW-5 MVVM 패턴으로 리팩토링
sjjeong/GoogryAndroidArchitecutreStudy pull request #451
Opened 2020-01-30 06:34 UTC by 172900

- MVP패턴에서 MVVM패턴으로 리팩토링
- 모든 파일에서 Presenter관련 로직 삭제

2020-01-31 08:16 UTC, swppppp approved these changes

2020-01-31 16:04 UTC, sjjeong requested changes

2020-01-31 16:04 UTC, sjjeong commented on 172900/GoogleArchitectureStudy/app/src/main/res/layout/activity_main.xml
> +            android:onClick="@{() -> viewModel.searchMovies(viewModel.searchString)}"/>
저번 리뷰할 때 못봤던 내용이네요
이미 searchString이 two-way binding되어 있기 때문에 searchMovies()를 호출할 때 전달해줄 필요 없이 함수 내부에서 직접 searchString에 접근해서 사용하면 됩니다.

2020-02-04 03:58 UTC, 172900 commented on 172900/GoogleArchitectureStudy/app/src/main/res/layout/activity_main.xml
> +            android:onClick="@{() -> viewModel.searchMovies(viewModel.searchString)}"/>
09dc6c7

2020-02-05 00:56 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-02-08 11:34 UTC, merged