HW-5 MVVM 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #452
Opened 2020-01-30 14:45 UTC by seunghee63

2020-01-31 03:35 UTC, AhnHyeonho approved these changes

2020-01-31 03:35 UTC, AhnHyeonho commented on seunghee63/MyApplication/app/src/main/java/com/song2/myapplication/ui/MainActivity.kt
> +        //??? 어떻게 처리하지???
필요없는 주석은 제거해주세요

2020-01-31 03:35 UTC, AhnHyeonho commented on seunghee63/MyApplication/app/src/main/java/com/song2/myapplication/ui/MainViewModel.kt
> +    val MAINVIEWMODEL = "mainViewModel :"
단순 log tag출력을 위한 string이라면 변수로 할당해주기보단 string resource로  log tag들을 관리해주고 이를 불러오는 식으로하는게 좋다고 생각합니다. 승희님의 의견은 어떤지 궁금하네요

2020-02-01 11:55 UTC, sjjeong requested changes

2020-02-01 11:55 UTC, sjjeong commented on seunghee63/MyApplication/app/src/main/java/com/song2/myapplication/ui/MainActivity.kt
>              btnMainActSearchBtn.setOnClickListener {
버튼 클릭 이벤트는 xml에서 처리해주세요

2020-02-01 11:55 UTC, sjjeong commented on seunghee63/MyApplication/app/src/main/java/com/song2/myapplication/adapter/MovieAdapter.kt
> +            addAll(newMovieList!!)
!!는 불필요해요

2020-02-01 11:55 UTC, sjjeong commented on seunghee63/MyApplication/app/src/main/java/com/song2/myapplication/ui/MainActivity.kt
> +    private fun showGetMovieSuccess() {
사용하지 않는 함수입니다. 제거해주세요

2020-02-01 11:55 UTC, sjjeong commented on seunghee63/MyApplication/app/src/main/java/com/song2/myapplication/ui/MainActivity.kt
>          binding.etMainActSearch.setOnEditorActionListener(object : TextView.OnEditorActionListener {
EditorActionListener를 추가하는걸 BindingAdapter로 만들어볼래요?
이건 꼭 하지 않아도 되는 거라서 안하셔도 돼요

2020-02-01 23:19 UTC, seunghee63 commented on seunghee63/MyApplication/app/src/main/java/com/song2/myapplication/ui/MainActivity.kt
> +        //??? 어떻게 처리하지???
8b40444

2020-02-29 12:01 UTC, closed without merging