Class07/swppppp
sjjeong/GoogryAndroidArchitecutreStudy pull request #453
Opened 2020-01-31 08:19 UTC by swppppp

mvp -> mvvm패턴 적용

2020-01-31 16:05 UTC, sjjeong commented
PR 이름 변경해주세요

2020-02-01 09:33 UTC, 172900 approved these changes

2020-02-01 12:14 UTC, sjjeong requested changes

2020-02-01 12:14 UTC, sjjeong commented on swppppp/app/src/main/java/com/siwon/prj/view/MainActivity.kt
> +            vm.searchMovie(edit_text_input.text.toString())
onClick을 xml에서 처리해서 xml에서 바로 vm에 있는 함수를 호출하도록 해보세요

2020-02-01 12:14 UTC, sjjeong commented on swppppp/app/src/main/java/com/siwon/prj/view/MainViewmodel.kt
> +    fun searchMovie(input: String) {
input값을 파라미터로 받지 말고 two-way binding으로 처리해보세요

2020-02-02 07:06 UTC, swppppp commented on swppppp/app/src/main/java/com/siwon/prj/view/MainActivity.kt
> +            vm.searchMovie(edit_text_input.text.toString())
312d34e3

2020-02-02 07:06 UTC, swppppp commented on swppppp/app/src/main/java/com/siwon/prj/view/MainViewmodel.kt
> +    fun searchMovie(input: String) {
312d34e3

2020-02-02 07:14 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-02-02 07:14 UTC, merged