HW-04 DataBinding 구현
sjjeong/GoogryAndroidArchitecutreStudy pull request #455
Opened 2020-02-03 10:54 UTC by Minoyam

2020-02-04 04:15 UTC, YKW93 commented on class08/Minoyam/app/src/main/java/com/cnm/homework/ui/MainActivity.kt
> +        binding = DataBindingUtil.setContentView(this, R.layout.activity_main)
lazy 를 사용해서 바로 초기화 해도 괜찮지 않을까요?

2020-02-04 04:15 UTC, YKW93 commented on class08/Minoyam/app/src/main/java/com/cnm/homework/adapter/MovieAdapter.kt
>              itemView.setOnClickListener {
itemView가 아닌 binding.root에 clickListener을 달아주는건 어떨까요??

2020-02-04 04:15 UTC, YKW93 commented on class08/Minoyam/app/src/main/java/com/cnm/homework/adapter/BindingAdapter.kt
> +    Glide.with(imageView.context).load(imageUri).into(imageView)
imageUri에 대한 null체크가 있으면 더욱 좋을꺼같습니다!

2020-02-04 14:12 UTC, Minoyam commented on class08/Minoyam/app/src/main/java/com/cnm/homework/ui/MainActivity.kt
> +        binding = DataBindingUtil.setContentView(this, R.layout.activity_main)
d9f162f671ad573aa79684892e141bb2ee14cf45 수정했습니다

2020-02-04 14:14 UTC, Minoyam commented on class08/Minoyam/app/src/main/java/com/cnm/homework/adapter/MovieAdapter.kt
>              itemView.setOnClickListener {
e9eb77614f6067c2d97a72fbc61313220e51c89a 수정했습니다

2020-02-04 14:19 UTC, Minoyam commented on class08/Minoyam/app/src/main/java/com/cnm/homework/adapter/BindingAdapter.kt
> +    Glide.with(imageView.context).load(imageUri).into(imageView)
29c5643277f640c4d550905f9c949c891dcd6d98수정했습니다
궁금한게 Response에서 imageUri은 String? 이아닌 String으로 받아오는데
그래도 null검사를 해줘야하는건가요??

2020-02-05 02:45 UTC, YKW93 commented on class08/Minoyam/app/src/main/java/com/cnm/homework/adapter/BindingAdapter.kt
> +    Glide.with(imageView.context).load(imageUri).into(imageView)
imageUri 값이 null 로 올 수도 있어서 String? 이걸로 선언해줘야되지 않을까요?

2020-02-05 02:46 UTC, YKW93 approved these changes

2020-02-05 02:50 UTC, Minoyam commented on class08/Minoyam/app/src/main/java/com/cnm/homework/adapter/BindingAdapter.kt
> +    Glide.with(imageView.context).load(imageUri).into(imageView)
그렇군요 답변 감사합니다!

2020-02-06 13:00 UTC, sjjeong requested changes

2020-02-06 13:00 UTC, sjjeong commented on class08/Minoyam/app/build.gradle
> +    kaptTest "androidx.ro   om:room-testing:2.2.3"
오타가 있네요

2020-02-06 13:00 UTC, sjjeong commented on class08/Minoyam/app/src/main/java/com/cnm/homework/adapter/BindingAdapter.kt
> +fun bindOnEditorActionListener(editText: EditText, activity: MainActivity) {
Activity를 받는것 보단 interface 형태로 받아보면 어떨까요?

2020-02-06 13:43 UTC, Minoyam commented on class08/Minoyam/app/build.gradle
> +    kaptTest "androidx.ro   om:room-testing:2.2.3"
7104ad27a11e3f13dd610eda0698a3f0236593ce 수정했습니다

2020-02-06 14:12 UTC, Minoyam commented on class08/Minoyam/app/src/main/java/com/cnm/homework/adapter/BindingAdapter.kt
> +fun bindOnEditorActionListener(editText: EditText, activity: MainActivity) {
89f9e4a76ba948d9e8359857cd1cd4e39c63b57b 수정했습니다!

2020-02-07 13:55 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-02-08 01:53 UTC, merged