HW-4 Databinding 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #456
Opened 2020-02-04 04:06 UTC by YKW93

2020-02-04 07:17 UTC, Minoyam commented on class08/YKW93/ArchitectureStudy/app/src/main/java/com/studyfork/architecturestudy/ui/main/MainActivity.kt
>          }
안에 내용을 함수로 만들어서 xml에서 activity를 받아서 처리하는것도 좋은 방법일꺼 같습니다

2020-02-04 08:41 UTC, YKW93 commented on class08/YKW93/ArchitectureStudy/app/src/main/java/com/studyfork/architecturestudy/ui/main/MainActivity.kt
>          }
e087e02  수정했습니다!

2020-02-04 09:29 UTC, Minoyam approved these changes

2020-02-06 13:05 UTC, sjjeong requested changes

2020-02-06 13:05 UTC, sjjeong commented on class08/YKW93/ArchitectureStudy/app/src/main/java/com/studyfork/architecturestudy/base/BaseActivity.kt
> +    protected val binding: B by lazy {
lazy이기 때문에 BaseActivity를 상속받는 클래스가 binding을 호출하지 않으면 바인딩이 되지 않는 문제가 있습니다.
BaseActivity에서 onCreate시점에 명시적으로 호출해주거나 다른 방법으로 변경해야 합니다.

2020-02-07 02:35 UTC, YKW93 commented on class08/YKW93/ArchitectureStudy/app/src/main/java/com/studyfork/architecturestudy/base/BaseActivity.kt
> +    protected val binding: B by lazy {
112bace
수정했는데 이런식으로 사용하면 괜찮을까요??

2020-02-07 13:56 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-02-08 04:37 UTC, merged