HW-6 AAC ViewModel & LiveData 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #458
Opened 2020-02-04 15:11 UTC by AhnHyeonho

* 기존 MVVM패턴의 VM을 AAC VM으로 변경
* 기존 Observable data들을 LiveData로 변경
* BindingAdapter의 recyclerView 관련 setter메소드 삭제
* xml 수정

2020-02-07 12:29 UTC, seunghee63 approved these changes

2020-02-07 12:29 UTC, seunghee63 commented on AhnHyeonho/FirstProject/app/src/main/java/com/hansung/firstproject/ui/main/MainViewModel.kt
> +            _showKeywordEmptyError.value = Throwable()
MutableLiveData에 값을 넣을 때,

```
_text.value = "data"
_text.setValue("data")
``` 
이렇게 setValue를 해서 데이터를 넣으셨는데,

```
_text.postValue("data")
```
이런식으로 postValue 메소드를 이용해서도 값을 넣을 수 있다고합니다!
postValue메소드도 값을 set하는 함수이지만, 메인쓰레드에서 과정이 이루어지는 setValue와는 다르게, 그 과정이 백그라운드에서 진행된다고 합니다!

[https://wooooooak.github.io/android/2019/06/11/Android_liveData_value/](https://wooooooak.github.io/android/2019/06/11/Android_liveData_value/)
한번 보시면 좋을 것 같습니다 :>

코드를 꼼꼼히 확인 해 봤는데 딱히 수정사항이 없어서.. 제가 이번과제 하면서 새로 알게되었던 정보 남겨놓고 갑니당... 수고하셨습니다~

2020-02-08 06:31 UTC, AhnHyeonho commented on AhnHyeonho/FirstProject/app/src/main/java/com/hansung/firstproject/ui/main/MainViewModel.kt
> +            _showKeywordEmptyError.value = Throwable()
정보 감사합니다 👍 앞으로 liveData를 쓸 때 경우에 따라 postValue()와 setValue()를 적절히 사용해야겠네요.

2020-02-08 11:15 UTC, sjjeong requested changes
AAC ViewModel 객체 생성하는게 잘못 됐습니다.
ViewModelProvider를 사용해서 만들도록 해주세요

2020-02-08 11:15 UTC, sjjeong commented on AhnHyeonho/FirstProject/app/src/main/java/com/hansung/firstproject/ui/main/MainActivity.kt
> +            }
기존처럼 BindingAdpater로 처리 할 수 있어요

2020-02-08 15:37 UTC, AhnHyeonho commented on AhnHyeonho/FirstProject/app/src/main/java/com/hansung/firstproject/ui/main/MainActivity.kt
> +            }
수정하였습니다.

787c1cd

2020-02-08 15:38 UTC, AhnHyeonho commented
> AAC ViewModel 객체 생성하는게 잘못 됐습니다.

수정하였습니다.


92b0ab9

2020-02-09 07:57 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-02-09 07:58 UTC, merged