HW-3 네이버 영화 검색 API 앱 , MVP 패턴 구현
sjjeong/GoogryAndroidArchitecutreStudy pull request #459
Opened 2020-02-05 03:56 UTC by HudsonPark

2020-02-05 16:05 UTC, devLibCH requested changes

2020-02-05 16:05 UTC, devLibCH commented on class08/HudsonPark/ArchtectStudy/app/src/main/java/com/example/archstudy/ui/main/MainPresenter.kt
> +        var context: Context? = mView?.let { it.getApplicationContext() }
presenter에서는 context를 사용하지 않는 것이 좋습니다
presenter에 dao를 넘겨주는 방식을 사용해야 할 것 같네요

2020-02-05 16:05 UTC, devLibCH commented on class08/HudsonPark/ArchtectStudy/app/src/main/java/com/example/archstudy/ui/main/MainActivity.kt
> +        insertLocalData(query,dataList)
local 저장은 presenter 내에서 자체적으로 하시면 됩니다.

2020-02-05 16:05 UTC, devLibCH commented on class08/HudsonPark/ArchtectStudy/app/src/main/java/com/example/archstudy/ui/main/MainActivity.kt
> +            requestRemoteData(query)
presenter에서 repository를 사용하므로 view에서는 remote와 local의 구분 없이 사용하시면 될 것 같네요

2020-02-05 16:05 UTC, devLibCH commented on class08/HudsonPark/ArchtectStudy/app/src/main/java/com/example/archstudy/ui/main/MainPresenter.kt
> +class MainPresenter(private var mContext : Context?) : MainInterface.Presenter {
위에 작성했던 것 처럼 presenter에서 context를  사용하지 않고 dao를 넘겨주면 될 것 같네요

2020-02-05 16:05 UTC, devLibCH commented on class08/HudsonPark/ArchtectStudy/app/src/main/java/com/example/archstudy/ui/main/MainActivity.kt
> +        presenter.bindView(this)
view를 presenter의 생성자로 사용하시면 좋습니다.

2020-02-05 16:05 UTC, devLibCH commented on class08/HudsonPark/ArchtectStudy/app/src/main/java/com/example/archstudy/ui/main/MainActivity.kt
> +                .get()
이부분은 merge후에 수정이 안된건가요?
이 부분도 presenter에서 사용하시면 됩니다

2020-02-06 02:15 UTC, HudsonPark commented on class08/HudsonPark/ArchtectStudy/app/src/main/java/com/example/archstudy/ui/main/MainActivity.kt
> +                .get()
@devLibCH 소스 merge하면서 error가 나서 commit reset을 했었는데, 그 과정에서 소스 트랙킹이 잘못 된듯합니다. 현재는 presenter에서 해당 소스가 실행되게 수정했습니다.

2020-02-06 02:33 UTC, HudsonPark commented on class08/HudsonPark/ArchtectStudy/app/src/main/java/com/example/archstudy/ui/main/MainActivity.kt
> +            requestRemoteData(query)
@devLibCH 그럼 Presenter에서 Local과 Remote 코드를 어떤 식으로 구분해서 사용해야 할까요?

2020-02-06 02:39 UTC, HudsonPark commented on class08/HudsonPark/ArchtectStudy/app/src/main/java/com/example/archstudy/ui/main/MainPresenter.kt
> +class MainPresenter(private var mContext : Context?) : MainInterface.Presenter {
@devLibCH 
aa6879e

2020-02-06 02:39 UTC, HudsonPark commented on class08/HudsonPark/ArchtectStudy/app/src/main/java/com/example/archstudy/ui/main/MainPresenter.kt
> +        var context: Context? = mView?.let { it.getApplicationContext() }
@devLibCH 
aa6879e

2020-02-06 02:41 UTC, HudsonPark commented on class08/HudsonPark/ArchtectStudy/app/src/main/java/com/example/archstudy/ui/main/MainActivity.kt
> +        insertLocalData(query,dataList)
@devLibCH 
b7a65a7

2020-02-06 02:44 UTC, HudsonPark commented on class08/HudsonPark/ArchtectStudy/app/src/main/java/com/example/archstudy/ui/main/MainActivity.kt
> +        presenter.bindView(this)
@devLibCH Presenter 생성할 때 view를 매개변수로 넘겨주라는 말씀이신가요?

2020-02-07 10:05 UTC, devLibCH commented on class08/HudsonPark/ArchtectStudy/app/src/main/java/com/example/archstudy/ui/main/MainActivity.kt
> +        presenter.bindView(this)
네 맞아요

2020-02-07 10:06 UTC, devLibCH commented on class08/HudsonPark/ArchtectStudy/app/src/main/java/com/example/archstudy/ui/main/MainActivity.kt
> +            requestRemoteData(query)
Presenter내에서 local을 먼저 호출해서 화면에 보여주고 이어서 remote를 호출하는 방식으로요

2020-02-29 03:36 UTC, HudsonPark commented on class08/HudsonPark/ArchtectStudy/app/src/main/java/com/example/archstudy/ui/main/MainActivity.kt
> +        presenter.bindView(this)
@devLibCH 
9e5c5c2

2020-02-29 03:36 UTC, HudsonPark commented on class08/HudsonPark/ArchtectStudy/app/src/main/java/com/example/archstudy/ui/main/MainActivity.kt
> +            requestRemoteData(query)
@devLibCH 
322a909

2020-02-29 04:37 UTC, devLibCH approved these changes

2020-02-29 13:18 UTC, sjjeong requested changes

2020-02-29 13:18 UTC, sjjeong commented on class08/HudsonPark/ArchtectStudy/app/src/main/java/com/example/archstudy/data/repository/NaverQueryRepositoryImpl.kt
> +            .apply {
apply 없이 enqueue를 해주면 됩니다

2020-02-29 13:18 UTC, sjjeong commented on class08/HudsonPark/ArchtectStudy/app/src/main/java/com/example/archstudy/ui/main/MainInterface.kt
> +interface MainInterface {
이름은 MainContract로 해주세요

2020-02-29 13:18 UTC, sjjeong commented on class08/HudsonPark/ArchtectStudy/app/src/main/java/com/example/archstudy/ui/main/MainPresenter.kt
> +        })
실패해서 리모트에서 데이터를 가져오는 로직은 repository가 해주면 됩니다.
Presenter는 repository가 주는 데이터를 화면에 뿌리는 역할을 해주면 됩니다.

2020-03-03 08:33 UTC, HudsonPark commented on class08/HudsonPark/ArchtectStudy/app/src/main/java/com/example/archstudy/ui/main/MainPresenter.kt
> +        })
@sjjeong 
a93e769

2020-03-03 08:33 UTC, HudsonPark commented on class08/HudsonPark/ArchtectStudy/app/src/main/java/com/example/archstudy/ui/main/MainInterface.kt
> +interface MainInterface {
@sjjeong 
0361329

2020-03-03 08:33 UTC, HudsonPark commented on class08/HudsonPark/ArchtectStudy/app/src/main/java/com/example/archstudy/data/repository/NaverQueryRepositoryImpl.kt
> +            .apply {
@sjjeong 
b89e29a

2020-03-03 16:03 UTC, sjjeong requested changes

2020-03-03 16:03 UTC, sjjeong commented on class08/HudsonPark/ArchtectStudy/app/src/main/java/com/example/archstudy/data/repository/NaverQueryRepositoryImpl.kt
> +            return resultData
리턴을 없애고 successCallback으로 전달해주세요

2020-03-04 13:26 UTC, HudsonPark commented on class08/HudsonPark/ArchtectStudy/app/src/main/java/com/example/archstudy/data/repository/NaverQueryRepositoryImpl.kt
> +            return resultData
@sjjeong 리턴을 없애고 successCallback으로 데이터를 전달하는 방식으로 수정했습니다. 
a1d0d95

2020-03-04 14:42 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋
앞으로 리뷰는 저에게만 달아주세요

2020-03-05 01:59 UTC, merged