HW-6 AAC ViewModel, LiveData 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #460
Opened 2020-02-05 15:52 UTC by handnew04

2020-02-06 16:32 UTC, ghkdua1829 approved these changes
수고하셨습니당 🌝

2020-02-07 14:02 UTC, sjjeong requested changes
목록이 나오지 않는 이유는 binding객체에 LifecycleOwner를 넘겨주지 않아서 그래요
LiveData를 DataBinding 해줄 땐 LifecycleOwner를 필수로 넘겨줘야 합니다.

2020-02-07 14:02 UTC, sjjeong commented on handnew04/app/src/main/java/com/example/handnew04/ui/main/MainViewModel.kt
> +    var inputText = MutableLiveData<String>()
전부 val로 선언해주세요

2020-02-07 16:34 UTC, handnew04 commented on handnew04/app/src/main/java/com/example/handnew04/ui/main/MainViewModel.kt
> +    var inputText = MutableLiveData<String>()
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/460/commits/d097d4e3e11500fdd7bf30919fc9b92c83697204

2020-02-08 11:18 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-02-08 12:08 UTC, merged