HW-6 AAC ViewModel LiveData 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #462
Opened 2020-02-06 16:28 UTC by ghkdua1829

2020-02-07 16:25 UTC, handnew04 requested changes

2020-02-07 16:25 UTC, handnew04 commented on ghkdua1829/app/src/main/java/com/example/architecture_project/feature/movie/ImageBindingModel.kt
> -    }
삭제하고 난 뒤 Adapter 에 데이터를 넣어주는 부분이 보이지 않는데, 혹시 어느부분에서 데이터를 set 하는지 궁금합니다.

2020-02-07 23:45 UTC, ghkdua1829 commented on ghkdua1829/app/src/main/java/com/example/architecture_project/feature/movie/ImageBindingModel.kt
> -    }
앗,,,리사이클러뷰에 데이터가 안 뿌려지는게 서버에 문제가 있어서 인줄 알고 철썩같이 믿고 있었는데, 데이터 set 해주는 걸 삭제만 하고 다시 만들지 않아서였네요.. 해결해주셔서 감사합니다!
05d9abe994a9ebbbb9d21cf269079a30e7c403a4

2020-02-08 00:12 UTC, ghkdua1829 commented on ghkdua1829/app/src/main/java/com/example/architecture_project/feature/movie/ImageBindingModel.kt
> -    }
근데 BindingAdapter를 통해서 데이터를 변경하는 거랑 지금 형태처럼 Observe를 통해서 데이터를 변경하는 거랑 딱히 차이가 없으니까 둘 중에 하나 아무거나 쓰면 되는 건지 궁금합니다.

2020-02-08 02:41 UTC, handnew04 commented on ghkdua1829/app/src/main/java/com/example/architecture_project/feature/movie/ImageBindingModel.kt
> -    }
저는 어댑터를 지웠다가 다시만들었어요. LifecycleOwner 를 넘겨주지 않아서 안되는줄 알았거든요. 지금은 다시 바인딩으로 바꿨는데 둘다 되더라구요! 전 리싸이클러뷰에 데이터 바인딩 하는부분도 남겨놓고 싶어서 어댑터로 다시 바꿨는데 뭐가 맞는지는 잘 모르겠어요 ㅎㅎ

2020-02-08 02:46 UTC, handnew04 approved these changes
수고하셨어요!!

2020-02-08 11:20 UTC, sjjeong requested changes

2020-02-08 11:20 UTC, sjjeong commented on ghkdua1829/app/src/main/java/com/example/architecture_project/ui/main/MainActivity.kt
> +        vm.movieData.observe(this, Observer<List<Movie>> {
기존에 BindingAdapter로 했던 형태로 변경해주세요

2020-02-08 11:20 UTC, sjjeong commented on ghkdua1829/app/src/main/java/com/example/architecture_project/ui/main/MainViewModel.kt
> +    var movieDataNum = MutableLiveData<Int>()
전부 val로 변경해주세요

2020-02-08 11:20 UTC, sjjeong commented on ghkdua1829/app/src/main/java/com/example/architecture_project/ui/main/MainViewModel.kt
> +    var isEmptyMovieData = MutableLiveData<Boolean>()
단순 이벤트를 던지기 위한 용도라면 Unit으로 type을 변경해도 됩니다.

2020-02-09 03:16 UTC, ghkdua1829 commented on ghkdua1829/app/src/main/java/com/example/architecture_project/ui/main/MainActivity.kt
> +        vm.movieData.observe(this, Observer<List<Movie>> {
4d13915b0056fb513157b13515fe89963c6dfd30

2020-02-09 03:16 UTC, ghkdua1829 commented on ghkdua1829/app/src/main/java/com/example/architecture_project/ui/main/MainViewModel.kt
> +    var movieDataNum = MutableLiveData<Int>()
bec73d7f28716463cd60f2e76050b3cd53e98371

2020-02-09 03:16 UTC, ghkdua1829 commented on ghkdua1829/app/src/main/java/com/example/architecture_project/ui/main/MainViewModel.kt
> +    var isEmptyMovieData = MutableLiveData<Boolean>()
bec73d7f28716463cd60f2e76050b3cd53e98371

2020-02-09 04:20 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-02-09 06:12 UTC, merged