Class08/dev lib ch
sjjeong/GoogryAndroidArchitecutreStudy pull request #463
Opened 2020-02-08 07:38 UTC by devLibCH

2020-02-09 06:34 UTC, HudsonPark commented on class08/devLibCH/Study/app/src/main/java/app/ch/study/ext/ViewExt.kt
> +
ViewExt.kt 파일이 BindingAdapter를 담당하는 파일인건가요?

2020-02-09 06:34 UTC, HudsonPark commented on class08/devLibCH/Study/app/src/main/java/app/ch/study/ui/main/presenter/MainPresenter.kt
>                  }
@devLibCH return@subscribe에서 '@subscribe‘를 리턴하는 이유에 대해 알 수 있을까요?

2020-02-09 09:03 UTC, devLibCH commented on class08/devLibCH/Study/app/src/main/java/app/ch/study/ext/ViewExt.kt
> +
네 맞습니다.

2020-02-09 09:05 UTC, devLibCH commented on class08/devLibCH/Study/app/src/main/java/app/ch/study/ui/main/presenter/MainPresenter.kt
>                  }
subscribe의 상위 메소드를 return하는 것이 아닌 subscribe 내에서 return을 하는 용도로 사용하고있습니다.

2020-02-10 16:11 UTC, sjjeong requested changes

2020-02-10 16:11 UTC, sjjeong commented on class08/devLibCH/Study/app/src/main/java/app/ch/study/core/BaseActivity.kt
> +    abstract fun getLayoutResId(): Int
abstract fun 대신 파라미터로 전달 받은 resId를 사용해주세요

2020-02-10 16:11 UTC, sjjeong commented on class08/devLibCH/Study/app/src/main/java/app/ch/study/ui/main/presenter/MainPresenter.kt
> +    var isVisible = ObservableField<Boolean>()
이렇게 되면 이름만 Presenter고 ViewModel처럼 구현하게 됩니다.
mvp 구현하는 것은 다 하셨으니 이 부분은 넘어가도록 할게요

2020-02-11 17:00 UTC, devLibCH commented on class08/devLibCH/Study/app/src/main/java/app/ch/study/core/BaseActivity.kt
> +    abstract fun getLayoutResId(): Int
01ea85e

2020-02-11 17:00 UTC, devLibCH commented on class08/devLibCH/Study/app/src/main/java/app/ch/study/ui/main/presenter/MainPresenter.kt
> +    var isVisible = ObservableField<Boolean>()
넵

2020-02-13 11:43 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-02-13 13:28 UTC, HudsonPark approved these changes

2020-02-13 13:29 UTC, merged