HW-8 Koin 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #469
Opened 2020-02-10 02:05 UTC by dksush

2020-02-11 00:50 UTC, JayYi requested changes
리뷰 완료했습니다. 리뷰 코멘트 확인 부탁드려요.

2020-02-11 00:50 UTC, JayYi commented on dksush/AndroidArchitecture/app/build.gradle
> +    implementation "org.koin:koin-androidx-scope:2.0.1"
koin-androidx-viewmodel 라이브러리 내에 scope이 포함되어 있는걸로 알고 있어요. 확인부탁드려요.

2020-02-11 01:13 UTC, dksush commented on dksush/AndroidArchitecture/app/build.gradle
> +    implementation "org.koin:koin-androidx-scope:2.0.1"
오오 확인해보니 포함되어 있군요. 감사합니다.
수정했습니다.
https://mvnrepository.com/artifact/org.koin/koin-androidx-scope/usages

1242e1f

2020-02-11 14:54 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-02-12 02:24 UTC, JayYi approved these changes
고생하셨습니다.

2020-02-12 02:24 UTC, merged