HW-5 MVVM 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #470
Opened 2020-02-10 03:45 UTC by YKW93

2020-02-10 04:53 UTC, Minoyam commented on class08/YKW93/ArchitectureStudy/app/src/main/java/com/studyfork/architecturestudy/ui/main/MainActivity.kt
> +                viewModel.getMovieList()
이부분을 vm에서 처리해주면 어떨까요?

2020-02-10 06:34 UTC, YKW93 commented on class08/YKW93/ArchitectureStudy/app/src/main/java/com/studyfork/architecturestudy/ui/main/MainActivity.kt
> +                viewModel.getMovieList()
hideKeyboard() 때문에 activity에서 처리를했는데 viewmodel에서 처리해야될 이유가 있을까요?

2020-02-10 06:40 UTC, Minoyam commented on class08/YKW93/ArchitectureStudy/app/src/main/java/com/studyfork/architecturestudy/ui/main/MainActivity.kt
> +                viewModel.getMovieList()
hideKeyboard를 setObservableCallback에서 처리하게 하고
vm에서 나머지를 처리하면 xml에서 activity를 더이상 사용하지 않고 vm만 쓰기 때문에
코드 정리가 더 잘 되는거 같아서 제기해봤습니다

2020-02-10 08:27 UTC, YKW93 commented on class08/YKW93/ArchitectureStudy/app/src/main/java/com/studyfork/architecturestudy/ui/main/MainActivity.kt
> +                viewModel.getMovieList()
50d08c0 ViewModel에서 처리하도록 변경했습니다!

2020-02-10 08:31 UTC, Minoyam approved these changes

2020-02-10 16:15 UTC, sjjeong requested changes

2020-02-10 16:15 UTC, sjjeong commented on class08/YKW93/ArchitectureStudy/app/src/main/java/com/studyfork/architecturestudy/base/BaseActivity.kt
> +    abstract fun getViewModelInstance(): VM
```kotlin
abstract val viewModel: VM
```
 정도면 될 것 같습니다.

2020-02-10 16:15 UTC, sjjeong commented on class08/YKW93/ArchitectureStudy/app/src/main/java/com/studyfork/architecturestudy/ui/main/MainViewModel.kt
> +    var hidesKeyboard: ObservableBoolean = ObservableBoolean()
val로 선언해주세요

2020-02-10 16:15 UTC, sjjeong commented on class08/YKW93/ArchitectureStudy/app/src/main/java/com/studyfork/architecturestudy/ui/main/MainViewModel.kt
> +    }
이렇게 처리하는 것보단 btn_search를 눌렀을 때 호출하는 함수, edit_movie_search를 눌렀을 때 호출하는 함수를 각각 만들어서 호출해주는게 좋습니다.

2020-02-10 16:16 UTC, sjjeong commented on class08/YKW93/ArchitectureStudy/app/src/main/java/com/studyfork/architecturestudy/ui/main/MainViewModel.kt
> +    }
또한 method reference 때문에 View를 파라미터로 전달 받았는데 lambda로 처리하면 View를 받지 않아도 됩니다.

2020-02-12 03:34 UTC, YKW93 commented on class08/YKW93/ArchitectureStudy/app/src/main/java/com/studyfork/architecturestudy/ui/main/MainViewModel.kt
> +    var hidesKeyboard: ObservableBoolean = ObservableBoolean()
236e66d 변경 했습니다.

2020-02-12 03:34 UTC, YKW93 commented on class08/YKW93/ArchitectureStudy/app/src/main/java/com/studyfork/architecturestudy/base/BaseActivity.kt
> +    abstract fun getViewModelInstance(): VM
bd1786f 수정 했습니다.

2020-02-12 03:34 UTC, YKW93 commented on class08/YKW93/ArchitectureStudy/app/src/main/java/com/studyfork/architecturestudy/ui/main/MainViewModel.kt
> +    }
d7e1f12 변경했습니다.

2020-02-13 11:50 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-02-13 20:05 UTC, merged