HW-5 MVVM 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #475
Opened 2020-02-14 14:59 UTC by L91519

2020-02-15 13:45 UTC, slflfl12 commented on class08/L91519/My Application/app/src/main/java/com/example/myapplication/DataBindingAdapter.kt
> +fun View.setMovieItemClickListener(link: String?) {
이거는 아직 구현 안하신건가요??

2020-02-15 13:45 UTC, slflfl12 commented on class08/L91519/My Application/app/src/main/java/com/example/myapplication/ui/MainViewModel.kt
> +                        naverRepository.saveCache(
DB처리는 repository에서 해줘야 하기 때문에 여기서 saveCache()를 부르는것이 아니라
findMovie()를 구현하기 전에 repository에서 saveCache()를 처리하는 것이 맞지 않을까요?

2020-02-15 13:45 UTC, slflfl12 commented on class08/L91519/My Application/app/src/main/java/com/example/myapplication/ui/MainViewModel.kt
> +            query.set(it.query)
query는 왜 다시 set 해주는 건가요???

2020-02-16 08:38 UTC, L91519 commented on class08/L91519/My Application/app/src/main/java/com/example/myapplication/ui/MainViewModel.kt
> +            query.set(it.query)
데이터 베이스에 저장하는게 검색어 + 영화 리스트이고 저렇게 하면 edit text에 어떤 검색어를 입력했나도 볼 수 있을 것 같아서 다시 set해줬습니다

2020-02-16 08:44 UTC, L91519 commented on class08/L91519/My Application/app/src/main/java/com/example/myapplication/ui/MainViewModel.kt
> +                        naverRepository.saveCache(
제가 잘 이해를 못 한 것 같은데 우선 저는 Repository에서 따로 save Cache라는 함수를 구현해 두었고 view model에서 최근 영화 가져오기, 검색한 영화 가져오기, 검색한 영화 저장하기 이렇게 세가지 동작을 구현해 두었습니다. 여기서 영화 저장하기 부분을 다른 곳에서 처리하면 되는 건가요?

2020-02-16 12:14 UTC, L91519 commented on class08/L91519/My Application/app/src/main/java/com/example/myapplication/ui/MainViewModel.kt
> +                        naverRepository.saveCache(
0da944012075ae405fb644890b9104b2033fc350

2020-02-16 12:14 UTC, L91519 commented on class08/L91519/My Application/app/src/main/java/com/example/myapplication/DataBindingAdapter.kt
> +fun View.setMovieItemClickListener(link: String?) {
c94b63d384d10770083b8898d3ea5acd77b3af16
구현했습니다!

2020-02-16 13:01 UTC, seosh817 approved these changes
수고하셨습니다~

2020-02-16 13:06 UTC, slflfl12 commented on class08/L91519/My Application/app/src/main/java/com/example/myapplication/ui/MainViewModel.kt
> +                        naverRepository.saveCache(
viewmodel의 findMovie()에서 부르는 것이 아니라 repository의 findMove()에서 처리하면 되는것으로 알고있어요. 정확한건 아니라서 일단 approve 하겠습니다!

2020-02-18 14:44 UTC, sjjeong requested changes

2020-02-18 14:44 UTC, sjjeong commented on class08/L91519/My Application/app/build.gradle
> +    kapt "android.arch.persistence.room:compiler:2.2.2  "
https://mvnrepository.com/artifact/androidx.room/room-runtime

androidx용으로 사용해야 합니다.

2020-02-18 14:44 UTC, sjjeong commented on class08/L91519/My Application/app/src/main/java/com/example/myapplication/ui/MainViewModel.kt
> +                        saveCache(it)
save해주는 로직은 naverRepository에서 getResultData() 내부에서 처리해주면 됩니다.
ViewModel은 데이터를 받아서 ObservableField에 set 해주는 역할만 해주면 됩니다.

2020-02-19 03:02 UTC, L91519 commented on class08/L91519/My Application/app/src/main/java/com/example/myapplication/ui/MainViewModel.kt
> +                        saveCache(it)
save는 데이터를 똑바로 받았을 경우에만 해주고 있는데 naverRepository에서의 getResultData()에서는 데이터를 잘 받았나 안 받았나에 대한 판단을 어떤 식으로 해야하는지 잘 모르겠습니다.

그래서 viewmodel에서 success일 경우에 저장하는 형식으로 했었는데 어떻게 repository에서 success를 구분하나요?

2020-02-19 03:22 UTC, L91519 commented on class08/L91519/My Application/app/build.gradle
> +    kapt "android.arch.persistence.room:compiler:2.2.2  "
5c0cd71962f162bc88cd25e7d1abfe1770c1958a

2020-02-19 15:03 UTC, sjjeong commented on class08/L91519/My Application/app/src/main/java/com/example/myapplication/ui/MainViewModel.kt
> +                        saveCache(it)
네 success처리는 RemoteDataSource에서 해주는게 맞을 수도 있습니다.
Repository는 결과데이터를 받아서 어떻게 처리할지를 하는 부분이기 때문에 데이터를 정상적으로 가져오면 Local에 저장하고 나를 호출한 ViewModel쪽에 데이터를 전달해주는 작업을 해주면 됩니다.

2020-02-20 07:07 UTC, L91519 commented on class08/L91519/My Application/app/src/main/java/com/example/myapplication/ui/MainViewModel.kt
> +                        saveCache(it)
59798462c368a19c2902af3d011f6222ff7eb89b

2020-02-20 11:20 UTC, sjjeong requested changes

2020-02-20 11:20 UTC, sjjeong commented on class08/L91519/My Application/app/src/main/java/com/example/myapplication/data/repository/NaverRepositoryImpl.kt
> +        }, fail = {})
이러면 성공과 실패를 ViewModel로 전달을 못하지 않나요?

2020-02-20 12:09 UTC, L91519 commented on class08/L91519/My Application/app/src/main/java/com/example/myapplication/data/repository/NaverRepositoryImpl.kt
> +        }, fail = {})
애뮬레이터에서 동작 되는 것 처럼 보였는데 제가 빌드를 안 하고 돌려봤었던 것 같습니다. 수정했습니다

b2a75507292d8ca74e5f0309c6fbb38be8a5239f

2020-02-21 10:54 UTC, sjjeong requested changes

2020-02-21 10:54 UTC, sjjeong commented on class08/L91519/My Application/app/src/main/java/com/example/myapplication/data/source/NaverRemoteDataSourceImpl.kt
> +                    )
이렇게 되면 RemoteDataSource와 Repository 결합도가 상호 참조하게 됩니다.
Repository는 Remote를 알지만 Remote는 Repository에 대해 모르게 해주세요

2020-02-21 13:59 UTC, L91519 commented on class08/L91519/My Application/app/src/main/java/com/example/myapplication/data/source/NaverRemoteDataSourceImpl.kt
> +                    )
077ed89c3b995b165136296490943969a1b969e8

2020-02-21 13:59 UTC, L91519 commented on class08/L91519/My Application/app/src/main/java/com/example/myapplication/data/source/NaverRemoteDataSourceImpl.kt
> +                    )
RemoteDataSource에서 바로 LocalDataSource.SaveCache를 호출하는 형식으로 수정했습니다.

2020-02-21 16:20 UTC, sjjeong commented on class08/L91519/My Application/app/src/main/java/com/example/myapplication/data/source/NaverRemoteDataSourceImpl.kt
> +                    )
Remote와 Local은 서로 연관관계를 몰라야 합니다.
데이터 방향은 Remote -> Repository 로 가야 하고 Repository는 Local에 데이터를 저장하면서 ViewModel에 데이터를 전달 해야 합니다

2020-02-22 12:39 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-02-22 12:40 UTC, merged