HW-5 MVVM적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #476
Opened 2020-02-15 06:34 UTC by devLibCH

2020-02-16 03:19 UTC, HudsonPark commented on class08/devLibCH/Study/app/src/main/java/app/ch/study/data/common/ExtraHelper.kt
> +const val KEY_QUERY_EMPTY = "query_empty"
@devLibCH 이 변수가 하는 역할은 어떤건가요?

2020-02-16 03:19 UTC, HudsonPark commented on class08/devLibCH/Study/app/src/main/java/app/ch/study/ui/main/viewmodel/MainViewModel.kt
>              return
@devLibCH showError.set()으로 위의 const val KEY_QUERY_EMPTY의 값을 변경하는 건가요?

2020-02-16 03:19 UTC, HudsonPark commented on class08/devLibCH/Study/app/src/main/java/app/ch/study/ui/main/viewmodel/MainViewModel.kt
> +                showLoading.set(false)
@devLibCH doOnComplete {} 블럭 내 코드는 searchMovie() 코드 후 실행되도록 하는 Rx 함수인가요?

2020-02-16 03:19 UTC, HudsonPark commented on class08/devLibCH/Study/app/src/main/java/app/ch/study/util/ErrorManager.kt
> +        val code = e.code()
@devLibCH  HttpException이 보통 어떤 경우에 일어나는지 알 수 있을까요?

2020-02-16 08:58 UTC, devLibCH commented on class08/devLibCH/Study/app/src/main/java/app/ch/study/data/common/ExtraHelper.kt
> +const val KEY_QUERY_EMPTY = "query_empty"
error handler 에서 key값으로 사용합니다.

2020-02-16 08:59 UTC, devLibCH commented on class08/devLibCH/Study/app/src/main/java/app/ch/study/ui/main/viewmodel/MainViewModel.kt
>              return
값을 변경하는건 아니고 ObservableField에 key를 넘겨줍니다.

2020-02-16 08:59 UTC, devLibCH commented on class08/devLibCH/Study/app/src/main/java/app/ch/study/ui/main/viewmodel/MainViewModel.kt
> +                showLoading.set(false)
네 맞습니다.

2020-02-16 09:01 UTC, devLibCH commented on class08/devLibCH/Study/app/src/main/java/app/ch/study/util/ErrorManager.kt
> +        val code = e.code()
보통은 서버에서 Exception을 줘야 발생하지만 오류 예방차원에서 넣어 놓았습니다.

2020-02-20 10:34 UTC, HudsonPark commented on class08/devLibCH/Study/app/src/main/java/app/ch/study/util/ErrorManager.kt
> +        val code = e.code()
@devLibCH 백엔드 개발하시는 분들이 처리해서 Exception을 전달 받는 구조인건가요?

2020-02-20 10:52 UTC, HudsonPark approved these changes

2020-02-20 11:28 UTC, sjjeong requested changes

2020-02-20 11:28 UTC, sjjeong commented on class08/devLibCH/Study/app/src/main/java/app/ch/study/core/BaseViewModel.kt
> +    fun Disposable.addToDisposable(): Disposable
이건 protected 면 좋겠네요

2020-02-20 11:28 UTC, sjjeong commented on class08/devLibCH/Study/app/build.gradle
> +apply plugin: 'kotlin-android-extensions'
이거는 왜 다시 추가 됐나요?

2020-02-20 14:01 UTC, devLibCH commented on class08/devLibCH/Study/app/build.gradle
> +apply plugin: 'kotlin-android-extensions'
이유는 없습니다 생각없이 추가해놨었네요 ㅎㅎ

2020-02-20 14:01 UTC, devLibCH commented on class08/devLibCH/Study/app/build.gradle
> +apply plugin: 'kotlin-android-extensions'
2a94bdf

2020-02-20 14:01 UTC, devLibCH commented on class08/devLibCH/Study/app/src/main/java/app/ch/study/core/BaseViewModel.kt
> +    fun Disposable.addToDisposable(): Disposable
4ffb99d

2020-02-21 13:15 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-02-21 14:53 UTC, merged