HW-6 AAC ViewModel / LiveData
sjjeong/GoogryAndroidArchitecutreStudy pull request #487
Opened 2020-02-18 12:31 UTC by L91519

2020-02-20 10:30 UTC, seosh817 approved these changes
잘하신거 같아요. 수고하셨습니다!

2020-02-21 13:17 UTC, sjjeong requested changes
@L91519 
L91519:class08/L91519로 rebase 하시고 force push 해주시고 알려주세요

2020-02-21 14:36 UTC, L91519 commented
rebase 후 push  했습니다

2020-02-21 16:21 UTC, sjjeong commented
이 pr은 https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/475 가 머지되면 다시 리뷰 하겠습니다.

2020-02-22 12:40 UTC, sjjeong requested changes
rebase다시 해주시고 포스푸시 해주세요

2020-02-22 12:44 UTC, L91519 commented
rebase 후 push 했습니다

2020-02-22 13:19 UTC, sjjeong requested changes

2020-02-22 13:19 UTC, sjjeong commented on class08/L91519/My Application/app/src/main/java/com/example/myapplication/ui/MainViewModel.kt
> +    }
이미 repository에서 해주고 있기 때문에 이 함수는 불필요해보이네요

2020-02-22 13:52 UTC, L91519 commented on class08/L91519/My Application/app/src/main/java/com/example/myapplication/ui/MainViewModel.kt
> +    }
1a56c80d05c2487a4816a9426c583bf1c8e2b98c 
수정했습니다!

2020-02-24 04:30 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-02-24 07:35 UTC, merged