HW-5 DataBinding 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #489
Opened 2020-02-19 05:35 UTC by doubleclutch30

2020-02-19 13:55 UTC, JayYi requested changes

2020-02-19 13:55 UTC, JayYi commented on doubleclutch30/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/data/repository/NaverSearchRepositoryImpl.kt
> +                return@flatMap Single.just(it)
subcribe는 task job 끝난 후에 처리 해야 될 일이 있을 때 호출해야 합니다. flatmap 내에서 호출하는 것은 적절해보이지 않아요.
delete 하거나 save 하다가 발생하는 error는 catch할 수 있는 구조가 아니예요. 그리고 repository에서는 subscribe가 필요 없어 보입니다.

2020-02-19 13:55 UTC, JayYi commented on doubleclutch30/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ext/ImageViewExt.kt
> +fun ImageView?.setUrl(url: String?) {
ImageView를 nullable 한 이유는 뭔가요?

2020-02-19 13:55 UTC, JayYi commented on doubleclutch30/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ext/ImageViewExt.kt
> +            .load(url)
url이 null 인 경우에 에러가 발생할 것으로 보입니다.

2020-02-19 13:55 UTC, JayYi commented on doubleclutch30/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/kin/KinPresenter.kt
> +        if(repository != null) {
```kotlin
repository?.let {
   // do something
}
```
kotlin 내  let을 사용하면  null check 하지 않아도 됩니다.

2020-02-19 13:55 UTC, JayYi commented on doubleclutch30/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/blog/BlogPresenter.kt
>      private val repository: NaverSearchRepository?
repository가 nullable 한 이유가 있을까요? 코드 보면 Database 사용을 위해서 context를 넘기게 되어 있는데 DB의 경우 application context를 사용하시면 될 것 같아요.

2020-02-19 13:55 UTC, JayYi commented on doubleclutch30/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/blog/BlogFragment.kt
>                  presenter.taskSearch(
input_text랑 edit_text는 kotlin extenstion을 유지 하고 있는 이유가 있을까요?
그리고 onClick 동작은 xml에서 처리 할 수 있습니다.

2020-02-23 04:40 UTC, jjunji commented on doubleclutch30/ArchitectureStudy/app/build.gradle
> +    dataBinding {
dataBinding 을 사용한다면 Kotlin Android Extensions 은 제거하시는게 좋을 것 같습니다.

2020-02-23 04:40 UTC, jjunji commented on doubleclutch30/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/kin/KinFragment.kt
> +        binding.btnSearch.setOnClickListener {
xml 에서 onClick  처리가 가능합니다. 여러 방법이 있겠지만 저는
xml data tag 에 presenter 선언 후
onClick 속성에 presenter.메소드( ) 로 구현했습니다.

2020-02-24 15:29 UTC, doubleclutch30 commented on doubleclutch30/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/data/repository/NaverSearchRepositoryImpl.kt
> +                return@flatMap Single.just(it)
말씀해주신대로 success error 작업은 repository보다는 presenter에서 하는게 적절한거 같네요.  수정했습니다.

2020-02-24 15:45 UTC, doubleclutch30 commented on doubleclutch30/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ext/ImageViewExt.kt
> +            .error(R.drawable.ic_launcher_background)
url 이 null 인 경우 기본이미지를 보여주게 되어있습니다.

2020-02-24 15:47 UTC, doubleclutch30 commented on doubleclutch30/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ext/ImageViewExt.kt
> +            .load(url)
url 이 null 인 경우 기본이미지를 보여주도록 했습니다.

2020-02-24 16:00 UTC, suhyeong-seo commented on doubleclutch30/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ext/ImageViewExt.kt
> +fun ImageView?.setUrl(url: String?) {
url 주소값이 null 일 경우 imageview도 null 할 수도 있을 거 같아서 nullable로  해주었습니다.

2020-02-24 16:12 UTC, doubleclutch30 commented on doubleclutch30/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/kin/KinPresenter.kt
> +        if(repository != null) {
let을 사용하니 코드가 더 간결해지네요!

2020-03-07 07:58 UTC, doubleclutch30 commented on doubleclutch30/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/blog/BlogPresenter.kt
>      private val repository: NaverSearchRepository?
아까 설명해주신것처럼 context 를 들고 있는 것은 좋지 않는 것 같습니다. 
다음과제에 application 을 적용해서 수정하겠습니다!

2020-03-07 08:00 UTC, doubleclutch30 commented on doubleclutch30/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/blog/BlogFragment.kt
>                  presenter.taskSearch(
xml 에서 onClick 동작하도록 수정했습니다

2020-03-07 08:00 UTC, doubleclutch30 commented on doubleclutch30/ArchitectureStudy/app/build.gradle
> +    dataBinding {
넵 수정했습니다.

2020-03-07 08:00 UTC, doubleclutch30 commented on doubleclutch30/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/kin/KinFragment.kt
> +        binding.btnSearch.setOnClickListener {
xml 에서 onClick 동작하도록 수정했습니다

2020-03-09 01:19 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-03-09 01:19 UTC, sjjeong commented on doubleclutch30/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ext/ImageViewExt.kt
> +fun ImageView?.setUrl(url: String?) {
@JayYi 데이터바인딩할때 파라미터는 nullable해야 합니다.

2020-03-09 09:14 UTC, jjunji approved these changes
수고하셨습니다~

2020-03-09 11:15 UTC, doubleclutch30 commented on doubleclutch30/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/data/repository/NaverSearchRepositoryImpl.kt
> +                return@flatMap Single.just(it)
말씀해주신대로 success error 작업은 repository보다는 presenter에서 하는게 적절한거 같네요.  수정했습니다.

6423b1e

2020-03-09 11:19 UTC, suhyeong-seo reviewed
--

2020-03-09 12:42 UTC, JayYi commented
수고하셨습니다

2020-03-09 12:45 UTC, JayYi approved these changes
수고하셨습니다

2020-03-09 12:48 UTC, merged