HW-8 multi module 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #490
Opened 2020-02-19 07:03 UTC by AhnHyeonho

* multi module 적용
* gradle 수정
* MainViewModelFactory 삭제

2020-02-27 12:17 UTC, sjjeong requested changes
에러가 발생하는데 수정하고 알려주세요

2020-02-28 14:41 UTC, seunghee63 approved these changes

2020-03-01 05:39 UTC, AhnHyeonho commented
혹시 unresolved reference 에러가 난다면 client_id, client_secret 이 들어가있는 clientInfos.xml 파일이  gitignore에 추가되어있어서 그런 것 같습니다. 

clientInfos.xml 추가해서 다시 올렸습니다.

2020-03-02 03:42 UTC, sjjeong requested changes
NaverRemoteDataSourceImpl와 같이 Impl 클래스는 외부에서 접근 할 수 없게 internal class로 해주세요

2020-03-02 03:42 UTC, sjjeong commented on AhnHyeonho/FirstProject/remote/src/main/res/values/clientinfos.xml
> +<?xml version="1.0" encoding="utf-8"?>
xml 파일명은 camelCase가 아니라 snake_case로 해야 합니다

2020-03-02 03:42 UTC, sjjeong commented on AhnHyeonho/FirstProject/remote/src/main/java/com/hansung/remote/data/ErrorStringResource.kt
>  package com.hansung.firstproject.data
패키지가 com.hansung.firstproject.data가 아니라 com.hansung.remote.data 여야 합니다.
다른 부분도 동일하게 변경해주세요

2020-03-02 03:42 UTC, sjjeong commented on AhnHyeonho/FirstProject/repository/src/main/java/com/hansung/repository/NaverRepository.kt
>  class NaverRepository(
이 클래스도 interface를 만들고 Impl 형태로 가고 주입 할 땐 interface 형태로 주입시켜주세요

2020-03-04 06:04 UTC, AhnHyeonho commented on AhnHyeonho/FirstProject/remote/src/main/res/values/clientinfos.xml
> +<?xml version="1.0" encoding="utf-8"?>
수정했습니다!


d765f11

2020-03-04 06:04 UTC, AhnHyeonho commented on AhnHyeonho/FirstProject/remote/src/main/java/com/hansung/remote/data/ErrorStringResource.kt
>  package com.hansung.firstproject.data
수정했습니다!


7bc350e

2020-03-04 06:05 UTC, AhnHyeonho commented on AhnHyeonho/FirstProject/repository/src/main/java/com/hansung/repository/NaverRepository.kt
>  class NaverRepository(
수정했습니다!


ed47ccf

239baad

2020-03-04 10:51 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋
고생 많았어요~

2020-03-04 14:42 UTC, AhnHyeonho commented
8주간 유익한 내용 알차게 배워갑니다!
감사합니다 :)

2020-03-04 14:43 UTC, merged