HW-8 Multi Module 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #494
Opened 2020-02-19 16:33 UTC by handnew04

중간에 커밋이 너무 큰 덩어리가 올라가게 되었습니다. 죄송합니다! ㅜㅜ

2020-02-21 06:56 UTC, ghkdua1829 approved these changes
고생하셨어요~~

2020-02-22 13:17 UTC, sjjeong requested changes
Repository, Remote, Local과 같이 외부에서 알 필요가 없을 것 같은 클래스는 internal로 만들어주세요 
그 외에 다른 것도 고민해보시고 같이 interna로 처리해주세요

2020-02-22 13:17 UTC, sjjeong commented on handnew04/model/src/main/java/com/example/model/data/MovieRepository.kt
>  class MovieRepository(
MovieRepository도 DataSource들 처럼 interface와 그것을 impl한 형태로 만들어주세요

2020-02-25 14:08 UTC, handnew04 commented on handnew04/model/src/main/java/com/example/model/data/MovieRepository.kt
>  class MovieRepository(
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/494/commits/96fc0ce37740b8474ce55f63688f0f67c7fd6da0

2020-02-27 11:40 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋
지금까지 고생많으셨어요~

2020-02-28 13:01 UTC, merged