HW-1 NaverMovie Sample
sjjeong/GoogryAndroidArchitecutreStudy pull request #507
Opened 2020-03-01 12:27 UTC by sooakim

2020-03-02 10:59 UTC, mtjin commented
제가 봤을때는 수정해야 할 사항이 보이지 않는 것 같습니다.

2020-03-02 11:35 UTC, sjjeong commented
@mtjin 
comment말고 approve로 해주세요~

2020-03-02 12:20 UTC, mtjin approved these changes
approve 했습니다.

2020-03-03 16:59 UTC, sjjeong requested changes
m prefix 컨벤션이 보이는데 이것은 자바스타일 입니다. 코틀린에서는 m prefix를 붙이지 않아요.

코드를 잘 짜셔서 제가 보면서 도움이 되는 부분도 있었어요
특히 Adapter에서 LayoutInflater를 한번만 만들고 재사용 하는 것은 생각하지도 못했던 코드네요👍👍

2020-03-03 16:59 UTC, sjjeong commented on 2003/sooakim/app/src/main/res/layout/activity_main.xml
> +        app:layout_constraintGuide_end="8dp" />
ConstraintLayout에 padding을 주고 이 Guideline에 제약이 걸린 View들은 parent로 하면 동일하다고 생각합니다.
이렇게 Guideline을 상하좌우에 다 주는 이유가 있을까요?

2020-03-03 16:59 UTC, sjjeong commented on 2003/sooakim/app/src/main/java/io/github/sooakim/ui/SAMainSearchResultAdapter.kt
> +    }
interface 대신 kotlin higher-order function을 이용해보세요

2020-03-03 16:59 UTC, sjjeong commented on 2003/sooakim/app/src/main/java/io/github/sooakim/ui/SAMainSearchResultAdapter.kt
> +        holder.tvActor.text = currentItem.actor
이 로직을 SAItemViewHolder에 함수를 하나 만들어서 그 안에서 처리하도록 해주세요.
그러면 view들을 private으로 관리 할 수 있어요

2020-03-03 16:59 UTC, sjjeong commented on 2003/sooakim/app/src/main/java/io/github/sooakim/ui/SAMainSearchResultAdapter.kt
> +class SAMainSearchResultAdapter :
onViewRecycled를 override해서 Glide 로딩을 clear하는 로직도 추가해주세요

2020-03-03 16:59 UTC, sjjeong commented on 2003/sooakim/app/src/main/java/io/github/sooakim/ui/SAMainActivity.kt
> +            .doOnNext { _ -> updateLoading(true) }
_ -> 는 생략이 가능해요

2020-03-03 16:59 UTC, sjjeong commented on 2003/sooakim/app/src/main/java/io/github/sooakim/ui/SAMainActivity.kt
> +    private fun updateLoading(isLoading: Boolean) {
updateLoading으로 boolean을 받아 visible invisible 하는 것보다
showLoading, hideLoading처럼 명확한 함수명으로 만들어주는게 좋아요

2020-03-03 16:59 UTC, sjjeong commented on 2003/sooakim/app/src/main/java/io/github/sooakim/ui/SAMainActivity.kt
> +            .doOnNext(mSearchResultAdapter::submitList)
adapter::submitList하는 것을 doOnNext가 아니라 subscribe에서 해야 합니다.

2020-03-03 16:59 UTC, sjjeong commented on 2003/sooakim/app/src/main/java/io/github/sooakim/ui/SAMainActivity.kt
> +            .doOnNext { _ -> updateLoading(false) }
error 케이스에도 loading이 hide 되어야 하기 때문에 doAfterTerminate로 변경해주세요

2020-03-03 16:59 UTC, sjjeong commented on 2003/sooakim/app/src/main/java/io/github/sooakim/ui/SAMainActivity.kt
> +            .let(mCompositeDisposable::add)
let()도 좋지만 rxKotlin을 사용하면 addTo 함수로 처리 할 수 있어요

2020-03-03 22:15 UTC, sooakim commented on 2003/sooakim/app/src/main/java/io/github/sooakim/ui/SAMainActivity.kt
> +            .doOnNext { _ -> updateLoading(false) }
@sjjeong onErrorReturn에서 error 케이스시 대체값을 반환하기 때문에 onNext만으로 커버가되지 않나요?

2020-03-03 22:17 UTC, sooakim commented on 2003/sooakim/app/src/main/java/io/github/sooakim/ui/SAMainActivity.kt
> +            .doOnNext(mSearchResultAdapter::submitList)
@sjjeong 마찬가지로 onErrorReturn에서 error 케이스시 대체값을 반환하고 있어서 따로 에러 처리가 필요 없을 것 같아 onNext로 했는데 이유가 있을까요?

2020-03-03 22:19 UTC, sooakim commented on 2003/sooakim/app/src/main/res/layout/activity_main.xml
> +        app:layout_constraintGuide_end="8dp" />
@sjjeong 회사에서 습관적으로 작성하던 코드라 넣었는데 그러고보니 padding으로도 가능하겠네요.

2020-03-04 01:12 UTC, sjjeong commented on 2003/sooakim/app/src/main/java/io/github/sooakim/ui/SAMainActivity.kt
> +            .doOnNext(mSearchResultAdapter::submitList)
Rx에서 데이터를 생성하는 쪽과 소비하는 쪽 개념으로 봤을 때 최종 결과는 subscribe에서 처리해줘야 합니다.
doOnNext는 단지 데이터가 전달 될 때 어떻게 할지 interceptor하는 느낌이라고 알고 있습니다

2020-03-04 01:13 UTC, sjjeong commented on 2003/sooakim/app/src/main/java/io/github/sooakim/ui/SAMainActivity.kt
> +            .doOnNext { _ -> updateLoading(false) }
아! onErrorReturn을 깜빡했네요 ㅋㅋ

2020-03-04 02:49 UTC, sooakim commented on 2003/sooakim/app/src/main/java/io/github/sooakim/ui/SAMainActivity.kt
> +            .let(mCompositeDisposable::add)
00b0370
d689b77

2020-03-04 02:52 UTC, sooakim commented on 2003/sooakim/app/src/main/java/io/github/sooakim/ui/SAMainActivity.kt
> +            .doOnNext(mSearchResultAdapter::submitList)
39a34b4

2020-03-04 03:31 UTC, sooakim commented on 2003/sooakim/app/src/main/java/io/github/sooakim/ui/SAMainActivity.kt
> +    private fun updateLoading(isLoading: Boolean) {
a1f7181

2020-03-04 03:32 UTC, sooakim commented on 2003/sooakim/app/src/main/java/io/github/sooakim/ui/SAMainActivity.kt
> +            .doOnNext { _ -> updateLoading(true) }
3d02e42

2020-03-04 03:32 UTC, sooakim commented on 2003/sooakim/app/src/main/java/io/github/sooakim/ui/SAMainSearchResultAdapter.kt
> +class SAMainSearchResultAdapter :
37f7930

2020-03-04 03:32 UTC, sooakim commented on 2003/sooakim/app/src/main/java/io/github/sooakim/ui/SAMainSearchResultAdapter.kt
> +        holder.tvActor.text = currentItem.actor
e0c8195

2020-03-04 03:33 UTC, sooakim commented on 2003/sooakim/app/src/main/java/io/github/sooakim/ui/SAMainSearchResultAdapter.kt
> +    }
e0c8195

2020-03-04 03:33 UTC, sooakim commented on 2003/sooakim/app/src/main/res/layout/activity_main.xml
> +        app:layout_constraintGuide_end="8dp" />
dcd9f38
dd13bdd

2020-03-04 11:08 UTC, sjjeong requested changes

2020-03-04 11:08 UTC, sjjeong commented on 2003/sooakim/app/src/main/java/io/github/sooakim/ui/base/SARecyclerViewAdapter.kt
> +                }
https://developer.android.com/kotlin/style-guide#braces
brace쪽을 보시면 이런 형태 일 때  { } 를 추가 해 줘야 합니다.

2020-03-04 11:11 UTC, sooakim commented on 2003/sooakim/app/src/main/java/io/github/sooakim/ui/base/SARecyclerViewAdapter.kt
> +                }
3acc9ca

2020-03-04 11:12 UTC, sooakim commented on 2003/sooakim/app/src/main/java/io/github/sooakim/ui/base/SARecyclerViewAdapter.kt
> +                }
@sjjeong 수정했어요~

2020-03-04 11:12 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-03-04 11:17 UTC, merged