HW-7 코인 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #509
Opened 2020-03-02 05:56 UTC by YKW93

2020-03-05 08:19 UTC, Minoyam approved these changes

2020-03-05 10:59 UTC, sjjeong requested changes

2020-03-05 10:59 UTC, sjjeong commented on class08/YKW93/ArchitectureStudy/app/src/main/java/com/studyfork/architecturestudy/di/UtilModule.kt
> +        ResourceProvider(BaseApplication.applicationContext())
koin에서 Application가져오는 함수가 있습니다.

2020-03-06 08:28 UTC, YKW93 commented on class08/YKW93/ArchitectureStudy/app/src/main/java/com/studyfork/architecturestudy/di/UtilModule.kt
> +        ResourceProvider(BaseApplication.applicationContext())
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/509/commits/3275999c763158f0906e022a9a31835f429634cc
수정 완료 했습니다!

2020-03-06 12:20 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-03-07 05:42 UTC, merged