HW-1 네이버 영화 검색 앱
sjjeong/GoogryAndroidArchitecutreStudy pull request #510
Opened 2020-03-02 13:09 UTC by mtjin

HW-1 네이버 검색 영화앱

2020-03-02 13:16 UTC, sooakim commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/api/ApiClient.kt
> +    companion object {
object하나로도 가능한데 굳이 companion object로 중첩사용할 필요 없을 것 같아요.

2020-03-02 13:19 UTC, sooakim commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/data/Movie.kt
> +    @Expose
Gson에 excludeFieldsWithoutExposeAnnotation()옵션을 주지 않았기때문에 Expose어노테이션을 굳이 달 필요 없을 것 같아요.

2020-03-02 13:22 UTC, sooakim commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/MainActivity.kt
> +                apiInterface.getSearchMovie(
rx이벤트를 dispose해주는 코드가 없네요. 메모리릭의 위험성이 있어보여요. 
예) api요청중 activity가 destroy되도 요청이 cancel되지 않아요.

2020-03-02 13:23 UTC, sooakim commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/MainActivity.kt
> +        startActivity(intent)
Intent.ACTION_VIEW 액션을 받는 액티비티가 없으면 예외가 발생할 수 있어요.

2020-03-02 13:23 UTC, sooakim commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/MainActivity.kt
> +    fun onToastMessage(message: String?) {
굳이 파라미터가 Nullable하지 않아도 될 것 같아요.

2020-03-02 13:25 UTC, sooakim commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/MovieAdapter.kt
> +        private var ivPoster: ImageView? = null
1. 파라미터를 Nullable로 할 필요가 없어보여요.
2. init블록 안에서 초기화 하지 않고 바로 초기화해도 동일하게 동작해요.

2020-03-02 13:26 UTC, sooakim commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/MovieAdapter.kt
> +                rvRating?.rating = userRating.toFloat() / 2
만약 String이 Float형식이 아니면 예외가 발생할 수 있어요.

2020-03-02 13:27 UTC, sooakim commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/MovieAdapter.kt
> +                itemView.setOnClickListener {
setOnClickListener를 viewholder가 bind될 때마다 해줄 필요는 없을 것 같아요.

2020-03-03 08:07 UTC, sooakim requested changes

2020-03-03 08:07 UTC, sooakim commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/api/ApiClient.kt
> +    companion object {
object하나로도 가능한데 굳이 companion object로 중첩사용할 필요 없을 것 같아요.

2020-03-03 08:07 UTC, sooakim commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/data/Movie.kt
> +)
Gson에 excludeFieldsWithoutExposeAnnotation()옵션을 주지 않았기때문에 Expose어노테이션을 굳이 달 필요 없을 것 같아요.

2020-03-03 08:07 UTC, sooakim commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/data/MovieResponse.kt
> +)
Gson에 excludeFieldsWithoutExposeAnnotation()옵션을 주지 않았기때문에 Expose어노테이션을 굳이 달 필요 없을 것 같아요.

2020-03-03 08:07 UTC, sooakim commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/MainActivity.kt
> +                    })
rx이벤트를 dispose해주는 코드가 없네요. 메모리릭의 위험성이 있어보여요.
예) api요청중 activity가 destroy되도 요청이 cancel되지 않아요.

2020-03-03 08:07 UTC, sooakim commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/MainActivity.kt
> +        startActivity(intent)
Intent.ACTION_VIEW 액션을 받는 액티비티가 없으면 예외가 발생할 수 있어요.

2020-03-03 08:07 UTC, sooakim commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/MainActivity.kt
> +    fun onToastMessage(message: String?) {
굳이 파라미터가 Nullable하지 않아도 될 것 같아요.

2020-03-03 08:07 UTC, sooakim commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/MovieAdapter.kt
> +        private var tvDirector: TextView? = null
1. 프로퍼티를 Nullable로 할 필요가 없어보여요.
2. init블록 안에서 초기화 하지 않고 바로 초기화해도 동일하게 동작해요.

2020-03-03 08:07 UTC, sooakim commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/MovieAdapter.kt
> +                rvRating?.rating = userRating.toFloat() / 2
만약 String이 Float형식이 아니면 예외가 발생할 수 있어요.

2020-03-03 08:07 UTC, sooakim commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/MovieAdapter.kt
> +                }
setOnClickListener를 viewholder가 bind될 때마다 해줄 필요는 없을 것 같아요.

2020-03-03 09:35 UTC, mtjin commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/data/MovieResponse.kt
> +)
d78e16fdca133b502f6772ed85fec3895dc89ce7

2020-03-03 09:39 UTC, mtjin commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/api/ApiClient.kt
> +    companion object {
object ApiClient로 수정하였습니다.

2020-03-03 09:39 UTC, mtjin commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/data/Movie.kt
> +)
Expose 어노테이션 제거했습니다

2020-03-03 09:43 UTC, sooakim commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/api/ApiClient.kt
> +    companion object {
@mtjin [스터디장 공간](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/tree/master/sjjeong) "리뷰에 코멘트 마다 나눠서 커밋 하고 코멘트에 커밋id 코멘트로 남기기" 확인해주세요.

2020-03-03 09:44 UTC, mtjin commented
리뷰 후 수정

2020-03-03 10:28 UTC, sooakim requested changes

2020-03-03 10:28 UTC, sooakim commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/MainActivity.kt
> +    }
사용되지 않는 메소드가 추가됐어요.

2020-03-03 10:28 UTC, sooakim commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/MainActivity.kt
> +                })
마찬가지로 call을 cancel해주는 코드가 없어요.

2020-03-03 10:28 UTC, mtjin commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/api/ApiClient.kt
> +    companion object {
[44251a2065d67e7645c7b2505a3aa15a73676c37](url)

2020-03-03 10:38 UTC, mtjin commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/api/ApiClient.kt
> +    companion object {
@sooakim 
링크 추가했습니다.
[304729c](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/510/commits/304729c9eceeb15152605f900bbc40d24048469c)

2020-03-03 10:40 UTC, mtjin commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/data/Movie.kt
> +)
d78e16f

2020-03-03 10:41 UTC, mtjin commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/MainActivity.kt
> +                    })
밑에 답변 확인했습니다.!
64031a3

2020-03-03 10:42 UTC, mtjin commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/MainActivity.kt
> +        startActivity(intent)
7991155

2020-03-03 10:44 UTC, mtjin commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/MainActivity.kt
> +    fun onToastMessage(message: String?) {
04ed9c0
수정했습니다.

2020-03-03 10:44 UTC, mtjin commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/MovieAdapter.kt
> +        private var tvDirector: TextView? = null
99958df
바로 초기화하도록 수정했습니다.

2020-03-03 10:44 UTC, mtjin commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/MovieAdapter.kt
> +                rvRating?.rating = userRating.toFloat() / 2
c0b4c89
예외처리했습니다.

2020-03-03 10:47 UTC, mtjin commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/MainActivity.kt
> +    }
네 제거하겠습니다.

2020-03-03 10:49 UTC, mtjin commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/MovieAdapter.kt
> +                }
99958df
bind 밖으로 빼줬습니다.

2020-03-04 05:19 UTC, sooakim requested changes

2020-03-04 05:19 UTC, sooakim commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/MainActivity.kt
> +                })
cancel해주는 로직 필요

2020-03-04 05:19 UTC, sooakim commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/MovieAdapter.kt
> +        private var tvDirector: TextView? = itemView.findViewById(R.id.tv_director)
1. 변경 가능성이 없는 프로퍼티, var -> val변경 해주세요.
2. Nullable하지 않은 프로퍼티인데 NonNull로 선언되었네요.

2020-03-04 05:19 UTC, sooakim commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/MovieAdapter.kt
> +        this.items = items.toMutableList()
toMutableList() 내부 코드 확인해보세요. 
매번 불필요한 객체를 생성하는건 좋지 않아요.

2020-03-04 05:55 UTC, mtjin commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/MainActivity.kt
> +                })
cancel해주는 로직을 추가했습니다.
644d523
밑 커밋은 위 커밋에서 call.cancel() 코드 위치를 수정했습니다.
459bb9e

2020-03-04 05:55 UTC, mtjin commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/MainActivity.kt
> +                })
cancel해주는 로직을 추가했습니다.
644d523
밑 커밋은 위 커밋에서 call.cancel() 코드 위치를 수정했습니다.
459bb9e

2020-03-04 05:56 UTC, mtjin commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/MovieAdapter.kt
> +        private var tvDirector: TextView? = itemView.findViewById(R.id.tv_director)
수정 했습니다.
844e1d6

d2d2572

2020-03-04 05:56 UTC, mtjin commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/MovieAdapter.kt
> +        this.items = items.toMutableList()
수정했습니다.
c6cdef9

2020-03-04 06:07 UTC, sooakim requested changes

2020-03-04 06:07 UTC, sooakim commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/MainActivity.kt
> +                })
작업이 끝난 후가 아닌 activity가 destory될 때 cancel해주세요.

2020-03-04 06:07 UTC, sooakim commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/MovieAdapter.kt
> +        this.items = items as ArrayList<Movie>
제가 요청한건 "this.items.addAll(items)"였어요. 그러면 18번째줄도 var가 아닌 val로 선언가능해요.

2020-03-04 06:30 UTC, mtjin commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/MovieAdapter.kt
> +        this.items = items as ArrayList<Movie>
수정했습니다.
24796da

f4cd558

2020-03-04 06:30 UTC, mtjin commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/MainActivity.kt
> +                })
전역변수로 빼서 onDestory()시 cancel 해주었습니다.
207092d

2020-03-04 06:32 UTC, sooakim requested changes

2020-03-04 06:32 UTC, sooakim commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/MainActivity.kt
> +        movieCall.cancel()
movieCall이 초기화되지 않았을 경우에 대한 예외처리를 추가해주세요.

2020-03-04 06:40 UTC, sooakim requested changes

2020-03-04 06:40 UTC, sooakim commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/MainActivity.kt
> +        movieCall?.cancel()
[스택오버플로우 답변 참조](https://stackoverflow.com/questions/37618738/how-to-check-if-a-lateinit-variable-has-been-initialized) movieCall이 lateinit var로 선언되어 있어서 ?이 의미가 없어요.

2020-03-04 06:42 UTC, mtjin commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/MainActivity.kt
> +        movieCall?.cancel()
감사합니다. 확인해보겠습니다.

2020-03-04 06:47 UTC, sooakim commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/MainActivity.kt
> +        movieCall?.cancel()
네 이것만 처리되면 approve할게요.

2020-03-04 06:55 UTC, mtjin commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/MainActivity.kt
> +        movieCall?.cancel()
수정했는데 movieCall을 lateinit말고 ?= null 로 해놓는게 더 낫나요?
fb3830f

2020-03-04 06:57 UTC, sooakim commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/MainActivity.kt
> +        movieCall?.cancel()
@mtjin lateinit을 쓸지 Nullable을 쓸지에 대해선 제 생각에는 개인 취향일 것 같아요.

2020-03-04 06:58 UTC, sooakim approved these changes

2020-03-04 07:08 UTC, mtjin commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/MainActivity.kt
> +        movieCall?.cancel()
@sooakim 넵 리뷰 감사합니다~

2020-03-04 11:31 UTC, sjjeong requested changes

2020-03-04 11:31 UTC, sjjeong commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/api/AppInterceptor.kt
> +        }
Builder pattern이기 때문에 run으로 하지 않아도 됩니다.

2020-03-04 11:31 UTC, sjjeong commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/MovieAdapter.kt
> +    }
interface말고 kotlin higher-order function으로 처리해보세요

2020-03-04 11:31 UTC, sjjeong commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/MovieAdapter.kt
> +    }
notify를 함수 내부에서 호출 하도록 해주세요 
아래 clear도 동일하게 해주세요

2020-03-04 11:31 UTC, sjjeong commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/MovieAdapter.kt
> +                Glide.with(itemView).load(image).placeholder(R.drawable.ic_default).into(ivPoster!!)
load부터 개행해서 한 함수당 한 라인씩 나오도록 해주세요

2020-03-04 11:31 UTC, sjjeong commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/MainActivity.kt
> +    fun initView() {
private 추가해주세요

2020-03-04 11:31 UTC, sjjeong commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/MainActivity.kt
> +                        body()?.movies?.let { it -> movieAdapter.setItems(it) }
if에서 body()가 null이 아닌걸 검사했는데 내부에서 ?로 사용하고 있네요
이거는 이렇게 수정하시면 됩니다.
```kotlin
val body = body()
if (isSuccessful && body != null) {
    body.movies.let { movieAdapter.setItems(it) }
    movieAdapter.notifyDataSetChanged()
} else {
    onToastMessage("불러오는데 실패 했습니다.")
}
```

2020-03-04 11:31 UTC, sjjeong commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/MainActivity.kt
> +        if(this::movieCall.isInitialized){
if와 ( 사이에 공백 추가해주세요 
reformat code 하시면 됩니다.

2020-03-04 13:07 UTC, mtjin commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/api/AppInterceptor.kt
> +        }
run코드 제거했습니다.
87f2a2e

2020-03-04 13:08 UTC, mtjin commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/MovieAdapter.kt
> +    }
higher-order function로 처리하였습니다.
15bb680

2020-03-04 13:08 UTC, mtjin commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/MovieAdapter.kt
> +    }
수정했습니다.
f82dc00

2020-03-04 13:09 UTC, mtjin commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/MovieAdapter.kt
> +                Glide.with(itemView).load(image).placeholder(R.drawable.ic_default).into(ivPoster!!)
수정했습니다.
35d017a

2020-03-04 13:09 UTC, mtjin commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/MainActivity.kt
> +    fun initView() {
추가했습니다.

254cb98

2020-03-04 13:10 UTC, mtjin commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/MainActivity.kt
> +                        body()?.movies?.let { it -> movieAdapter.setItems(it) }
수정했습니다.

e0b3a4a

2020-03-04 13:11 UTC, mtjin commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/MainActivity.kt
> +        if(this::movieCall.isInitialized){
레트로핏 onResponse() 쪽 수정할때 같이 수정하여 커밋했습니다.
e0b3a4a

2020-03-04 14:43 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-03-04 15:15 UTC, merged