2003/logout0607
sjjeong/GoogryAndroidArchitecutreStudy pull request #511
Opened 2020-03-03 09:06 UTC by logout0607

HW-1 네이버 영화 검색 API 앱

일단 구현만 했고, 에러는 잡지 않았습니다. ^^;;

2020-03-03 11:35 UTC, sjjeong commented
PR이름을 적절하게 변경해주세요
ex) HW-1 네이버 영화 검색 API 앱

2020-03-03 11:37 UTC, logout0607 commented
네 수정하였습니다.

2020-03-04 12:55 UTC, kangraemin requested changes

2020-03-04 12:55 UTC, kangraemin commented on 2003/logout0607/app/src/main/java/com/kmj/study/MainActivity.kt
> +//                Log.d("dd", response.body().toString())
확인용 로그는 삭제하셔도 될것같아요

2020-03-04 12:55 UTC, kangraemin commented on 2003/logout0607/app/src/main/java/com/kmj/study/MainActivity.kt
> +            }
오류 로그를 남길 수 있도록 printStackTrace를 추가하는게 좋을것 같아요.

2020-03-04 12:55 UTC, kangraemin commented on 2003/logout0607/app/src/main/java/com/kmj/study/MainActivity.kt
> +                    }
성능적으로 큰 차이점이 있는진 모르겠지만 ... 반복문을 돌리지 않고 MovieResponseDto에서 받은 items의 타입이 ArrayList<MovieDto>고, 이는 searchItems의 타입과 같으니 searchItems에 바로 items를 넣는게 어떨까 싶어요

2020-03-04 12:55 UTC, kangraemin commented on 2003/logout0607/app/src/main/java/com/kmj/study/view/adapter/MainRecyclerAdapter.kt
> +                Log.d("BB", item.toString())
확인용 로그는 삭제하셔도 될것같아요

2020-03-04 12:55 UTC, kangraemin commented on 2003/logout0607/app/src/main/res/layout/activity_main.xml
> +            android:text="검색" />
텍스트를 하드코딩하기보단 string.xml에서 관리하는게 좋을것같아요

2020-03-10 14:11 UTC, sjjeong commented
개인사정으로 참여할 수 없으셔서 close합니다.

2020-03-10 14:11 UTC, closed without merging