HW-1 NaverMovieAPI Project
sjjeong/GoogryAndroidArchitecutreStudy pull request #512
Opened 2020-03-03 11:00 UTC by byiryu

2020-03-04 21:56 UTC, tjdwlsl1021 reviewed
소스리뷰입니다.

2020-03-04 21:56 UTC, tjdwlsl1021 commented on 2003/byiryu/app/build.gradle
> +        release {
buildTypes에 release만 있는데 debug용도 세팅하는건 어떨까 싶습니다.
(빌드 속도를 빠르게 한다던가, debug때는 필요없는건 false처리하는 등의 작업)

2020-03-04 21:56 UTC, tjdwlsl1021 commented on 2003/byiryu/app/src/main/java/com/byiryu/study/api/model/MovieItem.kt
> +data class MovieItem(
샘플용 데이터를 주석으로 달아두는걸 보았는데, 이 방법도 괜찮은 것 같다고 느꼈습니다.

   /*
{
            "title": "<b>울</b>언니",
            "link": "https://movie.naver.com/movie/bi/mi/basic.nhn?code=129790",
            "image": "https://ssl.pstatic.net/imgmovie/mdi/mit110/1297/129790_P07_105449.jpg",
            "subtitle": "",
            "pubDate": "2014",
            "director": "이제락|",
            "actor": "오광록|하은|지성원|조상구|",
            "userRating": "3.68"
}
 */

2020-03-04 21:56 UTC, tjdwlsl1021 commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/MainActivity.kt
> +        recyclerView.adapter = adapter
recyclerView.adapter = adapter이 부분은 init으로 따로 구분해서 작업하신 분도 있던데,
꼭 구분할 필요는 없는건가요?

2020-03-04 21:56 UTC, tjdwlsl1021 commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/MainActivity.kt
> +    private fun loading(isLoading: Boolean) {
스터디장님이 다른 분에게 코멘트 남긴 내용입니다. 참고하시면 좋을 것 같습니다^^

sjjeong 19 hours ago Member
updateLoading으로 boolean을 받아 visible invisible 하는 것보다
showLoading, hideLoading처럼 명확한 함수명으로 만들어주는게 좋아요

2020-03-04 21:56 UTC, tjdwlsl1021 commented on 2003/byiryu/app/src/main/res/layout/view_main_item.xml
> +            android:layout_width="150dp"
xml에 dp적힌 내용을 @dimen으로 빼서 작업하는 분도 있어서, 참고하시면 좋을 것 같습니다.

2020-03-04 21:56 UTC, tjdwlsl1021 commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/MainRecyclerHolder.kt
> +            .load(item.image)
아래 옵션내용도 참고하면 좋을 것 같습니다. 
(에러났을 때나, 로딩하는 시간이 오래걸릴 때)
.error(R.drawable.bg_placeholder_movie)
.placeholder(R.drawable.bg_placeholder_movie)

2020-03-04 21:56 UTC, tjdwlsl1021 commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/MainRecyclerHolder.kt
> +        Glide.with(context)
Glide.with안에 context말고, view를 사용하는게 관리하기에 좋다는 말을 들었는데, 왜 그런것 까지는 잘 모르겠습니다.

2020-03-04 21:56 UTC, tjdwlsl1021 commented on 2003/byiryu/.gitignore
> +
제가 코드리뷰가 처음이라 다른분들 소스리뷰내용 참고해서 댓글 달았습니다.
부족하더라도 양해부탁드립니다;;

2020-03-05 01:24 UTC, BeokBeok commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/MainRecyclerHolder.kt
> +        Glide.with(context)
@tjdwlsl1021 
이유는 아마도 view 의 라이프싸이클에 따라 관리해서 그런 것이 아닐까 싶습니다.
>Although it’s good practice to clear loads you no longer need, you’re not required to do so. In fact, Glide will automatically clear the load and recycle any resources used by the load when the Activity or Fragment you pass in to Glide.with() is destroyed.

[Glide v4 : Getting Started](http://bumptech.github.io/glide/doc/getting-started.html)

2020-03-05 02:50 UTC, byiryu commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/MainActivity.kt
> +        recyclerView.adapter = adapter
어떤 분이 어떻게 작업하셨는지 잘 모르겠지만  init block을 이용한거라면 저 같은 경우에는 동작이 안됩니다.
라이프사이클상  recyclerView를 찾을수 없습니다.  함수 이름을 말씀하신거라면 개발자 취향이라고 생각합니다.

2020-03-05 02:51 UTC, byiryu commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/MainActivity.kt
> +    private fun loading(isLoading: Boolean) {
네 참고 하겠습니다. 개인적으로 BaseActivity에다가 만들어서 사용할 생각이었으나 시간이 없어서 작업 못했습니다. 추후 과제때에는 Progress를 작업해서 넣도록 하겠습니다.

2020-03-05 03:15 UTC, byiryu commented on 2003/byiryu/app/src/main/java/com/byiryu/study/api/model/MovieItem.kt
> +data class MovieItem(
네 의견 감사합니다. 개인적으로 주석을 혐오하는 스타일이라서 잘 안하는 편입니다 ㅠ_ㅠ

2020-03-05 03:15 UTC, byiryu commented on 2003/byiryu/.gitignore
> +
감사합니다.

2020-03-05 03:16 UTC, byiryu commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/MainRecyclerHolder.kt
> +        Glide.with(context)
좋은 정보 감사합니다. 몰랐던 내용이네요 
해당 내용 수정했습니다. @aa14344

2020-03-05 03:17 UTC, byiryu commented on 2003/byiryu/app/src/main/res/layout/view_main_item.xml
> +            android:layout_width="150dp"
네 동의합니다. 개인적으로 개발할때에는 공통 부분만 뺴서 작업했습니다. 
수정완료했습니다. @64fa187

2020-03-05 03:18 UTC, byiryu commented on 2003/byiryu/app/build.gradle
> +        release {
제가 builTypes 설정 내용을 잘 몰라서 공부하는대로 수정하겠습니다. 
몇가지 살펴본 내용만 추가했습니다. 

릴리즈로 돌릴 예정이 없어서  Debug설정만 했습니다.

@78da5d9

2020-03-05 03:19 UTC, byiryu commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/MainRecyclerHolder.kt
> +            .load(item.image)
감사합니다. 알고 있는 내용이었지만 이미지가 없어서 추가를 안했습니다.

위 내용 색상으로 넣어서 추가했습니다.

@fc1df57

2020-03-05 11:19 UTC, tjdwlsl1021 commented on 2003/byiryu/app/build.gradle
> +        release {
네 확인했습니다.

2020-03-05 11:19 UTC, tjdwlsl1021 commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/MainActivity.kt
> +        recyclerView.adapter = adapter
네 이부분은 제가 더 공부해보겠습니다

2020-03-05 11:20 UTC, tjdwlsl1021 commented on 2003/byiryu/app/src/main/res/layout/view_main_item.xml
> +            android:layout_width="150dp"
네 확인했습니다.

2020-03-05 11:20 UTC, tjdwlsl1021 commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/MainRecyclerHolder.kt
> +            .load(item.image)
네 확인했습니다.

2020-03-05 11:20 UTC, tjdwlsl1021 commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/MainRecyclerHolder.kt
> +        Glide.with(context)
네 확인했습니다.

2020-03-05 11:35 UTC, tjdwlsl1021 submitted a review, later dismissed
수고하셨습니다.
감사합니다.

2020-03-05 12:21 UTC, sjjeong requested changes

2020-03-05 12:21 UTC, sjjeong commented on 2003/byiryu/app/src/main/java/com/byiryu/study/api/model/MovieItem.kt
> +data class MovieItem(
저도 이방법은 좀..

2020-03-05 12:21 UTC, sjjeong commented on 2003/byiryu/app/src/main/java/com/byiryu/study/conf/config.kt
> +object config{
Config로 변경해주세요

2020-03-05 12:21 UTC, sjjeong commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/BaseActivity.kt
> +open class BaseActivity : AppCompatActivity() {
open보단 abstract로 하는게 좋습니다.
그러면 @SuppressLint("Registered") 이것도 제거 할 수 있습니다.

2020-03-05 12:21 UTC, sjjeong commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/BaseActivity.kt
> +    fun showMsg(res: Int) {
resId는 @StringRes annotation을 추가해주면 더 안전하게 코딩 할 수 있습니다.

2020-03-05 12:21 UTC, sjjeong commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/MainActivity.kt
> +    private var isLoading = false
unused 입니다 제거해주세요

2020-03-05 12:21 UTC, sjjeong commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/MainActivity.kt
> +    fun bind() {
private 추가해주세요

2020-03-05 12:21 UTC, sjjeong commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/MainActivity.kt
> +                    }
처리가 없다면 제거해주셔도 좋습니다

2020-03-05 12:21 UTC, sjjeong commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/MainActivity.kt
> +    private fun loading(isLoading: Boolean) {
뭔가 조금 이상한데 loading이면 invisible이고 loading이 아니면 visible인가요?

2020-03-05 12:21 UTC, sjjeong commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/MainActivity.kt
> +    }
내부적으로 dispose했는지 검사하기 때문에 이렇게만 해줘도 됩니다.
```kotlin
disposable?.dispose()
```

파괴 주기에서는 super를 맨 마지막에 부르는게 좋습니다.
```kotlin
override fun onDestroy() {
    disposable?.dispose()
    super.onDestroy()
}
```

2020-03-05 12:21 UTC, sjjeong commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/MainActivity.kt
> +    lateinit var text: String
이렇게 선언할 필요가 없습니다.
직접 사용하는 쪽에서 변수 선언 하도록 해주세요

2020-03-05 12:21 UTC, sjjeong commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/MainRecyclerAdapter.kt
> +    }
interface보단 higher-order function을 사용해보세요

2020-03-05 12:21 UTC, sjjeong commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/MainRecyclerAdapter.kt
> +        var item = getItem(position)
var 보단 val을 사용하는 습관을 가지면 좋습니다

2020-03-05 12:21 UTC, sjjeong commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/MainRecyclerHolder.kt
> +    var context: Context,
미사용 필드이기 때문에 제거해주세요

2020-03-05 12:21 UTC, sjjeong commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/MainRecyclerHolder.kt
> +        }
ViewHolder가 재사용되기 때문에 setOnClickListener를 bind할 때 마다 매번 할 필요가 없습니다.

2020-03-06 03:47 UTC, byiryu commented on 2003/byiryu/app/src/main/java/com/byiryu/study/conf/config.kt
> +object config{
수정완료
@af0d03d

2020-03-06 03:47 UTC, byiryu commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/BaseActivity.kt
> +open class BaseActivity : AppCompatActivity() {
수정완료
@J62fcc8c

2020-03-06 03:47 UTC, byiryu commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/BaseActivity.kt
> +    fun showMsg(res: Int) {
수정완료

2020-03-06 03:47 UTC, byiryu commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/MainActivity.kt
> +    private var isLoading = false
수정완료

2020-03-06 03:47 UTC, byiryu commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/MainActivity.kt
> +    lateinit var text: String
수정완료

2020-03-06 03:47 UTC, byiryu commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/MainRecyclerAdapter.kt
> +    }
코틀린이 익숙지 않아서 아직 사용을 잘 못해봤습니다. 이번에 좀 알게되었네요.
@7129e68

2020-03-06 03:47 UTC, byiryu commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/MainRecyclerHolder.kt
> +    var context: Context,
수정완료
@7129e68

2020-03-06 03:47 UTC, byiryu commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/MainRecyclerHolder.kt
> +        }
자주 이용했던 방법인데 잘못된 방법이었군요. 
@7129e68

2020-03-06 12:48 UTC, byiryu commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/MainActivity.kt
> +    fun bind() {
수정완료
c2fa80c

2020-03-06 12:48 UTC, byiryu commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/MainActivity.kt
> +                    }
수정완료  - Toast추가 
3c200c0

2020-03-06 12:52 UTC, byiryu commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/MainActivity.kt
> +    }
저도 하면서 이상하다고 생각했네요... 
수정완료 
loaDing()  함수 수정 - c907266
onDestroy() 함수 수정 - e9e6247

2020-03-06 12:55 UTC, byiryu commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/MainRecyclerAdapter.kt
> +        var item = getItem(position)
수정완료
7129e68

2020-03-06 14:10 UTC, sjjeong commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/MainRecyclerHolder.kt
> +        }
onBindViewHolder()에서 한다면 결국 제가 리뷰한 내용과 같습니다.
onCreateViewHolder()에서 처리해주세요

2020-03-07 09:46 UTC, wellscare commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/MainRecyclerHolder.kt
> +        }
 수정했습니다
ae8dfd9

2020-03-07 09:47 UTC, byiryu commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/MainRecyclerHolder.kt
> +        }
수정했습니다
ae8dfd9

2020-03-07 15:59 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-03-08 06:06 UTC, tjdwlsl1021 approved these changes
approve했습니다.

2020-03-08 06:11 UTC, merged