HW-1 NaverMovieAPI Project
sjjeong/GoogryAndroidArchitecutreStudy pull request #513
Opened 2020-03-03 14:30 UTC by tjdwlsl1021

- 기본 동작 구현

2020-03-04 03:07 UTC, byiryu commented on 2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/activity/MainActivity.kt
> +        startActivity(intent)
메인 액티비티에서 굳이  SearchMovieActivity로 다시 이동하는건 별로 좋아보이지 않습니다. 바로 메인에서 작업을 해도 별 무리 없어보이네요.

2020-03-04 03:07 UTC, byiryu commented on 2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/activity/SearchMovieActivity.kt
> +        btn_search.setOnClickListener(View.OnClickListener { getMovieList(et_movie_title.getText().toString()) })
버튼 클릭시   EditText 에서 텍스트가 널이거나 공백일때에 대한 처리도 있으면 좋을것 같습니다.

2020-03-04 03:07 UTC, byiryu commented on 2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/activity/SearchMovieActivity.kt
> +                    }
api 호출시 매번 어뎁터를 생성하는건 좋지 않습니다.  어뎁터를 처음 한번 생성하고 어뎁터에 아이템을 추가하는 형태가 좋아보이네요.

2020-03-04 03:07 UTC, byiryu commented on 2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/item/SearchMovieInfo.kt
> +}
kotlin에는 data class 라는  것이 있습니다. 지금도 무리는 없지만 활용하면 좋을것 같습니다.

2020-03-04 03:09 UTC, byiryu commented on 2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/item/SearchMovieInfo.kt
> +    @SerializedName("lastBuildDate")
kotlin 에는 data class라는것이 있습니다. 무리는 없지만 활용하면 더 좋을것 같습니다.

2020-03-04 13:32 UTC, tjdwlsl1021 commented on 2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/activity/MainActivity.kt
> +        startActivity(intent)
수정했습니다. @c747033

2020-03-04 13:33 UTC, tjdwlsl1021 commented on 2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/activity/SearchMovieActivity.kt
> +        btn_search.setOnClickListener(View.OnClickListener { getMovieList(et_movie_title.getText().toString()) })
수정했습니다 @eb9fe5f

2020-03-04 21:52 UTC, tjdwlsl1021 commented on 2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/activity/SearchMovieActivity.kt
> +                    }
수정했습니다. @ab68717

2020-03-04 21:53 UTC, tjdwlsl1021 commented on 2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/item/SearchMovieInfo.kt
> +    @SerializedName("lastBuildDate")
수정했습니다. @932b2de

2020-03-05 03:23 UTC, byiryu approved these changes
고생하셨습니다.

2020-03-05 11:20 UTC, sjjeong requested changes
commit id를 남길 때 @를 추가해서 링크가 생성되지 않고 있습니다.
commit id 앞 뒤에 공백만 있도록 해주세요

2020-03-05 11:20 UTC, sjjeong commented on 2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/network/SearchMovieServerURL.kt
> +    const val URL_MOVIE = "movie.json"
BaseUrl은 domain 부분만 있는게 일반적이기 때문에 https://openapi.naver.com 으로 하시고
나머지를 api쪽에 작성하시면 됩니다.
```kotlin
const val URL_BASE = "https://openapi.naver.com/"
const val URL_MOVIE = "v1/search/movie.json"
```

2020-03-05 11:20 UTC, sjjeong commented on 2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/network/RetrofitHelper.kt
> +    var retrofit: Retrofit? = null
nullable이 아니라 nonnull로 해주세요
그리고 retrofit을 매번 새로 만들어서 가져올 필요가 없습니다.
늦은 초기화가 필요하다면 lazy로 처리해주세요

2020-03-05 11:20 UTC, sjjeong commented on 2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/network/RetrofitHelper.kt
> +        ): Call<SearchMovieInfo?>? //-장르 코드
주석 위치가 잘못된 것 같습니다.

2020-03-05 11:20 UTC, sjjeong commented on 2003/tjdwlsl1021/app/src/main/res/layout/activity_search_movie.xml
> +        android:layout_width="match_parent"
match_parent 대신 0dp를 사용해주세요

2020-03-05 11:20 UTC, sjjeong commented on 2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/adapter/SearchMovieAdapter.kt
> +    private val context: Context,
context는 필요가 없습니다.
현재 코드를 봤을 때 onClick에서 필요하다면 view의 context를 가져오면 됩니다.
그리고 click했을 때 startActivity하는 것은 Adapter가 아닌 Activity에서 처리해주는 게 좋습니다.

2020-03-05 11:20 UTC, sjjeong commented on 2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/adapter/SearchMovieAdapter.kt
> +    private val movieInfoArrayList: ArrayList<SearchMovieItem>?
외부에서 받지 마시고 내부 필드로 선언해주세요 
Type은 ArrayList대신 MutalbeList이면서 Nonnull로 변경해주세요

2020-03-05 11:20 UTC, sjjeong commented on 2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/adapter/SearchMovieAdapter.kt
> +        }
setOnClickListener는 bind할 때 마다 새로 추가 해줄 필요가 없습니다.
RecyclerView에서 ViewHolder는 재사용하기 때문에 중복 set이 됩니다.

2020-03-05 11:20 UTC, sjjeong commented on 2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/adapter/SearchMovieAdapter.kt
> +        val iv_thumbnail: ImageView
선언하고 init에서 초기화 해주는 것은 선언과 동시에 초기화 하는 것과 같습니다.

init{}을 제거 하고 선언과 동시에 초기화 해주세요

2020-03-05 11:20 UTC, sjjeong commented on 2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/activity/SearchMovieActivity.kt
> +    fun getMovieList(query: String?) {
private 추가해주세요

2020-03-05 11:20 UTC, sjjeong commented on 2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/activity/SearchMovieActivity.kt
> +        val mLayoutManager: RecyclerView.LayoutManager = LinearLayoutManager(this)
layoutManager는 xml에서 추가 해 줄 수 있습니다.

2020-03-05 11:20 UTC, sjjeong commented on 2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/activity/SearchMovieActivity.kt
> +                getMovieList(et_movie_title.text.toString())
et_movie_title.text.toString() 가 중복 됩니다.
val로 선언해서 사용해주세요

2020-03-05 11:20 UTC, sjjeong commented on 2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/activity/SearchMovieActivity.kt
> +        )
getMovieList를 호출 할 때 마다 RequestNaverApi를 매번 새로 만들 필요가 없습니다.
RetrofitHelper에서 retrofit을 만드는 것과 동일하게 한번 만들고 재사용하게 해주세요

2020-03-05 11:20 UTC, sjjeong commented on 2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/activity/SearchMovieActivity.kt
> +                        val moives: ArrayList<SearchMovieItem> = ArrayList(result.items!!)
오타 있습니다.

2020-03-05 11:20 UTC, sjjeong commented on 2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/activity/SearchMovieActivity.kt
> +                        val moives: ArrayList<SearchMovieItem> = ArrayList(result.items!!)
!!는 제거해주세요

2020-03-05 11:20 UTC, sjjeong commented on 2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/activity/SearchMovieActivity.kt
> +                        rv_movie!!.adapter = movieAdapter
이 코드는 불필요 합니다. 제거해주세요

2020-03-06 21:31 UTC, tjdwlsl1021 commented on 2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/network/SearchMovieServerURL.kt
> +    const val URL_MOVIE = "movie.json"
수정했습니다.
502f246

2020-03-06 21:32 UTC, tjdwlsl1021 commented on 2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/network/RetrofitHelper.kt
> +    var retrofit: Retrofit? = null
수정했습니다.
aec846c27e1ee0db0c031fd03aaf59aa1ecccc70

2020-03-06 21:32 UTC, tjdwlsl1021 commented on 2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/network/RetrofitHelper.kt
> +        ): Call<SearchMovieInfo?>? //-장르 코드
수정했습니다.
495714b0d40c9c148414d2a11645a46f899e2c3f

2020-03-06 21:32 UTC, tjdwlsl1021 commented on 2003/tjdwlsl1021/app/src/main/res/layout/activity_search_movie.xml
> +        android:layout_width="match_parent"
수정했습니다.
e05ee86ed65d9633ec9015eb04c1f30c3d1104c4

2020-03-06 21:34 UTC, tjdwlsl1021 commented on 2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/adapter/SearchMovieAdapter.kt
> +    private val context: Context,
수정했습니다.
098c6eca141f9c423b5255baeac01d0e89af6d34

2020-03-06 21:34 UTC, tjdwlsl1021 commented on 2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/activity/SearchMovieActivity.kt
> +                getMovieList(et_movie_title.text.toString())
수정했습니다.
1c565fd0c682ec83775c79acc9faef6cec9e0ea2

2020-03-06 21:39 UTC, tjdwlsl1021 commented on 2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/activity/SearchMovieActivity.kt
> +        )
위에 RetrofitHelper.kt파일 11~14번 내용 수정할 때 같이 수정되었습니다.
aec846c27e1ee0db0c031fd03aaf59aa1ecccc70

2020-03-06 21:40 UTC, tjdwlsl1021 commented on 2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/activity/SearchMovieActivity.kt
> +                        val moives: ArrayList<SearchMovieItem> = ArrayList(result.items!!)
수정했습니다.
d22d28d2eb89d057f336cf87d2a74b10dfb4bc86

2020-03-06 21:41 UTC, tjdwlsl1021 commented on 2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/activity/SearchMovieActivity.kt
> +                        val moives: ArrayList<SearchMovieItem> = ArrayList(result.items!!)
위에 RetrofitHelper.kt파일 11~14번 줄 수정요청사항 반영할 때 같이 수정되었습니다.
aec846c27e1ee0db0c031fd03aaf59aa1ecccc70

2020-03-06 21:42 UTC, tjdwlsl1021 commented on 2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/adapter/SearchMovieAdapter.kt
> +    private val movieInfoArrayList: ArrayList<SearchMovieItem>?
수정했습니다.
c0409e92fc6cf9997cbd68ea5e6bc76b75c98c29

2020-03-06 21:45 UTC, tjdwlsl1021 commented on 2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/adapter/SearchMovieAdapter.kt
> +        }
수정은 했는데, 제대로 된건지 확인 부탁드리겠습니다.
098c6eca141f9c423b5255baeac01d0e89af6d34

2020-03-06 21:46 UTC, tjdwlsl1021 commented on 2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/adapter/SearchMovieAdapter.kt
> +        val iv_thumbnail: ImageView
수정했습니다.
ac1576e937a2b2823888099b453ad0d84f6dbd5f

2020-03-06 21:47 UTC, tjdwlsl1021 commented on 2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/activity/SearchMovieActivity.kt
> +    fun getMovieList(query: String?) {
수정했습니다.
07ee3740a27a6e3ac6d9a6cfa8c242650587caff

2020-03-06 21:47 UTC, tjdwlsl1021 commented on 2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/activity/SearchMovieActivity.kt
> +        val mLayoutManager: RecyclerView.LayoutManager = LinearLayoutManager(this)
수정했습니다.
366a0c933eccfdedd12697632f6671774742357e

2020-03-07 09:18 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-03-08 04:25 UTC, merged