2003/kangraemin
sjjeong/GoogryAndroidArchitecutreStudy pull request #515
Opened 2020-03-03 14:55 UTC by kangraemin

네이버 영화검색 api를 사용한 영화 검색 어플입니다. 

검색을 눌렀을 당시에 네트워크에 연결되어 있지 않은 경우를 추가하였습니다.

2020-03-04 14:40 UTC, kangraemin commented
스플래쉬 액티비티 / 로그인 화면을 추가하였습니다. 

추가적으로 

id, pw가 없는 경우 에러 메세지 출력 / 자동로그인 / 로그아웃 기능을 추가하였습니다.

2020-03-05 16:24 UTC, sjjeong requested changes

2020-03-05 16:24 UTC, sjjeong commented on 2003/kangraemin/app/build.gradle
> +apply plugin: 'kotlin-android-extensions'
5번째 줄에 있기 때문에 중복 선언 입니다.

2020-03-05 16:24 UTC, sjjeong commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/util/Utils.kt
> +class Utils {
이건 class보다 object가 더 어울리겠네요

2020-03-05 16:24 UTC, sjjeong commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/adapter/SearchResultAdapter.kt
> +class SearchResultAdapter(val context: Context, var data: List<ResponseMovieSearch>) :
context를 외부에서 받을 필요가 없습니다.
data도 Adapter 내부에 필드로 private으로 선언하고 함수를 통해서 데이터를 추가하도록 해주세요

2020-03-05 16:24 UTC, sjjeong commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/KangBaseActivity.kt
> +        compositeDisposable.dispose()
super.onDestroy()는 가장 마지막에 호출해주세요

2020-03-05 16:24 UTC, sjjeong commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/KangBaseActivity.kt
> +open class KangBaseActivity : AppCompatActivity() {
Base 클래스는 abstract로 해주세요

2020-03-05 16:24 UTC, sjjeong commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/KangBaseActivity.kt
> +    val compositeDisposable = CompositeDisposable()
protected를 추가해주면 좋겠습니다

2020-03-05 16:24 UTC, sjjeong commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/MovieSearchInterface.kt
> +    @Headers("Content-Type: application/json")
이것은 필요하지 않습니다.

2020-03-05 16:24 UTC, sjjeong commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/KangBaseActivity.kt
> +package com.example.kangraemin.model
KangBaseActivity는 model 은 아닌것 같습니다. 적절한 패키지로 이동해주세요

2020-03-05 16:24 UTC, sjjeong commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/Response/ResponseMovieSearch.kt
> +package com.example.kangraemin.Response
패키지는 대문자가 들어가면 안됩니다.

2020-03-05 16:24 UTC, sjjeong commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/SplashActivity.kt
> +            }
Completable.timer 를 사용하면 좋겠네요

2020-03-05 16:24 UTC, sjjeong commented on 2003/kangraemin/app/src/main/res/layout/activity_login.xml
> +            android:layout_width="match_parent"
match_parent보다 0dp를 사용하세요

2020-03-05 16:24 UTC, sjjeong commented on 2003/kangraemin/app/src/main/res/values/styles.xml
> +    </style>
스타일 이름은 AppTheme처럼 하셔야해요

2020-03-05 16:24 UTC, sjjeong commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/LoginActivity.kt
> +            }
hasEnteredId 필요 없이 skip(1)을 추가 해주면 됩니다.
```
val whenIdFocusChange = et_id.focusChanges()
    .skip(1)
    .subscribe { hasFocus ->
        layout_id.error = if (!hasFocus && et_id.text.toString().isEmpty()) {
            getString(R.string.login_error_id_empty)
        } else {
            null
        }
    }
```

2020-03-05 16:24 UTC, sjjeong commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/LoginActivity.kt
> +        }
user_info나 auto_login 값들은 상수로 관리하는게 나중에 버그를 줄일 수 있습니다.

2020-03-05 16:24 UTC, sjjeong commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/MainActivity.kt
> +        rv_search_result.layoutManager = LinearLayoutManager(this)
layoutManager는 xml에서 처리해 줄 수 있습니다.

2020-03-07 08:56 UTC, kangraemin commented on 2003/kangraemin/app/build.gradle
> +apply plugin: 'kotlin-android-extensions'
수정하였습니다 55044e762d502d1f3d7f91162a53ab8fa3bc0cde

2020-03-07 08:56 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/util/Utils.kt
> +class Utils {
수정하였습니다 ef53f883234a1bacb88713213b872778b3066234

2020-03-07 08:56 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/KangBaseActivity.kt
> +open class KangBaseActivity : AppCompatActivity() {
수정하였습니다 853a987736e58a0c96c38848f3a547442f0a0d4d

2020-03-07 08:57 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/KangBaseActivity.kt
> +        compositeDisposable.dispose()
수정하였습니다 5a250acfdbe93c0e49ac70bf8cd93d6f6140fba3

2020-03-07 08:58 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/KangBaseActivity.kt
> +    val compositeDisposable = CompositeDisposable()
수정하였습니다. 45aea7f0fe4a77c7ba41b06d97e4a1792bbb3a6c

2020-03-07 09:13 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/adapter/SearchResultAdapter.kt
> +class SearchResultAdapter(val context: Context, var data: List<ResponseMovieSearch>) :
수정하였습니다 fe215777c852089fa630ce0e34c9080e45beb63b d6dba08660c1a4cabef16fe740dbc006ac15cdba

2020-03-07 09:15 UTC, kangraemin commented on 2003/kangraemin/app/src/main/res/values/styles.xml
> +    </style>
수정하였습니다 90b7eec

2020-03-07 09:15 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/LoginActivity.kt
> +            }
수정하였습니다 b15e865

2020-03-07 09:16 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/LoginActivity.kt
> +        }
수정하였습니다 9636c61

2020-03-07 09:16 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/MainActivity.kt
> +        rv_search_result.layoutManager = LinearLayoutManager(this)
수정하였습니다 6b7e568

2020-03-07 09:16 UTC, kangraemin commented on 2003/kangraemin/app/src/main/res/layout/activity_login.xml
> +            android:layout_width="match_parent"
수정하였습니다 a755476

2020-03-07 09:17 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/SplashActivity.kt
> +            }
수정하였습니다 6a46478

2020-03-07 09:17 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/Response/ResponseMovieSearch.kt
> +package com.example.kangraemin.Response
수정하였습니다 ccb0781

2020-03-07 09:17 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/KangBaseActivity.kt
> +package com.example.kangraemin.model
수정하였습니다 067d5e0

2020-03-07 09:18 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/MovieSearchInterface.kt
> +    @Headers("Content-Type: application/json")
수정하였습니다 fc8f457

2020-03-07 09:19 UTC, kangraemin commented
gitKraken 에서 commit 내용 수정이랑 내용 수정 해보다가 커밋들이 엉켜버렸네요 ....

2020-03-07 16:02 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-03-07 16:03 UTC, sjjeong-dino approved these changes

2020-03-07 16:16 UTC, merged