HW-1 Advanced
sjjeong/GoogryAndroidArchitecutreStudy pull request #518
Opened 2020-03-04 14:23 UTC by sooakim

2020-03-05 04:26 UTC, mtjin approved these changes
꼭 변경해야할 사항은 안보여서 approve하겠습니다.

2020-03-05 04:26 UTC, mtjin commented on 2003/sooakim/app/src/main/res/layout/activity_login.xml
> +        android:id="@+id/pgb_loading"
취향차이지만 ProgressBar id는 pb를 많이 사용하지 않나요? 
나머지부분은 리뷰 남길게 없는 것 같습니다. 
approve하겠습니다.

2020-03-05 04:49 UTC, sooakim commented on 2003/sooakim/app/src/main/res/layout/activity_login.xml
> +        android:id="@+id/pgb_loading"
@sjjeong  
저는 pgb로 쓰고 있어서 참고 할만한 컨벤션이 있는 경우 링크 달아주시면 수정하고

2020-03-05 04:52 UTC, sjjeong commented on 2003/sooakim/app/src/main/res/layout/activity_login.xml
> +        android:id="@+id/pgb_loading"
이건 뭐.. 결국 어느 범주로 볼꺼냐 인 거죠
ProgressBar여서 pb로 볼 것인지 ProGressBar여서 pgb로 볼 것인지 인데 결국 취향차이에요
해외에서는 YouTube이지만 우리나라에서는 Youtube로 알고 있는 사람이 많은 것 처럼 결국 영어니까요
count냐 cnt냐 message냐 msg냐...

이 부분은 넘어가도록 하져

2020-03-06 13:57 UTC, sjjeong requested changes
나머지는 잘하셨네요!

2020-03-06 13:57 UTC, sjjeong commented on 2003/sooakim/app/src/main/java/io/github/sooakim/ui/base/SAActivity.kt
> +open class SAActivity : AppCompatActivity() {
이거는 abstract로 하면 어떨까요

2020-03-06 14:40 UTC, sooakim commented on 2003/sooakim/app/src/main/java/io/github/sooakim/ui/base/SAActivity.kt
> +open class SAActivity : AppCompatActivity() {
@sjjeong 넹 반영할게요.

2020-03-06 14:43 UTC, sooakim commented on 2003/sooakim/app/src/main/java/io/github/sooakim/ui/base/SAActivity.kt
> +open class SAActivity : AppCompatActivity() {
ac1a342

2020-03-06 14:50 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-03-06 14:50 UTC, merged