HW-1 코인헬퍼 카피 앱 만들기
sjjeong/GoogryAndroidArchitecutreStudy pull request #52
Opened 2019-06-08 14:37 UTC by sport0102

2019-06-11 14:13 UTC, machine-human commented on sport0102/app/src/main/res/layout/activity_main.xml
> +    </LinearLayout>
`        <TextView
                android:textColor="@color/grey"
                android:gravity="center"
                android:text="@string/all_krw"
                android:textSize="16sp"
                android:id="@+id/main_market_tab_tv_krw"
                android:layout_weight="1"
                android:layout_width="match_parent" android:layout_height="wrap_content"/>
        <TextView
                android:textColor="@color/grey"
                android:gravity="center"
                android:text="@string/all_btc"
                android:textSize="16sp"
                android:id="@+id/main_market_tab_tv_btc"
                android:layout_weight="1"
                android:layout_width="match_parent" android:layout_height="wrap_content"/>
        <TextView
                android:textColor="@color/grey"
                android:gravity="center"
                android:text="@string/all_eth"
                android:textSize="16sp"
                android:id="@+id/main_market_tab_tv_eth"
                android:layout_weight="1"
                android:layout_width="match_parent" android:layout_height="wrap_content"/>
        <TextView
                android:textColor="@color/grey"
                android:gravity="center"
                android:text="@string/all_usdt"
                android:textSize="16sp"
                android:id="@+id/main_market_tab_tv_usdt"
                android:layout_weight="1"
                android:layout_width="match_parent" android:layout_height="wrap_content"/>`

위 처럼 반복되는 뷰는 style 테마를 이용하시면 코드가 줄어듭니다 :)

2019-06-11 15:20 UTC, sjjeong commented
리뷰를 하셨는데 request changed인가요? approve인가요?
label도 같이 변경해주세요

2019-06-11 15:48 UTC, brooks-o submitted a review, later dismissed
네, 알겠습니다.

String Util, 패키지 분리 등과 UI(탭 선택과 전일대비 -/+ 색상 변경 등) 꼼꼼히 잘 하시고 배울점이 많은거 같습니다 :)

2019-06-11 16:12 UTC, sport0102 commented on sport0102/app/src/main/res/layout/activity_main.xml
> +    </LinearLayout>
오오 그렇군요! 스타일은 제가 잘 안쓰는 부분이어서... 이번기회에 한번 써보겠습니다!

2019-06-12 11:28 UTC, sjjeong commented
@machine-human 
Mentor Needed를 추가 하신거면 Approve도 같이 해주세요

2019-06-12 12:20 UTC, brooks-o submitted a review, later dismissed
네, 변경 했습니다 :)

2019-06-12 15:18 UTC, sjjeong requested changes
Preferences -> Editor -> Code Style -> XML -> Set from... -> Predefined Style -> Android
셋팅 추가 해주시고 프로젝트 전부 reformat code 해주세요.
각 리뷰마다 commit 나눠서 작업해주세요.

2019-06-12 15:18 UTC, sjjeong commented on sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/api/model/MarketModel.kt
> +    val english_name: String,
Property는 camelCase를 써야 합니다.

2019-06-12 15:18 UTC, sjjeong commented on sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/api/Retrofit.kt
> +    OkHttpClient().newBuilder().readTimeout(10, TimeUnit.SECONDS).connectTimeout(1, TimeUnit.SECONDS).build()
https://kotlinlang.org/docs/reference/coding-conventions.html#chained-call-wrapping
해당 부분 컨벤션 적용해주세요

2019-06-12 15:18 UTC, sjjeong commented on sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/util/StringUtil.kt
> +fun getKRWCommaPrice(price: Double): String = if (price.toString().split(".")[1].toInt() > 0) {
= 와 if 사이에 line brake를 추가해주시면 조금 더 보기 좋은 코드가 됩니다.

2019-06-12 15:18 UTC, sjjeong commented on sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/util/StringUtil.kt
> +fun getBTCETHCommaPrice(price: Double): String = String.format("%.8f", price)
`getBTCETHCommaPrice`보단 `getBtcEthCommaPrice`로 해주셔야 합니다.
https://source.android.com/setup/contribute/code-style#treat-acronyms-as-words

2019-06-12 15:18 UTC, sjjeong commented on sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/util/StringUtil.kt
> +fun getKRWTotalDealPrice(totalPrice: Double): String = "${String.format("%,d", (totalPrice / 1000000).toInt())} M"
1000000을 그냥 보기에 몇인지 구분하기 힘들어서 1_000_000로 표기하면 좋습니다.

2019-06-12 15:18 UTC, sjjeong commented on sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/util/StringUtil.kt
> +        return "${String.format("%,d", (totalPrice / 1000).toInt())} K"
return하지 않고 =로 바로 써도 됩니다.

2019-06-12 15:18 UTC, sjjeong commented on sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/ui/main/TickerListAdapter.kt
> +        val retView = LayoutInflater.from(parent.context)
=과 LayoutInflater 사이에 line break 추가해주시면 조금 더 보기 좋은 코드가 됩니다.

2019-06-12 15:18 UTC, sjjeong commented on sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/ui/main/TickerListAdapter.kt
> +        return tickerList.size
이 함수는
```kotlin
override fun getItemCount() = tickerList.size
```
로 축약해서 사용할 수 있습니다.

2019-06-12 15:18 UTC, sjjeong commented on sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/ui/main/TickerListAdapter.kt
> +        with(holder.itemView) {
onBindViewHolder에서 작업하는 내용들을 ViewHolder 내부 함수를 만들어서 이동시켜주세요.
onBindViewHolder에서는
```kotlin
holder.bind(tickerList[position])
```
정도만 있으면 됩니다.

2019-06-12 15:18 UTC, sjjeong commented on sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/ui/main/TickerListAdapter.kt
> +        tickerList = list
외부에서 들어온 List와 내부에서 사용하는 List는 다른 객체여야 합니다.
```kotlin
this.tickerList.clear()
this.tickerList.addAll(list)
```
로 수정해주세요.

2019-06-12 15:18 UTC, sjjeong commented on sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/ui/main/MainPagerAdapter.kt
> +    private val marketList = listOf(Market.KRW, Market.BTC, Market.ETH, Market.USDT)
```kotlin
private val marketList = Market.values()
```
처럼 사용 할 수 있습니다.
만약 list형태가 필요하다면 `.toList()`를 사용하면 됩니다.

2019-06-12 15:18 UTC, sjjeong commented on sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/ui/main/MainPagerAdapter.kt
> +    override fun getItem(position: Int): Fragment? {
함수 내부에서 return만 있다면 =을 사용해서 축약 할 수 있습니다.

2019-06-12 15:18 UTC, sjjeong commented on sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/ui/main/MainFragment.kt
> +                    response.body()?.filter { item -> item.market.startsWith(market.marketName, true) }
33번줄에서 이미 let으로 가져왔기 때문에 `response.body()`를 `it`으로 사용 할 수 있습니다.

2019-06-12 15:18 UTC, sjjeong commented on sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/ui/main/MainFragment.kt
> +                        ?.map { item -> query += item.market + "," }
query만드는 코드는
```kotlin
val query =
    it.filter { item ->
        item.market.startsWith(market.marketName, true)
    }
        .joinToString { marketModel ->
            marketModel.market
        }
```
로 작성 할 수 있습니다.

2019-06-12 15:18 UTC, sjjeong commented on sport0102/app/src/main/res/layout/activity_main.xml
> +    <LinearLayout
이부분은 TabLayout을 사용하면 간단하게 구현 할 수 있을 것 같습니다.

2019-06-13 13:25 UTC, sport0102 commented on sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/api/model/MarketModel.kt
> +    val english_name: String,
Model에 있는 property의 형태를 snake case에서 came case로 변경하였습니다

2019-06-13 13:28 UTC, sport0102 commented on sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/api/Retrofit.kt
> +    OkHttpClient().newBuilder().readTimeout(10, TimeUnit.SECONDS).connectTimeout(1, TimeUnit.SECONDS).build()
Chained call wrapping convention 적용하였습니다.

2019-06-13 13:29 UTC, sport0102 commented on sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/util/StringUtil.kt
> +fun getKRWCommaPrice(price: Double): String = if (price.toString().split(".")[1].toInt() > 0) {
line brake 적용하였습니

2019-06-13 13:32 UTC, sport0102 commented on sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/util/StringUtil.kt
> +fun getBTCETHCommaPrice(price: Double): String = String.format("%.8f", price)
해당부분 적용하였습니다. 항상 궁금하던 부분이었는데 레퍼런스까지 주셔서 감사합니다.

2019-06-13 13:35 UTC, sport0102 commented on sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/util/StringUtil.kt
> +fun getKRWTotalDealPrice(totalPrice: Double): String = "${String.format("%,d", (totalPrice / 1000000).toInt())} M"
이것도 몰랐던 부분인데 알려주셔서 감사합니다. 적용하였습니다.

2019-06-13 13:37 UTC, sport0102 commented on sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/util/StringUtil.kt
> +        return "${String.format("%,d", (totalPrice / 1000).toInt())} K"
적용하였습니다!

2019-06-13 13:38 UTC, sport0102 commented on sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/ui/main/TickerListAdapter.kt
> +        val retView = LayoutInflater.from(parent.context)
line break 적용하였습니

2019-06-13 13:39 UTC, sport0102 commented on sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/ui/main/TickerListAdapter.kt
> +        return tickerList.size
리턴방식을 변경하였습니

2019-06-13 13:45 UTC, sport0102 commented on sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/ui/main/TickerListAdapter.kt
> +        with(holder.itemView) {
수정하였습니다!

2019-06-13 13:46 UTC, sport0102 commented on sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/ui/main/TickerListAdapter.kt
> +        tickerList = list
제가 기초가 부족해서 잘 몰랐던 부분입니다. 알려주셔서 감사합니다!

2019-06-13 13:48 UTC, sport0102 commented on sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/ui/main/MainPagerAdapter.kt
> +    private val marketList = listOf(Market.KRW, Market.BTC, Market.ETH, Market.USDT)
오 잘 몰랐던 부분입니다. 알려주셔서 감사합니다!

2019-06-13 13:49 UTC, sport0102 commented on sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/ui/main/MainPagerAdapter.kt
> +    override fun getItem(position: Int): Fragment? {
적용하였습니다!

2019-06-13 13:50 UTC, sport0102 commented on sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/ui/main/MainFragment.kt
> +                    response.body()?.filter { item -> item.market.startsWith(market.marketName, true) }
적용하였습니다!

2019-06-13 13:54 UTC, sport0102 commented on sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/ui/main/MainFragment.kt
> +                        ?.map { item -> query += item.market + "," }
오오 joinToString의 사용방법을 몰랐었습니다! 알려주셔서 감사합니다!

2019-06-13 14:19 UTC, sport0102 commented on sport0102/app/src/main/res/layout/activity_main.xml
> +    <LinearLayout
TabLayout을 사용해 본 적 없었는데 이번기회에 사용해 보았습니다! 굉장히 편하네요 감사합니다!

2019-06-13 14:23 UTC, sjjeong commented
@sport0102 
각 리뷰마다 커밋 아이디 넣어주세요

2019-06-13 15:07 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-06-13 15:08 UTC, sjjeong commented
> 네, 변경 했습니다 :)

approve가 안됐습니다.
확인해주세요.

2019-06-14 01:49 UTC, brooks-o approved these changes

2019-06-14 01:49 UTC, brooks-o approved these changes

2019-06-14 01:49 UTC, brooks-o approved these changes

2019-06-14 01:50 UTC, brooks-o approved these changes

2019-06-14 03:01 UTC, merged