HW-1(기능추가) 네이버 영화검색 앱
sjjeong/GoogryAndroidArchitecutreStudy pull request #520
Opened 2020-03-05 08:54 UTC by mtjin

스플래쉬화면, 자동로그인, 로그인 창 구현 했습니다

2020-03-05 09:31 UTC, sooakim requested changes

2020-03-05 09:31 UTC, sooakim commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/LoginActivity.kt
> +        const val USER_PW = "P@sswOrd"
```suggestion
        private const val USER_ID = "id"
        private const val USER_PW = "P@sswOrd"
```

2020-03-05 09:31 UTC, sooakim commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/LoginActivity.kt
> +                PreferenceManager.setBoolean(this, PreferenceManager.AUTO_LOGIN_KEY, true)
로그인이 완료된 후 뒤로가기를 누르면 어떻게 될까요?
```suggestion
                PreferenceManager.setBoolean(this, PreferenceManager.AUTO_LOGIN_KEY, true)
                startActivity(Intent(this, MovieSearchActivity::class.java))
                finish()
               
```

2020-03-05 09:31 UTC, sooakim commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/utils/PreferenceManager.kt
> +    private fun getPreferences(context: Context): SharedPreferences? {
반환값이 Nullable일 필요가 있을까요?
```suggestion
    private fun getPreferences(context: Context): SharedPreferences {
```

2020-03-05 09:41 UTC, mtjin commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/LoginActivity.kt
> +        const val USER_PW = "P@sswOrd"
수정했습니다.

c90cf4c

2020-03-05 09:41 UTC, mtjin commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/LoginActivity.kt
> +                PreferenceManager.setBoolean(this, PreferenceManager.AUTO_LOGIN_KEY, true)
수정했습니다.

ed62341

2020-03-05 09:42 UTC, mtjin commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/utils/PreferenceManager.kt
> +    private fun getPreferences(context: Context): SharedPreferences? {
수정했습니다.

d13bbbf

2020-03-05 11:21 UTC, sooakim requested changes

2020-03-05 11:21 UTC, sooakim commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/LoginActivity.kt
> +                tvPw.error = "아이디와 또는 패스워드가 틀렸습니다"
컨벤션 문제
```suggestion
            } else if (id.isEmpty()) {
                tvId.error = "아이디를 입력해주세요"
            } else if (pw.isEmpty()) {
                tvPw.error = "비밀번호를 입력해주세요"
            } else {
                tvPw.error = "아이디와 또는 패스워드가 틀렸습니다"
            }
```

2020-03-05 14:23 UTC, mtjin commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/LoginActivity.kt
> +                tvPw.error = "아이디와 또는 패스워드가 틀렸습니다"
수정했습니다. commit suggestion 한번 해봤습니다.

2020-03-06 01:10 UTC, sooakim approved these changes

2020-03-06 12:36 UTC, sjjeong requested changes

2020-03-06 12:36 UTC, sjjeong commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/LoginActivity.kt
> +            }
validation 검사는 모든 케이스를 다 통과 하고 나서 성공처리를 해야 하기 때문에 보통 else에서 성공 처리를 합니다.

2020-03-07 03:45 UTC, mtjin commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/LoginActivity.kt
> +            }
위에서 commit suggestion으로 merge를 했다가 제 로컬과 충돌이 나서 제 브랜치 git pull을 해봐도 안되길래 강제 push를 하게되었습니다.

cdaa8af

2020-03-07 05:00 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-03-07 05:12 UTC, merged