HW-2 apply Model
sjjeong/GoogryAndroidArchitecutreStudy pull request #524
Opened 2020-03-08 14:24 UTC by sooakim

2020-03-08 14:46 UTC, sooakim commented
로그인 파트쪽 분리가 아직 안됐는데 영화 검색 파트는 완료되서 미리 리퀘스트 만들었어요. 리뷰할 때 참고해주세요.

2020-03-09 02:26 UTC, sjjeong requested changes
SAMovieEntity랑 SAMovieModel이 두개씩 있어서 코드 볼 때 조금 어려운 감이 있네요.
data class에 ViewModel이라는 postfix가 들어가서 추후 MVVM의 ViewModel과 혼용이 될 것 같아요
layout마다 postfix를 다르게 가져가면 어떨까요?
local, remote, data, domain, presentation 부분을요

근데 이게 multi module하면 접근제한이 생기니까 어느정도 혼용되는게 없어지는걸까요?

2020-03-09 02:26 UTC, sjjeong commented on 2003/sooakim/app/src/main/java/io/github/sooakim/network/SANetworkServiceImpl.kt
> +            level = HttpLoggingInterceptor.Level.BODY
BuildConfig.DEBUG로 검사에서 NONE을 넣어주면 좋겠네용

2020-03-09 02:26 UTC, sjjeong commented on 2003/sooakim/app/src/main/java/io/github/sooakim/domain/repository/SARepository.kt
> +interface SARepository
이거 unused 인데 SAAuthRepository랑 SAMovieRepository에 상속하려고 했던거 아니에요?

2020-03-09 02:26 UTC, sjjeong commented on 2003/sooakim/app/src/main/java/io/github/sooakim/ui/movie/mapper/SAMovieMapper.kt
> +class SAMovieMapper : SAMapper<SAMovieModel, SAMovieViewModel> {
object로 만들어서 직접 사용했을 때와 class로 만들고 의존주입 했을 때 중에 어떤면에서 후자가 더 좋다고 생각하셨나요?

object인지 class인지와 별개로
저희 회사 같은 경우에는 data class에 extension 함수로 만들어서 mapper를 대신해서 사용하고 있어요
1:1에서는 같은 효과인데 1:n이 되면 mapper 클래스가 많이 생겨야하고 확장성이 떨어지면서 어떤 mapper를 가져와야 하는지 알아야 하는 리소스가 있더라고요. 그래서 data class에 함수로 변환해서 사용하고 있어요

2020-03-09 02:30 UTC, sjjeong commented
@Hoyuo @Nanamare @improve777 @sabgilhun 
리뷰 한번씩 봐주세요

2020-03-09 02:39 UTC, sooakim commented on 2003/sooakim/app/src/main/java/io/github/sooakim/network/SANetworkServiceImpl.kt
> +            level = HttpLoggingInterceptor.Level.BODY
77b3a27

2020-03-09 02:40 UTC, sooakim commented on 2003/sooakim/app/src/main/java/io/github/sooakim/domain/repository/SARepository.kt
> +interface SARepository
1461d35

2020-03-09 03:12 UTC, sooakim commented on 2003/sooakim/app/src/main/java/io/github/sooakim/ui/movie/mapper/SAMovieMapper.kt
> +class SAMovieMapper : SAMapper<SAMovieModel, SAMovieViewModel> {
class로 만들어서 Application에 주입하면 Application 라이프사이클에 따라 메모리 해제할 수 있으니 object로 쓸 때보다 메모리 관리 측면에서 더 용이 하지 않을까 싶었어요..(틀릴 수도 있어요) extension으로도 해봤는데 다른 extension 함수랑 mapper함수랑 구분이 안되는 것 같더라고요.

2020-03-09 03:39 UTC, Hoyuo commented
모든 클래스에 SA를 붙이는 이유가 있을까요?

2020-03-09 03:46 UTC, sooakim commented
@Hoyuo iOS쪽에서 개발할 때 Alamofire -> AF같이 prefix를 붙여놓는 프레임워크가 많았는데 사용하다보니 어떤 프레임워크에 있는 클래스인지 구별하기가 좋았어서 Android에도 적용을 해봤어요. (다른 외부라이브러리가 prefix를 안 써서 별 효과가 없는 것 같기는 해요)

2020-03-09 03:49 UTC, Hoyuo commented
@sooakim iOS인 경우 패키지 개념이 없고 동일 namespace이기때문에 prefix를 사용 하는 경우가 많습니다.
두가지가 다른 플랫폼이기 때문에 각각 플랫폼에 맞는 방법을 추천 드립니다.

2020-03-09 04:23 UTC, Hoyuo commented on 2003/sooakim/app/build.gradle
> +    implementation 'androidx.room:room-runtime:2.2.4'
변수로 따로 빼서 버전 관리 하는 것을 추천 드립니다.
room 처럼 다 같이 버전 관리인 경우 더 유용 합니다.

`implementation "androidx.room:room-runtime:$roomVersion"`

2020-03-09 04:23 UTC, Hoyuo commented on 2003/sooakim/app/src/main/java/io/github/sooakim/data/local/converter/SADateTypeConverter.kt
> +import java.util.*
`import java.util.*` 말고 직접 명시 부탁드립니다.

2020-03-09 04:23 UTC, Hoyuo commented on 2003/sooakim/app/src/main/java/io/github/sooakim/data/local/dao/SAMovieDao.kt
> +    )
각각 검색 대상을 지정하는 것이 어떨까요?
하나의 검색어로 title, subtitle, directro, actor를 다 검색하는 것은 비 효율적으로 보입니다.

2020-03-09 04:23 UTC, Hoyuo commented on 2003/sooakim/app/src/main/java/io/github/sooakim/data/local/model/SAMovieEntity.kt
> +    val subtitle: String,
subtitle이 PK로 설정 하신 이유가 있을까요?

2020-03-09 04:23 UTC, Hoyuo commented on 2003/sooakim/app/src/main/java/io/github/sooakim/data/model/SAMovieEntity.kt
> +import java.util.*
동일합니다.

2020-03-09 04:23 UTC, Hoyuo commented on 2003/sooakim/app/src/main/java/io/github/sooakim/data/remote/mapper/SAMovieRemoteMapper.kt
> +import java.util.*
동일합니다

2020-03-09 04:23 UTC, Hoyuo commented on 2003/sooakim/app/src/main/java/io/github/sooakim/util/ext/Date.kt
> +import java.util.*
동일합니다

2020-03-09 04:28 UTC, sooakim commented on 2003/sooakim/app/src/main/java/io/github/sooakim/data/local/model/SAMovieEntity.kt
> +    val subtitle: String,
@Hoyuo 네이버 API를 조회한 결과를 봤을 때 subtitle이 다른 item과 중복되지 않을 것 같아서 PK로 지정했어요. autoGenereate 필드를 새로 만드는게 좋았을까요.

2020-03-09 04:30 UTC, sooakim commented on 2003/sooakim/app/src/main/java/io/github/sooakim/data/local/dao/SAMovieDao.kt
> +    )
@Hoyuo 각각 지정한다는 것이 getSearchWithSubtitle, getSearchWithTitle이런식으로 Dao를 나눈다는 의미일까요? 네이버 API에 query를 던졌을 때 title뿐만 아니라 다른 항목들도 비교해서 가져오는 것 같아서 OR로 넣었어요.

2020-03-09 04:32 UTC, Hoyuo commented on 2003/sooakim/app/src/main/java/io/github/sooakim/data/local/model/SAMovieEntity.kt
> +    val subtitle: String,
title, subtitle을 멀티 PK 설정 하셔도 괜찮을꺼 같습니다.
아니면 별도의 id 필드를 설정하셔도 괜찮습니다.

2020-03-09 04:34 UTC, Hoyuo commented on 2003/sooakim/app/src/main/java/io/github/sooakim/data/local/dao/SAMovieDao.kt
> +    )
네이버 Query 와 동일하게 하는 부분이 아닌 DB 이기 때문에 각각 나누어서 검색하시는 것이 좋아 보입니다.
title, subtitle, director, actor 각각 구현해서 하나의 getSearchMovie로 합치는 방법도 있습니다.

2020-03-09 04:39 UTC, Hoyuo commented on 2003/sooakim/app/src/main/java/io/github/sooakim/data/remote/utils/Single.kt
> +}
실제 현업에서 사용하고 계시는건가요??

2020-03-09 04:40 UTC, Hoyuo commented on 2003/sooakim/app/src/main/java/io/github/sooakim/domain/model/SAMovieModel.kt
> +import java.util.*
```suggestion
import java.util.Date
```

2020-03-09 04:41 UTC, sooakim commented on 2003/sooakim/app/src/main/java/io/github/sooakim/data/remote/utils/Single.kt
> +}
@Hoyuo 현업에서 사용하고 있는 코드는 아니고, ![안드로이드 아키텍처 가이드](https://developer.android.com/topic/libraries/architecture/images/network-bound-resource.png)에 있는 다이어그램대로 구현해보려고 추가했어요.

2020-03-09 05:01 UTC, Hoyuo commented on 2003/sooakim/app/src/main/java/io/github/sooakim/ui/base/SAActivity.kt
> +
`onDestroy`때만 `compositeDisposable.clear()`을 해야하는지 판단이 어렵습니다.
각 화면에게 자율 판단권을 주는 것이 더 안전합니다

2020-03-09 05:02 UTC, Hoyuo commented on 2003/sooakim/app/src/main/java/io/github/sooakim/ui/movie/mapper/SAMovieMapper.kt
> +import java.util.*
동일합니다.

2020-03-09 05:39 UTC, Hoyuo commented on 2003/sooakim/app/src/main/java/io/github/sooakim/util/ext/String.kt
> +import java.util.*
동일합니다.

2020-03-09 05:39 UTC, Hoyuo commented on 2003/sooakim/app/src/main/java/io/github/sooakim/ui/movie/SAMovieSearchActivity.kt
>              .observeOn(AndroidSchedulers.mainThread())
`observeOn`을 의도적으로 2번 하신 건가요?

2020-03-09 05:45 UTC, sooakim commented on 2003/sooakim/app/src/main/java/io/github/sooakim/ui/movie/SAMovieSearchActivity.kt
>              .observeOn(AndroidSchedulers.mainThread())
@Hoyuo getMovies가 io쓰레드에서 동작하고 있기때문에 hideLoading()을 해주기 위해서 다시 mainThread로 변경을 했어요.

2020-03-09 10:45 UTC, sooakim commented on 2003/sooakim/app/src/main/java/io/github/sooakim/util/ext/String.kt
> +import java.util.*
336baa5

2020-03-09 10:45 UTC, sooakim commented on 2003/sooakim/app/src/main/java/io/github/sooakim/ui/movie/mapper/SAMovieMapper.kt
> +import java.util.*
336baa5

2020-03-09 10:45 UTC, sooakim commented on 2003/sooakim/app/src/main/java/io/github/sooakim/domain/model/SAMovieModel.kt
> +import java.util.*
336baa5

2020-03-09 10:45 UTC, sooakim commented on 2003/sooakim/app/src/main/java/io/github/sooakim/util/ext/Date.kt
> +import java.util.*
336baa5

2020-03-09 10:45 UTC, sooakim commented on 2003/sooakim/app/src/main/java/io/github/sooakim/data/model/SAMovieEntity.kt
> +import java.util.*
336baa5

2020-03-09 10:45 UTC, sooakim commented on 2003/sooakim/app/src/main/java/io/github/sooakim/data/local/converter/SADateTypeConverter.kt
> +import java.util.*
336baa5

2020-03-09 11:13 UTC, sjjeong commented on 2003/sooakim/app/src/main/java/io/github/sooakim/ui/movie/mapper/SAMovieMapper.kt
> +class SAMovieMapper : SAMapper<SAMovieModel, SAMovieViewModel> {
제가 알기론 process가 죽을 때 Application이 같이 죽는걸로 알아요
그래서 Context가 필요없는 util성 클래스들은 object로 만들어도 충분합니다.

2020-03-09 11:14 UTC, sjjeong commented on 2003/sooakim/app/src/main/java/io/github/sooakim/data/local/converter/SADateTypeConverter.kt
> +import java.util.*
커밋 찍은게 뭔가 이 파일은 아닌거같네요

2020-03-09 12:53 UTC, sooakim commented on 2003/sooakim/app/src/main/java/io/github/sooakim/data/local/converter/SADateTypeConverter.kt
> +import java.util.*
bd2d6ca

2020-03-09 12:54 UTC, sooakim commented on 2003/sooakim/app/src/main/java/io/github/sooakim/data/remote/mapper/SAMovieRemoteMapper.kt
> +import java.util.*
bd2d6ca

2020-03-09 12:54 UTC, sooakim commented on 2003/sooakim/app/src/main/java/io/github/sooakim/data/local/converter/SADateTypeConverter.kt
> +import java.util.*
@sjjeong optimize import과정에서 수정 사항이 누락된 것 같네요. 수정했습니다.

2020-03-09 12:59 UTC, sooakim commented on 2003/sooakim/app/build.gradle
> +    implementation 'androidx.room:room-runtime:2.2.4'
f1f1a14

2020-03-09 13:31 UTC, improve777 commented on 2003/sooakim/app/src/main/java/io/github/sooakim/domain/mapper/SAMapper.kt
> +package io.github.sooakim.domain.mapper
Domain 패키지에서 Data 패키지에 대해 의존성이 생기기 때문에 해당 mapper 패키지를 data 패키지로 옮기는게 맞는 것 같습니다.

2020-03-09 13:31 UTC, improve777 commented on 2003/sooakim/app/src/main/java/io/github/sooakim/domain/repository/SAAuthRepositoryImpl.kt
> +class SAAuthRepositoryImpl(
Repository 의 구현 클래스도 Data 패키지에서 Domain 패키지에 있는 Repository 를 구현하는 것이기 때문에 Data 패키지로 옮기는게 맞을 것 같습니다.

2020-03-09 13:31 UTC, improve777 commented on 2003/sooakim/app/src/main/java/io/github/sooakim/domain/repository/SAMovieRepositoryImpl.kt
> +class SAMovieRepositoryImpl(
Repository 의 구현 클래스도 Data 패키지에서 Domain 패키지에 있는 Repository 를 구현하는 것이기 때문에 Data 패키지로 옮기는게 맞을 것 같습니다.

2020-03-09 13:31 UTC, improve777 commented on 2003/sooakim/app/src/main/java/io/github/sooakim/data/remote/model/SAModel.kt
> +interface SAModel
remote.model.response.SAResponse 와 동일한 역할이라 생각됩니다.
별도로 나누신 이유가 있을까요?

2020-03-09 13:32 UTC, improve777 commented
> SAMovieEntity랑 SAMovieModel이 두개씩 있어서 코드 볼 때 조금 어려운 감이 있네요.
> data class에 ViewModel이라는 postfix가 들어가서 추후 MVVM의 ViewModel과 혼용이 될 것 같아요
> layout마다 postfix를 다르게 가져가면 어떨까요?
> local, remote, data, domain, presentation 부분을요
> 
> 근데 이게 multi module하면 접근제한이 생기니까 어느정도 혼용되는게 없어지는걸까요?

석준님 말씀대로 SAMovieEntity(data/local), SAMovieModel(domain/remote) 가 동일한 이름으로 있어서 주의가 필요할 것 같습니다. 개인적으로는
UI : MoviePresentation
Data : MovieData
Local : MovieEntity
Remote : MovieRequest, MovieResponse
Domain : Movie
이런식으로 구별을 할 수 있는게 낫지 않을까 싶습니다.

2020-03-09 13:39 UTC, sooakim commented on 2003/sooakim/app/src/main/java/io/github/sooakim/data/remote/utils/Single.kt
> +}
캐싱 로직을 잘 못 이해하고 작성한 것 같아 해당 함수는 삭제했습니다.

2020-03-09 13:39 UTC, sooakim commented on 2003/sooakim/app/src/main/java/io/github/sooakim/data/remote/utils/Single.kt
> +}
5eefcf1

2020-03-09 13:39 UTC, sooakim commented on 2003/sooakim/app/src/main/java/io/github/sooakim/data/local/model/SAMovieEntity.kt
> +    val subtitle: String,
5eefcf1

2020-03-09 13:39 UTC, sooakim commented on 2003/sooakim/app/src/main/java/io/github/sooakim/data/local/dao/SAMovieDao.kt
> +    )
5eefcf1

2020-03-09 13:42 UTC, sooakim commented on 2003/sooakim/app/src/main/java/io/github/sooakim/ui/base/SAActivity.kt
> +
e6ac4fb

2020-03-09 13:51 UTC, sooakim commented on 2003/sooakim/app/src/main/java/io/github/sooakim/domain/repository/SAMovieRepositoryImpl.kt
> +class SAMovieRepositoryImpl(
7933e27

2020-03-09 13:51 UTC, sooakim commented on 2003/sooakim/app/src/main/java/io/github/sooakim/domain/repository/SAAuthRepositoryImpl.kt
> +class SAAuthRepositoryImpl(
7933e27

2020-03-09 13:51 UTC, sooakim commented on 2003/sooakim/app/src/main/java/io/github/sooakim/domain/mapper/SAMapper.kt
> +package io.github.sooakim.domain.mapper
62c65ef

2020-03-09 14:23 UTC, sooakim commented on 2003/sooakim/app/src/main/java/io/github/sooakim/ui/movie/mapper/SAMovieMapper.kt
> +class SAMovieMapper : SAMapper<SAMovieModel, SAMovieViewModel> {
네이밍: 
2dda2a9
ed00da8

class -> object:
56f3a01

2020-03-09 14:25 UTC, sooakim commented
현재까지 리뷰 내용 전부 반영했습니다. 시간 내서 리뷰해주셔서 감사합니다.. 많이 도움이 되네요.

2020-03-09 14:26 UTC, sooakim commented on 2003/sooakim/app/src/main/java/io/github/sooakim/data/remote/model/SAModel.kt
> +interface SAModel
Response안에 Model리스트가 랩핑(?)되어 있는 형태여서 Generic으로 선언할 때 인스턴스 타입을 제한하기 위해서 나눴습니다.

2020-03-09 15:06 UTC, ddaeyeonkim reviewed
LGTM 👍👍👍

2020-03-10 03:31 UTC, Nanamare requested changes

2020-03-10 03:31 UTC, Nanamare commented on 2003/sooakim/app/src/main/java/io/github/sooakim/ui/login/SALoginActivity.kt
>          startActivity(Intent(application, SAMovieSearchActivity::class.java))
여기 applicationContext 이 들어가는 이유가 있나요 ?

2020-03-10 03:31 UTC, Nanamare commented on 2003/sooakim/app/src/main/java/io/github/sooakim/ui/base/SAActivity.kt
>          get() {
한줄이라 게터 표현식으로 써도 될 꺼 같은데 return 으로 처리하는 이유가 있나요 ?

2020-03-10 03:31 UTC, Nanamare commented on 2003/sooakim/app/src/main/java/io/github/sooakim/ui/base/SAActivity.kt
>      }
requireApplication 함수가    
throw IllegalStateException("applicationContext is not instance of SAApplication") 를 던질수 있는 상황이 어떤 상황인가요 ?
방어 코드인가요 ?

protected val application: SAApplication?
    get() = (applicationContext as? SAApplication)

fun requireApplication(): SAApplication {
    return application as SAApplication
}

이런식으로 구현하면 문제가 생기나요 ?

2020-03-10 03:31 UTC, Nanamare commented on 2003/sooakim/app/src/main/java/io/github/sooakim/ui/SASplashActivity.kt
>              routeLogin()
routeLogin(), routeMovieSearch()
함수도 applicationContext 를 가지고 startActivity 를 하는 것 같네요

2020-03-10 03:43 UTC, sooakim commented on 2003/sooakim/app/src/main/java/io/github/sooakim/ui/base/SAActivity.kt
>          get() {
getter표현식이 어떤 걸 말씀하시는건가요? 예를 들어주실 수 있나요?

1번
```kotlin
protected val compositeDisposable: CompositeDisposable by lazy(::CompositeDisposable)
```
2번
```kotlin
protected val compositeDisposable: CompositeDisposable = CompositeDisposable()
```

2020-03-10 03:44 UTC, sooakim commented on 2003/sooakim/app/src/main/java/io/github/sooakim/ui/base/SAActivity.kt
>      }
말씀하신대로 방어 코드입니다.

2020-03-10 03:45 UTC, sooakim commented on 2003/sooakim/app/src/main/java/io/github/sooakim/ui/SASplashActivity.kt
>              routeLogin()
액티비티내에서 applicationContext로 startActivity했을 때 어떤 문제가 있나요?

2020-03-10 03:45 UTC, Nanamare commented on 2003/sooakim/app/src/main/java/io/github/sooakim/ui/base/SAActivity.kt
>      }
근데 이부분이 low memory killer 나 oom 에도 걸리지 않을 것 같고 정확히 어떤 상황에 대비하신 건지 궁금했습니다

2020-03-10 03:46 UTC, Nanamare commented on 2003/sooakim/app/src/main/java/io/github/sooakim/ui/base/SAActivity.kt
>          get() {
아아 application 프로퍼티인데 제가 코멘트 커서를 다른 부분 찍었습니다 ㅋ.ㅋ

2020-03-10 03:47 UTC, Hoyuo commented on 2003/sooakim/app/src/main/java/io/github/sooakim/ui/SASplashActivity.kt
>              routeLogin()
스택이 다르게 됩니다.

2020-03-10 03:56 UTC, Nanamare commented on 2003/sooakim/app/src/main/java/io/github/sooakim/ui/SASplashActivity.kt
>              routeLogin()
![image](https://user-images.githubusercontent.com/17498974/76278206-64abff00-62ce-11ea-9ad7-5c01ff862d56.jpeg)

아래 작은 글씨로 왜 사용하면 안되는지 나옵니다

2020-03-10 03:58 UTC, sooakim commented on 2003/sooakim/app/src/main/java/io/github/sooakim/ui/SASplashActivity.kt
>              routeLogin()
@Hoyuo @Nanamare 이해했습니다.

2020-03-10 04:00 UTC, sooakim commented on 2003/sooakim/app/src/main/java/io/github/sooakim/ui/base/SAActivity.kt
>      }
1. SAApplication을 사용하겠다고 해놓고 AndroidManifest에 다른 클래스를 적는 실수를 한 경우
말고는 딱히 생각나는 경우가 없긴합니다.

2020-03-10 04:06 UTC, Nanamare commented on 2003/sooakim/app/src/main/java/io/github/sooakim/ui/base/SAActivity.kt
>          get() {
그리고 적어주신 두개의 표현법에서는 당연히 1번(by lazy)이 좋은걸 로 알고 있습니다
언어차원에서 제공해주는 동기화, 값을 사용직전까지 최대한 지연시킬 수 있는 큰 장점들이 있는 것으로 알고 있습니다

2020-03-10 04:12 UTC, sooakim commented on 2003/sooakim/app/src/main/java/io/github/sooakim/ui/base/SAActivity.kt
>          get() {
@Nanamare 네 그래서 lazy구문을 사용했습니다. 또 공통 부모 액티비티에 있었기때문에 disposable이 필요없는 경우 생성하지 않을 수 있고요.

2020-03-10 04:15 UTC, sooakim commented on 2003/sooakim/app/src/main/java/io/github/sooakim/ui/base/SAActivity.kt
>          get() {
d9f4fbf

2020-03-10 04:15 UTC, sooakim commented on 2003/sooakim/app/src/main/java/io/github/sooakim/ui/SASplashActivity.kt
>              routeLogin()
7b0d604

2020-03-10 04:15 UTC, sooakim commented on 2003/sooakim/app/src/main/java/io/github/sooakim/ui/login/SALoginActivity.kt
>          startActivity(Intent(application, SAMovieSearchActivity::class.java))
7b0d604

2020-03-10 05:11 UTC, sabgilhun approved these changes
굿

2020-03-10 05:15 UTC, Nanamare approved these changes

2020-03-10 05:31 UTC, Hoyuo approved these changes
코드 작성을 잘 하셔서 저도 공부가 많이 되었습니다

2020-03-10 05:32 UTC, ddaeyeonkim approved these changes
LGTM 👍👍👍

2020-03-10 11:13 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋
많은 분들 고생하셨습니다

2020-03-10 11:13 UTC, merged