HW-2 Using repository & models
sjjeong/GoogryAndroidArchitecutreStudy pull request #526
Opened 2020-03-10 15:00 UTC by kangraemin

코드 정리 / 패키지 정리가 엉망인것 같네요 ... 
피드백 주시면 고치겠습니다

2020-03-10 15:47 UTC, sooakim requested changes

2020-03-10 15:47 UTC, sooakim commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/MainActivity.kt
> +        compositeDisposable.add(whenSearchFinished)
이거는 약간 위험해 보이는 코드인데요.
만약에 search함수가 이전에 호출되어서 네트워크 요청이 진행중인 상태에서 한 번더 search가 일어나는 경우
1. 나중에 호출한 search가 이전에 호출한 search보다 일찍 끝나는 경우 -> 이전 검색어로 리스트가 덮어써짐
2. 그 외의 경우 최신 검색에 대한 이벤트만 필요한데도 이전 검색에 대한 이벤트가 계속 실행됨
이런 문제가 발생해요.

해결 방법으로는
1. search전에 이전에 실행한 Single이벤트를 dispose시키고 작업한다.
2. 클릭 이벤트를 받아서 switchMap operator로 네트워크 이벤트로 변환한다. (switchMap 연산자는 새로운 이벤트가 들어오면 이전 이벤트를 dispose시켜줘요)

2020-03-10 15:47 UTC, sooakim commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/adapter/SearchResultAdapter.kt
> +    private var data = ArrayList<MovieDetail>()
아래에서 매번 새로운 객체를 넣어주고 있기때문에 초기화 할 때 생성된 리스트는 사용되지 않고 GC돼요.
var -> val로 바꿔주세요.

2020-03-10 15:47 UTC, sooakim commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/adapter/SearchResultAdapter.kt
> +        this.data = data
```suggestion
        this.data.clear()
        this.data.addAll(data)
```
이렇게 해주면 매번 새로운 리스트를 할당하지 않을 수 있어요.

2020-03-10 15:47 UTC, sooakim commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/AppDatabase.kt
> +        }
lock에 synchronized를 거는 이유가 있나요?

2020-03-10 15:47 UTC, sooakim commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/MovieSearchRepository.kt
> +    private val movieData = BehaviorSubject.create<Movies>()
Repository는 다른 View에서도 재사용이 가능한 클래스인데
movieData를 한 번 생성해서 재사용하면 
dispose된 이후로 emit이 안돼요.

그리고 Subject의 대표적인 오용 사례에 해당하는 것 같아요.
https://hyperconnect.github.io/2019/11/18/common-misuse-subject.html

2020-03-10 15:47 UTC, sooakim commented on 2003/kangraemin/app/build.gradle
> +    implementation "androidx.room:room-guava:$room_version"
guava가 프로젝트에서 사용되었나요? 불필요한 디펜던시 같아요.

2020-03-10 15:47 UTC, sooakim commented on 2003/kangraemin/app/build.gradle
> +    kapt "android.arch.persistence.room:compiler:$room_version"
위에가 androidx버전이고 아래는 레거시 버전이에요. 결론적으로 같은걸 두 번 선언했어요.

2020-03-10 15:47 UTC, sooakim commented on 2003/kangraemin/app/build.gradle
> +    // For Kotlin use kapt instead of annotationProcessor
For Kotlin use kapt instead of annotationProcessor
-> 코틀린에서는 어노테이션 프로세서 대신 kapt를 사용하세요.
밑에 kapt로 선언한 것과 중복되네요.

2020-03-10 15:47 UTC, sooakim commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/MovieSearchRepository.kt
> +            }, { movieData.onError(it) })
1. getAll은 Flowable이라 db에 변경사항이 있을 때마다 emit될거에요.
2. dispose해주지 않으면 메모리릭이 발생해요.

2020-03-10 15:47 UTC, sooakim commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/MovieSearchRepository.kt
> +            .observeOn(AndroidSchedulers.mainThread())
Repository는 View를 몰라야해요.
mainThread로 변경되는 작업은 View에서 해주세요.

2020-03-10 15:47 UTC, sooakim commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/MovieSearchRepository.kt
> +                localDataItemsMovieSearch
map이라는 함수로 간단하게 바꿔줄 수 있어요.
또 다른 모델로 Mapping하는 로직을 별도의 함수로 빼는게 보기 좋을 것 같아요.

2020-03-10 15:47 UTC, sooakim commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/MovieSearchRepository.kt
> +            MovieImpl()
dao는 싱글톤으로 작성하셨는데 MovieImpl는 매번 생성을 하고 있네요. 
한 번만 생성하고 재사용하는게 좋을 것 같아요.

2020-03-10 15:47 UTC, sooakim commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/MovieSearchRepository.kt
> +                .observeOn(Schedulers.io())
subscribeOn을 해서 observeOn이 의미가 없어요.

2020-03-10 15:47 UTC, sooakim commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/MovieSearchRepository.kt
> +                    itemsMovieSearch
마찬가지에요. 그리고 db에 insert하는 작업은 비동기에요.

2020-03-10 15:47 UTC, sooakim commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/MovieSearchRepository.kt
> +                .observeOn(AndroidSchedulers.mainThread())
마찬가지에요.

2020-03-10 15:47 UTC, sooakim commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/MovieSearchRepository.kt
> +                }, { movieData.onError(it) })
역시 메모리릭이 발생할 수 있는 코드에요.

2020-03-10 15:47 UTC, sooakim commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/local/datadao/MovieDao.kt
> +    fun getAll(): Flowable<List<Movie>>
한 번만 쿼리하고 싶으시면 Single, Maybe, Completable을 사용해야해요.

2020-03-10 15:47 UTC, sooakim commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/local/datadao/UserDao.kt
> +    fun findByUserId(userId: String): User
user_name을 userId랑 비교하는데 네이밍이 잘 못 된 것 같아요.
+ 이거 작동하나요? << 안될 것 같아서 적는 거에요.

2020-03-10 15:47 UTC, sooakim commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/local/datamodel/MovieModel.kt
> +    @ColumnInfo(name = "pub_data") var pubDate: String
var -> val

2020-03-10 15:47 UTC, sooakim commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/local/datamodel/MovieModel.kt
> +    var idx: Int = 0
얘만 따로 선언한 이유가 있나요?

2020-03-10 15:47 UTC, sooakim commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/local/datamodel/UserModel.kt
> +    var idx: Int = 0
마찬가지에요.

2020-03-10 15:47 UTC, sooakim commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/local/datamodel/UserModel.kt
> +    @ColumnInfo(name = "user_name") val userName: String
Model에서 LoginActivity에 접근할 필요는 없을 것 같아요.

2020-03-10 15:47 UTC, sooakim commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/remote/datadao/MovieImpl.kt
> +            .create(MovieInterface::class.java)
Retrofit과 MovieInterface를 매번 생성하고 있어요.

2020-03-10 15:47 UTC, sooakim commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/remote/datadao/MovieImpl.kt
> +}
인터페이스 사용방법을 잘 못 이해하신 것 같아요.

2020-03-10 15:55 UTC, sooakim requested changes

2020-03-10 15:55 UTC, sooakim commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/local/datadao/UserDao.kt
> +interface UserDao {
userDao는 사용이 안되고 있는 것 같아요.

2020-03-11 06:28 UTC, mtjin requested changes

2020-03-11 06:28 UTC, mtjin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/MainActivity.kt
> -                            adapter.data = responseMovieSearch.items
81라인은 setData() 인데 여기는. data로 여서 통일하시면 좋을 것 같습니다.

2020-03-11 06:28 UTC, mtjin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/MainActivity.kt
> -                            adapter.data = responseMovieSearch.items
81라인에서는 setData()를 사용하시는데 통일하시면 좋을 것 같습니다.

2020-03-11 06:28 UTC, mtjin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/MainActivity.kt
> -                            adapter.notifyDataSetChanged()
정석준 스터디장님께서 어댑터 setData() 함수안에서 notifyDataSetChanged() 하라고 전 리뷰받은적이 있는데 참고하시면 될 것 같습니다.

2020-03-11 06:45 UTC, sooakim commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/MainActivity.kt
> -                            adapter.data = responseMovieSearch.items
@mtjin 참고로 -붉은색으로 표시된 부분은 삭제된 코드, +초록색으로 표시된 부분은 추가된 코드에요.

2020-03-11 06:45 UTC, sooakim commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/MainActivity.kt
> -                            adapter.data = responseMovieSearch.items
@mtjin 참고로 -붉은색으로 표시된 부분은 삭제된 코드, +초록색으로 표시된 부분은 추가된 코드에요.

2020-03-11 06:47 UTC, sooakim commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/MainActivity.kt
> -                            adapter.data = responseMovieSearch.items
@mtjin 참고로 -붉은색으로 표시된 부분은 삭제된 코드, +초록색으로 표시된 부분은 추가된 코드에요.

2020-03-11 07:38 UTC, mtjin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/MainActivity.kt
> -                            adapter.data = responseMovieSearch.items
@sooakim 
실수했네요

2020-03-11 07:42 UTC, mtjin requested changes

2020-03-11 07:42 UTC, mtjin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/MainActivity.kt
> +                adapter.notifyDataSetChanged()
정석준 스터디장님께서 어댑터 setData() 함수안에서 notifyDataSetChanged() 하라고 전 리뷰받은적이 있는데 참고하시면 될 것 같습니다.

2020-03-12 17:15 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/adapter/SearchResultAdapter.kt
> +    private var data = ArrayList<MovieDetail>()
수정하였습니다.
1dc0229

2020-03-12 17:15 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/adapter/SearchResultAdapter.kt
> +        this.data = data
수정하였습니다.
1dc0229

2020-03-12 17:16 UTC, kangraemin commented on 2003/kangraemin/app/build.gradle
> +    implementation "androidx.room:room-guava:$room_version"
Android Developer에서 그대로 긁어온 뒤 그대로 놔뒀네요 ... 수정하였습니다 
10e0bf2

2020-03-12 17:16 UTC, kangraemin commented on 2003/kangraemin/app/build.gradle
> +    kapt "android.arch.persistence.room:compiler:$room_version"
수정하였습니다 
eb3184a

2020-03-12 17:17 UTC, kangraemin commented on 2003/kangraemin/app/build.gradle
> +    // For Kotlin use kapt instead of annotationProcessor
수정하였습니다
e668dd0

2020-03-12 17:17 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/MainActivity.kt
> +                adapter.notifyDataSetChanged()
수정하였습니다 
cd89def

2020-03-12 17:18 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/local/datamodel/UserModel.kt
> +    @ColumnInfo(name = "user_name") val userName: String
수정하였습니다
9c75b63

2020-03-12 17:19 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/local/datamodel/MovieModel.kt
> +    @ColumnInfo(name = "pub_data") var pubDate: String
수정하였습니다
21f785c

2020-03-12 17:20 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/MovieSearchRepository.kt
> +            .observeOn(AndroidSchedulers.mainThread())
수정하였습니다 
1e9a2ae

2020-03-12 17:20 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/MovieSearchRepository.kt
> +                .observeOn(Schedulers.io())
수정하였습니다
a63a943

2020-03-12 17:21 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/MovieSearchRepository.kt
> +                localDataItemsMovieSearch
수정하였습니다
c7f55aa

2020-03-12 17:24 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/MovieSearchRepository.kt
> +                    itemsMovieSearch
수정하였습니다 
55a5dd1

2020-03-12 17:26 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/local/datamodel/MovieModel.kt
> +    var idx: Int = 0
매핑 해 줄때 생성자에 primaryKey를 넣어주는것이 불편하다 느껴서 따로 뺐었습니다. 
room이 처음이라 안익숙하네요 ... 구체적인 커멘트 감사합니다 
수정하였습니다 
c5f29ba

2020-03-12 17:27 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/local/datamodel/UserModel.kt
> +    var idx: Int = 0
수정하였습니다
c5f29ba

2020-03-12 17:28 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/local/datamodel/UserModel.kt
> +    @ColumnInfo(name = "user_name") val userName: String
수정하였습니다
9c75b63

2020-03-12 17:28 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/MovieSearchRepository.kt
> +                .observeOn(AndroidSchedulers.mainThread())
수정하였습니다 
2cb58a4

2020-03-12 17:30 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/local/datadao/UserDao.kt
> +    fun findByUserId(userId: String): User
수정하였습니다 
7824451

2020-03-12 17:34 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/local/datadao/MovieDao.kt
> +    fun getAll(): Flowable<List<Movie>>
수정하였습니다
4323a87

2020-03-12 17:36 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/MovieSearchRepository.kt
> +    private val movieData = BehaviorSubject.create<Movies>()
수정하였습니다 
링크 정말 감사합니다 !!
ee5e3f2

2020-03-12 17:40 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/local/datadao/UserDao.kt
> +interface UserDao {
자동 로그인 정보를 SharedPreference로 저장하던것을 모델로 바꿔보고자 했는데, 영화 데이터 모델 변경만으로도 모르는게 너무 많아서 일단 넘겼었습니다. 차후에 사용하도록 하겠습니다.

2020-03-12 17:44 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/AppDatabase.kt
> +        }
룸 db를 싱글톤으로 만들어야 한다는 디벨로퍼 글을 읽고 싱글톤 구현 방법이 뭔지 몰라 검색 후 긁어온 코드 입니다. ( 출처 : https://stackoverflow.com/a/56703221 )
생각 없이 검색 후 긁어온것이라 이유는 잘 모르겠네요 ..

2020-03-12 17:46 UTC, kangraemin commented
아직 수정하지 못한부분 금요일 저녁에 모두 마무리 지을 수 있도록 하겠습니다.
중간에 모르는 것이 너무 많아 늦게 올린점 죄송합니다.

2020-03-12 17:57 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/MovieSearchRepository.kt
> +            }, { movieData.onError(it) })
혹시 Flowable.create로 바뀌면서 해당 이슈가 해결괴었을까요 ... ? 아직은 잘 모르겠네요...
4323a87
ee5e3f2

2020-03-13 01:27 UTC, sooakim commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/AppDatabase.kt
> +        }
@kangraemin 
synchorized는 여러개의 쓰레드가 동시에 접근할 때 lock을 걸어서 한 번에 한 개의 쓰레드만 접근할 수 있도록 해줘요. 파라미터로 넘겨주는 객체에 lock을 거는데 any에 lock을 거는건 의미가 없을 것 같아요.

2020-03-13 13:34 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/MainActivity.kt
> +        compositeDisposable.add(whenSearchFinished)
좋은 방법 제안 정말 감사합니다 !!
430c8ba

2020-03-13 13:34 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/AppDatabase.kt
> +        }
감사합니다 클래스에 락을 걸도록 수정하였습니다 
7d47151

2020-03-13 13:35 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/MovieSearchRepository.kt
> +            MovieImpl()
수정하였습니다
e1a52b2

2020-03-13 13:37 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/remote/datadao/MovieImpl.kt
> +            .create(MovieInterface::class.java)
수정하였습니다 
5b9c4c5

2020-03-13 13:38 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/remote/datadao/MovieImpl.kt
> +}
이제서야 감이 오네요 ... 감사합니다 !! 수정하였습니다 
b14d282

2020-03-13 13:45 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/MovieSearchRepository.kt
> +            }, { movieData.onError(it) })
제생각엔 ee5e3f2 커밋 ( Subject -> Flowable.create ) 로 바꾸어 뷰단에서 dispose 해줌으로써 해결 된 것 같습니다

2020-03-13 13:46 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/MovieSearchRepository.kt
> +                }, { movieData.onError(it) })
제생각엔 ee5e3f2 커밋 ( Subject -> Flowable.create ) 로 바꾸어 뷰단에서 dispose 해줌으로써 해결 된 것 같습니다

2020-03-13 14:20 UTC, sooakim commented
추가적으로 수정하신 내용쭉 봤는데 여전히 RxJava관련한 문제가 많이 보여요.
일단은 최대한 리뷰로 달아드릴려고 하는데 이렇게되면 스터디 전까지 리뷰가 끝나지 않을 것 같아요.
이번 스터디의 목적은 RxJava가 아니라 아키텍처 패턴을 구현하는 것이니 무리하게 사용하기 보단 Model구현에 집중하시는게 좋아보여요. @kangraemin

2020-03-13 14:39 UTC, sooakim requested changes

2020-03-13 14:39 UTC, sooakim commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/MainActivity.kt
> +                Flowable.just("init"),
초기값을 전달하고 싶으시다면
startWith를 사용하세요.

2020-03-13 14:39 UTC, sooakim commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/MainActivity.kt
> +                it
emit될 때마다 실행하고 싶은 구문이 있다면 doOnNext를 사용하세요.
그리고 네트워크 체크를 실행시마다 하는게 필요한지 의문이네요.

2020-03-13 14:39 UTC, sooakim commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/MainActivity.kt
> +                    search(et_search.text.toString())
이부분은 map에서 처리할 수 있어요.
```kotiln
   .map{
      et_search.text.toString()
   }
```

2020-03-13 14:39 UTC, sooakim commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/AppDatabase.kt
> +            return db!!
null체크를 두 번하고 있네요.

2020-03-13 14:39 UTC, sooakim commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/MovieSearchRepository.kt
> +                        }
메모리릭의 위험이 있어요. 어떤 작업을 실행 후 다음 작업을 실행하게하려면 flatMap같은 연산자를 사용해야해요.

2020-03-13 14:39 UTC, sooakim commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/MovieSearchRepository.kt
> +                    })
메모리릭의 위험이 있어요. Flowable.defer구문을 Flowable.create로 랩핑할 필요가 없어요.

2020-03-13 14:39 UTC, sooakim commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/MovieSearchRepository.kt
> +    }
[Kotlin Map](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/map.html)
제가 말한 map함수는 이거였어요.

2020-03-13 14:39 UTC, sooakim commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/remote/datadao/MovieDataSource.kt
> +interface MovieDataSource {
LocalDataSource인지 RemoteDataSource인지 구분이 안되네요. 이름을 수정해주세요.

2020-03-13 14:39 UTC, sooakim commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/remote/datadao/MovieImpl.kt
> +    }
전에 리뷰했을 때는 RemoteDataSource내의 함수에서 매번 create를 하고 계셔서 리뷰를 남겼던 건데

제가 원했던 것은 
1. RemoteDataSource를 init할 때 최초 1번만 create하거나 
2. application클래스나 activity클래스에서 create해서 RemoteDataSource의 생성자로 넘겨주는 방식 
이었어요.

2020-03-13 14:57 UTC, mtjin approved these changes
rxjava는 제가 몰라서 제외하고 다른 부분은 이상이 없는 것 같아 approve 했습니다.

2020-03-13 14:57 UTC, mtjin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/adapter/SearchResultAdapter.kt
>          holder.itemView.tv_castings.text = result.actor
이번에 추가된 코드는 아니지만 with()로 코드를 좀 생략할 수 있을 것 같습니다. (취향차이라 수정안하셔도 될 것 같긴해요.)

2020-03-13 15:04 UTC, mtjin requested changes

2020-03-13 15:04 UTC, mtjin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/remote/datadao/MovieImpl.kt
> +    private val getMovieApi: MovieInterface
getMovieApi 변수명보다 movieInterface나 movieApi가 낫지 않을까 싶습니다.

2020-03-13 18:23 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/remote/datadao/MovieImpl.kt
> +    private val getMovieApi: MovieInterface
수정했습니다 !
15adc5a

2020-03-13 18:23 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/adapter/SearchResultAdapter.kt
>          holder.itemView.tv_castings.text = result.actor
수정했습니다 
e5ea4d3

2020-03-13 18:24 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/local/datadao/UserDao.kt
> +interface UserDao {
UserDao -> AuthDao로 변경하여 자동로그인 여부를 SharedPreference에 담아 검사하던 것을 모델 / 저장소 패턴으로 변경하였습니다 
ac1c59c

2020-03-13 18:25 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/local/datadao/UserDao.kt
> +    fun findByUserId(userId: String): User
확인결과 작동되지 않았습니다 전혀 다른곳에서 조회하는 쿼리문이었어요 ..

2020-03-13 18:25 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/remote/datadao/MovieDataSource.kt
> +interface MovieDataSource {
수정했습니다
6a86fc0

2020-03-13 18:26 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/AppDatabase.kt
> +            return db!!
수정했습니다
f381f5a

2020-03-13 18:26 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/MainActivity.kt
> +                    search(et_search.text.toString())
수정했습니다
1a228c3

2020-03-13 18:27 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/MainActivity.kt
> +                it
수정했습니다 네트워크 체크 부분은 좀 더 생각해보겠습니다 
42b468e

2020-03-14 02:26 UTC, mtjin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/adapter/SearchResultAdapter.kt
>          holder.itemView.tv_castings.text = result.actor
@kangraemin 
onBindViewHolder() 안 쪽 말씀드린거였는데 해당 라인도 바꿀 수 있었네요

2020-03-14 04:37 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/adapter/SearchResultAdapter.kt
>          holder.itemView.tv_castings.text = result.actor
수정하였습니다
e93a6cb

2020-03-14 04:37 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/MovieSearchRepository.kt
> +    }
수정하였습니다
da93fcc

2020-03-14 04:38 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/remote/datadao/MovieImpl.kt
> +    }
수정했습니다
07ca929

2020-03-14 06:16 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/MovieSearchRepository.kt
> +                    })
수정했습니다
768ce85

2020-03-14 06:16 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/MainActivity.kt
> +                Flowable.just("init"),
수정했습니다
3c5833f

2020-03-14 06:17 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/MovieSearchRepository.kt
> +                        }
수정했습니다
4f6c783

2020-03-14 07:41 UTC, sooakim requested changes

2020-03-14 07:41 UTC, sooakim commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/MainActivity.kt
> +            .startWith(search(""))
startWith를 switchMap뒤에 놓으면 switchMap을 쓰는 의미가 없어요.
```suggestion
            .map { et_search.text.toString() }
             .startWith("")
            .switchMap { search(it) }
```

2020-03-14 07:41 UTC, sooakim commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/AppDatabase.kt
> +            return db!!
synchronized블록 밖에서 null체크를 하면 의미가 없어요. 
두 가지 방법이 있어요.
1. @Synchrozied 어노테이션을 사용해 메소드자체를 synchronized로 만든다.
2. synchronized내부에서 널 체크를 한다.

2020-03-14 07:41 UTC, sooakim commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/AuthRepository.kt
> +    }
모든 메소드를 호출할 때마다 context를 인자로 받고 있네요.
애초에 AuthRepository의 생성자에서 받으면 매번 인자로 넣어줄 필요가 없어요.

2020-03-14 07:41 UTC, sooakim commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/AuthRepository.kt
> +                val db = AppDatabase.getInstance(context = context)
얘도 마찬가지인데 매번 getInstance로 데이터베이스를 가져올 필요 없이
AuthRepository의 생성자로 받은 context를 통해 init구문에서 한번만 getInstance하거나
아예 AppDatabase.getInstance()를 외부에서 실행한 뒤 AuthRepository의 생성자로 넣어주면 해결이 돼요.

2020-03-14 07:41 UTC, sooakim commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/AuthRepository.kt
> +                    }, { emitter.onError(it) })
계속 반복되고 있는 문제인데 rx이벤트를 subscribe해준 뒤 dispose해주지 않으면 메모리릭이 발생해요.
그리고 이 경우에는 굳이 여기서 subscribe할 필요가 없어요.
Flowable.create로 랩핑하지 않아도 실행에 문제가 없어요.

Single을 Flowable로 바꾸고 싶다면 
```suggestion
                    .toFlowable(BackpressureStrategy.BUFFER)
```
와 같은 함수를 이용해야해요.

2020-03-14 07:41 UTC, sooakim commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/AuthRepository.kt
> +            }
```kotlin
   toCompletable()
```

2020-03-14 07:41 UTC, sooakim commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/AuthRepository.kt
> +        }
이것도 생성자로 넣어주는 걸 추천하는데 일단 지금으로선 실행에 문제가 없으니 넘어갈게요.

2020-03-14 07:41 UTC, sooakim commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/MovieSearchRepository.kt
> +    val remoteMovieDatasource: RemoteMovieDataSource
localDataSource가 없어요.

2020-03-14 07:41 UTC, sooakim commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/MovieSearchRepository.kt
> +    }
마찬가지로 context를 메소드에서 인자로 받을 필요가 없어요.
MovieSearchRepository 생성자 <- LocalDataSource 생성자 <- Database.getInstance(context)
이렇게 하면 Repository에서 굳이 context에 의존하지 않아도 돼요.

2020-03-14 07:41 UTC, sooakim commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/MovieSearchRepository.kt
> +                        db.movieDao().deleteAll()
```suggestion
                        db.movieDao().deleteAll()
                           .subscribeOn(Schedulers.io())
```

2020-03-14 07:41 UTC, sooakim commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/MovieSearchRepository.kt
> +                            .flatMapCompletable { db.movieDao().insertMovies(it) }
```suggestion
                            .flatMapCompletable { 
                               db.movieDao()
                                  .insertMovies(it)
                                  .subscribeOn(Schedulers.io())
                            }
```

2020-03-14 07:41 UTC, sooakim commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/local/datadao/AuthDao.kt
> +    fun deleteAuth(): Completable
대소문자는 일관성 있게 사용해주세요.
DELETE와 from은 모두 SQL 예약어 인데 상이하게 사용되고 있고,
테이블명은 파스칼케이스네요.

2020-03-14 07:41 UTC, sooakim commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/local/datadao/AuthDataSource.kt
> +}
```suggestion
interface AuthLocalDataSource {
    fun getAuth(): Single<Auth>
    fun addAuth(auth: Auth): Completable
    fun deleteAuth(): Completable
}
```

2020-03-14 07:41 UTC, sooakim commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/local/datadao/AuthImpl.kt
> +) : AuthDataSource {
```suggestion
class AuthLocalDataSourceImpl(
    private val db: AppDatabase
) : AuthLocalDataSource {
```

2020-03-14 07:41 UTC, sooakim commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/local/datadao/AuthImpl.kt
> +    }
여기도 매번 authDao()를 호출 해줄 필요 없이 
생성자에서 아예 AuthDao를 받으면 반복 코드가 줄겠죠?

2020-03-14 07:41 UTC, sooakim commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/local/datadao/MovieDao.kt
> +    fun deleteAll(): Completable
여기도 SQL예약어와 테이블 명칭이 일관성 없이 사용되고 있네요.

2020-03-14 07:41 UTC, sooakim commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/remote/datadao/MovieImpl.kt
> +) : RemoteMovieDataSource {
네이밍은 일관성 있게 다른 클래스, 인터페이스와 구분할 수 있도록 명확히 해주세요.
```suggestion
class MovieRemoteDataSourceImpl(
    private val movieApi: MovieApi
) : MovieRemoteDataSource {
```

2020-03-14 07:41 UTC, sooakim commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/remote/datadao/MovieInterface.kt
> +    ): Flowable<Movies>
네트워크 작업은 1회성이기때문에 Single을 쓰는걸 추천하지만 Flowable을 써도 당장 실행에는 문제가 없기때문에 이건 넘어가셔도 돼요.

2020-03-14 07:41 UTC, sooakim commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/remote/datadao/RemoteMovieDataSource.kt
> +interface RemoteMovieDataSource {
```suggestion
interface MovieRemoteDataSource {
```

2020-03-14 09:37 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/MainActivity.kt
> +            .startWith(search(""))
수정하였습니다
7b806d9

2020-03-14 09:37 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/AppDatabase.kt
> +            return db!!
수정하였습니다
e2a2f0c

2020-03-14 09:37 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/AuthRepository.kt
> +    }
수정하였습니다
2032c72

2020-03-14 09:38 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/AuthRepository.kt
> +                val db = AppDatabase.getInstance(context = context)
수정하였습니다
2032c72

2020-03-14 09:38 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/AuthRepository.kt
> +                    }, { emitter.onError(it) })
수정하였습니다
2032c72

2020-03-14 09:39 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/AuthRepository.kt
> +            }
수정하였습니다
2032c72

2020-03-14 09:39 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/AuthRepository.kt
> +        }
수정하였습니다
2032c72

2020-03-14 09:39 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/MovieSearchRepository.kt
> +    val remoteMovieDatasource: RemoteMovieDataSource
수정하였습니다
12a9354

2020-03-14 09:41 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/MovieSearchRepository.kt
> +    }
수정하였습니다
12a9354

2020-03-14 09:41 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/MovieSearchRepository.kt
> +                        db.movieDao().deleteAll()
수정하였습니다 
b40aa6a

2020-03-14 09:41 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/MovieSearchRepository.kt
> +                            .flatMapCompletable { db.movieDao().insertMovies(it) }
수정하였습니다
bee28ee

2020-03-14 09:42 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/local/datadao/AuthDao.kt
> +    fun deleteAuth(): Completable
수정하였습니다
0b9b0ac

2020-03-14 09:42 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/local/datadao/MovieDao.kt
> +    fun deleteAll(): Completable
수정하였습니다
0b9b0ac

2020-03-14 09:42 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/local/datadao/AuthDataSource.kt
> +}
수정하였습니다
35869b1

2020-03-14 09:43 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/local/datadao/AuthImpl.kt
> +) : AuthDataSource {
수정하였습니다 
ebe8b87

2020-03-14 09:43 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/local/datadao/AuthImpl.kt
> +    }
수정하였습니다 
d87226a

2020-03-14 09:43 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/remote/datadao/RemoteMovieDataSource.kt
> +interface RemoteMovieDataSource {
수정하였습니다 
4e81ab0

2020-03-14 09:44 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/remote/datadao/MovieImpl.kt
> +) : RemoteMovieDataSource {
수정하였습니다 
4e81ab0

2020-03-14 09:46 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/local/datadao/AuthImpl.kt
> +    }
movieDao() 에도 적용 해 주었습니다 
3d6e426

2020-03-14 10:09 UTC, sooakim requested changes

2020-03-14 10:09 UTC, sooakim commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/local/datadao/AuthDao.kt
> +    fun deleteAuth(): Completable
예약어를 대문자로 하기로 결정하셨다면 반대로 테이블 명은 모두 소문자로 바꿔주세요.

2020-03-14 10:10 UTC, sooakim commented
훨씬 나아졌네요. 위에 수정 사항 1개만 수정하시면 approve할게요.

2020-03-14 10:12 UTC, sooakim requested changes

2020-03-14 10:12 UTC, sooakim commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/local/datadao/MovieDao.kt
> +    fun deleteAll(): Completable
여기도요

2020-03-14 10:12 UTC, sooakim commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/local/datadao/LocalMovieImpl.kt
> +) : LocalMovieDataSource {
```suggestion
class LocalMovieDataSourceImpl(
    private val movieDao: MovieDao
) : LocalMovieDataSource {
```

2020-03-14 10:28 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/local/datadao/LocalMovieImpl.kt
> +) : LocalMovieDataSource {
수정하였습니다
f2e7a49

2020-03-14 10:28 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/local/datadao/MovieDao.kt
> +    fun deleteAll(): Completable
수정하였습니다
4c461d1

2020-03-14 10:28 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/local/datadao/AuthDao.kt
> +    fun deleteAuth(): Completable
수정하였습니다
4c461d1

2020-03-14 10:29 UTC, kangraemin commented
정말로 감사합니다 !! 진짜 정말 많이 배웠어요 ...

2020-03-14 10:30 UTC, sooakim approved these changes

2020-03-14 13:19 UTC, sjjeong requested changes

2020-03-14 13:19 UTC, sjjeong commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/LoginActivity.kt
> +
아무것도 하는게 없다면 // no-op 이라는 주석을 추가해서 안하는게 맞다고 명시해주세요

2020-03-14 13:19 UTC, sjjeong commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/adapter/SearchResultAdapter.kt
> +            notifyDataSetChanged()
이건 this.data.apply 내부가 아니여도 됩니다.

2020-03-14 13:19 UTC, sjjeong commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/adapter/SearchResultAdapter.kt
> +        holder.apply {
이건 apply보다 run이나 with를 사용하도록 해주세요

2020-03-14 13:19 UTC, sjjeong commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/remote/datadao/MovieApi.kt
> +    ): Flowable<Movies>
얘는 단건이라서 Flowable보단 Single로 처리해주세요

2020-03-14 13:57 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/model/remote/datadao/MovieApi.kt
> +    ): Flowable<Movies>
수정했습니다
c49b8db

2020-03-14 13:57 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/adapter/SearchResultAdapter.kt
> +        holder.apply {
수정했습니다
010e31e

2020-03-14 13:58 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/adapter/SearchResultAdapter.kt
> +            notifyDataSetChanged()
수정했습니다
6cd51ce

2020-03-14 13:58 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/LoginActivity.kt
> +
수정했습니다
e5c5858

2020-03-14 14:28 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-03-15 04:27 UTC, mtjin approved these changes

2020-03-15 04:27 UTC, merged