2003/byiryu
sjjeong/GoogryAndroidArchitecutreStudy pull request #527
Opened 2020-03-12 03:44 UTC by byiryu

2020-03-12 15:11 UTC, tjdwlsl1021 reviewed
다른 분들 리뷰 참고해서 작성했습니다.

2020-03-12 15:11 UTC, tjdwlsl1021 commented on 2003/byiryu/app/build.gradle
> +    implementation "android.arch.persistence.room:runtime:$roomVersion"
버전명을 따로 빼는게 관리하기에 더 편한건가요?

2020-03-12 15:11 UTC, tjdwlsl1021 commented on 2003/byiryu/app/src/main/java/com/byiryu/study/model/entity/MovieItem.kt
> +@Entity(tableName = "Movie")
SQL명령어가 대문자인데 테이블 명에 대문자를 쓰면 헷갈린다는 리뷰 내용이 있어서 작성했습니다.

2020-03-12 15:11 UTC, tjdwlsl1021 commented on 2003/byiryu/build.gradle
추가로 궁금한점이 있어서 질문 드립니다.
impl, class구조가 없어서, 혹시 이걸 꼭 나눠야하는게 아니고, 선택적인 부분인건가요??

2020-03-12 15:11 UTC, tjdwlsl1021 commented on 2003/byiryu/app/src/main/java/com/byiryu/study/model/Repository.kt
> +    private var localDataSource: LocalDataSource = LocalDataSource(movieDao)
이 부분을 Application객체에 생성해놓고 가져오는게 좋다는 리뷰도 있었는데,
지금 이 소스상에서도 적용되는 얘기인지는 한번 살펴보시면 좋을 것 같습니다.

2020-03-12 23:41 UTC, tjdwlsl1021 reviewed
answer review요청입니다.

2020-03-13 04:14 UTC, byiryu commented on 2003/byiryu/app/build.gradle
> +    implementation "android.arch.persistence.room:runtime:$roomVersion"
retrofit 이든 room이든 같이 써야하는 라이브러리들이 있기 때문에 따로 빼서 관리하는게 좋을것 같습니다.

2020-03-13 04:18 UTC, tjdwlsl1021 commented on 2003/byiryu/app/build.gradle
> +    implementation "android.arch.persistence.room:runtime:$roomVersion"
네 감사합니다.

2020-03-13 04:18 UTC, byiryu commented on 2003/byiryu/build.gradle
음 이부분에서 어떤걸 질문드리는건지 잘 모르겠습니다만
 Repository 부분을 설계하실때 impl과 아닌것을 말씀하시는거 같은데요
제 개인적으로는 어느정도는 선택적이라고 생각합니다. 프로젝트 규모가 적고 함수의 대한 내용이 한곳에만 적용되고 있기 때문에 따로 분리하지는 않았습니다. 규모가 커지고 여러가지 기능이 생긴다면 나누는것이 좋다고 생각합니다.

2020-03-13 04:25 UTC, byiryu commented on 2003/byiryu/app/src/main/java/com/byiryu/study/model/entity/MovieItem.kt
> +@Entity(tableName = "Movie")
수정했습니다

ea3cbad

2020-03-13 04:49 UTC, byiryu commented on 2003/byiryu/app/src/main/java/com/byiryu/study/model/Repository.kt
> +    private var localDataSource: LocalDataSource = LocalDataSource(movieDao)
수정했습니다

bf40c2f

2020-03-13 05:05 UTC, tjdwlsl1021 commented on 2003/byiryu/build.gradle
네 설명 감사합니다^^

2020-03-13 05:06 UTC, tjdwlsl1021 approved these changes
Approve입니다.

2020-03-13 13:43 UTC, sjjeong requested changes

2020-03-13 13:43 UTC, sjjeong commented on 2003/byiryu/app/src/main/java/com/byiryu/study/model/Repository.kt
> +    }
이 작업들도 local에 저장하는 것이기 때문에 LocalDataSource로 이동하면됩니다.
pref를 Local로 이동을 하고 그에 따라서 반영 해주면 됩니다.

2020-03-13 13:43 UTC, sjjeong commented on 2003/byiryu/app/src/main/java/com/byiryu/study/model/local/LocalDataSource.kt
> +            }
함수명은 saveMovies라서 저장 성공인 것 같지만 실제로 리턴되는 Completable은 삭제에 대한 것 입니다.
doOnComplete대신 andThen을 사용해주세요

2020-03-13 13:43 UTC, sjjeong commented on 2003/byiryu/app/src/main/java/com/byiryu/study/model/local/pref/AppPreference.kt
> +        const val PREF_AUTO_LOGIN = "A1B2-C3D4-E5F6-G7H8"
key의 값은 의미있는 값으로 해주세요

2020-03-13 13:43 UTC, sjjeong commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/login/LoginActivity.kt
> +    private var pw: String? = null
밖으로 빼서 쓰지 않는게 좋아보입니다.

2020-03-13 13:43 UTC, sjjeong commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/login/LoginActivity.kt
> +                        showLoading()
hide는 doAfterTerminate로 처리해주세요

2020-03-13 13:43 UTC, sjjeong commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/main/MainActivity.kt
> +                        hideLoading()
성공 케이스만 hide하면 나중에 error생기면 hide를 하지 못합니다.

2020-03-14 07:38 UTC, byiryu commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/main/MainActivity.kt
> +                        hideLoading()
수정했습니다. 
예외처리는 항상 못하네요 ..

1b59380

2020-03-14 07:38 UTC, byiryu commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/login/LoginActivity.kt
> +                        showLoading()
수정했습니다

d25422c

2020-03-14 07:39 UTC, byiryu commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/login/LoginActivity.kt
> +    private var pw: String? = null
수정했습니다. 
몇번 들었던 내용인거 같은데 왜 그런지 설명 한번만 더 부탁드립니다


1c863be

2020-03-14 07:39 UTC, byiryu commented on 2003/byiryu/app/src/main/java/com/byiryu/study/model/local/pref/AppPreference.kt
> +        const val PREF_AUTO_LOGIN = "A1B2-C3D4-E5F6-G7H8"
수정했습니다.
f8682b2

2020-03-14 07:40 UTC, byiryu commented on 2003/byiryu/app/src/main/java/com/byiryu/study/model/local/LocalDataSource.kt
> +            }
수정했습니다

524b904

2020-03-14 07:40 UTC, byiryu commented on 2003/byiryu/app/src/main/java/com/byiryu/study/model/Repository.kt
> +    }
수정했습니다

5eddb58

2020-03-14 12:34 UTC, sjjeong commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/login/LoginActivity.kt
> +    private var pw: String? = null
불필요하게 밖에 들고 있으면 `이걸 왜 밖에 선언했을까` 라는 생각을 가지고 코드를 볼 수 밖에 없게 됩니다.

2020-03-14 12:35 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-03-14 12:40 UTC, merged