2003/tjdwlsl1021
sjjeong/GoogryAndroidArchitecutreStudy pull request #528
Opened 2020-03-13 11:03 UTC by tjdwlsl1021

review요청드립니다.

2020-03-13 17:17 UTC, tjdwlsl1021 reviewed
경재님.
제가 label을 잘못 달았네요.
경재님에게 소스리뷰 요청드립니다.

2020-03-14 07:21 UTC, byiryu reviewed
반영부탁드립니다.

2020-03-14 07:21 UTC, byiryu commented on 2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/activity/SearchMovieActivity.kt
> +
Repository에서 각 데이터소스를 통해 데이터를 뷰에 뿌려주는 로직이라면 
뷰는 각 데이터 소스를 알필요가 없다고 생각합니다. 데이터 소스 부분은 세팅하는 부분은 Repository에서 해주시는게 좋은거 같네요

2020-03-14 07:21 UTC, byiryu commented on 2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/activity/SearchMovieActivity.kt
>      }
따로 함수를 만드신 이유라도 있을까요?

2020-03-14 07:21 UTC, byiryu commented on 2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/data/repository/MovieRepositoryImpl.kt
> +}
코루틴에 대해선 저도 잘 몰라서 따로 해드릴수가 없을것 같네요 ㅠ

2020-03-14 08:25 UTC, tjdwlsl1021 reviewed
질문 및 수정요청 내용 반영했습니다.

2020-03-14 08:25 UTC, tjdwlsl1021 commented on 2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/activity/SearchMovieActivity.kt
> +
4cd4fd981e40d1946a3f626c61098ad7070d038c
수정했습니다.

2020-03-14 08:25 UTC, tjdwlsl1021 commented on 2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/activity/SearchMovieActivity.kt
>      }
getMovieList함수는 패턴 적용하기전에 기존소스가 길어서 따로 뺀거고,
mMovieRepository.getMovieList함수는 지난수업 때 Impl, class로 나눠서 작업하는거 보고
계산하는 부분소스와, 결과값만 불러오는 부분을 나눌려는 이유로 이해하고 따로 뺐습니다.

2020-03-14 08:25 UTC, tjdwlsl1021 commented on 2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/data/repository/MovieRepositoryImpl.kt
> +}
네 저도 runBlocking을 사용하면 메인스레드가 함수 내부작업이 완료되면 다시실행한다 정도로만 알고 있습니다

2020-03-14 09:56 UTC, byiryu approved these changes
고생하셨습니다

2020-03-14 12:08 UTC, sjjeong requested changes

2020-03-14 12:08 UTC, sjjeong commented on 2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/activity/SearchMovieActivity.kt
> +    private lateinit var mMovieRepositoryDataSet: MovieRepositoryDataSet
m prefix제거해주세요

2020-03-14 12:08 UTC, sjjeong commented on 2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/adapter/SearchMovieAdapter.kt
> +        Glide.with(movieViewHolder.iv_thumbnail).load(item.image).into(movieViewHolder.iv_thumbnail)
함수 체이닝이 길어지면 가독성이 떨어지게 됩니다.
가독성을 높여주기 위해서 load함수부터 한줄씩 써주세요
```kotlin
Glide.with(movieViewHolder.iv_thumbnail)
    .load(item.image)
    .into(movieViewHolder.iv_thumbnail)
```

2020-03-14 12:08 UTC, sjjeong commented on 2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/data/local/MovieDatabase.kt
> +        private var mInstance: MovieDatabase? = null
여기도 m 제거 해주세요

2020-03-14 12:08 UTC, sjjeong commented on 2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/data/repository/MovieRepositoryDataSet.kt
> +    private lateinit var MMovieDao: MovieDao
여기도 m 제거 해주세요

2020-03-14 12:08 UTC, sjjeong commented on 2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/data/remote/MovieRemoteDataSourceImpl.kt
> +                    }
result가 null인 케이스도 처리해주세요

2020-03-14 12:08 UTC, sjjeong commented on 2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/data/repository/MovieRepositoryImpl.kt
> +}
runBlocking을 하면 메인스레드가 멈추게 됩니다.
이런용도로 사용하신다면 코루틴을 사용하는 의미가 없습니다.

코루틴 제거해주시고 RoomDatabase 만들때 이걸 넣어주세요 
https://developer.android.com/reference/androidx/room/RoomDatabase.Builder#allowMainThreadQueries()

2020-03-14 12:08 UTC, sjjeong commented on 2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/model/Item_SearchMovie.kt
> +data class Item_SearchMovie (
사용되지 않는 클래스네요
제거해주세요

2020-03-14 13:03 UTC, tjdwlsl1021 commented on 2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/data/repository/MovieRepositoryImpl.kt
> +}
f39534b
수정했습니다.

2020-03-14 13:05 UTC, tjdwlsl1021 commented on 2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/activity/SearchMovieActivity.kt
> +    private lateinit var mMovieRepositoryDataSet: MovieRepositoryDataSet
64a19c7
수정했습니다.

2020-03-14 13:05 UTC, tjdwlsl1021 commented on 2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/adapter/SearchMovieAdapter.kt
> +        Glide.with(movieViewHolder.iv_thumbnail).load(item.image).into(movieViewHolder.iv_thumbnail)
070d375
수정했습니다.

2020-03-14 13:05 UTC, tjdwlsl1021 commented on 2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/data/local/MovieDatabase.kt
> +        private var mInstance: MovieDatabase? = null
a893632
수정했습니다.

2020-03-14 13:06 UTC, tjdwlsl1021 commented on 2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/data/repository/MovieRepositoryDataSet.kt
> +    private lateinit var MMovieDao: MovieDao
52b7b0b
수정했습니다.

2020-03-14 13:06 UTC, tjdwlsl1021 commented on 2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/data/remote/MovieRemoteDataSourceImpl.kt
> +                    }
c340782
수정했습니다.

2020-03-14 13:06 UTC, tjdwlsl1021 commented on 2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/model/Item_SearchMovie.kt
> +data class Item_SearchMovie (
a527716
수정했습니다.

2020-03-14 13:08 UTC, tjdwlsl1021 reviewed
수정요청내용 반영했습니다.

2020-03-14 13:21 UTC, sjjeong commented
> 수정요청내용 반영했습니다.

@tjdwlsl1021 반영했다면 Review Needed 추가해주세요

2020-03-14 13:29 UTC, tjdwlsl1021 commented
> > 수정요청내용 반영했습니다.
> 
> @tjdwlsl1021 반영했다면 Review Needed 추가해주세요

>>@sjjeong 네 추가했습니다.

2020-03-14 14:44 UTC, sjjeong requested changes
m prefix를 제거하셨다면 변수명은 camelCase로 변경해야 합니다.

2020-03-14 14:50 UTC, tjdwlsl1021 commented
> m prefix를 제거하셨다면 변수명은 camelCase로 변경해야 합니다.


69aa8f5
수정했습니다.

2020-03-15 04:23 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-03-15 04:28 UTC, merged