HW-3 MVP 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #529
Opened 2020-03-15 13:18 UTC by mtjin

Login 부분은 Model은 안하고 VP만 했습니다.

 LoginPresenter 부분에서 이렇게 구현해도 되는건지 애매한 면이 있습니다, 따로 코멘트 달아놓겠습니다.

2020-03-15 13:21 UTC, mtjin commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/login/LoginPresenter.kt
> +        } else {
else문 부터 이렇게 구현해도 되는건지 궁금합니다. 
https://hashcode.co.kr/questions/3073/mvp-%ED%8C%A8%ED%84%B4%EC%97%90%EC%84%9C-startactivity%EB%8A%94-%EC%96%B4%EB%94%94%EC%84%9C-%ED%95%B4%EC%95%BC%ED%95%98%EB%82%98%EC%9A%94 를 참고했는데 구현방법이 여러가지가 있는 것 같습니다.

2020-03-15 13:22 UTC, sooakim commented
@kangraemin 먼저 리뷰 진행하시고 approve하면 제가 리뷰 시작할게요.

2020-03-16 12:55 UTC, raeminkang requested changes
또 splashActivity에서 autoLogin인지 아닌지 판단하는 부분이 있는데 이 부분도 Presenter에서 처리 해 줄 수 있을것같아요

2020-03-16 12:55 UTC, raeminkang commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/login/LoginPresenter.kt
> +            view.finishActivity()
개인적인 생각으로는 Presenter는 최대한 뷰를 몰라야 협업하기 편하다고 생각해요. 

만약 뷰의 컨텍스트 자체를 넘겨 버리면 View에 대한 정보를 많이 가져 올 수도 있고 이렇게 된다면 많은 로직들이 프레젠터에서 처리 할 수 있게 될 거고 그럼 업무를 나누는 부분에서 프레젠터를 맡는 사람의 업무량이 더 많아지게 될테니까요. 

에러 메세지를 넘겨주는 부분에서도, 에러메세지를 프레젠터에서 넘긴다면 프레젠터는 뷰가 어떻게 보일지 알고 있다는 것이 전제된것같아요. 이 전제도 뷰와 로직 부분을 나누겠다는 의미를 퇴색시키는 것이라 생각해요.

예를들어, 로그인 에러 메세지를 수정 하고자 할 때 로그인 에러메세지는 뷰에서보이고, 해당 작업은 뷰에서 진행되었을 것이라고 짐작 할것같아요. 그 뒤에 개발자는 뷰에 가서 로그인 에러메세지를 보여주는 showLoginErrorMessage 메소드를 찾을것이고, 해당부분을 수정 하면 되는데, 만약 에러메세지를 프레젠터에서 던져주고 이를 뷰에서는 메세지만 받아서 뿌려준다면 개발자는 프레젠터에 가서 수정을 해야 될 것 같아요 에러메세지를 수정하는데, 로직을 담당하는 프레젠터에서 수정하는것이 전 좀 어색하게 느껴 질 수도 있을 것 같아요

또 컨텍스트를 넘기는 것만으로 안드로이드 프레임워크와 프레젠터가 종속적인 관계가 되는 듯 해요 최대한 이를 없애주는것이 좋지 않을까 개인적으로 생각합니다. 

그리구 코드를 보여주고 싶을 때 해당 부분 ( LoginPresenter 의 17~ 20번째 줄 )을 클릭하여 쭉 당기면 선택가능해요 선택 하신 뒤에 커멘트를 남기면 해당 부분만 가져 올 수 있어 보여주기 편하답니다

2020-03-16 12:55 UTC, raeminkang commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/search/MovieAdapter.kt
> +            )
이부분을 이렇게 수정하신 이유가 있을까요 ?

2020-03-16 12:55 UTC, raeminkang commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/search/MovieSearchActivity.kt
> +        presenter = MovieSearchPresenter(this, scrollListener, myApplication, movieAdapter)
scrollListener를 presenter에서 받아서 하는 작업이 scrollListener를 초기화 작업인것같아요. 그러면 Listener를 presenter에 주입해서 직접 초기화를 하는 것 보다는 View에서 초기화를 하도록 프레젠터에서 뷰 함수를 부르는게 나을 것 같아요

2020-03-16 12:55 UTC, raeminkang commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/search/MovieSearchPresenter.kt
> +                        view.showToast("영화를 불러왔습니다.")
앞에서 말한 Context 주입과 같은 맥락인데요, 하드코딩된 텍스트는 유지보수 비용을 증가시키키므로 결국에 작업을 할 때 string.xml에서 스트링값을 가져 올 게 될거에요. 그런데 해당 작업엔 컨텍스트가 필요하므로 프레젠터에 컨텍스트를 가져와야 되게 될거구요 그러면 프레젠터에서 하는 역할이 점점 더 많아지는 것 같아요. 

또 앞에서 말했듯 코틀린 코드에 텍스트를 쓸 때는 string.xml에서 값을 가져오는것이 좀 더 좋아보여요 하드코딩된 텍스트가 많이 보이는데 그거에 대해선 더이상 달지 않을게요

2020-03-16 12:55 UTC, raeminkang commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/search/MovieSearchPresenter.kt
> +    private val movieAdapter: MovieAdapter
스크롤 리스너는 위에서 말씀 드렸고, MyApplication에서 movieRepository를 가져오는데 repository가 필요 한 경우에 ( ex_ 영화를 가져 올 때 ) movieRepository를 객체로 주입하면 생성 할 때 application을 넘기진 않아도 될 것 같아요 

또 어댑터도 프레젠터에 가져와서 뷰에 뿌려주기 보다는, 가져온 영화들을 뷰에 넘기고, 뷰에서 작업하도록 하는것이 좀 더 맞지 않나 생각들어요

2020-03-16 13:00 UTC, kangraemin requested changes
ㅠㅠ 다른 아이디로 잘못 달았네요 ... 리뷰내용은 상단에 있습니다 !

2020-03-16 15:25 UTC, mtjin commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/login/LoginPresenter.kt
> +            view.finishActivity()
8886938
context를 presenter에서 갖지 않도록 분리했습니다.

2020-03-16 15:30 UTC, mtjin commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/search/MovieAdapter.kt
> +            )
실수였던 것 같습니다. 원래대로 수정했습니다.
리뷰받고 처음으로 수정 후 커밋했는데 커밋메세지가 안보이네요... 
![image](https://user-images.githubusercontent.com/37071007/76773903-8af9ff00-67e6-11ea-91f5-fa74832e3921.png)

2020-03-16 15:32 UTC, mtjin commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/search/MovieSearchActivity.kt
> +        presenter = MovieSearchPresenter(this, scrollListener, myApplication, movieAdapter)
수정했습니다.
5d45085

2020-03-16 15:37 UTC, mtjin commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/search/MovieSearchPresenter.kt
> +                        view.showToast("영화를 불러왔습니다.")
5ce588a
수정했습니다.
레포지토리 부분의 Log 나 Throwable message 던져주는 것도 수정할려했는데 context문제 때문에 아직 수정하지 못했습니다.

2020-03-16 15:39 UTC, mtjin commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/search/MovieSearchPresenter.kt
> +    private val movieAdapter: MovieAdapter
5d45085
어댑터 부분 분리했습니다. movieRepository 부분도 수정했는데 말씀하신게 이게 맞는지 궁금합니다.

2020-03-17 13:19 UTC, kangraemin approved these changes

2020-03-17 13:22 UTC, kangraemin commented
@sooakim approve 하였습니다 ~~

2020-03-17 14:51 UTC, sooakim requested changes

2020-03-17 14:51 UTC, sooakim commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/login/LoginActivity.kt
> +    }
finish는 goMovieSearchActivity()안에서 호출해주세요.
goMovieSearchActvity 함수의 역할에 현재 뷰를 종료하는 역할도 포함된다고 생각해요.

2020-03-17 14:51 UTC, sooakim commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/login/LoginActivity.kt
> +    }
Preference는 Local DataSource이고 Model에 해당해요. Presenter에서 Repository를 통해 조작할 수 있도록 해주세요.

2020-03-17 14:51 UTC, sooakim commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/login/LoginActivity.kt
> +    override fun goMovieSearchActivity() {
저는 함수명에 View에 관한 구체적인 단어가 포함되면 안된다고 생각해요.
만약 Activity에서 Fragment로 교체를 하게된다면 함수 명을 수정해야하는 수고가 발생해요.

2020-03-17 14:51 UTC, sooakim commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/search/MovieSearchActivity.kt
> +    }
여기도 마찬가지인데 지금은 Toast지만 Snackbar나 AlertDialog를 사용하도록 기획이 변경된다면 어떨까요?
Toast가 없으면 단순히 로직만 변경하면 되지만 그렇지 않다면 함수명도 변경해야겠죠?

2020-03-17 14:51 UTC, sooakim commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/search/MovieSearchContract.kt
> +        fun adapterSetItems(movieList: List<Movie>)
여기도 구체적으로 View에서 어떤 조작을 할지는 Presenter에서 알 필요가 없다고 생각해요.

2020-03-17 14:51 UTC, sooakim commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/splash/SplashActivity.kt
> +        finish()
이 finish를 goLoginActivity와 goMovieSearchActivity밑으로 옮기는게 좋을 것 같아요.

2020-03-17 14:51 UTC, sooakim commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/splash/SplashActivity.kt
> +        presenter.splashStart()
Presenter가 init될 때 동작을 취하게 하거나
View의 생명주기에 변화가 생길 때 Presenter에 알려서 실행하게 하는게 좋을 것 같아요.

2020-03-17 14:51 UTC, sooakim commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/splash/SplashActivity.kt
> +    }
네이밍 확인

2020-03-17 14:51 UTC, sooakim commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/splash/SplashActivity.kt
> +    }
Model로 분리

2020-03-18 03:08 UTC, mtjin commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/search/MovieSearchContract.kt
> +        fun adapterSetItems(movieList: List<Movie>)
@sooakim 
네이밍을 바꾸는게 좋다는 말씀이신가요?

2020-03-18 03:40 UTC, sooakim commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/search/MovieSearchContract.kt
> +        fun adapterSetItems(movieList: List<Movie>)
@mtjin 네이밍도 변경해야할 것 같고, 두 개의 함수를 별도로 분리할 필요가 없을 것 같아요.

2020-03-18 04:57 UTC, mtjin commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/login/LoginActivity.kt
> +    }
0ab2d8c
수정했습니다.

2020-03-18 04:58 UTC, mtjin commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/login/LoginActivity.kt
> +    }
e175236
자동로그인 관련 Repository 생성 및 구현 했습니다.

2020-03-18 04:59 UTC, mtjin commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/login/LoginActivity.kt
> +    override fun goMovieSearchActivity() {
393adab
수정했습니다.

2020-03-18 04:59 UTC, mtjin commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/search/MovieSearchActivity.kt
> +    }
28bb114
수정했습니다.

2020-03-18 05:00 UTC, mtjin commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/search/MovieSearchContract.kt
> +        fun adapterSetItems(movieList: List<Movie>)
25ac389
수정했습니다.

2020-03-18 05:00 UTC, mtjin commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/splash/SplashActivity.kt
> +        finish()
843597e
2d74ded
수정했습니다.

2020-03-18 05:00 UTC, mtjin commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/splash/SplashActivity.kt
> +        presenter.splashStart()
62a51fe
수정했습니다.

2020-03-18 05:02 UTC, mtjin commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/splash/SplashActivity.kt
> +    }
393adab
수정했습니다

2020-03-18 05:03 UTC, mtjin commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/splash/SplashActivity.kt
> +    }
31af7ff

e175236
네이밍도 잘못됬어서 고쳤습니다.

2020-03-18 13:17 UTC, sooakim requested changes

2020-03-18 13:17 UTC, sooakim commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/data/login/source/local/LoginLocalDataSource.kt
> +    fun saveAutoLogin()
굳이 getter setter를 생성할 필요 없이 var로 선언해주면 돼요.

2020-03-18 14:33 UTC, mtjin commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/data/login/source/local/LoginLocalDataSource.kt
> +    fun saveAutoLogin()
@sooakim 
getAutoLogin()과 saveAutoLogin 둘 다 밑처럼 var autoLogin으로 처리하면 될까요? 
`override var autoLogin: Boolean
        get() = preferenceManager.getBoolean()
        set(value) { preferenceManager.setBoolean(value)}`

2020-03-18 14:44 UTC, mtjin commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/data/login/source/local/LoginLocalDataSource.kt
> +    fun saveAutoLogin()
b9bc1fb 
수정했습니다.

2020-03-19 02:49 UTC, sooakim commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/data/login/source/local/LoginLocalDataSource.kt
> +    fun saveAutoLogin()
@mtjin 네

2020-03-19 04:58 UTC, mtjin commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/data/login/source/local/LoginLocalDataSource.kt
> +    fun saveAutoLogin()
@sooakim 

e36c362
수정했습니다.

2020-03-19 06:01 UTC, sooakim commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/data/login/source/local/LoginLocalDataSource.kt
> +    fun saveAutoLogin()
@mtjin Preferences쪽도 바꿔주세요.

2020-03-19 07:12 UTC, mtjin commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/data/login/source/local/LoginLocalDataSource.kt
> +    fun saveAutoLogin()
@sooakim 

5732ae7
수정했습니다.

2020-03-19 11:26 UTC, sooakim approved these changes

2020-03-19 15:45 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-03-19 15:45 UTC, sjjeong commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/login/LoginPresenter.kt
> +        } else {
네 잘 하셨습니다.

2020-03-20 03:10 UTC, merged