Class02/beok beok
sjjeong/GoogryAndroidArchitecutreStudy pull request #53
Opened 2019-06-09 04:43 UTC by BeokBeok

1주차 과제 PR 요청 드립니다.

2019-06-09 05:50 UTC, sjjeong commented
PR이름을 수정해주세요
ex HW-1 과제

2019-06-09 06:17 UTC, BeokBeok commented
> PR이름을 수정해주세요
> ex HW-1 과제

변경하였습니다.

2019-06-10 16:06 UTC, NackUn commented on BeokBeok/app/src/main/java/com/architecturestudy/common/UpBitConnector.kt
> +                getTickers(markets?.asSequence()?.filter { prefix.length == 3 || prefix.length == 4 }
?.filter { prefix.length == 3 || prefix.length == 4 } 이부분이 없어도 될 것 같습니다.

2019-06-11 01:01 UTC, BeokBeok commented on BeokBeok/app/src/main/java/com/architecturestudy/common/UpBitConnector.kt
> +                getTickers(markets?.asSequence()?.filter { prefix.length == 3 || prefix.length == 4 }
> ?.filter { prefix.length == 3 || prefix.length == 4 } 이부분이 없어도 될 것 같습니다.

이 부분은 예외처리를 위해 추가하였습니다.
가령, KRW, USDT와 같이 글자 수로 필터링을 하기 위함입니다.
특정 String으로 비교하도록 수정하겠습니다.

2019-06-11 02:07 UTC, NackUn commented on BeokBeok/app/src/main/AndroidManifest.xml
> +                <action android:name="android.intent.action.VIEW" />
<action android:name="android.intent.action.VIEW" />
이건 어떤 이유로 사용하신 건지 궁금합니다.

2019-06-11 02:15 UTC, BeokBeok commented on BeokBeok/app/src/main/AndroidManifest.xml
> +                <action android:name="android.intent.action.VIEW" />
<action android:name="android.intent.action.VIEW" />
이 것을 설정하지 않으면, Google Search 시 App이 인덱싱이 되지 않습니다.
해서, 추가하였습니다.
개인적으로 warning(노란색)은 다 수정하는 편입니다.
참고로, 에러는 아닙니다.

2019-06-11 02:16 UTC, NackUn commented on BeokBeok/app/src/main/AndroidManifest.xml
> +                <action android:name="android.intent.action.VIEW" />
감사합니다! 덕분에 하나 더 배워갑니다^^

2019-06-11 12:33 UTC, BeokBeok commented on BeokBeok/app/src/main/java/com/architecturestudy/common/UpBitConnector.kt
> +                getTickers(markets?.asSequence()?.filter { prefix.length == 3 || prefix.length == 4 }
접두어를 필터링 하도록 함수 추가하였습니다.
f68175f36edeebf6fe35fc6b1402981ffbd3d477

2019-06-11 13:38 UTC, NackUn commented on BeokBeok/app/src/main/java/com/architecturestudy/common/UpBitConnector.kt
> +                getTickers(markets?.asSequence()?.filter { prefix.length == 3 || prefix.length == 4 }
확인했습니다. 고생하셨습니다

2019-06-11 15:18 UTC, sjjeong commented
@NackUn 
리뷰가 끝나고 변경점이 더이상 없다고 생각하셔서 Mentor Needed를 추가 하셨다면 approve도 같이 해주셔야 해요

2019-06-12 00:33 UTC, NackUn submitted a review, later dismissed
고생하셨습니다!

2019-06-12 15:49 UTC, sjjeong requested changes
reformat code도 해서 올려주세요.

2019-06-12 15:49 UTC, sjjeong commented on BeokBeok/app/src/main/java/com/architecturestudy/common/UpBitConnector.kt
> +                getTickers(markets?.asSequence()?.filter { hasPrefix(prefix) }
null chaining으로 처리보다 response.body() null체크를 하셔서 NonNull로 처리하면 좋을 것 같습니다.
getTicker()안에 파라미터로 들어가는 코드가 복잡해서 따로 변수로 선언해주면 좋을 것 같습니다.
https://kotlinlang.org/docs/reference/coding-conventions.html#chained-call-wrapping 참고하셔서 chaining 부분 line break 해주시면 좋을 것 같습니다.

2019-06-12 15:49 UTC, sjjeong commented on BeokBeok/app/src/main/java/com/architecturestudy/common/UpBitConnector.kt
> +    interface Retrofittable {
interface 이름을 보고 어떤 것인지 파악하기 어렵습니다.
UpBitApi로 변경하면 어떨까요?

2019-06-12 15:49 UTC, sjjeong commented on BeokBeok/app/src/main/java/com/architecturestudy/model/UpBitTickerResponse.kt
> +    @field:SerializedName("market")
`field:`는 생략해도 됩니다.

2019-06-12 15:49 UTC, sjjeong commented on BeokBeok/app/src/main/java/com/architecturestudy/view/MainFragment.kt
> +        val context = activity as MainActivity
ui를 setup하는 부분과 data를 set하는 부분을 분리해주세요.

2019-06-12 15:49 UTC, sjjeong commented on BeokBeok/app/src/main/java/com/architecturestudy/view/MainAdapter.kt
> +class MainAdapter(private val context: Context, private val marketPrice: List<UpBitTickerResponse>?) :
Adapter에 생성자로 data를 받는것은 좋지 않습니다.
내부에 list를 만들고 함수를 통해서 데이터를 넣어주는 방식으로 변경해주세요.

외부에서 context를 받아서 사용하지 말아주세요.

2019-06-12 15:49 UTC, sjjeong commented on BeokBeok/app/src/main/java/com/architecturestudy/view/MainAdapter.kt
> +    inner class ViewHolder(itemView: View?) : RecyclerView.ViewHolder(itemView!!) {
itemView를 NonNull로 변경해주세요.

2019-06-12 15:49 UTC, sjjeong commented on BeokBeok/app/src/main/java/com/architecturestudy/view/MainAdapter.kt
> +            tradingVal?.text = DecimalFormat("#,###M").format(marketPrice.accTradePrice24h?.div(1000000))
1000000보단 1_000_000이 한눈에 보기 더 좋아요

2019-06-12 15:49 UTC, sjjeong commented on BeokBeok/app/src/main/res/layout/fragment_main.xml
> +                android:layout_height="match_parent"
ConstraintLayout 자식에 있는 View는 match_parent보다 0dp를 권장 합니다.

2019-06-13 01:16 UTC, BeokBeok commented on BeokBeok/app/src/main/java/com/architecturestudy/common/UpBitConnector.kt
> +                getTickers(markets?.asSequence()?.filter { hasPrefix(prefix) }
적용하였습니다.
c52e535

2019-06-13 01:20 UTC, BeokBeok commented on BeokBeok/app/src/main/java/com/architecturestudy/common/UpBitConnector.kt
> +    interface Retrofittable {
UpBitService 로 명명하여 반영하였습니다.
d642443

2019-06-13 01:23 UTC, BeokBeok commented on BeokBeok/app/src/main/java/com/architecturestudy/model/UpBitTickerResponse.kt
> +    @field:SerializedName("market")
생략하였습니다.
7c58f74

2019-06-13 04:11 UTC, BeokBeok commented on BeokBeok/app/src/main/java/com/architecturestudy/view/MainAdapter.kt
> +class MainAdapter(private val context: Context, private val marketPrice: List<UpBitTickerResponse>?) :
적용하였습니다.
b1b4adc

2019-06-13 04:36 UTC, BeokBeok commented on BeokBeok/app/src/main/java/com/architecturestudy/view/MainFragment.kt
> +        val context = activity as MainActivity
적용하였습니다.
311bf0d

2019-06-13 04:42 UTC, BeokBeok commented on BeokBeok/app/src/main/java/com/architecturestudy/view/MainAdapter.kt
> +    inner class ViewHolder(itemView: View?) : RecyclerView.ViewHolder(itemView!!) {
적용하였습니다.
5a2cf3d

2019-06-13 04:47 UTC, BeokBeok commented on BeokBeok/app/src/main/java/com/architecturestudy/view/MainAdapter.kt
> +            tradingVal?.text = DecimalFormat("#,###M").format(marketPrice.accTradePrice24h?.div(1000000))
적용하였습니다.
58ddcd6

2019-06-13 04:57 UTC, BeokBeok commented on BeokBeok/app/src/main/res/layout/fragment_main.xml
> +                android:layout_height="match_parent"
@sjjeong 
width와 height 둘 다 0dp를 권장하는 것인가요?

2019-06-14 14:30 UTC, sjjeong commented on BeokBeok/app/src/main/res/layout/fragment_main.xml
> +                android:layout_height="match_parent"
@BeokBeok 
네 match_parent가 동작이 이상해서 0dp를 쓰는게 좋습니다.

2019-06-14 14:57 UTC, BeokBeok commented on BeokBeok/app/src/main/res/layout/fragment_main.xml
> +                android:layout_height="match_parent"
적용하였습니다.
4e797f11e1c02d4512b48d92856cec36ab24f154

2019-06-14 15:02 UTC, sjjeong commented on BeokBeok/app/src/main/res/layout/fragment_main.xml
> +                android:layout_height="match_parent"
16번째 줄도 수정해주셔야 합니다

2019-06-14 15:08 UTC, BeokBeok commented on BeokBeok/app/src/main/res/layout/fragment_main.xml
> +                android:layout_height="match_parent"
추가 적용하였습니다.
4133ff6

2019-06-14 15:09 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-06-14 16:11 UTC, NackUn approved these changes
고생하셨습니다!

2019-06-14 23:59 UTC, merged