HW-3 Use MVP pattern
sjjeong/GoogryAndroidArchitecutreStudy pull request #531
Opened 2020-03-15 14:13 UTC by kangraemin

2020-03-15 15:00 UTC, mtjin requested changes
패키지 구조가 presenter, activity, contract 패키지를 만들어서 관리하시는데 구글 블루프린트 예제코드에서는 하나의 액티비티 패키지에 presenter, activity, contract 를 넣어놨습니다.
그래서 저 같은 경우는 액티비티 별로 패키지를 만들어서   presenter, activity, contract 를 추가했는데 이 부분은 슬랙방에 여쭤보는게 확실할 것 같습니다.
![image](https://user-images.githubusercontent.com/37071007/76703973-24f37600-6719-11ea-89ad-13e6440d944f.png)

![image](https://user-images.githubusercontent.com/37071007/76703918-c0381b80-6718-11ea-84ad-7eff37d61667.png)

2020-03-15 15:00 UTC, mtjin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/presenter/MainPresenter.kt
> +import com.example.kangraemin.model.MovieSearchRepository
이번 FileChanges에는 없으나 MovieSearchRepository 클래스 생성자 부분에 remoteMovieDatasource -> remoteMovieDataSource 변경 해야할 것 같습니다.

![image](https://user-images.githubusercontent.com/37071007/76703712-d7760980-6716-11ea-96da-19d7c3c63731.png)

2020-03-15 15:00 UTC, mtjin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/LoginActivity.kt
>      val authRepository by lazy {
private 붙여주세요

2020-03-15 15:00 UTC, mtjin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/MainActivity.kt
>      val remoteMovieDataSource by lazy {
private 붙여주세요 (이 밑에 adapter 선언까지)

2020-03-15 15:00 UTC, mtjin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/presenter/LoginPresenter.kt
> +        if (id == "id" && password == "P@ssw0rd") {
로그인 성공하는 로직을 조건문 마지막으로 빼는게 좋다고 리뷰 받았었습니다.

2020-03-15 15:05 UTC, mtjin requested changes

2020-03-15 15:05 UTC, mtjin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/base/KangBasePresenter.kt
> +    fun disposeCompositDisposable()
disposeCompositDisposable -> disposeCompositeDisposable  스펠링 오타있습니다.

2020-03-16 13:30 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/base/KangBasePresenter.kt
> +    fun disposeCompositDisposable()
수정하였습니다
2a24592

2020-03-16 13:30 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/presenter/LoginPresenter.kt
> +        if (id == "id" && password == "P@ssw0rd") {
수정하였습니다
0a93905

2020-03-16 13:30 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/MainActivity.kt
>      val remoteMovieDataSource by lazy {
수정하였습니다
37d5894

2020-03-16 13:31 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/presenter/MainPresenter.kt
> +import com.example.kangraemin.model.MovieSearchRepository
수정하였습니다
0f58f30

2020-03-16 13:31 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/LoginActivity.kt
>      val authRepository by lazy {
수정하였습니다
37d5894

2020-03-16 13:36 UTC, kangraemin commented
패키지 정리도 하였습니다 
2ca7999

2020-03-16 13:56 UTC, mtjin approved these changes
@sooakim 
approve했습니다.

2020-03-16 15:27 UTC, sooakim requested changes

2020-03-16 15:27 UTC, sooakim commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/login/LoginActivity.kt
> +    }
따로 분리한 이유가 있을까요

2020-03-16 15:27 UTC, sooakim commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/login/LoginActivity.kt
> +    }
이 로직은 프레젠터에서 해주세요.

2020-03-16 15:27 UTC, sooakim commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/login/LoginActivity.kt
> +        presenter.disposeCompositeDisposable()
이 부분은 생명주기에 대응되는 함수를 프레젠터에 만들어 놓고, 프레젠터에서 진행하면 될 것 같아요.

2020-03-16 15:27 UTC, sooakim commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/login/LoginContract.kt
> +        fun addAutoLoginStatus(authRepository: AuthRepository)
repository는 매번 함수에서 전달 받지 말고 Presenter의 생성자를 통해 넘겨주세요.

2020-03-16 15:27 UTC, sooakim commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/login/LoginActivity.kt
> +            )
이 로직은 굳이 번거롭게 연산자를 쓰기 보다 
```suggestion
   presenter.checkLoginInfoHasEntered(
     id = et_id.text.toString(),
     password = et_pw.text.toString()
   )
```
이렇게 가는게 더 보기 좋을 것 같아요.

2020-03-16 15:27 UTC, sooakim commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/login/LoginActivity.kt
> +            }
또 activeButton같은 경우는 checkLoginInfoHasEntered에서 이미 판단해서 View에서 처리하도록 요청하는게 좋을 것 같아요.

2020-03-16 15:27 UTC, sooakim commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/main/MainContract.kt
> +        )
마찬가지로 생성자를 통해 주입해주세요.

2020-03-16 15:27 UTC, sooakim commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/login/LoginPresenter.kt
> +        compositeDisposable.add(getAuth)
이렇게 하면 문제가 있어요. 
checkAutoLoginStatus함수가 실행될 때마다 매번 새로운 Rx스트림이 생성될거에요.
이전 이벤트를 dispose하고 실행시키거나 switchMap을 사용하도록 해보세요.

2020-03-16 15:27 UTC, sooakim commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/login/LoginPresenter.kt
> +        compositeDisposable.add(addAuth)
마찬가지인데 얘는 아무것도 안하는건가요?

2020-03-16 15:27 UTC, sooakim commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/main/MainPresenter.kt
> +        compositeDisposable.add(getAuth)
여기도요.

2020-03-16 15:27 UTC, sooakim commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/main/MainPresenter.kt
> +        compositeDisposable.add(deleteAuth)
여기도요.

2020-03-16 15:27 UTC, sooakim commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/main/MainActivity.kt
> +                presenter.checkNetworkStatus(NetworkUtil().getConnectivityStatus(context = this))
얘도 생성자로 주입해주면 좋을 것 같아요.

2020-03-16 15:27 UTC, sooakim commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/main/MainPresenter.kt
> +        compositeDisposable.add(whenArrivedMovieData)
여기도 마찬가지

2020-03-16 15:27 UTC, sooakim commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/splash/SplashActivity.kt
> +        finish()
액티비티를 생성하는 작업도 비용이 드는 작업인데 굳이 로그인이 된 경우에도 LoginActivity로 넘어가서 MainActivity로 다시 이동해야되는지는 의문이네요.

2020-03-16 15:27 UTC, sooakim commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/splash/SplashPresenter.kt
> +        compositeDisposable.add(splashTimer)
여기도요.

2020-03-17 14:56 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/splash/SplashPresenter.kt
> +        compositeDisposable.add(splashTimer)
수정하였습니다
6f1a67b

2020-03-17 14:57 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/splash/SplashActivity.kt
> +        finish()
수정하였습니다
c04e5b4

2020-03-17 14:57 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/main/MainActivity.kt
> +                presenter.checkNetworkStatus(NetworkUtil().getConnectivityStatus(context = this))
수정하였습니다
93f3c9b

2020-03-17 14:57 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/main/MainPresenter.kt
> +        compositeDisposable.add(whenArrivedMovieData)
수정하였습니다
1b6a7b1

2020-03-17 14:58 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/main/MainContract.kt
> +        )
수정하였습니다
1b6a7b1

2020-03-17 14:58 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/login/LoginActivity.kt
> +    }
수정하였습니다
6a390c5

2020-03-17 14:59 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/login/LoginActivity.kt
> +    }
수정하였습니다
b0d6303

2020-03-17 15:00 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/login/LoginActivity.kt
> +    }
수정하였습니다
b0d6303

2020-03-17 15:00 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/login/LoginActivity.kt
> +        presenter.disposeCompositeDisposable()
수정하였습니다
63a1a2e

2020-03-17 15:01 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/login/LoginContract.kt
> +        fun addAutoLoginStatus(authRepository: AuthRepository)
수정하였습니다
04aa175

2020-03-17 15:02 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/login/LoginPresenter.kt
> +        compositeDisposable.add(getAuth)
수정하였습니다
cd8d991

2020-03-17 15:03 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/login/LoginPresenter.kt
> +        compositeDisposable.add(addAuth)
수정하였습니다
네 그렇습니다 Auth를 room에 저장하는 과정이라 과정이 끝난 뒤 하는일이 따로 없어 no-op을 적어놓았습니다
cd8d991

2020-03-17 15:03 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/main/MainPresenter.kt
> +        compositeDisposable.add(getAuth)
수정하였습니다
cd8d991

2020-03-17 15:03 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/main/MainPresenter.kt
> +        compositeDisposable.add(deleteAuth)
수정하였습니다
cd8d991

2020-03-17 15:06 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/login/LoginActivity.kt
> +            )
이부분 같은 경우는 여쭤볼게 있어 코멘트 남깁니다 

전 텍스트가 바뀔 때 마다 모든 값들이 입력되었는지 확인하고자 하였습니다. 
그런데 compositLatest로 textChange 스트림을 받지 않으면 텍스트가 바뀔 때 마다 체크를 못하게 되는것 같아 어떻게 고쳐야 할 지 감이 잘 안잡혀 여쭤봅니다 

아래의 부분도 해당 부분을 수정 할 때 같이 고치도록 하겠습니다.

2020-03-17 15:11 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/main/MainPresenter.kt
> +        compositeDisposable.add(getAuth)
수정하였습니다
cd8d991

2020-03-17 15:32 UTC, sooakim requested changes

2020-03-17 15:32 UTC, sooakim commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/login/LoginActivity.kt
> +        layout_pw.error = ""
다른 화면으로 이동하기 전에 지우는 이유가 있나요?

2020-03-17 15:32 UTC, sooakim commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/login/LoginContract.kt
> +        fun startMainActivity()
Activity가 나중에 Fragment로 변경된다면 함수명도 변경이 되야하니 Activity를 빼는게 좋을 것 같아요.

2020-03-17 15:32 UTC, sooakim commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/login/LoginActivity.kt
> +            )
@kangraemin 음.. 그렇다면 View에서는 단어가 변경될 때마다 presenter에 넘겨주는 역할만 하고,
나머지는 그 후 presenter에서 판단하에 View에 처리를 요청하도록 해야될 것 같아요.

2020-03-17 15:37 UTC, sooakim commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/login/LoginPresenter.kt
> +        compositeDisposable.add(getAuth)
@kangraemin 수정된 코드도 여전히 매번 새로운 Rx스트림을 생성해요. 관련 request 전부 다시 확인해주세요.

2020-03-18 10:58 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/login/LoginActivity.kt
> +            )
수정하였습니다
7e30d7f

2020-03-18 10:58 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/login/LoginActivity.kt
> +            }
수정하였습니다
7e30d7f

2020-03-18 10:58 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/login/LoginActivity.kt
> +        layout_pw.error = ""
아뇨 실수에요 .... 수정하였습니다
e50dbee

2020-03-18 10:58 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/login/LoginContract.kt
> +        fun startMainActivity()
수정하였습니다
7e4a58a

2020-03-18 13:27 UTC, sooakim requested changes

2020-03-18 13:27 UTC, sooakim commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/login/LoginActivity.kt
> +        compositeDisposable.add(whenPwTextChanged)
```suggestion
        val whenTextChanged = Observable.combineLatest(
           et_id.textChanges(),
           et_pw.textChanges(),
           BiFunction<CharSequence, CharSequence, Pair<String, String>>{
              id, pw ->
              id.toString() to pw.toString()
           }
         ) 
         .subscribe{
           //TODO: presenter.blabla
         }
         compositeDisposable.add(whenTextChanged)
```

2020-03-18 13:27 UTC, sooakim commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/main/MainPresenter.kt
> +        compositeDisposable.add(whenArrivedMovieData)
여기서 사용되는 switchMap은 searchText와 ""에 대해서만 의미가 있지 getMovies 호출 이벤트 자체는 계속 발행돼요.

2020-03-19 12:52 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/login/LoginActivity.kt
> +        compositeDisposable.add(whenPwTextChanged)
이런 방법도 있군요 감사합니다 수정했습니다
d8e57ce

2020-03-19 12:54 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/main/MainPresenter.kt
> +        compositeDisposable.add(whenArrivedMovieData)
수정하였습니다
0b69ee6

2020-03-19 14:38 UTC, sooakim requested changes

2020-03-19 14:38 UTC, sooakim commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/login/LoginPresenter.kt
> +        compositeDisposable.add(addAuth)
이벤트 중복 생성 확인

2020-03-19 14:38 UTC, sooakim commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/login/LoginContract.kt
> +        fun addAutoLoginStatus()
그러고 보니깐 이건 Presenter내부에서 사용되는 함수인데 여기에 있네요.

2020-03-19 14:38 UTC, sooakim commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/main/MainPresenter.kt
> +        compositeDisposable.add(deleteAuth)
이벤트 중복 생성 확인

2020-03-19 14:38 UTC, sooakim commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/main/MainPresenter.kt
> +            }, { it.printStackTrace() })
이벤트 중복 생성 확인

2020-03-19 14:38 UTC, sooakim commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/splash/SplashPresenter.kt
> +        compositeDisposable.add(splashTimer)
굳이 startTimer를 안 만들고 init구문으로 빼줘도 될 것 같아요.

2020-03-19 14:38 UTC, sooakim commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/splash/SplashPresenter.kt
> +        compositeDisposable.add(getAuth)
이벤트 중복 생성 확인

2020-03-20 15:41 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/login/LoginContract.kt
> +        fun addAutoLoginStatus()
수정했습니다
cc01ab0

2020-03-20 15:42 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/splash/SplashPresenter.kt
> +        compositeDisposable.add(splashTimer)
수정했습니다
fea6aab

2020-03-20 15:43 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/login/LoginPresenter.kt
> +        compositeDisposable.add(addAuth)
수정했습니다
8d78613

2020-03-20 15:45 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/main/MainPresenter.kt
> +        compositeDisposable.add(deleteAuth)
수정했습니다
62890ef

2020-03-20 15:45 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/main/MainPresenter.kt
> +            }, { it.printStackTrace() })
수정했습니다
62890ef

2020-03-20 15:46 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/splash/SplashPresenter.kt
> +        compositeDisposable.add(getAuth)
수정했습니다
3027e30

2020-03-20 16:20 UTC, sooakim approved these changes

2020-03-21 03:38 UTC, sjjeong requested changes

2020-03-21 03:38 UTC, sjjeong commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/login/LoginActivity.kt
> +    }
val 로 들고 있지 말고 presenter만들때 같이 넣어주도록 해주세요
repository만들 때 Local 만들어주는것 처럼요

2020-03-21 03:38 UTC, sjjeong commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/login/LoginPresenter.kt
> +                    .andThen(Flowable.just(Unit))
이 코드는 필요 없지 않을까요? 
Flowable.just(Unit)을 하신 이유가 있나요?

MainPresenter와 SplashPresenter쪽에도 있네요

2020-03-21 03:38 UTC, sjjeong commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/main/MainActivity.kt
> +    }
이것도 로그인에 리뷰 남겨드린 것과 동일하게 처리해주세요

2020-03-21 03:38 UTC, sjjeong commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/main/MainPresenter.kt
> +    private val localMovieDataSource: LocalMovieDataSourceImpl,
각각 받지 마시고 MoviewRepository를 받도록 해주세요

2020-03-21 06:04 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/main/MainPresenter.kt
> +    private val localMovieDataSource: LocalMovieDataSourceImpl,
수정하였습니다
7ac30e2

2020-03-21 06:04 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/main/MainActivity.kt
> +    }
수정하였습니다
7ac30e2

2020-03-21 06:04 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/login/LoginActivity.kt
> +    }
수정하였습니다
a3b3d1d

2020-03-21 06:13 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/login/LoginPresenter.kt
> +                    .andThen(Flowable.just(Unit))
authRepository.addAuth()가 Completable 이라 upstream의 타입에 맞게 변환 해 주려고 한 것입니다. 

 또 switchMap대신에 sitchMapCompletable을 사용하려고 했었는데, 이 오퍼레이터는 upstream이 Complete되어야 Complete를 뱉어 줘서 swichMap을 사용했고, 그 뒤에 Flowable 스트림으로 변환 해 준 것입니다.

2020-03-21 07:22 UTC, sjjeong commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/login/LoginPresenter.kt
> +                    .andThen(Flowable.just(Unit))
테스트 해보니까 래민님이 말씀하신게 맞네요
그러면 만약에 authRepository.addAuth()에서 error가 발생하면 이 stream은 닫힐 꺼고 addAuthSubject는 더이상 동작하지 않겠네요

2020-03-21 12:18 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/login/LoginPresenter.kt
> +                    .andThen(Flowable.just(Unit))
석준님 말을 듣고 생각해보니 그렇겠더라구요 ... 실제로 테스트 해봐도 그렇기도 하고 ...

상위 경우 말고도, movie repository에서 영화를 가져올 때도 에러를 냈을 때도 subject의 특성 상 바로 닫혀버려 같은 문제가 있더라구요 

 스트림이 재생성 되는 문제를 해결하기 위해 로그인 버튼 클릭 / 영화 검색 버튼 클릭의 스트림과 로그인 / 검색 등 presenter의 스트림을 suject를 사용하여 연결해 주었는데, subject를 사용하는 이상 해당 문제는 해결이 안될것같더라구요 ... 

그래서 해결책으로는 생각해봤던게 

1. subject를 사용하지 않고 버튼을 클릭하는 스트림을 아예 프레젠터의 파라메터로 넘겨 스트림을 이어준다 ( ex_ button.clicks()를 프레젠터로 넘겨 스트림을 이어준다 ) 

2. 에러가 생기면 액티비티를 재생성 -> 프레젠터를 재생성하여 subject를 재생성 해준다 

가 생각나고 나머지 해결책은 떠오르지 않는데 ... 해당 방법 말고 더 좋은 방법이 있을까 해서 여쭤봅니다

2020-03-21 14:10 UTC, sooakim commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/login/LoginPresenter.kt
> +                    .andThen(Flowable.just(Unit))
에러 발생시 재구독 연산자 retry, retryWhen또는 에러 발생시 대체값을 반환하는 연산자 onErrorReturn 들등을 찾아보세요

2020-03-21 16:07 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/login/LoginPresenter.kt
> +                    .andThen(Flowable.just(Unit))
base activity에 toast function 추가
ec4e92f
HW-3 toast에 쓰일 string 추가 
fad2c56
splash ui presenter 수정
f8a5c10
splash ui presenter에서 apply 사용 
6cb88d5
login ui presenter 수정
e793d6a
main ui presenter 수정 
2db0320

subject를 살리거나, 스트림 연결 방법에만 치중하여 고민하였었는데, 조언 주신것 바탕으로 다시 수정하였습니다. 에러를 낸 뒤 테스트 해본 결과 스트림이 죽지 않는것 확인하였습니다 감사합니다 !!

2020-03-22 04:36 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-03-22 04:53 UTC, merged