2003/tjdwlsl1021
sjjeong/GoogryAndroidArchitecutreStudy pull request #532
Opened 2020-03-16 14:49 UTC by tjdwlsl1021

review요청 드립니다.

2020-03-17 06:35 UTC, byiryu commented on 2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/ui/SearchMovieAdapter.kt
> +
필요없는 소스 같습니다.

2020-03-17 06:35 UTC, byiryu commented on 2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/ui/SearchMovieActivity.kt
굳이 presenter를 거치지 않고 사용하셔도 무방할것 같습니다.

2020-03-17 06:35 UTC, byiryu commented on 2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/ui/SearchMovieActivity.kt
> +
데이터를 불러오는 로직은 Presenter에서 해야합니다.

2020-03-17 06:35 UTC, byiryu commented on 2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/ui/SearchMovieActivity.kt
> +
showMovieList는 Presenter로 옮겨주세요

2020-03-17 06:35 UTC, byiryu commented on 2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/ui/SearchMovieActivity.kt
> +
필요없는 로직같습니다 search 함수에서 다 같이 처리하는게 좋아보입니다.

2020-03-17 06:35 UTC, byiryu commented on 2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/ui/SearchMovieActivity.kt
> +
필요없는 로직같습니다 search 함수에서 다 같이 처리하는게 좋아보입니다.

2020-03-17 10:01 UTC, tjdwlsl1021 commented on 2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/ui/SearchMovieAdapter.kt
> +
1. 영화목록 리스트의 아이템 onClickListner를 SearchMovieActivity로 넘겨줘서
클릭이벤트 처리하는 소스입니다. 한번만 더 확인 부탁드리겠습니다.

2020-03-17 10:02 UTC, tjdwlsl1021 commented on 2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/ui/SearchMovieActivity.kt
94210bf92c06e1348f967adc34771810de7f4ea8
수정했습니다.

2020-03-17 10:05 UTC, tjdwlsl1021 commented on 2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/ui/SearchMovieActivity.kt
> +
26b2d50a10624930856f9b66ac0aae20906f8b31
수정했습니다.

2020-03-17 10:05 UTC, tjdwlsl1021 commented on 2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/ui/SearchMovieActivity.kt
> +
1ed9c675c8a7dc7fbdd5181366d6dec88b407fcb
수정했습니다.

2020-03-17 10:06 UTC, tjdwlsl1021 commented on 2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/ui/SearchMovieActivity.kt
> +
1ed9c67
수정했습니다.

2020-03-17 10:43 UTC, tjdwlsl1021 reviewed
리뷰내용 수정 적용했습니다.
확인 부탁드립니다.

2020-03-17 13:41 UTC, byiryu commented on 2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/ui/SearchMovieAdapter.kt
> +
그러네요 제가 다른거랑 착가했습니다. 죄송합니다.

2020-03-17 13:43 UTC, byiryu commented on 2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/ui/SearchMovieActivity.kt
> +
이것도 위에 부분과 마찬가지 같습니다.   presenter 에서 search를 통해 검사를 하고 
다시  view를 갔다가 로드하는  presenter getMovieList를 부르는건 비효율적인거 같습니다

view -> prensener -> view -> presneter 가 아니라
view -> presenter  까지만 해도 처리가 가능할것 같습니다.

2020-03-17 13:46 UTC, byiryu approved these changes
고생하셨습니다.
Approve

2020-03-18 04:11 UTC, sjjeong requested changes
커밋하기전에 Reformat Code를 하셔서 unused import 제거와 코드 정렬이 되게 해주세요

2020-03-18 04:11 UTC, sjjeong commented on 2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/ui/Contract.kt
> +interface Contract {
클래스명 앞에 어떤 화면에서 쓰이는지 추가해주면 좋겠네요
ex) MainActivity에서 쓴다면 MainContract

2020-03-18 04:11 UTC, sjjeong commented on 2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/ui/SearchMoviePresenter.kt
> +        }
예외 케이스를 먼저 처리하고 동작케이스를 처리하는게 좋습니다.

함수명에 맞는 실제 동작인 repository에서 getMovieList()를 호출하는 것을 마지막에서 처리해주세요

2020-03-19 10:02 UTC, tjdwlsl1021 commented
> 커밋하기전에 Reformat Code를 하셔서 unused import 제거와 코드 정렬이 되게 해주세요


472368c
수정했습니다.

2020-03-19 10:03 UTC, tjdwlsl1021 commented on 2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/ui/Contract.kt
> +interface Contract {
31ffd9f
수정했습니다.

2020-03-19 10:03 UTC, tjdwlsl1021 commented on 2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/ui/SearchMoviePresenter.kt
> +        }
3adf0d5
수정했습니다.

2020-03-19 10:04 UTC, tjdwlsl1021 reviewed
수정요청내용 반영했습니다.
확인 부탁드립니다.

2020-03-19 15:48 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-03-21 04:28 UTC, merged