HW-3 MVP 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #533
Opened 2020-03-17 06:21 UTC by byiryu

2020-03-17 10:44 UTC, tjdwlsl1021 reviewed
소스리뷰 했습니다.

2020-03-17 10:44 UTC, tjdwlsl1021 commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/base/BasePresenter.kt
> +        private set
private set만 적어도 값이 담아지는건가요?

2020-03-17 10:44 UTC, tjdwlsl1021 commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/base/BasePresenter.kt
> +    class BaseViewNotAttachedException :
이 부분 호출하는 곳이 없는 것 같아서 혹시 나중에 사용할 예정인건가요?

2020-03-17 10:44 UTC, tjdwlsl1021 commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/login/LoginPresenter.kt
> +            mvpView?.showMsg(R.string.msg_invalid_id)
여기는 LoginPresenter인데, mvpView?.showMsg(R.string.msg_invalid_id) 출력하는게 있어서
이게 LoginActivity로 가야하는것 같아서 확인 요청 드립니다.

2020-03-17 10:44 UTC, tjdwlsl1021 commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/login/LoginPresenter.kt
> +            mvpView?.showMsg(R.string.msg_invalid_pw)
여기도 위 내용과 같습니다.

2020-03-17 10:44 UTC, tjdwlsl1021 commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/login/LoginPresenter.kt
> +                mvpView?.showMsg(R.string.msg_error_loading)
여기도 위 내용과 같습니다.

2020-03-17 10:44 UTC, tjdwlsl1021 commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/login/LoginPresenter.kt
> +                    mvpView?.showMsg(R.string.msg_incorrect_login)
여기도 위 내용과 같습니다.

2020-03-17 10:44 UTC, tjdwlsl1021 commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/login/LoginPresenter.kt
> +                mvpView?.showMsg("오류 발생 : $it")
여기도 위 내용과 같습니다.

2020-03-17 10:44 UTC, tjdwlsl1021 commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/login/LoginActivity.kt
> +    private fun initView(){
initView함수안에 선언된 내용이 없어서 나중에 사용하려고 세팅해놓은건가요?

2020-03-17 10:44 UTC, tjdwlsl1021 commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/main/MainPresenter.kt
> +class MainPresenter<V : MainConract.View> constructor(private val repository: Repository): BasePresenter<V>(), MainConract.Presenter<V> {
제 생각에는 줄이 좀 긴거 같아서 줄바꿈 처리하면 좋을 것 같습니다.

2020-03-17 10:44 UTC, tjdwlsl1021 commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/main/MainPresenter.kt
> +            mvpView?.showMsg(R.string.msg_search_value)
Presenter에 화면출력하는 
mvpView?.showMsg(R.string.msg_search_value)
내용이 있어서 확인 요청드립니다.

2020-03-17 10:44 UTC, tjdwlsl1021 commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/main/MainPresenter.kt
> +                        mvpView?.showMsg(R.string.msg_error_loading)
위 내용과 같습니다.

2020-03-17 10:44 UTC, tjdwlsl1021 commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/main/MainPresenter.kt
> +                        mvpView?.showMsg("오류 발생 $it")
위 내용과 같습니다.

2020-03-17 10:44 UTC, tjdwlsl1021 commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/main/MainActivity.kt
> +import android.util.Log
프로젝트 중간중간 import 사용 안하는것들이 있어서 이런거는 정리하면 좋을 것 같습니다.

2020-03-17 12:44 UTC, byiryu commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/login/LoginPresenter.kt
> +                mvpView?.showMsg(R.string.msg_error_loading)
mvpView가 각 해딩 뷰 엑티비티를 의미합니다. 메세지, 로딩 출력은 뷰에서 하는게 맞는거 같아서 presenter에서 view를 호출하는 형태입니다.

2020-03-17 13:31 UTC, byiryu commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/base/BasePresenter.kt
> +    class BaseViewNotAttachedException :
수정했습니다.
61be0c7

2020-03-17 13:31 UTC, byiryu commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/base/BasePresenter.kt
> +        private set
수정했습니다.  처음에는 set을 사용했었는데 수정되면서 잊었네요
61be0c7

2020-03-17 13:32 UTC, byiryu commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/login/LoginActivity.kt
> +    private fun initView(){
수정했습니다.

6dbd548

2020-03-17 13:33 UTC, byiryu commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/main/MainPresenter.kt
> +class MainPresenter<V : MainConract.View> constructor(private val repository: Repository): BasePresenter<V>(), MainConract.Presenter<V> {
리포맷 커밋으로 한번에 해버렸네요...ㅠ
46bdd42

2020-03-17 13:33 UTC, byiryu commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/main/MainActivity.kt
> +import android.util.Log
리포맷 습관이 안되어있어서 ㅠ_ㅠ 수정했습니다
46bdd42

2020-03-17 13:35 UTC, byiryu reviewed
같은 내용에 대한 리뷰가 있어서 다시 설명 드립니다

showMsg는 BaseContract.View에 정의된 함수로 뷰에서 호출되는 함수입니다. 

*  activity
 presetner = Presenter(Contract.View)
* presenter
view.showMsg

와 같은 원리입니다.

2020-03-18 15:17 UTC, tjdwlsl1021 commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/login/LoginPresenter.kt
> +                mvpView?.showMsg(R.string.msg_error_loading)
네 이 부분은 제가 더 공부해보겠습니다.

2020-03-18 15:18 UTC, tjdwlsl1021 commented
> 같은 내용에 대한 리뷰가 있어서 다시 설명 드립니다
> 
> showMsg는 BaseContract.View에 정의된 함수로 뷰에서 호출되는 함수입니다.
> 
> * activity
>   presetner = Presenter(Contract.View)
> * presenter
>   view.showMsg
> 
> 와 같은 원리입니다.

친철히 설명해주셔서 감사합니다^^

2020-03-18 15:20 UTC, tjdwlsl1021 commented
approve했습니다.
친절한 설명 감사했습니다^^

2020-03-18 15:20 UTC, tjdwlsl1021 approved these changes
Approve했습니다.
친절한 설명 감사합니다^^

2020-03-19 16:07 UTC, sjjeong requested changes

2020-03-19 16:07 UTC, sjjeong commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/intro/IntroPresenter.kt
> +    override fun onViewPrepared() {
onAttach에서 해도 되는 함수인 것 같습니다.
제거 하고 onAttach를 override해서 사용하는 쪽으로 변경하면 좋겠네요

2020-03-19 16:07 UTC, sjjeong commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/login/LoginActivity.kt
> +        finish()
Splash처럼 goMainActivity로 명확한 이름을 넣어주는게 좋겠습니다.
파라미터가 없는 goActivity()는 제거하는게 좋겠습니다.

2020-03-19 16:07 UTC, sjjeong commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/login/LoginActivity.kt
> +                loginPresenter.login(btn_auto_login.isChecked)
invalid검사해서 login시키는것 로직 자체가 login 함수 내에 있으면 됩니다.
view에서는 id와 pw를 loginPresenter.login()에 isChecked와 함께 전달 해주면 됩니다.

2020-03-19 16:07 UTC, sjjeong commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/login/LoginPresenter.kt
> +    lateinit var pw: String
invalid 함수를 제거하면서 같이 제거해주시면 됩니다.

2020-03-19 16:07 UTC, sjjeong commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/login/LoginPresenter.kt
> +                        repository.setAutoLogin()
{} 추가해주세요

2020-03-19 16:07 UTC, sjjeong commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/main/MainPresenter.kt
> +    override fun onViewPrepared() {
여기도 마찬가지로 onAttach를 override해서 사용하는 쪽으로 해주세요

2020-03-19 16:07 UTC, sjjeong commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/base/BasePresenter.kt
> +    var disposable: Disposable? = null
disposable로 하면 단건만 가지고 있게 됩니다.
여러개를 가질 수 있도록 CompositeDisposable을 사용해주세요

2020-03-19 16:07 UTC, sjjeong commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/base/BasePresenter.kt
> +    override fun onAttach(view: V) {
호출하는 쪽이 onCreate라서 BaseActivity에서 호출해주면 BaseActivity를 상속 받는 쪽에서 매번 호출 할 필요가 없습니다.

2020-03-19 16:07 UTC, sjjeong commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/base/BasePresenter.kt
> +    override fun onDetach() {
onAttach는 모든 Activity가 호출하는데 onDetach는 MainActivity만 호출하고 있습니다.
위에 onAttach와 동일하게 BaseActivity에서 호출하도록 변경해주세요

2020-03-20 12:32 UTC, byiryu commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/base/BasePresenter.kt
> +    override fun onAttach(view: V) {
무슨 말인지 이해가 잘 되지 않습니다.

2020-03-20 12:35 UTC, byiryu commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/base/BasePresenter.kt
> +    override fun onAttach(view: V) {
BaseActivity에서  presenter를 생성해서 onAttach를 호출하라는 말씀이신가요??

2020-03-20 12:46 UTC, byiryu commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/intro/IntroPresenter.kt
> +    override fun onViewPrepared() {
수정했습니다

f7aac02

2020-03-20 12:47 UTC, byiryu commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/login/LoginActivity.kt
> +        finish()
수정했습니다

b7670e9

2020-03-20 12:47 UTC, byiryu commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/login/LoginActivity.kt
> +                loginPresenter.login(btn_auto_login.isChecked)
수정했습니다

592f51a

2020-03-20 12:47 UTC, byiryu commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/login/LoginPresenter.kt
> +                        repository.setAutoLogin()
수정했습니다
07dff61

2020-03-20 12:48 UTC, byiryu commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/main/MainPresenter.kt
> +    override fun onViewPrepared() {
수정했습니다

1096302

2020-03-20 12:49 UTC, byiryu commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/base/BasePresenter.kt
> +    var disposable: Disposable? = null
처음에 만들때 그렇게 해보려고 했는데.. 사용법을 아직 잘 몰라서 안했었는데 
이렇게 하는게 맞는지 잘 모르겠습니다.


c0cf0d4

2020-03-20 12:50 UTC, byiryu commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/base/BasePresenter.kt
> +    override fun onDetach() {
수정했습니다

d7cecee

2020-03-20 12:50 UTC, byiryu commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/main/MainPresenter.kt
> +    override fun onViewPrepared() {
867549a

2020-03-21 03:41 UTC, sjjeong commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/base/BasePresenter.kt
> +    var disposable: Disposable? = null
이렇게하면 null이라서 add가 되지 않습니다.
```kotlin
val compositeDisposable = CompositeDisposable()
```
로 선언해서 사용하세요

2020-03-21 03:42 UTC, sjjeong commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/base/BasePresenter.kt
> +    override fun onAttach(view: V) {
모든 Activity가 onCreate에서 onAttach를 호출해주고 있는 형태로 구현하셨더라구요

그러면 BaseActivity에서 해준다면 BaseActivity를 상속받는 Activity들이 매번 호출 해줄 필요가 없는 거죠
presenter는 abstract val로 만든다면 BaseActivity에서 만들어줄 필요가 없습니다.

2020-03-21 07:02 UTC, byiryu commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/base/BasePresenter.kt
> +    override fun onAttach(view: V) {
오우... 잘 안되네요.. 수정은 햇습니다만 맞게 했는지 잘 모르겠습니다.

BaseActivity에서 presenter 타입을 어떻게 지정해야 할지 잘 안되네요. 


deb6113

2020-03-21 07:03 UTC, byiryu commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/base/BasePresenter.kt
> +    var disposable: Disposable? = null
수정했습니다.. 한번에 커밋을 해버려서.. 죄송합니다

deb6113

2020-03-21 07:20 UTC, byiryu commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/main/MainPresenter.kt
> +    override fun onViewPrepared() {
deb6113 부분에서 
로직 수정으로 onAttach를 override하면 binding이 되기 전에 세팅을 하게되서 
새로 수정해습니다.
8336e20

2020-03-21 07:46 UTC, sjjeong commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/base/BasePresenter.kt
> +    override fun onAttach(view: V) {
음 현재 구조에서는 수정하기 조금 어려운 부분이 있네요 일단 넘기겠습니다.

2020-03-21 07:46 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-03-21 11:21 UTC, merged