HW-1 코인 가격 보기 앱 제작
sjjeong/GoogryAndroidArchitecutreStudy pull request #54
Opened 2019-06-09 12:17 UTC by zion830

2019-06-10 14:51 UTC, Nanamare commented
개인적인 일이 있어 리뷰를 못하고 있는데, 내일 꼭 하도록하겠습니다!
늦어져서 죄송합니다. 과제도 올리도록하겠습니다

2019-06-10 15:28 UTC, zion830 commented
@Nanamare 네 괜찮습니다 ㅎㅎ 알겠습니다 ~ !

2019-06-11 14:38 UTC, Nanamare requested changes

2019-06-11 14:38 UTC, Nanamare commented on zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/adapter/CoinRecyclerViewAdapter.kt
> +            coinChangeRateText.textColor = if (data.signedChangeRate > 0) {
when 문을 사용하면 어떨까 싶습니다!

2019-06-11 14:40 UTC, Nanamare commented
깔끔하게 잘 짜셔서 코멘트 달 것이 없는 것 같습니다?!
👍

2019-06-11 15:16 UTC, sjjeong commented
@Nanamare 
request changed하시면 label도 answer needed로 변경해주세요.
그래야 pr주인이 리뷰가 끝난걸 보고 변경할 수 있습니다.

2019-06-11 15:22 UTC, zion830 commented on zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/adapter/CoinRecyclerViewAdapter.kt
> +            coinChangeRateText.textColor = if (data.signedChangeRate > 0) {
when문으로 변경했습니다 ㅎㅎ
9a77568

2019-06-11 15:26 UTC, sjjeong commented on zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/adapter/CoinRecyclerViewAdapter.kt
> +            coinChangeRateText.textColor = if (data.signedChangeRate > 0) {
@zion830 
현성님의 의도는 아마
```kotlin
when  {
    data.signedChangeRate > 0 -> Color.BLUE
    data.signedChangeRate < 0 -> Color.RED
    else -> Color.BLACK
}
```
이지 않을까 싶습니다.
(아니면 말구요...)

2019-06-11 15:36 UTC, zion830 commented on zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/adapter/CoinRecyclerViewAdapter.kt
> +            coinChangeRateText.textColor = if (data.signedChangeRate > 0) {
현성님의 의도대로 수정했습니다 ㅎㅎ
f1b843c

2019-06-11 15:44 UTC, sjjeong commented
@zion830 
리뷰 반영 했다면 reviewer가 확인 할 수 있도록 label을 Review Needed로 수정해주세요.

2019-06-12 16:44 UTC, sjjeong requested changes
code style에 xml도 Set from..으로 Android 설정하고 layout 코드들 reformat하는 작업도 해주세요.

2019-06-12 16:44 UTC, sjjeong commented on zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/util/NumberFormatUtil.kt
> +    fun skipUnderMillions(num: Double): String = if (num < 1000000) {
=과 if 사이에 line break를 추가 하면 더 보기 좋은 코드가 됩니다.

2019-06-12 16:44 UTC, sjjeong commented on zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/util/NumberFormatUtil.kt
> +    fun skipUnderMillions(num: Double): String = if (num < 1000000) {
1000000보다 1_000_000이 한눈에 보기 좋습니다.
또한 해당 값을 다른곳에서도 쓴다면 상수로 빼는게 좋습니다.

2019-06-12 16:44 UTC, sjjeong commented on zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/util/NumberFormatUtil.kt
> +    fun insertComma(num: Number): String = df.format(num).toString()
format()의 return이 String이어서 toString은 필요 없습니다.

2019-06-12 16:44 UTC, sjjeong commented on zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/util/NumberFormatUtil.kt
> +        var type = ""
```kotlin
fun getPercent(num: Double): String {
    val (type, percent) =
        when {
            num < 0 -> "▼" to -num
            num > 0 -> "▲" to num
            else -> "" to num
        }
    return String.format("%s %.2f%%", type, percent * 100)
}
```
이렇게 바꿔보면 어떨까요?

2019-06-12 16:44 UTC, sjjeong commented on zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/network/RetrofitBuilder.kt
> +        return service ?: initService()
service가 set되는 시점이 없어서 initService()가 계속 호출 됩니다.
service가 사용 될 때 초기화 해주고 싶다면 lazy패턴에 대해 알아보고 적용해주세요

2019-06-12 16:44 UTC, sjjeong commented on zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/network/RetrofitBuilder.kt
> +        builder.connectTimeout(TIME_OUT_SEC, TimeUnit.SECONDS)
BuilderPattern은 함수가 Builder 클래스를 return하기 때문에 변수로 선언해서 사용할 필요가 없습니다.

2019-06-12 16:44 UTC, sjjeong commented on zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/adapter/CoinRecyclerViewAdapter.kt
> +    var coinList: ArrayList<TickerModel>
private로 해서 외부에서 접근을 막아주세요.

2019-06-12 16:44 UTC, sjjeong commented on zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/adapter/CoinRecyclerViewAdapter.kt
> +    constructor(tickers: ArrayList<TickerModel>) : super() {
생성자로 외부에서 list를 받지 말아주세요.

2019-06-12 16:44 UTC, sjjeong commented on zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/adapter/CoinRecyclerViewAdapter.kt
> +    inner class CoinItemViewHolder(private var view: View) : RecyclerView.ViewHolder(view) {
RecyclerView.ViewHolder에 itemView가 있기 때문에 view를 var로 선언해서 사용할 필요가 없습니다.

2019-06-12 16:44 UTC, sjjeong commented on zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/adapter/CoinRecyclerViewAdapter.kt
> +            val coinNameText = view.tv_coin_name as TextView
with(view){}를 사용하면 view.을 매번 사용할 필요가 없게 됩니다.

2019-06-12 16:44 UTC, sjjeong commented on zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/activity/MainActivity.kt
> +        coinAdapter.coinList = ArrayList(coinData)
외부에서 만든 List 객체를 adapter 내부에서 사용하지 말아주세요.

2019-06-12 16:44 UTC, sjjeong commented on zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/activity/MainActivity.kt
> +                setCoinInfo(response.body() ?: listOf())
response.body()가 null인 경우도 throwable과 같이 에러처리 해주세요

2019-06-12 16:44 UTC, sjjeong commented on zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/activity/MainActivity.kt
> +                val marketStr = marketList.joinToString().replace(" ", "")
joinToString(",")를 사용하면 replace하지 않아도 됩니다.

2019-06-12 16:45 UTC, sjjeong commented
@Nanamare 
Mentor Needed 라벨은 없었지만 리뷰 먼저 진행 했습니다.
현성님도 리뷰 진행해주세요

2019-06-13 02:50 UTC, zion830 commented
@dino
우왓 엄청 꼼꼼한 리뷰 감사합니다!
맞춰서 수정하도록 하겠습니다 :-)

2019-06-13 16:40 UTC, zion830 commented on zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/util/NumberFormatUtil.kt
> +    fun skipUnderMillions(num: Double): String = if (num < 1000000) {
수정했습니다!
004c665

2019-06-13 16:41 UTC, zion830 commented on zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/util/NumberFormatUtil.kt
> +    fun skipUnderMillions(num: Double): String = if (num < 1000000) {
리터럴에 언더바를 넣을 수 있다는걸 첨 알았네요 ㅎㅎ
수정하였습니다!
004c665

2019-06-13 16:42 UTC, zion830 commented on zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/util/NumberFormatUtil.kt
> +    fun insertComma(num: Number): String = df.format(num).toString()
수정했습니다~
8cc22c0

2019-06-13 16:42 UTC, zion830 commented on zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/util/NumberFormatUtil.kt
> +        var type = ""
수정했습니다~
004c665

2019-06-13 16:42 UTC, zion830 commented on zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/network/RetrofitBuilder.kt
> +        return service ?: initService()
lazy패턴 적용하여 수정했습니다~
15e574d

2019-06-13 16:43 UTC, zion830 commented on zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/network/RetrofitBuilder.kt
> +        builder.connectTimeout(TIME_OUT_SEC, TimeUnit.SECONDS)
변수 삭제했습니다~
35a5f48

2019-06-13 16:43 UTC, zion830 commented on zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/adapter/CoinRecyclerViewAdapter.kt
> +    var coinList: ArrayList<TickerModel>
수정했습니다~
6d9d726

2019-06-13 16:44 UTC, zion830 commented on zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/adapter/CoinRecyclerViewAdapter.kt
> +    constructor(tickers: ArrayList<TickerModel>) : super() {
수정했습니다!
6748e8d

2019-06-13 16:45 UTC, zion830 commented on zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/adapter/CoinRecyclerViewAdapter.kt
> +    inner class CoinItemViewHolder(private var view: View) : RecyclerView.ViewHolder(view) {
val로 수정했습니다~
9ab867f

2019-06-13 16:45 UTC, zion830 commented on zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/adapter/CoinRecyclerViewAdapter.kt
> +            val coinNameText = view.tv_coin_name as TextView
with 사용해서 수정했습니다!
fe0b935

2019-06-13 16:45 UTC, zion830 commented on zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/activity/MainActivity.kt
> +        coinAdapter.coinList = ArrayList(coinData)
수정했습니다..! 만 맞게 고친건지는 잘 모르겠네요 ㅜ
c8c3d41

2019-06-13 16:46 UTC, zion830 commented on zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/activity/MainActivity.kt
> +                setCoinInfo(response.body() ?: listOf())
추가 했습니다!
0bfe8bb

2019-06-13 16:46 UTC, zion830 commented on zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/activity/MainActivity.kt
> +                val marketStr = marketList.joinToString().replace(" ", "")
수정했습니다~
0b945f1

2019-06-13 16:46 UTC, zion830 commented
레이아웃 파일에 reformat 적용 했습니다!
10ffde7

2019-06-14 13:36 UTC, Nanamare approved these changes

2019-06-14 13:37 UTC, Nanamare commented
@sjjeong @zion830 리뷰 다 봤습니다! 멋지네요:)

2019-06-14 14:31 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-06-14 14:39 UTC, merged