HW-4 DataBinding 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #543
Opened 2020-03-23 08:04 UTC by mtjin

2020-03-23 14:52 UTC, kangraemin requested changes

2020-03-23 14:52 UTC, kangraemin commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/search/MovieSearchActivity.kt
> +        binding.rvMovies.layoutManager = linearLayoutManager
LayoutManager는 xml에서 설정 할 수 있어요

2020-03-23 14:52 UTC, kangraemin commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/search/MovieAdapter.kt
> +            binding.movie = movie
binding.executePendingBindings() 을 추가하면 좋을 것 같아요 ( 수업시간에 들었던 대로 )

2020-03-23 14:52 UTC, kangraemin commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/res/layout/activity_movie_search.xml
> +            app:layout_constraintTop_toTopOf="parent" />
xml에서도 텍스트는 string.xml에서 관리해주는 습관이 좋아요

string.xml에서 텍스트를 관리하면, 기기의 언어가 바뀔 때 바뀐 언어의 string.xml에서 id에 해당하는 텍스트값을 가져와 자연스럽게 다국어 지원이 가능하기도 해요 
 
ex)
values-ko/string.xml 
<string name="login_btn">로그인</string>

values-en/string.xml
<string name="login_btn">login</string>

그리고 <Button>의 text가 android:text="@string/login_btn"이면, 기기의 설정이 영어일땐 login을, 한글일 땐 로그인을 가져오게 되요

2020-03-23 14:55 UTC, kangraemin commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/res/layout/activity_movie_search.xml
> +            app:layout_constraintTop_toTopOf="parent" />
android studio 에서 
Analyze - Run Inspection by Name 에서 
hard coded string / hard coded text를 검색하면 내 프로젝트에 하드 코딩된 텍스트나 스트링 값을 쉽게 검색할 수 있기도 합니다 ㅎㅎ

2020-03-24 04:24 UTC, mtjin commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/search/MovieSearchActivity.kt
> +        binding.rvMovies.layoutManager = linearLayoutManager
5d6aff2
수정했습니다.

2020-03-24 04:24 UTC, mtjin commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/search/MovieAdapter.kt
> +            binding.movie = movie
055f20d
수정했습니다.

2020-03-24 13:24 UTC, kangraemin requested changes

2020-03-24 13:24 UTC, kangraemin commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/search/MovieSearchActivity.kt
> +            EndlessRecyclerViewScrollListener(binding.rvMovies.layoutManager as LinearLayoutManager) {
커밋에 xml에 linearlayoutManager 추가하는 코드가 빠진것같아요 ~~

2020-03-24 14:45 UTC, mtjin commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/search/MovieSearchActivity.kt
> +            EndlessRecyclerViewScrollListener(binding.rvMovies.layoutManager as LinearLayoutManager) {
xml에 linearlayoutManager 추가 되있습니다~
![image](https://user-images.githubusercontent.com/37071007/77438723-827a7780-6e29-11ea-9e30-45d938250960.png)

2020-03-24 15:03 UTC, kangraemin approved these changes

2020-03-24 15:03 UTC, kangraemin commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/search/MovieSearchActivity.kt
> +            EndlessRecyclerViewScrollListener(binding.rvMovies.layoutManager as LinearLayoutManager) {
앗그렇군요 ... 제가못봤었네요 @sooakim approve하였습니다 ~~

2020-03-25 13:43 UTC, sjjeong commented
@kangraemin 
approve 하시면 mentor needed 라벨도 추가해주셔야 합니다.

2020-03-25 14:48 UTC, sooakim requested changes

2020-03-25 14:48 UTC, sooakim commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/utils/DataBindingAdapters.kt
> +    Glide.with(imageView.context).load(url)
Glide.with를 쓸 때 imageView.context대신 imageView를 넣어주세요.
with를 통해 넘어오는 파라미터의 생명주기에 따라 RequestManager 인스턴스를 자동으로 관리 해주는데 imageView.context를 쓰면 View가 어디에 위치하던지 activity의 생명주기를 따르게 돼요.

2020-03-25 14:48 UTC, sooakim commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/utils/DataBindingAdapters.kt
> +    }
이부분은 HtmlCompat을 써서 버전 분기 없이 한줄로 줄 일 수 있어요.

2020-03-25 14:48 UTC, sooakim commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/utils/DataBindingAdapters.kt
> +@BindingAdapter("bind:htmlText")
android:text와 같이 기본 attr에 대한 어댑터를 사용할 때는 prefix가 필요하지만 그 경우가 아니라면 bind prefix를 붙일 필요가 없어요.

2020-03-25 14:48 UTC, sooakim commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/utils/DataBindingAdapters.kt
> +@BindingAdapter("bind:urlImage")
bind: 제거

2020-03-25 14:48 UTC, sooakim commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/utils/DataBindingAdapters.kt
> +@BindingAdapter("bind:movieRating")
bind: 제거

2020-03-25 15:04 UTC, mtjin commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/utils/DataBindingAdapters.kt
> +@BindingAdapter("bind:htmlText")
88f5031
수정했습니다.

2020-03-25 15:05 UTC, mtjin commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/utils/DataBindingAdapters.kt
> +@BindingAdapter("bind:urlImage")
88f5031

2020-03-25 15:05 UTC, mtjin commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/utils/DataBindingAdapters.kt
> +@BindingAdapter("bind:movieRating")
88f5031

2020-03-25 15:05 UTC, mtjin commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/utils/DataBindingAdapters.kt
> +    }
af549d9
수정했습니다.

2020-03-25 15:05 UTC, mtjin commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/utils/DataBindingAdapters.kt
> +    Glide.with(imageView.context).load(url)
1aef5d3
수정했습니다.

2020-03-25 15:40 UTC, sooakim commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/utils/DataBindingAdapters.kt
> +@BindingAdapter("bind:movieRating")
@mtjin xml에서는 유지해주세요.
BindingAdapter에서 bind를 붙이지 않았더라도, xml에서는 bind를 붙일 수 있어요.
사실 xml에서는 아무거나 같다붙여도 동작하고, prefix가 없어도 동작해요. bind는 아무의미가 없기때문이죠. xml에서 bind를 붙여주는건 단순히 다른 attr과의 구분을 줘서 가독성을 높이기위해서에요.

2020-03-25 16:00 UTC, mtjin commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/utils/DataBindingAdapters.kt
> +@BindingAdapter("bind:movieRating")
af06d28
수정했습니다.

2020-03-26 06:08 UTC, sooakim approved these changes

2020-03-27 14:25 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-03-28 04:37 UTC, merged