HW-4 Use databinding
sjjeong/GoogryAndroidArchitecutreStudy pull request #546
Opened 2020-03-23 14:34 UTC by kangraemin

2020-03-24 03:36 UTC, mtjin requested changes
@kangraemin

2020-03-24 03:36 UTC, mtjin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/adapter/SearchResultAdapter.kt
> +        private val binding: AdapterSearchResultBinding
보통 리사이클러뷰 아이템 xml은 item_ 키워드를 붙여주지 않나요? 취향차이라 수정 안하셔도 될 것 같긴합니다.

2020-03-24 03:36 UTC, mtjin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/util/BIndingAdapter.kt
> +fun getImageFromUrl(view: ImageView, url: String) {
개인적인 생각으로는 밑의 setRating() 처럼 뷰에 값을 세팅하는 작업인데 setImageFromUrl() 이 더 어울릴 것 같습니다.

2020-03-24 03:36 UTC, mtjin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/util/BIndingAdapter.kt
> +    ratingBar.rating = rating.toFloat() / 2
`(rating.toFloatOrNull() ?: 0f) / 2`
 로 혹시 모를 예외처리를 할 수 있을 것 같습니다.

2020-03-24 13:32 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/util/BIndingAdapter.kt
> +    ratingBar.rating = rating.toFloat() / 2
추가했습니다
671e308

2020-03-24 13:32 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/util/BIndingAdapter.kt
> +fun getImageFromUrl(view: ImageView, url: String) {
수정했습니다 ~
af9ab3e

2020-03-24 14:10 UTC, mtjin approved these changes
@sooakim 
approve 했습니다.~

2020-03-25 13:43 UTC, sjjeong commented
@mtjin 
approve 하시면 mentor needed도 추가해주셔야 합니다.

2020-03-25 14:51 UTC, mtjin commented
> @mtjin
> approve 하시면 mentor needed도 추가해주셔야 합니다.

2020-03-25 14:51 UTC, sooakim requested changes

2020-03-25 14:51 UTC, sooakim commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/util/BIndingAdapter.kt
> +@BindingAdapter("bind:imageFromUrl")
xml에서 bind를 붙이는건 단순히 다른 속성과의 구분을 위해서에요. 어댑터에서는 bind를 붙여줄 필요 없어요.

2020-03-25 14:51 UTC, sooakim commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/util/BIndingAdapter.kt
> +@BindingAdapter("bind:rating")
bind:제거

2020-03-25 14:51 UTC, sooakim commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/util/BIndingAdapter.kt
> +@BindingAdapter("bind:fromHtml")
bind:제거

2020-03-25 14:51 UTC, sooakim commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/util/BIndingAdapter.kt
> +    }
이부분은 HtmlCompat으로 대체가능해요.

2020-03-25 14:53 UTC, mtjin commented
quote reply 했다가 close 됬었네요 다시 reopen했습니다.

2020-03-26 13:04 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/util/BIndingAdapter.kt
> +@BindingAdapter("bind:imageFromUrl")
수정했습니다
b30efaa

2020-03-26 13:04 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/util/BIndingAdapter.kt
> +@BindingAdapter("bind:rating")
수정했습니다
b30efaa

2020-03-26 13:04 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/util/BIndingAdapter.kt
> +@BindingAdapter("bind:fromHtml")
수정했습니다
b30efaa

2020-03-26 13:04 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/util/BIndingAdapter.kt
> +    }
수정했습니다
a7ec35d

2020-03-26 13:34 UTC, sooakim commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/util/BIndingAdapter.kt
> +@BindingAdapter("bind:imageFromUrl")
@kangraemin xml에서는 제거할 필요 없어요

2020-03-27 11:42 UTC, raeminkang commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/util/BIndingAdapter.kt
> +@BindingAdapter("bind:imageFromUrl")
수정했습니다 
404708b

2020-03-27 15:30 UTC, sooakim approved these changes

2020-03-28 08:51 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-03-28 10:48 UTC, merged