HW-4 Databindng 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #547
Opened 2020-03-24 13:37 UTC by byiryu

2020-03-24 21:42 UTC, tjdwlsl1021 approved these changes
data태그에 내용이 없는 부분만 확인 부탁드립니다.
approve했습니다.

2020-03-24 21:42 UTC, tjdwlsl1021 commented on 2003/byiryu/app/src/main/res/layout/activity_intro.xml
> +    <data>
data태그에 내용이 없어서, 지워야하는건지 확인 부탁드립니다.

2020-03-25 12:51 UTC, sjjeong commented on 2003/byiryu/app/src/main/res/layout/activity_intro.xml
> +    <data>
크게 상관 없는 부분 입니다.

2020-03-25 13:42 UTC, sjjeong requested changes

2020-03-25 13:42 UTC, sjjeong commented on 2003/byiryu/app/src/main/java/com/byiryu/study/model/Repository.kt
> +                    }
이건 왜 이렇게 넣으셨나요?

2020-03-25 13:42 UTC, sjjeong commented on 2003/byiryu/app/src/main/java/com/byiryu/study/model/Repository.kt
> +//            }
doOnSuccess로 save만 시켜줘도 됩니다.

2020-03-25 13:42 UTC, sjjeong commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/main/MainPresenter.kt
> +    override fun getPrevQuery(): String {
이전 코드처럼 view.setPrevQuery()로 해주세요

2020-03-25 13:42 UTC, sjjeong commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/main/MainRecyclerAdapter.kt
> +class MainRecyclerAdapter constructor(val onViewClickListener: OnViewClickListener) :
constructor는 생략이 가능합니다.

2020-03-25 13:42 UTC, sjjeong commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/main/MainRecyclerAdapter.kt
> +            setVariable(BR.itemClickListener, onViewClickListener)
executePendingBindings()를 호출해주세요

2020-03-25 13:42 UTC, sjjeong commented on 2003/byiryu/app/src/main/res/layout/activity_login.xml
> +        xmlns:app="http://schemas.android.com/apk/res-auto"
xmlns는 layout쪽에 있어도 됩니다.

제가 알려드린 방법으로 convert하면 layout에 생기게 됩니다.

2020-03-25 14:08 UTC, byiryu commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/main/MainPresenter.kt
> +    override fun getPrevQuery(): String {
binding 할때 한번에 세팅하고 싶어서 저렇게 한건데

view.setPreQuery를 쓰면 binding 을 전역으로 뺴야되는게 싫어서 했습니다

말씀하신 방법이 더 적합한가요?

2020-03-25 14:11 UTC, byiryu commented on 2003/byiryu/app/src/main/java/com/byiryu/study/model/Repository.kt
> +                    }
으이.. 테스트한다고 잠시 넣었던건데 못뺏네요.

수정했습니다 
5d968ca

2020-03-25 14:12 UTC, byiryu commented on 2003/byiryu/app/src/main/java/com/byiryu/study/model/Repository.kt
> +//            }
오호.. 한참 고민했는데 감사합니다.
5d968ca

2020-03-25 14:12 UTC, byiryu commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/main/MainRecyclerAdapter.kt
> +            setVariable(BR.itemClickListener, onViewClickListener)
수정했습니다

5586dcf

2020-03-25 14:12 UTC, byiryu commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/main/MainRecyclerAdapter.kt
> +class MainRecyclerAdapter constructor(val onViewClickListener: OnViewClickListener) :
수정했습니다.
6deb87a

2020-03-25 14:12 UTC, byiryu commented on 2003/byiryu/app/src/main/res/layout/activity_login.xml
> +        xmlns:app="http://schemas.android.com/apk/res-auto"
저는 convert가 왜 안될까요 ..
74b1c88

2020-03-25 14:14 UTC, sjjeong commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/main/MainPresenter.kt
> +    override fun getPrevQuery(): String {
네  View와 Presenter관계는 뭔가를 가져오기 보다 뭔가를 하게끔 해야 합니다.

2020-03-25 14:21 UTC, byiryu commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/main/MainPresenter.kt
> +    override fun getPrevQuery(): String {
수정했습니다
041eaf3

2020-03-25 14:27 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-03-25 14:39 UTC, merged