HW-1 코인헬퍼 따라잡기
sjjeong/GoogryAndroidArchitecutreStudy pull request #55
Opened 2019-06-10 10:28 UTC by NackUn

2019-06-10 13:22 UTC, BeokBeok reviewed
리뷰를 추가하였습니다.

2019-06-10 13:22 UTC, BeokBeok commented on NackUn/StudyFirst/.idea/codeStyles/Project.xml
>  </component>
.idea 폴더에 있는 내용은 빌드 시 자동으로 생성되므로, gitignore에 추가 요청 드립니다.

2019-06-10 13:22 UTC, BeokBeok commented on NackUn/StudyFirst/.idea/codeStyles/codeStyleConfig.xml
>  </component>
.idea 폴더에 있는 내용은 빌드 시 자동으로 생성되므로, gitignore에 추가 요청 드립니다.

2019-06-10 13:22 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/MainActivity.kt
> +        val retrofit = Retrofit.Builder()
기능별로 함수 단위로 쪼개서 작성하시는 게 좋아보입니다.

2019-06-10 13:22 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/MainActivity.kt
> +                if (response.body() != null) {
널체크를 ? 연산자를 사용하는 것이 좋아 보입니다.

2019-06-10 13:22 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/MainActivity.kt
> +                                    if (response.body() != null) {
널체크를 ? 연산자를 사용하는 것이 좋아 보입니다.

2019-06-10 13:22 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/MainActivity.kt
> +                    Toast.makeText(applicationContext, "끝", Toast.LENGTH_SHORT).show()
의미가 없어보이는 토스트로 보입니다.

2019-06-10 13:22 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/network/Retrofit_interface.kt
> +interface Retrofit_interface {
인터페이스명은 가급적 형용사로 명명하는 것을 추천합니다.

2019-06-10 13:22 UTC, BeokBeok commented on NackUn/StudyFirst/gradle.properties
> +kotlin.code.style=official
gitignore 에 추가 하는 것이 좋아 보입니다.

2019-06-10 13:22 UTC, BeokBeok commented on NackUn/StudyFirst/gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-5.4.1-all.zip
gitignore에 추가하는 것이 좋아 보입니다.

2019-06-10 13:22 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/res/layout/activity_main.xml
> +</RelativeLayout>
Depth를 보기가 불편합니다.
석준님이 말한 코드 포메터를 사용하거나
별도로 정렬하였으면 좋겠습니다.

2019-06-10 13:22 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/res/layout/activity_main.xml
> +              android:text="업비트(Upbit)"
레이아웃에서 사용하는 String은 가급적 Strings.xml에 저장하여 쓰는 것을 권장합니다.

2019-06-10 13:22 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/market/Ticker.kt
> +)
UI에서 표현하지 않는 변수는 사용하지 않는 것이 좋아 보입니다.

2019-06-10 13:22 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/TickerAdapter.kt
> +        tickerViewHolder?.comparePrice?.text = (items.get(p1).signed_change_price / 100000).toString() + "%"
div 함수 사용을 권장합니다

2019-06-10 13:22 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/res/layout/ticker_item.xml
> +</LinearLayout>
석준님이 말한 코드 포메터를 사용하거나
별도로 정렬하였으면 좋겠습니다.

2019-06-10 14:19 UTC, sjjeong commented on NackUn/StudyFirst/.idea/codeStyles/Project.xml
>  </component>
이거는 괜찮습니다

2019-06-10 14:19 UTC, sjjeong commented on NackUn/StudyFirst/.idea/codeStyles/codeStyleConfig.xml
>  </component>
이거는 괜찮습니다

2019-06-10 14:23 UTC, sjjeong commented
@BeokBeok 
수정 할 것이 필요하다면 Comment 말고 Request changes로 summit review해주세요.
그리고 라벨도 Review Needed를 제거해주시고 Answer Needed를 추가해주세요.

2019-06-10 15:39 UTC, zion830 commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/TickerAdapter.kt
> +        tickerViewHolder?.comparePrice?.text = (items.get(p1).signed_change_price / 100000).toString() + "%"
지나가다 궁금해서 여쭤보는데요,
함수를쓰면 연산자보다 어떤점이 더 좋은가요?

2019-06-10 15:44 UTC, sjjeong commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/TickerAdapter.kt
> +        tickerViewHolder?.comparePrice?.text = (items.get(p1).signed_change_price / 100000).toString() + "%"
음 저도 이 부분은 궁금하네요

2019-06-10 15:45 UTC, sjjeong commented on NackUn/StudyFirst/gradle.properties
> +kotlin.code.style=official
이거는 괜찮습니다

2019-06-10 15:46 UTC, sjjeong commented on NackUn/StudyFirst/gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-5.4.1-all.zip
이거는 괜찮습니다

2019-06-11 01:16 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/TickerAdapter.kt
> +        tickerViewHolder?.comparePrice?.text = (items.get(p1).signed_change_price / 100000).toString() + "%"
signed_change_price 타입이 nullable 인 줄 알고 div 함수를 권장한 것이였는데
확인해보니 nullable 이 아니네요.
Resolve 처리 하겠습니다.

2019-06-11 04:01 UTC, BeokBeok requested changes
Request Change로 변경하였습니다.

2019-06-11 12:35 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/MainActivity.kt
> +        val retrofit = Retrofit.Builder()
수정 확인하였습니다.
bd5fba3e39e68bb72e2061d7b06e301371b56c5d

2019-06-11 12:35 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/MainActivity.kt
> +                if (response.body() != null) {
수정 확인하였습니다.
bd5fba3e39e68bb72e2061d7b06e301371b56c5d

2019-06-11 12:36 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/MainActivity.kt
> +                                    if (response.body() != null) {
수정 확인하였습니다.
bd5fba3e39e68bb72e2061d7b06e301371b56c5d

2019-06-11 12:37 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/res/layout/activity_main.xml
> +              android:text="업비트(Upbit)"
수정 확인하였습니다.
7d1e47d98589254aa8da304769335a3de337d24b

2019-06-11 12:37 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/market/Ticker.kt
> +)
수정 확인하였습니다.
7d1e47d98589254aa8da304769335a3de337d24b

2019-06-11 12:37 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/res/layout/ticker_item.xml
> +</LinearLayout>
수정 확인 하였습니다.
7d1e47d98589254aa8da304769335a3de337d24b

2019-06-11 12:37 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/res/layout/activity_main.xml
> +</RelativeLayout>
수정 확인 하였습니다.
7d1e47d98589254aa8da304769335a3de337d24b

2019-06-11 12:37 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/MainActivity.kt
> +                    Toast.makeText(applicationContext, "끝", Toast.LENGTH_SHORT).show()
수정 확인 하였습니다.
bd5fba3e39e68bb72e2061d7b06e301371b56c5d

2019-06-11 12:38 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/network/Retrofit_interface.kt
> +interface Retrofit_interface {
수정 확인 하였습니다.
bd5fba3e39e68bb72e2061d7b06e301371b56c5d

2019-06-11 12:38 UTC, BeokBeok submitted a review, later dismissed
변경 사항 확인 하였습니다.

2019-06-11 15:21 UTC, sjjeong commented
@BeokBeok 
approve 하셨다면 mentor needed 라벨을 추가해주세요

2019-06-12 16:18 UTC, sjjeong requested changes
commit은 리뷰마다 하나씩 나눠서 해주세요.

2019-06-12 16:18 UTC, sjjeong commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/market/Ticker.kt
> +    val acc_trade_price_24h: Double,
Property는 camelCase로 작성해주세요

2019-06-12 16:18 UTC, sjjeong commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/network/UpbitCommunicable.kt
> +    @GET("https://api.upbit.com/v1/market/all")
https://api.upbit.com/v1/ 까지는 지워주세요.

2019-06-12 16:18 UTC, sjjeong commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/network/UpbitCommunicable.kt
> +interface UpbitCommunicable {
Upbit Api에 대한 interface이기 때문에 UpbitApi가 더 좋을 것 같습니다.

2019-06-12 16:18 UTC, sjjeong commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/MainActivity.kt
> +                var tt = findViewById<TextView>(v!!.id)
v를 casting 해서 사용해주세요.

2019-06-12 16:18 UTC, sjjeong commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/MainActivity.kt
> +                marketKRW.setTextColor(Color.parseColor("#bebbb4"))
color 값을 colors.xml로 빼서 사용해주세요.

2019-06-12 16:18 UTC, sjjeong commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/MainActivity.kt
> +        val retrofit = Retrofit.Builder()
Retrofit은 한번만 생성해주면 됩니다.
initView()를 호출 할 때마다 생성하지 말아주세요.

2019-06-12 16:18 UTC, sjjeong commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/MainActivity.kt
> +        val service = retrofit.create(UpbitCommunicable::class.java)
이부분도 매번 생성 할 필요가 없습니다.

2019-06-12 16:18 UTC, sjjeong commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/MainActivity.kt
> +                    var markets: String = ""
:String은 작성하지 않아도 됩니다.

2019-06-12 16:18 UTC, sjjeong commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/MainActivity.kt
> +                    response.body()?.filter { it.market.startsWith(marketLike) }
https://kotlinlang.org/docs/reference/coding-conventions.html#chained-call-wrapping
참고해서 수정해주세요.

2019-06-12 16:18 UTC, sjjeong commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/MainActivity.kt
> +                    markets = markets.substring(0, markets.length - 1)
query만드는 코드는
```kotlin
val query =
    it.filter { item ->
        item.market.startsWith(market.marketName, true)
    }
        .joinToString { marketModel ->
            marketModel.market
        }
```
로 작성 할 수 있습니다.

2019-06-12 16:18 UTC, sjjeong commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/MainActivity.kt
> +                                    tickerRecyclerView.layoutManager = LinearLayoutManager(this@MainActivity)
LayoutManager를 data가 올 때마다 새로 만들어서 넣어줄 필요가 없습니다.

2019-06-12 16:18 UTC, sjjeong commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/MainActivity.kt
> +                                    tickerRecyclerView.adapter = TickerAdapter(it, this@MainActivity)
Adapter를 data가 올 때마다 새로 만들어서 넣어줄 필요가 없습니다.

2019-06-12 16:18 UTC, sjjeong commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/TickerAdapter.kt
> +class TickerAdapter(val items: ArrayList<Ticker>, val context: Context) : RecyclerView.Adapter<TickerViewHolder>() {
Adapter 생성자로 context와 items를 받지 말아주세요.
외부에서 context를 전달 받을 필요가 없습니다.
items은 함수를 통해서 전달 받게 해주세요.
Adpater 내부에서는 외부에서 받은 list의 객체를 가지고 있지 말아주세요.

2019-06-12 16:18 UTC, sjjeong commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/TickerAdapter.kt
> +    var color: String = "";
; 제거해주세요.

2019-06-12 16:18 UTC, sjjeong commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/TickerAdapter.kt
> +        return items.size
함수 내부에 return만 있다면 = 를 사용해서 축약 할 수 있습니다.
```kotlin
override fun getItemCount() = items.size
```

2019-06-12 16:18 UTC, sjjeong commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/TickerAdapter.kt
> +        tickerViewHolder.tickerName.text = items.get(p1).market.substring(
get은 []로 사용할 수 있습니다.

2019-06-12 16:18 UTC, sjjeong commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/TickerAdapter.kt
> +    override fun onBindViewHolder(tickerViewHolder: TickerViewHolder, p1: Int) {
onBindViewHolder에서 작업하는 내용들을 ViewHolder 내부 함수를 만들어서 이동시켜주세요.
onBindViewHolder에서는
```kotlin
holder.bind(items[position])
```
정도만 있으면 됩니다.

2019-06-12 16:18 UTC, sjjeong commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/MainActivity.kt
> +    fun initView(marketLike: String): Unit {
Unit 제거해주세요

2019-06-13 05:17 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/market/Ticker.kt
> +    val acc_trade_price_24h: Double,
c5fcad9
수정하였습니다

2019-06-13 05:18 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/network/UpbitCommunicable.kt
> +    @GET("https://api.upbit.com/v1/market/all")
7cb843c
수정하였습니다.

2019-06-13 05:18 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/network/UpbitCommunicable.kt
> +interface UpbitCommunicable {
dc89bfb
변경하였습니다.

2019-06-13 05:18 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/MainActivity.kt
> +                var tt = findViewById<TextView>(v!!.id)
0123005
변경하였습니다.

2019-06-13 05:19 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/MainActivity.kt
> +                marketKRW.setTextColor(Color.parseColor("#bebbb4"))
aefa3de
수정하였습니다.

2019-06-13 05:19 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/TickerAdapter.kt
> +    var color: String = "";
1d9c2e2
제거하였습니다.

2019-06-13 05:19 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/TickerAdapter.kt
> +        return items.size
832936c
수정했습니다.

2019-06-13 05:19 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/TickerAdapter.kt
> +        tickerViewHolder.tickerName.text = items.get(p1).market.substring(
ccb1f14
수정했습니다.

2019-06-13 05:20 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/TickerAdapter.kt
> +    override fun onBindViewHolder(tickerViewHolder: TickerViewHolder, p1: Int) {
7eb3aad
수정했습니다.

2019-06-13 05:20 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/MainActivity.kt
> +    fun initView(marketLike: String): Unit {
175693a
제거했습니다.

2019-06-13 06:09 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/market/Ticker.kt
> +    val acc_trade_price_24h: Double,
4bf361f
재작성했습니다.

2019-06-13 14:16 UTC, sjjeong commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/MainActivity.kt
> +        val retrofit = Retrofit.Builder()
@NackUn

2019-06-13 14:16 UTC, sjjeong commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/MainActivity.kt
> +        val service = retrofit.create(UpbitCommunicable::class.java)
@NackUn

2019-06-13 14:16 UTC, sjjeong commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/MainActivity.kt
> +                    var markets: String = ""
@NackUn

2019-06-13 14:16 UTC, sjjeong commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/MainActivity.kt
> +                    response.body()?.filter { it.market.startsWith(marketLike) }
@NackUn

2019-06-13 14:16 UTC, sjjeong commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/MainActivity.kt
> +                    markets = markets.substring(0, markets.length - 1)
@NackUn

2019-06-13 14:16 UTC, sjjeong commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/MainActivity.kt
> +                                    tickerRecyclerView.layoutManager = LinearLayoutManager(this@MainActivity)
@NackUn

2019-06-13 14:16 UTC, sjjeong commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/MainActivity.kt
> +                                    tickerRecyclerView.adapter = TickerAdapter(it, this@MainActivity)
@NackUn

2019-06-13 14:16 UTC, sjjeong commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/TickerAdapter.kt
> +class TickerAdapter(val items: ArrayList<Ticker>, val context: Context) : RecyclerView.Adapter<TickerViewHolder>() {
@NackUn

2019-06-13 14:17 UTC, sjjeong commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/TickerAdapter.kt
> +        tickerViewHolder.tickerName.text = items.get(p1).market.substring(
해당 부분만 수정하면 되는게 아닙니다.
저렇게 사용되고 있는 코드 전부를 변경해주세요.

2019-06-13 14:19 UTC, sjjeong commented
@NackUn 
아직 수정이 덜 된 부분이 있습니다.

2019-06-13 16:17 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/MainActivity.kt
> +        val retrofit = Retrofit.Builder()
1e9c22e
수정하였습니다.

2019-06-13 16:18 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/MainActivity.kt
> +        val service = retrofit.create(UpbitCommunicable::class.java)
1e9c22e
retrofit과 service 같이 수정하였습니다.

2019-06-13 16:18 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/MainActivity.kt
> +                    var markets: String = ""
b9d5449
수정했습니다.

2019-06-13 16:19 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/MainActivity.kt
> +                    response.body()?.filter { it.market.startsWith(marketLike) }
9ea6bd5
참고해서 수정했습니다.

2019-06-13 16:19 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/MainActivity.kt
> +                    markets = markets.substring(0, markets.length - 1)
90dc511
이렇게 만드는 거였군요. 감사합니다.

2019-06-13 16:21 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/MainActivity.kt
> +                                    tickerRecyclerView.layoutManager = LinearLayoutManager(this@MainActivity)
e70156d
수정하였습니다.

2019-06-13 16:21 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/MainActivity.kt
> +                                    tickerRecyclerView.adapter = TickerAdapter(it, this@MainActivity)
e70156d
수정하였습니다.

2019-06-13 16:22 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/MainActivity.kt
> +                                    tickerRecyclerView.adapter = TickerAdapter(it, this@MainActivity)
f1f6956
재수정하였습니다.

2019-06-13 16:22 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/TickerAdapter.kt
> +class TickerAdapter(val items: ArrayList<Ticker>, val context: Context) : RecyclerView.Adapter<TickerViewHolder>() {
f1f6956
수정하였습니다.

2019-06-13 16:25 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/TickerAdapter.kt
> +class TickerAdapter(val items: ArrayList<Ticker>, val context: Context) : RecyclerView.Adapter<TickerViewHolder>() {
f1f6956
잘못 쓴 코드 삭제했습니다.

2019-06-14 07:40 UTC, NackUn commented
@sjjeong 
629f7c9
Optimize imports, Rearrange entries, Cleanup code 코드 정리와
26c97d1
노랑 부분도 수정하였습니다.

2019-06-14 14:34 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-06-14 15:11 UTC, BeokBeok approved these changes

2019-06-15 01:52 UTC, merged