HW-5 Pure MVVM
sjjeong/GoogryAndroidArchitecutreStudy pull request #550
Opened 2020-03-29 16:53 UTC by sooakim

2020-03-31 14:34 UTC, sjjeong requested changes

2020-03-31 14:34 UTC, sjjeong commented on 2003/sooakim/app/src/main/java/io/github/sooakim/ui/movie/SAMovieSearchViewModel.kt
> +    private val compositeDisposable: CompositeDisposable = CompositeDisposable()
compositeDisposable을 clear하는 부분이 없습니다.
Base쪽으로 빼는 것도 좋을 것 같습니다.

2020-03-31 16:05 UTC, sooakim commented on 2003/sooakim/app/src/main/java/io/github/sooakim/ui/movie/SAMovieSearchViewModel.kt
> +    private val compositeDisposable: CompositeDisposable = CompositeDisposable()
11cc431

2020-04-01 10:17 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-04-02 02:22 UTC, merged