HW-5 MVVM 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #553
Opened 2020-03-30 13:41 UTC by mtjin

MovieSearchActivity에 무한스크롤도 어떻게 처리할지 애매해서 일단 viewModel로 직접 호출하게 구현해놨습니다.
scrollListener = object :
            EndlessRecyclerViewScrollListener(binding.rvMovies.layoutManager as LinearLayoutManager) {
            override fun onLoadMore(page: Int, totalItemsCount: Int, view: RecyclerView?) {
                viewModel.requestPagingMovie(totalItemsCount + 1)
            }
        }

그리고 리사이클러뷰 클릭 이벤트도 현재 구현한거에서 다른 방식으로 바꿔야 되는건지 궁금합니다.
`movieAdapter = MovieAdapter { movie ->
            Intent(Intent.ACTION_VIEW, Uri.parse(movie.link)).takeIf {
                it.resolveActivity(packageManager) != null
            }?.run(this::startActivity)
        }`
처음이라 어렵네요... 리뷰 부탁드립니다.

2020-03-30 13:46 UTC, mtjin commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/search/MovieSearchActivity.kt
> +                viewModel.requestPagingMovie(totalItemsCount + 1)
메세지 남긴 부분입니다.

2020-03-30 13:51 UTC, mtjin commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/search/MovieSearchActivity.kt
> +                viewModel.requestPagingMovie(totalItemsCount + 1)
메세지 남긴 부분입니다. 이 위에 아이템클릭리스너 처리코드도 있습니다. 
수정된 라인은 한줄이라 그런지 다중라인으로 코멘트가 안달아지네요.

2020-03-31 15:20 UTC, kangraemin requested changes

2020-03-31 15:20 UTC, kangraemin commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/search/MovieSearchActivity.kt
> +            })
여기에서 lastPageMsg / emptyQueryMsg 가 false로 set 되면서 한번 더 콜백이 불리는 구조인것 같아 보여요

해당 observablefield를 재사용 하기 위해 초기화 해주는 작업 같은데, 제 생각엔 단순히 신호만 줄 것이라면 notifyChange()를 사용하는건 어떨 까 싶어요

lastPageMsg.notifyChange() / emptyQueryMsg.notifyChange() 를 뷰모델에서 불러주면, 각각 콜백 부분이 불리는데, 이렇게 사용하는게 어떨 까 싶어요

2020-03-31 15:20 UTC, kangraemin commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/search/MovieSearchActivity.kt
> +                viewModel.requestPagingMovie(totalItemsCount + 1)
음 .... 이것저것 찾아봤을때 리스너 등록은 액티비티에서 진행하는것이 맞는것 같아 문제 둘 다 문제 없어 보여요 ... 근데 저도 확신은 없네요

2020-04-01 04:05 UTC, mtjin commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/search/MovieSearchActivity.kt
> +            })
63fb252

2b371a0

17fe2ff
수정했습니다.

2020-04-01 06:52 UTC, byiryu commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/search/MovieSearchActivity.kt
> +            })
지나가다가.. 들러서 한글 써봅니당
모든 상태에 대한 ObserverField를 두는것보다 하나로 묶는 방법을 생각해보시면 콜백 코드가 많이 줄어들것 같습니다.
모든 값들이 다 쓰인다기 보다 어떤 상태에서 하나의 변수만 사용되는거 같거든요

2020-04-01 11:02 UTC, kangraemin commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/search/MovieSearchActivity.kt
> +            })
@byiryu
```
val msgFiled: ObservableField<MessageSet> = ObservableField()

    enum class MessageSet {
        LAST_PAGE,
        EMPTY_QUERY,
        ...
    }
```

뷰모델에서 이런식으로 묶어주고, 해당 옵저버 필드에 같은 값이 set될땐 notifyChange()를 불러주도록 구현해놓은뒤 액티비티 에서 받아도 될까요 ?

2020-04-01 11:03 UTC, kangraemin approved these changes
@sooakim approve 하였습니다 ~

2020-04-01 11:44 UTC, sjjeong commented
@sooakim 리뷰하시고 Mentor Needed는 제거하지 말아주세요

2020-04-02 02:46 UTC, sooakim requested changes

2020-04-02 02:46 UTC, sooakim commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/login/LoginViewModel.kt
> +    var successLogin: ObservableBoolean = ObservableBoolean(false)
아무 의미가 없는 값이면 ```ObservableBoolean```보다 ```ObservableField<Unit>```이 낫지 않을까요

2020-04-02 02:46 UTC, sooakim commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/search/MovieSearchActivity.kt
> +                viewModel.requestPagingMovie(totalItemsCount + 1)
커스텀 ```BindingAdapter```를 만들어서 xml을 통해 처리하는 방법도 있어요.

2020-04-02 02:46 UTC, sooakim commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/search/MovieSearchViewModel.kt
> +                        movieList.set(it as ArrayList<Movie>?)
뒤에서 set해주고 있기때문에 clear가 의미가 없어요.
clear를 지우면 ```ObservableField<ArrayList<Movie>>``` -> ```ObservableField<List<Movie>>```로 바꿀 수 있겠죠.

2020-04-02 02:46 UTC, sooakim commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/utils/DataBindingAdapters.kt
> +    Glide.with(context).load(url)
```suggestion
    Glide.with(this).load(url)
```

2020-04-02 03:49 UTC, mtjin commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/search/MovieSearchActivity.kt
> +            })
e95fef3
수정했습니다.

2020-04-02 05:52 UTC, mtjin commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/utils/DataBindingAdapters.kt
> +    Glide.with(context).load(url)
f739fdb
수정했습니다.

2020-04-02 05:53 UTC, mtjin commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/login/LoginViewModel.kt
> +    var successLogin: ObservableBoolean = ObservableBoolean(false)
e95fef3
먼저 위에 리뷰대로 수정했습니다.

2020-04-02 05:54 UTC, mtjin commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/search/MovieSearchViewModel.kt
> +                        movieList.set(it as ArrayList<Movie>?)
41943b5
수정했습니다.

2020-04-02 05:55 UTC, mtjin commented
41943b5
무한스크롤 관련해서 수정했습니다.

2020-04-02 12:07 UTC, sjjeong requested changes

2020-04-02 12:07 UTC, sjjeong commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/login/LoginViewModel.kt
> +    var successLogin: ObservableBoolean = ObservableBoolean(false)
리뷰사항이 반영되지 않았네요

2020-04-02 12:07 UTC, sjjeong commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/search/MovieSearchViewModel.kt
> +    enum class MessageSet {
클래스 선언은 함수와 companion object 사이로 옮겨주세요

2020-04-02 12:07 UTC, sjjeong commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/search/MovieSearchViewModel.kt
> +    //    var toastMsg: ObservableField<String> = ObservableField()
주석들은 제거해주세요

2020-04-02 12:07 UTC, sjjeong commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/search/MovieAdapter.kt
> +    private lateinit var binding: ItemMovieBinding
이거는 Adapter에 있으면 안됩니다 ViewHolder로 옮겨주세요

2020-04-02 12:07 UTC, sjjeong commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/search/MovieSearchViewModel.kt
> +                        movieList.set(it)
이렇게 하면 서버에서 받아온 새로운 데이터만 ViewModel에 있기 때문에 View에 보이는 데이터와 불일치하게 됩니다.
ViewModel은 View에 보여지는 데이터와 동일해야 합니다.

2020-04-02 13:25 UTC, mtjin commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/search/MovieSearchActivity.kt
> +                viewModel.requestPagingMovie(totalItemsCount + 1)
0c06303 수정했습니다.

2020-04-02 13:26 UTC, mtjin commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/search/MovieSearchViewModel.kt
> +    //    var toastMsg: ObservableField<String> = ObservableField()
d8a9905
수정했습니다.

2020-04-02 13:26 UTC, mtjin commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/login/LoginViewModel.kt
> +    var successLogin: ObservableBoolean = ObservableBoolean(false)
a3ab065
다른거랑 착각했네요.. 수정했습니다.

2020-04-02 13:26 UTC, mtjin commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/search/MovieSearchViewModel.kt
> +    enum class MessageSet {
7b72143
수정했습니다.

2020-04-02 13:27 UTC, mtjin commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/search/MovieAdapter.kt
> +    private lateinit var binding: ItemMovieBinding
39a7f7a
수정했습니다.

2020-04-02 13:58 UTC, mtjin commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/search/MovieSearchViewModel.kt
> +                        movieList.set(it)
@sjjeong 
requestMovie() 에서는 처음 검색결과여서 set으로 해도 괜찮지 않나요? (바인딩 어댑터쪽에서는 더 불러오기인지 분기처리로 어댑터 clear 해주는 로직으로 구현되어있습니다.)

75라인에 requestPagingMovie() 쪽을 수정해야 할 것 같아서 하는 중인데요.   notifyChange() 나 set() 을 새로 들어온 리스트로해주고 그 후 다시 리스트를 이전에 갖고있던 리스트와 새로들어온 리스트를 합쳐줘야 할 것 같은데 이러면 아이템이 중복되서 뿌려지게 되는 로직인데 어떻게 해야하나요..?

2020-04-04 08:49 UTC, sjjeong commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/search/MovieSearchViewModel.kt
> +                        movieList.set(it)
중복이 되지 않게 addAll이 아니라 reset을 해주시면 됩니다.

2020-04-04 09:43 UTC, mtjin commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/search/MovieSearchViewModel.kt
> +                        movieList.set(it)
b7e93bd
수정했습니다.

2020-04-05 06:54 UTC, mtjin commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/search/MovieSearchViewModel.kt
> +                        movieList.set(it)
7781fb9

f9944f9

수정했습니다.

2020-04-06 09:58 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-04-06 11:15 UTC, sooakim approved these changes

2020-04-06 11:18 UTC, merged