HW-5 Use MVVM
sjjeong/GoogryAndroidArchitecutreStudy pull request #555
Opened 2020-03-31 20:04 UTC by kangraemin

2020-04-01 03:04 UTC, mtjin requested changes

2020-04-01 03:04 UTC, mtjin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/main/MainActivity.kt
> +            }
인터넷이 연결된 상태에서 검색 하는건 잘 뜨는데, 인터넷연결이 끊켰을 때 검색했던 영화를 로컬에서 못 불러오는 것 같습니다.

2020-04-01 10:49 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/main/MainActivity.kt
> +            }
오프라인일때, 리사이클러뷰 전체를 가리는 것에서 토스트 메세지를 띄우는 것으로 수정했습니다 
aba77cb

2020-04-01 12:18 UTC, mtjin approved these changes
@sooakim 
approve 했습니다.

2020-04-02 05:13 UTC, sooakim requested changes

2020-04-02 05:13 UTC, sooakim commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/login/LoginActivity.kt
>          compositeDisposable.add(whenIdFocusChange)
데이터 바인딩으로 처리할 수 있어요

2020-04-02 05:13 UTC, sooakim commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/login/LoginViewModel.kt
> +) : ViewModel() {
AAC ViewModel은 이번 과제에 포함되는 내용이 아닌 것 같아요.

2020-04-02 05:13 UTC, sooakim commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/login/LoginActivity.kt
> +                loginViewModel.checkPasswordIsEmpty(hasFocus = hasFocus)
데이터 바인딩으로 처리할 수 있어요

2020-04-02 05:13 UTC, sooakim commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/login/LoginViewModel.kt
> +            loginResponse.notifyChange()
set을 했는데 다시 notifyChange를 하는 이유가 있나요

2020-04-03 13:25 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/login/LoginActivity.kt
> +                loginViewModel.checkPasswordIsEmpty(hasFocus = hasFocus)
수정했습니다
ad8b403

2020-04-03 13:25 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/login/LoginActivity.kt
>          compositeDisposable.add(whenIdFocusChange)
수정했습니다
ad8b403

2020-04-03 13:26 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/login/LoginViewModel.kt
> +            loginResponse.notifyChange()
로그인 실패를 여러번 하는 경우에 같은 값이 들어가 notify가 안되는 경우를 방지하려구 했습니다 
 loginResponse를 success / fail로 나누고 notifyChange로만 변경하였습니다 
f11aa87

2020-04-03 13:27 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/login/LoginViewModel.kt
> +) : ViewModel() {
수정하였습니다
f7e90fb

2020-04-04 02:58 UTC, sooakim requested changes

2020-04-04 02:58 UTC, sooakim commented on 2003/kangraemin/app/src/main/res/layout/activity_main.xml
> +            android:visibility="@{vm.showLogoutButton ? View.VISIBLE : View.GONE}"
커스텀 바인딩 어댑터를 만들면 View를 import하지 않아도 돼요.

2020-04-04 02:58 UTC, sooakim commented on 2003/kangraemin/app/src/main/res/layout/activity_login.xml
> +                    bind:onFocusChange="@{vm.getOnFocusChangeListener(vm.pwText)}"
```suggestion
                    bind:onFocusChange="@{(v, hasFocus) -> vm.pwFocusChanged(hasFocus)}"
```

2020-04-04 02:58 UTC, sooakim commented on 2003/kangraemin/app/src/main/res/layout/activity_login.xml
> +                    bind:onFocusChange="@{vm.getOnFocusChangeListener(vm.idText)}"
```suggestion
                    bind:onFocusChange="@{(v, hasFocus) -> vm.idFocusChanged(hasFocus)}"
```

2020-04-04 06:03 UTC, kangraemin commented on 2003/kangraemin/app/src/main/res/layout/activity_login.xml
> +                    bind:onFocusChange="@{vm.getOnFocusChangeListener(vm.pwText)}"
수정하였습니다 
c8ab1c0

2020-04-04 06:03 UTC, kangraemin commented on 2003/kangraemin/app/src/main/res/layout/activity_login.xml
> +                    bind:onFocusChange="@{vm.getOnFocusChangeListener(vm.idText)}"
수정하였습니다 
c8ab1c0

2020-04-04 06:03 UTC, kangraemin commented on 2003/kangraemin/app/src/main/res/layout/activity_main.xml
> +            android:visibility="@{vm.showLogoutButton ? View.VISIBLE : View.GONE}"
수정하였습니다
3500e75

2020-04-04 06:06 UTC, sooakim approved these changes

2020-04-04 09:07 UTC, sjjeong requested changes

2020-04-04 09:07 UTC, sjjeong commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/login/LoginViewModel.kt
> +    )
class는 맨 아래로 이동시켜주세요 
다른 클래스도 동일하게 변경해주세요

2020-04-04 09:42 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/login/LoginViewModel.kt
> +    )
수정했습니다
4742b50

2020-04-06 09:14 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-04-06 13:10 UTC, merged