HW-5 MVVM 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #556
Opened 2020-04-01 06:46 UTC by byiryu

기존에 있던 MVP 소스를 수정하지 않고 분리하여 보관했습니다.
신규로 패키지 MVVM을 만들어서 적용해봤습니다.

2020-04-01 09:26 UTC, tjdwlsl1021 approved these changes
수고하셨습니다.

제가 보기에는 괜찮은 것 같습니다;;
소스 줄 맞추는 거 정도만 하면 될 것 같습니다;;

2020-04-01 11:43 UTC, sjjeong requested changes

2020-04-01 11:43 UTC, sjjeong commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/mvvm/login/viewmodel/LoginViewModel.kt
> +    var loginStatus = ObservableField<Pair<Boolean, Int>>()
val로 선언해주세요

2020-04-01 11:43 UTC, sjjeong commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/mvvm/main/viewmodel/MainViewModel.kt
> +    var data = ObservableField<List<MovieItem>>()
여기도 마찬가지로 val로 해주세요
변수명은 data처럼 예약어는 사용하지 말아주세요

2020-04-01 11:43 UTC, sjjeong commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/mvvm/main/viewmodel/MainViewModel.kt
> +    private val disposable = CompositeDisposable()
공통으로 쓰이는 것인데 base로 옮겨주시면 더 좋을 것 같네요 
하단에 clear 로직도 같이 옮겨주세요

2020-04-01 11:43 UTC, sjjeong commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/mvvm/main/views/MainActivity.kt
> +                            }
이렇게 할 수 있습니다
```kotlin 
when (val str = second) {
    is Int -> showMsg(str)
    is String -> showMsg(str)
}
```

2020-04-01 11:43 UTC, sjjeong commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/mvvm/main/views/MainActivity.kt
> +        viewModel.onDestroy()
super.onDestory()보다 먼저 호출해주세요

2020-04-01 11:43 UTC, sjjeong commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/mvvm/login/views/LoginActivity.kt
> +            netStatus = viewModel.netStatus
netStatus를 따로 넣어줄 필요 없이 ViewModel에 접근해서 사용하면됩니다.
Main도 동일하게 수정해주세요

2020-04-03 12:44 UTC, byiryu commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/mvvm/main/views/MainActivity.kt
> +                            }
오우 좋네요

2020-04-03 12:47 UTC, byiryu commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/mvvm/login/views/LoginActivity.kt
> +            netStatus = viewModel.netStatus
수정했습니다
0e8f2a1

2020-04-03 12:47 UTC, byiryu commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/mvvm/main/views/MainActivity.kt
> +        viewModel.onDestroy()
수정했습니다.

340d569

2020-04-03 12:47 UTC, byiryu commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/mvvm/main/views/MainActivity.kt
> +                            }
수정했습니다
30a8f2b

2020-04-03 12:48 UTC, byiryu commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/mvvm/main/viewmodel/MainViewModel.kt
> +    private val disposable = CompositeDisposable()
수정했습니다.
0434fa8

2020-04-03 12:49 UTC, byiryu commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/mvvm/login/viewmodel/LoginViewModel.kt
> +    var loginStatus = ObservableField<Pair<Boolean, Int>>()
수정했습니다

3a1f193

2020-04-03 12:49 UTC, byiryu commented on 2003/byiryu/app/src/main/java/com/byiryu/study/ui/mvvm/main/viewmodel/MainViewModel.kt
> +    var data = ObservableField<List<MovieItem>>()
수정했습니다.
d1d6c8c
0c07041

2020-04-04 09:09 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-04-04 10:27 UTC, merged