HW-6 LiveData and ViewModel
sjjeong/GoogryAndroidArchitecutreStudy pull request #559
Opened 2020-04-05 09:46 UTC by sooakim

2020-04-06 14:54 UTC, sjjeong requested changes

2020-04-06 14:54 UTC, sjjeong commented on 2003/sooakim/app/src/main/java/io/github/sooakim/ui/login/SALoginState.kt
> +    class ShowMain : SALoginState()
sealed class를 상속받은 State가 특정 데이터를 가지고 있지 않는다면 object로 만들어주면 좋을 것 같아요
다른쪽도 같이 봐주세요

2020-04-07 06:38 UTC, sooakim commented on 2003/sooakim/app/src/main/java/io/github/sooakim/ui/login/SALoginState.kt
> +    class ShowMain : SALoginState()
a4e0ae1

2020-04-07 12:58 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-04-07 15:33 UTC, merged