HW-1 add Naver movie search API
sjjeong/GoogryAndroidArchitecutreStudy pull request #561
Opened 2020-04-05 17:14 UTC by Kyudong3

2020-04-08 17:32 UTC, ios-byungjoon-lee reviewed
리뷰 남겼습니다.

2020-04-08 17:32 UTC, ios-byungjoon-lee commented on 2004/kyudong3/app/src/main/java/com/example/kyudong3/extension/StringExtension.kt
> +}
HtmlCompat 을 사용하면 OS 버전별로 분기를 나누지 않아도 될 것 같습니다.

2020-04-08 17:32 UTC, ios-byungjoon-lee commented on 2004/kyudong3/app/src/main/java/com/example/kyudong3/MainActivity.kt
> +    lateinit var movieRvAdapter: SearchMovieRvAdapter
movieRvAdapter가 재할당 되는 곳이 없어보이는데  val 로 선언하는 것이 더 좋을것 같네요.
지연 초기화가 필요하다면 lazy를 사용하면 될것 같습니다.

접근 제어자는 private을 붙여주시면 좋을 것 같습니다.

2020-04-08 17:32 UTC, jesterz91 commented on 2004/kyudong3/app/src/main/java/com/example/kyudong3/model/Movie.kt
> +)
해당 클래스안에 items만 Movie List인데, 클래스명을 변경하는게 나을것 같습니다.

2020-04-08 17:32 UTC, jesterz91 commented on 2004/kyudong3/app/src/main/java/com/example/kyudong3/model/Movie.kt
> +)
json 데이터가 camelcase 가 아닌경우도 많기때문에
@SerialzedName 어노테이션을 명시 하는것도 좋을 것 같습니다.

2020-04-08 17:32 UTC, jesterz91 commented on 2004/kyudong3/app/src/main/java/com/example/kyudong3/MainActivity.kt
> +                    }
검색버튼 쪽 이벤트 부분과  중복코드 입니다.

2020-04-08 17:32 UTC, jesterz91 commented on 2004/kyudong3/app/src/main/java/com/example/kyudong3/MainActivity.kt
> +                if (response.body() != null) {
response의 isSuccessful 조건도  추가해주시면 좋을것 같습니다.

2020-04-08 17:32 UTC, jesterz91 commented on 2004/kyudong3/app/src/main/java/com/example/kyudong3/adapter/SearchMovieRvAdapter.kt
> +    RecyclerView.Adapter<SearchMovieRvAdapter.SearchMovieVH>() {
SearchMovieRvAdapter 의 인자로 context를 받을 필요가 없어 보입니다.

2020-04-08 17:32 UTC, jesterz91 commented on 2004/kyudong3/app/src/main/java/com/example/kyudong3/adapter/SearchMovieRvAdapter.kt
> +        holder.clickListener(movieList[position].link)
clickListener는 어댑터의  onCreateViewHolder
또는 뷰홀더의 초기화 블록 쪽에서 해주시는게 좋을것 같습니다.

2020-04-08 17:32 UTC, jesterz91 commented on 2004/kyudong3/app/src/main/java/com/example/kyudong3/network/RetrofitClient.kt
> +}
싱글톤 바꾸면 좋을 것 같습니다.

2020-04-08 21:13 UTC, ddaeyeonkim commented on 2004/kyudong3/app/src/main/java/com/example/kyudong3/adapter/SearchMovieRvAdapter.kt
> +    private var movieList: List<Movie> = listOf()
불변으로 바꿀수 있습니다.
```suggestion
    private val movieList = mutableListOf<Movie>()
```

2020-04-08 21:13 UTC, ddaeyeonkim commented on 2004/kyudong3/app/src/main/java/com/example/kyudong3/adapter/SearchMovieRvAdapter.kt
> +    }
기존의 movieList 를 초기화한 다음 아이템을 추가해주는게 좋습니다.

2020-04-08 21:13 UTC, ddaeyeonkim commented on 2004/kyudong3/app/src/main/java/com/example/kyudong3/adapter/SearchMovieRvAdapter.kt
> +            }
뷰홀더에 `bind(movie: Movie)` 함수를 만들어서 빼주는게 더 좋습니다.

2020-04-08 21:13 UTC, improve777 commented on 2004/kyudong3/app/src/main/java/com/example/kyudong3/network/NaverApiServiceImpl.kt
> +    private val retrofitClient: RetrofitClient
retrofitClient 는 init 블록 안에만 있어도 될것 같아요

2020-04-10 11:04 UTC, ios-byungjoon-lee reviewed
추가 리뷰

2020-04-10 11:04 UTC, jesterz91 commented on 2004/kyudong3/app/src/main/java/com/example/kyudong3/adapter/SearchMovieRvAdapter.kt
> +    }
Kotlin Android Extensions을 뷰홀더에서 사용할 때에는 
성능저하의 원인이 될 수 있습니다.
LayoutContainer 인터페이스에 대해 찾아 보시고 적용하면 좋을 것 같아요

2020-04-10 13:51 UTC, Kyudong3 commented on 2004/kyudong3/app/src/main/java/com/example/kyudong3/extension/StringExtension.kt
> +}
수정했습니다!

2020-04-10 13:53 UTC, Kyudong3 commented on 2004/kyudong3/app/src/main/java/com/example/kyudong3/MainActivity.kt
> +    lateinit var movieRvAdapter: SearchMovieRvAdapter
수정했습니다! 
8f052ad

2020-04-10 13:54 UTC, Kyudong3 commented on 2004/kyudong3/app/src/main/java/com/example/kyudong3/model/Movie.kt
> +)
수정했습니다!

2020-04-10 13:55 UTC, Kyudong3 commented on 2004/kyudong3/app/src/main/java/com/example/kyudong3/model/Movie.kt
> +)
수정했습니다! 4920999

2020-04-10 13:55 UTC, Kyudong3 commented on 2004/kyudong3/app/src/main/java/com/example/kyudong3/MainActivity.kt
> +                    }
수정하였습니다! 
20d4fec

2020-04-10 13:55 UTC, Kyudong3 commented on 2004/kyudong3/app/src/main/java/com/example/kyudong3/MainActivity.kt
> +                if (response.body() != null) {
수정했습니다! 
20d4fec

2020-04-10 13:56 UTC, Kyudong3 commented on 2004/kyudong3/app/src/main/java/com/example/kyudong3/network/NaverApiServiceImpl.kt
> +    private val retrofitClient: RetrofitClient
수정하였습니다! 
e4a39e5

2020-04-10 13:56 UTC, Kyudong3 commented on 2004/kyudong3/app/src/main/java/com/example/kyudong3/adapter/SearchMovieRvAdapter.kt
> +            }
수정하였습니다! 
595364c

2020-04-10 13:56 UTC, Kyudong3 commented on 2004/kyudong3/app/src/main/java/com/example/kyudong3/adapter/SearchMovieRvAdapter.kt
> +    }
수정하였습니다! 
595364c

2020-04-10 13:56 UTC, Kyudong3 commented on 2004/kyudong3/app/src/main/java/com/example/kyudong3/adapter/SearchMovieRvAdapter.kt
> +    private var movieList: List<Movie> = listOf()
수정하였습니다! 
595364c

2020-04-10 13:57 UTC, Kyudong3 commented on 2004/kyudong3/app/src/main/java/com/example/kyudong3/adapter/SearchMovieRvAdapter.kt
> +        holder.clickListener(movieList[position].link)
수정하였습니다! 
595364c

2020-04-10 13:57 UTC, Kyudong3 commented on 2004/kyudong3/app/src/main/java/com/example/kyudong3/adapter/SearchMovieRvAdapter.kt
> +    RecyclerView.Adapter<SearchMovieRvAdapter.SearchMovieVH>() {
수정하였습니다! 
595364c

2020-04-10 13:57 UTC, Kyudong3 commented on 2004/kyudong3/app/src/main/java/com/example/kyudong3/network/RetrofitClient.kt
> +}
수정하였습니다! 
577438b

2020-04-10 13:58 UTC, Kyudong3 commented on 2004/kyudong3/app/src/main/java/com/example/kyudong3/adapter/SearchMovieRvAdapter.kt
> +    }
LayoutContainer에 대해 조금 더 공부하고 바로 적용해보도록 할게요..!! 감사합니다

2020-04-10 14:01 UTC, Kyudong3 commented
@jesterz91 
@improve777 
리뷰 모두 수정하였습니다!

2020-04-10 14:22 UTC, sjjeong commented on 2004/kyudong3/app/src/main/java/com/example/kyudong3/adapter/SearchMovieRvAdapter.kt
> +    }
@jesterz91 
말씀하신 내용은 위 코드처럼 한 경우에는 해당사항이 없습니다.
itemView.moviewImagImv와 같은 view를 변수로 선언하지 않고 bind시점에 매번 itemView.moviewImagImv 형태로 사용할 때 경우입니다.

2020-04-10 14:37 UTC, sjjeong requested changes

2020-04-10 14:37 UTC, sjjeong commented on 2004/kyudong3/app/src/main/java/com/example/kyudong3/adapter/SearchMovieRvAdapter.kt
> +        }
지금은 with를 제거하고 holder.bind(movieList[position])로 써도 될 것 같습니다.

2020-04-10 14:37 UTC, sjjeong commented on 2004/kyudong3/app/src/main/java/com/example/kyudong3/adapter/SearchMovieRvAdapter.kt
> +        private val onClickListener = View.OnClickListener {
onClickListener가 unused입니다.
클릭처리 추가 해주세요

2020-04-10 14:37 UTC, sjjeong commented on 2004/kyudong3/app/build.gradle
> +        buildConfigField("String", "clientSecret", clientSecret)
상수는 대문자_대문자 형태로 선언해야 합니다.

2020-04-10 14:37 UTC, sjjeong commented on 2004/kyudong3/app/src/main/java/com/example/kyudong3/network/NaverApiServiceImpl.kt
> +    }
이렇게 할 필요는 없습니다.
naverService를 선언과 동시에 set 해주세요

2020-04-10 15:56 UTC, Kyudong3 commented on 2004/kyudong3/app/build.gradle
> +        buildConfigField("String", "clientSecret", clientSecret)
수정했습니다! 
f99caab

2020-04-10 15:57 UTC, Kyudong3 commented on 2004/kyudong3/app/src/main/java/com/example/kyudong3/network/NaverApiServiceImpl.kt
> +    }
수정하였습니다! 
4242e14

2020-04-10 15:57 UTC, Kyudong3 commented on 2004/kyudong3/app/src/main/java/com/example/kyudong3/adapter/SearchMovieRvAdapter.kt
> +        }
수정하였습니다!
100edf3

2020-04-10 15:57 UTC, Kyudong3 commented on 2004/kyudong3/app/src/main/java/com/example/kyudong3/adapter/SearchMovieRvAdapter.kt
> +        private val onClickListener = View.OnClickListener {
엇 그렇네요..! 수정하였습니다! 
8542448

2020-04-10 16:17 UTC, ios-byungjoon-lee approved these changes
Good

2020-04-11 03:05 UTC, sjjeong commented on 2004/kyudong3/app/src/main/java/com/example/kyudong3/adapter/SearchMovieRvAdapter.kt
> +        private val onClickListener = View.OnClickListener {
이렇게 하지 마시고 init{}에서 처리하도록 해주세요
movieItemView에는 Unit이 들어갑니다.

2020-04-11 05:15 UTC, Kyudong3 commented on 2004/kyudong3/app/src/main/java/com/example/kyudong3/adapter/SearchMovieRvAdapter.kt
> +        private val onClickListener = View.OnClickListener {
수정했습니다! 
382beb9

2020-04-11 14:34 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-04-11 15:44 UTC, merged