HW-1 네이버 영화 검색
sjjeong/GoogryAndroidArchitecutreStudy pull request #562
Opened 2020-04-05 19:56 UTC by nukeolaf

네이버 영화 검색 API 를 사용하여 영화 검색 어플리케이션을 만들었습니다

2020-04-06 10:49 UTC, ghost requested changes

2020-04-06 10:49 UTC, eunjin-hong commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/MovieDetailActivity.kt
> +        val actor = "출연진 : ${movieItem.actor.replace("|", " ")}"
🙋‍♀️ 외국 감독, 출연진들의 이름에는 띄어쓰기가 있으니, `|` 가 마음에 안 드신다면 다른 구분자를 넣어주시는건 어떨까요? (`,`나 `/` 등 )

2020-04-06 10:49 UTC, eunjin-hong commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/MainActivity.kt
> +                    notifyDataSetChanged()
🙋‍♀️`!!` 대신 `response.body()` 가 null일 경우에 대응하면 더 좋을 것 같습니다.

2020-04-06 10:49 UTC, eunjin-hong commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/MainActivity.kt
> +                            Log.d("onQueryTextListener", response.body().toString())
🙋‍♀️[OkHttpLoggingInterceptor](https://github.com/square/okhttp/tree/master/okhttp-logging-interceptor) 를 이용하시면 매번 로그를 찍지 않아도 로그를 볼 수  있습니다!

2020-04-06 10:49 UTC, eunjin-hong commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/MainActivity.kt
> +            var intent = Intent(this@MainActivity, MovieDetailActivity::class.java)
🙋‍♀️저희 과제가  영화 상세 페이지를 인터넷 브라우저에서 띄우기였던거같아요!  확인 부탁드립니다!

2020-04-06 23:30 UTC, ddaeyeonkim reviewed
아직은 코드량이 많지 않아서 괜찮지만 확장성을 고려해서 패키지 분리를 해주시는게 좋을 듯 합니다.

2020-04-06 23:30 UTC, ddaeyeonkim commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/MainActivity.kt
> +            var intent = Intent(this@MainActivity, MovieDetailActivity::class.java)
intent 변수 선언시 `val` 로 해주세요

2020-04-06 23:30 UTC, ddaeyeonkim commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/MainActivity.kt
> +    private val movieAdapter = MovieAdapter(ArrayList(0), itemListener)
Adapter 생성자에 list 를 넣지 않도록 하는게 좋습니다

2020-04-06 23:30 UTC, ddaeyeonkim commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/MainActivity.kt
> +        search_view.queryHint = "영화 검색"
xml 에도 해당 속성이 있긴 한데 xml 에서 적용이 안되서 코드에도 넣으신 것 같습니다.
xml 의 namespace 를 `android` 에서 `app` 으로 변경해주시면 위 코드는 생략이 가능할 것 같습니다.

2020-04-06 23:30 UTC, ddaeyeonkim commented on 2004/nukeolaf/app/src/main/res/layout/activity_main.xml
> +        android:queryHint="검색어를 입력하시오" />
이렇게 하면 속성이 적용되네요

```suggestion
        app:iconifiedByDefault="false"
        app:queryHint="검색어를 입력하시오" />
```

2020-04-06 23:30 UTC, improve777 commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/MovieAdapter.kt
> +        private var view = itemView
itemView 가 전역변수로 있기 때문에 따로 안만드셔도 될거같아요

2020-04-06 23:30 UTC, improve777 commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/MovieAdapter.kt
> +            view.apply {
```suggestion
            itemView.apply {
```

2020-04-06 23:30 UTC, improve777 commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/MovieAdapter.kt
> +                .into(view.movie_image)
```suggestion
            Glide.with(itemView)
                .load(item.image)
                .into(itemView.movie_image)
```

2020-04-06 23:30 UTC, improve777 commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/MovieAdapter.kt
> +        return (ViewHolder(inflatedView))
바깥쪽 괄호는 지워주세요

2020-04-06 23:30 UTC, improve777 commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/MovieAdapter.kt
> +        this.movies = list
어댑터 내부에서 따로 list 를 선언하고 `add()`, `addAll()` 해서 관리하는게 좋습니다.

2020-04-06 23:30 UTC, improve777 commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/MovieAdapter.kt
> +    private var movies: ArrayList<MovieItem>,
생성자에서 제거해주세요

2020-04-06 23:30 UTC, improve777 commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/MovieAdapter.kt
> +    fun setMovies(list: ArrayList<MovieItem>) {
리스트를 인자로 받을때는 `List<MovieItem>` 으로 받는게 좋습니다.

2020-04-06 23:30 UTC, improve777 commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/MainActivity.kt
> +                showMovies(response.body()!!.items).also {
response 에 대한 체크를 먼저 해주는게 좋습니다.

```kotlin
if ((response.body() != null) and response.isSuccessful) {
      // todo              
}
```

2020-04-06 23:30 UTC, improve777 commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/MainActivity.kt
> +    private fun showMovies(movies: ArrayList<MovieItem>) {
여기도 `List<MovieItem>` 으로 선언해주시는게 좋습니다

2020-04-06 23:30 UTC, improve777 commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/MovieAdapter.kt
> +        fun bind(item: MovieItem, position: Int) {
position 은 빼주셔도 될 것 같아요

2020-04-06 23:30 UTC, improve777 commented on 2004/nukeolaf/app/build.gradle
> +    annotationProcessor 'com.github.bumptech.glide:compiler:4.10.0'
글라이드 공식문서에서는 코틀린 사용시 `kapt` 로 선언하라고 명시되어 있습니다.

2020-04-06 23:30 UTC, improve777 commented on 2004/nukeolaf/app/src/main/res/layout/item_movies_rv.xml
> +                android:text="감독 : 김아무개"
디자인할때만 참고할수 있도록 `tools:text` 로 작성해주시는게 좋습니다

2020-04-06 23:30 UTC, improve777 commented on 2004/nukeolaf/app/src/main/res/layout/activity_main.xml
> +        android:layout_height="wrap_content"
recyclerview 는 `wrap_content` 로 안하시는게 좋습니다

2020-04-06 23:30 UTC, improve777 commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/MovieItem.kt
> +) : Serializable
`Parcelable` 로 구현해주시는게 어떨까요?

2020-04-06 23:30 UTC, improve777 commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/MovieResponse.kt
> +    val items: ArrayList<MovieItem>
여기도 `List<MovieItem>` 으로 선언해주시는게 좋습니다

2020-04-07 15:44 UTC, nukeolaf commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/MainActivity.kt
> +            var intent = Intent(this@MainActivity, MovieDetailActivity::class.java)
@eunjin-hong 수정했습니다! abfea91
@improve777 수정했습니다! 63acd12

2020-04-07 15:45 UTC, nukeolaf commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/MainActivity.kt
> +                            Log.d("onQueryTextListener", response.body().toString())
꿀팁 알려주셔서 감사합니다~ㅎㅎ
수정했습니다! 
0550522

2020-04-07 15:45 UTC, nukeolaf commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/MainActivity.kt
> +                    notifyDataSetChanged()
수정했습니다!
7facaa9

2020-04-07 15:46 UTC, nukeolaf commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/MovieDetailActivity.kt
> +        val actor = "출연진 : ${movieItem.actor.replace("|", " ")}"
수정했습니다! 03dd1de

2020-04-07 15:55 UTC, nukeolaf commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/MainActivity.kt
> +        search_view.queryHint = "영화 검색"
수정했습니다! bef13e9

2020-04-07 16:16 UTC, nukeolaf commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/MainActivity.kt
> +    private val movieAdapter = MovieAdapter(ArrayList(0), itemListener)
comment 감사합니다!
Adapter 생성자에 list 를 넣지 않도록 하는게 좋다는 것은
list 는 Adapter 의 전역변수로 선언하고, 나중에 set 함수로 초기화해주는 게 좋다는 뜻으로 이해해도 괜찮을까요?
일단은 제가 이해한대로 수정했습니다! bb4ae17

2020-04-07 16:19 UTC, nukeolaf commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/MovieResponse.kt
> +    val items: ArrayList<MovieItem>
수정했습니다! f950740
List<> 는 읽기만 가능한 자료구조라고 알고 있는데,
왜 List로 선언해주는게 좋은지 여쭤봐도 괜찮을까요???
검색해봐도 이유를 잘 못 찾겠습니다ㅠㅜ

2020-04-07 16:40 UTC, nukeolaf commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/MovieAdapter.kt
> +        private var view = itemView
수정했습니다! 8dd2b05

2020-04-07 16:41 UTC, nukeolaf commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/MainActivity.kt
> +    private val movieAdapter = MovieAdapter(ArrayList(0), itemListener)
앗..! 제가 생각한대로 수정했더니 에러가 떠서 수정했습니다!
5d78aff

2020-04-07 16:43 UTC, nukeolaf commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/MovieAdapter.kt
> +        return (ViewHolder(inflatedView))
수정했습니다!
ab0cd48

2020-04-07 16:58 UTC, nukeolaf commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/MovieAdapter.kt
> +        this.movies = list
와...! 이런 방법이 있었군요!! 
알려주셔서 감사합니다!! 정말 많이 배워갑니다!!
말씀하신대로 수정했습니다! 
cd57a9b

2020-04-07 17:00 UTC, nukeolaf commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/MovieAdapter.kt
> +    private var movies: ArrayList<MovieItem>,
수정했습니다! bb4ae17

2020-04-07 17:02 UTC, nukeolaf commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/MovieAdapter.kt
> +    fun setMovies(list: ArrayList<MovieItem>) {
수정했습니다! f950740

2020-04-07 17:04 UTC, nukeolaf commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/MainActivity.kt
> +                showMovies(response.body()!!.items).also {
수정했습니다! ee849bc

2020-04-07 17:06 UTC, nukeolaf commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/MainActivity.kt
> +    private fun showMovies(movies: ArrayList<MovieItem>) {
수정했습니다! 94e555d

2020-04-07 17:09 UTC, nukeolaf commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/MovieAdapter.kt
> +        fun bind(item: MovieItem, position: Int) {
수정했습니다! 35ffe72

2020-04-07 17:27 UTC, nukeolaf commented on 2004/nukeolaf/app/build.gradle
> +    annotationProcessor 'com.github.bumptech.glide:compiler:4.10.0'
수정했습니다! 25acab2

2020-04-07 17:31 UTC, nukeolaf commented on 2004/nukeolaf/app/src/main/res/layout/item_movies_rv.xml
> +                android:text="감독 : 김아무개"
수정했습니다! 1646cc7

2020-04-07 17:39 UTC, nukeolaf commented on 2004/nukeolaf/app/src/main/res/layout/activity_main.xml
> +        android:layout_height="wrap_content"
수정했습니다! aed9ffe

2020-04-07 17:58 UTC, nukeolaf commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/MovieItem.kt
> +) : Serializable
수정했습니다! e7dae33

2020-04-07 21:44 UTC, improve777 commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/MovieAdapter.kt
> +    private var movies: ArrayList<MovieItem> = ArrayList()
`val` 로 변경해주세요

2020-04-07 21:44 UTC, improve777 commented on 2004/nukeolaf/app/build.gradle
> +    }
`Parcelize` 어노테이션 사용할때 코틀린 1.3.40 버전 이전에만 experimental  이었던 것으로 알고 있습니다.
제거해주셔도 될것 같아요.

2020-04-08 12:34 UTC, TaeseongYun commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/MovieAdapter.kt
> +                    .into(this.movie_image)
Glide 처리할 때 error 처리도 하시면 좋을거 같아요! 가끔 영화사진이 없는게 있어요

2020-04-08 13:58 UTC, ghost approved these changes
깃허브 익숙하지 않아서 review awaiting 으로 뜨네요. 확인했습니다!
LGTM

2020-04-08 20:41 UTC, nukeolaf commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/MovieAdapter.kt
> +    private var movies: ArrayList<MovieItem> = ArrayList()
수정했습니다! a84102b

2020-04-08 20:41 UTC, nukeolaf commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/MovieAdapter.kt
> +                    .into(this.movie_image)
수정했습니다! ded7d12

2020-04-08 20:45 UTC, nukeolaf commented on 2004/nukeolaf/app/build.gradle
> +    }
writeToParcel()/createFromParcel() 를 자동으로 구현해주기 위해 experimental 을 사용했어요
experimental 을 제거하면 Parcelize 어노테이션 사용 시 구현해주라고 빨간줄이 떠요ㅠㅠ

2020-04-08 21:16 UTC, improve777 commented on 2004/nukeolaf/app/build.gradle
> +    }
ide 문제인 걸까요..ㅜ 알겠습니다.

2020-04-08 21:17 UTC, ddaeyeonkim approved these changes
LGTM 👍👍👍

2020-04-09 15:19 UTC, sjjeong requested changes

2020-04-09 15:19 UTC, sjjeong commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/MovieAdapter.kt
> +    private val movies: ArrayList<MovieItem> = ArrayList()
Kotlin에서는 ArrayList보다 MutableList를 사용하도록 해요
```kotlin
private val movies = mutableListOf<MovieItem>()
```

2020-04-09 15:19 UTC, sjjeong commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/MovieAdapter.kt
> +    inner class ViewHolder(itemView: View) : RecyclerView.ViewHolder(itemView) {
ViewHolder에는 inner를 가급적이면 사용하지 않도록 하는게 좋습니다

2020-04-09 15:19 UTC, sjjeong commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/MovieAdapter.kt
> +                }
click listener는 onCreateViewHolder 시점인 ViewHolder가 생성되는 시점에 해주면 됩니다.
position은 adapterPosition으로 접근 가능합니다.

2020-04-09 15:19 UTC, sjjeong commented on 2004/nukeolaf/app/build.gradle
> +        buildConfigField("String", "Naver_Client_Secret", Naver_Client_Secret)
상수는 대문자로 선언해주세요
NAVER_CLIENT_ID
NAVER_CLIENT_SECRET

2020-04-09 15:19 UTC, sjjeong commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/RetrofitClient.kt
> +                    addHeader("X-Naver-Client-Secret", Naver_Client_Secret)
이렇게 사용하면 Naver_Client_Id가 어디에 있는 값인지 알기가 어렵습니다.
BuildConfig.Naver_Client_Id 처럼 사용해주셔야 합니다.

2020-04-09 15:19 UTC, sjjeong commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/RetrofitClient.kt
> +                level = HttpLoggingInterceptor.Level.BODY
BuildConfig.DEBUG가 true일 때 BODY를 넣고 false이면 NONE을 넣도록 해주세요

2020-04-09 15:19 UTC, sjjeong commented on 2004/nukeolaf/app/src/main/res/layout/activity_main.xml
> +        android:layout_weight="1"
지금은 weight가 불필요해 보이네요
height를 match로 해도 됩니다.

2020-04-09 15:19 UTC, sjjeong commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/MainActivity.kt
> +    private lateinit var retrofitClient: RetrofitInterface
lateinit var 말고 val로 선언해서 바로 가져와도 될 것 같습니다.
```kotlin
private val retrofitClient: RetrofitInterface = RetrofitClient.client
```

2020-04-09 15:19 UTC, sjjeong commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/MainActivity.kt
> +                searchMovie(query!!)
!!는 사용하지 않는게 좋습니다.
null인지 검사해서 null이 아니면 searchMovie를 호출하도록 해주세요

2020-04-09 15:19 UTC, sjjeong commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/MainActivity.kt
> +                    val movies = response.body()!!.items
response.body()가 null이 아닌 것을 체크 했는데 nullable이 유지되고 있습니다.
이 코드는 아래처럼 변경하면 해결 됩니다.
```
val body = response.body()
if (body != null && response.isSuccessful) {
    val movies = body.items
```

2020-04-09 15:19 UTC, sjjeong commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/MainActivity.kt
> +            notifyDataSetChanged()
notifyDataSetChanged()를 setMovies 함수 내부로 이동하면 아래처럼 사용 할 수 있습니다.
```kotlin
movieAdapter.setMovies(movies)
```

2020-04-10 06:42 UTC, nukeolaf commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/MovieAdapter.kt
> +    private val movies: ArrayList<MovieItem> = ArrayList()
수정했습니다! 
9165f29

그런데 ArrayList 나 MutableList 나 Compile Time 에서는 다 같은 List 로 인식되어서 둘의 큰 차이는 없다고 하는데, 왜 MutableLilst 를 사용하도록 권장하는지, ArrayList 는 어떤경우에 사용하는게 좋은지 여쭤보아도 될까요?

2020-04-10 06:51 UTC, nukeolaf commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/MovieAdapter.kt
> +    inner class ViewHolder(itemView: View) : RecyclerView.ViewHolder(itemView) {
수정했습니다!
984199a

2020-04-10 06:52 UTC, nukeolaf commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/MovieAdapter.kt
> +                }
어떤 말씀이신지 잘 이해가 안돼서 이렇게 수정했는데
제가 잘 이해한것이 맞는지 확인 부탁드립니다!
832059f

2020-04-10 06:54 UTC, nukeolaf commented on 2004/nukeolaf/app/build.gradle
> +        buildConfigField("String", "Naver_Client_Secret", Naver_Client_Secret)
수정했습니다!
3b709ec

2020-04-10 06:55 UTC, nukeolaf commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/RetrofitClient.kt
> +                    addHeader("X-Naver-Client-Secret", Naver_Client_Secret)
수정했습니다!
3cbf989

import com.olaf.nukeolaf.BuildConfig.Naver_Client_Id
import com.olaf.nukeolaf.BuildConfig.Naver_Client_Secret
이렇게 import 되어 있어서 알 수 있다고 생각했는데,
import 로 어디에 있는 값인지 확인하는 것은 이상한가요??

2020-04-10 06:56 UTC, nukeolaf commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/RetrofitClient.kt
> +                level = HttpLoggingInterceptor.Level.BODY
수정했습니다!
5ed8854

2020-04-10 06:56 UTC, nukeolaf commented on 2004/nukeolaf/app/src/main/res/layout/activity_main.xml
> +        android:layout_weight="1"
수정했습니다!
9007b60

2020-04-10 06:57 UTC, nukeolaf commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/MainActivity.kt
> +    private lateinit var retrofitClient: RetrofitInterface
수정했습니다!
d043ab2

2020-04-10 07:01 UTC, nukeolaf commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/MainActivity.kt
> +                searchMovie(query!!)
수정했습니다!
0ca2c40

아무것도 입력 안하고 검색을 눌러도 null 일때 코드가 실행되지 않아서 !! 로 바꿨는데
!! 는 그럼 어떤 상황에 사용하는것이 좋을까요?

2020-04-10 07:02 UTC, nukeolaf commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/MainActivity.kt
> +                    val movies = response.body()!!.items
수정했습니다!
803af4b

2020-04-10 07:02 UTC, nukeolaf commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/MainActivity.kt
> +            notifyDataSetChanged()
수정했습니다!
915505d

2020-04-10 12:20 UTC, sjjeong commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/MovieAdapter.kt
> +    private val movies: ArrayList<MovieItem> = ArrayList()
많은 collection이나 exception류 들이 typealias되어 있어요
나중에 어떠한 이유 때문에 ArrayList같은 것을 사용하지 못할때 대응을 해주기 위해서 에요

2020-04-10 12:21 UTC, sjjeong commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/MovieAdapter.kt
> +    inner class ViewHolder(itemView: View) : RecyclerView.ViewHolder(itemView) {
inner class가 static class인건 아닌걸로 알고 있어요
ViewHolder를 inner class로 쓰면 나중에 View pool에서 메모리 릭 문제가 발생해요

2020-04-10 12:24 UTC, sjjeong commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/RetrofitClient.kt
> +                    addHeader("X-Naver-Client-Secret", Naver_Client_Secret)
코드 가독성을 높이기 위해서에요.
사용하는쪽에서 어떤 클래스에서 있는 상수인지 바로 알면 가독성이 올라가는데
그렇지 않으면 이 상수가 어디서 오는지 찾아봐야하는 불편함이 있어요

2020-04-10 12:25 UTC, sjjeong commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/RetrofitClient.kt
> +                level = HttpLoggingInterceptor.Level.BODY
if else가 한 라인에 들어가지 않는다면 {}를 추가해주셔야 해요

2020-04-10 12:26 UTC, sjjeong commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/MainActivity.kt
> +                searchMovie(query!!)
어떤 경우에도 사용하지 않는게 좋아요
!!는 NPE를 발생시켜서 앱이 중지되는 문제가 있어요

2020-04-10 12:28 UTC, sjjeong commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/MovieAdapter.kt
> +                }
setOnClickListener 등록하는것을 ViewHolder 생성 시점에서 처리 해주시면 돼요
ViewHolder 클래스가 객체로 만들어지는 시점에요

2020-04-11 12:43 UTC, nukeolaf commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/MovieAdapter.kt
> +                }
수정했습니다!
000f2d0

2020-04-11 12:43 UTC, nukeolaf commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/RetrofitClient.kt
> +                level = HttpLoggingInterceptor.Level.BODY
수정했습니다!
5433c4d

2020-04-11 14:35 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-04-11 14:37 UTC, merged