HW-1 Add NAVER search API(네이버 검색 api)
sjjeong/GoogryAndroidArchitecutreStudy pull request #563
Opened 2020-04-06 03:12 UTC by TaeseongYun

2020-04-07 17:40 UTC, ghost requested changes

2020-04-07 17:40 UTC, invitejay commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/NaverAPI.kt
> +    private const val baseUrl = "https://openapi.naver.com/v1/"
clientID와 secretKey 같이 baseUrl도 BuildConfig를 이용해서 관리하면 좋을거 같습니다 !

2020-04-07 17:40 UTC, invitejay commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ui/MainActivity.kt
> +            layoutManager = LinearLayoutManager(this.context)
layoutManager를 xml에서 선언해줄 수 있습니다

2020-04-07 17:40 UTC, invitejay commented on 2004/taeseongyun/app/src/main/res/layout/activity_main.xml
> +                        android:hint="@string/edit_text_hint" />
maxLine과 inputType을 작성해주면 좋을듯 합니다 저도 안썼는데 보고 생각났네요...

2020-04-07 23:42 UTC, TaeseongYun commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/NaverAPI.kt
> +    private const val baseUrl = "https://openapi.naver.com/v1/"
수정하였습니다 [bf27905](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/563/commits/bf27905684afd8d05f3c94c3d065cdcb8d64a866)

2020-04-07 23:57 UTC, TaeseongYun commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ui/MainActivity.kt
> +            layoutManager = LinearLayoutManager(this.context)
수정했습니다. b8d7796

2020-04-07 23:57 UTC, TaeseongYun commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/NaverAPI.kt
> +    private const val baseUrl = "https://openapi.naver.com/v1/"
수정했습니다. cc1fcf2

2020-04-07 23:58 UTC, TaeseongYun commented on 2004/taeseongyun/app/src/main/res/layout/activity_main.xml
> +                        android:hint="@string/edit_text_hint" />
수정했습니다. b8d7796

2020-04-08 01:23 UTC, ddaeyeonkim reviewed
작성해주신 코드보면서 제가 궁금한 내용이나 생각을 리뷰로 남겨봤습니다.

2020-04-08 01:23 UTC, ddaeyeonkim commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/NaverAPI.kt
> +        get() = createRetrofit(baseUrl, MovieInterface::class.java)
get() 으로 메서드를 호출하시면 매번 retrofit 인스턴스를 생성하게 됩니다.

2020-04-08 01:23 UTC, ddaeyeonkim commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/base/BaseRecyclerAdapter.kt
> +    internal val movieList = mutableListOf<ITEM>()
base 클래스인데 movieList 로 네이밍해주셔서 약간 한정적으로 되는것 같습니다.

2020-04-08 01:23 UTC, ddaeyeonkim commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/base/BaseRecyclerAdapter.kt
> +        createBindViewHolder(holder, position)
바로 holder.initBind 를 호출해주셔도 될것 같은데 별도로 createBindViewHolder() 를 해주시는 이유가 있을까요?

2020-04-08 01:23 UTC, ddaeyeonkim commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ui/MainActivity.kt
> +    private fun getMovieList(disposable: CompositeDisposable, query: String) {
disposable 을 인자로 받을 필요는 없을 것 같습니다.

2020-04-08 01:23 UTC, ddaeyeonkim commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ui/MainActivity.kt
> +        disposable.clear()
disposable 초기화작업을 `super.onDestroy()` 위에 올려주시는게 좋아요

2020-04-08 01:23 UTC, ddaeyeonkim commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ui/MainActivity.kt
> +        }
한줄이라서 굳이 run 블록 안에 안넣어도 될 것 같습니다.
그리고 쓰신다면 `apply` 가 더 적합해보입니다.

2020-04-08 01:23 UTC, ddaeyeonkim commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/base/RecyclerViewModel.kt
> +    fun addItems(items: List<Any>)
제네릭을 쓰시는게 어떨까요?

2020-04-08 01:23 UTC, improve777 commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ui/adapter/MovieRecyclerAdapter.kt
> +        }
타입 체크가 없어도 될것 같습니다

2020-04-08 01:23 UTC, improve777 commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/util/CustomImageWithGlide.kt
> +) : androidx.appcompat.widget.AppCompatImageView(context, attrs, defAttrs) {
패키지를 import 로 빼주세요

2020-04-08 01:23 UTC, improve777 commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/util/CustomImageWithGlide.kt
> +package com.tsdev.tsandroid.util
util 보다는 `ui.widget` 같은 패키지가 적합할 것 같아요

2020-04-08 02:03 UTC, TaeseongYun commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/NaverAPI.kt
> +        get() = createRetrofit(baseUrl, MovieInterface::class.java)
lazy를 이용해서 메소드를 호출할까 하다가 get()으로 호출시켰는데 lazy로 호출해도 결국 호출시 초기화가 되어버리니까 똑같다는 느낌이 들어 get()으로 하였는데 lazy를 이용하는게 맞는방법인가요?

2020-04-08 02:05 UTC, TaeseongYun commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ui/MainActivity.kt
> +        }
movie_recycler라는 findViewById를 통해 이미 생성된 객체라서 run을 이용하였는데 후에 리사이클러 매개변수(ex. scrollListener)를 사용하게 된다면 run 이 더 좋지않나요?

2020-04-08 02:07 UTC, TaeseongYun commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/util/CustomImageWithGlide.kt
> +package com.tsdev.tsandroid.util
수정하였습니다. d761f55

2020-04-08 02:09 UTC, TaeseongYun commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/util/CustomImageWithGlide.kt
> +) : androidx.appcompat.widget.AppCompatImageView(context, attrs, defAttrs) {
수정하였습니다. 1c2e002

2020-04-08 02:11 UTC, TaeseongYun commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ui/MainActivity.kt
> +        disposable.clear()
수정완료하였습니다. 44a2370

2020-04-08 02:13 UTC, TaeseongYun commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ui/MainActivity.kt
> +    private fun getMovieList(disposable: CompositeDisposable, query: String) {
수정했습니다. 20f8ce7

2020-04-08 05:33 UTC, improve777 commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ui/MainActivity.kt
> +        }
그렇네요 @TaeseongYun 님 말씀이 맞는거 같아요 :smile:

2020-04-08 05:35 UTC, improve777 commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/NaverAPI.kt
> +        get() = createRetrofit(baseUrl, MovieInterface::class.java)
lazy 로 하셔도 되고
```kotlin
val movieAPI = createRetrofit(baseUrl, MovieInterface::class.java)
``` 
로 해도 됩니다

2020-04-08 12:20 UTC, TaeseongYun commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/base/BaseRecyclerAdapter.kt
> +        createBindViewHolder(holder, position)
삭제 후 onBindViewHolder 호출로 변경하였습니다 
00c9993

2020-04-08 12:20 UTC, TaeseongYun commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ui/adapter/MovieRecyclerAdapter.kt
> +        }
수정 하였습니다. 
00c9993

2020-04-08 12:20 UTC, TaeseongYun commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/base/BaseRecyclerAdapter.kt
> +    internal val movieList = mutableListOf<ITEM>()
수정하였습니다 
00c9993

2020-04-08 12:24 UTC, TaeseongYun commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/NaverAPI.kt
> +        get() = createRetrofit(baseUrl, MovieInterface::class.java)
수정하였습니다.
e8ffb5f

2020-04-08 12:27 UTC, TaeseongYun commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/base/RecyclerViewModel.kt
> +    fun addItems(items: List<Any>)
수정하였습니다.
311f4d8

2020-04-08 12:34 UTC, invitejay commented
확인했습니다 ! 다른 분이 많이 도와주셔서 감개무량 하네요...! 더 공부 열심히 하도록 하겠습니다

2020-04-08 15:21 UTC, sjjeong requested changes

2020-04-08 15:21 UTC, sjjeong commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/base/BaseRecyclerViewHolder.kt
> +    }
BaseRecyclerAdapter.kt에서  BaseRecyclerViewHolder<*>를 BaseRecyclerViewHolder<ITEM>으로 변경하면 이 함수는 제거 할 수 있습니다.

2020-04-08 15:21 UTC, sjjeong commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/base/BaseRecyclerViewHolder.kt
> +typealias OnClickPositionEvent = (Int) -> Unit
사용되지 않고 있습니다.  제거해주셔도 좋을 것 같습니다.

2020-04-08 15:21 UTC, sjjeong commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/base/RecyclerViewModel.kt
> +    fun  addItem(item: ITEM)
reformat code 해주세요

2020-04-08 15:21 UTC, sjjeong commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ui/adapter/MovieRecyclerAdapter.kt
> +    }
이 함수는 BaseRecyclerAdapter로 옮길 수 있습니다.

2020-04-08 15:21 UTC, sjjeong commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/createRetrofit.kt
> +package com.tsdev.tsandroid
파일명은 대문자 카멜케이스로 해주세요

2020-04-08 15:21 UTC, sjjeong commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/createRetrofit.kt
> +}
아래 okHttpClient()를 public으로 바꾸면 이렇게 변경 할 수 있습니다.
```kotlin
inline fun <reified T> createRetrofit(baseUrl: String): T {
    return Retrofit.Builder()
        .addConverterFactory(GsonConverterFactory.create())
        .addCallAdapterFactory(RxJava3CallAdapterFactory.create())
        .baseUrl(baseUrl)
        .client(okHttpClient())
        .build()
        .create(T::class.java)
}
```

2020-04-08 15:21 UTC, sjjeong commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/createRetrofit.kt
> +            level = HttpLoggingInterceptor.Level.BODY
BuildConfig.DEBUG로 분기를 만들어서 Debug일 때만 BODY를 적용하게 하고 그게 아니면 NONE을 적용해주세요

2020-04-08 15:21 UTC, sjjeong commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ui/viewholder/MovieRecyclerViewViewHolder.kt
> +            adapterPosition.takeIf { adapterPosition > -1 }.apply {
apply보단 ?.let이 더 나아보입니다.

2020-04-08 15:21 UTC, sjjeong commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ui/MainActivity.kt
> +                    movieRecyclerAdapter.addItems(it.items)
새로운 query로 검색하면 리스트를 새로 갱신해줘야 합니다.
지금은 기존꺼에 add해주고 있습니다.

2020-04-08 18:44 UTC, improve777 commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/util/CustomImageWithGlide.kt
> +package com.tsdev.tsandroid.util
커스텀뷰라서 ui 패키지가 적합하다고 생각했는데 혹시 `util.widget` 으로 수정해주신 이유가 있을까요?

2020-04-08 19:19 UTC, TaeseongYun commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/createRetrofit.kt
> +            level = HttpLoggingInterceptor.Level.BODY
수정하였습니다. 7b5ae68

2020-04-08 19:22 UTC, TaeseongYun commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ui/viewholder/MovieRecyclerViewViewHolder.kt
> +            adapterPosition.takeIf { adapterPosition > -1 }.apply {
수정하였습니다. faa10f2

2020-04-08 19:24 UTC, TaeseongYun commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/base/BaseRecyclerViewHolder.kt
> +typealias OnClickPositionEvent = (Int) -> Unit
수정하였습니다. 89bc195

2020-04-08 19:31 UTC, TaeseongYun commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/base/BaseRecyclerViewHolder.kt
> +    }
수정하였습니다. de50bb0

2020-04-08 19:31 UTC, TaeseongYun commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ui/adapter/MovieRecyclerAdapter.kt
> +    }
수정하였습니다 .de50bb0

2020-04-08 19:33 UTC, TaeseongYun commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/createRetrofit.kt
> +package com.tsdev.tsandroid
수정하였습니다. ef3c320

2020-04-08 19:41 UTC, TaeseongYun commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/createRetrofit.kt
> +}
수정하였습니다. 0294686

2020-04-08 19:42 UTC, TaeseongYun commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/base/RecyclerViewModel.kt
> +    fun  addItem(item: ITEM)
수정하였습니다. 16f7855

2020-04-08 19:48 UTC, TaeseongYun commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ui/MainActivity.kt
> +                    movieRecyclerAdapter.addItems(it.items)
수정하였습니다. 95fb012

2020-04-09 14:59 UTC, sjjeong requested changes

2020-04-09 14:59 UTC, sjjeong commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/base/BaseRecyclerViewHolder.kt
> +    abstract fun onBindViewHolder(item: Item)
이렇게 하면 Item 클래스 말고 받을 수가 없습니다.
Adapter에 넘겨준 Generic을 받아서 type을 넣어주세요

2020-04-09 14:59 UTC, sjjeong commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ui/MainActivity.kt
> +                    } ?: movieRecyclerAdapter.addItems(movieResponse.items)
비어있는지 검사하는 로직은 불필요해 보입니다.
clear하고 addItems를 바로 해도 될 것 같은데 이렇게 하는 이유가 있나요?

2020-04-09 14:59 UTC, sjjeong commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/CreateRetrofit.kt
> +            level = if (BuildConfig.DEBUGING)
DEBUGING을 따로 만들지 않고 DEBUG값을 사용하시면 됩니다.

2020-04-09 14:59 UTC, sjjeong commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ui/viewholder/MovieRecyclerViewViewHolder.kt
> +            } ?: onClickListenerEvent.onClickEventListener(0)
adapterPosition이 -1 이하면 예상되지 않는 동작인데 0번째 인덱스를 넘기면 버그가 되지 않을까요?

2020-04-09 22:39 UTC, TaeseongYun commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ui/MainActivity.kt
> +                    } ?: movieRecyclerAdapter.addItems(movieResponse.items)
얘기치못한 버그가 발생할까봐 추가를 했었습니다 굳이 필요없을거 같네요 수정하였습니다.
a0ef0a7

2020-04-09 22:54 UTC, TaeseongYun commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/CreateRetrofit.kt
> +            level = if (BuildConfig.DEBUGING)
수정하였습니다. 7470ea5

2020-04-09 23:01 UTC, TaeseongYun commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/base/BaseRecyclerViewHolder.kt
> +    abstract fun onBindViewHolder(item: Item)
수정하였습니다.  0a2f3e9

2020-04-09 23:06 UTC, TaeseongYun commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ui/viewholder/MovieRecyclerViewViewHolder.kt
> +            } ?: onClickListenerEvent.onClickEventListener(0)
토스트를 띄우는것으로 수정하였습니다. 3e8397a

2020-04-10 12:31 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-04-11 04:28 UTC, ghost approved these changes

2020-04-11 05:06 UTC, merged