2003/kangraemin
sjjeong/GoogryAndroidArchitecutreStudy pull request #566
Opened 2020-04-07 13:46 UTC by kangraemin

2020-04-08 03:21 UTC, mtjin approved these changes
@sooakim 
고칠 부분이 없는 것 같아 approve 했습니다.

2020-04-08 03:21 UTC, mtjin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/splash/SplashViewModel.kt
> -    enum class SplashResult {
enum class 에서 Unit 타입으로 분리하신 이유가 있을까요?

2020-04-08 03:23 UTC, mtjin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/splash/SplashViewModel.kt
> -
enum class 에서 Unit 타입으로 분리하신 이유가 있을까요?

2020-04-08 03:23 UTC, mtjin approved these changes

2020-04-08 04:00 UTC, sjjeong commented
@kangraemin pr이름 변경해주세요

2020-04-08 12:41 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/splash/SplashViewModel.kt
> -
@mtjin 아무래도 분기를 액티비티에 한다는게 어색해서 석준님한테 여쭤봤었는데 상태 하나하나에 대한 변수들로 쪼개는게 맞다고 하셔셔 분리했습니다

2020-04-08 14:14 UTC, sjjeong requested changes

2020-04-08 14:14 UTC, sjjeong commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/login/LoginActivity.kt
> +        loginViewModel.registerLoginInfoListener.observe(this, Observer {
MediatorLiveData는 이런 용도로 쓰시면 안됩니다.
source를 observeForever해서 사용해주세요

2020-04-09 13:25 UTC, kangraemin commented on 2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/login/LoginActivity.kt
> +        loginViewModel.registerLoginInfoListener.observe(this, Observer {
수정하였습니다 
4ee1a54

2020-04-09 15:03 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-04-10 12:47 UTC, merged