HW-1 Naver Movie Project
sjjeong/GoogryAndroidArchitecutreStudy pull request #567
Opened 2020-04-07 16:06 UTC by jesterz91

2020-04-08 12:38 UTC, TaeseongYun reviewed
rxbinding과 rxjava를 이용하신거 같은데 궁금한 점이 있어 남깁니다~

2020-04-08 12:38 UTC, TaeseongYun commented on 2004/jesterz91/app/src/main/java/io/github/jesterz91/study/presentation/ui/MovieSearchActivity.kt
> +            .doOnNext { binding.progressBar.toGone() }
doOn... 함수는 오류를 잡기위해 사용한다고 알고있는데 여기서 뷰 처리를 해도 괜찮은가요?

2020-04-08 16:23 UTC, Kyudong3 reviewed
제가 봤을 때 리뷰할 것이 생각나지가 않네요 ㅜㅜ. 제가 리뷰를 봐야하지만 병준님 코드 보고 많이 배우는 것 같네요..! 더 공부해서 리뷰를 더 열심해 해 보겠습니다!

2020-04-08 16:23 UTC, Kyudong3 commented on 2004/jesterz91/app/src/main/java/io/github/jesterz91/study/presentation/ui/MovieSearchActivity.kt
> +            layoutManager = LinearLayoutManager(this@MovieSearchActivity)
스타일에 따라 다르겟지만 xml 파일에 직접 설정해줘도 좋을 것 같아요! ( app:layoutManager="androidx.recyclerview.widget.LinearLayoutManager" )

2020-04-10 02:47 UTC, jesterz91 commented on 2004/jesterz91/app/src/main/java/io/github/jesterz91/study/presentation/ui/MovieSearchActivity.kt
> +            .doOnNext { binding.progressBar.toGone() }
넵

2020-04-10 02:49 UTC, jesterz91 commented on 2004/jesterz91/app/src/main/java/io/github/jesterz91/study/presentation/ui/MovieSearchActivity.kt
> +            layoutManager = LinearLayoutManager(this@MovieSearchActivity)
네. 반영하겠습니다~

2020-04-10 02:51 UTC, jesterz91 commented on 2004/jesterz91/app/src/main/java/io/github/jesterz91/study/presentation/ui/MovieSearchActivity.kt
> +            .doOnNext { binding.progressBar.toGone() }
네

2020-04-10 12:54 UTC, jesterz91 commented on 2004/jesterz91/app/src/main/java/io/github/jesterz91/study/presentation/ui/MovieSearchActivity.kt
> +            layoutManager = LinearLayoutManager(this@MovieSearchActivity)
수정했습니다.  016e965

2020-04-11 01:45 UTC, Kyudong3 approved these changes
확인했습니다!

2020-04-11 03:47 UTC, sjjeong requested changes

2020-04-11 03:47 UTC, sjjeong commented on 2004/jesterz91/app/src/main/java/io/github/jesterz91/study/presentation/ui/MovieSearchAdapter.kt
> +class MovieSearchAdapter(override val items: MutableList<Movie>) :
items를 생성자로 받지 마시고 부모 클래스에서 abstract대신 val tiems = mutableListOf<ITEM>()으로 선언해주세요

2020-04-11 03:47 UTC, sjjeong commented on 2004/jesterz91/app/src/main/java/io/github/jesterz91/study/presentation/ui/MovieSearchAdapter.kt
> +    }
이 함수도 BaseAdapter에 있어도 될 것 같아요

2020-04-11 03:47 UTC, sjjeong commented on 2004/jesterz91/app/src/main/java/io/github/jesterz91/study/presentation/ui/MovieSearchActivity.kt
> +            .doOnNext { binding.progressBar.toGone() }
@TaeseongYun 
doOn이 debug용으로 사용한다고 나와있긴한데 어떤 이벤트가 발생 했을 때 처리 하기 위한 용도로도 사용합니다.

2020-04-11 04:40 UTC, jesterz91 commented on 2004/jesterz91/app/src/main/java/io/github/jesterz91/study/presentation/ui/MovieSearchAdapter.kt
> +class MovieSearchAdapter(override val items: MutableList<Movie>) :
수정 했습니다!  fad2e7e

2020-04-11 04:40 UTC, jesterz91 commented on 2004/jesterz91/app/src/main/java/io/github/jesterz91/study/presentation/ui/MovieSearchAdapter.kt
> +    }
수정 했습니다!  fad2e7e

2020-04-11 05:05 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-04-11 05:06 UTC, merged