2003/tjdwlsl1021
sjjeong/GoogryAndroidArchitecutreStudy pull request #568
Opened 2020-04-08 03:24 UTC by tjdwlsl1021

리뷰요청 드립니다.

2020-04-08 04:00 UTC, sjjeong commented
@tjdwlsl1021  pr이름 변경해주세요

2020-04-08 04:14 UTC, tjdwlsl1021 commented
> @tjdwlsl1021 pr이름 변경해주세요

네 변경했습니다.

2020-04-09 04:12 UTC, byiryu approved these changes
고생하셨씁니다

2020-04-09 15:04 UTC, sjjeong requested changes

2020-04-09 15:04 UTC, sjjeong commented on 2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/ui/SearchMovieActivity.kt
> +            this@SearchMovieActivity.movieAdapter.addItems(viewModel.movieList.value)
this@SearchMovieActivity. 는 생략해도 됩니다

2020-04-10 22:54 UTC, tjdwlsl1021 commented on 2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/ui/SearchMovieActivity.kt
> +            this@SearchMovieActivity.movieAdapter.addItems(viewModel.movieList.value)
수정했습니다.
5d32e701af33b53753020a77a60100825448b1ef

2020-04-10 22:55 UTC, tjdwlsl1021 reviewed
리뷰 반영했습니다.

2020-04-11 03:06 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-04-12 23:39 UTC, merged