HW-4 mvvm + LiveData 수정
sjjeong/GoogryAndroidArchitecutreStudy pull request #57
Opened 2019-06-10 22:14 UTC by improve777

mvvm + LiveData 로 변경하면서 rxKotlin 을 추가해봤습니다..

2019-06-14 07:56 UTC, namjackson requested changes

2019-06-14 07:56 UTC, namjackson commented on improve777/GAASProject/app/src/main/java/dev/daeyeon/gaasproject/ui/ticker/TickerFragment.kt
> +            rvTicker.adapter = tickerAdapter
tickerAdapter를 따로 변수선언하지않고 바로 어댑터에 `TickerAdapter()`로 생성하시면 
코드가 더 짧아질거같아요!

2019-06-14 07:56 UTC, namjackson commented on improve777/GAASProject/app/src/main/java/dev/daeyeon/gaasproject/ui/ticker/TickerViewModel.kt
> +            success = {
baseCurrency, searchTicker  파라미터도 
success나 fail처럼 파라미터명을 지정해주면 가독성이 좋아질거같아요!

2019-06-14 07:56 UTC, namjackson commented on improve777/GAASProject/app/src/main/java/dev/daeyeon/gaasproject/ui/ticker/TickerViewModel.kt
> +                searchText.value = ""
searchText를 초기화해주는 이유가 있나요?
search Dialog 검색어 입력중
getTicker가 실행되면 searchText가 증발되는현상이 있습니다!

2019-06-15 11:24 UTC, improve777 commented on improve777/GAASProject/app/src/main/java/dev/daeyeon/gaasproject/ui/ticker/TickerFragment.kt
> +            rvTicker.adapter = tickerAdapter
수정완료했습니다

5d7a12a7a6b2b8869df9aa07fa2a6bd674154f00

2019-06-15 11:24 UTC, improve777 commented on improve777/GAASProject/app/src/main/java/dev/daeyeon/gaasproject/ui/ticker/TickerViewModel.kt
> +            success = {
수정 완료 했습니다

ead414484ce52691d6b256483ffae43b2ad228a4

2019-06-15 11:25 UTC, improve777 commented on improve777/GAASProject/app/src/main/java/dev/daeyeon/gaasproject/ui/ticker/TickerViewModel.kt
> +                searchText.value = ""
수정 완료했습니다

e0485cccd21aef2a50fcf6508ca000b3e0817766

2019-06-16 07:47 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-06-17 14:14 UTC, merged