HW-2 add Model Layer (Model 적용)
sjjeong/GoogryAndroidArchitecutreStudy pull request #572
Opened 2020-04-11 14:27 UTC by TaeseongYun

2020-04-15 14:56 UTC, ghost requested changes

2020-04-15 14:56 UTC, invitejay commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/data/repository/NaverRepositoryImpl.kt
> +    private fun convertRemoteData(movieResponse: MovieResponse): Single<List<Item>> {
음..보통 convert하는부분은 adapter에서 하는 코드들을 많이봐서요. 이렇게 처리할 경우에는 어떤점이 좋나요? 그리고 RepositoryImpl말고 RemoteDataSourceImpl에 위치하는건 어떤지 궁금합니당.

2020-04-15 14:56 UTC, invitejay commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/data/source/NaverRemoteDataSourceImpl.kt
> +class NaverRemoteDataSourceImpl(private val naverAPI: NaverMovieInterface) : NaverRemoteDataSource {
naverAPI를 RepositoryImpl 에서 부터 parameter로 계속 전달해주기보다는 RemoteDataSourceImpl에서 생성해주고 사용해주는건 어떤가용?

2020-04-15 14:56 UTC, invitejay commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/api/NaverAPI.kt
> +    val movieAPI by lazy {
object로 선언했고 아직 다른것들이 없기 때문에 lazy를 이용해주지 않아도 괜찮을거 같습니다.
그리고 혹시 이부분에서 CreateRetrofit과 분리해놓은 이유가 BASE_URL을 달리할수도 있다는 것 외에 다른 이유도 있나요?

2020-04-16 01:13 UTC, TaeseongYun commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/data/repository/NaverRepositoryImpl.kt
> +    private fun convertRemoteData(movieResponse: MovieResponse): Single<List<Item>> {
레포지토리에서 리사이클러 뷰 아이템 값을 알고있어도 되는지 안되는지 명확히 몰라서 이렇게 구현을 한거라 음 이건 저도 멘토님의 확인이 필요해요

2020-04-16 01:17 UTC, TaeseongYun commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/api/NaverAPI.kt
> +    val movieAPI by lazy {
다른 큰 이유는 없고 저는 레트로핏 생성함수를 따로 빼두는 편이에요.
그리고 lazy는 상관없지 않나요?

2020-04-16 01:33 UTC, invitejay commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/data/repository/NaverRepositoryImpl.kt
> +    private fun convertRemoteData(movieResponse: MovieResponse): Single<List<Item>> {
넵 알겠습니다

2020-04-16 01:35 UTC, invitejay commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/api/NaverAPI.kt
> +    val movieAPI by lazy {
넵 지금은 상관없을거 같습니다.

2020-04-16 10:28 UTC, TaeseongYun commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/data/source/NaverRemoteDataSourceImpl.kt
> +class NaverRemoteDataSourceImpl(private val naverAPI: NaverMovieInterface) : NaverRemoteDataSource {
수정하였습니다.  d381b0d

2020-04-16 10:56 UTC, invitejay commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/data/source/NaverRemoteDataSourceImpl.kt
> +class NaverRemoteDataSourceImpl(private val naverAPI: NaverMovieInterface) : NaverRemoteDataSource {
넵 확인했습니다

2020-04-16 12:03 UTC, sjjeong requested changes

2020-04-16 12:03 UTC, sjjeong commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/data/repository/NaverRepositoryImpl.kt
> +        }
concatMap말고 map만 사용 해도 될 것 같습니다.
map { movieMapConverter.toMap(it.items) }

2020-04-16 12:03 UTC, sjjeong commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/util/MapConverter.kt
> +        )
data class에 있는 copy 함수를 사용해서 변경되는 필드만 넣어주는 방법도 있습니다.

2020-04-16 12:03 UTC, sjjeong commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ui/MainActivity.kt
> +    private val naverRepository by lazy {
type을 NaverRepository로 지정해주면 좋을 것 같아요

2020-04-16 12:20 UTC, TaeseongYun commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/util/MapConverter.kt
> +        )
몰랐던 부분이군요! 수정하였습니다. a47dc0f

2020-04-16 12:21 UTC, TaeseongYun commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/data/repository/NaverRepositoryImpl.kt
> +        }
수정하였습니다. f688d51

2020-04-16 12:21 UTC, TaeseongYun commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ui/MainActivity.kt
> +    private val naverRepository by lazy {
타입 추가하였습니다. ad4d09e

2020-04-16 13:03 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-04-16 13:04 UTC, sjjeong commented
@invitejay 
리뷰 확인해주시고 approve 해주세요

2020-04-16 13:06 UTC, ghost approved these changes

2020-04-16 13:11 UTC, merged