HW-2 apply Model Layer
sjjeong/GoogryAndroidArchitecutreStudy pull request #575
Opened 2020-04-12 15:51 UTC by Kyudong3

Model 레이어를 적용하였습니다

2020-04-15 16:54 UTC, jesterz91 commented
리뷰 남깁니다.

2020-04-15 19:41 UTC, ios-byungjoon-lee reviewed
리뷰

2020-04-15 19:41 UTC, ios-byungjoon-lee commented on 2004/kyudong3/app/src/main/java/com/example/kyudong3/data/repository/MovieRepositoryImpl.kt
> +    }
movieDataSourceImpl의 데이터 타입을 MovieDataSource로 변경해주세요.

2020-04-15 19:41 UTC, ios-byungjoon-lee commented on 2004/kyudong3/app/src/main/java/com/example/kyudong3/MainActivity.kt
> +                    this.toast("검색결과가 없습니다")
toast함수 사용은 this 없이 사용할수 있습니다.

2020-04-16 12:11 UTC, sjjeong requested changes

2020-04-16 12:11 UTC, sjjeong commented on 2004/kyudong3/app/src/main/java/com/example/kyudong3/data/remote/MovieDataSource.kt
> +interface MovieDataSource {
Remote인지 Local인지 명시해주는게 좋습니다.
MovieRemoteDataSource로 변경해주시고 impl 쪽도 변경해주세요

2020-04-16 12:11 UTC, sjjeong commented on 2004/kyudong3/app/src/main/java/com/example/kyudong3/network/NaverApiService.kt
> +        @Header("X-Naver-Client-Secret") clientSecret: String = BuildConfig.CLIENT_SECRET,
이참에 retrofit interceptor에 대해 알아보시고 변경도 한번 해보세요

2020-04-16 12:12 UTC, sjjeong commented
@jesterz91 
리뷰하시고 나서 변경사항이 있다면 comment보단 requested change로 해주시고 answer needed 라벨 추가해주세요

2020-04-16 16:59 UTC, Kyudong3 commented on 2004/kyudong3/app/src/main/java/com/example/kyudong3/data/repository/MovieRepositoryImpl.kt
> +    }
수정했습니다!
7ba3ae2

2020-04-16 16:59 UTC, Kyudong3 commented on 2004/kyudong3/app/src/main/java/com/example/kyudong3/MainActivity.kt
> +                    this.toast("검색결과가 없습니다")
수정했습니다! 
566617f

2020-04-16 16:59 UTC, Kyudong3 commented on 2004/kyudong3/app/src/main/java/com/example/kyudong3/data/remote/MovieDataSource.kt
> +interface MovieDataSource {
수정했습니다! 
dd26b1b

2020-04-16 17:00 UTC, Kyudong3 commented on 2004/kyudong3/app/src/main/java/com/example/kyudong3/network/NaverApiService.kt
> +        @Header("X-Naver-Client-Secret") clientSecret: String = BuildConfig.CLIENT_SECRET,
잘 변경했는지 모르겠지만 수정했습니다!
829e21d

2020-04-17 02:12 UTC, ios-byungjoon-lee approved these changes
Good

2020-04-17 14:43 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-04-17 15:09 UTC, merged