HW-2 Model layer 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #577
Opened 2020-04-12 18:11 UTC by nukeolaf

Model layer 를 적용하였습니다

2020-04-13 15:27 UTC, ghost requested changes
✏️ 리뷰 남깁니다! 👀

2020-04-13 15:27 UTC, eunjin-hong commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/ui/MainActivity.kt
> +                        makeToast("${query}에 대한 검색결과가 없습니다")
String 안에 값을 넣을 때 객체의 멤버 변수를 부르거나, 함수를 호출하는 것이 아니라면 curly brackets 을 사용하지 않아도 되는 걸로 알고있습니다!

2020-04-13 15:27 UTC, eunjin-hong commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/data/local/MovieLocalDataSourceImpl.kt
> +        editor.putString("movies", GsonBuilder().create().toJson(movies))
putString(`"movies",` ...) 와 sharedPreferences.getString(`"movies"`, ... 에 사용되고 있는 것이 하나의 키네요! `values/strings.xml`을 이용하면, 두가지가 같은 키를 사용한다는 걸 명시적으로 알기도 쉽고, 오타로 인한 버그도 예방할 수 있을거같습니다.

2020-04-13 15:27 UTC, eunjin-hong commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/data/local/MovieLocalDataSourceImpl.kt
> +            null
return 값을 nullable하게 하는 것보다, null일 경우 exception을 던지는 것이 더  좋을 것 같습니다!

2020-04-13 15:27 UTC, eunjin-hong commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/data/local/MovieLocalDataSourceImpl.kt
> +            null
또한 if (movies != null) 보다,  line 19 뒤에 elvis `?: ` 를 붙여서 null 처리를 하면 더 간결한 코드를 작성할 수 있습니다!

2020-04-13 15:27 UTC, eunjin-hong commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/data/local/MovieLocalDataSourceImpl.kt
> +        context.getSharedPreferences("movies", Context.MODE_PRIVATE)
아래에 사용된 movies 와는 다른 용도의 키로 보입니다. 이 역시 string.xml로 정리하여 사용하면 간결하게 사용할 수 있을 것 같습니다.

2020-04-15 06:07 UTC, nukeolaf commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/ui/MainActivity.kt
> +                        makeToast("${query}에 대한 검색결과가 없습니다")
넵넵 저도 그렇게 알고 있는데, curly brackets 를 제거하면 이상하게 query 를 인식을 못하더라구요...ㅠㅠ

2020-04-15 06:21 UTC, nukeolaf commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/data/local/MovieLocalDataSourceImpl.kt
> +            null
저기서 return 값을 nullable 하게 던진 이유는 로컬에 저장된 영화 데이터가 아무것도 없는 경우를 return 값이 null 값인 경우로 판별하도록 로직을 구성해서입니다. 혹시 제 방법이 좀 이상한가요?? ㅠㅠ

2020-04-15 06:21 UTC, nukeolaf commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/data/local/MovieLocalDataSourceImpl.kt
> +        editor.putString("movies", GsonBuilder().create().toJson(movies))
수정했습니다!
f99190f

2020-04-15 06:21 UTC, nukeolaf commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/data/local/MovieLocalDataSourceImpl.kt
> +        context.getSharedPreferences("movies", Context.MODE_PRIVATE)
수정했습니다!
f99190f

2020-04-15 14:52 UTC, eunjin-hong commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/data/local/MovieLocalDataSourceImpl.kt
> +            null
null을 return 하는 것은 괜찮습니다. 저는 보통 null을 내보내야하는 경우 exception을 던지는 걸 선호하는 편이라서요 ㅎㅎ.
(+) 하지만, 코틀린에서 `if (tempNullable != null)` 와 같은 null checking은 지양하는 것으로 알고 있습니다! elvis operator(?:)로 더 짧게 작성할 수 있거든요! [여기](https://kotlinlang.org/docs/reference/null-safety.html) 를 한번 참고해보세요!

2020-04-16 11:38 UTC, sjjeong commented
@nukeolaf @eunjin-hong 
리뷰 하시면서 라벨도 꼭 변경해주세요
현재 이 pr은 리뷰가 끝난 상태인가요?

2020-04-16 12:13 UTC, sjjeong commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/ui/MainActivity.kt
> +                        makeToast("${query}에 대한 검색결과가 없습니다")
@eunjin-hong @nukeolaf 
뒤에 "에" 라는 단어가 바로 붙어서 {}를 추가해주셔야 해요
"$query 에 대한 검색결과가 없습니다" 는 되는데
"$query에 대한 검색결과가 없습니다" 는 안돼요

2020-04-16 12:34 UTC, sjjeong requested changes

2020-04-16 12:34 UTC, sjjeong commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/data/local/MovieLocalDataSourceImpl.kt
> +            GsonBuilder().create().fromJson(movies, MovieResponse::class.java)
GsonBuilder().create() 이것도 위에 sharedPreferences 처럼 선언하면 좋을 것 같아요

2020-04-16 12:34 UTC, sjjeong commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/data/local/MovieLocalDataSourceImpl.kt
> +    private val editor = sharedPreferences.edit()
edit()함수는 사용할 때 호출 해야 해요 아래 코드들을 전부 sharedPreferences를 통해 접근하도록 변경해주세요

2020-04-16 12:34 UTC, sjjeong commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/data/local/MovieLocalDataSourceImpl.kt
> +            null
movies가 null 일 때 null을 리턴하는 것이라면 if 분기코드가 필요 없습니다.
```kotlin
return GsonBuilder().create().fromJson(movies, MovieResponse::class.java)
```

2020-04-16 12:34 UTC, sjjeong commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/network/RetrofitInterface.kt
> +        @QueryMap options: MutableMap<String, Any>
MutableMap이 아닌 Map으로만 선언해도 됩니다.

2020-04-16 12:34 UTC, sjjeong commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/data/remote/MovieRemoteDataSourceImpl.kt
> +        )
이렇게만 넣어줘도 됩니다.
```kotlin
val options = mapOf(
    "query" to query,
    "display" to 10,
    "start" to 1
)
```

2020-04-16 12:34 UTC, sjjeong commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/ui/MainActivity.kt
> +        movieLocalDataSource = MovieLocalDataSourceImpl(this@MainActivity)
MainActivity보단 applicationContext를 넣어주세요

2020-04-16 19:17 UTC, nukeolaf commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/network/RetrofitInterface.kt
> +        @QueryMap options: MutableMap<String, Any>
그냥 Map 으로 선언하면 이런 에러가 발생해서
java.lang.IllegalArgumentException: Parameter type must not include a type variable or wildcard: java.util.Map<java.lang.String, ?> (parameter #1)
MutableMap 을 사용했습니다

2020-04-16 19:17 UTC, nukeolaf commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/network/RetrofitInterface.kt
> +        @QueryMap options: MutableMap<String, Any>
그냥 Map 으로 선언하면 이런 에러가 발생해서
`java.lang.IllegalArgumentException: Parameter type must not include a type variable or wildcard: java.util.Map<java.lang.String, ?> (parameter #1)`
MutableMap 을 사용했습니다

2020-04-16 19:25 UTC, nukeolaf commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/network/RetrofitInterface.kt
> +        @QueryMap options: MutableMap<String, Any>
@JvmSuppressWildcards 어노테이션을 사용하니 해결이 되는군요! 
수정했습니다.
103dafe

2020-04-16 19:25 UTC, nukeolaf commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/data/remote/MovieRemoteDataSourceImpl.kt
> +        )
수정했습니다!
103dafe

2020-04-16 19:25 UTC, nukeolaf commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/ui/MainActivity.kt
> +        movieLocalDataSource = MovieLocalDataSourceImpl(this@MainActivity)
수정했습니다!
2058666

2020-04-16 19:25 UTC, nukeolaf commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/data/local/MovieLocalDataSourceImpl.kt
> +            GsonBuilder().create().fromJson(movies, MovieResponse::class.java)
수정했습니다!
325bb47

2020-04-16 19:26 UTC, nukeolaf commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/data/local/MovieLocalDataSourceImpl.kt
> +    private val editor = sharedPreferences.edit()
수정했습니다!
be86b72

2020-04-16 19:26 UTC, nukeolaf commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/data/local/MovieLocalDataSourceImpl.kt
> +            null
수정했습니다!
9050fb5

2020-04-17 14:44 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-04-18 14:34 UTC, ghost approved these changes
LGTM 👍

2020-04-20 10:54 UTC, merged