HW-1 코인헬퍼 스터디 프로젝트 추가
sjjeong/GoogryAndroidArchitecutreStudy pull request #58
Opened 2019-06-11 12:08 UTC by machine-human

2019-06-11 13:01 UTC, sport0102 commented
프로젝트 폴더 경로가 이상합니다. 루트 밑에 프로젝트 폴더가 있는데, 이를 본인 이름의 폴더 하위로 이동시켜주세요.

2019-06-11 13:19 UTC, sport0102 commented
앱의 현재가에 천의 자리수 이상일 때, 컴마 처리해주세요.

2019-06-11 13:19 UTC, sport0102 commented
전일대비 부분 소수점으로 되어있는 것 퍼센트로 바꾸어주세요

2019-06-11 13:20 UTC, sport0102 commented
거래대금이 천의 자리수 이상일 때, 컴마 처리해주세요.

2019-06-11 13:21 UTC, sport0102 commented
BTC일 경우, 소수점이 많으면 지수 처리되어있는데 이부분 숫자로 나오게 해주세요

2019-06-11 13:22 UTC, sport0102 commented
USDT탭에 코인가격이 0원인 것들이 나오는데 이 부분 확인 부탁드립니다

2019-06-11 13:23 UTC, sport0102 commented on AndroidArchitectureStudy/app/src/main/res/values/strings.xml
> +    <string name="trade_Price">현재가</string>
스네이크+카멜 케이스로 되어있는데, 스네이크 케이스로 수정 부탁드리겠습니다

2019-06-11 13:31 UTC, sport0102 commented on AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/adapter/recyclerviewadapter/RecyclerviewAdapter.kt
> +class RecyclerviewAdapter(var tickerList: ArrayList<TickerModel>) :
클래스 명을 RecyclerviewAdapter가 아닌 어떤 리스트의 Adapter인지 명시해주는게 좋지 않을까요?(Recyclerview가 늘어날 경우 이름이 중복될 소지가 있습니다)

2019-06-11 13:33 UTC, sport0102 commented on AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/adapter/recyclerviewadapter/RecyclerviewAdapter.kt
> +        if (tickerList != null)
이부분은 tickerList?.clear() 가 코틀린스러울 것 같습니다

2019-06-11 13:34 UTC, sport0102 commented on AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/ui/fragment/MainFragment.kt
> +    private val baseUrl = "https://api.upbit.com"
baseUrl같은 건 strings.xml에 넣어두거나, 특정 Retrofit 관련 클래스에서 정의해주는게 좋을 것 같습니다

2019-06-11 13:47 UTC, sport0102 commented on AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/ui/fragment/MainFragment.kt
> +    override fun onActivityCreated(savedInstanceState: Bundle?) {
사용하지 않는 override 함수입니다 삭제해주세요

2019-06-11 13:48 UTC, sport0102 commented on AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/ui/fragment/MainFragment.kt
> +        recyclerView = view!!.findViewById(R.id.recyclerview_mainfragment)
코틀린에서는 view id를 바로 찾을 수 있는데 view.recyclerview_mainfragment 방식으로 하는게 어떨까요

2019-06-11 13:55 UTC, sport0102 commented on AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/ui/fragment/MainFragment.kt
> +                recyclerview_mainfragment.adapter = RecyclerviewAdapter(response?.body()!!)
이 부분에서 fragment의 adapter에 recyclerviewAdapter를 넣고 노티파이데이터체인지 하면 되는거 아닌가요? RecyclerviewAdapter(response?.body()!!)로 새롭게 객체를 만들어서 넣은 이유가 궁금합니다

2019-06-11 15:55 UTC, sport0102 requested changes
코멘트 확인해서 수정하실부분은 수정해주시고 라벨 review needed로 수정해주세요!

2019-06-11 20:16 UTC, machine-human commented on AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/ui/fragment/MainFragment.kt
> +        recyclerView = view!!.findViewById(R.id.recyclerview_mainfragment)
감사합니다. 변경 완료 했습니다.

> 4a583edcc9d86d8220bb803da64e1ae1f5a71903

2019-06-11 20:24 UTC, machine-human commented on AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/ui/fragment/MainFragment.kt
> +    override fun onActivityCreated(savedInstanceState: Bundle?) {
수정 완료 했는데, 커밋할 실수한거 같습니다...
프로젝트에는 적용 되어 있습니다 :)

2019-06-11 20:25 UTC, machine-human commented on AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/ui/fragment/MainFragment.kt
> +    private val baseUrl = "https://api.upbit.com"
어디로 옮길지 고민하다가 말았는데, 추후 비즈니스 로직 분리할때 같이 작업 하겠습니다. 감사합니다 :)

2019-06-11 20:28 UTC, machine-human commented on AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/adapter/recyclerviewadapter/RecyclerviewAdapter.kt
> +        if (tickerList != null)
코틀린에 익숙치 않아 놓친 부분인데 감사합니다.

작업 완료 했는데, 커밋할때 문제가 생긴거 같습니다.
내일 다시 반영하겠습니다.
(미완료)

2019-06-11 20:29 UTC, machine-human commented on AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/adapter/recyclerviewadapter/RecyclerviewAdapter.kt
> +class RecyclerviewAdapter(var tickerList: ArrayList<TickerModel>) :
리뷰 감사합니다 :) 수정 완료 했습니다.
536543ac631fbfd7984817de31ca488f7b34e33c

2019-06-11 20:31 UTC, machine-human commented on AndroidArchitectureStudy/app/src/main/res/values/strings.xml
> +    <string name="trade_Price">현재가</string>
수정 완료 했습니다. 감사합니다 :)
b871f941962a8bddb1b2cbd74f90e3d71849a48d

2019-06-11 20:33 UTC, machine-human commented on AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/ui/fragment/MainFragment.kt
> +                recyclerview_mainfragment.adapter = RecyclerviewAdapter(response?.body()!!)
아뇨 다른 의미는 없습니다.
급하게 만들다보니 신경을 못하고 넘어간거 같습니다.
피드백 감사합니다. :)

2019-06-11 20:36 UTC, machine-human commented
-프로젝트 경 변경 완료

-전일대비/거래대금 데이터 포맷 미완성 (내일 최종적으로 완성 후 다시 리뷰 반영하겠습니다 :)

2019-06-12 12:46 UTC, machine-human commented
c71d29a
나머지 기능 완료 하였습니다. 확인 부탁 드립니다 :)

2019-06-12 13:16 UTC, sport0102 commented
프로젝트가 루트 폴더 밑에도 바로 있고, 본인 폴더에도 있습니다. 최종 프로젝트가 루트 밑에 있는 폴더로 보입니다. 루트 밑에 있는 프로젝트 폴더를 본인 이름의 폴더 밑으로 이동시켜주시고 루트 밑에 있는 폴더는 삭제해 주세요

2019-06-12 13:19 UTC, sport0102 commented
> USDT탭에 코인가격이 0원인 것들이 나오는데 이 부분 확인 부탁드립니다

여전히 해결되지 않았네요 수정 부탁드리겠습니다

2019-06-12 13:28 UTC, sport0102 requested changes
꼬인 프로젝트 한곳으로 몰아서 해주시면 다시 확인하겠습니다

2019-06-12 14:48 UTC, machine-human commented
> 프로젝트 폴더 경로가 이상합니다. 루트 밑에 프로젝트 폴더가 있는데, 이를 본인 이름의 폴더 하위로 이동시켜주세요.

test

2019-06-12 14:54 UTC, machine-human commented on AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/adapter/recyclerviewadapter/RecyclerviewAdapter.kt
> +        if (tickerList != null)
https://github.com/machine-human/GoogryAndroidArchitectureStudy/blob/class02/machine-human/machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/adapter/recyclerviewadapter/MainListAdapter.kt

반영하였습니다 :)

2019-06-12 14:54 UTC, machine-human commented
> 프로젝트 폴더 경로가 이상합니다. 루트 밑에 프로젝트 폴더가 있는데, 이를 본인 이름의 폴더 하위로 이동시켜주세요.

> 앱의 현재가에 천의 자리수 이상일 때, 컴마 처리해주세요.

> 전일대비 부분 소수점으로 되어있는 것 퍼센트로 바꾸어주세요

> 거래대금이 천의 자리수 이상일 때, 컴마 처리해주세요.

> BTC일 경우, 소수점이 많으면 지수 처리되어있는데 이부분 숫자로 나오게 해주세요

> USDT탭에 코인가격이 0원인 것들이 나오는데 이 부분 확인 부탁드립니다

위 데이터 포멧 관련 작업 완료 하였습니다.
-https://github.com/machine-human/GoogryAndroidArchitectureStudy/blob/class02/machine-human/machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/util/FormatUtil.kt
-https://github.com/machine-human/GoogryAndroidArchitectureStudy/blob/class02/machine-human/machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/adapter/recyclerviewadapter/MainListAdapter.kt

2019-06-12 15:37 UTC, sport0102 commented on AndroidArchitectureStudy/app/src/main/res/values/strings.xml
> +    <string name="trade_Price">현재가</string>
반영이 안되어있습니다... 다시 확인 부탁드리겠습니다.

2019-06-12 15:37 UTC, sport0102 commented
> USDT탭에 코인가격이 0원인 것들이 나오는데 이 부분 확인 부탁드립니다

이 부분 반영이 안되어 있네요 다시 부탁드리겠습니다.

2019-06-12 15:41 UTC, sport0102 commented on AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/ui/fragment/MainFragment.kt
> +    override fun onActivityCreated(savedInstanceState: Bundle?) {
수정이 안되어있습니다 다시 확인 부탁드리겠습니다!

2019-06-12 15:43 UTC, sport0102 commented on AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/ui/fragment/MainFragment.kt
> +        recyclerView = view!!.findViewById(R.id.recyclerview_mainfragment)
반영이 안되었습니다 확인 부탁드리겠습니다

2019-06-12 15:43 UTC, sport0102 commented on AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/ui/fragment/MainFragment.kt
> +                recyclerview_mainfragment.adapter = RecyclerviewAdapter(response?.body()!!)
반영이 안되었습니다 확인 부탁드리겠습니다

2019-06-12 15:44 UTC, sport0102 requested changes
제가 댓글 남긴 코멘트 쪽 확인하셔서 다시 수정 부탁드리겠습니다.

2019-06-12 16:48 UTC, machine-human commented on AndroidArchitectureStudy/app/src/main/res/values/strings.xml
> +    <string name="trade_Price">현재가</string>
어제 커밋 시 꼬인 것 같습니다. 수정 완료 했습니다. 감시합니다!

8a6ef6a

2019-06-12 16:51 UTC, machine-human commented on AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/ui/fragment/MainFragment.kt
> +    override fun onActivityCreated(savedInstanceState: Bundle?) {
죄송합니다. 위 반영도 어제 커밋 시 꼬인 것 같습니다.
수정 완료 하였습니다. 감사합니다 :)
dc54fe4

2019-06-12 16:51 UTC, machine-human commented on AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/ui/fragment/MainFragment.kt
> +    override fun onActivityCreated(savedInstanceState: Bundle?) {
커밋을 분리하지 못 했습니다. 죄송합니다...

2019-06-12 16:53 UTC, machine-human commented on AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/ui/fragment/MainFragment.kt
> +        recyclerView = view!!.findViewById(R.id.recyclerview_mainfragment)
이것도 반영이 안 된거 같습니다.

dc54fe4
+ 커밋을 분리하지 못 했습니다.. 죄송합니다.

2019-06-12 16:56 UTC, machine-human commented on AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/ui/fragment/MainFragment.kt
> +                recyclerview_mainfragment.adapter = RecyclerviewAdapter(response?.body()!!)
수정 완료 했습니다. dc54fe4
제 프로젝트에 이런 부분이 익숙치 않아 위와 같은 코드가 많지만 많이 놓치는거 같아서 고민이 많았는데, 피드백 주셔서 정말 감사합니다.

2019-06-12 16:58 UTC, machine-human commented
> > USDT탭에 코인가격이 0원인 것들이 나오는데 이 부분 확인 부탁드립니다
> 
> 이 부분 반영이 안되어 있네요 다시 부탁드리겠습니다.

수정 완료 했습니다. 1d3e115
꼼꼼한 리뷰 해주셔서 정말 감사합니다.
매주 더욱 공부해서 선민님께도 좋은 리뷰가 되도록 노력하겠습니다.

2019-06-13 03:05 UTC, sport0102 commented on AndroidArchitectureStudy/app/src/main/res/values/strings.xml
> +    <string name="trade_Price">현재가</string>
accTrade_price 부분도 바꾸어주세요!

2019-06-13 03:17 UTC, sport0102 commented on AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/ui/fragment/MainFragment.kt
> +        recyclerView = view!!.findViewById(R.id.recyclerview_mainfragment)
recyclerView라는 변수가 있을 필요가 없을 것 같습니다. 삭제하시고 뷰 id 그대로 사용하시면 될 것 같아요!

2019-06-13 03:21 UTC, sport0102 requested changes
2가지 코멘트 부분 마무리 해주시고 라벨 바꾸셔서 다시 보내주세요!

2019-06-13 08:21 UTC, machine-human commented on AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/ui/fragment/MainFragment.kt
> +        recyclerView = view!!.findViewById(R.id.recyclerview_mainfragment)
변경 완료 했습니다. 감사합니다.
d8878ac

2019-06-13 08:22 UTC, machine-human commented on AndroidArchitectureStudy/app/src/main/res/values/strings.xml
> +    <string name="trade_Price">현재가</string>
죄송합니다.. 한 부분을 놓쳤네요.. 리뷰 감사합니다!
4d2797c

2019-06-13 08:23 UTC, machine-human commented
2가지 코멘트 마무리 했습니다. 확인 부탁드립니다 :)

2019-06-13 10:32 UTC, sport0102 submitted a review, later dismissed
LGTM!

2019-06-13 15:00 UTC, sjjeong requested changes
코드에 !!를 사용하지 않고 null 핸들링 해주세요.

2019-06-13 15:00 UTC, sjjeong commented on machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/util/FormatUtil.kt
> +    fun commaDoubleFormat(number: Double) = format.format(number).toString()
format함수의 return이 String이기 때문에 toString()은 필요하지 않습니다

2019-06-13 15:00 UTC, sjjeong commented on machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/util/FormatUtil.kt
> +        if (number < 1) {
return은 if 앞에 빼서 사용할 수 있습니다.
아래 accTradePriceFormat도 동일합니다

2019-06-13 15:00 UTC, sjjeong commented on machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/api/model/MarketModel.kt
> +    val market: String,
Property 이름은 camelCase로 적용해주세요

2019-06-13 15:00 UTC, sjjeong commented on machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/adapter/viewpageradapter/MainViewPagerAdapter.kt
> +        return fragmentList.get(position)
kotlin에서는 get대신 []로 사용할 수 있습니다

2019-06-13 15:00 UTC, sjjeong commented on machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/adapter/recyclerviewadapter/MainListAdapter.kt
> +class MainListAdapter(var tickerList: ArrayList<TickerModel>) :
외부에서 List를 받아서 사용하는 것은 좋지 않습니다.
내부에 별도 List를 만들어 사용해주세요

2019-06-13 15:00 UTC, sjjeong commented on machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/adapter/recyclerviewadapter/MainListAdapter.kt
> +        val v = LayoutInflater.from(viewGroup?.context).inflate(R.layout.item_ticker, viewGroup, false)
viewGroup은 NonNull입니다

2019-06-13 15:00 UTC, sjjeong commented on machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/adapter/recyclerviewadapter/MainListAdapter.kt
> +    override fun getItemCount(): Int = tickerList!!.size
tickerList는 NonNull입니다

2019-06-13 15:00 UTC, sjjeong commented on machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/adapter/recyclerviewadapter/MainListAdapter.kt
> +            with(holder.itemView) {
ViewHolder에 데이터를 set해주는 부분은 ViewHolder내부에 함수를 구현해서 작업해주세요.

2019-06-13 15:00 UTC, sjjeong commented on machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/ui/activity/MainActivity.kt
> +        var firstFragmet: MainFragment = MainFragment.createInstance("KRW")
오타 수정해주세요

2019-06-13 15:00 UTC, sjjeong commented on machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/ui/activity/MainActivity.kt
> +        var secondFragmet: MainFragment = MainFragment.createInstance("BTC")
val로 사용하시면 됩니다

2019-06-13 15:00 UTC, sjjeong commented on machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/ui/activity/MainActivity.kt
> +            getSupportFragmentManager()
supportFragmentManager로 변경할 수 있습니다.

2019-06-13 15:00 UTC, sjjeong commented on machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/ui/activity/MainActivity.kt
> +    private lateinit var viewpager_main: ViewPager
camelCase 형식으로 변경해주세요

2019-06-13 15:00 UTC, sjjeong commented on machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/ui/activity/MainActivity.kt
> +        viewpager_main!!.adapter = adapter
NonNull이라서 !!가 필요 없습니다

2019-06-13 15:00 UTC, sjjeong commented on machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/ui/fragment/MainFragment.kt
> +    companion object {
companion object는 클래스 맨 아래에 작성해주세요
https://kotlinlang.org/docs/reference/coding-conventions.html#class-layout

2019-06-13 15:00 UTC, sjjeong commented on machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/ui/fragment/MainFragment.kt
> +            fragmentInstance.setArguments(bundle)
```kotlin
fragmentInstance.arguments = bundle
```
처럼 변경 할 수 있습니다.

2019-06-13 15:00 UTC, sjjeong commented on machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/ui/fragment/MainFragment.kt
> +    private val restApi: UPbitApi
restApi보다 upbitApi가 좋을 것 같습니다.

2019-06-13 15:00 UTC, sjjeong commented on machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/api/UPbitApi.kt
> +interface UPbitApi {
UpbitApi로 이름 수정해주세요

2019-06-13 15:00 UTC, sjjeong commented on machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/ui/fragment/MainFragment.kt
> +        var view: View? = inflater.inflate(R.layout.fragment_main, container, false);
; 제거해주세요

2019-06-13 15:00 UTC, sjjeong commented on machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/ui/fragment/MainFragment.kt
> +    override fun setUserVisibleHint(isVisibleToUser: Boolean) {
이 함수를 넣어서 getMarketList가 onCreateView와 함께 두번 호출 됩니다.
이 부분 수정해 주세요.

2019-06-13 15:00 UTC, sjjeong commented on machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/ui/fragment/MainFragment.kt
> +            val message = arguments!!.getString(EXTRA_MESSAGE)
arguments에서 가져오는 코드가 여러곳에 있기 때문에 message는 class property로 저장하고 사용하면 될 것 같습니다.

2019-06-13 15:00 UTC, sjjeong commented on machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/ui/fragment/MainFragment.kt
> +                response?.let {
response는 NonNull입니다.

2019-06-13 15:00 UTC, sjjeong commented on machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/ui/fragment/MainFragment.kt
> +                    val responseList = response.body()!!
!!는 null이 아니라고 확신할수 있을 때 사용해주세요.
가끔식 서버에 응답에 따라 body가 null이 될 수 있습니다.

2019-06-13 15:00 UTC, sjjeong commented on machine-human/AndroidArchitectureStudy/app/src/main/res/layout/fragment_main.xml
> +        android:layout_height="match_parent"></android.support.v7.widget.RecyclerView>
자식뷰가 없다면 />로 끝내주세요

2019-06-13 15:00 UTC, sjjeong commented on machine-human/AndroidArchitectureStudy/app/src/main/res/layout/item_ticker.xml
> +        android:paddingLeft="10dp"
paddingLeft대신 paddingStart를 사용해주세요

2019-06-13 15:00 UTC, sjjeong commented on machine-human/AndroidArchitectureStudy/app/src/main/res/layout/item_ticker.xml
> +        android:gravity="center|left"
center_vertical|start 로 변경해주세요.

2019-06-14 05:42 UTC, machine-human commented
와.. 완전 꼼꼼한 리뷰 정말 감사합니다 👍 

짝꿍님/스터디장님 서로 다른 시선의 리뷰를 받으니까 저도 시선이 넓어지고 정말 좋은거 같습니다.

수정 후 다시 요청 드리겠습니다. 

두분께 다시 한번 진심으로 감사드립니다. :)

2019-06-14 18:28 UTC, machine-human commented on machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/util/FormatUtil.kt
> +    fun commaDoubleFormat(number: Double) = format.format(number).toString()
감사합니다. return 타입을 생각 못 했습니다.

92f41e0 (커밋을 분리하지 못 했습니다..)

2019-06-14 18:29 UTC, machine-human commented on machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/util/FormatUtil.kt
> +        if (number < 1) {
감사합니다. 수정 완료 했습니다.

92f41e0

2019-06-14 18:30 UTC, machine-human commented on machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/api/model/MarketModel.kt
> +    val market: String,
프로젝트 추가 전엔 naming rule에 신경 썼는데, 막상 시작하니 잊고 진행한거 같습니다. 감사합니다.
ea490e4

2019-06-14 18:30 UTC, machine-human commented on machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/adapter/viewpageradapter/MainViewPagerAdapter.kt
> +        return fragmentList.get(position)
감사합니다. 수정하였습니다. 
f0e75d1

2019-06-14 18:32 UTC, machine-human commented on machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/adapter/recyclerviewadapter/MainListAdapter.kt
> +class MainListAdapter(var tickerList: ArrayList<TickerModel>) :
이유에 대해 아직 찾아보지 못 했습니다. 추후 프로젝트 진행하면서 찾아보겠습니다.
감사합니다.
996578e

2019-06-14 18:33 UTC, machine-human commented on machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/adapter/recyclerviewadapter/MainListAdapter.kt
> +        val v = LayoutInflater.from(viewGroup?.context).inflate(R.layout.item_ticker, viewGroup, false)
감사합니다. 수정 했습니다.

a86c2ea

2019-06-14 18:33 UTC, machine-human commented on machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/adapter/recyclerviewadapter/MainListAdapter.kt
> +    override fun getItemCount(): Int = tickerList!!.size
감사합니다. 수정 했습니다.
53a70be

2019-06-14 18:34 UTC, machine-human commented on machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/adapter/recyclerviewadapter/MainListAdapter.kt
> +            with(holder.itemView) {
해당 내용도 이유에 대해 아직 찾아보지 못 했습니다. 추후 찾아보겠습니다.
감사합니다 :)

996578e

2019-06-14 18:34 UTC, machine-human commented on machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/ui/activity/MainActivity.kt
> +        var firstFragmet: MainFragment = MainFragment.createInstance("KRW")
오타도 찾아주셨네요.. 감사합니다. 수정 완료 했습니다.

809d5df

2019-06-14 18:36 UTC, machine-human commented on machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/ui/activity/MainActivity.kt
> +        var secondFragmet: MainFragment = MainFragment.createInstance("BTC")
엇 반영이 안 된거 같습니다. 재 반영 하겠습니다.

2019-06-14 18:37 UTC, machine-human commented on machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/ui/activity/MainActivity.kt
> +            getSupportFragmentManager()
변경 완료 하였습니다. 감사합니다.

5b6ac62

2019-06-14 18:39 UTC, machine-human commented on machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/ui/activity/MainActivity.kt
> +    private lateinit var viewpager_main: ViewPager
커밋이 안 된거 같습니다. 링크로 대체 하겠습니다. 죄송합니다.

https://github.com/machine-human/GoogryAndroidArchitectureStudy/blob/class02/machine-human/machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/ui/activity/MainActivity.kt

2019-06-14 18:40 UTC, machine-human commented on machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/ui/activity/MainActivity.kt
> +        viewpager_main!!.adapter = adapter
감사합니다. 수정 했습니다.
117eb508e2fa314ca45170e794ee3ab90af38d07

2019-06-14 18:41 UTC, machine-human commented on machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/ui/fragment/MainFragment.kt
> +    companion object {
오 이 내용은 지나쳤습니다. 감사합니다 :)

b99ba87

2019-06-14 18:41 UTC, machine-human commented on machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/ui/fragment/MainFragment.kt
> +            fragmentInstance.setArguments(bundle)
감사합니다. 수정 완료 했습니다.

fee2de9

2019-06-14 18:42 UTC, machine-human commented on machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/ui/fragment/MainFragment.kt
> +    private val restApi: UPbitApi
클래스명,변수명 등 가독성이 매우 떨어진다고 생각했는데, 
리뷰 해주셔서 정말 감사합니다. 수정 완료 했습니다.

21bf820

2019-06-14 18:42 UTC, machine-human commented on machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/api/UPbitApi.kt
> +interface UPbitApi {
감사합니다. 수정 완료했습니다.

2566163

2019-06-14 18:43 UTC, machine-human commented on machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/ui/fragment/MainFragment.kt
> +        var view: View? = inflater.inflate(R.layout.fragment_main, container, false);
반영이 안 된거 같습니다. 재 반영 하도록 하겠습니다.

2019-06-14 18:45 UTC, machine-human commented on machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/ui/fragment/MainFragment.kt
> +    override fun setUserVisibleHint(isVisibleToUser: Boolean) {
반영이 안 되었습니다. 죄송합니다. 링크로 대체 하겠습니다.
https://github.com/machine-human/GoogryAndroidArchitectureStudy/blob/class02/machine-human/machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/ui/fragment/MainFragment.kt

2019-06-14 18:46 UTC, machine-human commented on machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/ui/fragment/MainFragment.kt
> +            val message = arguments!!.getString(EXTRA_MESSAGE)
class property로 저장하고 사용하라는 말씀은
data class를 이용 하라는 말씀이신가요..?
이해를 못 해서 반영하지 못 했습니다.
답변 받은 후 재 반영 하도록 하겠습니다.

2019-06-14 18:48 UTC, machine-human commented on machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/ui/fragment/MainFragment.kt
> +                response?.let {
반영이 안 되었습니다. 링크로 대체 하겠습니다.
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/58/commits/7d83ae6a8b37fde744a9d690c84c31f731493bf9

2019-06-14 18:48 UTC, machine-human commented on machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/ui/fragment/MainFragment.kt
> +                    val responseList = response.body()!!
감사합니다 :)
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/58/commits/7d83ae6a8b37fde744a9d690c84c31f731493bf9

2019-06-14 18:49 UTC, machine-human commented on machine-human/AndroidArchitectureStudy/app/src/main/res/layout/fragment_main.xml
> +        android:layout_height="match_parent"></android.support.v7.widget.RecyclerView>
감사합니다. 수정 완료 했습니다.

fef9018

2019-06-14 18:49 UTC, machine-human commented on machine-human/AndroidArchitectureStudy/app/src/main/res/layout/item_ticker.xml
> +        android:paddingLeft="10dp"
감사합니다. 수정 완료 했습니다.

74a6790

2019-06-14 18:50 UTC, machine-human commented on machine-human/AndroidArchitectureStudy/app/src/main/res/layout/item_ticker.xml
> +        android:gravity="center|left"
감사합니다. 수정 완료 했습니다.

74a6790

2019-06-14 18:50 UTC, machine-human commented
> 코드에 !!를 사용하지 않고 null 핸들링 해주세요.

2019-06-14 18:59 UTC, machine-human commented
-MainActivity.kt/var로 타입 변경 (반영 안 됨)
-MainFragment.kt/세미콜론 제거(반영 안 됨) , class preperty 사용
위 3개의 내용 재 반영 하도록 하겠습니다.

그리고

현재
-MainListAdapter에서 외부list->내부list변경 , 
-ViewHoder에 데이터 set 해주는 부분 ViewHoder 내부에 함수 구현
위 2가지 작업 후 itemCount가 0이고 Api Response에서 200코드와 null message를 받는 이슈가 발생했습니다.

아직 이해도가 부족해서 발생한거 같습니다.
위 내용들은 다음 과제때 추가적으로 작업 하겠습니다. 죄송합니다.

2019-06-15 00:19 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-06-16 05:07 UTC, sport0102 approved these changes

2019-06-16 05:08 UTC, merged