HW-7 Koin 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #580
Opened 2020-04-13 07:22 UTC by mtjin

factory 가 필요한데가 없어보여서 single로만 했는데 맞는지 모르겠네요.

2020-04-14 15:31 UTC, kangraemin requested changes

2020-04-14 15:31 UTC, kangraemin commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/module/LocalDataModule.kt
> +    }
다른 모듈 에서도 보이는 코드인데 androidContext들을 get() 으로 바꿀 수 있을 것 같아요 ( 제가 이해한게 맞다면, startKoin에서 context를 전달받고 get()으로 전달받은 context를 사용 할 수 있는것 같아요 )

2020-04-15 04:56 UTC, mtjin commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/module/LocalDataModule.kt
> +    }
e3a6a8c
수정했습니다.

2020-04-15 10:08 UTC, kangraemin approved these changes
@sooakim approve했습니다 ~

2020-04-15 10:28 UTC, sjjeong requested changes

2020-04-15 10:28 UTC, sjjeong commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/di/KoinApplication.kt
> +            else androidLogger(Level.NONE)
{} 추가해주세요

2020-04-15 12:48 UTC, mtjin commented on 2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/di/KoinApplication.kt
> +            else androidLogger(Level.NONE)
170728d
수정했습니다.

2020-04-16 05:20 UTC, sooakim approved these changes

2020-04-16 11:36 UTC, sjjeong approved these changes
보통 mvp 할때 Presenter를 factory로 많이 써요
지금 우리 예제에서는 mvvm이라서 viewModel을 사용하고 model 쪽은 single로만 구현하면 돼요
LGTM ✊ ✌️ 👋

2020-04-16 12:42 UTC, merged