make folder and change readme
sjjeong/GoogryAndroidArchitecutreStudy pull request #581
Opened 2020-04-13 11:57 UTC by sangjinKIM93

1. 2005/sangjinKIM93 폴더 생성

2. readme 파일 링크 수정 

이렇게 하는 것이 맞나요?

2020-04-14 00:46 UTC, sjjeong requested changes
master로 머지될 거라서 공간 링크는 뒤에 폴더명만 추가해주세요

2020-04-15 10:17 UTC, sangjinKIM93 commented
공간 링크를 master로 수정하였고
label을 review needed로 변경하였습니다.

2020-04-15 10:26 UTC, sjjeong requested changes

2020-04-15 10:26 UTC, sjjeong commented on 2005/README.md
> +[공간](https://github.com/sangjinKIM93/GoogryAndroidArchitectureStudy/tree/master/2005/sangjinKIM93)
링크는 StudyFork여야 합니다.

2020-04-15 10:44 UTC, sangjinKIM93 commented
링크 다시 수정했습니다

2020-04-15 10:59 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-04-15 11:01 UTC, merged