HW-7 Koin 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #588
Opened 2020-04-15 04:36 UTC by tjdwlsl1021

소스리뷰 요청 드립니다.

2020-04-15 08:27 UTC, byiryu commented on 2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/data/remote/network/NetworkService.kt
> +//}
주석처리는 보관하려고 두신거겠죠?

2020-04-15 08:27 UTC, byiryu commented on 2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/di/LocalDataModule.kt
> +    }
androidContext()는 Application에서 startKoin에 생성해서 get()으로 쓸수 있습니다

2020-04-15 08:27 UTC, byiryu commented on 2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/ui/base/AppApplication.kt
> +            )
androidContext()를 넣으셨으니 모듈에서는 get()으로 사용하시면 됩니다.

```
modules(
                repositoryModule,
                localDataModule,
                remoteDataModule,
                viewModelModule
            )
```
순서가 좀 이상한거 같습니다. local, remote, repository  순서로 해야될듯 합니다

2020-04-15 20:53 UTC, tjdwlsl1021 commented on 2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/data/remote/network/NetworkService.kt
> +//}
3ac464e
네;;
공부용으로 별도로 만들어서 주석소스는 제거했습니다.

2020-04-15 20:53 UTC, tjdwlsl1021 commented on 2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/di/LocalDataModule.kt
> +    }
4853785
수정했습니다.

2020-04-15 20:53 UTC, tjdwlsl1021 commented on 2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/ui/base/AppApplication.kt
> +            )
ff8fe86
수정했습니다.

2020-04-15 20:55 UTC, tjdwlsl1021 reviewed
잘 모르고 참고해서 하다보니 놓치는게 많네요;;
소스리뷰 감사합니다.

2020-04-17 04:43 UTC, byiryu approved these changes
이번주가 좀 바빠서 리뷰가 늦었습니다. 죄송합니다

2020-04-17 14:56 UTC, sjjeong requested changes

2020-04-17 14:56 UTC, sjjeong commented on 2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/di/RemoteDataModule.kt
> +    single { get<Retrofit>().create(NaverMovieApi::class.java) }
NaverMovieApi.kt 파일이 누락된거 같네요

2020-04-17 23:49 UTC, tjdwlsl1021 commented on 2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/di/RemoteDataModule.kt
> +    single { get<Retrofit>().create(NaverMovieApi::class.java) }
2e5d23bfb2d4a768827f2ee963ae388e22f1b2b7
수정했습니다.

2020-04-18 03:41 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-04-19 04:02 UTC, merged