HW-7 Koin 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #589
Opened 2020-04-15 08:34 UTC by byiryu

2020-04-15 21:13 UTC, tjdwlsl1021 approved these changes
궁금한점 하나만 질문드렸고, approve했습니다.

2020-04-15 21:13 UTC, tjdwlsl1021 commented on 2003/byiryu/app/src/main/java/com/byiryu/study/di/ApplicationModule.kt
> +val remoteModule = module {
ApplicationModule파일 하나만 만들어서 관리하는방식이랑
local, remote등 파일 각각 만들어서 관리하는방식이랑 큰 차이는 없는건가요?

2020-04-16 11:31 UTC, sjjeong commented on 2003/byiryu/app/src/main/java/com/byiryu/study/di/ApplicationModule.kt
> +val remoteModule = module {
큰 차이는 없습니다. 
결국 관리를 어떻게 할 꺼냐 차이인데
package나누지 않고 할건지 나눌건지 와 비슷한 느낌입니다.

2020-04-16 11:33 UTC, sjjeong requested changes

2020-04-16 11:33 UTC, sjjeong commented on 2003/byiryu/app/src/main/java/com/byiryu/study/di/ActivityModule.kt
> +val activityModule = module {
미사용 하는 것이라면 제거해주세요

2020-04-17 04:41 UTC, byiryu commented on 2003/byiryu/app/src/main/java/com/byiryu/study/di/ActivityModule.kt
> +val activityModule = module {
View에서 쓰는 모듈들을 사용하려고 만들어뒀습니다. 조만간 baseAdapter를 만들어서 할예정입니다.

2020-04-17 04:42 UTC, byiryu commented on 2003/byiryu/app/src/main/java/com/byiryu/study/di/ApplicationModule.kt
> +val remoteModule = module {
저도 같은 생각으로 구조를 설계했습니다.

2020-04-17 14:45 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-04-18 06:07 UTC, merged