HW-1 숙제
sjjeong/GoogryAndroidArchitecutreStudy pull request #59
Opened 2019-06-11 13:39 UTC by Nanamare

너무 바빠서 변수명, 클래스명, 하드코딩 된 것들이 많은데 시간날 때 마다 수정하겠습니다~!

2019-06-11 16:32 UTC, zion830 requested changes
Rx를 잘 몰라서 관련된 부분은 리뷰를 못해드렸네요 ㅜ
고생 많으셨습니다!!

2019-06-11 16:32 UTC, zion830 commented on Nanamare/SampleProject/app/build.gradle
> +    implementation 'com.squareup.okhttp3:logging-interceptor:3.9.1'
(뭔가 특별한 이유가 있는게 아니라면)
더 최근에 나온 상위 버전이 있으니 버전을 높이는건 어떨까요?

2019-06-11 16:32 UTC, zion830 commented on Nanamare/SampleProject/app/src/main/AndroidManifest.xml
> -        <activity android:name=".MainActivity">
안쓰이는 MainActivity가 ui 폴더 상위에 하나 더 있어서 프로젝트에 MainActivity가 두개입니다!

2019-06-11 16:32 UTC, zion830 commented on Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/adapter/BaseAdapter.kt
> +        insert(data, mData!!.size)
`add`와 `insert`를 나누지 않고 하나의 메서드로 사용해도 될 것 같습니다.

2019-06-11 16:32 UTC, zion830 commented on Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/api/ServiceDefine.kt
> +                level = if (BuildConfig.DEBUG)
kotlin style guide에 따르면, 실행문이 단문이더라도 괄호로 감싸주어야 합니다
링크 : https://developer.android.com/kotlin/style-guide/#braces

그리고 이 파일은 Ctrl + Alt + L이 필요해보입니다 ㅎㅎ

2019-06-11 16:32 UTC, zion830 commented on Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/adapter/BaseAdapter.kt
> +    private var mData: MutableList<T>? = ArrayList()
`data: List<T>` 타입으로 초기화를 한다면 nullable을 사용하지 않아도 될 것 같슴니다

2019-06-11 16:32 UTC, zion830 commented on Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/adapter/MarketListViewPager.kt
> +    (fm: FragmentManager) : FragmentPagerAdapter(fm) {
줄바꿈은 괄호보다는 콜론을 기준으로 해야할 것 같습니다 .ㅎㅎ

2019-06-11 16:32 UTC, zion830 commented on Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/ui/CoinFragment.kt
> +        Toast.makeText(context, getString(R.string.scroll_end), Toast.LENGTH_SHORT).show()
이 뒤에 progressbar를 감추는 코드가 추가로 필요해보입니다!

2019-06-11 16:32 UTC, zion830 commented on Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/ui/CoinFragment.kt
> +        ViewCompat.setNestedScrollingEnabled(rv_coin_list, true)
(질문) 혹시 `setNestedScrollingEnabled` 요건 왜 들어간건가요?

2019-06-11 16:51 UTC, Nanamare commented
@zion830  우오 리뷰 감사합니다. 코틀린이 미숙한데, 이번 기회에 익숙해질 수 있을 것 같네요!
시간날 때 마다 고칠게요:)

2019-06-11 16:53 UTC, Nanamare commented on Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/ui/CoinFragment.kt
> +        ViewCompat.setNestedScrollingEnabled(rv_coin_list, true)
나중에 UI 작업할 때 필요해서 미리 코딩해뒀습니다. 현재는 없어도 전혀 무방합니다

2019-06-14 14:21 UTC, Nanamare commented on Nanamare/SampleProject/app/build.gradle
> +    implementation 'com.squareup.okhttp3:logging-interceptor:3.9.1'
버전 업 했습니다!
7550f9188c3fbd9a3dc44bb9e2544568373e79e5

2019-06-14 14:21 UTC, Nanamare commented on Nanamare/SampleProject/app/src/main/AndroidManifest.xml
> -        <activity android:name=".MainActivity">
삭제했습니닷
a2f2660f25dffb94f4e8679d6beb51636d7a99f3

2019-06-14 14:25 UTC, Nanamare commented on Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/adapter/BaseAdapter.kt
> +        insert(data, mData!!.size)
insert 는 포지션을 가지고 넣고 싶은 인덱스 다음에 아이템을 넣는 함수
add는 리스트에 끝을 넣는 함수를 의도로 구현했던 것으로 기억합니다!

2019-06-14 14:26 UTC, Nanamare commented on Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/api/ServiceDefine.kt
> +                level = if (BuildConfig.DEBUG)
정리를 해보았는데 그래도 가독성이 좋지 못한 것 같습니다
96f5a04b7530fbacf2a50d7ce455d553fb71d6da

2019-06-14 14:27 UTC, Nanamare commented on Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/adapter/BaseAdapter.kt
> +    private var mData: MutableList<T>? = ArrayList()
고쳤습니다!
7db11b4bc82712a61919f11886b489972f474646

2019-06-14 14:27 UTC, Nanamare commented on Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/adapter/MarketListViewPager.kt
> +    (fm: FragmentManager) : FragmentPagerAdapter(fm) {
자동 생성을 사용하다보니 저런식으로 컨벤션이 되었네요
고쳤습니다!
5c46cc9c1bf11aaa08a302ab32dbc741a36fd793

2019-06-14 14:28 UTC, Nanamare commented on Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/ui/CoinFragment.kt
> +        Toast.makeText(context, getString(R.string.scroll_end), Toast.LENGTH_SHORT).show()
내려서 확인까지 해주실줄이야 ㅋㅋ
고쳤습니다 저도 잊고있었네요
5527e7888147b60047d212141b153e4cff2a5f0a

2019-06-14 14:45 UTC, zion830 submitted a review, later dismissed
전부 반영된 것 확인하였습니다 'u'
고생 많으셨습니다!

2019-06-14 16:12 UTC, sjjeong requested changes

2019-06-14 16:12 UTC, sjjeong commented on Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/adapter/viewholder/BaseViewHolder.kt
> +abstract class BaseViewHolder<out T>(itemView: View) : RecyclerView.ViewHolder(itemView) {
T의 사용 목적이 어떤건가요?

2019-06-14 16:12 UTC, sjjeong commented on Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/adapter/viewholder/TickerViewHolder.kt
> +         * Todo market 에 맞춰서 나중에 포맷 바꿔야함
Todo는 아직 처리 할 수 없는 부분 인가요?

2019-06-14 16:12 UTC, sjjeong commented on Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/adapter/BaseAdapter.kt
> +abstract class BaseAdapter<T : Any>(data: List<T>) : RecyclerView.Adapter<BaseViewHolder<Any>>() {
data를 toMutableList()로 해서 외부 객체와 내부 객체가 다르게 되서 좋은데
저는 생성하는 시점에서 데이터를 받는게 좋지 않다고 생각합니다.
만약 생성하는 시점에 데이터를 받는게 좋다고 생각하신다면 default 값을 추가하면 좋을 것 같습니다.
현재 CoinFragment에서 사용할 때 생성자로 listOf()를 전달하는데 이 부분이 생략 될 수 있습니다.

2019-06-14 16:12 UTC, sjjeong commented on Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/adapter/BaseAdapter.kt
> +    private var mData: MutableList<T> = data.toMutableList()
kotlin에서는 prefix로 m을 붙이지 않습니다.
그리고 저도 예전에 Adapter에 data, datas, dataList등으로 많이 사용 했었는데 items라는 변수명이 괜찮아서 계속 쓰고 있습니다.
변수명은 편하게 수정해주세요

2019-06-14 16:12 UTC, sjjeong commented on Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/adapter/BaseAdapter.kt
> +    override fun getItemCount(): Int {
return만 있는 함수라면 =를 사용해서 축약할 수 있습니다.

2019-06-14 16:12 UTC, sjjeong commented on Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/api/DisposableManager.kt
> +    private var compositeDisposable: CompositeDisposable? = null
Activity나 Fragment에서 compositeDisposable을 가지고 있는 상태에서 onDestroy()될때 dispose를 하는데 이 부분은 버그를 발생 시킬 위험이 있습니다.
각 화면에서 만든 disposable은 각 화면에서 관리해야 합니다.

2019-06-14 16:12 UTC, sjjeong commented on Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/api/DisposableManager.kt
> +        if (compositeDisposable == null || compositeDisposable!!.isDisposed) {
if(compositeDisposable?.isDisposed == true)로 할 수 있습니다.

2019-06-14 16:12 UTC, sjjeong commented on Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/ui/MainActivity.kt
> +    private lateinit var dialog: ProgressDialog
Deprecated된 클래스 입니다.
다른방법을 사용해주세요.
1. DialogFragment에 ProgressBar를 넣는다.
2. MainActivity에 ProgressBar를 넣는다.

2019-06-14 16:12 UTC, sjjeong commented on Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/ui/MarketListFragment.kt
> +        while (itr.hasNext()) {
iterator를 사용하지 않고 map으로 간단하게 처리 할 수 있습니다.

2019-06-15 11:26 UTC, Nanamare commented on Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/adapter/viewholder/BaseViewHolder.kt
> +abstract class BaseViewHolder<out T>(itemView: View) : RecyclerView.ViewHolder(itemView) {
와일드 카드를 잘못 쓴거 같아서 T타입으로 명시적으로 바꿨고, bind에서 캐스팅 없이 바로 사용할 수 있도록 수정했습니다.
bb0db99f56fff48acf731ac13f627e8d25f39e9b

2019-06-15 11:27 UTC, Nanamare commented on Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/adapter/viewholder/TickerViewHolder.kt
> +         * Todo market 에 맞춰서 나중에 포맷 바꿔야함
넵 저도 처리하고싶은데, BTC, KRW, ETH, USDT 에서 내려주는 포맷이 다 다른데, 이 숫자들이 의미하는 부분을 보려면 API 문서를 봐야할 것 같은데, 아직 보지 못하고 있습니다 흑흑 추후에 해도 될까요 ...?!

2019-06-15 11:35 UTC, Nanamare commented on Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/adapter/BaseAdapter.kt
> +abstract class BaseAdapter<T : Any>(data: List<T>) : RecyclerView.Adapter<BaseViewHolder<Any>>() {
넵 저는 이런식으로 처리해봤는데, 어떤가요~?
6f9e625042612cfa94227f192e8a5a7a4be1d333

2019-06-15 11:37 UTC, Nanamare commented on Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/adapter/BaseAdapter.kt
> +    private var mData: MutableList<T> = data.toMutableList()
저도 items 로 수정하였습니다~!
e8d27b669ecce4d660f8e376c70ebd73fda008b0

2019-06-15 11:39 UTC, Nanamare commented on Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/adapter/BaseAdapter.kt
> +    override fun getItemCount(): Int {
축약 완료하였습니다 :)
2950ceb9eb634c92c8481e2e4ab2a2b94be5718f

2019-06-15 11:55 UTC, Nanamare commented on Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/api/DisposableManager.kt
> +    private var compositeDisposable: CompositeDisposable? = null
삭제할까 하려다, 클래스로 변경하였습니다.
5102552f442acff4e2e2b31f2bfdb2c26a5febd6

2019-06-15 11:55 UTC, Nanamare commented on Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/api/DisposableManager.kt
> +        if (compositeDisposable == null || compositeDisposable!!.isDisposed) {
교체하였습니다!
5102552f442acff4e2e2b31f2bfdb2c26a5febd6

2019-06-15 12:34 UTC, Nanamare commented on Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/ui/MainActivity.kt
> +    private lateinit var dialog: ProgressDialog
교체했습니다~!
1981380537b3838f04feb2ad1f0b4e3e0e51fda0

2019-06-15 12:36 UTC, Nanamare commented on Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/ui/MarketListFragment.kt
> +        while (itr.hasNext()) {
map 으로 대체했을 뿐인데, 코드가 이뻐졌네요 ..!
0d4e58d2c9ad848d719a7adf5a5988996242289f

2019-06-16 05:07 UTC, sjjeong commented on Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/adapter/viewholder/TickerViewHolder.kt
> +         * Todo market 에 맞춰서 나중에 포맷 바꿔야함
네

2019-06-16 05:07 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-06-16 09:09 UTC, zion830 approved these changes

2019-06-16 09:17 UTC, merged