HW-2 apply Model Layer
sjjeong/GoogryAndroidArchitecutreStudy pull request #591
Opened 2020-04-15 10:38 UTC by jesterz91

현재는 Remote 에서만 데이터를 가져오게 되어있습니다.

2020-04-15 15:28 UTC, Kyudong3 requested changes

2020-04-15 15:28 UTC, Kyudong3 commented on 2004/jesterz91/app/src/main/java/io/github/jesterz91/study/domain/entity/Movie.kt
> +)
Entity 를 만드신 이유는 Room 디비를 사용하시면서 remote, local dto 를 하나로 묶어주기 위함인가요?!

2020-04-15 15:29 UTC, Kyudong3 commented
궁금한 것 외에는 다른 리뷰를 찾지 못했습니다..!!

2020-04-16 02:27 UTC, jesterz91 commented on 2004/jesterz91/app/src/main/java/io/github/jesterz91/study/domain/entity/Movie.kt
> +)
Repository에서 데이터를 가져와
적절하게 데이터를 가공하여 사용하기 위한 역할로 생성하였습니다.

2020-04-16 13:02 UTC, sjjeong requested changes

2020-04-16 13:02 UTC, sjjeong commented on 2004/jesterz91/app/src/main/java/io/github/jesterz91/study/data/local/MovieDatabase.kt
> +                return instance
return INSTANCE ?: run {} 으로 간략하게 만들 수 있어요

2020-04-16 13:02 UTC, sjjeong commented on 2004/jesterz91/app/src/main/java/io/github/jesterz91/study/data/local/dao/MovieDao.kt
> +    abstract fun selectMovie(): List<MovieLocal>
rx를 사용한다면 dao에서 rx를 사용하시면 돼요
https://developer.android.com/training/data-storage/room/accessing-data

또한 로컬에서 데이터를 가져올 때는 없는 경우도 있기 때문에 Maybe를 사용하는 것을 권장해요

2020-04-16 13:02 UTC, sjjeong commented on 2004/jesterz91/app/src/main/java/io/github/jesterz91/study/domain/usecase/GetMovieUseCase.kt
> +    override fun buildUseCase(params: String): Single<List<Movie>> {
보통 UseCase를 만들 땐 데이터가 여러번 전달 될 수도 있기 때문에 Observable이나 Flowable로 만듭니다.

2020-04-18 02:24 UTC, jesterz91 commented on 2004/jesterz91/app/src/main/java/io/github/jesterz91/study/data/local/MovieDatabase.kt
> +                return instance
elvis operator를 사용하도록 수정했습니다. 6da3eef

2020-04-18 02:25 UTC, jesterz91 commented on 2004/jesterz91/app/src/main/java/io/github/jesterz91/study/domain/usecase/GetMovieUseCase.kt
> +    override fun buildUseCase(params: String): Single<List<Movie>> {
Flowable로 변경하였습니다. 6da3eef

2020-04-18 02:26 UTC, jesterz91 commented on 2004/jesterz91/app/src/main/java/io/github/jesterz91/study/data/local/dao/MovieDao.kt
> +    abstract fun selectMovie(): List<MovieLocal>
Maybe를 사용하여 데이터를 가져오도록 변경하였습니다. 6da3eef

2020-04-18 02:34 UTC, jesterz91 commented
Local에서도 데이터를 가져오도록 수정했습니다.

2020-04-18 03:19 UTC, Kyudong3 approved these changes
Good!

2020-04-18 03:40 UTC, sjjeong requested changes

2020-04-18 03:40 UTC, sjjeong commented on 2004/jesterz91/app/src/main/java/io/github/jesterz91/study/data/local/MovieDatabase.kt
> +                var instance = INSTANCE
이 변수는 제거 할 수 있습니다.

2020-04-18 03:49 UTC, jesterz91 commented on 2004/jesterz91/app/src/main/java/io/github/jesterz91/study/data/local/MovieDatabase.kt
> +                var instance = INSTANCE
변수 제거했습니다. ab1bbad

2020-04-18 03:55 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-04-18 03:58 UTC, merged