HW-8 Multi-Module
sjjeong/GoogryAndroidArchitecutreStudy pull request #592
Opened 2020-04-19 12:36 UTC by sooakim

2020-04-19 12:39 UTC, sooakim commented
기존에 ViewModel에서 에러에 따라 분기 처리하는 코드가 있었는데 remote module쪽으로 retrofit이 분리되면서 app module에서 HttpException에 접근할 수 없게

```kotlin
 .onErrorResumeNext {
                when (it) {
                    is HttpException -> when (it.code()) {
                        404 -> Completable.error(UserNotFoundException())
                        409 -> Completable.error(InvalidPasswordException())
                        else -> Completable.error(it)
                    }
                    else -> Completable.error(it)
                }
            }
````

2020-04-21 03:49 UTC, sjjeong commented
> remote module쪽으로 retrofit이 분리되면서 app module에서 HttpException에 접근할 수 없게되어, remote쪽에서 exception을 매핑하는 코드를 작성했는데 exception도 model처럼 각 module마다 매핑을 해줘야할까요? @sjjeong
> 
> ```kotlin
>  .onErrorResumeNext {
>                 when (it) {
>                     is HttpException -> when (it.code()) {
>                         404 -> Completable.error(UserNotFoundException())
>                         409 -> Completable.error(InvalidPasswordException())
>                         else -> Completable.error(it)
>                     }
>                     else -> Completable.error(it)
>                 }
>             }
> ```

이런경우는 common 같은 공용 모듈을 만들어서 다른 모듈들이 전부 사용하도록 하면 됩니다.

2020-04-21 04:07 UTC, sjjeong requested changes
app module안에 di 패키지에 미사용 모듈들이 남아 있어요

2020-04-21 04:48 UTC, sooakim commented
> app module안에 di 패키지에 미사용 모듈들이 남아 있어요


19251ff

2020-04-21 04:53 UTC, sooakim commented
> > remote module쪽으로 retrofit이 분리되면서 app module에서 HttpException에 접근할 수 없게되어, remote쪽에서 exception을 매핑하는 코드를 작성했는데 exception도 model처럼 각 module마다 매핑을 해줘야할까요? @sjjeong
> > ```kotlin
> >  .onErrorResumeNext {
> >                 when (it) {
> >                     is HttpException -> when (it.code()) {
> >                         404 -> Completable.error(UserNotFoundException())
> >                         409 -> Completable.error(InvalidPasswordException())
> >                         else -> Completable.error(it)
> >                     }
> >                     else -> Completable.error(it)
> >                 }
> >             }
> > ```
> 
> 이런경우는 common 같은 공용 모듈을 만들어서 다른 모듈들이 전부 사용하도록 하면 됩니다.


6d774b9

2020-04-21 13:38 UTC, sjjeong approved these changes
8주간 고생 많았어요 ㅎㅎ

2020-04-21 16:34 UTC, merged