HW-8 Multi Module 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #593
Opened 2020-04-20 07:18 UTC by mtjin

모듈과 패키지로 분리하고 data 모듈에 app하고 remote, local 모델 변환해주는 mapper 를 구현했습니다.

2020-04-21 11:30 UTC, kangraemin requested changes

2020-04-21 11:30 UTC, kangraemin commented on 2003/mtjin/AndroidArchitectureStudy/.idea/gradle.xml
> +            <option value="$PROJECT_DIR$/remote" />
이건 질문인데 ... 이 부분의 역할은 무엇인가요 ?

2020-04-21 11:30 UTC, kangraemin commented on 2003/mtjin/AndroidArchitectureStudy/app/build.gradle
> +    implementation 'com.squareup.retrofit2:converter-gson:2.6.2'
이부분을 추가하신 이유가 있을까요 ?

2020-04-21 13:32 UTC, mtjin commented on 2003/mtjin/AndroidArchitectureStudy/.idea/gradle.xml
> +            <option value="$PROJECT_DIR$/remote" />
@kangraemin 
흠.. 제가 따로 손댄건 아니고 
gradle 버전에 대한 로컬 경로가 들어있고 사용자별로 다를수있다고 합니다.

2020-04-21 13:37 UTC, mtjin commented on 2003/mtjin/AndroidArchitectureStudy/app/build.gradle
> +    implementation 'com.squareup.retrofit2:converter-gson:2.6.2'
app 에서 필요없는 dependency 였네요 제거했습니다.
6f5ca6e

2020-04-22 01:04 UTC, kangraemin approved these changes
@sooakim approve 하였습니다 !! 고생많으셨어요 ㅎㅎ 감사합니다 ~~

2020-04-22 02:47 UTC, sooakim requested changes

2020-04-22 02:47 UTC, sooakim commented on 2003/mtjin/AndroidArchitectureStudy/data/build.gradle
> +    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
```suggestion
    implementation 'androidx.core:core-ktx:1.2.0'
    testImplementation 'junit:junit:4.12'
```

안드로이드 관련 의존성 제거

2020-04-22 02:47 UTC, sooakim commented on 2003/mtjin/AndroidArchitectureStudy/data/build.gradle
> +    implementation 'org.koin:koin-androidx-viewmodel:2.1.5'
```suggestion
    implementation 'org.koin:koin-core:2.1.5'
```

2020-04-22 02:47 UTC, sooakim commented on 2003/mtjin/AndroidArchitectureStudy/data/build.gradle
> +    annotationProcessor 'androidx.room:room-compiler:2.2.5'
```suggestion
    kept 'androidx.room:room-compiler:2.2.5'
```

kapt사용

2020-04-22 02:47 UTC, sooakim commented on 2003/mtjin/AndroidArchitectureStudy/data/build.gradle
> +    implementation project(':local')
data는 local과 remote를 몰라야해요.

2020-04-22 02:47 UTC, sooakim commented on 2003/mtjin/AndroidArchitectureStudy/data/src/main/java/com/mtjin/data/source/search/MovieRepositoryImpl.kt
> +                    success(mapperMovieListLocalToData(this))
local에서 data의 모델로 매핑해주세요.

2020-04-22 02:47 UTC, sooakim commented on 2003/mtjin/AndroidArchitectureStudy/data/build.gradle
> +    implementation 'com.squareup.retrofit2:converter-gson:2.6.2'
data에서 remote관련 의존성 제거

2020-04-22 02:47 UTC, sooakim commented on 2003/mtjin/AndroidArchitectureStudy/data/build.gradle
> +    annotationProcessor 'androidx.room:room-compiler:2.2.5'
data에서 local관련 의존성 제거

2020-04-22 14:35 UTC, mtjin commented on 2003/mtjin/AndroidArchitectureStudy/data/src/main/java/com/mtjin/data/source/search/MovieRepositoryImpl.kt
> +                    success(mapperMovieListLocalToData(this))
@sooakim 
local 에서 data의 모델로 매핑할려면 local 에서 implementation project(':data') 를 해야할 거 같은데 맞나요?

2020-04-22 14:45 UTC, sooakim commented on 2003/mtjin/AndroidArchitectureStudy/data/src/main/java/com/mtjin/data/source/search/MovieRepositoryImpl.kt
> +                    success(mapperMovieListLocalToData(this))
@mtjin 네

2020-04-22 15:35 UTC, mtjin commented on 2003/mtjin/AndroidArchitectureStudy/data/build.gradle
> +    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
a6272eb

5656591
수정했습니다.

2020-04-22 15:36 UTC, mtjin commented on 2003/mtjin/AndroidArchitectureStudy/data/build.gradle
> +    implementation 'org.koin:koin-androidx-viewmodel:2.1.5'
01aa21a
수정했습니다.

2020-04-22 15:36 UTC, mtjin commented on 2003/mtjin/AndroidArchitectureStudy/data/build.gradle
> +    annotationProcessor 'androidx.room:room-compiler:2.2.5'
1c32b00
수정했습니다.

2020-04-22 15:38 UTC, mtjin commented on 2003/mtjin/AndroidArchitectureStudy/data/build.gradle
> +    implementation project(':local')
8fb5514
f32d33a
e78a4d6
36f4e48

수정했습니다.

2020-04-22 15:38 UTC, mtjin commented on 2003/mtjin/AndroidArchitectureStudy/data/src/main/java/com/mtjin/data/source/search/MovieRepositoryImpl.kt
> +                    success(mapperMovieListLocalToData(this))
a87ae55 
수정했습니다.

2020-04-22 15:39 UTC, mtjin commented on 2003/mtjin/AndroidArchitectureStudy/data/build.gradle
> +    implementation 'com.squareup.retrofit2:converter-gson:2.6.2'
8fb5514
수정했습니다.

2020-04-22 15:40 UTC, mtjin commented on 2003/mtjin/AndroidArchitectureStudy/data/build.gradle
> +    annotationProcessor 'androidx.room:room-compiler:2.2.5'
f32d33a
수정했습니다.

2020-04-24 06:01 UTC, sooakim approved these changes

2020-04-24 13:10 UTC, sjjeong requested changes

2020-04-24 13:10 UTC, sjjeong commented on 2003/mtjin/AndroidArchitectureStudy/data/src/main/java/com/mtjin/data/model/search/MovieResponse.kt
> +data class MovieResponse(
unused class 입니다 제거해주세요

2020-04-24 13:10 UTC, sjjeong commented on 2003/mtjin/AndroidArchitectureStudy/local/src/main/java/com/mtjin/local/mapper/mapper.kt
> +fun mapperMovieListLocalToData(movies: List<Movie>): List<dataMovie> {
파일명은 대문자 카멜 케이스로 해주세요 
소문자로 되어있는부분 전부 수정해주세요

2020-04-25 04:42 UTC, mtjin commented on 2003/mtjin/AndroidArchitectureStudy/data/src/main/java/com/mtjin/data/model/search/MovieResponse.kt
> +data class MovieResponse(
6b6fba9
수정했습니다.

2020-04-25 04:42 UTC, mtjin commented on 2003/mtjin/AndroidArchitectureStudy/local/src/main/java/com/mtjin/local/mapper/mapper.kt
> +fun mapperMovieListLocalToData(movies: List<Movie>): List<dataMovie> {
01759ad
수정했습니다.

2020-04-26 04:47 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋
8주간 고생 많으셨어요~

2020-04-26 09:11 UTC, mtjin commented
감사합니다~

2020-04-26 09:11 UTC, merged