HW-8 Multi Module
sjjeong/GoogryAndroidArchitecutreStudy pull request #594
Opened 2020-04-20 13:28 UTC by byiryu

정리한다고 정리하면서 했는데... 잘 안됐습니다 ㅠㅠ

2020-04-21 13:00 UTC, tjdwlsl1021 approved these changes
시간이 오래 걸릴 것 같아서 우선 Approve했습니다;;
수고하셨습니다.

2020-04-21 14:05 UTC, sjjeong requested changes

2020-04-21 14:05 UTC, sjjeong commented on 2003/byiryu/remote/src/main/java/com/byiryu/remote/RemoteDataSourceImpl.kt
> +            MovieMapper.toData(it)
빌드에러가 발생합니다

2020-04-21 14:05 UTC, sjjeong commented on 2003/byiryu/local/src/main/java/com/byiryu/local/model/mapper/MovieMapper.kt
> +        return items.toList()
Mapper들 사용하는 코드들이 전부 이런 패턴인 것 같은데
movieItems.map { } 을 사용하면 더 좋을 것 같아요
그리고 MovieItem -> Item을 변환하는 함수를 만드는게 좀더 가독성이 좋을 것 같습니다.

2020-04-21 14:05 UTC, sjjeong commented on 2003/byiryu/local/src/main/java/com/byiryu/local/di/LocalModule.kt
> +        LocalDataBase.getInstance(get())
single로 singleton이 유지되기 때문에 getInstance() 내부 코드가 여기에 있으면 됩니다.

2020-04-25 08:16 UTC, byiryu commented on 2003/byiryu/local/src/main/java/com/byiryu/local/model/mapper/MovieMapper.kt
> +        return items.toList()
MovieItem -> Item 으로 변환하는게 이부분인데요 
어떤걸 말씀하시는지 이해가 잘 안갑니다.

2020-04-25 14:59 UTC, byiryu commented on 2003/byiryu/local/src/main/java/com/byiryu/local/di/LocalModule.kt
> +        LocalDataBase.getInstance(get())
수정했습니다

a418900

2020-04-25 14:59 UTC, byiryu commented on 2003/byiryu/local/src/main/java/com/byiryu/local/model/mapper/MovieMapper.kt
> +        return items.toList()
수정헸습니다
822102e

2020-04-25 14:59 UTC, byiryu commented on 2003/byiryu/remote/src/main/java/com/byiryu/remote/RemoteDataSourceImpl.kt
> +            MovieMapper.toData(it)
수정했습니다

ccf22ea

2020-04-26 04:50 UTC, sjjeong commented on 2003/byiryu/local/src/main/java/com/byiryu/local/model/mapper/MovieMapper.kt
> +        return items.toList()
지금 List<MovieItem> -> List<Item>으로 해주는 Mapper가 있는 것처럼 MovieItem -> Item으로 변환하는 Mapper를 말한거였어요

2020-04-26 04:50 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋
8주간 고생 많으셨어요~~

2020-04-26 08:01 UTC, byiryu commented on 2003/byiryu/local/src/main/java/com/byiryu/local/model/mapper/MovieMapper.kt
> +        return items.toList()
아하 이해했습니다 감사합니다

2020-04-26 08:02 UTC, merged