HW-3 Presneter 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #596
Opened 2020-04-20 15:25 UTC by nukeolaf

Contract 인터페이스에 View 와 Presenter 의 기능을 작성하였습니다.
비즈니스 로직을 Presenter로 옮겼습니다.

2020-04-21 14:26 UTC, ghost approved these changes
[![LGTM](https://www.lgtm.app/p/QWpb4HK5_)](https://www.lgtm.app/i/QWpb4HK5_)
🤔data source는 repository에서 접근하는 부분이라, 객체 생성도 repository에서 해야한다고 생각했습니다. 혹시 어떤 이유로 View에서 객체를 생성하셨는지 알 수 있을까요? 감사합니다 :)

2020-04-21 14:59 UTC, sjjeong requested changes

2020-04-21 14:59 UTC, sjjeong commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/ui/MainPresenter.kt
> +    private val movieRepository: MovieRepositoryImpl,
여기는 Class type보다 interface type으로 넣어주도록 해주세요

2020-04-21 14:59 UTC, sjjeong commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/ui/MainPresenter.kt
> +        if (query == null) {
query가 "" 빈값일 때도 처리 해주셔야 해요
query.isNullOrEmpty()를 사용하시면 됩니당

2020-04-22 18:49 UTC, nukeolaf commented
@eunjin-hong context 가 local data source 에서만 필요한데, 굳이 Repository 에 context 를 한 번 전달하고, 다시 Repository 에서 local Data Source 로 context 를 또한 번 전달하는것이 비효율적이라고 생각했습니다! @sjjeong 혹시 제가 한 방법이 MVP 패턴에서 많이 벗어났나요??

2020-04-22 18:52 UTC, nukeolaf commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/ui/MainPresenter.kt
> +    private val movieRepository: MovieRepositoryImpl,
수정했습니다!
fbae3aa

2020-04-22 18:52 UTC, nukeolaf commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/ui/MainPresenter.kt
> +        if (query == null) {
수정했습니다!
7167d73

2020-04-24 12:12 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋
아니요 잘 하셨어요 ㅎㅎ

2020-04-24 12:55 UTC, merged