HW-3 apply mvp pattern
sjjeong/GoogryAndroidArchitecutreStudy pull request #597
Opened 2020-04-20 15:50 UTC by Kyudong3

MVP 패턴을 적용하였습니다.
Room 데이터베이스를 사용하려고 했지만 데이터를 받아오는 것이 잘 되지 않았습니다. 추후에 추가하도록 하겠습니다.

2020-04-23 05:06 UTC, ios-byungjoon-lee requested changes
리뷰 남깁니다.

2020-04-23 05:06 UTC, ios-byungjoon-lee commented on 2004/kyudong3/app/src/main/java/com/example/kyudong3/data/local/MovieDatabase.kt
> +                    }
이 콜백은 불필요해 보입니다.

2020-04-23 05:06 UTC, jesterz91 commented on 2004/kyudong3/app/src/main/java/com/example/kyudong3/ui/movie/presenter/MoviePresenter.kt
> +    }
MoviePresenter가 movieRepository에 의존하고 있는 형태보다는
의존객체를 외부에서 생성하여 전달해주는 것이 좋을것 같아요.

2020-04-23 05:06 UTC, jesterz91 commented on 2004/kyudong3/app/src/main/java/com/example/kyudong3/ui/MainActivity.kt
> +    private lateinit var moviePresenter: MoviePresenter
val로 선언하고 지연 초기화 해주세요.

2020-04-23 15:28 UTC, Kyudong3 commented on 2004/kyudong3/app/src/main/java/com/example/kyudong3/data/local/MovieDatabase.kt
> +                    }
수정했습니다!
e609dfb

2020-04-23 15:28 UTC, Kyudong3 commented on 2004/kyudong3/app/src/main/java/com/example/kyudong3/ui/movie/presenter/MoviePresenter.kt
> +    }
수정하였습니다!
25a00f1

2020-04-23 15:28 UTC, Kyudong3 commented on 2004/kyudong3/app/src/main/java/com/example/kyudong3/ui/MainActivity.kt
> +    private lateinit var moviePresenter: MoviePresenter
수정하였습니다!

2020-04-23 15:30 UTC, Kyudong3 commented
@jesterz91  리뷰 수정하였습니다!

2020-04-23 16:17 UTC, ios-byungjoon-lee approved these changes
Good!
추가로 moviePresenter의 데이터 타입을 
interface로 명시하는게 좋을것 같습니다.

2020-04-24 12:48 UTC, sjjeong requested changes

2020-04-24 12:48 UTC, sjjeong commented on 2004/kyudong3/app/src/main/java/com/example/kyudong3/ui/movie/presenter/MoviePresenter.kt
> +    }
저장하는 로직은 presenter가 아니라 repository에서 처리하면 좋을 것 같아요
MovieRepository#getMovieListRemote함수에서 처리하게 해주세요

2020-04-24 16:10 UTC, Kyudong3 commented on 2004/kyudong3/app/src/main/java/com/example/kyudong3/ui/movie/presenter/MoviePresenter.kt
> +    }
수정하였습니다! 
341a5e1

2020-04-25 06:48 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-04-25 15:15 UTC, merged