HW-8 Use multi module
sjjeong/GoogryAndroidArchitecutreStudy pull request #598
Opened 2020-04-20 15:51 UTC by kangraemin

2020-04-21 02:44 UTC, mtjin requested changes

2020-04-21 02:44 UTC, mtjin commented on 2003/kangraemin/remote/src/main/java/com/example/remote/source/MovieRemoteDataSourceImpl.kt
>  class MovieRemoteDataSourceImpl(
internal 이 빠진 것 같습니다.

2020-04-21 02:44 UTC, mtjin commented on 2003/kangraemin/data/src/main/java/com/example/data/di/NetworkUtilModule.kt
> +        com.example.data.source.NetworkUtil(get())
import 문 생략 가능합니다.

2020-04-21 02:44 UTC, mtjin commented on 2003/kangraemin/data/src/main/java/com/example/data/source/NetworkUtil.kt
>          if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
![image](https://user-images.githubusercontent.com/37071007/79819498-11e15f00-83c5-11ea-9386-88ab385b568d.png)

이건 따로 permission 안해도 상관없는건가요..?

2020-04-21 11:31 UTC, kangraemin commented on 2003/kangraemin/remote/src/main/java/com/example/remote/source/MovieRemoteDataSourceImpl.kt
>  class MovieRemoteDataSourceImpl(
수정하였습니다.
95aaa59
261596d

2020-04-21 11:31 UTC, kangraemin commented on 2003/kangraemin/data/src/main/java/com/example/data/source/NetworkUtil.kt
>          if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
옮기면서 빠져버렸네요 ㅠ 수정하였습니다.
289eb57

2020-04-21 11:31 UTC, kangraemin commented on 2003/kangraemin/data/src/main/java/com/example/data/di/NetworkUtilModule.kt
> +        com.example.data.source.NetworkUtil(get())
수정하였습니다.
da46e10

2020-04-21 13:29 UTC, mtjin approved these changes
@sooakim 
approve 했습니다. 그동안 고생하셨습니다. ~

2020-04-21 14:16 UTC, sjjeong requested changes
data가 remote와 local을 가지는 형태가 아니라
remote와 local이 각각 data를 가지는 형태가 되어야 합니다.
data가 RemoteDataSource와 LocalDataSource를 가지고 remote local에서 각각 impl하는 구조로 해야 합니다.

2020-04-22 02:38 UTC, sooakim requested changes

2020-04-22 02:38 UTC, sooakim commented on 2003/kangraemin/data/build.gradle
> +    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
```suggestion
    implementation 'androidx.core:core-ktx:1.2.0'
    testImplementation 'junit:junit:4.12'
```

data 레이어가 android 관련 의존성을 가질 필요는 없을 것 같아요.

2020-04-22 02:38 UTC, sooakim commented on 2003/kangraemin/data/build.gradle
> +    implementation 'org.koin:koin-androidx-viewmodel:2.1.5'
```suggestion
    implementation 'org.koin:koin-core:2.1.5'
```

2020-04-22 02:38 UTC, sooakim commented on 2003/kangraemin/data/src/main/java/com/example/data/source/AuthRepositoryImpl.kt
> +            .subscribeOn(Schedulers.io())
```kotlin
     .subscribeOn(Schedulers.io())
```
은 local과 remote쪽에서 작성해주세요.

2020-04-22 02:38 UTC, sooakim commented on 2003/kangraemin/local/build.gradle
> +    kapt "androidx.room:room-compiler:$room_version"
```suggestion
    // optional - Kotlin Extensions and Coroutines support for Room
    implementation "androidx.room:room-ktx:$room_version"
    // optional - RxJava support for Room
    implementation "androidx.room:room-rxjava2:$room_version"
    // Test helpers
    testImplementation "androidx.room:room-testing:$room_version"

    kapt "androidx.room:room-compiler:$room_version"
```

2020-04-24 16:51 UTC, kangraemin commented on 2003/kangraemin/local/build.gradle
> +    kapt "androidx.room:room-compiler:$room_version"
수정하였습니다.
91829a0

2020-04-24 16:51 UTC, kangraemin commented on 2003/kangraemin/data/src/main/java/com/example/data/source/AuthRepositoryImpl.kt
> +            .subscribeOn(Schedulers.io())
수정하였습니다.
2e36d23

2020-04-24 16:52 UTC, kangraemin commented on 2003/kangraemin/data/build.gradle
> +    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
수정하였습니다.
ed87009

2020-04-24 16:52 UTC, kangraemin commented on 2003/kangraemin/data/build.gradle
> +    implementation 'org.koin:koin-androidx-viewmodel:2.1.5'
수정하였습니다.
1ac328e

2020-04-24 16:56 UTC, kangraemin commented
> data가 remote와 local을 가지는 형태가 아니라
> remote와 local이 각각 data를 가지는 형태가 되어야 합니다.
> data가 RemoteDataSource와 LocalDataSource를 가지고 remote local에서 각각 impl하는 구조로 해야 합니다.

수정했습니다. 
Room dependency를 app 모듈에서 삭제하여 common module을 추가하고 로컬 모듈에서 에러를 받아 올 수 있도록 하였습니다. 
8dff867

2020-04-27 14:53 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-04-27 15:04 UTC, sooakim approved these changes

2020-04-28 01:03 UTC, merged