HW-3 feat: add Presenter layer(프레젠터 추가)
sjjeong/GoogryAndroidArchitecutreStudy pull request #601
Opened 2020-04-21 09:30 UTC by TaeseongYun

2020-04-21 14:19 UTC, ghost reviewed
수정을 해야하는 부분은 딱히 없어 보입니다.
Rx가 들어가는 부분은 제가 리뷰해드리지 못해서 죄송합니다 ..!

2020-04-21 14:19 UTC, invitejay commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/presenter/MoviePresenter.kt
> +                    movieRecyclerAdapter.notifiedDataChange()
태성님 말대로 보니 그렇네요.. adapter에 list를 넣어주는 부분을 저는 view에서 담당하게 해놨는데 presenter에서 아예 작업을 해주는 방법으로 해주는게 좋을거 같네요. 좋은 공부가 되었습니다. 감사합니다 !

2020-04-22 07:42 UTC, TaeseongYun commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/presenter/MoviePresenter.kt
> +                    movieRecyclerAdapter.notifiedDataChange()
@invitejay  리뷰 끝나셨으면 approve랑 label 추가해주세요.

2020-04-22 07:48 UTC, ghost approved these changes

2020-04-22 14:49 UTC, sjjeong requested changes

2020-04-22 14:49 UTC, sjjeong commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/presenter/MoviePresenter.kt
> +    private val movieRecyclerAdapter: RecyclerViewModel<Item>
이것을 사용하기 때문에 MVP구조가 완성되지 않았습니다.
View -> Presenter를 바라보고 Presenter가 View를 바라보는 형태로 만들어주세요
또한 RecyclerViewModel을 사용하지 않도록 해주세요

2020-04-23 01:56 UTC, TaeseongYun commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/presenter/MoviePresenter.kt
> +    private val movieRecyclerAdapter: RecyclerViewModel<Item>
수정하였습니다. 07a8f49

2020-04-23 15:21 UTC, sjjeong requested changes

2020-04-23 15:21 UTC, sjjeong commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/presenter/MoviePresenter.kt
> +                .doOnSuccess { view.hideProgressBar() }
이러면 fail일 때는 progress가 사라지지 않아요
Single인 경우 doAfterTerminate를 하면 success와 fail 둘다 처리 할 수 있습니다.

2020-04-23 15:21 UTC, sjjeong commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/presenter/MovieContract.kt
> +        fun fetchMovieItem(items: List<Item>)
fetchMovieItem은 MovieItem을 가져온다는 느낌인데 실제 함수 내부 로직은 가져오기 보다는 보여주는 것이기 때문에 함수 이름을 변경하는게 좋을 것 같습니다.

2020-04-23 15:21 UTC, sjjeong commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/presenter/MoviePresenter.kt
> +                .observeOn(AndroidSchedulers.mainThread())
20번째 줄에서 observeOn으로 하고 있기 때문에 중복 선언이 될 것 같네요

2020-04-24 01:29 UTC, TaeseongYun commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/presenter/MovieContract.kt
> +        fun fetchMovieItem(items: List<Item>)
수정하였습니다. 프레젠터에서 실수로 함수명을 수정하지 않아 두번 커밋을 하였습니다
acb1b2a ,  c2020b3

2020-04-24 01:29 UTC, TaeseongYun commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/presenter/MoviePresenter.kt
> +                .observeOn(AndroidSchedulers.mainThread())
수정하였습니다. ec2a9d0

2020-04-24 01:29 UTC, TaeseongYun commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/presenter/MoviePresenter.kt
> +                .doOnSuccess { view.hideProgressBar() }
수정하였습니다. 90d3fb8

2020-04-24 12:12 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-04-25 01:17 UTC, merged