HW-3 MVP pattern
sjjeong/GoogryAndroidArchitecutreStudy pull request #608
Opened 2020-04-22 19:00 UTC by jesterz91

MVP 패턴을 적용하였습니다.

2020-04-23 14:21 UTC, Kyudong3 approved these changes
Good!

2020-04-23 14:28 UTC, Kyudong3 reviewed
궁금한 것 리뷰로 남깁니다!

2020-04-23 14:28 UTC, Kyudong3 commented on 2004/jesterz91/app/src/main/java/io/github/jesterz91/study/presentation/ui/MovieSearchActivity.kt
> +    private val movieUseCase: UseCase<Flowable<List<Movie>>, String> by lazy {
궁금한 것이 있는데, 위에 CustomTabsIntent는 타입을 빼고 lazy 로 초기화를 하고 movieUseCase 에서는 타입을 명시한 것인지 알 수 있을까요?!!!

2020-04-23 16:01 UTC, sjjeong requested changes

2020-04-23 16:01 UTC, sjjeong commented on 2004/jesterz91/app/src/main/java/io/github/jesterz91/study/presentation/ui/MovieSearchActivity.kt
> +    override fun getClickObservable(): Observable<Uri> = movieAdapter.getClickObservable()
View에서 get해서 가져오는게 아니라 다른 것들 처럼 Presenter가 가지고 있게 하면 좋을 것 같습니다.

2020-04-23 16:01 UTC, sjjeong commented on 2004/jesterz91/app/src/main/java/io/github/jesterz91/study/presentation/ui/MovieSearchContract.kt
> +        fun fetchSearchResult(items: List<Movie>)
fetch는 가져오는 느낌이라서 실제 함수 내부 구현부가 SearchResult를 가져오는 것이 구현되어 있을 것 같습니다.
함수 안에 구현부에 맞게 함수명을 변경해주세요

2020-04-25 01:49 UTC, jesterz91 commented on 2004/jesterz91/app/src/main/java/io/github/jesterz91/study/presentation/ui/MovieSearchContract.kt
> +        fun fetchSearchResult(items: List<Movie>)
수정했습니다. 35bfe78

2020-04-25 01:49 UTC, jesterz91 commented on 2004/jesterz91/app/src/main/java/io/github/jesterz91/study/presentation/ui/MovieSearchActivity.kt
> +    override fun getClickObservable(): Observable<Uri> = movieAdapter.getClickObservable()
수정했습니다. 35bfe78

2020-04-25 01:52 UTC, jesterz91 commented on 2004/jesterz91/app/src/main/java/io/github/jesterz91/study/presentation/ui/MovieSearchActivity.kt
> +    private val movieUseCase: UseCase<Flowable<List<Movie>>, String> by lazy {
customTabIntent는 타입을 명시하지 않아도 코드를 파악하는데 어려움이 없지만,
movieUseCaase는 타입을 명시하여 해당 UseCase가 어떤 파라미터와 리턴값을 가지는지
알 수 있어 코드파악에 더 용이하다고 생각했습니다.

2020-04-25 13:51 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-04-25 16:10 UTC, merged