HW-1 NAVER_API
sjjeong/GoogryAndroidArchitecutreStudy pull request #614
Opened 2020-04-26 14:40 UTC by hwaniiidev

- Retrofit 사용하여 naver_api 연동
- Response data recyclerview에 출력, 이미지는 Glide 로
- recyclerview item 클릭 시 웹브라우져로 열기

2020-04-27 02:35 UTC, LeeChungWoo92 commented
안녕하세요~ 
pr을 StudyFork/master로 하셨는데 저는 본인이름 브랜치로 하는걸로 알고있는데 
확인부탁드리겠습니다!

2020-04-27 14:45 UTC, hwaniiidev commented
> 안녕하세요~
> pr을 StudyFork/master로 하셨는데 저는 본인이름 브랜치로 하는걸로 알고있는데
> 확인부탁드리겠습니다!

오오 피드백 감사합니다. 말씀안해주셨으면 놓쳤겠네요. 브런치 upstream의 2005/hwaniiidev 브런치로 수정했씁니다

2020-04-28 13:36 UTC, LeeChungWoo92 requested changes

2020-04-28 13:36 UTC, LeeChungWoo92 commented on 2005/hwaniiidev/Architecture/app/src/main/res/layout/activity_main.xml
> +            app:layout_constraintEnd_toEndOf="parent"
LinearLayout가 부모 라서 app:layout_constraint 옵션은 적용 안되지 않나요?!??

2020-04-28 23:20 UTC, hwaniiidev commented on 2005/hwaniiidev/Architecture/app/src/main/res/layout/activity_main.xml
> +            app:layout_constraintEnd_toEndOf="parent"
426514d

맞네요.  LinearLayout에 넣기 전에 적용한 조건을 뺴주지 않아서 그렇네요. 
수정했습니다~~

2020-04-30 09:50 UTC, LeeChungWoo92 approved these changes

2020-05-03 10:47 UTC, sjjeong requested changes

2020-05-03 10:47 UTC, sjjeong commented on 2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/Model/Item.kt
> +package com.hwaniiidev.architecture.Model
패키지에는 대문자가 들어가면 안됩니다.

2020-05-03 10:47 UTC, sjjeong commented on 2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/AdapterMovieList.kt
> +    inner class MovieHolder(itemView: View) : RecyclerView.ViewHolder(itemView) {
nested class는 함수 선언들 이후에 있어야 합니다.
onBindViewHolder 이후로 이동해주세요

2020-05-03 10:47 UTC, sjjeong commented on 2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/AdapterMovieList.kt
> +        holder.itemView.setOnClickListener {
setOnClickListener는 data를 set하는게 아니기 때문에 onBindViewHolder가 아니라 onCreateViewHolder에서 해주는게 좋습니다.

2020-05-03 10:47 UTC, sjjeong commented on 2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/AdapterMovieList.kt
> +class AdapterMovieList(val context: Context, val movieList: List<Item>?) :
Context나 List는 생성자로 받는 것은 좋지 않습니다.
Context는 내부에서 View에서 가져올 수 있습니다.
List는 Adapter 내부에서 따로 가지고 있게 하고 내부 item만 추가해주는 방식으로 해서 외부와 같은 객체를 공유하지 않도록 해주세요

2020-05-03 10:47 UTC, sjjeong commented on 2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/AdapterMovieList.kt
> +        holder.txtRating.text = movieList!!.get(position).userRating
moviewList.get(position)이 중복으로 사용된다면 따로 val로 선언해서 사용하는게 좋습니다.

2020-05-03 10:47 UTC, sjjeong commented on 2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/APICall.kt
> +class APICall {
APICall보단 ApiCall이 더 좋은 이름입니다.

2020-05-03 10:47 UTC, sjjeong commented on 2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/APICall.kt
> +    companion object {
APIClass가 따로 객체를 만들어서 사용하는게 아니라면 companion object로 선언하지 않고 APICall 자체를 object로 만들면 됩니다.
```kotlin
object ApiCall {}
```

2020-05-03 10:47 UTC, sjjeong commented on 2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/APICall.kt
> +        val serverUrl: String = "https://openapi.naver.com/"
외부에서 사용하는게 아니라면 private을 추가해주세요

2020-05-03 10:47 UTC, sjjeong commented on 2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/APICall.kt
> +        }
fun 보다 val로 하면 좋을 것 같습니다.

2020-05-03 10:47 UTC, sjjeong commented on 2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/RetrofitService.kt
> +    ): retrofit2.Call<ResponseMovieSearchData>
`retrofit2.` 은 제거하면 좋을 것 같습니다.

2020-05-03 10:47 UTC, sjjeong commented on 2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/MainActivity.kt
> +    val displayValue = 30
상수 개념이라면 companion object를 만들어서 관리하는게 좋습니다.
또한 literal이라면 const를 추가하고 내부에서만 사용하는 것이라면 private을 추가 해주세요

2020-05-03 10:47 UTC, sjjeong commented on 2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/MainActivity.kt
> +        recyclerview_search_list.layoutManager = LinearLayoutManager(this)
LayoutManager는 xml에서도 추가할 수 있습니다.

2020-05-03 10:47 UTC, sjjeong commented on 2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/MainActivity.kt
> +    fun listUpdate() {
private 추가해주세요
함수명은 보통 동사가 앞으로 나옵니다. updateList()로 변경해주세요

2020-05-03 10:47 UTC, sjjeong commented on 2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/MainActivity.kt
> +        adapterMovieList.notifyDataSetChanged()
list를 업데이트 하는 과정에서 adapter를 새로 만들 필요는 없을 것 같습니다.
Adapter내부에서 사용하는 list에 item을 갱신하고 notifyDataSetChanged()만 호출하면 됩니다.

2020-05-03 10:47 UTC, sjjeong commented on 2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/MainActivity.kt
> +    var movieList: List<Item>? = null
Activity에서 List를 별도로 가지고 있을 필요가 없을 것 같습니다.
listUpdate에 파라미터로 List를 넘겨주는 형태로 변경해주세요

2020-05-03 10:47 UTC, sjjeong commented on 2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/MainActivity.kt
> +                                if (movieList!!.size == 0) {
isEmpty()를 사용하면 좀 더 Readability한 코드가 됩니다.

2020-05-03 10:47 UTC, sjjeong commented on 2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/MainActivity.kt
> +                                    text_plz_search.visibility = View.GONE
text_plz_search를 GONE하는 코드만 있고 VISIBLE하는 코드가 없습니다.

2020-05-03 10:47 UTC, sjjeong commented on 2005/hwaniiidev/Architecture/app/src/main/res/layout/activity_main.xml
> +            android:layout_width="wrap_content"
weight가 들어갔다면 0dp로 주면 됩니다.

2020-05-03 10:47 UTC, sjjeong commented on 2005/hwaniiidev/Architecture/app/src/main/res/layout/activity_main.xml
> +        app:layout_constraintEnd_toEndOf="@+id/recyclerview_search_list"
parent로 변경하면 좋을 것 같습니다.

2020-05-05 08:56 UTC, hwaniiidev commented on 2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/Model/Item.kt
> +package com.hwaniiidev.architecture.Model
70f706b 

패키지명 수정했습니다

2020-05-05 09:20 UTC, hwaniiidev commented on 2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/AdapterMovieList.kt
> +    inner class MovieHolder(itemView: View) : RecyclerView.ViewHolder(itemView) {
84a389e 수정했습니다. 

이 위치는 성능에는 지장이 없지만 Coding Conventions 의 따라 clean code를 위함이죠??

2020-05-05 09:36 UTC, hwaniiidev commented on 2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/AdapterMovieList.kt
> +        holder.itemView.setOnClickListener {
4b7e9fc
수정했습니다.

2020-05-05 09:38 UTC, hwaniiidev commented on 2005/hwaniiidev/Architecture/app/src/main/res/layout/activity_main.xml
> +        app:layout_constraintEnd_toEndOf="@+id/recyclerview_search_list"
dc2061c
수정했습니다

2020-05-05 09:38 UTC, hwaniiidev commented on 2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/MainActivity.kt
> +                                    text_plz_search.visibility = View.GONE
747c836
수정했습니다.

2020-05-05 09:38 UTC, sjjeong commented on 2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/AdapterMovieList.kt
> +    inner class MovieHolder(itemView: View) : RecyclerView.ViewHolder(itemView) {
@hwaniiidev 
네 맞습니다.
클래스 내부 구조상 nested class는 함수 이후에 선언되어야 합니다

2020-05-05 13:51 UTC, hwaniiidev commented on 2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/AdapterMovieList.kt
> +        holder.txtRating.text = movieList!!.get(position).userRating
ada917c
수정했습니다. val로 선언하여 사용하는게 좋은 이유는 단순히 중복 코드뿐 일까요 ??

2020-05-05 13:56 UTC, hwaniiidev commented on 2005/hwaniiidev/Architecture/app/src/main/res/layout/activity_main.xml
> +            android:layout_width="wrap_content"
bea3f7e
수정했습니다

2020-05-08 15:04 UTC, sjjeong commented
@hwaniiidev 
라벨 변경 해주셔야 합니다.
라벨 변경 없으셔서 과제 안하신줄 알고 리뷰를 안했네요

2020-05-09 05:56 UTC, hwaniiidev commented on 2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/MainActivity.kt
> +                                if (movieList!!.size == 0) {
ba21876
이 부분은 Request의 반환값 중 total값을 이용했습니다.

2020-05-09 05:57 UTC, hwaniiidev commented on 2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/MainActivity.kt
> +    var movieList: List<Item>? = null
ba21876
수정했습니다. 말씀하신대로 현재 코드에선 Activity에서 List를 쓸일이 없었더라고요

2020-05-09 06:42 UTC, hwaniiidev commented on 2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/AdapterMovieList.kt
> +class AdapterMovieList(val context: Context, val movieList: List<Item>?) :
cfa4860
수정했습니다. 
list를 공유하지 않아야 하는 이유는 액티비티에서 list값이 변경될 수 있는 상황을 피하기 위함인 것 같은데, 
context를 공유하지 않아야 하는 이유는 잘 모르겠어요!!  
어떤 이유때문인가요 ??

2020-05-09 09:19 UTC, sjjeong commented
@hwaniiidev 
comment resolve 하지 말아주세요

2020-05-09 09:20 UTC, sjjeong commented
![image](https://user-images.githubusercontent.com/4777586/81469736-abac6700-9221-11ea-9945-682f116eafb8.png)
아직 리뷰 반영되지 않은 것들이 있습니다.
전부다 되면 다시 리뷰 하겠습니다.

2020-05-09 09:21 UTC, hwaniiidev commented
@sjjeong-dino 
load more을 놓쳤네요 언능 하겠습니다

2020-05-09 14:13 UTC, hwaniiidev commented on 2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/APICall.kt
> +class APICall {
37b10be
수정했습니다

2020-05-09 14:14 UTC, hwaniiidev commented on 2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/APICall.kt
> +    companion object {
9e00a31
수정했습니다

2020-05-09 14:28 UTC, hwaniiidev commented on 2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/APICall.kt
> +        val serverUrl: String = "https://openapi.naver.com/"
85c0479
수정했습니다

2020-05-09 14:31 UTC, hwaniiidev commented on 2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/APICall.kt
> +        }
422d5ab
수정했습니다. fun 보다 val 로 하는게 좋을 것 같다고 하신 이유과 무엇인지 궁금합니다.

2020-05-09 14:31 UTC, hwaniiidev commented on 2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/RetrofitService.kt
> +    ): retrofit2.Call<ResponseMovieSearchData>
439b323
수정했습니다

2020-05-09 14:40 UTC, hwaniiidev commented on 2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/MainActivity.kt
> +        recyclerview_search_list.layoutManager = LinearLayoutManager(this)
0bac8ce
수정했습니다. 이건 코드 작성 스타일이라고 보여지는데 성능차이도 있나요??

2020-05-09 14:41 UTC, hwaniiidev commented on 2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/MainActivity.kt
> +    fun listUpdate() {
ca4f562
수정했습니다

2020-05-09 14:45 UTC, hwaniiidev commented on 2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/MainActivity.kt
> +        adapterMovieList.notifyDataSetChanged()
cfa4860
수정했습니다 
해당 코멘트를 보기 전, 다른 코멘트에서 미리 수정을 했었네요

2020-05-09 14:51 UTC, hwaniiidev commented on 2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/MainActivity.kt
> +    val displayValue = 30
4c092f6
수정했습니다

2020-05-09 14:53 UTC, hwaniiidev commented
@sjjeong-dino 
반영 안한 리뷰들 다시 작업했습니다!

2020-05-09 16:56 UTC, sjjeong commented on 2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/AdapterMovieList.kt
> +class AdapterMovieList(val context: Context, val movieList: List<Item>?) :
이미 내부에서 context에 접근할 수 있는 방법이 있어서 불필요한 전달입니다.

2020-05-09 16:56 UTC, sjjeong commented on 2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/APICall.kt
> +        }
fun으로 하면 호출 할때마다 새로 만들지만
val로 하면 한번만 만들기 때문이죠

2020-05-09 16:58 UTC, sjjeong commented on 2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/MainActivity.kt
> +        recyclerview_search_list.layoutManager = LinearLayoutManager(this)
성능차이는 없습니다.
정적인 처리를 xml에서 할 수 있다면 xml에서 최대한 하는게 좋다고 생각합니다.
만약 동적으로 변경해줘야 한다면 Kotlin 코드에서 해야 하는게 맞습니다.

2020-05-09 16:59 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-05-10 00:36 UTC, merged