HW-4 DataBinding 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #615
Opened 2020-04-27 11:11 UTC by TaeseongYun

2020-05-06 13:36 UTC, invitejay commented
새로 추가하신 Rx 부분은 리뷰해드리기 좀 어려운감이 있네요ㅎㅎ 이 부분은 멘토님에게 부탁드리겠습니다 !

2020-05-06 13:44 UTC, ghost approved these changes

2020-05-07 10:01 UTC, sjjeong requested changes
debounce 만든게 조금 이상하긴한데 나중에 만나서 이야기 드릴게요

2020-05-07 10:01 UTC, sjjeong commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ui/viewholder/MovieRecyclerViewViewHolder.kt
> +        recyclerDataBinding.movieItem = item
executependingbindings를 호출해주세요

2020-05-07 10:01 UTC, sjjeong commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/binding/ViewBindingAdapter.kt
> +        View.GONE
{} 추가해주세요

2020-05-07 11:47 UTC, TaeseongYun commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ui/viewholder/MovieRecyclerViewViewHolder.kt
> +        recyclerDataBinding.movieItem = item
수정하였습니다.
0247580

2020-05-07 11:49 UTC, TaeseongYun commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/binding/ViewBindingAdapter.kt
> +        View.GONE
수정하였습니다. 
05f1ec5

2020-05-07 11:50 UTC, TaeseongYun commented
debounce를 rxjava로 처음 구현하려 하다보니 코드가 저렇게 되었는데 후에 다른프로젝트에도 
저렇게 구현하면 큰 이슈가 발생할 경우가 생겨서 그런건가요?

2020-05-08 05:00 UTC, sjjeong commented
> debounce를 rxjava로 처음 구현하려 하다보니 코드가 저렇게 되었는데 후에 다른프로젝트에도
> 저렇게 구현하면 큰 이슈가 발생할 경우가 생겨서 그런건가요?

음 그것보다 구현을 잘못한것이 있어서 그거 이야기 드릴려고 했어요

2020-05-08 05:00 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-05-09 04:56 UTC, merged