HW-1 HW-1 Naver API를 이용한 영화 검색 리스트 구현
sjjeong/GoogryAndroidArchitecutreStudy pull request #616
Opened 2020-04-27 16:15 UTC by developer-sungjae

2020-04-28 05:29 UTC, TaeseongYun reviewed
안녕하세요 코드보다가 궁금한 점 코멘트로 남겼습니다.

2020-04-28 05:29 UTC, TaeseongYun commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/components/RetrofitService.kt
> +    fun getMovies(@Query("query") title: String?): Flowable<MovieData>?
네트워크 호출은 성공 or 실패인데 Nullable 하게 잡아준 이유가 있을까요?

2020-04-28 06:43 UTC, chuuuul commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/models/MovieData.kt
> +        @SerializedName("pubdate")
@SerializedName( ) 안의 내용이 Retrofit에 의해 Response되는 Json과 일치하지 않아서 Gson으로 바뀌지 않습니다.
그로인해 Gson으로 변환되었을때 null값이 들어오게 되었고, 현재 액티비티에서 제작연도가 나오지 않고 있습니다.

2020-04-28 08:34 UTC, developer-sungjae commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/components/RetrofitService.kt
> +    fun getMovies(@Query("query") title: String?): Flowable<MovieData>?
명확한 이유는 없고 간혹 서버에서 null이 오는 경우를 대비하려고 했습니다.
서버에서는 어떤일이 일어날지 몰라서 저렇게 작성했습니다.
수정할까요?

2020-04-28 08:35 UTC, developer-sungjae commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/models/MovieData.kt
> +        @SerializedName("pubdate")
아 감사합니다. 수정하겠습니다.

2020-04-28 08:35 UTC, chuuuul requested changes
커밋할때 첫번째 줄이 커밋 제목이 되는데 첫번째 줄에 어떤 작업 하셨는지 적으시는게 커밋 관리하는데에 좋을 것 같습니다!

2020-04-28 08:35 UTC, chuuuul commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/activities/MainActivity.kt
> +                    listview_movie.adapter = adapter
listview_movie.adapter = adapter 보단

forEach문에서는 SearchData를 업데이트하고 그 아래에
 listview_movie.adapter.notifyDataSetChanged() 를 사용하는게 좋을 것 같습니다.

notifyDataSetChange를 사용하면 adapter에 등록한 ArrayList의 변화에 따라서 알아서 업데이트가 됩니다.

--

forEach를 사용해서 반복을 돌리는것보다 ArrayList의 addAll()을 사용해서 한번에  데이터를 넣는게 좋을 것 같습니다.

2020-04-28 08:35 UTC, chuuuul commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/res/layout/activity_main.xml
> +        app:layout_constraintTop_toBottomOf="@id/btn_search" />
RecylcerView의 아랫면을 parent로 잡고 높이를 0dp로 잡는게 좋을 것 같습니다.

현재 레이아웃으로는 검색 결과가 많은 (ex : 해리) 키워드로 검색 시 리사이클러뷰가 잘리는 보이는 현상이 있습니다.

2020-04-28 08:35 UTC, chuuuul commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/components/RetrofitService.kt
> +            val builder = OkHttpClient.Builder()
retrofit이랑 okhttp를 같이 쓴 이유가 있나요?

2020-04-28 08:35 UTC, chuuuul commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/activities/MainActivity.kt
> +        adapter?.notifyItemRangeRemoved(0, searchData.count() - 1)
notifyDataSetChanged() 를 사용하는게 좋을 것 같습니다.

2020-04-28 08:35 UTC, chuuuul commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/activities/MainActivity.kt
> +        adapter = SearchAdapter(searchData)
여기서 listview_moview.adapter = adapter로 어뎁터 등록을 한번만 하시면 
이후 데이터가 바뀔 때마다 adpater.notifyDataSetChanged() 만 하셔도 변화를 감지하게 됩니다.

2020-04-28 14:15 UTC, developer-sungjae commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/activities/MainActivity.kt
> +                    listview_movie.adapter = adapter
수정하였습니다.

2020-04-28 14:17 UTC, developer-sungjae commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/activities/MainActivity.kt
> +        adapter?.notifyItemRangeRemoved(0, searchData.count() - 1)
제가 구현하려고 한 것은 새로 검색하면 ArrayList를 clear하고 다시 검색쿼리에 맞추어서 다시 0번부터 뿌려주는 것을 구현하였습니다. 그래서 arraylist는 clear하고 adapter에 셋팅된 데이터들은 지우는 작업을 하였습니다. 
혹시 이렇게 구현하더라도 notifyDataSetChanged를 이용해야 되는 이유가 있을까요?

2020-04-28 14:17 UTC, developer-sungjae commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/activities/MainActivity.kt
> +        adapter = SearchAdapter(searchData)
감사합니다. 수정하였습니다.

2020-04-28 14:19 UTC, SageHabitus commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/components/RetrofitService.kt
> +            val builder = OkHttpClient.Builder()
아 혹시 반복해서 생성되는것을 지적하신 건지요?

2020-04-28 14:21 UTC, developer-sungjae commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/res/layout/activity_main.xml
> +        app:layout_constraintTop_toBottomOf="@id/btn_search" />
감사합니다. 수정하였습니다.
추가적으로 HTML 태그 분리하는 코드도 작성해보겠습니다.

2020-04-29 05:21 UTC, chuuuul requested changes

2020-04-29 05:21 UTC, chuuuul commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/activities/MainActivity.kt
> +    private lateinit var searchData: ArrayList<MovieData.Items>
ArrayList를 lateinit var로 지연 초기화 하신 이유가 있으신가요? 바로 생성해도 될 것 같아서 여쭤봅니다!

바로 생성하게 되면 val로 선언할 수 있을 것 같습니다.

2020-04-29 05:21 UTC, chuuuul commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/models/MovieData.kt
> +        @SerializedName("pubdate")
아직 수정 안되셨습니다!

pubDate 입니다!

그리고 @SerializedName 사용 안하신다면 지우는건 어떻게 생각하시나요?

2020-04-29 05:21 UTC, chuuuul commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/activities/MainActivity.kt
> +        adapter?.notifyItemRangeRemoved(0, searchData.count() - 1)
이부분은 안바꾸셔도 될 것 같습니다!

2020-04-30 07:21 UTC, developer-sungjae commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/activities/MainActivity.kt
> +    private lateinit var searchData: ArrayList<MovieData.Items>
음.. 이유는 딱히 없고 non-null하게 하기 위한 버릇입니다

2020-04-30 09:17 UTC, developer-sungjae commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/activities/MainActivity.kt
> +    private lateinit var searchData: ArrayList<MovieData.Items>
수정하였습니다.
b8a6f1d

2020-04-30 09:18 UTC, developer-sungjae commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/activities/MainActivity.kt
> +        adapter?.notifyItemRangeRemoved(0, searchData.count() - 1)
수정하였습니다. 
aae728e

2020-04-30 09:19 UTC, developer-sungjae commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/models/MovieData.kt
> +        @SerializedName("pubdate")
수정하였습니다. 
b8a6f1d

2020-04-30 10:05 UTC, chuuuul commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/components/RetrofitService.kt
> +            val builder = OkHttpClient.Builder()
okhttp로 로그 보려고 하셨던거군요 감사합니다!

2020-04-30 10:15 UTC, chuuuul approved these changes
LGTM  !

2020-05-03 11:05 UTC, sjjeong requested changes

2020-05-03 11:05 UTC, sjjeong commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/adapters/SearchAdapter.kt
> +    }
SearchingResultHolder만 사용한다면 generic을 변경해서 사용해주세요
```kotlin
class SearchAdapter(private val searchData: ArrayList<MovieData.Items>) : RecyclerView.Adapter<RecyclerView.ViewHolder>()
```
->
```kotlin
class SearchAdapter(private val searchData: ArrayList<MovieData.Items>) : RecyclerView.Adapter<SearchingResultHolder>()
```

2020-05-03 11:05 UTC, sjjeong commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/activities/MainActivity.kt
> +                removeAllItems()
{} 추가 해주세요

2020-05-03 11:05 UTC, sjjeong commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/adapters/SearchAdapter.kt
> +class SearchAdapter(private val searchData: ArrayList<MovieData.Items>) : RecyclerView.Adapter<RecyclerView.ViewHolder>() {
List를 생성자로 받지 마시고 내부에서 별도로 가지고 있어서 Adapter외부와 객체를 공유하지 않도록 해주세요

2020-05-03 11:05 UTC, sjjeong commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/activities/MainActivity.kt
> +        listview_movie.layoutManager = LinearLayoutManager(this)
LayoutManager는 xml에서 추가해줄수 있습니다.

2020-05-03 11:05 UTC, sjjeong commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/activities/MainActivity.kt
> +            )
```kotlin
}, { error ->
    Log.d("error", error.toString())
})
```
이렇게 변경해주세요

2020-05-03 11:06 UTC, sjjeong requested changes

2020-05-03 11:06 UTC, sjjeong commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/components/Constants.kt
> +    const val NAVER_SEARCH_BASE_URL = "https://openapi.naver.com/v1/search/"
base url은 `https://openapi.naver.com/` 여기까지만 써주면 됩니다.

2020-05-04 03:21 UTC, developer-sungjae commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/activities/MainActivity.kt
> +                removeAllItems()
cc99bf6
수정하였습니다

2020-05-04 03:22 UTC, developer-sungjae commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/activities/MainActivity.kt
> +        listview_movie.layoutManager = LinearLayoutManager(this)
92f2684
수정하였습니다.

2020-05-04 03:22 UTC, developer-sungjae commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/components/Constants.kt
> +    const val NAVER_SEARCH_BASE_URL = "https://openapi.naver.com/v1/search/"
5e71c8f
수정하였습니다.

2020-05-04 03:23 UTC, developer-sungjae commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/adapters/SearchAdapter.kt
> +    }
ca00631
수정하였습니다.

2020-05-04 03:23 UTC, developer-sungjae commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/adapters/SearchAdapter.kt
> +class SearchAdapter(private val searchData: ArrayList<MovieData.Items>) : RecyclerView.Adapter<RecyclerView.ViewHolder>() {
a0e5c4b 0236369
수정하였습니다.

2020-05-04 03:24 UTC, developer-sungjae commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/activities/MainActivity.kt
> +            )
cc99bf6
수정하였습니다.

2020-05-04 03:34 UTC, developer-sungjae commented
제가 모르고  이 작업을 developer-sungjae branch-HW-1의 branch에서 안하고  developer-sungjae(기본) branch에서 한 상태인데 이럴땐 어떻게 해야할까요? rebase해서 다시 풀리퀘를 올려야 하나요? 아니면 머지 풀리퀘스트할때 방법이 있는건가요?

2020-05-05 07:00 UTC, sjjeong commented
> 제가 모르고 이 작업을 developer-sungjae branch-HW-1의 branch에서 안하고 developer-sungjae(기본) branch에서 한 상태인데 이럴땐 어떻게 해야할까요? rebase해서 다시 풀리퀘를 올려야 하나요? 아니면 머지 풀리퀘스트할때 방법이 있는건가요?

이번과제는 이대로 진행하시고 다음 과제부터 해주세요

2020-05-05 07:03 UTC, sjjeong requested changes

2020-05-05 07:03 UTC, sjjeong commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/adapters/SearchAdapter.kt
> +    }
이렇게하면 한개의 List객체를 Activity와 Adapter가 공유하게 됩니다.
객체를 공유하지않고 데이터만 전달하도록 해주세요

2020-05-06 13:55 UTC, developer-sungjae commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/adapters/SearchAdapter.kt
> +    }
ef9a7f8
수정하였습니다.
통신 후 데이터를 activity의 arraylist에 넣고 그것을 바로 연달아 adapter로 넣는것이 아닌 엑티비티 arraylist에 데이터 추가하는 것과 adapter에 데이터 추가하는 부분을 분리하였습니다.
이것이 맞는지는 잘모르겠습니다.
이틀동안 고민해봤는데 딱히 생각이 나지 않습니다..ㅠ

2020-05-07 10:03 UTC, sjjeong requested changes

2020-05-07 10:03 UTC, sjjeong commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/adapters/SearchAdapter.kt
> +        this.searchList = searchData
제가 공유해드린 블로그 내용 공부하시고 수정해보세요

2020-05-07 10:04 UTC, sjjeong commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/adapters/SearchAdapter.kt
> +        this.searchList = searchData
@developer-sungjae 
https://studyfork.slack.com/archives/CRQA6J1FD/p1588759608048200

2020-05-07 12:29 UTC, developer-sungjae commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/adapters/SearchAdapter.kt
> +        this.searchList = searchData
이 글은 지금 세번째 읽었습니다.
mutablelist는 추가 삭제가 가능한 List를 상속한 클래스이고
arraylist는 mutablelist의 자식격인 객체인데
혹시 이 자료형을 나누어서 두개의 다른 객체를 깨닫는걸 원하신건지 궁금하네요

2020-05-07 12:56 UTC, developer-sungjae commented
예전부터 읽어서 세번째 읽는건데 mutable 저게 찜찜하다 했었는데 이거였군요.. (답이 아니라면 민망) 이게 맞다면 대충 읽었네요.
다른 분이 쓴 코드 참고해서 풀어보았습니다.

2020-05-08 05:03 UTC, sjjeong requested changes

2020-05-08 05:03 UTC, sjjeong commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/adapters/SearchAdapter.kt
> +    private var searchList: MutableList<MovieData.Items> = mutableListOf()
val로 변경해주세요

2020-05-08 05:03 UTC, sjjeong commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/adapters/SearchAdapter.kt
> +        this.searchList = searchData
제가 드린 링크에는 이렇게 되어있지 않습니다.
다시보고 변경해보세요

2020-05-08 12:18 UTC, developer-sungjae commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/adapters/SearchAdapter.kt
> +    private var searchList: MutableList<MovieData.Items> = mutableListOf()
6014c5e
수정하였습니다. 역시 날카로우시군요..

2020-05-08 12:18 UTC, developer-sungjae commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/adapters/SearchAdapter.kt
> +        this.searchList = searchData
6014c5e
빼먹었었네요 죄송합니다.

2020-05-08 15:00 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-05-08 16:19 UTC, merged