HW-1 NAVER API로 영화 검색 앱 만들기
sjjeong/GoogryAndroidArchitecutreStudy pull request #618
Opened 2020-04-28 12:25 UTC by sangjinKIM93

영화이름을 입력하고 검색버튼을 누르면 하단에 리스트로 영화 목록 출력
목록에 있는 영화 아이템을 선택하면 웹브라우져로 이동
앞으로 스터디 할 내용들(MVP, MVVM, DataBinding 등등 사용하지 않고 과제 하기)

*사용한 라이브러리 - Retrofit2, Glide, Gson

2020-04-30 03:19 UTC, RyuC0605 commented
안녕하세요. 류승윤 입니다. 
상진님 반갑습니다. 
석준님께서 말씀 하신대로 커밋을 엄청 쪼개서 하셨네요. 너무 과할정도로;;;
일단 코드 리뷰에 앞써서 코드를 빌드해서 한번 돌려 봤습니다. 

앱이 요구사항과 맞지 않는 부분이 보이더군요.
가장 크리티컬한 부분은 영화를 검색 후 목록을 클릭하면 앱이 죽더군요. 

일딴 원인은 찾았고, 제가 알려드리면 실력 향상에 도움이 되지 않을 것 같아 
남기지 않으려 했으나, 첫 시간이니 간단히 말씀드리겠습니다. 
다음부턴 힌트만 드리겠습니다.

01. 앱 죽는 현상 : 인텐트에 값을 넘길때 넘기는 쪽은 LINK 받는쪽은 Link 로 해두셨더군요. 
대소문자를 구분하기 때문에 이런 경우 상수로 설정하는게 안전합니다.

02. 요구사항 준수 : 요구사항은 webView 서브화면 제작이 아닌, 외부 브라우져 호출입니다.

세부사항은 각 커밋에 해당하는 부분에 코멘트를 남기겠습니다. 

연휴 잘 보내세요.

2020-04-30 03:59 UTC, RyuC0605 requested changes
01. 앱 죽는 현상 : 인텐트에 값을 넘길때 넘기는 쪽은 LINK 받는쪽은 Link 로 해두셨더군요. 
대소문자를 구분하기 때문에 이런 경우 상수로 설정하는게 안전합니다.

02. 요구사항 준수 : 요구사항은 webView 서브화면 제작이 아닌, 외부 브라우져 호출입니다.

세부사항은 각 커밋에 해당하는 부분에 코멘트를 남기겠습니다. 

연휴 잘 보내세요.

2020-04-30 03:59 UTC, RyuC0605 commented on 2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/adapter/MovieListAdapter.kt
> +        return strEdited
<b> 태그를 수동으로 지워주는 것도 방법이지만, 컬러나 기타 각종 모든 태그를 이렇게 처리하려면 일이 커지죠.
이럴땐 Html.fromHtml 을 추천드립니다. 검색창에 검색해 보세요.

2020-04-30 03:59 UTC, RyuC0605 commented on 2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/MovieListActivity.kt
> +        guideMessageToInput.text = "검색 결과가 없습니다."
"검색 결과가 없습니다." 를 string.xml 로 리소스로 관리하는 것이  추후 다국어 라든지 여러모로 좋습니다.

2020-04-30 03:59 UTC, RyuC0605 commented on 2005/sangjinKIM93/newproject/app/src/main/res/layout/activity_movie_list.xml
> +        android:text="영화를 검색해주세요."
역시 하드코딩은 좋지 않습니다. 위에 언급한 string.xml 로 빼는걸 추천드립니다.

2020-04-30 11:08 UTC, sangjinKIM93 commented on 2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/adapter/MovieListAdapter.kt
> +        return strEdited
Html.fromHtml 라는 것을 새롭게 알게되었네요

반영했습니다. 감사합니다:)

2020-04-30 11:09 UTC, sangjinKIM93 commented on 2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/MovieListActivity.kt
> +        guideMessageToInput.text = "검색 결과가 없습니다."
kotlin 코드상의 String을 처리하지 않았네요. 반영했습니다!

2020-04-30 11:10 UTC, sangjinKIM93 commented on 2005/sangjinKIM93/newproject/app/src/main/res/layout/activity_movie_list.xml
> +        android:text="영화를 검색해주세요."
추후 수정 commit이 있는데 이전 commit이 먼저 남아있군요. 수정했습니다!

2020-04-30 11:20 UTC, sangjinKIM93 commented
크리티컬 한 리뷰에 대하여

1. 다시 한번 상수의 중요성을 느낍니다. 이번 기회에 습관을 들여야겠네요.
2. 요구사항을 잘못 이해한 부분 수정했습니다.(webView -> ACTION_VIEW)

commit 단위는 세부적으로 쪼개려다 보니까 오히려 읽는 사람이 읽기 부담스러운 커밋이 되었네요. 추후 커밋에서 좀 더 신경써보겠습니다.

값진 피드백 정말 감사드리고 승윤님도 즐거운 연휴 보내세요 :)

2020-04-30 13:21 UTC, RyuC0605 submitted a review, later dismissed

2020-04-30 13:43 UTC, RyuC0605 commented
approval 했었는데 상단 새로고침(?) 비슷하게 생긴 아이콘 건드렸다가 뭔가 꼬였네요;;;

2020-04-30 13:44 UTC, RyuC0605 commented
approval  에서  was requested for review 로 바꼈는데 다시 approval  시키는 방법을 못찾고 있네요.

2020-04-30 13:52 UTC, RyuC0605 submitted a review, later dismissed

2020-04-30 13:56 UTC, RyuC0605 commented
상단의 Reviewers 에 제 아이디 옆 새로고침(?) 비슷한 아이콘 건드렸다가 승인이 풀려버렸었네요.
지금은 다시 approval 했습니다. 휴... 식겁하게 하네요 깃허브...

2020-05-01 02:55 UTC, sangjinKIM93 commented
깃헙.... 까다로운 친구 같습니다 ㅎㅎ

승윤님 코드랑 다른분들 리뷰 보면서 부족한 부분 추가 수정하였습니다.

2020-05-01 05:30 UTC, sangjinKIM93 commented
깃헙.... 까다로운 친구 같습니다 ㅎㅎ

승윤님 코드랑 다른분들 리뷰 보면서 부족한 부분 추가 수정하였습니다.

2020-05-01 10:26 UTC, RyuC0605 approved these changes

2020-05-03 16:25 UTC, sjjeong commented
![image](https://user-images.githubusercontent.com/4777586/80919649-1f73ed00-8da6-11ea-895d-6504f6f045d0.png)
master로 보내면 안되고 2005/sangjinKIM93으로 보내야 합니다.
일단 제가 수정했는데 앞으로는 pr만드실 때 주의해주세요

2020-05-03 16:45 UTC, sjjeong requested changes

2020-05-03 16:45 UTC, sjjeong commented on 2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/adapter/MovieListAdapter.kt
> +class MovieListAdapter (private val movieList: ArrayList<Movie>, private val context: Context) : RecyclerView.Adapter<MovieListViewHolder>(){
생성자로 Context를 받는 부분 제거해주시고
List는 Adapter외부와 독립적으로 내부에 별도 객체로 가지고 있게 해주세요

2020-05-03 16:45 UTC, sjjeong commented on 2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/adapter/MovieListAdapter.kt
> +            var position: Long = item.tag as Long
tag를 사용하는 것은 좋은 방법이 아닙니다.
position은 ViewHolder에 있는 adapterPosition으로 가져오면 됩니다.

2020-05-03 16:45 UTC, sjjeong commented on 2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/adapter/MovieListAdapter.kt
> +            .load(movieList.get(position).image)
movieList.get(position)가 중복으로 사용되는데 val로 빼서 사용해주세요

2020-05-03 16:45 UTC, sjjeong commented on 2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/adapter/MovieListAdapter.kt
> +        }
아래와 같이 변경할 수 있습니다.
```kotlin
return if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
    Html.fromHtml(this, Html.FROM_HTML_MODE_LEGACY).toString()
} else {
    Html.fromHtml(this).toString()
}
```

2020-05-03 16:45 UTC, sjjeong commented on 2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/adapter/Movie.kt
> +    var userRating: String = ""
val로 변경해주시고 default를 지정하는 것은 제거해주세요

2020-05-03 16:45 UTC, sjjeong commented on 2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/MovieListActivity.kt
> +    fun showKeyPad(){
show/hide keypad는 private으로 변경해주세요

2020-05-03 16:45 UTC, sjjeong commented on 2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/MovieListActivity.kt
> +        else{
if의 }와 같은 라인에 있게 해주세요

2020-05-03 16:45 UTC, sjjeong commented on 2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/MovieListActivity.kt
> +        }
생성자로 넘기면 nullable 처리 없이 nonnull로 사용할 수 있습니다.

2020-05-04 06:12 UTC, sangjinKIM93 commented on 2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/adapter/MovieListAdapter.kt
> +class MovieListAdapter (private val movieList: ArrayList<Movie>, private val context: Context) : RecyclerView.Adapter<MovieListViewHolder>(){
수정했습니다.

질문이 있습니다!
1. private val movieList: ArrayList<Movie>를 위처럼 매개변수로 받아 바로 생성하는 것은 내부에 객체를 별도로 만드는 것과 어떻게 다른가요?
2. 내부에 별도 객체로 만들라고 하셨는데, 어떤 문제점 때문인가요?

2020-05-04 06:13 UTC, sangjinKIM93 commented on 2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/adapter/MovieListAdapter.kt
> +            var position: Long = item.tag as Long
수정했습니다.

찾아보니 불필요한 코드였네요. 감사합니다.

2020-05-04 06:14 UTC, sangjinKIM93 commented on 2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/adapter/MovieListAdapter.kt
> +            .load(movieList.get(position).image)
수정했습니다.

2020-05-04 06:14 UTC, sangjinKIM93 commented on 2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/adapter/MovieListAdapter.kt
> +        }
수정했습니다.

새롭게 알게 된 부분이네요. 감사합니다:)

2020-05-04 06:15 UTC, sangjinKIM93 commented on 2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/adapter/Movie.kt
> +    var userRating: String = ""
수정했습니다!

2020-05-04 06:15 UTC, sangjinKIM93 commented on 2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/MovieListActivity.kt
> +    fun showKeyPad(){
수정했습니다!

2020-05-04 06:15 UTC, sangjinKIM93 commented on 2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/MovieListActivity.kt
> +        else{
수정했습니다!

2020-05-04 06:16 UTC, sangjinKIM93 commented on 2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/MovieListActivity.kt
> +        }
말씀하신 의도를 잘 이해하지 못 했습니다. 
movieList.get(position).link 를 let을 활용해서 보내라는 말씀이신가요?

2020-05-05 07:18 UTC, sjjeong commented on 2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/adapter/MovieListAdapter.kt
> +class MovieListAdapter (private val movieList: ArrayList<Movie>, private val context: Context) : RecyclerView.Adapter<MovieListViewHolder>(){
지금 변경하신 내용도 객체는 같게 됩니다.
Activity가 가지고 있는 list의 hash와 Adapter가 가지고 있는 list의 hash를 출력해보세요

객체가 같으면 Activity에서 내용을 수정하면 Adapter에 있는 내용도 같이 변경되기 때문에 버그가 발생할 수 있습니다.
그래서 별도 객체를 가지도록 하는게 좋습니다.

2020-05-05 07:21 UTC, sjjeong commented on 2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/MovieListActivity.kt
> +        }
현재 MoviewListAdapterdk안에 onItemClickListener을 말하는 거였습니다.

2020-05-05 09:10 UTC, sangjinKIM93 commented on 2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/adapter/MovieListAdapter.kt
> +class MovieListAdapter (private val movieList: ArrayList<Movie>, private val context: Context) : RecyclerView.Adapter<MovieListViewHolder>(){
0c47078
이해되었습니다. 같은 메모리 주소를 참조하고 있으면 같은 영향을 받으니 문제가 생길 수 있겠군요. 
adapter에 새로운 arrayList 객체를 생성하고 addList()로 최신화 해주는 것으로 수정하였습니다.
좋은 지적 감사합니다:)

2020-05-05 09:13 UTC, sangjinKIM93 commented on 2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/MovieListActivity.kt
> +        }
a6db658
수정은 했는데 코드 진행방식이 적절한지 잘 모르겠네요 확인부탁드립니다!

onItemClickListener를 생성자로 넘길 생각은 못 해봤는데 새롭게 알고 갑니다.
감사합니다:)

2020-05-05 09:25 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-05-05 11:12 UTC, merged