HW-4 MVVM- LiveData
sjjeong/GoogryAndroidArchitecutreStudy pull request #62
Opened 2019-06-13 22:12 UTC by namjackson

2019-06-14 02:55 UTC, ddaeyeonkim requested changes

2019-06-14 02:55 UTC, improve777 commented on namjackson/ArchStudy/app/src/main/java/com/namjackson/archstudy/util/DatabindingUtil.kt
> +fun setCoinListRecyclerView(view: RecyclerView, list: List<Ticker>?) {
확장함수 형태로 메소드를 생성하는것도 좋을것 같습니다

2019-06-14 02:55 UTC, improve777 commented on namjackson/ArchStudy/app/src/main/java/com/namjackson/archstudy/view/coinlist/CoinListViewModel.kt
> +        _isLoading.postValue(true)
`postValue()` 메소드를 사용하신 이유가 궁금합니다!

2019-06-14 02:55 UTC, improve777 commented on namjackson/ArchStudy/app/src/main/res/layout/fragment_coin_list.xml
> +            android:visibility="@{viewmodel.isLoading ? View.VISIBLE : View.GONE}" />
view visibility 를 별도의 바인딩어댑터로 받는게 더 편리해질 것 같습니다

2019-06-14 07:18 UTC, namjackson commented on namjackson/ArchStudy/app/src/main/java/com/namjackson/archstudy/view/coinlist/CoinListViewModel.kt
> +        _isLoading.postValue(true)
Fragment에서 Timer를 사용해 해당 메소드를 호출할때,
호출하는 쓰레드가 메인쓰레드가 아니라 setValue 를 사용할수없었습니다! 

메인쓰레드 외의 백그라운드 작업시에는 postValue를 사용해야된다고 하네요! 

> Note: You must call the setValue(T) method to update the LiveData object from the main thread. If the code is executed in a worker thread, you can use the postValue(T) method instead to update the LiveData object.

2019-06-14 17:25 UTC, namjackson commented on namjackson/ArchStudy/app/src/main/java/com/namjackson/archstudy/util/DatabindingUtil.kt
> +fun setCoinListRecyclerView(view: RecyclerView, list: List<Ticker>?) {
확장함수 사용하니 좀더 짧아지네요!
702e712

2019-06-14 17:26 UTC, namjackson commented on namjackson/ArchStudy/app/src/main/res/layout/fragment_coin_list.xml
> +            android:visibility="@{viewmodel.isLoading ? View.VISIBLE : View.GONE}" />
c3956f1
하나 만들어놓으면, 추후에 번거로운 작업이 필요없겟네요!

2019-06-15 11:17 UTC, ddaeyeonkim submitted a review, later dismissed
LGTM 👍👍👍

2019-06-16 07:12 UTC, sjjeong requested changes
MediatorLiveData하는건 필수사항이 아니니
하다가 어려우면 안하셔도 괜찮아요

2019-06-16 07:12 UTC, sjjeong commented on namjackson/ArchStudy/app/src/main/java/com/namjackson/archstudy/util/DatabindingUtil.kt
> +fun setVisibility(view: View, boolean: Boolean) {
setCoinItem처럼 extension으로 해주면 좋을 것 같아요

2019-06-16 07:12 UTC, sjjeong commented on namjackson/ArchStudy/app/src/main/java/com/namjackson/archstudy/view/coinlist/CoinListViewModel.kt
> +        _filterCoinList.value = coinList.filter { it.name.contains(searchStr.value?.toUpperCase().toString()) }
filterCoinList 하는 부분을 MediatorLiveData로 한번 해보시겠어요??

2019-06-16 07:47 UTC, sjjeong submitted a review, later dismissed
LGTM ✊ ✌️ 👋

2019-06-18 05:53 UTC, namjackson commented on namjackson/ArchStudy/app/src/main/java/com/namjackson/archstudy/util/DatabindingUtil.kt
> +fun setVisibility(view: View, boolean: Boolean) {
extension적용햇습니다! 
0769c82

2019-06-18 05:54 UTC, namjackson commented on namjackson/ArchStudy/app/src/main/java/com/namjackson/archstudy/view/coinlist/CoinListViewModel.kt
> +        _filterCoinList.value = coinList.filter { it.name.contains(searchStr.value?.toUpperCase().toString()) }
MediatorLiveData 적용해봤습니다! 
7f13100

2019-06-18 06:15 UTC, improve777 commented on namjackson/ArchStudy/app/src/main/java/com/namjackson/archstudy/util/DatabindingUtil.kt
> +fun setVisibility(view: View, boolean: Boolean) {
이건 사소한것 같긴 한데.. 인자명으로 isVisible 이 더 좋았을거 같아요

2019-06-18 06:24 UTC, ddaeyeonkim approved these changes
LGTM 👍👍👍

2019-06-18 10:47 UTC, namjackson commented on namjackson/ArchStudy/app/src/main/java/com/namjackson/archstudy/util/DatabindingUtil.kt
> +fun setVisibility(view: View, boolean: Boolean) {
그게 더 명확하긴하네요! 다음주에 과제할때 반영할게요!

2019-06-18 10:48 UTC, merged