HW-1 Naver Api 사용한 영화검색 앱
sjjeong/GoogryAndroidArchitecutreStudy pull request #620
Opened 2020-04-29 00:15 UTC by LeeChungWoo92

2020-05-03 10:49 UTC, hwaniiidev approved these changes

2020-05-03 16:57 UTC, sjjeong requested changes

2020-05-03 16:57 UTC, sjjeong commented on 2005/leechungwoo92/StudyForkProject/app/src/main/java/com/lllccww/studyforkproject/view/adapter/MovieListAdapter.kt
> +class MovieListAdapter(val context: Context) : RecyclerView.Adapter<MovieListAdapter.ViewHolder>() {
Context는 전달 받을 필요가 없습니다.
제거하고 에러를 수정해보세요

2020-05-03 16:57 UTC, sjjeong commented on 2005/leechungwoo92/StudyForkProject/app/src/main/java/com/lllccww/studyforkproject/view/adapter/MovieListAdapter.kt
> +    fun setItems(items: ArrayList<MovieItem>) {
set이면 clear하고 addAll느낌인데 실제 함수 내부는 addAll만 해주고 있습니다.
함수명을 addItems로 변경하거나 함수 구현을 변경해주세요

2020-05-03 16:57 UTC, sjjeong commented on 2005/leechungwoo92/StudyForkProject/app/src/main/java/com/lllccww/studyforkproject/view/adapter/MovieListAdapter.kt
> +        holder.llParentView.setOnClickListener {
리스너 추가는 onCreateViewHolder에서 추가해주세요

2020-05-03 16:57 UTC, sjjeong commented on 2005/leechungwoo92/StudyForkProject/app/src/main/java/com/lllccww/studyforkproject/view/activity/MainActivity.kt
> +    private var movieList = ArrayList<MovieItem>()
사용하지 않는 것은 제거해주세요

2020-05-03 16:57 UTC, sjjeong commented on 2005/leechungwoo92/StudyForkProject/app/src/main/java/com/lllccww/studyforkproject/view/activity/MainActivity.kt
> +                        //movieList.clear()
불필요한 주석들은 제거해주세요

2020-05-03 16:57 UTC, sjjeong commented on 2005/leechungwoo92/StudyForkProject/app/src/main/java/com/lllccww/studyforkproject/view/activity/MainActivity.kt
> +                        display = Integer.parseInt(movieData!!.display)
Integer.parseInt보단 movieData.total.toInt()를 사용하는게 더 코틀린스럽게 코딩하는 방법입니다.

2020-05-03 16:57 UTC, sjjeong commented on 2005/leechungwoo92/StudyForkProject/app/src/main/java/com/lllccww/studyforkproject/view/activity/MainActivity.kt
> +        var view = this.currentFocus
var보단 val을 사용하도록 해주세요

2020-05-03 16:57 UTC, sjjeong commented on 2005/leechungwoo92/StudyForkProject/app/src/main/java/com/lllccww/studyforkproject/view/activity/MainActivity.kt
> +    fun closeKeyboard() {
private 추가해주세요

2020-05-03 16:57 UTC, sjjeong commented on 2005/leechungwoo92/StudyForkProject/app/src/main/java/com/lllccww/studyforkproject/view/activity/MainActivity.kt
> +        rv_movie_list.layoutManager = LinearLayoutManager(this)
LayoutManager는 xml에서 추가할 수 있습니다.

2020-05-07 05:10 UTC, LeeChungWoo92 commented on 2005/leechungwoo92/StudyForkProject/app/src/main/java/com/lllccww/studyforkproject/view/adapter/MovieListAdapter.kt
> +class MovieListAdapter(val context: Context) : RecyclerView.Adapter<MovieListAdapter.ViewHolder>() {
수정하였습니다.

2020-05-07 05:11 UTC, LeeChungWoo92 commented on 2005/leechungwoo92/StudyForkProject/app/src/main/java/com/lllccww/studyforkproject/view/adapter/MovieListAdapter.kt
> +    fun setItems(items: ArrayList<MovieItem>) {
넵 수정하였습니다! 

de1b91f

2020-05-07 05:13 UTC, LeeChungWoo92 commented on 2005/leechungwoo92/StudyForkProject/app/src/main/java/com/lllccww/studyforkproject/view/adapter/MovieListAdapter.kt
> +        holder.llParentView.setOnClickListener {
석준님 블로그 보고 수정하였습니다!

9524583

2020-05-07 05:14 UTC, LeeChungWoo92 commented on 2005/leechungwoo92/StudyForkProject/app/src/main/java/com/lllccww/studyforkproject/view/activity/MainActivity.kt
> +        rv_movie_list.layoutManager = LinearLayoutManager(this)
처음알았네요!! 감사합니다
수정하였습니다!

92b7ad2

2020-05-07 05:16 UTC, LeeChungWoo92 commented on 2005/leechungwoo92/StudyForkProject/app/src/main/java/com/lllccww/studyforkproject/view/activity/MainActivity.kt
> +    fun closeKeyboard() {
수정했습니다!

0ca393e
커밋이 통으로 되어버렸습니다 ㅠㅠ

2020-05-07 05:16 UTC, LeeChungWoo92 commented on 2005/leechungwoo92/StudyForkProject/app/src/main/java/com/lllccww/studyforkproject/view/activity/MainActivity.kt
> +        var view = this.currentFocus
수정했습니다!
커밋이 통으로 되어버렸습니다....
0ca393e

2020-05-07 05:17 UTC, LeeChungWoo92 commented on 2005/leechungwoo92/StudyForkProject/app/src/main/java/com/lllccww/studyforkproject/view/activity/MainActivity.kt
> +                        display = Integer.parseInt(movieData!!.display)
감사합니다 
수정하였습니다!! 
0ca393e

2020-05-08 15:14 UTC, sjjeong requested changes

2020-05-08 15:14 UTC, sjjeong commented on 2005/leechungwoo92/StudyForkProject/app/src/main/java/com/lllccww/studyforkproject/view/activity/MainActivity.kt
> +                    (recyclerView.layoutManager as LinearLayoutManager?)!!.findLastCompletelyVisibleItemPosition()
`as LinearLayoutManager?`보다 `as? LinearLayoutManager`로 쓰는게 좋습니다.
두개의 차이점에 대해 알아보세요

2020-05-08 15:14 UTC, sjjeong commented on 2005/leechungwoo92/StudyForkProject/app/src/main/java/com/lllccww/studyforkproject/view/activity/MainActivity.kt
> +                val itemTotalCount = recyclerView.adapter!!.itemCount - 1
movieListAdapter를 사용하면 !!를 쓰지 않아도 됩니다.

2020-05-08 15:14 UTC, sjjeong commented on 2005/leechungwoo92/StudyForkProject/app/src/main/java/com/lllccww/studyforkproject/view/activity/MainActivity.kt
> +                        Log.d("display : ", display.toString())
movieData에 !!를 전부 사용중인데 사용하지 않도록 해주세요

2020-05-08 15:14 UTC, sjjeong commented
@LeeChungWoo92 
리뷰 전부 반영하셨다면 라벨 변경해주세요

2020-05-09 08:33 UTC, LeeChungWoo92 commented on 2005/leechungwoo92/StudyForkProject/app/src/main/java/com/lllccww/studyforkproject/view/activity/MainActivity.kt
> +                    (recyclerView.layoutManager as LinearLayoutManager?)!!.findLastCompletelyVisibleItemPosition()
수정하였습니다!   609f81e
as? LinearLayoutManager 으로 사용할시 
TypeCastException을 방지해준다고 하는데 맞나요???

2020-05-09 08:34 UTC, LeeChungWoo92 commented on 2005/leechungwoo92/StudyForkProject/app/src/main/java/com/lllccww/studyforkproject/view/activity/MainActivity.kt
> +                val itemTotalCount = recyclerView.adapter!!.itemCount - 1
수정하였습니다!  fd3da74

2020-05-09 08:35 UTC, LeeChungWoo92 commented on 2005/leechungwoo92/StudyForkProject/app/src/main/java/com/lllccww/studyforkproject/view/activity/MainActivity.kt
> +                        Log.d("display : ", display.toString())
수정하였습니다 ! 3fe9e8f
movieData!! 말고
if (movieData != null) {

}
이거로 사용하면 되나요??

2020-05-09 08:36 UTC, LeeChungWoo92 commented
리뷰 전부 반영하였습니다.! 
라벨을 어떤걸로 변경해야하나요 ??

2020-05-09 14:56 UTC, hwaniiidev commented
answer 라벨을 mentor 라벨로 바꾸시면 될 거 같아요 
merge 라벨은 석준님이 달아주시는 걸로 알고 있습니다

2020-05-09 15:49 UTC, LeeChungWoo92 commented
Mentor Needed랑 Review Needed로 해놓으면되는건가용?

2020-05-09 17:00 UTC, sjjeong commented on 2005/leechungwoo92/StudyForkProject/app/src/main/java/com/lllccww/studyforkproject/view/activity/MainActivity.kt
> +                    (recyclerView.layoutManager as LinearLayoutManager?)!!.findLastCompletelyVisibleItemPosition()
네 맞습니다

2020-05-09 17:03 UTC, sjjeong requested changes

2020-05-09 17:03 UTC, sjjeong commented on 2005/leechungwoo92/StudyForkProject/app/src/main/java/com/lllccww/studyforkproject/view/activity/MainActivity.kt
> +                        }
val movieData = response.body() ?: return 해주면 아래 null 검사하는 로직이 없어도 됩니다.

2020-05-09 17:39 UTC, LeeChungWoo92 commented on 2005/leechungwoo92/StudyForkProject/app/src/main/java/com/lllccww/studyforkproject/view/activity/MainActivity.kt
> +                        }
수정하였습니다!! 6d99658
좋은방법이네요!!!!

2020-05-09 17:40 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-05-09 17:43 UTC, merged