2005/ryu c0605 hw1
sjjeong/GoogryAndroidArchitecutreStudy pull request #622
Opened 2020-04-30 02:53 UTC by RyuC0605

안녕하세요. 류승윤 입니다.

앞으로 잘 부탁드립니다.

다른 분들이 리사이클뷰를 이용하여 구현하실거 

같아서 요즘 잘 사용하지 않는 리스트뷰를 이용해 봤습니다.

리스트뷰를 모르시는 분들께 도움이 되길 바랍니다.

네트워크 체크 로직은 비용에 비해 불필요해보이는 작업이라 제외 했습니다.

요청사항에 없기도 했구... (사실 귀찮아서 안했습니다 ㅎㅎ)

감사합니다.

2020-05-01 00:59 UTC, sangjinKIM93 commented
안녕하세요 승윤님 ^^

공부하는 마음으로 한줄한줄 읽어나갔습니다.
작은 코딩 습관부터 새롭게 알게 된 개념까지 많은 것을 배우고 갑니다.

저도 최대한 도움을 드리고자 앱도 계속 테스트 해보고 코드도 다시 한번 보면서 연구했지만 아직 많이 부족해서 도움이 될지는 모르겠네요 ㅎㅎ

리뷰는 아래에 남기겠습니다.

2020-05-01 01:03 UTC, sangjinKIM93 commented on 2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/MainActivity.kt
> +                true
검색시 빈 항목으로 **검색 버튼**을 누르면 키패드가 사라지지 않지만 **키패드 검색 아이콘**을 눌렀을때는 키패드가 사라집니다.
일관성과 사용자의 편의성을 고려하면 키패트 검색 아이콘을 눌렀을때도 키패드가 사라지지 않도록 하는 것도 좋을 것 같습니다.

2020-05-01 01:05 UTC, sangjinKIM93 commented on 2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/MainActivity.kt
> +        var keyword: String = edt_input.text.toString();
여기 두 줄에는 ';' 을 남기셨는데 이유가 있으신건지 궁금합니다!

2020-05-01 01:12 UTC, sangjinKIM93 commented on 2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/MainActivity.kt
> +    }
매개변수로 받은 v가 활용되지 않았습니다. v.requestFocus()도 변경하는 것도 좋을 것 같습니다.

2020-05-01 08:45 UTC, RyuC0605 commented on 2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/MainActivity.kt
> +                true
hideKeyPad() 펑션이 onClick() 안쪽에 위치하는게 더 합리적으로 생각되어 수정하였습니다.
감사합니다.

2020-05-01 08:49 UTC, RyuC0605 commented on 2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/MainActivity.kt
> +        var keyword: String = edt_input.text.toString();
10년 가까이 자바코딩을 하다 보니 구문 끝에 
세미콜론 붙이는 습관을 고치기 쉽지 않네요.
그걸 감안해서 코틀린에선 세미콜론을 허용하고 있지만,
통일된 코드가 좋아보여 제거하였습니다. 

감사합니다.

2020-05-01 08:50 UTC, RyuC0605 commented on 2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/MainActivity.kt
> +    }
발견하지 못한 부분이네요. 역시 장기나 바둑도 훈수를 두면 더 잘 보이듯
내 눈에 보이지 않는 부분이 남에 눈에는 보인다는 걸 새삼 느꼈습니다.

감사합니다.

2020-05-03 17:14 UTC, sjjeong requested changes

2020-05-03 17:14 UTC, sjjeong commented on 2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/networks/RetrofitClient.kt
> +    fun getClient(baseUrl: String?): Retrofit {
이 함수는 미사용 중이라서 제거하면 좋을 것 같습니다

2020-05-03 17:14 UTC, sjjeong commented on 2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/networks/RetrofitClient.kt
> +            return builder.client(httpClient.build()).build()
Builder 패턴이기 때문에 method chaining 형태로 사용 할 수 있습니다.
```kotlin
return Retrofit.Builder()
    .baseUrl(BuildConfig.NAVER_API_URL)
    .addConverterFactory(GsonConverterFactory.create())
    .client(httpClient.build())
    .build()
```

2020-05-03 17:14 UTC, sjjeong commented on 2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/networks/RetrofitClient.kt
> +            val httpClient = genOkHttpClient()
genOkHttpClient가 Builder를 리턴하기 때문에 httpClientBuilder가 더 맞는 이름일 것 같습니다.
아니라면 genOkHttpClient함수가 OkHttpClient를 리턴하도록 내부에서 .build()를 호출해주세요

2020-05-03 17:14 UTC, sjjeong commented on 2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/networks/RetrofitClient.kt
> +        val client = OkHttpClient().newBuilder()
client보단 builder가 더 어울릴 것 같습니다.

2020-05-03 17:14 UTC, sjjeong commented on 2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/MainActivity.kt
> +    var mProgress: ProgressDialog? = null
kotlin에서는 m prefix를 사용하지 않고 있습니다.
progressDialog 정도면 좋을 것 같습니다.

2020-05-03 17:14 UTC, sjjeong commented on 2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/MainActivity.kt
> +    fun hideKeyPad(v: View) {
Activity 클래스 내부에서만 사용하는 함수라면 private을 추가해주세요

2020-05-03 17:14 UTC, sjjeong commented on 2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/MainActivity.kt
> +        imm.hideSoftInputFromWindow(v.getWindowToken(), 0)
v.getWindowToken()대신 v.windowToken으로 사용할 수 있습니다.
kotlin에서는 get과 set을 축약해서 사용 가능하니 showKeyPad()함수 내부와 MovieAdapter 에 있는 부분 같이 변경해주세요

2020-05-03 17:14 UTC, sjjeong commented on 2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/MainActivity.kt
> +        var api: NaverApi = RetrofitClient.client.create(NaverApi::class.java)
var보단 val을 사용하도록 해주세요

2020-05-03 17:14 UTC, sjjeong commented on 2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/MainActivity.kt
> +        keyword = keyword.trim()
trim을 edt_input.text.toString()에서 같이 해주면 좋을 것 같습니다.
하면서 var로 선언된 것을 val로 변경해주세요

2020-05-03 17:14 UTC, sjjeong commented on 2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/MainActivity.kt
> +        api.searchMovie(keyword)?.enqueue(object : Callback<MovieVo> {
searchMovie의 리턴이 nonnull이기 때문에 ?는 없어도 됩니다.

2020-05-03 17:14 UTC, sjjeong commented on 2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/MainActivity.kt
> +                var adt = response.body()?.let { MovieAdapter(response.body()!!.items) }
response.body()?.let {}을 했다면 let {} 내부에서는 it으로 접근하면 됩니다.
val로 선언해주시면서 만약 response.body가 null이면 정상동작이 아니기 때문에 return 처리를 하면 좋을 것 같습니다.

2020-05-03 17:14 UTC, sjjeong commented on 2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/MainActivity.kt
> +        override fun getView(position: Int, convertView: View?, parent: ViewGroup?): View {
getView에 ViewHolder 개념이 들어가지 않으면 View가 재사용 되지 않기 때문에 리소스 낭비가 되는 것으로 알고 있습니다.
ViewHolder 개념을 추가해주면 좋을 것 같습니다.

2020-05-03 17:14 UTC, sjjeong commented on 2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/MainActivity.kt
> +                .centerCrop().into(rowView.iv_thumbnail)
method가 chaining될 때는 함수 호출을 한 라인에서 처리하는게 가독성에 좋습니다.
```kotlin
Glide.with(rowView.context)
    .load(item.image)
    .placeholder(R.drawable.no_image)
    .centerCrop()
    .into(rowView.iv_thumbnail)
```

2020-05-03 17:14 UTC, sjjeong commented on 2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/MainActivity.kt
> +                lv_contents.onItemClickListener =
Adapter를 set하고 ItemClickListener를 set하는 것은 요청 이후에 매번 할 필요가 없어 보입니다.
Activity가 생성될 때 한번만 하도록 하기 위해 onCreate에서 처리해주시고 요청 이후 응답처리에서는 데이터만 교체하는 형태로 변경해주세요

2020-05-03 17:15 UTC, sjjeong commented
@RyuC0605 
리뷰 반영하셨다면 코멘트마다 커밋 id를 남겨주세요

2020-05-05 11:03 UTC, RyuC0605 commented on 2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/networks/RetrofitClient.kt
> +    fun getClient(baseUrl: String?): Retrofit {
이슈 1

2020-05-05 11:04 UTC, RyuC0605 commented on 2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/networks/RetrofitClient.kt
> +            return builder.client(httpClient.build()).build()
이슈 2

2020-05-05 11:04 UTC, RyuC0605 commented on 2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/networks/RetrofitClient.kt
> +            val httpClient = genOkHttpClient()
이슈 3

2020-05-05 11:04 UTC, RyuC0605 commented on 2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/networks/RetrofitClient.kt
> +        val client = OkHttpClient().newBuilder()
이슈 4

2020-05-05 11:04 UTC, RyuC0605 commented on 2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/MainActivity.kt
> +    var mProgress: ProgressDialog? = null
이슈 5

2020-05-05 11:04 UTC, RyuC0605 commented on 2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/MainActivity.kt
> +    fun hideKeyPad(v: View) {
이슈 6

2020-05-05 11:05 UTC, RyuC0605 commented on 2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/MainActivity.kt
> +        imm.hideSoftInputFromWindow(v.getWindowToken(), 0)
이슈 7

2020-05-05 11:17 UTC, RyuC0605 commented on 2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/MainActivity.kt
> +        keyword = keyword.trim()
이슈 9

2020-05-05 11:17 UTC, RyuC0605 commented on 2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/MainActivity.kt
> +        var api: NaverApi = RetrofitClient.client.create(NaverApi::class.java)
이슈 8

2020-05-05 11:19 UTC, RyuC0605 commented on 2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/MainActivity.kt
> +        api.searchMovie(keyword)?.enqueue(object : Callback<MovieVo> {
이슈 10

2020-05-05 11:20 UTC, RyuC0605 commented on 2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/MainActivity.kt
> +                var adt = response.body()?.let { MovieAdapter(response.body()!!.items) }
이슈 11

2020-05-05 11:25 UTC, RyuC0605 commented on 2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/MainActivity.kt
> +        override fun getView(position: Int, convertView: View?, parent: ViewGroup?): View {
이슈 12

2020-05-05 11:27 UTC, sangjinKIM93 approved these changes

2020-05-05 12:53 UTC, RyuC0605 commented on 2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/MainActivity.kt
> +                .centerCrop().into(rowView.iv_thumbnail)
이슈 13
수정했습니다.

감사합니다.

da1d66b88078e51f4e1c9df74bf1576bb653b951

2020-05-05 12:54 UTC, RyuC0605 commented on 2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/MainActivity.kt
> +                lv_contents.onItemClickListener =
이슈 14
수정했습니다.

감사합니다.
e5ee82bf630bf847b5a322254df3fd54bf2048dd

2020-05-05 14:11 UTC, sjjeong commented
@RyuC0605 
Answer Needed를 제거하셨다면 Review Needed를 추가해주셔야 해요

2020-05-05 14:20 UTC, sjjeong commented on 2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/MainActivity.kt
> +                adt.movieList.addAll(response.body()!!.items)
if(response.body() == null)로 null 체크를 했지만 아래에서 !!로 사용 중인 코드입니다.
```kotlin
val body = response.body()
if(body == null) {
    return
}
```
이렇게하면 !! 없이 사용할 수 있고
```kotlin
val body = response.body() ?: return
```
이렇게도 사용 할 수 있습니다.

2020-05-05 14:20 UTC, sjjeong commented on 2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/MainActivity.kt
> +        override fun getView(position: Int, convertView: View?, parent: ViewGroup?): View {
@RyuC0605 
네 kotlin-android-extensions 에 있는 기능입니다.
내부적으로는 findViewById와 동일한 동작을 하는 코드입니다.

2020-05-05 14:27 UTC, sjjeong requested changes

2020-05-05 14:27 UTC, sjjeong commented on 2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/MainActivity.kt
> +            }
이렇게 만들 수 있겠네요
```kotlin
val holder = (convertView?.tag as? ViewHolder)
    ?: run {
        val rowView = inflater.inflate(R.layout.row_content, parent, false)
        ViewHolder(rowView).also { rowView.tag = it }
    }
```

2020-05-05 15:13 UTC, RyuC0605 commented on 2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/MainActivity.kt
> +            }
convertView 가 null 이면 문제가 되지 않을지 also 키워드와 run 키워드.. .아직 코틀린 공부가 더 필요한 부분이 보이네요

2020-05-05 15:21 UTC, RyuC0605 commented on 2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/MainActivity.kt
> +                adt.movieList.addAll(response.body()!!.items)
2안으로 수정했습니다.

감사합니다.
6119d136e22c80096e7538dec2a91a9742f66e0b

2020-05-05 15:21 UTC, RyuC0605 commented on 2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/MainActivity.kt
> +            }
수정했습니다.

감사합니다.
6119d136e22c80096e7538dec2a91a9742f66e0b

2020-05-06 10:11 UTC, sjjeong commented on 2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/MainActivity.kt
> +            }
> 코딩하면서도 어떻게 축약하고는 싶은데 아직 코틀린이 아직 어설퍼서...
> 근데 convertView 가 null 이면 문제가 되지 않을지 모르겠네요...
> also 키워드와 run 키워드.. .아직 코틀린 공부가 더 필요한 부분이 보이네요

@RyuC0605 
convertView가 null이라면 convertView?.tag가 null이 되기 때문에 ?:를 통해 run 코드가 실행됩니다.

2020-05-06 10:11 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-05-06 15:17 UTC, merged