HW-4 DataBinding 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #625
Opened 2020-05-03 15:10 UTC by nukeolaf

DataBinding 을 처음 사용해봐서 조금 어려웠습니다.
제가 제대로 사용한게 맞는지 잘 모르겠네요ㅠㅠ

2020-05-06 13:03 UTC, ghost requested changes
확인 부탁드립니다!

2020-05-06 13:03 UTC, ghost commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/ui/MovieAdapter.kt
> +        return if (this.isNotEmpty()) {
isEmpty 대신 isBlank() 를 사용하면 "   " 같은 화이트 스페이스도 prefix 안붙일 수 있어서 더 좋을 거같아요!

2020-05-07 17:03 UTC, nukeolaf commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/ui/MovieAdapter.kt
> +        return if (this.isNotEmpty()) {
수정했습니다!
3d64877

2020-05-08 15:17 UTC, ghost approved these changes
LGTM 👍👍

2020-05-09 04:14 UTC, sjjeong requested changes

2020-05-09 04:14 UTC, sjjeong commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/ui/MovieAdapter.kt
> +        }
movies.map { it.copy(...) } 로 하면 됩니다.
data class의 copy 함수에 대해 알아보세요

2020-05-09 04:14 UTC, sjjeong commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/ui/MovieItemViewHolder.kt
>      private lateinit var movieItem: MovieItem
이거는 이제 binding.movieItem으로 접근하면 되니 삭제해도 될 것 같아요

2020-05-09 04:14 UTC, sjjeong commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/ui/MovieAdapter.kt
> +        val binding = ItemMoviesRvBinding.inflate(inflater, parent, false)
이렇게 사용 할 수 있지만 나중에 layout file name으로 사용중인 곳을 찾기 어려워지는 단점이 있어서 유지보수하기 어려워 집니다.
DataBindingUtil을 사용하도록 변경해주세요

2020-05-09 12:42 UTC, nukeolaf commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/ui/MovieAdapter.kt
> +        }
이런기능이 있었다니... 알려주셔서 감사합니다
collection 에 대해 완전 몰랐던거 같아서 더 공부해야겠네요

6bb7533

2020-05-09 12:54 UTC, nukeolaf commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/ui/MovieItemViewHolder.kt
>      private lateinit var movieItem: MovieItem
수정했습니다!
8865964

2020-05-09 12:54 UTC, nukeolaf commented on 2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/ui/MovieAdapter.kt
> +        val binding = ItemMoviesRvBinding.inflate(inflater, parent, false)
수정했습니다!
822e18c

2020-05-09 14:26 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-05-09 14:41 UTC, merged