HW-4 DataBinding
sjjeong/GoogryAndroidArchitecutreStudy pull request #627
Opened 2020-05-08 05:42 UTC by jesterz91

DataBinding 적용

2020-05-08 12:07 UTC, Kyudong3 requested changes
Good!!!

2020-05-08 12:07 UTC, Kyudong3 approved these changes
Good!!!

2020-05-08 12:10 UTC, Kyudong3 approved these changes

2020-05-08 15:03 UTC, sjjeong requested changes
Activity는 안하셨네요 
Activity에 있는 layout도 DataBinding을 쓰도록 해주세요

2020-05-09 14:08 UTC, jesterz91 commented
Activity에 있는 layout도 DataBinding을 사용하도록 수정했습니다.

669e690

2020-05-09 14:32 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-05-09 16:21 UTC, merged