HW-2 MVP 패턴 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #63
Opened 2019-06-17 13:31 UTC by BeokBeok

google blueprint 오픈 소스 참고하여 MVP 패턴 적용하였습니다.

2019-06-18 13:18 UTC, NackUn commented on BeokBeok/app/src/main/java/com/architecturestudy/upbitmarket/UpBitFragment.kt
> +    private lateinit var upBitPresenter: UpBitPresenter
upBitPresenter 어디에 쓰는 건가요??

2019-06-18 13:18 UTC, NackUn commented on BeokBeok/app/src/main/java/com/architecturestudy/upbitmarket/UpBitFragment.kt
> +        upBitPresenter = UpBitPresenter(UpBitRepository.getInstance(UpBitRetrofitDataSource.getInstance()), this)
presenter = UpBitPresenter(UpBitRepository.getInstance(UpBitRetrofitDataSource.getInstance()), this) 이렇게 해주면 안되나요?

2019-06-18 13:36 UTC, BeokBeok commented on BeokBeok/app/src/main/java/com/architecturestudy/upbitmarket/UpBitFragment.kt
> +    private lateinit var upBitPresenter: UpBitPresenter
뷰에서 프레젠터를 통하여 이벤트를 발생 시키고
해당 이벤트에 대한 데이터를 프레젠터에서 받아서 뷰에 전달 시키기 위해 사용합니다.

2019-06-18 13:40 UTC, BeokBeok commented on BeokBeok/app/src/main/java/com/architecturestudy/upbitmarket/UpBitFragment.kt
> +        upBitPresenter = UpBitPresenter(UpBitRepository.getInstance(UpBitRetrofitDataSource.getInstance()), this)
@NackUn 
UpBitRepository 에서 RemoteDataSource (Retrofit) 를 통하여 Retrofit 통신을 하고 난 데이터를 전달받기 위해 사용하였습니다.
단순하게 UpBitRepository에서 Retrofit 통신을 해도 되지만,
추후 Local Data Source 를 사용할 수도 있기 때문에 위와 같은 방식으로 구현하였습니다.

2019-06-19 01:24 UTC, NackUn commented on BeokBeok/app/src/main/java/com/architecturestudy/upbitmarket/UpBitFragment.kt
> +    private lateinit var upBitPresenter: UpBitPresenter
네! 친절한 설명 감사드립니다.

2019-06-19 01:25 UTC, NackUn commented on BeokBeok/app/src/main/java/com/architecturestudy/upbitmarket/UpBitFragment.kt
> +        upBitPresenter = UpBitPresenter(UpBitRepository.getInstance(UpBitRetrofitDataSource.getInstance()), this)
그렇군요! 배워갑니다. 제가 아직 미숙해서 조금 더 읽어보고 리뷰 마치도록 하겠습니다.

2019-06-19 01:36 UTC, NackUn commented on BeokBeok/app/src/main/java/com/architecturestudy/data/source/UpBitDataSource.kt
> +        fun onThickerLoaded(marketPrice: List<UpBitTicker>)
onThickerLoaded 함수명 오타이신 것 같아서요

2019-06-19 04:13 UTC, BeokBeok commented on BeokBeok/app/src/main/java/com/architecturestudy/data/source/UpBitDataSource.kt
> +        fun onThickerLoaded(marketPrice: List<UpBitTicker>)
@NackUn 
함수명 변경하였습니다.
700c9d6

2019-06-19 07:34 UTC, NackUn commented on BeokBeok/app/src/main/java/com/architecturestudy/data/source/UpBitDataSource.kt
> +        fun onThickerLoaded(marketPrice: List<UpBitTicker>)
확인했습니다. Mentor Needed 했습니다. 고생하셨습니다.

2019-06-19 12:29 UTC, NackUn commented on BeokBeok/app/src/main/java/com/architecturestudy/data/source/UpBitRetrofitDataSource.kt
> +                val responseTicker = response.body()
여기에 Elvis operator ( ?: )를 이용해보시는게 어떠실까요??

2019-06-19 13:54 UTC, BeokBeok commented on BeokBeok/app/src/main/java/com/architecturestudy/data/source/UpBitRetrofitDataSource.kt
> +                val responseTicker = response.body()
@NackUn 
엘비스 연산자는 default 값을 null 이 아닌 다른 값을 지정할 때 사용합니다.
해서, 이 부분에서는 엘비스 연산자의 의도와는 맞지 않다고 생각합니다.

2019-06-19 14:04 UTC, NackUn commented on BeokBeok/app/src/main/java/com/architecturestudy/data/source/UpBitRetrofitDataSource.kt
> +                val responseTicker = response.body()
아하 그렇군요 그런 의도인지는 몰랐네요 감사합니다!

2019-06-20 01:11 UTC, BeokBeok commented
@NackUn 
Request changes로 변경 부탁 드립니다.

2019-06-20 02:05 UTC, NackUn requested changes
확인했습니다.

2019-06-20 02:05 UTC, NackUn submitted a review, later dismissed

2019-06-25 13:57 UTC, NackUn requested changes
리뷰해주신거 다 고치신 것 같고 추가적으로 적용하셨네요. 멋있습니다!!
Rx 쪽은 몰라서 리뷰를 못했네요. 고생하셨습니다.

2019-06-25 13:57 UTC, NackUn commented on BeokBeok/app/src/main/java/com/architecturestudy/upbitmarket/recyclerview/UpbitAdapter.kt
> +        val view = LayoutInflater.from(parent.context)
이 부분을 뷰홀더에서 만들어주고 한 줄로 축약하는건 어떠세요?

2019-06-25 14:34 UTC, BeokBeok commented on BeokBeok/app/src/main/java/com/architecturestudy/upbitmarket/recyclerview/UpbitAdapter.kt
> +        val view = LayoutInflater.from(parent.context)
적용 하였습니다.
6805f37

2019-06-26 00:22 UTC, NackUn commented on BeokBeok/app/src/main/java/com/architecturestudy/upbitmarket/recyclerview/UpbitAdapter.kt
>      ): ViewHolder {
= ViewHolder(parent) 도 가능하지 않을까요?

2019-06-26 01:16 UTC, BeokBeok commented on BeokBeok/app/src/main/java/com/architecturestudy/upbitmarket/recyclerview/UpbitAdapter.kt
>      ): ViewHolder {
구현부가 1 Line 인 경우에 대하여 적용하였습니다.
b7434f3

2019-06-26 03:15 UTC, NackUn submitted a review, later dismissed
고생하셨습니다!

2019-06-26 15:12 UTC, sjjeong requested changes
고생하셨습니다!

2019-06-26 15:12 UTC, sjjeong commented on BeokBeok/app/src/main/java/com/architecturestudy/upbitmarket/UpbitFragment.kt
> +        tv_market_usdt.setOnClickListener { setViewColor(tv_market_usdt) }
```kotlin
tv_market_usdt.setOnClickListener(this::setViewColor)
```
이렇게 사용하시면 더 좋습니다.

2019-06-26 15:12 UTC, sjjeong commented on BeokBeok/app/src/main/java/com/architecturestudy/upbitmarket/UpbitFragment.kt
>          presenter.start()
presenter.start()는 onViewCreated로 이동하는게 좋을 것 같습니다.

2019-06-26 15:12 UTC, sjjeong commented on BeokBeok/app/src/main/java/com/architecturestudy/upbitmarket/recyclerview/UpbitAdapter.kt
> +    var marketPrice: List<Map<String, String>>? = null
```kotlin
val marketPrice = mutableListOf<Map<String, String>>()
```
으로 해주세요

2019-06-26 15:12 UTC, sjjeong commented on BeokBeok/app/src/main/java/com/architecturestudy/upbitmarket/recyclerview/UpbitAdapter.kt
> +        this.marketPrice = marketPrice
외부와 객체를 공유하면 좋지 않습니다.
clear와 addAll을 사용해 Collection안에 있는 데이터만 넣어주도록 해주세요

2019-06-27 00:53 UTC, BeokBeok commented on BeokBeok/app/src/main/java/com/architecturestudy/upbitmarket/UpbitFragment.kt
> +        tv_market_usdt.setOnClickListener { setViewColor(tv_market_usdt) }
적용 하였습니다.
b2b3ae9

2019-06-27 01:21 UTC, BeokBeok commented on BeokBeok/app/src/main/java/com/architecturestudy/upbitmarket/UpbitFragment.kt
>          presenter.start()
적용 하였습니다.
28a7f34

2019-06-27 01:28 UTC, BeokBeok commented on BeokBeok/app/src/main/java/com/architecturestudy/upbitmarket/recyclerview/UpbitAdapter.kt
> +    var marketPrice: List<Map<String, String>>? = null
적용 하였습니다.
6147124

2019-06-27 01:29 UTC, BeokBeok commented on BeokBeok/app/src/main/java/com/architecturestudy/upbitmarket/recyclerview/UpbitAdapter.kt
> +        this.marketPrice = marketPrice
적용 하였습니다.
6147124

2019-06-27 08:26 UTC, NackUn approved these changes
Approve 합니다!

2019-06-28 04:27 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-06-28 04:28 UTC, merged