HW-5 ViewModel적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #630
Opened 2020-05-10 15:29 UTC by TaeseongYun

2020-05-14 07:52 UTC, ghost reviewed
아직 ViewModel과 Activity의 경계가 뚜렷하지 않아서 리뷰해드리기가 애매했던거 같네요..
Rx 파트는 멘토님에게 부탁드리겠습니다. 늦어서 죄송합니다.

2020-05-14 07:52 UTC, invitejay commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/base/BaseRecyclerAdapter.kt
> +    internal val itemList = mutableListOf<ObservableField<ITEM>>()
저 같은 경우는 이부분에 ObservableField를 작성하지 않았습니다. 혹시 작성해야하는 이유가 있나요?

2020-05-14 07:52 UTC, invitejay commented on 2004/taeseongyun/app/src/main/res/layout/activity_main.xml
>              type="com.tsdev.tsandroid.ui.MainActivity" />
activity를 따로 참조하지 않으니 지워주셔도 될 거 같습니다

2020-05-14 07:52 UTC, invitejay commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ui/MainActivity.kt
> +    private fun showToastMessage(message: String) {
Toast는 Extension으로 만들어주면 좋을거 같습니다

2020-05-14 07:52 UTC, invitejay commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ui/viewmodel/BaseViewModel.kt
> +    abstract fun onBackKeyPressed()
BackPress는 Activity에서 관리해주는게 좋을거 같습니다.

2020-05-14 23:33 UTC, TaeseongYun commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/base/BaseRecyclerAdapter.kt
> +    internal val itemList = mutableListOf<ObservableField<ITEM>>()
옵저블필드를 처음 사용하다보니 미숙해서 어뎁터에도 들어가야 생각해서 넣었습니다.
다시 보니 들어갈 필요가 없네요 수정했습니다.

545ef55

2020-05-14 23:35 UTC, TaeseongYun commented on 2004/taeseongyun/app/src/main/res/layout/activity_main.xml
>              type="com.tsdev.tsandroid.ui.MainActivity" />
수정했습니다.

abdef95

2020-05-14 23:37 UTC, TaeseongYun commented on 2004/taeseongyun/app/src/main/res/layout/activity_main.xml
>              type="com.tsdev.tsandroid.ui.MainActivity" />
코드 보시면 액티비티 참고하고 있습니다.

2020-05-14 23:38 UTC, TaeseongYun commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ui/viewmodel/BaseViewModel.kt
> +    abstract fun onBackKeyPressed()
이건 멘토님께 물어봐야겠네요.

2020-05-14 23:42 UTC, TaeseongYun commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ui/MainActivity.kt
> +    private fun showToastMessage(message: String) {
수정했습니다.

ee1bf52

2020-05-15 06:37 UTC, ghost approved these changes
고생하셨습니다..!
멘토님 ViewModel의 BackPress 코드와 Rx 부분좀 부탁드릴게요

2020-05-15 12:54 UTC, sjjeong requested changes

2020-05-15 12:54 UTC, sjjeong commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ui/MainActivity.kt
> +        viewModel.onBackKeyPressed()
Presenter였을 땐 로직처리가 필요해서 그냥 뒀지만 ViewModel에서 하는 것은 성격이 잘 안맞을 것 같습니다.
onBackPressed를 눌렀을 때 다시 묻는 토스트가 나오는 Util class를 만들어서 처리하면 좋을 것 같습니다.

onCreate에 있는 코드들도 같이 이동해보세요

2020-05-15 12:54 UTC, sjjeong commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ui/viewmodel/MainViewModel.kt
> +    fun searchMovie(activity: Activity, view: View) {
Activity와 View를 받지 않도록 해주세요

2020-05-15 12:54 UTC, sjjeong commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ui/viewmodel/MainViewModel.kt
> +    }
BaseActivity처럼 BaseViewModel에서 처리하도록 해주세요
compositeDisposable도 이동해주세요

2020-05-15 12:54 UTC, sjjeong commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ui/viewmodel/MainViewModel.kt
> +                        }
여기선 apply보단 run이 적합할것 같습니다.

2020-05-15 12:54 UTC, sjjeong commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ui/viewmodel/MainViewModel.kt
> +    private val recyclerViewModel: RecyclerViewModel<Item>,
이것을 통해 전달 받기 보다
ViewModel에서 데이터 변화를 감지해서 View에서 갱신하도록 해주세요

2020-05-15 13:02 UTC, TaeseongYun commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ui/viewmodel/MainViewModel.kt
> +    private val recyclerViewModel: RecyclerViewModel<Item>,
이것이라는게 observableProvider 말씀하시는 건가요?

2020-05-15 13:03 UTC, TaeseongYun commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ui/viewmodel/MainViewModel.kt
> +    fun searchMovie(activity: Activity, view: View) {
액티비티와 뷰를 받으면 안되는이유가 context 때문일까요?

2020-05-15 14:03 UTC, sjjeong commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ui/viewmodel/MainViewModel.kt
> +    private val recyclerViewModel: RecyclerViewModel<Item>,
RecyclerViewModel 입니다

2020-05-15 14:05 UTC, sjjeong commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ui/viewmodel/MainViewModel.kt
> +    fun searchMovie(activity: Activity, view: View) {
네 차라리 hideKeyboard를 할 수 있는 higher-order function을 전달하고 호출만 하도록 해주세요

2020-05-15 15:18 UTC, TaeseongYun commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ui/viewmodel/MainViewModel.kt
> +    private val recyclerViewModel: RecyclerViewModel<Item>,
수정하였습니다. 

4d7bc2d

어떠한 이유 때문에 RecyclerViewModel 을 전달 받지않아야 하는지 알 수 있을까요?
ViewModel 과 view간의 관계가 어긋나서 인가요?

2020-05-15 15:20 UTC, TaeseongYun commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ui/viewmodel/MainViewModel.kt
> +                        }
수정하였습니다.

3cb4cfc

2020-05-15 15:24 UTC, TaeseongYun commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ui/viewmodel/MainViewModel.kt
> +    }
수정하였습니다.

86d715d

2020-05-15 15:39 UTC, sjjeong commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ui/viewmodel/MainViewModel.kt
> +    private val recyclerViewModel: RecyclerViewModel<Item>,
mvvm 패턴은 vm이 가지고 있는 데이터의 변화를 view가 받아서 처리하도록 해야 하는데
지금 사용하신 형태는 vm이 view를 갱신하도록 하는 mvp와 가까운 패턴입니다.

2020-05-15 15:45 UTC, TaeseongYun commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ui/MainActivity.kt
> +        viewModel.onBackKeyPressed()
항상 액티비티에서 처리 했었는데 따로 클래스를 만들어 
init 박스에서 데이터 감지를 하도록 만들었는데 맞게 만들었는지 의문입니다. ㅜㅜ

수정하였습니다. 
5acdd88

2020-05-15 16:06 UTC, TaeseongYun commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ui/viewmodel/MainViewModel.kt
> +    fun searchMovie(activity: Activity, view: View) {
수정하였습니다.

1662c59

2020-05-16 03:56 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-05-16 06:48 UTC, merged