HW-5 MVVM 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #632
Opened 2020-05-12 15:03 UTC by Kyudong3

2020-05-15 13:48 UTC, ios-byungjoon-lee requested changes
리뷰를 늦게 해드려서 죄송합니다.

2020-05-15 13:48 UTC, jesterz91 commented on 2004/kyudong3/app/src/main/java/com/example/kyudong3/extension/BindingAdapters.kt
> +            (adapter as SearchMovieRvAdapter).setMovieList(it)
smart casting 이 되므로 형변환을 명시하지 않아도 될 것 같습니다.

2020-05-15 13:48 UTC, jesterz91 commented on 2004/kyudong3/app/src/main/java/com/example/kyudong3/ui/MainActivity.kt
> +            })
ObservableField는 xml에서도 사용할수 있습니다.

2020-05-15 13:48 UTC, jesterz91 commented on 2004/kyudong3/app/src/main/java/com/example/kyudong3/ui/MainActivity.kt
>                  else -> {
이 부분은 BindingAdapter를 정의해서 사용할 수 있을 것 같습니다.

2020-05-15 13:48 UTC, jesterz91 commented on 2004/kyudong3/app/src/main/java/com/example/kyudong3/viewModel/MainViewModel.kt
> +    }
하나의 함수로 만들어 주는게 나을 것 같습니다.

2020-05-15 13:48 UTC, jesterz91 commented on 2004/kyudong3/app/src/main/res/layout/activity_main.xml
>              type="com.example.kyudong3.ui.MainActivity" />
이 변수는 사용되고 있지 않는 것 같네요.

2020-05-15 16:38 UTC, Kyudong3 commented on 2004/kyudong3/app/src/main/java/com/example/kyudong3/extension/BindingAdapters.kt
> +            (adapter as SearchMovieRvAdapter).setMovieList(it)
처음에 그렇게 했는데, adapter가 mutable type 이라 smart cast가 안된다고 해서 형변환을 붙여주었습니다!

2020-05-15 17:03 UTC, Kyudong3 commented on 2004/kyudong3/app/src/main/java/com/example/kyudong3/ui/MainActivity.kt
> +            })
수정했습니다!
d0066b7

2020-05-15 17:03 UTC, Kyudong3 commented on 2004/kyudong3/app/src/main/java/com/example/kyudong3/ui/MainActivity.kt
>                  else -> {
수정했습니다!
d0066b7

2020-05-15 17:03 UTC, Kyudong3 commented on 2004/kyudong3/app/src/main/java/com/example/kyudong3/viewModel/MainViewModel.kt
> +    }
수정하였습니다!
d0066b7

2020-05-15 17:03 UTC, Kyudong3 commented on 2004/kyudong3/app/src/main/res/layout/activity_main.xml
>              type="com.example.kyudong3.ui.MainActivity" />
수정했습니다!
d0066b7

2020-05-15 17:08 UTC, jesterz91 commented on 2004/kyudong3/app/src/main/java/com/example/kyudong3/extension/BindingAdapters.kt
> +            (adapter as SearchMovieRvAdapter).setMovieList(it)
넵. 제가 그 부분까지는 생각하지 못한것 같습니다.

2020-05-15 17:12 UTC, ios-byungjoon-lee approved these changes
Good👍

2020-05-16 01:34 UTC, jesterz91 commented on 2004/kyudong3/app/src/main/java/com/example/kyudong3/ui/MainActivity.kt
>                  else -> {
vm 자체를 전달하는 것 보다, vm 의 함수를 전달하여 더 개선할 수 있는 것 같습니다.

2020-05-16 04:02 UTC, sjjeong requested changes

2020-05-16 04:02 UTC, sjjeong commented on 2004/kyudong3/app/src/main/java/com/example/kyudong3/extension/BindingAdapters.kt
> +            (adapter as SearchMovieRvAdapter).setMovieList(it)
adapter가 사실 getAdapter()라서 if로 is 체크를 하더라도 동일합니다.
변경한다면
movies?.let { (adapter as? SearchMovieRvAdapter)?.setMovieList(it) } 으로 하시면 됩니다.

2020-05-16 04:02 UTC, sjjeong commented on 2004/kyudong3/app/src/main/java/com/example/kyudong3/viewModel/MainViewModel.kt
> +        val query = searchQuery.get() as String
as String 보단 ?:로 null check를 해주는게 좋습니다.

2020-05-16 04:02 UTC, sjjeong commented on 2004/kyudong3/app/src/main/java/com/example/kyudong3/viewModel/MainViewModel.kt
> +            return
이거는 불필요해 보입니다

2020-05-16 06:36 UTC, merged