HW-2 Model 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #633
Opened 2020-05-12 16:11 UTC by developer-sungjae

- 결합도가 높고 매우 기초적인 MVC 패턴에서 Model을 분리
- Repository, LocalDataBase, RemoteDataBase 추가
- 화면이 켜져있을 때, 캐싱처리를 위한 Local : RoomDataBase 추가 
   (검색할 때 캐싱처리를 구현하려고 했으나 지연시간이 너무 짧아 무의미하다 생각하여 켜질때 캐싱처 
   리로 변경)
- API 통신(Remote : Retrofit)의 Request는 오직 버튼을 눌렀을 때

2020-05-12 20:28 UTC, chuuuul reviewed
퇴근하고 늦은 시간까지 과제 완료하시느라, 검토를 못하신 것 같습니다!

일부 사용하지 않는 클래스 및 코드 등을 PR하시기 전에 점검 해 주시면 감사하겠습니다~

고생하셨습니다!

2020-05-12 20:28 UTC, chuuuul commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/data/source/remote/NaverRemoteDataSource.kt
> +}
불필요한 파일인 것 같습니다~

2020-05-12 20:28 UTC, chuuuul commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/data/source/remote/NaverRemoteDataSourceImpl.kt
> +}
불필요한 파일인 것 같습니다~

2020-05-12 20:28 UTC, chuuuul commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/data/source/remote/NaverMovieRemoteDataSourceImpl.kt
> +    @SuppressLint("CheckResult")
질문드립니다! Dispose를 안쓰고 @SuppressLint("CheckResult")를 쓰는 이유가 있을까요?

2020-05-12 20:28 UTC, chuuuul commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/data/source/local/room/MovieRoomDataBase.kt
> +        fun destoryInstance() {
오타있습니다! destroy로 바꿔주세요

2020-05-12 20:28 UTC, chuuuul commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/data/source/local/room/MovieRoomDataBase.kt
> +        fun getInstance(context: Context): MovieRoomDataBase? {
return 타입에 nullable이 없으면 좋을 것 같습니다!

2020-05-12 20:28 UTC, chuuuul commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/data/source/local/NaverMovieLocalDataSourceImpl.kt
> +    override fun saveMovieList(data: ArrayList<Movie.Items>, context: Context?) {
1. 다른 곳에서도 보이는데 context에 nullable을 사용하신 이유가 있나요?

2. context는 파라미터 제일 앞에 있는게 좋다고 생각하는데 어떻게 생각하신가요?

2020-05-12 20:28 UTC, chuuuul commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/data/source/local/room/MovieLocal.kt
> +    @ColumnInfo(name = "userRating") var userRating: Double?
다른 클래스와 달리 이곳에서만 nullable을 사용하신 이유가 있을까요?

2020-05-12 20:28 UTC, chuuuul commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/data/source/local/room/MovieItem.kt
> +class MovieItem(
사용 하지 않는 클래스인것같습니다.

2020-05-12 20:28 UTC, chuuuul commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/data/source/local/room/AppDataBase.kt
> +}
사용하지 않는 클래스이신것같습니다.

2020-05-12 20:28 UTC, chuuuul commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/data/repository/NaverMovieRepositoryImpl.kt
> +        naverMovieLocalDataSource.getMovieList(context,
제가 생각하기엔 adapter를 가져오고 작업을 가져오는것들은 Model영역에서 해야할 일이 아니라 Control의 영역이라고 생각하는데 어떻게 생각하시나요?

2020-05-12 20:28 UTC, chuuuul commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/data/source/local/NaverMovieLocalDataSourceImpl.kt
> +            }).start()
질문있습니다! Observable전에 deleteAll을 하는 Thread가 먼저 끝나는게 보장이 되나요?

2020-05-12 20:28 UTC, chuuuul commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/data/source/local/NaverMovieLocalDataSourceImpl.kt
> +                        arrList.addAll(it)
파라미터는 ArrayList, 어뎁터는 MutableList, Response는 List로 되어 있는것을 MutableList와 Collection으로 통합 하면 좋을 것 같습니다.

2020-05-12 20:28 UTC, chuuuul commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/adapters/SearchAdapter.kt
> +    private val savedLocalList: MutableList<MovieLocal> = mutableListOf()
저의 정말 개인적인 의견입니다! 코드 읽을때 변수명때문에 너무 헷갈려서

    private val remoteList: MutableList<Movie.Items> = mutableListOf()
    private val localList: MutableList<MovieLocal> = mutableListOf()

로 바꾸면 가독성이 조금더 좋아질 것 같습니다. 
이미 알고 계시겠지만 변수,메서드 이름을 한번에 바꾸는방법은 Shift + F6 입니다.

`fun resetData(search: ArrayList<Movie.Items>) { ... } `
`fun setLocalData(savedResultList: ArrayList<MovieLocal>) { ... }`
또한

`fun setRemoteData(remoteData: ArrayList<Movie.Items>) { ... }`
`fun setLocalData(localData: ArrayList<MovieLocal>) { ... }`
로 바꾸면 좋을 것 같습니다.

제 개인적인 의견이기 때문에 변경 안하셔도 됩니다!

2020-05-13 16:02 UTC, developer-sungjae commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/data/source/local/room/MovieItem.kt
> +class MovieItem(
만들다가 삭제한 파일입니다. 반영을 시키려면 어떻게 해야하는지 알 수 있을까요?

2020-05-13 16:02 UTC, developer-sungjae commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/data/source/local/room/AppDataBase.kt
> +}
삭제한 파일입니다. 반영을 시키려면 어떻게 해야하는지 알 수 있을까요?

2020-05-13 16:04 UTC, developer-sungjae commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/data/source/remote/NaverRemoteDataSource.kt
> +}
삭제한 파일입니다.

2020-05-14 01:01 UTC, developer-sungjae commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/data/source/remote/NaverRemoteDataSourceImpl.kt
> +}
삭제하였습니다.
44a0227

2020-05-14 12:25 UTC, developer-sungjae commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/data/source/local/room/AppDataBase.kt
> +}
수정하였습니다.

2020-05-14 12:39 UTC, developer-sungjae commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/data/source/local/room/MovieRoomDataBase.kt
> +        fun getInstance(context: Context): MovieRoomDataBase? {
destroyInstance에서 null처리를 해야하기 때문에 nullable 하게 작성하였습니다.

2020-05-14 12:45 UTC, developer-sungjae commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/adapters/SearchAdapter.kt
> +    private val savedLocalList: MutableList<MovieLocal> = mutableListOf()
훨씬 가독성이 좋아질 것 같습니다. 참고하여 수정하였습니다.
감사합니다.
23beefe

2020-05-14 12:52 UTC, developer-sungjae commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/data/source/local/NaverMovieLocalDataSourceImpl.kt
> +                        arrList.addAll(it)
참고하겠습니다. 감사합니다.

2020-05-14 12:53 UTC, developer-sungjae commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/data/source/local/room/MovieRoomDataBase.kt
> +        fun destoryInstance() {
수정하였습니다. 감사합니다.
23beefe

2020-05-14 16:55 UTC, chuuuul commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/data/source/local/NaverMovieLocalDataSourceImpl.kt
> +                        arrList.addAll(it)
수정하다보니 Collection으로 받을필요가 없을 것 같아서 저는 List와 MutableList로 거의 통일을 했습니다.

2020-05-14 17:01 UTC, chuuuul commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/data/source/local/room/MovieItem.kt
> +class MovieItem(
방법을 찾으셨나요?
여러가지 방법있긴한데 안드로이드 스튜디오에서 해당파일 삭제후에 ctrl + k 누르셔서 커밋창 띄우시면 파일 삭제된 파일 커밋 할 수 있습니다. 
그 후에 ctrl + shift + k 로 푸쉬 올리시면 됩니다~

2020-05-14 17:12 UTC, chuuuul commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/data/source/local/room/MovieRoomDataBase.kt
> +        fun getInstance(context: Context): MovieRoomDataBase? {
코드안에서 null일경우 instance를 생성해주지 않나요?

```
private var db : MovieRoomDatabase? = null

fun getInstance(context: Context): MovieRoomDataBase { 
    ...
    return db as MovieRoomDataBase
}
```

을 생각했습니다. 안바꾸셔도 괜찮을 것 같습니다 ㅎㅎ

2020-05-15 03:33 UTC, developer-sungjae commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/data/source/local/NaverMovieLocalDataSourceImpl.kt
> +            }).start()
보장이 안되는 것 같습니다. 보장하는 방법 혹시 아신다면 알려주시면 감사하겠습니다.

2020-05-15 03:34 UTC, developer-sungjae commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/data/source/local/room/MovieRoomDataBase.kt
> +        fun getInstance(context: Context): MovieRoomDataBase? {
저렇게 쓸 수도 있군요 배웠습니다 감사합니다.

2020-05-15 13:06 UTC, developer-sungjae commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/data/repository/NaverMovieRepositoryImpl.kt
> +        naverMovieLocalDataSource.getMovieList(context,
adapter는 view도 아니고 model도 아닌 view와 model을 바인딩하는 클래스라 두개의 속성을 모두 가지고 있다고 아래의 자료에서 읽어서 위와 같이 작성하였습니다.
https://medium.com/@jsuch2362/adapter-%EB%88%84%EA%B5%AC%EB%83%90-%EB%84%8C-data-view-2db7eff11c20

하지만 View에서 구현하는게 좀 더 깔끔할 것 같아서 수정해보겠습니다.

2020-05-15 13:07 UTC, developer-sungjae commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/data/source/local/NaverMovieLocalDataSourceImpl.kt
> +                        arrList.addAll(it)
갑자기 왜 받을 필요가 없다고 생각하신지 여쭤봐도 될까요?

2020-05-15 17:04 UTC, developer-sungjae commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/data/source/remote/NaverMovieRemoteDataSourceImpl.kt
> +    @SuppressLint("CheckResult")
음.. 명확한 이유는 알지 못합니다. 현재 공부중입니다. 알려주시면 감사하겠습니다.

2020-05-16 05:02 UTC, developer-sungjae commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/data/repository/NaverMovieRepositoryImpl.kt
> +        naverMovieLocalDataSource.getMovieList(context,
수정하였습니다.
1923c0f
ae1c75f

2020-05-16 16:20 UTC, chuuuul commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/data/source/remote/NaverMovieRemoteDataSourceImpl.kt
> +    @SuppressLint("CheckResult")
제가 공부한지 얼마 안돼서 짧은 지식이지만 공유하겠습니다. 해당 어노테이션은 disposable 처리를 안해서 사용하는 것으로 보입니다.

일단 RxKotlin을 사용하시면 많은 유용한 확장 함수들을 사용 할 수 있습니다.
그 중 에 addTo()라는 메서드가 있습니다. disposable 객체를 CompositeDisposable이라는 주머니에 넣는 메서드입니다.

` private val compositeDisposable = CompositeDisposable() `
로 주머니를 만들고,

subscribe가 끝나면 주머니에 disposable을 객체를 넣습니다.

` Flowable.subscribe( ... ) 
 .addTo(compositeDisposable)`

여기까지, 주머니에 disposable을 넣었을뿐 clear()나 dispose()를 하지 않았습니다.
clear() 또는 dispose()하는 타이밍은 객체가 destroy 될 때 입니다.

Composite Disposable에 관해서 찾아보시면 해결 하실 수 있을 것 같습니다.

또한 Retrofit에서 가져오는데이터는 Flowable보다는 Single로 가져오는편이 더 보편적일 것 같습니다.

2020-05-16 17:26 UTC, chuuuul requested changes
로컬에 저장하는 부분이 동작하고 있지 않습니다.

2020-05-16 17:26 UTC, chuuuul commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/data/source/local/NaverMovieLocalDataSourceImpl.kt
> +        context: Context,
사용하지 않는 파라미터입니다.

2020-05-16 17:26 UTC, chuuuul commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/data/repository/NaverMovieRepositoryImpl.kt
> +    override lateinit var naverMovieRemoteDataSource: NaverMovieRemoteDataSource
이게 소스가 왜 자꾸 추적이 안되지 하고 있었는데, 변수 타입에 Interface를 하셨네요.
인터페이스가 아닌 Implement 된 클래스의 타입을 가져야 합니다.

2020-05-16 17:26 UTC, chuuuul commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/data/source/local/NaverMovieLocalDataSourceImpl.kt
> +        }).start()
해당 메서드는 사용되고 있지 않습니다. 로컬에 저장하는 부분이 전부 동작하고 있지 않습니다.
동작 확인 후 커밋 올려주시면 좋을 것 같습니다~

2020-05-16 17:28 UTC, chuuuul commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/data/source/local/NaverMovieLocalDataSourceImpl.kt
> +                        arrList.addAll(it)
코드 정리하다가 느낀건데 굳이 up casting으로 받을 필요가 없다고 생각했습니다.

2020-05-16 17:33 UTC, chuuuul commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/data/source/local/NaverMovieLocalDataSourceImpl.kt
> +            }).start()
고민해봤는데 Thread를 제거하시고

```
 Observable.fromIterable(data).doOnSubscribe {
    MovieRoomDataBase.getInstance(nContext)?.getMovieDAO()?.deleteAll()
}
.subscribe { ... }

```
처럼 doOnSubscribe 사용하면 subscribe전에 작업을 지시 할 수 있습니다.
이걸로 해결 될 것 같습니다

2020-05-16 17:43 UTC, chuuuul requested changes

2020-05-16 17:43 UTC, chuuuul commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/data/source/local/room/MovieLocal.kt
> +    @PrimaryKey var id: Long?,
`@PrimaryKey(autoGenerate = true) var id: Long` 으로 자동 생성하셔도 되는데
nullable로 하시고 id를 null로 생성하신 이유가 있나요?

2020-05-18 12:29 UTC, developer-sungjae commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/data/source/local/room/MovieLocal.kt
> +    @PrimaryKey var id: Long?,
오류가 나서 짜다보니 놓친 것 같습니다. 수정하였습니다. val로 안하는 이유는 I/O 둘다 관여하는 모델이기 때문입니다.

2020-05-18 12:31 UTC, developer-sungjae commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/data/source/local/NaverMovieLocalDataSourceImpl.kt
> +        }).start()
수정하였습니다.
a755846 bd4bf1b
[확인로그]
2020-05-18 21:26:52.161 19138-19138/com.project.architecturestudy D/Toast: show: focusDisplayId = 0, isFocusInDesktop = false mCustomDisplayId=-1
2020-05-18 21:26:52.203 19138-19352/com.project.architecturestudy D/bsjbsj: RoomDatabase Save Success com.project.architecturestudy.data.source.local.room.MovieLocal@bf89c50
2020-05-18 21:26:52.204 19138-19352/com.project.architecturestudy D/bsjbsj: RoomDatabase Save Success com.project.architecturestudy.data.source.local.room.MovieLocal@e5b1e49
2020-05-18 21:26:52.204 19138-19352/com.project.architecturestudy D/bsjbsj: RoomDatabase Save Success com.project.architecturestudy.data.source.local.room.MovieLocal@57c534e
2020-05-18 21:26:52.207 19138-19352/com.project.architecturestudy D/bsjbsj: RoomDatabase Save Success com.project.architecturestudy.data.source.local.room.MovieLocal@22e5605
2020-05-18 21:26:52.213 19138-19352/com.project.architecturestudy D/bsjbsj: RoomDatabase Save Success com.project.architecturestudy.data.source.local.room.MovieLocal@963a568
2020-05-18 21:26:52.217 19138-19352/com.project.architecturestudy D/bsjbsj: RoomDatabase Save Success com.project.architecturestudy.data.source.local.room.MovieLocal@bb87a67
2020-05-18 21:26:52.221 19138-19352/com.project.architecturestudy D/bsjbsj: RoomDatabase Save Success com.project.architecturestudy.data.source.local.room.MovieLocal@2d3b980
2020-05-18 21:26:52.224 19138-19352/com.project.architecturestudy D/bsjbsj: RoomDatabase Save Success com.project.architecturestudy.data.source.local.room.MovieLocal@6704f5f
2020-05-18 21:26:52.227 19138-19352/com.project.architecturestudy D/bsjbsj: RoomDatabase Save Success com.project.architecturestudy.data.source.local.room.MovieLocal@974827b
2020-05-18 21:26:52.227 19138-19352/com.project.architecturestudy D/bsjbsj: RoomDatabase Save Success com.project.architecturestudy.data.source.local.room.MovieLocal@c7f3898
2020-05-18 21:26:52.338 19138-19138/com.project.architecturestudy D/ViewRootImpl@ad4f2e9[Toast]: setView = android.widget.LinearLayout@3ef2f96 TM=true MM=false
2020-05-18 21:26:52.338 19138-19138/com.project.architecturestudy D/bsjbsj: RoomDatabase GetData Success : com.project.architecturestudy.data.source.local.room.MovieLocal@7e49b6e
2020-05-18 21:26:52.338 19138-19138/com.project.architecturestudy D/bsjbsj: RoomDatabase GetData Success : com.project.architecturestudy.data.source.local.room.MovieLocal@8c5e20f
2020-05-18 21:26:52.338 19138-19138/com.project.architecturestudy D/bsjbsj: RoomDatabase GetData Success : com.project.architecturestudy.data.source.local.room.MovieLocal@dbc029c
2020-05-18 21:26:52.338 19138-19138/com.project.architecturestudy D/bsjbsj: RoomDatabase GetData Success : com.project.architecturestudy.data.source.local.room.MovieLocal@280d4a5
2020-05-18 21:26:52.339 19138-19138/com.project.architecturestudy D/bsjbsj: RoomDatabase GetData Success : com.project.architecturestudy.data.source.local.room.MovieLocal@e43007a
2020-05-18 21:26:52.339 19138-19138/com.project.architecturestudy D/bsjbsj: RoomDatabase GetData Success : com.project.architecturestudy.data.source.local.room.MovieLocal@508902b
2020-05-18 21:26:52.339 19138-19138/com.project.architecturestudy D/bsjbsj: RoomDatabase GetData Success : com.project.architecturestudy.data.source.local.room.MovieLocal@cd4ac88
be821a0

2020-05-18 12:31 UTC, developer-sungjae commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/data/repository/NaverMovieRepositoryImpl.kt
> +    override lateinit var naverMovieRemoteDataSource: NaverMovieRemoteDataSource
아.. 놓쳤었네요 감사합니다. 수정하였습니다.

2020-05-18 12:34 UTC, developer-sungjae commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/data/source/local/NaverMovieLocalDataSourceImpl.kt
> +        context: Context,
수정하였습니다
fc0e380

2020-05-18 12:35 UTC, developer-sungjae commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/data/source/local/NaverMovieLocalDataSourceImpl.kt
> +            }).start()
오.. 삽질했었는데 감사합니다. 수정하였습니다.

2020-05-18 12:44 UTC, developer-sungjae commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/data/source/local/NaverMovieLocalDataSourceImpl.kt
> +            }).start()
doOnSubscribe는 observable이 구독될때 doOnUnSubscribe는 구독이 해지될때 호출되는 콜백함수로군요. 한수 배웠습니다. 그런데 Schedulers.io전에 선언하면 save failure가 뜨네요.
원인은 자세히는 모르겠지만 아무튼 덕분에 수정하였습니다!

2020-05-18 12:54 UTC, developer-sungjae commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/data/source/remote/NaverMovieRemoteDataSourceImpl.kt
> +    @SuppressLint("CheckResult")
메모리 릭에 방지에 대한 방법이 3가지가 있네요.
수정하였습니다.
f363d58
(참고 : https://beomseok95.tistory.com/60)

2020-05-18 13:11 UTC, developer-sungjae commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/data/source/remote/NaverMovieRemoteDataSourceImpl.kt
> +    @SuppressLint("CheckResult")
> 또한 Retrofit에서 가져오는데이터는 Flowable보다는 Single로 가져오는편이 더 보편적일 것 같습니다.

2020-05-19 00:05 UTC, chuuuul commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/activities/MainActivity.kt
> +    private val naverMovieRepositoryImpl = NaverMovieRepositoryImpl
마지막으로 여쭤보고 싶은게 있는데, Object로 선언한 클래스를  객체로 생성하신 이유가 있나요?

2020-05-19 05:30 UTC, developer-sungjae commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/activities/MainActivity.kt
> +    private val naverMovieRepositoryImpl = NaverMovieRepositoryImpl
음.. 단순 카멜케이스때문에 그랬는데 삭제하는게 좋을 것 같습니다.
감사합니다. 수정하였습니다.
9f893e4

2020-05-19 13:00 UTC, chuuuul approved these changes
수고하셨습니다!

2020-05-19 16:43 UTC, sjjeong requested changes

2020-05-19 16:43 UTC, sjjeong commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/activities/MainActivity.kt
> +    private var adapter: SearchAdapter = SearchAdapter()
val로 변경해주세요

2020-05-19 16:43 UTC, sjjeong commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/activities/MainActivity.kt
> +        super.onDestroy()
super.onDestroy()는 맨 마지막에 호출해주세요

2020-05-19 16:43 UTC, sjjeong commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/data/repository/NaverMovieRepository.kt
> +        Failure: (Throwable) -> Unit
파라미터 인자는 소문자로 시작해주세요

2020-05-19 16:43 UTC, sjjeong commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/data/repository/NaverMovieRepositoryImpl.kt
> +    override lateinit var context: Context
context를 가지고 있다면 나중에 없어진 인자에 접근 할 수도 있습니다.
context를 가지고 있지 않도록 해주세요

2020-05-19 16:43 UTC, sjjeong commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/data/repository/NaverMovieRepositoryImpl.kt
> +        naverMovieRemoteDataSource: NaverMovieRemoteDataSourceImpl
두개는 생성자를 통해서 받도록 해주시고 interface 타입으로 받도록 해주세요

2020-05-19 16:43 UTC, sjjeong commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/data/source/local/room/MovieItemDAO.kt
> +interface MovieItemDAO {
DAO -> Dao 로 변경해주세요

2020-05-19 16:43 UTC, sjjeong commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/data/source/local/room/MovieRoomDataBase.kt
> +        }
이 함수가 어떤 이유로 필요하고 사용하나요?

2020-05-19 16:43 UTC, sjjeong commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/data/source/remote/NaverMovieRemoteDataSourceImpl.kt
> +            service.getMovies(keyWord)
rx를 사용한다면 여기서 subscribe하지 않고 Single을 리턴해서 Activity쪽에서 subscribe해주면 됩니다.

2020-05-19 16:43 UTC, sjjeong commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/activities/MainActivity.kt
> +                    NaverMovieRepositoryImpl.saveMovieListToLocal(items)
저장하는 함수를 호출하는 것은 repository쪽에서 해주세요

2020-05-19 16:43 UTC, sjjeong commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/adapters/SearchAdapter.kt
> +    private val localSearchList: MutableList<MovieLocal> = mutableListOf()
두개로 나눠서 관리하지 않고 한개로 관리하도록 변경해주세요

2020-05-20 03:10 UTC, chuuuul commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/data/repository/NaverMovieRepositoryImpl.kt
> +        naverMovieRemoteDataSource: NaverMovieRemoteDataSourceImpl
죄송합니다. 제가 interface 타입말고 impl로 받으라고 잘못 리뷰해드렸네요..
다형성 생각해서 interface로 받아야 하는 것 같습니다..

2020-05-22 14:11 UTC, developer-sungjae commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/activities/MainActivity.kt
> +    private var adapter: SearchAdapter = SearchAdapter()
수정하였습니다.
b7cce35

2020-05-22 14:11 UTC, developer-sungjae commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/activities/MainActivity.kt
> +        super.onDestroy()
수정하였습니다.
23f2677

2020-05-22 14:11 UTC, developer-sungjae commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/data/repository/NaverMovieRepository.kt
> +        Failure: (Throwable) -> Unit
수정하였습니다.
7d1b05c

2020-05-22 14:12 UTC, developer-sungjae commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/data/source/local/room/MovieItemDAO.kt
> +interface MovieItemDAO {
수정하였습니다.
c0b2a6e

2020-05-22 14:13 UTC, developer-sungjae commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/data/source/local/room/MovieRoomDataBase.kt
> +        }
MovieRoomDataBase가 null이면 instance를 얻어 database를 선언하고
생명주기에 맞추어서 null로 다시 메모리를 해제하려고 할 생각이었습니다!

2020-05-22 14:25 UTC, developer-sungjae commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/data/repository/NaverMovieRepositoryImpl.kt
> +        naverMovieRemoteDataSource: NaverMovieRemoteDataSourceImpl
수정하였습니다.
db8d739
a071bab

2020-05-22 14:26 UTC, developer-sungjae commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/data/repository/NaverMovieRepositoryImpl.kt
> +    override lateinit var context: Context
그렇군요..! 감사합니다. 수정하였습니다.
2cd428b

2020-05-22 14:26 UTC, developer-sungjae commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/data/source/remote/NaverMovieRemoteDataSourceImpl.kt
> +            service.getMovies(keyWord)
시도해보겠습니다.

2020-05-22 14:36 UTC, developer-sungjae commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/activities/MainActivity.kt
> +                    NaverMovieRepositoryImpl.saveMovieListToLocal(items)
수정하였습니다.
8f682b4
2913f3a

2020-05-22 16:12 UTC, developer-sungjae commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/adapters/SearchAdapter.kt
> +    private val localSearchList: MutableList<MovieLocal> = mutableListOf()
수정하였습니다.
1cfb55b
070408b

2020-05-23 11:29 UTC, developer-sungjae commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/data/source/local/room/MovieRoomDataBase.kt
> +        }
싱글톤이라 null이 필요없는 것 같습니다.
수정하였습니다.
822fbfe

2020-05-23 11:31 UTC, developer-sungjae commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/data/source/remote/NaverMovieRemoteDataSourceImpl.kt
> +            service.getMovies(keyWord)
수정하였습니다.
e57bf9d
58d0782

2020-05-23 11:34 UTC, developer-sungjae commented
추가적으로 간단한 질문드리고 싶은게 있는데
edee18d 해당커밋에서 isNullOrEmpty하면 if문 안을 안탑니다.
null 또는 빈값이 아닌데 안타져서 isNotEmpty로 고쳤는데 왜 안타는지 혹시 이유 아시면 설명좀 부탁드리겠습니다.
감사합니다.

2020-05-23 14:45 UTC, sjjeong commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/data/repository/NaverMovieRepository.kt
> +        Failure: (t: Throwable) -> Unit
Success나 Failure가 파라미터 이기 때문에 소문자로 시작해야합니다.

2020-05-23 14:45 UTC, sjjeong commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/data/repository/NaverMovieRepositoryImpl.kt
> +    override lateinit var context: Context
이렇게만 바꾸면 나중에 이 커밋으로 빌드하면 에러가 발생합니다.
커밋을 작업단위로 나눠서 해주세요

2020-05-23 15:30 UTC, sjjeong requested changes

2020-05-23 15:30 UTC, sjjeong commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/data/repository/NaverMovieRepositoryImpl.kt
> +            }
failure에 다른 동작이 없다면 기존처럼 해주시면 됩니다.

2020-05-23 21:33 UTC, developer-sungjae commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/data/repository/NaverMovieRepository.kt
> +        Failure: (t: Throwable) -> Unit
수정하였습니다.
82fa89c
ed5002c
2f95991

2020-05-23 21:34 UTC, developer-sungjae commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/data/repository/NaverMovieRepositoryImpl.kt
> +            }
굳이 failure 처리는 activity에서 진행하기 때문에 RemoteData쪽에서 실패했을 때 콜백을 삭제 하였습니다.
46e4cd3

2020-05-23 21:39 UTC, developer-sungjae commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/data/repository/NaverMovieRepositoryImpl.kt
> +    override lateinit var context: Context
단순 파일단위가 아닌 빌드가 가능한 범위에서 작업단위로 하라는 말씀이신지요?

2020-05-24 04:58 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-05-24 04:59 UTC, merged