HW-2 Model 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #635
Opened 2020-05-13 01:36 UTC by sangjinKIM93

HW-2 Model 적용하기

1. Repository 구조 적용 : Repository, source(remote, local), model
2. Repository에서 local cache 적용

*RemoteDataSource :  Retrofit2 사용
*LocalDataSource : Room 사용
*RxJava 추가(RoomDB 접근시 사용)

2020-05-18 10:20 UTC, RyuC0605 requested changes
안녕하세요. 류승윤 입니다.
즐거운 한주 보내셨는지요? 
그럼 리뷰 시작 하겠습니다.

Context 는 전역변수로 두지 않는 것이 좋은데 MovieListAdapter 에 그런 코드가 있네요.
그리고 같은 클래스의 onBindViewHolder 함수의 holder.containerView.tag = getItemId(position)
코드는 왜 존재하는지 알려주시겠어요?

동작이슈 
검색어에 "너나다" 를 입력하면 검색 결과가 있는데, 검색결과가 없다고 토스트메시지가 나오네요.

2020-05-18 10:20 UTC, RyuC0605 commented on 2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/data/source/local/MovieDao.kt
> +    fun getAllMovies() : List<Movie>
SELECT * 보다 사용하는 컬럼만 셀렉트 하는것이 여러모로 좋습니다.

2020-05-18 10:20 UTC, RyuC0605 commented on 2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/data/source/local/MovieDao.kt
> +    fun selectMovies(query: String): Single<List<Movie>>
역시 SELECT * 사용은 지양하는게 좋습니다.

2020-05-19 01:53 UTC, sangjinKIM93 commented on 2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/data/source/local/MovieDao.kt
> +    fun getAllMovies() : List<Movie>
e718052
특정 칼럼만 선택하여 select 해보았는데 다음과 같은 에러가 발생하였습니다.

The columns returned by the query does not have the fields [movieId,subtitle,pubDate,director,actor,userRating] in com.sangjin.newproject.data.model.Movie even though they are annotated as non-null or primitive. Columns returned by the query

관련 내용을 찾아보니 room에서는 movie객체를 return하기 위해서는 movie data class에 선언된 모든 column들이 select문에 포함되어야 하는 것 같습니다. 
그래서 movie data class에서 불필요한 column을 삭제하는 방식으로 수정하였는데 혹시 더 좋은 생각 있으시다면 추가적으로 반영하겠습니다!

2020-05-19 01:53 UTC, sangjinKIM93 commented on 2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/data/source/local/MovieDao.kt
> +    fun selectMovies(query: String): Single<List<Movie>>
위와 동일합니다.

2020-05-19 01:59 UTC, sangjinKIM93 commented
안녕하세요 승윤님
이번에도 좋은 리뷰 감사합니다:)


925f25a
1. tag는 지난번 수정때 미처 삭제를 못하였네요. 삭제하였습니다.

2. context는 glide때문에 전역으로 설정하였었는데 viewholder의 context를 직접 받는 방식으로 수정하였습니다.


cb64d9a
3. Toast 메시지 에러는 local cache에서 자료가 없을때  onSuccess콜백으로 넘어와서 생기는 에러였습니다.  local에서 select한 결과가 NullOrEmpty일 경우 onSuccess 콜백이 넘어가지 않도록 예외처리하였습니다.

2020-05-20 05:49 UTC, sangjinKIM93 commented
추가적인 변경사항입니다.

1. 기존 캐시 방식(검색시 local에 자료가 있을 경우 불러오는 구조)이 부적절한 것 같아. 앱 초기 화면에 최근 검색한 자료를 불러오는 데 local cache를 활용하는 것으로 변경하였습니다.

2. disposable 처리를 위해 기존 DataSource에서 subscribe()하던 것을 activity에서 subscribe 하도록 변경하였습니다.

2020-05-20 14:24 UTC, RyuC0605 commented on 2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/data/source/local/MovieDao.kt
> +    fun getAllMovies() : List<Movie>
사용하지 않는 컬럼을 만들어서 얻는 이득이 있을까요?

2020-05-20 14:26 UTC, RyuC0605 approved these changes

2020-05-20 14:51 UTC, sjjeong requested changes
model layer 구현은 잘 하셨네요

2020-05-20 14:51 UTC, sjjeong commented on 2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/data/repository/NaverMoviesRepositoryImpl.kt
> +    private val localDataSourceImpl: LocalDataSourceImpl
타입은 interface 형태로 변경해주세요

2020-05-20 14:51 UTC, sjjeong commented on 2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/data/source/local/LocalDataSourceImpl.kt
> +    private val roomDB = room
생성자 쪽에 선언해주면 됩니다.

2020-05-20 14:51 UTC, sjjeong commented on 2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/data/source/local/RoomDB.kt
> +abstract class RoomDB : RoomDatabase(){
클래스명을 RoomDb로 변경해주세요

2020-05-21 00:53 UTC, sangjinKIM93 commented on 2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/data/source/local/MovieDao.kt
> +    fun getAllMovies() : List<Movie>
그렇죠 필요한 칼럼만 사용하는게 좋은 것 같습니다:)

2020-05-21 01:46 UTC, sangjinKIM93 commented on 2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/data/source/local/LocalDataSourceImpl.kt
> +    private val roomDB = room
54a072e
감사합니다. 수정했습니다.

2020-05-21 01:46 UTC, sangjinKIM93 commented on 2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/data/source/local/RoomDB.kt
> +abstract class RoomDB : RoomDatabase(){
fc2a7f5

수정했습니다:)

2020-05-21 01:51 UTC, sangjinKIM93 commented on 2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/data/repository/NaverMoviesRepositoryImpl.kt
> +    private val localDataSourceImpl: LocalDataSourceImpl
c71a0e7

수정했습니다.

이렇게 타입을 바꿈으로써 얻는 장점이 뭔지 고민해봤는데 잘 모르겠네요 ㅠ
interface로 받는 것과 Impl로 받는 것에 어떤 차이점이 있는지 알려주실 수 있나요??

2020-05-21 14:44 UTC, sjjeong commented on 2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/data/repository/NaverMoviesRepositoryImpl.kt
> +    private val localDataSourceImpl: LocalDataSourceImpl
보통 interface를 사용하는 이유는 다형성을 위해서 입니다.
하지만 여기서 사용하는 것은 추후 모듈화 때 사용하기 위해서 입니다.

2020-05-21 14:44 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-05-22 00:42 UTC, sangjinKIM93 commented on 2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/data/repository/NaverMoviesRepositoryImpl.kt
> +    private val localDataSourceImpl: LocalDataSourceImpl
presenter 계층이 추가되었을때를 위해서 사용한다는 말씀이신가요??

2020-05-25 01:57 UTC, merged