2005/hwaniiidev hw2
sjjeong/GoogryAndroidArchitecutreStudy pull request #636
Opened 2020-05-13 14:10 UTC by hwaniiidev

현재 remote 쪽만 구현되어 있습니다. 
추가적으로 Local 부분도 구현할 예정입니다.

2020-05-18 08:08 UTC, LeeChungWoo92 requested changes

2020-05-18 08:08 UTC, LeeChungWoo92 commented on 2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/MainActivity.kt
> +        }
안녕하세요~ 영화검색 후 검색어 변경하여 입력했을때 데이터가 변경이 안되는것같습니다. 
확인부탁드릴게요!

2020-05-18 23:45 UTC, hwaniiidev commented on 2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/MainActivity.kt
> +        }
59b6316
수정했습니다~~

2020-05-19 05:20 UTC, LeeChungWoo92 requested changes

2020-05-19 05:20 UTC, LeeChungWoo92 commented on 2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/MainActivity.kt
> +        toast("네트워크에 연결할 수 없습니다. 네트워크 연결을 확인해주세요.")
onFailure 함수에 파라미터가 필요없는것같습니다.

2020-05-19 05:20 UTC, LeeChungWoo92 commented on 2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/MainActivity.kt
> +        toast("다시 시도해주세요.")
onError함수에 파라미터가 필요없는것같습니다.

2020-05-20 00:34 UTC, hwaniiidev commented on 2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/MainActivity.kt
> +        toast("다시 시도해주세요.")
ccd668c
해당 부분은 우선 Log처리 했습니다.
감사합니다

2020-05-20 00:34 UTC, hwaniiidev commented on 2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/MainActivity.kt
> +        toast("네트워크에 연결할 수 없습니다. 네트워크 연결을 확인해주세요.")
ccd668c
해당 부분은 우선 Log처리 했습니다.
감사합니다

2020-05-20 23:59 UTC, LeeChungWoo92 approved these changes

2020-05-21 15:32 UTC, sjjeong requested changes

2020-05-21 15:32 UTC, sjjeong commented on 2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/MainActivity.kt
> +                                )
로컬에 저장하는 부분을 repository 쪽에서 처리하도록 해주세요

2020-05-21 15:32 UTC, sjjeong commented on 2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/data/source/local/NaverMovieLocalDataSourceImpl.kt
> +        moviesDB = MoviesDB.getInstance(context)
context를 전달 받지 않고 NaverMovieLocalDataSourceImpl을 만들 때 생성자로 MoviesDB를 만들어서 넘겨주는게 좋습니다.

2020-05-21 15:32 UTC, sjjeong commented on 2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/data/source/remote/NaverMovieRemoteDataSourceImpl.kt
> +    }
companion object는 클래스 내부에 맨 아래에 위치해야 합니다

2020-05-21 15:32 UTC, sjjeong commented on 2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/model/ResponseMovieSearchData.kt
> +    val items: ArrayList<Item>,
ArrayList로 변경한 이유가 있나요?

2020-05-21 15:32 UTC, sjjeong commented on 2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/data/source/local/MoviesDB.kt
> +    }
이 함수가 어떤 이유로 필요하고 사용하나요?

2020-05-24 01:50 UTC, hwaniiidev commented on 2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/data/source/local/NaverMovieLocalDataSourceImpl.kt
> +        moviesDB = MoviesDB.getInstance(context)
34a4519
수정했습니다. 
함수 인자값으로 컨텍스트를 넘겨준 이유는 
1. 함수로 생성되는 변수들을 함수가 끝난 후 모두 휘발되니 생성자로 받았을 때 보다 메모리 소비가 적지 않을까하는 생각.
2. 혹여 생성자로 받은 context가 MainActivity가 종료되어 발생시킬 수 있는 에러를 조금이라도 줄여줄 수 있지 않을까 하는 생각

이러합니다.

2020-05-24 01:51 UTC, hwaniiidev commented on 2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/MainActivity.kt
> +                                )
78e082a
수정했습니다
로컬에 저장하는 기능은 View 보단 Model에서 하는게 맞겠네요

2020-05-24 01:51 UTC, hwaniiidev commented on 2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/data/source/remote/NaverMovieRemoteDataSourceImpl.kt
> +    }
6dfb454
수정했습니다!

2020-05-24 01:55 UTC, hwaniiidev commented on 2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/model/ResponseMovieSearchData.kt
> +    val items: ArrayList<Item>,
이미 Local DB에 저장되어 있는 영화 데이터는 중복하여 저장할 필요가 없어 중복 데이터를 체크하고 제거하는 로직이 필요했습니다. 이 때 listIterator를 사용했는데 List에는 remove함수가 없고 ArrayList에는 remove함수가 있어 변경하였습니다. 

더 좋은 방법들이 있겠지만 제가 당장 구현할 수 있는 방법으로 하다보니 ArrayList로 변경하게 되었습니다

2020-05-24 01:57 UTC, hwaniiidev commented on 2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/data/source/local/MoviesDB.kt
> +    }
SQLite를 사용할 때 생성했던 DB객체를 close해주지 않으면 메모리 소모도 있고 기타 에러도 발생하던 경험이 있어 위 함수가 close 역할을 해준다고 생각하여 사용했습니다

2020-05-24 16:46 UTC, sjjeong requested changes

2020-05-24 16:46 UTC, sjjeong commented on 2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/data/repository/NaverMovieRepositoryImpl.kt
> +                cachingMovies(query,response.items)
local에 저장만해서 화면에 아무 결과가 나오지 않습니다.

2020-05-24 16:46 UTC, sjjeong commented on 2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/data/source/local/MoviesDB.kt
> +    }
싱글턴 형태로 만들어서 사용해도 되기 때문에 null로 만들어 줄 필요가 없습니다.

2020-05-24 16:46 UTC, sjjeong commented on 2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/data/source/local/NaverMovieLocalDataSourceImpl.kt
> +            }
서버에서 받아오는 데이터가 최신 데이터이기 때문에 filter 로직 없이 덮어씌우기 하시면 됩니다.

2020-05-24 22:48 UTC, hwaniiidev commented on 2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/data/source/local/MoviesDB.kt
> +    }
c58fd9c
해당 부분 삭제했습니다
싱글턴 형태로 만들어서 사용해도 된다는 말이 정확히 이해가 안되는데 Dao class를 싱글턴 형태로 만들어도 된다는 말인가요 ??

2020-05-24 23:52 UTC, hwaniiidev commented on 2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/data/source/local/NaverMovieLocalDataSourceImpl.kt
> +            }
덮어쓰기를 위해 @Insert(onConflict = OnConflictStrategy.REPLACE) 를 했습니다
근데 덮어쓰기가 PrimaryKey를 기준으로 중복을 체크하지 않나요 ?? 
primarykey를 어떤 칼럼에 적용해야할지 잘 모르겠더라고요. title에 해도 겹치는 tilte이 있어서 온전히 저장이 안되는 경우가 있더라고요. 

그래서 id 칼럼을 추가하고 autoincreament를 했더니 id값이 겹치지가 않아서 덮어씌어지지 않고 누적되어 저장되더라고요. 
이를 막기위해 id값을 제가 직접 추가해줘야 할까요?

2020-05-25 03:14 UTC, sjjeong commented on 2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/data/source/local/NaverMovieLocalDataSourceImpl.kt
> +            }
지금 query 기준으로 데이터를 저정하고 가져오기 때문에 아마 여기서는 PrimaryKey가 query가 될 것 같네요

2020-05-25 14:05 UTC, hwaniiidev commented on 2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/data/source/local/NaverMovieLocalDataSourceImpl.kt
> +            }
query를 PrimaryKey로 하게 될 경우도 1개의 영화 정보가 저장되는 순간 나머지 같은 query의 영화정보들은 저장할 수 없게 됩니다.

2020-05-25 14:09 UTC, hwaniiidev commented on 2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/data/repository/NaverMovieRepositoryImpl.kt
> +                cachingMovies(query,response.items)
혹시 local에서 저장된 데이터를 화면에 출력하는 건 HW-3 과제에 이어서 하는건 안될까요?

2020-05-25 14:30 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-05-25 21:24 UTC, merged