HW-2  Model  적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #638
Opened 2020-05-14 06:05 UTC by LeeChungWoo92

아직 완벽하게 이해를 못한것같아서 local 쪽은  추가로 작업하겠습니다.

2020-05-19 23:57 UTC, hwaniiidev commented on 2005/leechungwoo92/StudyForkProject/app/src/main/java/com/lllccww/studyforkproject/view/activity/MainActivity.kt
> +                    Toast.makeText(this@MainActivity, "검색 결과가 없습니다.", Toast.LENGTH_SHORT).show()
람다? 식으로 하니 훨씬 간결하네요. 
근데 로직이 길어지거나 복잡해지면 람다식이 훨씬 읽기 어려운 코드가 되는건 아닐지 의문이 들긴 합니다 .

2020-05-20 14:55 UTC, sjjeong requested changes

2020-05-20 14:55 UTC, sjjeong commented on 2005/leechungwoo92/StudyForkProject/app/src/main/java/com/lllccww/studyforkproject/data/repository/NaverMovieRepositoryImpl.kt
> +class NaverMovieRepositoryImpl(private val movieRepositoryImpl: MovieRemoteDataSourceImpl) : NaverMovieRepository {
type은 interface 형태로 변경해주세요

2020-05-20 14:55 UTC, sjjeong commented on 2005/leechungwoo92/StudyForkProject/app/src/main/java/com/lllccww/studyforkproject/data/source/remote/MovieRemoteDataSourceImpl.kt
> +                    onSuccess(movieItems!!)
onResponse로 온 것이지 success인게 100% 보장되지 않습니다.
response.isSuccessful인지 비교하는 코드도 추가해주면 좀더 안전 합니다.

2020-05-20 14:55 UTC, sjjeong commented on 2005/leechungwoo92/StudyForkProject/app/src/main/java/com/lllccww/studyforkproject/view/activity/MainActivity.kt
> +                    Toast.makeText(this@MainActivity, "검색 결과가 없습니다.", Toast.LENGTH_SHORT).show()
간단한 로직이 들어가면 좋겠지만 코드가 길어진다면 함수로 빼는 방법도 있습니다.

2020-05-22 02:04 UTC, LeeChungWoo92 commented on 2005/leechungwoo92/StudyForkProject/app/src/main/java/com/lllccww/studyforkproject/data/source/remote/MovieRemoteDataSourceImpl.kt
> +                    onSuccess(movieItems!!)
감사합니다 수정했습니다!!
54c3a1c

2020-05-22 02:04 UTC, LeeChungWoo92 commented on 2005/leechungwoo92/StudyForkProject/app/src/main/java/com/lllccww/studyforkproject/view/activity/MainActivity.kt
> +                    Toast.makeText(this@MainActivity, "검색 결과가 없습니다.", Toast.LENGTH_SHORT).show()
감사합니다 수정했습니다 !! 
0df5cc5

2020-05-22 02:06 UTC, LeeChungWoo92 commented on 2005/leechungwoo92/StudyForkProject/app/src/main/java/com/lllccww/studyforkproject/data/repository/NaverMovieRepositoryImpl.kt
> +class NaverMovieRepositoryImpl(private val movieRepositoryImpl: MovieRemoteDataSourceImpl) : NaverMovieRepository {
interface로 변경시 생성자를 사용못하는데 저 생성자부분을 어떤식으로 
처리해야 하는게 좋을까요 ???

2020-05-23 03:00 UTC, sjjeong commented on 2005/leechungwoo92/StudyForkProject/app/src/main/java/com/lllccww/studyforkproject/data/repository/NaverMovieRepositoryImpl.kt
> +class NaverMovieRepositoryImpl(private val movieRepositoryImpl: MovieRemoteDataSourceImpl) : NaverMovieRepository {
제가 설명을 자세하게 안했네요
MovieRepositoryImpl type대신 MovieRepository 형태로 받으시면 됩니다.

2020-05-23 06:33 UTC, LeeChungWoo92 commented on 2005/leechungwoo92/StudyForkProject/app/src/main/java/com/lllccww/studyforkproject/data/repository/NaverMovieRepositoryImpl.kt
> +class NaverMovieRepositoryImpl(private val movieRepositoryImpl: MovieRemoteDataSourceImpl) : NaverMovieRepository {
5158a00
수정하긴햇는데 
이부분을 말씀하시는건지 아직이해를 하지 못했습니다 ㅠㅠ

2020-05-23 09:14 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-05-25 01:54 UTC, hwaniiidev approved these changes

2020-05-25 01:55 UTC, merged