HW-5 MVVM pattern
sjjeong/GoogryAndroidArchitecutreStudy pull request #639
Opened 2020-05-15 13:10 UTC by jesterz91

리뷰 요청드립니다. 
일이 많아서 과제제출이 늦어졌습니다.

2020-05-15 16:30 UTC, Kyudong3 approved these changes
GOOD! 멘토님 리뷰 부탁드리겠습니다!

2020-05-15 16:30 UTC, Kyudong3 commented on 2004/jesterz91/app/src/main/java/io/github/jesterz91/study/presentation/ui/MovieSearchViewModel.kt
> +        get() = _movieSearchResult
_movieSearchResult 앞에 언더스코어를 붙인 이유가 따로 있나요?! 
아래 backPressSubject는 Observable과 Subject로 변수명을 나누었는데 이 코드는 왜 그런지 궁금합니다!

2020-05-15 16:30 UTC, Kyudong3 commented on 2004/jesterz91/app/src/main/res/layout/activity_movie_search.xml
> +            name="vm"
vm 변수가 현재는 사용되지 않고 있는 것 같지만 mvvm 패턴에서는 기본적으로 사용되지 않아도 넣어주는 것이 일반적인가요?!

2020-05-16 01:13 UTC, jesterz91 commented on 2004/jesterz91/app/src/main/res/layout/activity_movie_search.xml
> +            name="vm"
이 변수는 데이터 바인딩을 사용하기 위해 선언 하였는데, 
Rx로 코드를 작성하다보니 활용하지 못한 것 같습니다.

2020-05-16 01:17 UTC, jesterz91 commented on 2004/jesterz91/app/src/main/java/io/github/jesterz91/study/presentation/ui/MovieSearchViewModel.kt
> +        get() = _movieSearchResult
하나의 변수로 사용하였다가.
내부에서 사용 될 변수와 외부에서 사용될 변수를 나누기 위해
_ 로 구분하여 나누게 되었습니다. 
이 부분은 제가 일관성 없게 명명한것 같네요

2020-05-16 04:10 UTC, sjjeong requested changes

2020-05-16 04:10 UTC, sjjeong commented on 2004/jesterz91/app/src/main/java/io/github/jesterz91/study/presentation/ui/MovieSearchViewModel.kt
> +        get() = _movieSearchResult
@Kyudong3 
내부와 외부에 타입을 다르게 하기위해서 보통 이렇게 많이 사용합니다.

2020-05-16 04:10 UTC, sjjeong commented on 2004/jesterz91/app/src/main/java/io/github/jesterz91/study/presentation/ui/MovieSearchActivity.kt
> +            }.addTo(disposables)
이 로직은 ViewModel에서 하도록 해주세요
ViewModel이 List를 가지고 있고 그것을 View에서 바라보고 있어서 List가 갱신되면 View를 갱신하도록 해주세요

2020-05-16 06:42 UTC, merged