HW-2 MVP 패턴 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #64
Opened 2019-06-17 14:32 UTC by sport0102

2019-06-20 19:34 UTC, brooks-o reviewed
저녁에 추가적으로 리뷰하도록 하겠습니다. :)
고생하셨습니다!!

2019-06-20 19:34 UTC, machine-human commented on sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/data/source/UpbitRepository.kt
> +            UpbitRemoteDataSource: UpbitDataSource
저도 todoapp 소스 기반으로 위 함수를 선언 하였지만 사용을 못 했는데,
적절하게 잘 사용하신거 같습니다 :)

2019-06-22 02:11 UTC, brooks-o submitted a review, later dismissed
고생하셨습니다!!

2019-06-24 07:57 UTC, machine-human commented
스터디장님께서의 피드백을 꼼꼼히 적용시키신 거 같습니다.
위 두 가지만 확인 해주시면 approve 진행하도록 하겠습니다.
고생하셨습니다 :)

2019-06-27 10:22 UTC, machine-human commented
확인 했습니다.

위 두가지 수정 사항과 추가적으로 RemoteDataSource에서 Throwable를 받지 않는것으로 보이는데,
이 부분까지 수정 부탁 드립니다 :)

2019-06-27 10:44 UTC, sport0102 commented
위 두가지 수정사항이라는게 어떤 수정사항인지 안나와서 그러는데 어떤건가요?

2019-06-27 10:48 UTC, machine-human commented
TickerListAdapter.kt의

어뎁터의 ArrayList를 -> MutableList,
인자의 ArrayList를 -> List 와

setData() 함수의
tickerList.run{
clear()
addAll()
}
로 변경 입니다 :)

2019-06-27 16:06 UTC, sport0102 commented
> TickerListAdapter.kt의
> 
> 어뎁터의 ArrayList를 -> MutableList,
> 인자의 ArrayList를 -> List 와
> 
> setData() 함수의
> tickerList.run{
> clear()
> addAll()
> }
> 로 변경 입니다 :)

수정하였습니다!
85f323ce8c2c092907a8e2e535fe18bb7fab0d0b
a0f7b213137de572fbb347596a2dc75c8809897e

2019-06-27 16:12 UTC, machine-human commented
확인 완료 했습니다.

f4100c7 같은 경우 object 클래스를 이론적으로는 알고 있으나 언제 사용하는지 적합한지 판단이 안되서 멘토님의 피드백이 필요할거 같습니다.

고생하셨습니다. :)

2019-06-27 16:13 UTC, brooks-o submitted a review, later dismissed

2019-06-27 16:13 UTC, brooks-o commented on sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/ui/main/TickerListAdapter.kt
질문 있습니다 :) 인자값 뿐만 아니라 Adapter에서 선언해주는 ArrayList도 List로 변경해주는거 아닌가용?

-> 
위 질문 수정합니다.
어뎁터의 ArrayList를 -> MutableList,
인자의 ArrayList를 -> List로 였습니다. :)

2019-06-27 16:13 UTC, brooks-o commented on sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/ui/main/TickerListAdapter.kt
>      }
tickerList.run{
clear()
addAll()
}
형태로 정리 가능합니다 :)

2019-06-28 04:37 UTC, sjjeong requested changes
고생하셨습니다!

2019-06-28 04:37 UTC, sjjeong commented on sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/ui/main/MainFragment.kt
> +            } ?: ""
?: "" 은 사용되지 않는 코드인것 같은데 어떤 이유로 넣으셨나요?

2019-06-28 04:37 UTC, sjjeong commented on sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/ui/main/MainPagerAdapter.kt
> +        else -> getFragmentByMarketName(Market.USDT.marketName)
3번 케이스까지 추가한다음
else에서는 에러 처리 하면될 것 같습니다.

2019-06-28 04:37 UTC, sjjeong commented on sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/ui/main/MainPresenter.kt
> +    override fun loadTickerList(marketList: ArrayList<MarketResponse>) {
marketList 내부가 변경되지 않는것 같아서 ArrayList보단 List로 써주시면 좋을 것 같아요.
ArrayList를 써야한다면 이유 남겨주세요

2019-06-28 04:37 UTC, sjjeong commented on sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/ui/main/MainPresenter.kt
> +    private fun modifyTickerList(tickerList: List<TickerResponse>): List<TickerModel> {
List를 받아서 List를 리턴하는것보다
```kotlin
mainView.shoTickerList(tickerList.map(::modifyTickerList))
```
로 처리해보세요.
이러면 함수명도 변경될수도 있구요

2019-06-28 04:37 UTC, sjjeong commented on sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/ui/main/TickerListAdapter.kt
> +    private var tickerList = mutableListOf<TickerModel>()
var보다 val을 사용해주세요

2019-06-28 17:16 UTC, sport0102 commented on sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/ui/main/MainFragment.kt
> +            } ?: ""
혹시나 marketName이 안들어올까 하는 마음에 넣었는데 그럴일이 없을 것 같습니다! 삭제하였습니
d27ceb9

2019-06-28 17:17 UTC, sport0102 commented on sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/ui/main/MainPagerAdapter.kt
> +        else -> getFragmentByMarketName(Market.USDT.marketName)
수정하였습니다 
8b3bd08

2019-06-28 17:17 UTC, sport0102 commented on sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/ui/main/MainPresenter.kt
> +    override fun loadTickerList(marketList: ArrayList<MarketResponse>) {
제가 잘못 사용하였습니다
a8702b6

2019-06-28 17:17 UTC, sport0102 commented on sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/ui/main/MainPresenter.kt
> +    private fun modifyTickerList(tickerList: List<TickerResponse>): List<TickerModel> {
처음사용해보았는데 매우 좋은 기능인것 같습니다!
739e6ad

2019-06-28 17:18 UTC, sport0102 commented on sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/ui/main/TickerListAdapter.kt
> +    private var tickerList = mutableListOf<TickerModel>()
주의하겠습니다! 
67a79a0

2019-06-28 17:19 UTC, sport0102 commented on sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/ui/main/TickerListAdapter.kt
수정하였습니다!

2019-06-28 17:19 UTC, sport0102 commented on sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/ui/main/TickerListAdapter.kt
>      }
수정하였습니다!

2019-06-29 00:16 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-06-29 02:13 UTC, brooks-o approved these changes

2019-06-29 02:14 UTC, merged