HW-6 apply Lifecycle & AAC ViewModel
sjjeong/GoogryAndroidArchitecutreStudy pull request #640
Opened 2020-05-17 04:08 UTC by TaeseongYun

2020-05-22 05:17 UTC, ghost approved these changes
새로 추가하신 LiveData와 ViewModel 코드에서는 크게 리뷰해드릴게 없는듯 합니다.
setValue와 postValue에 대한 차이를 잘 배워봐야겠네용
Rx파트는 멘토님에게 부탁드리겠습니다.

ㅡㅡㅡㅡ
실수로 approve를 눌렀네요 혹시 되돌리는 방법이 있나요?

2020-05-22 05:17 UTC, ghost commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ext/SingleLiveData.kt
> +        return if (_isPending)
{ }를 추가해주세요

2020-05-22 05:17 UTC, invitejay commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ui/MainActivity.kt
> +        viewModel.movieList.observe(this, Observer {
현재는 onclick 되었을 때 네트워크 통신을 통해 데이터가 바뀌기 때문에 따로 adapter를 다시 notifiedDataChange를 해주는 기능은 없어도 될 거 같습니다
아니면 어떤 용도로 사용하기 위해 작성해주셨나용?

2020-05-22 05:17 UTC, invitejay commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ui/viewmodel/MainViewModel.kt
> +        _movieList.value = emptyList()
onClearList의 기능과 좀 겹치는듯 합니다.
둘 중 하나만 남겨놓고 adapter의 list를 clear해주는 것은 어떨까요?

2020-05-22 15:52 UTC, TaeseongYun commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ext/SingleLiveData.kt
> +        return if (_isPending)
수정했습니다.

313373d

2020-05-22 16:57 UTC, TaeseongYun commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ui/viewmodel/MainViewModel.kt
> +        _movieList.value = emptyList()
수정했습니다.

7b173ea

2020-05-22 16:59 UTC, invitejay commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ui/MainActivity.kt
> +        viewModel.movieList.observe(this, Observer {
태성님 이 부분은 제가 다시보니 잘못 리뷰한듯 하네요.
저 같은 경우 clear, addAll, notifyDataChanged를 하나의 method에 넣어놨기 때문에 그걸 기준으로 생각을 했네요.. 죄송합니다ㅠㅠ

2020-05-22 17:02 UTC, TaeseongYun commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ui/MainActivity.kt
> +        viewModel.movieList.observe(this, Observer {
네 괜찮습니다. 혹시 바쁘지 않으시다면 제꺼 리뷰를 다시 부탁드려도 될까요 
제가 실수로 커밋을 잘못넣어서 컨플릭트가 나버렸습니다 ㅠㅠ

2020-05-22 17:04 UTC, invitejay commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ui/MainActivity.kt
> +        viewModel.movieList.observe(this, Observer {
넵 커밋 되돌리시고 다시 푸시하실건가요?

2020-05-22 17:21 UTC, ghost requested changes

2020-05-22 17:21 UTC, invitejay commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ui/viewmodel/MainViewModel.kt
> +                            if (_movieList.value?.containsAll(this) == true) {
containsAll()은 boolean을 반환하기 때문에 == true는 제거해주셔도 좋을거 같습니다

2020-05-22 17:27 UTC, TaeseongYun commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ui/viewmodel/MainViewModel.kt
> +                            if (_movieList.value?.containsAll(this) == true) {
MutableList 의 value 가 nullable 하기 때문에 containsAll 이 true일 때 까지 비교해주어야 실행이 제대로 돌아갑니다.

2020-05-22 17:28 UTC, invitejay commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ui/viewmodel/MainViewModel.kt
> +                            if (_movieList.value?.containsAll(this) == true) {
아 그렇군요 ! 제가 nullable 한 부분을 고려하지 못했네요..

2020-05-22 17:29 UTC, ghost approved these changes
Rx파트는 멘토님에게 부탁드리겠습니다
고생하셨습니다 !

2020-05-23 03:20 UTC, sjjeong requested changes

2020-05-23 03:20 UTC, sjjeong commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ext/SingleLiveData.kt
> +        private set
private set인데 내부에서 set이 되는 코드가 없어서 true로 변경되지는 않을 것 같네요
isPending이 필요한 경우가 있나요?

2020-05-23 03:20 UTC, sjjeong commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ui/MainActivity.kt
> +                    ResourceProviderImpl(this@MainActivity),
MainActivity context를 넣으면 안됩니다.
AAC ViewModel은 Activity가 재생성이 되더라도 ViewModel은 유지되기 때문에 메모리 릭이 발생할 수 있습니다.
ApplicationContext를 전달하도록 해주세요

2020-05-23 03:20 UTC, sjjeong commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ui/viewmodel/MainViewModel.kt
> +    lateinit var onClearList: () -> Unit
위에 isLoading처럼 LiveData 형태로 만들어 주시고 Activity에서 observe하는 형태로 변경해주세요

2020-05-23 03:20 UTC, sjjeong commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ui/viewmodel/MainViewModel.kt
> +                .doOnTerminate { _isLoading.event = false }
doAfterTerminate로 변경해주세요

2020-05-23 03:32 UTC, TaeseongYun commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ui/MainActivity.kt
> +                    ResourceProviderImpl(this@MainActivity),
수정했습니다.

cfb29dd

한 가지 질문이 있는데,
위에 말씀하신것처럼 액티비티 context를 넘겨주게되면 AAC ViewModel onCleared 가 호출 되는 시기는  onDestroy가 호출 된 후 호출되는걸로 알고 있는데 액티비티의 context를 넘겨주게 되면 중첩으로 context가 쌓이는 케이스가 생기기 때문인가요?

2020-05-23 03:38 UTC, TaeseongYun commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ext/SingleLiveData.kt
> +        private set
제가 isPedind을 true로 처리해주는 로직을 작성하지 않았네요
수정하였습니다.

fdf4656

2020-05-23 03:40 UTC, TaeseongYun commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ui/viewmodel/MainViewModel.kt
> +                .doOnTerminate { _isLoading.event = false }
수정하였습니다.

4cf8c50

2020-05-23 03:45 UTC, TaeseongYun commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ui/viewmodel/MainViewModel.kt
> +    lateinit var onClearList: () -> Unit
변수명이 oldQuery로 오해 하실만한 변수명으로 작성하였는데
제가 원했던건 네트워크 통신 후 MutableLiveData에 저장되어있는 이전 결과값과 리스폰스 결과값이 다르면 oldQuery라는 서브젝트에 onNext로 이전 결과값을 클리어 시켜주는 동작을 원해서 다음과같은 로직은 구현했는데
AAC ViewModel 취지와 맞지않은 걸까요?

2020-05-23 09:31 UTC, sjjeong commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ui/MainActivity.kt
> +                    ResourceProviderImpl(this@MainActivity),
@TaeseongYun 
화면 회전했을 때 Activity가 재생성이 되더라도 AAC ViewModel은 유지되기 때문에 이미 사라진 context에 접근해서 앱이 비정상 종료 될 수 있습니다.

2020-05-23 09:40 UTC, sjjeong commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ext/SingleLiveData.kt
> +            _isPending = true
true로 한다면 언제 다시 false로 바꿔주나요?

2020-05-23 09:40 UTC, sjjeong commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ui/viewmodel/MainViewModel.kt
> +    lateinit var onClearList: () -> Unit
현재 구현은 AAC ViewModel과 관련없이 단순하게 onClearList 함수를 호출 하는 것 뿐입니다.
LiveData의 사용하지 않을 이유는 없어보입니다.

2020-05-23 17:12 UTC, TaeseongYun commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ext/SingleLiveData.kt
> +            _isPending = true
옵저브를 할 때마다 새롭게 _isPeding을 할당해 주는것 인지 알았습니다.
수정하였습니다.

51c7b92

2020-05-23 17:18 UTC, TaeseongYun commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ui/viewmodel/MainViewModel.kt
> +    lateinit var onClearList: () -> Unit
수정하였습니다.

06e2c6a

2020-05-24 11:59 UTC, TaeseongYun commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ui/viewmodel/MainViewModel.kt
> +    lateinit var onClearList: () -> Unit
onClearList를 LiveData형식으로 구현하다가 결과값 없을 때  _movieList 라이브데이터 처리 로직이 빠져서 추가 커밋을 했습니다.

65da063

2020-05-24 16:59 UTC, sjjeong requested changes

2020-05-24 16:59 UTC, sjjeong commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ext/SingleLiveData.kt
> +            _isPending = true
이렇게 변경하면 한번은 무조건 null이 나오는 로직 아닌가요?

2020-05-25 02:21 UTC, TaeseongYun commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ext/SingleLiveData.kt
> +            _isPending = true
네 제가 이해한 싱글 라이브데이터는 한번은 null을 던져줌으로서 
`화면 회전이 발생 했을 때 저장 되어있는 데이터가 중복으로 옵저버 되지않도록 한다.`
이렇게 이해했는데 잘못 이해한 것 일까요?

아직 코드변경은 하지 않았습니다.

2020-05-25 03:13 UTC, sjjeong commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ext/SingleLiveData.kt
> +            _isPending = true
@TaeseongYun 
화면 회전뿐만 아니라 데이터를 여러번 넣으면 홀수번째에만 데이터가 정상적으로 나오고 짝수번째에는 무조건 null이 나올 것 같습니다.
직접 실행해본건 아니지만 태성님이 실행했을 때 정상적으로 동작했나요?

2020-05-25 03:57 UTC, TaeseongYun commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ext/SingleLiveData.kt
> +            _isPending = true
@sjjeong 
네 디버깅 찍으며 확인해본결과 doOnSubcribe때와 doAfterTerminate때 각각 event값(MutableSingleLiveData)을 변경해주기 때문에 데이터 넣은 요청 짝수 번 홀수 번에 관계없이 true와 false가 번갈아 찍히는것을 확인하였습니다.

2020-05-25 04:34 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-05-25 05:19 UTC, merged