HW-2 Model 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #642
Opened 2020-05-18 09:47 UTC by RyuC0605

네이버 영화 검색에 레퍼지토리 패턴 적용

2020-05-19 12:22 UTC, sangjinKIM93 commented on 2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/MainActivity.kt
adapter의 movielist를 퍼블릭으로 접근하고 있는데 이 경우 다른 객체에 의해 data가 변경될 수 있는 위험이  있다고 알고 있습니다. 변수를 private으로 설정하고 변수에 접근할 수 있는 메서드를 만들어서 접근할 수 있게 하는 것도 좋을 것 같습니다.

2020-05-19 12:22 UTC, sangjinKIM93 commented on 2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/MainActivity.kt
>                  val adt = lv_contents.adapter as MovieAdapter
private val adt = MovieAdapter() 처럼 전역 변수로 선언 후 사용하는 것이 아니라 위와 같이 adapter를 가져와서 사용하시는데 개인적으로는 전역 변수로 선언 후 사용하는 것이 추가적인 변수 선언이 필요 없어  코드가 조금 더 깔끔해질 수 있는 것 같습니다.
아니면 위와 같이 사용하시는 다른 이유가 있으신지 궁금합니다!

2020-05-20 14:18 UTC, RyuC0605 commented on 2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/MainActivity.kt
수정했습니다.

da460acf24a790a66f29e37213bbac8f7d4d4e07

2020-05-20 14:23 UTC, RyuC0605 commented on 2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/MainActivity.kt
>                  val adt = lv_contents.adapter as MovieAdapter
전역변수는 MainActivity가 GC 에 수집될때 까지 메모리에 상주하기 떄문에 
스코프를 벗어나면 정리되는 지역변수를 선호하고 있습니다.

2020-05-21 00:35 UTC, sangjinKIM93 commented on 2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/MainActivity.kt
>                  val adt = lv_contents.adapter as MovieAdapter
그런 뜻이 담겨있는지는 몰랐네요 ㅎㅎ 알겠습니다!

2020-05-21 00:35 UTC, sangjinKIM93 commented on 2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/MainActivity.kt
>                  val adt = lv_contents.adapter as MovieAdapter
그런 뜻이 담겨있는지 몰랐네요 ㅎㅎ 알겠습니다!

2020-05-21 01:10 UTC, sangjinKIM93 approved these changes

2020-05-21 15:43 UTC, sjjeong requested changes

2020-05-21 15:43 UTC, sjjeong commented on 2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/MainActivity.kt
> +        val repository: MovieRepositoryImpl = MovieRepositoryImpl()
onClick이 될 때 마다 MovieRepositoryImpl()를 만들지 않고 MainActivity의 property로 선언해서 사용해주세요 

MovieRepositoryImpl, NaverRemoteDataSourceImpl 여기에서도 함수를 호출 할 때마다 인스턴스를 만들지 않도록 변경해주세요

2020-05-21 15:43 UTC, sjjeong commented on 2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/MainActivity.kt
>                  val adt = lv_contents.adapter as MovieAdapter
RecyclerView가 Adapter를 가지고 있기 때문에 MainActivity가 destory 되기 전까지는 메모리에 상주하고 있습니다.
자주 사용한다면 property로 가지고 있어도 좋습니다.

2020-05-23 11:56 UTC, RyuC0605 commented on 2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/MainActivity.kt
>                  val adt = lv_contents.adapter as MovieAdapter
프로퍼티 선언과 생성을 같이 하면 메인액티비티 객체 생성 시 메모리에 올라가게 됩니다.
선언만 해놓고 널체크 코드를 넣으려니 코드가 더 지저분 해지는 느낌인데 이럴때 좋은 방법이 있을런지요?

2020-05-23 11:57 UTC, RyuC0605 commented on 2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/MainActivity.kt
> +        val repository: MovieRepositoryImpl = MovieRepositoryImpl()
수정하였습니다.

e353853afa12afda830f7292dc3375dbc13cb4bd

2020-05-25 03:17 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-05-25 03:17 UTC, merged