2005/developer sungjae hw 3
sjjeong/GoogryAndroidArchitecutreStudy pull request #645
Opened 2020-05-24 10:57 UTC by developer-sungjae

* Interface Contract 생성
* Contract 안에 Interface View, Presenter 선언
* 각 클래스에 구체적인 구현
* Adapter는 setAdapter 때문인지 Presenter내에서는 인식이 불가하여 Activity에서 구현
* Context 의존성을 없애기 위해서 Presenter에 Context 주입하지 않음

2020-05-26 08:40 UTC, chuuuul approved these changes
수고하셨습니다!
깔끔하게 잘 작성하신 것 같아서 리뷰드릴게 없네요!

2020-05-26 08:40 UTC, chuuuul commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/ui/search/SearchActivity.kt
> +        adapter.setRemoteMovieData(item)
adapter.setLocalMovieData와 adapter.setRemoteMovieData를 나눌 필요가 없을 것 같습니다.
View 또는 Adapter의 입장에서 가져온 데이터가 Local Data인지 Remote Data인지 구분할 필요가 없을 것 같습니다.
각각 다른 분기를 탈 것을 염두하시고 유지보수 용도로 작성하신거라면 그냥 두셔도 될 것 같습니다!

2020-05-26 09:00 UTC, developer-sungjae commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/ui/search/SearchActivity.kt
> +        adapter.setRemoteMovieData(item)
좋은 의견이라 개인적으로 다른 브랜치로 한번 작성해보겠습니다.

2020-05-26 09:18 UTC, chuuuul commented
추가적으로 개인적인 의견을 코멘트 드립니다!


1. 제가 블루프린트 MVP 예제를 봤는데 view쪽에서는 메서드 명에 set이라는 단어가 들어가질 않더라구요. TextView에 내용을 변경하는것도 set 대신 show를 사용해서 
``` fun showTitle() ``` 
등으로 사용하더라구요.
그래서 저도 setMovieList 대신 showMovieList로 변경했습니다. ㅎㅎ

2. Toast로 메세지 보여주는 메서드 명을
``` 
fun showSearchWordIsEmpty() 
fun showLocalDataSuccess()
```
등등 으로 작성하셨는데, 개인적인 의견으로는 message등 메세지 관련 단어가 들어가서 
"메세지를 보여주는 메서드구나" 를 명시하면 가독성에 좋을 것 같습니다~

ex)
```fun showMessageEmptyKeyword()``` 또는 ```fun showEmptyKeywordMessage()```

2020-05-26 09:19 UTC, developer-sungjae commented
> 추가적으로 개인적인 의견을 코멘트 드립니다!
> 
> 1. 제가 블루프린트 MVP 예제를 봤는데 view쪽에서는 메서드 명에 set이라는 단어가 들어가질 않더라구요. TextView에 내용을 변경하는것도 set 대신 show를 사용해서
>    `fun showTitle()`
>    등으로 사용하더라구요.
>    그래서 저도 setMovieList 대신 showMovieList로 변경했습니다. ㅎㅎ
> 2. Toast로 메세지 보여주는 메서드 명을
> 
> ```
> fun showSearchWordIsEmpty() 
> fun showLocalDataSuccess()
> ```
> 
> 등등 으로 작성하셨는데, 개인적인 의견으로는 message등 메세지 관련 단어가 들어가서
> "메세지를 보여주는 메서드구나" 를 명시하면 가독성에 좋을 것 같습니다~
> 
> ex)
> `fun showMessageEmptyKeyword()` 또는 `fun showEmptyKeywordMessage()`

수정해보겠습니다!

2020-05-27 15:55 UTC, sjjeong requested changes

2020-05-27 15:55 UTC, sjjeong commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/ui/search/SearchContract.kt
> +        fun showRemoteMovieData(item: List<MovieItem>)
두개가 결국은 List<MovieItem>을 전달하고 내부 로직도 동일하기 때문에 함수를 하나로 처리해도 됩니다.
Adapter도 함수를 하나로 합쳐주세요

2020-05-27 15:55 UTC, sjjeong commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/ui/search/SearchActivity.kt
> +            presenter.validateSearchWord(searchText)
view입장에서는 validateSearchWord보다 getMovieListFromRemote가 더 적절해 보입니다.
getMovieListFromRemote를 호출하고 getMovieListFromRemote함수 내부에서 validate하게 해주세요

2020-05-28 11:42 UTC, developer-sungjae commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/ui/search/SearchContract.kt
> +        fun showRemoteMovieData(item: List<MovieItem>)
수정하였습니다.
5c9ab25

2020-05-28 11:43 UTC, developer-sungjae commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/ui/search/SearchActivity.kt
> +            presenter.validateSearchWord(searchText)
그러네요 뷰 입장에 너무 많은 것을 알고 있었네요. 비즈니스 로직이 들어간 메서드보다는 직관적인 메서드 명으로 바꾸는게 훨씬 낫네요.
메서드 명 또한 주의해서 작성해야할 것 같습니다.
감사합니다. 수정하였습니다.
aefbb80

2020-05-28 12:10 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-05-28 23:40 UTC, merged