HW-3 MVP 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #646
Opened 2020-05-24 18:00 UTC by RyuC0605

안녕하세요. 류승윤 입니다. 
기존 영화 검색 예제에 MVP 적용 코드를 올리오니, 검토 부탁 드립니다.

2020-05-25 03:18 UTC, sjjeong commented
> 안녕하세요. 류승윤 입니다.
> 기존 영화 검색 예제에 MVP 적용 코드를 올리오니, 검토 부탁 드립니다.
> 뭐가 꼬였는지 과제2번 커밋 로그가 같이 올라와 있네요.
> "gradle 버전 업" [2e89b1e](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/commit/2e89b1e58fae7dfb21ca9a8a8af9ba09bced1443) 이전 커밋은 무시하셔도 됩니다.
> 
> 감사합니다.

2번째 과제를 merge를 안해서 이전 커밋로그가 같이 올라왔었네요
제가 2번째 과제 머지해서 현재 pr에 반영되도록 변경했습니다~
@sangjinKIM93 님도 참고해주세요

2020-05-26 06:39 UTC, sangjinKIM93 reviewed
안녕하세요 승윤님 :)

주말 잘 보내셨나요?
2주 단위로 리뷰 하다가 1주 단위로 하려니 뭔가 시간이 빠른 느낌이네요 ㅎㅎ

리뷰 시작하겠습니다.

2020-05-26 07:00 UTC, sangjinKIM93 commented on 2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/main/PresenterImpl.kt
> +        repository = repository ?: MovieRepositoryImpl()
repository = repository 는 불필요한 코드 같은데 따로 넣어주신 이유가 있나요?

2020-05-26 07:00 UTC, sangjinKIM93 commented on 2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/main/PresenterImpl.kt
> +
setView를 통해서 Contractor.view를 생성하셨는데 class presenter(private view : Contractor.View) 와 같이 매개변수로 받아서 생성하는 것에 대해서는 어떻게 생각하시나요?
개인적으로는 setView로 하면 깜빡하고 presenter.setView를 해주지 않았을 경우 null이 되는 위험성이 있고 코드도 조금 늘어나는 단점이 있어 후자가 더 괜찮은 방법 같다고 생각합니다.
위와 같은 방법으로 Contractor.View를 생성하신 이유가 있으실 것 같은데 그 이유가 궁금합니다!

2020-05-26 07:00 UTC, sangjinKIM93 commented on 2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/main/PresenterImpl.kt
> +
이거는 개인적으로 궁금한 부분인데요
if ~ else 를 쓰는 것보다 위와 같이 구현하는 것이 성능(속도)상으로 더 이점이 있나요?

2020-05-26 07:00 UTC, sangjinKIM93 commented on 2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/main/MainActivity.kt
> +
lateinit var를 사용하면 null 선언없이 사용 가능합니다.

2020-05-26 07:00 UTC, sangjinKIM93 commented on 2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/main/MainActivity.kt
> +
adt = parent.adapter as MovieAdapter 로 하지 않고 위와 같이 adt ?: 를 넣어주신 특별한 이유가 있나요?

2020-05-27 04:46 UTC, RyuC0605 commented on 2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/main/PresenterImpl.kt
> +        repository = repository ?: MovieRepositoryImpl()
복사/붙여넣기 실수였습니다. 
수정되었습니다.

51c2e65a682c2d6a07e2a9eca453d46606470b31

2020-05-27 04:47 UTC, RyuC0605 commented on 2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/main/PresenterImpl.kt
> +
생성자에 넣는다는 생각을 못했네요. 좋은 아이디어인거 같습니다.

5d9c617d3d9371c01c85cb58dc710827621b8831

2020-05-27 04:48 UTC, RyuC0605 commented on 2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/main/PresenterImpl.kt
> +
개인 취향이고, 성능면에선 차이가 없는걸로 알고 있습니다.
굳이 성능을 고려한다면 if 문에 더 많이 들어오는 케이스를 집어넣고 else 부분을 작성하면 성능면에선 더 낫다고 알고 있습니다.

2020-05-27 04:50 UTC, RyuC0605 commented on 2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/main/MainActivity.kt
> +
생성자에서 adt 를 받도록 수정하였습니다.

559a0a19d976f61053d93dc48e88727e4e81eb92

2020-05-27 04:50 UTC, RyuC0605 commented on 2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/main/MainActivity.kt
> +
생성자에서 adt 를 받도록 수정하였습니다.

559a0a19d976f61053d93dc48e88727e4e81eb92

2020-05-27 07:09 UTC, sangjinKIM93 commented on 2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/main/PresenterImpl.kt
> +
그렇군요. 답변감사합니다!

2020-05-27 07:13 UTC, sangjinKIM93 commented
LGTM 👍

2020-05-27 12:59 UTC, sangjinKIM93 approved these changes

2020-05-27 16:04 UTC, sjjeong requested changes

2020-05-27 16:04 UTC, sjjeong commented on 2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/main/Contractor.kt
> +interface Contractor {
이름은 Contract로 해주시고 어떤 화면에서 사용되는지 앞에 접미사를 추가해주세요
MainActivity에서 사용한다면 MainContract로 해주세요

2020-05-27 16:04 UTC, sjjeong commented on 2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/main/PresenterImpl.kt
> +class PresenterImpl(private val view: Contractor.View) : Contractor.Presenter {
이름은 MainPresenter로 해주세요

2020-05-27 16:04 UTC, sjjeong commented on 2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/main/MainActivity.kt
> +        hideKeyPad()
hideKeyPad는 searchData에서 validation 검사를 마치고 나서 showProgress()를 호출할 때 같이 호출하도록 해주세요
유저 입장에서 검색어가 비어있는데 키보드가 내려가면 다시 키보드를 올려야 하는 불편함이 있습니다.

2020-05-27 16:04 UTC, sjjeong commented on 2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/main/PresenterImpl.kt
> +
문제가 되는 예외 케이스를 먼저 처리하고 정상동작을 마지막에 하는 것이 좋은 condition 검사 패턴입니다.
저렇게 하는게 좋은 코드를 만드는 방법입니다.

2020-05-28 03:26 UTC, RyuC0605 commented on 2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/main/Contractor.kt
> +interface Contractor {
인터페이스 및 구현 클래스 이름 변경하였습니다

824b749388fda43649dff53001aaf7c67ff85e63

2020-05-28 03:26 UTC, RyuC0605 commented on 2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/main/PresenterImpl.kt
> +class PresenterImpl(private val view: Contractor.View) : Contractor.Presenter {
인터페이스 및 구현 클래스 이름 변경하였습니다

824b749388fda43649dff53001aaf7c67ff85e63

2020-05-28 03:27 UTC, RyuC0605 commented on 2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/main/MainActivity.kt
> +        hideKeyPad()
"검색결과가 없습니다" 화면을 보여주고 싶은 맘에 키패드를 내렸는데 욕심이 화를 불렀군요.
사용자 입장에선 더 불편하다 생각되어 수정하였습니다.

b910138f7071f237942423451e4fc14312743992

2020-05-28 12:11 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-05-28 22:38 UTC, merged