HW-6 apply LiveData & AAC viewModel
sjjeong/GoogryAndroidArchitecutreStudy pull request #647
Opened 2020-05-25 15:36 UTC by Kyudong3

2020-05-27 17:59 UTC, ios-byungjoon-lee requested changes
리뷰 남깁니다.

2020-05-27 17:59 UTC, jesterz91 commented on 2004/kyudong3/app/build.gradle
> +    implementation "androidx.lifecycle:lifecycle-extensions:2.2.0"
lifecycle-extensions 는 deprecated 되었습니다.
[Lifecycle  |  Android Developers](https://developer.android.com/jetpack/androidx/releases/lifecycle)

2020-05-27 17:59 UTC, jesterz91 commented on 2004/kyudong3/app/src/main/java/com/example/kyudong3/viewModel/MainViewModel.kt
> +    }
추가로 하는 작업이 없다면 override 하지 않아도 될것 같습니다.

2020-05-27 17:59 UTC, jesterz91 commented on 2004/kyudong3/app/src/main/java/com/example/kyudong3/ui/MainActivity.kt
> +        toast(message)
이미 확장함수로 toast() 가 정의 되어있는 상태에서
showToast()를 불필요하게 정의한 것 같습니다.

2020-05-27 17:59 UTC, jesterz91 commented on 2004/kyudong3/app/src/main/java/com/example/kyudong3/ui/MainActivity.kt
> +    }
하나의 LiveData<String> 변수를 observe 하도록 변경해도 될 것 같습니다.

2020-05-29 12:08 UTC, Kyudong3 commented on 2004/kyudong3/app/src/main/java/com/example/kyudong3/ui/MainActivity.kt
> +    }
수정했습니다!
37834be

2020-05-29 12:08 UTC, Kyudong3 commented on 2004/kyudong3/app/src/main/java/com/example/kyudong3/ui/MainActivity.kt
> +        toast(message)
수정했습니다!
37834be

2020-05-29 12:08 UTC, Kyudong3 commented on 2004/kyudong3/app/src/main/java/com/example/kyudong3/viewModel/MainViewModel.kt
> +    }
수정했습니다!
37834be

2020-05-29 12:08 UTC, Kyudong3 commented on 2004/kyudong3/app/build.gradle
> +    implementation "androidx.lifecycle:lifecycle-extensions:2.2.0"
수정했습니다!
37834be

2020-05-29 12:08 UTC, Kyudong3 commented
리뷰 수정하였습니다

2020-05-29 13:33 UTC, ios-byungjoon-lee approved these changes
👍

2020-05-29 15:07 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-05-29 15:19 UTC, merged