HW-3 MVP 패턴
sjjeong/GoogryAndroidArchitecutreStudy pull request #649
Opened 2020-05-26 05:06 UTC by sangjinKIM93

MVP 패턴 구현

1. Contract에서 interface로 요구사항을 정의(View와 Presenter로 나눠서)
2. View interface는 MovieListActivity에서 구현
3. Presenter interface는 MovieListPresenter에서 구현
    - presenter는 view와 repository를 생성자로 받아 이 둘에 접근할 수 있다.

*MovieListActivity를 적절한 커밋 단위로 쪼개는 것을 실패했습니다... MovieListActivity는 그냥 코드 파일로 보시는게 더 편하실 것 같습니다!

2020-05-26 07:02 UTC, developer-sungjae commented on 2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/MovieListPresenter.kt
> +    private val disposables = CompositeDisposable()
안녕하세요 질문 드리고 싶은게 있는데 혹시 disposables 일부러 복수형으로 하신건가요~?

2020-05-26 07:18 UTC, sangjinKIM93 commented on 2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/MovieListPresenter.kt
> +    private val disposables = CompositeDisposable()
CompositeDisposable이 disposable 묶음이라고 해서 disposables라고 했습니다.
생각해보니 compositeDisposable 로 가는게 좀 더 명확할 것 같네요. 리뷰 감사합니다!

2020-05-26 07:22 UTC, developer-sungjae commented on 2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/MovieListPresenter.kt
> +    private val disposables = CompositeDisposable()
답은 없고 그냥 의견이 궁금했습니다..!

2020-05-26 07:24 UTC, developer-sungjae commented on 2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/MovieListPresenter.kt
> +    }
dispose가 아닌 clear하시는 이유가 있나요?

2020-05-26 08:10 UTC, sangjinKIM93 commented on 2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/MovieListPresenter.kt
> +    }
생각 없이 쓴 부분인데 정확히 집어주셨네요 👀 
관련해서 찾아보니 
dispose()는 메서드 호출시 compositeDisposable이 resource에서 사라지고
clear()는 compositDisposable 안에 있는 disposable 들만 사라질뿐 compositeDisposable이 resource에서 사라지지는 않는 것 같네요.
즉, 해당 클래스의 재활용이 빈번한 경우 .clear()를 사용하는 것이 유용할 것 같습니다. 

하지만 해당 presenter의 경우 재활용되지 않으니 destroy될때 dispose로 깔끔하게 없애주는 것이 좋을 것 같다는 생각이 드네요.

성재님 의견도 궁금합니다!

2020-05-26 08:13 UTC, developer-sungjae commented on 2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/MovieListPresenter.kt
> +    }
저는 어차피 또 생성하는 로직이 들어가므로 dispose로 구현하였습니다.
두개가 있고 차이가 있는 것을 아시는지 해서 여쭤봤습니다. 
고생하세요!

2020-05-26 08:20 UTC, sangjinKIM93 commented on 2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/MovieListPresenter.kt
> +    }
좋은 피드백 감사합니다 :)

2020-05-27 04:23 UTC, RyuC0605 reviewed
안녕하세요. 류승윤 입니다. 말씀하신 것 처럼 한주가 빠르게 느껴 지네요.
리뷰에 남긴것 외에 번외로 영화 제목에 검색어는 볼드처리가 되지 않는건 취향이라 그렇게 바꾸신건 가요?

2020-05-27 04:23 UTC, RyuC0605 commented on 2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/MovieListActivity.kt
> +        Toast.makeText(this@MovieListActivity, R.string.no_movie_list, Toast.LENGTH_SHORT).show()
showMovieList(), noResult() 두 함수에 중복코드로  movieListAdapter.addList() 가 들어가 있는데
movieListAdapter.addList() 를 P 에서 한번만 해줄 수 있게 V의 함수로 빼는건 어떠신지요?

그렇게 수정해서 noResult 에는 Toast 만 뿌리는게 함수명에 더 맞는것 같습니다.

2020-05-27 04:23 UTC, RyuC0605 commented on 2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/MovieListActivity.kt
> +        movieListAdapter.addList(movies as ArrayList<Movie>)
movieListAdapter.addList() 의 받는 인자값을 ArrayList 가 아닌 List 로 받으면 불필요 캐스팅이 줄어들 것 같습니다.

2020-05-27 08:11 UTC, sangjinKIM93 commented on 2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/MovieListActivity.kt
> +        Toast.makeText(this@MovieListActivity, R.string.no_movie_list, Toast.LENGTH_SHORT).show()
0a9734b 
81e89d4

좋은 생각인 것 같네요. 수정했습니다!

2020-05-27 08:11 UTC, sangjinKIM93 commented on 2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/MovieListActivity.kt
> +        movieListAdapter.addList(movies as ArrayList<Movie>)
8977ba6

수정했습니다. 감사합니다:)

2020-05-27 08:18 UTC, sangjinKIM93 commented
spanned를 써야하는 이유를 몰랐었는데 검색어만 bold 처리가 되는 장점이 있었군요. 
수정했습니다!

18625b7 1b344a8

2020-05-28 03:12 UTC, RyuC0605 approved these changes

2020-05-28 16:16 UTC, sjjeong requested changes

2020-05-28 16:16 UTC, sjjeong commented on 2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/MovieListPresenter.kt
> +            view.refreshMovieList(movies)
movies가 비어있지 않으면 view.refreshMovieList를 두번 호출합니다.

2020-05-28 16:16 UTC, sjjeong commented on 2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/adapter/MovieListAdapter.kt
> +    fun addList(movieListFromActivity : List<Movie>){
함수가 하는 역할이 addList보단 resetList에 가깝네요
함수명을 변경해주세요

2020-05-29 02:55 UTC, sangjinKIM93 commented on 2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/MovieListPresenter.kt
> +            view.refreshMovieList(movies)
acba2af
수정했습니다. 감사합니다!

2020-05-29 02:57 UTC, sangjinKIM93 commented on 2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/adapter/MovieListAdapter.kt
> +    fun addList(movieListFromActivity : List<Movie>){
9a1ed6d
수정했습니다. 감사합니다!

2020-05-29 12:18 UTC, sjjeong commented on 2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/MovieListPresenter.kt
> +            view.refreshMovieList(movies)
else 안에 있는것을 지우지 말고 밖에 있는것을 지워는게 더 좋지 않을까요?

2020-05-29 12:19 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-05-30 02:03 UTC, merged