HW-2 MVP 변환
sjjeong/GoogryAndroidArchitecutreStudy pull request #65
Opened 2019-06-18 16:27 UTC by Nanamare

MarketListFragment 쪽을 나눠야할까 고민이 되었는데, 
일단은 리모트나 로컬에 접근 없이 메모리에서 처리 되어 그대로 나뒀습니다.
CompositeDisposable 클래스도 각각 Presenter 에서 관리 되는 부분도 고민이 있었지만 일단은 나뒀습니다.

더 좋은 구조가 생각나면 바꾸도록 하겠습니다.

태클 팍팍 걸어주세요 :)

2019-06-20 16:32 UTC, zion830 requested changes
고생하셨습니다!

2019-06-20 16:32 UTC, zion830 commented on Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/contract/CoinContract.kt
> +        fun showCoins(list: List<TickerModel>?)
`list`가 nullable인데, 지금은 매개변수로 null이 들어와도 `adapter.clear()` 가 호출될 수 있네요.
리스트가 비게될 경우에 대한 처리도 필요해보입니다 ㅎㅎ

2019-06-20 16:32 UTC, zion830 commented on Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/data/CoinRemoteDataSource.kt
> +            UpBitServiceManager.getTickerList(ticketList)
질문 : retrofit을 사용할 때 `.subscribeOn(Schedulers.io())` 전 후의 코드를 서로 다른 파일로 분리하는 이유는 무엇인가요?

2019-06-20 16:32 UTC, zion830 commented on Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/presenter/BaseView.kt
> +interface BaseView {
`presenter` 패키지 안에서는 쓰이지 않으니 `ui`로 이동하는 것이 좋아보입니다.

2019-06-20 16:32 UTC, zion830 commented on Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/ui/BaseFragment.kt
> +open class BaseFragment : Fragment() , BaseView {
BaseActivity와 중복되어서 구현된 함수가 사용되지 않는거같은데 BaseFragment에서도 BaseView의 재정의가 필요할까요.?

2019-06-20 16:32 UTC, zion830 commented on Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/data/CoinRepository.kt
> +    override fun getCoins(ticketList: MutableList<String>, success: (List<TickerModel>) -> Unit, failed: () -> Unit) {
함수를 이렇게도 넘길수 있다는걸 처음 알았네요 !!

2019-06-20 16:48 UTC, zion830 commented
현성님의 코드를 보고 궁금한게 있습니다!
지난번에 설명으로 View와 Presenter는 무조건 1:1 관계라 하셨는데,
View에 대해서 정의해야할 함수가 없더라도 Presenter가 만들어진 이상 아래처럼 View도 무조건 만들어주는게 원칙적으로 맞는거지요?! 제가 아직 패턴 적용이 익숙치 않아 현성님 코드를 그냥 감상(?)한것 같네요 ㅋㅋ

```
interface MarketView : BaseView

interface MarketPresenter : BasePresenter {
    fun getMarketList()
}
```

2019-06-22 02:13 UTC, Nanamare commented on Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/data/CoinRemoteDataSource.kt
> +            UpBitServiceManager.getTickerList(ticketList)
subscribeon(Scheduler.io()) 가 서버에서 데이터를 받아 올때 백그라운드에서 동작하도록 하는 코드라 그 이후는 사용하는 쪽에서 알아서 받아서 사용하게끔 분리해놨습니다 백그라운드에서 데이터 받아와서 UI 갱신 할 수도 있고 다시 백그라운드에서 동기적으로 데이터를 요청할 수도 있고 다양할 것 같아요

2019-06-22 02:18 UTC, Nanamare commented on Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/presenter/BaseView.kt
> +interface BaseView {
커뮤니케이션 완료!

2019-06-22 02:27 UTC, Nanamare commented on Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/ui/BaseFragment.kt
> +open class BaseFragment : Fragment() , BaseView {
BaseFragment 안에 있는 구현체들은 Activity에 있는 함수를 호출하게 됩니다!

2019-06-23 15:04 UTC, zion830 submitted a review, later dismissed

2019-06-23 15:07 UTC, zion830 commented
approve 했습니다~ 나머지 수정도 화이팅~
저도 그때 대충이지만 석준님이 리뷰해주신 내용을 적어두긴 했어서, 
혹시 기억이 흐릿해진게 있으시면 같이 기억을 쥐어짜볼게요 ㅋㅋㅋ

2019-06-25 13:15 UTC, sjjeong requested changes
잘 반영 하셨어요!

2019-06-25 13:15 UTC, sjjeong commented on Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/adapter/viewholder/TickerViewHolder.kt
> +    @LayoutRes layoutRes: Int,
특정 ViewHolder클래스를 만드는 경우라면 layoutRes를 받지말고 바로 사용해도 좋아요
```kotlin
) : BaseViewHolder<TickerModel>(R.layout.item_ticker, parent) {
```

2019-06-25 13:37 UTC, Nanamare commented on Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/adapter/viewholder/TickerViewHolder.kt
> +    @LayoutRes layoutRes: Int,
수정 하였습니다!
3f49ddae7c72443a4f0d1aa9e002c1a5e8880057

2019-06-25 13:38 UTC, Nanamare commented on Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/adapter/viewholder/TickerViewHolder.kt
> +    @LayoutRes layoutRes: Int,
수정 하였습니다!
3f49ddae7c72443a4f0d1aa9e002c1a5e8880057
@sjjeong

2019-06-25 15:01 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-06-25 15:01 UTC, sjjeong commented
@zion830 
최종확인 해주세요

2019-06-25 16:56 UTC, zion830 approved these changes
잘 수정된 것 같습니다..! 고생하셨습니다

2019-06-26 02:42 UTC, merged