HW3 - MVP 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #650
Opened 2020-05-26 07:13 UTC by chuuuul

- Model  ↔ Present ↔ View의 구조
- View는 UI의 I/O를 Present에 전달한다.
- Present는 로직을 처리한다.
- Contract는 View와 Present의 인터페이스를 구성한다.
- 각 액티비티 프래그먼트 마다 각각의 구조를 적용시킨다.

2020-05-26 07:41 UTC, developer-sungjae commented
안녕하세요~

2020-05-26 07:51 UTC, SageHabitus requested changes

2020-05-26 07:51 UTC, developer-sungjae commented on 2005/chuuuul/ArchitectureStudy/app/src/main/java/com/example/architecture/activity/search/adapter/MovieHolderPresenter.kt
> +    private val view: MovieHolderContract.View
안쓰는 것 같은데 확인 부탁드립니다.

2020-05-26 07:51 UTC, developer-sungjae commented on 2005/chuuuul/ArchitectureStudy/app/src/main/java/com/example/architecture/activity/search/adapter/MovieHolderPresenter.kt
> +
검색어 '안'을 쳐보시면 html 파싱이 안되는 것을 볼 수가 있습니다. 이 부분에 대해서도 파싱이 잘 되도록 변경 해주세요!

2020-05-26 07:51 UTC, developer-sungjae commented on 2005/chuuuul/ArchitectureStudy/app/src/main/java/com/example/architecture/activity/search/SearchActivity.kt
> +        Toast.makeText(this, getText(resId), Toast.LENGTH_SHORT).show()
어떤 토스트인지 메서드만으로는 추측할 수 없을 것 같습니다.

2020-05-26 07:55 UTC, developer-sungjae commented on 2005/chuuuul/ArchitectureStudy/app/src/main/java/com/example/architecture/activity/search/adapter/MovieAdapter.kt
> +    }
어떤부분은 괄호가 있고 어떤 부분은 없는데 통일 해주시면 좋을 것 같습니다.

2020-05-26 07:56 UTC, developer-sungjae commented on 2005/chuuuul/ArchitectureStudy/app/src/main/java/com/example/architecture/activity/search/adapter/MovieHolderPresenter.kt
> +            ConstValue.NO_IMAGE_URL
AppUtil은 import하셨는데 ConstValue는 따로 남겨 놓아서 이것도 없애는게 좋지 않을까요?

2020-05-26 07:59 UTC, developer-sungjae commented on 2005/chuuuul/ArchitectureStudy/app/src/main/java/com/example/architecture/activity/search/SearchActivity.kt
> +            searchPresenter.searchMovie(edt_search_keyword.text.toString())
가독성을 위해서 매우 긴 parameter는
`
val a = '매우 긴 value'
method(a)
`
식으로 쓰는게 가독성에 훨씬 더 보기 좋은 것 같습니다

2020-05-26 08:03 UTC, developer-sungjae commented on 2005/chuuuul/ArchitectureStudy/app/src/main/java/com/example/architecture/activity/search/SearchPresenter.kt
> +    }
그냥 질문입니다.
어디는 return if이고 어디는 if문이고 어디는 if문 + 밑의 return을 붙여주셨는데 혹시 가독성을 생각하시고 정하신건가요~? 아니면 기준이 있으신지 궁금합니다. 기준이 없으시다면 통일하면 좋을 것 같습니다.

2020-05-26 08:07 UTC, developer-sungjae commented
그 외에는 저보다 더 자세하게 구현하셨는데 딱히 코멘트 드릴게 없네요.

2020-05-26 08:29 UTC, developer-sungjae commented on 2005/chuuuul/ArchitectureStudy/app/src/main/java/com/example/architecture/data/repository/NaverRepositoryImpl.kt
> +        naverLocalDataSource.getMovieList(keyword, onSuccess)
혹시 로컬무비리스트 가져오는 동작방식은 어떻게 되나요~?

2020-05-26 09:38 UTC, chuuuul commented on 2005/chuuuul/ArchitectureStudy/app/src/main/java/com/example/architecture/activity/search/adapter/MovieHolderPresenter.kt
> +    private val view: MovieHolderContract.View
84ec814
수정했습니다.
onBind 작업을 ViewHolder에서 하지 않고 Presenter에서 작업하도록 하여 view로 전달하도록 하였습니다.

2020-05-26 09:49 UTC, chuuuul commented on 2005/chuuuul/ArchitectureStudy/app/src/main/java/com/example/architecture/activity/search/SearchActivity.kt
> +        Toast.makeText(this, getText(resId), Toast.LENGTH_SHORT).show()
12d0368
감사합니다. 수정했습니다.

2020-05-26 09:55 UTC, chuuuul commented on 2005/chuuuul/ArchitectureStudy/app/src/main/java/com/example/architecture/activity/search/adapter/MovieAdapter.kt
> +    }
b85c385
감사합니다. 수정했습니다

2020-05-26 09:57 UTC, chuuuul commented on 2005/chuuuul/ArchitectureStudy/app/src/main/java/com/example/architecture/activity/search/adapter/MovieHolderPresenter.kt
> +            ConstValue.NO_IMAGE_URL
f352da6
감사합니다. 수정했습니다.

2020-05-26 10:00 UTC, chuuuul commented on 2005/chuuuul/ArchitectureStudy/app/src/main/java/com/example/architecture/activity/search/SearchActivity.kt
> +            searchPresenter.searchMovie(edt_search_keyword.text.toString())
a96871c
감사합니다. 수정했습니다.

2020-05-26 10:05 UTC, chuuuul commented on 2005/chuuuul/ArchitectureStudy/app/src/main/java/com/example/architecture/activity/search/SearchPresenter.kt
> +    }
ae45975
감사합니다. 수정했습니다!

2020-05-26 11:38 UTC, chuuuul commented on 2005/chuuuul/ArchitectureStudy/app/src/main/java/com/example/architecture/activity/search/adapter/MovieHolderPresenter.kt
> +
a96871c
감사합니다. 성재님 코드 참고하여 수정했습니다!

2020-05-26 12:05 UTC, SageHabitus approved these changes

2020-05-26 12:10 UTC, developer-sungjae commented
고생하셨습니다.

2020-05-27 16:18 UTC, sjjeong requested changes

2020-05-27 16:18 UTC, sjjeong commented on 2005/chuuuul/ArchitectureStudy/app/src/main/java/com/example/architecture/activity/search/SearchPresenter.kt
> +            return false
return 제거 해주세요

2020-05-27 16:18 UTC, sjjeong commented on 2005/chuuuul/ArchitectureStudy/app/src/main/java/com/example/architecture/activity/search/adapter/MovieAdapterContract.kt
> +        fun getMovieCount(): Int
mvp에서 contract함수들은 return이 없는 형태로 만들어 주셔야 해요

2020-05-28 13:58 UTC, chuuuul commented on 2005/chuuuul/ArchitectureStudy/app/src/main/java/com/example/architecture/activity/search/adapter/MovieAdapterContract.kt
> +        fun getMovieCount(): Int
97839a2
감사합니다. 수정했습니다.

2020-05-28 13:58 UTC, chuuuul commented on 2005/chuuuul/ArchitectureStudy/app/src/main/java/com/example/architecture/activity/search/SearchPresenter.kt
> +            return false
b48fd5d
감사합니다. 수정했습니다!

2020-05-28 16:17 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-05-28 16:19 UTC, merged