2004/jesterz91
sjjeong/GoogryAndroidArchitecutreStudy pull request #651
Opened 2020-05-27 05:21 UTC by jesterz91

2020-05-28 16:29 UTC, Kyudong3 requested changes
GOOD!

2020-05-28 16:29 UTC, Kyudong3 commented on 2004/jesterz91/app/src/main/java/io/github/jesterz91/study/presentation/ui/MovieSearchViewModel.kt
> +    private val _movieListLiveData = MutableLiveData<List<Movie>>(emptyList())
emptyList() 로 해주어야 하는 이유가 따로 있나요?!

2020-05-28 16:30 UTC, Kyudong3 approved these changes

2020-05-28 16:35 UTC, sjjeong requested changes

2020-05-28 16:35 UTC, sjjeong commented on 2004/jesterz91/app/src/main/java/io/github/jesterz91/study/presentation/ui/MovieSearchAdapter.kt
> +    companion object {
companion object는 클래스 내부 맨 아래에 위치해야 합니다.

2020-05-29 13:31 UTC, jesterz91 commented on 2004/jesterz91/app/src/main/java/io/github/jesterz91/study/presentation/ui/MovieSearchAdapter.kt
> +    companion object {
수정했습니다. dff4c56

2020-05-29 13:35 UTC, jesterz91 commented on 2004/jesterz91/app/src/main/java/io/github/jesterz91/study/presentation/ui/MovieSearchViewModel.kt
> +    private val _movieListLiveData = MutableLiveData<List<Movie>>(emptyList())
default value 값을 설정하기 위함입니다.

2020-05-29 15:08 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-05-29 15:12 UTC, merged