HW-7 apply Koin(DI 적용)
sjjeong/GoogryAndroidArchitecutreStudy pull request #655
Opened 2020-05-31 10:35 UTC by TaeseongYun

2020-06-04 05:20 UTC, ghost reviewed
저는 기존에 SingleTon을 사용하기 때문에 해당 파일들은 object로 만들고 필드에 선언해서 사용했었는데 이번에 D.I 라는 개념을 배우면서 왜 태성님이 파라미터로 계속 넘겨주셨는지 알 수 있었습니다.
D.I 관련된 코드들은 잘 작성해주신듯 합니다. Rx는 아직 리뷰해드리지 못해서 죄송합니다

2020-06-04 05:20 UTC, invitejay commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/di/NetworkModule.kt
> +            chain.proceed(chain.request().newBuilder().also {
저는 also없이 쭉 이어서 작성했습니다. 혹시 이렇게 해준다면 어떤 장점이 있나요?

2020-06-04 05:27 UTC, TaeseongYun commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/di/NetworkModule.kt
> +            chain.proceed(chain.request().newBuilder().also {
also 로 작성하면 해당 수신 객체를 다시 반환 시켜주기 때문에 addHeader 가 들어간 채로 newBuilder값이 반환 될거라 생각하여 also 를 사용하였습니다.

참고 자료 - [코틀린 표준 라이브러리](https://medium.com/@limgyumin/%EC%BD%94%ED%8B%80%EB%A6%B0-%EC%9D%98-apply-with-let-also-run-%EC%9D%80-%EC%96%B8%EC%A0%9C-%EC%82%AC%EC%9A%A9%ED%95%98%EB%8A%94%EA%B0%80-4a517292df29)

2020-06-04 05:30 UTC, ghost approved these changes
고생하셨습니다 !

2020-06-04 16:13 UTC, sjjeong requested changes
NaverRepositoryImpl에는 NaverRemoteDataSource를 생성자로 주입시켜주시고
NaverRemoteDataSourceImpl에는 retrofit으로 만든 api를 생성자로 주입해주세요
NaverAPI.kt와 CreateRetrofit.kt 파일 제거해주세요 

미사용되는 파일들 모두 제거해주시고 unused import 정리해주세요 

프로젝트를 전반적으로 다시 보시면서 불필요한 요소들 있는지 확인해보시고 정리해주세요

2020-06-04 16:13 UTC, sjjeong commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/di/NetworkModule.kt
> +            chain.proceed(chain.request().newBuilder().also {
Builder 패턴이기 때문에 불필요한 also 입니다
제거해주세요

2020-06-04 16:13 UTC, sjjeong commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/di/NetworkModule.kt
> +                it.addHeader(X_NAVER_CLIENT_ID, BuildConfig.Client_ID)
상수는 전부 대문자로 선언해주세요
`CLIENT_ID`

2020-06-04 16:13 UTC, sjjeong commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/di/RxJavaModule.kt
> +    single<RxEventBus> { RxEventBusImpl() }
RxEventBus가 BaseActivity쪽에서는 koin으로 inject해주고 있지 않습니다.
inject하도록 변경해주세요

2020-06-04 16:13 UTC, sjjeong commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/di/RxJavaModule.kt
> +    single { CompositeDisposable() }
CompositeDisposable은 single로 하면 안됩니다.

2020-06-05 01:24 UTC, TaeseongYun commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/di/RxJavaModule.kt
> +    single { CompositeDisposable() }
CompositeDisposable를 di 로 넣으면 안되는건가요?

저는 single로 전역 처럼 이용하면 좋을거 같아 single로 감싸주었는데 factory가 아닌 single로 했을 때 문제점은  여러 스트림이 하나의 CompositeDisposable로 상태관리 되기 때문에 문제가 되는걸까요?

2020-06-06 01:09 UTC, TaeseongYun commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/di/NetworkModule.kt
> +                it.addHeader(X_NAVER_CLIENT_ID, BuildConfig.Client_ID)
수정하였습니다.
c8974e1

2020-06-06 01:12 UTC, TaeseongYun commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/di/RxJavaModule.kt
> +    single<RxEventBus> { RxEventBusImpl() }
수정하였습니다.

1dcf7c0

2020-06-06 01:44 UTC, sjjeong commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/di/RxJavaModule.kt
> +    single { CompositeDisposable() }
네 여러 스트림을 하나의 CompositeDisposable로 관리하면 문제가 됩니다.
어떤 화면에서 CompositeDisposable을 clear하거나 dispose하면 다른 곳에서 subscribe 한게 전부 취소 됩니다.

2020-06-06 01:46 UTC, sjjeong commented
미사용되는 파일들 모두 제거해주시고 unused import 정리해주세요

프로젝트를 전반적으로 다시 보시면서 불필요한 요소들 있는지 확인해보시고 정리해주세요

2020-06-06 02:22 UTC, TaeseongYun commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/di/RxJavaModule.kt
> +    single { CompositeDisposable() }
수정하였습니다.

b3e90ed

2020-06-06 02:27 UTC, TaeseongYun commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/di/RxJavaModule.kt
> +    single { CompositeDisposable() }
미사용 클래스 , 임포트 정리 수정하였습니다.

35ab01f

2020-06-06 04:56 UTC, sjjeong requested changes

2020-06-06 04:56 UTC, sjjeong commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/di/RxJavaModule.kt
> +    single { (finish: () -> Unit, showToast: (Int, Int) -> Unit) ->
single로 만들면 finish하는 이벤트가 한곳에만 걸려서 재사용할 수 없을 것 같네요

2020-06-06 04:56 UTC, sjjeong commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/di/RxJavaModule.kt
> +            get(),
BackKeyPressExt 2번째 인자가 CompositeDisposable인데 BackKeyPressExt를 사용하는 Activity에서 관리하는 CompositeDisposable을 전달해야 합니다.

2020-06-06 05:05 UTC, TaeseongYun commented on 2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/di/RxJavaModule.kt
> +            get(),
수정하였습니다.

e4004cc

2020-06-06 06:40 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-06-06 10:13 UTC, merged