2005/ryu c0605 hw 4 1
sjjeong/GoogryAndroidArchitecutreStudy pull request #656
Opened 2020-06-01 17:11 UTC by RyuC0605

안녕하세요. 류승윤 입니다.
기존 영화 검색 예제에 데이터바인딩 적용 코드를 올리오니, 검토 부탁 드립니다.
감사합니다.

2020-06-03 05:24 UTC, sangjinKIM93 reviewed
안녕하세요 승윤님:)

2020-06-03 05:24 UTC, sangjinKIM93 commented on 2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/networks/ImageLoader.kt
> +        }
imageLoader를 메서드로 생성하는 것이 아니라 클래스로 생성하신 이유가 있으신가요?

2020-06-03 05:24 UTC, sangjinKIM93 commented on 2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/main/MainActivity.kt
>          presenter = MainPresenter(this)
setcontentView"ActivityMainBinding"에서 "ActivityMainBinding"은 지워도 될 것 같습니다.

2020-06-03 05:24 UTC, sangjinKIM93 commented on 2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/main/MainActivity.kt
이런식으로도 설정할 수 있군요~! ㅎㅎ

2020-06-04 11:48 UTC, RyuC0605 commented on 2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/networks/ImageLoader.kt
> +        }
Glide 가 아닌 volley 나 여타 이미지로더로 변경 시 편의성을 위해 이미지로더 라는 클래스를 만들어 그 안에 로드 함수에 Glide 사용부를 넣은 것입니다.

2020-06-04 11:51 UTC, RyuC0605 commented on 2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/main/MainActivity.kt
>          presenter = MainPresenter(this)
제네릭스 ActivityMainBinding 을 말씀하신 것인가요?
이건 채워넣는걸 기본으로 코딩하는 습관이 있는데, 일단 수정 하였습니다.

9325bd63279240faa615906501d29e5ef62d0641

2020-06-04 11:52 UTC, RyuC0605 commented on 2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/main/MainActivity.kt
top 을 include 하였더니 저렇게 해야 하더군요;;;

2020-06-04 12:09 UTC, sangjinKIM93 approved these changes

2020-06-04 12:09 UTC, sangjinKIM93 commented on 2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/networks/ImageLoader.kt
> +        }
추후 추가 및 변경을 고려하신거군요. 답변 감사합니다!

2020-06-04 16:38 UTC, sjjeong requested changes

2020-06-04 16:38 UTC, sjjeong commented on 2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/networks/ImageLoader.kt
> +        fun load(iv: ImageView, url: String?) {
ImageView의 extension function으로 만들어 보면 좋습니다.
함수명이 load이라서 BindingAdpater 이름도 thumbnail보다 load가 좋을 것 같습니다.

2020-06-04 16:38 UTC, sjjeong commented on 2005/RyuC0605/Android_X/app/src/main/res/layout/activity_main.xml
> +            type="r.test.rapp.networks.ImageLoader" />
미사용이라서 제거하셔도 좋습니다.

2020-06-04 16:38 UTC, sjjeong commented on 2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/main/MainActivity.kt
> +        binding.top.setVariable(BR.present, presenter)
include에 직접 넣는 형태로 쓸 수 있군요
저는 보통 setContentView로 넣는 xml에 presenter를 넘기고 내부적으로 include에 전달하는 방식을 사용했습니다.
현재 코드도 나쁘지 않다고 생각들고 아래 링크 방식이 승윤님께서 보시기에 괜찮다고 생각이 되면 반영해보세요
https://developer.android.com/topic/libraries/data-binding/expressions#includes

2020-06-04 16:38 UTC, sjjeong commented on 2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/main/MainActivity.kt
>          }
해당 부분을 BindingAdpater로 만들고 onClick처럼 내부적으로 presenter.searchData()를 호출하도록 만들어보세요

2020-06-04 16:38 UTC, sjjeong commented on 2005/RyuC0605/Android_X/app/src/main/res/layout/layout_main_top.xml
> +            android:onClick="@{(keyword) -> present.searchData(edtInput.getText().toString().trim())}"
keyword를 사용하지 않는다면 `() ->` 처럼 비워두시면 됩니다.

2020-06-05 07:07 UTC, RyuC0605 commented on 2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/networks/ImageLoader.kt
> +        fun load(iv: ImageView, url: String?) {
수정 하였습니다.

a0dbcddbb13baf7a43303998aeb6196f9c4a1380

2020-06-05 07:08 UTC, RyuC0605 commented on 2005/RyuC0605/Android_X/app/src/main/res/layout/activity_main.xml
> +            type="r.test.rapp.networks.ImageLoader" />
수정 하였습니다.

e9f539ff281aa0b43692268a89e7623cb3053dff

2020-06-05 07:09 UTC, RyuC0605 commented on 2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/main/MainActivity.kt
> +        binding.top.setVariable(BR.present, presenter)
이 방법이 웬지 더 정석에 가까운 것 같군요.

ff76a301afafaa679a142d0a0062b0aeb7368e52

2020-06-05 07:10 UTC, RyuC0605 commented on 2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/main/MainActivity.kt
>          }
수정하였습니다.

92c6da3950eff1bc9373c29f23aef4fb40daff9e

2020-06-05 07:10 UTC, RyuC0605 commented on 2005/RyuC0605/Android_X/app/src/main/res/layout/layout_main_top.xml
> +            android:onClick="@{(keyword) -> present.searchData(edtInput.getText().toString().trim())}"
수정 완료

ed902fe8891e7d4d97220aa7885a7b55a937c8bc

2020-06-05 12:16 UTC, sjjeong requested changes

2020-06-05 12:16 UTC, sjjeong commented on 2005/RyuC0605/Android_X/app/src/main/res/layout/layout_main_top.xml
> +            bind:onSearch="@{present}" />
제가 기대했던 수정은 Button에
```kotlin
android:onClick="@{() -> present.searchData(edtInput.getText().toString().trim())}"
```
방식처럼 동일하게 EditText에도
```kotlin
bind:onSearch="@{() -> present.searchData(edtInput.getText().toString().trim())}"
```
였습니다.

2020-06-05 12:29 UTC, RyuC0605 commented on 2005/RyuC0605/Android_X/app/src/main/res/layout/layout_main_top.xml
> +            bind:onSearch="@{present}" />
EditText 에 리스너를 달지 않고 검색버튼을 누르는 이벤트를 발생시킬 방법이 있는지요?
bind:onSearch 호출 시 리스너를 생성하는 방법 외에 좋은 방안이 있다면 힌트를 부탁 드립니다.

2020-06-06 01:41 UTC, sjjeong commented on 2005/RyuC0605/Android_X/app/src/main/res/layout/layout_main_top.xml
> +            bind:onSearch="@{present}" />
```kotlin
@BindingAdapter("onEditorAction")
fun TextView.setOnEditorAction(action: (() -> Unit)? = null) {
    setOnEditorActionListener { _, actionId, _ ->
        if (imeOptions == actionId) {
            action?.invoke()
            true
        } else {
            false
        }
    }
}
```
```xml
<EditText
    bind:onEditorAction="@{() -> view.onEditorAction()}" />
```
이렇게 하면 됩니다.

2020-06-06 09:54 UTC, RyuC0605 commented on 2005/RyuC0605/Android_X/app/src/main/res/layout/layout_main_top.xml
> +            bind:onSearch="@{present}" />
수정하였습니다.

052c633ad86007bbd2b67c2f7795322c8b99e0ab

2020-06-07 06:42 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-06-07 09:38 UTC, merged