HW4 - DataBinding
sjjeong/GoogryAndroidArchitecutreStudy pull request #659
Opened 2020-06-01 23:43 UTC by hwaniiidev

DataBinding 
BindingAdapter 사용

2020-06-03 00:57 UTC, LeeChungWoo92 requested changes

2020-06-03 00:57 UTC, LeeChungWoo92 commented on 2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/ui/main/MainDataBindingExtension.kt
> +    view.text = Html.fromHtml(title)
html fromHtml이 N버전부터 deprecated 되었다고해서 분기를 태우시거나 다른코드로 대체 하시는게 
좋을것같습니다 !

2020-06-03 01:05 UTC, LeeChungWoo92 requested changes

2020-06-03 01:05 UTC, LeeChungWoo92 commented on 2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/ui/main/MainActivity.kt
>      }
스레드 사용목적이 무엇인가요!?

2020-06-03 01:19 UTC, LeeChungWoo92 requested changes

2020-06-03 01:19 UTC, LeeChungWoo92 commented on 2005/hwaniiidev/Architecture/app/src/main/res/layout/activity_main.xml
> +                android:text="검색" />
버튼클릭도 databinding 적용해보시면 좋을것같습니다.

2020-06-03 23:36 UTC, hwaniiidev commented on 2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/ui/main/MainDataBindingExtension.kt
> +    view.text = Html.fromHtml(title)
eefac83
반영했습니다!

2020-06-03 23:36 UTC, hwaniiidev commented on 2005/hwaniiidev/Architecture/app/src/main/res/layout/activity_main.xml
> +                android:text="검색" />
535cdf0
이부분도 반여해봤습니다!

2020-06-03 23:41 UTC, hwaniiidev commented on 2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/ui/main/MainActivity.kt
>      }
NaverMovieLocalDataSourceImpl 의 getCachedMovies 메서드가 Local에서 cashed 데이터를 가져오는 메서드입니다. DB에서 데이터를 가져올 때 서브스레드를 사용해야하다 보니 UI 변경하는 부분에서는UiThread를 사용하기위해 runOnUiThread 를 사용했습니다

2020-06-04 06:36 UTC, LeeChungWoo92 commented
수고하셨습니다!

2020-06-04 06:36 UTC, LeeChungWoo92 approved these changes

2020-06-04 16:44 UTC, sjjeong requested changes

2020-06-04 16:44 UTC, sjjeong commented on 2005/hwaniiidev/Architecture/app/src/main/res/layout/item_movie_list.xml
> +                    htmlTitle="@{movieItem.title}"/>
TextView 하나로 만든다면 LinearLayout도 필요 없습니다.

2020-06-07 02:28 UTC, hwaniiidev commented on 2005/hwaniiidev/Architecture/app/src/main/res/layout/item_movie_list.xml
> +                    htmlTitle="@{movieItem.title}"/>
7ee7d20
수정했습니다!

2020-06-07 04:38 UTC, sjjeong commented on 2005/hwaniiidev/Architecture/app/src/main/res/layout/item_movie_list.xml
> +                    htmlTitle="@{movieItem.title}"/>
이렇게 말고 String.format을 쓰거나 string res로 빼서 넣어주도록 해주세요
htmlTitle쪽은 이렇게 할 수 없겠네요

2020-06-07 04:38 UTC, sjjeong requested changes

2020-06-07 04:38 UTC, sjjeong commented on 2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/ui/main/MainDataBindingExtension.kt
> +    view.text = "서브제목 : ${subtitle}"
이렇게 말고 String.format을 쓰거나 string res로 빼서 넣어주도록 해주세요
htmlTitle쪽은 이렇게 할 수 없겠네요

2020-06-08 12:56 UTC, hwaniiidev commented on 2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/ui/main/MainDataBindingExtension.kt
> +    view.text = "서브제목 : ${subtitle}"
735e4d6
이렇게 해결했습니다. html 잘 반영되서 나오네요

2020-06-09 09:29 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-06-09 09:29 UTC, sjjeong commented
@LeeChungWoo92
 approve 해주세요

2020-06-09 11:03 UTC, merged