HW-5 AAC-MVVM 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #66
Opened 2019-06-19 02:39 UTC by improve777

* aac-mvvm 적용
* androidx 마이그레이션
* alertDialog 를 DialogFragment 로 수정
   (기기 회전시 다이얼로그가 재생성 되도록)

많은 리뷰 부탁드립니다!

2019-06-20 15:31 UTC, namjackson commented on improve777/GAASProject/app/src/main/java/dev/daeyeon/gaasproject/ui/ticker/TickerAdapter.kt
> +        RecyclerView.ViewHolder(binding.root)
수정요청은 아니고 저도 라인브레이킹 어떻게할지 고민이였는데
상속부분 라인 브레이킹할때
` RecyclerView.ViewHolder(binding.root)`

`:  RecyclerView.ViewHolder(binding.root)`
앞에 : 을 붙이는건 어떤가요?

2019-06-20 15:31 UTC, namjackson commented on improve777/GAASProject/app/src/main/java/dev/daeyeon/gaasproject/ui/ticker/marketchoice/MarketChoiceDialogFragment.kt
> +            replaceAll(choiceViewModel.marketList.value!!)
리스트를 바인딩어댑터에서 바인딩 해주는것도 좋은거같아요! 
그리고 ` marketAdapter by lazy ` 에 바로 생성해줄수 있을거같아요

2019-06-20 15:31 UTC, namjackson commented on improve777/GAASProject/app/src/main/java/dev/daeyeon/gaasproject/ui/ticker/search/TickerSearchDialogFragment.kt
> +        storeProducer = { viewModelStore }
TickerSearchViewModel 에 기능이 없는데 
 completeEvent를 위해 searchViewModel 만드신건가요? 

변경요청이라기보단 저의 개인적인 의견인데,,
비즈니스로직을 수행하는 기능이 없다면 
굳이 ViewModel 생성하지 않아도 될거같은데
searchViewModel을 뷰에 바인딩하는것보다 
dialog 바인딩해서 클릭이벤트를 걸어주는 방법은 어떨까요?

2019-06-21 09:10 UTC, improve777 commented on improve777/GAASProject/app/src/main/java/dev/daeyeon/gaasproject/ui/ticker/TickerAdapter.kt
> +        RecyclerView.ViewHolder(binding.root)
![image](https://user-images.githubusercontent.com/36095102/59910976-f2e50a00-944d-11e9-8323-276cb572a6bb.png)

convention 보면 콜론( : ) 뒤에 라인을 변경하라고 하긴 하는데
사실 라인변경을 할 정도로 인자가 많다거나, 슈퍼 클래스가 많은게 아니기 때문에 
라인변경을 일단 하지 않는걸로 수정하였습니다!

a6de9a5e1c1fe0a671ebe5b490562bce42461997

2019-06-21 09:11 UTC, improve777 commented on improve777/GAASProject/app/src/main/java/dev/daeyeon/gaasproject/ui/ticker/marketchoice/MarketChoiceDialogFragment.kt
> +            replaceAll(choiceViewModel.marketList.value!!)
수정 완료 하였습니다!

4ea188ac23797f5fb24ae3304fb53e87d19d8bcf

2019-06-21 09:21 UTC, improve777 commented on improve777/GAASProject/app/src/main/java/dev/daeyeon/gaasproject/ui/ticker/search/TickerSearchDialogFragment.kt
> +        storeProducer = { viewModelStore }
두 곳에 확인, 검색 버튼이 있어서 ticker 를 호출하고 dialog 를 종료시키는 목적으로
`completeEvent` 를 base 로 만들었습니다.

남재님 말씀처럼 구현해도 될 거 같긴 한데 일관성이 떨어지지 않나 싶기도 하네요

2019-06-21 10:34 UTC, namjackson commented on improve777/GAASProject/app/src/main/java/dev/daeyeon/gaasproject/ui/ticker/TickerAdapter.kt
> +        RecyclerView.ViewHolder(binding.root)
아하 콜론을 뒤로 바꿔야되는게 맞았네요!

2019-06-21 10:48 UTC, namjackson submitted a review, later dismissed

2019-06-23 03:32 UTC, sjjeong requested changes

2019-06-23 03:32 UTC, sjjeong commented on improve777/GAASProject/app/src/main/java/dev/daeyeon/gaasproject/ui/MainActivity.kt
> +        if (savedInstanceState == null) {
이거말고 tag이용해서 supportFragmentManager에서 findFragmentByTag로 찾아보세요

2019-06-23 03:32 UTC, sjjeong commented on improve777/GAASProject/app/src/main/java/dev/daeyeon/gaasproject/ui/ticker/TickerViewModel.kt
> +    private val _isShowProgressBar = MutableLiveData<Boolean>(false)
얘도 base로 빼면 좋을꺼같네요

2019-06-23 03:32 UTC, sjjeong commented on improve777/GAASProject/app/src/main/java/dev/daeyeon/gaasproject/ui/ticker/TickerViewModel.kt
> +            baseCurrency = _baseMarket.value!!,
null처리!

2019-06-23 03:32 UTC, sjjeong commented on improve777/GAASProject/app/src/main/java/dev/daeyeon/gaasproject/ui/ticker/marketchoice/MarketChoiceDialogFragment.kt
> +    private val tickerViewModel by createViewModelLazy(
번들로 전달하는게 좋을것 같아요

2019-06-23 03:32 UTC, sjjeong commented on improve777/GAASProject/app/src/main/java/dev/daeyeon/gaasproject/ui/ticker/search/TickerSearchDialogFragment.kt
> +            event.getContentIfNotHandled()?.let {
extension으로 만들어보아요

2019-06-24 02:09 UTC, improve777 commented on improve777/GAASProject/app/src/main/java/dev/daeyeon/gaasproject/ui/MainActivity.kt
> +        if (savedInstanceState == null) {
수정했습니다

ea649745cb93d97e95c66560e1f08c3ef1504374

2019-06-24 02:10 UTC, improve777 commented on improve777/GAASProject/app/src/main/java/dev/daeyeon/gaasproject/ui/ticker/TickerViewModel.kt
> +    private val _isShowProgressBar = MutableLiveData<Boolean>(false)
수정했습니다

145f77e

2019-06-24 02:10 UTC, improve777 commented on improve777/GAASProject/app/src/main/java/dev/daeyeon/gaasproject/ui/ticker/TickerViewModel.kt
> +            baseCurrency = _baseMarket.value!!,
수정했습니다

8fcaf5d

2019-06-24 02:10 UTC, improve777 commented on improve777/GAASProject/app/src/main/java/dev/daeyeon/gaasproject/ui/ticker/marketchoice/MarketChoiceDialogFragment.kt
> +    private val tickerViewModel by createViewModelLazy(
수정했습니다

534b1f2

2019-06-24 02:10 UTC, improve777 commented on improve777/GAASProject/app/src/main/java/dev/daeyeon/gaasproject/ui/ticker/search/TickerSearchDialogFragment.kt
> +            event.getContentIfNotHandled()?.let {
수정했습니다

b5122d2

2019-06-24 05:50 UTC, namjackson approved these changes

2019-06-25 13:02 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-06-25 13:30 UTC, merged