HW-4 DataBinding 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #660
Opened 2020-06-02 06:26 UTC by chuuuul

### DataBinding 적용

- ViewHolder에서 XML로 MovieModel을 전달
- XML에서 Movie Model을 각각의 요소에 데이터 삽입
- onClickEvent 작업을 데이터 바인딩으로 처리
- Image Load 작업을 어뎁터 바인딩으로 처리
- Html Render 작업을 어뎁터 바인딩으로 처리

### ETC
Recycler View에 MVP 적용한 내용을 다시 되돌렸습니다.
BaseBranch가 달라져서 커밋이 HW-3의 내용을 일부 포함하게 되었습니다.

Merge Conflict가 발생 할 수 있을 것 같습니다.

리뷰 잘 부탁드리겠습니다!

2020-06-03 03:37 UTC, developer-sungjae commented on 2005/chuuuul/ArchitectureStudy/app/build.gradle
> +    }
이렇게 설정한 이유가 있으신가요?

2020-06-03 03:48 UTC, SageHabitus requested changes

2020-06-03 03:48 UTC, developer-sungjae commented on 2005/chuuuul/ArchitectureStudy/app/src/main/java/com/example/architecture/activity/search/SearchActivity.kt
> +            DataBindingUtil.setContentView<ActivitySearchBinding>(this, R.layout.activity_search)
<> <-- 생략하는게 좋을 것 같습니다

2020-06-03 04:12 UTC, SageHabitus commented on 2005/chuuuul/ArchitectureStudy/app/src/main/java/com/example/architecture/ext/ImageViewExtension.kt
> +    if (url == null) return
코틀린 스탠다드 펑션으로 바꿔주시면 좋을 것 같습니다.

2020-06-03 13:35 UTC, chuuuul commented on 2005/chuuuul/ArchitectureStudy/app/build.gradle
> +    }
제가 DataBinding을 할때 jvm 1.8로 설정하라는 에러가 나와서 설정했습니다~

지우고 Clean Project 후 빌드하면 에러가 나네요!

2020-06-03 13:50 UTC, chuuuul commented on 2005/chuuuul/ArchitectureStudy/app/src/main/java/com/example/architecture/ext/ImageViewExtension.kt
> +    if (url == null) return
880857a
감사합니다. 수정했습니다.

2020-06-03 13:50 UTC, chuuuul commented on 2005/chuuuul/ArchitectureStudy/app/src/main/java/com/example/architecture/activity/search/SearchActivity.kt
> +            DataBindingUtil.setContentView<ActivitySearchBinding>(this, R.layout.activity_search)
63ae38a
감사합니다. 수정했습니다.

2020-06-04 03:29 UTC, SageHabitus approved these changes

2020-06-04 03:29 UTC, developer-sungjae commented
고생하셨습니다.

2020-06-04 16:48 UTC, sjjeong requested changes
5ec1c40455887fee8cdbedd7e66bf40b5cc861b3 이 커밋 이후로 내용이 달라졌습니다.
chuuuul:2005/chuuuul-HW-4(DataBinding)를 StudyFork:2005/chuuuul로 rebase해서 conflict 처리하고 force push해주세요 

그 이후에 코드 리뷰하도록 하겠습니다.

2020-06-04 17:30 UTC, chuuuul commented
감사합니다.
Approve 를 받고 Conflict를 해결해야 하는줄 알았는데 잘못되었네요..

Rebase후 Conflict 처리 했습니다.

2020-06-05 12:16 UTC, sjjeong commented
> 감사합니다.
> Approve 를 받고 Conflict를 해결해야 하는줄 알았는데 잘못되었네요..
> 
> Rebase후 Conflict 처리 했습니다.

원래는 Approve이후에 Conflict하는게 맞는건데 이건 git이 꼬여서 pr을 올리기전에 해결하고 올렸어야 하는 문제 입니다.

2020-06-05 16:26 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-06-05 21:23 UTC, merged