HW-4 DataBinding 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #662
Opened 2020-06-02 08:55 UTC by LeeChungWoo92

안녕하세요!
adapter에 ViewHolder에서 LayoutInflater를 했었는데 DatabindingUtil.inflate를 하려고하니
방법을 못찾아서 onCreateViewHolder쪽으로 옮기고 구조도 조금바꿨습니다!

2020-06-02 13:12 UTC, hwaniiidev commented on 2005/leechungwoo92/StudyForkProject/app/src/main/java/com/lllccww/studyforkproject/ui/extension/HtmlTextChangeExtension.kt
> +@BindingAdapter("htmlTextChange")
ImageViewExtension 과 HtmlTextChangeExtension를 따로 나누신 이유가 있으신가요??

2020-06-02 13:12 UTC, hwaniiidev commented on 2005/leechungwoo92/StudyForkProject/app/src/main/java/com/lllccww/studyforkproject/ui/extension/ImageViewExtension.kt
> +fun ImageView.loadUrl(url: String) {
저는 인자로 view를 받아줬는데 이렇게도 할 수 있군요

2020-06-03 01:21 UTC, LeeChungWoo92 commented on 2005/leechungwoo92/StudyForkProject/app/src/main/java/com/lllccww/studyforkproject/ui/extension/HtmlTextChangeExtension.kt
> +@BindingAdapter("htmlTextChange")
저는 ImageViewExtension에 ImageView관련된 다른 함수들도 들어갈것같아서
(예를들면 이미지 둥글게 처리하는 함수)
Image에관련된것들만 모아놓으려고 분리하였습니다 !!

2020-06-03 02:10 UTC, LeeChungWoo92 commented on 2005/leechungwoo92/StudyForkProject/app/src/main/java/com/lllccww/studyforkproject/ui/extension/ImageViewExtension.kt
> +fun ImageView.loadUrl(url: String) {
네! 어떤 방법이 좋은건지는 모르겠습니다....

2020-06-03 23:41 UTC, hwaniiidev commented on 2005/leechungwoo92/StudyForkProject/app/src/main/java/com/lllccww/studyforkproject/ui/extension/HtmlTextChangeExtension.kt
> +@BindingAdapter("htmlTextChange")
뷰에서 사용해야할 Extension이 많아지면 필히 이렇게 나누는게 좋겠군요

2020-06-03 23:42 UTC, hwaniiidev commented
아!! PR올리실 때 reviewers에 석준님을 항상 깜빡하시는거 같아요 ㅎㅎ

2020-06-04 16:54 UTC, sjjeong requested changes

2020-06-04 16:54 UTC, sjjeong commented on 2005/leechungwoo92/StudyForkProject/app/src/main/java/com/lllccww/studyforkproject/ui/extension/HtmlTextChangeExtension.kt
> +@BindingAdapter("htmlTextChange")
파일명은 TextView의 extension이니까 TextViewExtension이 더 좋을 것 같습니다.
그러면 나중에 TextView에서 사용되는 extension과 BindingAdapter를 모아서 볼 수 있습니다.

2020-06-04 16:54 UTC, sjjeong commented on 2005/leechungwoo92/StudyForkProject/app/src/main/java/com/lllccww/studyforkproject/ui/extension/ImageViewExtension.kt
> +fun ImageView.loadUrl(url: String) {
어떤 방법으로 해도 상관없습니다.
저는 이 방법을 더 선호합니다.

2020-06-04 16:54 UTC, sjjeong commented on 2005/leechungwoo92/StudyForkProject/app/src/main/java/com/lllccww/studyforkproject/ui/main/MovieListAdapter.kt
> +    private lateinit var binding: ItemMovieListBinding
binding은 Adapter가 아닌 ViewHolder에 있어야 합니다.

2020-06-04 16:54 UTC, sjjeong commented on 2005/leechungwoo92/StudyForkProject/app/src/main/java/com/lllccww/studyforkproject/ui/main/MovieListAdapter.kt
>          }
클릭처리 하는 것도 ViewHolder 내부에서 하도록 해보세요

2020-06-05 06:35 UTC, LeeChungWoo92 commented on 2005/leechungwoo92/StudyForkProject/app/src/main/java/com/lllccww/studyforkproject/ui/extension/HtmlTextChangeExtension.kt
> +@BindingAdapter("htmlTextChange")
cddb94a
수정하였습니다!
생각해보니 그렇네요 감사합니다!

2020-06-05 06:36 UTC, LeeChungWoo92 commented on 2005/leechungwoo92/StudyForkProject/app/src/main/java/com/lllccww/studyforkproject/ui/main/MovieListAdapter.kt
> +    private lateinit var binding: ItemMovieListBinding
0fc3b08
수정했습니다!

2020-06-05 06:39 UTC, LeeChungWoo92 commented on 2005/leechungwoo92/StudyForkProject/app/src/main/java/com/lllccww/studyforkproject/ui/main/MovieListAdapter.kt
>          }
0fc3b08
ViewHolder내부로 수정했습니다!
혹시 이 클릭처리도 xml에서 하게끔 해야하나요??

2020-06-05 12:19 UTC, sjjeong commented on 2005/leechungwoo92/StudyForkProject/app/src/main/java/com/lllccww/studyforkproject/ui/main/MovieListAdapter.kt
>          }
아니요 지금은 괜찮습니다.

2020-06-05 12:19 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-06-08 01:11 UTC, hwaniiidev approved these changes

2020-06-08 01:12 UTC, merged