2005/developer sungjae hw 4
sjjeong/GoogryAndroidArchitecutreStudy pull request #668
Opened 2020-06-03 10:15 UTC by developer-sungjae

- dataBinding 구현

2020-06-03 13:26 UTC, chuuuul requested changes
안녕하세요!
Two-way Databinding까지 사용하셨네요 ㅎㅎ

2020-06-03 13:26 UTC, chuuuul commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/components/ExtensionFunc.kt
>  fun String.parseHTMLTag(): String {
private로 지정해도 될 것 같습니다.

2020-06-03 13:26 UTC, chuuuul commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/res/layout/activity_search.xml
> +        <Button
앱 켜자마자 검색버튼 누르면 죽는 버그가 있습니다.

2020-06-03 13:26 UTC, chuuuul commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/res/layout/activity_search.xml
> +            android:text="@{etSearch.text}"
```android:text="@{searchWord}"```
로 바꾸는게 좋을 것 같습니다.

그리고 앱 켜자마자 Edit Text에 단어를 쳤을때 글자 따라 나오지 않는 기능은 의도 하신건가요?

2020-06-03 13:26 UTC, chuuuul commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/ui/search/SearchAdapter.kt
> +    fun bind(movieItem: MovieItem) {
넘어온 movieItem을 새로운 객체에 담아서 XML에 보내는 이유가 있을까요?

2020-06-04 14:27 UTC, SageHabitus commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/res/layout/activity_search.xml
> +        <Button
감사합니다 수정하였습니다.
1ab6b57

2020-06-04 14:28 UTC, SageHabitus commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/res/layout/activity_search.xml
> +            android:text="@{etSearch.text}"
의도랑 좀 다르게 되었네요.
감사합니다. 수정하였습니다.
c3fff75

2020-06-04 14:28 UTC, developer-sungjae commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/ui/search/SearchAdapter.kt
> +    fun bind(movieItem: MovieItem) {
철님 코드 참고하여 바인딩 어뎁터 내에서 처리하게 바꾸었습니다!
감사합니다.
cd63e61

2020-06-04 14:30 UTC, SageHabitus commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/components/ExtensionFunc.kt
>  fun String.parseHTMLTag(): String {
감사합니다. 수정하였습니다.
f9fd927

2020-06-04 17:08 UTC, chuuuul requested changes

2020-06-04 17:08 UTC, chuuuul commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/ui/search/SearchActivity.kt
> +        et_search.addTextChangedListener(textWatcher)
해당 내용을
```
        et_search.doAfterTextChanged {
            presenter.invokeTextChanged()
        }
```
로 바꿀 수 있을 것 같습니다!

2020-06-04 23:44 UTC, developer-sungjae commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/ui/search/SearchActivity.kt
> +        et_search.addTextChangedListener(textWatcher)
매우 유용하네요 감사합니다.
b943d86

2020-06-05 01:52 UTC, chuuuul approved these changes
수고하셨습니다!

2020-06-05 16:38 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-06-05 22:41 UTC, merged