HW-2 MVP 패턴 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #67
Opened 2019-06-19 12:32 UTC by NackUn

google blueprint 와 현석님 선민님 코드 많이 참고했습니다.

2019-06-19 14:01 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/data/DataSource.kt
> +        fun onTickersIsNull(err: String?)
함수명만 봤을 때에는 ticker가 null 인지에 대하여 전달하는 것으로 보이는데
파라미터에 전달할 에러 메시지는 ticker 가 null 이 아닐 경우에 대한 메시지도 있을 것이라 보입니다.
보다 명시적인 함수명으로 변경하는 것은 어떠신가요?

2019-06-19 14:24 UTC, BeokBeok requested changes
리뷰 작성하였습니다.

2019-06-19 14:24 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/data/remote/RemoteDataSource.kt
> +                lateinit var query: String
클래스 맴버변수가 아닌 함수 내에서 lateinit을 사용한 이유가 있나요?
이유가 있다면, var query: String 을 사용하지 않고 lateinit var query: String 을 사용했을 때 이점을 알고 싶습니다.

2019-06-19 14:24 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/data/DataSource.kt
> +        fun onTickersIsNull(err: String?)
함수명만 봤을 때에는 ticker가 null 인지에 대하여 전달하는 것으로 보이는데
파라미터에 전달할 에러 메시지는 ticker 가 null 이 아닐 경우에 대한 메시지도 있을 것이라 보입니다.
보다 명시적인 함수명으로 변경하는 것은 어떠신가요?

2019-06-19 14:24 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/main/MainContract.kt
> +        fun showTickes(tickers: ArrayList<Ticker>)
함수명에 오타가 있는 것 같습니다.
showTickers 로 보입니다.

2019-06-19 14:24 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/main/MainFragment.kt
> +                    var selectedMarket = v as TextView
변수 타입을 val로 해도 될 것 같습니다.

2019-06-19 14:24 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/res/layout/activity_main.xml
>          android:layout_width="match_parent" android:layout_height="match_parent"
code formatter를 사용하여 정리가 필요해 보입니다.

2019-06-19 14:24 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/res/layout/main_fragment.xml
> +        android:layout_width="match_parent" android:layout_height="match_parent"
code formatter를 사용하여 정리가 필요해 보입니다.

2019-06-19 14:24 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/res/layout/main_fragment.xml
> +            android:layout_marginLeft="12dp"
마진이나 패딩을 줄 경우,
Left 대신 Start를
Right 대신 End를 권장합니다.

2019-06-19 14:24 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/res/layout/main_fragment.xml
> +                android:textSize="20dp"
텍스트는 일반적으로 sp를 사용합니다.
의도가 있어서 dp를 사용하신 것이 아니라면, sp를 권장합니다.

2019-06-19 14:24 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/res/layout/main_fragment.xml
> +                xmlns:app="http://schemas.android.com/apk/res-auto"
xmlns 는 최상위 레이아웃에 정의 되어있으면 됩니다.
해당 부분은 불필요해 보입니다.

2019-06-20 12:54 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/data/remote/RemoteDataSource.kt
> +    private val service: DataSource.UpbitApi = retrofit.create(DataSource.UpbitApi::class.java)
변수를 2개 만들기 보다는
하나의 변수에서 retrofit을 build 및 create 하는 것은 어떤가요?

2019-06-20 12:54 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/data/remote/RemoteDataSource.kt
> +                        it.filter { item ->
coding conventions 참고하여 정리가 필요해보입니다.
https://kotlinlang.org/docs/reference/coding-conventions.html#chained-call-wrapping

2019-06-20 12:54 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/main/MainPresenter.kt
> +    override fun start() {
start 함수를 사용하지 않는다면, 제거하는 것이 나아보입니다.

2019-06-20 12:54 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/main/MainPresenter.kt
> +    //lateinit var arr:ArrayList<Ticker>
불필요한 주석은 제거하는 것이 좋습니다.
주석 처리 이후 계속 방치되는 경우가 많기 때문입니다.

2019-06-20 13:09 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/data/remote/RemoteDataSource.kt
> +                lateinit var query: String
변경했습니다.
fd877c5

2019-06-20 13:14 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/data/DataSource.kt
> +        fun onTickersIsNull(err: String?)
onGetError는 어떤가요?
9e02dd6

2019-06-20 13:17 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/main/MainContract.kt
> +        fun showTickes(tickers: ArrayList<Ticker>)
오타 수정했습니다
28822f3

2019-06-20 13:23 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/main/MainFragment.kt
> +                    var selectedMarket = v as TextView
변수 타입 변경했습니다. val로 변경하면 좋은 점이 있을까요?
검색해봤는데 코딩단계에서 버그발생확률을 낮추기위해서인가요?
efb6cbe

2019-06-20 13:25 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/res/layout/activity_main.xml
>          android:layout_width="match_parent" android:layout_height="match_parent"
변경했습니다.
e345f33

2019-06-20 13:26 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/res/layout/main_fragment.xml
> +        android:layout_width="match_parent" android:layout_height="match_parent"
정리했습니다. 전체 앱을 리포맷해서 올리는데 왜 layout_width랑 height만 붙어있을까요?
설정문제인가 확인해보겠습니다.
e345f33

2019-06-20 13:32 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/data/DataSource.kt
> +        fun onTickersIsNull(err: String?)
@NackUn 
정답은 없지만, onGetError 보다는 onError가 나아보입니다.
상용님의 판단에 맡기겠습니다.

2019-06-20 13:32 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/res/layout/main_fragment.xml
> +            android:layout_marginLeft="12dp"
변경했습니다. 딱히 차이는 없고 권장사항인가요?
56e6e75

2019-06-20 13:35 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/main/MainFragment.kt
> +                    var selectedMarket = v as TextView
val 로 하면 해당 변수는 read 만 가능합니다.
따라서, 불필요한 데이터가 저장되는 경우를 막을 수 있습니다.
정보보안관련 정보보호 원칙이긴 하지만 최소 권한의 원칙을 따르는 것이 좋습니다.

2019-06-20 13:36 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/res/layout/main_fragment.xml
> +                android:textSize="20dp"
감사합니다. 변경했습니다. 덕분에 sp, dp 다시 짚고 넘어가네요.
bff10d1

2019-06-20 13:38 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/res/layout/main_fragment.xml
> +                xmlns:app="http://schemas.android.com/apk/res-auto"
삭제했습니다.
ac33a04

2019-06-20 13:41 UTC, BeokBeok commented
@NackUn 
추가로, 커밋 시 규칙을 적용해주세요.
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/tree/master/sjjeong#pr-commit

2019-06-20 13:46 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/data/remote/RemoteDataSource.kt
> +    private val service: DataSource.UpbitApi = retrofit.create(DataSource.UpbitApi::class.java)
변경했습니다.
eea81fa

2019-06-20 13:53 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/data/remote/RemoteDataSource.kt
> +                        it.filter { item ->
정리했습니다. 항상 적용할 수 있도록 노력하겠습니다. 커밋 규칙도 적용했습니다.
83d1f7f

2019-06-20 13:53 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/res/layout/main_fragment.xml
> +            android:layout_marginLeft="12dp"
차이는 오른쪽에서 왼쪽으로 나타나는 언어 (아랍어, 힌디어 등)에서 문제가 발생합니다.
흔히 RTL (Right To Left) 언어라고 하며, 시간나시면 한번 검색해보세요

2019-06-20 13:57 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/main/MainPresenter.kt
> +    override fun start() {
presenter에 start()가 필요하다고 해서 넣었는데 제거하기 위해서 생각해보겠습니다.

2019-06-20 14:00 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/main/MainPresenter.kt
> +    //lateinit var arr:ArrayList<Ticker>
제거했습니다. 진짜 계속 방치되있는 경우가 많은 것 같습니다.
73d6c47

2019-06-20 14:05 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/data/DataSource.kt
> +        fun onTickersIsNull(err: String?)
넵! 변경했습니다.
1e8cc17

2019-06-20 14:07 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/main/MainFragment.kt
> +                    var selectedMarket = v as TextView
감사합니다. 정보보호를 위해서 사용하는 거였군요.

2019-06-20 14:08 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/res/layout/main_fragment.xml
> +            android:layout_marginLeft="12dp"
아 아랍쪽에선 반대로 쓰는 걸 알고 있습니다. 그게 여기서도 적용되서 start, end로 사용하는 거군요. 감사합니다!

2019-06-21 01:09 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/res/layout/main_fragment.xml
> +            android:layout_marginLeft="12dp"
@NackUn 
layout_marginLeft 와 layout_marginRight도 변경 바랍니다.

2019-06-21 01:32 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/data/remote/RemoteDataSource.kt
> +                        it.filter { item ->
@NackUn 
단순 파라미터가 하나이면 it을 써도 되지 않나요?
https://kotlinlang.org/docs/reference/lambdas.html#it-implicit-name-of-a-single-parameter

2019-06-21 07:05 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/res/layout/main_fragment.xml
> +            android:layout_marginLeft="12dp"
변경했습니다. 빼먹었는데 짚어주셔서 감사합니다.
f1b122b

2019-06-21 07:09 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/data/remote/RemoteDataSource.kt
> +                        it.filter { item ->
it을 사용했습니다
938a96f

2019-06-21 07:22 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/data/remote/RemoteDataSource.kt
> +                        it.filter { item ->
@NackUn 
joinToString 함수에도 적용 바랍니다.
또한, it 사용이 가능하다면 coding conventions 참고하여 정리 부탁 드립니다.
https://kotlinlang.org/docs/reference/coding-conventions.html#lambda-formatting

2019-06-21 22:38 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/data/remote/RemoteDataSource.kt
> +                        it.filter { item ->
변경하였습니다.
c2f82a1

2019-06-21 23:39 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/data/remote/RemoteDataSource.kt
> +                        it.filter { item ->
@NackUn 
coding conventions 이 적용 안된 것 같습니다.
https://kotlinlang.org/docs/reference/coding-conventions.html#chained-call-wrapping
재확인 바랍니다.

2019-06-22 02:24 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/data/remote/RemoteDataSource.kt
> +                        it.filter { item ->
이렇게 변경하면 될까요?
a0469db

2019-06-22 02:33 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/data/remote/RemoteDataSource.kt
> +                        it.filter { item ->
@NackUn 
네 맞습니다.

2019-06-22 02:35 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/main/MainPresenter.kt
> +    override fun start() {
제거했습니다
b5ae237

2019-06-22 02:37 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/main/MainPresenter.kt
> +    override fun start() {
@NackUn 
TextView 가 import 되어 있는데, 제거 바랍니다.

2019-06-24 11:48 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/main/MainPresenter.kt
> +    override fun start() {
제거했습니다.
b05d5e1

2019-06-26 03:16 UTC, NackUn commented
@BeokBeok 리뷰 부탁드립니다.

2019-06-26 03:49 UTC, BeokBeok requested changes
리뷰 작성하였습니다.

2019-06-26 03:49 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/Base/BaseFragment.kt
> +        return  inflater.inflate(layoutRes, container, false)
단일 표현 함수 관련하여 정리해 주세요
https://kotlinlang.org/docs/reference/functions.html#single-expression-functions

2019-06-26 03:49 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/Base/BasePresenter.kt
> +}
구현부가 없는 인터페이스는 중괄호 생략이 가능합니다.

2019-06-26 03:49 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/data/DataSource.kt
> +        fun onTickersLoaded(tickers: ArrayList<Ticker>)
파라미터를 ArrayList가 아닌 List 형태로 바꿔주세요.
OOP 5원칙 중 리스코브 치환의 원칙 참고하세요

2019-06-26 03:49 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/data/remote/RemoteDataSource.kt
> +    private val retrofitService = retrofitService
불필요한 변수 선언으로 보입니다.

2019-06-26 03:49 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/data/remote/RemoteDataSource.kt
> +                    callback.onError("Don't request Tickers")
에러 문구를 보내는 것 보다는 IllegalStateException 과 같은 예외를 던지는 방향으로 하는 것을 권장합니다.

2019-06-26 03:49 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/main/MainActivity.kt
> +        setContentView(R.layout.activity_main)
BaseActivity를 생성하여 레이아웃 ID를 전달하여 구현하시면
MainActivity가 보다 간결해질 수 있습니다.

2019-06-26 03:49 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/main/MainContract.kt
> +        fun showTickers(tickers: ArrayList<Ticker>)
파라미터를 ArrayList가 아닌 List 형태로 바꿔주세요.
OOP 5원칙 중 리스코브 치환의 원칙 참고하세요

2019-06-26 03:49 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/main/MainFragment.kt
> +                .baseUrl("https://api.upbit.com/v1/")
url 범위를 api.upbit.com 까지 하시는 것을 권장합니다

2019-06-26 03:49 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/ui/TickerAdapter.kt
> +    protected val items = mutableListOf<Ticker>()
접근자를 protected로 한 이유를 알고 싶습니다.

2019-06-26 03:49 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/ui/TickerAdapter.kt
> +//        @LayoutRes layoutRes: Int,
불필요한 주석은 제거해주세요

2019-06-26 03:49 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/ui/TickerAdapter.kt
> +        return TickerViewHolder(LayoutInflater.from(parent.context).inflate(R.layout.ticker_item, parent, false))
단일 표현 함수 관련하여 정리해 주세요
https://kotlinlang.org/docs/reference/functions.html#single-expression-functions

2019-06-26 03:49 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/ui/TickerAdapter.kt
> +        val tickerName = view.tickerName
ViewHolder 에서는 itemView를 제공하고 있습니다.
itemView를 사용하는 것을 권장합니다.

2019-06-26 03:49 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/ui/TickerAdapter.kt
> +            tickerName.text = TickerFormatter.convertTo(item)["tickerName"]
ViewHolder에서 연산을 하게 되면 속도가 저하됩니다.
연산은 외부에서 진행하여 가공된 데이터를 Adapter에 전달하는 것을 권장합니다.

2019-06-26 03:49 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/util/TickerFormatter.kt
> +            mutableMapOf(
convertItem 생성 이후 데이터의 가공이나 삭제가 없다면,
mutableMap이 아닌 일반 map을 권장합니다.

2019-06-26 03:49 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/util/TickerFormatter.kt
> +        when {
when 앞에 return을 붙이면, 각 case 별로 return을 붙이지 않아도 됩니다.

2019-06-26 03:49 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/util/TickerFormatter.kt
> +        String.format("%.2f", differPrice) + "%"
"%.2f%" 이렇게 표현해도 될 것 같습니다.

2019-06-26 03:49 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/res/layout/main_fragment.xml
> +            android:layout_alignParentLeft="true"
Left 는 Start로 변경해주세요

2019-06-26 03:49 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/res/layout/main_fragment.xml
> +            android:layout_below="@+id/tv_market_title"
id 생성 이외에는 +를 붙이지 않습니다.

2019-06-26 03:49 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/res/layout/main_fragment.xml
> +<?xml version="1.0" encoding="utf-8"?>
code rearrange 해주세요

2019-06-26 03:49 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/res/layout/ticker_item.xml
> +        android:layout_height="wrap_content" xmlns:tools="http://schemas.android.com/tools"
xmlns 는 상단에 위치해 주세요

2019-06-26 13:33 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/Base/BaseFragment.kt
> +        return  inflater.inflate(layoutRes, container, false)
적용했습니다
159c2a3

2019-06-26 13:35 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/Base/BasePresenter.kt
> +}
생략했습니다.
0248bce

2019-06-26 13:38 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/data/DataSource.kt
> +        fun onTickersLoaded(tickers: ArrayList<Ticker>)
변경했습니다. 감사합니다 리스코브 치환의 원칙을 검색해보겠습니다.
4a18535

2019-06-26 13:41 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/data/remote/RemoteDataSource.kt
> +    private val retrofitService = retrofitService
제거했습니다.
e137450

2019-06-26 13:46 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/main/MainActivity.kt
> +        setContentView(R.layout.activity_main)
BaseActivity 를 만들었습니다
de8a41c

2019-06-26 13:46 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/main/MainContract.kt
> +        fun showTickers(tickers: ArrayList<Ticker>)
변경했습니다. 감사합니다 리스코브 치환의 원칙을 검색해보겠습니다.
4a18535

2019-06-26 13:47 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/ui/TickerAdapter.kt
> +    protected val items = mutableListOf<Ticker>()
석준님의 SimpleRecyclerView 따라했는데 나중에 재사용하기 위해서 아닌가요?

2019-06-26 13:48 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/ui/TickerAdapter.kt
> +//        @LayoutRes layoutRes: Int,
지금 뷰홀더 축약이 안되네요... 축약을 하면 바인드가 제대로 안됩니다. 확인 후 주석 지우도록 하겠습니다.

2019-06-26 13:48 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/ui/TickerAdapter.kt
> +        return TickerViewHolder(LayoutInflater.from(parent.context).inflate(R.layout.ticker_item, parent, false))
적용했습니다
159c2a3

2019-06-26 13:55 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/ui/TickerAdapter.kt
> +        val tickerName = view.tickerName
와.. 안되는 이유가 바인더에 view 문제였네요. itemView로 하니 해결됬습니다. 감사합니다!! 
621bd6d

2019-06-26 13:55 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/ui/TickerAdapter.kt
> +//        @LayoutRes layoutRes: Int,
제거했습니다.
621bd6d

2019-06-26 13:56 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/res/layout/ticker_item.xml
> +        android:layout_height="wrap_content" xmlns:tools="http://schemas.android.com/tools"
넵 상단으로 옮겼습니다.
0ea97f7

2019-06-26 14:00 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/res/layout/main_fragment.xml
> +            android:layout_below="@+id/tv_market_title"
제거했습니다.
8f84677

2019-06-26 14:04 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/res/layout/main_fragment.xml
> +            android:layout_alignParentLeft="true"
변경했습니다. rounded.xml에 android:bottomLeftRadius 요기는 Start가 안되는 것 같습니다.
f5fde79

2019-06-26 14:06 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/util/TickerFormatter.kt
> +        String.format("%.2f", differPrice) + "%"
동작을 안하네요..포맷 인식을 못하는 것 같습니다.

2019-06-26 14:08 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/util/TickerFormatter.kt
> +        when {
return 하나씩 다 써줬는데.. 이제 그럴 필요가 없네요. 감사합니다!
12eeb50

2019-06-26 14:11 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/util/TickerFormatter.kt
> +            mutableMapOf(
변경했습니다.
2f79413

2019-06-26 14:13 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/ui/TickerAdapter.kt
> +            tickerName.text = TickerFormatter.convertTo(item)["tickerName"]
@BeokBeok  음.. 외부에서 진행한다는 것이 바인드 하기 전에 다른 곳에서 계산을 끝내놓고 값만 전달하라는 말씀이신가요?

2019-06-26 14:35 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/data/remote/RemoteDataSource.kt
> +                    callback.onError("Don't request Tickers")
이렇게 구현하면 될까요?
81c3456

2019-06-26 14:37 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/main/MainFragment.kt
> +                .baseUrl("https://api.upbit.com/v1/")
수정하였습니다.
aa6aff8

2019-06-26 14:42 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/res/layout/main_fragment.xml
> +<?xml version="1.0" encoding="utf-8"?>
코드 정리했습니다.
5c22e62

2019-06-27 01:34 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/data/remote/RemoteDataSource.kt
> +                    callback.onError("Don't request Tickers")
@NackUn 
링크한 commit id에 comment 작성하였습니다.

2019-06-27 01:36 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/ui/TickerAdapter.kt
> +    protected val items = mutableListOf<Ticker>()
@NackUn 
석준님이 만든 View 에는 해당 변수를 재사용을 하고 있기 때문에 protected로 하신 것 같습니다.
상용님 프로젝트에서 protected 접근자의 의미가 없다면, 바꾸는 것이 맞는 것 같습니다.

2019-06-27 01:37 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/ui/TickerAdapter.kt
> +            tickerName.text = TickerFormatter.convertTo(item)["tickerName"]
@NackUn 
네, 맞습니다.

2019-06-27 01:39 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/util/TickerFormatter.kt
> +        String.format("%.2f", differPrice) + "%"
제가 DecimalFormat과 햇갈린 상태로 리뷰한 것 같습니다.

2019-06-27 02:05 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/ui/TickerAdapter.kt
> +    protected val items = mutableListOf<Ticker>()
수정했습니다. 감사합니다!
c137885

2019-06-27 02:07 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/data/remote/RemoteDataSource.kt
> +                    callback.onError("Don't request Tickers")
수정했습니다
7dd0d12

2019-06-27 02:45 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/ui/TickerAdapter.kt
> +            tickerName.text = TickerFormatter.convertTo(item)["tickerName"]
수정했습니다.
c029dd3

2019-06-27 03:02 UTC, NackUn commented
메인프래그먼트의 셋 클릭, 셋 컬러 작성했습니다.
0b86fe9

2019-06-27 04:51 UTC, BeokBeok submitted a review, later dismissed
수고하셨습니다~

2019-06-28 04:44 UTC, sjjeong requested changes
고생하셨어요

2019-06-28 04:44 UTC, sjjeong commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/ui/TickerAdapter.kt
> +    @LayoutRes private val layoutRes: Int
이 Adapter는 TickerAdapter라는 특정 Adapter이기 때문에 layoutRes를 받을 필요는 없을 것 같아요
ViewHolder에 직접 R.layout.xx으로 사용하면 됩니다.

2019-06-28 04:44 UTC, sjjeong commented on NackUn/StudyFirst/app/src/test/java/sample/nackun/com/studyfirst/ExampleUnitTest.kt
> +        println("a = $a b = $b");
이건 왜 올라왔나요? ㅋㅋ

2019-06-28 15:40 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/ui/TickerAdapter.kt
> +    @LayoutRes private val layoutRes: Int
변경했습니다
27de6c8

2019-06-28 15:42 UTC, NackUn commented on NackUn/StudyFirst/app/src/test/java/sample/nackun/com/studyfirst/ExampleUnitTest.kt
> +        println("a = $a b = $b");
ㅋㅋㅋㅋ 지웠습니다 (파일을 지워야되나요??)
6983fa5

2019-06-29 00:17 UTC, sjjeong commented on NackUn/StudyFirst/app/src/test/java/sample/nackun/com/studyfirst/ExampleUnitTest.kt
> +        println("a = $a b = $b");
아니요 괜찮습니다 ㅋㅋ

2019-06-29 00:17 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-06-29 02:14 UTC, BeokBeok approved these changes

2019-06-30 06:30 UTC, merged