HW-8 Multi Module(멀티모듈 적용)
sjjeong/GoogryAndroidArchitecutreStudy pull request #672
Opened 2020-06-07 10:23 UTC by TaeseongYun

마지막 리뷰 부탁드리겠습니다.

용재님, 석준님 8주동안 수고많으셨습니다 : )

2020-07-01 08:56 UTC, ghost reviewed
app - domain, data, remote, presentation
domain - data
presentation - data, domain
remote - data
이렇게 implementation 하고 있는거 같습니다. 저도 아직 모듈의 관계를 어떻게 짜줘야 좋은지 잘 모르지만 presentation module은 domain만 implementation 해주는 것은 어떤지 궁금합니다.
석준님에게 어떤 구조가 좋은 것인지 여쭤보는게 좋을거 같습니다.
Q. data module을 domain이 implementation하는 상황에서 presentation module이 data와 domain module을 implementation 하는 것이 좋은 것인지?

2020-07-01 09:02 UTC, TaeseongYun commented
저도 이번이 처음이라 반신반의하며 코드를 작성했는데 용재님 말 처럼 멘토님의 말을 한번 들어봐야겠네요.

2020-07-02 14:20 UTC, sjjeong requested changes
domain 개념까지 넣으셨다면 clean architecture를 고려하신 것 같은데
https://github.com/bufferapp/android-clean-architecture-boilerplate
이거 보시고 반영해보도록 해보세요

2020-07-11 09:49 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋
고생하셨어요~

2020-07-22 15:38 UTC, merged