HW-5 MVVM dataBinding
sjjeong/GoogryAndroidArchitecutreStudy pull request #676
Opened 2020-06-08 15:07 UTC by developer-sungjae

- XML 변수 Activity 삭제 및 ViewModel 추가
- adapter Item 추가 뷰모델 연관 로직으로 수행
- toast 메세지 뷰모델 연관 로직으로 수행
- 검색결과 알림 문자 뷰모델 연관 로직으로 수행
- String resource를 Viewmodel에서 쓰기 위해 CustomApp, Strings Object 구현

2020-06-08 19:29 UTC, chuuuul requested changes
안녕하세요~

2020-06-08 19:29 UTC, chuuuul commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/ui/search/SearchViewModel.kt
> +        tvResultVisible.set(View.GONE)
``` val tvResultVisible = ObservableField<Int>(View.GONE)```
으로 초기화 할 수 있습니다.

2020-06-08 19:29 UTC, chuuuul commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/res/layout/activity_search.xml
>              name="searchWord"
searchWord가 ViewModel에도 있고 XML에도 중복되서 존재하는 것 같습니다!

2020-06-08 19:29 UTC, chuuuul commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/res/layout/activity_search.xml
> +            refinedString="@{String.format(@string/tv_result_text, searchWord)}"
1. refinedString라는 Adapter Binding 이 필요 없을 것 같습니다.

```
android:text="@{String.format(@string/tv_result_text, searchWord)}"
```
로 작성 하셔도 같은 동작을 할 것 같습니다.

2. 아래의
``` android:visibility="@{vm.tvResultVisible}" ```
코드로 textview의 visible이 set 되고 있으므로 refinedString라는 Adapter binding에서 다시 설정 할 필요가 없습니다.

2020-06-08 19:29 UTC, chuuuul commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/AndroidManifest.xml
> +        android:name=".CustomApp"
CustomApp은 어떤 용도로 만드셨는지 잘 모르겠어서 질문 드립니다!

2020-06-08 19:29 UTC, chuuuul commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/ui/search/SearchViewModel.kt
> +    val showToast = ObservableField<String>()
Toast 띄우는 방법을 석준님께서 알려주신 방법 말고 다른방법으로 하셨네요!

성재님께서 구현하신 방법이라면

#### 원 코드
```
// 선언
val showToast = ObservableField<String>()

// ViewModel에서의 set
showToast.set(Strings.get(R.string.get_local_data_success))

// Activity의 Callback
vm.showToast.addOnPropertyChangedCallback(object : Observable.OnPropertyChangedCallback() {
      override fun onPropertyChanged(sender: Observable?, propertyId: Int) {
          val msg = vm.showToast.get().toString()
          handler.postDelayed({ toast(msg) }, 0)
     }
})
```

#### 제안드리는 코드
```
//선언
val showToast = ObservableField<@StringRes Int>()

// ViewModel에서의 set
showToast.set(R.string.get_local_data_success)

// Activity의 Callback

vm.showToast.addOnPropertyChangedCallback(object : Observable.OnPropertyChangedCallback() {
      override fun onPropertyChanged(sender: Observable?, propertyId: Int) {
           val msg =  getString(vm.showToast.get()?:return)
           handler.postDelayed({ toast(msg) }, 0)
     }
 })
```

제안된 방법으로 하시면 직접 작성하신 Strings 클래스도 필요 없을 것 같고,
CustomApp Class도 해당 과정을 위해서 작성하신것이 맞다면 사용하실 필요 없을 것 같습니다.


#### 석준님 방법
추가로 석준님께서 스터디중 말씀해주신 방법 적어드리겠습니다!
```
//ViewModel
val showToast = ObservableField<Unit>()

//Activity
vm.showToast.addOnPropertyChangedCallback(object :
    OnPropertyChangedCallback() {
        override fun onPropertyChanged(sender: Observable?, propertyId: Int) {
            Toast.makeToast( ... ).show()
        }
    })

// Toast 발생
showToast.notifyChange()

```

2020-06-10 13:58 UTC, SageHabitus commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/ui/search/SearchViewModel.kt
> +        tvResultVisible.set(View.GONE)
감사합니다. 수정하였습니다.
0f12c34

2020-06-10 14:02 UTC, SageHabitus commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/res/layout/activity_search.xml
>              name="searchWord"
감사합니다. 수정하였습니다.
d2937d0

2020-06-10 14:05 UTC, SageHabitus commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/res/layout/activity_search.xml
> +            refinedString="@{String.format(@string/tv_result_text, searchWord)}"
그렇네요! 감사합니다. 수정하였습니다
5cc7d5f

2020-06-10 14:24 UTC, SageHabitus commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/AndroidManifest.xml
> +        android:name=".CustomApp"
밑의 코멘트로 인하여 삭제하였습니다. 감사합니다.
0d87429

2020-06-10 14:25 UTC, SageHabitus commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/ui/search/SearchViewModel.kt
> +    val showToast = ObservableField<String>()
갓철님 자세한 피드백 정말 감사합니다. 수정하였습니다. 감사합니다.
0d87429
1972f02

2020-06-10 16:23 UTC, chuuuul requested changes
하나만 더 고치시면 될 것 같습니다!

2020-06-10 16:23 UTC, chuuuul commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/AndroidManifest.xml
> +        android:name=".CustomApp"
```android:name=".CustomApp"```
부분은 지워도 될 것 같습니다~

2020-06-10 23:34 UTC, developer-sungjae commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/AndroidManifest.xml
> +        android:name=".CustomApp"
수정하였습니다.
992ef74

2020-06-11 07:48 UTC, chuuuul approved these changes
수고하셨습니다!

2020-06-11 17:03 UTC, sjjeong requested changes

2020-06-11 17:03 UTC, sjjeong commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/ui/search/SearchActivity.kt
> +        vm.getMovieListFromLocal()
여기서 호출할 필요 없이 ViewModel init에서 호출해주세요

2020-06-12 12:33 UTC, developer-sungjae commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/ui/search/SearchActivity.kt
> +        vm.getMovieListFromLocal()
감사합니다 수정하였습니다.
eeef176

2020-06-13 03:46 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-06-13 04:24 UTC, merged

2020-06-13 05:32 UTC, 2giwon commented
오오!
2020년 6월 13일 (토) 오후 1:25, Sungjae <notifications@github.com>님이 작성:

> Merged #676
> <https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/676>
> into 2005/developer-sungjae.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/676#event-3440442915>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACNLW4FJKLRLFWY4SMMSAZTRWL5RXANCNFSM4NYP7T6Q>
> .
>