HW-5 MVVM
sjjeong/GoogryAndroidArchitecutreStudy pull request #677
Opened 2020-06-09 04:38 UTC by sangjinKIM93

map -> mvvm  변경

*특이사항
- pc를 바꾸면서 안드로이드 스튜디오를 4.0으로 변경하였습니다.

2020-06-11 14:36 UTC, RyuC0605 reviewed
이걸 안하면 최종적으로 리뷰가 안가나 보네요?
몰랐던거 하나 또 배워갑니다.

2020-06-11 14:36 UTC, RyuC0605 commented on 2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/MovieListViewModel.kt
> +    }
복잡하게 추출하는것 보다, 검색어를 간단하게 sharedpreferences 같은곳에 저장하는건 어떨까요?
실제로 검색 시 띄어쓰기가 있으면 엉뚱한 검색어를 추출하네요

2020-06-11 14:36 UTC, RyuC0605 commented on 2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/MovieListActivity.kt
> +        }
ObservableField 를 사용하셨다면 XML 에 설정하는 것으로 자동 SET이 됩니다. 필요 없는 코드로 생각 됩니다.

2020-06-11 14:36 UTC, RyuC0605 commented on 2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/MovieListViewModel.kt
> +    var hideKeypad = ObservableField<Unit>()
``` var hideKeypad = ObservableField<Boolean>()```
으로 만들고 addOnPropertyChangedCallback 에서
get() 값이 true / false 일때 숨김/.보임 으로 하는것도 나쁘지 않아 보입니다.

2020-06-11 14:36 UTC, RyuC0605 commented on 2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/MovieListViewModel.kt
> +                    disposables.add(it)
disposables.add(it) 이 뭐하는 코드인지 짧게 설명해 주시겠어요?

2020-06-11 14:36 UTC, RyuC0605 commented on 2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/MovieListViewModel.kt
> +    val hideKeypad = _hideKeypad
val toastMsgNoKeyword = ObservableField<Unit>() 로 선언/초기화를 하지 않고
_toastMsgNoKeyword 를 만드신 이유를 설명해 주세요.

2020-06-11 14:36 UTC, RyuC0605 commented on 2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/MovieListActivity.kt
> -
리뷰를 하다보니 이미 작업을 하셨네요 ^^;;;

2020-06-12 01:11 UTC, sangjinKIM93 commented on 2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/MovieListViewModel.kt
> +                    disposables.add(it)
compositeDisposable의 객체로 Observable들을 하나의 묶음으로 관리해 이들을 lifeCycle에 맞게 해제할 수 있게 도와줍니다. 
여기서 .add()는 List에 element를 추가하듯이 compositeDisposable에 observable을 추가하는 것입니다.

2020-06-12 01:12 UTC, sangjinKIM93 commented on 2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/MovieListActivity.kt
> +        }
제가 이 부분은 나중에 깨달아서 말씀해주신 것처럼 추후 커밋에 수정하였습니다:)

2020-06-12 02:42 UTC, sangjinKIM93 commented on 2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/MovieListViewModel.kt
> +    var hideKeypad = ObservableField<Unit>()
좋은 의견 감사합니다!
추천해주신 방법을 시도해봤는데 이 경우 최초 검색에는 hidekeypad가 호출 되지만 이후 검색에는 hidekeypad가 호출되지 않는 문제가 있습니다 (showkeypad = false 인 상태라 false를 set해도 observer에게 notify가 되지 않는 것 같습니다.)
물론 변경 이후 notifyChange()한줄을 추가해주면 문제가 해결되는데 그러면 기존의 제 방식에서 크게 바뀌지 않는 것 같아서 일단은 수정하지 않았습니다.

2020-06-12 04:45 UTC, sangjinKIM93 commented on 2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/MovieListViewModel.kt
> +    val hideKeypad = _hideKeypad
변수를 private으로 보호하기 위해서 일종의 getter 역할을 하는 변수를 만든 것입니다.
_toastMsgNoKeyword는 클래스 private var로 선언하여 내부에서 변수를 수정시 사용하고 toastMsgNokeyword는 private이 없는 val로 선언하여 다른 클래스에서 해당 변수에 접근할 수는 있지만 변경할 수는 없게 만든것입니다.

(그리고 toastMsg관련 승윤님이 한 것처럼 toastMsgRes, toastMsgString이 더 코드를 줄일 수 있어 참고하여 수정하였습니다.)

2020-06-12 05:59 UTC, sangjinKIM93 commented on 2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/MovieListViewModel.kt
> +    }
지금 방식으로는 빈틈이 많군요.. sharedPref를 활용한 방식으로 수정하였습니다.

b2a2b22

2020-06-12 05:59 UTC, sangjinKIM93 commented on 2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/MovieListActivity.kt
> -
뒤늦게 생각이 나서 ㅎㅎ

2020-06-12 13:21 UTC, RyuC0605 approved these changes

2020-06-13 07:53 UTC, sjjeong requested changes

2020-06-13 07:53 UTC, sjjeong commented on 2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/MovieListViewModel.kt
> +    private var _hideKeypad = ObservableField<Boolean>()
값을 사용하지 않으니 Unit으로 하면 됩니다.

2020-06-14 00:38 UTC, sangjinKIM93 commented on 2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/MovieListViewModel.kt
> +    private var _hideKeypad = ObservableField<Boolean>()
수정했습니다!
a182600

2020-06-14 02:17 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-06-14 08:04 UTC, merged