HW-5 MVP -> MVVM
sjjeong/GoogryAndroidArchitecutreStudy pull request #678
Opened 2020-06-09 14:06 UTC by hwaniiidev

- MVP 패턴으로 동작 중인 기능 MVVM으로 대체 
- recyclerview, 검색결과에 따른 안내 텍스트 dataBinding으로 대체

2020-06-10 06:36 UTC, LeeChungWoo92 commented
안녕하세요!
현재  검색어를 입력했다가 다지우고 검색버튼을 누르면 토스트가잘뜨는데 
앱 실행하자마자 검색버튼을 누르면 앱이 종료됩니다. 확인부탁드리겠습니다!!

2020-06-10 07:01 UTC, LeeChungWoo92 requested changes

2020-06-10 07:01 UTC, LeeChungWoo92 commented on 2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/ui/main/MainDataBindingExtension.kt
> +}
저는 값 넣는 부분을   RecyclerView에 inflate한 xml에서   data class를   databinding 으로 넣어주는식으로 하고
html 변환해야되는 부분만 BindingAdapter에 함수로 구현했습니다

2020-06-10 07:15 UTC, LeeChungWoo92 requested changes

2020-06-10 07:15 UTC, LeeChungWoo92 commented on 2005/hwaniiidev/Architecture/app/src/main/res/layout/activity_main.xml
>              app:layout_constraintBottom_toBottomOf="parent"
[개인적인생각입니다]
android:visibility 하실 때    BindingAdapter로 함수 만들어서하시면 <import type="android.view.View">도 필요없고
관리하기 편할것같습니다.!

2020-06-10 07:29 UTC, LeeChungWoo92 requested changes

2020-06-10 07:29 UTC, LeeChungWoo92 commented on 2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/ui/main/MainActivity.kt
>          toast("네트워크에 연결할 수 없습니다. 네트워크 연결을 확인해주세요.")
Toast 함수들중에 메세지만 다른 함수가 여러개있는데 
만들어두신  private fun toast(message: String) 이 함수하나로 메세지만 바꾸면서 쓰시는게 좋을것같습니다.

2020-06-10 07:35 UTC, LeeChungWoo92 requested changes

2020-06-10 07:35 UTC, LeeChungWoo92 commented on 2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/ui/main/MainViewModel.kt
> +        const val ERROR_QUERY_IS_NONE = 6
현재  val error = ObservableField<Int>() 가 하는일이 최종적으로 토스트메세지 보여주고있는것같은데 
toast  ObservableField를 만들어서  error.set이 들어가는자리에 tost.set이 들어가면 어떨까요?

2020-06-11 13:15 UTC, hwaniiidev commented
앱 처음 실행하자마자 빈 검색어 검색하면 죽는 버그 수정했습니다
861c0a1

2020-06-11 13:21 UTC, hwaniiidev commented on 2005/hwaniiidev/Architecture/app/src/main/res/layout/activity_main.xml
>              app:layout_constraintBottom_toBottomOf="parent"
아! 무슨 말인지 알겠어요
근데 저 개인적으로는 저 정도 길이의 코드는 괜찮다고 생각해요.
오히려 더 직관적이고 관리가 편하지 않을까 생각했습니다.
BindingAdapter 함수로 만들면 1단계 타고 들어가야 하기도 하고 불필요한 함수만 늘어나고,
흔하진 않겠지만 비슷한 류의 함수들이 많아지면 올 수도 있을 거 같아요

2020-06-11 22:59 UTC, hwaniiidev commented on 2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/ui/main/MainDataBindingExtension.kt
> +}
dfbda8a
수정했습니다. 불필요하게 Extension늘릴 필요가 없네요

2020-06-11 23:27 UTC, hwaniiidev commented on 2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/ui/main/MainActivity.kt
>          toast("네트워크에 연결할 수 없습니다. 네트워크 연결을 확인해주세요.")
56d0cee
수정했습니다. 불필요한 함수들 제거 할 수 있어서 확실히 좋네요

2020-06-11 23:29 UTC, hwaniiidev commented on 2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/ui/main/MainViewModel.kt
> +        const val ERROR_QUERY_IS_NONE = 6
말씀하신 방법도 나쁘진 않은데 activity에서 toast로 보여줄지 alert로 보여줄지 모를 수 있는 상황에서는 명시적으로 toast 출력해라! 하는 것보단 error 상황임을 전달만 하는게 더 좋을 것 같습니다.

2020-06-12 02:21 UTC, LeeChungWoo92 commented
수고하셨습니다!!

2020-06-12 05:38 UTC, LeeChungWoo92 approved these changes

2020-06-13 08:02 UTC, sjjeong requested changes

2020-06-13 08:02 UTC, sjjeong commented on 2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/ui/main/AdapterMovieList.kt
> +        itemData.subtitle = "서브제목 : ${itemData.subtitle}"
이렇게 하지 마시고 strings.xml에 res를 추가해서 사용하면 좋을 것 같습니다.
```xml
android:text="@{@string/res_name(movieItem.subtitle)}
```

2020-06-13 08:02 UTC, sjjeong commented on 2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/ui/main/MainActivity.kt
> +                }
이거보다 enum을 만들고 enum에 string res 를 가지고 있으면 좋을 것 같습니다.

2020-06-13 08:02 UTC, sjjeong commented on 2005/hwaniiidev/Architecture/app/src/main/res/layout/activity_main.xml
> +                android:text="@={searchValue}" />
searchValue를 xml에서 가지고 있지 않고 ViewModel에서 가지고 있도록 해주세요

2020-06-13 14:32 UTC, hwaniiidev commented on 2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/ui/main/MainActivity.kt
> +                }
a706c95
수정했습니다

2020-06-13 23:24 UTC, hwaniiidev commented on 2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/ui/main/AdapterMovieList.kt
> +        itemData.subtitle = "서브제목 : ${itemData.subtitle}"
2bef622
9859a77수정했습니다~~
석준님 위와 같은 방법이나 string.format으로 관리했을 때의 장점들이 확실한가요??

2020-06-13 23:38 UTC, hwaniiidev commented on 2005/hwaniiidev/Architecture/app/src/main/res/layout/activity_main.xml
> +                android:text="@={searchValue}" />
ea13fec
수정했습니다. 
xml에서 searchValue가 어떤 연산이 일어날 게 아니고 단순 매개변수에 들어가기만 할 뿐이라 viewmovel에서 searchValue를 갖고 있도록 하라고 하신거 같은데 맞나요?
xml에서 변수를 갖고 있으면 안되는 이유라도 있나요??

2020-06-14 02:20 UTC, sjjeong commented on 2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/ui/main/AdapterMovieList.kt
> +        itemData.subtitle = "서브제목 : ${itemData.subtitle}"
TextView에 어떤 text가 들어가는지 확인하기 위해 여러곳을 볼 필요 없이 xml에 정의된 곳만 보게 되는 장점이 있습니다
신환님이 작업하신 것처럼 ViewHolder에서 data class 내용을 바꾸게 된다면 데이터에 영향을 받는 부분이 늘어나기 때문에 유지보수하기 어려운 점이 있습니다

2020-06-14 02:26 UTC, sjjeong commented on 2005/hwaniiidev/Architecture/app/src/main/res/layout/activity_main.xml
> +                android:text="@={searchValue}" />
mvvm에서는 view에 보여지는 데이터들은 vm에서 관리해야 하기 때문에 ViewModel로 옮기는 거에요

2020-06-14 02:26 UTC, sjjeong requested changes

2020-06-14 02:26 UTC, sjjeong commented on 2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/model/Item.kt
> +    @ColumnInfo(name = "user_rating") var userRating: String
다시 val로 변경해주세요

2020-06-14 10:11 UTC, hwaniiidev commented on 2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/model/Item.kt
> +    @ColumnInfo(name = "user_rating") var userRating: String
92334b6
변경했습니다

2020-06-14 15:29 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-06-14 22:51 UTC, merged