HW-5 MVVM(databinding)적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #679
Opened 2020-06-10 01:53 UTC by LeeChungWoo92

기존 코드를 MVVM으로 변경하였습니다.

2020-06-11 13:04 UTC, hwaniiidev commented on 2005/leechungwoo92/StudyForkProject/app/src/main/java/com/lllccww/studyforkproject/ui/main/MainActivity.kt
> +        movieRemoteDataSource = MovieRemoteDataSourceImpl()
movieRemoteDataSource를 NaverMovieRepositoryImpl 내에서 바로 생성 할 수 있을 거 같아요

2020-06-11 13:04 UTC, hwaniiidev commented on 2005/leechungwoo92/StudyForkProject/app/src/main/java/com/lllccww/studyforkproject/ui/main/MainViewModel.kt
> +        if (inputQuery.isNullOrBlank()) {
검색 결과가 있는 검색어로 검색한 후 빈 칸을 검색하니 아무런 반응이 없습니다. 예외 처리가 필요할 거 같아요

2020-06-11 13:04 UTC, hwaniiidev commented on 2005/leechungwoo92/StudyForkProject/app/src/main/java/com/lllccww/studyforkproject/ui/main/MainActivity.kt
>          binding.rvMovieList.adapter = movieListAdapter
adapter를 Extension에서 set해줄 수 있더라고요. 혹시 activity에서 코드를 줄이고 싶으시다면 한 번 해봐도 좋을 것 같습니다. 
참고만 하셔요

2020-06-12 01:11 UTC, hwaniiidev commented
이 외에는 문제 없어 보입니다!

2020-06-12 05:01 UTC, LeeChungWoo92 commented on 2005/leechungwoo92/StudyForkProject/app/src/main/java/com/lllccww/studyforkproject/ui/main/MainViewModel.kt
> +        if (inputQuery.isNullOrBlank()) {
8bcc672
토스트들이 최초한번만 실행되고 그다음부터는 안되는 버그가 있었네요 
수정하였습니다!  notifyChange()를 해주니까 되던데 
혹시 버그생긴이유가 ObservableField로 선언한 변수가 값이 달라지지않아서 작동을안햇던건가요?

2020-06-12 05:14 UTC, LeeChungWoo92 commented on 2005/leechungwoo92/StudyForkProject/app/src/main/java/com/lllccww/studyforkproject/ui/main/MainActivity.kt
> +        movieRemoteDataSource = MovieRemoteDataSourceImpl()
MainActivity 말고 MovieRemoteDataSourceImpl()클래스 안에서 생성하라는 
말씀이신가요 !??

2020-06-12 05:31 UTC, LeeChungWoo92 commented on 2005/leechungwoo92/StudyForkProject/app/src/main/java/com/lllccww/studyforkproject/ui/main/MainActivity.kt
> +        movieRemoteDataSource = MovieRemoteDataSourceImpl()
fd58cd7
이런식으로 한번 수정해봤습니다

2020-06-12 05:32 UTC, LeeChungWoo92 commented on 2005/leechungwoo92/StudyForkProject/app/src/main/java/com/lllccww/studyforkproject/ui/main/MainActivity.kt
>          binding.rvMovieList.adapter = movieListAdapter
오 좋은기능이네요 찾아보려고하는데 검색이잘안되서 
혹시 어떤 키워드로 검색해봐야하나요??

2020-06-12 13:31 UTC, hwaniiidev commented on 2005/leechungwoo92/StudyForkProject/app/src/main/java/com/lllccww/studyforkproject/ui/main/MainActivity.kt
> +        movieRemoteDataSource = MovieRemoteDataSourceImpl()
구체적으로 말씀드리자면 MovieRemoteDataSourceImpl도 그렇고 NaverMovieRepositoryImpl도 MainActivity에서 생성자로 만든다음 ViewModel 생성 시 파라미터로 넣어 줄 필요가 없다고 생각해요.
MainActivity에서 MovieRemoteDataSourceImpl 나 NaverMovieRepositoryImpl 가 쓰일게 아니기 때문에 ViewModel class에서 바로 생성해주는 거죠. 
수정하신 대로 진행하셔도 전혀 문제 없지만 Activity와의 의존성?? 을 최소화하는게  mvvm을 사용하는 목적이지 않을까 싶습니다

2020-06-12 13:40 UTC, hwaniiidev commented on 2005/leechungwoo92/StudyForkProject/app/src/main/java/com/lllccww/studyforkproject/ui/main/MainActivity.kt
>          binding.rvMovieList.adapter = movieListAdapter
저는 석준님이 구현하신 simpleRecyclerview 참고 했어요 
https://github.com/sjjeong/SimpleRecyclerView
어떤 기능이라기 보단 extension에서 rv의 adapter를 가져와서 apater 가 null인 경우 새로 달아주는 방식입니다

2020-06-12 13:50 UTC, hwaniiidev commented on 2005/leechungwoo92/StudyForkProject/app/src/main/java/com/lllccww/studyforkproject/ui/main/MainViewModel.kt
> +        if (inputQuery.isNullOrBlank()) {
네, 말씀하신대로 toastString.set("검색결과가 없습니다.") 를 1회라도 발생 시키면 toastString.set("검색결과가 없습니다.") 를 발생시키기 전까진 값이 변하지 않아서 그랬던거네요. 저는 정상적으로 값을 받아 왔을 때도 val error : ObservableField 에  NONE_ERROR 라고 해서 값을 변경 시켜줬었는데 청우님이 수정하신 것처럼 notifyChange() 만 해줘도 해결할 수 있겠네요

2020-06-12 13:52 UTC, hwaniiidev approved these changes

2020-06-12 13:52 UTC, hwaniiidev commented
고생하셨습니다

2020-06-13 08:14 UTC, sjjeong requested changes

2020-06-13 08:14 UTC, sjjeong commented on 2005/leechungwoo92/StudyForkProject/app/src/main/java/com/lllccww/studyforkproject/ui/main/MainActivity.kt
> +                val itemTotalCount = MovieListAdapter().itemCount - 1
이렇게 바꾸면 문제가 있을 것 같은데 확인부탁드려요

2020-06-13 08:14 UTC, sjjeong commented on 2005/leechungwoo92/StudyForkProject/app/src/main/java/com/lllccww/studyforkproject/ui/main/MainViewModel.kt
> +        toastString.notifyChange()
이렇게 하면 데이터가 두번 전달 됩니다.
msg가 같은경우에만 notifyChange를 호출하도록 해주세요

2020-06-13 09:21 UTC, LeeChungWoo92 commented on 2005/leechungwoo92/StudyForkProject/app/src/main/java/com/lllccww/studyforkproject/ui/main/MainViewModel.kt
> +        toastString.notifyChange()
3c35cda
이렇게 수정해보았습니다!

2020-06-13 09:22 UTC, LeeChungWoo92 commented on 2005/leechungwoo92/StudyForkProject/app/src/main/java/com/lllccww/studyforkproject/ui/main/MainActivity.kt
> +                val itemTotalCount = MovieListAdapter().itemCount - 1
3c35cda
기능이 작동을 안하고 있었네요;;; 
다시 수정하였습니다.

2020-06-13 09:23 UTC, LeeChungWoo92 commented on 2005/leechungwoo92/StudyForkProject/app/src/main/java/com/lllccww/studyforkproject/ui/main/MainActivity.kt
> +        movieRemoteDataSource = MovieRemoteDataSourceImpl()
이부분이 제일어려운것같습니다 ㅠㅠ 조금더 공부해서 수정해보겠습니다.
설명 감사합니다!

2020-06-13 13:48 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-06-14 05:03 UTC, merged