HW-2 MVP 패턴 적용하기
sjjeong/GoogryAndroidArchitecutreStudy pull request #68
Opened 2019-06-19 21:35 UTC by zion830

늦어서 죄송합니다 😢😢

2019-06-21 16:42 UTC, Nanamare requested changes
수고 많으셨습니다!

2019-06-21 16:42 UTC, Nanamare commented on zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/data/CoinDataSource.kt
> +    fun getAllMarkets(callback: CoinDataSource.LoadMarketsCallback)
같은 클래스에 있어서 CoinDataSource 는 생략해도 될 것 같아요
같은 클래스여도 명시적으로 선언하시는 스타일이시면 이대로 나둬도 될 것 같아요

2019-06-21 16:42 UTC, Nanamare commented on zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/data/CoinRepository.kt
> +    private val service = RetrofitBuilder.service
스터디에서 제 기억으로는 Repository은 Retrofit 을 바로 호출 하는 것이 아니라 RemoteDataSource 를 가지고 있고, RemoteDataSource 안에서 Retrofit 이 작동하는 것이 아닌가 라는 생각이 드는데 어떻게 생각하시나요 ?!

2019-06-21 16:42 UTC, Nanamare commented on zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/showcoin/view/MainActivity.kt
> +        layout_main_swipe.setOnRefreshListener {
저는  개인적으로는 리스너 같은 것들은 Implementation 해서 사용하는 것이 좋았던 거 같아요.
가령 뷰가 많아지면 initView() 코드가 더욱 커져서 가독성이 떨어졌던 거 같아요.
override fun onRefresh() {
        TODO("not implemented") //To change body of created functions use File | Settings | File Templates.
    }
이런식으로 IDE에서 자동생성 해주고 경고도 해주니 프로그래머가 잊고 구현하지 않는 실수도 줄어 들었던거 같아요.
OnClickListener 도 뷰들 모아놓고 id로 분기 시켜서 작성하면 편리했던거 같은데 저희 개인적인 생각입니다 :)

2019-06-21 16:42 UTC, Nanamare commented on zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/data/CoinRepository.kt
> +    override fun getAllMarkets(callback: CoinDataSource.LoadMarketsCallback) {
질문 : Response 을 받은 데이터의 가공을 원래는 Presenter 에서 맡아서 대신 해줘야하는 게 아닐까 싶습니다?!

2019-06-21 16:42 UTC, Nanamare commented on zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/data/CoinDataSource.kt
> +        fun onDataNotAvailable(msg: String, reason: String?)
네트워크 작업이 많아지면, 모든 callback 인터페이스에 onDataNotAvailable 함수가 있을 것 같은데, 이런 부분을 추상화 시킬 수 있을 것 같습니다.

2019-06-21 16:42 UTC, Nanamare commented on zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/showcoin/view/MainActivity.kt
> +        showProgress()
Activity 에서 showPregress()를 직접적으로 호출하지 않고, presenter 에서 이런 작업들을 하는 것이 아닌가라는 생각이 들어요!
getMarketData 하는 기능인데 다른 작업도 하는 느낌이랄까요

2019-06-21 16:42 UTC, Nanamare commented on zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/showcoin/view/MainActivity.kt
> +        hideRefreshIcon()
setCoinInfo 함수에서 많은 작업을 하는 느낌이라, 요런 느낌이면 어떨까 싶습니다 
```
override fun setCoinInfo(coinData: List<TickerModel>) {
        coinAdapter.setCoinList(coinData)
}
```

```
override fun onTickersLoaded(tickers: List<TickerModel>) {
        view.hideProgress()
        view.hideRefreshIcon()
        view.setCoinInfo(tickers)
    }
```

2019-06-21 16:42 UTC, Nanamare commented on zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/showcoin/CoinPresenter.kt
> +    override fun onTickersLoaded(tickers: List<TickerModel>) {
굳이 네이밍을 맞춘다면 onCoinsLoaded(coins: List<CoinModel>) ?!

2019-06-21 16:46 UTC, zion830 commented
@Nanamare 잘 봐주셔서 감사합니다. 주말 중으로 수정할게요 :D !!

2019-06-22 02:33 UTC, zion830 commented on zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/data/CoinDataSource.kt
> +    fun getAllMarkets(callback: CoinDataSource.LoadMarketsCallback)
생략했습니다
c71f2d0

2019-06-22 02:36 UTC, zion830 commented on zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/showcoin/view/MainActivity.kt
> +        showProgress()
수정했습니다
68d08d9

2019-06-22 02:37 UTC, zion830 commented on zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/showcoin/view/MainActivity.kt
> +        layout_main_swipe.setOnRefreshListener {
수정했습니다
fb3d1ce

2019-06-22 02:38 UTC, zion830 commented on zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/showcoin/CoinPresenter.kt
> +    override fun onTickersLoaded(tickers: List<TickerModel>) {
수정했습니다
ceb5dfb

2019-06-22 03:37 UTC, zion830 commented on zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/showcoin/view/MainActivity.kt
> +        hideRefreshIcon()
수정했습니다
915c540

2019-06-23 15:04 UTC, zion830 commented on zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/data/CoinDataSource.kt
> +        fun onDataNotAvailable(msg: String, reason: String?)
말씀해주신 추상화가, 더 상위의 callback interface를 하나 만들어서 상속받게 만드는 것을 의미하는 것인가요?

2019-06-23 15:09 UTC, Nanamare commented on zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/data/CoinDataSource.kt
> +        fun onDataNotAvailable(msg: String, reason: String?)
넵 그런식으로 두면 좋을 것 같아요
결정은 스스로 해주시면 될 것 같습니다 ㅋ.ㅋ!

2019-06-23 15:10 UTC, Nanamare submitted a review, later dismissed

2019-06-23 15:11 UTC, Nanamare commented
석준님이 말씀하신 것들만 추가적으로 하시면 될 것 같습니다 :)

2019-06-25 17:39 UTC, zion830 commented
@Nanamare 지난주 리뷰대로 수정하였습니다. 확인 부탁드려요!

2019-06-27 01:10 UTC, zion830 commented
@Nanamare 엇... 맞아요 제가 반대로 썼네요ㅎㅎ;;

2019-06-27 10:12 UTC, Nanamare approved these changes

2019-06-27 10:13 UTC, Nanamare commented
승인했습니다 :)
라벨 체인지 해주세욥!

2019-06-27 10:14 UTC, Nanamare submitted a review, later dismissed

2019-06-28 04:50 UTC, sjjeong requested changes
고생하셨어요~

2019-06-28 04:50 UTC, sjjeong commented on zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/adapter/CoinRecyclerViewAdapter.kt
> +    private var coinList: MutableList<TickerModel> = mutableListOf()
coinList의 타입을 명시해주지 않아도 좋아요

2019-06-28 04:50 UTC, sjjeong commented on zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/adapter/CoinRecyclerViewAdapter.kt
> +        private val tvCoinName by lazy { itemView.tv_coin_name as TextView }
as TextView는 없어도 되지 않나요?
이부분은 제가 kotlin-android-extensions을 안써서 잘은 모르겠네요

2019-06-28 12:21 UTC, zion830 commented on zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/adapter/CoinRecyclerViewAdapter.kt
> +    private var coinList: MutableList<TickerModel> = mutableListOf()
삭제했습니다~ 
f7c7ce0

2019-06-28 12:21 UTC, zion830 commented on zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/adapter/CoinRecyclerViewAdapter.kt
> +        private val tvCoinName by lazy { itemView.tv_coin_name as TextView }
명시적으로 쓴거라 없어도 괜찮습니다. 삭제했어요! 
0ea8c4d

2019-06-29 00:17 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-06-29 02:14 UTC, Nanamare approved these changes

2019-06-29 02:15 UTC, merged