Update README.md
sjjeong/GoogryAndroidArchitecutreStudy pull request #681
Opened 2020-06-13 11:51 UTC by DWL5

2020-06-14 02:27 UTC, sjjeong requested changes
1. 프로필 링크도 추가해주세요
2. 경로는 master 브랜치에서 접근 가능하도록 master로 해주세요
3. 개인폴더가 추가되지 않았습니다.

2020-06-16 08:22 UTC, DWL5 commented
반영했습니다

2020-06-17 11:20 UTC, sjjeong requested changes
폴더 명을 study 말고 본인 닉네임으로 해주세요

2020-06-19 17:49 UTC, DWL5 commented
반영했습니다.

2020-06-20 00:52 UTC, sjjeong requested changes
base branch가 StudyFork라서 링크를 StudyFork로 해주셔야 합니다

2020-06-21 02:40 UTC, merged