HW-5 AAC-ViewModel 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #69
Opened 2019-06-20 14:28 UTC by namjackson

AAC-ViewModel 적용

2019-06-21 11:18 UTC, ddaeyeonkim requested changes

2019-06-21 11:18 UTC, improve777 commented on namjackson/ArchStudy/app/src/main/java/com/namjackson/archstudy/view/coinlist/CoinListViewModel.kt
> +        _filterCoinList.addSource(baseCurrency, Observer { t ->
Observer 함수가 sam 이라서 축약해도 되네요!

2019-06-21 11:18 UTC, improve777 commented on namjackson/ArchStudy/app/src/main/java/com/namjackson/archstudy/view/coinlist/CoinListFragment.kt
> +        ).get(CoinListViewModel::class.java)
get 을 [] 로 치환할수 있습니다!

2019-06-21 11:18 UTC, improve777 commented on namjackson/ArchStudy/app/src/main/java/com/namjackson/archstudy/view/coinlist/CoinListFragment.kt
> -        viewModel.baseCurrency.observe(this, androidx.lifecycle.Observer { viewModel.initMarket() })
android.lifecycle.Observer 를 임포트해주세요

2019-06-23 03:26 UTC, namjackson commented on namjackson/ArchStudy/app/src/main/java/com/namjackson/archstudy/view/coinlist/CoinListFragment.kt
> -        viewModel.baseCurrency.observe(this, androidx.lifecycle.Observer { viewModel.initMarket() })
해당 코드는 삭제되었습니다!

2019-06-23 03:27 UTC, namjackson commented on namjackson/ArchStudy/app/src/main/java/com/namjackson/archstudy/view/coinlist/CoinListFragment.kt
> +        ).get(CoinListViewModel::class.java)
934ff4820ac540234174107b5e9cd8c157ed632a

2019-06-23 03:28 UTC, namjackson commented on namjackson/ArchStudy/app/src/main/java/com/namjackson/archstudy/view/coinlist/CoinListViewModel.kt
> +        _filterCoinList.addSource(baseCurrency, Observer { t ->
9fb35ec0fdb676e55d7394ba1067f6069cfb874b

2019-06-23 03:34 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-06-24 02:31 UTC, ddaeyeonkim approved these changes
LGTM 👍👍👍

2019-06-24 05:49 UTC, merged