HW-6 - ViewModel, LiveData 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #693
Opened 2020-06-16 12:12 UTC by sangjinKIM93

중간에 에러 하나를 잡기 위해서 여기저기 건드리다 commit 쪼개기를 실패했습니다...
(commit 세부사항에 수정 사항을 정리해서 적어놨습니다.)

저의 배려 없는 커밋으로 인해 리뷰 중 이해가 안 가시는 부분이 있다면 질문 남겨주십시오! 바로 답변드리겠습니다.

2020-06-16 15:21 UTC, RyuC0605 reviewed
안녕하세요. 류승윤 입니다. 리뷰 참고하시기 바랍니다. 
즐거운 한 주 보내세요.
감사합니다.

2020-06-16 15:21 UTC, RyuC0605 commented on 2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/MovieListActivity.kt
> +            Toast.makeText(applicationContext, getString(it),Toast.LENGTH_SHORT).show()
```
Toast.makeText(this@MovieListActivity , getString(it),Toast.LENGTH_SHORT).show()
```
MovieListActivity 에서 띄우는 Toast 이니 Activity Context를 사용해도 될 것 같습니다.

2020-06-16 15:21 UTC, RyuC0605 commented on 2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/MovieListViewModel.kt
> +    val toastMsgString: LiveData<String> = _toastMsgString
toastMsgRes와 toastMsgString 를 일원화 시킬 방법이 없을까요? 전 리소스를 생성자에서 받는 방법으로 통일 시켰습니다.

2020-06-18 08:31 UTC, sangjinKIM93 commented on 2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/MovieListActivity.kt
> +            Toast.makeText(applicationContext, getString(it),Toast.LENGTH_SHORT).show()
수정했습니다. 감사합니다:)

18f0457

2020-06-18 08:33 UTC, sangjinKIM93 commented on 2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/MovieListViewModel.kt
> +    val toastMsgString: LiveData<String> = _toastMsgString
좋은 제안 감사합니다 ㅎㅎ 
저는 AndroidViewModel을 활용했기 때문에 AndroidViewModel이 제공해주는 applicationContext를 일원화 해봤습니다.

94f8d73

2020-06-18 15:22 UTC, RyuC0605 approved these changes
삼성TM

2020-06-19 11:01 UTC, sjjeong requested changes

2020-06-19 11:01 UTC, sjjeong commented on 2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/MovieListViewModel.kt
> +    private val context = application
따로 자정하지 않아도 AndroidViewModel 내부에 선언되어 있으니 그것을 사용하면 됩니다.

2020-06-19 11:50 UTC, sangjinKIM93 commented on 2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/MovieListViewModel.kt
> +    private val context = application
감사합니다:) 수정했습니다.

34d6aad

2020-06-19 11:55 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-06-20 02:10 UTC, merged