HW-6 LiveData AAC ViewModel 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #694
Opened 2020-06-16 14:16 UTC by developer-sungjae

- 중복코드 제거를 위한 BaseActivity BaseRecyclerViewAdpater, BaseViewHolder, BaseViewModel 선언
- Local,Remote DataSource 싱글톤 변환
- DataSource 관련된 구독 객체 ViewModel에서 처리하게끔 변경
- BaseViewModel 메서드로 disposable 처리

2020-06-17 12:02 UTC, chuuuul requested changes
Data쪽 싱글턴을 엄청 잘 구현 하셨네요!
많이 배웠습니다.

2020-06-17 12:02 UTC, chuuuul commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/ui/search/SearchActivity.kt
> +        }
해당 작업들은 onCreate에서만 처리해도 될 것 같습니다.

2020-06-17 12:02 UTC, chuuuul commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/ui/search/SearchViewModel.kt
>          repository.getCashedMovieList(
개인적인 의견입니다.
다음과 같이 구성되었으면 어땠을까 싶습니다!

1. Local Data Source 및 Remote Data Source에서 return으로 Single이나 Observable을 넘긴다.
2. repository에서 return으로 Single이나 Observable을 넘긴다.
3. 받은 데이터를 처리하는 subscribe{...}을 ViewModel을 작성한다.

위에 적은 방법으로 구현한다면 onSuccess나 onFailure를 파라미터로 안넘기게 되고, 조금 깔끔해질것 같습니다.

```
// ViewModel
fun getMovieListFromRemote(searchWord: String) {

        ...

        repository
            .getMovieList(searchWord)
            .observeOn(AndroidSchedulers.mainThread())
            .subscribeOn(Schedulers.io())
            .subscribe(
                { remoteData ->
                     ...
                }, { t ->
                    ....
                }
            ).addDisposable()
    }
```

```
//Respository
    override fun getMovieList(
        keyWord: String
    ):Single<NaverApiData> {
        return naverMovieRemoteDataSource.getMovieList(keyWord)
    }
```

```
// RemoteDataSource
    override fun getMovieList(
        keyWord: String
    ) : Single<NaverApiData> {
         return service.getMovies(keyWord)
    }
```

2020-06-17 12:02 UTC, chuuuul commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/ui/search/SearchActivity.kt
>          et_search.doAfterTextChanged {
같은 동작이지만 LiveData를 배웠으니
 xml에 있는 searchWord를 ViewModel의 MutableLiveData<String> 으로 구현해서
```
// ViewModel
    val searchWord = MutableLiveData<String>().apply { this.value = "" }
```
```
// Activity
vm.searchWord.observe(this, Observer {
      vm.invokeTextChanged()
})
```
로 써도 좋을 것 같습니다!

2020-06-17 12:02 UTC, chuuuul commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/ui/search/SearchViewModel.kt
> +            val movieLocalItem = MovieLocalItem().apply {
Extension이나 함수로 정리하는게 가독성에 도움이 될 것 같습니다.

2020-06-18 03:36 UTC, developer-sungjae commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/ui/search/SearchViewModel.kt
>          repository.getCashedMovieList(
interface에 return을 넣지 말라는 석준님 코멘트를 본 것 같아서 일부러 이렇게 구현했습니다.

2020-06-18 14:52 UTC, developer-sungjae commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/ui/search/SearchActivity.kt
> +        }
소름이네요 감사합니다 수정하였습니다.
5b13d16

2020-06-18 14:56 UTC, developer-sungjae commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/ui/search/SearchActivity.kt
>          et_search.doAfterTextChanged {
아직 익숙치가 않네요. 수정하였습니다. 감사합니다. 
7934237

2020-06-18 15:26 UTC, developer-sungjae commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/ui/search/SearchViewModel.kt
> +            val movieLocalItem = MovieLocalItem().apply {
제 수준으로는 이것밖에 안떠오르네요 다른것 있으면 추천 부탁드립니다
수정하였습니다 감사합니다.
03b8f4d

2020-06-18 15:38 UTC, chuuuul commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/ui/search/SearchViewModel.kt
>          repository.getCashedMovieList(
앗 그런가요? MVP에서 Present의 Interface부분에서는 그런 말씀하신걸 리뷰 받았었는데, Repository도 마찬가지인가 보네요!

2020-06-18 15:40 UTC, chuuuul approved these changes
수고하셨습니다!

2020-06-18 15:43 UTC, developer-sungjae commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/ui/search/SearchViewModel.kt
>          repository.getCashedMovieList(
interface 구현할때는 그렇다는 말을 들어서 일단 좋은 의견 감사드립니다.
만약 코멘트를 또 받는다면 수정하도록 하겠습니다.

2020-06-19 11:04 UTC, sjjeong requested changes

2020-06-19 11:04 UTC, sjjeong commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/base/BaseRecyclerViewAdapter.kt
> +    fun updateMovieData(items: List<ITEM>?) {
범용적으로 사용하기 위해서 updateData정도면 될 것 같습니다.

2020-06-19 11:04 UTC, sjjeong commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/base/BaseViewHolder.kt
> +                setVariable(BR.movieItem, item)
범용적으로 사용하기위해 movie를 빼고 item정도가 좋을 것 같아요

2020-06-19 11:48 UTC, developer-sungjae commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/base/BaseRecyclerViewAdapter.kt
> +    fun updateMovieData(items: List<ITEM>?) {
감사합니다. 수정하였습니다.
40d7162

2020-06-19 11:48 UTC, developer-sungjae commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/base/BaseViewHolder.kt
> +                setVariable(BR.movieItem, item)
감사합니다. 수정하였습니다!
edff745

2020-06-19 11:56 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-06-19 12:22 UTC, merged