HW-6 AAC ViewModel & LiveData 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #696
Opened 2020-06-17 07:52 UTC by LeeChungWoo92

AAC ViewModel & LiveData 적용 하였고 
지적해주셨던 repository쪽도 수정해봤습니다. 
그리고 검색 후 키보드숨기기 기능을 추가했습니다.

2020-06-17 12:44 UTC, hwaniiidev commented
고생하셨습니다! 저도 특별히 코멘트 할 게 없네요
LGTM

2020-06-17 12:44 UTC, hwaniiidev approved these changes

2020-06-19 11:08 UTC, sjjeong requested changes

2020-06-19 11:08 UTC, sjjeong commented on 2005/leechungwoo92/StudyForkProject/app/src/main/java/com/lllccww/studyforkproject/ui/main/MainViewModel.kt
> +class MainViewModel(private val movieRepository: NaverMovieRepositoryImpl) : ViewModel() {
타입은 기존처럼 interface로 해주세요

2020-06-22 00:35 UTC, LeeChungWoo92 commented on 2005/leechungwoo92/StudyForkProject/app/src/main/java/com/lllccww/studyforkproject/ui/main/MainViewModel.kt
> +class MainViewModel(private val movieRepository: NaverMovieRepositoryImpl) : ViewModel() {
22a0a61
수정했습니다.

2020-06-22 05:09 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-06-22 05:46 UTC, merged