MVVM - Live Data 적용 및 AAC ViewModel 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #697
Opened 2020-06-17 13:56 UTC by chuuuul

### 리팩토링

 - Observable Field를 LiveData로 변경
 - ViewModel을 AAC ViewModel을 이용하여 구현
 - Repository Pattern을 싱글턴으로 수정

### 기능 추가

 - 키워드 변경 후 일정 시간 후에 자동으로 검색 기능
 - 검색 이후 일정 시간동안 검색 불가 기능
 - Resource Provider를 이용하여 getString 구현

2020-06-18 14:41 UTC, SageHabitus requested changes

2020-06-18 14:41 UTC, developer-sungjae commented on 2005/chuuuul/ArchitectureStudy/app/src/main/java/com/example/architecture/util/ConstValue.kt
> +        const val AUTO_SEARCH_TIME: Long = 3000
```suggestion
        const val AUTO_SEARCH_TIME = 3000L
```
통일성을 위해 위와 같이 쓰면 어떨까요?

2020-06-18 14:41 UTC, developer-sungjae commented on 2005/chuuuul/ArchitectureStudy/app/src/main/java/com/example/architecture/activity/search/SearchActivity.kt
> +                val resourceProvider = ResourceProviderImpl(this@SearchActivity.applicationContext)
applicationContext는 appication 정보를 담고 있는 context로 알고있습니다. 혹시 앞에 this@~~ 붙여주신 이유가 있나요?

2020-06-18 14:41 UTC, developer-sungjae commented on 2005/chuuuul/ArchitectureStudy/app/src/main/java/com/example/architecture/ext/LiveDataExtension.kt
> +fun <T> LiveData<T>.debounce(duration: Long = 1000L) = MediatorLiveData<T>().also { mld ->
개인적인 의견으로 디바운스 시간을 유동적으로 조정할 것이 아니라면 duration을 굳이 parameter로 안받아도 될 것 같습니다. 안바꾸셔도 됩니다.

2020-06-18 14:41 UTC, developer-sungjae commented on 2005/chuuuul/ArchitectureStudy/app/src/main/java/com/example/architecture/activity/search/SearchActivity.kt
> +        super.onPause()
```suggestion
    override fun onPause() {
    vm.unbindViewModel()
        super.onPause()
```
이 좋을 것 같습니다. (1) 방법
그런데 좀 이상한 것이 onPause에 선언하면 다른 엑티비티가 있을 경우에 다시 back하면 onCreate를 안타기 때문에 안전한 코드가 아닌 것 같습니다.

2020-06-18 14:41 UTC, developer-sungjae commented on 2005/chuuuul/ArchitectureStudy/app/src/main/java/com/example/architecture/activity/search/SearchViewModel.kt
> +
```suggestion
    override fun onCleared() {
        compositeDisposable.clear()
        super.onCleared()
    }
```
Activity에서 control하는 것(1) 보다는 activity는 disposable을 모르는게 좋을 것 같고 viewmodel 생명주기 관련은 viewmodel 안에서 작성하는게 좋을 것 같습니다.(2)
구글링 해보면  
`ViewModel은 액티비티 스코프가 완전히 종료되는 시점에 종료가 되고, 이때 onCleared() 함수가 호출됩니다. 이 콜백은 ViewModel 클래스의 유일한 함수이며 ViewModel의 리소스를 해제하기에 적합한 곳입니다.` 
라고 나와있습니다.

2020-06-18 14:44 UTC, developer-sungjae commented on 2005/chuuuul/ArchitectureStudy/app/src/main/java/com/example/architecture/activity/search/SearchViewModel.kt
>          naverRepository.clearCacheData()
단순 질문입니다. 이 함수는 언제 쓰이나요?

2020-06-18 14:52 UTC, chuuuul commented on 2005/chuuuul/ArchitectureStudy/app/src/main/java/com/example/architecture/activity/search/SearchViewModel.kt
>          naverRepository.clearCacheData()
Shared Preferences에 저장되어있는 캐시값을 지우는데 사용되는 함수인데 현재 프로젝트에서는 사용 할 곳이 없어서 기능만 남겨뒀습니다.

2020-06-18 15:00 UTC, chuuuul commented on 2005/chuuuul/ArchitectureStudy/app/src/main/java/com/example/architecture/activity/search/SearchActivity.kt
> +        super.onPause()
onCreate에 bind 되는 것이 아닌 onResume()에 다시 bindviewModel하는 것으로 되어있어서 괜찮을 것 같습니다!

unbindViewModel로 바로 써도 되지만,
vm의 있는 로직을 바로 호출하는게 아니라 unbind하는 작업을한다는것을 표현하는게 더 좋을 것 같다는 생각입니다.

2020-06-18 15:29 UTC, chuuuul commented on 2005/chuuuul/ArchitectureStudy/app/src/main/java/com/example/architecture/activity/search/SearchViewModel.kt
> +
의견 감사합니다. 
onCleared()는 Activity의 onDestory 다음에 오게 되네요.
onCreate - onCleared의 생명주기보다는 onResume - onPause의 생명주기에서 Disposable을 clear하려는 의도였습니다!

2020-06-18 15:31 UTC, chuuuul commented on 2005/chuuuul/ArchitectureStudy/app/src/main/java/com/example/architecture/util/ConstValue.kt
> +        const val AUTO_SEARCH_TIME: Long = 3000
3689ff9
감사합니다. 수정했습니다.

2020-06-18 15:31 UTC, chuuuul commented on 2005/chuuuul/ArchitectureStudy/app/src/main/java/com/example/architecture/activity/search/SearchActivity.kt
> +                val resourceProvider = ResourceProviderImpl(this@SearchActivity.applicationContext)
3945568
감사합니다. 수정했습니다.

2020-06-18 15:32 UTC, chuuuul commented on 2005/chuuuul/ArchitectureStudy/app/src/main/java/com/example/architecture/ext/LiveDataExtension.kt
> +fun <T> LiveData<T>.debounce(duration: Long = 1000L) = MediatorLiveData<T>().also { mld ->
9ea852b
감사합니다. 수정했습니다.

2020-06-18 15:33 UTC, SageHabitus requested changes

2020-06-18 15:33 UTC, developer-sungjae commented on 2005/chuuuul/ArchitectureStudy/app/src/main/java/com/example/architecture/activity/search/SearchActivity.kt
> +        super.onPause()
의도하신거라면 onCreate가 아닌 반복적인 bind때문에 굳이 onResume에서 해야할 이유가 있나요? onResume이 back했을때도 작동되는걸 의도하신거라면 flag를 두어서 처음엔 onCreate 그 이후엔 onResume에서 bind하는 쪽으로 코드를 작성하는게 좋을 것 같습니다.

2020-06-18 15:37 UTC, developer-sungjae commented on 2005/chuuuul/ArchitectureStudy/app/src/main/java/com/example/architecture/activity/search/SearchViewModel.kt
> +
제 말은 ViewModel클래스에서 생명주기에 따라서 리소스 해제하도록 onCleard를 제공하는 이유가 있을텐데 굳이 왜 onResume, onPause 생명주기를 이용하셔서 불완전하게 하시는건지 궁금합니다.  단순히 그냥 그때 하고 싶으신건지요? 아니면 개발할 때 onCleard를 이용할떄보다 더 좋은 이점이 있는건가요?

2020-06-18 16:04 UTC, chuuuul commented on 2005/chuuuul/ArchitectureStudy/app/src/main/java/com/example/architecture/activity/search/SearchViewModel.kt
> +
위에 코멘트 주시면 내용이랑 함께 의견을 적겠습니다.

> 제가 말씀드리고 싶은건 ViewModel클래스에서 생명주기에 따라서 리소스 해제하도록 onCleard를 제공하는 이유가 있을텐데 굳이 왜 onResume, onPause 생명주기를 이용하셔서 불완전하게 하시는건지 궁금합니다. 단순히 그냥 그때 하고 싶으신건지요? 아니면 개발할 때 onCleard를 이용할떄보다 더 좋은 이점이 있는건가요?

 예를 들겠습니다.
ViewModel에서 10초 걸리는 네트워크 통신 이후에 A전환이 일어나는 로직이 Rx Java로 동작하고 있다고 가정해보겠습니다. 그런데 사용자가 3초만에 홈키를 눌러서 앱을 onPause로 전환 시켰습니다. 그럴경우 어떻게 될까요? 10초 걸리는 작업의 Dispose가 Clear 되지 않았기 때문에 10초후에 화면전환이 일어나면서 앱이 올라오겠죠. 사용자의 관점에서는 홈키를 눌렀으니 코드 동작이 멈추는것을 기대했을거라 생각합니다. 그래서 onResume - onPause의 시점에서 Disposable을 Clear했습니다.

> 그리고 두번째로 onResume을 타기 전에 사용자가 어떠한 동작을 하면 앱은 어떻게 되나요 아니면 사용자가 항상 onResume후 vm세팅 후에 앱을 동작할거라는 보장이 있는지 궁금합니다.

onResume을 타기전에 사용자가 어떠한 동작을 할 수 있는지 잘 모르겠습니다. onResume을 지나서야 사용자와 상호작용을 할 수 있는것으로 알고 있습니다. 또한 이전 코멘트에서의 안전하지 않다는 의도를 잘 모르겠습니다.

2020-06-18 16:11 UTC, chuuuul commented on 2005/chuuuul/ArchitectureStudy/app/src/main/java/com/example/architecture/activity/search/SearchActivity.kt
> +        super.onPause()
>  flag를 두어서 처음엔 onCreate 그 이후엔 onResume에서 bind하는 쪽으로 코드를 작성하는게 좋을 것 같습니다.

 의도를 잘 모르겠습니다. onCreate이후 에도 onResume을 타는데 플래그를 사용해서 굳이 제어를 하려는 의도를 잘 모르겠습니다.

2020-06-18 16:12 UTC, developer-sungjae commented on 2005/chuuuul/ArchitectureStudy/app/src/main/java/com/example/architecture/activity/search/SearchViewModel.kt
> +
onStart관련해서 말씀드렸습니다. 그런 의도로 하신거군요 배웠습니다. 감사합니다

2020-06-18 16:14 UTC, SageHabitus approved these changes

2020-06-18 16:15 UTC, developer-sungjae commented
고생하셨습니다

2020-06-19 11:54 UTC, sjjeong requested changes

2020-06-19 11:54 UTC, sjjeong commented on 2005/chuuuul/ArchitectureStudy/app/src/main/java/com/example/architecture/activity/search/SearchViewModel.kt
> +    val keyword = MutableLiveData<String>().createDefault("")
이렇게 쓰면 됩니다.
```
val keyword = MutableLiveData("")
```

2020-06-19 11:54 UTC, sjjeong commented on 2005/chuuuul/ArchitectureStudy/app/src/main/java/com/example/architecture/activity/search/SearchViewModel.kt
> +
홈키를 눌러서 이전 동작을 취소하는거라면 맞는 동작입니다.

2020-06-19 12:40 UTC, chuuuul commented on 2005/chuuuul/ArchitectureStudy/app/src/main/java/com/example/architecture/activity/search/SearchViewModel.kt
> +    val keyword = MutableLiveData<String>().createDefault("")
7e489c7
감사합니다. 수정했습니다!

2020-06-21 04:56 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-06-21 05:03 UTC, merged