HW -  5 AAC ViewModel 변경
sjjeong/GoogryAndroidArchitecutreStudy pull request #70
Opened 2019-06-20 16:27 UTC by GongSulMin

2019-06-21 18:49 UTC, sabgilhun requested changes
이번 과제가 바꿔야할 코드가 적어서 리뷰를 할 코드가 적어서 쓸 내용이 없네요 ㅎㅎ..

그래서 한번 전체적인 구조에 대해서 의견을 내봅니다.

저는 아래처럼  ViewModel을 좀 더 세분화해서 나눠보는것도 좋을거 같다고 생각합니다.

- CoinListActivity - CoinListViewModel
	- searchTicker(searchKeyword로 변수명을 바꾸는것도 좋을거 같아요) = 검색할 코인 이름
	- baseCurrency
	- tickerList
	- showCoinSearchDialog(event)
	- fun loadCoin
	- fun onStop
	- fun loadTickerList <- private로 바꿔도 되겠네요
	- fun setBaseCurrency(여기서 baseCurrency가 기존의 것이랑 달라지면 loadCoin을 호출하는 방식으로 구현하면 좋을거 같네요)

- CoinMarketDialog - CoinMarketViewModel, CoinListViewModel
	- baseCurrencyList
	- fun loadBaseCurrency
	- coin market item 클릭 시 CoinListViewModel의 setBaseCurrency를 불러서 baseCurrency를 변경하고 Dialog를 dissmiss

**아래 처럼 리스너를 adapter에서 받아쓰면 클릭 이벤트를 위해 ViewModel을 꼭 adapter에 보내지 않아도 됩니다.**

```
class Adapter(
private val onItemClickListener: ((item: Item) -> Unit)?
) {

...

override fun onBindViewHolder(holder: viewHolder, position: Int) {
        holder.itemView.setOnClickListener {
            onItemClickListener?.invoke(getItem(position))
        }
    } 

...

}
```

- CoinSearchDialog - CoinSearchViewModel, CoinListViewModel
	- searchTickerList
	- fun loadTickerSearchResult(인자로 검색할 코인 이름을 받아서 검색하면 좋을거 같아요)
	- onActivityCreated에서 CoinSearchViewModel.loadTickerSearchResult(CoinListViewModel.searchTicker.value) 이런식으로 호출

이 구조 의견은 변경 요청 사항은 아닙니다 ㅎㅎ

2019-06-21 18:49 UTC, sabgilhun commented on gongsulmin/StudyGong/app/src/main/java/my/gong/studygong/ui/CoinListActivity.kt
>      }
이 상수는 ViewModel로 옮겨도 될것 같아요

2019-06-22 11:31 UTC, GongSulMin commented on gongsulmin/StudyGong/app/src/main/java/my/gong/studygong/ui/CoinListActivity.kt
>      }
f4fc4a5
변경하였습니다!

2019-06-22 11:33 UTC, GongSulMin commented
> 이번 과제가 바꿔야할 코드가 적어서 리뷰를 할 코드가 적어서 쓸 내용이 없네요 ㅎㅎ..
> 
> 그래서 한번 전체적인 구조에 대해서 의견을 내봅니다.
> 
> 저는 아래처럼 ViewModel을 좀 더 세분화해서 나눠보는것도 좋을거 같다고 생각합니다.
> 
> * CoinListActivity - CoinListViewModel
>   
>   * searchTicker(searchKeyword로 변수명을 바꾸는것도 좋을거 같아요) = 검색할 코인 이름
>   * baseCurrency
>   * tickerList
>   * showCoinSearchDialog(event)
>   * fun loadCoin
>   * fun onStop
>   * fun loadTickerList <- private로 바꿔도 되겠네요
>   * fun setBaseCurrency(여기서 baseCurrency가 기존의 것이랑 달라지면 loadCoin을 호출하는 방식으로 구현하면 좋을거 같네요)
> * CoinMarketDialog - CoinMarketViewModel, CoinListViewModel
>   
>   * baseCurrencyList
>   * fun loadBaseCurrency
>   * coin market item 클릭 시 CoinListViewModel의 setBaseCurrency를 불러서 baseCurrency를 변경하고 Dialog를 dissmiss
> 
> **아래 처럼 리스너를 adapter에서 받아쓰면 클릭 이벤트를 위해 ViewModel을 꼭 adapter에 보내지 않아도 됩니다.**
> 
> ```
> class Adapter(
> private val onItemClickListener: ((item: Item) -> Unit)?
> ) {
> 
> ...
> 
> override fun onBindViewHolder(holder: viewHolder, position: Int) {
>         holder.itemView.setOnClickListener {
>             onItemClickListener?.invoke(getItem(position))
>         }
>     } 
> 
> ...
> 
> }
> ```
> 
> * CoinSearchDialog - CoinSearchViewModel, CoinListViewModel
>   
>   * searchTickerList
>   * fun loadTickerSearchResult(인자로 검색할 코인 이름을 받아서 검색하면 좋을거 같아요)
>   * onActivityCreated에서 CoinSearchViewModel.loadTickerSearchResult(CoinListViewModel.searchTicker.value) 이런식으로 호출
> 
> 이 구조 의견은 변경 요청 사항은 아닙니다 ㅎㅎ

ViewModel을 나누어야 될거 같다고 생각하긴 했는데  쉽게 쉽게 갈려고 했나보네요......
정성스럽게 리뷰 남겨주셔서 감사합니다 ㅎㅎ 
많이 고민 해보고 변경하겠습니다!

2019-06-22 11:52 UTC, sabgilhun approved these changes
수고하셨습니다 👍

2019-06-23 03:38 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-06-23 03:45 UTC, merged