HW-6 Koin 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #703
Opened 2020-06-22 12:51 UTC by sangjinKIM93

의존성 주입 라이브러리 koin 적용

2020-06-26 04:39 UTC, RyuC0605 reviewed
안녕하세요. 류승윤 입니다.
이번주는 개인 용무가 많아 리뷰가 늦어진점 양해부탁드립니다.

이슈는 아니고, 한가지 팁으로 activity_movie_list.xml 에서 

<androidx.recyclerview.widget.RecyclerView
            tools:listitem="@layout/item_movie"

이렇게 수정하시면 미리보기가 조금 더 수월해 집니다. 

알고 계시겠지만 참고 삼아 말씀드립니다.

감사합니다.

2020-06-26 04:39 UTC, RyuC0605 commented on 2005/sangjinKIM93/newproject/app/build.gradle
> +    implementation "org.koin:koin-androidx-viewmodel:$koin_version"
implementation "org.koin:koin-core:$koin_version"
implementation "org.koin:koin-android-viewmodel:$koin_version"

이 두개는 땡겨오지 않아도 되지 않을까요?

2020-06-26 04:39 UTC, RyuC0605 commented on 2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/di/appModule.kt
> +    viewModel { MovieListViewModel(get(), get()) }
바로 androidApplication()을 넣어주지 않고, ResourceProvider 를 만든 이유가 궁금합니다.

2020-06-26 10:28 UTC, KimSangJin2 commented on 2005/sangjinKIM93/newproject/app/build.gradle
> +    implementation "org.koin:koin-androidx-viewmodel:$koin_version"
viewmodel은 추후 커밋에서 삭제했었는데 제가 명시를 안 해놨네요 ㅜㅜ

koin-core는 kotlin 언어에서 쓰기 위한 필요조건인 줄 알았는데 없어도 잘 되네요. 수정했습니다:)


eadfcf0

2020-06-26 10:31 UTC, KimSangJin2 commented on 2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/di/appModule.kt
> +    viewModel { MovieListViewModel(get(), get()) }
저는 androidViewModel을 쓰다가 못 쓰게 되서 "어? context는 이제 못 쓰네 provider 하나 만들어서 주입해야겠다" 이렇게 생각했었는데 그냥 context를 주입해도 되는걸 놓쳤네요 ㅎㅎ
context를 사용하는 것이 더 코드를 줄일 수 있는 방법 같아 수정했습니다.

9839602

2020-06-26 10:33 UTC, KimSangJin2 commented
tools:listitem="@layout/item_movie"

꿀팁 감사합니다!
사실 저거 1주차때 승윤님 코드 보고 신기해서 따라해봤는데, 안 됐었거든요 ㅎㅎ (이유는 모르겠습니다.)
그래서 그냥 넘어갔었는데 다시 해보니 잘 되네요 :)

2020-06-26 11:09 UTC, sangjinKIM93 commented on 2005/sangjinKIM93/newproject/app/build.gradle
> +    implementation "org.koin:koin-androidx-viewmodel:$koin_version"
viewmodel은 추후 커밋에서 삭제했었는데 제가 명시를 안 해놨네요 ㅜㅜ

koin-core는 kotlin 언어에서 쓰기 위한 필요조건인 줄 알았는데 없어도 잘 되네요. 수정했습니다:)

eadfcf0

2020-06-26 11:09 UTC, sangjinKIM93 commented on 2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/di/appModule.kt
> +    viewModel { MovieListViewModel(get(), get()) }
저는 androidViewModel을 쓰다가 못 쓰게 되서 "어? context는 이제 못 쓰네 provider 하나 만들어서 주입해야겠다" 이렇게 생각했었는데 그냥 context를 주입해도 되는걸 놓쳤네요 ㅎㅎ
context를 사용하는 것이 더 코드를 줄일 수 있는 방법 같아 수정했습니다.

9839602

2020-06-26 11:09 UTC, sangjinKIM93 commented
tools:listitem="@layout/item_movie"

꿀팁 감사합니다!
사실 저거 1주차때 승윤님 코드 보고 신기해서 따라해봤는데, 안 됐었거든요 ㅎㅎ (이유는 모르겠습니다.)
그래서 그냥 넘어갔었는데 다시 해보니 잘 되네요 :)

2020-06-26 12:06 UTC, RyuC0605 approved these changes

2020-06-27 03:10 UTC, sjjeong requested changes

2020-06-27 03:10 UTC, sjjeong commented on 2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/MyApplication.kt
> +            androidLogger()
Debug build일 때만 logger를 등록하도록 해주세요

2020-06-28 00:15 UTC, sangjinKIM93 commented on 2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/MyApplication.kt
> +            androidLogger()
수정했습니다.
감사합니다:)

d343695

2020-06-29 11:03 UTC, sjjeong requested changes

2020-06-29 11:03 UTC, sjjeong commented on 2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/MyApplication.kt
> +            androidLogger(Level.DEBUG)
Level을 DEBUG로 하는게 아니라 debug 빌드 일 때는 log가 생기지 않도록 해주세요
debug일때 androidLogger()를 추가하지 않도록 해주시면 됩니다.

2020-06-30 06:22 UTC, sangjinKIM93 commented on 2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/MyApplication.kt
> +            androidLogger(Level.DEBUG)
확인이 늦었네요.. 수정했습니다!
debug일때만 logger를 등록하라는 말씀이시죠? 
(위 코멘트와 아래 코멘트 내용이 달라 좀 헷갈립니다.)
개인적으로는 debug모드일때 log가 남는 것이 맞는 것 같아서 그렇게 수정했습니다.
석준님 의도에 맞게 수정한건지 잘 모르겠네요.  의도와 다르다면 피드백 부탁드립니다!

0c4daca

2020-06-30 06:57 UTC, sjjeong commented on 2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/MyApplication.kt
> +            androidLogger(Level.DEBUG)
@sangjinKIM93 
아.. 코멘트를 잘못 작성했네요
debug빌드 일 때만 Log가 생기도록 하는 것입니다. 수정은 잘 하셨습니다.

추가로 d343695 처럼 작업하는 것은 Debug로 출력되는 Log가 나오는 것 뿐이지 Debug build때만 나오는 것은 아닙니다.

2020-06-30 06:57 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-06-30 09:43 UTC, sangjinKIM93 commented on 2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/MyApplication.kt
> +            androidLogger(Level.DEBUG)
감사합니다 :)

2020-06-30 09:44 UTC, merged