HW - 7 Koin 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #708
Opened 2020-06-23 16:25 UTC by developer-sungjae

- 커스텀 앱 선언 및 코인 적용 메서드 선언
- 네트워크모듈, 로컬데이터소스모듈, 리모트데이터소스모듈, 뷰모델모듈 선언
- 각 데이터 소스, 리파지토리 콜백 제거 -> 리턴으로 변경
- 전체적인 패키지 정리

2020-06-24 12:02 UTC, chuuuul requested changes
안녕하세요

2020-06-24 12:02 UTC, chuuuul commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/data/source/local/NaverMovieLocalDataSourceImpl.kt
> +object NaverMovieLocalDataSourceImpl : NaverMovieLocalDataSource {
DI를 적용하는거라면 object를 class로 변경하는게 맞는 방식인 것 같습니다.

2020-06-24 13:01 UTC, developer-sungjae commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/data/source/local/NaverMovieLocalDataSourceImpl.kt
> +object NaverMovieLocalDataSourceImpl : NaverMovieLocalDataSource {
object로 한다면 좀 더 더러운 코딩이 되는 것 같습니다. 수정하였습니다. 감사합니다.
a10e8d8

2020-06-24 13:33 UTC, chuuuul approved these changes
잘 짜신것 같습니다!!

2020-06-26 10:01 UTC, sjjeong requested changes

2020-06-26 10:01 UTC, sjjeong commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/components/Retrofit.kt
> +                HttpLoggingInterceptor.Level.BODY
이 파일을 제거해도 되겠네요

2020-06-26 10:01 UTC, sjjeong commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/extensions/StringExt.kt
> +fun String.parseHTMLTag(): String {
parseHtmlTag로 변경해주세요

2020-06-26 13:36 UTC, developer-sungjae commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/extensions/StringExt.kt
> +fun String.parseHTMLTag(): String {
감사합니다 수정하였습니다.
a5f02da

2020-06-26 13:36 UTC, developer-sungjae commented on 2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/components/Retrofit.kt
> +                HttpLoggingInterceptor.Level.BODY
감사합니다 삭제하였습니다.
cbd0f52

2020-06-27 03:11 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-06-27 03:13 UTC, merged