Class02/machine human
sjjeong/GoogryAndroidArchitecutreStudy pull request #71
Opened 2019-06-20 18:46 UTC by machine-human

remoteDataSource를 호출하는 부분에서 이해가 어려웠는데, 
상용님 프로젝트를 참고하여 쉽게 이해하고 반영하였습니다.
많이 배웠습니다. 감사합니다.

2019-06-20 18:50 UTC, brooks-o reviewed
.

2019-06-20 18:51 UTC, machine-human commented
> pull 요청을 잘못한거 같습니다. 죄송합니다.
> 현 위치부터 시작입니다.



> pull 요청을 잘못한거 같습니다. 죄송합니다.
> 현 위치부터 시작입니다.

2019-06-20 18:52 UTC, brooks-o reviewed
.

2019-06-22 01:51 UTC, sport0102 requested changes
말씀드린 부분만 완료하시면 될 것 같습니다!

2019-06-22 01:51 UTC, sport0102 commented on machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/data/source/remote/TickerRemoteDataSource.kt
> +                    if (coinList != null) {
coinList?.let{ } 형태가 좀더 코틀린 스러울 것 같습니

2019-06-22 01:51 UTC, sport0102 commented on machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/adapter/recyclerviewadapter/MainListAdapter.kt
> +        return tickerList.size
= tickerList.size 형태로 바꿔주시면 좋을 것 같습니

2019-06-22 02:33 UTC, sport0102 submitted a review, later dismissed

2019-06-25 16:22 UTC, machine-human commented
Rxjava2를 이용하여 데이터를 주고받는 기능을 아주 기본적인 방법으로 RemoteDataSource에 적용 해봤습니다.

로직이 분리되어 있어서 Disposable 등을 어떤 클래스 및 시점에 사용해야하는지 감이 안 잡히고
반복적으로 Api를 호출하고 싶은데 생각보다 잘 안됐네요..ㅠㅠ

2019-06-27 16:29 UTC, sport0102 requested changes
리뷰가 늦었습니다 죄송합니다 ㅠ 확인부탁드릴게요!

2019-06-27 16:29 UTC, sport0102 commented on machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/data/source/remote/TickerRemoteDataSource.kt
> +                        map { it.market }?.
이 부분 대신에 flatmap을 사용해서 처리하실 수 있을 것 같습니다!

2019-06-27 16:29 UTC, sport0102 commented on machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/adapter/recyclerviewadapter/MainListAdapter.kt
> +    private val tickerList: MutableList<TickerModel> = ArrayList()
이렇게 사용하실 거면 
private val tickerList = ArrayList<TickerModel>() 혹은
private val tickerList = mutableListOf<TickerModel>()
둘 중 하나로 통일하는게 좋을 것 같습니다

2019-06-27 16:29 UTC, sport0102 commented on machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/base/BaseView.kt
> +    fun showProgress(text: Throwable)
Throwable 형태로 받으실 거면 파라미터 값을 text 대신에 다른걸로 하시는게 좋을 것 같아요

2019-06-27 16:29 UTC, sport0102 commented on machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/data/TickerRepository.kt
> +            return instance ?: TickerRepository(tickerRemoteDataSource = tickerRemoteDataSource)
return 제외하고 = 사용한 한문장으로 축약할 수 있을 것 같아요!

2019-06-27 16:29 UTC, sport0102 commented on machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/util/FormatUtil.kt
> +        if (number is Double) {
=  if(number is Double) format.format(number) ~~~ 이런 형태로 축약해서 사용할 수 있을 것 같습니다

2019-06-27 16:30 UTC, machine-human commented
> 리뷰가 늦었습니다 죄송합니다 ㅠ 확인부탁드릴게요!

아닙니다. 괜찮습니다 :)
확인하고 진행 하도록 하겠습니다!!
내일 다시 리뷰 부탁 드리겠습니다ㅎㅎ

2019-06-27 17:35 UTC, machine-human commented
> 리뷰가 늦었습니다 죄송합니다 ㅠ 확인부탁드릴게요!



> 리뷰가 늦었습니다 죄송합니다 ㅠ 확인부탁드릴게요!

2019-06-28 16:16 UTC, sport0102 reviewed
LGMT!

2019-06-28 16:16 UTC, sport0102 submitted a review, later dismissed

2019-06-29 09:26 UTC, sjjeong requested changes

2019-06-29 09:26 UTC, sjjeong commented on machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/adapter/recyclerviewadapter/MainListAdapter.kt
> +        holder?.setData(tickerList[position])
holder는 nonnull이라서 ? 하지 않아도 돼요

2019-06-29 09:26 UTC, sjjeong commented on machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/api/UPbitApi.kt
> +    fun getTicker(@Query("markets") markets: String): Flowable<List<TickerModel>>
RESTful은 Single로만 해도 돼요

2019-06-29 09:26 UTC, sjjeong commented on machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/base/BaseFragment.kt
> +        return view
```kotlin
return inflater.inflate(layoutId, container, false)
```
로 하시면 돼요
=를 사용하면 더 축약이 가능합니다

2019-06-29 09:58 UTC, machine-human commented on machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/adapter/recyclerviewadapter/MainListAdapter.kt
> +        holder?.setData(tickerList[position])
fdsa

2019-06-29 10:01 UTC, machine-human commented on machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/base/BaseFragment.kt
> +        return view
수정 완료 했습니다. 감사합니다.
ebe84e7

2019-06-29 10:02 UTC, machine-human commented on machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/adapter/recyclerviewadapter/MainListAdapter.kt
> +        holder?.setData(tickerList[position])
수정 완료했습니다. 감사합니다.

c4d11f0

2019-06-29 10:02 UTC, machine-human commented on machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/api/UPbitApi.kt
> +    fun getTicker(@Query("markets") markets: String): Flowable<List<TickerModel>>
수정 완료했습니다. 감사합니다.

c4d11f0

2019-06-29 12:40 UTC, sport0102 approved these changes

2019-07-01 11:49 UTC, sjjeong commented on machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/api/UPbitApi.kt
> +    fun getTicker(@Query("markets") markets: String): Flowable<List<TickerModel>>
ebe84e71fc33282c5767d20441b55f87584d5363

2019-07-01 11:49 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-07-01 12:16 UTC, merged