HW-7 DI(Koin)적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #711
Opened 2020-06-24 10:54 UTC by LeeChungWoo92

안녕하세요!
Koin 적용해봤습니다. 
이번에 좀많이 어려워서 계속공부하고 리뷰받으면서  
수정하겠습니다!

2020-06-25 13:32 UTC, hwaniiidev commented
문제 없다고 봅니다!! 

다만 여유가 되신다면 retrofit 사용하여 http 통신하는 부분에서도 koin을 활용할 수 있을 것 같습니다. 
저희 과제에서 통신이 1번 뿐이긴 하지만 실제 프로젝트에선 여러번 사용되니 koin적용해봐도 좋을 것 같습니다 .

그리고 localDataSource가 없던데 지난주 과제까지만해도 있지 않았나요 ?? 

나머지는 굳입니다

2020-06-25 13:33 UTC, hwaniiidev approved these changes

2020-06-26 11:05 UTC, sjjeong requested changes
Repository에 RemoteDataSource를 주입시켜주는 형태로 해주세요
RemoteDataSource에도 api를 주입하는 방식으로 변경해주세요

2020-06-27 06:48 UTC, LeeChungWoo92 commented
ef81deb
6cc6772
b69a850
수정해 보았습니다.!

2020-06-27 13:16 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-06-28 04:53 UTC, merged