HW-7 : Di 적용 ( Koin )
sjjeong/GoogryAndroidArchitecutreStudy pull request #712
Opened 2020-06-24 11:20 UTC by chuuuul

## Koin 적용

### App Module
- Repository
- Local Data Source
- Remote Data Source
- Resource Provider

### API Module
- Retrofit

2020-06-24 12:52 UTC, SageHabitus requested changes

2020-06-24 12:52 UTC, developer-sungjae commented on 2005/chuuuul/ArchitectureStudy/app/src/main/java/com/example/architecture/activity/search/SearchActivity.kt
> +                }
비즈니스 로직은 vm으로 빼주세요

2020-06-24 12:57 UTC, SageHabitus requested changes

2020-06-24 12:57 UTC, developer-sungjae commented on 2005/chuuuul/ArchitectureStudy/app/src/main/java/com/example/architecture/data/source/remote/NaverRemoteDataSourceImpl.kt
> +    private val movieSearchService by inject(MovieSearchService::class.java)
생성자로 받도록 해주시고  이 라인을 제거해주세요

2020-06-24 13:31 UTC, chuuuul commented on 2005/chuuuul/ArchitectureStudy/app/src/main/java/com/example/architecture/data/source/remote/NaverRemoteDataSourceImpl.kt
> +    private val movieSearchService by inject(MovieSearchService::class.java)
3edcbab
감사합니다. 수정했습니다.

2020-06-24 17:44 UTC, chuuuul commented on 2005/chuuuul/ArchitectureStudy/app/src/main/java/com/example/architecture/activity/search/SearchActivity.kt
> +                }
1a1ef4e
감사합니다. 수정했습니다.

2020-06-25 03:38 UTC, SageHabitus approved these changes

2020-06-25 03:38 UTC, developer-sungjae commented
고생하셨습니다!

2020-06-26 11:06 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-06-28 05:01 UTC, merged