hw 7 DI(Koin) 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #714
Opened 2020-06-26 04:24 UTC by RyuC0605

안녕하세요. 류승윤 입니다.
이번주는 개인 용무가 많아서 과제가 늦어졌습니다.
Koin 적용 코드를 커밋하오니, 검토부탁드립니다.

감사합니다.

2020-06-26 11:01 UTC, KimSangJin2 commented
안녕하세요 승윤님 :)

*MainActivity.class
vm.movies.observe(this, Observer {
            val inputList = vm.movies.value ?: return@Observer

            val adt = lv_contents.adapter as MovieAdapter
            **val movieList = adt.getMovieList()
            movieList.clear()
            movieList.addAll(inputList)
            adt.notifyDataSetChanged()**
        })

이 부분을 adapter.refreshData() 처름 함수를 하나 만들어서 호출하는 식으로 진행하면 더 이해하기 쉬운 코드가 될 것 같습니다!

(이번 과제에서 코멘트 드릴 부분을 딱히 못 찾아서, 다른 코드를 보며 작은 의견 하나 내봅니다 ㅎㅎ )

2020-06-26 11:08 UTC, sangjinKIM93 commented
안녕하세요 승윤님 :)

*MainActivity.class

> vm.movies.observe(this, Observer {
> 
>                 val inputList = vm.movies.value ?: return@Observer  
>                 val adt = lv_contents.adapter as MovieAdapter  
>                 val movieList = adt.getMovieList()  
>                 movieList.clear()  
>                 movieList.addAll(inputList)  
>                 adt.notifyDataSetChanged()
>         })

이 부분을 adapter.refreshData() 처름 함수를 하나 만들어서 호출하는 식으로 진행하면 더 이해하기 쉬운 코드가 될 것 같습니다!

(이번 과제에서 코멘트 드릴 부분을 딱히 못 찾아서, 다른 코드를 보며 작은 의견 하나 내봅니다 ㅎㅎ )

2020-06-26 11:09 UTC, sjjeong requested changes
RemoteDataSource에서 사용하는 Retrofit api도 생성자를 통해 전달하도록 변경해주세요

2020-06-26 12:51 UTC, RyuC0605 commented
> RemoteDataSource에서 사용하는 Retrofit api도 생성자를 통해 전달하도록 변경해주세요

6461223ef6b538a36f79a7d32a8713e7c9196dad
수정하였습니다.

2020-06-26 12:52 UTC, RyuC0605 commented
> 안녕하세요 승윤님 :)
> 
> *MainActivity.class
> 
> > vm.movies.observe(this, Observer {
> > ```
> >             val inputList = vm.movies.value ?: return@Observer  
> >             val adt = lv_contents.adapter as MovieAdapter  
> >             val movieList = adt.getMovieList()  
> >             movieList.clear()  
> >             movieList.addAll(inputList)  
> >             adt.notifyDataSetChanged()
> >     })
> > ```
> 
> 이 부분을 adapter.refreshData() 처름 함수를 하나 만들어서 호출하는 식으로 진행하면 더 이해하기 쉬운 코드가 될 것 같습니다!
> 
> (이번 과제에서 코멘트 드릴 부분을 딱히 못 찾아서, 다른 코드를 보며 작은 의견 하나 내봅니다 ㅎㅎ )

692c1d5232efa66492751bf67c874af108bc307d
수정하였습니다

2020-06-27 13:15 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-06-28 10:43 UTC, sangjinKIM93 approved these changes
늦어서 죄송합니다 :)
LGTM~!

2020-06-28 11:51 UTC, merged