HW-1 : 네이버 영화 api를 이용한 영화 ui 리스트
sjjeong/GoogryAndroidArchitecutreStudy pull request #720
Opened 2020-06-28 07:42 UTC by songmilee

- RecyclerView를 이용해 영화 정보 리스트 보여주기
- retrofit2를 이용한 네트워크 통신
- glide를 이용한 이미지 로딩

2020-06-29 05:08 UTC, manjee-study commented on class12/songmilee/class12Android/app/src/main/java/mi/song/class12android/view/MovieAdapter.kt
> +        private val  tvTitle:TextView = itemView.findViewById(R.id.tv_title)
41,42,43 라인 소스 정렬 필요할거 같습니다 :)

2020-06-29 05:30 UTC, sjjeong commented
@songmilee `Merge Needed`는 제가 추가하는 라벨이에요
@manjee-study 변경 사항이 필요하면 request change로 리뷰해주시면 됩니다.

2020-06-29 11:04 UTC, songmilee commented on class12/songmilee/class12Android/app/src/main/java/mi/song/class12android/view/MovieAdapter.kt
> +        private val  tvTitle:TextView = itemView.findViewById(R.id.tv_title)
말씀해주신 변수 라인 정렬하였습니다! (a09dcd5)

2020-06-29 11:06 UTC, songmilee commented
@sjjeong 저번 OT 때 들은게 아직 헷갈렸습니다. 주의하겠습니다...!!

2020-06-30 05:39 UTC, manjee-study approved these changes

2020-07-03 03:07 UTC, sjjeong commented
@manjee-study 
Mentor Needed를 추가 하실 때 Review Needed는 제거하시면 안됩니다.

2020-07-03 03:18 UTC, sjjeong requested changes
전체적으로 reformat code도 해주세요

2020-07-03 03:18 UTC, sjjeong commented on class12/songmilee/class12Android/app/src/main/java/mi/song/class12android/network/MovieService.kt
> +    fun getMovieInfo(@Query("query") query:String) : Call<JsonObject>
JsonObject 대신 response json에 맞는 data class를 만들어서 사용해주세요

2020-07-03 03:18 UTC, sjjeong commented on class12/songmilee/class12Android/app/src/main/java/mi/song/class12android/view/MainActivity.kt
> +    fun initUI(){
initUi 입니다.

2020-07-03 03:18 UTC, sjjeong commented on class12/songmilee/class12Android/app/src/main/java/mi/song/class12android/view/MainActivity.kt
> +        listMovie?.layoutManager = LinearLayoutManager(baseContext)
LayoutManager는 xml에서 추가 할 수 있습니다.

2020-07-03 03:18 UTC, sjjeong commented on class12/songmilee/class12Android/app/src/main/java/mi/song/class12android/view/MainActivity.kt
> +    val queryMovie: View.OnClickListener = View.OnClickListener {
val이나 var로 선언하는 property는 클래스 맨 위에 위치해야 합니다.
지금은 fun 아래에 있네요

2020-07-03 03:18 UTC, sjjeong commented on class12/songmilee/class12Android/app/src/main/java/mi/song/class12android/view/MovieAdapter.kt
> +    fun resetMovieList(){
reset보다 clear가 적절하겠네요

2020-07-03 03:18 UTC, sjjeong commented on class12/songmilee/class12Android/app/src/main/java/mi/song/class12android/view/MovieAdapter.kt
> +    inner class MovieVH(itemView:View) : RecyclerView.ViewHolder(itemView){
MovieVh나 MovieViewHolder로 변경해주면 좋겠네요

2020-07-03 03:18 UTC, sjjeong commented on class12/songmilee/class12Android/app/src/main/java/mi/song/class12android/view/MovieAdapter.kt
> +            movieInfo.image?.let { Glide.with(itemView.context).load(movieInfo.image).diskCacheStrategy(DiskCacheStrategy.AUTOMATIC).into(imgThumbnail) }
method chaining이 많아지면 한 라인에 한 메소드를 쓰는 것을 권장합니다.

2020-07-03 08:56 UTC, songmilee commented on class12/songmilee/class12Android/app/src/main/java/mi/song/class12android/view/MainActivity.kt
> +    fun initUI(){
fa5b99ce

2020-07-03 08:57 UTC, songmilee commented on class12/songmilee/class12Android/app/src/main/java/mi/song/class12android/view/MainActivity.kt
> +        listMovie?.layoutManager = LinearLayoutManager(baseContext)
0cdbe020

2020-07-03 08:57 UTC, songmilee commented on class12/songmilee/class12Android/app/src/main/java/mi/song/class12android/view/MovieAdapter.kt
> +    inner class MovieVH(itemView:View) : RecyclerView.ViewHolder(itemView){
fda9d69e

2020-07-03 08:57 UTC, songmilee commented on class12/songmilee/class12Android/app/src/main/java/mi/song/class12android/view/MovieAdapter.kt
> +            movieInfo.image?.let { Glide.with(itemView.context).load(movieInfo.image).diskCacheStrategy(DiskCacheStrategy.AUTOMATIC).into(imgThumbnail) }
4afd80f0

2020-07-03 08:58 UTC, songmilee commented on class12/songmilee/class12Android/app/src/main/java/mi/song/class12android/view/MovieAdapter.kt
> +    fun resetMovieList(){
68a3faed

2020-07-03 08:58 UTC, songmilee commented on class12/songmilee/class12Android/app/src/main/java/mi/song/class12android/view/MainActivity.kt
> +    val queryMovie: View.OnClickListener = View.OnClickListener {
11f2062e

2020-07-03 14:09 UTC, songmilee commented on class12/songmilee/class12Android/app/src/main/java/mi/song/class12android/network/MovieService.kt
> +    fun getMovieInfo(@Query("query") query:String) : Call<JsonObject>
data class 추가 (9c6ff5e1)
callback type 변경(f6c33422)

2020-07-03 14:45 UTC, sjjeong requested changes

2020-07-03 14:45 UTC, sjjeong commented on class12/songmilee/class12Android/app/src/main/java/mi/song/class12android/network/RetrofitHelper.kt
> +    companion object {
이렇게 되면 RetrofitHelper를 object로 만들면 돼요

2020-07-03 14:45 UTC, sjjeong commented on class12/songmilee/class12Android/app/src/main/java/mi/song/class12android/view/MainActivity.kt
> +    var movieAdapter: MovieAdapter? = null
lateinit var나 lazy를 사용하면 nonnull하게 사용 할 수 있어요

2020-07-03 23:05 UTC, songmilee commented on class12/songmilee/class12Android/app/src/main/java/mi/song/class12android/network/RetrofitHelper.kt
> +    companion object {
68323ad4

2020-07-03 23:09 UTC, songmilee commented on class12/songmilee/class12Android/app/src/main/java/mi/song/class12android/network/RetrofitHelper.kt
> +    companion object {
68323ad4

2020-07-03 23:12 UTC, songmilee commented on class12/songmilee/class12Android/app/src/main/java/mi/song/class12android/view/MainActivity.kt
> +    var movieAdapter: MovieAdapter? = null
9141c5ef

2020-07-04 04:57 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-07-04 14:01 UTC, merged