Class12/dlqkfzlr hw 1
sjjeong/GoogryAndroidArchitecutreStudy pull request #721
Opened 2020-06-28 12:19 UTC by dlqkfzlr

1st Class Assignment :)

2020-06-29 08:45 UTC, ysj1224 commented on class12/dlqkfzlr/study/app/src/main/java/m/woong/architecturestudy/ui/adapter/MovieAdapter.kt
> +        val imageImageView: ImageView
```suggestion
        val imageImageView: ImageView = v.movie_image 
```
이런식으로 바로 선언하고 init은 빼도 괜찮지 않을까요?

2020-06-29 08:45 UTC, ysj1224 commented on class12/dlqkfzlr/study/app/src/main/java/m/woong/architecturestudy/ui/item/MovieItem.kt
> +package m.woong.architecturestudy.ui.item
MovieResponse 에 있는 Data클래스를 활용하면 이 클래스는 필요 없을것 같아요!

2020-06-29 11:36 UTC, dlqkfzlr commented on class12/dlqkfzlr/study/app/src/main/java/m/woong/architecturestudy/ui/adapter/MovieAdapter.kt
> +        val imageImageView: ImageView
제안사항 반영했습니다 :)
(b68d69)

2020-06-29 11:48 UTC, dlqkfzlr commented on class12/dlqkfzlr/study/app/src/main/java/m/woong/architecturestudy/ui/item/MovieItem.kt
> +package m.woong.architecturestudy.ui.item
네 반영해서 교체하였습니다.
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/commit/e414aeca650873074f99d254898fb0e39108f36f

2020-06-30 00:30 UTC, ysj1224 approved these changes

2020-06-30 00:32 UTC, ysj1224 commented
approve 했습니다!

2020-07-01 10:50 UTC, sjjeong requested changes

2020-07-01 10:50 UTC, sjjeong commented on class12/dlqkfzlr/study/app/src/main/java/m/woong/architecturestudy/ui/main/MainActivity.kt
> +        val service = MovieApi.invoke(NetworkConnectionInterceptor(this))
retrofit으로 만든 api interface 객체는 매번 새로 만들 필요가 없습니다.
한번만 만들어서 사용하도록 해주세요

2020-07-01 10:50 UTC, sjjeong commented on class12/dlqkfzlr/study/app/src/main/java/m/woong/architecturestudy/network/NetworkConnectionInterceptor.kt
> +        val client_secret = "0vJ3mpzX6_"
상수는 const를 추가해주시고 CLIENT_ID처럼 대문자로 표시해주세요

2020-07-01 10:50 UTC, sjjeong commented on class12/dlqkfzlr/study/app/src/main/java/m/woong/architecturestudy/network/NetworkConnectionInterceptor.kt
> +            throw IOException("Make sure you have an active data connection")
라인이 달라지면 {}를 추가해줘야 합니다.

2020-07-01 10:50 UTC, sjjeong commented on class12/dlqkfzlr/study/app/src/main/java/m/woong/architecturestudy/network/NetworkConnectionInterceptor.kt
> +    private val applicationContext = context.applicationContext
ApplicationContext를 사용한다면 Application 클래스를 만들어서 Application객체를 사용하도록 해주세요

2020-07-01 10:50 UTC, sjjeong commented on class12/dlqkfzlr/study/app/src/main/java/m/woong/architecturestudy/ui/adapter/MovieAdapter.kt
> +    }
nested class는 클래스 맨 아래에 있어야 합니다.
https://kotlinlang.org/docs/reference/coding-conventions.html#class-layout

2020-07-01 10:50 UTC, sjjeong commented on class12/dlqkfzlr/study/app/src/main/java/m/woong/architecturestudy/ui/adapter/MovieAdapter.kt
> +class MovieAdapter(private val movieList: ArrayList<MovieResponse.Item>) :
Adapter에서 사용하는 리스트 객체를 외부와 공유하지 않도록 해주세요
아이템 갱신은 Adapter에 함수를 만들고 함수를 통해서만 업데이트 하도록 해주세요

2020-07-01 10:50 UTC, sjjeong commented on class12/dlqkfzlr/study/app/src/main/java/m/woong/architecturestudy/ui/adapter/MovieAdapter.kt
> +            holder.titleTextView.text =
os 버전에 따라 html텍스트를 가져오는 함수를 만들어서 사용하도록 변경해주세요

2020-07-01 10:50 UTC, sjjeong commented on class12/dlqkfzlr/study/app/src/main/java/m/woong/architecturestudy/ui/main/MainActivity.kt
> +    private lateinit var viewAdapter: RecyclerView.Adapter<*>
타입을 MovieAdapter로 변경해주세요

2020-07-01 10:50 UTC, sjjeong commented on class12/dlqkfzlr/study/app/src/main/java/m/woong/architecturestudy/ui/main/MainActivity.kt
> +            var keyword = movie_search_et.text
val로 변경해주세요

2020-07-01 10:50 UTC, sjjeong commented on class12/dlqkfzlr/study/app/src/main/java/m/woong/architecturestudy/ui/main/MainActivity.kt
> +            layoutManager = viewManager
LayoutManager는 xml에서도 추가할수 있습니다.

2020-07-01 10:50 UTC, sjjeong commented on class12/dlqkfzlr/study/app/src/main/java/m/woong/architecturestudy/ui/main/MainActivity.kt
> +                        movieList.add(
add대신 addAll을 사용하면 반복문 없이 처리가 가능합니다.

2020-07-01 10:50 UTC, sjjeong commented on class12/dlqkfzlr/study/app/src/main/res/layout/activity_main.xml
> +            android:layout_width="match_parent"
weight를 사용하면 0dp를 주면 됩니다.

2020-07-02 14:36 UTC, dlqkfzlr commented on class12/dlqkfzlr/study/app/src/main/java/m/woong/architecturestudy/ui/main/MainActivity.kt
> +                        movieList.add(
반영했습니다.

2020-07-03 10:59 UTC, dlqkfzlr commented on class12/dlqkfzlr/study/app/src/main/java/m/woong/architecturestudy/ui/main/MainActivity.kt
> +    private lateinit var viewAdapter: RecyclerView.Adapter<*>
수정했습니다
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/commit/1ffd1220799aeaef534e806d1e5cb33ae62e8967

2020-07-03 11:00 UTC, dlqkfzlr commented on class12/dlqkfzlr/study/app/src/main/java/m/woong/architecturestudy/ui/main/MainActivity.kt
> +            layoutManager = viewManager
수정했습니다
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/commit/1ffd1220799aeaef534e806d1e5cb33ae62e8967

2020-07-03 11:01 UTC, dlqkfzlr commented on class12/dlqkfzlr/study/app/src/main/java/m/woong/architecturestudy/ui/adapter/MovieAdapter.kt
> +    }
수정했습니다.
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/commit/04a281350f0ffbe0f93063548e281a6718d61a2e

2020-07-03 11:02 UTC, dlqkfzlr commented on class12/dlqkfzlr/study/app/src/main/java/m/woong/architecturestudy/network/NetworkConnectionInterceptor.kt
> +        val client_secret = "0vJ3mpzX6_"
수정했습니다
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/commit/762bfb96214f173bb4d65a950fbbf0f7a8d14145

2020-07-03 11:02 UTC, dlqkfzlr commented on class12/dlqkfzlr/study/app/src/main/java/m/woong/architecturestudy/ui/main/MainActivity.kt
> +        val service = MovieApi.invoke(NetworkConnectionInterceptor(this))
수정했습니다
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/commit/699647f881f698e6bd5d0f3526ae2acf095e6e4a

2020-07-03 11:02 UTC, dlqkfzlr commented on class12/dlqkfzlr/study/app/src/main/res/layout/activity_main.xml
> +            android:layout_width="match_parent"
수정했습니다
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/commit/225d1cbc79c1d2c488e9d7344d79fca082d0e4a5

2020-07-03 11:03 UTC, dlqkfzlr commented on class12/dlqkfzlr/study/app/src/main/java/m/woong/architecturestudy/ui/main/MainActivity.kt
> +            var keyword = movie_search_et.text
수정했습니다.
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/commit/ba688868642a308884667b532310dd812522643b

2020-07-03 12:49 UTC, dlqkfzlr commented on class12/dlqkfzlr/study/app/src/main/java/m/woong/architecturestudy/network/NetworkConnectionInterceptor.kt
> +            throw IOException("Make sure you have an active data connection")
수정했습니다
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/commit/762bfb96214f173bb4d65a950fbbf0f7a8d14145

2020-07-03 12:49 UTC, dlqkfzlr commented on class12/dlqkfzlr/study/app/src/main/java/m/woong/architecturestudy/network/NetworkConnectionInterceptor.kt
> +    private val applicationContext = context.applicationContext
혹시 그 이유를 좀 알려주실 수 있을까요?

2020-07-03 13:18 UTC, dlqkfzlr commented on class12/dlqkfzlr/study/app/src/main/java/m/woong/architecturestudy/ui/adapter/MovieAdapter.kt
> +            holder.titleTextView.text =
수정했습니다.
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/commit/4db8f033066a0f7d2723270b5f38e923f9789b90

2020-07-03 14:55 UTC, sjjeong commented on class12/dlqkfzlr/study/app/src/main/java/m/woong/architecturestudy/network/NetworkConnectionInterceptor.kt
> +    private val applicationContext = context.applicationContext
@dlqkfzlr 
Application Context는 앱이 실행되고 메모리에서 없어지기 전까지는 계속 유지되는 객체이기 때문에 저렇게 받을 필요가 없습니다

2020-07-03 14:55 UTC, sjjeong commented on class12/dlqkfzlr/study/app/src/main/java/m/woong/architecturestudy/ui/adapter/MovieAdapter.kt
> +class MovieAdapter(private val movieList: ArrayList<MovieResponse.Item>) :
@dlqkfzlr 
여기 수정하셨나요?

2020-07-03 14:57 UTC, sjjeong requested changes

2020-07-03 14:57 UTC, sjjeong commented on class12/dlqkfzlr/study/app/src/main/java/m/woong/architecturestudy/network/NetworkConnectionInterceptor.kt
> +    context: Context
이건 더이상 필요 없겠네요

2020-07-03 14:58 UTC, sjjeong commented
@dlqkfzlr 
누락된 부분도 추가 수정해주세요 
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/721#discussion_r449621892

2020-07-03 17:29 UTC, dlqkfzlr commented on class12/dlqkfzlr/study/app/src/main/java/m/woong/architecturestudy/network/NetworkConnectionInterceptor.kt
> +    private val applicationContext = context.applicationContext
수정했습니다.
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/commit/76d95197126c59ab63956b52cb5ab420a9fd7b93

2020-07-03 17:30 UTC, dlqkfzlr commented on class12/dlqkfzlr/study/app/src/main/java/m/woong/architecturestudy/network/NetworkConnectionInterceptor.kt
> +    context: Context
수정했습니다.
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/commit/76d95197126c59ab63956b52cb5ab420a9fd7b93

2020-07-03 17:31 UTC, dlqkfzlr commented on class12/dlqkfzlr/study/app/src/main/java/m/woong/architecturestudy/ui/adapter/MovieAdapter.kt
> +class MovieAdapter(private val movieList: ArrayList<MovieResponse.Item>) :
수정했습니다.
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/commit/bf496d8341af2d92ef7fed5da4ee9005b04b5dd2
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/commit/7fcf1397d973eff0305f2f37779e21e4f64871c5

2020-07-04 01:32 UTC, sjjeong requested changes

2020-07-04 01:32 UTC, sjjeong commented on class12/dlqkfzlr/study/app/src/main/java/m/woong/architecturestudy/App.kt
> +            get() = context
이렇게 하면 됩니다.
```kotlin
var appContext: Context?
    private set
```

2020-07-04 01:32 UTC, sjjeong commented on class12/dlqkfzlr/study/app/src/main/java/m/woong/architecturestudy/network/NetworkConnectionInterceptor.kt
> +class NetworkConnectionInterceptor() : Interceptor {
생성자에 아무것도 없다면 ()는 제거해도 됩니다.

2020-07-04 01:32 UTC, sjjeong commented on class12/dlqkfzlr/study/app/src/main/java/m/woong/architecturestudy/ui/adapter/MovieAdapter.kt
> +        movieList.clear()
여기도 notify를 추가해주셔야겠네요 

아니면 resetData()라는 함수를 만들고 내부에서 clear, addAll, notify를 해주면 됩니다.

2020-07-04 02:05 UTC, dlqkfzlr commented on class12/dlqkfzlr/study/app/src/main/java/m/woong/architecturestudy/ui/adapter/MovieAdapter.kt
> +        movieList.clear()
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/commit/6e0fda89c2e82aa2255040e060307064b9f45ec3

2020-07-04 02:05 UTC, dlqkfzlr commented on class12/dlqkfzlr/study/app/src/main/java/m/woong/architecturestudy/network/NetworkConnectionInterceptor.kt
> +class NetworkConnectionInterceptor() : Interceptor {
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/commit/b97dabdc32035e9818ec39c9b44fba356351ccbd

2020-07-04 02:06 UTC, dlqkfzlr commented on class12/dlqkfzlr/study/app/src/main/java/m/woong/architecturestudy/App.kt
> +            get() = context
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/commit/b218c46995cd44d7d6c172267b35c5b86b57f674

2020-07-04 03:01 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-07-04 03:02 UTC, merged