HW-8 멀티 모듈 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #722
Opened 2020-06-28 13:08 UTC by RyuC0605

안녕하세요. 류승윤 입니다.
기존 과제를 모듈로 쪼개는 작업을 진행하였습니다.
리뷰 부탁드립니다.

감사합니다.

PS : 
석준님 마지막 날인데 너무 투박하게 마지막 인사를 드린 것 같아 아쉽네요. 2개월 동안  많은 것을 배웠습니다. 감사합니다.
상진님 서로 리뷰 하며 좋은 경험을 했습니다. 좋은 곳 취업하길 기원할게요.

2020-06-30 07:17 UTC, sangjinKIM93 approved these changes
8주 동안 감사했습니다 :)
승윤님 코드와 피드백 덕분에 더욱 값진 시간들이었네요.
앞으로 하시는 일 승승장구 하시길 기원하겠습니다 ~! 

삼성TM~👍

2020-07-02 14:28 UTC, sjjeong requested changes

2020-07-02 14:28 UTC, sjjeong commented on 2005/RyuC0605/Android_X/data/src/main/java/r/test/data/MainViewModel.kt
> +package r.test.data
ViewModel은 app module에 있으면 됩니다~

2020-07-03 02:13 UTC, RyuC0605 commented on 2005/RyuC0605/Android_X/data/src/main/java/r/test/data/MainViewModel.kt
> +package r.test.data
5cecd06d47138a1c894a09123b561dab82da4777

app 모듈로 이동하였습니다.

석준님 8주동안 수고 많으셨습니다. 몸 건강하세요.

2020-07-03 02:25 UTC, sjjeong requested changes

2020-07-03 02:25 UTC, sjjeong commented on 2005/RyuC0605/Android_X/data/src/main/java/r/test/data/dataModule.kt
> +    viewModel { MainViewModel(get(), get()) }
에러가 나는 부분이라서 제거 해서 에러를 없애주세요

2020-07-03 02:25 UTC, sjjeong commented on 2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/KoinApplication.kt
> +            modules(dataModule)
modules(appModule, dataModule)로 했었는데 이렇게해도 동작하는 것을 첨 알았네요
이부분은 수정하지 않아도 됩니다.

2020-07-03 02:30 UTC, RyuC0605 commented on 2005/RyuC0605/Android_X/data/src/main/java/r/test/data/dataModule.kt
> +    viewModel { MainViewModel(get(), get()) }
e1f515873ebfc6cfcf2c12d89edd3f792e0eb516

수정했던 부분인데 커밋 할때 누락되었나보네요...
커밋 하였습니다.
마지막 까지 꼼꼼한 리뷰 감사 드립니다.

2020-07-03 02:34 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-07-03 02:34 UTC, sjjeong commented
8주간 고생 많으셨어요!

2020-07-03 02:49 UTC, merged