HW-1 : 네이버 영화 API를 이용한 영화 목록 페이지 만들기
sjjeong/GoogryAndroidArchitecutreStudy pull request #723
Opened 2020-06-28 13:19 UTC by DWL5

2020-06-29 05:32 UTC, sjjeong commented
@DWL5 이후에 commit하실 때 commit 앞에 HW-1 추가하도록 해주세요

2020-06-29 12:38 UTC, pgshoot13 requested changes
1. minSdkVersion 26 -> 21~24
2. Movie.kt 11, 18라인 정렬 요청

2020-06-29 12:38 UTC, pgshoot13 commented on class12/DWL5/study/app/src/main/java/com/world/tree/architecturestudy/Movie.kt
> +        val title:String,
11, 18번 정렬 부탁드립니다.

2020-06-29 12:38 UTC, pgshoot13 commented on class12/DWL5/study/app/build.gradle
> +        minSdkVersion 26
크리티컬한 부분은 아니지만,
minSdkVersion을 21~24이 좋지 않을까요?

2020-06-30 01:37 UTC, DWL5 commented on class12/DWL5/study/app/src/main/java/com/world/tree/architecturestudy/Movie.kt
> +        val title:String,
넵 리뷰 감사합니다. 안드로이드 스튜디오의 Crtl + L로 정렬했습니다.

2020-06-30 02:22 UTC, DWL5 commented on class12/DWL5/study/app/build.gradle
> +        minSdkVersion 26
네 min sdk21로 적용하였습니다. retrofit2 라이브러리 넣을 때, 26으로 바꾸라는 에러가 났었던거 같은데..
찾아보니 아래와 같이 되어 있네요.
Retrofit requires at minimum Java 8+ or Android API 21+.

2020-06-30 02:24 UTC, pgshoot13 commented on class12/DWL5/study/app/build.gradle
> +        minSdkVersion 26
넵 거의 대부분의 통신이 21부터 가능하더라구요. 수고하셨습니다!

2020-06-30 04:58 UTC, sjjeong commented
@pgshoot13 
Answer Needed를 추가하시면 Review Needed는 제거해주셔야 해요

2020-06-30 11:09 UTC, pgshoot13 approved these changes

2020-07-03 03:03 UTC, sjjeong requested changes

2020-07-03 03:03 UTC, sjjeong commented on class12/DWL5/study/app/src/main/java/com/world/tree/architecturestudy/MovieAdapter.kt
> +        Glide.with(context).load(movies[position].image)
context대신 holder.itemView.imgPoster 를 넣어주시고 Adapter에 생성자로 context를 받는 부분은 제거해주세요

2020-07-03 03:03 UTC, sjjeong commented on class12/DWL5/study/app/src/main/java/com/world/tree/architecturestudy/MovieAdapter.kt
> +        this.movies = data
List객체를 넣어주지 마시고 list안에 있는 Movie.Item을 넣어주도록 해주세요
Adapter가 가지고 있는 movies는 val로 선언해서 초기에 List객체를 만들어주세요

2020-07-03 03:03 UTC, sjjeong commented on class12/DWL5/study/app/src/main/java/com/world/tree/architecturestudy/RetrofitService.kt
> +    fun getService(): RetrofitService = retrofit.create(RetrofitService::class.java)
이것도 함수보다 val로 가지고 있으면 됩니다.

2020-07-03 03:03 UTC, sjjeong commented on class12/DWL5/study/app/src/main/java/com/world/tree/architecturestudy/MainActivity.kt
> +        recyclerView.layoutManager = LinearLayoutManager(this)
LayoutManager는 xml에서 추가해줄 수 있어요

2020-07-03 12:32 UTC, DWL5 commented on class12/DWL5/study/app/src/main/java/com/world/tree/architecturestudy/MovieAdapter.kt
> +        Glide.with(context).load(movies[position].image)
넵 리뷰 감사드립니다.

2020-07-03 12:35 UTC, DWL5 commented on class12/DWL5/study/app/src/main/java/com/world/tree/architecturestudy/MovieAdapter.kt
> +        this.movies = data
편한방법으로 DatasetChange를 사용하고 있었네요. 각 상황에 맞는 함수를 사용하도록 해야겠습니다. ㅠ

2020-07-03 12:36 UTC, DWL5 commented on class12/DWL5/study/app/src/main/java/com/world/tree/architecturestudy/RetrofitService.kt
> +    fun getService(): RetrofitService = retrofit.create(RetrofitService::class.java)
넵 리뷰 감사드립니다.

2020-07-03 12:36 UTC, DWL5 commented on class12/DWL5/study/app/src/main/java/com/world/tree/architecturestudy/MainActivity.kt
> +        recyclerView.layoutManager = LinearLayoutManager(this)
넵 리뷰 감사드립니다.

2020-07-03 12:36 UTC, DWL5 reviewed
반영했습니다.

2020-07-03 12:36 UTC, DWL5 commented
반영했습

2020-07-03 15:13 UTC, sjjeong commented
@DWL5 
코멘트에 커밋 아이디 남겨주세요

2020-07-03 15:15 UTC, sjjeong requested changes

2020-07-03 15:15 UTC, sjjeong commented on class12/DWL5/study/app/src/main/java/com/world/tree/architecturestudy/MainActivity.kt
> +                            }
반복문 없이 List에 addAll이라는 함수를 사용하면 됩니다.

2020-07-05 08:41 UTC, DWL5 commented on class12/DWL5/study/app/src/main/java/com/world/tree/architecturestudy/MainActivity.kt
> +                            }
097ed79f57a83fd9f16eb1d71f8d1962497444c3

반영했습니다.

2020-07-05 11:45 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-07-05 12:57 UTC, merged