Hw 1
sjjeong/GoogryAndroidArchitecutreStudy pull request #725
Opened 2020-06-29 12:58 UTC by ysj1224

2020-06-30 14:22 UTC, dlqkfzlr commented on class12/ysj1224/Study/app/build.gradle
> +    implementation 'com.google.code.gson:gson:2.8.6'
Dependency 추가시에 주석을 달아주시면 나중에 항목별 library 관리가 편하실 것 같습니다. (ex. 버전 관리 및 수정, 삭제)

2020-06-30 14:22 UTC, dlqkfzlr commented on class12/ysj1224/Study/app/src/main/java/com/example/study/RecyclerAdapter.kt
> +        holder.title.text = Html.fromHtml(item[position].title).toString()
'fromHtml(String!)' 메소드가 deprecated되어서 다른 메소드를 사용하시거나 버전별로 분기를 치시면 더 좋을 것 같습니다.

2020-06-30 14:22 UTC, dlqkfzlr commented on class12/ysj1224/Study/app/src/main/java/com/example/study/MainActivity.kt
> +                Toast.makeText(this@MainActivity, "검색어를 입력해주세요.", Toast.LENGTH_SHORT).show()
꼼꼼한 예외처리 좋습니다 :)

2020-06-30 14:22 UTC, dlqkfzlr commented on class12/ysj1224/Study/app/src/main/java/com/example/study/MainActivity.kt
> +            override fun onResponse(call: Call<NaverApiData>, response: Response<NaverApiData>) {
onResponse 시에도 response인자값에 따른 예외처리가 필요할 것 같습니다.

2020-07-01 04:43 UTC, ysj1224 commented on class12/ysj1224/Study/app/build.gradle
> +    implementation 'com.google.code.gson:gson:2.8.6'
d222001dc90f515d61e991aa5d0205bc41237d4f

2020-07-01 04:44 UTC, ysj1224 commented on class12/ysj1224/Study/app/src/main/java/com/example/study/RecyclerAdapter.kt
> +        holder.title.text = Html.fromHtml(item[position].title).toString()
다른 메소드 사용했습니다! 11eeb877a6e9bea0ea05553ff40420ddf5017efe

2020-07-01 04:45 UTC, ysj1224 commented on class12/ysj1224/Study/app/src/main/java/com/example/study/MainActivity.kt
> +            override fun onResponse(call: Call<NaverApiData>, response: Response<NaverApiData>) {
response결과값 처리했습니다! 90acf395ece629214747e1e21b3f1f01b70eae9d

2020-07-01 06:09 UTC, dlqkfzlr approved these changes
수고하셨습니다!

2020-07-01 11:02 UTC, sjjeong requested changes

2020-07-01 11:02 UTC, sjjeong commented on class12/ysj1224/Study/app/src/main/java/com/example/study/MainActivity.kt
> +    private lateinit var viewAdapter: RecyclerView.Adapter<*>
사용하는 Adapter 클래스 타입으로 선언해주세요

2020-07-01 11:02 UTC, sjjeong commented on class12/ysj1224/Study/app/src/main/java/com/example/study/MainActivity.kt
> +                    recyclerView.adapter = RecyclerAdapter(item)
Adapter를 매번 만들 필요가 없습니다.
한번만 만들어서 set하고 응답처리에서는 데이터만 전달해서 notify하도록 해주세요

2020-07-01 11:02 UTC, sjjeong commented on class12/ysj1224/Study/app/src/main/java/com/example/study/MainActivity.kt
> +                    item = response.body()!!.items
!!를 지양해주세요

2020-07-01 11:02 UTC, sjjeong commented on class12/ysj1224/Study/app/src/main/java/com/example/study/MainActivity.kt
> +            if (searchTitle == "") {
isEmpty()로 변경해주세요

2020-07-01 11:02 UTC, sjjeong commented on class12/ysj1224/Study/app/src/main/java/com/example/study/MainActivity.kt
> +                searchTitle = s.toString()
단순 text를 set하는 경우라면 TextChangedListener가 필요없습니다.
사용할 때 EditText에서 get해서 사용하도록 해주세요

2020-07-01 11:02 UTC, sjjeong commented on class12/ysj1224/Study/app/src/main/java/com/example/study/MainActivity.kt
> +            layoutManager = viewManager
LayoutManager는 xml에서 추가할 수 있습니다.

2020-07-01 11:02 UTC, sjjeong commented on class12/ysj1224/Study/app/src/main/java/com/example/study/MainActivity.kt
> +    private val baseUrl = "https://openapi.naver.com"
const val 로 선언하도록 해주세요

2020-07-01 11:02 UTC, sjjeong commented on class12/ysj1224/Study/app/src/main/java/com/example/study/RecyclerAdapter.kt
> +class RecyclerAdapter(apiItem: List<NaverApiData.Item>) :
List를 생성자를 통해서 받지 마시고 내부적으로 List객체를 가지고 있고 함수를 통해 데이터만 교체하도록 해주세요

2020-07-01 11:02 UTC, sjjeong commented on class12/ysj1224/Study/app/src/main/java/com/example/study/RecyclerAdapter.kt
> +        var image = view.iv_image
val로 선언해주세요

2020-07-01 11:02 UTC, sjjeong commented on class12/ysj1224/Study/app/src/main/res/layout/activity_main.xml
> +        android:layout_width="match_parent"
ConstraintLayout을 사용할 땐 match_parent를 사용하지 않도록 해주세요

2020-07-01 11:02 UTC, sjjeong commented on class12/ysj1224/Study/app/src/main/java/com/example/study/MainActivity.kt
> +        val service: NaverApiInterface = retrofit.create(NaverApiInterface::class.java)
이렇게 만든다면 NaverApiInterface다른곳에서 사용할 때 객체를 다시 만들게 됩니다.
object를 만들어서 singleton으로 관리하도록 해주세요

2020-07-02 07:42 UTC, ysj1224 commented on class12/ysj1224/Study/app/src/main/java/com/example/study/MainActivity.kt
> +    private lateinit var viewAdapter: RecyclerView.Adapter<*>
31fbbe1e
어댑터 선언 변경했습니다.

2020-07-02 07:43 UTC, ysj1224 commented on class12/ysj1224/Study/app/src/main/java/com/example/study/MainActivity.kt
> +                    recyclerView.adapter = RecyclerAdapter(item)
677112fd
어댑터 내부에 아이템 받아서 처리하는 함수 만들었습니다.

2020-07-02 07:44 UTC, ysj1224 commented on class12/ysj1224/Study/app/src/main/java/com/example/study/MainActivity.kt
> +                    item = response.body()!!.items
677112f
위 작업하면서 ?.let으로 변경하였습니다.

2020-07-02 07:44 UTC, ysj1224 commented on class12/ysj1224/Study/app/src/main/java/com/example/study/MainActivity.kt
> +            if (searchTitle == "") {
44caf430
변경완료!

2020-07-02 07:45 UTC, ysj1224 commented on class12/ysj1224/Study/app/src/main/java/com/example/study/MainActivity.kt
> +                searchTitle = s.toString()
d2192f14
바로 get해서 사용하도록 변경했습니다

2020-07-02 07:47 UTC, ysj1224 commented on class12/ysj1224/Study/app/src/main/java/com/example/study/MainActivity.kt
> +            layoutManager = viewManager
6429b8b4
레이아웃에서 설정하도록 변경했습니다.

2020-07-02 07:48 UTC, ysj1224 commented on class12/ysj1224/Study/app/src/main/java/com/example/study/MainActivity.kt
> +    private val baseUrl = "https://openapi.naver.com"
7ff2885c
변경완료!

2020-07-02 07:49 UTC, ysj1224 commented on class12/ysj1224/Study/app/src/main/java/com/example/study/RecyclerAdapter.kt
> +class RecyclerAdapter(apiItem: List<NaverApiData.Item>) :
677112fd
같이 진행했습니다.

2020-07-02 07:49 UTC, ysj1224 commented on class12/ysj1224/Study/app/src/main/java/com/example/study/RecyclerAdapter.kt
> +        var image = view.iv_image
97637070
변경완료!

2020-07-02 07:50 UTC, ysj1224 commented on class12/ysj1224/Study/app/src/main/java/com/example/study/MainActivity.kt
> +        val service: NaverApiInterface = retrofit.create(NaverApiInterface::class.java)
bff03419
인터페이스 안에서 다 처리했습니다.

2020-07-02 07:50 UTC, ysj1224 commented on class12/ysj1224/Study/app/src/main/res/layout/activity_main.xml
> +        android:layout_width="match_parent"
ba82b3c2
넵 0dp로 변경했습니다.

2020-07-03 03:05 UTC, sjjeong requested changes

2020-07-03 03:05 UTC, sjjeong commented on class12/ysj1224/Study/app/src/main/java/com/example/study/NaverApiInterface.kt
> +    fun service(): NaverApiInterface = retrofit.create(NaverApiInterface::class.java)
fun이 아니라 val로 선언해주세요

2020-07-03 03:05 UTC, sjjeong commented on class12/ysj1224/Study/app/src/main/java/com/example/study/RecyclerAdapter.kt
> +        item = apiItem
객체를 set하지 마시고 apiItem이 가지고 있는 NaverApiData.Item을 list에 넣어주도록 해주세요

2020-07-03 04:58 UTC, ysj1224 commented on class12/ysj1224/Study/app/src/main/java/com/example/study/NaverApiInterface.kt
> +    fun service(): NaverApiInterface = retrofit.create(NaverApiInterface::class.java)
ff786baa

2020-07-03 04:58 UTC, ysj1224 commented on class12/ysj1224/Study/app/src/main/java/com/example/study/RecyclerAdapter.kt
> +        item = apiItem
fa6a497d

2020-07-03 10:28 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-07-03 11:58 UTC, merged