HW-1: 네이버 영화 API를 이용한 영화 검색 페이지 만들기
sjjeong/GoogryAndroidArchitecutreStudy pull request #730
Opened 2020-06-30 11:41 UTC by manjee-study

2020-07-01 00:20 UTC, songmilee requested changes

2020-07-01 00:20 UTC, songmilee commented on class12/manjee-study/ArchitectureStudy/app/src/main/res/layout/activity_main.xml
> +    </androidx.recyclerview.widget.RecyclerView>
recyclerview 태그 안에 무언가 넣을게 아니라면 </androidx.recyclerview.widget.RecyclerView> => <androidx.recyclerview.widget.RecyclerView ... /> 로 바꾸는게 태그 관리 편할 것 같습니다

2020-07-01 05:25 UTC, songmilee requested changes

2020-07-01 05:25 UTC, songmilee commented on class12/manjee-study/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/network/MovieApi.kt
> +    )
저희가 계속 naver api를 쓰게 된다면 매번 header를 추가하는 것보다 interceptor로 넣는게 편할 것 같아요!

2020-07-01 08:57 UTC, manjee-study commented on class12/manjee-study/ArchitectureStudy/app/src/main/res/layout/activity_main.xml
> +    </androidx.recyclerview.widget.RecyclerView>
a298bf62646b2eae17be0d82fff231f2cbaf0534

2020-07-01 09:18 UTC, manjee-study commented on class12/manjee-study/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/network/MovieApi.kt
> +    )
955891853bd08888db342e78d28309b9a80c0c5a 그렇네요 수정했습니다!

2020-07-02 04:21 UTC, songmilee requested changes

2020-07-02 04:21 UTC, songmilee commented on class12/manjee-study/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/view/MovieAdapter.kt
> +        this.movieList.addAll(movieList)
addAll 함수를 사용하는 것은 Arrays.asList(data).toArray 과정을 거쳐 값을 중복적인 복사가 일어나는 것으로 알고 있습니다.
for loop을 이용한 add 나 System Api인 arraycopy를 이용하는 것이 좋아보입니다!

2020-07-03 03:23 UTC, sjjeong commented on class12/manjee-study/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/view/MovieAdapter.kt
> +        this.movieList.addAll(movieList)
addAll을 쓰는게 좋습니다.

2020-07-03 03:31 UTC, sjjeong requested changes

2020-07-03 03:31 UTC, sjjeong commented on class12/manjee-study/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/view/MainActivity.kt
> +        movieRecyclerView.layoutManager = LinearLayoutManager(this)
LayoutManager를 xml에서 추가할 수 있습니다.

2020-07-03 03:31 UTC, sjjeong commented on class12/manjee-study/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/network/MovieApiService.kt
> +class MovieApiService {
class가 아닌 object로 만들어도 됩니다.

2020-07-03 03:31 UTC, sjjeong commented on class12/manjee-study/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/network/MovieApiService.kt
> +    }
함수명은 create지만 실제로 create하는 작업은 아니고 단순 return만 해준다면 movieApiService로 접근하게 좋을 것 같습니다.

2020-07-03 03:31 UTC, sjjeong commented on class12/manjee-study/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/network/MovieApiService.kt
> +    var movieApiService: MovieApi = setRetrofit().create(MovieApi::class.java)
변경하지 않는다면 val로 선언해주세요

2020-07-03 03:31 UTC, sjjeong commented on class12/manjee-study/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/network/MovieApiService.kt
> +    private fun setRetrofit(): Retrofit {
이것도 함수보단 val로 선언하면 좋을 것 같습니다.

2020-07-03 03:32 UTC, sjjeong commented on class12/manjee-study/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/view/MovieAdapter.kt
> +        this.movieList.addAll(movieList)
@songmilee 
추가 의견이 없다면 approve 해주세요

2020-07-03 06:09 UTC, songmilee approved these changes

2020-07-03 11:29 UTC, manjee-study commented on class12/manjee-study/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/view/MainActivity.kt
> +        movieRecyclerView.layoutManager = LinearLayoutManager(this)
5ec54491a2cabc2d23d1de536481bcd4c392f004 수정 했습니다!

2020-07-03 11:30 UTC, manjee-study commented on class12/manjee-study/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/network/MovieApiService.kt
> +class MovieApiService {
4a465c12675e14f44d4bdac38689b6d6161885df
MovieApiService object로 변경 및 의미없는 메소드 들 val 로 변경했습니다

2020-07-03 15:16 UTC, sjjeong commented
@manjee-study 
아래 3개 코멘트에 대한 답이 없네요
응답 해주세요

2020-07-03 15:20 UTC, manjee-study commented on class12/manjee-study/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/network/MovieApiService.kt
> +    }
4a465c12675e14f44d4bdac38689b6d6161885df
movieApiService로 get()해서 사용하게 변경했습니다

2020-07-03 15:20 UTC, manjee-study commented on class12/manjee-study/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/network/MovieApiService.kt
> +    var movieApiService: MovieApi = setRetrofit().create(MovieApi::class.java)
4a465c12675e14f44d4bdac38689b6d6161885df
변경하지 않을 변수라 val로 선언했습니다

2020-07-03 15:21 UTC, manjee-study commented on class12/manjee-study/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/network/MovieApiService.kt
> +    private fun setRetrofit(): Retrofit {
4a465c12675e14f44d4bdac38689b6d6161885df
생각해보니 함수일 필요가 없어 val로 선언해 사용하도록 수정했습니다

2020-07-03 15:24 UTC, sjjeong commented
@manjee-study 
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/commit/4a465c12675e14f44d4bdac38689b6d6161885df
앞으로는 리뷰1개에 맞는 커밋을 하도록 해주세요

2020-07-03 15:24 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-07-03 15:26 UTC, merged