HW-8 Multi Module 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #731
Opened 2020-06-30 14:36 UTC by hwaniiidev

- Data관련 (repository, remote, local) 소스들 모듈화
- Mapper 로 Model 연동

2020-07-02 08:38 UTC, LeeChungWoo92 commented
잘하신것 같습니다. 
그동안 수고하셨습니다!!

2020-07-02 08:39 UTC, LeeChungWoo92 approved these changes

2020-07-03 02:33 UTC, sjjeong requested changes
1. RepositoryImpl도 data module에 있어야 합니다.
2. searchModule는 제거해주시고 mainViewModel를 사용하도록 해주세요
3. ApiCall object는 제거해도 될 것 같습니다.

2020-07-06 23:56 UTC, hwaniiidev commented
말씀해주신 3가지 모두 수정했습니다. 

궁금한게 있습니다. 
Mapper의 위치가 지금 본 app에 위치하고 있는데 이 위치가 맞나 헷갈립니다.
본 app에 위치 시킨건 본 app 모듈에서 사용할 dataModel의 형식을 data Module에서는 알 수 없고 
본 app 에서는 dataModule에서 사용되는 dataModel를 알 수 있기 때문에 본 app에 위치시킨 겁니다. 
근데 cleanArichitecture 다이어그램에서 보이는 mapper의 위치는 data Module이 맞다고 하는고 같네요

2020-07-11 10:58 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋
현재는 Domain 개념이 없어서 Mapper위치는 작업하신 위치가 맞습니다.
8주간 고생 많으셨어요~

2020-07-22 15:38 UTC, merged