HW-1: 네이버 API 영화 목록 검색 페이지 만들기
sjjeong/GoogryAndroidArchitecutreStudy pull request #732
Opened 2020-06-30 23:48 UTC by pgshoot13

1. recyclerView
2. retrofit
3. NaverAPI

2020-07-01 04:59 UTC, DWL5 commented
지금 작업 중이신건가요? 
아니면 잘 못 올리신게 아닌가 해서 코멘트 남깁니다!

2020-07-01 05:29 UTC, pgshoot13 commented
> 지금 작업 중이신건가요?
> 아니면 잘 못 올리신게 아닌가 해서 코멘트 남깁니다!

혹시 뭐가 잘못올라갔나요??

2020-07-01 05:32 UTC, pgshoot13 commented
> > 지금 작업 중이신건가요?
> > 아니면 잘 못 올리신게 아닌가 해서 코멘트 남깁니다!
> 
> 혹시 뭐가 잘못올라갔나요??

아...다시 확인해보겠습니다!

2020-07-01 05:52 UTC, pgshoot13 commented
> > 지금 작업 중이신건가요?
> > 아니면 잘 못 올리신게 아닌가 해서 코멘트 남깁니다!
> 
> 혹시 뭐가 잘못올라갔나요??

아 commit을 한꺼번에 올려서 죄송합니다...
다음번엔 꼭 잘라서 올리도록 하겠습니다...

2020-07-01 14:42 UTC, DWL5 reviewed
item = response.body()!!.items
이부분 response.body가 null일 수도 있어서
이런 식으로 null체크를 하는게 좋아보입니다.
response.body()?.let{
//code
}
---- 무시부탁드려요 ㅠㅠ

2020-07-01 14:44 UTC, DWL5 commented on class12/pgshoot13/HyApplication/app/src/main/java/com/hyper/hyapplication/MainActivity.kt
> +                item = response.body()!!.items
item = response.body()!!.items
이부분 response.body가 null일 수도 있어서
이런 식으로 null체크를 하는게 좋아보입니다.
response.body()?.let{
//code
}

2020-07-01 14:54 UTC, DWL5 commented on class12/pgshoot13/HyApplication/app/src/main/java/com/hyper/hyapplication/MainActivity.kt
> +                    adapter?.notifyDataSetChanged()
response.body()가 null인 경우도 있으니,
null체크 해야 할 것 같습니다.

저같은 경우는 아래와 같이 체크했습니다.
response.body?.let{
}

2020-07-01 14:54 UTC, DWL5 commented on class12/pgshoot13/HyApplication/app/src/main/java/com/hyper/hyapplication/MainActivity.kt
> +
clientId, clientSecert, baseUrl등은 상수로 사용해서
대문자, 언더바(?) 형태로 변수를 선언하는게 좋아 보입니다.

2020-07-01 14:56 UTC, DWL5 commented on class12/pgshoot13/HyApplication/app/src/main/java/com/hyper/hyapplication/MainActivity.kt
> +            setHasFixedSize(true)
Kotlin의 경우에는 findViewById를 사용하지 않고 xml에 정의된 id로 view에 바로 접근이 되는 걸로 알고 있습니다. 위의 private lateinit var recyclerView: RecyclerView 도 약간 불필요해 보여서 코멘트 남깁니다.

2020-07-02 01:00 UTC, pgshoot13 commented on class12/pgshoot13/HyApplication/app/src/main/java/com/hyper/hyapplication/MainActivity.kt
> +
client_ID, client_SECRET, base_URL
이렇게 반영하면 될까요?

2020-07-02 01:01 UTC, pgshoot13 commented on class12/pgshoot13/HyApplication/app/src/main/java/com/hyper/hyapplication/MainActivity.kt
> +                    adapter?.notifyDataSetChanged()
반영하였습니다. 감사합니다.

2020-07-02 01:39 UTC, pgshoot13 commented on class12/pgshoot13/HyApplication/app/src/main/java/com/hyper/hyapplication/MainActivity.kt
> +            setHasFixedSize(true)
cb1c936fb5d0886aaf7f92f88393475c4d071a9b
감사합니다.
제거하여 반영하였습니다.

2020-07-03 11:34 UTC, sjjeong commented
@pgshoot13 
Mentor Needed는 짝꿍이 리뷰하고 approve한 다음에 추가하는 겁니다.

2020-07-03 11:37 UTC, pgshoot13 commented
네 알겠습니다

2020-07-03 11:56 UTC, DWL5 reviewed
엇 let을 사용하면
response.body()!!은 필요 없습니다.
null check된 값이 let안에서 아마 it으로 들어올 것같아요!

let을 사용하시려면
MovieAdapter에 전달한 item을 it으로 바꾸고
!! 지우면 더 좋을 것 같아요!

2020-07-03 11:59 UTC, DWL5 reviewed
코멘트 하나 추가했습니다.

2020-07-03 11:59 UTC, DWL5 commented on class12/pgshoot13/HyApplication/app/src/main/java/com/hyper/hyapplication/MainActivity.kt
> +                        adapter?.notifyDataSetChanged()
엇 let을 사용하면
response.body()!!은 필요 없습니다.
null check된 값이 let안에서 아마 it으로 들어올 것같아요!

let을 사용하시려면
MovieAdapter에 전달한 item을 it으로 바꾸고
!! 지우면 더 좋을 것 같아요!

2020-07-03 12:05 UTC, DWL5 approved these changes

2020-07-03 15:23 UTC, sjjeong requested changes

2020-07-03 15:23 UTC, sjjeong commented on class12/pgshoot13/HyApplication/app/src/main/java/com/hyper/hyapplication/MainActivity.kt
> +    private lateinit var viewAdapter: RecyclerView.Adapter<*>
실제 사용하는 클래스의 타입을 써주도록 해주세요

2020-07-03 15:23 UTC, sjjeong commented on class12/pgshoot13/HyApplication/app/src/main/java/com/hyper/hyapplication/MainActivity.kt
> +        viewManager = LinearLayoutManager(this)
LayoutManager는 xml에서 추가할 수 있습니다.

2020-07-03 15:23 UTC, sjjeong commented on class12/pgshoot13/HyApplication/app/src/main/java/com/hyper/hyapplication/MainActivity.kt
> +            if (searchTitle == "") {
== "" 보단 isEmpty라는 함수를 써주시고
지금 if에 대한 처리가 없는데 코드를 추가하시거나 조건을 반대로 변경해주세요

2020-07-03 15:23 UTC, sjjeong commented on class12/pgshoot13/HyApplication/app/src/main/java/com/hyper/hyapplication/MainActivity.kt
> +            query = searchTitle
searchTitle를 class의 property로 선언하지 마시고 함수의 파라미터로 전달해주도록 해주세요

2020-07-03 15:23 UTC, sjjeong commented on class12/pgshoot13/HyApplication/app/src/main/java/com/hyper/hyapplication/MainActivity.kt
> +                item = response.body()!!.items
response.body()가 null인 경우에 앱이죽습니다.
!!는 지양해주세요

2020-07-03 15:23 UTC, sjjeong commented on class12/pgshoot13/HyApplication/app/src/main/java/com/hyper/hyapplication/MainActivity.kt
> +                        adapter = MovieAdapter(item)
Adapter는 매번 새로 만들 필요가 없습니다.
Adapter를 변경하지 않고 기존 Adapter에 데이터를 넣어주도록 해주세요

2020-07-03 15:23 UTC, sjjeong commented on class12/pgshoot13/HyApplication/app/src/main/java/com/hyper/hyapplication/MovieAdapter.kt
> +class MovieAdapter(private val movieLists: List<ResultGetSearchMovie.Item>) :
List는 외부에서 받지않고 내부에서 가지고 있고 함수를 통해 데이터를 갱신하도록 해주세요

2020-07-03 15:23 UTC, sjjeong commented on class12/pgshoot13/HyApplication/app/src/main/res/layout/activity_main.xml
> +        android:layout_height="match_parent"
weight가 들어가면 0dp로 변경해주셔야 합니다.

2020-07-03 15:23 UTC, sjjeong commented on class12/pgshoot13/HyApplication/app/src/main/res/layout/item_movie.xml
> +        android:layout_height="100dp"
높이를 고정으로 두는 것은 좋지 않습니다. wrap_content로 하고 minHeight를 주도록 해주세요

2020-07-04 04:46 UTC, pgshoot13 commented on class12/pgshoot13/HyApplication/app/src/main/java/com/hyper/hyapplication/MainActivity.kt
> +            if (searchTitle == "") {
eb2ee99f2b592549ef69f404cf175670d46e5300
null 체크 변경하였습니다.

2020-07-04 04:46 UTC, pgshoot13 commented on class12/pgshoot13/HyApplication/app/src/main/java/com/hyper/hyapplication/MainActivity.kt
> +        viewManager = LinearLayoutManager(this)
cee9a908d6b37837eb0ed9e98c0dd9fbdfeeefa7
LayoutManager를 xml에 추가하였습니다.

2020-07-04 04:49 UTC, pgshoot13 commented on class12/pgshoot13/HyApplication/app/src/main/java/com/hyper/hyapplication/MainActivity.kt
> +    private lateinit var viewAdapter: RecyclerView.Adapter<*>
cb1c936fb5d0886aaf7f92f88393475c4d071a9b
viewAdapter: MovieAdapter로 변경하였습니다.

2020-07-05 14:15 UTC, pgshoot13 commented on class12/pgshoot13/HyApplication/app/src/main/java/com/hyper/hyapplication/MainActivity.kt
> +            query = searchTitle
61c278333c5365d768877619de3af88b66ef305c
searchTitle 반영하였습니다.

2020-07-06 06:18 UTC, pgshoot13 commented on class12/pgshoot13/HyApplication/app/src/main/res/layout/activity_main.xml
> +        android:layout_height="match_parent"
1267b6dc1d551941ec380d4a976a725a60739a01
반영하였습니다.

2020-07-06 06:18 UTC, pgshoot13 commented on class12/pgshoot13/HyApplication/app/src/main/res/layout/item_movie.xml
> +        android:layout_height="100dp"
61bfb31fb806bcc731615898aad3b5c67a06dd3c
반영하였습니다.

2020-07-06 06:35 UTC, pgshoot13 reviewed
HW-2 Init -> Modify DataList

2020-07-06 13:32 UTC, pgshoot13 commented on class12/pgshoot13/HyApplication/app/src/main/java/com/hyper/hyapplication/MainActivity.kt
> +                item = response.body()!!.items
5d8c423d6b2806b3026cc3a722de02c85c66f9fb
전체 코드를 수정하였는데..
어느부분에서 화면 출력이 안되는지 못잡고 있습니다..

2020-07-06 13:32 UTC, pgshoot13 commented on class12/pgshoot13/HyApplication/app/src/main/java/com/hyper/hyapplication/MainActivity.kt
> +                        adapter = MovieAdapter(item)
5d8c423d6b2806b3026cc3a722de02c85c66f9fb
전체 코드를 수정하였는데..
어느부분에서 화면 출력이 안되는지 못잡고 있습니다..

2020-07-06 13:32 UTC, pgshoot13 commented on class12/pgshoot13/HyApplication/app/src/main/java/com/hyper/hyapplication/MovieAdapter.kt
> +class MovieAdapter(private val movieLists: List<ResultGetSearchMovie.Item>) :
5d8c423d6b2806b3026cc3a722de02c85c66f9fb
전체 코드를 수정하였는데..
어느부분에서 화면 출력이 안되는지 못잡고 있습니다..

2020-07-07 10:23 UTC, pgshoot13 commented
> 엇 let을 사용하면
> response.body()!!은 필요 없습니다.
> null check된 값이 let안에서 아마 it으로 들어올 것같아요!
> 
> let을 사용하시려면
> MovieAdapter에 전달한 item을 it으로 바꾸고
> !! 지우면 더 좋을 것 같아요!

d5b061f1d8c30d16782619d44951c8d995919067
반영하였습니다.

2020-07-08 04:35 UTC, sjjeong requested changes
ModelApplication이라고 만든 폴더는 제거해주세요

2020-07-08 07:37 UTC, pgshoot13 commented
> ModelApplication이라고 만든 폴더는 제거해주세요

b9bebe69a348bfc8b80ac90df4d247b93c31cafb
반영하였습니다.

2020-07-08 14:14 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-07-08 23:49 UTC, merged