HW-2 Naver 영화 API Model 만들기
sjjeong/GoogryAndroidArchitecutreStudy pull request #735
Opened 2020-07-05 06:33 UTC by manjee-study

2020-07-05 12:35 UTC, songmilee requested changes

2020-07-05 12:35 UTC, songmilee commented on class12/manjee-study/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/data/repository/MovieRespositoryImpl.kt
> +                    success(it.items)
이거 한 줄로 합쳐도 되지 않을까요?
response.boday()?.let {

2020-07-05 13:12 UTC, manjee-study commented on class12/manjee-study/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/data/repository/MovieRespositoryImpl.kt
> +                    success(it.items)
55a4055e7de98af138c703e9975bce26303d5f72 그게 좋겠네요 수정했습니다!

2020-07-07 07:31 UTC, songmilee approved these changes
approve!

2020-07-08 14:17 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-07-09 16:51 UTC, merged