HW-2 model 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #737
Opened 2020-07-05 12:31 UTC by songmilee

2020-07-05 13:07 UTC, manjee-study commented on class12/songmilee/class12Android/app/src/main/java/mi/song/class12android/ui/MainActivity.kt
>      val queryMovie: View.OnClickListener = View.OnClickListener {
initUI() 만드신 김에 클릭리스너도 안쪽으로 정리하는게 좋을거 같아요!

2020-07-07 07:26 UTC, songmilee commented on class12/songmilee/class12Android/app/src/main/java/mi/song/class12android/ui/MainActivity.kt
>      val queryMovie: View.OnClickListener = View.OnClickListener {
수정 하였습니다. (dd7df8fa)

2020-07-07 11:49 UTC, manjee-study approved these changes

2020-07-08 14:19 UTC, sjjeong requested changes
@songmilee 
base branch를 master가 아니라 본인 브랜치로 변경해주세요 
pr을 close하지 마시고 해당 pr에서 변경해주시면 됩니다.

2020-07-09 02:42 UTC, songmilee commented
@sjjeong 제가 해당 branch를 만들 때 제 origin class12/songmilee에서 만들었는데 제 브랜치로 변경하라는 것이 잘 이해가 안가서요. 새로 브랜치를 따 그 곳으로 rebase를 하라는 의미인가요??

2020-07-09 02:44 UTC, sjjeong commented
@songmilee 
다른분것과 비교해보면 into가 다른것을 확인할 수 있습니다.
![image](https://user-images.githubusercontent.com/4777586/86991248-8e702680-c1d9-11ea-946f-e4e2601ff7d2.png)

2020-07-09 02:45 UTC, sjjeong commented
@songmilee 
우측 상단에 edit 버튼 누르면 into로 하는 base branch를 변경할 수 있습니다.

2020-07-09 03:25 UTC, songmilee commented
@sjjeong 아..! 수정하였습니다!

2020-07-09 11:37 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-07-10 00:41 UTC, merged