HW - 2 Repository 구현
sjjeong/GoogryAndroidArchitecutreStudy pull request #741
Opened 2020-07-05 13:39 UTC by ysj1224

커밋 신경을 잘 못쓰고 했네요 좀더 신경써서 커밋해보겠습니다 !

2020-07-08 12:21 UTC, dlqkfzlr commented on class12/ysj1224/Study/app/src/main/java/com/example/study/data/repository/MovieListRepositoryImpl.kt
> +        NaverRetrofit.SERVICE.getSearch(
'추후에 doSearch메소드에서 Local의 DataSource를 사용할 상황' or 'getSearch메소드를 MovieListRepositoryImpl클래스의 다른 메소드에서 사용할 상황'을 감안해서 따로 빼서 메소드를 만드는게 좋을 것 같습니다.

2020-07-09 05:31 UTC, ysj1224 commented on class12/ysj1224/Study/app/src/main/java/com/example/study/data/repository/MovieListRepositoryImpl.kt
> +        NaverRetrofit.SERVICE.getSearch(
무슨말인지 잘 이해가 안되네요..ㅠ  getSearch 함수는 NaverApi에 있는 함수를 불러오고있는건데 어떻게 하면 될까요?

2020-07-09 05:46 UTC, dlqkfzlr commented on class12/ysj1224/Study/app/src/main/java/com/example/study/data/repository/MovieListRepositoryImpl.kt
> +        NaverRetrofit.SERVICE.getSearch(
MovieListRepositoryImpl클래스에서는 remoteDataSource.getMovies(q, success = success, error = error) 이런식으로 간단하게 처리하고, RemoteDataSource클래스를 따로 만드셔서 거기서 NaverRetrofit.SERVICE.getSearch()~~ 이런식으로 풀어나가는 걸 말씀드린겁니다.

2020-07-09 06:31 UTC, ysj1224 commented on class12/ysj1224/Study/app/src/main/java/com/example/study/data/repository/MovieListRepositoryImpl.kt
> +        NaverRetrofit.SERVICE.getSearch(
e0dea57d
a4c3abf0
구현해봤는데 이런식을 말씀하시는건지 잘 모르겠네요

2020-07-09 07:46 UTC, dlqkfzlr commented on class12/ysj1224/Study/app/src/main/java/com/example/study/data/repository/MovieListRepositoryImpl.kt
> +        NaverRetrofit.SERVICE.getSearch(
저희 수업때 배운 LocalDataSource랑 RemoteDataSource 기억하시나요? 
그 방식대로 RemoteDataSource에서 Retrofit으로 데이터 가져오는 getSearch메소드를 구현하시고, Repository에서는 remoteDataSource.getSearch()~ 로 간단하게 처리하는 걸 말씀드린거였습니다.

2020-07-09 08:20 UTC, ysj1224 commented on class12/ysj1224/Study/app/src/main/java/com/example/study/data/repository/MovieListRepositoryImpl.kt
> +        NaverRetrofit.SERVICE.getSearch(
9d6f0177
수정했습니다 레파지토리에서 리모트인터페이스 구현체 불러오고 있습니다.

2020-07-09 08:24 UTC, dlqkfzlr approved these changes

2020-07-09 11:47 UTC, sjjeong requested changes

2020-07-09 11:47 UTC, sjjeong commented on class12/ysj1224/Study/app/src/main/java/com/example/study/data/remote/RemoteInterface.kt
> +interface RemoteInterface {
RemoteDataSource로 변경해주세요

2020-07-09 11:47 UTC, sjjeong commented on class12/ysj1224/Study/app/src/main/java/com/example/study/view/MainActivity.kt
> +    private val moviList = MovieListRepositoryImpl()
이름이 moviList보단 movieListRepository가 좋을 것 같네요

2020-07-09 23:15 UTC, ysj1224 commented on class12/ysj1224/Study/app/src/main/java/com/example/study/data/remote/RemoteInterface.kt
> +interface RemoteInterface {
ced3c007

2020-07-09 23:15 UTC, ysj1224 commented on class12/ysj1224/Study/app/src/main/java/com/example/study/view/MainActivity.kt
> +    private val moviList = MovieListRepositoryImpl()
9abba04c

2020-07-10 23:51 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-07-12 11:48 UTC, merged