HW-2 model 구현
sjjeong/GoogryAndroidArchitecutreStudy pull request #743
Opened 2020-07-06 06:14 UTC by pgshoot13

HW-2 model 구현

2020-07-06 06:15 UTC, pgshoot13 commented
브랜치를 잘못따서 HW-1이 적용된 것 같습니다.
일단 Commit에서 HW-2으로 봐주셔야 될 것 같습니다.

2020-07-07 15:31 UTC, DWL5 commented on class12/pgshoot13/HyApplication/app/src/main/java/com/hyper/hyapplication/repository/NaverRepositoryImpl.kt
> +
movieDataSourceImpl를 생성자로 전달해 보면 어떨까요?
interface로 지정한 NaverRemoteDataSource를 파라미터로 주면 
다양한 구현체를 전달 할 수 있어서 나중에 테스트 하기에 용이하다고 하네요!

2020-07-08 00:36 UTC, pgshoot13 commented on class12/pgshoot13/HyApplication/app/src/main/java/com/hyper/hyapplication/repository/NaverRepositoryImpl.kt
> +
236e1913e4bd22c8dc11f8430cad7da1ab1f80a0
감사합니다! 반영하였습니다.

2020-07-08 03:51 UTC, DWL5 commented on class12/pgshoot13/HyApplication/app/src/main/java/com/hyper/hyapplication/repository/NaverRepositoryImpl.kt
> +    NaverRepository {
NaverRemoteDataSourceImpl 대신 인터페이스인 NaverDataSource를 전달하는게 더 좋아보입니답

ex) NaverDatasourceImpl:NaverDataSource

2020-07-08 04:37 UTC, sjjeong commented
HW-2 작업을 위한 branch를 만들어서 작업해주시면 됩니다.

2020-07-08 07:38 UTC, pgshoot13 commented
> 아직 HW-1이 머지되지 않아서 이전 커밋도 나오는거에요
> HW-1이 마무리되면 없어질꺼에요

네 알겠습니다!

2020-07-08 07:49 UTC, pgshoot13 commented on class12/pgshoot13/HyApplication/app/src/main/java/com/hyper/hyapplication/repository/NaverRepositoryImpl.kt
> +    NaverRepository {
cb57fb4e38af258de10ff51a9cb09abf57781bf2
아....오타를 냈네요... 반영하였습니다.

2020-07-08 09:56 UTC, DWL5 submitted a review, later dismissed
수고하셨습니다!!

2020-07-09 11:55 UTC, sjjeong requested changes

2020-07-09 11:55 UTC, sjjeong commented on class12/pgshoot13/HyApplication/app/src/main/java/com/hyper/hyapplication/NaverAPI.kt
> +object NaverRetrofit {
별도의 파일로 빼주세요

2020-07-09 11:55 UTC, sjjeong commented on class12/pgshoot13/HyApplication/app/src/main/java/com/hyper/hyapplication/source/local/NaverLocalDataSourceImpl.kt
> +class NaverLocalDataSourceImpl {
NaverLocalDataSource를 impl 해주세요

2020-07-09 11:55 UTC, sjjeong commented on class12/pgshoot13/HyApplication/app/src/main/java/com/hyper/hyapplication/source/local/NaverLocalDatasource.kt
> +interface NaverLocalDatasource {
s를 대문자로 변경해주세요

2020-07-09 11:55 UTC, sjjeong commented on class12/pgshoot13/HyApplication/app/src/main/java/com/hyper/hyapplication/ui/MainActivity.kt
> +const val BASE_URL = "https://openapi.naver.com"
별도의 파일로 빼서 분리해주세요

2020-07-09 11:55 UTC, sjjeong commented on class12/pgshoot13/HyApplication/app/src/main/java/com/hyper/hyapplication/ui/MainActivity.kt
> +            if (searchText.text.toString().isNotEmpty()) {
searchText.text.toString() 가 중복되고 있습니다.

2020-07-10 01:18 UTC, pgshoot13 commented on class12/pgshoot13/HyApplication/app/src/main/java/com/hyper/hyapplication/NaverAPI.kt
> +object NaverRetrofit {
별도의 파일로 빼달라는것은 다른 클래스로 분리 하라는 말씀이신가요?

2020-07-10 01:20 UTC, pgshoot13 commented on class12/pgshoot13/HyApplication/app/src/main/java/com/hyper/hyapplication/source/local/NaverLocalDatasource.kt
> +interface NaverLocalDatasource {
1866608b5d4c30deaa40b25ec0ff0d71c252dc6a
반영하였습니다.

2020-07-10 01:20 UTC, pgshoot13 commented on class12/pgshoot13/HyApplication/app/src/main/java/com/hyper/hyapplication/ui/MainActivity.kt
> +            if (searchText.text.toString().isNotEmpty()) {
3b021e2616787ec0dd267f2ef04923b573636232
반영하였습니다.

2020-07-10 01:21 UTC, pgshoot13 commented on class12/pgshoot13/HyApplication/app/src/main/java/com/hyper/hyapplication/source/local/NaverLocalDataSourceImpl.kt
> +class NaverLocalDataSourceImpl {
a1dd516eba12c0be5c06ec2d59d61f0267c7691a
반영하였습니다.

2020-07-10 01:22 UTC, sjjeong commented on class12/pgshoot13/HyApplication/app/src/main/java/com/hyper/hyapplication/NaverAPI.kt
> +object NaverRetrofit {
@pgshoot13 
이미 클래스는 분리되어 있는 상태입니다.
root level에 있는 클래스는 파일당 한개씩 있는게 좋습니다.

2020-07-10 01:22 UTC, sjjeong commented on class12/pgshoot13/HyApplication/app/src/main/java/com/hyper/hyapplication/ui/MainActivity.kt
> +const val BASE_URL = "https://openapi.naver.com"
@pgshoot13 
이 부분도 반영해주세요

2020-07-10 02:06 UTC, pgshoot13 commented on class12/pgshoot13/HyApplication/app/src/main/java/com/hyper/hyapplication/NaverAPI.kt
> +object NaverRetrofit {
66df4b0d2629df706800fb5901884f11d885e420
반영하였습니다.

2020-07-10 02:06 UTC, pgshoot13 commented on class12/pgshoot13/HyApplication/app/src/main/java/com/hyper/hyapplication/ui/MainActivity.kt
> +const val BASE_URL = "https://openapi.naver.com"
e62573a4e64a422235b850ddb09ec88b656aaa26
반영하였습니다.

2020-07-11 00:11 UTC, sjjeong commented on class12/pgshoot13/HyApplication/app/src/main/java/com/hyper/hyapplication/ui/MainActivity.kt
> +            if (searchText.text.toString().isNotEmpty()) {
@pgshoot13 
최종코드에는 반영이 안되어 있네요

2020-07-11 03:09 UTC, pgshoot13 commented on class12/pgshoot13/HyApplication/app/src/main/java/com/hyper/hyapplication/ui/MainActivity.kt
> +            if (searchText.text.toString().isNotEmpty()) {
48d99b2f35d1962aaa652dc18dac39d74020360f
수정하면서 팅긴것같습니다.

2020-07-11 08:15 UTC, sjjeong requested changes

2020-07-11 08:15 UTC, sjjeong commented on class12/pgshoot13/HyApplication/app/src/main/java/com/hyper/hyapplication/ui/MainActivity.kt
> +    private val searchList = searchText.text.toString()
말씀드린 것 처럼 onClickListener 안에서 처리하도록 이동해주세요

2020-07-12 10:51 UTC, pgshoot13 commented on class12/pgshoot13/HyApplication/app/src/main/java/com/hyper/hyapplication/ui/MainActivity.kt
> +    private val searchList = searchText.text.toString()
6da22ed6d41bfcde5c3c4689b2e334909423c58d
반영했습니다!

2020-07-12 12:15 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-07-12 12:15 UTC, sjjeong commented
@DWL5 approve 해주세요

2020-07-12 13:16 UTC, DWL5 approved these changes
고생하셨습니다!

2020-07-12 14:05 UTC, merged