HW-3 MVP 구조 만들기
sjjeong/GoogryAndroidArchitecutreStudy pull request #744
Opened 2020-07-11 05:52 UTC by manjee-study

2020-07-12 00:24 UTC, songmilee requested changes

2020-07-12 00:24 UTC, songmilee commented on class12/manjee-study/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/presenter/SearchMoviePresenter.kt
> +    private val searchMovieView = view
생성자로 view 넘겨주셔서 굳이 안에 새로운 변수 안만들고 생성자로 넘어온 view를 메소드에 사용하시면 될 것 같습니다

2020-07-12 09:48 UTC, manjee-study commented on class12/manjee-study/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/presenter/SearchMoviePresenter.kt
> +    private val searchMovieView = view
389693e8c9332a1feb08fdd2e37fd69b8368f4fd 넘어온 view로 사용하게끔 수정했습니다

2020-07-13 05:19 UTC, songmilee approved these changes
approve

2020-07-13 14:37 UTC, sjjeong requested changes

2020-07-13 14:37 UTC, sjjeong commented on class12/manjee-study/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/presenter/SearchMovieConstract.kt
> +        fun remoteSearchMovie(movieTitle: String)
함수명은 동사로 시작하는게 좋습니다
적절한 함수명으로 변경해주세요

2020-07-15 10:56 UTC, manjee-study commented on class12/manjee-study/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/presenter/SearchMovieConstract.kt
> +        fun remoteSearchMovie(movieTitle: String)
1c6e1eb001aec3554507e12e46afd81acbc32ce3 searchMovieOnRemote로 변경했습니다

2020-07-15 16:30 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-07-17 06:16 UTC, merged