HW-3 : MVP 패턴
sjjeong/GoogryAndroidArchitecutreStudy pull request #745
Opened 2020-07-11 06:32 UTC by dlqkfzlr

2020-07-13 05:12 UTC, ysj1224 commented on class12/dlqkfzlr/study/app/src/main/java/m/woong/architecturestudy/ui/main/MainActivity.kt
> +        val naverRepository = NaverRepositoryImpl(remoteDataSource)
object를 만들어서 관리 해보는건 어떨까요?

2020-07-15 16:16 UTC, dlqkfzlr commented on class12/dlqkfzlr/study/app/src/main/java/m/woong/architecturestudy/ui/main/MainActivity.kt
> +        val naverRepository = NaverRepositoryImpl(remoteDataSource)
dependencies container class를 만들었습니다.
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/commit/c6a8fe8cbd91bdcc845510ff0dacd593d1995c4d

2020-07-15 23:24 UTC, ysj1224 approved these changes

2020-07-16 12:50 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-07-16 12:56 UTC, sjjeong requested changes

2020-07-16 12:56 UTC, sjjeong commented on class12/dlqkfzlr/study/app/src/main/java/m/woong/architecturestudy/MoviePresenter.kt
> +interface MoviePresenter : MovieContract.Presenter {
승진님꺼 보고 이렇게 하신것 같은데 별도의 interface를 만들지 않으셔도 됩니다.

2020-07-16 12:58 UTC, dlqkfzlr commented on class12/dlqkfzlr/study/app/src/main/java/m/woong/architecturestudy/MoviePresenter.kt
> +interface MoviePresenter : MovieContract.Presenter {
아 승진님꺼랑 제꺼랑 유사해서 바꿔봤는데, 제껀 별도 interface 안만들어도 되는 이유는 뭔가요?

2020-07-16 13:00 UTC, dlqkfzlr commented on class12/dlqkfzlr/study/app/src/main/java/m/woong/architecturestudy/MoviePresenter.kt
> +interface MoviePresenter : MovieContract.Presenter {
아 이해했습니다.

2020-07-16 13:00 UTC, sjjeong commented on class12/dlqkfzlr/study/app/src/main/java/m/woong/architecturestudy/MoviePresenter.kt
> +interface MoviePresenter : MovieContract.Presenter {
승진님도 같은 리뷰 남겼습니다.
MoviewContract.Presenter가 이미 MoviePresenter가 해야하는 역할들을 interface화 했기 때문에 불필요한 interface의 상속으로 보입니다.

2020-07-16 13:05 UTC, dlqkfzlr commented on class12/dlqkfzlr/study/app/src/main/java/m/woong/architecturestudy/MoviePresenter.kt
> +interface MoviePresenter : MovieContract.Presenter {
다시 수정했습니다 :)
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/commit/8d848225b8ae6300ccf7f92a2ebb41f319ba3533

2020-07-18 11:56 UTC, sjjeong approved these changes

2020-07-18 11:59 UTC, merged