HW-3 : MVP 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #746
Opened 2020-07-12 00:03 UTC by songmilee

MVP 적용

2020-07-12 09:44 UTC, manjee-study commented on class12/songmilee/class12Android/app/src/main/java/mi/song/class12android/ui/MoviePresenter.kt
> +class MoviePresenter(val context: Context, val view: MovieInterface.View) :
외부에서 호출할 일이 없다면 private으로 만드는게 더 좋을거 같아요!

2020-07-12 09:46 UTC, manjee-study commented on class12/songmilee/class12Android/app/src/main/java/mi/song/class12android/ui/MoviePresenter.kt
>      private val searchMovieRepository: SearchMovieRepository by lazy {
lazy가 아닌 Impl로 바로 선언해서 사용해도 될거같아요

2020-07-13 05:28 UTC, songmilee commented on class12/songmilee/class12Android/app/src/main/java/mi/song/class12android/ui/MoviePresenter.kt
> +class MoviePresenter(val context: Context, val view: MovieInterface.View) :
private 선언으로 변경 (36c3f06b)

2020-07-13 05:28 UTC, songmilee commented on class12/songmilee/class12Android/app/src/main/java/mi/song/class12android/ui/MoviePresenter.kt
>      private val searchMovieRepository: SearchMovieRepository by lazy {
lazy에서 바로 선언으로 변경 (1be08d40)

2020-07-13 11:09 UTC, manjee-study approved these changes

2020-07-13 15:03 UTC, sjjeong requested changes

2020-07-13 15:03 UTC, sjjeong commented on class12/songmilee/class12Android/app/src/main/java/mi/song/class12android/presenter/MoviePresenter.kt
> +                view.updateMovieList(it)
두개 함수를 하나로 합쳐보면 좋을 것 같네요

2020-07-13 23:32 UTC, songmilee commented on class12/songmilee/class12Android/app/src/main/java/mi/song/class12android/presenter/MoviePresenter.kt
> +                view.updateMovieList(it)
updateMovieList 메소드가 리스트 clear 및 데이터 add 역할을 하도록 변경하였습니다(f4b7ac95)

2020-07-15 09:51 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-07-15 10:04 UTC, merged