HW-3 MVP 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #747
Opened 2020-07-12 08:18 UTC by DWL5

2020-07-13 05:39 UTC, pgshoot13 commented on class12/DWL5/study/app/src/main/java/com/world/tree/architecturestudy/presenter/MoviePresenterImpl.kt
> +        }
Blank일때도 함수로 만들면 어떨까 싶습니다.

2020-07-13 05:39 UTC, pgshoot13 commented on class12/DWL5/study/app/src/main/java/com/world/tree/architecturestudy/presenter/MoviePresenter.kt
> +}
Contract - MoviePresenter
Presenter - MoviePresenterImpl로 만드신거죠?

2020-07-14 14:05 UTC, DWL5 commented on class12/DWL5/study/app/src/main/java/com/world/tree/architecturestudy/presenter/MoviePresenter.kt
> +}
앗 넵 Presenrer를 만들고 그안에 view interface를 넣었습니다.
확인해보니 Contract안에 presenter, view 인터페이스를 만드는 방법도 있었네요

2020-07-14 14:10 UTC, DWL5 commented on class12/DWL5/study/app/src/main/java/com/world/tree/architecturestudy/presenter/MoviePresenterImpl.kt
> +        }
제 생각에는 blank toast가 비었다는 내용을 토스트로 보여주는 것이라면
파라미터로 메시지를 보내고, 해당 내용을 토스트 메시지로 보여주는 함수가 
더 유용 할 것 같아서 위와 같이 구현했습니다.

혹시 위와 같은 방법이 더 낫지 않을까요??
blank toast를 따로 함수로 만들면, 다른 메시지와 관련된 함수도 만들어줘야 할 것 같아서요!

2020-07-16 04:29 UTC, pgshoot13 approved these changes

2020-07-16 04:29 UTC, pgshoot13 commented on class12/DWL5/study/app/src/main/java/com/world/tree/architecturestudy/presenter/MoviePresenterImpl.kt
> +        }
아 맞네요! 제가 이해를 잘못 했습니다ㅎㅎ
다원씨 방법대로하면 다용으로 쓸수 있겠네요.
팁 감사합니다.

2020-07-16 04:29 UTC, pgshoot13 commented on class12/DWL5/study/app/src/main/java/com/world/tree/architecturestudy/presenter/MoviePresenter.kt
> +}
맞습니다!
수고하셨습니다!

2020-07-16 12:54 UTC, sjjeong requested changes

2020-07-16 12:54 UTC, sjjeong commented on class12/DWL5/study/app/src/main/java/com/world/tree/architecturestudy/presenter/MoviePresenter.kt
> +    interface View {
Contract안에 presenter, view 인터페이스를 만드는 방법으로 변경해주세요

2020-07-16 12:54 UTC, sjjeong commented on class12/DWL5/study/app/src/main/java/com/world/tree/architecturestudy/view/MainActivity.kt
> +    override fun setMovieData(list: List<Movie.Item>) {
이전에는 clear하고 add했는데 지금은 이 함수를 호출하는 곳이 없어서 add만 되는 것 같네요
한번 확인해주세요

2020-07-17 04:23 UTC, DWL5 commented on class12/DWL5/study/app/src/main/java/com/world/tree/architecturestudy/presenter/MoviePresenter.kt
> +    interface View {
c104553e4854ed72616813a20f648f80f0bb6212

수정했습니다.

2020-07-17 04:24 UTC, DWL5 commented on class12/DWL5/study/app/src/main/java/com/world/tree/architecturestudy/view/MainActivity.kt
> +    override fun setMovieData(list: List<Movie.Item>) {
9310377cfed5cf49cc1359b801259f5c3275d03c

수정했습니다.

2020-07-18 11:56 UTC, sjjeong approved these changes

2020-07-19 06:39 UTC, merged