HW-3 MVP 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #748
Opened 2020-07-12 12:35 UTC by ysj1224

2020-07-14 15:31 UTC, dlqkfzlr approved these changes
저와 코드가 유사해서 제 눈에는 딱히 수정할게 없는 것 같습니다.ㅋㅋ여유시간이 있으시다면 DI 관련해서 적용해보는 것도 좋을 것 같아요

2020-07-15 09:53 UTC, sjjeong requested changes
코드 정렬 해주세요

2020-07-15 09:53 UTC, sjjeong commented on class12/ysj1224/Study/app/src/main/java/com/example/study/MoviePresenter.kt
> +    private val repositoryImpl: MovieListRepositoryImpl
type은 class말고 interface로 해주세요

2020-07-15 23:39 UTC, ysj1224 commented on class12/ysj1224/Study/app/src/main/java/com/example/study/MoviePresenter.kt
> +    private val repositoryImpl: MovieListRepositoryImpl
66540641 , 075578df

2020-07-16 12:55 UTC, sjjeong commented on class12/ysj1224/Study/app/src/main/java/com/example/study/MoviePresenter.kt
> +    private val repositoryImpl: MovieListRepositoryImpl
잘못이해 하신 것 같네요
리뷰를 남긴 코드는 7번째 줄로 MovieListRepositoryImpl이 아니라 MovieListRepository로 변경해달라는거 였습니다.

2020-07-16 15:05 UTC, ysj1224 commented on class12/ysj1224/Study/app/src/main/java/com/example/study/MoviePresenter.kt
> +    private val repositoryImpl: MovieListRepositoryImpl
앗.. 수정했습니다 acf7679f

2020-07-18 11:57 UTC, sjjeong approved these changes

2020-07-20 05:20 UTC, merged