HW-3 : MVP 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #749
Opened 2020-07-13 02:36 UTC by pgshoot13

1. Add MainContract
2. Add MainPresenter
3. MVP Applied

2020-07-14 14:02 UTC, DWL5 reviewed
MovieAdapter의 초기화는 어디서 하나요??

2020-07-14 14:03 UTC, DWL5 reviewed
수고하셨습니다!

2020-07-14 14:03 UTC, DWL5 commented on class12/pgshoot13/HyApplication/app/src/main/java/com/hyper/hyapplication/ui/MainActivity.kt
> +    private val presenter = MainPresenter(this)
MovieAadapter의 초기화는 어디서 하나요?

2020-07-16 04:41 UTC, pgshoot13 commented on class12/pgshoot13/HyApplication/app/src/main/java/com/hyper/hyapplication/ui/MainActivity.kt
> +    private val presenter = MainPresenter(this)
아래에서 합니다.

        viewAdapter = MovieAdapter()
        recyclerView.apply {
            setHasFixedSize(true)
            adapter = viewAdapter
        }

2020-07-16 05:44 UTC, DWL5 commented on class12/pgshoot13/HyApplication/app/src/main/java/com/hyper/hyapplication/ui/MainActivity.kt
> +    private val presenter = MainPresenter(this)
앗 넵 알겠습니다.  코드변경 부분만 보아서 해당 부분을 못봤었네요!!

2020-07-16 05:45 UTC, DWL5 approved these changes
고생하셨습니다~~ Approve 합니다!!

2020-07-16 12:58 UTC, sjjeong requested changes

2020-07-16 12:58 UTC, sjjeong commented on class12/pgshoot13/HyApplication/app/src/main/java/com/hyper/hyapplication/ui/MainPresenter.kt
> +        }
조건을 반대로 변경해주세요
programming precondition에 대해 알아보시면 좋습니다.

2020-07-17 00:51 UTC, pgshoot13 commented on class12/pgshoot13/HyApplication/app/src/main/java/com/hyper/hyapplication/ui/MainPresenter.kt
> +        }
52288fff7e85d8d9b9402feec5ad7f078b39bd00
반영하였습니다!

2020-07-18 11:58 UTC, sjjeong approved these changes

2020-07-19 08:27 UTC, merged