HW4 - DataBinding
sjjeong/GoogryAndroidArchitecutreStudy pull request #751
Opened 2020-07-19 11:28 UTC by DWL5

HW4 - DataBinding

2020-07-21 01:06 UTC, pgshoot13 commented on class12/DWL5/study/app/src/main/java/com/world/tree/architecturestudy/view/MainActivity.kt
> +    }
새로운 액티비티를 호출하신 특별한 이유가 있나요?

2020-07-22 05:30 UTC, DWL5 commented on class12/DWL5/study/app/src/main/java/com/world/tree/architecturestudy/view/MainActivity.kt
> +    }
Movie 안의 link로 이동하는 기능을 추가 해보았는데,
다른 어플리케이션(웹브라우져)를 실행시켜야 해서 새로운 태스크로 실행되도록
해야하나 보더라구요 ㅠ 

아래 에러 때문에 플래그 추가 하였습니다.

   Process: com.world.tree.architecturestudy, PID: 8707
    android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?

2020-07-22 05:31 UTC, DWL5 commented on class12/DWL5/study/app/src/main/java/com/world/tree/architecturestudy/view/MainActivity.kt
> +    }
아! 그리고 호영님 소스 보고나서 MainActivity에도 데이터 바인딩 적용하였습니다.
저는 ViewHolder 쪽에만 적용했었네요

2020-07-22 07:22 UTC, pgshoot13 commented on class12/DWL5/study/app/src/main/java/com/world/tree/architecturestudy/view/MainActivity.kt
> +    }
> 아! 그리고 호영님 소스 보고나서 MainActivity에도 데이터 바인딩 적용하였습니다.
> 저는 ViewHolder 쪽에만 적용했었네요

왜 안넣으셨나 했는데..굳입니당!

2020-07-22 15:33 UTC, sjjeong requested changes

2020-07-22 15:33 UTC, sjjeong commented on class12/DWL5/study/app/src/main/res/layout/item_movie.xml
> +            app:loadImage="@{movie.image}"></ImageView>
ImageView나 TextView는 ViewGroup이 아니라서 />로 해도 됩니다.

2020-07-22 15:33 UTC, sjjeong commented on class12/DWL5/study/app/src/main/java/com/world/tree/architecturestudy/view/MovieAdapter.kt
> +    inner class MovieViewHolder(itemView: View) : RecyclerView.ViewHolder(itemView) {
interface나 class는 함수 아래에 있어야 합니다.

2020-07-22 15:33 UTC, sjjeong commented on class12/DWL5/study/app/src/main/java/com/world/tree/architecturestudy/view/MainActivity.kt
> +        baseContext.startActivity(
baseContext를 넣은 이유가 있나요?
baseContext가 없다면 NEW_TASK flag도 없어도 될 것 같습니다.

2020-07-22 15:33 UTC, sjjeong commented on class12/DWL5/study/app/src/main/java/com/world/tree/architecturestudy/view/MovieAdapter.kt
> +    fun setOnclickItemListener(onItemClickListener: OnItemClickListener) {
함수명 컨벤션을 인터페이스이름에 맞게 변경해주세요

2020-07-24 05:44 UTC, DWL5 commented on class12/DWL5/study/app/src/main/res/layout/item_movie.xml
> +            app:loadImage="@{movie.image}"></ImageView>
3decad0
반영했습니다

2020-07-24 05:44 UTC, DWL5 commented on class12/DWL5/study/app/src/main/java/com/world/tree/architecturestudy/view/MovieAdapter.kt
> +    inner class MovieViewHolder(itemView: View) : RecyclerView.ViewHolder(itemView) {
a9955ef
반영했습니다

2020-07-24 05:45 UTC, DWL5 commented on class12/DWL5/study/app/src/main/java/com/world/tree/architecturestudy/view/MovieAdapter.kt
> +    fun setOnclickItemListener(onItemClickListener: OnItemClickListener) {
609337e
반영했습니다

2020-07-24 06:00 UTC, DWL5 commented on class12/DWL5/study/app/src/main/java/com/world/tree/architecturestudy/view/MainActivity.kt
> +        baseContext.startActivity(
832789b
반영했습니다.
Context에 대한 이해 없이 구현을 했던 것 같네요.

Application Context, Base Context, Activity의 차이점에 대해 공부해 봐야 겠습니다 ㅠ
https://www.charlezz.com/?p=1080
https://black-jin0427.tistory.com/220

2020-07-25 03:43 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-07-27 07:53 UTC, pgshoot13 approved these changes

2020-07-27 09:25 UTC, merged