HW-4 databindng
sjjeong/GoogryAndroidArchitecutreStudy pull request #752
Opened 2020-07-20 07:35 UTC by ysj1224

databinding 적용해서 변경했습니다. 부족한 부분 리뷰 부탁드리겠습니다

2020-07-21 14:08 UTC, dlqkfzlr commented on class12/ysj1224/Study/app/src/main/res/layout/activity_main.xml
> +            name="VM"
이 VM변수는 사용되고 있지 않아서 혹시 쓰신 이유가 궁금합니다.

2020-07-21 14:08 UTC, dlqkfzlr commented on class12/ysj1224/Study/app/src/main/java/com/example/study/view/MainActivity.kt
> +        binding.rvMain.apply {
Databinding 라이브러리를 사용했으니
binding.rvMain => rv_main 으로 수정해도 작동하지 않을까 싶습니다.
이렇게 하신 이유가 있다면 궁금합니다.

2020-07-21 14:08 UTC, dlqkfzlr commented on class12/ysj1224/Study/app/src/main/java/com/example/study/view/MainActivity.kt
> +        binding.btnCheck.setOnClickListener {
위와 마찬가지로 그대로 두셔도 작동할텐데 수정하신 이유가 궁금합니다.

2020-07-22 01:24 UTC, ysj1224 commented on class12/ysj1224/Study/app/src/main/java/com/example/study/view/MainActivity.kt
> +        binding.rvMain.apply {
레이아웃에다가 바로하는것보다는 바인딩된 레이아웃을 사용해야될것같아서 저렇게했습니다.

2020-07-22 01:30 UTC, ysj1224 commented on class12/ysj1224/Study/app/src/main/res/layout/activity_main.xml
> +            name="VM"
버튼 온클릭에 사용하려고 했는데 잘 안되서 지운기록이 남아있네요 수정했습니다!
ca286597

2020-07-22 01:34 UTC, dlqkfzlr commented on class12/ysj1224/Study/app/src/main/res/layout/activity_main.xml
> +            name="VM"
네 알겠습니다. 근데 commit링크가 작동되지 않아서 그것만 수정해주세요~

2020-07-22 02:05 UTC, ysj1224 commented on class12/ysj1224/Study/app/src/main/res/layout/activity_main.xml
> +            name="VM"
ca28659

2020-07-22 02:16 UTC, dlqkfzlr approved these changes

2020-07-22 15:05 UTC, sjjeong requested changes

2020-07-22 15:05 UTC, sjjeong commented on class12/ysj1224/Study/app/src/main/res/layout/rv_item.xml
> +            name="VM"
VM보다 item이 더 적절한 이름인것 같습니다.

2020-07-22 15:05 UTC, sjjeong commented on class12/ysj1224/Study/app/src/main/res/layout/rv_item.xml
> +        <import type="android.text.Html"/>
사용하지 않는 import는 제거해주세요

2020-07-22 15:05 UTC, sjjeong commented on class12/ysj1224/Study/app/src/main/java/com/example/study/RecyclerAdapter.kt
> +            binding.vm = data
binding에 item을 넣어주고나서 
executePendingBindings()을 호출해주세요

2020-07-23 02:18 UTC, ysj1224 commented on class12/ysj1224/Study/app/src/main/res/layout/rv_item.xml
> +            name="VM"
c11a2d22

2020-07-23 02:19 UTC, ysj1224 commented on class12/ysj1224/Study/app/src/main/res/layout/rv_item.xml
> +        <import type="android.text.Html"/>
e6616b25

2020-07-23 02:19 UTC, ysj1224 commented on class12/ysj1224/Study/app/src/main/java/com/example/study/RecyclerAdapter.kt
> +            binding.vm = data
cde266ea

2020-07-23 03:59 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-07-23 07:54 UTC, merged