HW-4 : DataBinding
sjjeong/GoogryAndroidArchitecutreStudy pull request #754
Opened 2020-07-21 00:58 UTC by pgshoot13

1. Modify DataBinding ButtonEvent
2. Modify DataBinding MovieData
3. Add Binding Adapter

2020-07-22 05:26 UTC, DWL5 commented on class12/pgshoot13/HyApplication/app/src/main/res/layout/activity_main.xml
> +            type="com.hyper.hyapplication.ui.MainActivity" />
이미 구현 된 MainActivity를 전달 하기 보다
view와 presenter interface를 전달하면 어떨까요??

2020-07-22 07:23 UTC, pgshoot13 commented on class12/pgshoot13/HyApplication/app/src/main/res/layout/activity_main.xml
> +            type="com.hyper.hyapplication.ui.MainActivity" />
9c5540612141dcb38ff4699d8c4e9ffcfb372802
그렇게하면 결합도가 더 낮아져서 좋겠군요!
반영하였습니다.

2020-07-22 15:02 UTC, DWL5 commented on class12/pgshoot13/HyApplication/app/src/main/res/layout/activity_main.xml
> +            type="com.hyper.hyapplication.ui.MainActivity" />
수고하셨습니다~

2020-07-22 15:02 UTC, DWL5 approved these changes

2020-07-22 15:37 UTC, sjjeong requested changes

2020-07-22 15:37 UTC, sjjeong commented on class12/pgshoot13/HyApplication/app/src/main/res/layout/activity_main.xml
> +            type="com.hyper.hyapplication.ui.MainContract.View" />
사용되지 않는 것이라서 제거 해주세요

2020-07-22 15:37 UTC, sjjeong commented on class12/pgshoot13/HyApplication/app/src/main/java/com/hyper/hyapplication/ui/MainContract.kt
> +        fun searchMovie(movieName: String)
사용되지 않는 것이라서 제거 해주세요

2020-07-23 07:57 UTC, pgshoot13 commented on class12/pgshoot13/HyApplication/app/src/main/res/layout/activity_main.xml
> +            type="com.hyper.hyapplication.ui.MainContract.View" />
54c6e6ed50615bdd9c3291991e7b6f808f9924aa
반영하였습니다.

2020-07-23 07:57 UTC, pgshoot13 commented on class12/pgshoot13/HyApplication/app/src/main/java/com/hyper/hyapplication/ui/MainContract.kt
> +        fun searchMovie(movieName: String)
e88f82be7224cbbed17f0ab8e59ded198b543c36
반영하였습니다.

2020-07-23 11:50 UTC, sjjeong requested changes
에러 수정해주세요

2020-07-24 00:19 UTC, pgshoot13 commented
> 에러 수정해주세요

bd9877a59da6c2fed4715cfcfa26669f9b07b4d6
반영하였습니다.

2020-07-25 01:57 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-07-25 02:01 UTC, sjjeong commented
conflict 처리해주세요

2020-07-27 01:14 UTC, pgshoot13 commented
> conflict 처리해주세요

13,23 머지하였습니다. 요청 부탁드립니다.

2020-07-27 09:20 UTC, sjjeong commented
머지커밋이 잘못된거같네요
아직 conflic가 해결되지 않았고 다른사람 커밋이 들어왔습니다.

2020-07-27 23:45 UTC, pgshoot13 commented
> 머지커밋이 잘못된거같네요
> 아직 conflict가 해결되지 않았고 다른사람 커밋이 들어왔습니다.

제가 머지하기전이 bd9877a59da6c2fed4715cfcfa26669f9b07b4d6 여기인데
이때로 reset 하면 이전 manjee님 로그가 다 지워지나요?

2020-07-28 01:34 UTC, closed without merging