hw-5 : mvvm
sjjeong/GoogryAndroidArchitecutreStudy pull request #756
Opened 2020-07-27 03:56 UTC by songmilee

2020-07-27 15:52 UTC, manjee-study approved these changes

2020-07-30 11:46 UTC, sjjeong requested changes

2020-07-30 11:46 UTC, sjjeong commented on class12/songmilee/class12Android/app/src/main/java/mi/song/class12android/data/source/remote/RetrofitHelper.kt
> +    }
이런 형태는 OkHttpClient.Builder의 extension function으로 만들면 기존 빌더 패턴처럼 사용할 수 있습니다

2020-07-30 11:46 UTC, sjjeong commented on class12/songmilee/class12Android/app/src/main/res/layout/activity_main.xml
> +            type="String" />
query는 ViewModel에 넣고 two way binding으로 처리 해주세요

2020-07-30 11:46 UTC, sjjeong commented on class12/songmilee/class12Android/app/src/main/java/mi/song/class12android/viewmodel/MovieViewModel.kt
> +class MovieViewModel(context: Context) {
ViewModel는 context를 가지고 있지 않는게 좋습니다.

context를 전달하지 말고 SearchMovieRepositoryImpl객체를 만들어서 전달받도록 해주세요

2020-07-30 11:46 UTC, sjjeong commented on class12/songmilee/class12Android/app/src/main/java/mi/song/class12android/ui/MainActivity.kt
> +            movieAdapter.addMovieInfo(list)
잘하셨는데 BindingAdapter로 처리하는 방식으로 변경해보세요

2020-07-31 07:09 UTC, songmilee commented on class12/songmilee/class12Android/app/src/main/java/mi/song/class12android/data/source/remote/RetrofitHelper.kt
> +    }
7bcaf773

2020-07-31 07:10 UTC, songmilee commented on class12/songmilee/class12Android/app/src/main/res/layout/activity_main.xml
> +            type="String" />
dbcfb9e2

2020-07-31 07:10 UTC, songmilee commented on class12/songmilee/class12Android/app/src/main/java/mi/song/class12android/viewmodel/MovieViewModel.kt
> +class MovieViewModel(context: Context) {
3e467f14

2020-07-31 07:10 UTC, songmilee commented on class12/songmilee/class12Android/app/src/main/java/mi/song/class12android/ui/MainActivity.kt
> +            movieAdapter.addMovieInfo(list)
9bac7904

2020-08-01 02:11 UTC, sjjeong commented on class12/songmilee/class12Android/app/src/main/java/mi/song/class12android/data/source/remote/RetrofitHelper.kt
> +    }
OkHttpClient.Builder의 extension function로 만들어주세요

2020-08-01 04:47 UTC, songmilee commented on class12/songmilee/class12Android/app/src/main/java/mi/song/class12android/data/source/remote/RetrofitHelper.kt
> +    }
22e83721

2020-08-02 04:23 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-08-04 00:31 UTC, merged