HW-5 Observe pattern
sjjeong/GoogryAndroidArchitecutreStudy pull request #759
Opened 2020-07-27 15:53 UTC by manjee-study

2020-07-28 00:06 UTC, songmilee approved these changes

2020-07-30 11:51 UTC, sjjeong requested changes

2020-07-30 11:51 UTC, sjjeong commented on class12/manjee-study/ArchitectureStudy/app/src/main/res/layout/activity_main.xml
> +            android:onClick="@{() -> viewModel.searchMovieOnRemote(searchEditText.getText().toString())}"
query를 파라미터로 전달하지 말고 ViewModel이 가지고 있고 two-way binding으로 처리 해보세요

2020-07-30 11:51 UTC, sjjeong commented on class12/manjee-study/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/MainActivity.kt
> +    fun showMovieList(movieList: List<MovieData>) {
BindingAdapter로 처리하는 방식으로 처리해보세요

2020-07-31 12:06 UTC, manjee-study commented on class12/manjee-study/ArchitectureStudy/app/src/main/res/layout/activity_main.xml
> +            android:onClick="@{() -> viewModel.searchMovieOnRemote(searchEditText.getText().toString())}"
5b47acfc1ae6ab8b8d7b68b4793f52fb10abaf61 처리했습니다

2020-07-31 12:29 UTC, manjee-study commented on class12/manjee-study/ArchitectureStudy/app/src/main/res/layout/activity_main.xml
> +            android:onClick="@{() -> viewModel.searchMovieOnRemote(searchEditText.getText().toString())}"
396d1d1e8a23c5ba955bb1899cf9cdb292bebf50

2020-07-31 12:30 UTC, manjee-study commented on class12/manjee-study/ArchitectureStudy/app/src/main/res/layout/activity_main.xml
> +            android:onClick="@{() -> viewModel.searchMovieOnRemote(searchEditText.getText().toString())}"
396d1d1e8a23c5ba955bb1899cf9cdb292bebf50 소스 수정

2020-08-03 14:16 UTC, manjee-study commented on class12/manjee-study/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/MainActivity.kt
> +    fun showMovieList(movieList: List<MovieData>) {
f6fffdfedeb80da78619aaaf6e5e50654d05f00a BindingAdapter로 처리하는 방식으로 변경했습니다

2020-08-03 15:05 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-08-05 07:22 UTC, merged