HW-6 DI (Koin) 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #76
Opened 2019-06-27 10:56 UTC by namjackson

Koin 적용!!

2019-06-28 05:15 UTC, ddaeyeonkim submitted a review, later dismissed
LGTM 👍👍👍

2019-06-29 09:29 UTC, sjjeong requested changes

2019-06-29 09:29 UTC, sjjeong commented on namjackson/ArchStudy/app/src/main/java/com/namjackson/archstudy/di/DataSourceModule.kt
> +    single { TickerLocalDataSourceImpl.getInstance() }
```kotlin
single<TickerLocalDataSource> { TickerLocalDataSourceImpl.getInstance() }
```
형태로 provide를 만드셔야해요

2019-06-29 09:29 UTC, sjjeong commented on namjackson/ArchStudy/app/src/main/java/com/namjackson/archstudy/di/NetworkModule.kt
> +    single { UpbitService.upbitApi }
UbitService.upbitApi에 있는 내용을 여기에 작성해주시면 돼요

2019-07-03 07:15 UTC, namjackson commented on namjackson/ArchStudy/app/src/main/java/com/namjackson/archstudy/di/DataSourceModule.kt
> +    single { TickerLocalDataSourceImpl.getInstance() }
adbcd3d99c05625091b1bbfdbf52eca5321d30f1

2019-07-03 07:16 UTC, namjackson commented on namjackson/ArchStudy/app/src/main/java/com/namjackson/archstudy/di/NetworkModule.kt
> +    single { UpbitService.upbitApi }
수정했습니다!
f941769d0a216abc6c9e14ee6347d92fce8b320a

2019-07-03 11:18 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-07-03 11:18 UTC, merged