HW5 - MVVM
sjjeong/GoogryAndroidArchitecutreStudy pull request #762
Opened 2020-07-28 07:19 UTC by DWL5

2020-07-29 14:25 UTC, pgshoot13 commented on class12/DWL5/study/app/src/main/java/com/world/tree/architecturestudy/view/MainActivity.kt
옵저버 관련하여 addOnPropertyChangedCallback은 따로 안쓰신건가요?

2020-07-30 07:11 UTC, DWL5 commented on class12/DWL5/study/app/src/main/java/com/world/tree/architecturestudy/view/MainActivity.kt
12ded8e
데이터를 바로 바인딩 할 수 있는 부분은 사용하지 않았고,
toast 처리 처럼 데이터 변경 후 view에서 처리해줘야 할 부분은 수정했습니다.

2020-07-30 15:37 UTC, pgshoot13 commented on class12/DWL5/study/app/src/main/java/com/world/tree/architecturestudy/view/MainActivity.kt
아 이런 방법도 있군요.
수고하셨습니다!

2020-07-30 15:38 UTC, pgshoot13 approved these changes

2020-08-01 03:25 UTC, sjjeong commented on class12/DWL5/study/app/src/main/java/com/world/tree/architecturestudy/BindingAdapter.kt
> +fun bindData(recyclerView: RecyclerView, data : ArrayList<Movie.Item>) {
List타입으로 받아주세요

2020-08-01 03:25 UTC, sjjeong commented on class12/DWL5/study/app/src/main/java/com/world/tree/architecturestudy/BindingAdapter.kt
> +    val adapter = recyclerView.adapter as MovieAdapter
(recyclerView.adapter as? MovieAdapter)?.addData(data)

2020-08-01 03:30 UTC, sjjeong requested changes

2020-08-01 03:30 UTC, sjjeong commented on class12/DWL5/study/app/src/main/java/com/world/tree/architecturestudy/BindingAdapter.kt
> +    adapter.addData(data)
clear도 추가해주세요

2020-08-01 03:30 UTC, sjjeong commented on class12/DWL5/study/app/src/main/java/com/world/tree/architecturestudy/view/MainActivity.kt
> +                if (viewModel.toastMsg.get()!!.isEmpty()) return
!!는 쓰지 말아주세요 
```kotlin
if (viewModel.toastMsg.get().isNullOrEmpty()) return
```

2020-08-01 03:30 UTC, sjjeong commented on class12/DWL5/study/app/src/main/res/layout/activity_main.xml
> +            android:onClick="@{()-> viewModel.searchMovie(viewModel.title)}"
파라미터로 전달하지 말고 ViewModel에서 직접 사용해주세요

2020-08-01 03:32 UTC, sjjeong requested changes
Presenter와 Contract도 같이제거해주세요

2020-08-03 09:32 UTC, DWL5 commented on class12/DWL5/study/app/src/main/java/com/world/tree/architecturestudy/view/MainActivity.kt
> +                if (viewModel.toastMsg.get()!!.isEmpty()) return
ed9e610 반영했습니다.

2020-08-03 09:32 UTC, DWL5 commented on class12/DWL5/study/app/src/main/java/com/world/tree/architecturestudy/BindingAdapter.kt
> +fun bindData(recyclerView: RecyclerView, data : ArrayList<Movie.Item>) {
585429d 반영했습니다.

2020-08-03 09:33 UTC, DWL5 commented on class12/DWL5/study/app/src/main/java/com/world/tree/architecturestudy/BindingAdapter.kt
> +    adapter.addData(data)
b4a7ff9 반영했습니다.

2020-08-03 09:33 UTC, DWL5 commented on class12/DWL5/study/app/src/main/java/com/world/tree/architecturestudy/BindingAdapter.kt
> +    val adapter = recyclerView.adapter as MovieAdapter
b4a7ff9 반영했습니다.

2020-08-03 11:39 UTC, DWL5 commented on class12/DWL5/study/app/src/main/res/layout/activity_main.xml
> +            android:onClick="@{()-> viewModel.searchMovie(viewModel.title)}"
73647b6 반영했습니다.

2020-08-03 15:06 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-08-04 02:01 UTC, merged