HW-5 viewmodel
sjjeong/GoogryAndroidArchitecutreStudy pull request #763
Opened 2020-07-28 07:39 UTC by ysj1224

android:onClick="@{() -> vm.requestMovieList(etvSearch.getText().toString())}"
이걸 사용하고 싶은데 작성하면 반응을 안하네요.. 혹시 아시면 도움 부탁드려요

2020-07-29 11:45 UTC, dlqkfzlr reviewed
혹시 two-way라서 @={ ~ } 로 해야되는게 아닐까요?
아니면 EditText에도 데이터 바인딩 적용하신다음에
vm.requestMovieList(vm.EtSearch) 이런식으로 하면 될 것 같아요

2020-07-29 15:12 UTC, dlqkfzlr commented on class12/ysj1224/Study/app/src/main/java/com/example/study/view/MainActivity.kt
>              rvMain.apply {
adapter도 xml에서 설정하는게 좋을 것 같습니다.

2020-07-29 15:12 UTC, dlqkfzlr commented on class12/ysj1224/Study/app/src/main/res/layout/activity_main.xml
>              android:id="@+id/btn_check"
xml에서 requestMovieList를 호출하는게 더 좋을 것 같아요

2020-07-30 00:26 UTC, dlqkfzlr commented on class12/ysj1224/Study/app/src/main/res/layout/activity_main.xml
>              android:id="@+id/etv_search"
여기엔 DataBinding 적용이 안되어있네요

2020-07-30 13:28 UTC, ysj1224 commented
2way 방식으로 해도 작동이 안되고 xml 에 선웅님과 동일한 방식으로 했는데도 잘 안되네요.. 토요일에 석준님께 코드 보여드리고 도움청해야 할것같네요.. 36b602c2

2020-07-30 13:43 UTC, dlqkfzlr commented
> 2way 방식으로 해도 작동이 안되고 xml 에 선웅님과 동일한 방식으로 했는데도 잘 안되네요.. 토요일에 석준님께 코드 보여드리고 도움청해야 할것같네요.. [36b602c](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/commit/36b602c2d1dc9f6266f3d18d84588df93307faae)

위에 남겨드린 Comment들은 수정하신건가요??

2020-07-31 00:31 UTC, ysj1224 commented
코멘트 참조해서 고쳐봤는데 작동을 안해서 다시 원상복구 시키고 어댑터 뷰모델쪽으로 뺏는데 어댑터는 뷰에 가깝다고 하셔서 다시 원상복구 시켜야 할것같네욥

2020-07-31 07:42 UTC, dlqkfzlr commented
> 코멘트 참조해서 고쳐봤는데 작동을 안해서 다시 원상복구 시키고 어댑터 뷰모델쪽으로 뺏는데 어댑터는 뷰에 가깝다고 하셔서 다시 원상복구 시켜야 할것같네욥

네 그럼 일단 approve하겠습니다.

2020-07-31 07:42 UTC, dlqkfzlr approved these changes

2020-08-01 03:35 UTC, sjjeong requested changes

2020-08-01 03:35 UTC, sjjeong commented on class12/ysj1224/Study/app/src/main/java/com/example/study/view/MainActivity.kt
> +                viewModel.requestMovieList(binding.etvSearch.text.toString())
xml에서 처리해주세요

2020-08-01 03:35 UTC, sjjeong commented on class12/ysj1224/Study/app/src/main/java/com/example/study/view/MainActivity.kt
> +                    movieList.get()?.let { showMovieList(it) }
BindingAdapter로 처리해보세요

2020-08-01 03:35 UTC, sjjeong commented on class12/ysj1224/Study/app/src/main/java/com/example/study/viewmodel/MovieViewModel.kt
> +        noQuery.set(noQuery.get()?.plus(1))
noQuery.notifyChange() 호출하면 됩니다.

2020-08-01 03:35 UTC, sjjeong commented on class12/ysj1224/Study/app/src/main/java/com/example/study/viewmodel/MovieViewModel.kt
> +    fun requestMovieList(query: String) {
query를 파라미터로 받지 말고 MovieViewModel 안에 query를 만들고 two-way 처리 해주세요

2020-08-03 08:02 UTC, ysj1224 commented on class12/ysj1224/Study/app/src/main/java/com/example/study/viewmodel/MovieViewModel.kt
> +    fun requestMovieList(query: String) {
ed252fbd

2020-08-03 08:02 UTC, ysj1224 commented on class12/ysj1224/Study/app/src/main/java/com/example/study/view/MainActivity.kt
> +                viewModel.requestMovieList(binding.etvSearch.text.toString())
ed252fbd

2020-08-03 08:03 UTC, ysj1224 commented on class12/ysj1224/Study/app/src/main/java/com/example/study/view/MainActivity.kt
> +                    movieList.get()?.let { showMovieList(it) }
885ff1b9

2020-08-03 08:03 UTC, ysj1224 commented on class12/ysj1224/Study/app/src/main/java/com/example/study/viewmodel/MovieViewModel.kt
> +        noQuery.set(noQuery.get()?.plus(1))
dcc2e9d8

2020-08-03 15:07 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-08-04 00:33 UTC, merged