HW-5: MVVM with Databinding
sjjeong/GoogryAndroidArchitecutreStudy pull request #764
Opened 2020-07-29 12:04 UTC by dlqkfzlr

목요일에 주석처리해놓은 Toast기능 적용할 예정입니다.

2020-07-30 09:34 UTC, ysj1224 approved these changes

2020-07-30 14:16 UTC, sjjeong requested changes

2020-07-30 14:16 UTC, sjjeong commented on class12/dlqkfzlr/study/app/src/main/java/m/woong/architecturestudy/MovieViewModel.kt
> +    private val adapter: MovieAdapter,
adapter는 View에 가까운 클래스 이기 때문에 ViewModel에서 들고 있지 않게 해주세요

2020-07-30 14:16 UTC, sjjeong commented on class12/dlqkfzlr/study/app/src/main/res/layout/activity_main.xml
> +            name="ViewModel"
이름은 카멜케이스로 첫 시작이 소문자로 구성되어야 합니다.

2020-07-31 11:34 UTC, dlqkfzlr commented on class12/dlqkfzlr/study/app/src/main/res/layout/activity_main.xml
> +            name="ViewModel"
수정했습니다.
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/commit/5e0ceb2cc121effba65d91fba577d5a7fa4372c4

2020-07-31 12:51 UTC, dlqkfzlr commented on class12/dlqkfzlr/study/app/src/main/java/m/woong/architecturestudy/MovieViewModel.kt
> +    private val adapter: MovieAdapter,
xml의 'bind:adapter'는 수정할 필요없이 adapter를 들고 있는 class만 ViewModel에서 View로 옮기라는 의미인가요?

2020-08-01 17:07 UTC, dlqkfzlr commented on class12/dlqkfzlr/study/app/src/main/java/m/woong/architecturestudy/MovieViewModel.kt
> +    private val adapter: MovieAdapter,
수정완료
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/commit/2a62537434efc60535287838dd3a2e50a627340b

2020-08-02 04:24 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-08-02 04:25 UTC, merged