HW-5 : MVVM
sjjeong/GoogryAndroidArchitecutreStudy pull request #765
Opened 2020-07-30 02:43 UTC by pgshoot13

1. Apply MVVM
2. Remove Contract/Presenter
3. Add ViewModel
4. Add Observer

2020-07-30 02:56 UTC, pgshoot13 commented
커밋 분류가 좀 꼬였는데
양해 부탁드립니다.

2020-07-30 07:01 UTC, DWL5 commented on class12/pgshoot13/HyApplication/app/src/main/java/com/hyper/hyapplication/ui/MainActivity.kt
> +        mainViewModel.movieItem.addOnPropertyChangedCallback(object :
BindingAdapter를 이용하시면 movie data를 바로 Recyclerview에 바인딩 가능 합니다.

2020-07-31 02:18 UTC, pgshoot13 commented on class12/pgshoot13/HyApplication/app/src/main/java/com/hyper/hyapplication/ui/MainActivity.kt
> +        mainViewModel.movieItem.addOnPropertyChangedCallback(object :
35109ceb32a4089d4877fda0fac02363729c3374
반영하였습니다.

2020-07-31 11:34 UTC, DWL5 commented on class12/pgshoot13/HyApplication/app/src/main/java/com/hyper/hyapplication/ui/MainActivity.kt
> +        mainViewModel.movieItem.addOnPropertyChangedCallback(object :
수고하셨습니다!

2020-08-01 03:40 UTC, sjjeong requested changes

2020-08-01 03:40 UTC, sjjeong commented on class12/pgshoot13/HyApplication/app/src/main/java/com/hyper/hyapplication/BindingAdapter.kt
> +fun bindData(recyclerView: RecyclerView, data: ArrayList<ResultGetSearchMovie.Item>) {
List type으로 변경해주세요

2020-08-01 03:40 UTC, sjjeong commented on class12/pgshoot13/HyApplication/app/src/main/java/com/hyper/hyapplication/BindingAdapter.kt
> +    val viewAdapter = recyclerView.adapter as MovieAdapter
as?로 변경해주세요

2020-08-01 03:40 UTC, sjjeong commented on class12/pgshoot13/HyApplication/app/src/main/java/com/hyper/hyapplication/ui/MainViewModel.kt
> +    private val movieList = NaverRepositoryImpl(NaverRemoteDataSourceImpl())
List보단 Repository로 해주세요

2020-08-01 03:40 UTC, sjjeong commented on class12/pgshoot13/HyApplication/app/src/main/java/com/hyper/hyapplication/ui/MainViewModel.kt
> +    fun movieSearch(query: String) {
query를 파라미터로 받지 말고 movieName에서 가져다가 쓰도록 해주세요

2020-08-01 11:27 UTC, pgshoot13 commented on class12/pgshoot13/HyApplication/app/src/main/java/com/hyper/hyapplication/BindingAdapter.kt
> +    val viewAdapter = recyclerView.adapter as MovieAdapter
d4d086049fb793b77153438036c9eab06f054058
반영하였습니다.

2020-08-01 11:27 UTC, pgshoot13 commented on class12/pgshoot13/HyApplication/app/src/main/java/com/hyper/hyapplication/ui/MainViewModel.kt
> +    private val movieList = NaverRepositoryImpl(NaverRemoteDataSourceImpl())
9c091650838c986319e4abc5434d6f6ac0263b8c
반영하였습니다.

2020-08-01 11:28 UTC, pgshoot13 commented on class12/pgshoot13/HyApplication/app/src/main/java/com/hyper/hyapplication/ui/MainViewModel.kt
> +    fun movieSearch(query: String) {
29f2ec5e48c0f5864455675049dcd8319087563a
반영하였습니다.

2020-08-02 06:41 UTC, pgshoot13 commented on class12/pgshoot13/HyApplication/app/src/main/java/com/hyper/hyapplication/BindingAdapter.kt
> +fun bindData(recyclerView: RecyclerView, data: ArrayList<ResultGetSearchMovie.Item>) {
70df918fe85c9b703bd95fa86c5dd7fae0fb8f78
반영하였습니다.

2020-08-02 08:05 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-08-02 15:08 UTC, DWL5 approved these changes

2020-08-02 22:40 UTC, merged