HW-6 aac viewmodel & livedata
sjjeong/GoogryAndroidArchitecutreStudy pull request #766
Opened 2020-08-04 08:32 UTC by ysj1224

2020-08-05 05:37 UTC, dlqkfzlr approved these changes
잘하셨어요 👍

2020-08-05 10:45 UTC, sjjeong requested changes

2020-08-05 10:45 UTC, sjjeong commented on class12/ysj1224/Study/app/src/main/java/com/example/study/viewmodel/MovieViewModel.kt
> +    val noQuery: LiveData<Boolean> get() = _noQuery
값을 사용하는게 아니기 때문에 MutableLiveData<Unit> 으로 타입을 변경해주세요

2020-08-06 23:42 UTC, ysj1224 commented on class12/ysj1224/Study/app/src/main/java/com/example/study/viewmodel/MovieViewModel.kt
> +    val noQuery: LiveData<Boolean> get() = _noQuery
244e4683

2020-08-08 03:54 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-08-08 03:54 UTC, sjjeong commented on class12/ysj1224/Study/app/src/main/java/com/example/study/viewmodel/MovieViewModel.kt
> +    val noQuery = MutableLiveData<Boolean>(false)
제가 리뷰를 잘못남겼네요 ㅠ
기존꺼에서 Boolean 타입을 Unit으로 바꾸면 됩니다.

일단 이번과제에서는 머지하시고 다음과제에서 같이 변경해주세요

2020-08-10 06:42 UTC, merged