HW6 - LiveData
sjjeong/GoogryAndroidArchitecutreStudy pull request #767
Opened 2020-08-04 14:16 UTC by DWL5

HW6 - LiveData

2020-08-05 02:55 UTC, pgshoot13 commented on class12/DWL5/study/app/src/main/java/com/world/tree/architecturestudy/view/MainViewModel.kt
> +    }
ArrayList()를 따로 사용하신 이유가 알고싶습니다!

2020-08-06 08:35 UTC, DWL5 commented on class12/DWL5/study/app/src/main/java/com/world/tree/architecturestudy/view/MainViewModel.kt
> +    }
Value값에 아무것도 안넣어주면, Recyclerview data bind 하는 부분에서 에러가 발생해서
빈 arrayList를 넣어주었습니다.

2020-08-06 09:11 UTC, DWL5 commented
AAC Viewmodel로 안 바꿨었네요 ㅠㅠ 반영했습니다.

2020-08-08 01:37 UTC, pgshoot13 approved these changes

2020-08-08 06:14 UTC, sjjeong requested changes

2020-08-08 06:14 UTC, sjjeong commented on class12/DWL5/study/app/src/main/java/com/world/tree/architecturestudy/view/MainViewModel.kt
> +    private val _movieList = MutableLiveData<List<Movie.Item>>().also {
```kotlin
private val _movieList = MutableLiveData<List<Movie.Item>>(mutableListOf())
```
이렇게 하면 됩니다.

2020-08-08 06:14 UTC, sjjeong commented on class12/DWL5/study/app/src/main/java/com/world/tree/architecturestudy/view/MainViewModel.kt
> +    val movieList = _movieList
```kotlin
val movieList: LiveData<List<Movie.Item>> = _movieList
```
이렇게 해주셔야합니다.
아래 toastMsg도 동일하게 변경해주세요

2020-08-08 06:14 UTC, sjjeong commented on class12/DWL5/study/app/src/main/java/com/world/tree/architecturestudy/view/MainViewModelProvider.kt
> +class MainViewModelProvider(private val repository: Any) : ViewModelProvider.Factory {
Any가 아니라 NaverRepository 로 받으면 됩니다

2020-08-08 06:14 UTC, sjjeong commented on class12/DWL5/study/app/src/main/java/com/world/tree/architecturestudy/view/MainActivity.kt
> +        val viewModel = MainViewModelProvider(movieContainer.repository).create(MainViewModel::class.java)
create말고 get을 사용해주세요

2020-08-10 16:04 UTC, DWL5 commented on class12/DWL5/study/app/src/main/java/com/world/tree/architecturestudy/view/MainViewModel.kt
> +    private val _movieList = MutableLiveData<List<Movie.Item>>().also {
8ff997b
반영했습니다.

2020-08-10 16:04 UTC, DWL5 commented on class12/DWL5/study/app/src/main/java/com/world/tree/architecturestudy/view/MainViewModel.kt
> +    val movieList = _movieList
8ff997b
반영했습니다.

2020-08-10 16:05 UTC, DWL5 commented on class12/DWL5/study/app/src/main/java/com/world/tree/architecturestudy/view/MainViewModelProvider.kt
> +class MainViewModelProvider(private val repository: Any) : ViewModelProvider.Factory {
ff240ca
반영했습니다

2020-08-10 16:05 UTC, DWL5 commented on class12/DWL5/study/app/src/main/java/com/world/tree/architecturestudy/view/MainActivity.kt
> +        val viewModel = MainViewModelProvider(movieContainer.repository).create(MainViewModel::class.java)
3f49dbf
반영했습니다

2020-08-11 13:12 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-08-12 07:07 UTC, merged