HW6 : AAC LiveData
sjjeong/GoogryAndroidArchitecutreStudy pull request #768
Opened 2020-08-05 02:48 UTC by pgshoot13

1. Add AAC ViewModel
2. Add AAC LiveData

2020-08-06 09:10 UTC, DWL5 requested changes

2020-08-06 09:10 UTC, DWL5 commented on class12/pgshoot13/HyApplication/app/src/main/java/com/hyper/hyapplication/ui/MainViewModel.kt
>              MainActivity().showEmptyMessage()
ViewModel이 MainActivity에 대해서 알면 안될 것 같아요
LiveData로 메세지 처리를 하시면 어떨가요??

2020-08-09 12:53 UTC, pgshoot13 commented on class12/pgshoot13/HyApplication/app/src/main/java/com/hyper/hyapplication/ui/MainViewModel.kt
>              MainActivity().showEmptyMessage()
여행때문에 답변이 늦었습니다..
현재 라이브 데이터로는 showFailure 메세지를 
사용하고 있어서 이처럼 사용했습니다...

2020-08-10 11:38 UTC, DWL5 commented on class12/pgshoot13/HyApplication/app/src/main/java/com/hyper/hyapplication/ui/MainViewModel.kt
>              MainActivity().showEmptyMessage()
넵 알겠습니다!! 수고하셨습니다.

2020-08-10 14:53 UTC, sjjeong requested changes

2020-08-10 14:53 UTC, sjjeong commented on class12/pgshoot13/HyApplication/app/src/main/java/com/hyper/hyapplication/ui/MainViewModel.kt
>              MainActivity().showEmptyMessage()
엑티비티를 직접 만드시면 안됩니다.
LiveData로 이벤트를 전달하고 observe하는 방식으로 처리해주세요

2020-08-11 01:49 UTC, pgshoot13 commented on class12/pgshoot13/HyApplication/app/src/main/java/com/hyper/hyapplication/ui/MainViewModel.kt
>              MainActivity().showEmptyMessage()
b8a47003b647f56cfc5952ac8fb31be47d8bff1f
반영하였습니다.

2020-08-11 13:09 UTC, sjjeong requested changes

2020-08-11 13:09 UTC, sjjeong commented on class12/pgshoot13/HyApplication/app/src/main/java/com/hyper/hyapplication/ui/MainViewModel.kt
> +            _emptyData.value = emptyData.value
실제 사용하는 곳에서 value를 사용하지 않는다면 type을 Unit으로 만들고 
```kotlin
_emptyData.value = Unit
```
이렇게 처리해주시면 됩니다.

2020-08-12 01:45 UTC, pgshoot13 commented on class12/pgshoot13/HyApplication/app/src/main/java/com/hyper/hyapplication/ui/MainViewModel.kt
> +            _emptyData.value = emptyData.value
c566ae53fbb2f90bbde8143afff997418cf86c7c
아! 감사합니다!
반영하였습니다!

2020-08-12 15:26 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-08-13 02:56 UTC, DWL5 approved these changes
수고하셨습니다!

2020-08-13 03:05 UTC, merged