HW-6:Livedata&ViewModel
sjjeong/GoogryAndroidArchitecutreStudy pull request #770
Opened 2020-08-05 08:46 UTC by songmilee

2020-08-05 13:24 UTC, manjees approved these changes

2020-08-05 13:28 UTC, manjee-study approved these changes
실수로 다른 계정으로 리뷰 달아버렸네여

Good!

2020-08-05 15:48 UTC, sjjeong requested changes

2020-08-05 15:48 UTC, sjjeong commented on class12/songmilee/class12Android/app/src/main/java/mi/song/class12android/viewmodel/MovieViewModel.kt
> +    val successResult = MutableLiveData<List<MovieInfo>>()
ViewModel 밖에서 set할 경우가 없기 때문에 private으로 변경해주시고 외부에서는 LiveData 형태로 접근하도록 변경해주세요

2020-08-08 06:23 UTC, songmilee commented on class12/songmilee/class12Android/app/src/main/java/mi/song/class12android/viewmodel/MovieViewModel.kt
> +    val successResult = MutableLiveData<List<MovieInfo>>()
aab90d44

2020-08-08 06:24 UTC, sjjeong requested changes

2020-08-08 06:24 UTC, sjjeong commented on class12/songmilee/class12Android/app/src/main/java/mi/song/class12android/util/BindingAdapterUtil.kt
> +fun updateMovieList(recyclerView: RecyclerView, movieInfoList: LiveData<List<MovieInfo>>?) {
여기는 LiveData일 필요가 없습니다

List<MovieInfo>? 로 변경해주세요

2020-08-08 06:33 UTC, songmilee commented on class12/songmilee/class12Android/app/src/main/java/mi/song/class12android/util/BindingAdapterUtil.kt
> +fun updateMovieList(recyclerView: RecyclerView, movieInfoList: LiveData<List<MovieInfo>>?) {
0b0ed83f

2020-08-08 06:34 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-08-08 06:40 UTC, merged