HW-6 LiveData
sjjeong/GoogryAndroidArchitecutreStudy pull request #771
Opened 2020-08-05 13:29 UTC by manjee-study

2020-08-07 02:58 UTC, songmilee requested changes

2020-08-07 02:58 UTC, songmilee commented on class12/manjee-study/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/viewmodel/MainViewModel.kt
> +            movieTitleLiveData.value.toString(),
postValue 보다 setValue가 좋을 것 같아요

2020-08-07 09:23 UTC, manjee-study commented on class12/manjee-study/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/viewmodel/MainViewModel.kt
> +            movieTitleLiveData.value.toString(),
598737af5e1d6e956101e59b8ed64fe8ede9f622 수정했습니다!

2020-08-07 09:53 UTC, songmilee approved these changes

2020-08-08 02:06 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-08-08 02:09 UTC, merged