HW-7 : Koin & Hilt
sjjeong/GoogryAndroidArchitecutreStudy pull request #778
Opened 2020-08-08 13:35 UTC by dlqkfzlr

2020-08-11 09:02 UTC, ysj1224 approved these changes

2020-08-11 13:14 UTC, sjjeong requested changes

2020-08-11 13:14 UTC, sjjeong commented on class12/dlqkfzlr/study/app/src/main/java/m/woong/architecturestudy/di/NetworkModule.kt
> +    factory { provideMovieApi(get()) }
api는 매번 만들필요가 없으니 single이면 됩니다.

2020-08-11 13:14 UTC, sjjeong commented on class12/dlqkfzlr/study/app/src/main/java/m/woong/architecturestudy/MovieViewModel.kt
> +    val repository: MovieRepository
public일 필요가 없습니다.
다른곳도 다시 private으로 변경해주세요

2020-08-11 14:37 UTC, dlqkfzlr commented on class12/dlqkfzlr/study/app/src/main/java/m/woong/architecturestudy/di/NetworkModule.kt
> +    factory { provideMovieApi(get()) }
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/778/commits/db20b2c5a43b1e2a49adbbb59161e3b712aef60b

2020-08-11 14:39 UTC, dlqkfzlr commented on class12/dlqkfzlr/study/app/src/main/java/m/woong/architecturestudy/MovieViewModel.kt
> +    val repository: MovieRepository
그럼 처음에 inject받는 부분인 MainActivity에서만 public으로 처리하면 되는건가요?
수정은 했습니다.
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/commit/6cc2de639cbd4757ff99d1e986831cf543e9c370

2020-08-11 15:17 UTC, sjjeong commented on class12/dlqkfzlr/study/app/src/main/java/m/woong/architecturestudy/MovieViewModel.kt
> +    val repository: MovieRepository
koin을 사용하는 경우에는 private이어도 상관없습니다.
Dagger나 Hilt를 사용할때 filed injection인 경우에만 public이어야 합니다.

2020-08-11 15:17 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-08-12 00:32 UTC, dlqkfzlr commented on class12/dlqkfzlr/study/app/src/main/java/m/woong/architecturestudy/MovieViewModel.kt
> +    val repository: MovieRepository
넵 답변 감사합니다ㅎㅎ

2020-08-12 00:32 UTC, merged