13기 황준홍 README.md 링크 수정
sjjeong/GoogryAndroidArchitecutreStudy pull request #779
Opened 2020-08-08 13:51 UTC by Hwangjunhong

2020-08-09 12:59 UTC, sjjeong requested changes

2020-08-09 12:59 UTC, sjjeong commented on class13/README.md
> +[공간](https://github.com/Hwangjunhong/GoogryAndroidArchitectureStudy/tree/master/class13/Hwangjunhong)
공간 링크는 StudyFork로 해주세요

2020-08-09 17:25 UTC, Hwangjunhong commented
공간링크 수정했습니다!

2020-08-10 14:44 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-08-10 15:05 UTC, merged