HW-7 koin적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #782
Opened 2020-08-11 05:32 UTC by ysj1224

2020-08-11 05:50 UTC, dlqkfzlr commented on class12/ysj1224/Study/app/src/main/java/com/example/study/App.kt
> +            androidContext(this@App)
androidLogger 추가해주세요

2020-08-11 05:50 UTC, dlqkfzlr commented on class12/ysj1224/Study/app/src/main/java/com/example/study/viewmodel/MovieViewModel.kt
> +    val repository = MovieListRepositoryImpl()
이거 DI가 안되어 있습니다.

2020-08-11 05:50 UTC, dlqkfzlr commented on class12/ysj1224/Study/app/src/main/java/com/example/study/di/Module.kt
> +    single<MovieListRepository> { MovieListRepositoryImpl() }
RemoteDataSourceImpl도 DI하셔야 할 것 같아요

2020-08-11 05:50 UTC, dlqkfzlr commented on class12/ysj1224/Study/app/src/main/java/com/example/study/data/repository/MovieListRepositoryImpl.kt
> +    val remoteInterfaceImpl = RemoteDataSourceImpl()
DI가 안되어 있는 것 같네요

2020-08-11 05:50 UTC, dlqkfzlr commented on class12/ysj1224/Study/app/src/main/java/com/example/study/viewmodel/MovieViewModel.kt
> +    val noQuery = MutableLiveData<Unit>()
Boolean으로 했을때 원하는 의도대로 작동하지 않아서 Unit으로 변경하신건가요??

2020-08-11 05:52 UTC, dlqkfzlr commented
아 그리고 Commit에는 없던 내용인데, Retrofit관련해서도 DI가 안되어 있어서 추가하셔야 할 것 같네요.

2020-08-12 01:38 UTC, ysj1224 commented on class12/ysj1224/Study/app/src/main/java/com/example/study/App.kt
> +            androidContext(this@App)
e5c1b57d

2020-08-12 01:38 UTC, ysj1224 commented on class12/ysj1224/Study/app/src/main/java/com/example/study/viewmodel/MovieViewModel.kt
> +    val repository = MovieListRepositoryImpl()
cf50279a

2020-08-12 01:38 UTC, ysj1224 commented on class12/ysj1224/Study/app/src/main/java/com/example/study/di/Module.kt
> +    single<MovieListRepository> { MovieListRepositoryImpl() }
cf50279a

2020-08-12 01:38 UTC, ysj1224 commented on class12/ysj1224/Study/app/src/main/java/com/example/study/data/repository/MovieListRepositoryImpl.kt
> +    val remoteInterfaceImpl = RemoteDataSourceImpl()
cf50279a

2020-08-12 01:39 UTC, ysj1224 commented on class12/ysj1224/Study/app/src/main/java/com/example/study/viewmodel/MovieViewModel.kt
> +    val noQuery = MutableLiveData<Unit>()
석준님이 Unit으로 처리하라고 하셨는데 어떻게 해야될지 감이 안오네요 :(

2020-08-12 02:08 UTC, dlqkfzlr commented on class12/ysj1224/Study/app/src/main/java/com/example/study/viewmodel/MovieViewModel.kt
> +    val repository = MovieListRepositoryImpl()
parameter type을 interface로 바꾼건 잘 하셨는데, DI는 아직도 안되어 있습니다.
appModule에 single이나 factory식으로 추가해 달라는 말이었습니다.

2020-08-12 02:08 UTC, dlqkfzlr commented on class12/ysj1224/Study/app/src/main/java/com/example/study/di/Module.kt
> +    single<MovieListRepository> { MovieListRepositoryImpl() }
주석 HelloRepository로 되어있는거 수정해주세요

2020-08-12 02:09 UTC, dlqkfzlr commented on class12/ysj1224/Study/app/src/main/java/com/example/study/data/repository/MovieListRepositoryImpl.kt
> +    val remoteInterfaceImpl = RemoteDataSourceImpl()
마찬가지입니다.

2020-08-12 02:11 UTC, dlqkfzlr commented on class12/ysj1224/Study/app/src/main/java/com/example/study/viewmodel/MovieViewModel.kt
> +    val repository = MovieListRepositoryImpl()
아 커밋링크가 module쪽이 아니어서 착각했습니다. 추가해주셨네요 👍

2020-08-12 02:13 UTC, dlqkfzlr commented on class12/ysj1224/Study/app/src/main/java/com/example/study/di/Module.kt
> +    single<MovieListRepository> { MovieListRepositoryImpl() }
이것도 추가되었네요. 👍

2020-08-12 02:18 UTC, dlqkfzlr commented on class12/ysj1224/Study/app/src/main/java/com/example/study/viewmodel/MovieViewModel.kt
> +    val repository = MovieListRepositoryImpl()
제가 의도한 DI의 의미는 이렇게 객체를 생성하는 것이 아닌 constructor안에 repository를 parameter로 넣어주는걸 의미한거였습니다.

2020-08-12 04:37 UTC, ysj1224 commented on class12/ysj1224/Study/app/src/main/java/com/example/study/viewmodel/MovieViewModel.kt
> +    val repository = MovieListRepositoryImpl()
잘 이해가 안되네요

2020-08-12 04:37 UTC, ysj1224 commented on class12/ysj1224/Study/app/src/main/java/com/example/study/data/repository/MovieListRepositoryImpl.kt
> +    val remoteInterfaceImpl = RemoteDataSourceImpl()
잘이해가 안되네요

2020-08-12 05:19 UTC, dlqkfzlr commented on class12/ysj1224/Study/app/src/main/java/com/example/study/viewmodel/MovieViewModel.kt
> +    val repository = MovieListRepositoryImpl()
commit링크에 들어갔을때 저부분이 변경된걸로 나와있지 않아서 이렇게 코멘트를 달았는데 파라미터로 이미 받고 계시네요?
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/commit/cf50279a5a78ec4efd7557176a3d636f0694a31a 이 커밋때 고치신건가요?? 제가 착각한거 같기도 하구요

2020-08-12 05:23 UTC, dlqkfzlr commented on class12/ysj1224/Study/app/src/main/java/com/example/study/data/repository/MovieListRepositoryImpl.kt
> +    val remoteInterfaceImpl = RemoteDataSourceImpl()
appModule에 추가하신걸 commit링크로 달아주셔야하는데 RepositoryImpl쪽으로 달아주셔서 추가하신줄 몰랐습니다.

2020-08-12 05:28 UTC, dlqkfzlr commented on class12/ysj1224/Study/app/src/main/java/com/example/study/viewmodel/MovieViewModel.kt
> +    val noQuery = MutableLiveData<Unit>()
저는 Boolean으로 해서 approved 받았는데, Boolean으로 해서 작동이 안돼서 석준님이 Unit으로 바꿔보라고 하신건가요?
제가 전후사정을 몰라서 승진님꺼 지난번 PR을 봤는데도 잘 모르겠네요..

2020-08-12 05:30 UTC, dlqkfzlr commented
> 아 그리고 Commit에는 없던 내용인데, Retrofit관련해서도 DI가 안되어 있어서 추가하셔야 할 것 같네요.

이건 NaverApi 인터페이스 모듈에 추가해달라는 말이었습니다.

2020-08-12 05:39 UTC, ysj1224 commented on class12/ysj1224/Study/app/src/main/java/com/example/study/viewmodel/MovieViewModel.kt
> +    val noQuery = MutableLiveData<Unit>()
boolean으로는 정상 작동되었는데 석준님이 unit으로 바꿔보라고 하셔서 바꿔보는데 잘 모르겠네요...

2020-08-12 07:29 UTC, ysj1224 commented
932d03ed
해보긴했는데 제가 아직 di에대한 이해가 부족해서 그런지 이점을 모르겠네요 ㅠ

2020-08-12 09:14 UTC, dlqkfzlr commented
> [932d03e](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/commit/932d03ed5732ed032275ca19ba0b08a46655bca8)
> 해보긴했는데 제가 아직 di에대한 이해가 부족해서 그런지 이점을 모르겠네요 ㅠ

모듈에 추가하신건 잘하셨는데 Commit에는 RemoteDataSourceImp에서 NaverApi 처리를 어떻게 변경하셨는지 안나오네요

2020-08-12 09:16 UTC, dlqkfzlr commented on class12/ysj1224/Study/app/src/main/java/com/example/study/di/Module.kt
> +    single<RemoteDataSource> { RemoteDataSourceImpl( ) }
single<RemoteDataSource> { RemoteDataSourceImpl(get()) } 으로 변경하시고 RemoteDataSourceImpl에 생성자로  naverApi 넣어주세요

2020-08-13 00:50 UTC, ysj1224 commented on class12/ysj1224/Study/app/src/main/java/com/example/study/di/Module.kt
> +    single<RemoteDataSource> { RemoteDataSourceImpl( ) }
87ddd0b9

2020-08-14 02:18 UTC, ysj1224 commented
e3474797

2020-08-17 17:12 UTC, sjjeong requested changes

2020-08-17 17:12 UTC, sjjeong commented on class12/ysj1224/Study/app/src/main/java/com/example/study/App.kt
> +            androidLogger()
androidLogger는 BuildConfig.DEBUG가 true일때만 추가하도록 해주세요

2020-08-17 17:12 UTC, sjjeong commented on class12/ysj1224/Study/app/src/main/java/com/example/study/data/remote/RemoteDataSourceImpl.kt
> +class RemoteDataSourceImpl(private val NaverApi: NaverApi) : RemoteDataSource {
property는 소문자로 시작해야합니다.

2020-08-17 17:12 UTC, sjjeong commented on class12/ysj1224/Study/app/src/main/java/com/example/study/viewmodel/MovieViewModel.kt
> +    val noQuery = MutableLiveData<Unit>()
이벤트만 전달하면 되기 때문에 LiveData가 notify해줄수 있도록 Unit만 set 해주면 되는겁니다.
하단에 코드 구현해주세요

2020-08-17 17:12 UTC, sjjeong commented on class12/ysj1224/Study/app/src/main/java/com/example/study/di/NetworkModule.kt
> +fun NaverRetrofit() : NaverApi{
함수명은 동사로 시작하고 소문자로 시작 해주세요

2020-08-18 01:13 UTC, ysj1224 commented on class12/ysj1224/Study/app/src/main/java/com/example/study/App.kt
> +            androidLogger()
b89a27b9

2020-08-18 01:14 UTC, ysj1224 commented on class12/ysj1224/Study/app/src/main/java/com/example/study/data/remote/RemoteDataSourceImpl.kt
> +class RemoteDataSourceImpl(private val NaverApi: NaverApi) : RemoteDataSource {
70abb1fa

2020-08-18 01:14 UTC, ysj1224 commented on class12/ysj1224/Study/app/src/main/java/com/example/study/di/NetworkModule.kt
> +fun NaverRetrofit() : NaverApi{
63750d56

2020-08-18 01:15 UTC, ysj1224 commented on class12/ysj1224/Study/app/src/main/java/com/example/study/di/NetworkModule.kt
> +fun NaverRetrofit() : NaverApi{
3747b4dc

2020-08-19 12:07 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-08-20 00:29 UTC, dlqkfzlr approved these changes

2020-08-20 00:29 UTC, merged