HW-7:koin
sjjeong/GoogryAndroidArchitecutreStudy pull request #783
Opened 2020-08-11 12:34 UTC by songmilee

2020-08-12 02:51 UTC, manjee-study approved these changes

2020-08-12 15:22 UTC, sjjeong requested changes

2020-08-12 15:22 UTC, sjjeong commented on class12/songmilee/class12Android/app/src/main/java/mi/song/class12android/app/MovieApplication.kt
> +            androidLogger(Level.DEBUG)
```kotlin
if(BuildConfig.DEBUG) {
    androidLogger()
}
```
이렇게 해주셔야 합니다.

2020-08-12 15:22 UTC, sjjeong commented on class12/songmilee/class12Android/app/src/main/java/mi/song/class12android/app/MovieApplication.kt
> +            modules(listOf(movieSearchModule, networkModule))
vararg여서 list로 만들 필요는 없습니다.

2020-08-12 15:22 UTC, sjjeong commented on class12/songmilee/class12Android/app/src/main/java/mi/song/class12android/data/repository/SearchMovieRepositoryImpl.kt
> +class SearchMovieRepositoryImpl(val movieService: MovieService) : SearchMovieRepository {
movieService를 private으로 해주셔도 됩니다.

2020-08-13 07:46 UTC, songmilee commented on class12/songmilee/class12Android/app/src/main/java/mi/song/class12android/data/repository/SearchMovieRepositoryImpl.kt
> +class SearchMovieRepositoryImpl(val movieService: MovieService) : SearchMovieRepository {
92bfaf4e

2020-08-13 07:47 UTC, songmilee commented on class12/songmilee/class12Android/app/src/main/java/mi/song/class12android/app/MovieApplication.kt
> +            modules(listOf(movieSearchModule, networkModule))
24e0f1ee

2020-08-13 07:47 UTC, songmilee commented on class12/songmilee/class12Android/app/src/main/java/mi/song/class12android/app/MovieApplication.kt
> +            androidLogger(Level.DEBUG)
83949d0d

2020-08-13 07:47 UTC, songmilee commented on class12/songmilee/class12Android/app/src/main/java/mi/song/class12android/data/repository/SearchMovieRepositoryImpl.kt
> +class SearchMovieRepositoryImpl(val movieService: MovieService) : SearchMovieRepository {
92bfaf4e

2020-08-13 13:23 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-08-14 12:56 UTC, merged