HW7 : Koin 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #784
Opened 2020-08-12 06:11 UTC by pgshoot13

1. Add MainApplication.kt
2. Inject mainViewModel
3. Add Network/View Module

2020-08-12 06:12 UTC, pgshoot13 commented
아직 HW-6 과제가 마무리 되지 않아서
commit에 포함되어 있습니다.

2020-08-12 06:13 UTC, pgshoot13 commented
Koin에 대해 완벽 이해가 되지 않아서
이번과제에 부족함이 많습니다.
리뷰 부탁드립니다.

2020-08-12 15:36 UTC, DWL5 reviewed
저는 Hilt로 먼저해서.. 부랴부랴 코인 쪽보고 코멘트남겨드려요 ㅠ

2020-08-12 15:36 UTC, DWL5 commented on class12/pgshoot13/HyApplication/app/src/main/java/com/hyper/hyapplication/ui/MainActivity.kt
> +
https://start.insert-koin.io/#/quickstart/android-viewmodel

Koin Android Viewmodel 사용하면 inject()대신 viewmodel() 사용 가능합니다.

2020-08-12 15:36 UTC, DWL5 commented on class12/pgshoot13/HyApplication/app/src/main/java/com/hyper/hyapplication/module/NetworkModule.kt
> +            .build()
해당 코드들은 불필요해보입니다.
retrofit service를 주입받는 곳이 없기 때문입니다.

그리고 궁금한게 하나 있는데 
.addConverterFactory(get())
.addCallAdapterFactory(get())

해도 코드 잘 동작하나요?
get()으로 얻어올 때 얻어오는 부분이 정의되어 있지 않은것 같아서요..

2020-08-13 01:41 UTC, pgshoot13 reviewed
조금 의아한 부분이...
Class "MainApplication" is never used로
MainApplication는 manifest를 제외하고는 불리는게
없는것 같아서...근데 작동이 잘 하네요...

2020-08-13 01:41 UTC, pgshoot13 commented on class12/pgshoot13/HyApplication/app/src/main/java/com/hyper/hyapplication/module/NetworkModule.kt
> +            .build()
00a6efa9dd377c703b2c8e52600beae01e31e91b
NetworkModule을 전체 지웠습니다!
음...제가 봐도 그 부분이 이상했는데
아마 이 부분을 부르는 부분 자체가 없어서
그 상황이 발생하지 않아서 뻑이 나지 않은것 같습니다.

2020-08-13 01:41 UTC, pgshoot13 commented on class12/pgshoot13/HyApplication/app/src/main/java/com/hyper/hyapplication/ui/MainActivity.kt
> +
81c4232338fa53bbf2eba2ac91bdc22187f04020
감사합니다!
반영하였습니다.

2020-08-13 02:57 UTC, DWL5 commented
고생하셨습니다~

2020-08-13 13:25 UTC, sjjeong requested changes

2020-08-13 13:25 UTC, sjjeong commented on class12/pgshoot13/HyApplication/app/src/main/java/com/hyper/hyapplication/module/ViewModelModule.kt
> +    single<NaverRemoteDataSource> { NaverRemoteDataSourceImpl() }
RemoteDataSourceImpl이 NaverApi를 받도록 변경해주세요

2020-08-14 06:30 UTC, pgshoot13 commented on class12/pgshoot13/HyApplication/app/src/main/java/com/hyper/hyapplication/module/ViewModelModule.kt
> +    single<NaverRemoteDataSource> { NaverRemoteDataSourceImpl() }
single로 선언을 말씀하시는건가요?
아니면 NaverRemoteDataSourceImpl 클래스 내부에서 말씀하시는건가요?

2020-08-17 17:13 UTC, sjjeong commented on class12/pgshoot13/HyApplication/app/src/main/java/com/hyper/hyapplication/module/ViewModelModule.kt
> +    single<NaverRemoteDataSource> { NaverRemoteDataSourceImpl() }
이거 수정해주세요

2020-08-20 06:57 UTC, pgshoot13 commented on class12/pgshoot13/HyApplication/app/src/main/java/com/hyper/hyapplication/module/ViewModelModule.kt
> +    single<NaverRemoteDataSource> { NaverRemoteDataSourceImpl() }
d359e8d73eba39f901b1552d070284fd460f2122
죄송합니다ㅠㅠ
헤매다가 겨우 수정하였습니다...

2020-08-24 05:15 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-08-27 08:14 UTC, DWL5 approved these changes
### 수고하셨습니다

2020-09-04 00:46 UTC, merged