HW-7 koin
sjjeong/GoogryAndroidArchitecutreStudy pull request #786
Opened 2020-08-12 16:20 UTC by manjee-study

2020-08-13 07:43 UTC, songmilee requested changes

2020-08-13 07:43 UTC, songmilee commented on class12/manjee-study/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/MyApplication.kt
> +            androidLogger()
BuildConfig.Build일 때 사용하게 바꿔야 할 것 같아요

2020-08-13 07:43 UTC, songmilee commented on class12/manjee-study/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/di/NetworkModule.kt
> +    single { MovieRemoteService.movieApiService }
이거 선언만 하고 사용 안하신 거 같아요!

2020-08-13 10:10 UTC, manjee-study commented on class12/manjee-study/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/MyApplication.kt
> +            androidLogger()
어떤 의미인지 이해를 못 하겠습니다 ㅠㅠ

2020-08-13 10:13 UTC, songmilee commented on class12/manjee-study/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/MyApplication.kt
> +            androidLogger()
아 헙 제가 잘못 달았네요. Build가 아니라 BuildConfig.Debug일 때 android Logger를 사용하게 바꾸는거요!
`
if(BuildConfig.Debug)  
    androidLogger()
`

2020-08-13 10:26 UTC, manjee-study commented on class12/manjee-study/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/di/NetworkModule.kt
> +    single { MovieRemoteService.movieApiService }
MovieRemoteService.movieApiService 로 생성된 retrofit으로 MovieRemoteDataSource의 searchMovie가 동작하는데 이런식으로 사용하는게 아닌가요??ㅠㅠ

2020-08-13 10:46 UTC, songmilee commented on class12/manjee-study/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/di/NetworkModule.kt
> +    single { MovieRemoteService.movieApiService }
네트워크 모듈의 리턴 데이터 형식이 MovieRemoteDataSource이 아닌 줄 알고 헷갈렸네요ㅜㅜ 
이렇게 사용하면 될 거 같습니다!

2020-09-09 14:46 UTC, sjjeong commented
너무 오래되서 close 합니다

2020-09-09 14:46 UTC, closed without merging