HW - 6 Koin 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #79
Opened 2019-06-28 14:09 UTC by GongSulMin

2019-06-29 03:01 UTC, sabgilhun submitted a review, later dismissed
수고하셨습니다😁

2019-06-29 09:38 UTC, sjjeong requested changes

2019-06-29 09:38 UTC, sjjeong commented on gongsulmin/StudyGong/app/src/main/java/my/gong/studygong/di/NetworkModule.kt
> +    single { RetrofitProvider() }
UpbitRepository에서 저거를 내부에서 가져다가 쓰고있어요
upbitApi를 주입받아서 처리하도록 변경해주세요.

2019-06-30 14:42 UTC, GongSulMin commented on gongsulmin/StudyGong/app/src/main/java/my/gong/studygong/di/NetworkModule.kt
> +    single { RetrofitProvider() }
8c0e534

수정하였습니다!

2019-07-01 11:50 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-07-01 14:35 UTC, merged