initial commit & add gitignore
sjjeong/GoogryAndroidArchitecutreStudy pull request #792
Opened 2020-08-17 03:38 UTC by ddochi93

2020-08-17 17:20 UTC, sjjeong requested changes

2020-08-17 17:20 UTC, sjjeong commented on class13/ddochi93/app/.gitignore
> +# Created by https://www.toptal.com/developers/gitignore/api/androidstudio
해당 내용은 app모듈이 아닌 프로젝트의 .gitignore에 들어가야 합니다.

2020-08-19 12:59 UTC, ddochi93 commented on class13/ddochi93/app/.gitignore
> +# Created by https://www.toptal.com/developers/gitignore/api/androidstudio
넵 상위 폴더로 이동시켰습니다.

2020-08-19 14:31 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-08-19 22:37 UTC, merged