HW8 MultiModule
sjjeong/GoogryAndroidArchitecutreStudy pull request #793
Opened 2020-08-20 02:19 UTC by DWL5

MultiModule

2020-08-22 04:41 UTC, pgshoot13 commented
수고하셨습니다!

2020-08-22 04:41 UTC, pgshoot13 approved these changes

2020-08-25 14:36 UTC, sjjeong requested changes

2020-08-25 14:36 UTC, sjjeong commented on class12/DWL5/study/app/build.gradle
> +    implementation project(":study-library")
app 모듈 build.grade에서 필요없는 것들은 이동하면서 정리해주시면 됩니다.
retrofit 등등

2020-08-25 14:36 UTC, sjjeong commented on class12/DWL5/study/study-library/build.gradle
> +    implementation 'androidx.hilt:hilt-lifecycle-viewmodel:1.0.0-alpha02'
과제로 내드린 내용은 data 관련 내용들을 module로 빼는것이기 때문에 ui관련 라이브러리들은 추가하지 않아야합니다.

2020-08-27 08:37 UTC, DWL5 commented on class12/DWL5/study/study-library/build.gradle
> +    implementation 'androidx.hilt:hilt-lifecycle-viewmodel:1.0.0-alpha02'
72f92f3
반영했습니다

2020-08-27 08:37 UTC, DWL5 commented on class12/DWL5/study/app/build.gradle
> +    implementation project(":study-library")
72f92f3
반영했습니다

2020-08-27 11:06 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋
스터디 참여하시고 끝까지 과제 완수 하시느라 고생 많으셨어요!

2020-08-28 02:09 UTC, merged

2020-08-28 02:09 UTC, DWL5 commented
감사합니다~