HW-1 : 샘플 프로젝트 제작
sjjeong/GoogryAndroidArchitecutreStudy pull request #794
Opened 2020-08-23 06:46 UTC by CmplxN

RxJava와 Retrofit을 이용한 영화 검색 샘플 프로젝트 제작.
정확한 구현 스펙이 없어서? 누락된 사항이 있다면 알려주시면 감사하겠습니다.

2020-08-24 03:52 UTC, Hwangjunhong approved these changes
제가 잘못 이해하고있는 부분이 있다면 말씀해주세요! ㅎㅎ

2020-08-24 03:52 UTC, Hwangjunhong commented on class13/CmplxN/AAS/app/src/main/java/com/example/aas/ApiResult.kt
> +}
9e7ae585c3f6dde71a8823840ed0ffb04a7de626
데이터클래스는 최대한 분리하는게 좋다는 얘기를 들었습니다
저도 이유는 정확히 모르지만 유지보수나 가독성 때문인거같은데 어떻게 생각하시나요~?

2020-08-24 03:52 UTC, Hwangjunhong commented on class13/CmplxN/AAS/app/src/main/java/com/example/aas/MovieAdapter.kt
> +
601700ed77e4673f78b4f9c7a96ba75e66443994
getItemCount = movieList.size 로 바꿔도 좋을것 같습니다

2020-08-24 03:52 UTC, Hwangjunhong commented on class13/CmplxN/AAS/app/src/main/java/com/example/aas/MovieViewHolder.kt
> +}
601700ed77e4673f78b4f9c7a96ba75e66443994
conpanion object를 만든 이유가 있으신가요~?
오브젝트로 따로 빼지않고 class MovieViewHolder(view: View) 부분에서 바로 처리하는건 어떨까요?

2020-08-24 03:52 UTC, Hwangjunhong commented on class13/CmplxN/AAS/app/src/main/java/com/example/aas/MovieViewHolder.kt
> +	private val movieRating = view.findViewById<TextView>(R.id.tv_rating)
601700ed77e4673f78b4f9c7a96ba75e66443994
view.findViewById 로 일일이 초기화 하는건 비효율 적인거 같은데
fun bind 부분에서 apply나 with로 처리하는건 어떨까요?

2020-08-24 03:52 UTC, Hwangjunhong commented on class13/CmplxN/AAS/app/src/main/res/layout/activity_main.xml
> +		app:layout_constraintTop_toTopOf="parent">
79a628f84d2942ed801aa5d3bec7c6cf988c79b8
가이드라인이 있는데 레이아웃을 하나 더 쓰신 이유가 있을까요~?

2020-08-24 09:06 UTC, CmplxN commented on class13/CmplxN/AAS/app/src/main/java/com/example/aas/MovieViewHolder.kt
> +	private val movieRating = view.findViewById<TextView>(R.id.tv_rating)
말씀하신대로 해도  java code로 바꾸면 bind에서 findViewById 하지 않나요?
`LayoutContainer`는 experimental이라해서 안쓰긴 했는데...

2020-08-24 09:08 UTC, CmplxN commented on class13/CmplxN/AAS/app/src/main/res/layout/activity_main.xml
> +		app:layout_constraintTop_toTopOf="parent">
저는 (검색창 + 버튼)을 하나의 레이아웃으로 생각하고 구현했습니다.
굳이 레이아웃 없어도 만들 수는 있을 것 같습니다.

2020-08-24 09:11 UTC, CmplxN commented on class13/CmplxN/AAS/app/src/main/java/com/example/aas/MovieViewHolder.kt
> +}
저는 multitype의 뷰홀더를 다룰 때 
ViewHolder Factory를 만들어서 Factory 내부의 companion object로 ViewHolder를 만드는 편인데요
습관적으로 그렇게 한 것 같습니다. 생성자 부분에서 처리하는 방법을 한번 공부해보겠습니다.

2020-08-24 09:12 UTC, CmplxN commented on class13/CmplxN/AAS/app/src/main/java/com/example/aas/MovieAdapter.kt
> +
말씀하신대로 반환형은 redundant한 것 같습니다.

2020-08-24 09:26 UTC, CmplxN commented on class13/CmplxN/AAS/app/src/main/java/com/example/aas/ApiResult.kt
> +}
다른 글이나 컨벤션 등 찾아보고 반영하도록 하겠습니다.

2020-08-24 09:31 UTC, Hwangjunhong commented on class13/CmplxN/AAS/app/src/main/java/com/example/aas/MovieViewHolder.kt
> +	private val movieRating = view.findViewById<TextView>(R.id.tv_rating)
같은 효율을 보인다면 가독성이 우수한 쪽이 낫지 않을까 싶습니다!
코틀린에서 제공하는 코틀린 익스텐션이 있는데 보일러 플레이트 코드를 한번더 적게 되는거 같아서 의견 내봤습니다 !ㅎㅎ
LayoutContainer는 저도 검색해봐야겠네요

2020-08-24 09:44 UTC, Hwangjunhong commented on class13/CmplxN/AAS/app/src/main/res/layout/activity_main.xml
> +		app:layout_constraintTop_toTopOf="parent">
넵 view의 depth가 깊어지면 효율이 떨어져 의견 내봤습니다!
물론 현재는 한개라서 별차이가 없겠지만요! ㅋㅋ

2020-08-24 13:48 UTC, CmplxN commented on class13/CmplxN/AAS/app/src/main/res/layout/activity_main.xml
> +		app:layout_constraintTop_toTopOf="parent">
1cc6024

2020-08-24 13:50 UTC, CmplxN commented on class13/CmplxN/AAS/app/src/main/java/com/example/aas/ApiResult.kt
> +}
8b1834a
지금처럼 클래스 멤버가 적은게 아니라 많으면 확실히 분리하는게 좋을 것 같습니다.
분리하면 좋다고 한 글? 기억나시면 공유 가능할까요

2020-08-24 13:53 UTC, CmplxN commented on class13/CmplxN/AAS/app/src/main/java/com/example/aas/MovieViewHolder.kt
> +	private val movieRating = view.findViewById<TextView>(R.id.tv_rating)
bind에서 하면 bind 부를때마다 findViewById하므로 초기화 부분에 했습니다.
말씀하신대로 init에서 scope함수를 쓸 수 있지만 이경우 그게 줄수를 더 증가시키므로
아래 commit과 같이 수정했습니다.
2336827

2020-08-24 13:54 UTC, CmplxN commented on class13/CmplxN/AAS/app/src/main/java/com/example/aas/MovieViewHolder.kt
> +}
98f2471
단순한 뷰홀더는 말씀하신대로 하면 편할 것 같습니다.

2020-08-24 13:55 UTC, CmplxN commented on class13/CmplxN/AAS/app/src/main/java/com/example/aas/MovieAdapter.kt
> +
5ed8049

2020-08-24 14:01 UTC, Hwangjunhong commented on class13/CmplxN/AAS/app/src/main/java/com/example/aas/ApiResult.kt
> +}
저도 글로본게 아니라 어디서 흘려들어서요..ㅠ 죄송합니다

2020-08-24 14:36 UTC, Hwangjunhong approved these changes
바인드를 불러낼때마다 findViewById를 하는것을 방금 알았네요..! 좋은 정보 감사합니다 ㅎㅎ

2020-08-24 14:36 UTC, Hwangjunhong commented on class13/CmplxN/AAS/app/src/main/java/com/example/aas/RetrofitManager.kt
> +					.addHeader("X-Naver-Client-Secret", "sggbgPBFjF")
9e7ae58
헤더같은 경우는 보안상 중요하기 때문에 BuildConfig에 넣으시면 좋을것 같습니다!

2020-08-24 14:36 UTC, Hwangjunhong commented on class13/CmplxN/AAS/app/src/main/java/com/example/aas/MainActivity.kt
> +				.timeout(5000L, TimeUnit.MILLISECONDS)
79a628f84d2942ed801aa5d3bec7c6cf988c79b8
타임아웃 설정 같은 경우는 네트워크 모듈에서 설정해도 좋을것 같습니다

2020-08-24 14:36 UTC, Hwangjunhong commented on class13/CmplxN/AAS/app/src/main/java/com/example/aas/RetrofitManager.kt
> +			.addInterceptor(httpLoggingInterceptor)
9e7ae58
로깅 같은경우는 디버깅을 위한 것이기 때문에 디버그 모드일때만 작동하기 위한 조건문이 있으면 좋을것 같습니다

2020-08-25 12:08 UTC, CmplxN commented on class13/CmplxN/AAS/app/src/main/java/com/example/aas/RetrofitManager.kt
> +			.addInterceptor(httpLoggingInterceptor)
8d1da88

2020-08-25 12:09 UTC, CmplxN commented on class13/CmplxN/AAS/app/src/main/java/com/example/aas/MainActivity.kt
> +				.timeout(5000L, TimeUnit.MILLISECONDS)
67bd610

2020-08-25 12:09 UTC, CmplxN commented on class13/CmplxN/AAS/app/src/main/java/com/example/aas/RetrofitManager.kt
> +					.addHeader("X-Naver-Client-Secret", "sggbgPBFjF")
4cd6fa2

2020-08-25 12:09 UTC, CmplxN commented
반영하여 커밋하였습니다.

2020-08-25 12:55 UTC, Hwangjunhong commented
수고하셨습니다! LGTM!!

2020-08-25 14:57 UTC, sjjeong requested changes

2020-08-25 14:57 UTC, sjjeong commented on class13/CmplxN/AAS/app/src/main/java/com/example/aas/MainActivity.kt
> +		btn_request.setOnClickListener {
RxView.clicks(btn_request)로 변경하고 flatMap을 이용해서 Refrofit 요청하는 것도 체이닝해서 처리해보세요

2020-08-25 14:57 UTC, sjjeong commented on class13/CmplxN/AAS/app/src/main/java/com/example/aas/MainActivity.kt
> +				.addTo(compositeDisposable)
```kotlin
.subscribe({
	Toast.makeText(this, "Search Completed", Toast.LENGTH_SHORT).show()
	movieAdapter.setList(it.movies)
}, {
	Toast.makeText(this, "Network Error", Toast.LENGTH_LONG).show()
	it.printStackTrace()
})
.addTo(compositeDisposable)
```
이렇게 하면 더 좋을것 같네요

2020-08-25 14:57 UTC, sjjeong commented on class13/CmplxN/AAS/app/src/main/java/com/example/aas/Util.kt
> +fun interpretHtml(str: String): Spanned {
String extension function으로 만들어보고 함수명은 toHtml정도면 좋겠네요

2020-08-25 14:57 UTC, sjjeong commented on class13/CmplxN/AAS/app/src/main/java/com/example/aas/MovieViewHolder.kt
> +		}
ClickListener는 한번만 등록하면 되는 것이기 때문에 ViewHolder가 init되는 시점에 처리하면 됩니다.

2020-08-25 14:57 UTC, sjjeong commented on class13/CmplxN/AAS/app/src/main/java/com/example/aas/RetrofitManager.kt
> +	private val TIME_OUT = 5000L
private const val로 변경해주세요

2020-08-25 14:57 UTC, sjjeong commented on class13/CmplxN/AAS/app/src/main/java/com/example/aas/RetrofitManager.kt
> +			level = HttpLoggingInterceptor.Level.BODY
BuildConfig.DEBUG가 true일때만 BODY를 넣고 그렇지 않으면 NONE을 넣어주도록 해주세요 
하단에 addInterceptor에서 DEBUG체크하는 것은 제거해주세요

2020-08-25 14:57 UTC, sjjeong commented on class13/CmplxN/AAS/app/src/main/res/layout/item_movie.xml
> +	android:paddingVertical="10dp">
보통 4의배수나 8의 배수로 하는게 보편적입니다.

2020-08-25 14:57 UTC, sjjeong commented on class13/CmplxN/AAS/app/src/main/res/layout/item_movie.xml
> +		android:text="title"
tools:text로 변경해주세요
아래에 있는 내용들도 동일하게 반영해주세요

2020-08-26 14:59 UTC, CmplxN commented on class13/CmplxN/AAS/app/src/main/res/layout/item_movie.xml
> +		android:text="title"
497be8e tools:text로 변경했습니다.

2020-08-26 14:59 UTC, CmplxN commented on class13/CmplxN/AAS/app/src/main/res/layout/item_movie.xml
> +	android:paddingVertical="10dp">
35ed8c4 padding과 margin을 4의배수로 바꾸었습니다.

2020-08-26 14:59 UTC, CmplxN commented on class13/CmplxN/AAS/app/src/main/java/com/example/aas/RetrofitManager.kt
> +			level = HttpLoggingInterceptor.Level.BODY
4a95465 를 참조해주세요.

2020-08-26 14:59 UTC, CmplxN commented on class13/CmplxN/AAS/app/src/main/java/com/example/aas/RetrofitManager.kt
> +	private val TIME_OUT = 5000L
4e5e13a 변경했습니다.

2020-08-26 14:59 UTC, CmplxN commented on class13/CmplxN/AAS/app/src/main/java/com/example/aas/MovieViewHolder.kt
> +		}
181365d 로 변경했습니다.
`onCreateViewHolder`에서 `RxView.clicks` + `throttleFirst`를 사용했고, adapter 생성자에 `CompositeDisposable`을 넘겨 그걸 addTo했습니다.

2020-08-26 14:59 UTC, CmplxN commented on class13/CmplxN/AAS/app/src/main/java/com/example/aas/Util.kt
> +fun interpretHtml(str: String): Spanned {
0889443 로 해보았습니다.
혹시 언제 확장함수로 만드는 게 좋고, 언제 일반 함수로 만드는 게 좋은지 기준 같은게 있을까요?

2020-08-26 14:59 UTC, CmplxN commented on class13/CmplxN/AAS/app/src/main/java/com/example/aas/MainActivity.kt
> +				.addTo(compositeDisposable)
297b458 로 리포매팅 해보았습니다.

2020-08-26 14:59 UTC, CmplxN commented on class13/CmplxN/AAS/app/src/main/java/com/example/aas/MainActivity.kt
> +		btn_request.setOnClickListener {
529be24 로 변경해보았습니다.

2020-08-27 12:08 UTC, sjjeong commented on class13/CmplxN/AAS/app/src/main/java/com/example/aas/MainActivity.kt
> +				RetrofitManager.naverMoviesApi.getMovies(keyword.toString()).toObservable()
flatMapSingle로 하면 toObservable을 할 필요가 없습니다.

2020-08-27 12:08 UTC, sjjeong commented on class13/CmplxN/AAS/app/src/main/java/com/example/aas/Util.kt
> +fun interpretHtml(str: String): Spanned {
해당 클래스가 원래 가지고 있을 것 같은 함수들을 보통 확장함수로 만듭니다.

2020-08-27 12:12 UTC, sjjeong requested changes

2020-08-27 12:12 UTC, sjjeong commented on class13/CmplxN/AAS/app/src/main/java/com/example/aas/MovieAdapter.kt
> +				}.addTo(compositeDisposable)
라이브러리 개발자인 JakeWharton이 click자체는 dispose가 필요없다고 합니다.
해당 부분은 제거 해주고 생성자로 CompositeDisposable을 받는것도 제거하면 되겠네요
https://github.com/JakeWharton/RxBinding/issues/282

2020-08-27 12:12 UTC, sjjeong commented on class13/CmplxN/AAS/app/src/main/java/com/example/aas/RetrofitManager.kt
> +					HttpLoggingInterceptor.Level.NONE
{}를 추가해주세요 
https://developer.android.com/kotlin/style-guide#expressions

2020-08-27 12:17 UTC, sjjeong commented
인덴트가 생각보다 많이 밀려있는데 코드스타일 한번 확인해주세요

2020-08-27 13:18 UTC, CmplxN commented on class13/CmplxN/AAS/app/src/main/java/com/example/aas/RetrofitManager.kt
> +					HttpLoggingInterceptor.Level.NONE
752fe7d 에서 추가했습니다.

2020-08-27 13:20 UTC, CmplxN commented on class13/CmplxN/AAS/app/src/main/java/com/example/aas/MovieAdapter.kt
> +				}.addTo(compositeDisposable)
0e25646 에서 VH disposable add를 지웠습니다.

음,, 그러면 혹시 아래 clicks도 굳이 compositeDisposable에 추가하지 않아도 되는 것인가요?
```kotlin
RxView.clicks(btn_request)
	.flatMapSingle {
		val keyword = et_movie_name.text.also { et_movie_name.setText("") }
		et_movie_name.clearFocus()
		hideKeyboard(this, et_movie_name)
		RetrofitManager.naverMoviesApi.getMovies(keyword.toString())
	}
	.observeOn(AndroidSchedulers.mainThread())
	.subscribe({
		Toast.makeText(this, "Search Completed", Toast.LENGTH_SHORT).show()
		movieAdapter.setList(it.movies)
	}, {
		Toast.makeText(this, "Network Error", Toast.LENGTH_LONG).show()
		it.printStackTrace()
	}).addTo(compositeDisposable)
```
throttle로 체이닝하나, flatMapSingle로 체이닝하나 같은거겠죠?

2020-08-27 13:21 UTC, CmplxN commented
개인적으로 tab indent을 좋아했어서 tab이 커져있는 상태였네요.
tab indent를 끄고 전부 리포매팅했습니다.
f34d137

2020-08-28 12:49 UTC, sjjeong commented on class13/CmplxN/AAS/app/src/main/java/com/example/aas/MovieAdapter.kt
> +				}.addTo(compositeDisposable)
네 그렇습니다 이 경우는 다릅니다.

2020-08-28 12:51 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-08-28 14:15 UTC, merged