HW-1 : 영화 검색 프로젝트
sjjeong/GoogryAndroidArchitecutreStudy pull request #795
Opened 2020-08-23 13:07 UTC by HyeJeongHan

2020-08-27 13:02 UTC, sjjeong requested changes

2020-08-27 13:02 UTC, sjjeong commented on class13/HyeJeongHan/project/app/src/main/java/com/hjhan/hyejeong/MainActivity.kt
> +            layoutManager = LinearLayoutManager(context)
LayoutManager는 xml에서 추가 할 수 있습니다.

2020-08-27 13:02 UTC, sjjeong commented on class13/HyeJeongHan/project/app/src/main/java/com/hjhan/hyejeong/MainActivity.kt
> +        val api = serviceClient.createService(ApiInterface::class.java)
api는 매번 만들 필요가 없습니다.
다른분들 과제 하신거 참고해보세요

2020-08-27 13:02 UTC, sjjeong commented on class13/HyeJeongHan/project/app/src/main/java/com/hjhan/hyejeong/MovieAdapter.kt
> +class MovieAdapter(private val context: Context) :
context는 외부에서 받아올 필요가 없습니다.

2020-08-27 13:02 UTC, sjjeong commented on class13/HyeJeongHan/project/app/src/main/java/com/hjhan/hyejeong/MovieAdapter.kt
> +            Glide.with(context)
ImageView꺼를 사용하도록 해주세요

2020-08-27 13:02 UTC, sjjeong commented on class13/HyeJeongHan/project/app/src/main/java/com/hjhan/hyejeong/network/ServiceClient.kt
> +    private var mRetrofit: Retrofit? = null
m은 java에서 붙이던 스타일 입니다. 제거해주세요

2020-08-27 13:02 UTC, sjjeong commented on class13/HyeJeongHan/project/app/src/main/res/layout/activity_main.xml
> +            android:layout_width="match_parent"
weight를 주면 크기를 0dp로 변경해줘야합니다.

2020-08-27 13:57 UTC, HyeJeongHan commented on class13/HyeJeongHan/project/app/src/main/java/com/hjhan/hyejeong/MainActivity.kt
> +            layoutManager = LinearLayoutManager(context)
7e47d01

2020-08-27 13:57 UTC, HyeJeongHan commented on class13/HyeJeongHan/project/app/src/main/java/com/hjhan/hyejeong/MovieAdapter.kt
> +class MovieAdapter(private val context: Context) :
b8925fa

2020-08-27 13:58 UTC, HyeJeongHan commented on class13/HyeJeongHan/project/app/src/main/res/layout/activity_main.xml
> +            android:layout_width="match_parent"
b6d35ed

2020-08-27 13:58 UTC, HyeJeongHan commented on class13/HyeJeongHan/project/app/src/main/java/com/hjhan/hyejeong/MainActivity.kt
> +        val api = serviceClient.createService(ApiInterface::class.java)
236abcc

2020-08-27 13:58 UTC, HyeJeongHan commented on class13/HyeJeongHan/project/app/src/main/java/com/hjhan/hyejeong/network/ServiceClient.kt
> +    private var mRetrofit: Retrofit? = null
5befb69

2020-08-27 13:59 UTC, HyeJeongHan commented on class13/HyeJeongHan/project/app/src/main/java/com/hjhan/hyejeong/MovieAdapter.kt
> +            Glide.with(context)
라이브러리를 사용하지 않는 방향으로 가야하는건가요?

2020-08-27 14:02 UTC, sjjeong commented on class13/HyeJeongHan/project/app/src/main/java/com/hjhan/hyejeong/MovieAdapter.kt
> +            Glide.with(context)
context대신에 ImageView를 넣으면 됩니다.

2020-08-27 14:03 UTC, sjjeong commented on class13/HyeJeongHan/project/app/src/main/java/com/hjhan/hyejeong/MovieAdapter.kt
> +            Glide.with(context)
@HyeJeongHan

2020-08-28 10:00 UTC, HyeJeongHan commented on class13/HyeJeongHan/project/app/src/main/java/com/hjhan/hyejeong/MovieAdapter.kt
> +            Glide.with(context)
e14cdd9

2020-08-28 12:52 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-08-29 11:32 UTC, ddochi93 approved these changes

2020-08-29 11:32 UTC, ddochi93 commented on class13/HyeJeongHan/project/app/src/main/java/com/hjhan/hyejeong/MainActivity.kt
> +        })
onFailure에서 실패처리로 Toast같은 거 띄워주면 좋을것같습니다

2020-08-29 14:19 UTC, HyeJeongHan commented on class13/HyeJeongHan/project/app/src/main/java/com/hjhan/hyejeong/MainActivity.kt
> +        })
862d557

2020-08-30 10:49 UTC, merged