HW-1 : 샘플 프로젝트 제작
sjjeong/GoogryAndroidArchitecutreStudy pull request #796
Opened 2020-08-23 13:14 UTC by Hwangjunhong

네이버 검색 api를 이용한 영화 검색 프로젝트
Retrofit을 이용했습니다
저도 누락된 스펙 있으면 알려주시면 감사하겠습니다!

2020-08-23 16:04 UTC, CmplxN requested changes
석준님이 알려주신 컨벤션 맞추기?가 되어있지 않은 것 같습니다.
그것 외에는 커멘트를 달았습니다.
제가 잘못 알고 있었던거나 잘못 이해한 점이 있으면 알려주시면 감사하겠습니다.

2020-08-23 16:04 UTC, CmplxN commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/MovieAdapter.kt
> +    }
애초에 `holder`의 type을 `MovieViewHolder`로 하면 typecasting을 안해도 되지 않을까요?

2020-08-23 16:04 UTC, CmplxN commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/MovieViewHolder.kt
> +                this.context.startActivity(intent)
여기의 this는 있는거랑 없는거랑 차이가 없지 않을까요?

2020-08-23 16:04 UTC, CmplxN commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/network/RetrofitCreator.kt
> +}
object를 사용해서 singleton으로 하는게 좋지 않을까요?

2020-08-23 16:04 UTC, CmplxN commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/MainActivity.kt
> +        createRetrofit().getMovies("baPVy6Scd6jvsqAsrrHu", "lCfi3Abd26", query).enqueue(
매번 `NaverMovieApi`를 만들면 비효율적일 것 같습니다.

2020-08-23 16:04 UTC, CmplxN commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/MainActivity.kt
> +            if(edit_search.text.toString().isEmpty()){
빈칸(스페이스)만 치고 버튼을 눌러도 동작하는데
`isBlank()`를 쓰는 것도 괜찮을 것 같아요.

2020-08-23 16:04 UTC, CmplxN commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/MainActivity.kt
> +                        if (isSuccessful && body != null) { body.items.let { adapter.addItem(it) }}
body에 대한 null check가 되었는데
```kotlin
adapter.addItem(body.items)
```
대신 let을 이용한 이유가 따로 있나요?

2020-08-23 16:04 UTC, CmplxN commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/MainActivity.kt
> +            object : retrofit2.Callback<MovieResultData> {
이거도 매번 익명객체가 생성되어 비효율적일 것 같습니다.

2020-08-23 16:04 UTC, CmplxN commented on class13/Hwangjunhong/ArchitectureStudy/app/build.gradle
> +    annotationProcessor 'com.github.bumptech.glide:compiler:4.11.0'
혹시 kapt대신 annotationProcessor를 쓰는 이유가 따로 있나요?

2020-08-24 05:56 UTC, Hwangjunhong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/MainActivity.kt
> +            object : retrofit2.Callback<MovieResultData> {
익명클래스가 매번 생성되어 메모리릭이 발생하기 때문에 비효율적인건가요~?

2020-08-24 08:58 UTC, CmplxN commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/MainActivity.kt
> +            object : retrofit2.Callback<MovieResultData> {
제가 알기론 더이상 참조할 수 없으면 gc대상이 됩니다.
이경우 한번 검색하고 참조를 잃으므로 gc대상이 되어 메모리 릭은 아닌 것 같습니다.

대신 생성하지 않아도 되는 객체를 생성하게 되는거죠.
검색을 100번하면 객체가 100번 생성되는? 그것도 다른 위치에 말이죠(gc유발)

2020-08-24 09:08 UTC, Hwangjunhong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/MainActivity.kt
> +            object : retrofit2.Callback<MovieResultData> {
아아 이해했습니다! 
말씀은 이해했으나 어떻게하면 익명클래스를 매번 생성하지 않을수 있는지 알수 있을까요??
retrofit에서 기본제공하는 인터페이스가 이런 형태인데 어떤 방법이 있을까요!?
아무리 검색해봐도 잘 모르겠네요ㅠ

2020-08-24 09:20 UTC, CmplxN commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/MainActivity.kt
> +            object : retrofit2.Callback<MovieResultData> {
adapter를 접근할 수 있는 곳(예를 들면 activity 내부)에서 만들면 되지 않을까요
예를 들면,
```kotlin
private val callBack = object : retrofit2.Callback<MovieResultData> { ... }
```

2020-08-24 09:25 UTC, CmplxN commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/MainActivity.kt
> +            object : retrofit2.Callback<MovieResultData> {
애초에 이앱이 여러번 검색을 하려는 것은 아니니까 굳이 반영하실 필요는 없습니다.
의견 제시? 토론?이에요

2020-08-24 09:32 UTC, Hwangjunhong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/MainActivity.kt
> +            object : retrofit2.Callback<MovieResultData> {
아닙니다 항상 최선의 상황을 생각해야지요ㅋㅋ 마구마구 날려주세요!
말씀해주신것을 보니 이해됐습니다. 반영해보도록 하겠습니다 감사합니다!

2020-08-24 11:55 UTC, Hwangjunhong commented
말씀해주신 부분 수정해서 반영하였습니다!

2020-08-24 13:58 UTC, CmplxN commented
커멘트 관련 수정사항이 있으면
reply에 commit 번호를 적어주면 좋을 것 같습니다.
[링크](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/blob/master/sjjeong/README.md#pr-commit)

2020-08-24 14:02 UTC, Hwangjunhong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/MovieAdapter.kt
> +    }
7bdfceb

2020-08-24 14:02 UTC, Hwangjunhong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/MovieViewHolder.kt
> +                this.context.startActivity(intent)
63a89f9

2020-08-24 14:03 UTC, Hwangjunhong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/network/RetrofitCreator.kt
> +}
0bd55e3

2020-08-24 14:03 UTC, Hwangjunhong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/MainActivity.kt
> +        createRetrofit().getMovies("baPVy6Scd6jvsqAsrrHu", "lCfi3Abd26", query).enqueue(
0bd55e3

2020-08-24 14:04 UTC, Hwangjunhong commented on class13/Hwangjunhong/ArchitectureStudy/app/build.gradle
> +    annotationProcessor 'com.github.bumptech.glide:compiler:4.11.0'
59c4bd8

2020-08-24 14:33 UTC, CmplxN requested changes
unused import 몇개만 처리하시면 될 것 같습니다.

2020-08-24 14:33 UTC, CmplxN commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/network/RetrofitCreator.kt
> +        }
생각해보니 scope function을 써서 할 수도 있었네요. 감사합니다.

2020-08-24 14:33 UTC, CmplxN commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/MainActivity.kt
> +import com.hong.architecturestudy.Constants.BASE_URL
쓰이지 않는 import 같습니다. unused import를 없애주세요.

2020-08-24 14:33 UTC, CmplxN commented on class13/Hwangjunhong/ArchitectureStudy/app/build.gradle
> +        buildConfigField "String", "NAVER_CLIENT_SECRET", '\"lCfi3Abd26\"'
이렇게도 설정할 수 있군요. 배웠습니다. ㅎㅎ

2020-08-24 14:33 UTC, CmplxN commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/MovieViewHolder.kt
> +import kotlinx.android.synthetic.main.activity_main.*
unused import입니다.

2020-08-24 14:33 UTC, CmplxN commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/network/NaverMovieApi.kt
> +import retrofit2.http.Header
unused import입니다.

2020-08-24 14:38 UTC, Hwangjunhong commented on class13/Hwangjunhong/ArchitectureStudy/app/build.gradle
> +        buildConfigField "String", "NAVER_CLIENT_SECRET", '\"lCfi3Abd26\"'
도움이 되셨다니 다행입니다!!ㅎㅎ

2020-08-24 15:55 UTC, Hwangjunhong commented
106aed0
unused import 모두 제거후 ViewHolder 부분도 수정했습니다
감사합니다 정태님

2020-08-25 12:12 UTC, CmplxN reviewed
MovieAdapter 부분 reformatting만 하시면 될 것 같아요.
단축키를 활용해서 하면 쉽게 할 수 있을 것 같습니다.

2020-08-25 12:12 UTC, CmplxN commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/MovieAdapter.kt
> +    fun addItem(item: List<MovieData>){
이 라인이 아직 컨벤션에 맞지 않는 것 같습니다. 리포매팅 해주세요.

2020-08-25 12:53 UTC, Hwangjunhong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/MovieAdapter.kt
> +    fun addItem(item: List<MovieData>){
20a25f0
반영하였습니다!

2020-08-25 12:55 UTC, CmplxN approved these changes
LGTM입니다.

2020-08-25 15:34 UTC, sjjeong requested changes

2020-08-25 15:34 UTC, sjjeong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ext/FuncExt.kt
> +fun htmlToText(str: String): Spanned {
String extension function으로 변경해보세요
함수명은 toHtml정도면 됩니다.

2020-08-25 15:34 UTC, sjjeong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ext/ImageViewExt.kt
> +fun ImageView.loadGlideImageView(imageUrl: String) {
함수명에 특정 라이브러리가 들어가는건 좋지 않기 때문에 Glide는 빼면 좋겠습니다.
추후 Glide를 다른 3rd party library로 변경했을 때 함수명이 바뀌는 일이 생깁니다.

2020-08-25 15:34 UTC, sjjeong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/network/RetrofitCreator.kt
> +            this.setLevel(HttpLoggingInterceptor.Level.BODY)
이렇게하면 밑에 BODY만 적용되지 않나요?

2020-08-25 15:34 UTC, sjjeong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/MainActivity.kt
> +        rv_movies_list.setItemViewCacheSize(adapter.itemCount)
이렇게하면 itemViewCacheSize는 항상 0이지 않나요?
adapter.itemCount만큼 CacheSize를 두는것도 좋지 않습니다.
기본값을 유지하도록 set하는 코드는 제거해주세요

2020-08-25 15:34 UTC, sjjeong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/MainActivity.kt
> +    private val movieCallBack = object : retrofit2.Callback<MovieResultData> {
property는 함수 위로 올려주세요

2020-08-25 15:34 UTC, sjjeong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/MovieAdapter.kt
> +    fun addItem(item: List<MovieData>) {
함수명을 보면 `한개의 아이템을 추가`인데 실제 동작은 resetAll or replaceAll입니다.
적절한 함수명으로 변경해주세요

2020-08-25 15:34 UTC, sjjeong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/MovieViewHolder.kt
> +        }
ClickListener는 한번만 등록하면 되는 것이기 때문에 ViewHolder가 init되는 시점에 처리하면 됩니다.

2020-08-25 18:02 UTC, Hwangjunhong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ext/ImageViewExt.kt
> +fun ImageView.loadGlideImageView(imageUrl: String) {
4bae593
변경하였습니다!

2020-08-25 18:03 UTC, Hwangjunhong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ext/FuncExt.kt
> +fun htmlToText(str: String): Spanned {
2b2cfdf
변경하여 적용해 보았습니다!

2020-08-25 18:04 UTC, Hwangjunhong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/network/RetrofitCreator.kt
> +            this.setLevel(HttpLoggingInterceptor.Level.BODY)
1d3fd1e
찾아보니 BODY안에 HEADERS의 내용이 포함되어있어 HEADERS를 삭제하고 코드 수정하였습니다!

2020-08-25 18:04 UTC, Hwangjunhong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/MainActivity.kt
> +        rv_movies_list.setItemViewCacheSize(adapter.itemCount)
7adf5a1
제거했습니다!

2020-08-25 18:04 UTC, Hwangjunhong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/MainActivity.kt
> +    private val movieCallBack = object : retrofit2.Callback<MovieResultData> {
7adf5a1
적용하였습니다!

2020-08-25 18:05 UTC, Hwangjunhong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/MovieAdapter.kt
> +    fun addItem(item: List<MovieData>) {
7adf5a1
s만 붙여서 items도 괜찮은가요..? addAll 로 하려다가 함수명이랑 일치해서 items로 했습니다!

2020-08-25 18:07 UTC, Hwangjunhong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/MovieViewHolder.kt
> +        }
7adf5a1
이렇게 적용해봤습니다!

2020-08-27 12:14 UTC, sjjeong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ext/FuncExt.kt
> +        Html.fromHtml(this)
{}를 추가해주세요
https://developer.android.com/kotlin/style-guide#expressions

2020-08-27 12:14 UTC, sjjeong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ext/FuncExt.kt
> +fun htmlToText(str: String): Spanned {
해당 함수는 제거해주세요

2020-08-27 12:14 UTC, sjjeong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/MainActivity.kt
> +        rv_movies_list.setItemViewCacheSize(adapter.itemCount)
@Hwangjunhong 
커밋 아이디가 잘못 된것 같습니다.

2020-08-27 12:16 UTC, sjjeong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/MovieAdapter.kt
> +    fun addItem(item: List<MovieData>) {
addItems()는 `여러개의 아이템을 추가`인데 지금 하는 동작은 `기존 아이템을 제거하고 새로운 아이템으로 덮어씌우는 동작`입니다.

2020-08-27 12:46 UTC, Hwangjunhong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/MainActivity.kt
> +        rv_movies_list.setItemViewCacheSize(adapter.itemCount)
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/796#commitcomment-41815360
변경하였습니다!

2020-08-27 13:07 UTC, Hwangjunhong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/MovieAdapter.kt
> +    fun addItem(item: List<MovieData>) {
b0c57d2
setData로 수정하였습니다!

2020-08-27 13:08 UTC, Hwangjunhong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ext/FuncExt.kt
> +        Html.fromHtml(this)
826c5a6
추가하였습니다!

2020-08-27 13:08 UTC, Hwangjunhong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ext/FuncExt.kt
> +fun htmlToText(str: String): Spanned {
733a4c7
제거하였습니다!

2020-08-28 12:53 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋
1줄의 자잘한 커밋이라도 나눠서 하는 습관을 가져주세요

2020-08-28 13:19 UTC, merged