Class13/sangmeebee
sjjeong/GoogryAndroidArchitecutreStudy pull request #798
Opened 2020-08-24 01:49 UTC by Sangmeebee

네이버 검색 api를 이용한 영화 검색 프로젝트
Retrofit을 이용했습니다
저도 누락된 스펙 있으면 알려주시면 감사하겠습니다!

2020-08-24 17:07 UTC, camai reviewed
작성하신 Commit별 코드를 보고 리뷰를 남깁니다.

먼저, 전체적인 코드 리뷰 내용은 수정한 내역에 대한 설명이 추가가 필요, 작성하신 코드 중 작성한 이유에 설명이 추가가 필요할 것 같다고 생각듭니다.

자세한 사항은 아래 내용을 참고 해주세요. 
1. http 통신 구현( 0796a6d ) 
Movie 검색 결과를 리턴 받는 모델을 클래스별 (Movie, Item) 구분하셨는데 혹시 이유가 있을까요?
 결과를 받는 모델로 데이터 내용이 다르지만 사용의도가 있으셔서 클래스 생성하여 나누셨던 것 같습니다.
개발한 분은 알겠지만 이 내용을 모르는 사람이 봤을 땐 의도를 알기 어렵다고 느꼈습니다. 
 Item이 어떤 데이터 모델인지 어디서 사용하는지 확인하러 직접 봐야되는 수고가 발생되는것 같습니다.

따라서, 구분하신 이유가 있으시면 Movie, Item 모델의 역할과 이유를 주석으로 설명으로 표현하시면 내용 파악하는데 좋을 것 같습니다.

2. ( 38850c2,  a77e622)retrofit 수정이라고 올려주셨는데 어떤 내용을 수정 하셨는지 코드를 확인해야지만 볼 수 있었습니다.
따라서, 어떤 내용을 수정 하셨는지를 간략하게 라도 적어주시면 더 좋을 것 같다고 느꼈습니다.

이외에는 코드 상으로는 좀 더 추가되는 내용이 있다면 리뷰 남기도록 하겠습니다.

2020-08-25 03:27 UTC, Sangmeebee commented
6261204, eef58b6 
commit message 수정하였습니다.  rebase 과정에서 하위 commit들도 rebase되었습니다...ㅎ 협업이 아니여서 별다른 문제는 없을 것 같습니다.

6b1154e
관련이 있는 모델은 하나로 합치는게 맞겠다고 동의하여 하나로 합쳤습니다.

2020-08-25 05:32 UTC, camai commented on class13/Sangmeebee/MyProject/app/src/main/java/com/example/myproject/MainActivity.kt
> +
마지막으로 Activity onCreate() 에서 view 객체 초기화는 따로 함수를 만들어서 분리하시는건 어떨까 합니다.
현재는 사용되는 view 객체가 적어서 상관 없을것 같지만 
어떤 경우에는 view 객체 초기화 할 작업 코드가 많아지면 해당 코드로 인해 가독성이 떨어지지 않을까 생각듭니다.
apply 를 활용하시는 것도 좋을 것 같습니다.

2020-08-25 07:05 UTC, Sangmeebee commented on class13/Sangmeebee/MyProject/app/src/main/java/com/example/myproject/MainActivity.kt
> +
해당내용 수정했습니다! 감사합니다
b6443c7

2020-08-25 07:13 UTC, camai commented on class13/Sangmeebee/MyProject/app/src/main/java/com/example/myproject/MainActivity.kt
> +
고생하셨습니다~

2020-08-25 08:32 UTC, camai commented
코드 수정하시느라 고생하셨습니다~
다음 스탭 진행하시면 됩니다~

2020-08-25 09:15 UTC, camai approved these changes
수정한 내역 모두 확인하였습니다. 
고생하셨습니다. 다음 스탭 진행하시면 됩니다.

2020-08-27 12:42 UTC, sjjeong requested changes

2020-08-27 12:42 UTC, sjjeong commented on class13/Sangmeebee/MyProject/app/src/main/java/com/example/myproject/MainActivity.kt
> +    val movieAdapter = MovieAdapter(this, movies)
private 추가해주세요
public일 필요없는 함수와 속성들을 전부 private으로 변경해주세요

2020-08-27 12:42 UTC, sjjeong commented on class13/Sangmeebee/MyProject/app/src/main/java/com/example/myproject/MainActivity.kt
> +            recyclerview.layoutManager = LinearLayoutManager(context)
layoutManager는 xml에서 추가 할 수 있습니다.

2020-08-27 12:42 UTC, sjjeong commented on class13/Sangmeebee/MyProject/app/src/main/java/com/example/myproject/MainActivity.kt
> +            addItemDecoration(DividerItemDecoration(context, LinearLayoutManager(context).orientation))
Orientation은 객체를 만들어서 가져올 필요 없이 RecyclerView.VERTICAL 를 set하시면 됩니다.

2020-08-27 12:42 UTC, sjjeong commented on class13/Sangmeebee/MyProject/app/src/main/java/com/example/myproject/MainActivity.kt
> +                    if (movies.size == 0) {
movies.isEmpty()로 변경하시면 됩니다.

2020-08-27 12:42 UTC, sjjeong commented on class13/Sangmeebee/MyProject/app/src/main/java/com/example/myproject/MainActivity.kt
> +                    val movies = ArrayList<Items>(response.body()!!.items)
!! 보다 ?를 사용해서 null handling 하도록 해주세요

2020-08-27 12:42 UTC, sjjeong commented on class13/Sangmeebee/MyProject/app/src/main/java/com/example/myproject/MovieAdapter.kt
> +            .into(holder.getImage()!!)
이 작업들은 ViewHolder안에 item을 파라미터로 받는 함수를 만들어서 처리하도록 해주세요

2020-08-27 12:42 UTC, sjjeong commented on class13/Sangmeebee/MyProject/app/src/main/java/com/example/myproject/MovieAdapter.kt
> +        }
ClickListener는 한번만 set하면 되기 때문에 onCreateViewHolder에서 해주면 됩니다.

2020-08-27 12:42 UTC, sjjeong commented on class13/Sangmeebee/MyProject/app/src/main/java/com/example/myproject/MovieAdapter.kt
> +    }
nested class는 클래스 내부에서 companion object 바로 위에 위치하면됩니다.
현재는 companion object가 없으니 맨 아래로 내려주시면 됩니다.

2020-08-27 12:42 UTC, sjjeong commented on class13/Sangmeebee/MyProject/app/src/main/java/com/example/myproject/retrofit/RetrofitClient.kt
> +    private val mOkHttpClient = builder.build()
m은 빼주세요

2020-08-27 12:42 UTC, sjjeong commented on class13/Sangmeebee/MyProject/app/src/main/java/com/example/myproject/retrofit/model/Movie.kt
> +)
파일을 별도로 만들거나 nested class로 해주세요

2020-08-29 15:08 UTC, Sangmeebee commented on class13/Sangmeebee/MyProject/app/src/main/java/com/example/myproject/MainActivity.kt
> +    val movieAdapter = MovieAdapter(this, movies)
eafc85f

2020-08-29 15:09 UTC, Sangmeebee commented on class13/Sangmeebee/MyProject/app/src/main/java/com/example/myproject/MainActivity.kt
> +            addItemDecoration(DividerItemDecoration(context, LinearLayoutManager(context).orientation))
6f7dc9a

2020-08-29 15:09 UTC, Sangmeebee commented on class13/Sangmeebee/MyProject/app/src/main/java/com/example/myproject/MainActivity.kt
> +            recyclerview.layoutManager = LinearLayoutManager(context)
e4c16f5

2020-08-29 15:09 UTC, Sangmeebee commented on class13/Sangmeebee/MyProject/app/src/main/java/com/example/myproject/MainActivity.kt
> +                    if (movies.size == 0) {
b6467d8

2020-08-29 15:09 UTC, Sangmeebee commented on class13/Sangmeebee/MyProject/app/src/main/java/com/example/myproject/MainActivity.kt
> +                    val movies = ArrayList<Items>(response.body()!!.items)
f6afe6a

2020-08-29 15:10 UTC, Sangmeebee commented on class13/Sangmeebee/MyProject/app/src/main/java/com/example/myproject/MovieAdapter.kt
> +            .into(holder.getImage()!!)
8cd5dbe

2020-08-29 15:10 UTC, Sangmeebee commented on class13/Sangmeebee/MyProject/app/src/main/java/com/example/myproject/MovieAdapter.kt
> +        }
ba584e3

2020-08-29 15:10 UTC, Sangmeebee commented on class13/Sangmeebee/MyProject/app/src/main/java/com/example/myproject/MovieAdapter.kt
> +    }
add1115

2020-08-29 15:11 UTC, Sangmeebee commented on class13/Sangmeebee/MyProject/app/src/main/java/com/example/myproject/retrofit/RetrofitClient.kt
> +    private val mOkHttpClient = builder.build()
c839eff

2020-08-29 15:11 UTC, Sangmeebee commented on class13/Sangmeebee/MyProject/app/src/main/java/com/example/myproject/retrofit/model/Movie.kt
> +)
65774d1

2020-08-30 03:48 UTC, sjjeong approved these changes
Duplicate of #

2020-08-30 03:57 UTC, merged