HW-2 : MODEL 구현
sjjeong/GoogryAndroidArchitecutreStudy pull request #801
Opened 2020-08-31 19:42 UTC by Hwangjunhong

많이 부족하네요ㅠ
잘못된 부분이나 수정할만한 부분이 보이면 말씀해주시면 감사하겠습니다!

2020-09-01 10:48 UTC, Hwangjunhong commented
과제가 DialogFragment를 이용하는 것인지 방금 확인하여서 수정해서 다시 올립니다!

2020-09-01 15:01 UTC, CmplxN requested changes
잘못 이해한 점 있으면 알려주시면 감사하겠습니다.
저는 바빠서 언제 올릴지 모르겠네요 ㅠㅠ

2020-09-01 15:01 UTC, CmplxN commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/res/layout/item_movie_search_list.xml
> +        android:textSize="20sp"
이것들 정렬이 안되어서 리포매팅을 하면 순서가 바뀔 것 같습니다.

2020-09-01 15:01 UTC, CmplxN commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/res/layout/dialog_fragment_movie_list.xml
> +        app:layoutManager="androidx.recyclerview.widget.LinearLayoutManager"/>
이것도 리포매팅 시키면 레이아웃 매니저가 위로 가는 것 같습니다.

2020-09-01 15:01 UTC, CmplxN commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/MovieListDialogFragment.kt
> +    }
이걸 `companion object`로 만들고 `MainActivity`에서는 
```kotlin
private val movieListDialogFragment = MovieListDialogFragment.newInstance()
```
이렇게 하는게 좋을 것 같습니다.
지금처럼하면 인스턴스 두개 생깁니다.

2020-09-01 15:01 UTC, CmplxN commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/MainActivity.kt
> +    lateinit var titleListener: ((String) -> Unit)
typealias를 써도 괜찮을 것 같습니다.

2020-09-01 15:01 UTC, CmplxN commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/MovieListDialogFragment.kt
> +            (requireActivity() as MainActivity).titleListener.invoke(it)
타입캐스팅해서 액티비티를 접근해서 쓰는 것 보다 `MovieAdapter`처럼 멤버로 받던가 하는게 낫지 않을까요?
`MovieListDialogFragment` 참조가 필요한거는 `MovieListDialogFragment`서 하구요.

2020-09-01 15:01 UTC, CmplxN commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/MainActivity.kt
> +                }, {
it 두개가 타입이 달라서 알 수 있지만도, 이름을 지어주는 건 어떨까요?

2020-09-01 15:01 UTC, CmplxN commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/MovieSearchListViewHolder.kt
> +    private var movieTitle = itemView.tv_movie_title
val 대신 var를 쓴 이유가 있나요?

2020-09-01 15:01 UTC, CmplxN commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/MovieSearchListAdapter.kt
> +    lateinit var onClick: ((String) -> Unit)
이건 의견인데, onClick은 mandatory 멤버라고 생각해서 생성자로 받는게 좋다고 생각합니다. 어떤게 맞는지는 잘 모르겠네요.

2020-09-01 15:01 UTC, CmplxN commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/MovieListDialogFragment.kt
> +        val rvSearchItem = view?.findViewById<RecyclerView>(R.id.rv_search_list)
참고로 저는 처음에 rcv말고 [이거](https://developer.android.com/guide/topics/ui/dialogs?hl=en#AddingAList) 생각했네요.

2020-09-01 15:01 UTC, CmplxN commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/MainActivity.kt
> +    private val repositoryDataSourceImpl: RepositoryDataSourceImpl by lazy {
인터페이스를 쓰는 만큼 type을 인터페이스로 하면 어떨까요?

2020-09-01 15:01 UTC, CmplxN commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/data/source/local/LocalDataSourceImpl.kt
> +        CoroutineScope(Dispatchers.IO).async {
질문 : launch대신 async를 쓴 이유가 있나요?

2020-09-01 15:01 UTC, CmplxN commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/MainActivity.kt
> +            }, this)
이 부분은 DialogFragment에도 있고, Activity에도 있습니다.

2020-09-01 15:01 UTC, CmplxN commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/MovieListDialogFragment.kt
> +        repositoryDataSourceImpl.loadData(this, Observer {
의견 : 개인적으론 `loadData()`로 LiveData를 받아오고 Fragment에서 observe를 거는게 어떤가 합니다.

2020-09-01 15:01 UTC, CmplxN commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/data/source/local/entity/MovieInfo.kt
> +}
질문 : 보조생성자 따로 빼지 않아도 주생성자에서 기본값 설정을 할 수 있지 않나요?

2020-09-01 15:01 UTC, CmplxN commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/data/source/local/MovieDatabase.kt
> +        fun getInstance(context: Context): MovieDatabase? {
volatile를 쓰는 singleton도 한번 찾아보면 좋을 것 같아요.

2020-09-01 15:03 UTC, CmplxN commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/res/layout/item_movie_search_list.xml
> +        android:textSize="20sp"
+item_movie_list도 리포매팅 걸리는 것 같습니다.

2020-09-02 15:26 UTC, Hwangjunhong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/MovieSearchListViewHolder.kt
> +    private var movieTitle = itemView.tv_movie_title
37519ad
TYPO!

2020-09-02 15:26 UTC, Hwangjunhong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/MainActivity.kt
> +            }, this)
9b8c0bc
Activity 코드 삭제하였습니다!

2020-09-02 15:28 UTC, Hwangjunhong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/MovieListDialogFragment.kt
> +        repositoryDataSourceImpl.loadData(this, Observer {
11759fb
적용하였습니다!

2020-09-02 15:28 UTC, Hwangjunhong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/MainActivity.kt
> +    lateinit var titleListener: ((String) -> Unit)
b05135b
이런 느낌인가요..?

2020-09-02 15:28 UTC, Hwangjunhong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/data/source/local/MovieDatabase.kt
> +        fun getInstance(context: Context): MovieDatabase? {
65ccf98
감사합니다 좋은공부 됐습니다!

2020-09-02 15:29 UTC, Hwangjunhong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/MainActivity.kt
> +                }, {
1f4aab6
수정하였습니다!

2020-09-02 15:30 UTC, Hwangjunhong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/MovieListDialogFragment.kt
> +    }
3766afe
적용하였습니다!

2020-09-02 15:31 UTC, Hwangjunhong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/res/layout/item_movie_search_list.xml
> +        android:textSize="20sp"
623ded2
커밋전에 리포매팅 설정이 안돼있었네요ㅜ 설정했습니다!

2020-09-02 15:31 UTC, Hwangjunhong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/res/layout/dialog_fragment_movie_list.xml
> +        app:layoutManager="androidx.recyclerview.widget.LinearLayoutManager"/>
3959ad6

2020-09-02 15:32 UTC, Hwangjunhong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/data/source/local/LocalDataSourceImpl.kt
> +        CoroutineScope(Dispatchers.IO).async {
a826a3e
코루틴을 처음 공부하면서 써보느라 deferred 적용해보다가 못바꿨네요
수정하였습니다!

2020-09-02 15:32 UTC, Hwangjunhong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/data/source/local/entity/MovieInfo.kt
> +}
5fe3164
수정하였습니다!

2020-09-02 15:33 UTC, Hwangjunhong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/MainActivity.kt
> +    private val repositoryDataSourceImpl: RepositoryDataSourceImpl by lazy {
fcbeb6d
앗.. 그러네요! 적용하였습니다ㅎㅎ

2020-09-02 15:34 UTC, Hwangjunhong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/MovieListDialogFragment.kt
> +        val rvSearchItem = view?.findViewById<RecyclerView>(R.id.rv_search_list)
저도 처음에 이거 봤었는데 배열리소스를 동적으로 추가할수있나요??

2020-09-02 15:35 UTC, Hwangjunhong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/MovieSearchListAdapter.kt
> +    lateinit var onClick: ((String) -> Unit)
저도 찾아보니 뭐가 더 낫다는 그런건 알수 없었습니다ㅠ
913b59f
적용하였습니다!

2020-09-02 15:37 UTC, Hwangjunhong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/MovieListDialogFragment.kt
> +            (requireActivity() as MainActivity).titleListener.invoke(it)
913b59f
일단 멤버로 받긴 했는데 가늠이 잘 안돼서 적용하진 못했습니다ㅜ
그러면 MainActivity에 MovieSearchListAdapter을 초기화시켜줘야 하지 않나요??

2020-09-03 13:49 UTC, CmplxN commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/data/source/local/LocalDataSourceImpl.kt
> +        CoroutineScope(Dispatchers.IO).async {
이건 저도 잘은 몰라서요.
코루틴 대충 봤을 때 launch는 결과값이 없고 async는 deferred로 결과값을 받을 수 있다? 이렇게만 알고 있거든요.
혹시 그거말고 더 있나 해서 물어봤습니다.

2020-09-03 14:19 UTC, CmplxN commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/MovieListDialogFragment.kt
> +            .observe(this, Observer {
> Fragment는 Fragment View보다 긴 생명주기를 가지며, 일반적으로 UI를 업데이트용으로는 Fragment View Lifecycle 이 적절합니다. 그리고, Fragment View Lifecycle 도입으로 LiveData#observe에서 사용하는 Observer 중복 호출 문제도 해결할 수 있습니다. Fragment 사용 시 데이터 갱신에 대한 Lifecycle을 Fragment Lifecycle보다 Fragment View Lifecycle이 올바르다고 언급하고 있습니다.

http://pluu.github.io/blog/android/2020/01/25/android-fragment-lifecycle/
viewLifecycleOwner를 쓰는게 좋은 것 같습니다.

2020-09-03 14:19 UTC, CmplxN commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/MainActivity.kt
> +    lateinit var titleListener: ((String) -> Unit)
쓴다면 그 함수의 의미로 타입 이름을 지으면 될 것 같습니다. GetMovieInfo 라던가

2020-09-03 14:22 UTC, CmplxN commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/MovieListDialogFragment.kt
> +            (requireActivity() as MainActivity).titleListener.invoke(it)
```kotlin
class MovieListDialogFragment(private val getMovieInfo: GetMovieInfo) : DialogFragment()
```

```kotlin
// MainActivity
private val movieListDialogFragment = MovieListDialogFragment.newInstance { movieTitle ->
    repositoryDataSourceImpl.getMovieList(movieTitle, { movieData ->
        adapter.setData(movieData)
        hideKeyboard(this, edit_search)
    }, {
        Toast.makeText(this, "검색 실패", Toast.LENGTH_LONG).show()
    })
}
```

```kotlin
val movieSearchListAdapter = MovieSearchListAdapter {
    getMovieInfo(it.movieTitle)
    dismiss()
}
```

이런 느낌으로 단 코멘트였습니다.

2020-09-03 14:42 UTC, CmplxN commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/MovieListDialogFragment.kt
> +        val rvSearchItem = view?.findViewById<RecyclerView>(R.id.rv_search_list)
그러네요. Acitivity에서 show하기 전에 데이터를 다 받는다던가.. 해야겠군요
구현 방식은 자유니까 rcv로 해도 좋은 것 같습니다.

2020-09-04 10:37 UTC, Hwangjunhong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/MovieListDialogFragment.kt
> +            .observe(this, Observer {
처음에 글을 읽고나서 수정을 하였습니다!
477cb33
그런데 에러가 나서 찾아보니 DialogFragment는 Fragment와 생명주기가 달라서 viewLifecycleOwner을 쓰게되면 에러가 납니다
DialogFragment는 액티비티의 생명주기를 따라야 해서 requireActivity 를 넣어주었습니다!
e5886e4

2020-09-04 10:38 UTC, Hwangjunhong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/MainActivity.kt
> +    lateinit var titleListener: ((String) -> Unit)
90384c5
쓰다보니 typeAlias가 필요한 시점이 어딘지 알게됐습니다 감사합니다

2020-09-04 10:44 UTC, Hwangjunhong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/MovieListDialogFragment.kt
> +            (requireActivity() as MainActivity).titleListener.invoke(it)
e5886e4
이런 느낌이 맞을까요??
타입 캐스팅을 하는게 비용을 많이잡아먹는건 알고있지만 찾아봐도 구체적인건 잘 모르겠던데 이렇게 바꿨을때에 차이가 많이나나요~?

2020-09-04 14:14 UTC, CmplxN commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/MovieListDialogFragment.kt
> +            .observe(this, Observer {
아 그러네요, DialogFragment는 onCreateDialog -> onCreateView니까요..
onCreateView에서 viewLifecycleOwner를 써야하는거죠.
죄송합니다 ㅠ

2020-09-04 14:34 UTC, CmplxN commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/MovieListDialogFragment.kt
> +            (requireActivity() as MainActivity).titleListener.invoke(it)
아무래도 타입캐스팅이 확장성을 떨어뜨리는 면이 있다보니
별다른 코스트 없이 쓰지 않고 구현할 수 있으면 지양하는게 맞다고 생각합니다.

2020-09-04 15:10 UTC, CmplxN commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/MovieSearchListAdapter.kt
> +                onClick.invoke(movieListItems[absoluteAdapterPosition].movieTitle)
invoke를 하지 않아도 됩니다.
```kotlin
onClick(movieListItems[absoluteAdapterPosition].movieTitle)
```

2020-09-04 15:10 UTC, CmplxN commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/MovieListDialogFragment.kt
> +            getMovieTitle.invoke(it)
invoke 없이도 call 할 수 있습니다.
```kotlin
getMovieTitle(it)
```

2020-09-04 15:10 UTC, CmplxN commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/MovieListDialogFragment.kt
> +        val movieSearchListAdapter = MovieSearchListAdapter {}
`GetMovieTitle`을 `MovieSearchListAdpater`의 생성자로 했으면, 생성자로 전달해주는 것이 좋을 것 같습니다.
저는 setter보다는 할 수 있으면 생성자를 선호하는 편인데 세터로 하고 싶으시면,
`MovieSearchListAdpater`의 생성자에서 `onClick` 빼버리고 일반 프로퍼티로 하고 아래에서 처럼 set하면 될 것 같습니다.

2020-09-04 15:10 UTC, CmplxN commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/MovieListDialogFragment.kt
> +        val inflater = activity?.layoutInflater
아래에 `requireActivity()`가 있으므로 여기서도 `requireActivity()`를 쓰는게 어떨까요. (아래 requireActivity때매 어짜피 null이면 예외 발생)

2020-09-04 15:15 UTC, CmplxN commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/MainActivity.kt
> +    lateinit var titleListener: ((String) -> Unit)
typealias가 성능에 영향을 끼치는지는 잘 모르겠네요... 그냥 별칭 지어주는거라고 생각해서요.

2020-09-04 15:21 UTC, CmplxN commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/MainActivity.kt
> +    lateinit var titleListener: ((String) -> Unit)
안그러면 제가 구현한거처럼 java style로 인터페이스 만들고 하시면 될 것 같습니다.

2020-09-04 16:50 UTC, Hwangjunhong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/MovieSearchListAdapter.kt
> +                onClick.invoke(movieListItems[absoluteAdapterPosition].movieTitle)
7d48452
앗.. 몰랐습니다! 좋은정보 감사합니다!

2020-09-04 16:51 UTC, Hwangjunhong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/MovieListDialogFragment.kt
> +        val inflater = activity?.layoutInflater
98a0fcc
엇 이건 저도 마구니가..
몰아냈습니다!

2020-09-04 16:52 UTC, Hwangjunhong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/MovieListDialogFragment.kt
> +        val movieSearchListAdapter = MovieSearchListAdapter {}
f365384
이것도 마구니가 낀듯 싶습니다..
제가 못봤네요ㅜ 저도 생성자에서 처리하는것을 선호합니다!
몰아냈습니다!

2020-09-04 16:52 UTC, Hwangjunhong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/MovieListDialogFragment.kt
> +            getMovieTitle.invoke(it)
f365384

2020-09-05 02:35 UTC, CmplxN commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/MovieListDialogFragment.kt
> +        val inflater = activity?.layoutInflater
아 제가 말씀드린건 25 라인의 `val inflater = activity?.layoutInflater`입니다.
`getActivity()`가 `requireActivity()`랑 다른거는 null 여부뿐인데
이미 아래서 `requireActivity()`를 부르는 이상 `getActivity()`를 쓸 이유가 있나 해서 적어봤습니다.

그리고 14라인의 import도 없어도 되는 것 같아요

2020-09-05 02:44 UTC, CmplxN commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/MovieListDialogFragment.kt
> +        return dialog.create()
다시보니까 여기도 체이닝 할 수 있을 것 같습니다.
```kotlin
return AlertDialog.Builder(requireActivity())
    .setView(view)
    .setTitle("최근 검색")
    .create()
```

2020-09-05 02:44 UTC, CmplxN commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/MovieListDialogFragment.kt
> +import com.hong.architecturestudy.ui.GetMovieTitle as GetMovieTitle
이 라인(14)는 없어도 되는 것 같습니다.

2020-09-05 03:49 UTC, Hwangjunhong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/MovieListDialogFragment.kt
> +import com.hong.architecturestudy.ui.GetMovieTitle as GetMovieTitle
42ee5e6

2020-09-05 03:49 UTC, Hwangjunhong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/MovieListDialogFragment.kt
> +        return dialog.create()
c68ead6

2020-09-05 03:50 UTC, Hwangjunhong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/MovieListDialogFragment.kt
> +        val inflater = activity?.layoutInflater
0f50aa3
엇 그러네요ㅜ 감사합니다!

2020-09-05 06:44 UTC, CmplxN commented
Fragment를 생성자로 만들 때 주의사항이 있는데, 제가 그걸 간과했었네요. ㅠㅠ
처음 만드신거처럼 DialogFragment도 Fragment니까 생성자를 비워두거나,
Fragment Factory를 사용하는 방식을 써야할 것 같습니다.

[참고 링크](https://medium.com/capital-one-tech/android-fragmentfactory-75823af015fd)
6625e7d : 제 과제 수정한 커밋 (FragmentFactory 사용)

2020-09-06 02:31 UTC, CmplxN approved these changes
수고하셨습니다. 룩굿투미

2020-09-06 05:21 UTC, sjjeong requested changes

2020-09-06 05:21 UTC, sjjeong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/data/repository/RepositoryDataSource.kt
> +    fun loadData(context: Context): LiveData<List<MovieInfo>>
context를 전달하지 않도록 해주시고 LiveData를 리턴하지 않는 형태로 변경해주세요

2020-09-06 05:21 UTC, sjjeong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/data/source/local/entity/MovieInfo.kt
> +    @ColumnInfo(name = "movietitle") var movieTitle: String = ""
Annotation과 선언을 한줄말고 두줄로 나눠주세요
```kotlin
@PrimaryKey(autoGenerate = true)
val id: Long? = null
```

2020-09-06 05:21 UTC, sjjeong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/data/source/remote/RemoteDataSourceImpl.kt
> +                        log("[MainActivity] : 데이터 불러오기 실패")
onFailure로 Throwable을 전달하도록 해주세요

2020-09-06 05:21 UTC, sjjeong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/MainActivity.kt
> +        MovieDatabase.destroyInstance()
super는 맨 마지막에 호출하도록 해주세요

2020-09-06 05:21 UTC, sjjeong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/MovieListDialogFragment.kt
> +class MovieListDialogFragment(private val getMovieTitle: GetMovieTitle) : DialogFragment() {
람다는 데이터가 아니라서 생성자로 받으면 안됩니다.
Bundle에 넣을 수 있는 형태만 전달하도록 해주세요

2020-09-06 05:21 UTC, sjjeong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/res/layout/dialog_fragment_movie_list.xml
> +        android:layout_width="match_parent"
ConstraintLayout일때는 match_parent대신 0dp를 써야합니다.

2020-09-06 05:21 UTC, sjjeong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/res/layout/item_movie_search_list.xml
> +        android:layout_marginEnd="10dp"
marginHorizontal을 사용하시면 됩니다

2020-09-06 05:21 UTC, sjjeong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/MovieSearchListAdapter.kt
> +class MovieSearchListAdapter(var onClick: GetMovieTitle) :
val로 선언해주세요

2020-09-06 05:21 UTC, sjjeong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/MovieSearchListAdapter.kt
> +    private val movieListItems = mutableListOf<MovieInfo>()
movieListItems는 영화 리스트의 아이템들을 가지고 있는거라 List<List<Movie>>느낌입니다.
movieItems로 하면 좋겠습니다.

2020-09-06 05:21 UTC, sjjeong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/MainActivity.kt
> +                        repositoryDataSourceImpl.saveData(keyword, this)
save는 저번시간에 이야기 한것 처럼 repository.getMovieList함수 내부에서 처리하면 됩니다.

2020-09-06 12:34 UTC, Hwangjunhong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/data/source/local/entity/MovieInfo.kt
> +    @ColumnInfo(name = "movietitle") var movieTitle: String = ""
0afe85e
수정하였습니다!

2020-09-06 12:34 UTC, Hwangjunhong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/MainActivity.kt
> +                        repositoryDataSourceImpl.saveData(keyword, this)
c29a530
수정하였습니다

2020-09-06 12:34 UTC, Hwangjunhong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/MovieSearchListAdapter.kt
> +    private val movieListItems = mutableListOf<MovieInfo>()
cea433a
수정하였습니다

2020-09-06 12:34 UTC, Hwangjunhong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/MovieSearchListAdapter.kt
> +class MovieSearchListAdapter(var onClick: GetMovieTitle) :
d0cf504

2020-09-06 12:34 UTC, Hwangjunhong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/res/layout/item_movie_search_list.xml
> +        android:layout_marginEnd="10dp"
667f809

2020-09-06 12:35 UTC, Hwangjunhong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/res/layout/dialog_fragment_movie_list.xml
> +        android:layout_width="match_parent"
dfeca69

2020-09-06 12:35 UTC, Hwangjunhong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/MainActivity.kt
> +        MovieDatabase.destroyInstance()
1e22704

2020-09-06 12:35 UTC, Hwangjunhong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/data/source/remote/RemoteDataSourceImpl.kt
> +                        log("[MainActivity] : 데이터 불러오기 실패")
be15e25
수정하였습니다!

2020-09-06 12:35 UTC, Hwangjunhong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/data/repository/RepositoryDataSource.kt
> +    fun loadData(context: Context): LiveData<List<MovieInfo>>
d2a453d
수정하였습니다!

2020-09-09 09:52 UTC, sjjeong requested changes

2020-09-09 09:52 UTC, sjjeong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/data/source/local/LocalDataSourceImpl.kt
> +class LocalDataSourceImpl(context: Context) : LocalDataSource {
context를 전달하는 것보다 context를 이용해서 만든 MovieDatabase를 전달하는게 좋습니다.

2020-09-09 11:12 UTC, Hwangjunhong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/data/source/local/LocalDataSourceImpl.kt
> +class LocalDataSourceImpl(context: Context) : LocalDataSource {
b769e21
수정하였습니다!

2020-09-09 14:30 UTC, sjjeong requested changes

2020-09-09 14:30 UTC, sjjeong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/MainActivity.kt
> +        CoroutineScope(Dispatchers.IO).cancel()
불필요한 작업입니다ㅏ.

2020-09-09 14:30 UTC, sjjeong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/MovieListDialogFragment.kt
> +        CoroutineScope(Dispatchers.IO).launch {
lifecycleScope를 사용하시면 됩니다.

2020-09-09 16:57 UTC, Hwangjunhong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/MainActivity.kt
> +        CoroutineScope(Dispatchers.IO).cancel()
7b0b413
수정하였습니다

2020-09-09 17:06 UTC, Hwangjunhong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/MovieListDialogFragment.kt
> +        CoroutineScope(Dispatchers.IO).launch {
f2bc7c0
lifecycleScope를 사용하면 사이클에 맞춰 알아서 종료시켜주는군요!
적용하였습니다

2020-09-10 09:28 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-09-10 11:57 UTC, merged