HW-2 : MODEL 구현
sjjeong/GoogryAndroidArchitecutreStudy pull request #802
Opened 2020-09-01 13:21 UTC by camai

2주차 과제 Model 구현 

너무 많은 삽질했네요.. 더 공부하면서 소스 추가하겠습니다.
잘못된 부분이 있거나 수정할 부분이 있으면 코멘트 부탁드립니다.

2020-09-04 19:11 UTC, Sangmeebee reviewed
제가 아는 선에서는 이 두가지에 관해서만 말씀드려야겠네요...
발전해서 점점 더 좋은 리뷰 남기겠습니다!

2020-09-04 19:11 UTC, Sangmeebee commented on class13/camai/ArchitectureStudy/app/src/main/java/com/camai/archtecherstudy/ui/MainActivity.kt
> +    private lateinit var viewModel: RecentMovieNameViewModel
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/802/commits/86be6d6995c8ca303b02eb8e58910377cb462608
onCreate에서 선언과 동시에 초기화 해도 되지 않을까요??

2020-09-04 19:11 UTC, Sangmeebee commented on class13/camai/ArchitectureStudy/app/src/main/java/com/camai/archtecherstudy/source/local/room/RecentSearchListDatabase.kt
> +        }
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/802/commits/1c385a7a16253f59898030b21785dd07e86409a8
kotlin coding convention을 지켜 companion object는 method 정의 뒤에 위치시키는 것이 좋을 것 같습니다

2020-09-05 12:04 UTC, camai commented on class13/camai/ArchitectureStudy/app/src/main/java/com/camai/archtecherstudy/source/local/room/RecentSearchListDatabase.kt
> +        }
말씀해주신 리뷰 내용이 잘 이해가 되지 않네요.. 메소드가 오브젝트 안에 선언되어 있어서요..

2020-09-05 12:12 UTC, camai commented on class13/camai/ArchitectureStudy/app/src/main/java/com/camai/archtecherstudy/ui/MainActivity.kt
> +    private lateinit var viewModel: RecentMovieNameViewModel
832c20f

리뷰 주신 내용으로 수정해보았습니다.

2020-09-05 12:21 UTC, Sangmeebee commented on class13/camai/ArchitectureStudy/app/src/main/java/com/camai/archtecherstudy/source/local/room/RecentSearchListDatabase.kt
> +        }
아 그렇네요 제가 잘 못보았네요!

2020-09-05 12:22 UTC, Sangmeebee approved these changes
수고하셨습니다!

2020-09-06 05:35 UTC, sjjeong requested changes

2020-09-06 05:35 UTC, sjjeong commented on class13/camai/ArchitectureStudy/app/build.gradle
> +    implementation "androidx.lifecycle:lifecycle-livedata-ktx:2.2.0"
ViewModel과 LiveData는 나중에 추가 해주세요
지금은 제거해주세요

2020-09-06 05:35 UTC, sjjeong commented on class13/camai/ArchitectureStudy/app/src/main/java/com/camai/archtecherstudy/data/model/RecentMovieNameViewModel.kt
> +}
아직 MVVM이나 MVP를 한것이 아니기 때문에 제거해주세요

2020-09-06 05:35 UTC, sjjeong commented on class13/camai/ArchitectureStudy/app/src/main/java/com/camai/archtecherstudy/data/network/MovieApiServiceImpl.kt
> +    fun create(): MovieApiService {
함수가 아니라 val로 가지고 있는게 좋을 것 같네요

2020-09-06 05:35 UTC, sjjeong commented on class13/camai/ArchitectureStudy/app/src/main/java/com/camai/archtecherstudy/data/repository/MovieRepository.kt
> +    fun deteleDb(context: Context)
context를 전달하지 않도록 해주세요

2020-09-06 05:35 UTC, sjjeong commented on class13/camai/ArchitectureStudy/app/src/main/java/com/camai/archtecherstudy/data/source/remote/MovieRemoteDataSourceImpl.kt
> +                    Log.e(TAG, response.message())
failed로 throwable을 전달하는 것도 추가해주세요

2020-09-06 05:35 UTC, sjjeong commented on class13/camai/ArchitectureStudy/app/src/main/java/com/camai/archtecherstudy/ui/MainActivity.kt
> +                insertMovieNameInDb(movietitle)
data를 추가하는 작업은 view에서 다시 할 필요 없이 repository안에서 해주시면 됩니다.

2020-09-06 05:35 UTC, sjjeong commented on class13/camai/ArchitectureStudy/app/src/main/java/com/camai/archtecherstudy/ui/adapter/RecentMovieAdapter.kt
> +    val recentlist: List<RecentSearchNameList>,
생성자를 통해서 리스트를 받지 않도록 해주세요

2020-09-06 05:35 UTC, sjjeong commented on class13/camai/ArchitectureStudy/app/src/main/java/com/camai/archtecherstudy/ui/adapter/RecentMovieAdapter.kt
> +    class ViewHolder(itemView: View?) : RecyclerView.ViewHolder(itemView!!) {
Nonnull로 해도 됩니다.

2020-09-06 05:35 UTC, sjjeong commented on class13/camai/ArchitectureStudy/app/src/main/res/layout/recent_item.xml
> +        android:paddingEnd="24sp"
dp로 변경해주세요 start랑 end의 값이 같으면 Horizontal로 쓰면 됩니다.

2020-09-06 05:35 UTC, sjjeong commented on class13/camai/ArchitectureStudy/app/src/main/java/com/camai/archtecherstudy/data/source/local/room/RecentSearchListDatabase.kt
> +            INSTANCE = null
db instance를 null로 했다가 새로 만드는 작업은 불필요해보입니다.
null로 만드는 작업은 제거해주세요

2020-09-06 05:35 UTC, sjjeong commented on class13/camai/ArchitectureStudy/app/src/main/java/com/camai/archtecherstudy/data/source/local/room/RecentSearchNameList.kt
> +class RecentSearchNameList(
List라는 용어는 제거하는게 좋을 것 같습니다.

2020-09-06 05:35 UTC, sjjeong commented on class13/camai/ArchitectureStudy/app/src/main/java/com/camai/archtecherstudy/ui/RecentMovieListDialog.kt
> +    override fun onActivityCreated(savedInstanceState: Bundle?) {
이 함수는 추후 deprecate 될 함수입니다. onViewCreated를 사용해주세요

2020-09-06 05:35 UTC, sjjeong commented on class13/camai/ArchitectureStudy/app/src/main/java/com/camai/archtecherstudy/ui/RecentMovieListDialog.kt
> +        context?.let {
requireContext를 사용하도록 해주세요

2020-09-07 00:37 UTC, camai commented on class13/camai/ArchitectureStudy/app/src/main/java/com/camai/archtecherstudy/data/network/MovieApiServiceImpl.kt
> +    fun create(): MovieApiService {
38f7d9b

적용하였습니다.

2020-09-07 00:41 UTC, camai commented on class13/camai/ArchitectureStudy/app/src/main/res/layout/recent_item.xml
> +        android:paddingEnd="24sp"
UI 구성하는 부분을 다시 공부해야겠네요.. 
감사합니다.

29ed421

2020-09-07 00:42 UTC, camai commented on class13/camai/ArchitectureStudy/app/src/main/java/com/camai/archtecherstudy/data/source/local/room/RecentSearchListDatabase.kt
> +            INSTANCE = null
리뷰 감사합니다.

508e91c

2020-09-07 00:44 UTC, camai commented on class13/camai/ArchitectureStudy/app/src/main/java/com/camai/archtecherstudy/data/source/local/room/RecentSearchNameList.kt
> +class RecentSearchNameList(
리뷰 감사합니다.

0e36fdd

2020-09-07 00:47 UTC, camai commented on class13/camai/ArchitectureStudy/app/src/main/java/com/camai/archtecherstudy/ui/RecentMovieListDialog.kt
> +    override fun onActivityCreated(savedInstanceState: Bundle?) {
DialogFragment 사용법을 다시 확인해보겠습니다. 
리뷰 감사합니다.

321f799

2020-09-07 08:57 UTC, camai commented on class13/camai/ArchitectureStudy/app/build.gradle
> +    implementation "androidx.lifecycle:lifecycle-livedata-ktx:2.2.0"
ViewModel과 LiveData를 왜? 써야 되는지를 먼저 생각해봤었야 하는데
좀 더 편한 방법이 있구나 부터 생각했네요.
왜? 써야되는지를 다시 생각하면서 확인해봐야겠네요~
리뷰 감사합니다.

fa543a4

2020-09-07 09:00 UTC, camai commented on class13/camai/ArchitectureStudy/app/src/main/java/com/camai/archtecherstudy/data/model/RecentMovieNameViewModel.kt
> +}
리뷰 감사합니다.

bd11d54

2020-09-07 09:09 UTC, camai commented on class13/camai/ArchitectureStudy/app/src/main/java/com/camai/archtecherstudy/data/repository/MovieRepository.kt
> +    fun deteleDb(context: Context)
매번 context를 전달하지 않도록 수정하였습니다.

싱글톤으로 맨처음 db init 할때 context를 받도록 수정했습니다.
리뷰 감사합니다.

3bebad1

2020-09-07 09:13 UTC, camai commented on class13/camai/ArchitectureStudy/app/src/main/java/com/camai/archtecherstudy/data/source/remote/MovieRemoteDataSourceImpl.kt
> +                    Log.e(TAG, response.message())
해당 내용이 빠졌었네요

리뷰 감사합니다.

6ec0644

2020-09-07 09:17 UTC, camai commented on class13/camai/ArchitectureStudy/app/src/main/java/com/camai/archtecherstudy/ui/MainActivity.kt
> +                insertMovieNameInDb(movietitle)
수업에서 말씀해주신 내용인데 적용하지 못하였네요.

리뷰 감사합니다.

b657b0c

2020-09-07 09:25 UTC, camai commented on class13/camai/ArchitectureStudy/app/src/main/java/com/camai/archtecherstudy/ui/adapter/RecentMovieAdapter.kt
> +    class ViewHolder(itemView: View?) : RecyclerView.ViewHolder(itemView!!) {
view 선언 시 null 체크를 하고 있었네요.

리뷰 감사합니다.

cca1230

2020-09-07 09:29 UTC, camai commented on class13/camai/ArchitectureStudy/app/src/main/java/com/camai/archtecherstudy/ui/RecentMovieListDialog.kt
> +        context?.let {
requireContext 경우 
Fragment의 Context? 를 반환하기 때문에 requireContext를 통해 Context를 반환 가능하는걸 알게 되었습니다.

처음 접하는 내용으로 context 관련하여 다시 공부하게 되었습니다.
리뷰 감사합니다.

e3704d3

2020-09-07 09:57 UTC, camai commented on class13/camai/ArchitectureStudy/app/src/main/java/com/camai/archtecherstudy/ui/adapter/RecentMovieAdapter.kt
> +    val recentlist: List<RecentSearchNameList>,
기존 리사클러뷰 어댑터에서는 생성자에서 받지 않도록 작업 해두고
이번에는 추가했었던걸 확인하였습니다.

리뷰 감사합니다.

8ab5ec4

2020-09-07 09:59 UTC, camai commented on class13/camai/ArchitectureStudy/app/src/main/java/com/camai/archtecherstudy/data/model/RecentMovieNameViewModel.kt
> +}
ViewModel 대신하여 
다이얼로그에서 클릭 했을 때 클릭된 영화 검색어를 검색하도록 수정하였습니다. 

f132607

2020-09-08 13:40 UTC, camai commented on class13/camai/ArchitectureStudy/app/src/main/java/com/camai/archtecherstudy/ui/adapter/RecentMovieAdapter.kt
> +    val recentlist: List<RecentSearchNameList>,
생성자를 통해 리스트를 받지 않도록 하는 이유에 대해 찾아보고 제가 3가지로 생각해봤는데요. 
1. 생성자 선언 시 어댑터의 초기 상태를 설정 하는데 초기 상태 값 셋팅에 리스트를 전달함으로 목적에 부합되지 않아서
2. 생성자 에서 리스트를 받지 않고 값이 변경될 때 어댑터에 리스트를 받을 수 있게 할 수 있어서 필요하지 않은 값을 전달하기에
3. 생성자 선언 시 리스트 객체를 전달함으로 필요하지 않은 메모리 사용을 하기 때문에

이렇게 생각해봤는데요. 생성자를 통해서 리스트를 받지 않도록 하는 이유에 대해 잘못 접근했을까요?

2020-09-09 14:17 UTC, sjjeong commented on class13/camai/ArchitectureStudy/app/src/main/java/com/camai/archtecherstudy/data/network/MovieApiServiceImpl.kt
> +    fun create(): MovieApiService {
httpLoggingInterceptor이 아니라 create함수를 변경해달라는 거였어요

2020-09-09 14:19 UTC, sjjeong commented on class13/camai/ArchitectureStudy/app/src/main/java/com/camai/archtecherstudy/data/repository/MovieRepository.kt
> +    fun deteleDb(context: Context)
Impl 클래스들이 전부 object라서 생성자를 통해 context로 만든 것을 주입 받을 수 없네요
ApplicationContext를 접근하도록 변경해서 파라미터로 context를 전달하지 않도록 해주세요

2020-09-09 14:20 UTC, sjjeong commented on class13/camai/ArchitectureStudy/app/src/main/java/com/camai/archtecherstudy/ui/MainActivity.kt
> +                insertMovieNameInDb(movietitle)
Remote에서 Repository에 함수를 호출하는게 아닙니다.
Repository가 Remote의 결과를 받고 거기서 Local 함수를 호출해야 합니다.

2020-09-09 14:23 UTC, sjjeong commented on class13/camai/ArchitectureStudy/app/src/main/java/com/camai/archtecherstudy/ui/adapter/RecentMovieAdapter.kt
> +    val recentlist: List<RecentSearchNameList>,
외부와 내부가 같은리스트(인스턴스가 같음)를 공유하게 된다면 외부에서 리스트를 변경했을 때 어뎁터 안에 있는 리스트의 내용이 같이 변경되기 때문에 버그가 발생할 수 있기 때문입니다.

2020-09-09 14:25 UTC, sjjeong commented on class13/camai/ArchitectureStudy/app/src/main/java/com/camai/archtecherstudy/data/source/local/room/RecentSearchListDatabase.kt
> +            INSTANCE = null
리뷰 반영을 잘못하신것 같은데 해당함수를 제거해달라는 겁니다

2020-09-09 14:49 UTC, camai commented on class13/camai/ArchitectureStudy/app/src/main/java/com/camai/archtecherstudy/ui/adapter/RecentMovieAdapter.kt
> +    val recentlist: List<RecentSearchNameList>,
아.. 그렇군요 잘못 접근하고 찾아봤네요
리뷰 감사합니다.

2020-09-10 08:44 UTC, camai commented on class13/camai/ArchitectureStudy/app/src/main/java/com/camai/archtecherstudy/ui/MainActivity.kt
> +                insertMovieNameInDb(movietitle)
리뷰 주신 내용으로 수정하였습니다.
리뷰 감사합니다.
부족한게 많네요..

8dfc7d0

2020-09-10 09:09 UTC, camai commented on class13/camai/ArchitectureStudy/app/src/main/java/com/camai/archtecherstudy/data/source/local/room/RecentSearchListDatabase.kt
> +            INSTANCE = null
리뷰 내용을 잘 이해를 못했나보네요.. 

그리고 이미 Destroy 될때 INSTANCE가 null 이네요.. 
불필요한 작업인 걸 확인했습니다.

리뷰 감사합니다.

afe3b45

2020-09-10 14:44 UTC, camai commented on class13/camai/ArchitectureStudy/app/src/main/java/com/camai/archtecherstudy/data/repository/MovieRepository.kt
> +    fun deteleDb(context: Context)
해당 내용 수정하였습니다.

리뷰 감사합니다.

c107a57

2020-09-10 15:25 UTC, camai commented on class13/camai/ArchitectureStudy/app/src/main/java/com/camai/archtecherstudy/data/network/MovieApiServiceImpl.kt
> +    fun create(): MovieApiService {
수정했습니다.

리뷰 감사합니다.

83440e2

2020-09-11 13:51 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-09-12 01:24 UTC, merged