HW-2 : MODEL 구현 (이정태)
sjjeong/GoogryAndroidArchitecutreStudy pull request #803
Opened 2020-09-02 16:05 UTC by CmplxN

Local은 SharedPreferences로 했고, data가 작아서 Local query 저장 / 불러오기는 UI Thread에서 했습니다.

Q : Observable과 Single에 중복되는
```kotlin
.observeOn(AndroidSchedulers.mainThread())
.subscribe({
    Toast.makeText(this, "Search Completed", Toast.LENGTH_SHORT).show()
    movieAdapter.setList(it.movies)
}, {
    Toast.makeText(this, "Network Error", Toast.LENGTH_LONG).show()
    it.printStackTrace()
}).addTo(compositeDisposable)
```
이 부분을 Extension Function으로 중복을 줄여보고 싶은데 불가능한가요?

2020-09-03 10:28 UTC, Hwangjunhong commented on class13/CmplxN/AAS/app/src/main/java/com/example/aas/ui/MainActivity.kt
> +                movieSearchRepository.getMovies(keyword.toString(), applicationContext)
applicationContext를 쓰신 이유가 있을까요~?

2020-09-03 10:29 UTC, Hwangjunhong commented
fun Single<ApiResult>.observableAndSingle(
    activity: AppCompatActivity,
    movieAdapter: MovieAdapter,
    compositeDisposable: CompositeDisposable
) {
    this.observeOn(AndroidSchedulers.mainThread())
        .subscribe({
            activity.makeToast("Search Completed")
            movieAdapter.setList(it.movies)
        }, {
            activity.makeToast("Network Error")
            it.printStackTrace()
        }).addTo(compositeDisposable)
}

fun AppCompatActivity.makeToast(message: String) {
    Toast.makeText(this, message, Toast.LENGTH_LONG).show()
}

2020-09-03 10:32 UTC, Hwangjunhong approved these changes

2020-09-03 10:32 UTC, Hwangjunhong commented on class13/CmplxN/AAS/app/src/main/java/com/example/aas/data/source/remote/RemoteDataSourceImpl.kt
> +    }
```kotlin
create RemoteDataSource
override fun getMovies(query: String): Single<ApiResult> =
        RetrofitManager.naverMoviesApi.getMovies(query)
```
의견! - 이것 뿐이라면 얘도 괜찮을것같습니다!

2020-09-03 10:35 UTC, Hwangjunhong commented on class13/CmplxN/AAS/app/src/main/java/com/example/aas/ui/SavedQueryDialogFragment.kt
> +            movieSearchRepository.getSavedQueries(requireActivity().applicationContext).reversed()
모든곳에다가 applicationContext를 받으셨는데 activity context로 바꾸는게 좋은것같습니다!
여기도 requireActivity()만 받아도 될것같습니다

2020-09-03 11:19 UTC, Hwangjunhong commented on class13/CmplxN/AAS/app/src/main/java/com/example/aas/data/source/local/LocalDataSourceImpl.kt
> +            context.getSharedPreferences(sharedPreferencesName, Context.MODE_PRIVATE)
sharedPreferences 도 extension function으로 빼봐도 좋을것 같습니다!
덤으로 Glide 같은 것들도요!

2020-09-03 11:28 UTC, Hwangjunhong commented on class13/CmplxN/AAS/app/src/main/java/com/example/aas/ui/SavedQueryDialogFragment.kt
> +                .setItems(searchHistory.toTypedArray()) { _, idx ->
chain을 이어줘도 될것같습니다!
```kotlin
val builder = AlertDialog.Builder(it)
            	.setTitle("최근 5개 검색어")
            	.setItems(searchHistory.toTypedArray()) { _, idx ->
```

2020-09-03 11:42 UTC, Hwangjunhong commented
제가 이것저것 잘못눌렀네요ㅜ
깔끔해서 제가 코멘트를 달부분이 많이없네요! (제가 부족해서 그럴수도 있습니다..!)
의견 - 대부분 바로 리턴받는 것들은 타입과 브레이스를 빼고 처리해도 깔끔할것 같습니다!
제가 잘못이해한점이 있다면 알려주시면 감사하겠습니다!

2020-09-03 12:55 UTC, CmplxN commented on class13/CmplxN/AAS/app/src/main/java/com/example/aas/ui/MainActivity.kt
> +                movieSearchRepository.getMovies(keyword.toString(), applicationContext)
그러게요? 왜쓴거지 하네요 ㅋㅋ 머릿속에 마구니가 가득찼나봅니다.

2020-09-03 13:19 UTC, CmplxN commented on class13/CmplxN/AAS/app/src/main/java/com/example/aas/data/source/local/LocalDataSourceImpl.kt
> +            context.getSharedPreferences(sharedPreferencesName, Context.MODE_PRIVATE)
Glide는 extension을 해도 좋을 것 같은데
sharedPreferences는 어떤 부분인지 잘 모르겠습니다.
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/794#discussion_r478368512

2020-09-03 13:24 UTC, CmplxN commented on class13/CmplxN/AAS/app/src/main/java/com/example/aas/ui/SavedQueryDialogFragment.kt
> +                .setItems(searchHistory.toTypedArray()) { _, idx ->
f8e9325

2020-09-03 13:24 UTC, CmplxN commented on class13/CmplxN/AAS/app/src/main/java/com/example/aas/data/source/local/LocalDataSourceImpl.kt
> +            context.getSharedPreferences(sharedPreferencesName, Context.MODE_PRIVATE)
662fd9a 로 Glide는 바꾸어보았습니다.

2020-09-03 13:25 UTC, CmplxN commented on class13/CmplxN/AAS/app/src/main/java/com/example/aas/data/source/remote/RemoteDataSourceImpl.kt
> +    }
02db637 한줄짜리 표현식은 그게더 좋겠네요

2020-09-03 13:25 UTC, CmplxN commented on class13/CmplxN/AAS/app/src/main/java/com/example/aas/ui/MainActivity.kt
> +                movieSearchRepository.getMovies(keyword.toString(), applicationContext)
badb55c 마구니를 몰아냈습니다.

2020-09-03 13:36 UTC, CmplxN commented
> ```kotlin
> fun Single<ApiResult>.observableAndSingle(
>     activity: AppCompatActivity,
>     movieAdapter: MovieAdapter,
>     compositeDisposable: CompositeDisposable
> ) {
>     this.observeOn(AndroidSchedulers.mainThread())
>         .subscribe({
>             activity.makeToast("Search Completed")
>             movieAdapter.setList(it.movies)
>         }, {
>             activity.makeToast("Network Error")
>             it.printStackTrace()
>         }).addTo(compositeDisposable)
> }
> 
> fun AppCompatActivity.makeToast(message: String) {
>     Toast.makeText(this, message, Toast.LENGTH_LONG).show()
> }
> ```
> 
> 뭔가.. 좋은것 같지는 않지만 이렇게 빼볼수 있지 않을까요?

위처럼 하면 Single쪽만 붙일 수 있고, Observable쪽은 안돼요

그래서 Single에 toObservable걸고 7ad87b1 로 해보았습니다.

2020-09-03 16:40 UTC, Hwangjunhong commented on class13/CmplxN/AAS/app/src/main/java/com/example/aas/data/source/local/LocalDataSourceImpl.kt
> +            context.getSharedPreferences(sharedPreferencesName, Context.MODE_PRIVATE)
아아 sharedPreferences는 유틸클래스로 빼도 좋을거같다는 거였습니다!
아니면 KTX도 괜찮은것 같습니다!
https://developer.android.com/kotlin/ktx?hl=ko

이건 여담인데 sharedPreferences 대신
https://android-developers.googleblog.com/2020/09/prefer-storing-data-with-jetpack.html?linkId=98693079&m=1
이런게 나오는거 같습니다

2020-09-03 16:56 UTC, Hwangjunhong commented
깔끔하게 잘짜신것같습니다! 더 달아드리고싶은데 제가 rx을 잘 몰라서 아쉽네요ㅜ
수고하셨습니다ㅎㅎ

2020-09-05 05:28 UTC, CmplxN commented
수정할 사항이 있어서 제가 수정하고 다시 레이블 바꾸겠습니다.

2020-09-05 06:51 UTC, CmplxN commented
1. Fragment Factory를 만들어서 적용
2. `HistorySelectionListener`나 `FragmentFactoryImpl`모두 해당 클래스에서만 쓸거라는 의미로 nested class로 바꿈

2020-09-05 16:10 UTC, Hwangjunhong commented
와우.. 좋은정보 감사합니다! 저도 수정해서 올리겠습니다ㅎㅎ

2020-09-06 05:47 UTC, sjjeong requested changes

2020-09-06 05:47 UTC, sjjeong commented on class13/CmplxN/AAS/app/src/main/java/com/example/aas/data/repository/MovieSearchRepository.kt
> +    fun getSavedQueries(context: Context): List<String>
context를 전달하지 않도록 해주세요

2020-09-06 05:47 UTC, sjjeong commented on class13/CmplxN/AAS/app/src/main/java/com/example/aas/data/repository/MovieSearchRepositoryImpl.kt
> +        localDataSource.saveQuery(query, context)
네트워크요청에 성공했을때만 저장하도록 하면 어떨까요?

2020-09-06 05:47 UTC, sjjeong commented on class13/CmplxN/AAS/app/src/main/java/com/example/aas/data/repository/MovieSearchRepositoryImpl.kt
> +    override fun getSavedQueries(context: Context): List<String> =
get의 리턴값을 List<String>도 좋긴한데 Rx를 사용해서 Single<List<String>>으로 받아오도록 변경해보세요

2020-09-06 14:13 UTC, CmplxN commented
까먹으신 것 같아서 레이블을 answer needed로 바꿉니다.

2020-09-08 14:50 UTC, CmplxN commented on class13/CmplxN/AAS/app/src/main/java/com/example/aas/data/repository/MovieSearchRepository.kt
> +    fun getSavedQueries(context: Context): List<String>
47d58dc 에서 application context를 썼습니다.

2020-09-08 14:51 UTC, CmplxN commented on class13/CmplxN/AAS/app/src/main/java/com/example/aas/data/repository/MovieSearchRepositoryImpl.kt
> +        localDataSource.saveQuery(query, context)
8cfa006 에서 flatmap으로 `Single<Pair<ApiResult, Completable>>`를 받아온 뒤 Success면 Completable을 구독하게 했습니다.

2020-09-08 14:51 UTC, CmplxN commented on class13/CmplxN/AAS/app/src/main/java/com/example/aas/data/repository/MovieSearchRepositoryImpl.kt
> +    override fun getSavedQueries(context: Context): List<String> =
8cfa006
하다보니 윗 코멘트와 같은 커밋이 되어버렸습니다.
양해 부탁드립니다. ㅠ

2020-09-09 14:14 UTC, sjjeong commented on class13/CmplxN/AAS/app/src/main/java/com/example/aas/data/repository/MovieSearchRepositoryImpl.kt
> +        localDataSource.saveQuery(query, context)
제가 리뷰 했을때는 doOnSuccess가 없었는데 https://github.com/StudyFork/GoogryAndroidArchitectureStudy/commit/8cfa00671e087d8d2e056dd690562eeaee582d62 여기에는 doOnSuccess가 있네요 ㄷ
제 원래 의도는 doOnSuccess에서 local에 save하는거였습니다.

2020-09-09 15:30 UTC, CmplxN commented on class13/CmplxN/AAS/app/src/main/java/com/example/aas/data/repository/MovieSearchRepositoryImpl.kt
> +        localDataSource.saveQuery(query, context)
ebd07ed
`getSavedQuery()`가 Single이 되면서, subscribe를 해야돼서 아예 `saveQuery()`를 Completable로 만들고 `MainActivity`에서 구독했었습니다.
현재 `saveQuery()`에서 `getSavedQuery()` 구독후 disposable 처리가 없는데, timeout을 걸어서 유사시(?) 알아서 죽게 만들었습니다.

2020-09-09 16:16 UTC, CmplxN commented on class13/CmplxN/AAS/app/src/main/java/com/example/aas/data/repository/MovieSearchRepositoryImpl.kt
> +        localDataSource.saveQuery(query, context)
7bd9db9
disposable 추가하고
onDestroy에 clear하도록 변경했습니다.

2020-09-10 09:29 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-09-10 11:49 UTC, merged