HW-2 : MODEL 구현
sjjeong/GoogryAndroidArchitecutreStudy pull request #804
Opened 2020-09-06 09:54 UTC by HyeJeongHan

model 구현했습니다.

제대로 잘 한 건지 모르겠네요...
피드백 부탁드립니다!😁

2020-09-08 12:18 UTC, ddochi93 commented on class13/HyeJeongHan/project/app/src/main/java/com/hjhan/hyejeong/data/source/remote/NaverRemoteDataSourceImpl.kt
> +    }
불필요한 개행이 많은것 같아요. 19행과 21행 사이만 있는게 더 보기 좋을것같습니다.

2020-09-08 12:18 UTC, ddochi93 commented on class13/HyeJeongHan/project/app/src/main/java/com/hjhan/hyejeong/data/source/local/SharedPreferencesUtil.kt
> +            }
신박한 방법인것같습니다. 검색기록을 문자열 하나에 저장해서 JsonArray형태로 받아오는 방법인건가요?

2020-09-08 12:18 UTC, ddochi93 commented on class13/HyeJeongHan/project/app/src/main/java/com/hjhan/hyejeong/ui/MainActivity.kt
> +    }
repositoryImpl의 타입은 NaverRepositoryImpl처럼 구상클래스로 하는 것보다 NaverRepository같은 interface형으로 하는게 더 낫다고 들은 것 같은데 확실히는 모르겠습니다 ..ㅎ

2020-09-08 12:18 UTC, ddochi93 commented on class13/HyeJeongHan/project/app/src/main/java/com/hjhan/hyejeong/ui/MainActivity.kt
> +        }
위와 마찬가지로 개행이 불필요하게 많은것같아요

2020-09-08 12:18 UTC, ddochi93 commented on class13/HyeJeongHan/project/app/src/main/java/com/hjhan/hyejeong/ui/MainActivity.kt
> +    }
저도 과제 해보고 알게되면 추가로 리뷰할게요

2020-09-09 00:54 UTC, sjjeong requested changes
@ddochi93 
변경사항이 있다면 Request changes로 해주셔야 합니다.

2020-09-09 12:36 UTC, HyeJeongHan commented on class13/HyeJeongHan/project/app/src/main/java/com/hjhan/hyejeong/data/source/remote/NaverRemoteDataSourceImpl.kt
> +    }
불필요한 개행 제거 했습니다~
27a870f

2020-09-09 12:36 UTC, HyeJeongHan commented on class13/HyeJeongHan/project/app/src/main/java/com/hjhan/hyejeong/ui/MainActivity.kt
> +        }
@ddochi93 불필요한 개행 제거 했습니다~
27a870f

2020-09-09 12:52 UTC, HyeJeongHan commented on class13/HyeJeongHan/project/app/src/main/java/com/hjhan/hyejeong/data/source/local/SharedPreferencesUtil.kt
> +            }
@ddochi93 네네 sharedpreferences 에 리스트를 바로 저장해버리고 싶었는데 리스트 타입은 바로 저장할 수 없더라고요.. 
그래서 String으로 값을 변환해서 저장하는데, 
구글링 해보니까 리스트를 JsonArray 로 변환 후 저장하는 방법이 있어서 그 방법을 사용했습니다!

2020-09-09 12:56 UTC, HyeJeongHan commented on class13/HyeJeongHan/project/app/src/main/java/com/hjhan/hyejeong/ui/MainActivity.kt
> +    }
@ddochi93 넵넵 저도 하다보니까 헷갈리는 부분도 많고, 설명 듣는 거랑 직접 구현하는 거랑 진짜 ㅋㅋㅋㅋ 천지 차이네요ㅜㅜ 피드백 있으시면 또 부탁드릴게요~

2020-09-09 14:46 UTC, sjjeong requested changes

2020-09-09 14:46 UTC, sjjeong commented on class13/HyeJeongHan/project/app/src/main/java/com/hjhan/hyejeong/data/source/local/SharedPreferencesUtil.kt
> +    fun setQueryList(query: String) {
실제로 파라미터로 전달하는건 List가 아닌 String이기 때문에 setQuery면 좋겠네요

2020-09-09 14:46 UTC, sjjeong commented on class13/HyeJeongHan/project/app/src/main/java/com/hjhan/hyejeong/ui/MainActivity.kt
> +    }
타입은 interface로 선언해주시면 됩니다

2020-09-10 11:49 UTC, HyeJeongHan commented on class13/HyeJeongHan/project/app/src/main/java/com/hjhan/hyejeong/data/source/local/SharedPreferencesUtil.kt
> +    fun setQueryList(query: String) {
@sjjeong 넵 변경했습니다. 
9fb061e

2020-09-10 11:50 UTC, HyeJeongHan commented on class13/HyeJeongHan/project/app/src/main/java/com/hjhan/hyejeong/ui/MainActivity.kt
> +    }
@sjjeong 넵 타입 변경 했습니다! 24e08be

2020-09-10 11:55 UTC, ddochi93 requested changes

2020-09-10 11:55 UTC, ddochi93 commented on class13/HyeJeongHan/project/app/src/main/java/com/hjhan/hyejeong/data/repository/NaverRepositoryImpl.kt
> +    private val naverLocalDataSourceImpl: NaverLocalDataSourceImpl
여기도 인터페이스 타입으로 받는게 좋을것같아요

2020-09-10 12:03 UTC, HyeJeongHan commented on class13/HyeJeongHan/project/app/src/main/java/com/hjhan/hyejeong/data/repository/NaverRepositoryImpl.kt
> +    private val naverLocalDataSourceImpl: NaverLocalDataSourceImpl
@ddochi93 넵 수정했습니다! 053fe79

2020-09-10 12:11 UTC, ddochi93 approved these changes

2020-09-10 12:19 UTC, ddochi93 approved these changes

2020-09-11 13:52 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-09-12 03:06 UTC, merged