Class13/sangmeebee
sjjeong/GoogryAndroidArchitecutreStudy pull request #805
Opened 2020-09-07 18:09 UTC by Sangmeebee

2020-09-08 00:52 UTC, camai commented on class13/Sangmeebee/MyProject/app/src/main/java/com/example/myproject/data/source/remote/NaverRemoteDataSourceImpl.kt
> +                    Log.e(TAG, response.message())
Failed 일 때도 데이터 전달 해주시면 좋을것 같네요.
위에 fun onFailure 에서는 실패 데이터를 리턴 받게 되어 있는데 해당 부분은 
로그만 남기시네요.

2020-09-08 01:06 UTC, camai commented on class13/Sangmeebee/MyProject/app/src/main/java/com/example/myproject/data/Preferences.kt
> +        val json = preferences.getString("SearchList", "EMPTY")
sharedpreferences 에서 "EMPTY" 문자열로 null 체크보단  null 을 추가해서 null 체크 해도 되지 않을까요?

2020-09-08 01:12 UTC, camai commented on class13/Sangmeebee/MyProject/app/src/main/java/com/example/myproject/ui/TitleAdapter.kt
> +    RecyclerView.Adapter<TitleAdapter.TitleViewHolder>() {
저와 같은 부분을 하셔서~ 리뷰 남깁니다
생성자를 통해서 리스트를 받지 않도록 수정하면 좋을것 같습니다.

2020-09-08 01:16 UTC, camai commented on class13/Sangmeebee/MyProject/app/src/main/java/com/example/myproject/ui/TitleFragmentDialog.kt
> +
setOnClickListener는 사용되지 않고 있는것 같습니다. 
동작되지 않는 부분은 제거해주시면 좋을것 같습니다.

2020-09-08 01:21 UTC, camai commented on class13/Sangmeebee/MyProject/app/src/main/res/layout/activity_main.xml
> +
새로 추가된 hitory 버튼에는 weight를 적용안하신 이유가 있을까요?
그리고 weight 경우 리니어의 orientation 기준으로 0dp를 주는걸로 알고 있습니다. 
한번 확인해보시는것도 좋을것 같습니다.

2020-09-08 01:24 UTC, camai commented
제가 확인한 내용을 리뷰로 남겼습니다.
확인 부탁드립니다.

추가로 다이얼로그에서 리사이클러뷰 아이템 클릭 시 이후 동작이 누락된것 같습니다.

2020-09-08 09:56 UTC, Sangmeebee commented on class13/Sangmeebee/MyProject/app/src/main/java/com/example/myproject/ui/TitleFragmentDialog.kt
> +
aa631ce
리사이클러뷰 아이템 클릭 시 이후 동작을 추가하면서 수정하였습니다
감사합니다

2020-09-08 09:57 UTC, Sangmeebee commented on class13/Sangmeebee/MyProject/app/src/main/java/com/example/myproject/data/source/remote/NaverRemoteDataSourceImpl.kt
> +                    Log.e(TAG, response.message())
a3a7d58
MainActivity에선 failed에 대한 처리를 해주었는데 정작 여기선 안해주었네요
감사합니다

2020-09-08 09:57 UTC, Sangmeebee commented on class13/Sangmeebee/MyProject/app/src/main/java/com/example/myproject/data/Preferences.kt
> +        val json = preferences.getString("SearchList", "EMPTY")
5ce45b4
리뷰해주신 내용으로 수정해보았습니다
감사합니다

2020-09-08 09:59 UTC, Sangmeebee commented on class13/Sangmeebee/MyProject/app/src/main/java/com/example/myproject/ui/TitleAdapter.kt
> +    RecyclerView.Adapter<TitleAdapter.TitleViewHolder>() {
c242981
변경했습니다.
혹시 생성자로 리스트를 받았을 때의 문제를 알 수 있을까요?

2020-09-08 09:59 UTC, Sangmeebee commented on class13/Sangmeebee/MyProject/app/src/main/res/layout/activity_main.xml
> +
f9c5e09
리뷰해주신 내용으로 변경했습니다
감사합니다

2020-09-08 10:05 UTC, Sangmeebee commented
다이얼로그에서 리사이클러뷰 아이템 클릭 시 이후 동작 추가했습니다!
aa631ce

2020-09-08 13:36 UTC, camai commented on class13/Sangmeebee/MyProject/app/src/main/java/com/example/myproject/ui/TitleAdapter.kt
> +    RecyclerView.Adapter<TitleAdapter.TitleViewHolder>() {
저도 찾아보고 있어요 ㅠㅠ ㅎㅎ

2020-09-08 13:39 UTC, camai approved these changes
고생하셨습니다. 멘토님께 리뷰 받으시면 될것 같습니다.

2020-09-09 14:42 UTC, sjjeong requested changes

2020-09-09 14:42 UTC, sjjeong commented on class13/Sangmeebee/MyProject/app/src/main/java/com/example/myproject/data/App.kt
> +        super.onCreate()
super.onCreate()를 나중에 부르는 이유가 있나요?

2020-09-09 14:42 UTC, sjjeong commented on class13/Sangmeebee/MyProject/app/src/main/java/com/example/myproject/data/Preferences.kt
> +    fun saveData(data: String) {
함수명이 saveData, readData보다는 saveRecentSearchQuery와 같은 명확한 이름으로 변경하면 좋겠네요

2020-09-09 14:42 UTC, sjjeong commented on class13/Sangmeebee/MyProject/app/src/main/java/com/example/myproject/ui/MainActivity.kt
> +                        repositoryDataSourceImpl.saveData(title)
save를 여기서 호출하지 않고 getMovieList안에서 데이터 가져오는 것을 성공했을때 저장하도록 해보세요

2020-09-09 14:42 UTC, sjjeong commented on class13/Sangmeebee/MyProject/app/src/main/java/com/example/myproject/ui/TitleFragmentDialog.kt
> +        }
여기서는 Fragment에 들어갈 View를 생성하고 리턴하는 작업만 해주시고 다른작업들은 onViewCreated에서 해주세요

2020-09-09 14:42 UTC, sjjeong commented on class13/Sangmeebee/MyProject/app/src/main/java/com/example/myproject/ui/MainActivity.kt
> +            val dialog = TitleFragmentDialog().newInstance(repositoryDataSourceImpl.readData())
이렇게하면 객체를 두번 만들지 않나요?
TitleFragmentDialog()에서 한번
.newInstance()에서 한번

2020-09-09 15:41 UTC, Sangmeebee commented on class13/Sangmeebee/MyProject/app/src/main/java/com/example/myproject/data/Preferences.kt
> +    fun saveData(data: String) {
감사합니다 앞으로 신경써서 메소드명 작성하겠습니다
801701a

2020-09-09 15:43 UTC, Sangmeebee commented on class13/Sangmeebee/MyProject/app/src/main/java/com/example/myproject/ui/MainActivity.kt
> +                        repositoryDataSourceImpl.saveData(title)
Model layer를 사용하는 이유를 다시 상기시켰습니다.
f7a9873

2020-09-09 15:44 UTC, Sangmeebee commented on class13/Sangmeebee/MyProject/app/src/main/java/com/example/myproject/ui/TitleFragmentDialog.kt
> +        }
감사합니다! 좋은 공부 됐습니다.
2bbc68d

2020-09-09 15:44 UTC, Sangmeebee commented on class13/Sangmeebee/MyProject/app/src/main/java/com/example/myproject/ui/MainActivity.kt
> +            val dialog = TitleFragmentDialog().newInstance(repositoryDataSourceImpl.readData())
aac1820
수정하였습니다 감사합니다!

2020-09-09 15:46 UTC, Sangmeebee commented on class13/Sangmeebee/MyProject/app/src/main/java/com/example/myproject/data/App.kt
> +        super.onCreate()
구글링을 통해 작성한 코드입니다.
저렇게 쓰라고만 나와있지 이유는 안나와있네요
super.onCreate()를 먼저 사용해도 문제가 없어 수정했습니다!
58c7f75

2020-09-10 09:34 UTC, sjjeong requested changes

2020-09-10 09:34 UTC, sjjeong commented on class13/Sangmeebee/MyProject/app/src/main/java/com/example/myproject/ui/TitleFragmentDialog.kt
> +    fun newInstance(titleList: ArrayList<String>): TitleFragmentDialog {
보통 newInstance라는 함수는 static하게 접근해서 새로운 instance를 만드는 것인데 이것은 이전에 만들어진 instance에 데이터만 set하는 형태로 되어 있습니다.
예제를 찾아보시고 함수이름에 맞게 변경해보세요

2020-09-10 09:55 UTC, Sangmeebee commented on class13/Sangmeebee/MyProject/app/src/main/java/com/example/myproject/ui/TitleFragmentDialog.kt
> +    fun newInstance(titleList: ArrayList<String>): TitleFragmentDialog {
수정해보았습니다
ae6a8de

2020-09-11 10:10 UTC, Sangmeebee commented on class13/Sangmeebee/MyProject/app/src/main/java/com/example/myproject/ui/TitleFragmentDialog.kt
> +    fun newInstance(titleList: ArrayList<String>): TitleFragmentDialog {
08c6b43

2020-09-11 13:56 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-09-11 14:05 UTC, merged