HW1 영화 검색 구현
sjjeong/GoogryAndroidArchitecutreStudy pull request #806
Opened 2020-09-12 01:16 UTC by ddochi93

2020-09-13 07:19 UTC, HyeJeongHan requested changes
잘 구현하신 것같네요! 확인부탁드려요

2020-09-13 07:19 UTC, HyeJeongHan commented on class13/ddochi93/Dkarch/app/src/main/res/layout/item_movie.xml
> +            android:text="제목 : " />
xml 전체적으로 reformat code 해주셔요

2020-09-13 07:19 UTC, HyeJeongHan commented on class13/ddochi93/Dkarch/app/src/main/java/com/example/dkarch/presentation/MainActivity.kt
> +        movieAdapter = MovieAdapter(movieList, movieItemClicked)
adapter 세팅할때 빈 리스트값을 먼저 넣어 놓는건가요?

2020-09-13 16:12 UTC, sjjeong approved these changes
일단 머지하시고 2주차, 3주차 과제 진행해주세요

2020-09-15 04:27 UTC, HyeJeongHan approved these changes

2020-09-21 09:04 UTC, merged