HW-3 MVP 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #809
Opened 2020-09-15 11:37 UTC by HyeJeongHan

mvp 적용했습니다. 이해를 잘 한건지 모르겠네요
일단 base 는 넣기는 넣어놨지만 ㅋㅋㅋㅋ 제대로 했는지는 잘 모르겠습니다
피드백 부탁드립니다!

2020-09-17 10:05 UTC, ddochi93 requested changes
전체적으로 가독성도 좋아지고 잘 하신것 같아요. 특히 BaseActivity, BasePresenter나눠서 상속하신 부분 아주 좋은것 같습니다.

Activity에서 repository를 아는게 맞는건지는 저도 모르겠어요. 공부하면서 알아보겠습니다.

2020-09-17 10:05 UTC, ddochi93 commented on class13/HyeJeongHan/project/app/src/main/java/com/hjhan/hyejeong/ui/MainActivity.kt
>      }
생성자의 인자로 repository를 넘겨주는게 아니라,  Presenter의 가야될 것 같아요. View는 Model을 모르는게 좋으니까... 맞나? 저도 잘 모르겠습니다...ㅎ

2020-09-17 10:05 UTC, ddochi93 commented on class13/HyeJeongHan/project/app/src/main/java/com/hjhan/hyejeong/ui/MainPresenter.kt
> +    private val repositoryImpl: NaverRepository
repository를 생성자의 인자로 받으면 장점도 있을것같고 단점도 있을것같은데 잘 모르겠네요ㅜ

2020-09-17 10:05 UTC, ddochi93 commented on class13/HyeJeongHan/project/app/src/main/java/com/hjhan/hyejeong/ui/MainPresenter.kt
> +                })
성공, 실패 case나눠서 view단에서 ui변경만 하게 한 코드 아주 좋은것 같습니다.

2020-09-17 10:05 UTC, ddochi93 commented on class13/HyeJeongHan/project/app/src/main/java/com/hjhan/hyejeong/ui/base/BaseActivity.kt
> +    }
'알 수 없는 에러'보다는 throwable type의 error를 받아서 error에 맞게 다른 메시지를 보여주면 더 좋을 것 같아요

2020-09-17 14:44 UTC, HyeJeongHan commented on class13/HyeJeongHan/project/app/src/main/java/com/hjhan/hyejeong/ui/MainActivity.kt
>      }
@ddochi93 Presenter에서 객체 생성을 해야한다는 말씀이시죠?

2020-09-17 14:44 UTC, HyeJeongHan commented on class13/HyeJeongHan/project/app/src/main/java/com/hjhan/hyejeong/ui/MainPresenter.kt
> +    private val repositoryImpl: NaverRepository
어렵네요..ㅜㅜ

2020-09-17 14:44 UTC, HyeJeongHan commented on class13/HyeJeongHan/project/app/src/main/java/com/hjhan/hyejeong/ui/base/BaseActivity.kt
> +    }
@ddochi93 에러 메시지 수정했습니다~
671c38c

2020-09-17 14:58 UTC, sjjeong requested changes

2020-09-17 14:58 UTC, sjjeong commented on class13/HyeJeongHan/project/app/src/main/java/com/hjhan/hyejeong/ui/MainActivity.kt
>      }
생성자로 넘기는것은 맞는데 이렇게 val로 들고있으면 안됩니다.
Presenter 객체를 만드는 37번째줄 에서 생성후 바로 생성자로 넘겨주도록 해주세요

2020-09-17 14:58 UTC, sjjeong commented on class13/HyeJeongHan/project/app/src/main/java/com/hjhan/hyejeong/ui/base/BasePresenter.kt
> +open class BasePresenter<T : BaseContract.View>() {
abstract로 해주세요

2020-09-18 11:14 UTC, HyeJeongHan commented on class13/HyeJeongHan/project/app/src/main/java/com/hjhan/hyejeong/ui/base/BasePresenter.kt
> +open class BasePresenter<T : BaseContract.View>() {
@sjjeong 수정했습니다  138c1a8

2020-09-18 11:14 UTC, HyeJeongHan commented on class13/HyeJeongHan/project/app/src/main/java/com/hjhan/hyejeong/ui/MainActivity.kt
>      }
@sjjeong 수정했습니다!  ff2afab

2020-09-18 11:15 UTC, HyeJeongHan commented
제가 깜빡하고 최근 검색어 화면 mvp 패턴을 적용 안했었네요.. 추가해뒀습니다!

2020-09-19 11:07 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-09-24 10:37 UTC, ddochi93 approved these changes
LGTM

2020-09-24 11:15 UTC, ddochi93 commented on class13/HyeJeongHan/project/app/src/main/java/com/hjhan/hyejeong/ui/base/BaseActivity.kt
> +    }
good

2020-09-24 14:05 UTC, merged