HW-3 MVP 적용(이정태)
sjjeong/GoogryAndroidArchitecutreStudy pull request #810
Opened 2020-09-15 14:27 UTC by CmplxN

MVP 적용해보았습니다.

\+ 지금 바로 필요한 건 아닌데 나중에 필요할 수도 있어 BasePresenter와 BaseDialogFragment에 Rx용 CompositeDisposable을 만들었습니다.

2020-09-15 18:00 UTC, Hwangjunhong commented
계속 봐도 깔끔하네요..! LGTM!!

2020-09-16 14:31 UTC, sjjeong requested changes

2020-09-16 14:31 UTC, sjjeong commented on class13/CmplxN/AAS/app/src/main/java/com/example/aas/ui/main/MainActivity.kt
> +                presenter.getMovies(et_movie_name.text.toString())
flatMapSingle로 처리하면 안됩니다.
subscribe로 presenter의 함수를 호출하고
presenter에서 처리 후 view의 함수를 호출하도록 해야합니다.

최근검색도 동일하게 처리해주세요

2020-09-16 14:31 UTC, sjjeong commented on class13/CmplxN/AAS/app/src/main/java/com/example/aas/ui/savedquerydialog/SavedQueryDialogFragment.kt
> +        searchHistory = presenter.getSavedQuery(arguments?.getStringArray(HISTORY_LIST))
이렇게 return하는 방식이 아닌 presenter 함수 내부에서 view의 함수를 호출해서 view가 어떤 일을 할지 해주면 됩니다.

2020-09-17 15:28 UTC, CmplxN commented on class13/CmplxN/AAS/app/src/main/java/com/example/aas/ui/main/MainActivity.kt
> +                presenter.getMovies(et_movie_name.text.toString())
240a7ee 로 적용해보았습니다.

2020-09-17 15:28 UTC, CmplxN commented on class13/CmplxN/AAS/app/src/main/java/com/example/aas/ui/savedquerydialog/SavedQueryDialogFragment.kt
> +        searchHistory = presenter.getSavedQuery(arguments?.getStringArray(HISTORY_LIST))
659cb8d 로 적용해보았습니다.
요렇게 하는게 맞는지 잘 모르겠네요.

2020-09-19 11:09 UTC, sjjeong commented on class13/CmplxN/AAS/app/src/main/java/com/example/aas/ui/savedquerydialog/SavedQueryDialogFragment.kt
> +        searchHistory = presenter.getSavedQuery(arguments?.getStringArray(HISTORY_LIST))
contract에는 리턴이 없는 함수들만 정의하면 됩니다.
view -> presenter -> view 이런식으로 함수 호출 하도록 해주시면 됩니다.

2020-09-19 11:10 UTC, sjjeong commented on class13/CmplxN/AAS/app/src/main/java/com/example/aas/ui/savedquerydialog/SavedQueryDialogFragment.kt
> +        searchHistory = presenter.getSavedQuery(arguments?.getStringArray(HISTORY_LIST))
@CmplxN 
contract에는 리턴이 없는 함수들만 정의하면 됩니다.
view -> presenter -> view 이런식으로 함수 호출 하도록 해주시면 됩니다.

2020-09-19 16:36 UTC, CmplxN commented on class13/CmplxN/AAS/app/src/main/java/com/example/aas/ui/savedquerydialog/SavedQueryDialogFragment.kt
> +        searchHistory = presenter.getSavedQuery(arguments?.getStringArray(HISTORY_LIST))
0cdf53b 로 해보았습니다.

2020-09-23 06:32 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-09-23 06:50 UTC, Hwangjunhong approved these changes
수고하셨습니다!

2020-09-23 06:51 UTC, merged