HW-2 : MODEL 구현
sjjeong/GoogryAndroidArchitecutreStudy pull request #813
Opened 2020-09-22 05:01 UTC by ddochi93

@HyeJeongHan 리뷰 부탁드립니다~

2020-09-22 13:20 UTC, HyeJeongHan requested changes
전체적으로 잘 하신것같네요 databinding도 추가 하셨군요..! 확인부탁드립니다!

2020-09-22 13:20 UTC, HyeJeongHan commented on class13/ddochi93/Dkarch/app/src/main/java/com/example/dkarch/domain/sharedpref/SharedPreferenceHelper.java
> +public class SharedPreferenceHelper {
여기는 자바코드로 넣으셧네요

2020-09-22 13:20 UTC, HyeJeongHan commented on class13/ddochi93/Dkarch/app/src/main/java/com/example/dkarch/domain/repository/NaverMovieRepository.kt
> -
혹시 이 부분은 삭제하신 이유가 있을까요? 어차피 NaverMovieRepositoryImpl 에 override 안하고 구현하시긴 하셧지만..

2020-09-24 10:45 UTC, ddochi93 commented on class13/ddochi93/Dkarch/app/src/main/java/com/example/dkarch/domain/sharedpref/SharedPreferenceHelper.java
> +public class SharedPreferenceHelper {
동아리에서 전부터 전해져내려오던 코드 재활용했습니다 ㅎㅎ

2020-09-24 11:03 UTC, ddochi93 commented on class13/ddochi93/Dkarch/app/src/main/java/com/example/dkarch/domain/repository/NaverMovieRepository.kt
> -
@HyeJeongHan NaverMovieRepository에서는 영화목록 가져오기랑 저장된 영화제목 가져오기기능만 하고, saveQuery기능은 localRepsotory에서 해야한다고 생각해서 이렇게 구현했어요. private fun 부분 없앴습니다. 
8cb84ef

2020-09-24 14:11 UTC, HyeJeongHan commented
저는 코드리뷰 끝났습니다! 전체적으로 잘 하셨네요. 코드 보면서 저도 수정해봐야겠다 하는 부분도 생겼네요

2020-09-24 14:11 UTC, HyeJeongHan approved these changes

2020-10-05 11:27 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋
머지 하시고 5주차 진행해주세요

2020-10-05 11:28 UTC, merged