HW-4 : Databinding
sjjeong/GoogryAndroidArchitecutreStudy pull request #814
Opened 2020-09-23 15:53 UTC by CmplxN

databinding 적용해봤습니다.
throttle click 관련해서 제대로 구현한 건지 모르겠네요.

2020-09-23 15:59 UTC, Hwangjunhong commented on class13/CmplxN/AAS/app/src/main/java/com/example/aas/ui/BindingAdapters.kt
> +}
이부분은 HtmlCompat 이용해서 한줄로 줄일수 있을것 같습니다

2020-09-23 16:25 UTC, Hwangjunhong commented on class13/CmplxN/AAS/app/src/main/java/com/example/aas/ui/main/MovieViewHolder.kt
> +        binding.movie = movie
binding.executePendingBindings() 이걸 적용하면 더 좋을것 같습니다

2020-09-23 16:55 UTC, Hwangjunhong commented
> databinding 적용해봤습니다.
> throttle click 관련해서 제대로 구현한 건지 모르겠네요.

제가 볼때에는 throttle click 잘 구현한것 같습니다
itemview binding 부분도 잘봤습니다!

2020-09-24 04:58 UTC, CmplxN commented on class13/CmplxN/AAS/app/src/main/java/com/example/aas/ui/BindingAdapters.kt
> +}
팁 감사드립니다!
eb40d0d

2020-09-24 04:58 UTC, CmplxN commented on class13/CmplxN/AAS/app/src/main/java/com/example/aas/ui/main/MovieViewHolder.kt
> +        binding.movie = movie
깜빡했군요 감사합니다!
70374a8

2020-09-24 07:16 UTC, Hwangjunhong approved these changes
수고하셨습니다!
LGTM!

2020-09-24 12:25 UTC, sjjeong requested changes

2020-09-24 12:25 UTC, sjjeong commented on class13/CmplxN/AAS/app/src/main/java/com/example/aas/ui/BindingAdapters.kt
> +fun View.setThrottleClick(function: PresenterMediator) {
나중에 파라미터가 있는 함수를 호출해야할 때 문제가 생깁니다.
View.OnClickListener를 파라미터로 받도록 하고 Event Binding해주세요

2020-09-24 12:25 UTC, sjjeong commented on class13/CmplxN/AAS/app/src/main/java/com/example/aas/ui/main/MainActivity.kt
> +    private val movieAdapter = MovieAdapter(presenter)
Adapter에 Presenter를 전달하지 않도록 해주세요

2020-09-25 04:59 UTC, CmplxN commented on class13/CmplxN/AAS/app/src/main/java/com/example/aas/ui/main/MainActivity.kt
> +    private val movieAdapter = MovieAdapter(presenter)
f4e8bc2 어댑터에 콜백을 주는 방식으로 하였습니다.

2020-09-25 04:59 UTC, CmplxN commented on class13/CmplxN/AAS/app/src/main/java/com/example/aas/ui/BindingAdapters.kt
> +fun View.setThrottleClick(function: PresenterMediator) {
5e04dbe 2838174
로 적용해봤습니다. 이게 맞는건지 모르겠네요.

2020-09-26 06:04 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-09-26 06:43 UTC, merged