HW-4 databinding 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #816
Opened 2020-09-24 14:34 UTC by HyeJeongHan

activity와 dialogFragmemt 쪽 databinding 적용 했습니다. 빼먹은 부분 있는지 확인부탁드립니다!

2020-09-26 01:35 UTC, ddochi93 requested changes
MainActivity 에서 DataBinding하는 부분 BaseActivity에서 해주시는거만 봐주시면 될것같아요
아직 공부가 많이 안된상태라 코드리뷰를 자세히못해드려서 죄송합니다

2020-09-26 01:35 UTC, ddochi93 commented on class13/HyeJeongHan/project/app/src/main/res/layout/activity_main.xml
> +        tools:context=".ui.MainActivity">
18라인은 <layout> 태그로 올리는게 아닌가요? 지난주 설명을 안들어서 잘 모르겠네요..

2020-09-26 01:35 UTC, ddochi93 commented on class13/HyeJeongHan/project/app/src/main/java/com/hjhan/hyejeong/ui/MainActivity.kt
> +        binding.activity = this
BaseActivity쪽에서 하는게 재사용성 면에서 더 좋을것 같습니다

2020-09-26 01:35 UTC, ddochi93 commented on class13/HyeJeongHan/project/app/src/main/java/com/hjhan/hyejeong/ui/base/BaseActivity.kt
> +abstract class BaseActivity<T : BaseContract.Presenter> : AppCompatActivity(), BaseContract.View {
MainActivity에서 DataBinding한 부분을 여기서 구현하는게 재사용성면에서 나을 것 같다고 생각합니다

2020-09-30 05:25 UTC, ddochi93 requested changes

2020-09-30 05:25 UTC, ddochi93 commented on class13/HyeJeongHan/project/app/src/main/java/com/hjhan/hyejeong/ui/QueryHistoryDialog.kt
> +            binding.dialog = this@QueryHistoryDialog
dataBinding하는코드는 따로 함수로 빼던가 해서 분리하는게 나을것같아요

2020-09-30 05:25 UTC, ddochi93 commented on class13/HyeJeongHan/project/app/src/main/java/com/hjhan/hyejeong/ui/QueryHistoryDialog.kt
>          queryHistoryAdapter = QueryHistoryAdapter()
이렇게하면 presenter에서 setRecentQueryList()호출 시마다 어댑터가 매번 새로 생성될것같은데 onCreateView()쪽으로 옮겨서 한번만 생성하도록 하는게 나을것같아요

2020-09-30 05:33 UTC, HyeJeongHan commented on class13/HyeJeongHan/project/app/src/main/java/com/hjhan/hyejeong/ui/MainActivity.kt
> +        binding.activity = this
Base로 넘겼습니다
`binding.activity = this` -> 이부분은 일부러 base로 넘기지 않았습니다. 
xml에 variable name이 무조건 activity만 사용하지는 않을것같아서 일단은 main에서 set해주는 걸로 판단했습니다~
d80ba33

2020-09-30 05:33 UTC, HyeJeongHan commented on class13/HyeJeongHan/project/app/src/main/java/com/hjhan/hyejeong/ui/base/BaseActivity.kt
> +abstract class BaseActivity<T : BaseContract.Presenter> : AppCompatActivity(), BaseContract.View {
d80ba33

2020-09-30 05:50 UTC, ddochi93 commented on class13/HyeJeongHan/project/app/src/main/java/com/hjhan/hyejeong/ui/MainActivity.kt
> +        binding.activity = this
이게 맞는것같아요~ good

2020-09-30 06:04 UTC, HyeJeongHan commented on class13/HyeJeongHan/project/app/src/main/java/com/hjhan/hyejeong/ui/QueryHistoryDialog.kt
>          queryHistoryAdapter = QueryHistoryAdapter()
계속 adapter를 생성하고 있었네요. 수정했습니다.
871ce08

2020-09-30 06:05 UTC, HyeJeongHan commented on class13/HyeJeongHan/project/app/src/main/java/com/hjhan/hyejeong/ui/QueryHistoryDialog.kt
> +            binding.dialog = this@QueryHistoryDialog
말씀해주신대로 따로 함수로 빼니까 훨씬 깔끔해보이네요. 수정했습니다.
871ce08

2020-09-30 06:08 UTC, HyeJeongHan commented on class13/HyeJeongHan/project/app/src/main/res/layout/activity_main.xml
> +        tools:context=".ui.MainActivity">
이부분은 저도 잘 모르겠습니다..
https://developer.android.com/studio/write/tool-attributes#toolscontext
화면과 레이아웃을 연결시켜준다고는 하는데 태그로 올려야하는지는 모르겠습니다.

2020-09-30 13:53 UTC, ddochi93 commented on class13/HyeJeongHan/project/app/src/main/res/layout/activity_main.xml
> +        tools:context=".ui.MainActivity">
지금 해놓으신게 맞는 것 같아요. 많은 예제에서 이렇게하고있네요

2020-09-30 13:53 UTC, ddochi93 approved these changes
LGTM

2020-10-05 11:30 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-10-05 12:25 UTC, merged