HW-5 : MVVM
sjjeong/GoogryAndroidArchitecutreStudy pull request #817
Opened 2020-09-29 21:20 UTC by Hwangjunhong

databinding과 viewmodel 같이 쓰니까 코드가 정말 깔끔해지네요
처음이라 그런지 어려웠네요..!
수정해야 할점이나 이상한부분 있으면 말씀해주시면 감사하겠습니다!

2020-09-30 06:53 UTC, CmplxN reviewed
일단 의견 남겨보았습니다. 잘못이해한 것 있으면 알려주세요.

2020-09-30 06:53 UTC, CmplxN commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ext/ButtonExt.kt
> +            dialogFragment?.show(manager, "fragmentDialog")
`show(it, "fragmentDialog")`을 의도하지 않았나 합니다.

2020-09-30 06:53 UTC, CmplxN commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ext/ContextExt.kt
> +}
구조를 변경하셔서 더이상 쓰지 않는 함수 인 것 같습니다.

2020-09-30 06:53 UTC, CmplxN commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ext/RecyclerViewExt.kt
> +    }
그냥 의견인데, 여기서 한줄짜리에 굳이 with을 쓸 필요는 없지 않을까요? (Dialog Adapter쪽도 비슷한 의견입니다.)

2020-09-30 06:53 UTC, CmplxN commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/moviedialog/MovieListDialogFragment.kt
> +    var mainViewModel: MainViewModel? = null
저번에 Adapter에 Presenter를 통째로 넘기니까 석준님이 지양하라고 하셨는데, 이렇게 세터방식으로 하는건 괜찮을련지 모르겠네요.
그래서 MainActivity에 콜백주고 거기서 Presenter 접근했었습니다.

2020-09-30 06:53 UTC, CmplxN commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/moviedialog/holder/MovieSearchListViewHolder.kt
> +                this.executePendingBindings()
`executePendingBindings()`가 가운데 줄로 들어간 이유가 따로 있나요?

2020-09-30 06:53 UTC, CmplxN commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ext/ViewExt.kt
> +@BindingAdapter("onClick")
이름이 좀더 링크 여는 것에 가까우면 어떨까요?
그냥 일반적인 클릭의 경우를 말하는 것 같습니다.

2020-09-30 06:53 UTC, CmplxN commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ext/ViewExt.kt
> +        }
url을 non-null로 하셔서 불필요한 let의 사용 같습니다.

2020-09-30 06:53 UTC, CmplxN commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/res/layout/dialog_fragment_movie_list.xml
> +            bind:setHasFixedSize="@{true}" />
상수 같은데 따로 xml에 속성으로 이렇게 하신 이유가 있을까요?

2020-09-30 13:55 UTC, Hwangjunhong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ext/ButtonExt.kt
> +            dialogFragment?.show(manager, "fragmentDialog")
5e10419
앗 감사합니다ㅎㅎ

2020-09-30 13:58 UTC, Hwangjunhong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ext/ContextExt.kt
> +}
이것은 제가 일부러 남겨놨습니다!

2020-09-30 13:59 UTC, Hwangjunhong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ext/RecyclerViewExt.kt
> +    }
80e075a
아 여기다가 원래 어답터의 데이터셋도 시켜주려고 하다가 되돌리지 않았네요! 수정하였습니다!

2020-09-30 14:01 UTC, Hwangjunhong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/moviedialog/MovieListDialogFragment.kt
> +    var mainViewModel: MainViewModel? = null
저도 그부분에 대해서는 정확히 모르겠습니다
다만 뷰모델을 최대한 이용하기 위해서 만들어봤습니다!

2020-09-30 14:02 UTC, Hwangjunhong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/moviedialog/holder/MovieSearchListViewHolder.kt
> +                this.executePendingBindings()
4e52c86
이유는 딱히 없습니다..! 그냥 순서대로 작성하다보니 그렇게 된거같습니다ㅎㅎ
수정하였습니다

2020-09-30 14:02 UTC, Hwangjunhong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ext/ViewExt.kt
> +@BindingAdapter("onClick")
f60435c

2020-09-30 14:02 UTC, Hwangjunhong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ext/ViewExt.kt
> +        }
58cfbbe

2020-09-30 14:02 UTC, Hwangjunhong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/res/layout/dialog_fragment_movie_list.xml
> +            bind:setHasFixedSize="@{true}" />
이부분도 데이터바인딩을 최대한 활용해보고자 이것저것 연습하다가 넣게됐습니다ㅎㅎ
사실상 항상 true로 적용시켜주는 부분이라 필요없긴 하지요!

2020-10-01 04:01 UTC, CmplxN commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/moviedialog/MovieListDialogFragment.kt
> +    var mainViewModel: MainViewModel? = null
저도 아직 초보라서 어떤게 좋은지 잘 모르겠네요ㅋㅋ.
석준님 코멘트를 기다려보겠습니다.

2020-10-01 04:07 UTC, CmplxN commented
뷰모델 활용 방법이라던가 저랑 스타일이 약간 달라서 긴가민가한 점은 있습니다만
아직은 보는 눈이 부족한 것 같으니 석준님, 부탁드리겠습니다.

2020-10-05 11:35 UTC, sjjeong requested changes

2020-10-05 11:35 UTC, sjjeong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ext/ButtonExt.kt
> +}
이 동작들은 사실 Activity나 Fragment에서 하시면 됩니다.
xml에서 throttleClick 리스너만 추가하고 거기서 해당 처리를 하는 함수를 호출하시면 되겠네요

BindingAdapter는 재사용되게끔 설계하는게 좋습니다.
다른부분도 다시 보시고 고쳐보세요

2020-10-05 18:44 UTC, Hwangjunhong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ext/ButtonExt.kt
> +}
77c33a0, adb6b3a
이 동작들은 다시 액티비티로 돌려놨고,
바인딩어답터로 recyclerView set 시킨 부분 MainActivity와 Dialog로 다시 돌려놨습니다!

2020-10-06 09:38 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-10-06 09:39 UTC, CmplxN approved these changes

2020-10-06 09:40 UTC, merged