HW-4 databinding 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #818
Opened 2020-09-30 07:48 UTC by Sangmeebee

늦었습니다...하하
어느부분을 적용을 더해야할지 헷갈리네요
늦었지만 리뷰 부탁드립니다!

2020-10-01 14:21 UTC, camai commented on class13/Sangmeebee/MyProject/app/src/main/java/com/example/myproject/ui/main/MainActivity.kt
> +        val title = edit_title.text.toString()
binding을 쓰셨는데 edittext id를 바로 호출하고 있는것 같습니다.
BaseActivity를 사용하셔셔 그런지.. binding에서 edittext id를 호출하는게 맞지 않나 싶네요.
이부분이 맞는지 확인이 필요할 것 같습니다.

2020-10-01 14:28 UTC, camai commented
리뷰가 늦었네요,
제가 확인한 부분을 리뷰 남겼습니다.

2020-10-01 14:29 UTC, Sangmeebee commented on class13/Sangmeebee/MyProject/app/src/main/java/com/example/myproject/ui/main/MainActivity.kt
> +        val title = edit_title.text.toString()
e3eef49
수정해보았습니다!

2020-10-02 09:07 UTC, camai approved these changes
리뷰가 늦어 죄송해요
고생하셨습니다. 스터디장님께 리뷰 받으시면 될것 같습니다.

2020-10-05 11:42 UTC, sjjeong requested changes

2020-10-05 11:42 UTC, sjjeong commented on class13/Sangmeebee/MyProject/app/src/main/java/com/example/myproject/ui/MovieAdapter.kt
> +class MovieAdapter(private val context: Context, private val movieArrayList: ArrayList<Items>) :
context는 필요하지 않고 list도 내부에서 private으로 들고있어서 외부랑 공유하지 않도록 해주세요

2020-10-05 11:42 UTC, sjjeong commented on class13/Sangmeebee/MyProject/app/src/main/java/com/example/myproject/ui/MovieAdapter.kt
> +            binding.item = item
executePendingBindings를 추가해주세요

2020-10-05 12:03 UTC, Sangmeebee commented on class13/Sangmeebee/MyProject/app/src/main/java/com/example/myproject/ui/MovieAdapter.kt
> +class MovieAdapter(private val context: Context, private val movieArrayList: ArrayList<Items>) :
c194c5d
감사합니다 수정했습니다

2020-10-05 12:05 UTC, Sangmeebee commented on class13/Sangmeebee/MyProject/app/src/main/java/com/example/myproject/ui/MovieAdapter.kt
> +            binding.item = item
761344f
즉시 업데이트하는 메소드인 executePendingBindings를 이제야 알았네요;;하하

2020-10-05 16:05 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-10-05 16:18 UTC, merged