HW-5 : MVVM
sjjeong/GoogryAndroidArchitecutreStudy pull request #819
Opened 2020-09-30 08:12 UTC by CmplxN

ObservableField + Activity에서 observer 등록으로 했습니다.
DialogFragment의 경우 VM이 필요없어 보여서 아예 없앴습니다.
(그냥 화면구성 대응도 넣어봤습니다.)

2020-09-30 13:10 UTC, Hwangjunhong commented on class13/CmplxN/AAS/app/src/main/java/com/example/aas/data/model/Movie.kt
> +) : Parcelable {
Parcelable은 자바에서 사용하던 코드로 보일러플레이트 코드가 많아지는 단점이 있습니다
Parcelable보다 Parcelize를 이용하는게 좋아보입니다!

2020-09-30 13:20 UTC, Hwangjunhong commented on class13/CmplxN/AAS/app/src/main/java/com/example/aas/ui/main/MainActivity.kt
> +        }
initBinding과는 맞지않는 코드가 들어간것 같습니다

2020-09-30 13:23 UTC, Hwangjunhong commented on class13/CmplxN/AAS/app/src/main/java/com/example/aas/ui/main/MainActivity.kt
> +        })
상태값이 변하는걸 체크하지 않아도 되는부분 같습니다!
그리고 바인딩 처리하여 액티비티에서의 코드를 줄일수 있을것 같습니다!

2020-09-30 13:35 UTC, Hwangjunhong commented on class13/CmplxN/AAS/app/src/main/java/com/example/aas/ui/main/MainActivity.kt
> +        })
이부분도 searchRequestEvent를 옵저버필드로 만들어서 상태를 관찰하기 보다 MainViewModel에 getMovies 메소드의 query를 옵저버필드로 만들어서 et_movie_name로 쿼리를 바인딩 시켜도 될것같습니다
그러면 getMovies의 생성자에 쿼리를 받지 않아도되고 보일러 플레이트코드도 줄어들것 같습니다!

2020-09-30 13:54 UTC, Hwangjunhong commented
모든 코드가 연관성이 있는거 같네요..! 
부분 부분을 찝기가 애매해서 코멘트로 남기겠습니다!
강의시간에 석준님이 말씀하신 내용에 따르면 viewmodel과 databinding을 이용하게 되면
나중에는 액티비티나 프래그먼트의 코드가 거의없고 그냥 클래스 초기화하는 정도만 남게 된다고 하셔서
저는 viewModel과 databinding을 최대한 사용해서 액티비티와 프래그먼트의 코드를 줄이는게 좋을것 같다는 생각입니다!

인터페이스를 많이 사용해서 처리하셨는데 인터페이스 대신 뷰모델과 데이터바인딩을 최대한 활용해 보는것은 어떤가 합니다!
(저의 개인적인 생각입니다! ㅎㅎ)
그렇게되면 현재 메인액티비티의 대부분의 코드는 사라질것같습니다!

명절 잘보내세요!!

2020-10-01 03:48 UTC, CmplxN commented on class13/CmplxN/AAS/app/src/main/java/com/example/aas/ui/main/MainActivity.kt
> +        })
말씀하신대로 하면 최근 검색어 선택으로 검색하면 검색어가 잠시 보이지 않나요?
(검색어 선택 -> 지운다고 해도 query에 바인딩 되어 edittext에 잠시 보임)

2020-10-01 03:49 UTC, CmplxN commented on class13/CmplxN/AAS/app/src/main/java/com/example/aas/data/model/Movie.kt
> +) : Parcelable {
팁 감사합니다. 
b353504

2020-10-01 03:49 UTC, CmplxN commented on class13/CmplxN/AAS/app/src/main/java/com/example/aas/ui/main/MainActivity.kt
> +        })
단순 이벤트도 presenter나 vm을 거쳐서 해야하나해서 위처럼 했었습니다. 거치지 않고 작동하는 것으로 변경했습니다.
cb5857c

2020-10-01 03:50 UTC, CmplxN commented on class13/CmplxN/AAS/app/src/main/java/com/example/aas/ui/main/MainActivity.kt
> +        }
그러네요. 놓친 부분 잡아주셔서 감사합니다.
cb5857c

2020-10-01 03:59 UTC, CmplxN commented
c266d3d 에서 몇가지 부분을 databinding으로 돌렸습니다.

전달할 데이터가 없거나(Unit), 특정 뷰랑 관련 없는 이벤트의 경우 databiding 대신 일반적인 옵저버 패턴을 썼습니다.

1. `searchRequestEvent` : EditText에 two-way binding 식으로 하면, 기록을 선택해서 검색할 때 잔상?이 남아서 이쪽으로 구현했습니다. 데이터 전달 없이 단순 이벤트라서 databinding을 하지 않았습니다.
2. `failureEvent` : 이것도 단순 이벤트라서 databinding을 하지 않았습니다.
3. `savedQueryResult` : 정확히 어떤 뷰랑 바인딩 되어야할지 애매해서 옵저버 패턴으로 처리했습니다.

2020-10-01 08:57 UTC, Hwangjunhong commented on class13/CmplxN/AAS/app/src/main/java/com/example/aas/ui/main/MainActivity.kt
> +        })
맞습니다! 그렇다면 쿼리는 바인딩 시키지 않고 리스너 처리하는부분만 달리해도 괜찮을것 같습니다ㅎㅎ
수고하셨습니다!

2020-10-01 08:59 UTC, Hwangjunhong commented
> [c266d3d](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/commit/c266d3dd3fa84e87bd75c9471a9eb8c309ce1266) 에서 몇가지 부분을 databinding으로 돌렸습니다.
> 
> 전달할 데이터가 없거나(Unit), 특정 뷰랑 관련 없는 이벤트의 경우 databiding 대신 일반적인 옵저버 패턴을 썼습니다.
> 
> 1. `searchRequestEvent` : EditText에 two-way binding 식으로 하면, 기록을 선택해서 검색할 때 잔상?이 남아서 이쪽으로 구현했습니다. 데이터 전달 없이 단순 이벤트라서 databinding을 하지 않았습니다.
> 2. `failureEvent` : 이것도 단순 이벤트라서 databinding을 하지 않았습니다.
> 3. `savedQueryResult` : 정확히 어떤 뷰랑 바인딩 되어야할지 애매해서 옵저버 패턴으로 처리했습니다.


사실상 아직은 정답을 모르기에 스타일의 차이? 라고 생각됩니다!
석준님에게 같이 리뷰받아보는게 좋을듯 싶습니다! ㅎㅎ
고생하셨습니다!

2020-10-01 09:00 UTC, Hwangjunhong approved these changes

2020-10-05 11:46 UTC, sjjeong requested changes

2020-10-05 11:46 UTC, sjjeong commented on class13/CmplxN/AAS/app/src/main/java/com/example/aas/base/BaseViewModel.kt
> +    val compositeDisposable = CompositeDisposable()
클래스 외부에서 사용되는게 아니라면 protected로 하면 좋겠네요

2020-10-05 12:19 UTC, CmplxN commented on class13/CmplxN/AAS/app/src/main/java/com/example/aas/base/BaseViewModel.kt
> +    val compositeDisposable = CompositeDisposable()
1ec8286
에서 protected를 추가했습니다.

2020-10-05 16:05 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-10-05 16:07 UTC, merged