HW-5 MVVM
sjjeong/GoogryAndroidArchitecutreStudy pull request #821
Opened 2020-10-05 15:36 UTC by HyeJeongHan

흐아.. 너무 어려웠지만 일단 진행해봤습니다.
extension 부분을 저렇게 사용하는 건지 잘 모르겠습니다..
데이터 세팅하는 부분을 최대한 xml 쪽으로 뺐습니다. 확인부탁드립니다.

2020-10-06 10:01 UTC, sjjeong requested changes

2020-10-06 10:01 UTC, sjjeong commented on class13/HyeJeongHan/project/app/src/main/java/com/hjhan/hyejeong/ui/MovieAdapter.kt
> +        this.list = list.toMutableList()
여기는 기존 코드를 유지하도록 해주세요 
QueryHistoryAdapter도 동일하게 해주세요

2020-10-06 10:01 UTC, sjjeong commented on class13/HyeJeongHan/project/app/src/main/java/com/hjhan/hyejeong/ui/QueryHistoryViewModel.kt
> +    fun getRecentQueryList() = repositoryImpl.getQueryList()
이렇게 하면 안되고 getQueryList의 데이터를 ObservableField형태로 가지고 있어야합니다.

2020-10-07 11:55 UTC, HyeJeongHan commented on class13/HyeJeongHan/project/app/src/main/java/com/hjhan/hyejeong/ui/MovieAdapter.kt
> +        this.list = list.toMutableList()
수정했습니다! 49e94bf

2020-10-07 11:55 UTC, HyeJeongHan commented on class13/HyeJeongHan/project/app/src/main/java/com/hjhan/hyejeong/ui/QueryHistoryViewModel.kt
> +    fun getRecentQueryList() = repositoryImpl.getQueryList()
수정했습니다~  1893c00

2020-10-08 03:51 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-10-08 03:52 UTC, sjjeong-dino approved these changes

2020-10-08 11:33 UTC, merged