HW-5 : MVVM
sjjeong/GoogryAndroidArchitecutreStudy pull request #822
Opened 2020-10-06 15:33 UTC by Sangmeebee

부족한점이 역시나 많네요
과제를 하면서 많이 배워요!!
리뷰해주시면 감사하겠습니다!

2020-10-07 01:07 UTC, camai commented on class13/Sangmeebee/MyProject/app/src/main/java/com/example/myproject/ui/MainActivity.kt
> +        binding.activity = this
해당 코드를 사용한 이유가 있을까요?

2020-10-07 01:09 UTC, camai commented on class13/Sangmeebee/MyProject/app/src/main/java/com/example/myproject/ui/MainActivity.kt
> +        })
ViewModel addOnPropertyChangedCallback 을 처리하는 로직은 따로 메소드로 만들어서 사용하시는건 어떨까요?

2020-10-07 01:22 UTC, camai commented
전반적으로 확인 시, onCreate 부분에 코드를 메소드로 만들어 정리하시는것 이외의 
다른 부분의 리뷰는 없는것 같습니다.
그리고 과제 하다 보니 recyclerview , adpter 선언을 BindingAdapter에서 사용하면 코드가 줄어들더라고요.
그런데 Slack에 스터디 장님이 올려주신 내용이 해당 부분을 사용하면 안좋다는건지 아닌지 몰라서 추가 리뷰는
스터디장님께 받으면 좋을것 같습니다.

고생하셨습니다.

2020-10-07 05:49 UTC, Sangmeebee commented on class13/Sangmeebee/MyProject/app/src/main/java/com/example/myproject/ui/MainActivity.kt
> +        binding.activity = this
xml코드에 activity에 있는 showTitleDialog 메소드를 사용하기위해 binding.activity = this 코드를 사용하여 xml에 넘겨주었습니다!

2020-10-07 05:55 UTC, Sangmeebee commented on class13/Sangmeebee/MyProject/app/src/main/java/com/example/myproject/ui/MainActivity.kt
> +        })
0814408
적용해 보았습니다~!

2020-10-07 07:33 UTC, camai commented on class13/Sangmeebee/MyProject/app/src/main/java/com/example/myproject/ui/MainActivity.kt
> +        binding.activity = this
아하 넵 궁금해서 물어보게 되었습니다.

2020-10-07 07:33 UTC, camai commented on class13/Sangmeebee/MyProject/app/src/main/java/com/example/myproject/ui/MainActivity.kt
> +        })
넵 고생하셨습니다.

2020-10-07 07:33 UTC, camai approved these changes
고생하셨습니다.
스터디 장님께 리뷰 받으시면 될것 같습니다.

2020-10-08 03:59 UTC, sjjeong requested changes

2020-10-08 03:59 UTC, sjjeong commented on class13/Sangmeebee/MyProject/app/src/main/java/com/example/myproject/ui/MainActivity.kt
> +        binding.activity = this
activity대신 viewModel을 넘겨서 처리하도록 해보세요

2020-10-08 03:59 UTC, sjjeong commented on class13/Sangmeebee/MyProject/app/src/main/java/com/example/myproject/ui/TitleAdapter.kt
> +    var mainViewModel: MainViewModel? = null
ViewModel을 전달하게 되면 TitleAdapter는 MainViewModel만 사용할 수 있게 됩니다.
결합도가 높아져서 재사용성이 떨어지고 있습니다.
ViewModel의 함수를 직접 호출하는게 아니라 이벤트를 전달하는 방식으로 처리해주세요

2020-10-08 03:59 UTC, sjjeong commented on class13/Sangmeebee/MyProject/app/src/main/java/com/example/myproject/ui/TitleFragmentDialog.kt
> +        adapter.setTitleList(vm.titleList.get() as ArrayList<String>)
ArrayList로 타입캐스팅하지 마시고 setTitleList함수의 타입을 List로 변경해주세요

2020-10-08 07:20 UTC, Sangmeebee commented on class13/Sangmeebee/MyProject/app/src/main/java/com/example/myproject/ui/TitleAdapter.kt
> +    var mainViewModel: MainViewModel? = null
cd7c517
activity대신 viewModel을 넘겨서 처리

7a2c401
ViewModel을 직접 넘기지 않고 ViewModel의 메소드를 인자로 넘기는 방식으로 변경

수정해보았습니다!

2020-10-08 07:21 UTC, Sangmeebee commented on class13/Sangmeebee/MyProject/app/src/main/java/com/example/myproject/ui/TitleFragmentDialog.kt
> +        adapter.setTitleList(vm.titleList.get() as ArrayList<String>)
dd02e2d
수정해보았습니다!

2020-10-09 07:33 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-10-09 08:02 UTC, merged