HW-5 MVVM 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #823
Opened 2020-10-07 01:02 UTC by camai

너무 많은 삽질과 부족한 부분이 많다보니 오래 걸리네요..
리뷰 부탁드립니다.

2020-10-07 20:08 UTC, Sangmeebee requested changes
이런식으로 해보면 어떨까 하는 부분에 한에서 리뷰 남깁니다 
수고하셨습니다!

2020-10-07 20:08 UTC, Sangmeebee commented on class13/camai/ArchitectureStudy/app/src/main/java/com/camai/archtecherstudy/extension/BindingViewExtension.kt
>  @BindingAdapter("ImageDrawable", "ImageDrawableError")
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/823/commits/25b6d605251fced559bba2b6003bb5d8a0824558
ImageViewAdapter의 메소드명을 imageViewAdapter로 lowerCamelCase로 작성하는 것이 좋을 것 같습니다

2020-10-07 20:08 UTC, Sangmeebee commented on class13/camai/ArchitectureStudy/app/src/main/java/com/camai/archtecherstudy/observer/MainViewModel.kt
> +    val successSearch = ObservableField<Unit>()
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/823/commits/61aab0af6c72a00a4d98d66f58db44a5baed4e76
successSearch가 있는 이유가 있나요??

2020-10-07 20:08 UTC, Sangmeebee commented on class13/camai/ArchitectureStudy/app/src/main/java/com/camai/archtecherstudy/observer/MainViewModel.kt
> +    }
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/823/commits/61aab0af6c72a00a4d98d66f58db44a5baed4e76
onClickSearch 메소드와 onSearchMoive 메소드는 중복되는 코드가 많은데 하나의 메소드로 만들 수는 없나요?

2020-10-07 20:08 UTC, Sangmeebee commented on class13/camai/ArchitectureStudy/app/src/main/java/com/camai/archtecherstudy/extension/BindingViewExtension.kt
> +}
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/823/commits/25b6d605251fced559bba2b6003bb5d8a0824558
이부분은 석준님에게 리뷰를 받아보셔야 할 것 같습니다.
공지에 올라온대로 재사용성이 떨어져 특정한 Activity나 fragment에 사용하는 코드를 사용하지 말라고 하신게 별도의 파일을 만들어 사용해서 그런건지, 하나의 파일로 만들어서 이런식으로 메소드를 추가해주면 상관없는지 그 부분이 저도 헷갈리긴 합니다

2020-10-07 20:15 UTC, Sangmeebee commented on class13/camai/ArchitectureStudy/app/src/main/java/com/camai/archtecherstudy/observer/RecentViewModel.kt
> +class RecentViewModel(private val MovieRepositoryImpl: MovieRepositoryImpl) {
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/823/commits/65d889bb5ff56a221b23445d036cb68cf29d9483
MovieRepository를 object로 선언하셔서 굳이 생성자로 안받고 사용 할 수 있을 것 같습니다.

2020-10-08 00:50 UTC, camai commented on class13/camai/ArchitectureStudy/app/src/main/java/com/camai/archtecherstudy/extension/BindingViewExtension.kt
>  @BindingAdapter("ImageDrawable", "ImageDrawableError")
메소드명에 대한 항상 어려움이 있네요 ㅎ 감사합니다.

2998f89

2020-10-08 00:53 UTC, camai commented on class13/camai/ArchitectureStudy/app/src/main/java/com/camai/archtecherstudy/observer/MainViewModel.kt
> +    val successSearch = ObservableField<Unit>()
해당 부분을 뺀줄 알았는데 들어가 있었네요
감사합니다. 

0718e70

2020-10-08 00:56 UTC, camai commented on class13/camai/ArchitectureStudy/app/src/main/java/com/camai/archtecherstudy/observer/MainViewModel.kt
> +    }
중복 되는게 있었네요 감사합니다.

7fc45d6

2020-10-08 00:57 UTC, camai commented on class13/camai/ArchitectureStudy/app/src/main/java/com/camai/archtecherstudy/extension/BindingViewExtension.kt
> +}
해당 부분은 클릭된 영화 제목을 메인에 넘겨주는 용도로 재사용하지 않아도 될것 같다 생각했습니다.

2020-10-08 01:02 UTC, camai commented on class13/camai/ArchitectureStudy/app/src/main/java/com/camai/archtecherstudy/observer/RecentViewModel.kt
> +class RecentViewModel(private val MovieRepositoryImpl: MovieRepositoryImpl) {
리뷰 주신것과 같네요.
굳이 생성자로 안받아도 되네요.
감사합니다.

4bccefe

2020-10-08 01:30 UTC, Sangmeebee commented on class13/camai/ArchitectureStudy/app/src/main/java/com/camai/archtecherstudy/observer/MainViewModel.kt
> +    }
기존에 코드에서 onSearchMovie 메소드를 아예 없에고 onClickSearch메소드만 사용해도 상관없지 않나요?
다른점이 isVisibile.set(true) 이부분과 if(name.isNullOrBlank()){ textNull.notifyChange() } 이부분인데
두 코드 모두 dialog에 item을 클릭했을 때 있어도 되는 코드여서 MainActivity에 vm.openDialog.addOnPropertyChangedCallback 메소드 안에 onSearchMovie대신 onClickSearch메소드를 사용해도 무방해 보이는데 어떻게 생각하시는지 의견 듣고 싶습니다!

2020-10-08 01:31 UTC, Sangmeebee commented on class13/camai/ArchitectureStudy/app/src/main/java/com/camai/archtecherstudy/observer/RecentViewModel.kt
> +class RecentViewModel(private val MovieRepositoryImpl: MovieRepositoryImpl) {
private var movieRepositoryImpl : MovieRepository = MovieRepositoryImpl
이렇게 선언을 해도 좋지만 변수자체를 선언을 안하고 53번째 줄에 MovieRepositoryImpl.getMovieNameSearch()로 메소드를 호출해도 될 것 같다는 생각입니다

2020-10-08 02:27 UTC, camai commented on class13/camai/ArchitectureStudy/app/src/main/java/com/camai/archtecherstudy/observer/MainViewModel.kt
> +    }
말씀해주신 리뷰가 맞더라고요

뭔가 일하다가 급하게 바꿀려니 보이지 않았나보네요

수정했습니다. 감사합니다.

4bccefe

2020-10-08 02:29 UTC, camai commented on class13/camai/ArchitectureStudy/app/src/main/java/com/camai/archtecherstudy/observer/RecentViewModel.kt
> +class RecentViewModel(private val MovieRepositoryImpl: MovieRepositoryImpl) {
네~ 감사합니다.
수정했습니다.

35a31aa

2020-10-08 02:33 UTC, Sangmeebee commented on class13/camai/ArchitectureStudy/app/src/main/java/com/camai/archtecherstudy/observer/MainViewModel.kt
> +    }
마지막으로 private var name : String = "" 은 재사용이 되지 않으니 onClickSearch 메소드 안에서 바로 초기화 시켜줘도 될것같습니다. 또한 name = keyword.get().toString() 부분에서 toString을 사용함으로써 nullable이 아니게 되었는데, 조건문에서 name.isNullOrBlank()이 사용되고 있습니다.
이부분만 수정하시면 좋을 것 같습니다

2020-10-08 04:05 UTC, camai commented on class13/camai/ArchitectureStudy/app/src/main/java/com/camai/archtecherstudy/observer/MainViewModel.kt
> +    }
name.isNullOrBlack() 일 경우 isBlack()로 변경하였습니다.
 데이터 없을 경우에 대한 Toast띄우기 위한 목적으로 사용하였습니다.
name String도 수정하였습니다.

감사합니다.

a59b75d

2020-10-08 04:45 UTC, Sangmeebee approved these changes
고생하셨습니다!

2020-10-09 08:22 UTC, sjjeong requested changes

2020-10-09 08:22 UTC, sjjeong commented on class13/camai/ArchitectureStudy/app/src/main/java/com/camai/archtecherstudy/extension/BindingViewExtension.kt
> +fun lowerCamelCase(view: ImageView, res: String?, error: Drawable) {
Sangmeebee님의 의도는 함수명을 imageViewAdapter 로 변경해달라는 거였네요

2020-10-09 08:22 UTC, sjjeong commented on class13/camai/ArchitectureStudy/app/src/main/java/com/camai/archtecherstudy/extension/BindingViewExtension.kt
> +}
이렇게하면 items을 받을때마다 adapter를 새로 set하게되고 한번만 하면 되는 작업을 여러번 하게 됩니다.
실제로는 item을 set하는 작업만 하게 하고 나머지는 Activity나 Fragment에서 하도록 해주세요
아니면 this.run 안에 있는것은 한번만 동작하도록 해주세요 

아래도 동일하게 변경해주세요

2020-10-09 08:22 UTC, sjjeong commented on class13/camai/ArchitectureStudy/app/src/main/java/com/camai/archtecherstudy/ui/main/MainActivity.kt
> +    private fun isObserverCallBack() {
is는 boolean을 리턴하는 성격의 함수 앞에 붙습니다.
is보다 setup으로 변경해주세요

2020-10-09 10:44 UTC, camai commented on class13/camai/ArchitectureStudy/app/src/main/java/com/camai/archtecherstudy/extension/BindingViewExtension.kt
> +fun lowerCamelCase(view: ImageView, res: String?, error: Drawable) {
아.. 그렇네요 ㅎㅎ 감사합니다.

233a190

2020-10-09 10:45 UTC, camai commented on class13/camai/ArchitectureStudy/app/src/main/java/com/camai/archtecherstudy/extension/BindingViewExtension.kt
> +}
아 리뷰 주신 부분은 생각해보질 못했네요..
리뷰 감사합니다.
Activity, Fragment에서 set 작업을 하도록 수정했습니다.

0a9c08b,  0cff760

2020-10-09 10:46 UTC, camai commented on class13/camai/ArchitectureStudy/app/src/main/java/com/camai/archtecherstudy/ui/main/MainActivity.kt
> +    private fun isObserverCallBack() {
넵 리뷰 주신것과 같이 함수명 수정하였습니다.
감사합니다.

a3d86d0

2020-10-10 09:50 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-10-10 16:17 UTC, merged