HW-6 : AAC ViewModel & LiveData
sjjeong/GoogryAndroidArchitecutreStudy pull request #824
Opened 2020-10-10 16:51 UTC by CmplxN

AAC ViewModel을 사용하고, ObservableField를 LiveData로 변경했습니다.

2020-10-10 20:26 UTC, Hwangjunhong commented on class13/CmplxN/AAS/app/src/main/java/com/example/aas/ui/main/MainViewModel.kt
> +    val savedQueryResult = _savedQueryResult
제가 의도하신것을 이해한게 맞을지 모르겠지만
이렇게 사용하려면 LiveData 형태여야 하지 않을까요~?
이렇게 되면 안에서나 밖에서나 get set이 가능해서 의미가 없을것같습니다!

2020-10-11 02:45 UTC, CmplxN commented on class13/CmplxN/AAS/app/src/main/java/com/example/aas/ui/main/MainViewModel.kt
> +    val savedQueryResult = _savedQueryResult
ㄷㄷ 잘못올렸군요.
a4d2b3f 로 수정했습니다.

2020-10-11 10:17 UTC, Hwangjunhong commented
이건 그냥 소소한건데 MovieAdapter 쪽에 movieList private 붙여주시면 좋을것같습니다!

2020-10-11 10:20 UTC, CmplxN commented
e306c29
에서 변경했습니다.
저번에 savedInstance를 썼었다가 방식을 바꾸면서 누락했습니다.

2020-10-11 10:23 UTC, Hwangjunhong approved these changes
Approve를 잊을뻔했네요ㅎㅎ
수고하셨습니다!!

2020-10-11 14:11 UTC, sjjeong requested changes

2020-10-11 14:11 UTC, sjjeong commented on class13/CmplxN/AAS/app/src/main/java/com/example/aas/ui/main/MainViewModel.kt
>      fun getMovies(query: String) {
query를 파라미터로 받지 않고 two way binding으로 처리해주세요

2020-10-12 12:43 UTC, CmplxN commented on class13/CmplxN/AAS/app/src/main/java/com/example/aas/ui/main/MainViewModel.kt
>      fun getMovies(query: String) {
9493864 를 참조해주세요

2020-10-13 10:48 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-10-13 14:01 UTC, merged