HW-6 : AAC ViewModel & LiveData
sjjeong/GoogryAndroidArchitecutreStudy pull request #825
Opened 2020-10-10 20:38 UTC by Hwangjunhong

AAC ViewModel을 적용시키고 LiveData로 변경하였습니다!

2020-10-11 03:41 UTC, CmplxN commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/moviedialog/MovieListDialogFragment.kt
> +        binding.lifecycleOwner = viewLifecycleOwner
binding이 여러개가 되었으면 scope function을 사용하는 것도 괜찮을 것 같습니다. (option)

2020-10-11 03:41 UTC, CmplxN commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/base/BaseActivity.kt
> +        binding.lifecycleOwner = this
```kotlin
binding = DataBindingUtil.setContentView<VDB>(this, layoutResId).apply {
    lifecycleOwner = this@BaseActivity
}
```
두줄짜리지만 위의 방식으로 할 수도 있을 것 같습니다.(option)

2020-10-11 03:41 UTC, CmplxN commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/moviedialog/MovieListDialogViewModel.kt
> +    val movieInfo = MutableLiveData<List<MovieInfo>>()
갠적으론 MainViewModel쪽도 포함해서 MutableLiveData(내부용)와 LiveData(외부용) 두개를 만들어서 쓰는게 어떤가 합니다. (option)

2020-10-11 03:41 UTC, CmplxN commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/moviedialog/MovieListDialogFragment.kt
> +        vm.movieInfo.observe {
infix function을 만들었기 때문에 아래 처럼 할 수 있을 것 같습니다.
```kotlin
vm.movieInfo observe {
    vm.movieInfo.value?.let {
        movieAdapter.setList(it)
    }
}
```
MainActivity에서도 비슷하게 세 군데 바꿀 수 있을 것 같습니다.

2020-10-11 03:41 UTC, CmplxN commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/moviedialog/MovieListDialogViewModel.kt
> +        movieInfo.postValue(list)
코루틴에서는 어떻게 다루는지 잘 모르겠지만, 간단한 방법이 있다면 메인스레드에서 setValue할 수 있으면 좋을 것 같습니다.

2020-10-11 03:41 UTC, CmplxN commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/moviedialog/MovieListDialogFragment.kt
>      var mainViewModel: MainViewModel? = null
mainViewModel도 fragment ktx의 activtyViewModels를 이용해 받아오는게 좋을 것 같습니다.

2020-10-11 05:53 UTC, Hwangjunhong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/moviedialog/MovieListDialogViewModel.kt
> +        movieInfo.postValue(list)
```
viewModelScope.launch(Dispatchers.Main) {
            _movieInfo.value = list
        }
```

이렇게 사용해볼수 있습니다.
근데 이렇게 사용하면 데이터가 실시간으로 변하지 않는 문제가 생기는데 원인 파악이 되질 않네요ㅠ

2020-10-11 05:53 UTC, Hwangjunhong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/moviedialog/MovieListDialogFragment.kt
> +        binding.lifecycleOwner = viewLifecycleOwner
2ec70e6

2020-10-11 05:54 UTC, Hwangjunhong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/base/BaseActivity.kt
> +        binding.lifecycleOwner = this
1f307e1

2020-10-11 05:56 UTC, Hwangjunhong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/moviedialog/MovieListDialogViewModel.kt
> +    val movieInfo = MutableLiveData<List<MovieInfo>>()
2b97135
Fragment쪽 만들어주는걸 깜빡했네요ㅎㅎ 
MainViewModel쪽에 LiveData를 만들지 않은 두개는 외부에서 set을 해줘야하기 때문에 그렇게 해놨는데
외부에서도 셋해줘야할 경우가 있을때는 어떻게 처리할수있나요~?

2020-10-11 05:57 UTC, Hwangjunhong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/moviedialog/MovieListDialogFragment.kt
> +        vm.movieInfo.observe {
제가 짠 코드랑 동일한것 같습니다..!

2020-10-11 05:58 UTC, Hwangjunhong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/moviedialog/MovieListDialogFragment.kt
>      var mainViewModel: MainViewModel? = null
971b829
뷰모델을 공유할수 있었죠!ㅎㅎ
전체적으로 꼼꼼히 봐주셔서 감사합니다

2020-10-11 06:08 UTC, CmplxN commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/moviedialog/MovieListDialogViewModel.kt
> +    val movieInfo = MutableLiveData<List<MovieInfo>>()
뷰모델 외부에서 처리한다면 데이터 변경 부분을 뷰모델로 옮기거나, 아니면 지금처럼 하시면 될 것 같습니다.

2020-10-11 06:09 UTC, CmplxN commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/moviedialog/MovieListDialogFragment.kt
> +        vm.movieInfo.observe {
movieInfo와 observe 사이에 `.`이 있는데 그게 없어도 된다는 뜻이었습니다. (infix function)

2020-10-11 06:15 UTC, CmplxN commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/moviedialog/MovieListDialogFragment.kt
> +        binding.lifecycleOwner = viewLifecycleOwner
전 이런 경우 “with this object, do the following.” 라는 느낌으로 [with](https://medium.com/@zzaing0502/2020%EB%85%84-%EC%83%81%EB%B0%98%EA%B8%B0-%EC%B7%A8%EC%97%85-%EC%A4%80%EB%B9%84%EC%83%9D%EC%9D%98-%ED%9A%8C%EA%B3%A0-fac2d5af475)를 썼는데, 어떤게 용례에 맞는지는 잘 모르겠네요..

2020-10-11 06:42 UTC, CmplxN commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/moviedialog/MovieListDialogFragment.kt
> +        vm.movieInfo.observe {
그리고 observe의 lambda argument로 애초에 list가 들어오므로 
```kotlin
vm.movieInfo.observe {
    movieAdapter.setList(it)
}
```
이런 식으로 해도 되지 않나 합니다.

2020-10-11 06:46 UTC, CmplxN commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/moviedialog/MovieListDialogViewModel.kt
> +        movieInfo.postValue(list)
최신 리스트 반영하기 전에 뷰모델이 죽어서 뷰모델 스코프가 도중에 터져서(?) 그런걸로 추측됩니다.
이게 코루틴을 제대로 쓰는 방법인지는 모르겠지만
```kotlin
CoroutineScope(Dispatchers.Main).launch {
    _movieInfo.value = list
}
```
이면 실시간 반영이 됩니다.

2020-10-11 07:10 UTC, Hwangjunhong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/moviedialog/MovieListDialogViewModel.kt
> +        movieInfo.postValue(list)
d03cd9c
아 맞네요 뷰모델스코프는 조금더 알아봐야 할것같네요ㅠ
코루틴스코프를 쓰게되면 작업종료를 시켜줘야해서 이렇게 반영해봤습니다!
감사합니다

2020-10-11 07:11 UTC, Hwangjunhong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/moviedialog/MovieListDialogFragment.kt
> +        binding.lifecycleOwner = viewLifecycleOwner
ace6b18
찾아보니 이런경우는 with가 더 맞는것같습니다!
감사합니다

2020-10-11 07:12 UTC, Hwangjunhong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/moviedialog/MovieListDialogFragment.kt
> +        vm.movieInfo.observe {
025cc18
맞네요..ㅠ 꼼꼼한 리뷰 정말감사드립니다

2020-10-11 10:05 UTC, CmplxN approved these changes
수고하셨습니다.

2020-10-11 14:33 UTC, sjjeong requested changes

2020-10-11 14:33 UTC, sjjeong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ext/ViewExt.kt
>  fun View.setOnClickQuery(query: String, vm: MainViewModel? = null) {
Binding Adapter 수정이 필요합니다
MainViewModel을 넘기지 않고 처리하도록 해주세요

2020-10-11 14:33 UTC, sjjeong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/main/MainActivity.kt
>              activity = this@MainActivity
binding 객체에 activity를 넘기는 것은 제거해주세요

2020-10-11 14:33 UTC, sjjeong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/main/MainActivity.kt
> +        }
observe하는 작업은 한번만 하면 되는 것이라서 이 함수안에 있을 필요는 없습니다.

2020-10-11 14:33 UTC, sjjeong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/main/MainActivity.kt
> +    }
BaseActivity를 상속받으셨으니 BaseActivity에 위치하도록 해주세요

2020-10-11 14:33 UTC, sjjeong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/moviedialog/MovieListDialogFragment.kt
> +    private val mainViewModel: MainViewModel by activityViewModels {
여기서 mainViewModel은 불필요해보입니다.
mainViewModel을 사용하지 않고 처리하도록 해보세요

2020-10-11 14:33 UTC, sjjeong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/moviedialog/MovieListDialogViewModel.kt
> +        }
이 작업은 왜 하신건가요?

2020-10-13 11:30 UTC, Hwangjunhong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/main/MainActivity.kt
> +    }
5e95a7e
수정하였습니다

2020-10-13 11:30 UTC, Hwangjunhong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/main/MainActivity.kt
> +        }
9c6cf16
수정하였습니다

2020-10-13 11:33 UTC, Hwangjunhong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/moviedialog/MovieListDialogFragment.kt
> +    private val mainViewModel: MainViewModel by activityViewModels {
0c14f33
이렇게 처리하는게 맞는지 모르겠습니다

2020-10-13 11:33 UTC, Hwangjunhong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/moviedialog/MovieListDialogViewModel.kt
> +        }
이 메소드가 룸에서 데이터를 받아오는 중이라 현재 백그라운드에서 작업중입니다
postValue를 지양하시는것 같아서 setValue로 해주기 위해서 이렇게 작업했는데 이렇게 쓰면 잘못된 작업일까요?!

2020-10-13 11:34 UTC, Hwangjunhong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/main/MainActivity.kt
>              activity = this@MainActivity
21cd569
수정하였습니다

2020-10-13 11:35 UTC, Hwangjunhong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ext/ViewExt.kt
>  fun View.setOnClickQuery(query: String, vm: MainViewModel? = null) {
32f3992
어렵네요.. 전체적으로 올바른 방법인지 모르겠습니다
수정해보았습니다!

2020-10-13 13:41 UTC, sjjeong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/main/MainActivity.kt
>              activity = this@MainActivity
커밋 아이디를 보니까 
```kotlin
binding.activity = this
```
로 그대로 넘겨주고 있네요

2020-10-13 13:42 UTC, sjjeong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/main/MainActivity.kt
> +    }
protected도 추가해주세요

2020-10-13 13:43 UTC, sjjeong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/moviedialog/MovieListDialogFragment.kt
> +    private val mainViewModel: MainViewModel by activityViewModels {
이렇게 하면 해당 Dialog는 MainActivity와 강하게 결합되서 재사용할 수 없습니다.
Dialog 이벤트 처리하는 방법을 찾아보세요

2020-10-13 13:47 UTC, sjjeong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/moviedialog/MovieListDialogViewModel.kt
> +        }
loadRecentSearchMovieList를 호출하는 시점에서 IO로 처리하고 있네요
스코프 관리를 위해서 호출하는 쪽이 아니라 함수 내부에서 비동기처리하게 해주세요

2020-10-13 22:03 UTC, Hwangjunhong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/main/MainActivity.kt
>              activity = this@MainActivity
아 이부분을 말씀하시는 거였군요
혹시 이것을 제거해야 하는 이유가 어떤건지 알수 있을까요??
bindingAdapter에 있는것을 MainActivty에서 함수로 만들어서 activity_main.xml에서 참조 한 작업입니다!
그냥 onClickListener로 만들어서 작업을 하는게 나은건가요~?
생각해보고 검색해봐도 이유가 잘 나오지 않아서 궁금합니다!

55376f2

일단은 제거후 RxView로 대체해보았습니다

2020-10-13 22:03 UTC, Hwangjunhong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/main/MainActivity.kt
> +    }
fa33879
추가하였습니다

2020-10-13 22:04 UTC, Hwangjunhong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/moviedialog/MovieListDialogViewModel.kt
> +        }
f0f9004
수정하였습니다

2020-10-13 22:08 UTC, Hwangjunhong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/moviedialog/MovieListDialogFragment.kt
> +    private val mainViewModel: MainViewModel by activityViewModels {
bb279fa, 55376f2
activity 바인딩 객체 제거후 커밋을 깜빡해서 합쳐졌네요ㅠ
일단 mainViewModel을 참조하지 않고 처리했습니다
참조하지 않으려고 역으로 데이터를 전달해줬는데 이방법이 맞는지 잘 모르겠습니다
Dialog 이벤트를 통한 해결법은 하루종일 해도 잘모르겠네요.. 
Dialog 이벤트 처리로 해결하는 방법이 어떤건지 힌트 부탁드립니다..!! 계속 생각날거같아요..
잘못된점 지적 부탁드립니다!

2020-10-16 06:35 UTC, sjjeong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/main/MainActivity.kt
>              activity = this@MainActivity
모든 이벤트나 처리는 VM를 거쳐서 진행 해야 합니다.
View는 VM에 있는 데이터나 액션에 따라서 처리하는동작만 있으면 됩니다.

2020-10-16 09:46 UTC, Hwangjunhong commented on class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/main/MainActivity.kt
>              activity = this@MainActivity
3f13281
처리하였습니다!
밑에질문 드렸던 다른 리뷰들은 괜찮은건가요~?

2020-10-16 14:30 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-10-17 01:49 UTC, merged