HW-6 AAC ViewModel & LiveData 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #828
Opened 2020-10-14 05:03 UTC by camai

ViewModel과 LiveData 적용하였습니다.

부족하지만 리뷰 부탁 드립니다.

2020-10-14 10:33 UTC, Sangmeebee requested changes
전체적으로 코드 정리를 한번 하셔야 할 것 같습니다.
안쓰는 클래스나 메소드들을 제거하시면 좋을 것 같습니다.

2020-10-14 10:33 UTC, Sangmeebee commented on class13/camai/ArchitectureStudy/app/src/main/java/com/camai/archtecherstudy/ui/rencentdialog/RecentMovieDialog.kt
> +        mvm  =  ViewModelProvider(getViewModelStoreOwner(), MainViewModelFactory())[MainViewModel::class.java]
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/828/commits/6c34a3ce23fb20aa20c139a309f5190c147ba313
getViewModelStoreOwner 를 따로 메소드로 만드신 이유가 있을까요?
바로 requireActivity를 인자로 넣어주는 방식과 차이가 있을까요?

2020-10-14 10:33 UTC, Sangmeebee commented on class13/camai/ArchitectureStudy/app/src/main/java/com/camai/archtecherstudy/ui/rencentdialog/RecentMovieDialog.kt
> +
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/828/commits/6c34a3ce23fb20aa20c139a309f5190c147ba313
isSuccess를 제거하고 
~~~
mvm.recentList.observe(viewLifecycleOwner, Observer<List<String>> {
    recentMovieAdapter.setClearAndAddList(it)
}
~~~
이런식으로 하면 불필요한 프로퍼티를 제거 할 수 있을 것 같습니다.

2020-10-14 12:05 UTC, camai commented on class13/camai/ArchitectureStudy/app/src/main/java/com/camai/archtecherstudy/ui/rencentdialog/RecentMovieDialog.kt
> +        mvm  =  ViewModelProvider(getViewModelStoreOwner(), MainViewModelFactory())[MainViewModel::class.java]
requireActivity는 getActivity가 null일 경우 IllegalStateException이 될 경우가 발생하여
확장함수를 만들어서 사용하였습니다.

2020-10-14 12:06 UTC, camai commented on class13/camai/ArchitectureStudy/app/src/main/java/com/camai/archtecherstudy/ui/rencentdialog/RecentMovieDialog.kt
> +
이렇게 사용할 수 있는지는 몰랐네요
좋은 리뷰 감사합니다.

73424f3

2020-10-14 13:05 UTC, Sangmeebee approved these changes
수고하셨습니다
제가 모르는 부분이 많아 더 정확한 리뷰 석준님께 받아보시길 바랍니다!

2020-10-16 07:39 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-10-16 07:40 UTC, merged