Class14/init readme
sjjeong/GoogryAndroidArchitecutreStudy pull request #839
Opened 2020-10-18 05:26 UTC by simuelunbo

2020-10-19 12:59 UTC, sjjeong requested changes

2020-10-19 12:59 UTC, sjjeong commented on class14/README.md
>  [공간](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/tree/master/class14/)
여기에 링크가 누락됐네요

2020-10-19 14:00 UTC, simuelunbo commented on class14/README.md
>  [공간](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/tree/master/class14/)
네 수정하였습니다

2020-10-20 13:20 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-10-21 12:31 UTC, merged