HW-1 15기 최미정 update README.md
sjjeong/GoogryAndroidArchitecutreStudy pull request #843
Opened 2020-10-18 11:45 UTC by PeonyF

class15/init-readme에 PeonyF 폴더를 만들고 이름과 폴더링크를 추가하였습니다.

2020-10-18 11:53 UTC, PeonyF commented
class15/init-readme/class15 의 메인화면에 있는 READM.md의 내용  ( github 아이디, 주소, 공간 주소) 를 변경하였습니다.

2020-10-19 13:01 UTC, sjjeong requested changes
과제 내용을 제외하고 임시 파일들(6개) 모두 제거해주세요

2020-10-20 05:42 UTC, PeonyF commented
말씀하신 임시파일(6개) 제거한 뒤 전달드립니다.
다만, 제거하는 과정에서 "git pull --rebase upstream" 코드를 사용해 모두 이전 커밋으로 돌아가서 위와 같이 3개의 파일을 리뷰 요청 드립니다.

2020-10-20 13:21 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-10-20 15:16 UTC, merged