HW-7 Hilt 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #846
Opened 2020-10-19 01:36 UTC by camai

Hilt 적용하였습니다.

리뷰 부탁 드립니다.

2020-10-21 07:15 UTC, Sangmeebee approved these changes
시험기간이라 부득이하게 리뷰를 추후에 남기겠습니다. 죄송합니다ㅠㅠㅠ
저때문에 피해를 보시면 안되니 승인 먼저 하겠습니다!

2020-10-21 14:17 UTC, sjjeong requested changes

2020-10-21 14:17 UTC, sjjeong commented on class13/camai/ArchitectureStudy/app/src/main/java/com/camai/archtecherstudy/data/repository/MovieRepositoryImpl.kt
> +    private val remoteMovieRepository: MovieRemoteDataSourceImpl
type을 interface type으로 해주세요

2020-10-22 14:01 UTC, camai commented on class13/camai/ArchitectureStudy/app/src/main/java/com/camai/archtecherstudy/data/repository/MovieRepositoryImpl.kt
> +    private val remoteMovieRepository: MovieRemoteDataSourceImpl
적용 하였습니다.

25b9323

2020-10-23 17:54 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-10-25 03:54 UTC, merged