14기 정상훈 README template 추가
sjjeong/GoogryAndroidArchitecutreStudy pull request #848
Opened 2020-10-19 10:48 UTC by hunihun

14기 정상훈 README template 추가

2020-10-19 13:04 UTC, sjjeong requested changes

2020-10-19 13:04 UTC, sjjeong commented on class14/README.md
> +[공간](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/tree/class14/init-readme/class14/hunihun)
master branch를 바라보도록 해주시면 됩니다.

2020-10-20 01:10 UTC, hunihun commented on class14/README.md
> +[공간](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/tree/class14/init-readme/class14/hunihun)
master branch 에 class14 폴더가 없는데 그냥 넣으면 될까요 ??

2020-10-20 13:27 UTC, sjjeong requested changes

2020-10-20 13:27 UTC, sjjeong commented on GoogryAndroidArchitectureStudy.iml
> +<?xml version="1.0" encoding="UTF-8"?>
과제 내용과 관련 없는 임시파일은 제거해주세요

2020-10-21 01:36 UTC, hunihun commented on GoogryAndroidArchitectureStudy.iml
> +<?xml version="1.0" encoding="UTF-8"?>
제거 했습니다! 근데 깃 관리를 지금 안드로이드 스튜디오 통해서 하고있는데 관련없는 파일들이 자동생성 됩니다... 
명령어로 깃 관리를 해야하는건가요 ???

2020-10-21 14:19 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-10-21 14:19 UTC, sjjeong commented on GoogryAndroidArchitectureStudy.iml
> +<?xml version="1.0" encoding="UTF-8"?>
커밋할때 필요한 것들만 추가해서 커밋 할 수 있습니다.

2020-10-22 01:28 UTC, merged