2주차 과제: 프로젝트 생성, gitignore 수정
sjjeong/GoogryAndroidArchitecutreStudy pull request #853
Opened 2020-10-25 05:34 UTC by juan-rybczinski

- Init GoogryAndroidArchitectureStudy project
- Update gitignore of app module

2020-10-26 14:59 UTC, sjjeong requested changes

2020-10-26 14:59 UTC, sjjeong commented on class14/juan-rybczinski/GoogryAndroidArchitectureStudy/app/.gitignore
> +# Created by https://www.toptal.com/developers/gitignore/api/android,androidstudio,kotlin
.gitignore는 app module이 아니라 project에 있는 .gitignore에 추가해야합니다.

2020-10-26 21:26 UTC, juan-rybczinski commented on class14/juan-rybczinski/GoogryAndroidArchitectureStudy/app/.gitignore
> +# Created by https://www.toptal.com/developers/gitignore/api/android,androidstudio,kotlin
반영했습니다!

2020-10-27 09:16 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-10-27 09:29 UTC, merged