HW-8 : Multi Module
sjjeong/GoogryAndroidArchitecutreStudy pull request #857
Opened 2020-10-25 18:50 UTC by Hwangjunhong

지금 깃이 꼬여버렸네요ㅠ 일단 저도 통커밋입니다..!

2020-10-25 18:51 UTC, Hwangjunhong commented
5e2068d
이거 하나만 보시면 될것 같습니다

2020-10-26 14:45 UTC, CmplxN commented on class13/Hwangjunhong/ArchitectureStudy/config.gradle
> +    implementation 'androidx.hilt:hilt-lifecycle-viewmodel:1.0.0-alpha01'
이거는 뷰모델에서만 쓰이므로 전역으로 쓰일 config.gradle이 아니라 app쪽에만 있어도 될 것 같습니다.
savedstate쪽은 쓰이지 않는 것 같습니다.

2020-10-26 14:48 UTC, CmplxN commented on class13/Hwangjunhong/ArchitectureStudy/config.gradle
> +    kapt 'androidx.hilt:hilt-compiler:1.0.0-alpha01'
이거는 뷰모델에서만 쓰이므로 전역으로 쓰일 config.gradle이 아니라 app쪽에만 있어도 될 것 같습니다.
savedstate쪽은 쓰이지 않는 것 같습니다.

2020-10-26 17:03 UTC, Hwangjunhong commented on class13/Hwangjunhong/ArchitectureStudy/config.gradle
> +    kapt 'androidx.hilt:hilt-compiler:1.0.0-alpha01'
![image](https://user-images.githubusercontent.com/33698885/97203566-562c3c80-17f8-11eb-8e97-ab27c1e3e653.png)
![image](https://user-images.githubusercontent.com/33698885/97203614-693f0c80-17f8-11eb-8a52-33d6e85e9d11.png)
진짜 git 한번 꼬인이후로 이상해졌네요.. add commit push가 다안돼서 사진으로남깁니다..! 수정했습니다

2020-10-26 17:10 UTC, CmplxN commented on class13/Hwangjunhong/ArchitectureStudy/config.gradle
> +    kapt 'androidx.hilt:hilt-compiler:1.0.0-alpha01'
근데 push가 안되면 아예 진행이 안되는거 아니에요 ㄷ?

2020-10-26 17:13 UTC, Hwangjunhong commented on class13/Hwangjunhong/ArchitectureStudy/config.gradle
> +    kapt 'androidx.hilt:hilt-compiler:1.0.0-alpha01'
그쵸.. 주말부터 지금까지 이거 고쳐보려고 별짓다해봤는데 뭐가 꼬였는지 안됩니다ㅠ 그래도 이게 마지막 커밋이된다면 문제가 없을것같기도해요

2020-10-26 17:56 UTC, CmplxN commented
저도 일단 원격으로는 준홍님 깃 문제를 어떻게 해결해야될지 모르겠어서 Mentor Needed로 전환합니다.

2020-10-27 09:17 UTC, sjjeong requested changes
pr 다시 만들어주세요
branch가 둘다 잘못됐습니다.

2020-10-27 14:02 UTC, closed without merging