fist init
sjjeong/GoogryAndroidArchitecutreStudy pull request #87
Opened 2019-07-02 14:56 UTC by onemask

2019-07-03 11:19 UTC, sjjeong requested changes
root의 README.md도 같이 수정해주세요~

2019-07-04 10:32 UTC, onemask commented
말씀하신 root Read.md라는게 
제 repo에 class03 branch인가요? 아니면 
                master branch인가요? 
일단은 class03 branch의 Read.md로 수정하여 푸시하였습니다-

2019-07-05 00:59 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-07-05 01:00 UTC, sjjeong commented
> 말씀하신 root Read.md라는게
> 제 repo에 class03 branch인가요? 아니면
> master branch인가요?
> 일단은 class03 branch의 Read.md로 수정하여 푸시하였습니다-

네 잘하셨어요
제가 의도한 root는 저장소의 맨 아래 경로를 말하는 거 였어요~
잘 수정하셨어요!

2019-07-05 02:06 UTC, merged