Class15/showmiso
sjjeong/GoogryAndroidArchitecutreStudy pull request #870
Opened 2020-11-01 02:12 UTC by showmiso

첫번째 과제입니다.

2020-11-02 07:54 UTC, sjjeong commented
@showmiso 
리뷰 요청할 때는 `Review Needed`만 있으면 됩니다.
제가 `Asnwer Needed`는 제거 했습니다.

2020-11-03 15:23 UTC, realizer12 commented on class15/showmiso/ArchitectureStudy/app/src/main/java/com/showmiso/architecturestudy/MovieAdapter.kt
> +//            val movie: Model.Movie = itemView.tag as Model.Movie
음 제생각엔  주석 처리로 비활성화 한 부분은  이유를 남기거나, 쓰지 않는다면 지우는게 어떨까요?

2020-11-03 15:26 UTC, realizer12 commented on class15/showmiso/ArchitectureStudy/app/src/main/java/com/showmiso/architecturestudy/MainActivity.kt
> +            Toast.makeText(this, "텍스트를 입력해주세요.", Toast.LENGTH_SHORT).show()
토스트에서  메세지는  리소스로 따로 빼는게 어떨까요?

2020-11-03 15:26 UTC, realizer12 commented on class15/showmiso/ArchitectureStudy/app/src/main/java/com/showmiso/architecturestudy/api/Movie.kt
> +
파일명이 Movie.kt 보단  데이터 모델임을 알려줄수 있는 명칭으로 바꾸는게 어떨까요??

2020-11-03 15:39 UTC, realizer12 commented on class15/showmiso/ArchitectureStudy/app/src/main/res/values/naver_movie_api.xml
> +    <string name="clientSecret">Whv2MSg0Ks</string>
naver_movie_api.xml 내용이 private 한 정보여서 해당 파일을 gitignore에  추가하는건 어떨까요??

2020-11-04 09:19 UTC, showmiso commented on class15/showmiso/ArchitectureStudy/app/src/main/java/com/showmiso/architecturestudy/MovieAdapter.kt
> +//            val movie: Model.Movie = itemView.tag as Model.Movie
넵 tag에 관련된 질문을 하려고 남겨놨었는데 지우고 해결해볼께요 !

2020-11-04 09:22 UTC, showmiso commented on class15/showmiso/ArchitectureStudy/app/src/main/java/com/showmiso/architecturestudy/MainActivity.kt
> +            Toast.makeText(this, "텍스트를 입력해주세요.", Toast.LENGTH_SHORT).show()
2a2cc3933d30d89c3aa47fd0e63cbec1d8aef2d6 넵 수정했습니다 !

2020-11-04 09:23 UTC, showmiso commented on class15/showmiso/ArchitectureStudy/app/src/main/java/com/showmiso/architecturestudy/api/Movie.kt
> +
57fddeb4b341d7d69c33daf811319e759d434bb9 넵 수정했습니다 !

2020-11-04 09:27 UTC, showmiso commented on class15/showmiso/ArchitectureStudy/app/src/main/java/com/showmiso/architecturestudy/api/Movie.kt
> +
b8952c1915c10bfa50fb47c443aec14cfb15917a 넵 수정했습니다 !

2020-11-04 09:34 UTC, showmiso commented on class15/showmiso/ArchitectureStudy/app/src/main/res/values/naver_movie_api.xml
> +    <string name="clientSecret">Whv2MSg0Ks</string>
이 부분은 다음주까지 꼭 수정하겠습니다..... !!

2020-11-04 15:16 UTC, sjjeong requested changes

2020-11-04 15:16 UTC, sjjeong commented on class15/showmiso/ArchitectureStudy/app/src/main/java/com/showmiso/architecturestudy/MainActivity.kt
> +    }
이거는 by lazy로 처리하면 더 좋겠네요

2020-11-04 15:16 UTC, sjjeong commented on class15/showmiso/ArchitectureStudy/app/src/main/res/values/naver_movie_api.xml
> +    <string name="clientSecret">Whv2MSg0Ks</string>
보통 string을 resource로 관리하는 것들은 다국어를 위한 것들로 합니다
이런 값들은 상수로 관리하는게 좋습니다

2020-11-04 15:16 UTC, sjjeong commented on class15/showmiso/ArchitectureStudy/app/src/main/java/com/showmiso/architecturestudy/MainActivity.kt
> +    private fun initUI() {
함수명은 `initUi`로 i를 소문자로 변경해주세요

2020-11-04 15:16 UTC, sjjeong commented on class15/showmiso/ArchitectureStudy/app/src/main/java/com/showmiso/architecturestudy/MainActivity.kt
> +        rcv_result.layoutManager = LinearLayoutManager(this)
layoutManager는 xml에서도 추가 할 수 있습니다

2020-11-04 15:16 UTC, sjjeong commented on class15/showmiso/ArchitectureStudy/app/src/main/java/com/showmiso/architecturestudy/MainActivity.kt
> +                    adapter.notifyDataSetChanged()
두개의 기능을 같이 하는 함수를 adapter에 구현하고 list만 파라미터로 넘겨주도록 해주세요

2020-11-04 15:16 UTC, sjjeong commented on class15/showmiso/ArchitectureStudy/app/src/main/java/com/showmiso/architecturestudy/MovieAdapter.kt
> +    var movies: List<MovieModel.Movie> = ArrayList()
list가 Adapter 클래스 외부와 내부가 공유되게 됩니다
private val 로 선언해서 리스트 객체를 변경하지않고 내부의 아이템을 변경하도록 해주세요

2020-11-04 15:16 UTC, sjjeong commented on class15/showmiso/ArchitectureStudy/app/src/main/java/com/showmiso/architecturestudy/MovieAdapter.kt
> +    inner class MovieViewHolder(itemView: View) : RecyclerView.ViewHolder(itemView) {
nested 클래스는 함수와 companion object 사이에 배치하도록 해주세요
그리고 inner는 제거해주세요

2020-11-04 15:16 UTC, sjjeong commented on class15/showmiso/ArchitectureStudy/app/src/main/java/com/showmiso/architecturestudy/api/APIInterface.kt
> +interface APIInterface {
ApiInterface로 변경해주세요

2020-11-04 15:16 UTC, sjjeong commented on class15/showmiso/ArchitectureStudy/app/src/main/res/layout/activity_main.xml
> +        android:layout_width="match_parent"
ConstraintLayout을 사용할 때 자식 뷰들은 match_parent대신 0dp를 사용해야 합니다

2020-11-04 15:39 UTC, showmiso commented on class15/showmiso/ArchitectureStudy/app/src/main/java/com/showmiso/architecturestudy/MainActivity.kt
> +    private fun initUI() {
멘토님 궁금한게 UI는 UserInterface의 약자인데, 약자도 Ui라고 적는게 맞나요?

2020-11-04 15:47 UTC, showmiso commented on class15/showmiso/ArchitectureStudy/app/src/main/java/com/showmiso/architecturestudy/MovieAdapter.kt
> +    var movies: List<MovieModel.Movie> = ArrayList()
014da707a1354879b10c82337aeea1ef92d8c90b 넵 ! 수정했습니다.

2020-11-04 15:47 UTC, showmiso commented on class15/showmiso/ArchitectureStudy/app/src/main/java/com/showmiso/architecturestudy/MovieAdapter.kt
> +    var movies: List<MovieModel.Movie> = ArrayList()
014da707a1354879b10c82337aeea1ef92d8c90b 수정했습니다 !

2020-11-04 15:47 UTC, showmiso commented on class15/showmiso/ArchitectureStudy/app/src/main/java/com/showmiso/architecturestudy/MainActivity.kt
> +                    adapter.notifyDataSetChanged()
014da707a1354879b10c82337aeea1ef92d8c90b 수정했습니다.!

2020-11-04 15:47 UTC, sjjeong commented on class15/showmiso/ArchitectureStudy/app/src/main/java/com/showmiso/architecturestudy/MainActivity.kt
> +    private fun initUI() {
@showmiso 
네 약어도 camelCase로 작성하시면 됩니다
https://developer.android.com/kotlin/style-guide#camel_case

2020-11-04 15:50 UTC, showmiso commented on class15/showmiso/ArchitectureStudy/app/src/main/java/com/showmiso/architecturestudy/MovieAdapter.kt
> +    inner class MovieViewHolder(itemView: View) : RecyclerView.ViewHolder(itemView) {
15de44e296bb0a8ad898472374995ac46a0236b1 수정했습니다 !

2020-11-04 16:18 UTC, showmiso commented on class15/showmiso/ArchitectureStudy/app/src/main/res/layout/activity_main.xml
> +        android:layout_width="match_parent"
08f332a79d6140f3289bfad084467b6662175ee5 수정했습니다 :)

2020-11-04 16:19 UTC, showmiso commented on class15/showmiso/ArchitectureStudy/app/src/main/java/com/showmiso/architecturestudy/MainActivity.kt
> +    }
dce306bb02923650aeb859f315a68252f169ed75 수정했습니다 !

2020-11-04 16:19 UTC, showmiso commented on class15/showmiso/ArchitectureStudy/app/src/main/res/values/naver_movie_api.xml
> +    <string name="clientSecret">Whv2MSg0Ks</string>
dce306bb02923650aeb859f315a68252f169ed75 수정했습니다 !

2020-11-04 16:20 UTC, showmiso commented on class15/showmiso/ArchitectureStudy/app/src/main/java/com/showmiso/architecturestudy/api/APIInterface.kt
> +interface APIInterface {
1e77154d9f1e8186c75be74d78ecc84d1cebccb3 수정했습니다!

2020-11-04 16:21 UTC, showmiso commented on class15/showmiso/ArchitectureStudy/app/src/main/java/com/showmiso/architecturestudy/MainActivity.kt
> +    private fun initUI() {
1e77154d9f1e8186c75be74d78ecc84d1cebccb3 수정했습니다 !

2020-11-04 16:23 UTC, showmiso commented on class15/showmiso/ArchitectureStudy/app/src/main/java/com/showmiso/architecturestudy/MainActivity.kt
> +        rcv_result.layoutManager = LinearLayoutManager(this)
c697a007429099fc7e121a1a998eada1558bf95b 수정했습니다. !

2020-11-04 16:25 UTC, showmiso commented on class15/showmiso/ArchitectureStudy/app/src/main/res/values/naver_movie_api.xml
> +    <string name="clientSecret">Whv2MSg0Ks</string>
dce306bb02923650aeb859f315a68252f169ed75 이 부분 상수화 하여 수정했습니다 !

2020-11-04 16:40 UTC, sjjeong requested changes

2020-11-04 16:40 UTC, sjjeong commented on class15/showmiso/ArchitectureStudy/app/src/main/java/com/showmiso/architecturestudy/MovieAdapter.kt
> +        this.movies = movies
이렇게 하면 리스트 객체가 같기 때문에 외부에서 리스트를 수정하는 경우에도 RecyclerView가 스크롤될때 갱신되기 때문에 버그가 발생합니다
실제로 RecyclerView는 어뎁터의 list를 갱신하려고 할때 갱신되도록 해야합니다

2020-11-05 08:11 UTC, showmiso commented on class15/showmiso/ArchitectureStudy/app/src/main/java/com/showmiso/architecturestudy/MovieAdapter.kt
> +        this.movies = movies
629e036196ef4dd218db727a73bd99ac5f5dc59d 수정했습니다.

2020-11-05 09:07 UTC, sjjeong requested changes

2020-11-05 09:07 UTC, sjjeong commented on class15/showmiso/ArchitectureStudy/app/src/main/java/com/showmiso/architecturestudy/MovieAdapter.kt
> +        this.movies = movies.toList()
이렇게 하게 되면 리스트 객체를 새로 만들게 됩니다
객체를 새로 만들지 않고 내부 데이터를 clear하고 addAll하도록 해주세요
변수 선언은 var가 아니라 val로 해주세요

2020-11-05 10:59 UTC, showmiso commented on class15/showmiso/ArchitectureStudy/app/src/main/java/com/showmiso/architecturestudy/MovieAdapter.kt
> +        this.movies = movies.toList()
256d8d8861e0a80f316d900094a5d4b62fc3ad96 확인부탁드립니다. 한번에 끝내질 못하네요...

2020-11-05 14:36 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-11-06 10:41 UTC, realizer12 approved these changes

2020-11-06 11:57 UTC, merged