HW-1 Implementing sample project
sjjeong/GoogryAndroidArchitecutreStudy pull request #871
Opened 2020-11-01 02:36 UTC by jihoi-kang

2020-11-03 05:17 UTC, PeonyF reviewed
코루틴은 제가 다뤄보지 않아서 따로 코멘트를 적지 않았습니다.
오히려 제가 지회님 코드를 보고 많이 배울 수 있어서 감사했습니다. 👍 👍

2020-11-03 05:17 UTC, ChaaaChaaa commented on class15/jihoi-kang/aas/build.gradle
> +        constraintLayoutVersion = '2.0.3'
Constraintlayout의 Version 2.0.4로 업그레드 해주세요
-> https://developer.android.com/jetpack/androidx/releases/constraintlayout

2020-11-03 05:17 UTC, ChaaaChaaa commented on class15/jihoi-kang/aas/app/src/main/res/layout/activity_main.xml
> +        android:paddingEnd="8dp"
dimens.xml 파일엔 image 관련 변수값만 있고 다른 정보는 없는데, 혹시 다른 이유가 있으신가요?
중복되는 값의 경우 재사용을 위해 dimens에 넣는게 좋을것 같아요 :)

2020-11-03 05:17 UTC, ChaaaChaaa commented on class15/jihoi-kang/aas/app/build.gradle
> +        buildConfigField "String", "NAVER_CLIENT_SECRET", "\"${getProperty("local.properties", "naver_client_secret")}\""
이렇게도 Client 값들을 보관할 수 있군요! 배우고 갑니다 👍

2020-11-03 05:17 UTC, PeonyF commented on class15/jihoi-kang/aas/app/src/main/java/com/jay/aas/ui/MovieActivity.kt
> +    }
onDestroy 함수의 경우 시스템에 의해 activity를 끝내기 전에 호출되는 함수로 알고 있습니다.
따라서 기타 함수(job.cancel()) 들이 먼저 호출된 후에 super.onDestroy()가 호출되어야 맞지않을까요? ( 궁금해서 질문드립니다.)

2020-11-03 12:31 UTC, jihoi-kang commented on class15/jihoi-kang/aas/build.gradle
> +        constraintLayoutVersion = '2.0.3'
ConstraintLayout version up 하였습니다.
[6a8c859](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/871/commits/6a8c8590f6044ac7a5c474f52c5396d9da32e6a6)

2020-11-03 12:33 UTC, jihoi-kang commented on class15/jihoi-kang/aas/app/src/main/res/layout/activity_main.xml
> +        android:paddingEnd="8dp"
중복되는 값 재사용 위해 dimens에 정의하여 사용하였습니다.
[e58f664](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/871/commits/e58f6641b2e25c715f0ad9b53870c8ec5c2b0cde)

2020-11-03 12:35 UTC, jihoi-kang commented on class15/jihoi-kang/aas/app/build.gradle
> +        buildConfigField "String", "NAVER_CLIENT_SECRET", "\"${getProperty("local.properties", "naver_client_secret")}\""
저도 최근에 알게되었습니다. Git에 client 값들을 담지않고 관리할 수 있어 보안상 장점을 가질 수 있을 것 같습니다!👍

2020-11-03 12:45 UTC, jihoi-kang commented on class15/jihoi-kang/aas/app/src/main/java/com/jay/aas/ui/MovieActivity.kt
> +    }
super.onDestroy()가 먼저 호출되어도 다음 코드인 job.cancel()이 호출되기 때문에 문제없이 동작할겁니다.
[드로이드나이츠2020 - 권태환님 발표](https://youtu.be/r8wCqh0i6w8?t=458)때 예시로 나온코드이기도 합니다.

2020-11-03 13:36 UTC, PeonyF commented on class15/jihoi-kang/aas/app/build.gradle
> +        buildConfigField "String", "NAVER_CLIENT_SECRET", "\"${getProperty("local.properties", "naver_client_secret")}\""
아하 그렇군요! 저는 ignore 해서 했었는데 이게 더 좋은방법같아요 :)

2020-11-03 13:36 UTC, PeonyF commented on class15/jihoi-kang/aas/app/src/main/java/com/jay/aas/ui/MovieActivity.kt
> +    }
아.. 그렇군요 드로이드나이츠를 다시보고 와야겠습니다. 감사합니다 👍

2020-11-03 13:40 UTC, sjjeong commented
@PeonyF 
Review Needed도 추가해주셔야 합니다

2020-11-04 15:35 UTC, sjjeong requested changes

2020-11-04 15:35 UTC, sjjeong commented on class15/jihoi-kang/aas/app/src/main/java/com/jay/aas/api/RetrofitHelper.kt
> +    fun getRetrofit(): Retrofit {
Retrofit 객체를 새로 만들 필요가 없어보입니다
val로 선언해주세요

2020-11-04 15:35 UTC, sjjeong commented on class15/jihoi-kang/aas/app/src/main/java/com/jay/aas/ui/MovieActivity.kt
> +        get() = job + Dispatchers.Main
scope를 직접 만들지 마시고 lifecycleScope를 사용해주세요

2020-11-04 15:35 UTC, sjjeong commented on class15/jihoi-kang/aas/app/src/main/java/com/jay/aas/ui/MovieActivity.kt
> +        job.cancel()
@PeonyF @jihoi-kang 
create, start, resume은 super를 맨 처음에 부르고
destory, stop, pause는 super를 맨 마지막에 호출하는게 좋습니다.
라이프 사이클을 스택에 쌓는 개념으로 생각해보시면 좋습니다

2020-11-04 15:35 UTC, sjjeong commented on class15/jihoi-kang/aas/app/src/main/java/com/jay/aas/ui/MovieActivity.kt
> +            movieService.searchMovies(query).enqueue(object : Callback<MovieResponse> {
searchMovies함수를 suspend로 만들면 콜백형태로 받아오지 않아도 됩니다

2020-11-04 15:35 UTC, sjjeong commented on class15/jihoi-kang/aas/app/src/main/java/com/jay/aas/ui/MovieAdapter.kt
> +    private var movies: List<Movie> = emptyList()
private val로 선언해서 사용해주세요
실제 아이템 변경은 clear()와 addAll()을 사용하도록 해주세요

2020-11-04 15:35 UTC, sjjeong commented on class15/jihoi-kang/aas/app/src/main/java/com/jay/aas/ui/MovieViewHolder.kt
> +            else View.VISIBLE
binding.llUserRating.isGone = movie.userRating == "0.00"을 하시면 됩니다

2020-11-05 08:32 UTC, jihoi-kang commented on class15/jihoi-kang/aas/app/src/main/java/com/jay/aas/api/RetrofitHelper.kt
> +    fun getRetrofit(): Retrofit {
수정하였습니다.
6e0eb30

2020-11-05 08:32 UTC, jihoi-kang commented on class15/jihoi-kang/aas/app/src/main/java/com/jay/aas/ui/MovieAdapter.kt
> +    private var movies: List<Movie> = emptyList()
수정하였습니다.
14bc6e3

2020-11-05 08:33 UTC, jihoi-kang commented on class15/jihoi-kang/aas/app/src/main/java/com/jay/aas/ui/MovieViewHolder.kt
> +            else View.VISIBLE
수정하였습니다.
e506675

2020-11-05 08:36 UTC, jihoi-kang commented on class15/jihoi-kang/aas/app/src/main/java/com/jay/aas/ui/MovieActivity.kt
> +            movieService.searchMovies(query).enqueue(object : Callback<MovieResponse> {
수정하였습니다.
6e16bc1

2020-11-05 08:40 UTC, jihoi-kang commented on class15/jihoi-kang/aas/app/src/main/java/com/jay/aas/ui/MovieActivity.kt
> +        get() = job + Dispatchers.Main
수정하였습니다. lifecycleScope에서 Destroyed될 때에 coroutineContext를 cancel해주는 코드가 있어 onDestory()에 있던 job.cancel()도 지워주었습니다.
628198d

2020-11-05 08:40 UTC, jihoi-kang commented on class15/jihoi-kang/aas/app/src/main/java/com/jay/aas/ui/MovieActivity.kt
> +        job.cancel()
무슨 말씀하시는지 이해했습니다!
감사합니다.

2020-11-05 09:08 UTC, sjjeong commented on class15/jihoi-kang/aas/app/src/main/java/com/jay/aas/ui/MovieActivity.kt
> +class MovieActivity : AppCompatActivity(), LifecycleObserver {
LifecycleObserver는 왜 추가하셨나요?

2020-11-05 09:12 UTC, jihoi-kang commented on class15/jihoi-kang/aas/app/src/main/java/com/jay/aas/ui/MovieActivity.kt
> +class MovieActivity : AppCompatActivity(), LifecycleObserver {
실수로 추가 되었습니다. 조심하겠습니다.
8ebc472

2020-11-05 09:26 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-11-05 09:26 UTC, sjjeong commented
@PeonyF 
더이상 리뷰할게 없다면 approve해주세요

2020-11-05 10:35 UTC, PeonyF approved these changes

2020-11-06 01:36 UTC, merged