Class14/dev donghwan
sjjeong/GoogryAndroidArchitecutreStudy pull request #872
Opened 2020-11-01 09:37 UTC by dev-donghwan

2020-11-02 12:52 UTC, onxmoreplz commented on class14/dev-donghwan/studyfork/app/src/main/java/com/example/studyfork/model/Network.kt
> +                .addHeader("X-Naver-Client-Secret", "1w6dwTIT7D")
API 호출 시 Client ID, Secet 값들은 직접적으로 노출시키지 않는 것이 좋다고 합니다.

< 참고 >
https://stackoverrun.com/ko/q/2449738

2020-11-02 12:55 UTC, onxmoreplz commented on class14/dev-donghwan/studyfork/app/src/main/res/layout/activity_main.xml
> +            android:layout_height="wrap_content" />
EditText에는 layout_weight를 속성 사용하지만, Button에서는 weight를 사용하지 않아 불필요해보입니다.

2020-11-04 09:21 UTC, dev-donghwan commented on class14/dev-donghwan/studyfork/app/src/main/res/layout/activity_main.xml
> +            android:layout_height="wrap_content" />
https://m.blog.naver.com/PostView.nhn?blogId=1579swu&logNo=50159623724&proxyReferer=https:%2F%2Fwww.google.com%2F

혹시 이 내용 고려해서 판단해주실 수 있을까요

2020-11-04 09:21 UTC, dev-donghwan commented on class14/dev-donghwan/studyfork/app/src/main/java/com/example/studyfork/model/Network.kt
> +                .addHeader("X-Naver-Client-Secret", "1w6dwTIT7D")
6c349f1

2020-11-04 12:23 UTC, onxmoreplz commented on class14/dev-donghwan/studyfork/app/src/main/res/layout/activity_main.xml
> +            android:layout_height="wrap_content" />
의도를 오해했었습니다. 그대로 쓰셔도 좋을 것 같아요.

2020-11-04 12:27 UTC, onxmoreplz commented on class14/dev-donghwan/studyfork/app/src/main/java/com/example/studyfork/model/Network.kt
> +                .addHeader("X-Naver-Client-Secret", "1w6dwTIT7D")
말씀드린 의도는 따로 string.xml 이나 local.properties 파일에 선언해두고 사용하는 것이었습니다.
사실 크게 문제있어 보이지는 않습니다.

2020-11-04 15:37 UTC, sjjeong requested changes

2020-11-04 15:37 UTC, sjjeong commented on class14/dev-donghwan/studyfork/app/src/main/java/com/example/studyfork/MainActivity.kt
> +        }
이거는 Application 클래스 구현해서 onCreate에서 호출하도록 해주세요

2020-11-05 09:09 UTC, sjjeong commented
@dev-donghwan 
코멘트에 커밋아이디 남겨주세요

2020-11-06 02:51 UTC, dev-donghwan commented on class14/dev-donghwan/studyfork/app/src/main/java/com/example/studyfork/MainActivity.kt
> +        }
026e220

2020-11-06 10:48 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-11-07 02:46 UTC, onxmoreplz approved these changes

2020-11-07 02:46 UTC, merged