HW1-First Build
sjjeong/GoogryAndroidArchitecutreStudy pull request #873
Opened 2020-11-01 12:20 UTC by onxmoreplz

단계별로 Commit 못한 점 양해부탁드립니다.

2020-11-02 04:45 UTC, dev-donghwan commented on class14/onxmoreplz/HW2_Project/app/src/main/java/com/example/hw2_project/MainActivity.kt
> +    lateinit var recyclerView : RecyclerView
View들은 내부에서만 쓰이기때문에 private를 붙여주는게 어떨까요

2020-11-02 04:47 UTC, dev-donghwan commented on class14/onxmoreplz/HW2_Project/app/src/main/java/com/example/hw2_project/MainActivity.kt
> +            .build()
Retrofit2을 보통 많이 사용하는데 어떠신가요
https://medium.com/@joycehong0524/android-studio-retrofit2-%EA%B8%B0%EB%B3%B8-%EC%82%AC%EC%9A%A9%EB%B2%95-retrofit-%EC%9D%98%EB%AC%B8%EC%A0%90-%ED%92%80%EC%96%B4%ED%97%A4%EC%B9%98%EA%B8%B0-%EC%8A%A4%EC%95%95-f150db436add

2020-11-02 04:57 UTC, dev-donghwan commented on class14/onxmoreplz/HW2_Project/app/src/main/java/com/example/hw2_project/MainActivity.kt
> +                    editTextMovieName.setText("")
지속적으로 adapter를 생성하지않고 생성된 adpater에 아이템만 교체해주는 방식으로하면 좋을거 같습니다.

2020-11-02 04:57 UTC, dev-donghwan commented on class14/onxmoreplz/HW2_Project/app/src/main/java/com/example/hw2_project/MainActivity.kt
> +            .build()
Retrofit2을 보통 많이 사용하는데 어떠신가요
https://medium.com/@joycehong0524/android-studio-retrofit2-%EA%B8%B0%EB%B3%B8-%EC%82%AC%EC%9A%A9%EB%B2%95-retrofit-%EC%9D%98%EB%AC%B8%EC%A0%90-%ED%92%80%EC%96%B4%ED%97%A4%EC%B9%98%EA%B8%B0-%EC%8A%A4%EC%95%95-f150db436add

2020-11-02 04:57 UTC, dev-donghwan commented on class14/onxmoreplz/HW2_Project/app/src/main/java/com/example/hw2_project/MainActivity.kt
> +    lateinit var recyclerView : RecyclerView
접근제한자를 private로 두는게 좋을거 같아요.

2020-11-02 04:57 UTC, dev-donghwan commented on class14/onxmoreplz/HW2_Project/app/src/main/java/com/example/hw2_project/MainActivity.kt
> +            recyclerView.setHasFixedSize(true)
https://woovictory.github.io/2020/06/24/Android-RecyclerView-Attr/

2020-11-02 04:57 UTC, dev-donghwan commented on class14/onxmoreplz/HW2_Project/app/src/main/java/com/example/hw2_project/RecyclerViewAdapter.kt
> +        val movie_director = itemView.findViewById<TextView>(R.id.textview_movie_description)
이 부분도 접근제한자를 private로 하면 좋을것같습니다.

2020-11-02 04:57 UTC, dev-donghwan commented on class14/onxmoreplz/HW2_Project/app/src/main/res/layout/movie_item.xml
> +<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
linear의 중첩이 많이 생기는 경우에 constraint가 좋을거라고 생각합니다.
https://abandonia.tistory.com/1

2020-11-04 13:36 UTC, onxmoreplz commented on class14/onxmoreplz/HW2_Project/app/src/main/java/com/example/hw2_project/MainActivity.kt
> +    lateinit var recyclerView : RecyclerView
감사합니다. 수정했습니다.

38f00b2

2020-11-04 13:37 UTC, onxmoreplz commented on class14/onxmoreplz/HW2_Project/app/src/main/java/com/example/hw2_project/MainActivity.kt
> +            recyclerView.setHasFixedSize(true)
setHasFixedSize 메서드 관련 좋은 자료 감사합니다. 
주석 수정 했습니다.

dbfc862

2020-11-04 13:38 UTC, onxmoreplz commented on class14/onxmoreplz/HW2_Project/app/src/main/java/com/example/hw2_project/RecyclerViewAdapter.kt
> +        val movie_director = itemView.findViewById<TextView>(R.id.textview_movie_description)
감사합니다. 수정했습니다.

c122ee1

2020-11-04 13:38 UTC, onxmoreplz commented on class14/onxmoreplz/HW2_Project/app/src/main/res/layout/movie_item.xml
> +<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
수정해봤습니다.

5d99063

2020-11-04 13:40 UTC, onxmoreplz commented on class14/onxmoreplz/HW2_Project/app/src/main/java/com/example/hw2_project/MainActivity.kt
> +            .build()
Retrofit2 적용은 다음주 과제하면서 같이 적용시키겠습니다.

4a559ed

2020-11-04 13:44 UTC, onxmoreplz commented on class14/onxmoreplz/HW2_Project/app/src/main/java/com/example/hw2_project/MainActivity.kt
> +                    editTextMovieName.setText("")
좋은 의견 감사합니다. 이 부분을 Adapter 클래스에 addItem() 함수를 추가하려고 하다보니 생각보다 수정할 부분이 많네요.
다음주 과제하면서 수정하겠습니다.

2020-11-04 15:56 UTC, sjjeong commented
@onxmoreplz 
과제 전부 반영했다면 짝꿍이 리뷰할 수 있도록 라벨을 변경해주셔야 합니다
@dev-donghwan 
남기신 코멘트에 리뷰 확인해주세요

2020-11-05 08:43 UTC, sjjeong commented
@dev-donghwan 
approve하시고 Review Needed도 추가해주세요

2020-11-05 08:49 UTC, dev-donghwan approved these changes

2020-11-05 09:15 UTC, sjjeong requested changes

2020-11-05 09:15 UTC, sjjeong commented on class14/onxmoreplz/HW2_Project/app/src/main/java/com/example/hw2_project/MainActivity.kt
> +    val clientSecret = "v8aD8p_Ri0"
외부에서 사용하는게 아니라면 private을 추가해주세요

2020-11-05 09:15 UTC, sjjeong commented on class14/onxmoreplz/HW2_Project/app/src/main/java/com/example/hw2_project/MainActivity.kt
> +            recyclerView.setHasFixedSize(true)
이거는 버튼 누를때마다 할 필요는 없습니다
초기화 하는 단계에서 한번만 하게 해주세요

2020-11-05 09:15 UTC, sjjeong commented on class14/onxmoreplz/HW2_Project/app/src/main/java/com/example/hw2_project/MainActivity.kt
> +    fun fetchJson(vararg p0 : String){
private으로 변경해주시고 함수명과 파라미터를 의미있는 용어로 변경해주세요

2020-11-05 09:15 UTC, sjjeong commented on class14/onxmoreplz/HW2_Project/app/src/main/java/com/example/hw2_project/MainActivity.kt
> +                    recyclerView.adapter = RecyclerViewAdapter(moviefeed)
Adapter를 매번 추가하지 않고 한번만 추가하도록 하고
아이템을 변경함으로써 Adapter에 notify하도록 해주세요

이번 과제에서 진행해주세요

2020-11-05 11:22 UTC, onxmoreplz commented on class14/onxmoreplz/HW2_Project/app/src/main/java/com/example/hw2_project/MainActivity.kt
> +    val clientSecret = "v8aD8p_Ri0"
추가했습니다.

29cdab9

2020-11-05 11:23 UTC, onxmoreplz commented on class14/onxmoreplz/HW2_Project/app/src/main/java/com/example/hw2_project/MainActivity.kt
> +            recyclerView.setHasFixedSize(true)
객체 생성 후 한 번만 적용하도록 코드 위치 변경했습니다.

59fd57a

2020-11-05 11:24 UTC, onxmoreplz commented on class14/onxmoreplz/HW2_Project/app/src/main/java/com/example/hw2_project/MainActivity.kt
> +    fun fetchJson(vararg p0 : String){
접근제한자 추가 및 함수명, 파라미명 변경했습니다.

488c177

2020-11-05 11:25 UTC, onxmoreplz commented on class14/onxmoreplz/HW2_Project/app/src/main/java/com/example/hw2_project/MainActivity.kt
> +                    recyclerView.adapter = RecyclerViewAdapter(moviefeed)
Adapter 한 번만 생성한 후, Item 변경 시 notify할 수 있는 함수 만들었습니다.


d050045

2020-11-05 14:45 UTC, sjjeong requested changes

2020-11-05 14:45 UTC, sjjeong commented on class14/onxmoreplz/HW2_Project/app/src/main/java/com/example/hw2_project/MainActivity.kt
> +    private val mAdapter = RecyclerViewAdapter()
kotlin에서는 m을 붙이지 않습니다

2020-11-05 14:45 UTC, sjjeong commented on class14/onxmoreplz/HW2_Project/app/src/main/java/com/example/hw2_project/MainActivity.kt
> +                    recyclerView.adapter = mAdapter
RecyclerView에 adapter를 set하는 코드를 여기가 아니라 초기화 하는 부분에서 하게 해주세요

2020-11-05 15:47 UTC, onxmoreplz commented on class14/onxmoreplz/HW2_Project/app/src/main/java/com/example/hw2_project/MainActivity.kt
> +    private val mAdapter = RecyclerViewAdapter()
변수명앞에 멤버변수임을 표시하는 건 JAVA에서만 하는군요. 수정하였습니다.

c16e3d7

2020-11-05 15:48 UTC, onxmoreplz commented on class14/onxmoreplz/HW2_Project/app/src/main/java/com/example/hw2_project/MainActivity.kt
> +                    recyclerView.adapter = mAdapter
RecyclerView 어댑터 설정 초기화하는 부분으로 수정하였습니다.


49bfd27

2020-11-06 10:49 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-11-06 13:34 UTC, merged