HW-1 영화 검색 및 목록 출력 과제
sjjeong/GoogryAndroidArchitecutreStudy pull request #874
Opened 2020-11-01 12:46 UTC by dktsudgg

첫번째 과제입니다.

2020-11-03 14:56 UTC, hhi-5258 reviewed
커밋 메세지는 (HW-n xxx) 형식으로 작성하여야 한다고 합니다!

https://github.com/StudyFork/GoogryAndroidArchitectureStudy/tree/master/sjjeong

2020-11-03 14:56 UTC, hhi-5258 commented on class15/dktsudgg/AndroidArchitectureStudy/app/src/main/java/kr/dktsudgg/androidarchitecturestudy/view/adapter/MovieListAdapter.kt
> +    }
Html.fromHtml 이 N버전 부터 deprecated 되었다고 합니다.
버전을 분기 처리하는 것을 추천드립니다!

2020-11-03 14:56 UTC, hhi-5258 commented on class15/dktsudgg/AndroidArchitectureStudy/app/src/main/res/values/strings.xml
> +    <string name="naver_client_secret">vyGKaZQhsK</string>
저도 그냥 로컬에 박긴 했지만, 보안을 위해서 api key 값은 
1) 따로 xml 파일에 저장한 후 gitignore에 추가하거나
2) local.properties 에 저장하는 방법 들이 있다고 합니다!

2020-11-03 15:21 UTC, dktsudgg commented
> 커밋 메세지는 (HW-n xxx) 형식으로 작성하여야 한다고 합니다!
> 
> https://github.com/StudyFork/GoogryAndroidArchitectureStudy/tree/master/sjjeong

2020-11-03 15:34 UTC, dktsudgg commented on class15/dktsudgg/AndroidArchitectureStudy/app/src/main/java/kr/dktsudgg/androidarchitecturestudy/view/adapter/MovieListAdapter.kt
> +    }
pr에만 prefix 붙여서 요청하는걸로 착각해서 커밋메세지 리베이스 했습니다ㅜㅜ

Html.fromHtml 메소드 버전별 대응하는 소스 커밋하였습니다!
c91591a

감사합니다!

2020-11-03 16:36 UTC, dktsudgg commented on class15/dktsudgg/AndroidArchitectureStudy/app/src/main/res/values/strings.xml
> +    <string name="naver_client_secret">vyGKaZQhsK</string>
6d6b80e
이미 커밋 히스토리에 남아서 큰 의미는 없지만ㅠㅠ secrets.properties라는 파일을 app디렉토리 밑에 생성하여 네이버 id, secret값들을 명세한 뒤에, 그 설정값들을 빌드시점에 BuildConfig 클래스의 멤버변수로 끼워넣어주는 코드를 app/build.gradle에 작성하여 적용해보았습니다!

2020-11-04 08:57 UTC, hhi-5258 commented on class15/dktsudgg/AndroidArchitectureStudy/app/src/main/res/values/strings.xml
> +    <string name="naver_client_secret">vyGKaZQhsK</string>
저도 공부하고 있던 중이라 규진님의 코드를 많이 참고하였습니다! 감사합니다!

2020-11-04 15:46 UTC, sjjeong requested changes

2020-11-04 15:46 UTC, sjjeong commented on class15/dktsudgg/AndroidArchitectureStudy/app/src/main/java/kr/dktsudgg/androidarchitecturestudy/MainActivity.kt
> +        searchedMovieList.layoutManager = LinearLayoutManager(this);
layoutManager는 xml에서 추가 하실 수 있습니다

2020-11-04 15:46 UTC, sjjeong commented on class15/dktsudgg/AndroidArchitectureStudy/app/src/main/java/kr/dktsudgg/androidarchitecturestudy/MainActivity.kt
> +    fun searchMovie(context: Context, searchText: String) {
MainActivity가 Context라서 this로 접근하면 되기 때문에 context를 파라미터로 전달할 필요는 없습니다
private으로 변경해주시고 refreshSearchedMovieList도 동일하게 반영해주세요

2020-11-04 15:46 UTC, sjjeong commented on class15/dktsudgg/AndroidArchitectureStudy/app/src/main/java/kr/dktsudgg/androidarchitecturestudy/MainActivity.kt
> +        }
이렇게 하면 검색 할 때 마다 Adapter를 새로 만들어서 비효율적인 코드가 됩니다
Adapter는 한번만 만들도록 하시고 내부 List의 아이템을 갱신하고 notify를 호출하도록 해주세요

2020-11-04 15:46 UTC, sjjeong commented on class15/dktsudgg/AndroidArchitectureStudy/app/src/main/java/kr/dktsudgg/androidarchitecturestudy/api/WebRequestManager.kt
> +class WebRequestManager {
이 클래스를 객체화 시켜서 사용하지 않기 때문에 object로 만드시면 됩니다

2020-11-04 15:46 UTC, sjjeong commented on class15/dktsudgg/AndroidArchitectureStudy/app/src/main/java/kr/dktsudgg/androidarchitecturestudy/view/adapter/MovieListAdapter.kt
> +class MovieListAdapter(val context: Context, var movieList: MutableList<MovieItem>) :
context는 외부에서 받아올 필요가 없습니다.
ViewGroup이나 View가 결국 context를 가지고 있습니다

movieList도 생성자를 통해서 받지 마시고 내부적으로 private val 로 선언해서 관리해주세요

2020-11-04 15:46 UTC, sjjeong commented on class15/dktsudgg/AndroidArchitectureStudy/app/src/main/java/kr/dktsudgg/androidarchitecturestudy/view/adapter/MovieListAdapter.kt
> +            .into(holder.image);
해당 작업을 ViewHolder 안에 함수로 빼서 사용해주세요

2020-11-05 12:59 UTC, dktsudgg commented on class15/dktsudgg/AndroidArchitectureStudy/app/src/main/java/kr/dktsudgg/androidarchitecturestudy/MainActivity.kt
> +        searchedMovieList.layoutManager = LinearLayoutManager(this);
80dee98
xml로 이관하였습니다. 감사합니다!

2020-11-05 13:15 UTC, dktsudgg commented on class15/dktsudgg/AndroidArchitectureStudy/app/src/main/java/kr/dktsudgg/androidarchitecturestudy/MainActivity.kt
> +    fun searchMovie(context: Context, searchText: String) {
4f6cfb0
액티비티 내부에서만 사용하는 메소드를 private으로 선언, Context를 파라미터로 받는 부분을 제거하였습니다.
감사합니다!

2020-11-05 13:43 UTC, dktsudgg commented on class15/dktsudgg/AndroidArchitectureStudy/app/src/main/java/kr/dktsudgg/androidarchitecturestudy/MainActivity.kt
> +        }
80168b7
어댑터 객체를 새로 할당하지않고, 어댑터 내부에서 리스트로 관리 및 갱신하도록 수정하였습니다.
감사합니다!

2020-11-05 13:52 UTC, dktsudgg commented on class15/dktsudgg/AndroidArchitectureStudy/app/src/main/java/kr/dktsudgg/androidarchitecturestudy/api/WebRequestManager.kt
> +class WebRequestManager {
b03994f
수정하였습니다. 감사합니다!

2020-11-05 14:00 UTC, dktsudgg commented on class15/dktsudgg/AndroidArchitectureStudy/app/src/main/java/kr/dktsudgg/androidarchitecturestudy/view/adapter/MovieListAdapter.kt
> +class MovieListAdapter(val context: Context, var movieList: MutableList<MovieItem>) :
83877c4
수정하였습니다. 감사합니다!

2020-11-05 14:09 UTC, dktsudgg commented on class15/dktsudgg/AndroidArchitectureStudy/app/src/main/java/kr/dktsudgg/androidarchitecturestudy/view/adapter/MovieListAdapter.kt
> +            .into(holder.image);
abdc22f
수정하였습니다. 감사합니다!

2020-11-05 14:46 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-11-07 09:01 UTC, hhi-5258 approved these changes

2020-11-07 09:02 UTC, merged