HW-1 영화 검색 및 출력 과제
sjjeong/GoogryAndroidArchitecutreStudy pull request #875
Opened 2020-11-01 13:31 UTC by realizer12

2020-11-02 10:56 UTC, showmiso requested changes
- ApiServices 
Header Key 값을 적용하는 나이스한 방법이 뭔지 좀 헷갈리는데요. 
코드상에서 Header Annotation으로 바로 넣는 것은 나중에 문제가 될 수 있어요.
Play Store에 올릴경우 경고가 뜹니다.
- RetrofitClient, ServerIp
이 클래스는 코드정렬이 필요합니다.

2020-11-02 11:02 UTC, showmiso requested changes
코드 중간에 불필요한 줄바꿈은 가독성을 떨어트립니다.

2020-11-02 11:02 UTC, showmiso commented on class15/realizer12/AndroidArchitectureStudy/app/src/main/java/com/example/androidarchitecturestudy/MainActivity.kt
> +        retrofitClient = RetrofitClient(ServerIp.naverMovieApiUrl)
getMovieDate() 함수 내에서 retrofitClient 변수를 초기화합니다.
함수를 호출할때마다 초기화하는 것보단 onCreate할 때 한번만 초기화하는게 좋을 것 같아요.

2020-11-02 11:09 UTC, showmiso requested changes
code 내에 typo 나 warning은 최대한 없애는게 좋아요.
Naver 같은 typo는 project-level dictionary로 typo를 없앨 수 있습니다. 
주석 다음에 한칸 띄워주세요 ! (ex. // 주석)

2020-11-02 11:09 UTC, showmiso commented on class15/realizer12/AndroidArchitectureStudy/app/src/main/java/com/example/androidarchitecturestudy/adapter/MovieListRecyclerViewAdapter.kt
> +        val tvMovieTitle = itemview.findViewById<TextView>(R.id.tv_movie_title)
ViewHolder 내부에서 findViewById 를 호출하지 않아도
itemView.tv_movie_title 로 접근이 가능해요.

2020-11-02 11:09 UTC, showmiso commented on class15/realizer12/AndroidArchitectureStudy/app/src/main/java/com/example/androidarchitecturestudy/adapter/MovieListRecyclerViewAdapter.kt
> +            Html.fromHtml(htmlText).toString()
deprecated된 함수는 쓰지 않는게 좋습니다. (어차피 나중에 수정해야하기 때문이죠.)
Play Store에 올릴경우 경고가 떠요.

2020-11-02 11:09 UTC, showmiso commented on class15/realizer12/AndroidArchitectureStudy/app/src/main/java/com/example/androidarchitecturestudy/MainActivity.kt
> +                    Log.v("check_log", t.message.toString())
error 로그는 Log.e("") 를 사용하는게 좋아요.
로그를 용도에 따라서 사용하면 Logcat에서 보기도 좋습니다.

2020-11-02 11:10 UTC, showmiso reviewed
이상입니다. 고생하셨습니다 👍

2020-11-04 00:18 UTC, realizer12 commented on class15/realizer12/AndroidArchitectureStudy/app/src/main/java/com/example/androidarchitecturestudy/MainActivity.kt
> +        retrofitClient = RetrofitClient(ServerIp.naverMovieApiUrl)
06cc2f5

2020-11-04 00:19 UTC, realizer12 commented on class15/realizer12/AndroidArchitectureStudy/app/src/main/java/com/example/androidarchitecturestudy/adapter/MovieListRecyclerViewAdapter.kt
> +        val tvMovieTitle = itemview.findViewById<TextView>(R.id.tv_movie_title)
06cc2f5 해당 수정 사항  반영했습니다.

2020-11-04 00:22 UTC, realizer12 commented on class15/realizer12/AndroidArchitectureStudy/app/src/main/java/com/example/androidarchitecturestudy/adapter/MovieListRecyclerViewAdapter.kt
> +        val tvMovieTitle = itemview.findViewById<TextView>(R.id.tv_movie_title)
53beccd. 수정 하였습니다!

2020-11-04 10:06 UTC, realizer12 commented on class15/realizer12/AndroidArchitectureStudy/app/src/main/java/com/example/androidarchitecturestudy/MainActivity.kt
> +                    Log.v("check_log", t.message.toString())
53beccd. 수정사항 반영했습니다!

2020-11-04 10:08 UTC, realizer12 commented on class15/realizer12/AndroidArchitectureStudy/app/src/main/java/com/example/androidarchitecturestudy/adapter/MovieListRecyclerViewAdapter.kt
> +        val tvMovieTitle = itemview.findViewById<TextView>(R.id.tv_movie_title)
d7a1a1d  전체 주석 및 typo , warning문제 수정 하였습니다!

2020-11-04 10:10 UTC, realizer12 commented on class15/realizer12/AndroidArchitectureStudy/app/src/main/java/com/example/androidarchitecturestudy/adapter/MovieListRecyclerViewAdapter.kt
> +        val tvMovieTitle = itemview.findViewById<TextView>(R.id.tv_movie_title)
ed399c2  뷰홀더 findviewbyid 문제 해결하였습니다!

2020-11-04 10:12 UTC, realizer12 commented on class15/realizer12/AndroidArchitectureStudy/app/src/main/java/com/example/androidarchitecturestudy/MainActivity.kt
> +        retrofitClient = RetrofitClient(ServerIp.naverMovieApiUrl)
d46bc5d  RetrofitClient, ServerIp 클래스 코드정렬  진행하였습니다!

2020-11-04 13:30 UTC, realizer12 commented on class15/realizer12/AndroidArchitectureStudy/app/src/main/java/com/example/androidarchitecturestudy/adapter/MovieListRecyclerViewAdapter.kt
> +            Html.fromHtml(htmlText).toString()
03e3fd5. deprecated 된  함수 부분  수정 하엿습니다.

2020-11-04 13:31 UTC, realizer12 commented on class15/realizer12/AndroidArchitectureStudy/app/src/main/java/com/example/androidarchitecturestudy/MainActivity.kt
> +        retrofitClient = RetrofitClient(ServerIp.naverMovieApiUrl)
header key 부분은 이번주 안에  적용하겠습니다.!

2020-11-04 15:54 UTC, sjjeong requested changes

2020-11-04 15:54 UTC, sjjeong commented on class15/realizer12/AndroidArchitectureStudy/app/src/main/java/com/example/androidarchitecturestudy/MainActivity.kt
> +    }
해당 처리는 Lifecycle과 관련되지 않아서 직접 선언과 초기화를 같이 해주셔도 됩니다

2020-11-04 15:54 UTC, sjjeong commented on class15/realizer12/AndroidArchitectureStudy/app/src/main/java/com/example/androidarchitecturestudy/MainActivity.kt
> +            layoutManager = GridLayoutManager(this@MainActivity, 2)//그리드 형태로
layoutManager는 xml에서 처리 할 수 있습니다

2020-11-04 15:54 UTC, sjjeong commented on class15/realizer12/AndroidArchitectureStudy/app/src/main/java/com/example/androidarchitecturestudy/MainActivity.kt
> +    private fun searchMovie() {
함수이름은 영화검색이라는 의미로 영화를 검색하는 것 같지만 실제로는 ui들의 동작처리 입니다
적절한 이름으로 함수명을 변경해주세요

2020-11-04 15:54 UTC, sjjeong commented on class15/realizer12/AndroidArchitectureStudy/app/src/main/java/com/example/androidarchitecturestudy/MainActivity.kt
> +    private fun updateRecyclerView(movieList: ArrayList<GetMovieInfo.MovieData>) {
type은 List로 변경해주세요
파라미터로 넘어오는 자료형은 보통 List, Map, Set등으로 interface를 사용합니다

2020-11-04 15:54 UTC, sjjeong commented on class15/realizer12/AndroidArchitectureStudy/app/src/main/java/com/example/androidarchitecturestudy/Retrofit/ServerIp.kt
> +    companion object{
이렇게 사용하는 거라면 ServerIp를 object로 만들어주세요

2020-11-04 15:54 UTC, sjjeong commented on class15/realizer12/AndroidArchitectureStudy/app/src/main/java/com/example/androidarchitecturestudy/adapter/MovieListRecyclerViewAdapter.kt
> +class MovieListRecyclerViewAdapter(private val context: Context) :
adapter는 context를 외부에서 받지 않아도 됩니다

2020-11-04 15:54 UTC, sjjeong commented on class15/realizer12/AndroidArchitectureStudy/app/src/main/java/com/example/androidarchitecturestudy/adapter/MovieListRecyclerViewAdapter.kt
> +    private var movieList = ArrayList<GetMovieInfo.MovieData>()
list 객체를 val로 선언하고 list 내부 아이템을 교체하는 식으로 처리해주세요

2020-11-04 15:54 UTC, sjjeong commented on class15/realizer12/AndroidArchitectureStudy/app/src/main/java/com/example/androidarchitecturestudy/adapter/MovieListRecyclerViewAdapter.kt
> +    fun getMovieData(movieList: ArrayList<GetMovieInfo.MovieData>) {
함수명은 get보다 set이 적절하겠네요
보통 get은 값을 리턴하는 성격을 가집니다

2020-11-04 15:54 UTC, sjjeong commented on class15/realizer12/AndroidArchitectureStudy/app/src/main/java/com/example/androidarchitecturestudy/adapter/MovieListRecyclerViewAdapter.kt
> +        val rtbMovieGrade = itemview.rtb_movie_grade
private으로 선언해주세요

2020-11-04 15:54 UTC, sjjeong commented on class15/realizer12/AndroidArchitectureStudy/app/src/main/res/layout/activity_main.xml
> +        android:layout_width="match_parent"
ConstraintLayout 자식 View들은 match_parent를 사용하지 않습니다

2020-11-06 11:48 UTC, realizer12 commented on class15/realizer12/AndroidArchitectureStudy/app/src/main/java/com/example/androidarchitecturestudy/MainActivity.kt
> +    }
3bd7d3e. 해당 내용 반영하였습니다!!

2020-11-06 11:49 UTC, realizer12 commented on class15/realizer12/AndroidArchitectureStudy/app/src/main/java/com/example/androidarchitecturestudy/MainActivity.kt
> +            layoutManager = GridLayoutManager(this@MainActivity, 2)//그리드 형태로
4302f1b  xml처리로 수정 하였습니다!

2020-11-06 11:49 UTC, realizer12 commented on class15/realizer12/AndroidArchitectureStudy/app/src/main/java/com/example/androidarchitecturestudy/MainActivity.kt
> +    private fun searchMovie() {
cd9b0d0  initEventListeners()로  함수명 변경하였습니다!

2020-11-06 11:50 UTC, realizer12 commented on class15/realizer12/AndroidArchitectureStudy/app/src/main/java/com/example/androidarchitecturestudy/MainActivity.kt
> +    private fun updateRecyclerView(movieList: ArrayList<GetMovieInfo.MovieData>) {
f252039  list로 변경하였습니다!

2020-11-06 11:50 UTC, realizer12 commented on class15/realizer12/AndroidArchitectureStudy/app/src/main/java/com/example/androidarchitecturestudy/Retrofit/ServerIp.kt
> +    companion object{
5a1dd44  object로  변경하였습니다!

2020-11-06 11:51 UTC, realizer12 commented on class15/realizer12/AndroidArchitectureStudy/app/src/main/java/com/example/androidarchitecturestudy/adapter/MovieListRecyclerViewAdapter.kt
> +class MovieListRecyclerViewAdapter(private val context: Context) :
7a9cd2c  context  adapter내부에서  처리하도록 수정하였습니다!

2020-11-06 11:52 UTC, realizer12 commented on class15/realizer12/AndroidArchitectureStudy/app/src/main/java/com/example/androidarchitecturestudy/adapter/MovieListRecyclerViewAdapter.kt
> +    private var movieList = ArrayList<GetMovieInfo.MovieData>()
964b27d  해당 내용 수정 하였습니다!

2020-11-06 11:52 UTC, realizer12 commented on class15/realizer12/AndroidArchitectureStudy/app/src/main/java/com/example/androidarchitecturestudy/adapter/MovieListRecyclerViewAdapter.kt
> +    fun getMovieData(movieList: ArrayList<GetMovieInfo.MovieData>) {
0479558  set으로 수정하였습니다!

2020-11-06 11:53 UTC, realizer12 commented on class15/realizer12/AndroidArchitectureStudy/app/src/main/res/layout/activity_main.xml
> +        android:layout_width="match_parent"
61efcdf  0dp로 수정하였습니다!

2020-11-06 11:53 UTC, realizer12 commented on class15/realizer12/AndroidArchitectureStudy/app/src/main/java/com/example/androidarchitecturestudy/adapter/MovieListRecyclerViewAdapter.kt
> +        val rtbMovieGrade = itemview.rtb_movie_grade
a2fb806  private 으로  수정하였습니다!

2020-11-06 12:46 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-11-07 06:37 UTC, realizer12 commented on class15/realizer12/AndroidArchitectureStudy/app/src/main/java/com/example/androidarchitecturestudy/MainActivity.kt
> +        retrofitClient = RetrofitClient(ServerIp.naverMovieApiUrl)
fbd5242. 네이버  api 키 BuildConfig 로  옮겨서  처리하였습니다!

2020-11-07 07:17 UTC, showmiso approved these changes

2020-11-07 07:18 UTC, merged