HW-1 영화 검색 프로젝트
sjjeong/GoogryAndroidArchitecutreStudy pull request #876
Opened 2020-11-01 14:04 UTC by simuelunbo

코틀린을 시작한지 얼마 안되서 코드가 자바스럽다 던가 좀 어색하거나
Volley 라이브러리를 자주 사용해서 Retrofit은 잘 안써봐 코드적으 어색한 부분이 있습니다
그 부분을 중심으로 피드백 해주시면 감사 하겠습니다.

2020-11-03 15:34 UTC, Myung777 commented on class14/simuelunbo/AndroidArchitectureStudy/app/src/main/java/com/example/androidarchitecturestudy/ui/MainActivity.kt
> +                   Log.e("MainActivity", response.message())
progressBar가 검색이 실패했을때 없어지지 않는 이슈가 있을것 같습니다.

2020-11-03 15:34 UTC, Myung777 commented on class14/simuelunbo/AndroidArchitectureStudy/app/src/main/res/layout/item_movie.xml
> +        android:background="#FAF0F0"
색상은 style 파일에 넣어서 사용하는게 좋을것 같습니다.

2020-11-03 15:34 UTC, Myung777 commented on class14/simuelunbo/AndroidArchitectureStudy/app/src/main/java/com/example/androidarchitecturestudy/ui/MovieHolder.kt
> +        itemView.tv_director_name.text = movie.director
director도 title 처럼 필요없는 단어는 replace 가 되었으면 보기 좋을것 같아요

2020-11-03 15:37 UTC, Myung777 commented
코틀린을 제가 잘몰라서 좋은 리뷰를 못드려서 죄송합니다.
과제한다고 고생하셨습니다.

2020-11-04 03:49 UTC, simuelunbo commented on class14/simuelunbo/AndroidArchitectureStudy/app/src/main/java/com/example/androidarchitecturestudy/ui/MainActivity.kt
> +                   Log.e("MainActivity", response.message())
c41c48428f2f3d2381f3a4b28cc2f1ac02d2d167 네 수정하였습니다

2020-11-04 03:50 UTC, simuelunbo commented on class14/simuelunbo/AndroidArchitectureStudy/app/src/main/res/layout/item_movie.xml
> +        android:background="#FAF0F0"
dbab64423be2c6ad6b6805217ddee2b4bec1dd7d

2020-11-04 03:50 UTC, simuelunbo commented on class14/simuelunbo/AndroidArchitectureStudy/app/src/main/java/com/example/androidarchitecturestudy/ui/MovieHolder.kt
> +        itemView.tv_director_name.text = movie.director
94d98110657d4b6c74a4114c43e01c59b8ba865b

2020-11-04 03:54 UTC, simuelunbo commented
아니에요 저도 코틀린 배우는 중이라서 저도 리뷰하면서 놓친것들이 있을꺼에요 
서로서로 부족한거 채워 나가면서 잘해봐요 :)

2020-11-04 16:03 UTC, sjjeong requested changes

2020-11-04 16:03 UTC, sjjeong commented on class14/simuelunbo/AndroidArchitectureStudy/app/src/main/java/com/example/androidarchitecturestudy/ui/MainActivity.kt
> +        recyclerViewInit()
보편적으로 함수는 동사로 시작합니다
init을 앞으로 옮겨주세요

2020-11-04 16:03 UTC, sjjeong commented on class14/simuelunbo/AndroidArchitectureStudy/app/src/main/java/com/example/androidarchitecturestudy/ui/MainActivity.kt
> +                progressBar.isVisible = true
progressBar를 visible하는 것을 requestMovieInfo함수 안으로 옮기면 좋겠습니다.
추후에 requestMovieInfo를 다른곳에서 호출 했을 때 progressBar가 보이지 않는 버그가 나올 수 있는 확률이 높은 코드입니다

2020-11-04 16:03 UTC, sjjeong commented on class14/simuelunbo/AndroidArchitectureStudy/app/src/main/java/com/example/androidarchitecturestudy/ui/MovieAdapter.kt
> +    fun setMovieList(movieList: ArrayList<Movie>){
movieList type을 List로 변경해주세요

2020-11-04 16:03 UTC, sjjeong commented on class14/simuelunbo/AndroidArchitectureStudy/app/src/main/java/com/example/androidarchitecturestudy/ui/MovieAdapter.kt
> +    private var movies = ArrayList<Movie>()
val로 선언해주세요

2020-11-04 16:03 UTC, sjjeong commented on class14/simuelunbo/AndroidArchitectureStudy/app/src/main/res/layout/activity_main.xml
> +        android:layout_width="match_parent"
ConstraintLayout에서는 match_parent를 사용하지않고 0dp를 사용합니다

2020-11-05 04:56 UTC, simuelunbo commented on class14/simuelunbo/AndroidArchitectureStudy/app/src/main/java/com/example/androidarchitecturestudy/ui/MainActivity.kt
> +        recyclerViewInit()
a548009c1a90f39b1ce97531b5e83a4734702f84 네 변경하였습니다

2020-11-05 04:57 UTC, simuelunbo commented on class14/simuelunbo/AndroidArchitectureStudy/app/src/main/java/com/example/androidarchitecturestudy/ui/MainActivity.kt
> +                progressBar.isVisible = true
그 부분을 생각 하지 못했네요 531447371c9a8a3536313795988e80d1d268e0a2 수정했습니다

2020-11-05 04:57 UTC, simuelunbo commented on class14/simuelunbo/AndroidArchitectureStudy/app/src/main/java/com/example/androidarchitecturestudy/ui/MovieAdapter.kt
> +    fun setMovieList(movieList: ArrayList<Movie>){
2dbf6c6a901990af6abeeb92bf6972630a5387d3

2020-11-05 04:58 UTC, simuelunbo commented on class14/simuelunbo/AndroidArchitectureStudy/app/src/main/java/com/example/androidarchitecturestudy/ui/MovieAdapter.kt
> +    private var movies = ArrayList<Movie>()
2dbf6c6a901990af6abeeb92bf6972630a5387d3

2020-11-05 04:58 UTC, simuelunbo commented on class14/simuelunbo/AndroidArchitectureStudy/app/src/main/res/layout/activity_main.xml
> +        android:layout_width="match_parent"
2736af0f005af527f23e16ba5f87aa895b038201 수정 하였습니다

2020-11-05 09:10 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-11-05 09:10 UTC, sjjeong commented
@Myung777 
Mentor Needed 추가 해주실때는 approve도 같이 해주시면 됩니다

2020-11-05 12:09 UTC, Myung777 approved these changes

2020-11-05 12:23 UTC, merged