HW-1 영화 검색 과제
sjjeong/GoogryAndroidArchitecutreStudy pull request #878
Opened 2020-11-01 15:26 UTC by Myung777

2020-11-03 10:18 UTC, simuelunbo reviewed
한곳에 class를 모아 놓는것 보다 하위 package directory 생성해서 api, activity, adapter등 구분 하는것이 좋아보입니다

2020-11-03 10:18 UTC, simuelunbo commented on class14/myung777/StudyFork/app/src/main/java/com/deepco/studyfork/MainActivity.kt
> +        api.getSearchNews(name).enqueue(object : Callback<MovieData> {
getSearchNews는 뭔가 신문 기사나 뉴스 찾는 느낌이 강해요 getSearchNews 보단 getSearchMovie가 더 낫지 않을까요?

2020-11-03 10:18 UTC, simuelunbo commented on class14/myung777/StudyFork/app/src/main/java/com/deepco/studyfork/MainActivity.kt
> +                LinearLayoutManager(this@MainActivity, LinearLayoutManager.VERTICAL, false)
LinearLayoutManager XML 파일에 추가 할수 있어요
https://jamie-dev.tistory.com/57

2020-11-03 10:18 UTC, simuelunbo commented on class14/myung777/StudyFork/app/src/main/java/com/deepco/studyfork/RecyclerAdapterMovie.kt
> +        return this.modelList.size
list.size랑 값은 같지만 count를 써보시는건 어떤가요 코드의 길이도 짧아지고 효율적인걸로 알고 있어요
https://www.reddit.com/r/Kotlin/comments/7k5vi3/kotlin_collections_difference_between_size_and/

2020-11-03 10:18 UTC, simuelunbo commented on class14/myung777/StudyFork/app/src/main/res/layout/activity_main.xml
> +<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
나중에 디자인을 수정하거나, 확장성을 생각 해봤을때 
LinearLayout보단 Constraintlayout 쓰는게 더 바람직 하다고 생각합니다

2020-11-03 10:18 UTC, simuelunbo commented on class14/myung777/StudyFork/app/src/main/res/layout/movie_item.xml
> +<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
activity_main.xml과 마찬가지로  Constraintlayout 쓰는것이 바람직 하다고 생각합니다

2020-11-03 16:08 UTC, Myung777 commented on class14/myung777/StudyFork/app/src/main/res/layout/activity_main.xml
> +<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
Constraintlayout 으로 변경하였습니다.
77aabd5

2020-11-03 16:08 UTC, Myung777 commented on class14/myung777/StudyFork/app/src/main/java/com/deepco/studyfork/MainActivity.kt
> +                LinearLayoutManager(this@MainActivity, LinearLayoutManager.VERTICAL, false)
xml에서 설정해보았습니다
8fee3b6

2020-11-03 16:09 UTC, Myung777 commented on class14/myung777/StudyFork/app/src/main/java/com/deepco/studyfork/MainActivity.kt
> +        api.getSearchNews(name).enqueue(object : Callback<MovieData> {
네이밍 변경하였습니다.
8fee3b6

2020-11-03 16:09 UTC, Myung777 commented on class14/myung777/StudyFork/app/src/main/java/com/deepco/studyfork/RecyclerAdapterMovie.kt
> +        return this.modelList.size
네 감사합니다. 한번 사용해볼게요
b5bc656

2020-11-04 04:01 UTC, simuelunbo commented on class14/myung777/StudyFork/app/src/main/res/layout/activity_main.xml
> +<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
아 제가 말하던거는 부모만 Constraintlayout 으로 변경 하는게 어떤가 말했던거 였어요. 
필요에 따라 Linearlayout 쓰는건 괜찮아요
근데 이렇게 변경 하셔도 크게 상관은 없을듯 하네요

2020-11-04 16:04 UTC, sjjeong commented
@simuelunbo 
Mentor Needed 추가 해주실때는 approve도 같이 해주세요

2020-11-04 16:13 UTC, sjjeong requested changes

2020-11-04 16:13 UTC, sjjeong commented on class14/myung777/StudyFork/app/src/main/java/com/deepco/studyfork/MainActivity.kt
> +    var movieList = ArrayList<Item>()
이 변수는 필요해 보이지 않습니다
제거해주세요

2020-11-04 16:13 UTC, sjjeong commented on class14/myung777/StudyFork/app/src/main/java/com/deepco/studyfork/RecyclerAdapterMovie.kt
> +    fun setItemList(modelList: ArrayList<Item>) {
modelList type은 List로 변경해주세요

2020-11-04 16:13 UTC, sjjeong commented on class14/myung777/StudyFork/app/src/main/java/com/deepco/studyfork/RecyclerAdapterMovie.kt
> +        this.modelList = modelList
=이 아니라 addAll로 처리해주세요

2020-11-04 16:13 UTC, sjjeong commented on class14/myung777/StudyFork/app/src/main/java/com/deepco/studyfork/api/RetrofitService.kt
> +            httpLoggingInterceptor.level = HttpLoggingInterceptor.Level.BODY
BuildConfig가 DEBUG가 아니면 NONE을 set하도록 해주세요

2020-11-05 01:09 UTC, simuelunbo approved these changes

2020-11-05 13:04 UTC, Myung777 commented on class14/myung777/StudyFork/app/src/main/java/com/deepco/studyfork/MainActivity.kt
> +    var movieList = ArrayList<Item>()
필요 없는 변수 삭제했습니다.
2e0748d

2020-11-05 13:04 UTC, Myung777 commented on class14/myung777/StudyFork/app/src/main/java/com/deepco/studyfork/RecyclerAdapterMovie.kt
> +    fun setItemList(modelList: ArrayList<Item>) {
리스트로 변경완료 했습니다.
7d46a6a

2020-11-05 13:05 UTC, Myung777 commented on class14/myung777/StudyFork/app/src/main/java/com/deepco/studyfork/RecyclerAdapterMovie.kt
> +        this.modelList = modelList
리스트 추가를 addAll 로 수정하였습니다.
529db1a

2020-11-05 13:06 UTC, Myung777 commented on class14/myung777/StudyFork/app/src/main/java/com/deepco/studyfork/api/RetrofitService.kt
> +            httpLoggingInterceptor.level = HttpLoggingInterceptor.Level.BODY
DEBUG 모드에 따라서 로그 레벨 변경하였습니다.
b045794

2020-11-06 10:49 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-11-06 11:16 UTC, merged