HW-1 영화 검색 과제
sjjeong/GoogryAndroidArchitecutreStudy pull request #879
Opened 2020-11-02 09:38 UTC by hhi-5258

2020-11-03 12:47 UTC, dktsudgg commented on class15/hhi-5258/HHiApplication/app/src/main/java/com/hhi/myapplication/MainActivity.kt
> +            if (main_edit_search.text.isEmpty()) {
if (main_edit_search.text.isNotEmpty()) {

2020-11-03 12:48 UTC, dktsudgg commented on class15/hhi-5258/HHiApplication/app/src/main/java/com/hhi/myapplication/MainActivity.kt
> +            if (main_edit_search.text.isEmpty()) {
```suggestion
            if (main_edit_search.text.isNotEmpty()) {
```

2020-11-03 12:48 UTC, dktsudgg commented on class15/hhi-5258/HHiApplication/app/src/main/java/com/hhi/myapplication/MainActivity.kt
> +                return@setOnClickListener
```suggestion
                searchMovie(main_edit_search.text.toString())
```

2020-11-03 12:48 UTC, dktsudgg commented on class15/hhi-5258/HHiApplication/app/src/main/java/com/hhi/myapplication/MainActivity.kt
> +            } else {
```suggestion
            }
```

2020-11-03 12:49 UTC, dktsudgg commented on class15/hhi-5258/HHiApplication/app/src/main/java/com/hhi/myapplication/MainActivity.kt
> +                searchMovie(main_edit_search.text.toString())
```suggestion
```

2020-11-03 12:49 UTC, dktsudgg commented on class15/hhi-5258/HHiApplication/app/src/main/java/com/hhi/myapplication/MainActivity.kt
> +            }
```suggestion
```

2020-11-03 12:51 UTC, dktsudgg commented on class15/hhi-5258/HHiApplication/app/src/main/java/com/hhi/myapplication/MainActivity.kt
> +            if (main_edit_search.text.isEmpty()) {
```suggestion
            if (main_edit_search.text.isNotEmpty()) {
                searchMovie(main_edit_search.text.toString())
            }
```

2020-11-03 12:51 UTC, dktsudgg commented on class15/hhi-5258/HHiApplication/app/src/main/java/com/hhi/myapplication/MainActivity.kt
> +            if (main_edit_search.text.isEmpty()) {
이렇게 else문을 제거하는 것도 괜찮을 것 같아요!

2020-11-03 12:54 UTC, dktsudgg commented on class15/hhi-5258/HHiApplication/app/src/main/java/com/hhi/myapplication/MainActivity.kt
> +            if (main_edit_search.text.isEmpty()) {
이렇게 else문을 제거하는 것도 괜찮을 것 같아요!
```suggestion
            if (main_edit_search.text.isNotEmpty()) {
                searchMovie(main_edit_search.text.toString())
            }
```

2020-11-03 12:55 UTC, dktsudgg commented on class15/hhi-5258/HHiApplication/app/src/main/java/com/hhi/myapplication/MainActivity.kt
> +                searchMovie(main_edit_search.text.toString())
이렇게 else문을 제거하는 것도 괜찮을 것 같아요!
```suggestion
            if (main_edit_search.text.isNotEmpty()) {
                searchMovie(main_edit_search.text.toString())
            }
```

2020-11-03 12:56 UTC, dktsudgg commented on class15/hhi-5258/HHiApplication/app/src/main/java/com/hhi/myapplication/MainActivity.kt
> +            if (main_edit_search.text.isEmpty()) {
```java
            if (main_edit_search.text.isNotEmpty()) {
                searchMovie(main_edit_search.text.toString())
            }
```

2020-11-03 12:56 UTC, dktsudgg commented on class15/hhi-5258/HHiApplication/app/src/main/java/com/hhi/myapplication/MainActivity.kt
> +            if (main_edit_search.text.isEmpty()) {
이렇게 else문을 제거하는 것도 괜찮을 것 같아요!

2020-11-03 13:01 UTC, dktsudgg commented on class15/hhi-5258/HHiApplication/app/src/main/java/com/hhi/myapplication/RecyclerAdapter.kt
> +            Glide.with(itemView.context).load(data.image)
바로 밑 라인에는 감독이나 출연진 데이터가 비어있을 경우를 체크하셨는데,
이미지 url이 비어있을 경우도 대비해서 Glide의 placeholder메소드를 사용하는건 어떨까요?

2020-11-04 10:00 UTC, hhi-5258 commented on class15/hhi-5258/HHiApplication/app/src/main/java/com/hhi/myapplication/MainActivity.kt
> +            if (main_edit_search.text.isEmpty()) {
훨씬 깔끔해졌습니다 감사합니다! 
b2be9e3

2020-11-04 10:01 UTC, hhi-5258 commented on class15/hhi-5258/HHiApplication/app/src/main/java/com/hhi/myapplication/RecyclerAdapter.kt
> +            Glide.with(itemView.context).load(data.image)
수정하였습니다, 감사합니다!
c415dcc

2020-11-04 12:26 UTC, dktsudgg approved these changes
수고하셨습니다!

2020-11-04 16:22 UTC, sjjeong requested changes

2020-11-04 16:22 UTC, sjjeong commented on class15/hhi-5258/HHiApplication/app/src/main/java/com/hhi/myapplication/MainActivity.kt
> +            LinearLayoutManager(this, LinearLayoutManager.VERTICAL, false)
layoutManager는 xml에서도 할 수 있습니다

2020-11-04 16:22 UTC, sjjeong commented on class15/hhi-5258/HHiApplication/app/src/main/java/com/hhi/myapplication/MainActivity.kt
> +                searchMovie(main_edit_search.text.toString())
main_edit_search.text가 중복으로 호출되고 있습니다
val로 선언해서 사용하도록 해주세요

2020-11-04 16:22 UTC, sjjeong commented on class15/hhi-5258/HHiApplication/app/src/main/java/com/hhi/myapplication/MainActivity.kt
> +                        recyclerAdapter.notifyDataSetChanged()
두개 작업을 같이 하는 함수를 adapter안에서 만들어서 처리해주세요

2020-11-04 16:22 UTC, sjjeong commented on class15/hhi-5258/HHiApplication/app/src/main/java/com/hhi/myapplication/RecyclerAdapter.kt
> +    var movieList: List<MovieData.MovieItem> = ArrayList()
private val로 변경해주시고
List객체를 변경하지 마시고 List안에 있는 아이템을 변경하도록 해주세요

2020-11-04 16:22 UTC, sjjeong commented on class15/hhi-5258/HHiApplication/app/src/main/java/com/hhi/myapplication/RecyclerAdapter.kt
> +            }
if 문 보다 if 식으로 변경해서 처리해보세요

2020-11-04 16:22 UTC, sjjeong commented on class15/hhi-5258/HHiApplication/app/src/main/res/layout/activity_main.xml
> +        android:layout_width="match_parent"
ConstraintLayout에서는 match_parent대신 0dp를 사용합니다

2020-11-06 09:04 UTC, hhi-5258 commented on class15/hhi-5258/HHiApplication/app/src/main/java/com/hhi/myapplication/MainActivity.kt
> +            LinearLayoutManager(this, LinearLayoutManager.VERTICAL, false)
수정하였습니다, 감사합니다!

4f01644

2020-11-06 09:04 UTC, hhi-5258 commented on class15/hhi-5258/HHiApplication/app/src/main/java/com/hhi/myapplication/MainActivity.kt
> +                searchMovie(main_edit_search.text.toString())
수정하였습니다, 감사합니다!

c8df38d

2020-11-06 09:04 UTC, hhi-5258 commented on class15/hhi-5258/HHiApplication/app/src/main/java/com/hhi/myapplication/MainActivity.kt
> +                        recyclerAdapter.notifyDataSetChanged()
수정하였습니다, 감사합니다!

4e8ed3d

2020-11-06 09:05 UTC, hhi-5258 commented on class15/hhi-5258/HHiApplication/app/src/main/java/com/hhi/myapplication/RecyclerAdapter.kt
> +    var movieList: List<MovieData.MovieItem> = ArrayList()
수정하였습니다, 감사합니다!

c958ddd

2020-11-06 09:05 UTC, hhi-5258 commented on class15/hhi-5258/HHiApplication/app/src/main/java/com/hhi/myapplication/RecyclerAdapter.kt
> +            }
수정하였습니다, 감사합니다!

ef82beb

2020-11-06 09:06 UTC, hhi-5258 commented on class15/hhi-5258/HHiApplication/app/src/main/res/layout/activity_main.xml
> +        android:layout_width="match_parent"
수정하였습니다, 감사합니다!

be6a3e4

2020-11-06 10:50 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-11-06 16:53 UTC, merged