HW-3 mvvm 변환
sjjeong/GoogryAndroidArchitecutreStudy pull request #88
Opened 2019-07-02 15:36 UTC by Nanamare

TODO

2019-07-05 19:18 UTC, zion830 requested changes
mvvm 어렵네여... 고생하셨습니다 !!

2019-07-05 19:18 UTC, zion830 commented on Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/adapter/viewholder/TickerViewHolder.kt
> +class TickerViewHolder(parent: ViewGroup) : BaseViewHolder<CoinModel>(R.layout.item_ticker, parent) {
item_ticker와 ViewHolder에도 데이터바인딩을 적용해서 
bind 함수 안의 코드를 더 간결하게 쓸 수 있을 것 같습니다.

```
override fun bind(data: CoinModel) {
    binding.data = data
}
```

2019-07-05 19:18 UTC, zion830 commented on Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/base/BaseActivity.kt
> +        binding.setLifecycleOwner(this)
setter를 쓰지 않아도 됩니다!
근데 요거 LiveData가 없어도 쓸수있는 메서드인가요?

2019-07-05 19:18 UTC, zion830 commented on Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/ui/coin/CoinFragment.kt
> +        coinVM.navigator = this@CoinFragment
이렇게 할당을 하면 ViewModel이 View를 직접적으로 알게되는 형태가 될 것 같아요.

2019-07-05 19:18 UTC, zion830 commented on Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/ui/MainActivity.kt
> +            navigator = this@MainActivity
이렇게 할당을 하면 ViewModel이 View를 직접적으로 알게되는 형태가 될 것 같아요

2019-07-05 19:18 UTC, zion830 commented on Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/vm/MarketViewModel.kt
> +    var navigator: MarketNavigator? = null
nonnull과 val로 바꿔도 될 거 같아요!

2019-07-05 19:18 UTC, zion830 commented on Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/vm/MarketViewModel.kt
> +            navigator?.hideLoadingDialog()
BaseFragment에서 정의된 함수를 호출하는 대신 observable 한 객체를 사용해야할 것 같습니다

2019-07-05 19:18 UTC, zion830 commented on Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/ui/coin/CoinFragment.kt
>      private fun initView() {
initView안의 초기화 코드도 위와 비슷하게 쓰면 좋을거같습니다

```
binding.rvCoinList.run {
    setLayoutManager(LinearLayoutManager(context))
    ...
}
```

2019-07-05 19:18 UTC, zion830 commented on Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/vm/CoinViewModel.kt
> +    var navigator: CoinNavigator? = null
nonnull과 val로 바꿔도 될 거 같아요!

2019-07-06 02:25 UTC, sjjeong requested changes

2019-07-06 02:25 UTC, sjjeong commented on Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/base/BaseActivity.kt
> +    protected lateinit var binding: B
set을 Base에서만 할 수 있게 private set 추가해주세요

2019-07-06 02:25 UTC, sjjeong commented on Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/vm/CoinViewModel.kt
> +        coins.set(mutableListOf())
ObservableField에 default 값을 주는 생성자가 있습니다.

2019-07-06 02:25 UTC, sjjeong commented on Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/vm/CoinViewModel.kt
> +class CoinViewModel {
BaseViewModel도 만들어주세요

2019-07-11 15:03 UTC, Nanamare commented on Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/ui/coin/CoinFragment.kt
> +        coinVM.navigator = this@CoinFragment
클릭하거나 해서 발생하는 이벤트는 아니라서 이렇게 처리하였는데, 어떤식으로 하면 좋을까요 ?

2019-07-11 15:04 UTC, Nanamare commented on Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/ui/MainActivity.kt
> +            navigator = this@MainActivity
요것도 위와 같은 방식인데 뷰 자체를 아는 것은 아니고, 인터페이스를 통해 간접적으로 알고 있다고 생각하는데, 어떤식으로 하면 더 좋을까요 ?

2019-07-12 12:50 UTC, Nanamare commented on Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/adapter/viewholder/TickerViewHolder.kt
> +class TickerViewHolder(parent: ViewGroup) : BaseViewHolder<CoinModel>(R.layout.item_ticker, parent) {
63a2de67d74d7ae0e14949a641ebdeb54abd23be
적용하였습니다!

2019-07-12 12:51 UTC, Nanamare commented on Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/base/BaseActivity.kt
> +        binding.setLifecycleOwner(this)
4a2d26565cb709b86be246f45bb86ee22c1731d6
제거하였습니다 :)

2019-07-12 12:52 UTC, Nanamare commented on Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/ui/coin/CoinFragment.kt
> +        coinVM.navigator = this@CoinFragment
navigator 를 없애고 observer-subscriber 구조로 바꿨습니다

2019-07-12 12:52 UTC, Nanamare commented on Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/ui/MainActivity.kt
> +            navigator = this@MainActivity
요거도 navigator 를 없애고 observer-subscriber 구조로 바꿨습니다

2019-07-12 12:53 UTC, Nanamare commented on Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/vm/MarketViewModel.kt
> +    var navigator: MarketNavigator? = null
삭제하였습니다 :)

2019-07-12 12:54 UTC, Nanamare commented on Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/vm/MarketViewModel.kt
> +            navigator?.hideLoadingDialog()
451b7335fb0ee7caa2f78cc4aa1ecb5012ca178a
변경했습니다!

2019-07-12 12:54 UTC, Nanamare commented on Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/ui/coin/CoinFragment.kt
>      private fun initView() {
b2f69cf797bfc605bf706b474ce1252f44f30c70
수정하였습니다

2019-07-12 12:54 UTC, Nanamare commented on Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/vm/CoinViewModel.kt
> +    var navigator: CoinNavigator? = null
삭제하였습니다 :)

2019-07-12 12:55 UTC, Nanamare commented on Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/base/BaseActivity.kt
> +    protected lateinit var binding: B
22bd8174f957a9e995c27eae3bc62fa638dd0f9c
추가 완료하였습니다

2019-07-12 12:55 UTC, Nanamare commented on Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/vm/CoinViewModel.kt
> +        coins.set(mutableListOf())
d88a291527eecdfd7c312a506a65522e10cca278
생성자로 초기화 처리 하였습니다

2019-07-12 12:55 UTC, Nanamare commented on Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/vm/CoinViewModel.kt
> +class CoinViewModel {
c3b3530616b78bcde8b095e816e133bd18abd2a4
추가 하였습니다.

2019-07-12 12:59 UTC, Nanamare commented
@sjjeong @zion830 
네비게이터 삭제 하고 대체 한 부분에 피드백 부탁드립니다 :)

2019-07-13 03:12 UTC, zion830 approved these changes

2019-07-13 05:00 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-07-13 05:13 UTC, merged