HW-1 영화 api 호출 및 검색 과제
sjjeong/GoogryAndroidArchitecutreStudy pull request #880
Opened 2020-11-02 12:27 UTC by PeonyF

Retrofit을 사용하여 네이버 영화 API를 출력 및 검색하는 프로젝트 입니다.

2020-11-03 03:23 UTC, jihoi-kang commented on class15/PeonyF/AndroidArchitectureStudy/app/src/main/java/com/architecture/androidarchitecturestudy/adapter/MovieViewHolder.kt
> +        Log.e("position", adapterPosition.toString())
adapterPosition 변수를 선언해서 사용할 필요가 없을 거 같습니다.

2020-11-03 03:23 UTC, jihoi-kang commented on class15/PeonyF/AndroidArchitectureStudy/app/src/main/java/com/architecture/androidarchitecturestudy/ui/MainActivity.kt
> +            LinearLayoutManager(this, RecyclerView.VERTICAL, false)
LayoutManager는 xml에서 추가 할 수 있습니다.

2020-11-03 03:23 UTC, jihoi-kang commented on class15/PeonyF/AndroidArchitectureStudy/app/src/main/java/com/architecture/androidarchitecturestudy/ui/MainActivity.kt
> +                    rv_main_movie_list.adapter = MovieAdapter(movieResponse!!.items)
영화를 검색할 때마다 Adapter를 재생성하는 것보다 Item만 교체해도 될 거 같습니다.

2020-11-03 03:23 UTC, jihoi-kang commented on class15/PeonyF/AndroidArchitectureStudy/app/src/main/res/layout/activity_main.xml
> +        android:layout_height="match_parent"
ConstraintLayout일 때에는 match_parent가 아닌 match_constraint를 선언해서 사용하기를 권장하는 글을 봤던 것 같습니다.
match_constraint은 xml에서 0dp로 선언할 수 있습니다.

2020-11-03 03:23 UTC, jihoi-kang commented on class15/PeonyF/AndroidArchitectureStudy/app/src/main/java/com/architecture/androidarchitecturestudy/util/config.kt
> +    val clientSecret = "3W11_jr5DD"
상수는 const를 사용하시고 변수가 대문자로 표시해주세요.
ex) CLIENT_ID, CLIENT_SECRET

2020-11-03 03:23 UTC, jihoi-kang commented on class15/PeonyF/AndroidArchitectureStudy/app/src/main/java/com/architecture/androidarchitecturestudy/adapter/MovieViewHolder.kt
> +        title.text = Html.fromHtml(movieData.title)
Html.fromHtml("")이 N 버전부터 deprecated 되어서 N버전이상일때와 그 외 버전일 때 따로 구분하셔야합니다.

2020-11-04 06:12 UTC, PeonyF commented on class15/PeonyF/AndroidArchitectureStudy/app/src/main/java/com/architecture/androidarchitecturestudy/adapter/MovieViewHolder.kt
> +        Log.e("position", adapterPosition.toString())
말씀하신 변수 삭제하였습니다.  
d1540d0

2020-11-04 06:13 UTC, PeonyF commented on class15/PeonyF/AndroidArchitectureStudy/app/src/main/java/com/architecture/androidarchitecturestudy/ui/MainActivity.kt
> +            LinearLayoutManager(this, RecyclerView.VERTICAL, false)
말씀하신 LayoutManager를 activity_main.xml로 이동시켰습니다.
6a20790

2020-11-04 06:14 UTC, PeonyF commented on class15/PeonyF/AndroidArchitectureStudy/app/src/main/java/com/architecture/androidarchitecturestudy/ui/MainActivity.kt
> +                    rv_main_movie_list.adapter = MovieAdapter(movieResponse!!.items)
말씀하신대로 item을 받아서 Adapter에 전달하는 방식으로 변경하였습니다.
a259f98

2020-11-04 06:17 UTC, PeonyF commented on class15/PeonyF/AndroidArchitectureStudy/app/src/main/res/layout/activity_main.xml
> +        android:layout_height="match_parent"
말씀하신대로 match_constraint로 선언하는 방식으로 변경하였습니다. 910fe5f
다만, 궁금한 부분이 있는데요, 지회님의 경우, 어떤 경우에 match_constraint를 선언하시는지 궁금합니다.
구글링 해보니까 ConstraintLayout 바로 아래있는 view의 경우 사용하지 말고, nested inside of views 일경우 사용하란 글을 봤습니다만, 이런 방식으로 진행하면 될까요?
https://stackoverflow.com/questions/37603751/set-width-to-match-constraints-in-constraintlayout

2020-11-04 06:18 UTC, PeonyF commented on class15/PeonyF/AndroidArchitectureStudy/app/src/main/java/com/architecture/androidarchitecturestudy/util/config.kt
> +    val clientSecret = "3W11_jr5DD"
말씀하신 대문자로 변경하였습니다. b0209d9
지회님이 하셨던 방식으로 변경하고 싶은데 어떤 키워드로 검색해야할지 모르겠더라구요..
키워드좀 알려주실 수 있으신가요?!

2020-11-04 06:18 UTC, PeonyF commented on class15/PeonyF/AndroidArchitectureStudy/app/src/main/java/com/architecture/androidarchitecturestudy/adapter/MovieViewHolder.kt
> +        title.text = Html.fromHtml(movieData.title)
말씀하신대로 버전 구분하는 메소드 추가하였습니다. 
0082060

2020-11-04 09:18 UTC, jihoi-kang commented on class15/PeonyF/AndroidArchitectureStudy/app/src/main/res/layout/activity_main.xml
> +        android:layout_height="match_parent"
저같은 경우 <androidx.constraintlayout.widget.ConstraintLayout> 을 사용할 때에 1 depth child view, layout에서 wrap_content가 아닌 전체를 layout으로 잡고 싶을 때 0dp 를 선언합니다.

말씀하신것처럼 ConstraintLayout 바로 아래 있는 view의 경우 match_parent를 사용하지 않고 0dp를 사용합니다!

2020-11-04 09:30 UTC, jihoi-kang commented on class15/PeonyF/AndroidArchitectureStudy/app/src/main/java/com/architecture/androidarchitecturestudy/util/config.kt
> +    val clientSecret = "3W11_jr5DD"
'how to read local local.properties in gradle'
위와 같이 구글에 검색해 보시겠어요? 좀 자료들이 나오는거 같습니다.

저는 [skydoves](https://github.com/skydoves/TheMovies2/blob/master/app/build.gradle) 에 올리신 거 보고 알게 되었습니다.

2020-11-04 09:35 UTC, jihoi-kang commented
LGTM👍
고생하셨습니다!

2020-11-04 09:44 UTC, PeonyF commented on class15/PeonyF/AndroidArchitectureStudy/app/src/main/res/layout/activity_main.xml
> +        android:layout_height="match_parent"
아하 답변 감사합니다 저도 앞으로 그렇게 해야겠어요! 😄

2020-11-04 09:45 UTC, PeonyF commented on class15/PeonyF/AndroidArchitectureStudy/app/src/main/java/com/architecture/androidarchitecturestudy/util/config.kt
> +    val clientSecret = "3W11_jr5DD"
바쁘실텐데 자료 찾아주셔서 감사합니다. 다음번에 적용해보겠습니다 :)

2020-11-04 16:23 UTC, sjjeong commented
@jihoi-kang 
코멘트를 resolve하지 말아주세요
닫혀 있으면 다른분들이 보기 어렵습니다

2020-11-04 16:37 UTC, sjjeong requested changes

2020-11-04 16:37 UTC, sjjeong commented on class15/PeonyF/AndroidArchitectureStudy/app/src/main/java/com/architecture/androidarchitecturestudy/adapter/MovieAdapter.kt
> +    private var modelList = ArrayList<Movie>()
private val 로 선언해주세요

2020-11-04 16:37 UTC, sjjeong commented on class15/PeonyF/AndroidArchitectureStudy/app/src/main/java/com/architecture/androidarchitecturestudy/adapter/MovieAdapter.kt
> +        this.modelList = modelList
=이 아니라 addAll로 변경해주세요

2020-11-04 16:37 UTC, sjjeong commented on class15/PeonyF/AndroidArchitectureStudy/app/src/main/java/com/architecture/androidarchitecturestudy/adapter/MovieAdapter.kt
> +    fun setItemList(modelList: ArrayList<Movie>) {
List타입으로 받도록 해주세요

2020-11-04 16:37 UTC, sjjeong commented on class15/PeonyF/AndroidArchitectureStudy/app/src/main/java/com/architecture/androidarchitecturestudy/ui/MainActivity.kt
> +    var movieList = ArrayList<Movie>()
해당 변수는 필요 없습니다

2020-11-04 16:37 UTC, sjjeong commented on class15/PeonyF/AndroidArchitectureStudy/app/src/main/java/com/architecture/androidarchitecturestudy/util/config.kt
> +object config {
Config로 변경해주세요
파일명도 변경해주세요

2020-11-04 16:37 UTC, sjjeong commented on class15/PeonyF/AndroidArchitectureStudy/app/src/main/res/layout/activity_main.xml
> +        android:layout_height="match_parent"
0dp로 변경해주세요

2020-11-04 16:37 UTC, sjjeong commented on class15/PeonyF/AndroidArchitectureStudy/app/src/main/res/values/dimens.xml
> +    <dimen name="height_150dp">150dp</dimen>
직접 값을 넣는거랑 차이가 없습니다
제거하고 직접 값을 사용하도록 해주세요

2020-11-05 09:17 UTC, jihoi-kang approved these changes

2020-11-05 09:23 UTC, PeonyF commented on class15/PeonyF/AndroidArchitectureStudy/app/src/main/java/com/architecture/androidarchitecturestudy/util/config.kt
> +    val clientSecret = "3W11_jr5DD"
말씀해주신 자료 검색하다가 괜찮은 사이트를 찾았어요. 여기는 gradle.properties에 적용하는 방식이지만, stepbystep이라 도움이 될것같아 전달드립니다.
https://richardroseblog.wordpress.com/2016/05/29/hiding-secret-api-keys-from-git/

2020-11-05 09:25 UTC, PeonyF commented on class15/PeonyF/AndroidArchitectureStudy/app/src/main/java/com/architecture/androidarchitecturestudy/adapter/MovieAdapter.kt
> +    private var modelList = ArrayList<Movie>()
값을 변경하지 못하도록 하기위해 가변인자 val로 변경하였습니다.
00c1b19

2020-11-05 09:25 UTC, PeonyF commented on class15/PeonyF/AndroidArchitectureStudy/app/src/main/java/com/architecture/androidarchitecturestudy/adapter/MovieAdapter.kt
> +        this.modelList = modelList
말씀하신 대로 addAll로 변경하였습니다.
6724513

2020-11-05 09:28 UTC, PeonyF commented on class15/PeonyF/AndroidArchitectureStudy/app/src/main/java/com/architecture/androidarchitecturestudy/adapter/MovieAdapter.kt
> +    fun setItemList(modelList: ArrayList<Movie>) {
말씀하신대로 ArrayList 에서 List로 변경하였습니다. (0a80257)
다만 List로 변경하는 이유가 ArrayList 외의 다른 List 종류를 사용시 쉽게 변경하기 위해 List를 사용하는것으로 이해하면 될까요? :thinking_face:

2020-11-05 09:30 UTC, PeonyF commented on class15/PeonyF/AndroidArchitectureStudy/app/src/main/java/com/architecture/androidarchitecturestudy/ui/MainActivity.kt
> +    var movieList = ArrayList<Movie>()
말씀하신 movieList 변수를 제거하였습니다. 2238f36
이에 따라 MainActivity의 retrofit 부분도 변경하였습니다. 30a0850

2020-11-05 09:30 UTC, sjjeong commented on class15/PeonyF/AndroidArchitectureStudy/app/src/main/java/com/architecture/androidarchitecturestudy/adapter/MovieAdapter.kt
> +    fun setItemList(modelList: ArrayList<Movie>) {
`oop의 다형성` + `immutable`로 해주기 위해서 입니다

2020-11-05 09:32 UTC, PeonyF commented on class15/PeonyF/AndroidArchitectureStudy/app/src/main/java/com/architecture/androidarchitecturestudy/util/config.kt
> +object config {
말씀하신대로 Config 파일로 변경하였습니다. (fcdfc47)
다만, local.properties에 API KEY값을 넣는것이 더 보안에 좋다고 생각하여 Config 파일을 삭제하고 (c996de9)
 local.properties에 API KEY값을 넣는것으로 변경하였습니다. (f8c45d6)

2020-11-05 09:32 UTC, PeonyF commented on class15/PeonyF/AndroidArchitectureStudy/app/src/main/res/layout/activity_main.xml
> +        android:layout_height="match_parent"
layout_height 값을 0dp로 변경하였습니다. 
e9fdd6e

2020-11-05 09:33 UTC, PeonyF commented on class15/PeonyF/AndroidArchitectureStudy/app/src/main/res/values/dimens.xml
> +    <dimen name="height_150dp">150dp</dimen>
layout의 값을 직접값으로 변경하고(31d3fdc) , dimens.xml을 삭제(79e4e5f)하였습니다.

2020-11-05 09:37 UTC, PeonyF commented on class15/PeonyF/AndroidArchitectureStudy/app/src/main/java/com/architecture/androidarchitecturestudy/adapter/MovieAdapter.kt
> +    fun setItemList(modelList: ArrayList<Movie>) {
oop 다형성은 이해하였습니다만, immutable은 잘 이해가 가지 않습니다. :(
다형성(arraylist, linked list) 을 위해  더 넓은 범위인 list로 변경하는것으로 이해했습니다만,
불변성은.. 어떤 상황에서 발생하는지 잘 모르겠습니다. :(

2020-11-05 09:39 UTC, PeonyF commented on class15/PeonyF/AndroidArchitectureStudy/app/src/main/java/com/architecture/androidarchitecturestudy/adapter/MovieAdapter.kt
> +    fun setItemList(modelList: ArrayList<Movie>) {
아! 이해했습니다. Immutable List의 경우 List의 값들을 추가나 삭제가 불가능 하군요!
(https://www.geeksforgeeks.org/immutable-list-in-java/ )
감사합니다 :)

2020-11-05 09:40 UTC, sjjeong commented on class15/PeonyF/AndroidArchitectureStudy/app/src/main/java/com/architecture/androidarchitecturestudy/adapter/MovieAdapter.kt
> +    fun setItemList(modelList: ArrayList<Movie>) {
함수형 프로그래밍에서 함수는 외부에 영향을 주지 않도록 순수함수로 구현해야하는데
파라미터로 넘어온 리스트를 수정 할 수 있게 된다면 순수함수가 아니게 됩니다
그래서 immutable한 타입으로 List로 받는 겁니다

2020-11-05 09:46 UTC, PeonyF commented on class15/PeonyF/AndroidArchitectureStudy/app/src/main/java/com/architecture/androidarchitecturestudy/adapter/MovieAdapter.kt
> +    fun setItemList(modelList: ArrayList<Movie>) {
아....그래서군요 앞으로 함수형 프로그래밍시에 유의해서 코딩하도록하겠습니다.

2020-11-05 09:56 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-11-05 10:31 UTC, merged