Class14/hunihun
sjjeong/GoogryAndroidArchitecutreStudy pull request #881
Opened 2020-11-02 16:54 UTC by hunihun

영화 검색 과제입니다.

기능단위별 커밋을 찍지 못한점 양해 부탁드리겠습니다.

2020-11-04 03:22 UTC, juan-rybczinski commented on class14/hunihun/app/src/main/java/com/wybh/androidarchitecturestudy/retrofit/RetrofitImpl.kt
> +    @Headers("X-Naver-Client-Id: VsqhmqtGTmcUWFZ_Cv2I", "X-Naver-Client-Secret: bfUieu0BGT")
- 다른 Naver API 호출 시에도 항상 추가될 것으로 기대되는 Header 정보는 Global하게 관리하는 게 어떨까요?
- Client ID와 Secret 같은 민감한 정보는 Public Repository에 직접적으로 노출시키지 않는 게 어떨까요?

2020-11-04 03:25 UTC, juan-rybczinski commented on class14/hunihun/app/src/main/java/com/wybh/androidarchitecturestudy/retrofit/RetrofitCreator.kt
> +        private const val API_BASE_URL = "https://openapi.naver.com/v1/search/"
- 향후 Naver API의 버전 업데이트를 대비해 API_BASE_URL을 좀 더 짧게 가져가는 게 어떨까요?

2020-11-04 03:35 UTC, juan-rybczinski commented
아직 안드로이드 코딩에 익숙하지 않아 자세한 리뷰를 드리지 못해 죄송합니다.
다음 과제부터는 제출과 리뷰 좀 더 분발해 볼게요.

2020-11-04 15:10 UTC, hunihun commented
1

2020-11-04 16:05 UTC, hunihun commented on class14/hunihun/app/src/main/java/com/wybh/androidarchitecturestudy/retrofit/RetrofitImpl.kt
> +    @Headers("X-Naver-Client-Id: VsqhmqtGTmcUWFZ_Cv2I", "X-Naver-Client-Secret: bfUieu0BGT")
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/881/commits/d54a8052a2f3956dd36655e21755f106f55373da

2020-11-04 16:07 UTC, hunihun commented on class14/hunihun/app/src/main/java/com/wybh/androidarchitecturestudy/retrofit/RetrofitCreator.kt
> +        private const val API_BASE_URL = "https://openapi.naver.com/v1/search/"
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/881/commits/e6d795de0cbc1dbfb722ae1b87c3d6a5054c72d3

확인 감사합니다!

2020-11-05 09:25 UTC, sjjeong requested changes

2020-11-05 09:25 UTC, sjjeong commented on class14/hunihun/app/src/main/java/com/wybh/androidarchitecturestudy/CinemaAdapter.kt
> +class CinemaAdapter(private var itemList: ArrayList<CinemaItem>, private var activity: Activity): RecyclerView.Adapter<CinemaAdapter.CinemaViewHolder>() {
생성자에 list와 activity를 둘다 받지 않도록 수정해주세요

제거하면서 궁금한거 있으시면 채널에 남겨주세요

2020-11-05 09:25 UTC, sjjeong commented on class14/hunihun/app/src/main/java/com/wybh/androidarchitecturestudy/CinemaAdapter.kt
> +        itemList = list
리스트 객체를 변경하지 마시고 리스트 안에 있는 데이터만 변경하도록 해주세요

2020-11-05 09:25 UTC, sjjeong commented on class14/hunihun/app/src/main/java/com/wybh/androidarchitecturestudy/CinemaAdapter.kt
> +    fun setList(list: ArrayList<CinemaItem>) {
타입은 List로 받으면 됩니다

2020-11-05 09:25 UTC, sjjeong commented on class14/hunihun/app/src/main/java/com/wybh/androidarchitecturestudy/CinemaAdapter.kt
> +            llItem.setOnClickListener {
llItem보다 itemView에 click listener를 추가하면 됩니다
bind 될 때마다 ClickListener를 set하는건 좋지 않습니다
view를 생성하고 초기화 하는 단계에서 한번만 하도록 해주세요

2020-11-05 09:25 UTC, sjjeong commented on class14/hunihun/app/src/main/java/com/wybh/androidarchitecturestudy/MainActivity.kt
> +    private lateinit var mAdapter: CinemaAdapter
kotlin에서는 m prefix를 사용하지 않습니다.

2020-11-05 09:25 UTC, sjjeong commented on class14/hunihun/app/src/main/java/com/wybh/androidarchitecturestudy/MainActivity.kt
> +        super.onDestroy()
super.onDestroy()는 맨 마지막에 호출되도록 해주세요

2020-11-05 09:25 UTC, sjjeong commented on class14/hunihun/app/src/main/java/com/wybh/androidarchitecturestudy/MainActivity.kt
> +        }
dispose할때 내부적으로 검사하기 때문에 if가 필요없습니다

2020-11-05 09:25 UTC, sjjeong commented on class14/hunihun/app/src/main/java/com/wybh/androidarchitecturestudy/MainActivity.kt
> +                        }
response.items.map{}을 사용하시면 새로운 list객체가 나옵니다 
itemList 변수는 제거해주세요

2020-11-05 09:25 UTC, sjjeong commented on class14/hunihun/app/src/main/java/com/wybh/androidarchitecturestudy/retrofit/RetrofitCreator.kt
> +    companion object {
RetrofitCreator 자체를 객체로 사용하지 않는다면 object로 만들면 됩니다

2020-11-05 09:25 UTC, sjjeong commented on class14/hunihun/app/src/main/java/com/wybh/androidarchitecturestudy/retrofit/RetrofitImpl.kt
> +    fun getCinemaData(@Query("query") query: String?): Observable<ResponseCinemaData>
rest api는 단건 처리라서 Observable보단 Single이 적합 합니다

2020-11-05 16:28 UTC, hunihun commented on class14/hunihun/app/src/main/java/com/wybh/androidarchitecturestudy/MainActivity.kt
> +                        }
itemList 변수는 새롭게 만든 CinemaItem 에 대한 List 인데 제거하라는 말씀은  data class 를 새로 만들지말고 기존에 만들었던 data model 을 사용하라는 말씀이신건가용 ???

2020-11-05 16:30 UTC, hunihun commented on class14/hunihun/app/src/main/java/com/wybh/androidarchitecturestudy/CinemaAdapter.kt
> +class CinemaAdapter(private var itemList: ArrayList<CinemaItem>, private var activity: Activity): RecyclerView.Adapter<CinemaAdapter.CinemaViewHolder>() {
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/881/commits/7aed4712ccbeeda9a489a0dc6873de4a2edbd597

둘다 동시에 받지 말란 뜻인건가요 ??? 이유가 궁금합니다!

2020-11-05 16:31 UTC, hunihun commented on class14/hunihun/app/src/main/java/com/wybh/androidarchitecturestudy/CinemaAdapter.kt
> +        itemList = list
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/881/commits/a551700f81735ba9bb673dd42c82f18c259b9420

추후 activity 에서 list 값을 변경했을때 문제가 생길수 있기때문인가요 ??

2020-11-05 16:32 UTC, hunihun commented on class14/hunihun/app/src/main/java/com/wybh/androidarchitecturestudy/CinemaAdapter.kt
> +    fun setList(list: ArrayList<CinemaItem>) {
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/881/commits/3a48d228211721885492eb151c764f07a4b8e458

ArrayList로 받으면 안되는 이유가 있을까요 ??

2020-11-05 16:33 UTC, hunihun commented on class14/hunihun/app/src/main/java/com/wybh/androidarchitecturestudy/CinemaAdapter.kt
> +            llItem.setOnClickListener {
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/881/commits/3b63038d16a8095cc8aaa433a5e2992ae79253eb

수정했습니다!

2020-11-05 16:33 UTC, hunihun commented on class14/hunihun/app/src/main/java/com/wybh/androidarchitecturestudy/MainActivity.kt
> +    private lateinit var mAdapter: CinemaAdapter
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/881/commits/0527921530e2b5644525e63e1621494f0ed06069

수정했습니다!

2020-11-05 16:46 UTC, hunihun commented on class14/hunihun/app/src/main/java/com/wybh/androidarchitecturestudy/MainActivity.kt
> +        super.onDestroy()
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/881/commits/77e0550c529a90f81080285a56969abf3dc26c07

onDestroy()를 class 제일 하단에 위치하라는 말씀이신거죠????

2020-11-05 16:47 UTC, hunihun commented on class14/hunihun/app/src/main/java/com/wybh/androidarchitecturestudy/MainActivity.kt
> +        }
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/881/commits/53f38930a43ce405c78a6fa099371e93685d3074

수정했습니다~

2020-11-05 16:47 UTC, hunihun commented on class14/hunihun/app/src/main/java/com/wybh/androidarchitecturestudy/retrofit/RetrofitCreator.kt
> +    companion object {
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/881/commits/f2be3c03e04b702bbf33b1ca7bac35e2f2d65836

수정했습니다~

2020-11-05 16:47 UTC, hunihun commented on class14/hunihun/app/src/main/java/com/wybh/androidarchitecturestudy/retrofit/RetrofitImpl.kt
> +    fun getCinemaData(@Query("query") query: String?): Observable<ResponseCinemaData>
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/881/commits/61829a9f3a69a740f5999a7bd820474e438c3bf3

수정했습니다!

2020-11-06 10:53 UTC, sjjeong commented on class14/hunihun/app/src/main/java/com/wybh/androidarchitecturestudy/CinemaAdapter.kt
> +        itemList = list
네 맞습니다

2020-11-06 10:53 UTC, sjjeong commented on class14/hunihun/app/src/main/java/com/wybh/androidarchitecturestudy/CinemaAdapter.kt
> +class CinemaAdapter(private var itemList: ArrayList<CinemaItem>, private var activity: Activity): RecyclerView.Adapter<CinemaAdapter.CinemaViewHolder>() {
context는 내부에서 View를 통해서 접근할 수 있고
List는 외부와 공유하지 않기 위해서 입니다

2020-11-06 10:55 UTC, sjjeong commented on class14/hunihun/app/src/main/java/com/wybh/androidarchitecturestudy/CinemaAdapter.kt
> +    fun setList(list: ArrayList<CinemaItem>) {
Mutable한 타입으로 받으면 내부에서 리스트 객체를 수정할 수 있어서 좋은 패턴이 아니게 됩니다
항상 클래스나 함수를 구현할때는 private하게 하고 final하게 구현하는게 좋습니다

2020-11-06 10:55 UTC, sjjeong commented on class14/hunihun/app/src/main/java/com/wybh/androidarchitecturestudy/MainActivity.kt
> +        super.onDestroy()
아닙니다
함수 내부에서 super.onDestroy()를 마지막에 호출해달라는 겁니다

2020-11-06 10:56 UTC, sjjeong commented on class14/hunihun/app/src/main/java/com/wybh/androidarchitecturestudy/MainActivity.kt
> +                        }
저는 itemList 변수를 제거 해달라고 했지 CinemaItem data class를 사용하지 말라고는 하지 않았습니다

list map에 대해서 알아보시면 지금 코드와 동일한 동작을 하는 것을 알 수 있을 겁니다

2020-11-06 10:59 UTC, sjjeong requested changes

2020-11-06 10:59 UTC, sjjeong commented on class14/hunihun/app/src/main/java/com/wybh/androidarchitecturestudy/CinemaAdapter.kt
> +class CinemaAdapter(private var itemList: ArrayList<CinemaItem>): RecyclerView.Adapter<CinemaAdapter.CinemaViewHolder>() {
private val 로 내부에서 리스트객체를 만들어서 가지도록 해주세요

2020-11-06 10:59 UTC, sjjeong commented on class14/hunihun/app/src/main/java/com/wybh/androidarchitecturestudy/CinemaAdapter.kt
> +        itemList.addAll(list)
함수명은 set인데 내부적으로는 addAll만 하고 있습니다
clear하는 것도 같이 처리해주세요

2020-11-06 10:59 UTC, sjjeong commented on class14/hunihun/app/src/main/java/com/wybh/androidarchitecturestudy/MainActivity.kt
> +            layoutManager = LinearLayoutManager(this@MainActivity)
LayoutManager는 xml에서 추가할 수 있습니다

2020-11-06 10:59 UTC, sjjeong commented on class14/hunihun/app/src/main/java/com/wybh/androidarchitecturestudy/MainActivity.kt
> +                        }
map을 사용해서 처리해주세요

2020-11-07 04:31 UTC, hunihun commented on class14/hunihun/app/src/main/java/com/wybh/androidarchitecturestudy/CinemaAdapter.kt
> +class CinemaAdapter(private var itemList: ArrayList<CinemaItem>, private var activity: Activity): RecyclerView.Adapter<CinemaAdapter.CinemaViewHolder>() {
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/881/commits/b63213a1775976d0ed0ab1e7caa40b513e8df0f7

adapter 에서 list 받지 않게 처리

2020-11-07 04:32 UTC, hunihun commented on class14/hunihun/app/src/main/java/com/wybh/androidarchitecturestudy/CinemaAdapter.kt
> +        itemList.addAll(list)
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/881/commits/83a15e25b4acc1c1094fbfac4d0886d78f21ff78

수정하였습니다!

2020-11-07 04:32 UTC, hunihun commented on class14/hunihun/app/src/main/java/com/wybh/androidarchitecturestudy/MainActivity.kt
> +            layoutManager = LinearLayoutManager(this@MainActivity)
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/881/commits/c95ed218d40659cfed7e34564b4a564a64d918ca

수정하였습니다

2020-11-07 04:33 UTC, hunihun commented on class14/hunihun/app/src/main/java/com/wybh/androidarchitecturestudy/MainActivity.kt
> +                        }
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/881/commits/8e86e49b51bce82fa1d45747d9b08352387cfb5b 

수정하였습니다

2020-11-07 04:34 UTC, hunihun commented on class14/hunihun/app/src/main/java/com/wybh/androidarchitecturestudy/MainActivity.kt
> +        super.onDestroy()
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/881/commits/6111dc49a31328cf557c85f12070323a782d0945

수정하였습니다!

2020-11-08 03:27 UTC, sjjeong approved these changes
머지 하시고 다음 과제 진행해 주세요

2020-11-08 07:57 UTC, juan-rybczinski approved these changes

2020-11-08 13:49 UTC, merged