HW-1 영화 검색 과제
sjjeong/GoogryAndroidArchitecutreStudy pull request #882
Opened 2020-11-04 01:53 UTC by juan-rybczinski

늦어서 죄송합니다

2020-11-04 15:10 UTC, hunihun reviewed
안드로이드 경력이 얼마 없다고 하셨는데 역시.. 짬에서 나오는 바이브는 엄청나네요..!!
코드에 추후 확정성을 생각하고 작성한 모습이 보였습니다! 
오히려 제가 더 배운것 같습니다!  감사합니다!

2020-11-04 15:10 UTC, hunihun commented on class14/juan-rybczinski/GoogryAndroidArchitectureStudy/app/src/main/java/com/example/googryandroidarchitecturestudy/fragment/MovieFragment.kt
> +class MovieFragment : Fragment() {
Fragment를 사용하신 이유가 있으실까요???

2020-11-04 15:11 UTC, hunihun commented
안드로이드 경력이 얼마 없다고 하셨는데 역시.. 짬에서 나오는 바이브는 엄청나네요..!!
코드에 추후 확정성을 생각하고 작성한 모습이 보였습니다!
오히려 제가 더 배운것 같습니다! 감사합니다!

2020-11-04 15:12 UTC, hunihun commented
> 1

2020-11-04 15:38 UTC, sjjeong commented
@hunihun 
왜 close 하셨나요?

2020-11-04 16:12 UTC, hunihun commented
@sjjeong 
엥...? 그러네요 제가 뭘 잘못눌렀나봐요 ...

2020-11-04 16:12 UTC, sjjeong commented
@hunihun 
제가 reopen 할게요

2020-11-04 22:17 UTC, juan-rybczinski commented on class14/juan-rybczinski/GoogryAndroidArchitectureStudy/app/src/main/java/com/example/googryandroidarchitecturestudy/fragment/MovieFragment.kt
> +class MovieFragment : Fragment() {
Navigation Component들을 사용하고 싶어서 였는데,
사실 화면이 하나이고 화면 이동도 없으니 불필요할 것으로 보이면 다음주 과제하면서 수정하겠습니다!

2020-11-05 12:46 UTC, hunihun commented on class14/juan-rybczinski/GoogryAndroidArchitectureStudy/app/src/main/java/com/example/googryandroidarchitecturestudy/fragment/MovieFragment.kt
> +class MovieFragment : Fragment() {
굳이 수정 할 필요 없을것같습니다!

2020-11-06 11:16 UTC, sjjeong requested changes

2020-11-06 11:16 UTC, sjjeong commented on class14/juan-rybczinski/GoogryAndroidArchitectureStudy/app/src/main/java/com/example/googryandroidarchitecturestudy/App.kt
> +    }
companion object는 클래스 맨 아래에 위치해야 합니다

2020-11-06 11:16 UTC, sjjeong commented on class14/juan-rybczinski/GoogryAndroidArchitectureStudy/app/src/main/java/com/example/googryandroidarchitecturestudy/ui/fragment/MovieFragment.kt
> +        get() = job + Dispatchers.Main
viewLifecycleOwner.lifecycleScope 를 사용하시면 해당코드들은 필요없습니다

2020-11-06 11:16 UTC, sjjeong commented on class14/juan-rybczinski/GoogryAndroidArchitectureStudy/app/src/main/java/com/example/googryandroidarchitecturestudy/ui/fragment/MovieFragment.kt
> +        }
해당 작업들은 onViewCreated에서 해주세요

2020-11-06 11:16 UTC, sjjeong commented on class14/juan-rybczinski/GoogryAndroidArchitectureStudy/app/src/main/java/com/example/googryandroidarchitecturestudy/ui/recycler/MovieAdapter.kt
> +    private var movies: List<Movie>
list는 Adapter 외부와 내부가 같은 리스트 객체를 사용하지 않도록 해주세요
내부에서 list를 별도로 가지고 있고 list안에 있는 아이템을 추가하고 변경하도록 해주시면 됩니다

2020-11-06 11:16 UTC, sjjeong commented on class14/juan-rybczinski/GoogryAndroidArchitectureStudy/app/src/main/res/layout/fragment_movie.xml
> +        android:layout_marginBottom="@dimen/default_margin"
4방향이 다 같은 값이라면 layout_margin으로 하시면 됩니다

2020-11-06 11:16 UTC, sjjeong commented on class14/juan-rybczinski/GoogryAndroidArchitectureStudy/app/src/main/res/layout/fragment_movie.xml
> +        android:layout_marginEnd="@dimen/default_margin"
start와 end가 같은 값이라면 layout_marginHorizontal로 하시면 됩니다

2020-11-08 03:28 UTC, sjjeong approved these changes
머지 하시고 다음 과제 진행해 주세요

2020-11-08 13:52 UTC, hunihun approved these changes

2020-11-08 22:01 UTC, merged