HW-2 : Repository 및 DataSource 추가
sjjeong/GoogryAndroidArchitecutreStudy pull request #884
Opened 2020-11-08 14:43 UTC by showmiso

2020-11-11 15:12 UTC, realizer12 commented on class15/showmiso/ArchitectureStudy/app/src/main/java/com/showmiso/architecturestudy/data/repository/NaverRepositoryImpl.kt
> +    }
음 제가  맞는지는 잘모르겠지만,  
현재  데이터소스에서 api 관련  정보만  리턴후,  
레포지토리에서  서버 통신을 진행하는것 같습니다!

저는  데이터소스에서  통신 과정이 진행되는 것으로 알고 있습니다!

혹시 제 리뷰가 틀렸다면 알려주세요!!

2020-11-12 11:38 UTC, showmiso commented on class15/showmiso/ArchitectureStudy/app/src/main/java/com/showmiso/architecturestudy/data/repository/NaverRepositoryImpl.kt
> +    }
그럼 콜백으로 데이터를 받아야 한다는 말씀이신가요?~

2020-11-12 12:35 UTC, realizer12 commented on class15/showmiso/ArchitectureStudy/app/src/main/java/com/showmiso/architecturestudy/data/repository/NaverRepositoryImpl.kt
> +    }
음  그런거 같아요.!

저는  뷰에서 쿼리를 받으면 레포지토리를 통해  
데이터소스로 넘겨 
데이터소스에서  통신후  결과를 레포지토리로 콜백하는 형식으로 구현했습니다!

음  제가  잘못안것일수도 있으니,  
멘토님의  리뷰를 기다려야 할듯합니다 ㅎㅎ;;

암튼  그외  리뷰사항은 없습니다!
수고하셨어요~

2020-11-13 14:54 UTC, realizer12 approved these changes

2020-11-13 15:56 UTC, sjjeong requested changes

2020-11-13 15:56 UTC, sjjeong commented on class15/showmiso/ArchitectureStudy/app/src/main/java/com/showmiso/architecturestudy/data/repository/NaverRepositoryImpl.kt
> +            .observeOn(AndroidSchedulers.mainThread())
observeOn은 실제 subscribe하는 부분에서 추가해주는게 좋습니다

2020-11-13 15:57 UTC, sjjeong commented on class15/showmiso/ArchitectureStudy/app/src/main/java/com/showmiso/architecturestudy/data/repository/NaverRepositoryImpl.kt
> +    }
@realizer12 
Rx로 진행하면 실제 서버통신하는 순간은 subscribe할 때 입니다
이렇게 하셔도 됩니다

2020-11-14 01:32 UTC, realizer12 commented on class15/showmiso/ArchitectureStudy/app/src/main/java/com/showmiso/architecturestudy/data/repository/NaverRepositoryImpl.kt
> +    }
@sjjeong   아하  그렇군요!!   감사합니다!

2020-11-14 03:15 UTC, showmiso commented on class15/showmiso/ArchitectureStudy/app/src/main/java/com/showmiso/architecturestudy/data/repository/NaverRepositoryImpl.kt
> +            .observeOn(AndroidSchedulers.mainThread())
넵 수정했습니다. d101619a800dde60a659ee3090a3da0208e2007a

2020-11-14 07:23 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-11-14 07:24 UTC, merged