HW-2 Add model layer
sjjeong/GoogryAndroidArchitecutreStudy pull request #885
Opened 2020-11-08 14:51 UTC by jihoi-kang

PR을 잘못했는지 HW-1 부분까지 포함되어 있어서 다시 PR 만듭니다.
Local data source도 추가하여 캐시된 값이 있으면 Local에서 가져오는 부분까지 구현해보았습니다.

2020-11-10 08:25 UTC, PeonyF commented
코루틴과 룸을 사용한 프로젝트여서 제가 따로 리뷰드릴 내용이 없어 보입니다 😢 
Mentor Needed로 상태 변경하겠습니다.

2020-11-11 10:58 UTC, sjjeong requested changes

2020-11-11 10:58 UTC, sjjeong commented on class15/jihoi-kang/aas/app/src/main/java/com/jay/aas/data/MovieRepositoryImpl.kt
> +        return movies
이러면 remote가 한번 불리고 그 뒤로 remote가 불리지 않네요

2020-11-12 02:02 UTC, PeonyF approved these changes

2020-11-12 06:26 UTC, jihoi-kang commented on class15/jihoi-kang/aas/app/src/main/java/com/jay/aas/data/MovieRepositoryImpl.kt
> +        return movies
검색시에 항상 remote가 불리게 구현하였습니다. 
a7815fa

맨 처음 앱을 시작할 때에 Local 데이터들을 디스플레이 해줍니다.
60475a8

2020-11-12 09:41 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-11-12 10:23 UTC, merged