HW-2 Repository, RemoteDataSource 구현
sjjeong/GoogryAndroidArchitecutreStudy pull request #887
Opened 2020-11-09 05:05 UTC by hhi-5258

2020-11-10 13:46 UTC, dktsudgg commented on class15/hhi-5258/HHiApplication/app/src/main/java/com/hhi/myapplication/RecyclerAdapter.kt
>  class RecyclerAdapter() : RecyclerView.Adapter<RecyclerAdapter.ViewHolder>() {
제 기억이 맞다면 저번 스터디에서 석준님이 코딩하실 때, 주생성자에 파라미터가 없는 경우에는 생략하셨던 것 같습니다! RepositoryDataSourceImpl클래스에서도 마찬가지로 생략해도 괜찮을 것 같아요!

 음 그리고 제가 해인님꺼 소스를 받아서 API레벨 23인 에뮬레이터로 실행해봤는데 이미지가 없는 경우에 Glide라이브러리 error함수 사용하신 부분에서 에러가 나더라구요, R.drawable.ic_launcher_foreground 리소스를 못찾겠다는 에러였는데 살펴보니까 drawable-v24 폴더에 R.drawable.ic_launcher_foreground파일을 넣어두셔서 그런 것 같습니다! drawable로 옮기면 해결될 것 같아요. 실기기로 테스트 했을 때는 api레벨이 높아서 에러가 나지 않았습니다.

 에러발생 시나리오는 "hi" 라고 검색했을 때, 검색 결과 중에 "오 하이 앤"이라는 영화가 있는데 얘가 이미지url이 없는 영화입니다! 감사합니다!

2020-11-11 10:40 UTC, hhi-5258 commented on class15/hhi-5258/HHiApplication/app/src/main/java/com/hhi/myapplication/RecyclerAdapter.kt
>  class RecyclerAdapter() : RecyclerView.Adapter<RecyclerAdapter.ViewHolder>() {
클래스 선언 시 파라미터 없는 경우 괄호 삭제 하였습니다, 감사합니다!
6990175

ic_launcher_foreground 이미지 또한 이동하였습니다, 실 기기에서만 테스트하느라 몰랐네요 ㅎㅎ
0a79a2b

2020-11-11 14:43 UTC, dktsudgg commented on class15/hhi-5258/HHiApplication/app/src/main/java/com/hhi/myapplication/RecyclerAdapter.kt
>  class RecyclerAdapter() : RecyclerView.Adapter<RecyclerAdapter.ViewHolder>() {
넵 수고하셨습니다!

2020-11-11 14:43 UTC, dktsudgg approved these changes

2020-11-12 09:43 UTC, sjjeong requested changes

2020-11-12 09:43 UTC, sjjeong commented on class15/hhi-5258/HHiApplication/app/src/main/java/com/hhi/myapplication/data/repository/RepositoryDataSource.kt
> +interface RepositoryDataSource {
RemoteDataSource를 NaverRemoteDataSource로 했으니까
Repository 이름도 NaverRepository로 해주세요

2020-11-12 11:10 UTC, hhi-5258 commented on class15/hhi-5258/HHiApplication/app/src/main/java/com/hhi/myapplication/data/repository/RepositoryDataSource.kt
> +interface RepositoryDataSource {
네, 수정하였습니다!
e9a6e2b

2020-11-13 13:49 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-11-14 02:05 UTC, merged