HW-2 model 추가
sjjeong/GoogryAndroidArchitecutreStudy pull request #888
Opened 2020-11-09 09:56 UTC by simuelunbo

2020-11-09 13:52 UTC, Myung777 reviewed
어떤부분이 더 수정되어야 할지 감이 안잡히네요 잘 구현하신것 같아요 고생하셨습니다~

2020-11-09 13:52 UTC, Myung777 commented on class14/simuelunbo/AndroidArchitectureStudy/app/src/main/java/com/example/androidarchitecturestudy/data/remote/RemoteMovieDataImpl.kt
> +                        it.items?.let { it1 -> repositoryMovieImpl.saveMovieData(it1) }
it1 말고 다른 명칭을 쓰면 좋을것 같아보이네요

2020-11-10 04:58 UTC, simuelunbo commented on class14/simuelunbo/AndroidArchitectureStudy/app/src/main/java/com/example/androidarchitecturestudy/data/remote/RemoteMovieDataImpl.kt
> +                        it.items?.let { it1 -> repositoryMovieImpl.saveMovieData(it1) }
c0bda028c87975bc1b006d22b1e7c72287d9cbe9 수정하였습니다

2020-11-10 13:07 UTC, Myung777 approved these changes

2020-11-11 11:07 UTC, sjjeong requested changes

2020-11-11 11:07 UTC, sjjeong commented on class14/simuelunbo/AndroidArchitectureStudy/app/src/main/java/com/example/androidarchitecturestudy/data/remote/RemoteMovieDataImpl.kt
> +    private val repositoryMovieImpl = RepositoryMovieImpl(this,localMovieDataImpl)
Remote가 Repository를 가지고 있으면 안됩니다

2020-11-12 04:41 UTC, simuelunbo commented on class14/simuelunbo/AndroidArchitectureStudy/app/src/main/java/com/example/androidarchitecturestudy/data/remote/RemoteMovieDataImpl.kt
> +    private val repositoryMovieImpl = RepositoryMovieImpl(this,localMovieDataImpl)
58073a63c73201ad7a361487229db8767fbe386d 수정했습니다

2020-11-12 09:45 UTC, sjjeong requested changes
Model layer 클래스명 변경이 필요합니다

NaverRemoteDataSource
NaverLocalDataSource
NaverRepository

로 변경해주세요

2020-11-12 10:57 UTC, simuelunbo commented
e9ea6a67c0a1f8d03ab31b138155a42bff69035b Model layer 클래스명 변경 하였습니다

2020-11-13 13:49 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-11-13 14:09 UTC, merged