HW-2 Remote Datasource와 Repository 추가하여 뷰와 데이터를 분리시키는 과제수행
sjjeong/GoogryAndroidArchitecutreStudy pull request #890
Opened 2020-11-09 13:39 UTC by dktsudgg

두번째 과제입니다.

2020-11-11 10:26 UTC, hhi-5258 reviewed
수고하셨습니다!

2020-11-11 10:26 UTC, hhi-5258 commented on class15/dktsudgg/AndroidArchitectureStudy/app/src/main/java/kr/dktsudgg/androidarchitecturestudy/MainActivity.kt
> +
이건 제가 그냥 궁금해서 질문드리는 건데, repository 를 interface 로 선언한 후, implement 한 클래스로 할당하는 이유가 있으신 가요?

2020-11-11 10:26 UTC, hhi-5258 commented on class15/dktsudgg/AndroidArchitectureStudy/app/src/main/java/kr/dktsudgg/androidarchitecturestudy/data/repository/NaverMovieRepository.kt
> +        successCallback: (NaverMovieResponse?) -> Unit,
파라미터를 nullable 로 받는 이유가 있으신 가요?

2020-11-11 15:45 UTC, dktsudgg commented on class15/dktsudgg/AndroidArchitectureStudy/app/src/main/java/kr/dktsudgg/androidarchitecturestudy/MainActivity.kt
> +
음 이거는 그냥 제 주관적인 생각인데요ㅎㅎ
MainActivity가 NaverMovieRepository**Impl**에 종속적일 것이라는 느낌 자체를 주기 싫었던 것 같아요.
(사실 지금 Impl클래스에는 인터페이스에서 정의한 메소드 밖에 없어서 그냥 구현체로 선언해도 상관 없다고 생각합니다ㅎㅎㅎ..)

예를 들면 NaverMovieRepository**Impl**클래스가 인터페이스에서 정의된 메소드 말고도 searchPopularMovies(인기있는 영화 검색)메소드도 추가되어있는 상황이라고 가정하고, 메인엑티비티에서 NaverMovieRepository**Impl**를 멤버변수로 선언해서 사용한다면

제가 사실 MainActivity에서 사용하고자 하는 메소드는 그냥 searchMovies메소드 하나였을 뿐인데, 
다른 개발자가 봤을 때 "굳이 searchPopularMovies 메소드도 존재하는 NaverMovieRepository**Impl**클래스를 멤버변수로 선언한 이유가 있겠지 !" 라고 오해하는 여지를 없애고 싶었던 것 같습니다!

만약 메인엑티비티에서 NaverMovieRepository**Impl*에 종속적인 구현을 처음부터 의도했을 경우에는 구현체를 멤버변수로 선언해서 사용하는 게 맞다고 생각합니다!

2020-11-11 15:54 UTC, hhi-5258 commented on class15/dktsudgg/AndroidArchitectureStudy/app/src/main/java/kr/dktsudgg/androidarchitecturestudy/MainActivity.kt
> +
아하, 의도를 명확히 전달하기 위해서 이렇게 할 수도 있군요 ㅎㅎ 
상세한 설명 정말 감사합니다!

2020-11-11 16:18 UTC, dktsudgg commented on class15/dktsudgg/AndroidArchitectureStudy/app/src/main/java/kr/dktsudgg/androidarchitecturestudy/data/repository/NaverMovieRepository.kt
> +        successCallback: (NaverMovieResponse?) -> Unit,
Retrofit으로 요청했던 응답 결과를 사용 할 때, response.body()메소드의 리턴타입이 null가능이라서 이렇게 선언했었는데,
생각해보니 성공콜백에서 응답 결과를 null로 주는 경우를 고려하는 것 자체가 직관적이지 않은 것 같네요!
수정하였습니다 감사합니다!

2020-11-11 16:28 UTC, hhi-5258 commented on class15/dktsudgg/AndroidArchitectureStudy/app/src/main/java/kr/dktsudgg/androidarchitecturestudy/data/repository/NaverMovieRepository.kt
> +        successCallback: (NaverMovieResponse?) -> Unit,
저는 검색은 성공하였는데 결과 값 자체가 없는 상황을 success 로 고려하시는 건가 궁금했어요. 

response.body를 받을 때 non-null 체크를 하기 위해 let 을 사용하기도 하더라구요, 참고하시라고 링크 남겨둘께요. 수고하셨습니다!
https://blog.yena.io/studynote/2020/04/15/Kotlin-Scope-Functions.html

2020-11-12 06:55 UTC, hhi-5258 approved these changes

2020-11-12 09:48 UTC, sjjeong requested changes

2020-11-12 09:48 UTC, sjjeong commented on class15/dktsudgg/AndroidArchitectureStudy/app/src/main/java/kr/dktsudgg/androidarchitecturestudy/data/datasource/remote/NaverMovieDataSource.kt
> +interface NaverMovieDataSource {
Remote 작업을 수행하는 interface 니까
NaverMovieRemoteDataSource로 변경해주세요

2020-11-12 13:07 UTC, dktsudgg commented on class15/dktsudgg/AndroidArchitectureStudy/app/src/main/java/kr/dktsudgg/androidarchitecturestudy/data/datasource/remote/NaverMovieDataSource.kt
> +interface NaverMovieDataSource {
43a3dd3
수정하였습니다. 감사합니다!

2020-11-13 13:50 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-11-13 13:55 UTC, merged