HW2 - Repository
sjjeong/GoogryAndroidArchitecutreStudy pull request #892
Opened 2020-11-09 15:59 UTC by dev-donghwan

2020-11-10 13:40 UTC, onxmoreplz commented on class14/dev-donghwan/studyfork/app/src/main/res/layout/activity_main.xml
> +    </data>
<Data> 태그 안에 내용이 없는 건 나중을 위해서인가요? 궁금해서요.

2020-11-10 13:40 UTC, onxmoreplz commented on class14/dev-donghwan/studyfork/app/src/main/java/com/example/studyfork/model/RepositoryImpl.kt
> +        this.compositeDisposable.clear()
메모리 누수 막기 위해 CompositeDisposable 클래스 사용하신 건가요?

2020-11-10 13:40 UTC, onxmoreplz commented on class14/dev-donghwan/studyfork/app/src/main/java/com/example/studyfork/model/RepositoryImpl.kt
> +class RepositoryImpl(private val remoteDataSource: RemoteDataSource) : Repository {
RepositoryImpl 파라미터에 RemoteDataSource를 준 방법이 좋네요!

2020-11-11 01:40 UTC, dev-donghwan commented on class14/dev-donghwan/studyfork/app/src/main/res/layout/activity_main.xml
> +    </data>
음 일단 databinding을 디폴트로 생성할때 생기는 부분인데 사실 현재는 필요없어서 지워도 상관없지만 mvvm으로 bindingapdater 사용할때 필요하기도하고해서 그대로 둔 상태입니다.

2020-11-11 01:42 UTC, dev-donghwan commented on class14/dev-donghwan/studyfork/app/src/main/java/com/example/studyfork/model/RepositoryImpl.kt
> +        this.compositeDisposable.clear()
넵! 맞습니다.

2020-11-11 12:41 UTC, onxmoreplz approved these changes

2020-11-12 09:51 UTC, sjjeong requested changes

2020-11-12 09:51 UTC, sjjeong commented on class14/dev-donghwan/studyfork/app/src/main/java/com/example/studyfork/model/RepositoryImpl.kt
> +    private val compositeDisposable = CompositeDisposable()
Repository에서 CompositeDisposable을 관리하지 않도록 해주세요 
여러개 Fragment에서 같이 사용됐을 때 다른 Framgent에서 작업하던것도 같이 제거될 수 있습니다
Lifecycle관련해서 dispose해주는 거라면 각 Activity나 Fragment에서 관리하도록 해주세요

2020-11-12 09:51 UTC, sjjeong commented on class14/dev-donghwan/studyfork/app/build.gradle
> +    }
지금 추가하면 4주차에서 과제 할게 없습니다
일단 이대로 두는 것으로 할게요

2020-11-13 15:58 UTC, sjjeong approved these changes
리뷰코멘트에 커밋아이디 추가하는거 잊지 말아주세요 
LGTM ✊ ✌️ 👋

2020-11-14 02:13 UTC, merged