HW-2 Repository, RemoteDataSource 구현
sjjeong/GoogryAndroidArchitecutreStudy pull request #893
Opened 2020-11-09 16:01 UTC by hunihun

리뷰 부탁드리겠습니다!

2020-11-10 00:46 UTC, juan-rybczinski commented on .idea/workspace.xml
>    <component name="ChangeListManager">
gitignore에 추가되어 있는데 해당 파일 수정 이력이 계속 따라오는 이유가 뭘까요?

2020-11-10 01:22 UTC, juan-rybczinski commented on class14/hunihun/app/src/main/java/com/wybh/androidarchitecturestudy/data/remote/RemoteNaverApi.kt
> +interface RemoteNaverApi {
향후에 Naver 이외의 RemoteDataSource가 추가될 것을 대비해 Interface는 좀더 공통적인 Naming을 가져가는 게 어떨까요?

2020-11-10 01:26 UTC, hunihun commented on .idea/workspace.xml
>    <component name="ChangeListManager">
그러게요........구글링 해서 적용해봐도 계속 따라오네용 ......

2020-11-10 01:28 UTC, hunihun commented on class14/hunihun/app/src/main/java/com/wybh/androidarchitecturestudy/data/remote/RemoteNaverApi.kt
> +interface RemoteNaverApi {
다른 RemoteApi가 생기면 interface로 더 빼서 사용하려고 했는데 좋은 방법이 아닌건가요???????
뭔가 하나에 다 들어있으면 보기 안좋을거같아서요!

2020-11-10 01:34 UTC, juan-rybczinski commented on .idea/workspace.xml
>    <component name="ChangeListManager">
저도 가끔 gitignore가 말을 안 들을 때가 있던데 아래 링크 한번 참고해 보세요.
https://blog.skcript.com/gitignore-not-working-here-s-the-solution-c16e7b34dc9f

`git rm -r --cached .`
이 명령어가 좀 무서운(?) 것 같아서 아래 설명 잘 참고하시구요!

> Before you even try to execute any command from this post, make sure you have committed all the changes that you have made locally, and also you have fetched the code from the master to your local repo that others have committed.

2020-11-10 01:36 UTC, juan-rybczinski commented on class14/hunihun/app/src/main/java/com/wybh/androidarchitecturestudy/data/remote/RemoteNaverApi.kt
> +interface RemoteNaverApi {
아, 사실 저도 잘 몰라서 ㅋㅋㅋ 이 부분은 멘토님께 여쭤보는 게 좋을 것 같네요!

2020-11-10 01:38 UTC, juan-rybczinski approved these changes
고생 많으셨습니다!

2020-11-10 15:06 UTC, hunihun commented on .idea/workspace.xml
>    <component name="ChangeListManager">
감사합니다! 참고해서 적용해보겠습니다!!

2020-11-10 15:06 UTC, hunihun commented on class14/hunihun/app/src/main/java/com/wybh/androidarchitecturestudy/data/remote/RemoteNaverApi.kt
> +interface RemoteNaverApi {
넵!!!

2020-11-11 12:19 UTC, sjjeong commented on class14/hunihun/app/src/main/java/com/wybh/androidarchitecturestudy/data/remote/RemoteNaverApi.kt
> +interface RemoteNaverApi {
보통 api interface는 host url에 맞춰서 만드는 것 같아요
지금처럼 해도 좋다고 생각합니다

2020-11-11 12:27 UTC, sjjeong requested changes

2020-11-11 12:27 UTC, sjjeong commented on class14/hunihun/app/src/main/java/com/wybh/androidarchitecturestudy/data/remote/RemoteNaverApi.kt
> +interface RemoteNaverApi {
이름은 RemoteNaverDataSource로 해주세요

2020-11-11 16:14 UTC, hunihun commented on class14/hunihun/app/src/main/java/com/wybh/androidarchitecturestudy/data/remote/RemoteNaverApi.kt
> +interface RemoteNaverApi {
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/893/commits/ce1d3b7b2f83e32e5a9a6f05060e601da9f4c63b

수정했습니다!

2020-11-12 09:52 UTC, sjjeong commented on class14/hunihun/app/src/main/java/com/wybh/androidarchitecturestudy/data/remote/RemoteNaverApi.kt
> +interface RemoteNaverApi {
제가 이름을 잘못 남겼네요
NaverRemoteDataSource로 변경해주세요

2020-11-13 12:19 UTC, hunihun commented on class14/hunihun/app/src/main/java/com/wybh/androidarchitecturestudy/data/remote/RemoteNaverApi.kt
> +interface RemoteNaverApi {
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/893/commits/b3f3efedbb4ea8db26191ab0e959e89ae8bfb003

수정ㅎ했습니다!!

2020-11-13 13:51 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-11-13 14:15 UTC, merged