HW-2. 레포지토리 + remote 데이터 소스  적용 및 데이터 연결 과제
sjjeong/GoogryAndroidArchitecutreStudy pull request #895
Opened 2020-11-10 16:42 UTC by realizer12

2020-11-12 11:41 UTC, showmiso reviewed
전체적으로 함수 마지막 블록의 주석은 지우는게 좋을 것 같고, 코드정렬이 안되어있습니다.

2020-11-12 12:42 UTC, realizer12 commented
ac9ec78 해당 내용 반영했습니다!

2020-11-13 00:01 UTC, showmiso approved these changes

2020-11-13 16:00 UTC, sjjeong requested changes

2020-11-13 16:00 UTC, sjjeong commented on class15/realizer12/AndroidArchitectureStudy/app/src/main/java/com/example/androidarchitecturestudy/MainActivity.kt
> +    private val movieRepositoryImp = MovieRepositoryImpl()
변수명에 l이 빠진거같네요

2020-11-13 16:00 UTC, sjjeong commented on class15/realizer12/AndroidArchitectureStudy/app/src/main/java/com/example/androidarchitecturestudy/MainActivity.kt
> +            }else{
커밋하기전에 reformat code 하는거 잊지 말아주세요

2020-11-13 16:00 UTC, sjjeong commented on class15/realizer12/AndroidArchitectureStudy/app/src/main/java/com/example/androidarchitecturestudy/data/datasource/RemoteMovieDataImpl.kt
> +class RemoteMovieDataImpl : RemoteMovieDataSource {
이름은 MoviewRemoteDataSource와 MovieRemoteDataSourceImpl 이면 됩니다

2020-11-14 01:47 UTC, realizer12 commented on class15/realizer12/AndroidArchitectureStudy/app/src/main/java/com/example/androidarchitecturestudy/MainActivity.kt
> +    private val movieRepositoryImp = MovieRepositoryImpl()
f552602  해당 내용  수정 하였습니다!

2020-11-14 01:48 UTC, realizer12 commented on class15/realizer12/AndroidArchitectureStudy/app/src/main/java/com/example/androidarchitecturestudy/MainActivity.kt
> +            }else{
6154e70  reformat code  다시 진행하였습니다!

2020-11-14 01:48 UTC, realizer12 commented on class15/realizer12/AndroidArchitectureStudy/app/src/main/java/com/example/androidarchitecturestudy/data/datasource/RemoteMovieDataImpl.kt
> +class RemoteMovieDataImpl : RemoteMovieDataSource {
c513daf  이름 변경 완료 하였습니다!

2020-11-14 07:30 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-11-14 07:30 UTC, merged