HW3 - convert MVP
sjjeong/GoogryAndroidArchitecutreStudy pull request #896
Opened 2020-11-14 04:57 UTC by dev-donghwan

2020-11-16 12:36 UTC, onxmoreplz commented on class14/dev-donghwan/studyfork/app/src/main/java/com/example/studyfork/MainActivity.kt
> +    BaseActivity<ActivityMainBinding>(R.layout.activity_main),
특별히 BaseActivity라는 추상 클래스를 만드신 이유를 알 수 있을까요?

2020-11-17 01:47 UTC, dev-donghwan commented on class14/dev-donghwan/studyfork/app/src/main/java/com/example/studyfork/MainActivity.kt
> +    BaseActivity<ActivityMainBinding>(R.layout.activity_main),
원래는 BaseActivity Activity에서 공통으로 사용하는것들을 빼는 Base로 빼서 상속을 통해서 추가 선언없이 사용하는 목적으로 사용하려구 했습니다. 그리고 상속받으면 base가 먼저 생성되는걸로 알아서 binding을 초기화하는 부분을 base의 onCreate에 작성해서 지난번 석준님이 말씀하신 by lazy 사용할때 실수할 수 있는 부분을 없애려고 사용했습니다~

2020-11-17 11:30 UTC, onxmoreplz commented on class14/dev-donghwan/studyfork/app/src/main/java/com/example/studyfork/MainActivity.kt
> +    BaseActivity<ActivityMainBinding>(R.layout.activity_main),
효율적일 것 같네요! 알겠습니다!

2020-11-18 13:05 UTC, sjjeong requested changes

2020-11-18 13:05 UTC, sjjeong commented on class14/dev-donghwan/studyfork/app/src/main/java/com/example/studyfork/MainActivity.kt
> +        presenter.requestClearDisposable()
저번시간에 했던 Base 관계 만드는 것을 통해서 BaseActivity에서 처리하도록 해보세요

2020-11-20 07:38 UTC, dev-donghwan commented on class14/dev-donghwan/studyfork/app/src/main/java/com/example/studyfork/MainActivity.kt
> +        presenter.requestClearDisposable()
> 저번시간에 했던 Base 관계 만드는 것을 통해서 BaseActivity에서 처리하도록 해보세요

감이 잘 안오는데
BasePresenter에 requestClearDisposable()을 만들고
BaseActivity는 BaseView를 만들어 상속받고 onDestroy()에서 자동적으로 처리되도록 만들어야 하는건가요?

2020-11-20 15:09 UTC, sjjeong commented on class14/dev-donghwan/studyfork/app/src/main/java/com/example/studyfork/MainActivity.kt
> +        presenter.requestClearDisposable()
넵 그런식으로 하시면 됩니당

2020-11-21 05:28 UTC, sjjeong approved these changes
Base 작업하는건 필수는 아니니까 머지해주시고 다음 과제 진행해주세요

2020-11-21 07:18 UTC, onxmoreplz approved these changes

2020-11-23 06:44 UTC, merged