HW-3 Convert to MVP
sjjeong/GoogryAndroidArchitecutreStudy pull request #897
Opened 2020-11-14 11:16 UTC by jihoi-kang

2020-11-17 03:11 UTC, PeonyF commented
조언드릴 사항보단 배우는게 더 많아서 죄송하네요 유효하지 않은 검색어, 검색결과 처리, 기타 알수 없는 에러발생 처리 등 모두 잘 구현되어있어 approved 처리 하겠습니다.

2020-11-17 03:12 UTC, PeonyF approved these changes

2020-11-17 03:12 UTC, ChaaaChaaa commented on class15/jihoi-kang/aas/app/src/main/java/com/jay/aas/ui/MoviePresenter.kt
> +        }
try-catch문으로 예외 분리하시고 안에다가 progress 진행과정을 다 넣으셔서 한눈에 보기가 좋네요 하나 배워갑니다 👍

2020-11-17 03:12 UTC, PeonyF commented on class15/jihoi-kang/aas/app/src/main/java/com/jay/aas/ui/MoviePresenter.kt
> +        } else {
저는 결과가 없을경우 (showNoResult()) 를 구현하기 위해서 repository랑 remote에 해당값을 추가한 후 presenter에 넣는 방식으로 했는데  MoviePresenter에서 분기에 따라 진행하도록 하는 방식도 있군요. 여러 클래스를 변경하는것 보다 이게 더 간단해 보이네요 🤔🤔

2020-11-17 03:12 UTC, PeonyF commented on class15/jihoi-kang/aas/app/src/main/java/com/jay/aas/ui/MovieContract.kt
> +        fun searchMovies(query: String)
getMovies()를 따로 빼서 작성하셨네요 👍

2020-11-18 13:18 UTC, sjjeong requested changes
잘 하셨습니다
시간이 있으니 Base하는 작업 진행해보세요

2020-11-19 13:58 UTC, jihoi-kang commented
a85698c
Base 코드를 구현 할 때에 익숙하지 않아 코드 변경이 잦을 것 같아서 커밋을 분리하지 못하였습니다.

2020-11-19 14:49 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-11-19 15:26 UTC, merged