HW-3 MVP Design Pattern
sjjeong/GoogryAndroidArchitecutreStudy pull request #898
Opened 2020-11-14 11:55 UTC by Myung777

MVP 패턴으로 적용을 해보았습니다.
Presenter 를 생성해서 로직을 분리하였습니다.

2020-11-17 03:42 UTC, simuelunbo approved these changes
수고하셨습니다 
다음번에는 과제 적용 하시면서 새로운 기능들 조금씩 조금씩 추가하시면 좋을거 같아요

2020-11-18 13:22 UTC, sjjeong requested changes
잘 하셨습니다~
Base하는 작업도 해보세요

2020-11-20 11:46 UTC, Myung777 commented
@sjjeong 
base 하는 작업을 해보았는데 BasePresenter 어떠한 작업을 추가해야 할지 몰라서 비어두었습니다.
ea05293, 2f3d7ba

2020-11-20 15:11 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-11-20 15:16 UTC, merged