HW-3. MVP 패턴 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #899
Opened 2020-11-15 07:15 UTC by onxmoreplz

2020-11-16 01:31 UTC, dev-donghwan commented on class14/onxmoreplz/HW2_Project/app/src/main/java/com/example/hw2_project/RecyclerViewAdapter.kt
>                  Glide.with(view.context).load(movie.image).into(movie_img)
Glide 옵션에서 error를 처리하는 함수가 있는데 한번 찾아보시는것도 좋을거 같습니다.

2020-11-16 01:31 UTC, dev-donghwan commented on class14/onxmoreplz/HW2_Project/app/src/main/java/com/example/hw2_project/data/remote/MovieRemoteDataSourceImpl.kt
> +    private val CLIENT_SECRET = "v8aD8p_Ri0"
https://kimch3617.tistory.com/entry/Kotlin%EC%97%90%EC%84%9C-val-%EC%99%80-const-val-%EC%9D%98-%EC%B0%A8%EC%9D%B4

2020-11-16 12:39 UTC, onxmoreplz commented on class14/onxmoreplz/HW2_Project/app/src/main/java/com/example/hw2_project/RecyclerViewAdapter.kt
>                  Glide.with(view.context).load(movie.image).into(movie_img)
error 옵션이 있었군요! 감사합니다!

ad2cd3c

2020-11-16 12:40 UTC, onxmoreplz commented on class14/onxmoreplz/HW2_Project/app/src/main/java/com/example/hw2_project/data/remote/MovieRemoteDataSourceImpl.kt
> +    private val CLIENT_SECRET = "v8aD8p_Ri0"
const 변수로 바꿨습니다.

f168dd5

2020-11-18 13:25 UTC, sjjeong requested changes
잘 하셨습니다~
Base하는 작업도 해보세요

2020-11-21 05:28 UTC, sjjeong approved these changes
Base 작업하는건 필수는 아니니까 머지해주시고 다음 과제 진행해주세요

2020-11-23 13:05 UTC, dev-donghwan approved these changes

2020-11-23 13:06 UTC, merged