HW-3: MVP 패턴
sjjeong/GoogryAndroidArchitecutreStudy pull request #902
Opened 2020-11-16 09:33 UTC by simuelunbo

- View, Presenter 이용하여 구현 하였습니다 
- 해당 리스트 아이템을 클릭시 발생하는 이벤트를 추가적으로 구현 했습니다

2020-11-17 13:09 UTC, Myung777 reviewed
고생하셨습니다~

2020-11-17 13:09 UTC, Myung777 commented on class14/simuelunbo/AndroidArchitectureStudy/app/src/main/java/com/example/androidarchitecturestudy/ui/MainActivity.kt
> +    private val mainPresenter by lazy {
repositoryMovieImpl 를 이부분에서만 사용되는데 위에서 선언하지 않고 여기서 바로 사용하는 방법은 별로일까요?
repositorty 에 직접 접근할일이 없을것 같아서 여쭤봤습니다.

2020-11-17 13:09 UTC, Myung777 commented on class14/simuelunbo/AndroidArchitectureStudy/app/src/main/java/com/example/androidarchitecturestudy/ui/MainActivity.kt
> +            mainPresenter.openMovieLink(link)
액티비티를 한번만 이동하는 일인데 presenter 를 사용해야 하는것인지 궁금합니다.
저번주에 이런건 사람마다 다르다고 했던것 같은데 그게 이런건가요?

2020-11-18 07:01 UTC, simuelunbo commented on class14/simuelunbo/AndroidArchitectureStudy/app/src/main/java/com/example/androidarchitecturestudy/ui/MainActivity.kt
> +    private val mainPresenter by lazy {
위에서 선언하지 않고 바로 사용하는 방법이 무엇인가요?
repositoryMovieImple같은 경우에는 Presenter에 값을 전달하기 위해서 사용했습니다

2020-11-18 07:16 UTC, simuelunbo commented on class14/simuelunbo/AndroidArchitectureStudy/app/src/main/java/com/example/androidarchitecturestudy/ui/MainActivity.kt
> +            mainPresenter.openMovieLink(link)
추후에 단순히 페이지 이동이 아니라 로직을 처리하여 페이지 이동으로 수정 해야한다면 Presenter 에서 로직을 처리해야 하기 때문에 
presenter를 사용해야 한다 판단되어서 넣었습니다.

2020-11-18 07:27 UTC, Myung777 approved these changes

2020-11-18 07:27 UTC, Myung777 commented on class14/simuelunbo/AndroidArchitectureStudy/app/src/main/java/com/example/androidarchitecturestudy/ui/MainActivity.kt
> +    private val mainPresenter by lazy {
`   private val repositoryMovieImpl = NaverRepositoryImpl(remoteMovieDataImpl, localMovieDataImpl)`

위의 코드를 없애고  밑의 코드처럼 하면 더 코드가 줄어들지 않나 해서 여쭤봤습니다. 저처럼 하면 가독성은 떨어지는거 같은데 머가 더 좋은 방법인지 잘 모르겠네요
```
 private val mainPresenter by lazy { 
           MainPresenter(this, NaverRepositoryImpl(remoteMovieDataImpl, localMovieDataImpl))
  }
```

2020-11-18 13:41 UTC, sjjeong requested changes
변경하시고 Base하는 작업도 같이 해보세요

2020-11-18 13:41 UTC, sjjeong commented on class14/simuelunbo/AndroidArchitectureStudy/app/src/main/java/com/example/androidarchitecturestudy/ui/MainActivity.kt
> +    private val mainPresenter by lazy {
Activity에서는 data layer쪽에 있는 클래스들을 사용하지 않기 때문에 lazy안에서 presenter 만들때 생성하도록 해주세요

2020-11-18 13:41 UTC, sjjeong commented on class14/simuelunbo/AndroidArchitectureStudy/app/src/main/java/com/example/androidarchitecturestudy/ui/MainActivity.kt
> +            mainPresenter.openMovieLink(link)
제가 저번에 말씀 드렸던 내용이 이거 입니다.
이렇게 해도 괜찮고 저렇게 해도 괜찮습니다
저는 presenter를 거쳐서 처리하는 편입니다

2020-11-20 01:42 UTC, simuelunbo commented on class14/simuelunbo/AndroidArchitectureStudy/app/src/main/java/com/example/androidarchitecturestudy/ui/MainActivity.kt
> +    private val mainPresenter by lazy {
03f85a53e4fd6392f2f7009d5a51615f6d080519 수정하였습니다

2020-11-20 01:43 UTC, simuelunbo commented
base 작업도 추가 하였습니다 0650257512dcf1542ee59b7fd450c6d72147c48d

2020-11-20 15:24 UTC, sjjeong requested changes

2020-11-20 15:24 UTC, sjjeong commented on class14/simuelunbo/AndroidArchitectureStudy/app/src/main/java/com/example/androidarchitecturestudy/ui/BaseActivity.kt
> +import kotlinx.android.synthetic.main.activity_main.*
이렇게 되면 다른 Activity에서는 사용할수 없습니다
progressBar를 자식 클래스에서 받아오도록 해주세요

2020-11-21 05:26 UTC, simuelunbo commented on class14/simuelunbo/AndroidArchitectureStudy/app/src/main/java/com/example/androidarchitecturestudy/ui/BaseActivity.kt
> +import kotlinx.android.synthetic.main.activity_main.*
9c92796a028d910f63277d3e57ef116d73a81048 변경하였습니다

2020-11-21 06:01 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-11-21 06:33 UTC, merged