HW-3 : MVP 패턴 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #903
Opened 2020-11-16 11:31 UTC by hhi-5258

2020-11-17 12:17 UTC, dktsudgg approved these changes
잘 적용하신 것 같아서 approve하겠습니다. 수고하셨습니다!

2020-11-18 13:50 UTC, sjjeong requested changes
잘 하셨습니다~
Base 하는 작업도 해보세요

2020-11-20 12:55 UTC, hhi-5258 commented
> 잘 하셨습니다~
> Base 하는 작업도 해보세요

2020-11-20 13:00 UTC, hhi-5258 commented
base 추가해 보았습니다.

a0667ef
5201e76
98ab4dd

2020-11-20 15:37 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-11-20 15:38 UTC, merged