HW-3 뷰에 집중된 로직을 Presenter, View로 분리하는 MVP를 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #904
Opened 2020-11-16 11:50 UTC by dktsudgg

세번째 과제입니다.

2020-11-18 02:14 UTC, hhi-5258 approved these changes
수고하셨습니다, 잘 하신것 같아요!

2020-11-18 13:51 UTC, sjjeong requested changes
잘 하셨습니다~
Base 하는 작업도 해보세요

2020-11-19 16:43 UTC, dktsudgg commented
@sjjeong 
Base작업 적용해보았습니다. 감사합니다!

36da614, a10466a

2020-11-20 15:39 UTC, sjjeong requested changes

2020-11-20 15:39 UTC, sjjeong commented on class15/dktsudgg/AndroidArchitectureStudy/app/src/main/java/kr/dktsudgg/androidarchitecturestudy/BaseActivity.kt
> +open class BaseActivity<P : BasePresenter> : AppCompatActivity(), BaseContract.View {
open 보다 abstract를 사용하도록 해주세요 
BasePresenter도 변경해주세요

2020-11-20 15:39 UTC, sjjeong commented on class15/dktsudgg/AndroidArchitectureStudy/app/src/main/java/kr/dktsudgg/androidarchitecturestudy/BaseActivity.kt
> +    }
함수들이 하는 동작이 다 같다면 하나로 만들어도 되지 않을까요?
동작은 toast를 보여주는 것이기 때문에 showToast정도면 좋겠네요

2020-11-20 16:13 UTC, dktsudgg commented on class15/dktsudgg/AndroidArchitectureStudy/app/src/main/java/kr/dktsudgg/androidarchitecturestudy/BaseActivity.kt
> +open class BaseActivity<P : BasePresenter> : AppCompatActivity(), BaseContract.View {
수정하였습니다. 감사합니다!
38d298d

2020-11-20 16:13 UTC, dktsudgg commented on class15/dktsudgg/AndroidArchitectureStudy/app/src/main/java/kr/dktsudgg/androidarchitecturestudy/BaseActivity.kt
> +    }
수정하였습니다. 감사합니다!
53201f9

2020-11-21 01:39 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-11-21 01:39 UTC, sjjeong commented on class15/dktsudgg/AndroidArchitectureStudy/app/src/main/java/kr/dktsudgg/androidarchitecturestudy/view/ui/MoviePresenter.kt
> +        if (isEmptyData(query)) view.showToast("검색어를 입력하세요")
여기에 return이 필요해보이네요
다음 과제에서 추가해주세요

2020-11-21 05:51 UTC, merged