HW-3 MVP 패턴 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #905
Opened 2020-11-16 15:05 UTC by PeonyF

기존 작성한 프로젝트에서 MVP 패턴 적용하였습니다.

- MVP 패턴 적용으로 인한 MainContract, MainPresenter 생성
- MVP 패턴 적용으로 인한 코드 전체적인 수정(MainActivity)
- remote, repository 패키지에 결과값이 없을 경우 상황 관련 코드 추가

2020-11-17 01:51 UTC, jihoi-kang commented on class15/PeonyF/AndroidArchitectureStudy/app/src/main/java/com/architecture/androidarchitecturestudy/ui/MainContract.kt
> +        fun removeKeyboard(): Boolean
Presenter에서 `removeKeyboard()` 반환값을 가지고 뭔가를 하지 않기 때문에 반환값 없이 구현하셔도 될 거 같습니다.

2020-11-17 01:51 UTC, jihoi-kang commented on class15/PeonyF/AndroidArchitectureStudy/app/src/main/java/com/architecture/androidarchitecturestudy/ui/MainActivity.kt
> +            findMovie(et_main_search.text.toString())
`view`의 `findMovie(...)`를 호출하지 않고 바로 presenter의 findMovie를 호출하셔도 될 거 같습니다.

2020-11-17 05:58 UTC, PeonyF commented on class15/PeonyF/AndroidArchitectureStudy/app/src/main/java/com/architecture/androidarchitecturestudy/ui/MainContract.kt
> +        fun removeKeyboard(): Boolean
말씀하신대로 boolean을 삭제하였으며 그에 따라 MainActivity에 있는 removeKeyboard 메소드 또한 수정하였습니다.
(b5f69a2)

2020-11-17 06:07 UTC, PeonyF commented on class15/PeonyF/AndroidArchitectureStudy/app/src/main/java/com/architecture/androidarchitecturestudy/ui/MainActivity.kt
> +            findMovie(et_main_search.text.toString())
말씀하신대로 findMovie를 Presenter에서 바로 호출하도록 변경하였습니다. (45c422e)
이에 따라 사용하지 않게 되는 메소드를 MainActivity와 MainContract에서 삭제하하고 Presenter interface로 관련 메소드를 이동하였습니다.(f9a667e)

2020-11-17 07:38 UTC, jihoi-kang approved these changes
고생하셨습니다!
LGTM👍

2020-11-18 13:53 UTC, sjjeong requested changes
리뷰사항 반영하시고 Base하는것도 해보세요

2020-11-18 13:53 UTC, sjjeong commented on class15/PeonyF/AndroidArchitectureStudy/app/src/main/java/com/architecture/androidarchitecturestudy/data/remote/MovieRemoteDataSourceImpl.kt
> +                        }
비어있는지 검사하는 로직은 Presenter에서 하시면 됩니다

2020-11-18 13:53 UTC, sjjeong commented on class15/PeonyF/AndroidArchitectureStudy/app/src/main/java/com/architecture/androidarchitecturestudy/ui/MainContract.kt
> +        fun resultNone()
함수가 동사로 시작하도록 해주세요

2020-11-20 17:02 UTC, PeonyF commented on class15/PeonyF/AndroidArchitectureStudy/app/src/main/java/com/architecture/androidarchitecturestudy/ui/MainContract.kt
> +        fun resultNone()
말씀하신대로 함수명을 동사로 변경하였습니다. (aabc729)

2020-11-20 17:05 UTC, PeonyF commented on class15/PeonyF/AndroidArchitectureStudy/app/src/main/java/com/architecture/androidarchitecturestudy/data/remote/MovieRemoteDataSourceImpl.kt
> +                        }
기존에 위치한 검사로직을 모두 삭제, 변수를 String에서 none으로 변경하였습니다. (e95fbbf)
이에따라 MainPresenter 클래스에서 onEmptyList()에 의해 검사하도록 변경하였습니다.

2020-11-20 17:08 UTC, PeonyF commented
BaseActivity,BaseContract,BasePresenter 클래스를 생성하여 연결하였습니다.
(8ec08c0 , 94ec34d , 9e25047 , 094a3cd , 58dbb11 , f6cada4 , 00291fc , 984af71)

2020-11-21 01:50 UTC, sjjeong requested changes

2020-11-21 01:50 UTC, sjjeong commented on class15/PeonyF/AndroidArchitectureStudy/app/src/main/java/com/architecture/androidarchitecturestudy/ui/base/BaseActivity.kt
> +open class BaseActivity<P : BaseContract.Presenter> : AppCompatActivity(), BaseContract.View {
abstract로 변경해주세요
BasePresenter도 같이 변경해주세요

2020-11-21 01:50 UTC, sjjeong commented on class15/PeonyF/AndroidArchitectureStudy/app/src/main/java/com/architecture/androidarchitecturestudy/ui/base/BaseActivity.kt
> +    override fun showErrorMessage(message: String) {
에러만 보여주기 보다는 String을 토스트로 보여주는 함수니까 showToast나 showMessage정도면 좋을 것 같아요

2020-11-21 01:50 UTC, sjjeong commented on class15/PeonyF/AndroidArchitectureStudy/app/src/main/java/com/architecture/androidarchitecturestudy/ui/base/BaseContract.kt
> +class BaseContract {
interface로 해주세요

2020-11-21 01:50 UTC, sjjeong commented on class15/PeonyF/AndroidArchitectureStudy/app/src/main/java/com/architecture/androidarchitecturestudy/data/remote/MovieRemoteDataSourceImpl.kt
> +                            onEmptyList()
items.isNotEmpty()라는 아이템이 비어있는지 검사하는 로직 자체를 Presenter에서 해주셔야 합니다
onEmptyList 파라미터를 제거해주세요

2020-11-21 04:39 UTC, PeonyF commented on class15/PeonyF/AndroidArchitectureStudy/app/src/main/java/com/architecture/androidarchitecturestudy/ui/base/BaseActivity.kt
> +open class BaseActivity<P : BaseContract.Presenter> : AppCompatActivity(), BaseContract.View {
말씀하신대로 open에서 abstract클래스로 변경하였습니다. (95a50b2)

2020-11-21 04:40 UTC, PeonyF commented on class15/PeonyF/AndroidArchitectureStudy/app/src/main/java/com/architecture/androidarchitecturestudy/ui/base/BaseActivity.kt
> +    override fun showErrorMessage(message: String) {
메소드명을 showMessage로 변경하였습니다. (c5d01f1)

2020-11-21 04:40 UTC, PeonyF commented on class15/PeonyF/AndroidArchitectureStudy/app/src/main/java/com/architecture/androidarchitecturestudy/ui/base/BaseContract.kt
> +class BaseContract {
class에서 interface로 변경하였습니다. (4025b9b)

2020-11-21 04:49 UTC, PeonyF commented on class15/PeonyF/AndroidArchitectureStudy/app/src/main/java/com/architecture/androidarchitecturestudy/data/remote/MovieRemoteDataSourceImpl.kt
> +                            onEmptyList()
해당클래스의 onEmptyList 메소드를 제거하였으며 (943402a) 이에따라 연결되어있던 MovieRemoteDataSource.kt,MovieRemoteDataSourceImpl.kt,MovieRepository.kt ,MovieRepositoryImpl.kt 의 onEmptyList()를 모두 삭제하였습니다. (4fea673)
그리고 MainPresenter에 아이템 비어있는지 여부 확인하는 로직을 추가하였습니다. (d9a323e,b96155e)

2020-11-21 06:01 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-11-21 07:28 UTC, merged