Class14/hunihun
sjjeong/GoogryAndroidArchitecutreStudy pull request #906
Opened 2020-11-16 15:06 UTC by hunihun

HW-3 : MVP 패턴 적용

2020-11-17 00:44 UTC, juan-rybczinski commented on class14/hunihun/app/src/main/java/com/wybh/androidarchitecturestudy/CinemaAdapter.kt
> +                itemClickListener(itemList[adapterPosition].link)
저는 ViewHolder를 Adapter와 별도의 파일로 만들어서 ClickListener에서 선택한 Movie에 접근하기가 쉽지 않았는데 상훈님처럼 ViewHolder를 Adapter의 Inner 클래스로 만드는 게 좋을까요?

2020-11-17 00:44 UTC, juan-rybczinski commented on class14/hunihun/app/src/main/java/com/wybh/androidarchitecturestudy/main/MainActivity.kt
> +            startActivity(Intent(Intent.ACTION_VIEW, Uri.parse(it)))
이 부분도 View와 Presenter의 인터페이스에 정의하면 너무 과할까요?

2020-11-17 00:45 UTC, juan-rybczinski commented on class14/hunihun/app/src/main/java/com/wybh/androidarchitecturestudy/main/MainActivity.kt
> +            startActivity(Intent(Intent.ACTION_VIEW, Uri.parse(it)))
41번 라인만 선택하고 싶은데 잘 안되네요 ㅋㅋㅋ

2020-11-18 13:59 UTC, sjjeong requested changes

2020-11-18 13:59 UTC, sjjeong commented on class14/hunihun/app/src/main/java/com/wybh/androidarchitecturestudy/CinemaAdapter.kt
> +                itemClickListener(itemList[adapterPosition].link)
inner클래스로 하면 나중에 분리할때 문제가 되서 생성자로 넘겨주면 좋아요
지금은 따로 변경하지 않아도 됩니다

2020-11-18 13:59 UTC, sjjeong commented on class14/hunihun/app/src/main/java/com/wybh/androidarchitecturestudy/main/MainActivity.kt
> +    }
클래스 내부에 함수와 변수등 위치가 어디있어야 하는지 컨벤션이 있습니다.
https://kotlinlang.org/docs/reference/coding-conventions.html#class-layout

2020-11-18 13:59 UTC, sjjeong commented on class14/hunihun/app/src/main/java/com/wybh/androidarchitecturestudy/main/MainActivity.kt
> +        }
run은 불필요해보입니다
`rvCinema.adapter = cinemaAdapter` 로 변경해주세요

2020-11-18 13:59 UTC, sjjeong commented on class14/hunihun/app/src/main/java/com/wybh/androidarchitecturestudy/model/remote/NaverRemoteDataSourceImpl.kt
> +    }
repository나 data source 등의 클래스는 singleton으로 많이 사용됨으로써 여기서 CompositeDisposable을 관리하는건 좋지 않습니다 Presenter에서 관리하도록 해주시고 subscrdibe도 Presenter에서 하도록 해주세요

2020-11-19 15:51 UTC, hunihun commented on class14/hunihun/app/src/main/java/com/wybh/androidarchitecturestudy/CinemaAdapter.kt
> +                itemClickListener(itemList[adapterPosition].link)
별도 파일로 만들어서 사용했을때에도 viewHolder에 movieAdapter에서 사용하는 item이 바인딩된 뷰를 전달해서 사용하기 때문에 다른 Adapter에서 재사용이 가능한가싶네요!
 굳이 뽑자면 viewType 으로 구분해서 아이템을 생성해주는 Adapter에서는 사용이 가능할거같긴한데...
석준님께 물어봅시다!!ㅎㅎ

2020-11-19 15:51 UTC, hunihun commented on class14/hunihun/app/src/main/java/com/wybh/androidarchitecturestudy/main/MainActivity.kt
> +            startActivity(Intent(Intent.ACTION_VIEW, Uri.parse(it)))
제가 저번 수업때 이해했던건 뷰와 로직의 분리였는데 로직이 없는데 presenter에서 구현할 필요가 있는지 헷갈리네요...ㅎㅎ

이것도 물어봐야 할 것 같아요!

2020-11-19 15:51 UTC, hunihun commented on class14/hunihun/app/src/main/java/com/wybh/androidarchitecturestudy/CinemaAdapter.kt
> +                itemClickListener(itemList[adapterPosition].link)
나중에 분리를 해야하는 경우가 언제인지 알수있을까요 ???

2020-11-19 15:51 UTC, hunihun commented on class14/hunihun/app/src/main/java/com/wybh/androidarchitecturestudy/model/remote/NaverRemoteDataSourceImpl.kt
> +    }
Presenter 에서 subscribe를 어떤방식으로 사용해야하는지 감이 잘 안잡힙니다 ㅠㅠ
설명 한번 부탁드려도 될까요 ?

2020-11-19 15:52 UTC, hunihun commented on class14/hunihun/app/src/main/java/com/wybh/androidarchitecturestudy/main/MainActivity.kt
> +        }
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/906/commits/10786cb6d597ece9e7fba58009f93ec0d2e8141d

변경했습니다!

2020-11-20 05:17 UTC, juan-rybczinski approved these changes
고생 많으셨습니다!

2020-11-20 15:41 UTC, sjjeong commented on class14/hunihun/app/src/main/java/com/wybh/androidarchitecturestudy/model/remote/NaverRemoteDataSourceImpl.kt
> +    }
Rx 생산자를 리턴으로 받아서 처리하면 됩니다

2020-11-20 16:52 UTC, hunihun commented on class14/hunihun/app/src/main/java/com/wybh/androidarchitecturestudy/model/remote/NaverRemoteDataSourceImpl.kt
> +    }
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/906/commits/51cf4ceda77d20a4ae2c92f733e92784d0f6bbf2

이렇게하면 될까요 !?

2020-11-21 01:40 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-11-21 03:32 UTC, merged