HW-4 : Data Binding, 최근 검색 추가
sjjeong/GoogryAndroidArchitecutreStudy pull request #908
Opened 2020-11-23 09:43 UTC by hhi-5258

2020-11-25 08:31 UTC, dktsudgg commented on class15/hhi-5258/HHiApplication/app/src/main/java/com/hhi/myapplication/data/local/SharedPreferenceUtil.kt
> +    }
SharedPreferenceUtil클래스는 유틸성 클래스니까 단순히 shared preferences에 put/get하는 로직만 넣어두고
영화와 관련된 로직들을 repository쪽으로 옮기는 건 어떨까요??

아니면 혹시 제가 이해한 것과는 달리 saveQuery / getQueryList 메소드가 
영화 이력 저장 기능에 특정된 것이 아니라, 어떤 데이터를 정렬해 넣는 기능을 공통적으로 작성하신 거라면 메소드명만 적절히 바꿔주시는 것도 괜찮을 것 같아요!

2020-11-25 08:32 UTC, dktsudgg commented on class15/hhi-5258/HHiApplication/app/src/main/java/com/hhi/myapplication/data/local/SharedPreferenceUtil.kt
> +    }
리뷰가 늦어서 죄송합니다! 다음 과제 부터는 일찍 리뷰할게요ㅠㅠ

2020-11-25 12:10 UTC, hhi-5258 commented on class15/hhi-5258/HHiApplication/app/src/main/java/com/hhi/myapplication/data/local/SharedPreferenceUtil.kt
> +    }
재사용성을 위해서 그렇게 하는게 훨씬 좋을것 같아요, 감사합니다!
그렇게 수정하였습니다.

950622c

2020-11-25 13:27 UTC, dktsudgg approved these changes
수고하셨습니다!

2020-11-26 14:51 UTC, sjjeong requested changes

2020-11-26 14:51 UTC, sjjeong commented on class15/hhi-5258/HHiApplication/app/src/main/java/com/hhi/myapplication/App.kt
> +    }
companion object는 클래스 안에서 맨 아래에 위치해야 합니다

2020-11-26 14:51 UTC, sjjeong commented on class15/hhi-5258/HHiApplication/app/src/main/java/com/hhi/myapplication/App.kt
> +        super.onCreate()
onCreate가 먼저 호출되도록 순서를 변경해주세요

2020-11-26 14:51 UTC, sjjeong commented on class15/hhi-5258/HHiApplication/app/src/main/java/com/hhi/myapplication/data/local/NaverLocalDataSourceImpl.kt
> +        }
jsonArray[i]로 접근해서 add하는 것보다
jsonArray.map {} 해서 하면 좋을 것 같네요

2020-11-26 14:51 UTC, sjjeong commented on class15/hhi-5258/HHiApplication/app/src/main/java/com/hhi/myapplication/data/local/SharedPreferenceUtil.kt
> +private const val FILENAME: String = "prefs"
FILE_NAME이 좀더 좋을 것 같아요

2020-11-26 14:51 UTC, sjjeong commented on class15/hhi-5258/HHiApplication/app/src/main/java/com/hhi/myapplication/main/MainActivity.kt
> +    private lateinit var binding: ActivityMainBinding
BaseActivity가 있으니까 Base쪽으로 빼보세요

2020-11-26 14:51 UTC, sjjeong commented on class15/hhi-5258/HHiApplication/app/src/main/java/com/hhi/myapplication/recentSearch/RecentSearchRecyclerAdapter.kt
> +            it.context.startActivity(intent)
MainActivity를 새로 띄우지 마시고 activity result 방식으로 처리해주세요

2020-11-26 14:51 UTC, sjjeong commented on class15/hhi-5258/HHiApplication/app/src/main/res/layout/recent_search_recycler_item.xml
> +            android:textSize="25dp"
크게 중요하지 않긴한데 Material Guide에서는 4의 배수를 사용하는것을 권장하고있어요

2020-11-26 14:51 UTC, sjjeong commented on class15/hhi-5258/HHiApplication/app/src/main/java/com/hhi/myapplication/recentSearch/RecentSearchRecyclerAdapter.kt
> +            itemView.recent_item_text_title.setOnClickListener(listener)
여기도 DataBinding으로 접근하게 변경해주세요

2020-11-26 14:51 UTC, sjjeong commented on class15/hhi-5258/HHiApplication/app/src/main/java/com/hhi/myapplication/recentSearch/RecentSearchRecyclerAdapter.kt
> +        this.queryList.addAll(list.asReversed())
이런 중복접근은 with나 run을 사용하면 좋습니다

2020-11-26 14:51 UTC, sjjeong commented on class15/hhi-5258/HHiApplication/app/src/main/java/com/hhi/myapplication/recentSearch/RecentSearchActivity.kt
> +    private fun setUpUI() {
이름은 setupUi로 해주세요

2020-11-27 13:51 UTC, hhi-5258 commented on class15/hhi-5258/HHiApplication/app/src/main/java/com/hhi/myapplication/recentSearch/RecentSearchActivity.kt
> +    private fun setUpUI() {
수정하였습니다!
d9f166d

2020-11-27 13:51 UTC, hhi-5258 commented on class15/hhi-5258/HHiApplication/app/src/main/java/com/hhi/myapplication/recentSearch/RecentSearchRecyclerAdapter.kt
> +        this.queryList.addAll(list.asReversed())
수정하였습니다!
50cd94d

2020-11-27 13:52 UTC, hhi-5258 commented on class15/hhi-5258/HHiApplication/app/src/main/java/com/hhi/myapplication/recentSearch/RecentSearchRecyclerAdapter.kt
> +            itemView.recent_item_text_title.setOnClickListener(listener)
수정하였습니다!
665efd4

2020-11-27 13:52 UTC, hhi-5258 commented on class15/hhi-5258/HHiApplication/app/src/main/res/layout/recent_search_recycler_item.xml
> +            android:textSize="25dp"
수정하였습니다!
ba60d57

2020-11-27 13:52 UTC, hhi-5258 commented on class15/hhi-5258/HHiApplication/app/src/main/java/com/hhi/myapplication/recentSearch/RecentSearchRecyclerAdapter.kt
> +            it.context.startActivity(intent)
수정하였습니다!
2d41448

2020-11-27 13:53 UTC, hhi-5258 commented on class15/hhi-5258/HHiApplication/app/src/main/java/com/hhi/myapplication/main/MainActivity.kt
> +    private lateinit var binding: ActivityMainBinding
수정하였습니다!
cb66eda

2020-11-27 13:53 UTC, hhi-5258 commented on class15/hhi-5258/HHiApplication/app/src/main/java/com/hhi/myapplication/data/local/SharedPreferenceUtil.kt
> +private const val FILENAME: String = "prefs"
수정하였습니다!
a8dadb3

2020-11-27 13:54 UTC, hhi-5258 commented on class15/hhi-5258/HHiApplication/app/src/main/java/com/hhi/myapplication/App.kt
> +    }
수정하였습니다!
55fcf2c

2020-11-27 13:54 UTC, hhi-5258 commented on class15/hhi-5258/HHiApplication/app/src/main/java/com/hhi/myapplication/App.kt
> +        super.onCreate()
수정하였습니다!
55fcf2c

2020-11-27 14:03 UTC, hhi-5258 commented on class15/hhi-5258/HHiApplication/app/src/main/java/com/hhi/myapplication/data/local/NaverLocalDataSourceImpl.kt
> +        }
제가 찾기엔 JSONArray 가 map 함수를 지원하지 않는 것 같은데 JSONArray 를 stream 으로 바꿔서 해야하는 건가요?

2020-11-27 15:52 UTC, sjjeong commented on class15/hhi-5258/HHiApplication/app/src/main/java/com/hhi/myapplication/data/local/NaverLocalDataSourceImpl.kt
> +        }
[i]로 접근해서 제공할 줄 알았는데 아니였군요
괜찮습니다

2020-11-27 15:55 UTC, sjjeong requested changes
상수로 사용하는 것들은 companion object로 옮겨주세요

2020-11-28 01:19 UTC, hhi-5258 commented
companion object 로 수정하였습니다!
080f825

2020-11-28 01:42 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-11-28 02:09 UTC, merged