HW-4 Add Databinding & Add latest search function
sjjeong/GoogryAndroidArchitecutreStudy pull request #909
Opened 2020-11-23 12:37 UTC by jihoi-kang

이번에 변경사항이 좀 많네요. Directory 변경 및 잘못 짜여진 코드들이 있어서 변경했습니다.

e4c2ecb 는 `BaseContract`가 `abstract class`여서 변경하였습니다.
dd9fb76 는 원래 ui directory 밑에 바로 Movie 관련된 Activity 코드들이 작성되어 있었는데 최근 검색 Activity가 추가되면서 directory 구조를 변경하였습니다. movie 라는 directory를 추가하여 Movie 관련된 Activity 코드들을 작성하였습니다.

2020-11-25 13:56 UTC, sjjeong requested changes

2020-11-25 13:56 UTC, sjjeong commented on class15/jihoi-kang/aas/app/src/main/java/com/jay/aas/ui/history/SearchHistoryViewHolder.kt
> +            searchHistory?.queryText?.let(onItemClick)
binding.item으로 접근하면 됩니다
MovieViewHolder도 동일하게 해주세요

2020-11-25 13:56 UTC, sjjeong commented on class15/jihoi-kang/aas/app/src/main/java/com/jay/aas/ui/movie/MovieActivity.kt
> +            data?.getStringExtra(EXTRA_QUERY_TEXT)?.let { query ->
SearchHistoryActivity. EXTRA_QUERY_TEXT 로 접근하도록 해주세요

2020-11-26 02:09 UTC, jihoi-kang commented on class15/jihoi-kang/aas/app/src/main/java/com/jay/aas/ui/movie/MovieActivity.kt
> +            data?.getStringExtra(EXTRA_QUERY_TEXT)?.let { query ->
수정하였습니다.
4ec6240

2020-11-26 02:09 UTC, jihoi-kang commented on class15/jihoi-kang/aas/app/src/main/java/com/jay/aas/ui/history/SearchHistoryViewHolder.kt
> +            searchHistory?.queryText?.let(onItemClick)
수정하였습니다.
d5e8882

2020-11-26 14:24 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-11-27 07:36 UTC, PeonyF approved these changes
수고하셨습니다!

2020-11-27 08:16 UTC, merged