HW-4: Databinding + 최근 검색어 추가
sjjeong/GoogryAndroidArchitecutreStudy pull request #910
Opened 2020-11-24 10:06 UTC by simuelunbo

2020-11-24 14:53 UTC, Myung777 reviewed
최근검색 다이얼로그에서 아이템을 클릭했을때 이벤트가 없는것 같은데 넣으면 좋을것 같아요~
고생하셨습니다!

2020-11-24 14:53 UTC, Myung777 commented on class14/simuelunbo/AndroidArchitectureStudy/app/src/main/java/com/example/androidarchitecturestudy/ui/TitleAdapter.kt
> +            binding.tvTitle.text = title
저도 이런식으로 구현을 하였는데 최근검색기록을 List<String> 말고 데이터 클래스를 만들어서 List<Title> 에 넣어서 xml 에서 @{movie.title} 이런식으로하면 더 깔끔할것 같아요. 근데 저는 데이터 클래스에 최근검색기록을 넣는방법을 못했는데 혹시 어떤식으로 구현하면 될지 아시나요?

2020-11-24 14:58 UTC, Myung777 commented on class14/simuelunbo/AndroidArchitectureStudy/app/src/main/java/com/example/androidarchitecturestudy/Preferences.kt
> +        editor.putString("titleList", jsonArray.toString())
"titleList" 같은 경우는 const val 으로 빼서 사용하면 좋을것 같아요

2020-11-25 12:04 UTC, simuelunbo commented on class14/simuelunbo/AndroidArchitectureStudy/app/src/main/java/com/example/androidarchitecturestudy/Preferences.kt
> +        editor.putString("titleList", jsonArray.toString())
6332478 변경했습니다

2020-11-25 12:06 UTC, simuelunbo commented on class14/simuelunbo/AndroidArchitectureStudy/app/src/main/java/com/example/androidarchitecturestudy/ui/TitleAdapter.kt
> +            binding.tvTitle.text = title
e65a695 저는 editText 입력 받는 데이터 클래스를 하나 생성 해서 만들었습니다

2020-11-25 12:40 UTC, Myung777 approved these changes

2020-11-25 12:41 UTC, Myung777 approved these changes

2020-11-25 13:24 UTC, sjjeong requested changes

2020-11-25 13:24 UTC, sjjeong commented on class14/simuelunbo/AndroidArchitectureStudy/app/src/main/java/com/example/androidarchitecturestudy/Preferences.kt
> +        }
이 로직은 LocalDataSource에 있고 여기서는 List<String>을 받아서 저장하게 하면 될 것 같습니다

2020-11-25 13:24 UTC, sjjeong commented on class14/simuelunbo/AndroidArchitectureStudy/app/src/main/java/com/example/androidarchitecturestudy/ui/TitleFragmentDialog.kt
> +        initRecyclerView()
이 두 작업은 onViewCreated에서 하도록 해주세요

2020-11-26 03:58 UTC, simuelunbo commented on class14/simuelunbo/AndroidArchitectureStudy/app/src/main/java/com/example/androidarchitecturestudy/ui/TitleFragmentDialog.kt
> +        initRecyclerView()
3050e0e 수정하였습니다

2020-11-26 03:59 UTC, simuelunbo commented on class14/simuelunbo/AndroidArchitectureStudy/app/src/main/java/com/example/androidarchitecturestudy/Preferences.kt
> +        }
dc54edf 변경하였습니다

2020-11-26 14:26 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-11-26 14:54 UTC, merged