HW-4 Databinding + 최근 검색 기록
sjjeong/GoogryAndroidArchitecutreStudy pull request #911
Opened 2020-11-24 14:06 UTC by Myung777

데이터 바인딩 적용하고 최근검색기록 페이지를 만들어보았습니다
최근 검색 아이템을 클릭하게 되면 그 문구에 맞는 영화 리스트를 보여주게 구현하였습니다.

2020-11-25 11:46 UTC, simuelunbo reviewed
리뷰가 늦어서 죄송합니다
과제 하시느라 고생하셨습니다

2020-11-25 11:46 UTC, simuelunbo commented on class14/myung777/StudyFork/app/src/main/java/com/deepco/studyfork/MainActivity.kt
>          search_btn.setOnClickListener {
XML파일 activity_main에 Listener bindings 가능해요

2020-11-25 11:46 UTC, simuelunbo commented on class14/myung777/StudyFork/app/src/main/java/com/deepco/studyfork/RecentSearchActivity.kt
> +    private val mainPresenter by lazy {
mainPresenter 변수명 변경해주세요

2020-11-25 11:46 UTC, simuelunbo commented on class14/myung777/StudyFork/app/src/main/java/com/deepco/studyfork/RecentSearchRecyclerAdapter.kt
> +    fun clear() {
clear() 함수 사용하지 않고 있네요

2020-11-25 11:46 UTC, simuelunbo commented on class14/myung777/StudyFork/app/src/main/java/com/deepco/studyfork/BaceActivity.kt
>  open class BaseActivity<P : BasePresenter> : AppCompatActivity(), BaseContract.View {
https://seunghyun.in/android/1/ 이 글 한번 참고하세요 얼마 안되는 짧은 코드이긴 하지만 이런 방법으로 Boilerplate 코드를 줄일수 있다고 하네요

2020-11-25 15:18 UTC, Myung777 commented on class14/myung777/StudyFork/app/src/main/java/com/deepco/studyfork/RecentSearchActivity.kt
> +    private val mainPresenter by lazy {
변경하였습니다
b1ebb68

2020-11-25 15:18 UTC, Myung777 commented on class14/myung777/StudyFork/app/src/main/java/com/deepco/studyfork/MainActivity.kt
>          search_btn.setOnClickListener {
3fc464d

2020-11-25 15:18 UTC, Myung777 commented on class14/myung777/StudyFork/app/src/main/java/com/deepco/studyfork/BaceActivity.kt
>  open class BaseActivity<P : BasePresenter> : AppCompatActivity(), BaseContract.View {
좋은 방법 감사합니다 👍 
3fc464d

2020-11-25 15:19 UTC, Myung777 commented on class14/myung777/StudyFork/app/src/main/java/com/deepco/studyfork/RecentSearchRecyclerAdapter.kt
> +    fun clear() {
현재 사용하지 않아도 clear 는 필요할 곳이 있을것 같아서 미리 생성 해두었습니다.

2020-11-26 03:22 UTC, simuelunbo approved these changes

2020-11-26 15:11 UTC, sjjeong requested changes
다음부터 커밋 앞에 HW-n 추가해주세요

2020-11-26 15:11 UTC, sjjeong commented on class14/myung777/StudyFork/app/src/main/java/com/deepco/studyfork/BaceActivity.kt
> +open class BaseActivity<presenter : BaseContract.Presenter, binding : ViewDataBinding>(@LayoutRes val layoutResId: Int) :
abstract class로 변경해주세요

2020-11-26 15:11 UTC, sjjeong commented on class14/myung777/StudyFork/app/src/main/java/com/deepco/studyfork/BaceActivity.kt
> +    protected lateinit var binding: binding
보통 Generic은 대문자로 표기 합니다
```kotlin
protected lateinit var binding: B
```

2020-11-26 15:11 UTC, sjjeong commented on class14/myung777/StudyFork/app/src/main/java/com/deepco/studyfork/BaceActivity.kt
> +    }
이것들은 Base와 거리가 멀어보입니다
특성 Activity class로 이동시켜주세요

2020-11-26 15:11 UTC, sjjeong commented on class14/myung777/StudyFork/app/src/main/java/com/deepco/studyfork/MyApplication.kt
> +    }
companion object는 클래스 안에서 맨 아래에 위치해야 합니다

2020-11-26 15:11 UTC, sjjeong commented on class14/myung777/StudyFork/app/src/main/java/com/deepco/studyfork/MyApplication.kt
> +    }
onCreate가 먼저 호출되도록 순서를 변경해주세요

2020-11-26 15:11 UTC, sjjeong commented on class14/myung777/StudyFork/app/src/main/java/com/deepco/studyfork/RecentSearchActivity.kt
> +        api = RetrofitService.create()
이렇게 따로 뺄 필요 없이 RemoteMovieDataImpl 만들때 넣어주세요

2020-11-26 15:11 UTC, sjjeong commented on class14/myung777/StudyFork/app/src/main/java/com/deepco/studyfork/RecentSearchActivity.kt
> +import kotlinx.android.synthetic.main.activity_main.*
DataBinding으로 접근하도록 해주세요

2020-11-26 16:05 UTC, Myung777 commented on class14/myung777/StudyFork/app/src/main/java/com/deepco/studyfork/BaceActivity.kt
> +open class BaseActivity<presenter : BaseContract.Presenter, binding : ViewDataBinding>(@LayoutRes val layoutResId: Int) :
ffc526d

2020-11-26 16:05 UTC, Myung777 commented on class14/myung777/StudyFork/app/src/main/java/com/deepco/studyfork/BaceActivity.kt
> +    protected lateinit var binding: binding
47512dc

2020-11-26 16:05 UTC, Myung777 commented on class14/myung777/StudyFork/app/src/main/java/com/deepco/studyfork/BaceActivity.kt
> +    }
8881c3d

2020-11-26 16:05 UTC, Myung777 commented on class14/myung777/StudyFork/app/src/main/java/com/deepco/studyfork/MyApplication.kt
> +    }
15821e2

2020-11-26 16:06 UTC, Myung777 commented on class14/myung777/StudyFork/app/src/main/java/com/deepco/studyfork/RecentSearchActivity.kt
> +        api = RetrofitService.create()
51fa491

2020-11-26 16:06 UTC, Myung777 commented on class14/myung777/StudyFork/app/src/main/java/com/deepco/studyfork/RecentSearchActivity.kt
> +import kotlinx.android.synthetic.main.activity_main.*
48be2c0

2020-11-26 16:06 UTC, Myung777 commented
커밋을 HW-n 으로 하라는 문구를 제대로 보지 못했네요 다음 작업부터는 그렇게 진행하도록 할게요!

2020-11-27 12:41 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-11-27 12:42 UTC, sjjeong commented
제가 리뷰 해드리는 내용을 한줄한줄 다 해드릴수는 없어요
앞으로는 리뷰 해드린 내용에 대해 비슷한 항목이 있으면 같이 변경해주세요

2020-11-28 02:02 UTC, merged