HW-4 : Add dataBinding and History feature
sjjeong/GoogryAndroidArchitecutreStudy pull request #912
Opened 2020-11-24 14:22 UTC by showmiso

2020-11-25 16:30 UTC, realizer12 reviewed
이상입니다!. 
수고하셨습니다 미소님~

(저도 과제 오늘 중으로  빨리 올리겠습니다 ㅠ )

2020-11-25 16:30 UTC, realizer12 commented on class15/showmiso/ArchitectureStudy/app/src/main/java/com/showmiso/architecturestudy/MainActivity.kt
>              if (actionId == EditorInfo.IME_ACTION_SEARCH) {
음 이부분 @bindingadapter를  사용해서 
데이터 바인딩을 적용 할수 있지 않을까요??

2020-11-26 16:05 UTC, sjjeong requested changes
kotlinx.android.synthetic 로 view에 접근하던 방식을 DataBinding으로 접근하게 변경해주세요

2020-11-26 16:05 UTC, sjjeong commented on class15/showmiso/ArchitectureStudy/app/src/main/AndroidManifest.xml
> +        <activity android:name=".HistoryActivity"></activity>
/>로 끝내도 괜찮겠네요

2020-11-26 16:05 UTC, sjjeong commented on class15/showmiso/ArchitectureStudy/app/src/main/java/com/showmiso/architecturestudy/Constants.kt
> +    const val REQUEST_CODE = 0x01
한 엑티비티 안에 requestCode가 여러개가 되면 대응하기가 어렵게 됩니다
각 엑티비티 안에 const val로 어떤 동작의 requestCode인지 작성해주세요

2020-11-26 16:05 UTC, sjjeong commented on class15/showmiso/ArchitectureStudy/app/src/main/java/com/showmiso/architecturestudy/HistoryActivity.kt
> +import kotlinx.android.synthetic.main.activity_history.*
제거하고 Binding객체로 접근하게 해주세요

2020-11-26 16:05 UTC, sjjeong commented on class15/showmiso/ArchitectureStudy/app/src/main/res/layout/activity_history.xml
> +            android:onClick="onClick"
DataBinding에 listener binding으로 처리해주세요

2020-11-26 16:05 UTC, sjjeong commented on class15/showmiso/ArchitectureStudy/app/src/main/java/com/showmiso/architecturestudy/HistoryActivity.kt
> +        Toast.makeText(this, getString(R.string.msg_delete_all), Toast.LENGTH_SHORT).show()
이 동작들은 presenter에서 호출하도록 해주세요

2020-11-26 16:05 UTC, sjjeong commented on class15/showmiso/ArchitectureStudy/app/src/main/java/com/showmiso/architecturestudy/MainActivity.kt
> +            if (requestCode == Constants.REQUEST_CODE) {
보통은 requestCode로 먼저 검사하고 resultCode를 검사하는 편입니다

2020-11-26 16:05 UTC, sjjeong commented on class15/showmiso/ArchitectureStudy/app/src/main/java/com/showmiso/architecturestudy/data/local/LocalDataSourceImpl.kt
> +    private var data: String?
data는 예약어니까 다른 단어를 사용하도록 해주세요

2020-11-26 16:05 UTC, sjjeong commented on class15/showmiso/ArchitectureStudy/app/src/main/java/com/showmiso/architecturestudy/data/local/LocalDataSourceImpl.kt
> +class LocalDataSourceImpl(context: Context) : LocalDataSource {
context를 넘기기보다 context를 사용해서 만든 클래스(SharedPreference)를 넘기도록 해주세요

2020-11-26 16:05 UTC, sjjeong commented on class15/showmiso/ArchitectureStudy/app/src/main/java/com/showmiso/architecturestudy/data/repository/NaverRepository.kt
> +    fun removeAll()
removeAllHistory로 변경해주세요

2020-11-26 16:05 UTC, sjjeong commented on class15/showmiso/ArchitectureStudy/app/src/main/java/com/showmiso/architecturestudy/HistoryActivity.kt
> +        adapter.setHistoryList(presenter.getHistory())
presenter에서 값을 가져오는게 아니라 presenter에서 view에게 어떤 역할을 하라고 지정해야합니다

2020-11-26 16:05 UTC, sjjeong commented on class15/showmiso/ArchitectureStudy/app/src/main/java/com/showmiso/architecturestudy/HistoryActivity.kt
> +    override fun onItemClick(text: String) {
이게 어떤 작업을 하는건지 명확한 함수명으로 변경해주세요

2020-11-27 07:19 UTC, showmiso commented on class15/showmiso/ArchitectureStudy/app/src/main/AndroidManifest.xml
> +        <activity android:name=".HistoryActivity"></activity>
8de41104f973800723fb05c31786c05f0dbdbb5d
수정했습니다.

2020-11-27 07:19 UTC, showmiso commented on class15/showmiso/ArchitectureStudy/app/src/main/java/com/showmiso/architecturestudy/Constants.kt
> +    const val REQUEST_CODE = 0x01
58d21459c318177c078c4171d435700bb29a8b1c
REQUET_CODE 는 MainActivity 의 Companion으로 이동하고, 
RESULT 는 알아보기 쉽도록 이름 수정했습니다.

2020-11-27 07:21 UTC, showmiso commented on class15/showmiso/ArchitectureStudy/app/src/main/java/com/showmiso/architecturestudy/data/repository/NaverRepository.kt
> +    fun removeAll()
0c01d110be4ecdc7a70878104d1ff7d12414e7de
넵 이름 수정했습니다.

2020-11-27 07:24 UTC, showmiso commented on class15/showmiso/ArchitectureStudy/app/src/main/res/layout/activity_history.xml
> +            android:onClick="onClick"
2b3eabd6952e2c3d59d8ae81dbddbd0892e3f873
onClick 제거했습니다.

2020-11-27 07:29 UTC, showmiso commented on class15/showmiso/ArchitectureStudy/app/src/main/java/com/showmiso/architecturestudy/data/local/LocalDataSourceImpl.kt
> +    private var data: String?
429eff7390ae5e00da5b0f6408455b092fb9916d
이름 수정했습니다.

2020-11-27 07:38 UTC, showmiso commented on class15/showmiso/ArchitectureStudy/app/src/main/java/com/showmiso/architecturestudy/HistoryActivity.kt
> +import kotlinx.android.synthetic.main.activity_history.*
6e4c3adf271c2976ff1f8ce2041ec4c177385516
수정했습니다.

2020-11-27 07:41 UTC, showmiso commented on class15/showmiso/ArchitectureStudy/app/src/main/java/com/showmiso/architecturestudy/MainActivity.kt
> +            if (requestCode == Constants.REQUEST_CODE) {
398c5b1d2c4ebacd3ca5121989cf0b078e1befbe
수정했습니다.

2020-11-27 09:16 UTC, showmiso commented on class15/showmiso/ArchitectureStudy/app/src/main/java/com/showmiso/architecturestudy/HistoryActivity.kt
> +        Toast.makeText(this, getString(R.string.msg_delete_all), Toast.LENGTH_SHORT).show()
1dd8dc1ab92321692fc5288f8f10db48b2643992
HistoryContract, HistoryPresenter 수정했습니다.

2020-11-27 09:16 UTC, showmiso commented on class15/showmiso/ArchitectureStudy/app/src/main/java/com/showmiso/architecturestudy/HistoryActivity.kt
> +        adapter.setHistoryList(presenter.getHistory())
1dd8dc1ab92321692fc5288f8f10db48b2643992
수정했습니다.

2020-11-27 09:17 UTC, showmiso commented on class15/showmiso/ArchitectureStudy/app/src/main/java/com/showmiso/architecturestudy/HistoryActivity.kt
> +    override fun onItemClick(text: String) {
1dd8dc1ab92321692fc5288f8f10db48b2643992
이름 History 추가해서 변경했습니다. 
아이템을 클릭할때 검색하도록 하는 기능인데 기능을 설명하는 함수 명이 더 적절할까요?

2020-11-27 09:18 UTC, showmiso commented on class15/showmiso/ArchitectureStudy/app/src/main/java/com/showmiso/architecturestudy/HistoryActivity.kt
> +        Toast.makeText(this, getString(R.string.msg_delete_all), Toast.LENGTH_SHORT).show()
이렇게 기능 나누는게 아직 익숙치 않아서 어렵네요 ㅠㅠ

2020-11-27 09:23 UTC, showmiso commented on class15/showmiso/ArchitectureStudy/app/src/main/java/com/showmiso/architecturestudy/MainActivity.kt
>              if (actionId == EditorInfo.IME_ACTION_SEARCH) {
넵 :) 수정해볼게요 !

2020-11-27 09:29 UTC, showmiso commented on class15/showmiso/ArchitectureStudy/app/src/main/java/com/showmiso/architecturestudy/data/local/LocalDataSourceImpl.kt
> +class LocalDataSourceImpl(context: Context) : LocalDataSource {
a579c7c399800a114ae03a9ecf8cb2119b6808d8 
수정했습니다.

2020-11-27 10:51 UTC, showmiso commented on class15/showmiso/ArchitectureStudy/app/src/main/java/com/showmiso/architecturestudy/data/local/LocalDataSourceImpl.kt
> +class LocalDataSourceImpl(context: Context) : LocalDataSource {
8d66952d8fdcae6ad1315515dc4568b567f75892

2020-11-27 12:45 UTC, sjjeong commented on class15/showmiso/ArchitectureStudy/app/src/main/java/com/showmiso/architecturestudy/HistoryActivity.kt
> +        Toast.makeText(this, getString(R.string.msg_delete_all), Toast.LENGTH_SHORT).show()
괜찮습니다~ 이렇게 하면서 실력 늘어가는거죠

2020-11-27 12:47 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-11-27 23:15 UTC, realizer12 approved these changes

2020-11-28 01:41 UTC, merged