Class15/dktsudgg
sjjeong/GoogryAndroidArchitecutreStudy pull request #913
Opened 2020-11-25 12:49 UTC by dktsudgg

네번째 과제입니다. 늦어서 죄송합니다 ^^;

2020-11-25 13:49 UTC, hhi-5258 commented on class15/dktsudgg/AndroidArchitectureStudy/app/build.gradle
> +    implementation "com.facebook.stetho:stetho:$stetho_version"
이런 디버깅 플랫폼이 있고, 이렇게 사용하는지 덕분에 알게되었습니다!

2020-11-25 13:49 UTC, hhi-5258 commented on class15/dktsudgg/AndroidArchitectureStudy/app/src/main/java/kr/dktsudgg/androidarchitecturestudy/MainActivity.kt
> +    override fun updateMovieSearchHistoryList(data: List<String>) {
공통적으로 사용되지 않는 함수들도 override 되고 하니, MainActivity 와 MovieSearchHistoryActivity 의 Contract와 presenter 를 각각 따로 만드는 건 어떨까요?

2020-11-26 01:57 UTC, dktsudgg commented on class15/dktsudgg/AndroidArchitectureStudy/app/src/main/java/kr/dktsudgg/androidarchitecturestudy/MainActivity.kt
> +    override fun updateMovieSearchHistoryList(data: List<String>) {
기존에 작성된 MovieContract의 이름을 MovieSearchContract로 변경하였고
7189319

MovieSearchContract, MovieHistoryContract
MovieSearchPresenter, MovieHistoryPresenter
이렇게 두개로 분리 구현하였습니다. 감사합니다!
b48183e

2020-11-26 03:00 UTC, hhi-5258 approved these changes
수고하셨습니다!

2020-11-26 15:44 UTC, sjjeong requested changes

2020-11-26 15:44 UTC, sjjeong commented on class15/dktsudgg/AndroidArchitectureStudy/app/src/main/java/kr/dktsudgg/androidarchitecturestudy/MainActivity.kt
> +    private lateinit var binding: ActivityMainBinding
BaseActivity가 있으니까 binding 생성을 Base에서 해보세요

2020-11-26 15:44 UTC, sjjeong commented on class15/dktsudgg/AndroidArchitectureStudy/app/src/main/res/values/strings.xml
> +    <string name="movie_search_history">MOVIE_SEARCH_HISTORY</string>
보통 string res는 다국어를 위해서 사용합니다
이런 상수값들은 kotlin에서 관리해주세요

2020-11-26 15:44 UTC, sjjeong commented on class15/dktsudgg/AndroidArchitectureStudy/app/src/main/java/kr/dktsudgg/androidarchitecturestudy/view/adapter/MovieSearchHistoryListAdapter.kt
> +                    (binding.root.context as Activity).finish()
이 작업들은 Adapter 밖에서 처리해주세요

2020-11-26 15:44 UTC, sjjeong commented on class15/dktsudgg/AndroidArchitectureStudy/app/src/main/java/kr/dktsudgg/androidarchitecturestudy/view/adapter/MovieSearchHistoryListAdapter.kt
> +            when (clickedView.id) {
view id로 검사할 필요 없이 한가지 역할을 하는 함수로 만들어주면 됩니다

2020-11-26 15:44 UTC, sjjeong commented on class15/dktsudgg/AndroidArchitectureStudy/app/src/main/java/kr/dktsudgg/androidarchitecturestudy/view/adapter/MovieSearchHistoryListAdapter.kt
> +            binding.viewHolder = this
마지막에 binding.executePendingBindings()를 호출하도록 해주세요

2020-11-26 15:44 UTC, sjjeong commented on class15/dktsudgg/AndroidArchitectureStudy/app/src/main/java/kr/dktsudgg/androidarchitecturestudy/view/adapter/MovieSearchHistoryListAdapter.kt
> +        textList.addAll(txtList)
with나 run을 묶어서 사용할 수 있습니다

2020-11-26 15:44 UTC, sjjeong commented on class15/dktsudgg/AndroidArchitectureStudy/app/src/main/java/kr/dktsudgg/androidarchitecturestudy/MainActivity.kt
> +                movieSearchBtn.performClick()
resultCode가 OK인 경우 검사도 추가해주세요

2020-11-27 03:31 UTC, dktsudgg commented on class15/dktsudgg/AndroidArchitectureStudy/app/src/main/java/kr/dktsudgg/androidarchitecturestudy/MainActivity.kt
> +    private lateinit var binding: ActivityMainBinding
수정하였습니다. 감사합니다!
3fb9485

2020-11-27 03:31 UTC, dktsudgg commented on class15/dktsudgg/AndroidArchitectureStudy/app/src/main/res/values/strings.xml
> +    <string name="movie_search_history">MOVIE_SEARCH_HISTORY</string>
수정하였습니다. 감사합니다!
2e2f869

2020-11-27 03:33 UTC, dktsudgg commented on class15/dktsudgg/AndroidArchitectureStudy/app/src/main/java/kr/dktsudgg/androidarchitecturestudy/view/adapter/MovieSearchHistoryListAdapter.kt
> +                    (binding.root.context as Activity).finish()
이 로직을 BaseActivity쪽에 메소드를 만들어서 이관하고
어댑터에서는 그 메소드를 호출하도록 수정하였습니다. 감사합니다!
1767b32

2020-11-27 03:34 UTC, dktsudgg commented on class15/dktsudgg/AndroidArchitectureStudy/app/src/main/java/kr/dktsudgg/androidarchitecturestudy/view/adapter/MovieSearchHistoryListAdapter.kt
> +            when (clickedView.id) {
수정하였습니다. 감사합니다!
d6a38e7

2020-11-27 03:36 UTC, dktsudgg commented on class15/dktsudgg/AndroidArchitectureStudy/app/src/main/java/kr/dktsudgg/androidarchitecturestudy/view/adapter/MovieSearchHistoryListAdapter.kt
> +            binding.viewHolder = this
MovieSearchHistoryAdapter, MovieListAdapter
두 군데 모두 추가하였습니다. 감사합니다!
ece3ba4

2020-11-27 03:37 UTC, dktsudgg commented on class15/dktsudgg/AndroidArchitectureStudy/app/src/main/java/kr/dktsudgg/androidarchitecturestudy/view/adapter/MovieSearchHistoryListAdapter.kt
> +        textList.addAll(txtList)
수정하였습니다. 감사합니다!
5b79abb

2020-11-27 03:37 UTC, dktsudgg commented on class15/dktsudgg/AndroidArchitectureStudy/app/src/main/java/kr/dktsudgg/androidarchitecturestudy/MainActivity.kt
> +                movieSearchBtn.performClick()
수정하였습니다. 감사합니다!
f647d95

2020-11-27 13:31 UTC, sjjeong requested changes

2020-11-27 13:31 UTC, sjjeong commented on class15/dktsudgg/AndroidArchitectureStudy/app/src/main/java/kr/dktsudgg/androidarchitecturestudy/BaseActivity.kt
> +            setResult(RESULT_OK)
{} 추가해주세요

2020-11-27 14:25 UTC, dktsudgg commented on class15/dktsudgg/AndroidArchitectureStudy/app/src/main/java/kr/dktsudgg/androidarchitecturestudy/BaseActivity.kt
> +            setResult(RESULT_OK)
수정하였습니다. 감사합니다!
bf2bdcd

2020-11-27 15:56 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-11-27 16:03 UTC, merged