HW-4. Data Binding, 최근 검색 Activity 추가
sjjeong/GoogryAndroidArchitecutreStudy pull request #914
Opened 2020-11-25 13:13 UTC by onxmoreplz

최근 검색어 저장 Activity 만드는 부분에서 오래걸려 늦었습니다. 죄송합니다.
최근 검색어 저장 기능 구현 부분에서 @hhi-5258 님 PR 참고했습니다.

2020-11-26 13:03 UTC, dev-donghwan commented on class14/onxmoreplz/HW2_Project/app/src/main/java/com/example/hw2_project/ViewExtensions.kt
> +    Glide.with(this.context)
binding adapter에서 받아오는 인자는 nullable로 받아와서 null check후에 사용해야하는걸로 알고 있습니다!

2020-11-26 13:03 UTC, dev-donghwan commented on class14/onxmoreplz/HW2_Project/app/src/main/java/com/example/hw2_project/recentSearch/RecentSearchRecyclerViewAdapter.kt
> +            itemView.recent_item_text_title.setOnClickListener(listener)
여기도 databinding을 적용해 보는게 좋을거 같습니다.

2020-11-27 12:06 UTC, onxmoreplz commented on class14/onxmoreplz/HW2_Project/app/src/main/java/com/example/hw2_project/recentSearch/RecentSearchRecyclerViewAdapter.kt
> +            itemView.recent_item_text_title.setOnClickListener(listener)
네! 적용했습니다!

2723baf

2020-11-27 12:07 UTC, onxmoreplz commented on class14/onxmoreplz/HW2_Project/app/src/main/java/com/example/hw2_project/ViewExtensions.kt
> +    Glide.with(this.context)
그렇군요 수정했습니다!

77aeca7

2020-11-27 14:28 UTC, sjjeong requested changes

2020-11-27 14:28 UTC, sjjeong commented on class14/onxmoreplz/HW2_Project/app/src/main/java/com/example/hw2_project/App.kt
> +    }
companion object는 맨 아래로 옮겨주세요

2020-11-27 14:28 UTC, sjjeong commented on class14/onxmoreplz/HW2_Project/app/src/main/java/com/example/hw2_project/App.kt
> +        super.onCreate()
onCreate를 먼저 호출해주세요

2020-11-27 14:28 UTC, sjjeong commented on class14/onxmoreplz/HW2_Project/app/src/main/java/com/example/hw2_project/SharedPreferenceUtil.kt
> +class SharedPreferenceUtil( context : Context) {
reformat code 해주세요

2020-11-27 14:28 UTC, sjjeong commented on class14/onxmoreplz/HW2_Project/app/src/main/java/com/example/hw2_project/SharedPreferenceUtil.kt
> +        }
이런 로직은 LocalDataSource쪽에서 처리 해주세요

2020-11-27 14:28 UTC, sjjeong commented on class14/onxmoreplz/HW2_Project/app/src/main/java/com/example/hw2_project/main/MainActivity.kt
> +    private val movieRepositoryImp = MovieRepositoryImpl()
변수명에서 Imp는 빼주세요

2020-11-27 14:28 UTC, sjjeong commented on class14/onxmoreplz/HW2_Project/app/src/main/java/com/example/hw2_project/main/MainPresenter.kt
> +            repository.saveQuery(query)
save는 여기서 호출하지 마시고 repository에서 처리해주세요

2020-11-27 14:28 UTC, sjjeong commented on class14/onxmoreplz/HW2_Project/app/src/main/java/com/example/hw2_project/main/MainRecyclerViewAdapter.kt
> +        this.arrListOfMovie.addAll(movies)
with나 run으로 묶어줄 수 있습니다

2020-11-27 14:28 UTC, sjjeong commented on class14/onxmoreplz/HW2_Project/app/src/main/res/layout/activity_recent_search.xml
> +            android:onClick="@{() -> recentSearchActivity.clickBackBtn()}"/>
이 버튼 동작하나요?

2020-11-27 14:28 UTC, sjjeong commented on class14/onxmoreplz/HW2_Project/app/src/main/java/com/example/hw2_project/recentSearch/RecentSearchRecyclerViewAdapter.kt
> +            recentMovieItemBinding.recentItemTextTitle.setOnClickListener(listener)
리스너는 bind시점이 아니라 create시점에 추가하도록 해주세요

2020-11-27 16:12 UTC, onxmoreplz commented on class14/onxmoreplz/HW2_Project/app/src/main/java/com/example/hw2_project/App.kt
> +    }
코드 위치 수정했습니다!

23c07c9

2020-11-27 16:13 UTC, onxmoreplz commented on class14/onxmoreplz/HW2_Project/app/src/main/java/com/example/hw2_project/App.kt
> +        super.onCreate()
수정했습니다.


5191460

2020-11-27 16:13 UTC, onxmoreplz commented on class14/onxmoreplz/HW2_Project/app/src/main/java/com/example/hw2_project/SharedPreferenceUtil.kt
> +class SharedPreferenceUtil( context : Context) {
전체적으로 reformat 했습니다!

e4a32fe

2020-11-27 16:14 UTC, onxmoreplz commented on class14/onxmoreplz/HW2_Project/app/src/main/java/com/example/hw2_project/main/MainRecyclerViewAdapter.kt
> +        this.arrListOfMovie.addAll(movies)
with으로 묶었습니다! 감사합니다!

17f3101

2020-11-27 16:17 UTC, onxmoreplz commented on class14/onxmoreplz/HW2_Project/app/src/main/java/com/example/hw2_project/main/MainActivity.kt
> +    private val movieRepositoryImp = MovieRepositoryImpl()
변수명 수정했습니다.

9e739fb

2020-11-27 16:18 UTC, onxmoreplz commented on class14/onxmoreplz/HW2_Project/app/src/main/res/layout/activity_recent_search.xml
> +            android:onClick="@{() -> recentSearchActivity.clickBackBtn()}"/>
동작을 안하네요. 함수 참조도 되는데 실행이 안되는 이유가 뭔가요?

2020-11-29 13:40 UTC, onxmoreplz commented on class14/onxmoreplz/HW2_Project/app/src/main/java/com/example/hw2_project/main/MainRecyclerViewAdapter.kt
> +        this.arrListOfMovie.addAll(movies)
코드가 동작을 안해서 run함수로 바꿨습니다!

307f2ab

2020-11-29 13:41 UTC, onxmoreplz commented on class14/onxmoreplz/HW2_Project/app/src/main/java/com/example/hw2_project/main/MainPresenter.kt
> +            repository.saveQuery(query)
save기능 함수 위치 Repository로 이동했습니다.

cc569f8

2020-11-29 13:42 UTC, onxmoreplz commented on class14/onxmoreplz/HW2_Project/app/src/main/java/com/example/hw2_project/SharedPreferenceUtil.kt
> +        }
로직들 LocalDataSource에서 처리하도록 수정했습니다.

e248add

2020-11-29 13:46 UTC, onxmoreplz commented on class14/onxmoreplz/HW2_Project/app/src/main/java/com/example/hw2_project/recentSearch/RecentSearchRecyclerViewAdapter.kt
> +            recentMovieItemBinding.recentItemTextTitle.setOnClickListener(listener)
listener 추가 위치 변경하면서 click시 호출되는 함수 부분에 영화 text 전달하기 위해 인터페이스에 함수 만들어 오버라이딩했습니다.

추가로, MainActivity에서 액티비티 호출 함수 변경했습니다.(startActivity -> startActivityForResult)

2020-11-29 13:46 UTC, onxmoreplz commented on class14/onxmoreplz/HW2_Project/app/src/main/res/layout/activity_recent_search.xml
> +            android:onClick="@{() -> recentSearchActivity.clickBackBtn()}"/>
동작을 안하네요...제가 놓치고 있는 부분이 뭘까요...

2020-11-29 14:08 UTC, dev-donghwan approved these changes

2020-11-29 14:13 UTC, sjjeong commented on class14/onxmoreplz/HW2_Project/app/src/main/res/layout/activity_recent_search.xml
> +            android:onClick="@{() -> recentSearchActivity.clickBackBtn()}"/>
recentSearchActivity가 null이에요
binding.recentSearchActivity = this 추가해주면 됩니다

2020-11-29 14:20 UTC, onxmoreplz commented on class14/onxmoreplz/HW2_Project/app/src/main/res/layout/activity_recent_search.xml
> +            android:onClick="@{() -> recentSearchActivity.clickBackBtn()}"/>
감사합니다...놓쳐서는 안될거를 놓치고있었네요...
수정했습니다!


0cf3366

2020-11-29 14:21 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-11-29 14:47 UTC, merged