HW-4 Data Binding(+Recent Search)
sjjeong/GoogryAndroidArchitecutreStudy pull request #915
Opened 2020-11-25 16:32 UTC by juan-rybczinski

- 검색이 시작되고 끝날 때 ProgressBar visibility를 Data Binding으로 제어해 보려고 했는데 잘 안되네요.(Binding Adapter를 써야 할까요?)
- ChipGroup과 Chip을 활용해 봤는데 Chip 구성할 때 Data Binding을 어떻게 활용해야할 지 잘 몰라서 그냥 View에서 로직으로 만들어 버렸습니다 ;
- Coroutine을 쓰고는 있지만 잘 몰라서 ; Coroutine 안에서 반환 받은 값을 Binding Adapter에서 쓰려고 했더니 시점이 어긋나 버리네요.
- 공통되는 것 같은 로직을 Base로 하나하나 빼다보니 Base로 거의 다 옮겨 버렸네요 ;

2020-11-26 11:24 UTC, hunihun reviewed
늦어서 죄송합니다 ㅠㅠ (아직 제것도 못했어용...) 
프로젝트가 점점 커져서 어렵네요 ...ㅎㅎ, Room쪽은 제가 아예 몰라서 넘겼습니다 ㅠㅠ

2020-11-26 11:24 UTC, hunihun commented on class14/juan-rybczinski/GoogryAndroidArchitectureStudy/app/src/main/java/com/example/googryandroidarchitecturestudy/ui/fragment/BaseFragment.kt
> +    protected val movieRepository: MovieRepository by lazy {
repository 관리는 Fragment 가아니라 Prensenter에서 하지않나용 ????

2020-11-26 11:24 UTC, hunihun commented on class14/juan-rybczinski/GoogryAndroidArchitectureStudy/app/src/main/java/com/example/googryandroidarchitecturestudy/ui/fragment/BaseFragment.kt
> +    protected val movieAdapter = MovieAdapter {
BaseFragment 에 Adapter까지 관리할 필요가있나용 ???
뭔가 Base의 성격에 안맞는 듯한 느낌..?? (ProgressBar or Toast 등등이 맞는것같습니다!)

2020-11-27 09:30 UTC, juan-rybczinski commented on class14/juan-rybczinski/GoogryAndroidArchitectureStudy/app/src/main/java/com/example/googryandroidarchitecturestudy/ui/fragment/BaseFragment.kt
> +    protected val movieRepository: MovieRepository by lazy {
Repository에 접근하는 로직은 Presenter에 다 있으니 Repository는 Presenter로 가는게 맞겠네요. Presenter에 Repository 대신 Context를 전달하게 바꾸었습니다. MVP 역할 분리가 완전하지 않았는데 좋은 지적 감사합니다!

ab19c9ef5

2020-11-27 09:31 UTC, juan-rybczinski commented on class14/juan-rybczinski/GoogryAndroidArchitectureStudy/app/src/main/java/com/example/googryandroidarchitecturestudy/ui/fragment/BaseFragment.kt
> +    protected val movieAdapter = MovieAdapter {
확실히 Base가 movieAdapter가 있는 건 이상하네요 😂
하지만 Movie와 Recent의 공통 로직은 공유하고 싶어 MovieList라는 새로운 추상화 계층을 또 만들었습니다. 이렇게 해도 되겠죠? ㅋㅋㅋ

1b3f84878

2020-11-27 09:51 UTC, hunihun commented on class14/juan-rybczinski/GoogryAndroidArchitectureStudy/app/src/main/java/com/example/googryandroidarchitecturestudy/ui/fragment/BaseFragment.kt
> +    protected val movieRepository: MovieRepository by lazy {
:+1:

2020-11-27 09:55 UTC, hunihun commented on class14/juan-rybczinski/GoogryAndroidArchitectureStudy/app/src/main/java/com/example/googryandroidarchitecturestudy/ui/fragment/BaseFragment.kt
> +    protected val movieAdapter = MovieAdapter {
MVP 패턴에 대한 단점중 view와 present 가 1:1 구조이기 때문에 중복되는 로직에 대한 문제를 본것같아요!
그걸 해결하기 위한게 MVVM이라고 알고있는데 MVP를 사용할때 중복로직에 대한 베스트가 뭔지 잘 모르겠네요..ㅎㅎ

2020-11-27 09:56 UTC, hunihun commented
고생하셨습니다!!

2020-11-27 09:57 UTC, hunihun approved these changes

2020-11-27 15:09 UTC, sjjeong requested changes

2020-11-27 15:09 UTC, sjjeong commented on class14/juan-rybczinski/GoogryAndroidArchitectureStudy/app/src/main/java/com/example/googryandroidarchitecturestudy/network/MovieHeaderInterceptor.kt
> +                    App.instance.getString(R.string.naver_client_secret)
key 값을 string res보다 kotlin에서 상수로 관리하게 해주세요

2020-11-27 15:09 UTC, sjjeong commented on class14/juan-rybczinski/GoogryAndroidArchitectureStudy/app/src/main/java/com/example/googryandroidarchitecturestudy/ui/fragment/BaseFragment.kt
> +    var onProgress = View.INVISIBLE
이거 프로그래스가 실제로는 동작을 안할 것 같은데 mvvm하면서 개선 될 거니까 넘어갈게요

2020-11-29 11:42 UTC, juan-rybczinski commented on class14/juan-rybczinski/GoogryAndroidArchitectureStudy/app/src/main/java/com/example/googryandroidarchitecturestudy/network/MovieHeaderInterceptor.kt
> +                    App.instance.getString(R.string.naver_client_secret)
BuildConfig 활용하게 수정했습니다.
gitignore에 등록한 secrets.xml로 관리하는 방법은 추천하지 않으시는 건가요?

 e13ef6af9

2020-11-29 12:16 UTC, sjjeong commented on class14/juan-rybczinski/GoogryAndroidArchitectureStudy/app/src/main/java/com/example/googryandroidarchitecturestudy/network/MovieHeaderInterceptor.kt
> +                    App.instance.getString(R.string.naver_client_secret)
resource에 접근하려면 context가 필요해서 저는 잘 안하는 편입니다.
라이브러리 내부에서 resource key로 접근하면 어쩔수 없이 그렇게 하지만 제가 관리하는 거라면 kotlin에서 관리해요

2020-11-29 12:16 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-11-30 00:00 UTC, merged