HW-4 Databinding, 최근 검색 기록 기능 추가
sjjeong/GoogryAndroidArchitecutreStudy pull request #916
Opened 2020-11-26 10:57 UTC by PeonyF

- Data Binding 적용
- SharedPreference를 사용하여 최근 검색 기록 저장(package : data.local) 하여 리사이클러뷰에 출력(package : ui.searchhistory)

2020-11-26 15:27 UTC, jihoi-kang commented on class15/PeonyF/AndroidArchitectureStudy/app/src/main/java/com/architecture/androidarchitecturestudy/adapter/MovieViewHolder.kt
> +        binding.movie = movieData
movie를 set한 후 바로 binding을 하기 위해서 `executePendingBindings`를 추가해주세요.
https://developer.android.com/topic/libraries/data-binding/generated-binding#immediate_binding

2020-11-26 15:27 UTC, jihoi-kang commented on class15/PeonyF/AndroidArchitectureStudy/app/src/main/java/com/architecture/androidarchitecturestudy/adapter/MovieViewHolder.kt
> +            val intent = Intent(Intent.ACTION_VIEW, Uri.parse(tempData.link))
`tempData.link` 대신 `binding.movie.link`로 접근 가능합니다.

2020-11-26 15:27 UTC, jihoi-kang commented on class15/PeonyF/AndroidArchitectureStudy/app/src/main/java/com/architecture/androidarchitecturestudy/ui/searchhistory/SearchHistoryContract.kt
> +class SearchHistoryContract {
interface로 구현해주세요.

2020-11-26 15:27 UTC, jihoi-kang commented on class15/PeonyF/AndroidArchitectureStudy/app/src/main/java/com/architecture/androidarchitecturestudy/ui/searchhistory/SearchHistoryViewHolder.kt
> +    private var searchHistoryEntity: SearchHistoryEntity? = null
`searchHistoryEntity` 변수를 쓰지 않는다면 삭제하셔도 될거같습니다!

2020-11-26 15:27 UTC, jihoi-kang commented on class15/PeonyF/AndroidArchitectureStudy/app/src/main/java/com/architecture/androidarchitecturestudy/util/App.kt
> +    }
companion object는 `onCreate()` 아래로 내려주세요.

2020-11-26 19:23 UTC, PeonyF commented on class15/PeonyF/AndroidArchitectureStudy/app/src/main/java/com/architecture/androidarchitecturestudy/adapter/MovieViewHolder.kt
> +        binding.movie = movieData
말씀하신 excutePendingBindings 추가하였습니다. ( 추가 설명 감사합니다. 👍 )
6ce6490

2020-11-26 19:24 UTC, PeonyF commented on class15/PeonyF/AndroidArchitectureStudy/app/src/main/java/com/architecture/androidarchitecturestudy/adapter/MovieViewHolder.kt
> +            val intent = Intent(Intent.ACTION_VIEW, Uri.parse(tempData.link))
binding을 사용하지 않았던 변수들 모두 변경하였습니다. (39c8053)

2020-11-26 19:24 UTC, PeonyF commented on class15/PeonyF/AndroidArchitectureStudy/app/src/main/java/com/architecture/androidarchitecturestudy/ui/searchhistory/SearchHistoryContract.kt
> +class SearchHistoryContract {
Contract Class를 Interface로 변경하였습니다. (0d35496)

2020-11-26 20:12 UTC, PeonyF commented on class15/PeonyF/AndroidArchitectureStudy/app/src/main/java/com/architecture/androidarchitecturestudy/ui/searchhistory/SearchHistoryViewHolder.kt
> +    private var searchHistoryEntity: SearchHistoryEntity? = null
null인지 여부 확인 후 진행해야할 것 같아서 넣었습니다만,  굳이 진행할 필요가 없는것 같아 삭제 하였습니다. (2147906)

2020-11-26 20:13 UTC, PeonyF commented on class15/PeonyF/AndroidArchitectureStudy/app/src/main/java/com/architecture/androidarchitecturestudy/util/App.kt
> +    }
해당 부분외에 동일한 문제가 있는 부분들을 모두 onCreate() 밑 (클래스 가장 밑) 으로 이동하였습니다.
(18e72e3 )

2020-11-27 07:05 UTC, jihoi-kang approved these changes
확인하였습니다. 고생하셨습니다!
LGTM👍

2020-11-27 15:25 UTC, sjjeong requested changes

2020-11-27 15:25 UTC, sjjeong commented on class15/PeonyF/AndroidArchitectureStudy/app/src/main/java/com/architecture/androidarchitecturestudy/adapter/DataBindingAdapter.kt
> +@BindingAdapter("setImage")
저도 처음에는 set이라는 단어를 붙였는데 view의 attr 관점으로 보면 set은 빼도 될 것 같더라구요
imageUrl정도로 하면 좋을 것 같네요

2020-11-27 15:25 UTC, sjjeong commented on class15/PeonyF/AndroidArchitectureStudy/app/src/main/java/com/architecture/androidarchitecturestudy/adapter/MovieAdapter.kt
> +    private lateinit var binding: MovieItemBinding
여기에 선언하고 사용하시면 안됩니다
Binding객체는 ViewHolder랑 관련있는것이라서 그쪽에서 관리해야합니다

2020-11-27 15:25 UTC, sjjeong commented on class15/PeonyF/AndroidArchitectureStudy/app/src/main/java/com/architecture/androidarchitecturestudy/data/repository/MovieRepositoryImpl.kt
> +    }
이렇게 하면 매번 검색할때마다 save를 같이 해줘야 합니다
getMovieData를 호출할때 저장시키면 좋겠습니다

2020-11-27 15:25 UTC, sjjeong commented on class15/PeonyF/AndroidArchitectureStudy/app/src/main/java/com/architecture/androidarchitecturestudy/ui/searchhistory/SearchHistoryAdapter.kt
> +        holder.itemView.setOnClickListener {
클릭 리스너는 bind말고 create시점에 추가하면 됩니다

2020-11-27 22:38 UTC, PeonyF commented on class15/PeonyF/AndroidArchitectureStudy/app/src/main/java/com/architecture/androidarchitecturestudy/adapter/DataBindingAdapter.kt
> +@BindingAdapter("setImage")
setImage를 ImgaeUrl로, setRatingStar를 bindRatingStar로 변경하였습니다.  (57296c1)
다만, 말씀하신 view의 attr관점이 잘 이해가 가지 않아 수업시간에 해당부분 질문드리겠습니다. 🤔🤔

2020-11-27 22:39 UTC, PeonyF commented on class15/PeonyF/AndroidArchitectureStudy/app/src/main/java/com/architecture/androidarchitecturestudy/adapter/MovieAdapter.kt
> +    private lateinit var binding: MovieItemBinding
말씀하신 binding 객체선언 위치를 onCreateViewHolder() 안으로 이동하였습니다. (4e541e9)

2020-11-27 22:39 UTC, PeonyF commented on class15/PeonyF/AndroidArchitectureStudy/app/src/main/java/com/architecture/androidarchitecturestudy/ui/searchhistory/SearchHistoryAdapter.kt
> +        holder.itemView.setOnClickListener {
click listener 위치를 onCreateViewHolder()로 이동하였습니다. (44eae5a)

2020-11-27 22:41 UTC, PeonyF commented on class15/PeonyF/AndroidArchitectureStudy/app/src/main/java/com/architecture/androidarchitecturestudy/data/repository/MovieRepositoryImpl.kt
> +    }
말씀하신 saveSearchHistory() 메소드를 MovieRepositoryImpl.kt의 getMovieData() 안으로 이동하였습니다.
이에 따라 MainActivity,MainContract.kt,MainPresenter.kt 에 위치한 관련 메소드를 삭제하였습니다. (849cb9f)

2020-11-28 01:47 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-11-28 13:10 UTC, merged