HW-4 : Data Binding, 최근 검색 목록 추가
sjjeong/GoogryAndroidArchitecutreStudy pull request #917
Opened 2020-11-26 15:28 UTC by hunihun

늦어서 죄송합니다....

2020-11-27 08:02 UTC, juan-rybczinski approved these changes

2020-11-27 08:02 UTC, juan-rybczinski commented on class14/hunihun/app/src/main/java/com/wybh/androidarchitecturestudy/extension/CinemaExtension.kt
> +fun bindImage(view: ImageView, url: String) {
BindingAdapter 정의하실 때 대상 View의 Extension Function으로 정의하셔도 좋을 것 같네요. 취향 차이인 것 같으니 굳이 바꾸시지는 않아도 될 것 같습니다!

2020-11-27 08:02 UTC, juan-rybczinski commented on class14/hunihun/app/src/main/java/com/wybh/androidarchitecturestudy/main/MainActivity.kt
> +        startActivityForResult(
요즘은 startActivityForResult 대신 아래 링크처럼 처리하는 것도 같으니 다음번에 참고해보시면 좋을 것 같습니다!
https://medium.com/droid-log/androidx-activity-result-apis-the-new-way-7cfc949a803c

2020-11-27 08:02 UTC, juan-rybczinski commented
고생 많으셨습니다!

2020-11-27 08:12 UTC, hunihun commented on class14/hunihun/app/src/main/java/com/wybh/androidarchitecturestudy/main/MainActivity.kt
> +        startActivityForResult(
요거는 안쓰는 코드인데 지우는걸 깜빡했네요... ㅎㅎ
다음에 사용할때 한번 적용해보도록 하겠습니다!

2020-11-27 08:14 UTC, hunihun commented on class14/hunihun/app/src/main/java/com/wybh/androidarchitecturestudy/extension/CinemaExtension.kt
> +fun bindImage(view: ImageView, url: String) {
저번주 멘토님도 대상 view로 정의하던데... 흠... 물어봐야겠네용

2020-11-27 09:36 UTC, juan-rybczinski commented on class14/hunihun/app/src/main/java/com/wybh/androidarchitecturestudy/CinemaAdapter.kt
> +            binding.item = item
급한 마음에 Approve 눌러버렸지만 ㅋㅋㅋ
상훈님도 여기에 `binding.executePendingBindings()` 적용해 주시면 좋을 것 같아요.

2020-11-27 15:40 UTC, sjjeong requested changes

2020-11-27 15:40 UTC, sjjeong commented on class14/hunihun/app/src/main/java/com/wybh/androidarchitecturestudy/CinemaAdapter.kt
> +            binding.item = item
이거도 작업해주세요

2020-11-27 15:40 UTC, sjjeong commented on class14/hunihun/app/src/main/java/com/wybh/androidarchitecturestudy/HistoryAdapter.kt
> +    private lateinit var binding: HistoryItemBinding
이 Binding은 ViewHolder에 있어야합니다 제거해주세요

2020-11-27 15:40 UTC, sjjeong commented on class14/hunihun/app/src/main/java/com/wybh/androidarchitecturestudy/HistoryAdapter.kt
> +    inner class HistoryViewHolder(private val binding: HistoryItemBinding) :
inner 키워드 제거 해주세요

2020-11-27 15:40 UTC, sjjeong commented on class14/hunihun/app/src/main/java/com/wybh/androidarchitecturestudy/HistoryAdapter.kt
> +            binding.data = word
여기도 executePendingBindings()추가해주세요

2020-11-27 15:40 UTC, sjjeong commented on class14/hunihun/app/src/main/java/com/wybh/androidarchitecturestudy/SharedPref.kt
> +class SharedPref {
인스턴스를 만들지 않는다면 object로 만들어주세요

2020-11-27 15:40 UTC, sjjeong commented on class14/hunihun/app/src/main/java/com/wybh/androidarchitecturestudy/VerticalSpaceItemDecoration.kt
> +class VerticalSpaceItemDecoration(private val verticalSpaceWidth: Int) :
left right에 space를 주는거라면 vertical이 아니라 horizontal입니다

2020-11-27 15:40 UTC, sjjeong commented on class14/hunihun/app/src/main/java/com/wybh/androidarchitecturestudy/history/RecentSearchWord.kt
> +class RecentSearchWord : AppCompatActivity(), RecentSearchWordContract.View {
클래스 이름에 Activity추가해주세요

2020-11-27 15:40 UTC, sjjeong commented on class14/hunihun/app/src/main/java/com/wybh/androidarchitecturestudy/history/RecentSearchWord.kt
> +        cinemaAdapter.notifyDataSetChanged()
이 코드를 수행하는 작업을 cinemaAdapter클래스 내에 함수로 구현하고 그 함수를 호출하도록 해주세요

2020-11-27 15:40 UTC, sjjeong commented on class14/hunihun/app/src/main/java/com/wybh/androidarchitecturestudy/history/RecentSearchWordPresenter.kt
> +                    }
이 작업은 rx의 map함수에서 해주세요

2020-11-27 15:40 UTC, sjjeong commented on class14/hunihun/app/src/main/java/com/wybh/androidarchitecturestudy/main/MainPresenter.kt
> +        repository.saveSearchWord(word)
별도로 save를 하는게 아니라 영화검색을 할 때 저장하도록 해주세요

2020-11-30 16:56 UTC, hunihun commented on class14/hunihun/app/src/main/java/com/wybh/androidarchitecturestudy/CinemaAdapter.kt
> +            binding.item = item
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/917/commits/b2b877a6a6436af91e5b18caa1737bbb7c1f5218

수정했습니다!

2020-11-30 16:56 UTC, hunihun commented on class14/hunihun/app/src/main/java/com/wybh/androidarchitecturestudy/SharedPref.kt
> +class SharedPref {
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/917/commits/5e15bedd6607d0a537083ada90c9df467aec10a1

수정했습니다!

2020-11-30 16:57 UTC, hunihun commented on class14/hunihun/app/src/main/java/com/wybh/androidarchitecturestudy/VerticalSpaceItemDecoration.kt
> +class VerticalSpaceItemDecoration(private val verticalSpaceWidth: Int) :
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/917/commits/15f4e1050da2c89cc417168fe8d92cda8c65cc30

수정했습니다!

2020-11-30 16:57 UTC, hunihun commented on class14/hunihun/app/src/main/java/com/wybh/androidarchitecturestudy/history/RecentSearchWord.kt
> +class RecentSearchWord : AppCompatActivity(), RecentSearchWordContract.View {
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/917/commits/3063aaf249b7a8e35521a57292cdac3f56b14921

수정했습니다!

2020-11-30 16:58 UTC, hunihun commented on class14/hunihun/app/src/main/java/com/wybh/androidarchitecturestudy/history/RecentSearchWord.kt
> +        cinemaAdapter.notifyDataSetChanged()
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/917/commits/57cf9c9206b0baa668e7328ecb1326786450006a

수정했습니다!

2020-11-30 16:59 UTC, hunihun commented on class14/hunihun/app/src/main/java/com/wybh/androidarchitecturestudy/history/RecentSearchWordPresenter.kt
> +                    }
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/917/commits/baa112b2e20caf3ca191eae120a8f5563796ba79

rx의 map 에서 가공한 데이터를 succese 에 넣기위해서 ArrayList<CinemaItem> 객체를 클래스에다가 선언했는데 상관없을까요 ?

2020-11-30 16:59 UTC, hunihun commented on class14/hunihun/app/src/main/java/com/wybh/androidarchitecturestudy/main/MainPresenter.kt
> +        repository.saveSearchWord(word)
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/917/commits/8c8cac0568cb97143ff498e708a4e73dbe57c370

수정했습니다!

2020-11-30 17:00 UTC, hunihun commented on class14/hunihun/app/src/main/java/com/wybh/androidarchitecturestudy/HistoryAdapter.kt
> +    private lateinit var binding: HistoryItemBinding
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/917/commits/6a4616f6d5e6f138531920500f184d90a6161ecb

수정했습니다!

2020-11-30 17:01 UTC, hunihun commented on class14/hunihun/app/src/main/java/com/wybh/androidarchitecturestudy/HistoryAdapter.kt
> +    inner class HistoryViewHolder(private val binding: HistoryItemBinding) :
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/917/commits/6a4616f6d5e6f138531920500f184d90a6161ecb

inner 를 제거하면서 ClickListener 에 필요한 data를 bind() 함수에서 가져오는데 괜찮은건가요 ??

2020-11-30 17:02 UTC, hunihun commented on class14/hunihun/app/src/main/java/com/wybh/androidarchitecturestudy/HistoryAdapter.kt
> +            binding.data = word
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/917/commits/b2b877a6a6436af91e5b18caa1737bbb7c1f5218

수정했습니다!

2020-12-01 14:09 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-12-01 14:13 UTC, merged