HW4:DataBinding, RecentSearchList
sjjeong/GoogryAndroidArchitecutreStudy pull request #918
Opened 2020-11-27 09:31 UTC by dev-donghwan

회사일이 겹쳐서 늦게 작성하게 됐네요ㅠㅠ
깜박하고 commit에 hw 못단거같아요...

2020-11-27 13:22 UTC, onxmoreplz commented on class14/dev-donghwan/studyfork/app/src/main/java/com/example/studyfork/data/local/LocalDataSourceImpl.kt
> +    private val pref = context.getSharedPreferences("local", MODE_PRIVATE)
Context를 넘기는 것보다 context를 사용해서 만든 SharedPreference 클래스를 넘기도록 하는게 좋다고 합니다.

2020-11-27 13:22 UTC, onxmoreplz commented
고생하셨습니다!

2020-11-28 12:35 UTC, sjjeong requested changes

2020-11-28 12:35 UTC, sjjeong commented on class14/dev-donghwan/studyfork/app/src/main/AndroidManifest.xml
> +        <activity android:name=".recent.RecentSearchListActivity"></activity>
여기는 /> 로 마무리 해주세요

2020-11-28 12:35 UTC, sjjeong commented on class14/dev-donghwan/studyfork/app/src/main/java/com/example/studyfork/RecentSearchAdapter.kt
> +            binding.root.setOnClickListener{
리스너는 create시점에 추가해주세요

2020-11-28 12:35 UTC, sjjeong commented on class14/dev-donghwan/studyfork/app/src/main/java/com/example/studyfork/RecentSearchAdapter.kt
> +            binding.tvTitle.text = item
item을 set하고 executePendingBinding을 호출해주세요

2020-11-29 12:17 UTC, sjjeong approved these changes
앞으로 리뷰 코멘트에 커밋 아이디 남기도록 해주세요

2020-11-29 12:18 UTC, dev-donghwan commented
> 앞으로 리뷰 코멘트에 커밋 아이디 남기도록 해주세요

넵 죄송합니다 매번 까먹네요..ㅠ

2020-11-29 12:18 UTC, dev-donghwan commented on class14/dev-donghwan/studyfork/app/src/main/java/com/example/studyfork/data/local/LocalDataSourceImpl.kt
> +    private val pref = context.getSharedPreferences("local", MODE_PRIVATE)
4f7cb6a

2020-11-29 12:19 UTC, dev-donghwan commented on class14/dev-donghwan/studyfork/app/src/main/java/com/example/studyfork/RecentSearchAdapter.kt
> +            binding.tvTitle.text = item
43b673f

2020-11-29 12:19 UTC, dev-donghwan commented on class14/dev-donghwan/studyfork/app/src/main/java/com/example/studyfork/RecentSearchAdapter.kt
> +            binding.root.setOnClickListener{
d1ad470

2020-11-29 12:19 UTC, dev-donghwan commented on class14/dev-donghwan/studyfork/app/src/main/AndroidManifest.xml
> +        <activity android:name=".recent.RecentSearchListActivity"></activity>
774708a

2020-11-29 13:39 UTC, onxmoreplz approved these changes

2020-11-29 14:07 UTC, merged