HW-4 MVVM 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #92
Opened 2019-07-03 12:21 UTC by BeokBeok

MVVM 적용 하였습니다.

2019-07-04 01:54 UTC, NackUn requested changes

2019-07-04 01:54 UTC, NackUn commented on BeokBeok/app/src/main/java/com/architecturestudy/upbitmarket/UpbitFragment.kt
> +        binding.vm = vm
binding.vm = vm 의 역할이 binding.setVariable(BR.vm, vm) 이거랑 같은 건가요?

2019-07-04 01:54 UTC, NackUn commented on BeokBeok/app/src/main/java/com/architecturestudy/upbitmarket/UpbitFragment.kt
>              view.setTextColor(Color.BLUE)
이곳에서 한 번에 컬러와 리스트를 처리 안 하신 것은 분리하기 위해서인가요?

2019-07-04 02:09 UTC, BeokBeok commented on BeokBeok/app/src/main/java/com/architecturestudy/upbitmarket/UpbitFragment.kt
> +        binding.vm = vm
네, 맞습니다.

2019-07-04 02:12 UTC, BeokBeok commented on BeokBeok/app/src/main/java/com/architecturestudy/upbitmarket/UpbitFragment.kt
>              view.setTextColor(Color.BLUE)
filter와 map을 사용하여 선택된 뷰가 아닌 것들에 대하여 gray 처리 후, 선택된 뷰만 blue 처리하도록 하였습니다.

2019-07-04 15:06 UTC, NackUn submitted a review, later dismissed
고생하셨습니다!

2019-07-04 15:06 UTC, NackUn reviewed
제가 Approve해도 되나요?

2019-07-04 15:28 UTC, BeokBeok commented
@NackUn 
석준님이 approve 하는 것으로 변경되었습니다.

2019-07-06 02:13 UTC, NackUn commented on BeokBeok/app/src/main/java/com/architecturestudy/upbitmarket/UpbitFragment.kt
> +                        setViewColor((sender.get() as TextView))
요기 구분하고자 가로 2개 하신건가요??

2019-07-06 03:33 UTC, sjjeong requested changes

2019-07-06 03:33 UTC, sjjeong commented on BeokBeok/app/src/main/java/com/architecturestudy/upbitmarket/UpbitViewModel.kt
> +    var selectedTextView = ObservableField<TextView>()
나중에 테스트나 이런것 때문에 ViewModel쪽에는 DataBinding을 위한 것을 외에는 TextView나 View와 같은 android 관련 패키지 내용이 들어오게 되면 안됩니다.

2019-07-07 03:20 UTC, BeokBeok commented on BeokBeok/app/src/main/java/com/architecturestudy/upbitmarket/UpbitViewModel.kt
> +    var selectedTextView = ObservableField<TextView>()
수정 하였습니다.
30abda1

해당 수정사항이 석준님이 의도한 수정사항인지는 잘 모르겠습니다.
만약, 의도하신 것이 아니라면 방향성만 제시 부탁 드립니다.

2019-07-07 03:21 UTC, BeokBeok commented on BeokBeok/app/src/main/java/com/architecturestudy/upbitmarket/UpbitFragment.kt
> +                        setViewColor((sender.get() as TextView))
텍스트뷰를 받지 않는 것으로 변경하면서 수정되었습니다.
30abda1

2019-07-09 15:58 UTC, NackUn reviewed
callback 제거를 higher order function 이 아닌 observe를 이용해서 하셨군요

2019-07-10 16:46 UTC, sjjeong requested changes

2019-07-10 16:46 UTC, sjjeong commented on BeokBeok/app/src/main/java/com/architecturestudy/data/upbit/UpbitRepository.kt
> +    val throwable = ObservableField<Throwable>()
repository에 OservableField가 있으면 안됩니다.
저번에 말했던것처럼 higher-order function으로 데이터 전달하게 해주세요

2019-07-10 16:46 UTC, sjjeong commented on BeokBeok/app/src/main/java/com/architecturestudy/data/upbit/source/UpbitRetrofitDataSource.kt
> +    private val retrofit = UpbitRetrofit.retrofit
retrofit을 생성자쪽에서 받게 해주세요

2019-07-10 16:46 UTC, sjjeong commented on BeokBeok/app/src/main/java/com/architecturestudy/data/upbit/source/UpbitRetrofitDataSource.kt
> +    private val upbitRepository = UpbitRepository(this)
DataSource는 Repository를 알면 안됩니다.
이 코드는 제거해주세요.

2019-07-10 16:46 UTC, sjjeong commented on BeokBeok/app/src/main/java/com/architecturestudy/upbitmarket/UpbitFragment.kt
> +                        binding.tvMarketKrw.setTextColor(Color.GRAY)
color을 set해주는 부분은 xml에서 처리해주세요

2019-07-10 16:46 UTC, sjjeong commented on BeokBeok/app/src/main/java/com/architecturestudy/upbitmarket/UpbitViewModel.kt
> +            v.setTextColor(Color.BLUE)
View나 TextView가 ViewModel에 있으면 안됩니다.
해당부분은 xml에서 처리해주세요

2019-07-10 16:46 UTC, sjjeong commented on BeokBeok/app/src/main/java/com/architecturestudy/upbitmarket/adapter/UpbitAdapter.kt
> +            binding.tvCoinName.text = marketPrice["coinName"]
text을 set해주는 부분은 xml에 있으면 됩니다.

2019-07-11 06:28 UTC, BeokBeok commented on BeokBeok/app/src/main/java/com/architecturestudy/data/upbit/UpbitRepository.kt
> +    val throwable = ObservableField<Throwable>()
c72640b 
적용 하였습니다.

2019-07-11 06:28 UTC, BeokBeok commented on BeokBeok/app/src/main/java/com/architecturestudy/data/upbit/source/UpbitRetrofitDataSource.kt
> +    private val upbitRepository = UpbitRepository(this)
c72640b 
적용 하였습니다.

2019-07-11 06:28 UTC, BeokBeok commented on BeokBeok/app/src/main/java/com/architecturestudy/data/upbit/source/UpbitRetrofitDataSource.kt
> +    private val retrofit = UpbitRetrofit.retrofit
773eb43 
적용 하였습니다.

2019-07-11 06:28 UTC, BeokBeok commented on BeokBeok/app/src/main/java/com/architecturestudy/upbitmarket/UpbitFragment.kt
> +                        binding.tvMarketKrw.setTextColor(Color.GRAY)
ae840a6 
적용 하였습니다.

2019-07-11 06:28 UTC, BeokBeok commented on BeokBeok/app/src/main/java/com/architecturestudy/upbitmarket/UpbitViewModel.kt
> +            v.setTextColor(Color.BLUE)
ae840a6 
적용 하였습니다.

2019-07-11 06:28 UTC, BeokBeok commented on BeokBeok/app/src/main/java/com/architecturestudy/upbitmarket/adapter/UpbitAdapter.kt
> +            binding.tvCoinName.text = marketPrice["coinName"]
df63aa6
적용 하였습니다.

2019-07-11 15:27 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-07-11 23:10 UTC, merged