HW-4  데이터 바인딩 과제
sjjeong/GoogryAndroidArchitecutreStudy pull request #920
Opened 2020-11-28 06:05 UTC by realizer12

로컬  데이터 소스 연결은 일욜까지 할께요 ㅠ

2020-11-28 12:01 UTC, sjjeong requested changes

2020-11-28 12:01 UTC, sjjeong commented on class15/realizer12/AndroidArchitectureStudy/app/src/main/java/com/example/androidarchitecturestudy/MainActivity.kt
> +        dataBindingSet()
이름은 setupDataBinding으로 해주세요

2020-11-28 12:01 UTC, sjjeong commented on class15/realizer12/AndroidArchitectureStudy/app/src/main/java/com/example/androidarchitecturestudy/adapter/MovieListRecyclerViewAdapter.kt
> +            binding.movieData = movieData
executePendingBindings도 호출해주세요

2020-11-28 12:01 UTC, sjjeong commented on class15/realizer12/AndroidArchitectureStudy/app/src/main/java/com/example/androidarchitecturestudy/util/EditSearchActionExt.kt
> +             (activity as MainActivity).searchMovie(this)
activity를 넘기지 말고 고차함수를 받아서 이 부분에서 invoke해주도록 해주세요

2020-12-01 04:30 UTC, showmiso reviewed
전체 프로젝트 코드정렬 필요해보입니다.

2020-12-01 15:22 UTC, realizer12 commented on class15/realizer12/AndroidArchitectureStudy/app/src/main/java/com/example/androidarchitecturestudy/MainActivity.kt
> +        dataBindingSet()
40313fc. 해당 내용 반영했습니다!

2020-12-01 15:22 UTC, realizer12 commented on class15/realizer12/AndroidArchitectureStudy/app/src/main/java/com/example/androidarchitecturestudy/adapter/MovieListRecyclerViewAdapter.kt
> +            binding.movieData = movieData
2f4cb81  해당 사항 반영했습니다!

2020-12-01 15:22 UTC, realizer12 commented on class15/realizer12/AndroidArchitectureStudy/app/src/main/java/com/example/androidarchitecturestudy/util/EditSearchActionExt.kt
> +             (activity as MainActivity).searchMovie(this)
aa6ef45  고차함수 넘기는걸로  수정하였습니다!

2020-12-01 15:23 UTC, realizer12 commented
저번주에 못했던  room을 이용한  최근 검색어  저장   완료 하였습니다.
자꾸 늦어져서 죄송합니다 ㅠ  
이번주 과제는 이번주안에 꼭 하도록 하겠습니다!

2020-12-02 11:53 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-12-02 12:44 UTC, showmiso approved these changes

2020-12-02 12:47 UTC, realizer12 commented
> 전체 프로젝트 코드정렬 필요해보입니다.

6637120

2020-12-02 12:48 UTC, merged