HW-5 : Change to MVVM
sjjeong/GoogryAndroidArchitecutreStudy pull request #921
Opened 2020-11-30 07:30 UTC by showmiso

제대로 했는지 모르겠네요 ...

2020-12-02 12:34 UTC, realizer12 reviewed
이상입니다!  수고 하셨습니다!!

2020-12-02 12:34 UTC, realizer12 commented on class15/showmiso/ArchitectureStudy/app/src/main/java/com/showmiso/architecturestudy/extensions/ViewExtension.kt
> +fun EditText.onEditorEnter(callback: () -> Unit) {
미소님 혹시 이렇게 안되나요??
돌려서 확인해보고 싶은데,  빌드에러나서  못돌려봤어요 ㅠ

@BindingAdapter("onEditorEnter")
fun EditText.onEditorEnter(callback: (query:String) -> Unit) {
    setOnEditorActionListener { textView, actionId, _ ->
        if (actionId == EditorInfo.IME_ACTION_SEARCH) {
            // TODO: 여기서 textView.toString() 을 callback 에 넘기려면 어떻게 해야하나요?
            // xml 에서 자꾸 오류가 나서요 ㅠ
            callback.invoke(textView.toString())
            return@setOnEditorActionListener true
        }
        return@setOnEditorActionListener false
    }
}

2020-12-03 11:36 UTC, sjjeong requested changes

2020-12-03 11:36 UTC, sjjeong commented on class15/showmiso/ArchitectureStudy/app/src/main/res/layout/activity_main.xml
> +                bind:onEditorEnter="@{() -> vm.searchMovie(etSearch.getText().toString())}"
ViewModel에 query 관련 ObservableField를 만드시고 EditText에 two-way로 묶어주신 다음에 searchMovie로 String을 넘기는 것을 제거해주세요

2020-12-03 11:36 UTC, sjjeong commented on class15/showmiso/ArchitectureStudy/app/src/main/res/layout/activity_history.xml
> +            type="com.showmiso.architecturestudy.ui.HistoryActivity" />
Activity 받는거는 제거 해주시고 vm을 통해서 이벤트 전달하도록 해주세요

2020-12-03 11:36 UTC, sjjeong commented on class15/showmiso/ArchitectureStudy/app/src/main/java/com/showmiso/architecturestudy/ui/MovieViewModel.kt
> +        naverRepository.addHistory(query)
history 추가하는거는 여기서 하지 마시고 getMoviesList에서 요청에 성공했을 때 처리하도록 getMoviesList함수 내부로 옮겨주세요

2020-12-03 11:36 UTC, sjjeong commented on class15/showmiso/ArchitectureStudy/app/src/main/java/com/showmiso/architecturestudy/ui/HistoryAdapter.kt
> +            }
click listener 추가하는거는 bind말고 create 시점에서 하도록 해주세요

2020-12-09 10:54 UTC, showmiso commented on class15/showmiso/ArchitectureStudy/app/src/main/res/layout/activity_main.xml
> +                bind:onEditorEnter="@{() -> vm.searchMovie(etSearch.getText().toString())}"
14d8399e5934938b1f75af8be4ab03c943f8a30b
수정했습니다.

2020-12-09 10:56 UTC, showmiso commented on class15/showmiso/ArchitectureStudy/app/src/main/java/com/showmiso/architecturestudy/extensions/ViewExtension.kt
> +fun EditText.onEditorEnter(callback: () -> Unit) {
왜때문인지 모르겠는데 String 을 넘기니까 자꾸 바인딩에러가 나서 테스트해보지 못했습니다.ㅠㅠ

2020-12-09 11:11 UTC, showmiso commented on class15/showmiso/ArchitectureStudy/app/src/main/java/com/showmiso/architecturestudy/ui/MovieViewModel.kt
> +        naverRepository.addHistory(query)
f163e3afedf66830c6d8f4d0150e94808fb5edb0
수정했습니다.

2020-12-09 11:15 UTC, showmiso commented on class15/showmiso/ArchitectureStudy/app/src/main/java/com/showmiso/architecturestudy/ui/HistoryAdapter.kt
> +            }
295475c1fecd47abdc64ba3441b5fad29ea67fea
수정했습니다.

2020-12-09 11:23 UTC, showmiso commented on class15/showmiso/ArchitectureStudy/app/src/main/res/layout/activity_history.xml
> +            type="com.showmiso.architecturestudy.ui.HistoryActivity" />
e823392e093419dac9c854a410411581ca70fad2
이렇게 해야하는군용... 수정했습니다 !

2020-12-09 11:24 UTC, showmiso commented on class15/showmiso/ArchitectureStudy/app/src/main/java/com/showmiso/architecturestudy/ui/HistoryAdapter.kt
> +            }
오래걸려서 죄송합니다.
막상 시간내서 하니까 금방하는데 너무 막막하다고 생각했던것 같아요 ㅠㅠ
감사합니다 !

2020-12-09 11:25 UTC, showmiso commented
오래 걸려서 죄송합니다 ㅠㅠ
막상 하면 그리 오래 안걸리는데, 
다 모르는거라고 생각하니까 너무 막막하다고 생각했던 것 같아요.
리뷰 감사합니다 :)

2020-12-09 15:15 UTC, realizer12 approved these changes

2020-12-10 05:08 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-12-10 05:46 UTC, merged