HW-5 MVVM
sjjeong/GoogryAndroidArchitecutreStudy pull request #923
Opened 2020-11-30 15:07 UTC by juan-rybczinski

끼워 맞추기 식으로 아키텍쳐를 고치다 보니 커밋 단위가 엉망이네요 😂

2020-12-01 16:42 UTC, hunihun reviewed
회사 일이 많아서 요즘 항상 늦게 리뷰해드리네용... 죄송합니다 ㅠㅠㅠㅠㅠㅠㅠㅠ

2020-12-01 16:42 UTC, hunihun commented on class14/juan-rybczinski/GoogryAndroidArchitectureStudy/app/src/main/java/com/example/googryandroidarchitecturestudy/ui/fragment/MovieSearchFragment.kt
> +        binding.v = this
apply블럭을 사용해도 될것같습니다!

2020-12-02 01:58 UTC, juan-rybczinski commented on class14/juan-rybczinski/GoogryAndroidArchitectureStudy/app/src/main/java/com/example/googryandroidarchitecturestudy/ui/fragment/MovieSearchFragment.kt
> +        binding.v = this
아니에요, 괜찮습니다!
apply 구문 추가로 적용했습니다.

9d9666ad9

2020-12-02 10:12 UTC, hunihun approved these changes

2020-12-02 13:12 UTC, sjjeong requested changes

2020-12-02 13:12 UTC, sjjeong commented on class14/juan-rybczinski/GoogryAndroidArchitectureStudy/app/src/main/java/com/example/googryandroidarchitecturestudy/ui/extension/ChipGroupExtensions.kt
> +                MovieRecentViewModel.showMovieSearchEvent.set(text.toString())
리스너 안에서 이렇게 하지마시고 파라미터로 데이터를 넘겨주도록 해주세요
2번째 파라미터에 `action: (String) -> Unit` 이렇게 하시면 될겁니다

2020-12-02 13:12 UTC, sjjeong commented on class14/juan-rybczinski/GoogryAndroidArchitectureStudy/app/src/main/res/layout/fragment_movie_search.xml
> +            android:onClick="@{() -> v.queryMovieList(searchText.getText().toString())}"
1. v가 아니라 vm의 함수를 호출하도록 해주세요 
2. v는 제거해주세요 
3. searchText는 two-way binding 해주세요

2020-12-02 13:12 UTC, sjjeong commented on class14/juan-rybczinski/GoogryAndroidArchitectureStudy/app/src/main/res/layout/fragment_movie_recent.xml
> +            name="v"
여기도 v는 제거해주세요

2020-12-02 13:12 UTC, sjjeong commented on class14/juan-rybczinski/GoogryAndroidArchitectureStudy/app/src/main/java/com/example/googryandroidarchitecturestudy/ui/viewmodel/MovieViewModel.kt
> +    private val context: Context
ViewModel이 context를 가지지 않도록 해주세요

2020-12-02 13:12 UTC, sjjeong commented on class14/juan-rybczinski/GoogryAndroidArchitectureStudy/app/src/main/java/com/example/googryandroidarchitecturestudy/ui/fragment/MovieSearchFragment.kt
> +        viewModel.clickRecentButtonCompleted()
이걸 만들 필요가 없을 것 같습니다.
true, false로 변경하지마시고 notifyChange()를 호출해주시면 됩니다

2020-12-02 13:12 UTC, sjjeong commented on class14/juan-rybczinski/GoogryAndroidArchitectureStudy/app/src/main/java/com/example/googryandroidarchitecturestudy/ui/fragment/MovieRecentFragment.kt
> +        }
viewmodel이 lazy로 생성되니까 이 부분은 viewmodel이 init 될때 호출해주도록 해주시면 됩니다

2020-12-02 13:12 UTC, sjjeong commented on class14/juan-rybczinski/GoogryAndroidArchitectureStudy/app/src/main/java/com/example/googryandroidarchitecturestudy/ui/fragment/MovieSearchFragment.kt
> +        binding.apply {
apply는 초기화와 동시에 객체 자신을 리턴해야할때 사용합니다
with나 run으로 사용하시는게 좋습니다

2020-12-02 13:12 UTC, sjjeong commented on class14/juan-rybczinski/GoogryAndroidArchitectureStudy/app/src/main/java/com/example/googryandroidarchitecturestudy/ui/viewmodel/BaseViewModel.kt
> +        }
selectedUrl에 INVALID_URL를 넣어서 유효하지 않는 URL을 전달하지 마시고
새로운 ObservableField를 사용하도록 해주세요

2020-12-03 03:08 UTC, juan-rybczinski commented on class14/juan-rybczinski/GoogryAndroidArchitectureStudy/app/src/main/java/com/example/googryandroidarchitecturestudy/ui/fragment/MovieSearchFragment.kt
> +        viewModel.clickRecentButtonCompleted()
처음에 말씀하신대로 구현 했었는데 테스트 하다보니,
첫번째 화면 이동 시에는 잘 동작하다가 검색 화면으로 돌아와서 다시 한번 화면 이동을 시도하면
`onPropertyChanged`가 2번 호출되면서 
`Navigation action/destination cannot be found from the current destination Destination`
에러가 발생하더라구요.

원인을 찾지 못하다가 정확하게 동일한 케이스는 아니지만 아래 codelab의 Step2를 참고한 로직이었는데
다른 해결 방법이 있을까요?
https://developer.android.com/codelabs/kotlin-android-training-live-data?index=..%2F..android-kotlin-fundamentals#6

2020-12-03 03:09 UTC, juan-rybczinski commented on class14/juan-rybczinski/GoogryAndroidArchitectureStudy/app/src/main/java/com/example/googryandroidarchitecturestudy/ui/viewmodel/MovieViewModel.kt
> +    private val context: Context
대신 repository는 전달해도 될까요?

2020-12-04 07:00 UTC, juan-rybczinski commented on class14/juan-rybczinski/GoogryAndroidArchitectureStudy/app/src/main/java/com/example/googryandroidarchitecturestudy/ui/extension/ChipGroupExtensions.kt
> +                MovieRecentViewModel.showMovieSearchEvent.set(text.toString())
반영했습니다. 말씀하신대로 하니까 잘 되네요!
ad0f55c7b

2020-12-04 07:05 UTC, juan-rybczinski commented on class14/juan-rybczinski/GoogryAndroidArchitectureStudy/app/src/main/res/layout/fragment_movie_search.xml
> +            android:onClick="@{() -> v.queryMovieList(searchText.getText().toString())}"
Two-way Binding 적용해서 동작은 하는데 제대로 한건 지 잘 모르겠네요 ;
1, 2번은 말씀주신대로 다음주 과제 때 적용하도록 하겠습니다.
f9105bed7

2020-12-04 07:05 UTC, juan-rybczinski commented on class14/juan-rybczinski/GoogryAndroidArchitectureStudy/app/src/main/res/layout/fragment_movie_recent.xml
> +            name="v"
반영했습니다!
08f24e1f8

2020-12-04 07:07 UTC, juan-rybczinski commented on class14/juan-rybczinski/GoogryAndroidArchitectureStudy/app/src/main/java/com/example/googryandroidarchitecturestudy/ui/fragment/MovieRecentFragment.kt
> +        }
마찬가지로 다음주 과제 때 적용하도록 하겠습니다!

2020-12-04 07:10 UTC, juan-rybczinski commented on class14/juan-rybczinski/GoogryAndroidArchitectureStudy/app/src/main/java/com/example/googryandroidarchitecturestudy/ui/fragment/MovieSearchFragment.kt
> +        binding.apply {
apply의 용법을 확실하게 알아갑니당
2e1fb6809

2020-12-04 07:10 UTC, juan-rybczinski commented on class14/juan-rybczinski/GoogryAndroidArchitectureStudy/app/src/main/java/com/example/googryandroidarchitecturestudy/ui/viewmodel/BaseViewModel.kt
> +        }
반영했습니다!
f16b652f4

2020-12-04 15:02 UTC, sjjeong commented on class14/juan-rybczinski/GoogryAndroidArchitectureStudy/app/src/main/java/com/example/googryandroidarchitecturestudy/ui/viewmodel/MovieSearchViewModel.kt
> +    }
이거를 ObservableField로 선언하면 됩니다

2020-12-04 15:02 UTC, sjjeong commented on class14/juan-rybczinski/GoogryAndroidArchitectureStudy/app/src/main/res/layout/fragment_movie_search.xml
> +            name="query"
이거는 필요 없습니다

2020-12-04 15:02 UTC, sjjeong commented on class14/juan-rybczinski/GoogryAndroidArchitectureStudy/app/src/main/java/com/example/googryandroidarchitecturestudy/ui/fragment/MovieSearchFragment.kt
> +        viewModel.clickRecentButtonCompleted()
SingleLiveData 라는것을 찾아보세요

2020-12-07 11:13 UTC, juan-rybczinski commented on class14/juan-rybczinski/GoogryAndroidArchitectureStudy/app/src/main/java/com/example/googryandroidarchitecturestudy/ui/viewmodel/MovieSearchViewModel.kt
> +    }
반영했습니다! 제가 문서를 잘못 읽었었네요 ;
3eea51926

2020-12-07 11:13 UTC, juan-rybczinski commented on class14/juan-rybczinski/GoogryAndroidArchitectureStudy/app/src/main/res/layout/fragment_movie_search.xml
> +            name="query"
반영했습니다!
928fa4727

2020-12-07 11:14 UTC, juan-rybczinski commented on class14/juan-rybczinski/GoogryAndroidArchitectureStudy/app/src/main/java/com/example/googryandroidarchitecturestudy/ui/fragment/MovieSearchFragment.kt
> +        viewModel.clickRecentButtonCompleted()
훨씬 깔끔하네요! 키워드만 정확히 알려주셔서 감사합니다 😆
f1840c075

2020-12-07 12:03 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-12-07 14:47 UTC, merged