HW-5 MVVM 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #924
Opened 2020-11-30 17:40 UTC by Myung777

mainActivity 에서 recyclerView 를 @BindingAdapter 이용해서 만들었는데 RecentSearchActivity 에서 Item onClick 부분 때문에 어떻게  @BindingAdapter 이용해서 구현을 해야 될지 모르겠네요

2020-12-02 09:28 UTC, simuelunbo reviewed
이번주에도 리뷰 늦어서 죄송합니다 ㅠㅠ

2020-12-02 09:28 UTC, simuelunbo commented on class14/myung777/StudyFork/app/src/main/java/com/deepco/studyfork/BaceActivity.kt
> +abstract class BaseActivity<B : ViewDataBinding>(@LayoutRes val layoutResId: Int) :
파일명 오타 난거 같은데요 BaceActivity라고 되어있네요

2020-12-02 09:28 UTC, simuelunbo commented on class14/myung777/StudyFork/app/src/main/java/com/deepco/studyfork/RecentSearchActivity.kt
>          binding.activity = this
binding.activity 쓰고 있는게 없네요 사용하시지 않으시면 지워도 될거같아요

2020-12-02 09:28 UTC, simuelunbo commented on class14/myung777/StudyFork/app/src/main/java/com/deepco/studyfork/RecentSearchActivity.kt
>          recentSearchRecyclerAdapter = RecentSearchRecyclerAdapter { query ->
Extension 에 추가 하셔서 처리 해도 될거 같아요

2020-12-03 07:32 UTC, Myung777 commented on class14/myung777/StudyFork/app/src/main/java/com/deepco/studyfork/BaceActivity.kt
> +abstract class BaseActivity<B : ViewDataBinding>(@LayoutRes val layoutResId: Int) :
8f37ba9

2020-12-03 07:32 UTC, Myung777 commented on class14/myung777/StudyFork/app/src/main/java/com/deepco/studyfork/RecentSearchActivity.kt
>          binding.activity = this
제거하였습니다! 
aa0ca53

2020-12-03 07:34 UTC, Myung777 commented on class14/myung777/StudyFork/app/src/main/java/com/deepco/studyfork/RecentSearchActivity.kt
>          recentSearchRecyclerAdapter = RecentSearchRecyclerAdapter { query ->
리스트를 넣는부분만 Extension에 추가하게 되었는데 Listener 처리도 Extension에서 하는 방법을 잘모르겠네요...
4837f65

2020-12-03 10:02 UTC, simuelunbo commented on class14/myung777/StudyFork/app/src/main/java/com/deepco/studyfork/RecentSearchActivity.kt
>          recentSearchRecyclerAdapter = RecentSearchRecyclerAdapter { query ->
item layout에 onClick 처리를 ViewModel에서 하면 되지 않나요?

2020-12-03 10:15 UTC, simuelunbo approved these changes
상명님 수정후 리뷰 재요청 하실때 Re-review Request 눌려주시면 감사하겠습니다 :)

2020-12-03 10:39 UTC, Myung777 commented on class14/myung777/StudyFork/app/src/main/java/com/deepco/studyfork/RecentSearchActivity.kt
>          recentSearchRecyclerAdapter = RecentSearchRecyclerAdapter { query ->
item Layout에서 textView 클릭햇을때 onClick 처리를 말씀하시는건가요? TextView 말고 해당 아이템 전체(아무곳이나) 클릭을 했을때 처리를 하고 싶은데 생각보다 잘안되더라고요...

2020-12-03 10:44 UTC, simuelunbo commented on class14/myung777/StudyFork/app/src/main/java/com/deepco/studyfork/RecentSearchActivity.kt
>          recentSearchRecyclerAdapter = RecentSearchRecyclerAdapter { query ->
TextView 말고 감싸고 있는 Constraint로 하시면 될거 같은데요

2020-12-03 11:29 UTC, Myung777 commented on class14/myung777/StudyFork/app/src/main/java/com/deepco/studyfork/RecentSearchActivity.kt
>          recentSearchRecyclerAdapter = RecentSearchRecyclerAdapter { query ->
이렇게 Adapter 쪽으로 recentSearchViewModel 을 넘겨줘야 작업이 가능한데 Extension 에서는 RecentSearchActivity 의 
recentSearchViewModel 을 넘겨주는게 힘들지 않나요?
dcd2153

2020-12-03 12:09 UTC, sjjeong requested changes

2020-12-03 12:09 UTC, sjjeong commented on class14/myung777/StudyFork/app/src/main/java/com/deepco/studyfork/Extension.kt
> +    }
kotlin으로 좀더 간소화 할 수 있습니다.
과제 하시는동안 해결 해보시고 안되면 수업시간에 물어보시면 알려드릴게요

2020-12-03 12:09 UTC, sjjeong commented on class14/myung777/StudyFork/app/src/main/java/com/deepco/studyfork/RecentSearchActivity.kt
> +    val recentSearchViewModel = RecentSearchViewModel()
private 추가 해주세요

2020-12-03 12:09 UTC, sjjeong commented on class14/myung777/StudyFork/app/src/main/java/com/deepco/studyfork/RecentSearchActivity.kt
> +        recentSearchViewModel.getSearchHistories()
recentSearchViewModel 생성을 lazy로 하시면 내부에서 init시점에 호출 할 수 있습니다

2020-12-03 12:09 UTC, sjjeong commented on class14/myung777/StudyFork/app/src/main/java/com/deepco/studyfork/viewmodel/MainViewModel.kt
> +            repositoryMovieDataImpl.saveQuery(query.get().toString())
query save하는 거는 getMovieList 함수 내부에서 remote요청이 성공했을때 하도록 해주세요

2020-12-03 12:09 UTC, sjjeong commented on class14/myung777/StudyFork/app/src/main/java/com/deepco/studyfork/MainActivity.kt
>          binding.activity = this
activity set하는 코드는 제거해주세요

2020-12-04 07:28 UTC, Myung777 commented on class14/myung777/StudyFork/app/src/main/java/com/deepco/studyfork/RecentSearchActivity.kt
> +    val recentSearchViewModel = RecentSearchViewModel()
afa5f01

2020-12-04 07:29 UTC, Myung777 commented on class14/myung777/StudyFork/app/src/main/java/com/deepco/studyfork/viewmodel/MainViewModel.kt
> +            repositoryMovieDataImpl.saveQuery(query.get().toString())
63365c1

2020-12-04 07:29 UTC, Myung777 commented on class14/myung777/StudyFork/app/src/main/java/com/deepco/studyfork/MainActivity.kt
>          binding.activity = this
5dce7a1

2020-12-04 07:30 UTC, Myung777 commented on class14/myung777/StudyFork/app/src/main/java/com/deepco/studyfork/RecentSearchActivity.kt
> +        recentSearchViewModel.getSearchHistories()
db2f339
init 시점에서 호출할수 있다는 말이 잘이해가 안가는데 어떤 장점이 있는건가요?

2020-12-04 07:31 UTC, Myung777 commented on class14/myung777/StudyFork/app/src/main/java/com/deepco/studyfork/Extension.kt
> +    }
130def5
간소화 작업을 진행해 보았는데 이런식으로 하는게 맞는건지 모르겠네요

2020-12-04 15:08 UTC, sjjeong commented on class14/myung777/StudyFork/app/src/main/java/com/deepco/studyfork/Extension.kt
> +    }
이렇게하면  될 것 같습니다.
```kotlin
list ?: return
val adapter = adapter ?: MovieRecyclerAdapter().apply {
    adapter = this
}
adapter.setItemsList(list)
```

2020-12-04 15:09 UTC, sjjeong commented on class14/myung777/StudyFork/app/src/main/java/com/deepco/studyfork/RecentSearchActivity.kt
> +        recentSearchViewModel.getSearchHistories()
recentSearchViewModel.getSearchHistories() 코드가 ViewModel init {} 안에 있어야합니다
실제 ViewModel이 초기화 되는 시점에 호출 할 수 있는 장점이 있습니다

2020-12-04 16:15 UTC, Myung777 commented on class14/myung777/StudyFork/app/src/main/java/com/deepco/studyfork/Extension.kt
> +    }
99af926 수정했습니다

2020-12-04 16:16 UTC, Myung777 commented on class14/myung777/StudyFork/app/src/main/java/com/deepco/studyfork/RecentSearchActivity.kt
> +        recentSearchViewModel.getSearchHistories()
넵 감사합니다! 😊 
58ef48a

2020-12-05 05:37 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-12-05 13:02 UTC, merged