HW-5 MVP -> MVVM 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #925
Opened 2020-12-02 09:51 UTC by dktsudgg

5번째 과제입니다.

2020-12-02 12:59 UTC, hhi-5258 commented on class15/dktsudgg/AndroidArchitectureStudy/app/src/main/java/kr/dktsudgg/androidarchitecturestudy/MainActivity.kt
>      override fun onClick(clickedView: View) {
onClick 을 databinding 으로 xml 에서 처리해 주어도 좋을것 같습니다!

2020-12-02 15:34 UTC, hhi-5258 commented on class15/dktsudgg/AndroidArchitectureStudy/app/src/main/java/kr/dktsudgg/androidarchitecturestudy/MainActivity.kt
> +                Toast.makeText(this@MainActivity, "검색어를 입력하세요", Toast.LENGTH_LONG).show();
BaseActivity 에 있는 showToast 함수를 사용해도 좋을 것 같습니다!

2020-12-03 09:29 UTC, dktsudgg commented on class15/dktsudgg/AndroidArchitectureStudy/app/src/main/java/kr/dktsudgg/androidarchitecturestudy/MainActivity.kt
>      override fun onClick(clickedView: View) {
"영화 검색 버튼" 클릭 시, 뷰모델(vm)을 호출하여 영화 검색 결과를 갱신하도록 수정하였습니다.
d0f4ab8

현재 "영화 검색이력 보기 버튼" 클릭 시에는 [뷰모델을 사용하지 않고 그냥 액티비티의 메소드를 호출](https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/925/files#diff-ef669eb375bfdc4e5aef81fd2cde5f67e0dcc343d0cca95efa6855b5a937817cR45)하여 새로운 액티비티로 이동하도록 구현되어있는데요, 이렇게 구현해도 괜찮은건지 잘 모르겠네요.

 잠깐 든 생각에는 뷰모델에다가 "새로운 액티비티로 이동하라고 알리기 위한 ObservableField변수"를 하나 두고
액티비티에서는 그 변수를 옵저빙하고있다가 변경사항이 감지됐을 때, startActivityForResult를 호출하는 방법도 문득 생각이 들긴 했는데 이런식으로 특정 액티비티 로직에 종속되면 뷰모델이 다른곳에서 재사용이 가능할까 싶기도 하고...
어떤식으로 짜야할지 헷갈리네요.

2020-12-03 09:30 UTC, dktsudgg commented on class15/dktsudgg/AndroidArchitectureStudy/app/src/main/java/kr/dktsudgg/androidarchitecturestudy/MainActivity.kt
> +                Toast.makeText(this@MainActivity, "검색어를 입력하세요", Toast.LENGTH_LONG).show();
수정하였습니다. 감사합니다!
b5759b3

2020-12-03 12:01 UTC, hhi-5258 commented on class15/dktsudgg/AndroidArchitectureStudy/app/src/main/java/kr/dktsudgg/androidarchitecturestudy/MainActivity.kt
>      override fun onClick(clickedView: View) {
저는 후자의 방식으로 했는데, 석준님이 얘기했듯이 특정 viewmodel 이 다른 view 에서도 그대로 사용되려면 두 개의 view가 같은 기능을 수행해야 하는데 그런 경우는 드물 것이라 생각되어 activity 별로 viewModel 을 만들었습니다.

근데 저도 이게 맞는지는 잘 모르겠어서 석준님의 답변을 기다려 봐야 할 것 같습니다 ㅎㅎ

2020-12-03 12:01 UTC, hhi-5258 approved these changes
수고하셨습니다!

2020-12-03 12:29 UTC, sjjeong requested changes

2020-12-03 12:29 UTC, sjjeong commented on class15/dktsudgg/AndroidArchitectureStudy/app/src/main/java/kr/dktsudgg/androidarchitecturestudy/MainActivity.kt
>          binding.activity = this@MainActivity
activity set하는 코드는 제거해주세요

2020-12-03 12:29 UTC, sjjeong commented on class15/dktsudgg/AndroidArchitectureStudy/app/src/main/java/kr/dktsudgg/androidarchitecturestudy/MovieSearchHistoryActivity.kt
> +        movieSearchHistoryViewModel.refreshMovieSearchHistoryList()
ViewModel이 init 될때 호출하도록 해주면 됩니다

2020-12-03 12:29 UTC, sjjeong commented on class15/dktsudgg/AndroidArchitectureStudy/app/src/main/res/layout/activity_main.xml
> +                    android:onClick="@{()-> vm.refreshSearchMovieList(movieSearchEditText.getText().toString())}"
query text를 파라미터로 전달하지 말고 two-way binding으로 처리해보세요

2020-12-03 12:29 UTC, sjjeong commented on class15/dktsudgg/AndroidArchitectureStudy/app/src/main/res/layout/activity_main.xml
>              name="activity"
activity는 제거해주세요

2020-12-03 15:46 UTC, dktsudgg commented on class15/dktsudgg/AndroidArchitectureStudy/app/src/main/res/layout/activity_main.xml
>              name="activity"
수정하였습니다. 감사합니다!
513768c

2020-12-03 15:46 UTC, dktsudgg commented on class15/dktsudgg/AndroidArchitectureStudy/app/src/main/java/kr/dktsudgg/androidarchitecturestudy/MainActivity.kt
>          binding.activity = this@MainActivity
수정하였습니다. 감사합니다!
513768c

2020-12-03 16:02 UTC, dktsudgg commented on class15/dktsudgg/AndroidArchitectureStudy/app/src/main/java/kr/dktsudgg/androidarchitecturestudy/MovieSearchHistoryActivity.kt
> +        movieSearchHistoryViewModel.refreshMovieSearchHistoryList()
수정하였습니다. 감사합니다!
d630312

2020-12-03 16:25 UTC, dktsudgg commented on class15/dktsudgg/AndroidArchitectureStudy/app/src/main/res/layout/activity_main.xml
> +                    android:onClick="@{()-> vm.refreshSearchMovieList(movieSearchEditText.getText().toString())}"
수정하였습니다. 감사합니다!
92f002a

2020-12-03 16:26 UTC, dktsudgg commented on class15/dktsudgg/AndroidArchitectureStudy/app/src/main/java/kr/dktsudgg/androidarchitecturestudy/MainActivity.kt
>      override fun onClick(clickedView: View) {
@hhi-5258 저도 후자의 방식으로 수정하였습니다ㅎㅎ

2020-12-04 15:11 UTC, sjjeong commented on class15/dktsudgg/AndroidArchitectureStudy/app/src/main/java/kr/dktsudgg/androidarchitecturestudy/MovieSearchHistoryActivity.kt
> +        movieSearchHistoryViewModel.refreshMovieSearchHistoryList()
class init {}을 만들어서 내부에서 호출하도록 해주세요

2020-12-04 15:23 UTC, dktsudgg commented on class15/dktsudgg/AndroidArchitectureStudy/app/src/main/java/kr/dktsudgg/androidarchitecturestudy/MovieSearchHistoryActivity.kt
> +        movieSearchHistoryViewModel.refreshMovieSearchHistoryList()
다시 수정하였습니다!
55d0df2

2020-12-04 15:51 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-12-04 16:25 UTC, merged