HW-5: MVVM 변환
sjjeong/GoogryAndroidArchitecutreStudy pull request #926
Opened 2020-12-02 12:52 UTC by simuelunbo

이번 과제는 저에겐 많이 삽질하고 힘들었습니다 MVVM 으로 제대로 했는지 모르겠네요...
하면서 이것 저것 수정 한다고 빠진거 있는거 피드백 주시면 감사하겠습니다.

2020-12-03 06:19 UTC, Myung777 reviewed
고생하셨습니다 :)

2020-12-03 06:19 UTC, Myung777 commented on class14/simuelunbo/AndroidArchitectureStudy/app/src/main/java/com/example/androidarchitecturestudy/ui/main/MainViewModel.kt
> +    fun requestLocalMovieData(){
혹시 로컬 데이터를 다지우고 새로 시작해보셨나요? 이부분에서 kotlin.collections.EmptyList cannot be cast to java.util.ArrayList 이런식으로 나오는데 movieList를 List 로 변경하면 해결이 될것 같습니다

2020-12-03 06:19 UTC, Myung777 commented on class14/simuelunbo/AndroidArchitectureStudy/app/src/main/java/com/example/androidarchitecturestudy/ui/main/MainActivity.kt
> +                Toast.makeText(this@MainActivity, viewModel.msg.get(), Toast.LENGTH_SHORT).show()
Toast 는 다른 액티비티에서도 사용가능하기 때문에 base 에 넣는게 더 좋지 않을까요?

2020-12-03 10:31 UTC, simuelunbo commented on class14/simuelunbo/AndroidArchitectureStudy/app/src/main/java/com/example/androidarchitecturestudy/ui/main/MainViewModel.kt
> +    fun requestLocalMovieData(){
4e022ff71032f40f47dcf419cb11628cd24c255a 수정했습니다

2020-12-03 10:50 UTC, simuelunbo commented on class14/simuelunbo/AndroidArchitectureStudy/app/src/main/java/com/example/androidarchitecturestudy/ui/main/MainActivity.kt
> +                Toast.makeText(this@MainActivity, viewModel.msg.get(), Toast.LENGTH_SHORT).show()
d641674639160281b096d4dd0280f487aa6b2d23 말씀하시는게 이렇게 변경 해달라는건가요?

2020-12-03 11:00 UTC, Myung777 commented on class14/simuelunbo/AndroidArchitectureStudy/app/src/main/java/com/example/androidarchitecturestudy/ui/main/MainActivity.kt
> +                Toast.makeText(this@MainActivity, viewModel.msg.get(), Toast.LENGTH_SHORT).show()
넵 근데 사실 저기에 넣는게 좋은건지는 잘모르곘네요 ...ㅎㅎ

2020-12-03 11:01 UTC, Myung777 approved these changes

2020-12-03 12:40 UTC, sjjeong requested changes

2020-12-03 12:40 UTC, sjjeong commented on class14/simuelunbo/AndroidArchitectureStudy/app/src/main/java/com/example/androidarchitecturestudy/Extension.kt
> +fun RecyclerView.bindQueryList(items: ArrayList<QueryHistory>) {
List를 받도록 해주세요

2020-12-03 12:40 UTC, sjjeong commented on class14/simuelunbo/AndroidArchitectureStudy/app/src/main/java/com/example/androidarchitecturestudy/ui/TitleFragmentDialog.kt
>          binding.dialog = this
이거는 제거해주세요

2020-12-04 09:23 UTC, simuelunbo commented on class14/simuelunbo/AndroidArchitectureStudy/app/src/main/java/com/example/androidarchitecturestudy/Extension.kt
> +fun RecyclerView.bindQueryList(items: ArrayList<QueryHistory>) {
4290e0ec7f5dd8396fd50fc2bd1f6a4a162cc226 수정하였습니다

2020-12-04 09:24 UTC, simuelunbo commented on class14/simuelunbo/AndroidArchitectureStudy/app/src/main/java/com/example/androidarchitecturestudy/ui/TitleFragmentDialog.kt
>          binding.dialog = this
3ea14e8c00608af94ccc916438437539dbc055a3

2020-12-04 15:12 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-12-05 02:24 UTC, merged