HW-5. MVVM 패턴 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #927
Opened 2020-12-02 13:53 UTC by onxmoreplz

recent_movie_item 레이아웃 파일과 RecentViewModel 데이터바인딩 이용해서 Click 이벤트 처리하려했으나
왠지모르게 RecentSearchViewModel에서 Observable 값들을 Set 해줘도
RecentSearchActivity에서 addOnPropertyChanged 콜백함수가 호출이 안되네요...
코드수정 가능성이 있어 주석처리 해놨습니다. 

혹시 예상되는 해결방법이 있다면 Comment 부탁드려요!

2020-12-03 17:37 UTC, dev-donghwan approved these changes

2020-12-03 17:37 UTC, dev-donghwan commented on class14/onxmoreplz/HW2_Project/app/src/main/java/com/example/hw2_project/main/MainViewModel.kt
> +    val failToGetMovie = ObservableField<Unit>()
같은 기능을 수행하지만 성공과 실패로 나뉘는데 Boolean값으로 true false를 나누는건 어떨까요?
--> 정정하겠습니다 LiveData가 아니라서 현재 방식이 더 좋을거 같아요.

2020-12-04 12:56 UTC, onxmoreplz commented on class14/onxmoreplz/HW2_Project/app/src/main/java/com/example/hw2_project/main/MainViewModel.kt
> +    val failToGetMovie = ObservableField<Unit>()
넵!

2020-12-04 15:27 UTC, sjjeong requested changes

2020-12-04 15:27 UTC, sjjeong commented on class14/onxmoreplz/HW2_Project/app/src/main/java/com/example/hw2_project/ViewExtensions.kt
> +    var recentSearchRecyclerViewAdapter = adapter as RecentSearchRecyclerViewAdapter
val로 선언해주시고 as?를 사용하도록 해주세요

2020-12-04 15:27 UTC, sjjeong commented on class14/onxmoreplz/HW2_Project/app/src/main/java/com/example/hw2_project/recentSearch/RecentSearchRecyclerViewAdapter.kt
> +        binding.vm = RecentSearchViewModel(repository)
여기서 ViewModel를 새로 만들지 말아주세요

2020-12-04 15:27 UTC, sjjeong commented on class14/onxmoreplz/HW2_Project/app/src/main/res/layout/activity_main.xml
> +                android:onClick="@{() -> vm.getMovieFromRepository(etMovieName.getText().toString())}"
검색어는 파라미터로 전달하지 마시고 two-way처리 해주세요

2020-12-05 16:39 UTC, onxmoreplz commented on class14/onxmoreplz/HW2_Project/app/src/main/java/com/example/hw2_project/recentSearch/RecentSearchRecyclerViewAdapter.kt
> +        binding.vm = RecentSearchViewModel(repository)
사용되는 곳이 없었네요.

8f2a446

2020-12-05 16:39 UTC, onxmoreplz commented on class14/onxmoreplz/HW2_Project/app/src/main/java/com/example/hw2_project/ViewExtensions.kt
> +    var recentSearchRecyclerViewAdapter = adapter as RecentSearchRecyclerViewAdapter
수정했습니다.

08f6028

2020-12-05 16:40 UTC, onxmoreplz commented on class14/onxmoreplz/HW2_Project/app/src/main/res/layout/activity_main.xml
> +                android:onClick="@{() -> vm.getMovieFromRepository(etMovieName.getText().toString())}"
파라미터 없앤 뒤, 2-way 데이터바인딩 적용했습니다.
 
127a3ec

2020-12-06 06:42 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-12-07 11:50 UTC, merged