HW- 5 : MVVM 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #929
Opened 2020-12-02 17:20 UTC by hhi-5258

늦어서 죄송합니다 ㅠㅠ

2020-12-03 09:59 UTC, dktsudgg reviewed
MainViewModel이랑 RecentSearchViewModel에 둘다 loading이라는 변수를 선언하여 프로그레스 동작을 제어하는데요,

데이터가 갱신될 때 프로그레스 동작을 제어하는것은 대부분 공통적으로 들어갈 만한 사항이니까
BaseViewModel같은걸 하나 만들어두고 loading변수를 두어도 괜찮을 것 같다는 생각입니다!

2020-12-03 12:11 UTC, hhi-5258 commented
수정하였습니다!

5c83729

2020-12-03 12:16 UTC, dktsudgg approved these changes
수고하셨습니다~

2020-12-03 12:45 UTC, sjjeong requested changes

2020-12-03 12:45 UTC, sjjeong commented on class15/hhi-5258/HHiApplication/app/src/main/java/com/hhi/myapplication/base/BaseViewModel.kt
> +    val loading = ObservableField(View.GONE)
boolean을 받아서 xml에서 visible 처리 하도록 해주세요

2020-12-03 12:45 UTC, sjjeong commented on class15/hhi-5258/HHiApplication/app/src/main/java/com/hhi/myapplication/recentSearch/RecentSearchActivity.kt
> +        binding.activity = this@RecentSearchActivity
activity set하는 코드는 제거해주세요

2020-12-03 12:45 UTC, sjjeong commented on class15/hhi-5258/HHiApplication/app/src/main/res/layout/activity_main.xml
> +            android:onClick="@{()->vm.searchMovie(mainEditSearch.getText().toString())}"
검색어는 EditText에 two-way로 처리해주세요

2020-12-03 12:45 UTC, sjjeong commented on class15/hhi-5258/HHiApplication/app/src/main/java/com/hhi/myapplication/main/MainActivity.kt
> +        binding.activity = this@MainActivity
activity set 하는 코드 제거해주세요

2020-12-04 12:05 UTC, hhi-5258 commented on class15/hhi-5258/HHiApplication/app/src/main/java/com/hhi/myapplication/main/MainActivity.kt
> +        binding.activity = this@MainActivity
수정하였습니다!
5924f1b

2020-12-04 12:05 UTC, hhi-5258 commented on class15/hhi-5258/HHiApplication/app/src/main/java/com/hhi/myapplication/recentSearch/RecentSearchActivity.kt
> +        binding.activity = this@RecentSearchActivity
수정하였습니다!
5924f1b

2020-12-04 12:06 UTC, hhi-5258 commented on class15/hhi-5258/HHiApplication/app/src/main/res/layout/activity_main.xml
> +            android:onClick="@{()->vm.searchMovie(mainEditSearch.getText().toString())}"
수정하였습니다!
417018f

2020-12-04 12:06 UTC, hhi-5258 commented on class15/hhi-5258/HHiApplication/app/src/main/java/com/hhi/myapplication/base/BaseViewModel.kt
> +    val loading = ObservableField(View.GONE)
수정하였습니다!
4ab1799

2020-12-04 15:37 UTC, sjjeong requested changes

2020-12-04 15:37 UTC, sjjeong commented on class15/hhi-5258/HHiApplication/app/src/main/res/layout/activity_main.xml
> +            name="activity"
여기도 같이 제거해주세요 
다른 xml에 있는 activity도 제거해주세요

2020-12-04 15:50 UTC, hhi-5258 commented on class15/hhi-5258/HHiApplication/app/src/main/res/layout/activity_main.xml
> +            name="activity"
아, 그걸 빼먹었네요! 수정하였습니다.
9973854

2020-12-04 15:51 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-12-04 15:53 UTC, merged