HW-4 MVVM 패턴 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #93
Opened 2019-07-04 01:56 UTC by NackUn

2019-07-04 04:55 UTC, BeokBeok requested changes
리뷰 작성 하였습니다.

2019-07-04 04:55 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/main/MainFragment.kt
>      private fun setOnClick() {
해당 함수는 불필요한 함수입니다.
클릭 리스너 자체를 데이터바인딩을 사용하여 정리해주세요.

2019-07-04 04:55 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/main/MainFragment.kt
> +            vm.requestTickers(view)
View에서 ViewModel을 호출하는 방식이 아니라,
View에 대한 이벤트는 ViewModel로 받고, 데이터바인딩을 통하여 View에 전달되어야 합니다.
ObservableField를 사용하여 처리해 주세요.

MVVM 구조 이미지 URL
- https://files.slack.com/files-pri/TKE6B3X7Y-FL365TM2B/image.png

2019-07-04 04:55 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/main/MainViewModel.kt
> +    DataSource.RequestTickersCallback {
개행하지 마시고 BaseViewModel 옆에 위치해 주세요

2019-07-04 04:55 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/Base/BaseActivity.kt
>  package sample.nackun.com.studyfirst.Base
패키지명은 소문자로 변경해주세요

2019-07-04 04:55 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/Base/BasePresenter.kt
> -interface BasePresenter
BaseView도 제거해주세요

2019-07-04 04:55 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/Base/BaseActivity.kt
> +        binding.lifecycleOwner = this
Activity에서 데이터바인딩을 사용하지 않는 것으로 보이는데,
사용하지 않는다면 제거해주세요

2019-07-04 04:55 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/Base/BaseActivity.kt
> +    protected lateinit var binding: B
BaseActivity를 상속받은 MainActivity에서 해당 변수를 사용하지 않는 것으로 보입니다.
확인 후 알맞은 접근자로 변경해주세요

2019-07-04 04:55 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/Base/BaseFragment.kt
> +        binding.lifecycleOwner = this
lifecycleOwner를 설정하는 것은 무슨 의미인가요?

2019-07-04 04:55 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/main/MainFragment.kt
> +import java.util.*
사용하지 않는 import는 정리해주세요

2019-07-04 04:55 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/main/MainFragment.kt
> +        binding.setVariable(BR.vm, vm)
중복된 로직으로 보입니다.
확인 후 제거해주세요

2019-07-04 04:55 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/main/MainViewModel.kt
> +    val repository: Repository
해당 변수의 사용 범위를 확인하여 접근자 추가해주세요

2019-07-04 04:55 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/ui/TickerAdapter.kt
>      fun setItems(tickers: List<Map<String, String>>) {
BindingAdapter Annotation 추가해주세요

2019-07-04 04:55 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/res/layout/main_fragment.xml
> -    </TextView>
`<TextView></TextView>` 대신 `<TextView />` 로 변경해주세요

2019-07-04 04:55 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/res/layout/main_fragment.xml
>  <?xml version="1.0" encoding="utf-8"?>
전체 선택 후 Ctrl + Alt + L 을 누르면 재정렬됩니다.
해당 기능을 적용해 주세요

2019-07-04 04:55 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/res/layout/main_fragment.xml
>              </android.support.v7.widget.RecyclerView>
`<android.support.v7.widget.RecyclerView></android.support.v7.widget.RecyclerView>` 대신
`<android.support.v7.widget.RecyclerView />` 로 적용해주세요

2019-07-04 04:55 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/res/layout/ticker_item.xml
> +                android:paddingStart="4dp"
paddingStart를 적용하셨으면, paddingEnd도 적용해주세요

2019-07-04 04:55 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/Base/BaseViewModel.kt
> +abstract class BaseViewModel : BaseObservable()
BaseViewModel은 하는 것이 없어 보이는데, 제거하는 것은 어떤가요?

2019-07-04 04:55 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/ui/TickerAdapter.kt
>  package sample.nackun.com.studyfirst.ui
main 패키지와 ui 패키지가 나뉘어야 하는 이유를 모르겠습니다.

2019-07-05 01:14 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/Base/BaseFragment.kt
> +        binding.lifecycleOwner = this
라이프사이클을 일치시켜주는 건 줄 알고 사용했습니다만 LiveData를 사용할 때 이용하는 것 같습니다.
To use a LiveData object with your binding class, you need to specify a lifecycle owner to define the scope of the LiveData object. The following example specifies the activity as the lifecycle owner after the binding class has been instantiated:

출처 : https://developer.android.com/topic/libraries/data-binding/architecture

2019-07-05 01:19 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/ui/TickerAdapter.kt
>  package sample.nackun.com.studyfirst.ui
처음 예제를 만들 때 쉽게 익히기 위해서 따로 뒀는데 현석님 말씀대로 바꿔야겠습니다.
main 패키지를 없애고 ui 패키지의 TickerActivity 처럼 main을 전부 Ticker로 바꿔도 될까요?
그럼 시작을 TickerActivity로 해야되는데 헷갈리지 않을까요?

2019-07-05 01:25 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/main/MainViewModel.kt
> +    DataSource.RequestTickersCallback {
수정하였습니다
61aaba8

2019-07-05 01:26 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/Base/BaseActivity.kt
>  package sample.nackun.com.studyfirst.Base
변경했습니다
a3d2fd0

2019-07-05 01:26 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/Base/BasePresenter.kt
> -interface BasePresenter
제거했습니다
ed10482

2019-07-05 01:27 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/Base/BaseActivity.kt
> +    protected lateinit var binding: B
사용하지 않는 Binding 제거하였습니다
f48a0b6

2019-07-05 01:27 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/Base/BaseActivity.kt
> +        binding.lifecycleOwner = this
사용하지 않는 Binding 제거하였습니다
f48a0b6

2019-07-05 01:27 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/main/MainFragment.kt
> +import java.util.*
정리했습니다

2019-07-05 01:28 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/res/layout/main_fragment.xml
>              </android.support.v7.widget.RecyclerView>
변경했습니다
1f1d8f3

2019-07-05 01:28 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/res/layout/main_fragment.xml
> -    </TextView>
전체적으로 변경했습니다
489ffb9

2019-07-05 01:28 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/res/layout/main_fragment.xml
>  <?xml version="1.0" encoding="utf-8"?>
해당 기능을 적용했습니다
489ffb9

2019-07-05 02:50 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/Base/BaseViewModel.kt
> +abstract class BaseViewModel : BaseObservable()
제거했습니다.
aa35e7a

2019-07-05 04:39 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/Base/BaseFragment.kt
> +        binding.lifecycleOwner = this
그렇다면, LifeCycle을 학습하신 후 사용하시는 것이 어떤가요?

2019-07-05 04:39 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/main/MainFragment.kt
> +import java.util.*
커밋 id 적어주세요

2019-07-05 04:42 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/ui/TickerAdapter.kt
>  package sample.nackun.com.studyfirst.ui
메니페스트에 Main이라 명시된 부분을 찾으면 되기 때문에, 시작점을 찾는 부분은 크게 어렵지 않다고 생각합니다.

2019-07-05 19:08 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/ui/TickerAdapter.kt
>  package sample.nackun.com.studyfirst.ui
변경했습니다.
c017375

2019-07-05 19:10 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/res/layout/ticker_item.xml
> +                android:paddingStart="4dp"
paddingStart를 사용하면 꼭 paddingEnd도 사용해야되나요??

2019-07-05 19:13 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/ui/TickerAdapter.kt
>      fun setItems(tickers: List<Map<String, String>>) {
setItems에 추가해줘야되나요?

2019-07-05 19:22 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/main/MainFragment.kt
> +import java.util.*
커밋시 cleanup을 사용하고 있는데 언제 빠졌는지 모르겠습니다.
70710ae

2019-07-05 19:52 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/Base/BaseFragment.kt
> +        binding.lifecycleOwner = this
현석님 말씀이 맞으십니다. 삭제하려고 했는데 일이 생겨 지금에서야 삭제합니다.
5eddab1

2019-07-05 19:53 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/main/MainFragment.kt
>      private fun setOnClick() {
데이터바인딩을 사용했습니다.
8ca59db

2019-07-05 19:53 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/main/MainFragment.kt
> +            vm.requestTickers(view)
현석님 코드 참고하여 변경했습니다.
f9b18d4

2019-07-05 19:54 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/main/MainViewModel.kt
> +    val repository: Repository
접근자 추가했습니다.
a041a4e

2019-07-05 19:57 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/main/MainFragment.kt
> +        binding.setVariable(BR.vm, vm)
제거하면 실행이 안되네요. 바인딩에 셋해주는게 필요한거 아닌가요?

2019-07-05 23:40 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/main/MainFragment.kt
> +import java.util.*
ticker_item.xml 과 activity_main.xml 에는 layout 테그가 불필요해보입니다.

2019-07-05 23:43 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/main/MainFragment.kt
> +        binding.setVariable(BR.vm, vm)
binding.vm 으로 잘 못 봤습니다.

2019-07-05 23:44 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/res/layout/ticker_item.xml
> +                android:paddingStart="4dp"
반드시는 아니지만, IDE에서 나타내는 warning을 참고하시어 작업해주세요

2019-07-06 03:32 UTC, sjjeong requested changes

2019-07-06 03:32 UTC, sjjeong commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/ui/ticker/TickerFragment.kt
> +    override fun onViewCreated(
onActivityCreated()로 변경

2019-07-06 03:32 UTC, sjjeong commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/ui/ticker/TickerFragment.kt
> +        tv_market_krw.callOnClick()
이거 제거 해주세요. 다른방법으로 처리해주세요

2019-07-06 03:32 UTC, sjjeong commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/ui/ticker/TickerFragment.kt
> +    private fun setMarketColor(view: View) {
이부분은 mvvm구조에서 맞지 않습니다.

2019-07-06 03:32 UTC, sjjeong commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/ui/ticker/TickerRecyclerViewExt.kt
> +    val adapter: TickerAdapter = recyclerView.adapter as TickerAdapter
as? 를 사용해서 safe type casting 해주세요

2019-07-07 14:47 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/main/MainFragment.kt
> +import java.util.*
제거 후 paddingEnd 추가했습니다.
5ae9cad

2019-07-07 14:48 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/res/layout/ticker_item.xml
> +                android:paddingStart="4dp"
제거 후 paddingEnd 추가했습니다.
5ae9cad

2019-07-07 15:37 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/ui/ticker/TickerFragment.kt
> +    override fun onViewCreated(
변경했습니다
f353ec6

2019-07-07 15:37 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/ui/ticker/TickerFragment.kt
> +    private fun setMarketColor(view: View) {
이렇게 변경해봤습니다.
ad16ea7

2019-07-07 15:37 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/ui/ticker/TickerRecyclerViewExt.kt
> +    val adapter: TickerAdapter = recyclerView.adapter as TickerAdapter
변경했습니다
6a084cc

2019-07-11 13:46 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/ui/TickerAdapter.kt
>      fun setItems(tickers: List<Map<String, String>>) {
@BeokBeok TickerRecyclerViewExt.kt 요기에 셋네임이 되있는데... 함수명이 같아서 문제가 발생할까요?

2019-07-11 14:32 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/ui/ticker/TickerFragment.kt
> +        tv_market_krw.callOnClick()
이렇게 변경했습니다.
f877a52

2019-07-11 14:32 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/ui/TickerAdapter.kt
>      fun setItems(tickers: List<Map<String, String>>) {
관련 노란색(warning)은 제거했습니다.
18fd95c

2019-07-12 01:30 UTC, BeokBeok requested changes

2019-07-12 01:30 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/ui/ticker/TickerFragment.kt
> +        vm.showTickers(vm.selectedMarket.get().toString())
초반에 데이터를 뿌려주기 위함이라면, 파라미터에 String을 넣어도 되지 않을까요?

2019-07-12 01:30 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/ui/ticker/TickerViewModel.kt
> +    fun selectedMarket(view: View) {
view model 에서는 TextView와 같은 View를 가지고 있으면 안됩니다.
View 를 제거해주세요

2019-07-12 01:30 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/res/layout/ticker_fragment.xml
> +        <ScrollView
리싸이클러뷰 자체에서 스크롤이 되는데,
혹시 스크롤뷰로 리싸이클러뷰를 감싼 이유가 있나요?

2019-07-12 01:57 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/ui/ticker/TickerFragment.kt
> +        vm.showTickers(vm.selectedMarket.get().toString())
초반 시작마켓을 바꿀 수도 있어서 ObservableField 초기값만 바꾸면 되게 코드를 짰는데 String을 넣는게 좋을까요?

2019-07-12 01:57 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/res/layout/ticker_fragment.xml
> +        <ScrollView
제거했습니다
670130c

2019-07-12 01:58 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/ui/ticker/TickerViewModel.kt
> +    fun selectedMarket(view: View) {
변경했습니다
a2cbe09

2019-07-12 02:18 UTC, BeokBeok requested changes

2019-07-12 02:18 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/ui/ticker/TickerViewModel.kt
> +    val selectedMarket = ObservableField<String>("KRW")
생성자로 String을 받은 경우에는
앞에 String 타입을 명시하지 않아도 됩니다.

2019-07-12 02:18 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/ui/ticker/TickerFragmentExt.kt
> +    if (textView.text.toString().equals(selectedMarket)) {
단순히 값만 비교하는 것이라면, == 을 권장합니다.

참고 URL
- https://medium.com/@agrawalsuneet/equality-in-kotlin-and-equals-d8373ef529f1

2019-07-12 02:18 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/ui/ticker/TickerFragment.kt
> +import android.widget.TextView
사용하지 않는 import 문 정리 해주세요

2019-07-12 02:18 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/ui/ticker/TickerFragment.kt
> +        vm.showTickers(vm.selectedMarket.get().toString())
상용님의 의도를 몰랐습니다.
그리고 toString으로 변환하셨는데, 
vm.selectedMarket.get() 이 Nullable 하기 때문에 NPE 발생 가능성이 있어 보입니다.
NPE 예외처리가 필요할 것 같습니다.

2019-07-12 02:19 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/ui/ticker/TickerFragment.kt
> +        vm.showTickers(vm.selectedMarket.get().toString())
상용님의 의도를 몰랐습니다.
그리고 toString으로 변환하셨는데,
vm.selectedMarket.get() 이 Nullable 하기 때문에 NPE 발생 가능성이 있어 보입니다.
NPE 예외처리가 필요할 것 같습니다.

2019-07-12 02:44 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/ui/ticker/TickerFragment.kt
> +import android.widget.TextView
제거하였습니다. 혹시 커밋 시에 Cleanup 체크 되있으면 알아서 해주는거 아닌가요??
0d0dc9e

2019-07-12 02:44 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/ui/ticker/TickerFragment.kt
> +        vm.showTickers(vm.selectedMarket.get().toString())
이렇게 변경해봤습니다.
035935a

2019-07-12 02:44 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/ui/ticker/TickerViewModel.kt
> +    val selectedMarket = ObservableField<String>("KRW")
변경하였습니다. 감사합니다!!
0f7a220

2019-07-12 02:47 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/ui/ticker/TickerFragmentExt.kt
> +    if (textView.text.toString().equals(selectedMarket)) {
변경했습니다. 아지도 자바처럼 생각하고 있었네요..ㅎㅎ 근데 참고 URL에서 말하는 경우
Float, Double 형일 때에 경우아닌가요?? 
6783858

2019-07-12 03:22 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/ui/ticker/TickerFragmentExt.kt
> +    if (textView.text.toString().equals(selectedMarket)) {
IDE 에서도 해당 Warning이 나타나고 있기 때문에, String도 마찬가지 인 것 같습니다.

2019-07-12 03:22 UTC, BeokBeok commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/ui/ticker/TickerFragment.kt
> +import android.widget.TextView
Optimize import 를 체크하셔야 합니다.

2019-07-12 03:24 UTC, BeokBeok reviewed
LGTM

2019-07-12 04:38 UTC, NackUn commented on NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/ui/ticker/TickerFragment.kt
> +import android.widget.TextView
아.. Optimize import 체크가 안되있었네요. 감사합니다 ㅎㅎ 앞으로는 체크해서 커밋하도록 하겠습니다.

2019-07-12 14:42 UTC, BeokBeok approved these changes

2019-07-13 05:09 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-07-14 05:04 UTC, merged