HW-5 MVP -> MVVM 패턴 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #930
Opened 2020-12-02 20:11 UTC by PeonyF

- 기존 MVP 패턴에서 MVVM 패턴으로 변경하였습니다.
- 이에따라 Presenter,Contract 클래스를 삭제하였으며, ViewModel 클래스를 추가하였습니다.

2020-12-03 04:22 UTC, jihoi-kang commented on class15/PeonyF/AndroidArchitectureStudy/app/src/main/java/com/architecture/androidarchitecturestudy/ui/main/MainViewModel.kt
> +class MainViewModel(private val movieRepository: MovieRepositoryImpl) {
`MovieRepositoryImpl` 대신 interface인 `MovieRepository`로 선언하는게 맞는 방법인 거 같습니다.
`SearchHistoryViewModel` class도 확인 부탁드립니다.

2020-12-03 04:22 UTC, jihoi-kang commented on class15/PeonyF/AndroidArchitectureStudy/app/src/main/java/com/architecture/androidarchitecturestudy/ui/main/MainViewModel.kt
> +            showToastMsg.notifyChange()
코드상으로 보았을 때 `showToastMsg`를 한후에도 아래 `movieRepository.getMovieData(...)` 코드를 실행할 거 같습니다.
혹시 의도하신 것인지 확인 부탁드립니다. 의도하신 것이 아니라면 `return`으로 아래 코드들을 실행하지 않게 막을 수 있을 거 같습니다.

2020-12-03 14:04 UTC, PeonyF commented on class15/PeonyF/AndroidArchitectureStudy/app/src/main/java/com/architecture/androidarchitecturestudy/ui/main/MainViewModel.kt
> +            showToastMsg.notifyChange()
의도하지 않은 부분이며 놓쳤던 부분입니다. 감사합니다 :)
(2047d91)

2020-12-03 14:05 UTC, PeonyF commented on class15/PeonyF/AndroidArchitectureStudy/app/src/main/java/com/architecture/androidarchitecturestudy/ui/main/MainViewModel.kt
> +class MainViewModel(private val movieRepository: MovieRepositoryImpl) {
말씀하신 부분 확인하여 두클래스 모두 변경하였습니다. 감사합니다!
(b246dfd)

2020-12-03 17:17 UTC, jihoi-kang approved these changes
고생하셨습니다.
LGTM👍

2020-12-04 15:49 UTC, sjjeong requested changes

2020-12-04 15:49 UTC, sjjeong commented on class15/PeonyF/AndroidArchitectureStudy/app/src/main/java/com/architecture/androidarchitecturestudy/adapter/DataBindingAdapter.kt
> +    movieAdapter.setMovieList(list)
이렇게하면  될 것 같습니다.
```kotlin
list ?: return
val movieAdapter = adapter ?: MovieAdapter().apply {
    adapter = this
}
movieAdapter.setMovieList(list)
```

2020-12-04 15:49 UTC, sjjeong commented on class15/PeonyF/AndroidArchitectureStudy/app/src/main/res/layout/activity_main.xml
>              name="mainActivity"
activity 제거해주세요

2020-12-04 15:49 UTC, sjjeong commented on class15/PeonyF/AndroidArchitectureStudy/app/src/main/res/layout/activity_search_history.xml
>              name="searchActivity"
activity 제거해주세요

2020-12-04 17:15 UTC, ChaaaChaaa commented on class15/PeonyF/AndroidArchitectureStudy/app/src/main/java/com/architecture/androidarchitecturestudy/adapter/DataBindingAdapter.kt
> +    movieAdapter.setMovieList(list)
말씀해주신 부분 확인하여 변경하였습니다. (7e7af17)

2020-12-04 17:16 UTC, PeonyF commented on class15/PeonyF/AndroidArchitectureStudy/app/src/main/res/layout/activity_main.xml
>              name="mainActivity"
MainActivity와 xml에서 mainActivity  변수제거 하였습니다. (c7c349e)

2020-12-04 17:17 UTC, PeonyF commented on class15/PeonyF/AndroidArchitectureStudy/app/src/main/res/layout/activity_search_history.xml
>              name="searchActivity"
SearchHistoryActivity 와 xml에서 searchActivity  변수제거 하였습니다. (632f539)

2020-12-05 05:38 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-12-05 09:46 UTC, merged