Class14/dev donghwan
sjjeong/GoogryAndroidArchitecutreStudy pull request #931
Opened 2020-12-04 15:53 UTC by dev-donghwan

죄송합니다 요즘 바빠서ㅠㅠ

2020-12-05 05:42 UTC, sjjeong requested changes

2020-12-05 05:42 UTC, sjjeong commented on class14/dev-donghwan/studyfork/app/src/main/res/layout/activity_main.xml
>              name="activity"
activity 제거하고 viewmodel로 함수 호출하도록 해주세요

2020-12-05 05:42 UTC, sjjeong commented on class14/dev-donghwan/studyfork/app/src/main/java/com/example/studyfork/main/MainViewModel.kt
> +        if (query.isNullOrEmpty()) showQueryError.set(Unit)
query가 비어있으면 하단 로직을 동작하지 않도록 return 처리도 추가해주세요

2020-12-05 05:42 UTC, sjjeong commented on class14/dev-donghwan/studyfork/app/src/main/java/com/example/studyfork/main/MainViewModel.kt
> +                else movieList.set(it.items)
{} 추가 해주세요

2020-12-05 05:42 UTC, sjjeong commented on class14/dev-donghwan/studyfork/app/src/main/res/layout/activity_recent_search_list.xml
>              name="activity"
여기도 activity 제거 해주세요

2020-12-07 11:50 UTC, onxmoreplz approved these changes

2020-12-08 11:44 UTC, dev-donghwan commented on class14/dev-donghwan/studyfork/app/src/main/java/com/example/studyfork/main/MainViewModel.kt
> +                else movieList.set(it.items)
6bd0fea

2020-12-08 11:44 UTC, dev-donghwan commented on class14/dev-donghwan/studyfork/app/src/main/java/com/example/studyfork/main/MainViewModel.kt
> +        if (query.isNullOrEmpty()) showQueryError.set(Unit)
814e2d4

2020-12-08 11:45 UTC, dev-donghwan commented on class14/dev-donghwan/studyfork/app/src/main/res/layout/activity_main.xml
>              name="activity"
af9449c

2020-12-08 11:45 UTC, dev-donghwan commented on class14/dev-donghwan/studyfork/app/src/main/java/com/example/studyfork/main/MainViewModel.kt
> +                else movieList.set(it.items)
6bd0fea

2020-12-08 11:45 UTC, dev-donghwan commented on class14/dev-donghwan/studyfork/app/src/main/res/layout/activity_recent_search_list.xml
>              name="activity"
20e596e

2020-12-09 01:21 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-12-09 02:11 UTC, merged