Convert to AAC ViewModel & LiveData
sjjeong/GoogryAndroidArchitecutreStudy pull request #932
Opened 2020-12-06 04:03 UTC by jihoi-kang

5주차 과제때 모르고 ViewModel class에 ViewModel() 상속 받아서 쓰고 있었는데 AAC ViewModel인지 모르고 사용하고 있었네요.
수업을 통해 5주차 ViewModel과 AAC ViewModel의 차이점을 알게 되었습니다.

AAC ViewModel & LiveData 과제 올립니다.

2020-12-08 18:22 UTC, PeonyF approved these changes
딱히 문제되는 부분을 찾지못하여 Approve 처리하겠습니다. 수고하셨습니다. 👍

2020-12-09 10:42 UTC, sjjeong requested changes

2020-12-09 10:42 UTC, sjjeong commented on class15/jihoi-kang/aas/app/src/main/java/com/jay/aas/ui/history/SearchHistoryActivity.kt
> +        binding.lifecycleOwner = this
이거는 base에서 처리하면 두개 activity에서 추가할 필요가 없습니다

2020-12-09 10:50 UTC, jihoi-kang commented on class15/jihoi-kang/aas/app/src/main/java/com/jay/aas/ui/history/SearchHistoryActivity.kt
> +        binding.lifecycleOwner = this
5bfcbc3
수정하였습니다.

2020-12-10 05:10 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-12-10 07:49 UTC, merged