HW-6 AAC ViewModel, LiveData 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #933
Opened 2020-12-06 06:59 UTC by Myung777

2020-12-09 09:40 UTC, simuelunbo approved these changes
잘 하신거 같아서 approve 하였습니다 수고하셨습니다

2020-12-09 10:43 UTC, sjjeong requested changes

2020-12-09 10:43 UTC, sjjeong commented on class14/myung777/StudyFork/app/src/main/java/com/deepco/studyfork/MainActivity.kt
> +        binding.lifecycleOwner = this
Base에서 추가 해주시면 됩니다

2020-12-09 14:22 UTC, Myung777 commented on class14/myung777/StudyFork/app/src/main/java/com/deepco/studyfork/MainActivity.kt
> +        binding.lifecycleOwner = this
수정하였습니다
bccac4a

2020-12-10 05:13 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-12-10 06:54 UTC, merged