HW-6 AAC ViewModel, LiveData 적용 과제
sjjeong/GoogryAndroidArchitecutreStudy pull request #935
Opened 2020-12-07 17:30 UTC by dktsudgg

6번째 과제입니다

2020-12-08 13:45 UTC, hhi-5258 approved these changes
잘 하신것같습니다! 수고하셨습니다!

2020-12-09 10:44 UTC, sjjeong requested changes

2020-12-09 10:44 UTC, sjjeong commented on class15/dktsudgg/AndroidArchitectureStudy/app/src/main/java/kr/dktsudgg/androidarchitecturestudy/MainActivity.kt
> +        binding.lifecycleOwner = this
Base에서 추가 해줄 수 있습니다

2020-12-09 16:16 UTC, dktsudgg commented on class15/dktsudgg/AndroidArchitectureStudy/app/src/main/java/kr/dktsudgg/androidarchitecturestudy/MainActivity.kt
> +        binding.lifecycleOwner = this
수정하였습니다. 감사합니다!
0a4aa2d

2020-12-10 05:13 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-12-10 11:06 UTC, merged