HW-6 : aac ViewModel, LiveData 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #936
Opened 2020-12-08 13:33 UTC by hhi-5258

2020-12-09 08:09 UTC, dktsudgg commented
잘 하신 것 같아서 승인하겠습니다~ 수고하셨습니다!

2020-12-09 08:10 UTC, dktsudgg approved these changes
잘 하신 것 같아서 승인하겠습니다~ 수고하셨습니다!

2020-12-09 10:45 UTC, sjjeong requested changes

2020-12-09 10:45 UTC, sjjeong commented on class15/hhi-5258/HHiApplication/app/src/main/java/com/hhi/myapplication/main/MainActivity.kt
> +        binding.lifecycleOwner = this
Base에서 추가 할 수 있습니다.

2020-12-10 13:09 UTC, hhi-5258 commented on class15/hhi-5258/HHiApplication/app/src/main/java/com/hhi/myapplication/main/MainActivity.kt
> +        binding.lifecycleOwner = this
수정하였습니다!
f30df67

2020-12-10 14:02 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-12-12 05:32 UTC, merged