HW-6  ACC ViewModel, LiveData 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #939
Opened 2020-12-09 18:44 UTC by PeonyF

기존 ViewModel에서 ACC ViewModel과 LiveData로 변경하였습니다.
이에따라 ui패키지의 main,searchhistory 패키지의 내용이 변경되었으며, xml viewmodel 변수명을 수정하였습니다.

2020-12-10 02:46 UTC, jihoi-kang commented on class15/PeonyF/AndroidArchitectureStudy/app/src/main/java/com/architecture/androidarchitecturestudy/ui/main/MainActivity.kt
> +        binding.lifecycleOwner = this
lifecycleOwner 는 base에서 처리하면 두개 activity에서 추가할 필요가 없습니다. (저도 어제 받은 피드백이라서..)

2020-12-10 06:13 UTC, PeonyF commented on class15/PeonyF/AndroidArchitectureStudy/app/src/main/java/com/architecture/androidarchitecturestudy/ui/main/MainActivity.kt
> +        binding.lifecycleOwner = this
아하! 그렇군요!! 말씀하신 licycleOwner를 baseActivity로 이동하였습니다. (92451a2)

2020-12-10 07:48 UTC, jihoi-kang approved these changes
고생하셨습니다!
LGTM👍

2020-12-10 14:01 UTC, sjjeong requested changes

2020-12-10 14:01 UTC, sjjeong commented on class15/PeonyF/AndroidArchitectureStudy/app/src/main/java/com/architecture/androidarchitecturestudy/ui/main/MainViewModel.kt
> +    var isVisibleToast = true
이런 플래그는 필요가 없습니다
SingleLiveData 라는것을 찾아보세요

2020-12-11 06:16 UTC, PeonyF commented on class15/PeonyF/AndroidArchitectureStudy/app/src/main/java/com/architecture/androidarchitecturestudy/ui/main/MainViewModel.kt
> +    var isVisibleToast = true
말씀해주신 키워드 확인하여 수정하였습니다. (204e7c7)

2020-12-12 02:48 UTC, sjjeong commented on class15/PeonyF/AndroidArchitectureStudy/app/src/main/java/com/architecture/androidarchitecturestudy/ui/main/MainViewModel.kt
> +    var isVisibleToast = true
@PeonyF 
SingleLiveData 자체를 쓰시면 해당 플래그를 사용하지 않아도 됩니당

2020-12-12 12:03 UTC, PeonyF commented on class15/PeonyF/AndroidArchitectureStudy/app/src/main/java/com/architecture/androidarchitecturestudy/ui/main/MainViewModel.kt
> +    var isVisibleToast = true
잉 석준님 위에 전달드렸던  커밋 (204e7c7) 클릭시에 
 -   var isVisibleToast = true
 +  val pending: AtomicBoolean = AtomicBoolean(false)
로 isVisibleToast 플래그를 삭제하고 peding으로 변경하였는데, 저기에는 +표시되어있네요 제 commit에 문제가 있는걸까요?

2020-12-13 15:06 UTC, PeonyF commented on class15/PeonyF/AndroidArchitectureStudy/app/src/main/java/com/architecture/androidarchitecturestudy/ui/main/MainViewModel.kt
> +    var isVisibleToast = true
SingleLiveEvent 클래스를 만들어서(a096ae4) 내용 변경시 해당 클래스를 호출하여 toast가 출력되도록(dfe5eac)
변경하였습니다.  이에 따라 Main class의 해당 부분도 변경하였습니다.(7dfbfba)

2020-12-14 04:26 UTC, dino-prnd approved these changes
LGTM ✊ ✌️ 👋⭐️ 🌟 💫

2020-12-14 04:27 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-12-14 05:46 UTC, merged