HW-3 MVVM Databinding 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #94
Opened 2019-07-04 08:26 UTC by sport0102

2019-07-04 11:54 UTC, brooks-o requested changes

2019-07-04 11:54 UTC, machine-human commented on sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/data/source/UpbitRepository.kt
>  ) : UpbitDataSource {
확인해보니 remoteDataSource에서는 invoke 함수로 싱글톤 되어 있는데,
Repository 클래스에는 적용 안 하신 이유가 있으신가요??

2019-07-04 12:02 UTC, machine-human commented on sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/ui/main/MainViewModel.kt
> +
private var tickerObservable = ObservableField<List<TickerResponse>>()
private var isDataLoadingError = ObservableField<Boolean>()
로 선언해주시면 코드를 축약할 수 있습니다 :)

2019-07-04 12:11 UTC, machine-human commented
위 두 코멘트 확인 부탁드립니다. 고생하셨습니다!!

2019-07-05 05:25 UTC, sport0102 commented on sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/ui/main/MainViewModel.kt
> +
수정하였습니다!

2019-07-05 05:29 UTC, sport0102 commented on sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/data/source/UpbitRepository.kt
>  ) : UpbitDataSource {
그냥 제가 까먹은 것 같아요 ㅎㅎ 확인해주셔서 감사합니다! 수정했어요~

2019-07-05 11:54 UTC, brooks-o submitted a review, later dismissed
확인 했습니다.
고생하셨습니다 :)

2019-07-06 03:34 UTC, sjjeong requested changes

2019-07-06 03:34 UTC, sjjeong commented on sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/ui/main/MainFragment.kt
> +        binding.fragmentTickerListRv.adapter = TickerListAdapter()
Adapter도 onActivityCreated에서 해주세요

2019-07-06 03:34 UTC, sjjeong commented on sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/ui/main/MainFragment.kt
> +        binding = DataBindingUtil.inflate(inflater, R.layout.fragment_main, container, false)
DataBinding을 초기화 해주는 작업은 매우 반복적이어서 BaseFragment에서 처리하도록 해주세요.
BaseActivity도 만들어서 현재 MainActivity에서 android-kotlin-extension 사용하는 부분 제거해주세요

2019-07-06 03:34 UTC, sjjeong commented on sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/ui/main/MainViewModel.kt
> +    var tickerObservable = ObservableField<List<TickerResponse>>()
ObservableField는 한번 선언되고 바뀔일이 없기때문에 val로 선언해주세요

2019-07-06 03:34 UTC, sjjeong commented on sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/ui/main/MainViewModel.kt
> +    var isDataLoadingError = ObservableField<Boolean>()
이 변수는 사용되고있지 않는데 어떤목적으로 만드셨나요?

2019-07-09 04:05 UTC, sport0102 commented on sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/ui/main/MainFragment.kt
> +        binding = DataBindingUtil.inflate(inflater, R.layout.fragment_main, container, false)
BaseFragment에 DataBinding 추가 했습니다
55a5d04
BaseActivity 생성 및 적용하였습니다
0d73faa

2019-07-09 04:05 UTC, sport0102 commented on sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/ui/main/MainViewModel.kt
> +    var tickerObservable = ObservableField<List<TickerResponse>>()
val로 선언하였습니다
32bc0b2

2019-07-09 04:06 UTC, sport0102 commented on sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/ui/main/MainViewModel.kt
> +    var isDataLoadingError = ObservableField<Boolean>()
사용하게 변경하였습니다
f1ca3e4

2019-07-09 04:06 UTC, sport0102 commented on sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/ui/main/MainFragment.kt
> +        binding.fragmentTickerListRv.adapter = TickerListAdapter()
onActivityCreated에서 하도록 변경하였습니다
889881a

2019-07-10 10:01 UTC, sport0102 commented on sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/ui/main/MainFragment.kt
> +        binding = DataBindingUtil.inflate(inflater, R.layout.fragment_main, container, false)
android-kotlin-extension 제거 하였습니다
8bc8355

2019-07-10 15:20 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2019-07-11 05:39 UTC, merged