HW-6 AAC ViewModel, LiveData
sjjeong/GoogryAndroidArchitecutreStudy pull request #940
Opened 2020-12-10 17:03 UTC by hunihun

개인사정으로 너무 늦어진점 죄송합니다 ㅠㅠ 저번주꺼는 하지도 못했네용...

2020-12-11 02:15 UTC, juan-rybczinski commented on class14/hunihun/app/src/main/java/com/wybh/androidarchitecturestudy/history/RecentSearchWordViewModel.kt
> +        _wordList.value = repository.getSearchWord()!!.split(",")
최초 실행해서 검색 기록이 없는 상태로 RecentSearchWord 뷰가 호출되면 에러가 나지 않을까요? Null 체크를 하는게 좋을 것 같네요!

2020-12-11 02:15 UTC, juan-rybczinski commented on class14/hunihun/app/src/main/java/com/wybh/androidarchitecturestudy/history/RecentSearchWordActivity.kt
> +        vm.getSearchWord()
(멘토님께 받은 리뷰) 이 부분은 ViewModel의 init 블록에서 수행하셔도 좋을 것 같네요

2020-12-11 02:15 UTC, juan-rybczinski commented on class14/hunihun/app/src/main/java/com/wybh/androidarchitecturestudy/main/MainViewModel.kt
> +    private val tempList = ArrayList<CinemaItem>()
tempList를 써야 한다면 Kotlin이니까 MutableList를 고려해보셔도 좋을 것 같네요!
https://stackoverflow.com/a/43116238/8629522

2020-12-11 02:15 UTC, juan-rybczinski commented on class14/hunihun/app/src/main/java/com/wybh/androidarchitecturestudy/main/MainViewModel.kt
> +    val cinemaItemList: LiveData<ArrayList<CinemaItem>> = _cinemaItemList
여기는 List를 쓰시는 게 어떨까요?

2020-12-11 08:56 UTC, hunihun commented on class14/hunihun/app/src/main/java/com/wybh/androidarchitecturestudy/history/RecentSearchWordActivity.kt
> +        vm.getSearchWord()
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/940/commits/87c32b5885d0f14df473be032a44c3d2efe7619f

적용했습니다!

2020-12-11 08:57 UTC, hunihun commented on class14/hunihun/app/src/main/java/com/wybh/androidarchitecturestudy/main/MainViewModel.kt
> +    val cinemaItemList: LiveData<ArrayList<CinemaItem>> = _cinemaItemList
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/940/commits/d442c81165313f34dbc2506efca604775bf3d0dc

적용했습니다!

2020-12-11 08:57 UTC, hunihun commented on class14/hunihun/app/src/main/java/com/wybh/androidarchitecturestudy/main/MainViewModel.kt
> +    private val tempList = ArrayList<CinemaItem>()
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/940/commits/d4cc2cb8fa0af017620de18fc09621af9721b739

동작은 동일한데 의미전달용으로 사용되는군요.... 좋은 정보 감사합니다:)!

2020-12-11 08:58 UTC, hunihun commented on class14/hunihun/app/src/main/java/com/wybh/androidarchitecturestudy/history/RecentSearchWordViewModel.kt
> +        _wordList.value = repository.getSearchWord()!!.split(",")
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/940/commits/5a1261d3cd4881621e6d477368e985c77ee3cf95

empty view를 넣어봐야겠네요 ㅋㅋㅋ

2020-12-11 11:27 UTC, juan-rybczinski approved these changes
바쁘신데도 고생 많으셨습니다!

2020-12-12 03:35 UTC, sjjeong requested changes

2020-12-12 03:35 UTC, sjjeong commented on class14/hunihun/app/src/main/java/com/wybh/androidarchitecturestudy/main/MainActivity.kt
> +        vm.removeCompositeDisposable()
ViewModel에 onCleared를 override하면 됩니다

2020-12-12 04:16 UTC, hunihun commented on class14/hunihun/app/src/main/java/com/wybh/androidarchitecturestudy/main/MainActivity.kt
> +        vm.removeCompositeDisposable()
https://github.com/StudyFork/GoogryAndroidArchitectureStudy/pull/940/commits/0d2c2e48ffabe4e46e8e859572d138085a3a25e2

적용했습니다!

2020-12-12 04:52 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-12-12 04:55 UTC, merged