HW-7 Apply DI
sjjeong/GoogryAndroidArchitecutreStudy pull request #942
Opened 2020-12-13 04:24 UTC by jihoi-kang

2020-12-16 05:46 UTC, PeonyF approved these changes
별다른 이견없어 Approve 처리합니다. 수고하셨습니다!
(Room을 저렇게 처리할 수 있구나 하고 배울 수 있어서 좋았습니다. (6c03910))

2020-12-16 13:24 UTC, sjjeong requested changes

2020-12-16 13:24 UTC, sjjeong commented on class15/jihoi-kang/aas/app/src/main/java/com/jay/aas/data/MovieRemoteDataSourceImpl.kt
> +    private val retrofitHelper: RetrofitHelper,
RetrofitHelper 대신에 MovieService를 전달하도록 해보세요

2020-12-16 13:24 UTC, sjjeong commented on class15/jihoi-kang/aas/app/src/main/java/com/jay/aas/data/MovieLocalDataSourceImpl.kt
> +    private val roomHelper: RoomHelper,
MovieDao를 전달하도록 해보세요

2020-12-17 10:13 UTC, jihoi-kang commented on class15/jihoi-kang/aas/app/src/main/java/com/jay/aas/data/MovieRemoteDataSourceImpl.kt
> +    private val retrofitHelper: RetrofitHelper,
NetworkModule 추가하였습니다.
7ad45c0

2020-12-17 10:14 UTC, jihoi-kang commented on class15/jihoi-kang/aas/app/src/main/java/com/jay/aas/data/MovieLocalDataSourceImpl.kt
> +    private val roomHelper: RoomHelper,
RoomModule 추가하였습니다.
6591051

2020-12-17 12:10 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-12-17 16:25 UTC, merged