HW-7 Hilt 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #943
Opened 2020-12-13 09:20 UTC by Myung777

Hlit를 이용해 DI 를 적용해 보았습니다.

2020-12-17 11:35 UTC, simuelunbo approved these changes
고생 하셨습니다 👍🏻

2020-12-17 12:17 UTC, sjjeong requested changes

2020-12-17 12:17 UTC, sjjeong commented on class14/myung777/StudyFork/app/src/main/java/com/deepco/studyfork/data/local/LocalMovieDataImpl.kt
> +class LocalMovieDataImpl @Inject constructor() : LocalMovieData {
SharedPreference를 주입받도록 해주세요

2020-12-17 12:17 UTC, sjjeong commented on class14/myung777/StudyFork/app/src/main/java/com/deepco/studyfork/data/remote/RemoteMovieDataImpl.kt
> +    private var retrofitHelper: RetrofitHelper
RetrofitService를 주입받도록 해주세요

2020-12-17 14:46 UTC, Myung777 commented on class14/myung777/StudyFork/app/src/main/java/com/deepco/studyfork/data/local/LocalMovieDataImpl.kt
> +class LocalMovieDataImpl @Inject constructor() : LocalMovieData {
45943a3
수정하였습니다.

2020-12-17 14:46 UTC, Myung777 commented on class14/myung777/StudyFork/app/src/main/java/com/deepco/studyfork/data/remote/RemoteMovieDataImpl.kt
> +    private var retrofitHelper: RetrofitHelper
7862945
수정하였습니다.

2020-12-18 13:11 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-12-18 17:00 UTC, merged