HW-7 Hilt 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #945
Opened 2020-12-15 15:18 UTC by PeonyF

기존 프로젝트에서 Hilt를 적용하였습니다. 
이에 따라 각 object들의 lifecycle에 따라 사용하고  dependencies를 적용할 수 있도록 변경하였습니다.

data package :  -DataSourceImpl 클래스들에 Hilt 관련 annotation을 추가하였습니다. 
util package : App 클래스에 @HiltAndroidApp annotation를 추가하였습니다.
ui package : 각 -ViewModel 클래스들에  @ViewModelInject annotation를 추가하여 
-Activity 클래스들에 mainViewModel변수를 viewModels를 통해 사용하도록 변경하였습니다.

2020-12-16 08:52 UTC, jihoi-kang approved these changes
고생하셨습니다.
LGTM👍

2020-12-16 13:28 UTC, sjjeong requested changes

2020-12-16 13:28 UTC, sjjeong commented on class15/PeonyF/AndroidArchitectureStudy/app/src/main/java/com/architecture/androidarchitecturestudy/data/local/MovieLocalDataSourceImpl.kt
> +class MovieLocalDataSourceImpl @Inject constructor() : MovieLocalDataSource {
SharedPreference를 주입해서 사용하도록 해보세요

2020-12-16 13:28 UTC, sjjeong commented on class15/PeonyF/AndroidArchitectureStudy/app/src/main/java/com/architecture/androidarchitecturestudy/data/remote/MovieRemoteDataSourceImpl.kt
> +    private val apiClient: ApiClient
ApiClient 안에 있는 NetworkService 를 주입받도록 해주세요

2020-12-18 17:51 UTC, PeonyF commented on class15/PeonyF/AndroidArchitectureStudy/app/src/main/java/com/architecture/androidarchitecturestudy/data/remote/MovieRemoteDataSourceImpl.kt
> +    private val apiClient: ApiClient
NetworkModule 클래스를 새로 생성하고(bf815a6) RemoteDataSourceImpl 클래스에서 NetworkService를 주입받도록 변경하였습니다. (2b36f85)

2020-12-18 17:53 UTC, PeonyF commented on class15/PeonyF/AndroidArchitectureStudy/app/src/main/java/com/architecture/androidarchitecturestudy/data/local/MovieLocalDataSourceImpl.kt
> +class MovieLocalDataSourceImpl @Inject constructor() : MovieLocalDataSource {
SharedPreferenceUtil 클래스를 singleton과 inject를 추가한 뒤 (f3f627e)  LocalDataSourceImpl 클래스에서 sharedPreferenceUtil변수를 주입받도록 변경하였습니다. (72c1607)

2020-12-19 09:14 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-12-19 21:31 UTC, merged