HW-7. DI 적용(Hilt)
sjjeong/GoogryAndroidArchitecutreStudy pull request #946
Opened 2020-12-16 12:32 UTC by onxmoreplz

영화 Api 클래스에서 OkHttp, Retrofit 객체 생성 시, DI를 추가적으로 사용하려고 했는데 결국엔 못 했습니다.
조금 더 이해가 필요할 것 같네요...
보시고 수정 필요한 부분 커멘트 부탁드려요!

2020-12-17 12:20 UTC, dev-donghwan approved these changes
저도 막히는 부분이 있어서ㅠㅠ 고생하셨습니다

2020-12-17 12:29 UTC, sjjeong requested changes

2020-12-17 12:29 UTC, sjjeong commented on class14/onxmoreplz/HW2_Project/app/src/main/java/com/example/hw2_project/data/local/MovieLocalDataSourceImpl.kt
> +class MovieLocalDataSourceImpl @Inject constructor() : MovieLocalDataSource {
SharedPreference를 주입받도록 해주세요

2020-12-17 12:29 UTC, sjjeong commented on class14/onxmoreplz/HW2_Project/app/src/main/java/com/example/hw2_project/data/repository/MovieRepositoryImpl.kt
> +    private val localMovieLocalDataSourceImpl: MovieLocalDataSourceImpl
interface형태를 받도록 해주세요

2020-12-17 12:29 UTC, sjjeong commented on class14/onxmoreplz/HW2_Project/app/src/main/java/com/example/hw2_project/data/remote/MovieRemoteDataSourceImpl.kt
> +    private val naverMovieApiModule: NaverMovieApiModule
NaverMovieApi 를 받도록 해주세요

2020-12-17 12:29 UTC, sjjeong commented on class14/onxmoreplz/HW2_Project/app/src/main/java/com/example/hw2_project/di/NaverMovieApiModule.kt
> +       fun provideNaverApi(retrofit: Retrofit) = retrofit.create(NaverMovieApi::class.java)*/
주석 제거해주세요

2020-12-18 13:32 UTC, onxmoreplz commented on class14/onxmoreplz/HW2_Project/app/src/main/java/com/example/hw2_project/data/local/MovieLocalDataSourceImpl.kt
> +class MovieLocalDataSourceImpl @Inject constructor() : MovieLocalDataSource {
추가했습니다!

ae92f6f

2020-12-18 13:32 UTC, onxmoreplz commented on class14/onxmoreplz/HW2_Project/app/src/main/java/com/example/hw2_project/data/repository/MovieRepositoryImpl.kt
> +    private val localMovieLocalDataSourceImpl: MovieLocalDataSourceImpl
27e58e2

2020-12-18 13:33 UTC, onxmoreplz commented on class14/onxmoreplz/HW2_Project/app/src/main/java/com/example/hw2_project/data/remote/MovieRemoteDataSourceImpl.kt
> +    private val naverMovieApiModule: NaverMovieApiModule
수정했습니다!

6e2236a

2020-12-18 13:35 UTC, onxmoreplz commented on class14/onxmoreplz/HW2_Project/app/src/main/java/com/example/hw2_project/di/NaverMovieApiModule.kt
> +       fun provideNaverApi(retrofit: Retrofit) = retrofit.create(NaverMovieApi::class.java)*/
위에 커멘트 해주신 NaverMovieApi 변경하면서 주석 내용 다시 살렸습니다.

6e2236a

2020-12-19 09:15 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-12-20 03:35 UTC, merged