HW-7: hilt 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #947
Opened 2020-12-17 11:40 UTC by simuelunbo

의존성 주입 개념이 아직 까진 익숙 하지 않아 잘 적용했는지 모르겠네요 
이상한 부분은 피드백 부탁 드립니다

2020-12-17 13:21 UTC, Myung777 approved these changes
고생하셨습니다~

2020-12-17 15:43 UTC, sjjeong requested changes

2020-12-17 15:43 UTC, sjjeong commented on class14/simuelunbo/AndroidArchitectureStudy/app/src/main/java/com/example/androidarchitecturestudy/Preferences.kt
> +    private val preferences: SharedPreferences = MyApplication.context.getSharedPreferences(
constructor로 context를 주입받아서 만들어주세요

2020-12-17 15:43 UTC, sjjeong commented on class14/simuelunbo/AndroidArchitectureStudy/app/src/main/java/com/example/androidarchitecturestudy/data/remote/NaverRemoteDataSourceImpl.kt
> +    private val retrofitClient: RetrofitClient
RetrofitClient 대신 NaverMovieInterface 를 주입 받아보세요

2020-12-20 05:53 UTC, simuelunbo commented on class14/simuelunbo/AndroidArchitectureStudy/app/src/main/java/com/example/androidarchitecturestudy/data/remote/NaverRemoteDataSourceImpl.kt
> +    private val retrofitClient: RetrofitClient
bd8a66c1a3aa7cdf87cde5a5d9bf7be89f87181b

2020-12-20 05:55 UTC, simuelunbo commented on class14/simuelunbo/AndroidArchitectureStudy/app/src/main/java/com/example/androidarchitecturestudy/Preferences.kt
> +    private val preferences: SharedPreferences = MyApplication.context.getSharedPreferences(
bd8a66c

2020-12-20 05:55 UTC, simuelunbo commented on class14/simuelunbo/AndroidArchitectureStudy/app/src/main/java/com/example/androidarchitecturestudy/data/remote/NaverRemoteDataSourceImpl.kt
> +    private val retrofitClient: RetrofitClient
dba69f3 변경했습니다

2020-12-20 09:02 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-12-20 09:03 UTC, merged