HW7 : Hilt
sjjeong/GoogryAndroidArchitecutreStudy pull request #948
Opened 2020-12-17 12:22 UTC by dev-donghwan

2020-12-17 12:40 UTC, onxmoreplz commented
고생하셨습니다!😄

2020-12-17 12:40 UTC, onxmoreplz approved these changes

2020-12-17 13:13 UTC, sjjeong requested changes

2020-12-17 13:13 UTC, sjjeong commented on class14/dev-donghwan/studyfork/app/src/main/java/com/example/studyfork/data/local/LocalDataSourceImpl.kt
> +    @ApplicationContext context: Context
context대신 SharedPreference를 전달해주세요

2020-12-17 13:13 UTC, sjjeong commented on class14/dev-donghwan/studyfork/app/src/main/java/com/example/studyfork/data/remote/RemoteDataSourceImpl.kt
> +class RemoteDataSourceImpl @Inject constructor() : RemoteDataSource {
NaverApi를 전달 해주세요

2020-12-18 12:17 UTC, dev-donghwan commented on class14/dev-donghwan/studyfork/app/src/main/java/com/example/studyfork/data/local/LocalDataSourceImpl.kt
> +    @ApplicationContext context: Context
> context대신 SharedPreference를 전달해주세요

SharedPreference도 Inject처럼 해서 넘겨줘야 하는건가요?

어떻게 넘겨줘야 할지 잘 모르겠습니다ㅠ

2020-12-18 13:07 UTC, dev-donghwan commented on class14/dev-donghwan/studyfork/app/src/main/java/com/example/studyfork/data/remote/RemoteDataSourceImpl.kt
> +class RemoteDataSourceImpl @Inject constructor() : RemoteDataSource {
388f3a5

2020-12-18 13:18 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-12-21 01:27 UTC, merged