HW-7 : Hilt 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #949
Opened 2020-12-18 09:14 UTC by hhi-5258

2020-12-18 11:15 UTC, dktsudgg requested changes

2020-12-18 11:15 UTC, dktsudgg commented on class15/hhi-5258/HHiApplication/app/src/main/java/com/hhi/myapplication/data/repository/NaverRepositoryDataSourceImpl.kt
>      private val naverLocalDataSource = NaverLocalDataSourceImpl()
naverRemoteDataSource와 naverLocalDataSource를 생성자에서 주입받아 사용해도 될 것 같아요!

2020-12-18 11:15 UTC, dktsudgg commented on class15/hhi-5258/HHiApplication/app/src/main/java/com/hhi/myapplication/viewmodel/MainViewModel.kt
>      private val repositoryDataSourceImpl = NaverRepositoryDataSourceImpl()
repositoryDataSourceImpl를 생성자에서 주입받아도 될 것 같아요!

2020-12-18 11:15 UTC, dktsudgg commented on class15/hhi-5258/HHiApplication/app/src/main/java/com/hhi/myapplication/viewmodel/RecentSearchViewModel.kt
>      private val naverRepositoryDataSource = NaverRepositoryDataSourceImpl()
naverRepositoryDataSource를 생성자에서 주입받아도 될 것 같아요!

2020-12-18 12:51 UTC, hhi-5258 commented
수정하였습니다!
d70230a

2020-12-18 12:59 UTC, dktsudgg approved these changes
수고하셨습니다!

2020-12-19 09:23 UTC, sjjeong requested changes

2020-12-19 09:23 UTC, sjjeong commented on class15/hhi-5258/HHiApplication/app/src/main/java/com/hhi/myapplication/data/local/NaverLocalDataSourceImpl.kt
> +class NaverLocalDataSourceImpl @Inject constructor() : NaverLocalDataSource {
SharedPreference를 주입받도록해주세요

2020-12-19 09:23 UTC, sjjeong commented on class15/hhi-5258/HHiApplication/app/src/main/java/com/hhi/myapplication/data/remote/NaverRemoteDataSourceImpl.kt
> +class NaverRemoteDataSourceImpl @Inject constructor() : NaverRemoteDataSource {
NaverApi를 주입받도록 해주세요

2020-12-19 09:23 UTC, sjjeong commented on class15/hhi-5258/HHiApplication/app/src/main/java/com/hhi/myapplication/data/repository/NaverRepositoryDataSourceImpl.kt
> +    private val naverLocalDataSource: NaverLocalDataSourceImpl
interface type으로 변경해주세요

2020-12-24 03:44 UTC, hhi-5258 commented on class15/hhi-5258/HHiApplication/app/src/main/java/com/hhi/myapplication/data/repository/NaverRepositoryDataSourceImpl.kt
> +    private val naverLocalDataSource: NaverLocalDataSourceImpl
수정하였습니다
99ccc14

2020-12-24 03:44 UTC, hhi-5258 commented on class15/hhi-5258/HHiApplication/app/src/main/java/com/hhi/myapplication/data/local/NaverLocalDataSourceImpl.kt
> +class NaverLocalDataSourceImpl @Inject constructor() : NaverLocalDataSource {
수정하였습니다
a93012b

2020-12-24 03:44 UTC, hhi-5258 commented on class15/hhi-5258/HHiApplication/app/src/main/java/com/hhi/myapplication/data/remote/NaverRemoteDataSourceImpl.kt
> +class NaverRemoteDataSourceImpl @Inject constructor() : NaverRemoteDataSource {
수정하였습니다
b3ad020

2020-12-25 04:59 UTC, sjjeong approved these changes
LGTM ✊ ✌️ 👋

2020-12-25 04:59 UTC, sjjeong commented on class15/hhi-5258/HHiApplication/app/src/main/java/com/hhi/myapplication/App.kt
> +        lateinit var context: Application
Application을 주입 받는 방법이 있는데 이거는 8주차 과제 하시면서 해결해주세요

2020-12-28 07:18 UTC, merged