HW-4 MVVM + DataBinding 적용
sjjeong/GoogryAndroidArchitecutreStudy pull request #96
Opened 2019-07-04 10:22 UTC by machine-human

2019-07-05 05:05 UTC, sport0102 requested changes
수정사항 반영 부탁드리겠습니다!

2019-07-05 05:05 UTC, sport0102 commented on machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/view/activity/main/MainViewModel.kt
> +    getMessage: String
getMessage 같은 동사형 변수명을 좋지 않습니다. message와 같은 명사형으로 바꿔주세요

2019-07-05 05:05 UTC, sport0102 commented on machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/view/activity/main/MainViewModel.kt
> +        dataSource = remoteDataSOurce
dataSource와 getMessage를 지금은 java에서 사용하시는 형태로 하고 계신데, 이렇게 안하시고 클래스 생성자로 바로 표현하실 수 있습니다
class MainViewModel(
	    val remoteDataSOurce: BaseDataSource,
	    val getMessage: String
이런식으로 선언하시면 바로 저 변수에 접근하셔서 사용하실 수 있습니다

2019-07-05 05:05 UTC, sport0102 commented on machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/view/activity/main/MainViewModel.kt
> +        dataSource = remoteDataSOurce
아 추가적으로 remoteDataSOurce source부분 오타 수정 부탁드릴게요!

2019-07-05 05:05 UTC, sport0102 commented on machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/view/bindingadapter/bindTickerData.kt
> +    (view.adapter as? MainListAdapter)?.run {
as 옆의 nullable 표시랑 MainListAdapter 옆에 nullable표시 없어도 되지않나요?

2019-07-05 05:05 UTC, sport0102 commented on machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/view/bindingadapter/bindTickerData.kt
> +        notifyDataSetChanged()
데이터를 set한 뒤에 notify를 해야하지않을까요?

2019-07-05 11:55 UTC, machine-human commented on machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/view/bindingadapter/bindTickerData.kt
> +        notifyDataSetChanged()
저번에 오류가 나서 앞으로 뺀건데, 피드백 후 다시 진행하니 됩니다.
감사합니다 ^_^

d996e4e

2019-07-05 11:55 UTC, machine-human commented on machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/view/bindingadapter/bindTickerData.kt
> +    (view.adapter as? MainListAdapter)?.run {
오류가 나서 붙힌건데, 이번 부분이 체크가 어렵네요....
리뷰 감사합니다.

d996e4e

2019-07-05 11:56 UTC, machine-human commented on machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/view/activity/main/MainViewModel.kt
> +        dataSource = remoteDataSOurce
객체를 초기화 하는 표현이 아직 익숙치가 않네요..ㅠ.ㅠ
리뷰 감사합니다.

ee7ae91

2019-07-05 11:57 UTC, machine-human commented on machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/view/activity/main/MainViewModel.kt
> +    getMessage: String
그렇군요..!!
수정 했습니다. 감사합니다.

ee7ae91

2019-07-05 15:03 UTC, sport0102 commented on machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/view/bindingadapter/bindTickerData.kt
> +        notifyDataSetChanged()
ㅠㅠㅠ reformat좀 해주세요 ㅠㅠ 보기 불편합니당

2019-07-05 15:04 UTC, sport0102 approved these changes
LGMT!

2019-07-06 00:33 UTC, merged

2019-07-06 02:09 UTC, sjjeong commented on machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/base/BaseFragment.kt
> +        binding.lifecycleOwner = this
binding.lifecyclerOwner가 어떤의미로 쓰이는지 알고 추가하신건가요?

2019-07-06 02:09 UTC, sjjeong commented on machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/view/activity/main/MainViewModel.kt
> +    var observableErrorMessage = MutableLiveData<Throwable>()
MutableLiveData는 아직 사용하지 말아주세요. ObservableField를 사용해주세요

2019-07-06 02:09 UTC, sjjeong commented on machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/view/activity/main/MainViewModel.kt
> +    message: String
message보다 이게 어떤 용도로 쓰이는 변수인지 알 수 있게 수정해주세요

2019-07-11 17:22 UTC, machine-human commented on machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/view/activity/main/MainViewModel.kt
> +    message: String
수정 했습니다. 감사합니다. 
e17ba77

2019-07-11 17:22 UTC, machine-human commented on machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/view/activity/main/MainViewModel.kt
> +    var observableErrorMessage = MutableLiveData<Throwable>()
수정 했습니다. 감사합니다.

e17ba77

2019-07-11 17:25 UTC, brooks-o commented on machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/base/BaseFragment.kt
> +        binding.lifecycleOwner = this
Android X로 마이그레이션 시 제거 했습니다.